### ISSUE TITLE
ffmpeg Not played in loop

### ISSUE THREAD

**Issue by Berttholio** [Rapptz/discord.py#100]
Creating a function for client to disconnect after file is done playing. The client stays connected for the length of time to play file, but no audio is transited. If loop is removed stream plays fine

`voice = yield from client.join_voice_channel(hard_coded_channel)
player = voice.create_ffmpeg_player('music.mp3')
player.start()
while player.is_done() is False:	
	if player.is_done() is True:
		exit= yield from disconnect(voice)`

**Comment by cookkkie** [comment]
Try this:
```python
voice = yield from client.join_voice_channel(hard_coded_channel)
player = voice.create_ffmpeg_player('music.mp3')
player.start()
while not player.is_done():
    pass
yield from client.voice.disconnect()    
```

**Comment by Berttholio** [comment]
Works now, Thanks!
