### ISSUE TITLE
`invoke_without_group` kwarg for HybridCommand

### ISSUE THREAD

**Issue by PPearoo** [Rapptz/discord.py#10006]
### Summary

Discord's limitation of 100 commands per bot is not enough for multi-purpose bots that want to allow slash commands and text commands to be used supported. A workaround is adding some commands as subcommands for slash command groups, but then it's inconvenient for the users. This kwarg would automate adding a slash command to a slash group, and a standalone text command.

### What is the feature request for?

discord.ext.commands

### The Problem

Let's say I have an economy system. I want to make it so users can invoke `/economy work` (slash command) or `!work` (text command) and have the same results. Currently, you can solve this issue by making a separate `commands.Command` that invokes the `HybridCommand`:
```py
@commands.hybrid_group(name="economy", description="A leaderboard of the richest users")
async def economy(self, ctx: commands.Context):
    if not ctx.interaction:
        await ctx.send_help("economy")

@economy.command(name="work", description="Earn money by working ($300-$1500)")
async def work(self, ctx: commands.Context):
    amount: int = random.randint(300, 1500)
    await self.helper.add_money(ctx.author.id, ctx.guild.id, amount)

    message: dict = await self.custom_message("work", ctx, amount=amount)

    await ctx.reply(**message)

@commands.command(name="work", hidden=True, callback=work)
async def work_callback(self, ctx: commands.Context):
    await ctx.invoke(self.work)
```
But this can be tedious because you have to copy-paste this under every command you might want to add in the future.

### The Ideal Solution

```py
@commands.hybrid_group(
    name="economy",
    description="A leaderboard of the richest users"
)
async def economy(self, ctx: commands.Context):
    if not ctx.interaction:
        await ctx.send_help("economy")

@economy.command(name="work", description="Earn money by working ($300-$1500)", invoke_without_group=True)
# invoke_without_group would add the command to Bot.commands as both a subcommand of "economy" and as a standalone command "work"
# it should be a Union[str, bool]. if True, the command will be added to the library as "/group command" and "!command", where command is the name of the command
# if it's a string, it should be added as "/group command" and "!custom_name" where custom_name is the value of this argument
async def work(self, ctx: commands.Context):
    amount: int = random.randint(300, 1500)
    await self.helper.add_money(ctx.author.id, ctx.guild.id, amount)
    
    message: dict = await self.custom_message("work", ctx, amount=amount)
    
    await ctx.reply(**message)
```

### The Current Solution

As shown above, you can add it manually to the text commands, but it's tedious.

**Comment by LeoCx1000** [comment]
[commands.GroupCog](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.GroupCog) does this.

**Comment by PPearoo** [comment]
Damn, it really does. I didn't think of that.
