### ISSUE TITLE
Pip error

### ISSUE THREAD

**Issue by SirPigari** [Rapptz/discord.py#10009]
### Summary

version 2.7.0 does not exist

### Reproduction Steps

pip install discord.py==2.7.0

### Minimal Reproducible Code

```python
PS E:\skittle-chan> pip install discord.py==2.7.0
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement discord.py==2.7.0 (from versions: 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.7.0, 0.8.0, 0.9.0, 0.9.1, 0.9.2, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.16.4, 0.16.5, 0.16.6, 0.16.7, 0.16.8, 0.16.9, 0.16.10, 0.16.11, 0.16.12, 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.4.0, 1.4.1, 1.4.2, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.2.0, 2.2.2, 2.2.3, 2.3.0, 2.3.1, 2.3.2, 2.4.0)
ERROR: No matching distribution found for discord.py==2.7.0
PS E:\skittle-chan>
```

### Expected Results

install it

### Actual Results

PS E:\skittle-chan> python.exe -m pip install --upgrade pip
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in c:\users\admin\appdata\roaming\python\python312\site-packages (24.3.1)
PS E:\skittle-chan> pip install discord.py==2.7.0
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement discord.py==2.7.0 (from versions: 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.7.0, 0.8.0, 0.9.0, 0.9.1, 0.9.2, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.16.4, 0.16.5, 0.16.6, 0.16.7, 0.16.8, 0.16.9, 0.16.10, 0.16.11, 0.16.12, 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.4.0, 1.4.1, 1.4.2, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.2.0, 2.2.2, 2.2.3, 2.3.0, 2.3.1, 2.3.2, 2.4.0)
ERROR: No matching distribution found for discord.py==2.7.0
PS E:\skittle-chan>

### Intents

intents = discord.Intents.default() intents.messages = True intents.guilds = True intents.members = True intents.message_content = True bot = commands.Bot(command_prefix="!", intents=intents) tree = bot.tree

### System Information

PS E:\skittle-chan> python -m discord -v
- Python v3.12.6-final
- discord.py v2.4.0-final
- aiohttp v3.10.5
- system info: Windows 11 10.0.22621
PS E:\skittle-chan>

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by LostLuma** [comment]
Version 2.7.0 does not exist, as pip is telling you. The last [tagged release](https://github.com/Rapptz/discord.py/tags) is 2.4.0 at this time, which you have already installed.
