### ISSUE TITLE
discord.Message.system_content of type chat_input_command always fails

### ISSUE THREAD

**Issue by ItsPadar** [Rapptz/discord.py#10015]
### Summary

The system_content attribute of a chat_input_command discord.Message will always return an empty string

### Reproduction Steps

In my case I was making a Quote this Message context menu command and found that attempting to use it on a message responding to someone's command use would always respond with an empty string

### Minimal Reproducible Code

```python
import discord

intents = discord.Intents.default()
intents.message_content = True
client = discord.Client(intents = intents)

@client.event
async def on_message(message: discord.Message):
    if message.type.name == "chat_input_command":
        content = message.system_content
        if content == "":
            print(f"Empty message of chat_input_command from {message.author.name}")
        else:
            print(f"Content of chat_input_command type found: {content}")

client.run(TOKEN)
```

### Expected Results

.system_content responding with the content of the response message, like .content does. Perhaps if the message hasn't been responded to yet, it would be empty but in the case I encountered this (using a context menu on a message) I would have expected the actual content of the message.

### Actual Results

system_content responded with an empty string

### Intents

discord.Intents.default() with message_content enabled

### System Information

discord.py v2.5.0-alpha
discord.py metadata: v2.5.0a0

I believe the exact commit is [this](https://github.com/Rapptz/discord.py/commit/e94fb455274d78969922082bb9822f88345984d5)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by ItsPadar** [comment]
This also seems to apply to context_menu_command

**Comment by Rapptz** [comment]
Those aren't really "system content" in the sense that the library is using the term. System content is content that the Discord client itself injects and shows to users. You're just looking for regular content. You can do `message.system_content or message.content` if you want a fallback.
