### ISSUE TITLE
Adding role error 

### ISSUE THREAD

**Issue by SoMuchSpoon** [Rapptz/discord.py#1001]
Hello, 
i am currently using a self bot and i am making a command that when you run it it should add a role to a user but its not adding the role.
my code:

#command 7
role = "399581540717428736"
@client.command(pass_context = True)
async def Blacklist(ctx, *, member : discord.Member = None):
    if not ctx.message.author.server_permissions.administrator:
        return
 
    if not member:
        return await client.say(ctx.message.author.mention + "Specify a user to Blacklist!")
    try:
        await client.add_roles(user, role)
    except Exception as e:
        if 'Privilege is too low' in str(e):
            return await client.say(":x: Privilege too low!")
 
    embed = discord.Embed(description = "**%s** has been Blacklisted!"%member.name, color = 0xFF0000)
    return await client.say(embed = embed)

**Comment by kittenswolf** [comment]
Selfbots are banned: https://support.discordapp.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-
Also, try and fix up the formatting. It's kinda hard to read

**Comment by SoMuchSpoon** [comment]
Sorry new to this
