### ISSUE TITLE
What does this refer to?

### ISSUE THREAD

**Issue by JoshWidrick** [Rapptz/discord.py#1002]
everyone = discord.PermissionOverwrite(read_messages=False)
            mine = discord.PermissionOverwrite(read_messages=True)
            await bot.create_channel(server, 'secret', (default_role, everyone), (me, mine))

In this what does 'server' in '..bot.create_channel(server..' refer to?

**Comment by Rapptz** [comment]
An instance of `discord.Server` that denotes the server you are interested in creating a channel for.

**Comment by JoshWidrick** [comment]
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "file.py", line 2055, in on_message
    await client.create_channel(server, 'secret', (default_role, everyone), (me, mine))
  File "/usr/local/lib/python3.6/site-packages/discord/client.py", line 2151, in create_channel
    'id': target.id
AttributeError: 'CachedSlotProperty' object has no attribute 'id'

when I run 

server = discord.Server
default_role = server.default_role
me = server.me

everyone = discord.PermissionOverwrite(read_messages=False)
mine = discord.PermissionOverwrite(read_messages=True)
await client.create_channel(server, 'secret', (default_role, everyone), (me, mine))

Im trying to create a channel, Im just not sure what is wrong.

Also, thank you for your quick response before.

**Comment by datmellow** [comment]
Questions like these are best asked in the official server

https://discord.gg/r3sSKJJ

**Comment by JoshWidrick** [comment]
Ok, thank you.
