### ISSUE TITLE
Missing __init__.py

### ISSUE THREAD

**Issue by Hadesz1** [Rapptz/discord.py#1003]
On the "**rewrite branch**" is missing __init__.py file inside the folder discord.ext
It was giving me an import error when trying to import commnads:
from discord.ext import commands
Issue was fixed after i put __init__.py file from version 0.16.12 inside the ext directory.

**Comment by Rapptz** [comment]
By design because it's a namespace package.

Your issue sounds like something else.

**Comment by Hadesz1** [comment]
I was using eclipse as IDE, as soon as I created that init file, compilation went ok.

**Comment by Rapptz** [comment]
That code should work fine as-is (as evident by the probably thousands of people who do it without issue).
