### ISSUE TITLE
*Channel.purge() raises NotFound

### ISSUE THREAD

**Issue by rnxm** [Rapptz/discord.py#10045]
### Summary

TextChannel.purge() raises a NotFound exception, which isn't documented.

### What is the feature request for?

The core library

### The Problem

When using `TextChannel.purge()`, `StageChannel.purge()`, and `VoiceChannel.purge()`, if `bulk` is set to `True`, the library falls back to single deleting messages if they are older than two weeks. This is - obviously - expected and documented.

However, when this single deletion method is used, if a user deletes a message during the purge process that was supposed to be deleted by the bot, a `NotFound` error is raised, which isn't obvious just by looking at the documentation.

This wouldn't be a big issue by itself - however, this also just stops the entirety of the purge function altogether. Which means that the only way to handle it is to put it in a try-except block. But this workaround is only semi-functional, because this way, you can't store the deleted messages by storing the return value of `.purge()`. If you want to tell the users that some messages couldn't be deleted because they were already deleted by a user, you can't tell the user how many messages were actually deleted, because the return value can't be stored, and you can't access that value within the `except` block.

### The Ideal Solution

Add a new parameter that, when set to true, will ignore `NotFound` errors during single delete, resulting in exceptionless behaviour.

**Comment by AbstractUmbra** [comment]
This feature is explicitly within the library, see the comment as to why:-
https://github.com/Rapptz/discord.py/blob/9806aeb83179d0d1e90d903e30db7e69e0d492e5/discord/abc.py#L124-L133

**Comment by Rapptz** [comment]
10008 is already handled (this is unknown message), whereas the channel deletion case is handled differently. I think this patch isn't cut for release however so that's probably the discrepancy.

**Comment by rnxm** [comment]
Oh, that's weird. Sorry for being off-topic, but how does a purge raise a NotFound for me?

```py
await interaction.channel.purge(limit=amount)
```

If full code is needed, I'll post it on Discord, don't worry.
