### ISSUE TITLE
'Intents' object has no attribute 'message_content'

### ISSUE THREAD

**Issue by therealunderscoreethereal** [Rapptz/discord.py#10047]
### Summary

It's telling me that Intents has no attribute message_content, despite it existing.

### Reproduction Steps

I set message_content to True.

### Minimal Reproducible Code

```python
"""Code that raised error"""
import discord as dsc
from discord.ext import commands as cmd

intents = dsc.Intents.default()
intents.message_content = True
```

### Expected Results

I expected it to not raise any errors.

### Actual Results

It raised the warning:
'Intents' object has no attribute 'message_content'

And also:
'Intents' object attribute 'message_content' is read-only

### Intents

I am only using the message_content intent.

### System Information

- Python v3.9.0-final
- discord.py v2.4.0-final
- aiohttp v3.11.2
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

There was no traceback, this is a warning I got in my IDE, PyCharm.

**Comment by tailoric** [comment]
> There was no traceback, this is a warning I got in my IDE, PyCharm.
Just to make sure, this error only appears as a warning in PyCharm?
Does your code run successfully if you start the bot itself via the command line?

**Comment by therealunderscoreethereal** [comment]
It shows as a warning; the code works fine.

**Comment by mikeshardmind** [comment]
This isn't a problem with discord.py, This is a pycharm bug that they have been aware of [for years](https://youtrack.jetbrains.com/issue/PY-47698).

**Comment by therealunderscoreethereal** [comment]
Oh my bad, sorry about this.
