### ISSUE TITLE
Add a way to create an application owned emoji

### ISSUE THREAD

**Issue by GingerGigiCat** [Rapptz/discord.py#10059]
### Summary

It would be great if a way to create an application emoji was added to discord.py since it allows up to 2000 emojis to be added.

### What is the feature request for?

The core library

### The Problem

Custom emojis can be uploaded to guilds through discord.py, but not to the application/bot itself. This is a problem because a standard non-nitro guild can only have 50 emojis, so the bot would have to be in 40 different guilds in order to have access to 2000 custom emojis. This is where application emojis are so helpful, because a huge number of emojis can just be uploaded to the application and used by the bot in any server it is in.

### The Ideal Solution

Ideally, usage would be similar in concept to creating custom emojis in a guild, so `await bot.application.create_custom_emoji(name="emoji_name", image=image_data)` would create a new emoji, and `bot.application.emojis` would give a list of emojis in the application.

### Additional Context

Documentation for the API can be found at https://discord.com/developers/docs/resources/emoji#create-application-emoji

**Comment by tailoric** [comment]
This has been already implemented in the master branch:
See the docs here
https://discordpy.readthedocs.io/en/latest/ext/commands/api.html?highlight=emoji#discord.ext.commands.Bot.create_application_emoji

**Comment by GingerGigiCat** [comment]
Thanks, I couldn't find anything about it from searching
