### ISSUE TITLE
Send message with image URL without generating the preview

### ISSUE THREAD

**Issue by shrx** [Rapptz/discord.py#1006]
I want to send a message containing an URL with an image.
Putting the URL inside `<>` brackets is supposed to suppress the preview. However, the image preview is still displayed.
 ```python
reply = "image URL: <{}>".format(imgur_url)
yield from self.send_message(channel, reply)
```

**Comment by scragly** [comment]
Tested the code and can't replicate the issue. 

Used imgur gallery link, and direct image urls for the following file types:
- jpg
- png
- gif
- mp4

No previews were created, and removing the `<` and `>` from around `{}` resulted in previews, showing that it's specifically the `<>` preventing it.

**Comment by shrx** [comment]
OK I am closing the issue. The generated image URL had a newline character at the end, this broke the formatting.
