### ISSUE TITLE
Bot disconnects randomly 

### ISSUE THREAD

**Issue by Note2Self** [Rapptz/discord.py#1007]
Hey I've created a bot that streams radio 

I use 

`player = voice.create_ffmpeg_player('http://example.com/example') 
player.start()
`
however about 10 mins in to listening to the stream the bot automatically disconnects when not commanded to do so my internet connection is good so it's definitely not the issue.

`@stream.command(pass_context=True, no_pm=True)
    async def stop(self, ctx):
        """Stops Stream"""
        server = ctx.message.server
        author = ctx.message.author
        voice_client = self.voice_client(server)
        await asyncio.sleep(1)
        self.voice_client(server)
        await voice_client.disconnect()
        await self.bot.say(":stop_button: Stream Stopped.")
        
    def voice_client(self, server):
        return self.bot.voice_client_in(server)

    def voice_connected(self, server):
        if self.bot.is_voice_connected(server):
            return True`

I'm sure it could be the way I've either added this part disconnect the bot or I'm lacking a requirement 

`import discord
from discord import InvalidArgument
from discord.ext import commands
from cogs.utils import checks
from __main__ import send_cmd_help
import threading
import os
import asyncio
import inspect
import subprocess
import datetime
import time`

Should I any requirements that are missing to stream from a URL and any poss reason why the bot could be disconnecting as I don't get an error in the console?

discord.py[voice]
pytz
memory_profiler
pip
youtube-dl
imgurpython
aiohttp
asyncio
websockets==3.4
chardet
PyNaCl
cffi
pycparser
six
tabulate
mcstatus
feedparser 
js2py
beautifulsoup4
psutil
matplotlib

**Comment by Tsunamical** [comment]
What version of ffmpeg? Try updating to a nightly if you're on a stable build. Otherwise, try these args:
"-reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5"

Usage:
```
args = "-reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5"
self.player = await self.voice.create_ffmpeg_player(url, before_options=args)
```

**Comment by fixator10** [comment]
As i can see in imports (`from cogs.utils import checks`), you use Red-DiscordBot
Try `[p]audioset emptydisconnect`
