### ISSUE TITLE
change_presence update loop freeze

### ISSUE THREAD

**Issue by ScottKane** [Rapptz/discord.py#1008]
Hi,

I am having a problem with client.change_presence() where when I am sending updates for a timer through a loop the updates seem to crash and will stop on e.g "Playing 8". Is there some limitation on change_presence() that wont allow an update every second?

My code is:

```
import discord
import asyncio

client = discord.Client()

@asyncio.coroutine
def countdown(number):
    while number >= 0:
        yield from client.change_presence(game=discord.Game(name=number))
        yield from asyncio.sleep(1)
        number -= 1
    yield from client.change_presence(game=discord.Game(name="DONE"))

@client.event
async def on_ready():
    print('Connected!')
    print('Username: ' + client.user.name)
    print('ID: ' + client.user.id)

@client.event
async def on_message(message):
    if message.content.startswith("!count"):
        args = message.content.split(" ")
        number = args[1]
        if number.isdigit():
            number = int(number)
            await client.loop.create_task(countdown(number))
```

Thanks in advance

**Comment by Vexs** [comment]
Yes, there is a ratelimit on change_presence. 30s is a good time to wait before editing presence again.

For future reference, if you want to loop over something a number of times, use range() and a for loop.

**Comment by ScottKane** [comment]
Thanks, much appreciated. I will switch to a for loop with range if it's more efficient than a while loop.
