### ISSUE TITLE
Bot occasionally quits with "Task was destroyed but it is pending!"

### ISSUE THREAD

**Issue by shrx** [Rapptz/discord.py#101]
```
Task was destroyed but it is pending!
task: <Task pending coro=<my_background_task() running at /home/shrx/bin/discordBot.py:77> wait_for=<Future pending cb=[Task._wakeup()]>>
```
The only background task I have:

```
@asyncio.coroutine
def my_background_task():
    yield from asyncio.sleep(5)
    yield from client.wait_until_ready()
    counter = 0
    channel = discord.Object(id='default_channel_id')
    while not client.is_closed:
       yield from asyncio.sleep(3600*24) #  <-- this is line 77 where the code fails
       resetCounters()
       yield from client.send_message(channel, "@everyone counters reset")

def resetCounters():
    for m in onlineMembers.keys():
        for c in onlineMembers[m]["counters"].keys():
            onlineMembers[m]["counters"][c]["c"] = 0
```

**Comment by Rapptz** [comment]
This is not a discord.py issue. If you want to make it "not pending" then cancel it. `Task.cancel` is a member function to do so.

**Comment by shrx** [comment]
What do you mean "when I'm done with it"? I expect the loop to run indefinitely.

**Comment by shrx** [comment]
I think you misunderstood my problem. The bot quits (crashes) **because** the task is destroyed, which should never happen - it's supposed to execute a function every 24 hours.

**Comment by khazhyk** [comment]
What is your full error and traceback? Generally you see this error because something else caused the loop to exit, and result in your task getting destroyed.

**Comment by shrx** [comment]
No other errors or trackebaks are displayed. Just these two lines and the bot script quits.

**Comment by khazhyk** [comment]
This warning only shows up if the bot exits for some other reason. This is just a warning saying that you still had pending tasks when you exited the bot.

**Comment by Rapptz** [comment]
My guess is that you had something blocking for longer than heartbeat_interval left and that closed the websocket and the bot.

**Comment by shrx** [comment]
Aha, thanks for this, will investigate.

**Comment by shrx** [comment]
I can confirm this happens under heavy CPU and memory load - there are no other warnings and then the "pending task destroyed" warning happens.

**Comment by shrx** [comment]
I have created a question on SO: http://stackoverflow.com/questions/35911782/python-asyncio-loop-exits-with-task-was-destroyed-but-it-is-pending
