### ISSUE TITLE
on_reaction_add positional arguments

### ISSUE THREAD

**Issue by MysteryPig** [Rapptz/discord.py#1010]
When on_reaction_add() is called, this error is thrown:
`Ignoring exception in on_reaction_add
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
TypeError: on_reaction_add() takes 0 positional arguments but 2 were given
`

**Comment by Vexs** [comment]
That's because it takes two positional arguments- reaction, and user. http://discordpy.readthedocs.io/en/latest/api.html#discord.on_reaction_add

**Comment by MysteryPig** [comment]
Oh, I read the numbers backwards. Maybe I am dyslexic. Thank you!
