### ISSUE TITLE
get online status

### ISSUE THREAD

**Issue by rektile** [Rapptz/discord.py#1012]
i want my bot to get all the players that are online atm
but when i try it doesnt give an output.

```python
for member in bot.get_all_members():
        if member.status == "online":
             print(member.name, member.status)
```

i hope you could help me.
its probably something stupid

**Comment by scragly** [comment]
The github issues are really for bugs and such with the lib, not really for code help. If you need help, there's a good community in the support server:
https://discord.gg/discord-api

**Comment by rektile** [comment]
im not someone who's always home or has time to go to discord

**Comment by SunDwarf** [comment]
Unfortunately that doesn't change that this issues board is not a board for basic bot help. Find some time to join the Discord and get help there.

**Comment by rektile** [comment]
nvm already found it
