### ISSUE TITLE
Bot crashes on `client.run()`

### ISSUE THREAD

**Issue by IanGolsby** [Rapptz/discord.py#1013]
When I use `client.run(token)` with the token variable (which is set to my token, and when I get not lazy I'll get the token for the actual bot from the developers page), I get errors saying invalid token was passed. I know the token works cause I directly copied it from local storage (double clicked var name so it's automatically all in the clipboard). Any idea why this is happening?

**Comment by IanGolsby** [comment]
import discord
import asyncio

token = "my token"
client = discord.Client()

@client.event
async def on_ready():
    print("Logged in as:")
    print(client.user.name)
    print(client.user.id)
    print("-----")

@client.event
async def on_message(message):
    if message.author.id == 224712063832948736:
        if message.content.startsWith('>help'):
            await client.send_message(message.channel, '**Commands List:**\n`>help` - sends this message. Lists all commands.')

client.run(token)

**Comment by adx59** [comment]
When creating a self bot, you need to pass the `bot=False` param to your run function.
It should be `client.run(token, bot=False)` instead.

**Comment by diceroll123** [comment]
`and when I get not lazy I'll get the token for the actual bot from the developers page`

Your laziness is the actual issue here.

`client.run(token, bot=False)` is how you'd run a selfbot.
