### ISSUE TITLE
change_status returns string error

### ISSUE THREAD

**Issue by Funky7Monkey** [Rapptz/discord.py#102]
The attached file returns the following error:
[selfbot.txt](https://github.com/Rapptz/discord.py/files/133520/selfbot.txt) (it's a *.py, just changed to *.txt for upload)

`Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\discord\client.py", line 540, in dispatch
    getattr(self, event_method, utils._null_event)(*args, **kwargs)
  File "*files*\selfbot.py", line 23
, in on_message
    client.change_status(game = mes)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\discord\client.py", line 1478, in change_status
    'game': game and {'name': game.name},
AttributeError: 'str' object has no attribute 'name'`

**Comment by diceroll123** [comment]
`client.change_status(discord.Game(name='Half-Life 3 beta'))`

Need to make it a discord.Game object!

**Comment by Funky7Monkey** [comment]
Tested that. It didn't change the status for me. It might actually be a problem with Discord, as I am trying to have it say my primary account is playing a game, rather than a bot account. I will test with a bot account.

**Comment by khazhyk** [comment]
A note that if you set your own game status with a bot, you will never see it on you own account, but you will usually be able to see it from another account.
