### ISSUE TITLE
Webhook management

### ISSUE THREAD

**Issue by speedstyle** [Rapptz/discord.py#1021]
There does not appear to be a method of [creating webhooks](https://github.com/discordapp/discord-api-docs/blob/master/docs/resources/Webhook.md#create-webhook--post-channelschanneliddocs_channelchannel-objectwebhooks) — or, if there is, any [documentation](http://discordpy.readthedocs.io/en/latest/search.html?q=webhook&check_keywords=yes&area=default) about it.

**Comment by MysterialPy** [comment]
Webhook Support is only available on the Rewrite branch of the Library.

**You can install the latest version of Rewrite:**
`python3 -m pip install -U git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]`

If you choose to switch, please read through:
http://discordpy.readthedocs.io/en/rewrite/migrating.html

For documentation on Webhook Support in Rewrite:
http://discordpy.readthedocs.io/en/rewrite/api.html#webhook-support
