### ISSUE TITLE
Pass extra arguments to on_message

### ISSUE THREAD

**Issue by Blacksilver42** [Rapptz/discord.py#1022]
For example,
```
client = discord.Client()
TOKEN = "..."

@client.event
async def on_message(M, f):
    print("#"+str(M.channel) + " <" + str(M.user) + "> " + M.content, file=f)


logfile = open("discord.log", "w")

client.run(TOKEN, on_message_args=(logfile,))
```
Or `on_error` or whatever. My use case for this isn't actually logging to a file, but this seemed like the simplest example.

[Feature request]

**Comment by Vexs** [comment]
What exactly are you saying here? You don't need to pass things as arguments to have access to them within that scope.

 Is this a feature request?

**Comment by AileenLumina** [comment]
You may want to look into configuring the logging module to write to a file. discord.py's Logger is called `discord`.

**Comment by Blacksilver42** [comment]
It's just an example; I don't actually want to log to a file.

**Comment by Helehelehele** [comment]
How would the library know what you want to be passed?

**Comment by Rapptz** [comment]
Use subclassing and just assign it to a variable.

This is an overcomplication for no real benefit.
