### ISSUE TITLE
How to send a private message.

### ISSUE THREAD

**Issue by MCMXCIII** [Rapptz/discord.py#1025]
I saw where someone else asked this question but when I tried using it in that context I couldn't get it to work maybe you can show me an example line?

**Comment by Dalekfodder** [comment]
A quick search on the documents gives you this:
https://gyazo.com/09c06af18538031b1f8c85cb87bc81bf

**Now imagine what you can do with a slightly longer search.**

**Comment by Gorialis** [comment]
This looks like you're trying to ask how to DM a user based on an ID. Your image already shows how to do this, so you can just combine it with the documentation as shown by @Dalekfodder : 
```py
user = discord.utils.get(client.get_all_members(), id='1234')

if user is not None:
    await client.send_message(user, "A message for you")
else:
    # Your bot can't see the user, and therefore wouldn't have permission to DM them anyway.
    # Choose how you want to handle this here.
```

**Comment by laggycomputer** [comment]
Kindly do not post on dead, long gone closed issues.

The README links a [help server ](discord.gg/dpy)that you can join to request help with library use. GitHub issues are not where help is given.
