### ISSUE TITLE
Creating channel categories

### ISSUE THREAD

**Issue by Bradon-Lodwick** [Rapptz/discord.py#1026]
Hi! I was having troubles making channel categories.  When I try to specify the type in the create_channel method, I am told that the enums file doesn't have a category option, and when i try using the value of 4 like it is written on the enums file in the repo it doesn't work either. Is this option not on the live version and only in the development version? Thanks in advance!

**Comment by SourSpoon** [comment]
Creating channel categories is not available in 0.16.x (async branch). The development version has it.  If you wish to use the development version it is recommended that you visit the discord.py discord server, and subscribe to update announcements.

https://discord.gg/r3sSKJJ

**Comment by Bradon-Lodwick** [comment]
Awesome! Thank you!
