### ISSUE TITLE
What's wrong?

### ISSUE THREAD

**Issue by revazed** [Rapptz/discord.py#1028]
When I type in Ubuntu;

`sudo pip install discord.py`

I am getting the following error;

`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-PBJCDD/aiohttp/`

Any idea about how to fix this?

**Comment by AbadeQ8** [comment]
are you sure you are used pip3 ?

try 
sudo pip3 install discord.py

**Comment by revazed** [comment]
Thanks, typed the following in terminal and helped!


`sudo apt install python3-pip`
