### ISSUE TITLE
on_reaction_add(reaction, user) does not work after bot restart

### ISSUE THREAD

**Issue by onkels** [Rapptz/discord.py#1030]
Hi,

I created a bot with discord.py and added some emojs to messages. As long as the bot runs, it get's notified when a user clicks an emoij via on_reaction_add. But if I need to restart the bot, I get no events for clicks on emojs created in the previous run of the bot.

Can you give me a hint how to re-attach all old emojis to the current bot session?

BR

**Comment by Vexs** [comment]
There is no clean solution to add stuff to the cache such that it triggers those events. Instead, filter the `on_socket_raw_receive` event for reactions being added, or use the rewrite branch which has `on_raw_reaction_add`, which is filtered and processed for you.

**Comment by onkels** [comment]
Thank you very much for the hints and the fast respone :-)
