### ISSUE TITLE
I get an SSL Error when running my bot

### ISSUE THREAD

**Issue by keeganjk** [Rapptz/discord.py#1031]
I get this error when running my bot:
`aiohttp.errors.ClientOSError: [Errno 1] Cannot connect to host discordapp.com:443 ssl:True [Can not connect to discordapp.com:443 [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)]]
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x1055167f0>`

Here's the code for the bot:
```
#!/usr/bin/env python3
  
import discord, asyncio

client = discord.Client()

@client.event
async def on_ready():
        print("Logged in as:")
        print("client.user.name")
        print("client.user.id")
        print("_" * 80)

@client.event
async def on_message():
        await client.say("hi")

client.run('token')
```

Why do I get this error and how can I fix it?

**Comment by SourSpoon** [comment]
Common Issue on python 3.6 & OSX
Navigate to your Applications/Python 3.6/ folder and double click the Install Certificates.command to fix t

**Comment by BusyGene** [comment]
> Common Issue on python 3.6 & OSX
> Navigate to your Applications/Python 3.6/ folder and double click the Install Certificates.command to fix this

I've had installed cerifi but it still doesn't not work.

**Comment by Amorano** [comment]
I am not using OSX, and have this issue. Win 7.

**Comment by Termed** [comment]
I am getting the same problem and Im using Windows 10, Python 3.8.2

**Comment by AbstractUmbra** [comment]
Please don't necro old issues.

This issue is #4159 please see here for the resolution.

**Comment by isaako-mode** [comment]
I have the same problem and I'm running Python 3.7 on windows 10.

**Comment by TheRealKeto** [comment]
See the comment above for a resolution.

**Comment by apanin** [comment]
> Common Issue on python 3.6 & OSX
> Navigate to your Applications/Python 3.6/ folder and double click the Install Certificates.command to fix this

Anyone using mac, this is it!

**Comment by egel-lang** [comment]
I had the same problem. Fixed with the install certificates command. Most people don't seem to encounter this though, the bug is maybe due to me having various Python brew installs around, i.e., the certificates get updated but in the wrong Python environment. Not likely you'ld want to spend a lot of time on.

**Comment by GabrielBrezeanu** [comment]
I have two fixes:
1. $ sudo update-ca-certificates --fresh
    $ export SSL_CERT_DIR=/etc/ssl/certs
    $ sudo update-ca-certificates --fresh

2. pip install --upgrade certifi

**Comment by Byproduct** [comment]
> I have two fixes:
> 
>     1. $ sudo update-ca-certificates --fresh
>        $ export SSL_CERT_DIR=/etc/ssl/certs
> 
>     2. pip install --upgrade certifi

Thank you for this. Had to google so long but this finally fixed the problem on Linux

**Comment by Megan8821** [comment]
> I'm on Mac Os X and use Python 3.8 and I tried to double click on installCertificates.command but I have this :
> 
> -- pip install --upgrade certifi Collecting certifi Using cached https://files.pythonhosted.org/packages/98/99/def511020aa8f663d4a2cfaa38467539e864799289ff354569e339e375b1/certifi-2020.4.5.2-py2.py3-none-any.whl Installing collected packages: certifi ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/certifi' Consider using the `--user` option or check the permissions.
> 
> WARNING: You are using pip version 19.2.3, however version 20.1.1 is available. You should consider upgrading via the 'pip install --upgrade pip' command. Traceback (most recent call last): File "", line 44, in File "", line 24, in main File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8', '-E', '-s', '-m', 'pip', 'install', '--upgrade', 'certifi']' returned non-zero exit status 1. logout Saving session... ...copying shared history... ...saving history...truncating history files... ...completed.
> 
> and it still not works

I got this error too! Any ways to solve it?
