### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by revazed** [Rapptz/discord.py#1033]
Alright, this is what I get when Heroku runs my bot:

`AttributeError: 'Client' object has no attribute 'send_message'`

But on my machine it works fine, what could be wrong?

**Comment by SourSpoon** [comment]
Ensure that the version of discord.py is the same on both heroku and your PC. The latest stable release is 0.16.12 which is what you have coded your bot for.

**Comment by Rapptz** [comment]
This looks like a version mismatch. Probably installing v1.0 on Heroku and v0.16.x on your machine.
