### ISSUE TITLE
How can I redirect stdin and stdout?

### ISSUE THREAD

**Issue by Rxted** [Rapptz/discord.py#1034]
I'd like to redirect stdin and stdout to the yield from await message and yield from send message respectively. I'm completely unsure if this is possible or not.

**Comment by BlackSynder** [comment]
You might be able to hack something up with [redirect_stdout.](https://docs.python.org/3/library/contextlib.html#contextlib.redirect_stdout)

**Comment by Modelmat** [comment]
https://github.com/Rapptz/RoboDanny/blob/rewrite/cogs/admin.py#L70-L115 has an example of this.
