### ISSUE TITLE
Adding ban reason

### ISSUE THREAD

**Issue by spectras** [Rapptz/discord.py#1036]
Hello.
Thanks for your work on this api, using it has been great so far.
However, I would need to specify ban reasons when my bot bans a user, for logging purposes.

It is a new optional string parameter that was added to the [create guild ban](https://discordapp.com/developers/docs/resources/guild#create-guild-ban) endpoint a few months ago I believe. It would be great if you could add it to the `Client.ban` method.

**Comment by scragly** [comment]
Ban reasons have already  been added to the rewrite version, and async won't be receiving any new features as far as I know.

**Comment by spectras** [comment]
Okay my bad I just took the last release tag. It's still based on `async` branch.

Alright, I'll look into switching to rewrite the. Thanks.
