### ISSUE TITLE
Make bot.client_id a string and oauth_url take in a string parameter

### ISSUE THREAD

**Issue by bmintz** [Rapptz/discord.py#1041]
Currently bot.client_id is a string, and oauth_url is documented as requiring one. However, since it uses `.format`, it can also take an int. Change the docs to say that the client_id parameter is an int, and so is Client.client_id.

**Comment by mental32** [comment]
async branch treats IDs as strings.
rewrite treats them as ints.

str.format will typecast each argument to a string so it doesn't matter if you pass in an `int` or `str` it'll end up a string

**Comment by Gorialis** [comment]
`Client.client_id` is not a real attribute on either of the active branches. I can only assume from the rest of the issue comment that you mean you want the (oauth_url docstring)[https://github.com/Rapptz/discord.py/blob/rewrite/discord/utils.py#L101] changed to say that it is an integer, not a string.
On async, all IDs are strings, so it doesn't make a lot of sense to change there.
On rewrite, while IDs are generally represented as integers, I don't think it really makes a difference to change the docstring here. I don't think it'd be an unwelcome change, just that it's very low priority as it works either way (as you mention).
