### ISSUE TITLE
Colour factories

### ISSUE THREAD

**Issue by speedstyle** [Rapptz/discord.py#1043]
Surely it would be more logical to have a single colour keyword factory (e.g. `Colour.keyword('teal')`) rather than the current system of individual keyword factories (e.g. `Colour.teal()`)? This would allow for later expansion (e.g. CSS colour keywords).

Additionally, there are four colours (not including white) which appear on the [Discord branding](https://discordapp.com/branding) website. Two of them (blurple and greyple) are already defined, but I think the others would also be useful.

**Comment by Rapptz** [comment]
One approach requires a dictionary for no real purpose other than syntax.

The other works as-is.

I see no benefit to your approach.
