### ISSUE TITLE
[Discord.py]Change the nick of a user

### ISSUE THREAD

**Issue by stavzog** [Rapptz/discord.py#1044]
I want to change the nick of a user but I dont know what do u need to put in the first param of the change_nickname() corourtine. Cam sb pls help me with that

**Comment by FrostLuma** [comment]
The first argument is the member you want to change the nickname of, the second one a string with the new nickname. (see [here](https://discordpy.readthedocs.io/en/v0.16.7/api.html#discord.Client.change_nickname) for the documentation)

You can get the member by either using [`server.get_member`](https://discordpy.readthedocs.io/en/v0.16.7/api.html#discord.Server.get_member) if you know the members user ID or from context in an event (eg. in [`on_message`](https://discordpy.readthedocs.io/en/v0.16.7/api.html#discord.on_message) you have the `author` attribute which is a member if the message is not in a private channel, other events work similarly)

**Comment by stavzog** [comment]
Thanks aaaaa LOT! It worked. I have searched all the internet on how to make it work!!Thank you very very much

**Comment by banana312323** [comment]
what is the class that i should take from the change_nickname() func?

**Comment by oliver-ni** [comment]
> what is the class that i should take from the change_nickname() func?

This doesn't exist anymore. Use `Member.edit` with the `nick` kwarg.

**Comment by banana312323** [comment]
can you write your code here?

**Comment by oliver-ni** [comment]
no

**Comment by banana312323** [comment]
why?

**Comment by oliver-ni** [comment]
I told you how to do it. Do it yourself.

**Comment by banana312323** [comment]
it doesn't working

**Comment by oliver-ni** [comment]
https://discord.gg/dpy
