### ISSUE TITLE
Get txt channel ID only when u have the name

### ISSUE THREAD

**Issue by stavzog** [Rapptz/discord.py#1046]
Is there a way to get the ID of a text channel only by knowing its name.If there is please tell me how.

**Comment by Modelmat** [comment]
http://discordpy.readthedocs.io/en/rewrite/api.html#discord.utils.get

**Comment by LewdNeko** [comment]
Heya! You'd be able to get quicker and better help in the discord.py support server. Here's an invite https://discord.gg/r3sSKJJ
