### ISSUE TITLE
Message Embeds parameter

### ISSUE THREAD

**Issue by Werseter** [Rapptz/discord.py#1048]
I am in process of migrating my bot from 0.16 async version to 1.0.0 rewrite. I've been using a custom wrapper to send embeds along the text messages. I've noticed that rewrite has *embeds* parameter available, but it doesn't seem to work.

`await channel.send(msg, embed=embeds[0])` - this works correctly, as expected
`await channel.send(msg, embeds=embeds)` - results in no message being sent.

**Comment by SourSpoon** [comment]
you need to give `.send()` an embed object to the kwarg `embed`. You can not send multiple embeds.

Embeds is not a valid kwarg.

These kind of questions are better suited to the discord.py discord server. https://discord.gg/r3sSKJJ

**Comment by Werseter** [comment]
According to rewrite api docs - this is a valid option.

**Comment by Werseter** [comment]
- embed (Embed) – The rich embed for the content to send. This cannot be mixed with embeds parameter.
- embeds (List[Embed]) – A list of embeds to send with the content. Maximum of 10. This cannot be mixed with the embed parameter.

**Comment by Ikusaba-san** [comment]
`embeds` are for webhooks, not channels.
