### ISSUE TITLE
how to get the members of a voice channel?

### ISSUE THREAD

**Issue by George-Kaloudis** [Rapptz/discord.py#1049]
I want to make a timeout command and i need a command that gtets all the users of a voice channel.

**Comment by scragly** [comment]
**Async**
`channel.voice_members`
http://discordpy.readthedocs.io/en/latest/api.html#discord.Channel.voice_members

**Rewrite**
`voicechannel.members`
http://discordpy.readthedocs.io/en/rewrite/api.html#discord.VoiceChannel.members

**Comment by George-Kaloudis** [comment]
Thanks!!

**Comment by scragly** [comment]
Please close the issue.
