### ISSUE TITLE
fast color change in roles

### ISSUE THREAD

**Issue by daxil34** [Rapptz/discord.py#1050]
hello everyone how to make the roles change colors every 3 seconds. I know that I have to use role_edit but I still do not know how to change every 3 seconds it can be time.sleep (3)?

**Comment by SourSpoon** [comment]
This is a bad idea and will be considered api abuse. This can lead to your account getting banned.

However, what I will say is that time.sleep is a blocking function and will stop your bot from processing messages, sending heartbeats ect while the function is sleeping. Use asyncio.sleep instead, which is a coroutine.

**Comment by daxil34** [comment]
Thx
