### ISSUE TITLE
[Question] Load UTF-8 JSON file async inside a bot

### ISSUE THREAD

**Issue by MrDini123** [Rapptz/discord.py#1058]
Hi,

I have a huge JSON file encoded in UTF-8 because of some chinese values are stored in it... But when I try to simply read it using the open("filepath").read() function, it throws a Can't decode error... If I use codecs library, than it works from console, and I Can extract values from that, but I don't think it is asynchronous... And the bot does nothing in action.

What is the easiest way to load and go through a big JSON file/array?

And as I experienced, an event with a return in it Can break the commands to be executed. Is it right? Like I have an on_message event with a return. Then the ?help command not works (and all the others).

Thanks a lot!

PS: Sorry for my bad english

**Comment by Vexs** [comment]
Loading a json (regardless of utf-8ness) is the same- you just use the json module. 

```
with open("somefile.json") as f:
    data = json.load(f)```
The json module is very fast, so unless your json file is completely massive(10-100mb) and you're loading it a lot, (In which case, a database is what you want) you don't need to worry about blocking, but you could use asyncio's loop.run_in_executor if you do match that. (And again, a database would be better)

Also, returning from an event isn't what's causing your issue, you can return in an event just fine. The commands ext uses on_message to process commands, and when you define your own, it overrides it- all you have to do is add `await bot.process_commands(message)`, as is noted in the FAQ part of the docs.

**Comment by imayhaveborkedit** [comment]
```py
with open("filepath", encoding='utf8') as f: ...
```

**Comment by MrDini123** [comment]
Thanks a lot guys! That worked.
