### ISSUE TITLE
Default Help Command

### ISSUE THREAD

**Issue by Swifx** [Rapptz/discord.py#1059]
- Well, about this, I tried everything I could to remove he default help command, and I added a command, by doing the on_message method, and now it shows both, and yes i also did bot.remove_command(help) and it did nothing.

**Comment by OneEyedKnight** [comment]
Did you put it before on_ready? Also it's ``bot.remove_command('help')`` and join the official discord server for discord.py if you haven't already.  https://discord.gg/r3sSKJJ

**Comment by Vexs** [comment]
On_ready doesn't matter here. 

Could you please put your bot code, sans token, into hastebin/ghostbin/gist?

**Comment by Swifx** [comment]
Alright, I will when I get home.

**Comment by Swifx** [comment]
import discord
import asyncio
import requests
import whatever( this is a example, not gonna show everything lmao)

client = discord.Client()
bot_prefix= "thebotprefixlol"
client = commands.Bot(command_prefix=bot_prefix)
bot.remove_command('help')

@client.event
async def on_ready():
    print('Logged in as')
    print(client.user.name)
    print(client.user.id)
    print('Complete!')
 


@client.command(pass_context = True)
async def test(ctx):
    embed = discord.Embed(title = "t",color = 0xFFFFF)
    return await client.say(embed = embed)






client.run('mytoken')

**Comment by Swifx** [comment]
^ Yes I realize, it requires ``from discord.ext import commands``

**Comment by Vexs** [comment]
Right, you're mixing discord.Client and commands.Bot. Use one or the other, not both. Commands.bot does everything discord.Client does as well as the commands ext. 

Replace bot.remove_command with client.remove_command, as you have named your instance of commands.Bot client.

**Comment by Swifx** [comment]
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fb692e47c18>
After that.

**Comment by Swifx** [comment]
And it does nothing, even after the error is fixed.

**Comment by Swifx** [comment]
Still shows the normal help command.

**Comment by notBanii** [comment]
```python
Client = discord.Client()
# delete this above line all together, dont use both commands.Bot and discord.Client
bot_prefix= "theprefix"
client = commands.Bot(command_prefix=bot_prefix)
client.remove_command('help')
```

**Comment by Swifx** [comment]
I'll try.

**Comment by Swifx** [comment]
Still displays normal help command, this is the async branch btw.

**Comment by Swifx** [comment]
Nevermind, thanks!
