### ISSUE TITLE
Print usernames of users who use the bot?

### ISSUE THREAD

**Issue by Poncedeleon100** [Rapptz/discord.py#1066]
I'm writing my own bot and I want to be able to print the message a user says in chat when a user uses a command, and their username and ID in the console.

I already know how to get the user's ID in the console, here's my code for one of the commands.
![image](https://user-images.githubusercontent.com/36371808/36074659-420e913c-0f11-11e8-95ae-ef6374ac30d2.png)
And this is what is shown in the console
![image](https://user-images.githubusercontent.com/36371808/36074671-771af76c-0f11-11e8-8174-c845566a3484.png)

**Comment by diceroll123** [comment]
Let me get this straight...

You *uppercase the user's input*, then *check the now-uppercased user's input*, and your question is to print *the user's input*? I think you're overlooking something.

**Comment by Dannyiy** [comment]
await client.send_message(
        message.channel,
        "<{0} ({1})> {2}".format(
            message.author,
            message.author.id,
            message.content
        )
    )
