### ISSUE TITLE
Opus not working on bot

### ISSUE THREAD

**Issue by keeganjk** [Rapptz/discord.py#1077]
I've installed several `opus` packages in `brew` and `pip`, but when I run my bot 
(
```
import discord, random, subprocess, time
discord.opus.load_opus('opus')
client = discord.Client()
```
), I get this error:

`OSError: dlopen(opus, 6): image not found`

Why am I getting this error and how can I fix it?

**Comment by Naught0** [comment]
Hey this appears to be a Mac specific issue based on some cursory Googling. Try this SO thread https://stackoverflow.com/a/33794703 and here's the relevant excerpt.  
```
pip install --upgrade billiard
pip install --upgrade celery
pip install --upgrade kombu
pip install --upgrade amqp
```

**Comment by Rapptz** [comment]
If you installed it with brew for the system you don't need to use `discord.opus.load_opus`.
