### ISSUE TITLE
Invite link in FAQ, to the discord.py server, is invalid. 

### ISSUE THREAD

**Issue by Esterni** [Rapptz/discord.py#1079]
Just tried to connect to the Discord server of discord.py and i appears to have expired or been deleted. Would greatly appreciate some help 😁

**Comment by jwshields** [comment]
The link is still valid. I just tested it with my account.

**Comment by Esterni** [comment]
Ahh, I see the issue. The specific invite link in the FAQ [here](https://github.com/Rapptz/discord.py/blob/async/docs/faq.rst#is-there-any-documentation-for-this) is invalid. But not the one at the top of the Readme.

**Comment by DeveloperACE** [comment]
the one in the READme seems to have expired for me

**Comment by Vexs** [comment]
The invite is valid. You may have been banned.

**Comment by Esterni** [comment]
Yes. Both the invites in the README.md are valid. The link contained in the FAQ [here](https://github.com/Rapptz/discord.py/blob/async/docs/faq.rst#is-there-any-documentation-for-this) is still not valid as I said above.

**Comment by Vexs** [comment]
You're correct- was replying to @DeveloperACE. The FAQ is fixed on the rewrite branch which should become the main branch soon™
