### ISSUE TITLE
[bug?] Message.mentions does not have all mentions

### ISSUE THREAD

**Issue by tkossak** [Rapptz/discord.py#1080]
Hi,
I have a message in a channel for which discord.py shows wrong number of mentions: there are only 2 mentions in `Message.mentions` but 3 mentions in `Message.raw_mentions` (this one is correct). When i look at discod it really has 3 mentions (I can click on all of them). The missing mention is at the end of the message.
Worth noting is that `Message.clean_content` shows first 2 mentions by their name (`@NAME`) and 3'rd mention by user ID (` <@!ID>`).

I use:
Linux MInt
Python 3.6.4
discord.py: VersionInfo(major=0, minor=16, micro=12, releaselevel='final', serial=0)

I can PM you the exact details of the message (content, actual mentions, IDs, etc).

**Comment by Vexs** [comment]
Message.mentions returns member objects from the cache for mentioned people. If the bot does not share a server with a mentioned person, they are not in the member cache, and thus won't show up in message.mentions

**Comment by tkossak** [comment]
Yes, that's the case here. If it is by design then maybe it's worth noting in the docs: http://discordpy.readthedocs.io/en/latest/api.html#discord.Message.mentions

**Comment by Rapptz** [comment]
`Message.mentions` is returned by Discord, I just transform it into `User` objects and then optionally transform them into `Member` objects.

If the count is off it's because it's not an actual mention recognised by Discord.

`Message.raw_mentions` instead uses regex and is as a result much more liberal.
