### ISSUE TITLE
How do I Send A Direct Message With a Users' ID?

### ISSUE THREAD

**Issue by Duncan494** [Rapptz/discord.py#1087]
So Far i have this,
await client.send_message(discord.Object(id="USERSID"), "MESSAGE")
I have tried lots of things but it won't Work please help!

**Comment by SourSpoon** [comment]
You need a user object or member object.

How you would get these kinda depends on some context. But here is a quick faq on the topic.
http://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-get-a-specific-user-role-channel-server

**Comment by Vexs** [comment]
This is one of the few places a discord.Object can't be used in lieu of a proper member object- the lib explicitly checks for a discord.Member/user object

**Comment by Rapptz** [comment]
Duplicate of #1025

**Comment by CodingDotExe** [comment]
Try:
```python
user = await bot.get_user_info(user_id="USER'S ID")
await bot.send_message(user, "Your message")
```
It should work (for discord;py==0.16.12)
