### ISSUE TITLE
user.mention() doesn't mention users properly

### ISSUE THREAD

**Issue by Funky7Monkey** [Rapptz/discord.py#109]
Mentions done through user.mention() do not mention users in a way that gives the mention notification, or even just doesn't work at all (as shown in first screenshot). Also, (as shown in second screenshot, taken by user mentioned in both messages (cropped for privacy)) mentions done through user.mention() are not highlighted like they are when done through a client.

![ss 2016-02-20 at 09 54 11](https://cloud.githubusercontent.com/assets/16708714/13200607/6beb0728-d81e-11e5-84b3-0b4c54131727.png)
![ss 2016-02-20 at 10 04 30](https://cloud.githubusercontent.com/assets/16708714/13200608/6bede254-d81e-11e5-84d5-3d6d9655c95e.png)

**Comment by Rapptz** [comment]
This is fixed in async.It will not be backported into legacy.
