### ISSUE TITLE
How do you use add_roles

### ISSUE THREAD

**Issue by BadScripter** [Rapptz/discord.py#1092]
I've been trying to use this function, but I can't figure out how to make it work.  I need some kind of example to work off of.

**Comment by Vexs** [comment]
For rewrite branch it's 
`await some_member_object.add_roles(*[role_object1, role_object2])`
For async branch it's
`await client.add_roles(some_member_object, *[role_object1, role_object2])`

Member objects can be obtained as attributes of message objects, (or server objects) and role objects are usually obtained by iterating through server.roles

**Comment by BadScripter** [comment]
Thanks! That helps a lot!!
