### ISSUE TITLE
Unclosed client session client_session: <aiohttp.client.ClientSession object at 0x0000005B52D75400>

### ISSUE THREAD

**Issue by NitroFox0** [Rapptz/discord.py#1096]
`import discord
import json
import os.path

client = discord.Client()
BOT_TOKEN = "took this out"

@client.event
async def on_ready():
    print(client.user.name)
    print("Bot has been activated")
    print("===================")

@client.event
async def on_message(message):

    if message.content.lower().startswith('.test'):
        await client.send_message(message.channel, "Test")

    if message.content.lower().startswith('.xp'):
        await client.send_message(message.channel, "you have `{}` XP!".format(get_xp(message.author.id)))

    user_add_xp(message.author.id, 2)

def user_add_xp(user_id: int, xp: int):
    if os.path.isfile("users.json"):
        try:
            with open('users.json', 'r') as fp:
                users = json.load(fp)
            users[user_id]['xp'] += xp
            with open('users.json', 'w') as fp:
                json.dump(users, fp, sort_keys=True, indent=4)
        except KeyError:
            with open('users.json', 'r') as fp:
                users = json.load(fp)
            users[user_id] = {}
            users[user_id]['xp'] = xp
            with open('users.json', 'w') as fp:
                json.dump(users, fp, sort_keys=True, indent=4)
    else:
        users = {user_id: {}}
        users[user_id]['xp'] = xp
        with open('users.json', 'w') as fp:
            json.dump(users, fp, sort_keys=True, indent=4)

def get_xp(user_id: int):
    if os.path.isfile('users.json'):
        with open('users.json', 'r') as fp:
            users = json.load(fp)
        return users[user_id]['xp']
    else:
        return 0
`

**Comment by Gorialis** [comment]
This error is because you never run your bot using `client.run`, so the client gets destroyed without ever starting. The ClientSession error is the bot's internal session complaining that it wasn't closed gracefully (as the bot never had a chance to exit properly, given that it never even started)

**Comment by vlnerable** [comment]
How can I solve this problem?

**Comment by gamescom15** [comment]
This is not an issue with discord.py.
GitHub issues for this repository should be used to report issues with this library.
For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) as the README recommends.
