### ISSUE TITLE
[RFE] Configurable list of excluded keys from the cooldown check

### ISSUE THREAD

**Issue by mrc0mmand** [Rapptz/discord.py#1097]
In the current state, the [cooldown](https://github.com/Rapptz/discord.py/blob/async/discord/ext/commands/cooldowns.py) functionality does not allow excluding certain keys (users/roles/etc.) from the cooldown check - e.g. when having a cooldown check with `BucketType.user` type[0], it would be nice to have a list of users for which this check would be always skipped (regular users vs admins).

The first solution which came to my mind would be creating a dummy class, which would inherit properties of the `Cooldown` class, but the `is_rate_limited()` method would always return zero. Then the `CooldownMapping.get_bucket()` would instantiate this class instead of the `Cooldown` one for all keys from the exclusion list.

But of course there are definitely better solutions to achieve this.

[0] `@commands.cooldown(rate=3, per=60, type=commands.BucketType.user)`

**Comment by Vexs** [comment]
You can use command error handlers to solve this problem. 

```py
    @command_name.error
    async def command_name_error(self, ctx, error):
        if isinstance(error,commands.CommandOnCooldown):
            if ctx.message.author.server_permissions.manage_roles:
                await ctx.reinvoke()
                return
            await ctx.send(error)```

**Comment by mrc0mmand** [comment]
@Vexs Oh my, how could I miss that... thanks a lot!
