### ISSUE TITLE
on_ready / wait_until_ready occurring before library has guild data.

### ISSUE THREAD

**Issue by MattIPv4** [Rapptz/discord.py#1098]
This is an issue(?) I've found within rewrite involving ready stuff happening before the internal cache is populated and ready to be used fully.
I present my issue in the form of a gist as this was easiest to write up the testing and results.
https://gist.github.com/MattIPv4/6ce18631cbbdb6a71772f9da983fa0cd

**Comment by tazz4843** [comment]
I can reproduce this, but it only seems to happen when average websocket latency is <75ms. on_ready fires normally on my bots hosted at home where latency is about 100ms, but my more popular bots are on VPSes in San Francisco, where their WS latency is about 72ms. Then again this might just be a random unrelated issue, who knows.

**Comment by Rapptz** [comment]
Please don't necro issues. Likewise, latencies under 75ms are common and do not cause any issues.
