### ISSUE TITLE
Allow channel.history() to include the messages passed as before/after arguments

### ISSUE THREAD

**Issue by qxu21** [Rapptz/discord.py#1099]
Currently, if you have in a channel:

Message1
Message2
Message3

and you store these messages as variables,

`channel.history(before=Message3, after=Message1)`

will only return Message2 in an AsyncIterator. Is there any way (like an `inclusive` parameter, default `False`) we can have the AsyncIterator return all three messages in this case, or include the before and after messages?

**Comment by Vexs** [comment]
You can do this by just adding or subtracting some time from the timestamp of the message objects. 

Alternatively, as a little hack, you can add/subtract 1000000 to the ID, and then use utils.snowflake_time() to get a datetime, which would move the before/after time just enough to include them.

**Comment by Rapptz** [comment]
Problem with this is that the current behaviour is `(a, b)`. With a single flag would that make it `[a, b)`, `[a, b]` or `(a, b]`? Two flags seems kind of excessive for fine grained behaviour but also a possibility.

**Comment by OrangutanGaming** [comment]
This has been implemented

**Comment by Harmon758** [comment]
@OrangutanGaming I'm not sure what you're referring to.
The description of the issue is still the current case, and I don't think there have been any relevant changes to `Messageable.history` yet.
