### ISSUE TITLE
change_presence works, but appears to revert a short time later

### ISSUE THREAD

**Issue by foresto** [Rapptz/discord.py#1103]
In my `on_ready()` handler, I `await self.change_presence(status=discord.Status.invisible)`. Immediately after the call completes, `server.me.status` is `offline`, as expected.

However, a short time later, `server.me.status` reverts to `online` again.

I have no other clients running, so I don't think it can be interference from another one.  What am I missing here?

**Comment by Rapptz** [comment]
That's my only guess.

Considering change_presence is simple and is just a websocket send the fact it stops displaying in the client could just be a bug with Discord. Not much I can do for you here.
