### ISSUE TITLE
Invisible bot commands

### ISSUE THREAD

**Issue by NihilistBrew** [Rapptz/discord.py#1108]
Sometimes, you don't want to show what commands users have called or maybe you don't want the bot to always show the output of said command to everyone in the server.

This issue has created botspam channels for servers, especially big ones. This very common workaround feels hatched-together and clunky, it creates a barrier between bot commands and chat, especially considering how the majority of software (especially games) hides command input/output for everyone but the caller. 

This functionallity can be seen with discord's own built-in bot Clyde.

Suggestion:

Add a flag that allows commands to be called and output silently, effectively removing the need for botspam channels and instead being able to merge a "general" chat with a "botspam" chat.

**Comment by Rapptz** [comment]
This isn't the place to ask for Discord feedback.

Sorry. Go to https://feedback.discordapp.com or https://discord.gg/discord-feedback to give feedback.
