### ISSUE TITLE
Some types of messages can not be deleted, even by the author

### ISSUE THREAD

**Issue by ButterCheezii** [Rapptz/discord.py#1114]
In some cases, `message.author.id == client.user.id` but `client.delete_message(message)` will error. This is because some types of messages can not be deleted by the author.

The types of messages that I have so far observed to have this behavior can only be created in a private message between two user accounts. Namely, the messages that occur when you start a voice call.

Feel free to close this issue, as I've never observed this issue with actual bot accounts. However, I do believe it should be noted in the documentation that being the author of a message does not necessarily mean you can delete it.

**Comment by Modelmat** [comment]
These are called system messages.
