### ISSUE TITLE
Python 3.7.0a4 x64 Windows throws SyntaxError on library import

### ISSUE THREAD

**Issue by ScttB** [Rapptz/discord.py#1116]
```Traceback (most recent call last):
  File "scottbeebibot.py", line 1, in <module>
    import discord
  File "C:\Users\####\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "C:\Users\####\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 38, in <module>
    from .state import ConnectionState
  File "C:\Users\####\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\state.py", line 36, in <module>
    from . import utils, compat
  File "C:\Users\####\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\compat.py", line 32
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax```

**Comment by Rapptz** [comment]
This is already fixed in development but not published on PyPI because 3.7 is not stable.

**Comment by ScttB** [comment]
Thanks, didn't think I would need to use the development version, you should probably put that in the FAQ until it's published.

**Comment by gogurtenjoyer** [comment]
I'm confused - you want them to put a note in the FAQ for everyone who happens to be using a pre-release python and expecting this to work?

**Comment by jwshields** [comment]
[README.md](https://github.com/Rapptz/discord.py/blob/async/README.md) on this repo shows "3.4, 3.5" as the versions that this library is compatible for.
The prereqs of rewrite state "3.4.2 or higher" [[Here]](http://discordpy.readthedocs.io/en/rewrite/intro.html#prerequisites) which, while doesn't explicitly disallow 3.7, it should be more or less inferred that developmental versions of languages should be used with care, if they're decided to be used at all.

On a tangent, read this thread, https://github.com/npm/npm/issues/19883#issuecomment-367644712
NPM mistakenly published a pre-release version which broke many things.

IMO, **there's no good reason to explicitly call out to not use 3.7** - if somebody is aware enough to download 3.7, they're making an obvious and conscious choice to download a pre-release version of the language. See this link: [Python.org Downloads](https://www.python.org/downloads/) - The main download presented is 3.6.4; and to get 3.7 you'd need to click into the pre-release link.

**Comment by vanillamice** [comment]
Now python 3.7 is stable and it's the main download but still this error shows up.

**Comment by ItWasAllIntended** [comment]
Yes, the async branch of dpy does not get updates anymore. There is a fix for the error on the repo but it has not been pushed to pypi

**Comment by vanillamice** [comment]
what should i do then? just manually fix it? or go back to 3.6.something?

**Comment by vanillamice** [comment]
i used the fix in the repo,thanks anyway

**Comment by vanillamice** [comment]
okay i fixed it but run into a similar problem with the websockets module,i think i will just go back to 3.6
