### ISSUE TITLE
How to avoid rate limiting

### ISSUE THREAD

**Issue by Breee** [Rapptz/discord.py#1119]
Greetings,

I wonder how I can avoid getting rate limited.
Is there a function implemented yet, to limit the number of messages sent by a bot in a specific time interval?

Kind regards
Bree

**Comment by Rapptz** [comment]
Rate limiting is already handled internally.

**Comment by Tips-Tricks-Solutions** [comment]
> Rate limiting is already handled internally.

But my bot got rate limited.Why?

**Comment by AbstractUmbra** [comment]
Common reasons are as follows:-
- You are using repl.it or another host that shares a block of IPs to a single node.
  - This means that all requests come from one origin IP and they all share a ratelimit.
- You are making HTTP requests to the API a lot.
  - This is why we provide many cache methods. (i.e. `get_X` vs `await fetch_X`)
