### ISSUE TITLE
[Rewrite] client.change_presence no longer works

### ISSUE THREAD

**Issue by Zenrac** [Rapptz/discord.py#1121]
I just noticed something since the last commit of the rewrite, 

```
game = discord.Game(type=1, url=None, name=None) 
await client.change_presence(activity=game, status=None, afk=False) # btw on discord.py.readthedoc it's still "game" instead of "activity" for the parameter
```
This code should put the bot in streaming status, but it doesn't. Moreover, whatever if I put 0, 1, 2, 3 it always displays "Playing a game".
Did I miss something with the breaking changes ?

**Comment by Rapptz** [comment]
You don't use discord.Game anymore to set non-Playing statuses. Please read the announcement post in the official server before creating an issue.
