### ISSUE TITLE
discord.errors.NotFound: NOT FOUND (status code: 404): Unknown Guild

### ISSUE THREAD

**Issue by 12rambau** [Rapptz/discord.py#1126]
I'm want to delete a certain user.role so I use this code : 
```python
for role in member.roles:
        print(role.name)
        if not (role.name == "@everyone" or role.name == "modo"): await client.delete_role(member, role)
```
as you can imagine the `print(role.name)` work perfectly but when it comes to the `delete_role` function I receive this error : 
```shell
File "PoGoBot.py", line 96, in changeTeam
    await client.delete_role(member, role)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/client.py", line 2883
, in delete_role
    yield from self.http.delete_role(server.id, role.id)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/http.py", line 198, i
n request
    raise NotFound(r, data)
discord.errors.NotFound: NOT FOUND (status code: 404): Unknown Guild
```
It's very strange because the role that I'm giving to the function is completely known as I can print its .name. Is this a bug ? M I blind to an abvious typo ? 

Thx

**Comment by Vexs** [comment]
[Delete_role takes in a server and a role, not a member and a role. ](http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.delete_role) 

It also deletes a role *from the server* not remove it from a user. You likely want [remove_roles.](http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.remove_roles)

**Comment by 12rambau** [comment]
sorry I will better read the doc next time
