### ISSUE TITLE
Sometimes ctx.guild.shard_id returns an error

### ISSUE THREAD

**Issue by Zenrac** [Rapptz/discord.py#1129]
Hi again,

I made a simple command to check the shard_id of my guilds, but one of my guilds returned an error with guild.shard_id.

`TypeError: unsupported operand type(s) for >>: 'str' and 'int'`

I found the sharding formula :
`(guild_id >> 22) % num_shards == shard_id`

I assume that guild_id type is str instead of int for this guild. 
I'm wondering why it is happening, and why only one guild.
I fixed it by restarting the bot, I don't know how to repro for the moment.

**Comment by Rapptz** [comment]
Very very very unlikely.

Two things:

1. I cannot repro, 
![image](https://user-images.githubusercontent.com/1695103/37237929-85ed0db0-23e9-11e8-8099-d9238c5be12f.png)
2. As seen [here](https://github.com/Rapptz/discord.py/blob/8ba78168a6e71cf8ade47b62e4659a720a13aa06/discord/guild.py#L214), there is a very explicit cast to `int`.

So unless you have some sort of traceback or some more information to go with this issue I'm going to close it.

**Comment by Zenrac** [comment]
Problem solved, I found these lines in one of my commands :
```
server = ctx.guild
server.id = str(ctx.guild.id)
```
It was pretty stupid to merge it like that, it overwrite until restart the ctx.guild.id. 

My bad.
