### ISSUE TITLE
Removing TTS messages in channels that have no focus will leave the notification icon.

### ISSUE THREAD

**Issue by JochemKuijpers** [Rapptz/discord.py#113]
Our bot sends TTS messages to a channel and deletes them moments later (about 10 seconds).

When I do not view these messages, the red notification icon stays next to the channel name even though the messages are already deleted. I could not reproduce this with normal users so it seems to me the problem is in DIscord.py.

Screenshot:
http://i.imgur.com/Pe89Aqn.png

Code (the part that sends the message):

```
    # send message with tts and autoremove after 10 seconds
    sentmsg = yield from client.send_message(botchannel, msg, tts=True)
    yield from asyncio.sleep(10)
    yield from client.delete_message(sentmsg)
```

According to @discordapp on Twitter, this is probably not caused by Discord itself:
https://twitter.com/discordapp/status/703282178009014272

**Comment by khazhyk** [comment]
The bots function as normal users and use the same functionality as "normal" users, so I can't imagine that this is a problem with the api.

**Comment by Rapptz** [comment]
There is no possibility of this being an issue on my end. I replicate what the actual discord client does. The acking aspect of the client is not touched and is entirely client sided on your end, not the bot's end.

**Comment by JochemKuijpers** [comment]
@khazhyk Can you give me a short description how to reproduce this behaviour with the normal Discord client instead of using bots? I will report this to Discord again.

Thanks for your replies.

**Comment by khazhyk** [comment]
@JochemKuijpers unless I'm misunderstanding the situation, the "red" notification only shows up when you @mention or @everyone - I was able to reproduce by joining an instant invite in incognito mode, clicking out to a different server on my main client, mentioning myself on the incognito client, then deleting the message.

**Comment by JochemKuijpers** [comment]
I reported this to Discord. Haven't got a response yet.

Thanks again.
