### ISSUE TITLE
My Discord Bot will not join the Voice Channel

### ISSUE THREAD

**Issue by Diamondman195** [Rapptz/discord.py#1131]
This is the code for the summon command:
    @commands.command(pass_context=True, no_pm=True)
    async def summon(self, ctx):
        """Summons the bot to join your voice channel."""
        summoned_channel = ctx.message.author.voice_channel
        if summoned_channel is None:
            await self.bot.say('You are not in a voice channel.')
            return False

        state = self.get_voice_state(ctx.message.server)
        if state.voice is None:
            state.voice = await self.bot.join_voice_channel(summoned_channel)
        else:
            await state.voice.move_to(summoned_channel)

        return True

The error I get is:
AttributeError: 'Member' object has no attribute 'voice_channel'

I have seen in other issues that changing to ctx.messgae.author.voice.voice_channel works for others, when I tried that I got the error 'VoiceState' object has no attribute 'voice_channel'
I have also tried reinstalling the libraries with the pip -U option and the pip --no-chache-dir options. 
A lot of the other commands wont work as well, when I try to do the play command it gives me an error of 'Member' has no attribute 'server'

**Comment by Rapptz** [comment]
You somehow have the rewrite version of the library installed. Though I can't say how you managed to accidentally install it considering the installation steps are not easy to do accidentally.

**Comment by Diamondman195** [comment]
How do I install the right version of the library?
