### ISSUE TITLE
Unclosed client session error ?

### ISSUE THREAD

**Issue by cluelessperson** [Rapptz/discord.py#1132]
I'm trying to catch login failures, but I keep getting this.

```
client = discord.Client()
try:
    client.run(TOKEN)
except (HTTPException, LoginFailure) as e:
    client.logout()
    client.close()
    log.fatal(e)
    log.fatal("Deleting config file.  Please re-enter at startup.")
    rmtree(default_config.config_dir)
```
OUTPUT:
```
Improper token has been passed.
Deleting config file.  Please re-enter at startup.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f307a6b1fd0>
```

**Comment by Gorialis** [comment]
`client.logout` and `client.close` are both coroutiens so they will not actually run like this.
Since `logout` just calls `close`, you can drop `close` and then just do:
```py
client.loop.run_until_complete(client.logout())
```
which should properly close the ClientSession, preventing this error.

**Comment by cluelessperson** [comment]
This error still occurs at a failed login.

**Comment by fourjr** [comment]
it's not really an error though, can you send your modified code?

**Comment by ST3VI3-RICHI3** [comment]
This happens to me despite the fact I don't use client at all, fact my client variable equals the bot variable so I use `bot.run(TOKEN)`
