### ISSUE TITLE
Retry connecting to Discord after Provider Disconnect

### ISSUE THREAD

**Issue by FWidm** [Rapptz/discord.py#1134]
Hi! I am currently selfhosting a small bot I've written with your library and came to one issue: 

My provider assigns new ip addresses daily, as such the bot will disconnect for an amount of time before the assignment & reconnect of the connection is finished. i've read in the descriptions: `This library implements reconnection logic and thus will end up calling this event whenever a RESUME request fails.`.  Is there a way to specify a timeout interval, so that the bot does not stop working after being disconnected for a few minutes?

Thanks for your help!

**Comment by Rapptz** [comment]
v0.16.x doesn't have backoff reconnect logic for internet outages. The v1.0 branch (i.e. rewrite) does. I don't plan on backporting it to v0.16.x.

So to answer the question, no, there isn't a way to specify a timeout interval because the reconnect logic in v0.16.x doesn't work like that.
