### ISSUE TITLE
AttributeError for some attribute without reason

### ISSUE THREAD

**Issue by RetardedGenji** [Rapptz/discord.py#1135]
Hey,

So first of all I'm french so sorry for my bad english.
I already created a bot using discord.py and everything worked just fine (it was on an other pc) but this time I get some AttributeError for some reason:
`AttributeError: module 'discord.ext.commands' has no attribute 'BotMissingPermissions'`
`AttributeError: module 'discord.ext.commands' has no attribute 'guild_only'`

I really don't get it and its kind of triggering me.
Can you help me ^^

**Comment by NCPlayz** [comment]
Hey, can you come to the discord.py server listed in the README.md? Thanks.

**Comment by Ikusaba-san** [comment]
`commands.BotMissingPermissions` and `commands.guild_only` are in the *rewrite branch* of discord.py.

It probably worked in your other PC because it had the rewrite version installed, but your current PC doesn't have it (probably discord.py 0.16.x or something), hence all the AttributeErrors.
