### ISSUE TITLE
How to find emojis in message

### ISSUE THREAD

**Issue by vertangelx** [Rapptz/discord.py#1136]
How can you extract the emoji in a message, assuming there is always one?

Because we want to echo that emoji back to the message.author, how can we get the emoji in the following formats:

 - `\U0001F44D`
 - `\N{THUMBS UP SIGN}`

For example:

    @client.event
    async def on_message(message):
	if 'my emoji is' in message.content.lower():
		print(message.content)
		await client.send_message(message.channel, 'Echoing emoji {0}'.format(message.content))

**Comment by TomsUsername** [comment]
regex or the emoji converter from the command ext

**Comment by Vexs** [comment]
The emoji converter only handles custom emojis, and regex is pointless overkill for this. 

If you want to just echo the emoji back to them, just echo it back, they're regular strings. Unless you mean send it back as a name/codepoint?

**Comment by vertangelx** [comment]
Echoing back the entire message including emoji works. However printing it out using `print` in Python prints out strange squares

![image](https://user-images.githubusercontent.com/8826684/37349427-c97aa82e-26ac-11e8-8748-870f4b889d12.png)

But how do we 
1. extract the emoji and just echo the emoji?
2. react to his message with the emoji in the message?

**Comment by Vexs** [comment]
Those "strange squares" means your font doesn't have support for those characters. As for sending them back as reactions, you just have to extract the characters and then just use client.add_reaction()
