### ISSUE TITLE
Serialization of a commands.Bot instance

### ISSUE THREAD

**Issue by Breee** [Rapptz/discord.py#1137]
Greetings, 

I'm building a discord-bot to create polls. 
Now the next step is to implement persistence, such that the bot does not "forget" created polls on restart. 

Which attributes of a commands.Bot object have to be serialized/saved, in order to ensure full functionality after a restart?  

-- Bree

**Comment by Rapptz** [comment]
You're probably better off storing the polls themselves rather than the entire Bot and its cache since it will be out of date the next time you boot.

**Comment by Breee** [comment]
Restoring my data structures  and self.messages (discord.Client)  won't do the trick, the bot will still not know the old messages. 

So probably you store some additional information about received messages, somewhere, i'll just go ahead and use a debugger to figure out the control flow I guess.
