### ISSUE TITLE
cannot change_nickname 

### ISSUE THREAD

**Issue by 12rambau** [Rapptz/discord.py#1139]
Hi, 
I try to use the `client.change_nickname(member, newNick)` but I receive systematically the same error whatever the privilege I give to the bot. I think that I cannot make more than
- [x] administrator

 member is a `member` and newNick is a `str`

See here the details of the error:
```shell
await client.change_nickname(member, newNick)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/client.py", line 1966
, in change_nickname
    yield from self.http.change_nickname(member.server.id, member.id, nickname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/http.py", line 196, i
n request
    raise Forbidden(r, data)
discord.errors.Forbidden: FORBIDDEN (status code: 403): Privilege is too low...
```

**Comment by davfsa** [comment]
Make sure the bots role is over the role of the person that you are trying to change (that should fix it)

**Comment by Ikusaba-san** [comment]
You're giving your bot "permissions" when you give it "administrator".

"privilege" usually refers to hierarchy, ie the member's top role is higher than your bots, or you're trying changing the server owner's nick.

**Comment by Rapptz** [comment]
You can't change the server owner's nickname nor someone's nickname if they have a role that is higher than yours.

**Comment by 12rambau** [comment]
In fact everything was working. I had just not realized that the owner was a god-like member ;-) 
I created another user and it worked just fine
Thx 😘
