### ISSUE TITLE
Example for get_all_members()

### ISSUE THREAD

**Issue by jzburda** [Rapptz/discord.py#114]
I don't understand how get_all_members() can be harnessed so it prints every username and ID for every member in the console. Could I get an example on it?

**Comment by khazhyk** [comment]
for member in get_all_members:
  print(member.name, member.id)

**Comment by jzburda** [comment]
Oh cool, thanks. There's very little documentation on Generators.

**Comment by khazhyk** [comment]
https://docs.python.org/3.5/tutorial/classes.html#generators

if you need a reference that whole page is pretty good

**Comment by sinancetinkaya** [comment]
I couldn't find "get_all_members" in your API docs, where is it?
