### ISSUE TITLE
Changing voice channel category

### ISSUE THREAD

**Issue by NIlmonas** [Rapptz/discord.py#1145]
Is there any way to change the category of a voice channel that already exists? Or set the category of the voice channel upon creation.

**Comment by diceroll123** [comment]
http://discordpy.readthedocs.io/en/rewrite/api.html#discord.Guild.create_voice_channel

You can pass a category as you create it.

**Comment by diceroll123** [comment]
Ah yes and http://discordpy.readthedocs.io/en/rewrite/api.html#discord.VoiceChannel.edit for changing category.

**Comment by NIlmonas** [comment]
Thanks!
