### ISSUE TITLE
Multiple webhook issues

### ISSUE THREAD

**Issue by pavlukivan** [Rapptz/discord.py#1150]
1. `'AsyncWebhookAdapter' object has no attribute 'http'`  when sending pictures (haven't tested with other media types, message still sends so I justs ignore it)

2. `BAD REQUEST (status code: 400): Cannot send an empty message` when sending a message (happens randomly, retrying helps)

I use `wait=True`

**Comment by pavlukivan** [comment]
the second one could be "Rate limited", in that case the description needs to be updated

**Comment by Rapptz** [comment]
This isn't how you post tracebacks.

The last line is useless without the rest of it.

#2 doesn't sound like something I can fix since the json is sent properly. Your secondary comment says something about rate limiting but I'm not sure what you're referring to. If you mean that you get rate limited, well that's normal and the script should ideally wait until you're not and retry for you.

Again, please improve this issue if you expect it to be actionable.

**Comment by pavlukivan** [comment]
alright
```cpp
  File "C:\Python35\lib\site-packages\discord\webhook.py", line 198, in handle_execution_response
    return Message(data=data, state=self, channel=self.webhook.channel)
  File "C:\Python35\lib\site-packages\discord\message.py", line 213, in __init__

    self._update(channel, data)
  File "C:\Python35\lib\site-packages\discord\message.py", line 272, in _update
    self._try_patch(data, 'attachments', lambda x: [Attachment(data=a, state=self._state) for a in x])
  File "C:\Python35\lib\site-packages\discord\message.py", line 227, in _try_patch
    setattr(self, key, transform(value))
  File "C:\Python35\lib\site-packages\discord\message.py", line 272, in <lambda>

    self._try_patch(data, 'attachments', lambda x: [Attachment(data=a, state=self._state) for a in x])
  File "C:\Python35\lib\site-packages\discord\message.py", line 272, in <listcomp>
    self._try_patch(data, 'attachments', lambda x: [Attachment(data=a, state=self._state) for a in x])
  File "C:\Python35\lib\site-packages\discord\message.py", line 72, in __init__
    self._http = state.http
AttributeError: 'AsyncWebhookAdapter' object has no attribute 'http'```

**Comment by pavlukivan** [comment]
also i had an issue where `channel.webhooks()` returned None, idk how to reproduce it though

**Comment by Rapptz** [comment]
This should be fixed.

I haven't gotten a repro on `channel.webhooks()` being `None` and I have not seen issue 2 mentioned in the months that this issue has been opened. However the attribute error was fixed.
