### ISSUE TITLE
message.embeds don't return discord.embed object

### ISSUE THREAD

**Issue by 12rambau** [Rapptz/discord.py#1151]
I quote the documentation :
`Message.embeds`
list – A list of embedded objects. The elements are objects that meet oEmbed’s specification.

`discord.Embed(**kwargs)`
Represents a Discord embed.
The following attributes can be set during creation of the object:
Certain properties return an `EmbedProxy`. Which is a type that acts similar to a regular dict except access the attributes via dotted access, e.g. `embed.author.icon_url`. If the attribute is invalid or `empty`, then a special sentinel value is returned, `Embed.Empty`.
For ease of use, all parameters that expect a str are implicitly casted to str for you.

The list of Message.embeds isn't a list of discord.Embed ? if not why ?

**Comment by Rapptz** [comment]
In v0.16.x they're not Embeds because it would be a breaking change for other people. In v1.0 they are converted into `discord.Embed` objects.

**Comment by 12rambau** [comment]
ok cool, I'll move to the v1.0 whenever I can then. because it's way much more convenient to use EmbedProxy 😄
