### ISSUE TITLE
Not enough permission?

### ISSUE THREAD

**Issue by FlamboyantFlamingo** [Rapptz/discord.py#1152]
Alright, so I'm trying to change the nickname of a user, but I'm having problems that I feel are _not_ with my code, but I might be wrong. I made a video that you can watch instead of me trying to describe the problem:

https://youtu.be/6IRbV7NyFAA

I put the bit of code for this on pastebin here:

https://pastebin.com/VT366ex3

**Comment by LewdNeko** [comment]
Youre probs gettin hierarchy'd mate

**Comment by FlamboyantFlamingo** [comment]
I wish, but the bot has admin. I tried putting it above the 'king' role, but that has nothing to do with it.

**Comment by jwshields** [comment]
Are you the owner the the guild?
If so, you can't do anything to have the bot edit your nickname/etc.
It's hierarchy.

**Comment by LewdNeko** [comment]
its hierarchy mate. try it on a different user / server

**Comment by Vexs** [comment]
Unrelated, but it's worth noting that's kind of an awful way to store "coins". Be better off with json and an in-memory dict, or do it properly and use a database like postgresql. It's worth knowing how to use [.format](https://pyformat.info/) as well.

**Comment by LewdNeko** [comment]
If you have given your bot permissions, but it is still giving you errors, you are getting 
`H I E R A R C H Y`'d
This means that your bot is lower on the role list than the person/role you are trying to edit, or your bot is trying to edit the server owner, which can't happen.

 A nice tag from the D.py server. You should join it cos youll get help faste. there should be a link in the readme to it

**Comment by FlamboyantFlamingo** [comment]
Thanks for the help! It should've been obvious that it's because I'm the server owner.
