### ISSUE TITLE
TypeError: set_image() missing 1 required positional argument: 'self' with set_image()

### ISSUE THREAD

**Issue by PwnKitteh** [Rapptz/discord.py#1153]
Hi @Rapptz 
Sorry for the noob question. This is a pretty sweet library, but I'm having an issue when trying to embed images. I want my bot to be able to post embedded images, which it gets from giphy. I query for the image url, and then pass it to `Image_URL`. I then try to post it. I have no problems when I just post the link, using send_message. Discord finds the file and inserts it. But I want to embed the image without sending the link in front of it. How do I do that?
```
await discord.Embed.set_image(url=Image_URL)
client.send_message(message.channel, Image)
```
I don't know how to do this, and the docs are kind of unclear. Do I need to use send_message in order to send the embedded gif, or does Embed.set_image already do that for me? When I try to run this code, I get the error `TypeError: set_image() missing 1 required positional argument: 'self'` on the first line I posted above. I honestly have no idea what I'm doing, and really appreciate your response. 
Thanks.

**Comment by Rapptz** [comment]
`discord.Embed` is a type. You need an instance, e.g. 
``py
embed = discord.Embed()
embed.set_image(url='...')
await client.send_message(message.channel, embed=embed)
```

Considering this is pretty basic Python knowledge I recommend reading a tutorial like the one here: https://python.swaroopch.com/oop.html
