### ISSUE TITLE
after does not work in guild.audit_logs

### ISSUE THREAD

**Issue by dustinpianalto** [Rapptz/discord.py#1157]
I am trying to get all the 'kick' audit logs since a specific time, I have tried using a datetime object and also a message object. In both instances it returns all of the audit logs that match the other arguments without regards to the 'after' argument. 'before', 'action' and 'limit' work just fine. Here is what I am trying to use.

```python
logs = await ctx.guild.audit_logs(after=await ctx.channel.get_message(<msg_id>), action=discord.AuditLogAction.kick).flatten()
```

I have also tried this.

```python
from datetime import datetime, timedelta
chk_time = datetime.utcnow() - timedelta(minutes=10)
logs = await ctx.guild.audit_logs(after=chk_time, action=discord.AuditLogAction.kick).flatten()
```

**Comment by Rapptz** [comment]
This is a discord bug. It requires Discord to fix it, I've been told by @jhgg that this will be fixed eventually but it's been a long time.

For now I would just not use `after` keyword argument.
