### ISSUE TITLE
How do I achieve permissions for downloading an attached image?

### ISSUE THREAD

**Issue by emctague** [Rapptz/discord.py#1158]
Currently, I am trying to download images like 

```py
url = message.attachments[0]['proxy_url']
urllib.request.urlretrieve(url, 'manip.png')
```

However, this is just giving a 403 forbidden error, as discord images seem to require being logged into an account on the guild.

Is there any tool in the library to retrieve images without permission issues? I can't find any documentation whatsoever for the attachments property.

**Comment by kittenswolf** [comment]
Try using requests with a common useragent.

**Comment by scragly** [comment]
good save, kittens

**Comment by Werseter** [comment]
You can also try using the bot's active connection.

`await bot.http._session.get('http://google.com')`
