### ISSUE TITLE
Implement Webhooks Update Event

### ISSUE THREAD

**Issue by EndenDragon** [Rapptz/discord.py#1159]
Since the rewrite's goal is to eventually encapsulate the whole Discord API in a wrapper, is it possible to implement Webhooks Update event? My bot currently utilize webhooks to function and I had to fork the lib in order to implement such event. https://github.com/Rapptz/discord.py/compare/rewrite...TitanEmbeds:3568f6dce704c521980bb2a6bf41d14565e92217
It would be cool if that event came default in the main discord.py rewrite.

**Comment by Harmon758** [comment]
This was added with https://github.com/Rapptz/discord.py/commit/17f9916b03eeb3d108913d8191a12156fd79ab85 and https://github.com/Rapptz/discord.py/commit/d092c6635b69335d0d6aa174868f0eca08c50fb5 (https://github.com/Rapptz/discord.py/pull/1403).
