### ISSUE TITLE
Non-Raw Reaction Events Non-Functional

### ISSUE THREAD

**Issue by AXAz0r** [Rapptz/discord.py#1162]
It seems that `discord.on_reaction_add(r, u)` and `..remove(r, u)` never get called, raw versions function.
Rewrite branch last pulled at 2018-03-24 21:10 GMT.

**Comment by Gorialis** [comment]
![image](https://user-images.githubusercontent.com/8049998/37870053-9e34cfbe-3007-11e8-8206-7541d86885f1.png)
No repro.

**Comment by Rapptz** [comment]
The messages being reacted need to be in the message cache to trigger.

This is not a bug and is documented.

If you have another instance of it not working then feel free to re-open the issue but this does not have enough information.
