### ISSUE TITLE
What to put under function "join_voice_channel"

### ISSUE THREAD

**Issue by TheUnbAnmAn** [Rapptz/discord.py#1165]
I'm not entirely sure what to put under the function "join_voice_channel". I've tried the channel id (using the copy id), the channel name (of many different channels), but it still says it isn't a voice channel.
![c0c688526bceea71bb6878a21a2ae79f](https://user-images.githubusercontent.com/28844824/37887541-2d783b74-3077-11e8-999c-24b7493440ea.png)
![96f31b734f6e7444d4d11f0be0c0d3a6](https://user-images.githubusercontent.com/28844824/37887542-32d0fcdc-3077-11e8-8abb-9c090677ff13.png)

**Comment by Vexs** [comment]
If you'll note from the docs, [it takes in an instance of discord.Channel,](http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.join_voice_channel) not a string. There are some examples on the github, playlist.py is relevant to you. https://github.com/Rapptz/discord.py/blob/async/examples/playlist.py
