### ISSUE TITLE
Messages not detected from users with Emojis in their Usernames

### ISSUE THREAD

**Issue by RobertRiachi** [Rapptz/discord.py#1167]
Was working with Discord.py, and it seems to not detect user messages in channels when the user has an emoji in their username, but still works when they have one in their nickname.

**Comment by Vexs** [comment]
No repro.
Probably some issue in your code; you could put it in a gist so we could investigate further, but not much else to be done here.

**Comment by Rapptz** [comment]
This is simply not true.

Probably an issue with your code.
