### ISSUE TITLE
Add a way to invite other bots to a server and determine whether a user is on a mobile device or a PC.61

### ISSUE THREAD

**Issue by LaughOutQuiet** [Rapptz/discord.py#1168]
Hi, I've been experimenting with discord.py for a while now and I believe it'd be pretty cool to have a way to determine whether an online user is using a mobile device or a computer, also, adding a way for bots to invite other bots by giving an invitation link as input would be very cool and would open a lot of new doors.

**Comment by Vexs** [comment]
None of this is something the lib(discord.py) can implement, the lib can only use information the Discord API provides. If it doesn't, it can't. 
[Discord, however, has a feedback page.](https://feedback.discordapp.com/forums/326712-discord-dream-land)

As a note, bots inviting bots is right out. They've already taken a number of actions to prevent this.
