### ISSUE TITLE
Retrieving the last embed image?

### ISSUE THREAD

**Issue by nekusata** [Rapptz/discord.py#1169]
I am trying to add a feature to my bot where it would retrieve the last image posted and apply a filter to it. I know how make it apply the filter; but how do I retrieve the last embed image to be posted? I believe I have to use ``message.embed`` ; I'm just not sure how.

Apologies if my question is silly.

**Comment by Vexs** [comment]
message.embeds contains embeds- eg, the "boxes" that pop up for some urls, as well as the images that pop up for image urls. 
message.attachments contains a list of attachments for a message- the files a user uploads to discord, be they text files, or images. 

Depending if you're on the rewrite or async branch of the lib (if you don't know what the rewrite branch is, you don't have it) attachments/embeds will be a list of dicts(async) or a list of embed/attachment objects(rewrite). Another note, if you want to check if an attachment is an image, you can look for the `width` attribute/key. 

If you want to do something with the image, you have to first fetch the url (look over message.embeds/message.attachments) and then download it with aiohttp. Further implementation is up to you, but we have an example of working with pil [here](https://gist.github.com/Gorialis/e89482310d74a90a946b44cf34009e88). Mind you, this is for the rewrite branch of the lib, but the core tenants remain the same.

**Comment by nekusata** [comment]
@Vexs I see, thank you.
