### ISSUE TITLE
Cannot Upload a ZIP File

### ISSUE THREAD

**Issue by IngeniousCoder** [Rapptz/discord.py#1170]
I did this code:
`zipf = zipfile.ZipFile('upload.zip', 'w', zipfile.ZIP_DEFLATED)
  zipdir('Uploads/', zipf)
  
  await bot.send_file(discord.Object(id="428143395320365067"),fp=zipf,filename="upload.zip", content=None, tts=False)`

It resulted in this error: "
![image](https://user-images.githubusercontent.com/29097583/37963414-c19faa74-31f0-11e8-87df-a38702b955bb.png)

Can anyone help?

**Comment by nosklo** [comment]
You have to open it as normal file
```
with open('upload.zip', 'rb') as f:
    await bot.send_file(discord.Object(id="428143395320365067"),fp=f,filename="upload.zip", content=None, tts=False)
```

**Comment by Vexs** [comment]
@nosklo's answer isn't correct- not only do you still need to close the zipfile object, but the `fp` kwarg accepts a file location, so you could just give it the filename string to start with. Plus, you can just use a bytesio to handle this all in memory, not invoking the slow hdd, as shown below.

`zipdir()` is the function from [this stackoverflow](https://stackoverflow.com/questions/1855095/how-to-create-a-zip-archive-of-a-directory) correct? Doesn't matter much, just clears up what you're trying to do. 

Either way, the correct way to do this is:
```py
b = io.BytesIO()
zipf = zipfile.ZipFile(b, mode="w"....etc)
zipdir('Uploads/', zipf)
zipf.close()
b.seek(0)

await bot.send_file(channel, fp=b, filename="upload.zip.....etc)```

It's worth noting that you might want to do this in an executor, to prevent blocking up the event loop.

**Comment by eltontay11** [comment]
It worked after I just placed fp as the file directory. However, the uploaded zip file, when downloaded, is always corrupt. Any idea on a fix?

**Comment by Vexs** [comment]
Please re-read the rest of my comment. Not only have I laid out the correct way to do it, I wrote the code for you.

**Comment by eltontay11** [comment]
What do you mean by executor?

**Comment by Harmon758** [comment]
@Vexs is referring to [`Executor objects in concurrent.futures`](https://docs.python.org/3/library/concurrent.futures.html#executor-objects), which you can use with [`asyncio.loop.run_in_executor`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor).

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.
