### ISSUE TITLE
[FR] Case insensitive command prefixes

### ISSUE THREAD

**Issue by MrDini123** [Rapptz/discord.py#1172]
Hi,

I couldn't found any easy way/workaround to achieve case insensitive prefixes using the current d.py rewrite branch, and I think it'd be a useful feature such as the case insensitive commands.

Please consider adding it.

**Comment by Rapptz** [comment]
There is already a callable prefix which you can use to permutate all possible cases of your prefixes. So there's no reason to implement this on my end since you can easily implement it yourself.

**Comment by MrDini123** [comment]
Yes, but AFAIK I Cannot get the used prefix inside the callable prefix function. And if I have a prefix like `prefix$` there are a lot of possibilities to include inside a list now (64 in this case).

**Comment by Rapptz** [comment]
It's not hard to create those permutations programmatically so I don't know what to tell you. The way the prefix function works makes it impossible to do this any other way.

**Comment by MrDini123** [comment]
A but off, but Can I convert the user's message to lowercase inside the on_message event, before calling process_commands?

**Comment by Rapptz** [comment]
That'd create a lot more issues than it'd solve. If you want to do that in the prefix function go ahead though.
