### ISSUE TITLE
seek

### ISSUE THREAD

**Issue by Gunner-Bones** [Rapptz/discord.py#1174]
Hello,
Is there a way for seeking with StreamPlayers? Like jumping to certain parts while playing audio, because there is no support for seek methods or even what the current time pos is, etc
Someone suggested seeking with ffmpeg, but that's for mp4 or movie files, not Stream objects.
Does anyone know a fix?
Thanks

**Comment by imayhaveborkedit** [comment]
There's no good way to, besides reading and discarding input to "seek" forwards.  Whatever math you need to do to figure out how much to discard is up to you though.

**Comment by LouisGerard** [comment]
```py
voice_client.play(source)
voice_client._player._start = start
```
