### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by PLOliwier** [Rapptz/discord.py#1178]
`    async def update_now_playing_status(self, entry=None, is_paused=False):
        game = None

        if self.user.bot:
            activeplayers = sum(1 for p in self.players.values() if p.is_playing)
            if activeplayers > 1:
                game = discord.Game(name="massage" % activeplayers)
                entry = None

            elif activeplayers == 1:
                player = discord.utils.get(self.players.values(), is_playing=True)
                entry = player.current_entry

        if entry:
            prefix = u'\u275A\u275A ' if is_paused else ''

            name = u'{}{}'.format(prefix, entry.title)[:128]
            game = discord.Game(name=name)

        async with self.aiolocks[_func_()]:
            if game != self.last_status:
                await self.change_presence(game=game)
                self.last_status = game`

I would like to have my own message and not the title of the song

**Comment by Modelmat** [comment]
This is not the place for this kind of help, please ask in the discord.py discord server https://discord.gg/r3sSKJJ

**Comment by excorpsexd** [comment]
```
await client.change_presence(game = discord.Game(
    name = 'game'
))
```
