### ISSUE TITLE
@bot.event error

### ISSUE THREAD

**Issue by JennyDiscord** [Rapptz/discord.py#1179]
C:\Users\helga>python jenny.py
Traceback (most recent call last):
  File "jenny.py", line 9, in <module>
    @bot.event
  File "C:\Users\helga\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 873, in event
    raise ClientException('event registered must be a coroutine function')
discord.errors.ClientException: event registered must be a coroutine function
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000022579491400>

**Comment by ryanhampton** [comment]
Is your event, in fact, a coroutine?

**Comment by Gorialis** [comment]
This error is self-explanatory. Make sure you [know what a coroutine is](http://discordpy.readthedocs.io/en/latest/faq.html#what-is-a-coroutine) and consider checking out the [examples](https://github.com/Rapptz/discord.py/tree/async/examples) for how a bot script should look.
