### ISSUE TITLE
How to count the reactions? Please help me

### ISSUE THREAD

**Issue by Rettend** [Rapptz/discord.py#1181]
I tried to make the `poll` command better, so after 12 hours the Bot will count the reactions and send a message of the result. Here is my code:
`if message.content.upper().startswith('POLL'):
        msg = await client.send_message(message.channel, "**A Poll has started! 12 hour remaining**")

        def check(reaction, user):
            e = str(reaction.emoji)
            return e.startswith(("\U0001F44D",  "\U0001F44E"))
        react_count1 = 0
        react_count2 = 0
        await client.add_reaction(msg, "\U0001F44D")
        await client.add_reaction(msg, "\U0001F44E")
        res1 = await client.wait_for_reaction(emoji="\U0001F44D", message=msg, check=check)
        res2 = await client.wait_for_reaction(emoji="\U0001F44E", message=msg, check=check)
        while res1:
            react_count1 =+ 1
        while res2:
            react_count2 =+ 1
        asyncio.sleep(3) #It will be 42300 secs
        if react_count1 >= react_count2:
            await client.send_message(message.channel, "**Poll ended, the Result: __Yes__**")
        if react_count1 < react_count2:
            await client.send_message(message.channel, "**Poll ended, the Result: __Nop__**")`

The Bot adds the reactions but than nothing happens...
I dont know what to do.

**Comment by Modelmat** [comment]
This is not the place for this kind of help, please ask in the discord.py discord server https://discord.gg/r3sSKJJ
