### ISSUE TITLE
this library can be used without events?

### ISSUE THREAD

**Issue by katmai1** [Rapptz/discord.py#1186]
Hi,
I doing a script and I want that result send to a channel of discord.
I want only send message and close connection, is possible use client.send_message() without use the loop and his events?
thanks

**Comment by Vexs** [comment]
You want a webhook, not a bot. Rewrite branch has support for these, [or you could just do the requests yourself, which is quite easy. ](https://discordapp.com/developers/docs/resources/webhook)

**Comment by katmai1** [comment]
ok! thanks for info
