### ISSUE TITLE
How to make case insensitive commands

### ISSUE THREAD

**Issue by SlenderDoge** [Rapptz/discord.py#1188]
I'm new to discord.py and have looked through the documentation, but I can't seem to figure out how to use the case_insensitive option. I know that there has already been a post on this, about a year ago, but as I've said, I found a "case_insensitive option" for commands in the API Reference -> Bot section and just can't get it to work. So far I've tried this:

```python
from discord.ext import commands

bot = commands.Bot(command_prefix="!", case_insensitive=True)
```

Any help would be appreciated.

**Comment by SlenderDoge** [comment]
How do I use the rewrite branch?

**Comment by JennyDiscord** [comment]
import discord
from discord.ext import commands
from discord.ext.commands import Bot

**Comment by johann-lau** [comment]
```py
@bot.event
async def on_message(message):
  partitioned = message.partition(" ")
  await bot.process_commands(partitioned[0].lower()+" "+partitioned[2])
```
