### ISSUE TITLE
Is there a way to send an @user messages (the ones that beep and show up highlighted)

### ISSUE THREAD

**Issue by dburr** [Rapptz/discord.py#119]
In Discord you can address a public message to a specific user by prefixing it with "@username", this causes the user's client to notify them (if they have notifications enabled) and the message shows up highlighted. Can I send a message using `send_message()` and have it alert the user in this way? I can send a message prefixed with @everyone (e.g. "@everyone testing 1 2 3") then it does this, however if I try sending a message with a valid username ("@SomeValidUsername testing 1 2 3") it just sends the message without any notification, highlighting, etc. Am I doing something wrong or is this not yet a supported feature?

**Comment by Rapptz** [comment]
If you read the docs (which you should), you would know that `Member.mention` would do what you ask for. It's even in the examples.

**Comment by imayhaveborkedit** [comment]
Docs: http://discordpy.readthedocs.org/en/latest/api.html#discord.User.mention
Example: https://github.com/Rapptz/discord.py/blob/async/examples/reply.py#L12

**Comment by FroggoBoi** [comment]
How about an example that doesn't message back the author.

**Comment by Harmon758** [comment]
Please don't necrobump issues.
`User.mention` can be used with any `User` object.
For further help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README also links.
