### ISSUE TITLE
<rewrite> Cannot set prefix as none

### ISSUE THREAD

**Issue by XtremeCoder1384** [Rapptz/discord.py#1191]
When i set bot = commands.Bot(command_prefix="",description=""),
I get an error stating prefix cannot be empty. Is there any way to make the prefix NONE

**Comment by Modelmat** [comment]
Why would you want this? The bot is designed to be used. However, if you want the bot to be only mentioned, use `commands.when_mentioned`

**Comment by Rapptz** [comment]
No there is no way to set an empty prefix.. This is by design.
