### ISSUE TITLE
AttributeError: 'str' object has no attribute 'mention'

### ISSUE THREAD

**Issue by SlenderDoge** [Rapptz/discord.py#1194]
How can I call an attribute that is part of the discord.Role class, so that I can do (in this case using the string variable containing the role called admin_role) admin_role.id, or admin_role.mention? Basically, I need it to act as the variable "role" in:
```python
async def adminrole(ctx, role: discord.Role=None):
```
Here is that part of the code:
```python
@bot.command(pass_context=True)
async def adminrole(ctx, role: discord.Role=None):

	#Gives information about the already assigned admin role
	if (role == None):
		filenotfound = False
		try:
			open(os.path.join(adminroles_path,((str(ctx.message.author.server.id)) + ("_adminrole.bot"))), "rb")
		except FileNotFoundError:
			await bot.say("You haven't assigned an admin role yet!")
			filenotfound = True
		if (filenotfound == False):
			with open(os.path.join(adminroles_path,((str(ctx.message.author.server.id)) + ("_adminrole.bot"))), "rb") as f:
				admin_role = (str(pickle.load(f))) #Loads the admin role name from the file corresponding to that server
			print (admin_role)
			await bot.say("The current admin role is " + str(admin_role.mention)) #error occurs here
```

**Comment by JellyWX** [comment]
`admin_role` is a string and it needs to be evaluated to a Role object either using `utils.get` or other method. The issues section should really be reserved for issues with the API, I recommend taking your error to somewhere like the official discord.py server or another Discord.py help server
