### ISSUE TITLE
authentication to discord

### ISSUE THREAD

**Issue by dave7280** [Rapptz/discord.py#1195]
where in this library is some information how to authenticate before even using it?
i'm checking examples but there's nothing about authentication, not or git page....

**Comment by colcrunch** [comment]
http://discordpy.readthedocs.io/en/rewrite/discord.html

**Comment by XtremeCoder1384** [comment]
1. Are you using ASYNC or Rewrite
2. Please Read the docs. https://discordpy.rtfd.io

**Comment by Vexs** [comment]
As you haven't really gotten a good answer yet, put bluntly, we have no idea what you're asking for.  What exactly are you talking about regarding "authentication"?

**Comment by dave7280** [comment]
Hello again,

Sorry for missleading question. I was really confused, the entire library looks very good but i had really hard time how to perform authentication to discord server - i mean using this so called token.
How to find it, where to put it.

At the end i managed to create new app using discord panel and get a key from there.. but there should be quick 5 point tutorial for this. Especially since i had no experience with discord but had to implement a notification using it.

**Comment by dave7280** [comment]
Also the library focuses a lot on so called full-time bots. It was quite difficult to find information how to perform simple log-in and send message task... then quit. Finally i made it, but quite confusing for such simple tasks using these coroutines.

**Comment by Vexs** [comment]
Bot accounts aren't really for logging in and sending a single message, as you get a limited number of connects/day. It's also quite a lot of information to send/receive just for a single message. If you want that functionality, use webhooks instead, [defined in the docs here](https://discordapp.com/developers/docs/resources/webhook). Webhooks are supported on the rewrite branch of the lib, but it's trivial to post them yourself.

It's generally assumed that you have some knowledge of how discord bots work, [but the process for creating a bot account is documented on the development branch.](http://discordpy.readthedocs.io/en/rewrite/discord.html) Furthermore, the [examples](https://github.com/Rapptz/discord.py/tree/async/examples) serve as a more than sufficient, well, example for just a basic bot.

**Comment by dave7280** [comment]
Do you know what the estimated limit is for number of connects per-day?

**Comment by XtremeCoder1384** [comment]
I’m quite sure it’s infinite

**Comment by TomsUsername** [comment]
2000 gateway conns. per 24hrs they reset your token if more ,  you don't need a lib for what you want, refer to the Discord doc's you can achieve what you want with a simple post request.

**Comment by Vexs** [comment]
All of the above is incorrect. [You are limited to 1000 `identify` calls within a 24 hour period, across all shards.](https://discordapp.com/developers/docs/topics/gateway#identifying) Bots with more than 100k servers receive a higher limit, but I'm unsure what it is. 

Again, connecting a bot to discord transfers quite a lot of information. Members, servers, emojis, all that jazz. I highly recommend that you just use a webhook if you're intending to stay within one channel, as it involves none of the above restrictions, doesn't require a lib, coros, or anything, just a single, basic POST request.

**Comment by XtremeCoder1384** [comment]
I would also like to check, what is a identify call?

Does things like creating channels count? As my bot has a create channel command.
