### ISSUE TITLE
Suggestion: add __weakref__ slot

### ISSUE THREAD

**Issue by spectras** [Rapptz/discord.py#1196]
Hello,

I am using `rewrite` branch, it's working great. I just found that most of `discord.py` types have a `__slots__` attribute. So far so good, however it doesn't have a `__weakref__` entry. This means this code fails:

```python
_event_buses = weakref.WeakKeyDictionary()

def bus(guild):
    global _event_buses
    try:
        obj = _event_buses[key]
    except KeyError:
        _event_buses[key] = obj = MessageBus()
    return obj
```
> TypeError: cannot create weak reference to 'Guild' object

Granted, I could use a regular dictionary and add event handlers to manually delete entries, but it feels inelegant. How about adding the `__weakref__` entry to objects that might be worth caching stuff for? `Guild`, `User`, `Member`, perhaps the `*Channel` class family.

**Comment by Rapptz** [comment]
I only really add `__weakref__` to things that I personally need for the library to function since it adds memory overhead (which is why I'm using `__slots__` in the first place).

`User` already has a `__weakref__` attribute e.g. because I need it for the lib to function.

**Comment by spectras** [comment]
Too bad but fair enough, I guess I'll have to handle lifetime manually by responding to events.

About `User` then, is the weakref attribute part of the official API and I can rely on it being present, or should I take it as an implementation detail that could be gone in next version and I should use events as well?

**Comment by Rapptz** [comment]
I have no plans to remove it since it affects other official parts of the API such as e.g. `get_user` and friends.

**Comment by spectras** [comment]
Thanks for the fast answers, keep up the good work ^^
