### ISSUE TITLE
Add option to get a user/channel from name or ID

### ISSUE THREAD

**Issue by SpinahVieh** [Rapptz/discord.py#12]
Right now you always have to wait for a channel or user to be active in some way, which results in problems. For example when you want the bot to type regularly in a specific channel you always need to grab it from someone typing in it first. So you cant make the bot post a text every five minutes in the channel unless somebody types in that channel before. Equal for users, but the problem is rather minor there.

**Comment by Rapptz** [comment]
There's `Client.get_channel` which you pass in a string ID and you get the channel.

For users you can use `discord.utils.find`.
