### ISSUE TITLE
How to edit profile in-place

### ISSUE THREAD

**Issue by shrx** [Rapptz/discord.py#120]
The comment in `edit_profile` function says that 
>         The profile is **not** edited in place.

When does the edit happen?
Is it possible to perform the edit immediately on function call?

**Comment by berler** [comment]
I think you are misunderstanding the documentation. The edit does happen immediately (as in it does send the edit to the server). Just not all of the effects of the edit will be reflected immediately when the function returns.  For example if you edit your username, immediately after calling the function, `client.user.name` will still have the old username.  If you wait a short time (once the `user_update` message gets received on the websocket), then `client.user.name` will now be correct.

**Comment by shrx** [comment]
Ah, ok, thanks for the explanation.
