### ISSUE TITLE
create_custom_emoji does not note the "roles" parameters

### ISSUE THREAD

**Issue by AtomToast** [Rapptz/discord.py#1201]
I just saw that "create guild emoji" actually takes "roles" as a parameter.
https://discordapp.com/developers/docs/resources/emoji#create-guild-emoji
The description reads "roles for which this emoji will be whitelisted"
This paramater is also visible in the discord.log, though empty.

Because this parameter seems to be not supported in discord.py? 
http://rapptz.github.io/discord.py/docs/api.html#discord.Guild.create_custom_emoji

**Comment by Harmon758** [comment]
This was resolved with https://github.com/Rapptz/discord.py/commit/0e6082c57d9139dbba6e998c147b34cae5018e78 (https://github.com/Rapptz/discord.py/pull/1436).
