### ISSUE TITLE
move_channel coroutine doesn't work

### ISSUE THREAD

**Issue by DanielVip3** [Rapptz/discord.py#1206]
I already found that issue on the github, but it was labeled as 'stale'. I don't know if stale means that you would fix it, there's already a solution or that there will be no solution.
Anyway, that was my first code : 

```
@bot.command(pass_context=True)
async def maketext(ctx, name):
    channel = await bot.create_channel(ctx.message.server, name, type=discord.ChannelType.text)
    await asyncio.sleep(5)
    await bot.move_channel(channel, 22)
```
But it didn't work. Then I added an event in the command, to try if it can fix the issue :
```
@bot.command(pass_context=True)
async def maketext(ctx, name):
    channel = await bot.create_channel(ctx.message.server, name, type=discord.ChannelType.text)
    await asyncio.sleep(5)
    
    @bot.event
    async def on_socket_raw_receive(msg):
        await bot.move_channel(channel, 22)
        print ('Did it.')
```
Nothing to do, the code doesn't work.
There isn't any error. 
The channel is created, then the Shell prints out 'Did it.' but doesn't move the channel.
Thank you for even considering that issue, even if it has already been reported.
I don't know if reporting an issue labeled as 'stale' is a bad thing, so if so, I'm sorry.
Also, eventually, sorry for my bad english.

**Comment by DanielVip3** [comment]
I fixed it by updating to the rewrite version.
For anyone that wants to do that, should install this : 
py -m pip install -U https://github.com/Rapptz/discord.py/archive/rewrite.zip
It can be unstable, but it's the version that contains categories and other new things that can be useful and that aren't in the old version. Also, I think that's more easy to use too.

**Comment by Gorialis** [comment]
It's not recommended to install rewrite through the archive as this means it cannot get the correct commit number & hash for the version string. In situations where we might require your version of rewrite, we won't be able to help you without these details.

It is recommended instead to install git and use the following:
```sh
pip install -U git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]
```

**Comment by DanielVip3** [comment]
Thank you for your explication.
