### ISSUE TITLE
Add Channel To Category

### ISSUE THREAD

**Issue by jatinluthra14** [Rapptz/discord.py#1208]
While using discord.client.create_channel, 
How can I add all roles to the new channel?

**Comment by Vexs** [comment]
There is an example of this for a single role [in the docs,](http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.create_channel) I've taken the liberty of posting it below as well. To do it for all roles is a simple iteration over `server.roles`.

```py
everyone_perms = discord.PermissionOverwrite(read_messages=False)
my_perms = discord.PermissionOverwrite(read_messages=True)

everyone = discord.ChannelPermissions(target=server.default_role, overwrite=everyone_perms)
mine = discord.ChannelPermissions(target=server.me, overwrite=my_perms)
await client.create_channel(server, 'secret', everyone, mine)
```

**Comment by jatinluthra14** [comment]
@Vexs I tried The iteration but it is not working. Above example has only for bot and @everyone role.

**Comment by jatinluthra14** [comment]
Anyone?

**Comment by BlackSynder** [comment]
This place is for issues regarding the library. Questions like this one are easier to answer on [The discord server](https://discord.gg/r3sSKJJ).

**Comment by jatinluthra14** [comment]
Now the thing is changed
The Question is how to add a channel to category.
Got a "No Way" from Discord Server of discord.py

**Comment by BlackSynder** [comment]
Doesn't change the fact that this isn't the place to look for this kind of help.

**Comment by Vexs** [comment]
The async (0.16.x) branch has no support for channel categories. In short: "No Way"

**Comment by edraft** [comment]
Hello, you can find Categories with:
`    for c in s.channels:
        if c.type == 4:
            if c.name == '•☆• -- V.I.P. -- •☆•':
                print('FOUND')
                print(c.name, c.type, c.position, c.is_private)
                ' here you can use the channel with c.`

**Comment by Harmon758** [comment]
@jatinluthra14 You can set the target to any role or user. Those are just examples.
As for category channels, they are fully supported on the rewrite branch as [`CategoryChannel`](https://discordpy.readthedocs.io/en/rewrite/api.html#categorychannel)s.
