### ISSUE TITLE
Troubles with bot status discord.py

### ISSUE THREAD

**Issue by manzholmgren** [Rapptz/discord.py#1212]
This is my coding:

import discord
from discord.ext import commands
from discord.voice_client import VoiceClient
import asyncio
import time

client = discord.Client()

startup_extensions = ["Music"]
bot = commands.Bot("?")

@bot.event
async def on_ready():
    print("bot started")

class Main_Commands():
        def __init__(self, bot):
         self.bot = bot

if __name__ == "__main__":
    for extension in startup_extensions:
        try:
            bot.load_extension(extension)
        except Exception as e:
            exc = '{}: {}'.format(type(e).__name__, e)
            print('Failed to load extension {}\n{}'.format(extension, exc))

@bot.event
async def on_ready():
    await client.change_status(game=discord.Game(name='whatever'))

I want to change the status of my bot but how?? The last snippet is my attempt. Im new to python plz help...

**Comment by excorpsexd** [comment]
@client.event
async def on_ready():
    await client.change_presence(game = discord.Game(
        name = 'game name'
    ))
