### ISSUE TITLE
Embed object properties do not have a setter

### ISSUE THREAD

**Issue by Douile** [Rapptz/discord.py#1213]
The embed object's properties [video](https://discordapp.com/developers/docs/resources/channel#embed-object-embed-video-structure) and [provider](https://discordapp.com/developers/docs/resources/channel#embed-object-embed-provider-structure) do not have a function allowing the user to set their value.

https://github.com/Rapptz/discord.py/blob/1863a1c6636f53592519320a173ec9573c090c0b/discord/embeds.py#L270-L292

I would assume they would have one like the image property,

https://github.com/Rapptz/discord.py/blob/1863a1c6636f53592519320a173ec9573c090c0b/discord/embeds.py#L219-L235

Not sure if you intended it to be like this. For now I'm just gonna add it in my [own version](https://github.com/Douile/discord.py).

Here's how I created the set function.
https://github.com/Douile/discord.py/blob/5f80dbf191783a47e919187b987d367eafdf6f37/discord/embeds.py#L284-L299

**Comment by Gorialis** [comment]
These are not settable values. `provider` indicates the website the embed came from (you are not a website) and `video` is only available on a per-case basis in automatically generated embeds from websites (ditto here).

**Comment by Harmon758** [comment]
The relevant Discord Developer Documentation:
"For the embed object, you can set every field except `type` (it will be `rich` regardless of if you try to set it), `provider`, `video`, and any `height`, `width`, or `proxy_url` values for images."
https://discordapp.com/developers/docs/resources/channel#create-message-params

**Comment by Rapptz** [comment]
As said, by design.

**Comment by Douile** [comment]
Oh thought those rules only applied to webhooks
