### ISSUE TITLE
792 limit

### ISSUE THREAD

**Issue by EpicShardGamingYT** [Rapptz/discord.py#1216]
im tryna load all members of every server the bot is in and it, for some reason it stops working at 792???
code: 

       ```
 args = message.content.upper().split(' ')
        ntmp = []
        print("Loading!")
        if args[2] == 'PLAYERS':
            for i in client.servers:
                for x in i.members:
                    print("test")
                    if x in ntmp:
                        pass
                    else:
                        ntmp.append(x)
            Players = ntmp
            await client.send_message(message.channel, "Loaded all Players!")
```

**Comment by scragly** [comment]
For general help on using the lib, it's usually best to pop into the [official discord.py support server](https://discord.gg/r3sSKJJ). Github tickets really should be for bugs, problems with code, api coverage or feature enhancements specifically to do with the code of the library. 

When you ask for help, don't forget to include info like:

- What python version are you using
- What discord.py version are you using
- What platform are you on

This helps us give more accurate advice and can sometimes help narrow down the cause of some issues that might come up.

Looking at your code, there's a few things you could improve, but there's nothing specific that seems to be jumping out as to why it's stopping at a certain number of members other than perhaps that's all the members there are. You haven't actually told us enough info to help further:

- Did you check if the loop has completed by perhaps doing a `print` before `Players = ntmp`, as if your only symptom of an issue is "It's not sending the last message", it's not enough to actually see if it's ending the loop and failing on Players, or if the loop is where the failure is.
- If it's failing in the loop, is it always a specific member.
- Is there any error traceback or is it just silent.

There's additional improvements on your code you can make also:
- You should look into [client.get_all_members()](http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.get_all_members) as it's getting the full member list already for you in an easy to use generator.
- If you're just adding members into the list `ntmp` that aren't already there, you can instead make `ntmp` a `set` and update the set with the data from get_all_members:
```py
# ntmp is a set
all_members = list(client.get_all_members())
ntmp.update(all_members)
```
- I see you're attempting to parse your own args, so it might be worth looking into the commands extension for discord.py. It's already in your lib, and allows you to more easily create commands and parse the arguments, including automatic type conversions, such a discord objects like member, etc. Lots of bonus' with it, and people will be willing to tell you more in the support server. [Here's an example basic bot using the commands extension](https://github.com/Rapptz/discord.py/blob/async/examples/basic_bot.py).

For this specific issue though, if you can do some more detailed troubleshooting and error details, and then pop into the discord.py support server to follow-up, we might be able to help a bit more.

**Comment by EpicShardGamingYT** [comment]
I already use the commands exstention, but switches between them, thx 4 making it work ;)
