### ISSUE TITLE
case insensitive commands are not removed when unloading the cog

### ISSUE THREAD

**Issue by AEnterprise** [Rapptz/discord.py#1217]
when using a bot with `case_insensitive=True` and unloading a cog that includes a command with a capital letter in it's name (for example setStatus), the command will not be removed when the cog is unloaded

if i rename the command function to `setstatus` the command is removed when unloading the cog and i can reload it again at runtime

**Comment by Harmon758** [comment]
This was fixed with https://github.com/Rapptz/discord.py/commit/bf9ca405e333cb3b6c6a54a224d55bf30587700d.

**Comment by AEnterprise** [comment]
yeah this is no longer an issue, thanks for fixing that 👍
