### ISSUE TITLE
i get a random error when i run my bot?

### ISSUE THREAD

**Issue by EpicShardGamingYT** [Rapptz/discord.py#1220]
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x06947670>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x06947830>
[Finished in 0.4s]

**Comment by LyricLy** [comment]
This is simply a notice, not an error.

**Comment by EpicShardGamingYT** [comment]
@LyricLy the bot crashes isntantly thou

**Comment by EpicShardGamingYT** [comment]
@LyricLy shall i restart pc or

**Comment by Rapptz** [comment]
This means you're not running the bot.

Next time you open an issue attach code so you can actually get help. As-is this issue is not actionable.

Please read the examples before opening an issue here too.
