### ISSUE TITLE
AttributeError: 'str' object has no attribute '_members'

### ISSUE THREAD

**Issue by glyphs** [Rapptz/discord.py#1222]
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "dra.py", line 100, in on_message
    u = discord.Server.get_member("432828245331804170","Jack#8374")
  File "/usr/lib/python3.6/site-packages/discord/server.py", line 143, in get_member
    return self._members.get(user_id)
AttributeError: 'str' object has no attribute '_members'

I'm trying to run 
discord.Server.get_member("432828245331804170",user)

(user is a correct username)

**Comment by SourSpoon** [comment]
server.get_member() only takes 1 arg, the string ID of said member you are looking for.

Server also has to be a instance of discord.Server, the library gives you methods of getting this.

In future questions like this are better suited to the discord server found here:
https://discord.gg/r3sSKJJ

**Comment by glyphs** [comment]
No

If I use one argument I get this:

```Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "dra.py", line 100, in on_message
    u = discord.Server.get_member(i)
TypeError: get_member() missing 1 required positional argument: 'user_id'

**Comment by mental32** [comment]
You need an instance of the discord.Server not the class itself, the instance is provided by the library mainly through context

**Comment by glyphs** [comment]
How do I start the instance

**Comment by mental32** [comment]
Again you don't start anything. The library handles this for you, you can use `discord.utils.get(client.servers, id=someid)` to search for the server in the clients internal cache, the example uses id.

**Comment by SourSpoon** [comment]
These questions are better suited to the d.py discord server found here:
https://discord.gg/r3sSKJJ

**Comment by Rapptz** [comment]
You should honestly learn some Python before even attempting to use this library.

Some resources:

https://automatetheboringstuff.com/ (for complete beginners to programming)
https://learnxinyminutes.com/docs/python3/ (for people who know programming already)
https://docs.python.org/3.5/tutorial/ (official tutorial)
http://python.swaroopch.com/ (useful book)
see also: http://www.codeabbey.com/ (exercises for beginners)
