### ISSUE TITLE
client.change_presence Not working

### ISSUE THREAD

**Issue by MuFFyy** [Rapptz/discord.py#1224]
Hi im trying to set game state with the following.
    if message.content.startswith('!!!game'):
        await client.change_presence(game=discord.Game('Test'))

When I type !!!game in discord it throws this error.
 File "zDBOT.py", line 21, in on_message
    await client.change_presence(game=discord.Game("with your mum"))
TypeError: __init__() takes 1 positional argument but 2 were given

Any help would be appreciated.

**Comment by Vexs** [comment]
it's 
`discord.Game(name="x")` not `discord.Game("x")`

**Comment by MuFFyy** [comment]
Thanks, that was quite obvious.

**Comment by fourjr** [comment]
Can this issue be  closed?

**Comment by MuFFyy** [comment]
Yes. Thank you
