### ISSUE TITLE
bot.say Issues

### ISSUE THREAD

**Issue by jamzs2** [Rapptz/discord.py#1225]
Hello, I'm trying to experiment with some sort of XP system with a bot, where members will gain an amount of XP at random for every message they send, and for testing purposes, I'm trying to get it to tell me the amount of XP that is generated. Here's my code:

```
@bot.event
async def on_message(message):
    xpGain = random.randint(0,3)
    print(xpGain)
    await bot.say(message.channel,xpGain)
```

I've tried adding `await bot.process_commands(message)` to the end of my function which is the only possible remedy I found online, but regardless I still receive the same error message:

`TypeError: send_message() takes from 2 to 3 positional arguments but 4 were given`

I can't quite understand it because from what I can see, I'm only giving 2 arguments, `message.channel` and `xpGain`, so any help would be greatly appreciated :)

**Comment by paradoor** [comment]
See [this](https://discordpy.readthedocs.io/en/latest/faq.html#can-i-use-bot-say-in-other-places-aside-from-commands). You shouldn't be using `bot.say` outside of commands. Also, in future, these types of questions can be asked at the official Discord server: https://discord.gg/r3sSKJJ

**Comment by NCPlayz** [comment]
You cannot use Bot.say in events, instead use Client.send_message, also if you ran it, it would go on a loop, so you might want to fix that, if that's not what you want.

**Comment by jamzs2** [comment]
Thanks for all of your help, kinda new to programming in general, so I have little clue what I'm doing. Thanks again!
