### ISSUE TITLE
Issue with nickname command

### ISSUE THREAD

**Issue by jonasu19** [Rapptz/discord.py#1226]
Hey, I want to make a command that changes the user his nickname with whatever he has input when using the command.

Scenario:
A types !battletag test#4242
A's nickname gets changed to test#4242
If no value after !battletag is input the bot should return an error message. (instead of discord.forbidden check)
If the input does not contain the string "#" it should return an error message. (instead of discord.forbidden check) (recognizing that it is not a battletag as it does not contain "#")

My code: 
` @commands.command(no_pm=True, pass_context=True)
    async def battletag(self, ctx, user : discord.Member, *, battletag=""):
        """Registers your battletag and sets your discord nickname.`

     `   ex. !battletag test#21867"""
        nickname = battletag.strip()
        if battletag == "":
            nickname = None
      try:
            await self.bot.change_nickname(user, nickname)
            await self.bot.say("Your battletag (" + nickname + ")" " is now registered and your nickname has been set to " + nickname + ".")
        except discord.Forbidden:
            await self.bot.say("I cannot do that, I lack the "
                "\"Change Nickname\" permission.")`

Issues:
At the moment it requires the user to input their username ex. !battletag username newnickname
I want the command to only require a new nickname and for the bot to execute the command on the author instead of by which username was input (user : discord.Member)

Thanks in advance!

**Comment by DiNitride** [comment]
You can get the author from the ctx object. Remove the user parameter and use ctx.message.author to get the user

**Comment by jonasu19** [comment]
Thanks for your reply, I tried that some time back and it gives this error:

`[19/04/2018 11:26] ERROR red on_command_error 371: Exception in command 'battletag'
Traceback (most recent call last):
  File "lib\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\Youn\Desktop\Red-DiscordBot\cogs\owner.py", line 416, in battletag
    await self.bot.say("Your battletag (" + nickname + ")" " is now registered and your nickname has been set to " + nickname + ".")
TypeError: must be str, not NoneType
`

My code:
`    #!battletag assignment           
    @commands.command(no_pm=True, pass_context=True)
    async def battletag(self, ctx, *, battletag=""):
        """Registers your battletag and sets your discord nickname.

        ex. !battletag Younes#21867"""
        nickname = battletag.strip()
        if battletag == "":
            nickname = None
        try:
            await self.bot.change_nickname(ctx.message.author, nickname)
            await self.bot.say("Your battletag (" + nickname + ")" " is now registered and your nickname has been set to " + nickname + ".")
        except discord.Forbidden:
            await self.bot.say("I cannot do that, I lack the "
                "\"Change Nickname\" permission.")`

**Comment by Articuno1234** [comment]
are you seriously using Red-DiscordBot?!?!?!?!?

DIY....

**Comment by Harmon758** [comment]
When there's no `battletag` input, you're setting `nickname` to `None` and then attempting to add `None` with strings.

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.
