### ISSUE TITLE
Uploading a random image (send_file)

### ISSUE THREAD

**Issue by ToooD** [Rapptz/discord.py#1228]
I can upload an image if i put in the image's name.
But when i create a map with more images and i put in only the path without the image and try to select a random one, i get Permission Denied error...

Code:
    with open('C:\\Users\\MyUser\\PycharmProjects\\Discord_bot\\Images', 'rb') as f:
        await bot.send_file(channel, (f))

Error:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\MyUser\\PycharmProjects\\Discord_bot\\Images'

How can i upload a random image from the file?

**Comment by Vexs** [comment]
...You can't open a directory as a file. 

As for choosing one randomly, that falls well outside of what github issues are for, [and can be solved with a very short google search](https://www.google.com/search?q=python+get+random+file+from+directory)

**Comment by qwertyquerty** [comment]
```
await bot.send_file(channel, "C:\\Users\\MyUser\\PycharmProjects\\Discord_bot\\Images\\"+random.choice(os.listdir("C:\\Users\\MyUser\\PycharmProjects\\Discord_bot\\Images")))
```

Enjoy my spaghetti code, also this isn't what discord issues are for. You really should figure this kind of thing out on your own.
