### ISSUE TITLE
Dependency Error

### ISSUE THREAD

**Issue by dakoslug** [Rapptz/discord.py#123]
I get the following error after trying to install the async beta

Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_arik/aiohttp
Storing debug log for failure in /home/arik/.pip/pip.log

The log is [here](http://pastebin.com/GAP6HzKQ). I'd be grateful if someone would point me in the right direction.

**Comment by Rapptz** [comment]
> RuntimeError: aiohttp requires Python 3.4.1+

You're using Python 2.7.

**Comment by dakoslug** [comment]
I specifically installed the latest version. Must be using the wrong version.

**Comment by alfalfascout** [comment]
try pip3 instead of pip

**Comment by Rapptz** [comment]
For future references, you can use a specific python interpreter's version of pip by doing e.g.

```
$ python3.5 -m pip install <stuff>
```

**Comment by dakoslug** [comment]
Thanks for the help guys

**Comment by nodox** [comment]
@alfalfascout solved it with `sudo pip3 install <DEPENDENCY>`

Thank you!
