### ISSUE TITLE
When on_message() is used, bot ignores commands but focuses on code in on_message()

### ISSUE THREAD

**Issue by TechnoTew** [Rapptz/discord.py#1235]
^Title. How does it work?

**Comment by Vexs** [comment]
http://discordpy.readthedocs.io/en/latest/faq.html#why-does-on-message-make-my-commands-stop-working

**Comment by Rapptz** [comment]
[Read the documentation next time](http://discordpy.readthedocs.io/en/latest/faq.html#why-does-on-message-make-my-commands-stop-working)
