### ISSUE TITLE
Hiding commands in default !help command

### ISSUE THREAD

**Issue by King-Pie** [Rapptz/discord.py#1236]
Is there a way to hide commands when the help command is used? I want to hide some admin only commands from regular users.

**Comment by Vexs** [comment]
To elaborate- if a check fails, the command won't show up. If hidden=True, the command will not be shown regardless of check success/failure- the user still has to pass checks to use it though.

**Comment by King-Pie** [comment]
That's exactly what I need. Thanks!

**Comment by narFnarF** [comment]
hidden=true doesn't work on the lastest commando on npm (0.10.0). Is there an alternative way of hidding a command from help?
