### ISSUE TITLE
Output discord server messages to website?

### ISSUE THREAD

**Issue by bionichuman** [Rapptz/discord.py#1237]
Would it be possible to output all discord messages from a channel to a website?
 I want a bot to be looking for numbers such as 1 2 3 from the server and what ever number is said the mos t is shown on a website? Is this possible?

**Comment by Modelmat** [comment]
Firstly, please use the discord help server [here](https://discord.gg/r3sSKJJ) for these sort of questions.

Yes, this is possible. Look up Django or Flask.
