### ISSUE TITLE
discord.colour has poor data validation

### ISSUE THREAD

**Issue by NegativeZero000** [Rapptz/discord.py#1241]
I don't know if this is a bug or status by design but I was trying to randomize embed colours and was passing string based hex values to `discord.colour`

    listing_embed = discord.Embed(title=self.title, description=self.description,
                                                        color=discord.Colour(hex(random.randint(0, 16777215))),
                                                        url=self.url)

I had assumed that this was working fine since there was not error thrown at declaration. However using that code netted me a HTTP 400 error on submission. I have since changed it to 

     listing_embed = discord.Embed(title=self.title, description=self.description,
                                                        color=discord.Colour(random.randint(0, 16777215)),
                                                        url=self.url)

Which works exactly how I wanted it to. I would have done that in the first place if the data I passed it was rejected. I was reading http://discordpy.readthedocs.io/en/latest/api.html?highlight=colour#discord.Embed.colour which is why I thought about using `.Colour()`. FYI I am not great at Python but looking at colour.py I noticed this for the constructor

    def __init__(self, value):
        self.value = value

Yes, the docs for Colour support that it should be int. Should there not be some data validation there or no? I am told, in #help, that this is not an issue in the rewrite branch.

**Comment by Rapptz** [comment]
Right this is fixed already.

Manually setting is unsupported however.
