### ISSUE TITLE
Application_info

### ISSUE THREAD

**Issue by Yolotroll101** [Rapptz/discord.py#1245]
can I have a screenshot or something of the code for the application info thing? Specifically one that tells the bot that I am the bot owner? (i am a beginner and do not understand the stuff in the discord.py documentation. :/)

**Comment by Modelmat** [comment]
We went over this. We are not spoonfeeding you your code.
We gave you everything you need (gogurt even gave you a working code snippet) so you should be able to do it.
Secondly, this is most certainly not the place for library help. This is for bugs etc about this library.

**Comment by gogurtenjoyer** [comment]
I already gave you exactly what you asked for in the server where questions like these belong, instead of here, which you already know.

**Comment by Yolotroll101** [comment]
omfg i do not get where it goes

**Comment by Rapptz** [comment]
Don't use issues for spoonfeed requests like these.
