### ISSUE TITLE
"playing" status 

### ISSUE THREAD

**Issue by varieney** [Rapptz/discord.py#125]
How to change "playing" status?

**Comment by Rapptz** [comment]
`await client.change_status(game=discord.Game(name='whatever'))`

**Comment by Angel-Bokkuyoshi** [comment]
This doesn't work for me, it's a self not by the way. When I change_presence I see no difference, the playing status is still not there.

**Comment by Angel-Bokkuyoshi** [comment]
This is deprecated and so I use change_presence, however using the same format just doesn't do anything for me. My playing status does not change, I am using a self not by the way.

**Comment by ccubed** [comment]
You don't broadcast status updates to yourself. You won't see your status change on yourself if this is a self bot.

**Comment by Angel-Bokkuyoshi** [comment]
How disappointing....

**Comment by ThePiGuy24** [comment]
it just throws me an error when i run the line that rapptz provided, do i need anything else?

**Comment by Angel-Bokkuyoshi** [comment]
You have to actually say what the error is, other than that what I can tell you right now is to use change_presence not the deprecated change_status.

**Comment by ThePiGuy24** [comment]
I will try that, if unsuccessful, I will post the error. (can't now as I'm away from my pc)

**Comment by ThePiGuy24** [comment]
That didnt work, heres the error i get now:
```Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Python36-32\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "B:\Users\Electricguy45\Desktop\PiBot.py", line 23, in on_ready
    await client.change_presence(game=discord.Game(name='pi.helpme'))
  File "C:\Python36-32\lib\site-packages\discord\client.py", line 1934, in change_presence
    yield from self.ws.change_presence(game=game, status=status, afk=afk)
AttributeError: 'NoneType' object has no attribute 'change_presence'
```

**Comment by Angel-Bokkuyoshi** [comment]
That is because your client is nothing, it's not a bot and it's no a client so it can't do anything.
Make sure you've done client = discord.Client() or client = discord.ext.commands.Bot(bot_prefix = "prefix") or client = discord.ext.commands.Bot(None)

**Comment by ThePiGuy24** [comment]
I have tried client = discord.Client(), ill try the others (no backtick on this phone)

**Comment by 0xicl33n** [comment]
```
try:
    import discord
    from discord.ext.commands import Bot
    from discord import Client as client
except:
    print("You need to install the discord.py api")
    sys.exit(-1)

my_bot = Bot(command_prefix="!")
bothAuth = ''

@client.event
async def wait_until_login():
    await client.change_presence(game=discord.Game(name='something goes here'))

@my_bot.command()
async def command(*args):
    pass #command goes here

try:
    my_bot.run(botAuth)
except:
    print('[!]ERROR')
    sys.exit(-1)
```

Is there something im doing wrong? I cant seem to make it work.

**Comment by Nekorooni** [comment]
@0xicl33n 
you wrote client.event but your bot is called my_bot


_Sent from my Samsung SM-G935F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by 0xicl33n** [comment]
Yeaaaa looks like im an idiot and was reading the docs and mixing them with my own crap @Nekorooni
