### ISSUE TITLE
Getting past messages

### ISSUE THREAD

**Issue by chirag-jhamb** [Rapptz/discord.py#1252]
Is there any way to get past messages? 
In client the `messages` method returns empty deque
```
async def on_ready():
    print('Logged in as')
    print(client.user.name)
    print(client.user.id)
    print(client.messages)
```

**Comment by SourSpoon** [comment]
Questions like this are more suited to the [discord.py discord server.](https://discord.gg/r3sSKJJ)

However you will need to use the coroutine [logs from](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.logs_from)

You will also need a channel object to get the messages from, see (this FAQ article)[http://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-get-a-specific-user-role-channel-server] for info on getting a channel object.
