### ISSUE TITLE
how do i get the server nickname of a user?

### ISSUE THREAD

**Issue by LemonSPY** [Rapptz/discord.py#1256]
for example to get the discord username of someone i use "message.author.name" is there a way to get the server username?

**Comment by Vexs** [comment]
As per the docs, [member.nick](http://discordpy.readthedocs.io/en/latest/api.html#discord.Member.nick), but odds are you want [member.display_name.](http://discordpy.readthedocs.io/en/latest/api.html#discord.User.display_name)

As a note, GH issues are really not for "please point something obvious out to me", and more for actual issues with the lib. Similar questions are best asked on the [discord.py discord server.](https://discord.gg/r3sSKJJ)

**Comment by LemonSPY** [comment]
thanks for the help. i will refure to the discord from now on for questions. thanks!

**Comment by AMESU** [comment]
Hi, use message.member.user.tag to display :)

**Comment by Aens** [comment]
I use:
`message.author.name if message.author.nick is None else message.author.nick`
