### ISSUE TITLE
Cogs within folders don't unload correctly

### ISSUE THREAD

**Issue by tekulvw** [Rapptz/discord.py#126]
[karma.zip](https://github.com/Rapptz/discord.py/files/160806/karma.zip)

Steps to reproduce:
- Use load_extension to load karma FOLDER
- Use unload_extension to unload karma FOLDER
- Use load_extension to load karma FOLDER

`ClientException: Command karma is already registered.`

Looking into this a bit, it seems like the inspect.getmodule() check in unload is giving false failures.

**Comment by someunknownperson** [comment]
Why are you using folders for commands? What is the point of that it would be easier to have it in the same folder as the rest of your code.

**Comment by Rapptz** [comment]
Fixed in https://github.com/Rapptz/discord.py/commit/b6ac8568687880418cda73b546c32dc085af7411
