### ISSUE TITLE
Send message to specific channel

### ISSUE THREAD

**Issue by FelixEcker** [Rapptz/discord.py#1266]
Hello There again!

How do i send a message in a specific channel? For example on join of a member i wan't to send a message in the welcome channel. I tried copying the Channel ID and did this: 
`await client.send_message(442646501433540608, "Welcome to The Hole of Freedom @" + str(member))`

But i don't get any message. Or could it be that i test this with a discord bot?

**Comment by OneEyedKnight** [comment]
http://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-send-a-message-to-a-specific-channel

**Comment by FelixEcker** [comment]
Thank You! Somehow couldn't find it myself...

**Comment by flamekong** [comment]
Couple of things here:

- You can't just specify an id as a destination, it needs to be a channel object, refer to this: http://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-send-a-message-to-a-specific-channel
- ID's are strings on v0.16
- You shouldn't be mentioning anything by formatting it like this, you can mention a user using: http://discordpy.readthedocs.io/en/latest/api.html#discord.User.mention

For future questions like these, join the discord.py support server: https://discord.gg/r3sSKJJ

**Comment by ahmadallouch** [comment]
Hi!
What needs to be imported for this to work?

**Comment by numbermaniac** [comment]
You only need to `import discord` to use this.

**Comment by Etika-py** [comment]
```await channel.send('hello')
    ^
SyntaxError: 'await' outside function``` i get this error when i try to run it, anyone has a fix for this?

**Comment by Richie-Moon** [comment]
> ```await channel.send('hello')
>     ^
> SyntaxError: 'await' outside function``` i get this error when i try to run it, anyone has a fix for this?
> 

What have you set `channel` equal to?

**Comment by lganWebb** [comment]
Don’t necrobump old issues, and as your error says, you can only use `await` within an asynchronous function.

**Comment by McJoe21** [comment]
Can i do this by getting the user args

**Comment by lganWebb** [comment]
> 
> 
> Don’t necrobump old issues, and as your error says, you can only use `await` within an asynchronous function.

Please do not necrobump old issues, especially when the last comment in the issue was telling somebody not to do this. If you'd like help with the library, please join the [Official Support Server](https://discord.gg/dpy) as the README suggests.
