### ISSUE TITLE
How do i add a role to a member?

### ISSUE THREAD

**Issue by 0alberts0** [Rapptz/discord.py#1269]
I am trying to make a mute command for my bot, but i am running into some trouble with doing so. I am failing to make the bot add the role. Here is the code that I've got so far.
![scrpt](https://user-images.githubusercontent.com/39065582/39719229-42e6980c-5241-11e8-9044-a936b9cafc5e.png)
The output says,
![howww](https://user-images.githubusercontent.com/39065582/39719248-51d89c16-5241-11e8-8ff2-9dcf0556558a.png)
If anyone can help, please do. I would be really thankful.

**Comment by SourSpoon** [comment]
add roles takes a role object. `"mute"` is a string. See below on how to get role objects:
http://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-get-a-specific-user-role-channel-server

In future questions like this are better aimed at the [discord server](https://discord.gg/r3sSKJJ)

**Comment by 0alberts0** [comment]
Ok, thank you.
