### ISSUE TITLE
Issue setting up this package (calling python 2 instead of 3)

### ISSUE THREAD

**Issue by vpontin** [Rapptz/discord.py#1270]
During setup of [Red bot](https://twentysix26.github.io/Red-Docs/red_install_raspbian/) on my raspberry pi i was instructed to run this line: `sudo pip3 install -U git+https://github.com/Rapptz/discord.py@master#egg=discord.py[voice]`

But it gives me this error: https://gist.github.com/vpontin/cfab6da42f2a9ef5a39941a9181a6f40

From what i understand the command runs `python` instead of `python3` what calls the python 2.x installed instead of 3.x, what throws the error.

Can someone gives me help?

**Comment by ItWasAllIntended** [comment]
I have no idea but isn't installation of dpy handled by the red script? And is this really a dpy issue? Where were you instructed. Mind you I'm no Red expert

**Comment by ItWasAllIntended** [comment]
You're missing the Python Dev headers. Use this: sudo apt-get install python3-dev

**Comment by LewdNeko** [comment]
Support for Red bot belongs in discord.gg/red You're far more likely to get the correct and faster help there than asking for it here

**Comment by vpontin** [comment]
i'm following the manual installation according with red docs (i dont like automated scripts), and i got the error only parsing this line. Anyway i will try installing python3-dev like @ItWasAllIntended said

**Comment by LewdNeko** [comment]
If you're following Red's documentation and are having a problem with it, you should go to the Red support server.

**Comment by vpontin** [comment]
It worked! Thanks @ItWasAllIntended !
