### ISSUE TITLE
Can you take Audio input

### ISSUE THREAD

**Issue by gman1230321** [Rapptz/discord.py#1282]
I want to build a general purpose bot that can be activated through voice chat. I only have one monitor so when I'm listening to music with a bot, or need to do anything with a bot, and I'm playing a game, I have to alt tab out, send the command, then alt tab back in. This is a huge pain and I know plenty of others who have the same issue. I want to make a bot that solves this. I already can program the main part of it with the functions and commands, and maybe some tts feedback. The main issue is being able to say a wake word, like "Alexa", and then taking that audio and turning it into text. I can probably get the speech to text part myself, but I don't know how to get the audio from discord into the processor. I mostly use python for my bots as I don't know node or cs well. Any help would be appreciated!

**Comment by flamekong** [comment]
Voice receive isn't implemented yet, but it will come Soon™

**Comment by gman1230321** [comment]
Ok is there any other 3rd party API's that can or is it just completely unsupported on Discords end
