### ISSUE TITLE
[FR] Paginator optional line ending

### ISSUE THREAD

**Issue by Diniboy1123** [Rapptz/discord.py#1283]
I am using the build in commands.Paginator a lot and it is super useful. But, it'd be cool if I Could change the line endings somehow. Like if I have a long member list, but I wanna print them separated by the `, ` characters, I Cannot do that rn. So an optional line_ending kwarg or something like that would be super useful! 😃 

Ty

**Comment by Rapptz** [comment]
I don't think this would be possible since there is the concept of "empty" lines and that would be weird without the '\n' line ending.

**Comment by Rapptz** [comment]
The paginator has API to insert empty lines.

**Comment by ttatanepvp123** [comment]
can someone tell me what it means [FR]
because for me it means French

**Comment by Harmon758** [comment]
Feature Request

**Comment by ttatanepvp123** [comment]
okay

**Comment by Diniboy1123** [comment]
Would be a nice feature to add, however we don't need it anymore, so closing this issue now. If anyone is looking for the same thing, feel free to open a new issue I guess.
