### ISSUE TITLE
bot.remove_listener not working nor responding

### ISSUE THREAD

**Issue by retke** [Rapptz/discord.py#1284]
I tried to use the `bot.remove_listener()` function to remove a custom listener on command, but it didn't remove it, while it successfully passed the call without error. Is there a way to know if the listener was successfully removed? And why is that not working? I'm giving the same function as when it was created.

```Py
    @instantcmd.command(aliases=["del", "remove"])
    async def delete(self, ctx, command: str):
        """
        Remove a command from the registered instant commands.
        """

        _commands = await self.data.commands()
        
        if command not in _commands:
            await ctx.send("That instant command doesn't exist")
            return

        if not self.bot.remove_command(command):
            function = self.get_function_from_str(_commands[command])
            self.bot.remove_listener(function)
        _commands.pop(command)
        await self.data.commands.set(_commands)
        await ctx.send("The command/listener `{}` was successfully removed.".format(command))
```
The `settings.json` file:

```Json
{
    "260" : {
        "GLOBAL" : {
            "commands" : {
                "on_reaction_add" : "async def on_reaction_add(reaction, user):\n    await reaction.message.add_reaction(bot.get_emoji(230124998382190592))"
            }
        }
    }
}
```

**Comment by Rapptz** [comment]
The function's `id` must match the one being removed. They are key'd through that. Which means that if you dynamically create a listener then you're going to have to make a custom callable that implements `__eq__` and `__call__` or something for it to actually be removed.
