### ISSUE TITLE
bot.command and bot.event on_message

### ISSUE THREAD

**Issue by Wileyy** [Rapptz/discord.py#1285]
I've seen other threads on this and have already tried putting `await bot.process_commands(message)` but it still will not launch any commands. I'm not sure what the issue is, and I'm not receiving any error codes.
I'd be super grateful if I could receive some help with this.

```
import discord
from discord.ext import commands
from discord.ext.commands import Bot
import asyncio
import time

bot = commands.Bot(command_prefix = "+")
chat_filter = ["XXX"]
bypass_list = []

@bot.event
async def on_ready():
    print ("Hello, everyone!")
    
@bot.event
async def on_message(message):
    if message.content.upper().startswith('+KISSU'):
        userID = message.author.id
        await bot.send_message(message.channel, "<@%s> Mwah! :hearts:" % (userID))
        await bot.process_commands(message)

@bot.event
async def on_message(message):
    contents = message.content.split(" ") #contents is a list type
    for word in contents:
        if word.upper() in chat_filter:
            if not message.author.id in bypass_list:
                try:
                    await bot.delete_message(message)
                    await bot.send_message(message.channel, "**Hey!** Please do not use that kind of language!")
                except discord.errors.NotFound:
                    return
                    await bot.process_commands(message)
bot.run("XXX")
```

**Comment by gogurtenjoyer** [comment]
You've unfortunately followed some bad tutorial from youtube or a blog post somewhere. 

You have two on_message events where you should only have one.

Also - these types of questions are best asked on the official help server (https://discord.gg/r3sSKJJ) as this area is for actual library issues.

**Comment by Wileyy** [comment]
@gogurtenjoyer Yeah, I'm kind of new to Python. How should I go about fixing it?

**Comment by gogurtenjoyer** [comment]
Please see the link in my last comment and close this issue, thanks!
