### ISSUE TITLE
Can you guys help me some errors in my code?

### ISSUE THREAD

**Issue by PurpleHuman** [Rapptz/discord.py#1287]
So I've started to code a announce command but I keep on coming into the issue listed below. My code is also down there free to use if fixed. Thank you! 
![unknown](https://user-images.githubusercontent.com/38821587/39984758-92d661fe-579f-11e8-906d-32f437464013.png)

Code (free to use):
@bot.command(pass_context=True)
async def announce(ctx, *, content):
    embed=discord.Embed(title="{} has announced!".format(ctx.messege.author.mention))
    embed=discord.Embed(description="@everyone, {}".format(content))
    await bot.send_message(embed=embed)

- Purple Human

**Comment by Modelmat** [comment]
**Please ask these questions in future in the [discord.py](https://discord.gg/r3sSKJJ) server**

You've spelt message wrong - it's `ctx.message`.

**Comment by PurpleHuman** [comment]
Sorry for my clumsy mistake. Thank you for helping me so quickly!

**Comment by Tarek1337** [comment]
Also, fyi. mentions doesn't notify if they are inside a rich embed.

Also don't forget to close the issue.
