### ISSUE TITLE
'User' object has no attribute 'server'

### ISSUE THREAD

**Issue by karoljoc** [Rapptz/discord.py#1288]
Hi,

When getting a member from from server you can use:

server = ctx.message.author.server
server.get_member(member_id)

How do you achieve this in a direct message?  The context seems to change. So how do I check if member is in my direct message?

**Comment by bionichuman** [comment]
@karoljoc Join here and someone will help you. 

https://discord.gg/87uZscw

**Comment by karoljoc** [comment]
Thank you will try. Can I ask one more thing.  How do you escape a code block so it renders as markdown and not plain text?

**Comment by Ikusaba-san** [comment]
You don't need to use the author for the server. It's easier to use `ctx.message.server`, which will be `None` if it's in a direct message.

Not exactly sure what "member" do you want, or why you want a *member* in particular. `ctx.message.author` will already be a member if it's in a server, and, as you already found out, a user in DMs.

A side note:
\```py
abc
\```
for codeblocks.

**Comment by karoljoc** [comment]
I need the members as to only display info about member that are still on the server. I save the member id's in a database to display bids. So if a member has left the server I no longer want to display their bids.

**Comment by karoljoc** [comment]
ps: 
if I do:
```py
**this should be bold**
```
It ignores the ** and just prints it exactly like that

**Comment by karoljoc** [comment]
It works directly in the message block on discord but not from code
