### ISSUE TITLE
Nick name empty

### ISSUE THREAD

**Issue by karoljoc** [Rapptz/discord.py#1289]
Is this a bug in the code? 

This is in members "mention"

```
@property
    def mention(self):
        if self.nick:
            return '<@!{}>'.format(self.id)
        return '<@{}>'.format(self.id)
```

Looks like the nick does not get used?

**Comment by fixator10** [comment]
Used.
![img](https://Moeka.is-a-good-waifu.com/1cef8c.png)
https://discordapp.com/developers/docs/reference#message-formatting

**Comment by karoljoc** [comment]
Sorry i see the author object uses name not nick. :-)
