### ISSUE TITLE
Invalid characters in usernames

### ISSUE THREAD

**Issue by F-lop** [Rapptz/discord.py#1291]
I've been coding a discord bot in python for a couple of days now, but I've run into a problem that is really bugging me. How do you deal with usernames that contain invalid characters? Is there any way of getting the string of a username object that removes the invalid characters or changes the encoding so that they work? I know of ways to remove invalid characters in strings, but they don't work with username objects and I can't change the object to a string as it contains invalid characters. A solution to this would be very much appreciated, hope someone can help me here.

I want to do this:
username = str(message.author) #where message.author contains an invalid character

**Comment by imayhaveborkedit** [comment]
You should probably use the name or nick attribute on member objects since str will return `name#discrim`, and # is that pesky invalid character.

**Comment by F-lop** [comment]
The # isn't the problem, the actual username contains an invalid character. I need a way of somehow getting the string version of the message.author object while ignoring the invalid characters. str(message.author,"utf-8","ignore") doesn't work as it needs to be a bytes-like object

**Comment by Gorialis** [comment]
You're going to need to define what "invalid" is in this context. Every username you can receive from Discord is valid in terms of Unicode - if it weren't, the packet would be malformed and you'd have experience an error much sooner than whatever you're trying to do.

**Comment by F-lop** [comment]
To be honest I'm not exactly sure what the problem is. ﷺ and ⛧ are examples of the invalid characters I mean, they give the error "SyntaxError: invalid character in identifier"

**Comment by BeatButton** [comment]
That would imply that you're trying to name some variable using those characters. Is that what you're doing?

**Comment by BeatButton** [comment]
Name or access, I suppose

**Comment by Gorialis** [comment]
It sounds like somehow you're executing member information as if it was code. I'm not quite sure what has led you to do this, but if it's somehow intentional, note that it can allow strangers to arbitrarily execute code within your bot.

I wager that you're actually attempting to do something else, but I can't really help any further without seieng your code.

**Comment by F-lop** [comment]
I'm trying to get a string containing the message author's username. I'm completely new to bot coding and python in general so I have no clue if what I'm doing is completely dumb or not
