### ISSUE TITLE
[Question] Logs_from Vs Purge_from

### ISSUE THREAD

**Issue by Jaedeke** [Rapptz/discord.py#1296]
Hey

Can you tell me what there difference between Logs_from and Purge_from?
tell me Which one is best to use

**Comment by Vexs** [comment]
`client.logs_from` retrieves the channel history according to the kwargs you set- `client.purge_from`, on the other hand, uses `client.logs_from` to retrieve messages, and then uses `client.delete_messages` to delete said messages. 

Neither is better or worse than the other. Knives vs Screwdrivers.

**Comment by Jaedeke** [comment]
yeah thank 
i was thinking about if it should have been in the discord chat instead
