### ISSUE TITLE
Consume Args Keeping Quotes

### ISSUE THREAD

**Issue by Modelmat** [Rapptz/discord.py#1297]
If you happen to have a command defined as such - 
```py
@bot.command()
async def example(ctx, arg, *, args):
    await ctx.send(f"{arg} {args}")
```
then you run it - 
```
you >>> ?example "say hello" "to my little code"
bot >>> say hello "to my little code"
```
This is slightly annoying, for instance, 
![image](https://user-images.githubusercontent.com/25718989/40227184-23c69c7c-5ad1-11e8-9f26-c5c5800e9bd2.png)
If it were possible to disable this or have the option to disable this happening it would be great!

**Comment by Rapptz** [comment]
Intended behaviour. If you don't want it just strip the quotes.
