### ISSUE TITLE
Accept_invite doesn't throw exception, but doesn't join server

### ISSUE THREAD

**Issue by Exelic** [Rapptz/discord.py#1298]
Hello, 

I'm having issues with accept_invite method it doesn't throw a error and doesn't join the server.
I'm not trying this with a bot/token, I'm using email:pass
 ` await client.accept_invite(invite_url)`
Thanks!

**Comment by Vexs** [comment]
You can no longer use accept invite with a user token, or email/pass due to spam reduction efforts from discord.

 Furthermore, if you are going to selfbot, be sure to use the token method- discord doesn't like selfbots, but they like email/pass a lot less.

**Comment by Exelic** [comment]
So there isn't a way to join a server programmatically? Only manually?
