### ISSUE TITLE
load_opus() missing 1 required positional argument: 'name'

### ISSUE THREAD

**Issue by GhostFire90** [Rapptz/discord.py#1300]
Ive looked everywhere! WHAT IS THE 'name'!!!!!!!

**Comment by Harmon758** [comment]
https://discordpy.readthedocs.io/en/latest/api.html#discord.opus.load_opus

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.
