### ISSUE TITLE
Default Channel is obsolete.

### ISSUE THREAD

**Issue by Cirrial** [Rapptz/discord.py#1301]
On a server I've been trying to write a bot for, the channel that's considered the "default channel" is _not_ the default channel, and is accessible only to a subset of users. However, the Channel.permissions_for method assumes if a channel is set as default, it should be read from. This is not the case, and I'm getting 403 errors and breakages from my bot trying to access this channel on the assumption it's able to read it.

**Comment by Rapptz** [comment]
This is fixed in the rewrite version of the library.
