### ISSUE TITLE
Default channel not set

### ISSUE THREAD

**Issue by ACollectionOfAtoms** [Rapptz/discord.py#1303]
When trying to do something like this [(from an example](https://github.com/Rapptz/discord.py/blob/async/examples/new_member.py)):

```python
@client.event
async def on_member_join(member):
    server = member.server
    fmt = 'Welcome {0.mention} to {1.name}!'
    await client.send_message(server, fmt.format(member, server))
```

The Not found exception is raised:
```
ERROR:__main__:NOT FOUND (status code: 404): Unknown Channel
Traceback (most recent call last):
  File "./bot.py", line 96, in on_member_join
    await client.send_message(server, fmt.format(server, random_welcome_message()))
  File "/usr/local/lib/python3.6/site-packages/discord/client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "/usr/local/lib/python3.6/site-packages/discord/http.py", line 198, in request
    raise NotFound(r, data)
discord.errors.NotFound: NOT FOUND (status code: 404): Unknown Channel
```

Maybe this issue has something to do with it? 
https://github.com/SinisterRectus/Discordia/issues/59

more particularly: 
https://github.com/discordapp/discord-api-docs/pull/329

**Comment by SourSpoon** [comment]
Yes, correct. Default channels don't necessarily exist anymore, you will have to find another way to get an appropriate channel.

This is typically getting a server moderator to configure this and storing the channel id.

**Comment by ACollectionOfAtoms** [comment]
Per the referenced api docs merged PR:

```The "default" channel for a given user is now the channel with the highest position that their permissions allow them to see. ```

Is there a simple way to do this using discord.py ?

Also I think I will make a PR to the referenced example adding a comment about what you said @SourSpoon (for it to work, requires a some manual setup on the server); failing that maybe it should just be removed until `server.default_channel` returns something sensible?

**Comment by SourSpoon** [comment]
New servers can not have default channels. Old servers can have them, but if the channel has been deleted they can not create a new one. 

This is for all intents and purposes, obsolete.

**Comment by ACollectionOfAtoms** [comment]
Ah got it, and I'm sure the example will be removed along with it.

Well that's unfortunate. 

I'm curious how other bots do it then as I know that they are capable of sending "welcome" messages without admins having to modify server settings...

**Comment by Vexs** [comment]
Odds are they use the default channel (if it exists), then fallback to the topmost writeable channel, or, y'know, do the sensible thing and have a command to configure a channel as the welcome message channel. I'm not really aware of any decent bots that do welcome messages without a config of some kind.

**Comment by ACollectionOfAtoms** [comment]
@Vexs you're correct! Thanks.

I guess I won't close this issue sense others might be thrown off by the example.
