### ISSUE TITLE
Replicate message with attachments

### ISSUE THREAD

**Issue by jatinluthra14** [Rapptz/discord.py#1307]
Is there a way that we can replicate a message from one channel with messages and post to other channel?
Channel is not the problem but How to add the attachments to the message.
For example, Here is a sample Message:
Text1......
Image1
Text2......
Image2
Text3.....

How can we put a new message in exact same format?

**Comment by Harmon758** [comment]
https://discordpy.readthedocs.io/en/latest/api.html#discord.Message.attachments
https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.send_file or for rewrite: https://discordpy.readthedocs.io/en/rewrite/api.html#discord.abc.Messageable.send

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.

**Comment by jatinluthra14** [comment]
Ok, There was a confusion that images can be there in between text. But a possibility turns out that they are always at end. So Till I Fiddle with it, The Issue can be Closed
