### ISSUE TITLE
[Suggestion] Concatenate username and discriminator with strings

### ISSUE THREAD

**Issue by GnomoP** [Rapptz/discord.py#1309]
When including a given user's username and discriminator inside a string, like such:
```python
arg = "User: '%s'" % user
```
the snippet works. However, the same does not happen when it is done implicitly, like this:
```python
arg = "User: " + user
```

Could the second snippet be a valid way of achieving the same result as well?

**Comment by fixator10** [comment]
```py
arg = "User: " + str(user)
```

Also, better to ask questions like this on [discord.py server](https://discord.gg/r3sSKJJ)

**Comment by LyricLy** [comment]
Implicit casting to string with concatenation is impossible, by the way.

**Comment by Rapptz** [comment]
This isn't how Python works.
