### ISSUE TITLE
user.display_name returns regular username instead of nickname for self.bot.user

### ISSUE THREAD

**Issue by Remiccino** [Rapptz/discord.py#1311]
As the title says. For normal members and other bot accounts when pulled as discord.Member or discord.User, it's working as intended. The issue is for self.bot.user only.

**Comment by Modelmat** [comment]
I believe this might be a slight misconception - user.display_name will always return the username. Self.bot.user is a username, not a guild member thus nicknames will never show. Try using guild.me.display_name instead.

**Comment by Remiccino** [comment]
Thank you for the reply and solution. It was indeed my oversight as to how `self.bot.user` is without a server context as opposed to `member`.  Allow me to close this issue.
