### ISSUE TITLE
How to take a message object and turn it into a string?

### ISSUE THREAD

**Issue by billybobjoe778** [Rapptz/discord.py#1312]
So I am trying to make a bot called Web MD. That essentially takes a message, and if it says "My ____ hurts" it will say "Hello (user). You have ___ cancer." Now my problem is that the message object is different from the string, and I am not   sure how to change it to a string object. As `str(message)` doesn't exactly work.
Here is my code, without the token obviously, so please tell me how to change the message object to a string object.
```
import discord

TOKEN = 'LolNope'

client = discord.Client()

@client.event
async def on_message(message):
    if message.author == client.user:
        return
    messageString = str(message)
    print(messageString)
    messageList = messageString.split()
    if messageList[0] == 'My' and messageList[-1] == 'hurts.':
        cancer = messageList[1:-1]
        print('a')
        cancer = ' '.join(cancer)
        msg = 'Hello {0.author.mention}. You have ' + cancer + ' cancer.'.format(message)
        await client.send_message(message.channel, msg)

@client.event
async def on_ready():
    print('Logged in as')
    print(client.user.name)
    print(client.user.id)
    print('------')

client.run(TOKEN)
```

**Comment by Harmon758** [comment]
https://discordpy.readthedocs.io/en/latest/api.html#discord.Message.content

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.

**Comment by Modelmat** [comment]
Please join the [discord.py](https://discord.gg/r3sSKJJ) help server in future.

Message.content returns the message's content.
