### ISSUE TITLE
getting 'dict' object has no attribute 'status_code'

### ISSUE THREAD

**Issue by ashutoshdev** [Rapptz/discord.py#1316]
hi,
 getting 'dict' object has no attribute 'status_code' issue in python 3

**Comment by Harmon758** [comment]
Firstly, when requesting help with an error, you need to provide more information, including the full traceback for the error as well as when you're encountering it.

`status_code` is only ever used once, on the rewrite branch in `RequestsWebhookAdapter`. Is this where you're encountering the error?
