### ISSUE TITLE
discord.py does not exist

### ISSUE THREAD

**Issue by Arkansas640** [Rapptz/discord.py#1318]
I tried to run one of the examples after I ran the install command and `setup.py`, but i got this error:
`Traceback (most recent call last):
  File "C:\Users\Alex PC\Desktop\discord.py-async\examples\reply.py", line 1, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'`
does anyone know what I'm missing?

I'm running Python 3.6.5

**Comment by gogurtenjoyer** [comment]
You'll need to install discord.py as per the instructions on the readme for the repo. If you already have, chances are high that you're invoking your bot from a separate python environment that doesn't have it installed.
