### ISSUE TITLE
@bot.command error

### ISSUE THREAD

**Issue by paixlukee** [Rapptz/discord.py#1319]
My bot seemed to be working perfectly fine. I edited some code, and boom.. not working. 

Error: `C:\Users\--\AppData\Local\Programs\Python\Python36-32\Lady Tohru>tohru.py
  File "C:\Users\--\AppData\Local\Programs\Python\Python36-32\Lady Tohru\tohru.py", line 311
    @bot.command(pass_context = True)
    ^
IndentationError: unexpected unindent`

The indentation seemed to be working fine before. I then attempted to change all of the indentation and it gave me a `SyntaxError`.

I have asked some people and they have said there is not a reason why it shouldn't be working.

Here is the gist: [https://gist.github.com/paixlukee/3ea4a98ca2b2c2011c4115f7021a32ef](url)

I am very confused on what I did wrong, and what to do now.

Thanks,
          Luke

**Comment by mrc0mmand** [comment]
Well, I guess it's caused by the commented out `except` block on line 308 - if you don't want to use it, just replace the body of the `except` block with `pass`.

Also, for future questions from the *user* point of view it's advised to use the official discord.py Discord server.

**Comment by paixlukee** [comment]
I did that just now and I got, a `SyntaxError`

**Comment by mrc0mmand** [comment]
What exactly did you do? After changing the try-except section as mentioned the error goes away:
```python
async def kick(ctx, userName: discord.User= None, *modreason):                         
    if userName is None:                   
        await bot.say("So you want to kick someone off of a dragon's nest?, Use This: `<3kick <user>`")                                                                       
    try:                                                                                                                                                                      
        author = ctx.message.author        
        await bot.kick(userName)                                                                                                                                              
        await bot.say("<:toxh:449941181325901824> **{}**, Success! **{}** has been **kicked** from this server for **{}**".format(author, userName, reason))                  
        await bot.whisper(userName, "**{}** has kicked you from the server for **{}**".format(author, reason))                                                                
    except:                                                                                                                                                                   
        pass       
```

Nevertheless, the code still contains a few uninitialized variables, so you should look into that as well:
```
$ pylint-3 -E tohru.py 
No config file found, using default configuration
************* Module tohru
E:306,148: Undefined variable 'reason' (undefined-variable)
E:307,102: Undefined variable 'reason' (undefined-variable)
E:320,153: Undefined variable 'reason' (undefined-variable)
E:321,106: Undefined variable 'reason' (undefined-variable)
```

**Comment by paixlukee** [comment]
It Worked! Thank you!
