### ISSUE TITLE
is @client.command got removed or the problem is from my workspace

### ISSUE THREAD

**Issue by MSparkle** [Rapptz/discord.py#1321]
i tried to work on @client.command instead of @client.event
so when i saw the python api page this one http://discordpy.readthedocs.io/en/latest/faq.html
there's a code down there 
""@client.command(pass_context=True)
async def joined_at(ctx, member: discord.Member = None):
    if member is None:
        member = ctx.message.author

    await client.say('{0} joined at {0.joined_at}'.format(member))""

when i try to run it tells me in console 

`AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 296, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class 'discord.client.Client'>' object has no attribute 'command'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x06065D70>`

so whats the solution for this?

**Comment by SourSpoon** [comment]
You are confusing `discord.Client` with `commands.Bot`. The Bot class has all the functionality of discord.Client with an added commands framework.

You can see examples of it's usage [Here](https://github.com/Rapptz/discord.py/blob/async/examples/basic_bot.py)

Typically questions like this are better suited for the [discord server ](https://discord.gg/r3sSKJJ)

**Comment by MSparkle** [comment]
thanks it worked to me the whole problem was in my code

**Comment by gamerpres2020** [comment]
I still get this issue???

**Comment by Harmon758** [comment]
Please don't necrobump issues.
As explained, [`commands.Bot`](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#bot) is different from [`discord.Client`](https://discordpy.readthedocs.io/en/latest/api.html#client).
As also mentioned, for further help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README also links.
