### ISSUE TITLE
how i can remove discord.ext.commands.errors.CommandNotFound: Command "..." is not found

### ISSUE THREAD

**Issue by MSparkle** [Rapptz/discord.py#1322]
when i try run a command that is not in the code the console log:
discord.ext.commands.errors.CommandNotFound: Command "..." is not found
can i remove that like using try: and except: ?
or maybe i can't because i'm trying to make a custom console log

**Comment by SourSpoon** [comment]
As I said before, questions like this are better suited for the [discord server ](https://discord.gg/r3sSKJJ)

You will need to implement an error handler. You can see an example of one here.
https://gist.github.com/Vexs/daa1dcc92ff80fad7ca020d0f7bb4f75

**Comment by MSparkle** [comment]
thanks and sorry bout annoying lol i finally joined the server
