### ISSUE TITLE
send_file embed parameter inconsitent

### ISSUE THREAD

**Issue by Douile** [Rapptz/discord.py#1324]
I'm trying to attach a local file for use in an embed and noticed that I could not use an embed in send_message. Not sure if there is some other way to do this or if this is an issue.
https://github.com/Rapptz/discord.py/blob/1863a1c6636f53592519320a173ec9573c090c0b/discord/http.py#L299
https://github.com/Rapptz/discord.py/blob/1863a1c6636f53592519320a173ec9573c090c0b/discord/client.py#L1176

**Comment by SourSpoon** [comment]
This has been resolved in the rewrite version of the library

**Comment by Douile** [comment]
Ah ok thanks, so this is not likely to be changed in async branch?

**Comment by Vexs** [comment]
Yep. Mind you, if you really don't want to update you could probably backport it.
