### ISSUE TITLE
AIOHTTP

### ISSUE THREAD

**Issue by paixlukee** [Rapptz/discord.py#1325]
I am very confused on how exactly to do AIOHTTP. I tried lots. I ended up deleting it because it did not work. Is there an example for it? It’s for https://discordemoji.com/api

**Comment by Harmon758** [comment]
aiohttp is a python library used by discord.py
Not sure what exactly you're asking, but you can find the documentation for it here:
https://aiohttp.readthedocs.io/en/stable/

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.
