### ISSUE TITLE
Embed images and thumbnails only work if the image has an extension

### ISSUE THREAD

**Issue by JakeStanger** [Rapptz/discord.py#1326]
I'm not sure whether this is by design or on Discord's end but I feel I should raise it as an issue.

Doing `embed.set_thumbnail(url='https://example.com/image-file')` will not work. Changing the name of the image file to `image-file.png` (even if it is a jpeg) fixes this. The same is true for the `set_image` method. 

However, the `icon_url` field in `set_footer` has no issues being displayed even if the image has no extension.

**Comment by Harmon758** [comment]
> Changing the name of the image file to `image-file.png` (even if it is a jpeg) fixes this. The same is true for the `set_image` method.

I'm unable to reproduce this with either .jpeg or .jpg files.

> However, the `icon_url` field in `set_footer` has no issues being displayed even if the image has no extension.

I'm also unable to reproduce this with either .jpeg, .jpg, or .png files.

Every embed image URL field requires the proper extension for me.
What are the image URLs you're using to test this?

**Comment by JakeStanger** [comment]
I am using:
`https://files.jakestanger.com/mpd/current`
`https://files.jakestanger.com/mpd/current.png`

In both cases it is the same file, which is a jpg image. Only the 2nd image works for thumbnails; both for footer images.

**Comment by daredevil28** [comment]
Seems like the first one doesn't embed in discord. but the second one does. Feels like this one is on discords side.

**Comment by Harmon758** [comment]
For the latter, it resolves to a png image, so it seems to be functioning normally.
For the former, it's just dependent on how Discord handles image URLs without a file extension or `Content-Type` in the response header for each case, be it for different embed fields or link embeds themselves.
