### ISSUE TITLE
how I can get guild object with ID of server?

### ISSUE THREAD

**Issue by katmai1** [Rapptz/discord.py#1327]
I need get a list  of users with a specific role of a specific server, but I only can get this info when message  is sent from channel but I want all commands via private messages...
if I have a server (guild) id and role name, how I can get a list users (IDs)?
Sorry but I'm trying find it 2hours ago, I'm blocked...
thanks

**Comment by Harmon758** [comment]
https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.get_server
https://discordpy.readthedocs.io/en/latest/api.html#discord.Server.roles
https://discordpy.readthedocs.io/en/latest/api.html#discord.Member.roles

For the rewrite branch:
https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Client.get_guild
https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Guild.roles
https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Role.members

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.

**Comment by katmai1** [comment]
thanks for info and sorry for use github to questions...
