### ISSUE TITLE
Animated emojis not working

### ISSUE THREAD

**Issue by Qlii256** [Rapptz/discord.py#1335]
I can send whatever emoji I want to my server with my bot. But an animated one does not work. The docs do not specify anything related to animated emojis so I'm not sure whether I need to set an argument for the bot to understand it as an animated emoji.

`emoji1 = str(discord.Emoji(name='a:emoji_name', id='number', server='number'))`

I hope someone can help me. The emoji1 gets printed out as `<:a:emoji_name:id>`. When I remove the a: from the name it's also not working.

Another thing I've noticed. Printing out the url `print(emoji1.url)` will give me a link that ends on png and a static version of the emoji is visible. When I change the end from png to gif I can see the working animating emoji. To me it seems like Discord.py is not handling animated emojis or I'm doing something wrong. But the docs do no specify anything about animated emojis.

**Comment by Harmon758** [comment]
Animated emoji are only supported on the rewrite branch of the library.
If you really want to send an animated emoji on the async branch, you can send `<a:{name}:{id}>` manually.

**Comment by Qlii256** [comment]
Oh, and what is the rewrite branch? A WIP branch?

**Comment by Harmon758** [comment]
Yes, it's the next major version.
You can get more information about it in the [official discord.py server](https://discord.gg/r3sSKJJ).

**Comment by Qlii256** [comment]
Do you recommend me to use plaintext for now (manually) or install the Rewrite version?

**Comment by Harmon758** [comment]
The rewrite branch is better in a lot of other ways as well, so I'd recommend you look into migrating.
Be sure to join the [official discord.py server](https://discord.gg/r3sSKJJ) to stay up to date on news about the rewrite branch.

**Comment by Qlii256** [comment]
I've joined the channel but I cannot find any documentation on how to install this branch.

**Comment by Harmon758** [comment]
R. Danny has a tag for it: `?tag install rewrite`
For further help, you should ask in the server itself.

**Comment by Qlii256** [comment]
I'm blind... It's even on the README of Rewrite... I just noticed the exact moment you commented. TY for the help!
