### ISSUE TITLE
Unclosed Client Session

### ISSUE THREAD

**Issue by BreakitBilly** [Rapptz/discord.py#1340]
`Unclosed client session client_session: <aiohttp.client.ClientSession object at 0x04442DD0> Unclosed client session client_session: <aiohttp.client.ClientSession object at 0x04442F90>`

Every time I try to open up my discord bot (which worked perfectly in the past) it returns the above error code. I haven't been able to find a case like mine where there are two unclosed sessions so I figured that it would be fitting to start a new discussion thread.

**Comment by Vexs** [comment]
These errors are symptomatic- that is to say, not the cause of the error. Generally they show up when the bot errors out from some other error. We need the full traceback to diagnose this- and I'd recommend you pursue further support on [our discord server](https://discord.gg/r3sSKJJ)
