### ISSUE TITLE
aiohttp 3.3 is incompatible with Python 3.5.2

### ISSUE THREAD

**Issue by Tobotimus** [Rapptz/discord.py#1344]
I was curious as to why the rewrite's minimum python version is now specified as 3.5.2, since [aiohttp 3.3's minimum python version is 3.5.3](https://github.com/aio-libs/aiohttp/blob/v3.3.0/setup.py#L133).

Kind regards from me :smiley:

**Comment by bassamf16** [comment]
00

**Comment by Tobotimus** [comment]
Resolved by #1345
