### ISSUE TITLE
Ban/Kick commands = how to do?

### ISSUE THREAD

**Issue by kaynsi** [Rapptz/discord.py#1348]
I'm wondering how to do the commands of banning and kicking in my code. I don't see any example in the folder and there is no YouTube video explaining it since many of the damn videos are about JavaScript.
Just please send me the code.

**Comment by Harmon758** [comment]
https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.ban
https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.kick

For the rewrite branch:
https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Guild.ban
https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Guild.kick

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.

**Comment by kaynsi** [comment]
That litterally confuses me.

**Comment by TheRockettek** [comment]
rewrite or in discord.py
