### ISSUE TITLE
How would I go about making my bot put multiple lines of text in the same message?

### ISSUE THREAD

**Issue by Skeletontrain** [Rapptz/discord.py#1349]
I would like some help with my Discord bot I am currently working on.
I would like the bot to post a message with multiple lines of text in it.
Including a Discord ID tag of a person's account
An item value
A number value
An increment
A time value
And another number value

Essentially, if that's too much to ask for, I'd like to simply know how to create multiple lines of text in the same message.

**Comment by mrc0mmand** [comment]
Just use an escape character for a newline `\n` like you would use with *classic* Python.

```python
...
await channel.send("First line\nSecond line\nThird line")
...
```

And you probably want to use formatting strings. For more info see
```bash
$ python3 -c "help('FORMATTING')"
```

Also, for future questions from the *user* perspective, it's advised to use the official Discord.py Discord server.

**Comment by mental32** [comment]
You should really try googling these before opening an issue, this is a general programming question.

What you're looking for is the newline escape character `\n` .

**Comment by Skeletontrain** [comment]
Haha, I just realized I've been using a forward slash this entire time. Sorry for the bother, I had googled it, but as you can see, mistakes were made.

Side note: Don't try and code after being awake for over 24 hours!

**Comment by Skeletontrain** [comment]
Also, where are my manners? Thank you to you two for actually commenting and helping out, it was a mistake on my end.
