### ISSUE TITLE
on_message_edit does not trigger when a message is pinned/unpinned

### ISSUE THREAD

**Issue by Jgray705** [Rapptz/discord.py#1350]
I noticed in the docs that the event on_message_edit is supposed to trigger when a message is pinned, but it only triggers when a message is edited.
`@bot.event
async def on_message_edit(before, after):  
    print("edit")
    if not before.pinned and after.pinned:
        embed = discord.Embed(title="A message by {} has been pinned".format(after.author), description=after.content, color=discord.Colour.blue())
        await bot.send_message('channel', embed=embed)`
This is the code I have and the word "edit" only prints when content is changed even though it should also print when a message is pinned.

**Comment by Jgray705** [comment]
I'm pinning the most recent message and my max messages is set at 10000

**Comment by Harmon758** [comment]
If the most recent message was sent before the bot started up, it still wouldn't be in the messages cache.
