### ISSUE TITLE
Using PermissionOverwrite's causes pylint error

### ISSUE THREAD

**Issue by TheSnoozer** [Rapptz/discord.py#1352]
Branch: rewrite
Based on the examples in https://discordpy.readthedocs.io/en/rewrite/api.html#discord.PermissionOverwrite

```python
overwrite = discord.PermissionOverwrite()
overwrite.send_messages = False
overwrite.read_messages = True
await channel.set_permissions(member, overwrite=overwrite)
```

Running `python3.5 -m pylint *.py --disable=R,C,W` causes:
```
E:X,20: Assigning to attribute 'send_messages' not defined in class slots (assigning-non-slot)
E:X,20: Assigning to attribute 'read_messages' not defined in class slots (assigning-non-slot)
```

**Comment by Gorialis** [comment]
This looks like an issue with pylint not acknowledging settable properties, and as such probably has a better home being reported to its developers with this context.

As a workaround, use the kwargs instead:
```py
overwrite = discord.PermissionOverwrite(send_messages=False, read_messages=True)
await channel.set_permissions(member, overwrite=overwrite)
```

**Comment by TheSnoozer** [comment]
Thanks for the input.
Workaround does the trick for me.
