### ISSUE TITLE
how to move a specified user to another text channel ?

### ISSUE THREAD

**Issue by KxC954** [Rapptz/discord.py#1356]
Hey, everything is in the title
I've been looking for this since yesterday, so i probably suck at looking for stuffs ! Thanks in advance for your help

**Comment by Ikusaba-san** [comment]
This is a weird question. You can't "move" users to a different text channel.

The response posted by Pigman is wrong, as that's for **voice** channels only.

**Comment by Pigman168** [comment]
Apologies, misread the question.

**Comment by KxC954** [comment]
Oh god .. It's only now that I realize.. I'm going to solve this in another way, thanks Ikubasa-san
