### ISSUE TITLE
No module named 'discord'

### ISSUE THREAD

**Issue by Pyprar** [Rapptz/discord.py#1365]
So, I wanted to make a Discord bot for my server, I did everything right, etc, etc following this tutorial https://www.youtube.com/watch?v=pEnRUKhAcOM

I'm using as shown, Visual Studio Code, and on the bottom box it says Python 2,7 32-bit even after installing Python 3,6,5

So, I did everything good, installed pip etc, even upgraded it to the newest version, but I can't find a solution, I don't have any folder named Discord in my project folder, please help

**Comment by Modelmat** [comment]
This question is not related to discord.py at all. This is something related to Visual Studio Code.
Please ask this question in [here](https://discord.gg/code) for further VSCode questions and for future questions about this lib please ask in [here](https://discord.gg/r3sSKJJ).

**Comment by Pyprar** [comment]
Okay thanks
