### ISSUE TITLE
How can i use "add_roles"

### ISSUE THREAD

**Issue by KxC954** [Rapptz/discord.py#1367]
Hello,
i did this way:      await client.add_roles(message.author, roles=discord.Role.id(xxxxxxxxxx))
and it printed me out "TypeError: 'member_descriptor' object is not callable"
Thanks in advance

**Comment by Harmon758** [comment]
[`Role.id`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Role.id) is an attribute used to get the ID for an existing `Role` object.
Don't attempt to create the `Role` object. Instead, you can [`get`](https://discordpy.readthedocs.io/en/latest/api.html#discord.utils.get) the `Role` you want, by ID, from a list of roles, e.g. [`Server.roles`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Server.roles).

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.
