### ISSUE TITLE
aiohttp client session not closed

### ISSUE THREAD

**Issue by neko404notfound** [Rapptz/discord.py#1368]
Would it be worth adding `discord.Client._do_cleanup` as a handler to the builtin Python exit handler module in the constructor for discord.Client?

Since the `_do_cleanup` call checks if the loop is running anyway, this would enable us to cleanly kill the aiohttp client session even if the bot does not get started.

Something perhaps along these lines?
```py
import atexit

class Client:
    ...
    def __init__(self, **kwargs):
        ...
        atexit.register(self._do_cleanup)
```

**Comment by Rapptz** [comment]
No. Some people would not want the library to take ownership of the loop like that because it'd hide some bugs in their code.
