### ISSUE TITLE
TextChannel.topic doesn't convert emojis correctly

### ISSUE THREAD

**Issue by 12pm** [Rapptz/discord.py#1374]
Only converts emojis to unicode when it's the very first character in the topic, else it's displayed as the shortcut (``:emoji_name:``). E.g. ``:two::two:`` is outputed as ``2⃣:two:``.
 On Discord itself they are displayed correctly.

**Comment by Rapptz** [comment]
There is no "conversion" of emojis on my side at all. The person who input the topic probably didn't use the codepoints directly themselves.
