### ISSUE TITLE
Design issue for repeating the events across multiple modules

### ISSUE THREAD

**Issue by CorentinJ** [Rapptz/discord.py#1384]
I'm starting to have a lot of functions implemented in my bot, and I feel it's just poor design to have methods such as `on_message` which do 20 different things in the same function block.

I wish to split responsibilities among different modules which would all have the capabilities of the Client class but while sharing the same instance.

I made an example to illustrate my point:

```
# File bot.py
class Bot(discord.Client):   
    def __init__(self):
        self.modules = [Module1()] # Initialize all modules
        super().__init__()

    # This method is broadcast, it will also be called on every module attached using the same 
    # parameters.
    @event_broadcast    
    async def on_message(self, message: discord.Message):
        # Here I have access to the Client fields, e.g. client.servers:
        for server in self.servers:
            print("I am connected to server %s!" % server.name)
        # However, most modules have different actions upon receiving a message, so I let each
        # module implement its own logic
        
# File module1.py
class Module1():
    async def on_message(self, message: discord.Message):
        # Here I don't have access to the client fields because Module doesn't inherit from 
        # Client... I can pass a reference to the Client instance, but that creates circular 
        # dependencies.
        pass

```

I'm not sure whether I am missing a design pattern that would solve my problem or if I am limited by the design of library to revolve around a single instance.

**Comment by LyricLy** [comment]
This already exists as cogs. They are part of the discord.ext.commands modules.

**Comment by mrc0mmand** [comment]
You can pass a Client/Bot instance during a cog setup:

```python

class Example:
    def __init__(self, bot):
        self.bot = bot

    async def on_message(self, message):
        if message.author == self.bot.user:
            return
        ...

def setup(bot):
    bot.add_cog(Example(bot))
```

**Comment by LyricLy** [comment]
Specifically a Bot. Client has no support for cogs.

**Comment by CorentinJ** [comment]
Thanks, I was unaware of the Bot API. Is there a reason it is undocumented on the page http://discordpy.readthedocs.io/en/latest/api.html?

**Comment by Harmon758** [comment]
The command extension is undocumented on the async branch.
The documentation for it on the rewrite branch is specifically for the rewrite branch, so there will be parts that don't apply or are incorrect for the async branch.

For further questions, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.
