### ISSUE TITLE
Client.run seems to be hanging on syntax check?

### ISSUE THREAD

**Issue by Taiiwo** [Rapptz/discord.py#1388]
My diagnosis could be totally wrong, but I've never come across an error like this before. Basically, running a basic use case of this library, and nothing in the file is executed at all. The terminal just hangs.

```python
print(1)
import discord
import asyncio

userEmail = "replaced"
userPassword = """replaced"""

client = discord.Client()

@client.event
async def on_ready():
    print("Logged in")

client.run(userEmail, userPassword)
```
Notice the `print` on line 1. When run this code does nothing, implying that it never gets to executing the first line of the code.

literally: 
```
taiiwo@DESKTOP /.../Downloads
$ python3.6.exe script.py

```

Wireshark says no networking is being done. Maybe I should install pyCharm and do some debugging if it can't be replicated, but I've never really used pyCharm before. The weird thing is that if I try with invalid creds it prints line 1 and throws an "Improper credentials" error. Same if I comment out `client.run()`.

It works fine on my linux box (I'm running this on python for windows), and it used to run fine on this machine until now.

Is this a discord.py bug or something I'm doing wrong?

**Comment by Harmon758** [comment]
[Self-bots are not allowed](https://support.discordapp.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-).
Not only that, but using an email and password (instead of a static token) was prohibited and unsupported even before self-bots were, and doing so now is definitely a very bad idea.

**Comment by Taiiwo** [comment]
Oh, my bad. I also tried it with an bot auth token and got the same result. I knew that self bots weren't allowed, but I didn't know the library was dropping support for them. The issue is still present in Cygwin, even when running the windows binaries. Solved the issue for now by running the script in powershell. This might be a cygwin issue?

**Comment by notBanii** [comment]
maybe try just `python.exe` or `python36.exe` idk

**Comment by Gorialis** [comment]
The Windows binaries for CPython have an absurdly long load time when launched through environment emulators like Cygwin or MSYS. If you want to use the Windows binaries, use `cmd` or Powershell.

MSYS also has a Linux version that can be installed (`pacman -S python`) and used (`python ...`) within the environment itself (but is unusable outside of it).

**Comment by Taiiwo** [comment]
I don't think it's a load time issue as I left it over night on a hanging shell. I don't remember it ever doing this before. Anyway, it's working in command prompt/powershell now so I guess this issue is fixed. I am having a problem with it seeming to take an infinite amount of time to log in by report of my friend, but it's probably something he's doing wrong, and if not I'll make another issue.

thanks

**Comment by khazhyk** [comment]
@Taiiwo this is an issue with your terminal emulator - your stdout isn't connected or something so anything  attempting to print hangs indefinitely. this is a common issue if you are running in msys or cygwin using the windows python binary (in which case you need to use winpty to allow it to print)

e.g. `winpty python script.py`
