### ISSUE TITLE
Bot hanging and not responding to the gateway

### ISSUE THREAD

**Issue by EndenDragon** [Rapptz/discord.py#1402]
![](https://cdn.discordapp.com/attachments/381965564807086080/465710378521722914/unknown.png)
![](https://media.discordapp.net/attachments/381889733053251584/465729194869915648/unknown.png?width=1920&height=866)
I'm having this issue where the bot hangs and goes into a restart loop. I am using discord.py's rewrite branch.

**Comment by Harmon758** [comment]
There's not much to go off of here to diagnose the issue.
Is your connection stable? Are you doing anything [blocking](https://discordpy.readthedocs.io/en/rewrite/faq.html#what-does-blocking-mean)?

**Comment by EndenDragon** [comment]
I am not sure how to avoid blocking lines of code. Here is the bot in question https://github.com/TitanEmbeds/Titan/blob/master/discordbot/titanembeds/bot.py

**Comment by Harmon758** [comment]
From a cursory overview, it seems like the issue could be your database interface.
I believe sqlalchemy is blocking and even running it in an executor doesn't ensure that it won't block the event loop. I'd recommend switching to a library that is asynchronous.

This doesn't seem to be an issue with discord.py though, so for further help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by EndenDragon** [comment]
I switched to an asynchronous database lib (Gino). However it's still acting up. ![](https://cdn.discordapp.com/attachments/465713881021415448/466689176948047883/SmartSelect_20180711-123406_ConnectBot.jpg)

**Comment by Harmon758** [comment]
I also see `time.sleep` multiple times in your code.
See https://discordpy.readthedocs.io/en/rewrite/faq.html#what-does-blocking-mean.

For further help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api).
