### ISSUE TITLE
Command not found error 

### ISSUE THREAD

**Issue by LngShlong** [Rapptz/discord.py#1405]
`import discord
from discord.ext.commands import Bot
import random
token = '*'
Bot_Prefix = ('!')

client = Bot(command_prefix=Bot_Prefix)

@client.command(name='dice')
async def dice_roll():
      roll = ['1','2','3','4','5','6']

      await client.say(random.choice(roll))
    

client.run(token)
`
I was wondering if anyone could help me figure out why whenever I enter in the command !dice it tells me that the command dice is not found

**Comment by Harmon758** [comment]
I'm unable to reproduce this. Are you sure this is the code you're running?

**Comment by Harmon758** [comment]
What I'm asking is if this is the exact code you're running, besides the token.
A simple copy + paste and token replacement works as anticipated.

As for GitHub code blocks, see: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by LngShlong** [comment]
Ya it is the exact code im running

**Comment by Harmon758** [comment]
Are you restarting your bot after you've modified its code?
Unless you're using cogs, the bot doesn't dynamically update, so you have to stop and re-run it.

**Comment by LngShlong** [comment]
how exactly do I do that?

**Comment by Harmon758** [comment]
Stop execution of the Python script and start it again, the same way you did before.

This doesn't seem to be an issue with the library, so for further help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by LngShlong** [comment]
ah alright thank you

**Comment by XziimP** [comment]
It's really sad all of the issues with hold ups, due to rewriting and lack of proper instructions. How can people learn when nothing works )))

**Comment by lganWebb** [comment]
It is not a good idea to comment on old, closed issues. If you need help with anything to do with the library, follow the links above and ask there.

**Comment by XziimP** [comment]
oh ok

**Comment by Harmon758** [comment]
As explained, please don't necrobump issues.
This is a closed issue which was a question about an issue caused by user error, not an issue with the library. There is [thorough documentation for the library](https://discordpy.readthedocs.io/en/latest/), along with [a detailed guide for migrating to v1.0](https://discordpy.readthedocs.io/en/latest/migrating.html), and the library is fully functional.
