### ISSUE TITLE
client.get_reaction_users issue.

### ISSUE THREAD

**Issue by adekki** [Rapptz/discord.py#1407]
I'm trying to add the report bans to my discord bot. It's supposed to count the ❌ and ✅ reactions on the "~report @ person" command after 30 seconds. It's almost finished but the client.get_reaction_users makes generator instead of list or array. And i can't use this in my project. 
`countno = сlient.get_reaction_users('❌')
countyes = client.get_reaction_users('✅')
if len(countno) > len(countyes):
    await client.send_message(message.channel, '1st case')
elif len(countno) < len(countyes):
    await client.send_message(message.channel, '2nd case')
    client.ban(repname)
else:
     await client.send_message(message.channel, '3rd case')`
This causes problems. When i tried to print countno and countyes variables i got this:
`<generator object Client.get_reaction_users at 0x02CD86C0>
<generator object Client.get_reaction_users at 0x02CD8750>`
When i tried to use list() i got this:
![image](https://user-images.githubusercontent.com/41084314/42533126-6f30c660-84a2-11e8-80b7-23e64aeab998.png)
How can i fix this? Thx in advance.

**Comment by Harmon758** [comment]
[`get_reaction_users`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.get_reaction_users) is a coroutine, so you need to await it.
It also accepts a [`Reaction`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Reaction) object, not an emoji character/string.

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.

**Comment by adekki** [comment]
I already tried using `await` and it just crashes with no error.

**Comment by Harmon758** [comment]
Like I said, you need to pass in a [`Reaction`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Reaction) object, not an emoji character/string.

For further help, join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api).
