### ISSUE TITLE
Error With python -m pip install discord.py

### ISSUE THREAD

**Issue by MineClipper** [Rapptz/discord.py#1410]
![error](https://user-images.githubusercontent.com/25290723/42546283-b191475e-848a-11e8-85b8-57cfb591e811.PNG)
Can anyone tell me why this isn't working? I'm still really new with python, so please give your response in basic terms. 
I'm using python 3.6.6.

**Comment by scragly** [comment]
Ensure your PYTHONPATH and PYTHONHOME env variables exist and are pointed to the correct locations for your python interpreter.

**Comment by MineClipper** [comment]
Could you send me a link? I'm still really new to all of this and I don't know how to fully work it yet.

**Comment by scragly** [comment]
The README is the first page in this repo, the main page. You would not have missed you, you likely just didn't read it.

[The server invite is here](https://discord.gg/discord-api)

Please close this issue though, due to being irrelevant to the lib.
