### ISSUE TITLE
Sending TTS Messages to a Specific Channel

### ISSUE THREAD

**Issue by SpaceGuru01** [Rapptz/discord.py#1412]
Hi All,
I need some help to get a bot to send messages to a specific channel. The way the bot I am making works is that that there is a button on the bot's website which runs a js trigger to send a message. I know how to use `message.channel.send()` but I think that only works when the bot is sending a message based on a message sent trigger.

Thanks.

**Comment by Harmon758** [comment]
If you have the channel's ID, you can use [`get_channel`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Client.get_channel).

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.
