### ISSUE TITLE
Segmentation Fault with audio bots

### ISSUE THREAD

**Issue by JellyWX** [Rapptz/discord.py#1419]
Linux seg fault with audio bots. GDB trace:

```
[mp3 @ 0x671400] Estimating duration from bitrate, this may be inaccurate
[New Thread 0x7fffc5c47700 (LWP 3512)]

Thread 604 "python3" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc6c49700 (LWP 3510)]
__memcpy_avx_unaligned ()
    at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:268
268     ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S: No such file or directory.
```

**Comment by JellyWX** [comment]
This is my code and the seg fault is some sort of internal bug, but i agree it is likely opus or FFmpeg rather than d.py causing the issues. im just asking on the off chance, since i dont know where to file and i have nothing to run off with debugging what's likely C code

**Comment by JellyWX** [comment]
For now I've set up a script that autorestarts the bot. A better solution, from here or from Opus, would be nice though

**Comment by JellyWX** [comment]
I'm running it on a new server (OpenVZ with an older kernel) and it gives me this:

    *** Error in `python3': free(): invalid size: 0x00000000037e3190 ***
    Segmentation fault (core dumped)

I don't know if that means anything more. Sounds like issues with the garbage collector?

**Comment by imayhaveborkedit** [comment]
I'm fairly sure this is an issue with the lib calling libopus' `opus_encode` with bad arguments, or ending up with some weird state that causes this error.  The voice code has changed a bit since then so if this happens again I'll look into it further.
