### ISSUE TITLE
discord.Client().close() does not always close the session

### ISSUE THREAD

**Issue by NelsonMinar** [Rapptz/discord.py#142]
My Discord client programs are printing "Unclosed client session" when my program ends. That's an error generated by aiohttp because the session wasn't closed by the time the `__del__` method was called (at program end). I think the problem may have been introduced with change ff14fa0fe; it appears that `session.close()` is  not always called by the discord Client's close function.

Here's a simple demo program to reproduce the problem:

```python
# Demo of a bug in discord.py 0.10.0-alpha (tested with 53a240e)

# This program causes the following error to be printed when Python exits
# Unclosed client session
# client_session: <aiohttp.client.ClientSession object at 0x7f3bd7a83358>

import discord

c = discord.Client()
c.close()

# Adding this line seems to fix the problem
# c.session.close()
```

**Comment by Rapptz** [comment]
`close` is a coroutine: https://github.com/Rapptz/discord.py/blob/async/discord/client.py#L545.

This isn't documented. I will fix it.
