### ISSUE TITLE
Task exception was never retrieved

### ISSUE THREAD

**Issue by EertNL** [Rapptz/discord.py#1420]
My script was working fine until some time ago. I was on holiday so i'm not sure when it first appeared. 
My BOT is working for some time until at some point it raises an error
The error i get is:

Task exception was never retrieved
future: <Task finished coro=<my_background_task() done, defined at pibot.py:29> exception=AttributeError("'NoneType' object has no attribute 'get'",)>
Traceback (most recent call last):
  File "pibot.py", line 82, in my_background_task
    await bot.send_message(channel, embed=em)
  File "/usr/local/lib/python3.6/site-packages/discord/client.py", line 1153, in send_message
    channel = self.get_channel(data.get('channel_id'))
AttributeError: 'NoneType' object has no attribute 'get'

I have looked at the channel and it seems fine because before this error comes it is posting things and so on. And after this error the bot will still listen and answer for example the ?hello or the ?add commands.

Who can enlighten me?

**Comment by kennethtran93** [comment]
I think you would get more response if either you 
a) post your code (excluding token) or a snippet of it, or 
b) join discord and ask there.
c) what discord version? 
d) my premature thinking says it may be a connection issue if Discord or your script has somehow terminated the connection and a reconnect isn't done yet.
