### ISSUE TITLE
ImportError: No module named discord

### ISSUE THREAD

**Issue by Rimmy50** [Rapptz/discord.py#1423]
I downloaded and installed the discord module and I have tried uninstalling and reinstalling it, but I keep getting the above error. I also looked at the folder that contains the python modules and found it there. What am I doing wrong?

**Comment by Harmon758** [comment]
Are you trying to import it using the same Python version that you installed it for?
Or do you have a folder named discord in your project?

For questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.

**Comment by Rimmy50** [comment]
I solved the issue, thanks for the help anyways!

**Comment by senju-dev** [comment]
Great... how?
