### ISSUE TITLE
Inconsistencies in ready statements on rewrite

### ISSUE THREAD

**Issue by JakeMakesStuff** [Rapptz/discord.py#1427]
Hi,

This is a bug I recently reported in the discord.py guild and was told by spoopy to write here too. `on_ready` and `on_shard_ready` seem to be very inconsistent. A good example would be this code here:

```py
import discord
import logging
import os

logging.basicConfig(level=logging.INFO)

client = discord.AutoShardedClient(
    shard_count=3
)

@client.event
async def on_ready():
    print("on_ready works!")

@client.event
async def on_shard_ready(shard_id):
    print(shard_id)

client.run(os.environ.get("TOKEN"))
```

In this code on my bot, `on_ready` gets called multiple times whereas `on_shard_ready` does not get called. However, I was later told by spoopy that is because it is in no large guilds (a test bot at the moment). `on_ready` also should not get called multiple times because it is the final event when all shards are ready from what I have been made aware.

![powershell](https://i.imgur.com/EF2DTOK.png)

Looking forward to a fix,
Jake (JakeMakesStuff#0001)

**Comment by Rapptz** [comment]
I know this issue is old but consistency with these events has been fixed for a while now both in master and in sharding-rework so I'm closing this.
