### ISSUE TITLE
No module named discord.ext; Discord is not a package?

### ISSUE THREAD

**Issue by lychee6** [Rapptz/discord.py#1430]
Trying to run a bot i made in Python but when I run it, it can't get past the first two lines?

Code:
`Traceback (most recent call last):
  File "discord.py", line 1, in <module>
    import discord
  File "C:\Users\Evan\Desktop\bots\discord.py", line 2, in <module>
    from discord.ext import commands
ModuleNotFoundError: No module named 'discord.ext'; 'discord' is not a package`

**Comment by Harmon758** [comment]
Do you have a file or folder named discord in your project?

For questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.

**Comment by lychee6** [comment]
> folder named discord 


Where would I put that? I only have a python script, no other extensions

**Comment by Harmon758** [comment]
I hadn't seen that your file itself was named `discord.py` before I replied.
As I clarified in my edit a few min. later, rename your script to something else besides `discord`.

**Comment by lychee6** [comment]
So I changed the name, and now it's only throwing an error because theres no module called discord. I think that was a step in the right direction, though

**Comment by Harmon758** [comment]
Make sure you're using the same Python version to run the script that you installed discord.py for.

For further help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api).

**Comment by lychee6** [comment]
Im using python 3.7, what version of discord.py should I be using? I just assumed I should install the latest one right?

**Comment by Harmon758** [comment]
If you have other versions of Python installed, make sure you installed discord.py on 3.7 and that you're using 3.7 to run the script.
The async branch of discord.py doesn't support Python 3.7, so you need to use the rewrite branch with websockets 6.0.

**Comment by Kev-in123** [comment]
try running: "pip install discord"  in cmd

**Comment by Stan-1337** [comment]
Do `pip install discord`

**Comment by Stan-1337** [comment]
Or `pip install discord.py`
