### ISSUE TITLE
Cannot install on linux

### ISSUE THREAD

**Issue by kpjhg0124** [Rapptz/discord.py#1435]
root@ubuntu_18:~# python3 -m pip install -U discord.py
Collecting discord.py
  Using cached https://files.pythonhosted.org/packages/97/3c/2a97b47fd8839f8863241857bbd6a3998d1de1662b788c8d9322e5a40901/discord.py-0.16.12.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-2n8cc7wj/discord.py/

Python version is 3.6.5, and enviroment is Ubuntu 18.04 LTS.
Why I cannot install discord.py?

**Comment by Harmon758** [comment]
Have you tried installing setuptools first?

**Comment by AddyPaddy** [comment]
Please install "setuptools"

To do so, type "pip3 install setuptools" in terminal and try again.

**Comment by kpjhg0124** [comment]
Hoo... Thanks!
