### ISSUE TITLE
[Rewrite] CRASH (kills bot) in parse_typing_start

### ISSUE THREAD

**Issue by PikalaxALT** [Rapptz/discord.py#1439]
Exception may be derived from receiving malformed or incomplete data which maps a TextChannel without a guild.  Unclear whether this is due to an incomplete cache or Discord sending malformed data.  Problem appears to be random and may be difficult to replicate in a controlled setting.

Output from systemd

    Jul 20 00:16:40 raspberrypi sh[22854]: await self.ws.poll_event()
    Jul 20 00:16:40 raspberrypi sh[22854]: File "/usr/local/lib/python3.6/site-packages/discord/gateway.py", line 444, in poll_event
    Jul 20 00:16:40 raspberrypi sh[22854]: await self.received_message(msg)
    Jul 20 00:16:40 raspberrypi sh[22854]: File "/usr/local/lib/python3.6/site-packages/discord/gateway.py", line 398, in received_message
    Jul 20 00:16:40 raspberrypi sh[22854]: func(data)
    Jul 20 00:16:40 raspberrypi sh[22854]: File "/usr/local/lib/python3.6/site-packages/discord/state.py", line 823, in parse_typing_start
    Jul 20 00:16:40 raspberrypi sh[22854]: member = guild.get_member(user_id)
    Jul 20 00:16:40 raspberrypi sh[22854]: AttributeError: 'NoneType' object has no attribute 'get_member'

**Comment by khazhyk** [comment]
eventually consistent:tm:

**Comment by khazhyk** [comment]
I just got this starting up my beta bot, wonder if it's due to recent changes?
