### ISSUE TITLE
Can't install functools

### ISSUE THREAD

**Issue by Adytzuma** [Rapptz/discord.py#1455]
C:\Windows\system32>py -m pip install functools
Collecting functools
  Using cached https://files.pythonhosted.org/packages
77054f2cf940ef2acc8a2857e5664045ed75a1c6a/functools-0.
    Complete output from command python setup.py egg_i
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\aaaa\AppData\Local\Programs\Pyt
ackages\setuptools\__init__.py", line 4, in <module>
        import functools
      File "C:\Users\aaaa\AppData\Local\Temp\pip-ins
nctools.py", line 34
        raise TypeError, 'compose expects at least one
                       ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error C:\Users\Adytzu\AppData\Local\Temp\pip-install-mm_xd_m5\functools\

~~
I tried in a normal cmd, same error
~~

**Comment by Harmon758** [comment]
[functools](https://docs.python.org/3/library/functools.html) is part of the Python standard library.

**Comment by Adytzuma** [comment]
Nvm fixed it
