### ISSUE TITLE
Unknown Emoji - '\N{DIGIT ZERO}'

### ISSUE THREAD

**Issue by jedenastka** [Rapptz/discord.py#1456]
Why `await el.add_reaction(msg_here, '\N{DIGIT ZERO}')`
causes error
`discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: BAD REQUEST (status code: 400): Unknown Emoji`
and don't work?

**Comment by Harmon758** [comment]
`'\N{DIGIT ZERO}'` is just the character, `0`, and not an emoji.
The emoji you're probably trying to use is Keycap Digit Zero, which is Digit Zero followed by Combining Enclosing Keycap, i.e. `'\N{DIGIT ZERO}\N{Combining Enclosing Keycap}'`.

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.

**Comment by jedenastka** [comment]
Thank you for help.
