### ISSUE TITLE
how do i have a user give them selfs a role buy typing a command

### ISSUE THREAD

**Issue by blazeresells** [Rapptz/discord.py#1458]
Hi i was wondering how i get a user to give them selves a role buy typing .(role) i cant seem to figure it out can someone help me. im using @bot.command

**Comment by Harmon758** [comment]
https://github.com/Rapptz/discord.py/blob/1863a1c6636f53592519320a173ec9573c090c0b/discord/ext/commands/context.py#L28-L38
http://discordpy.readthedocs.io/en/latest/api.html#discord.Message.author
http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.add_roles
http://discordpy.readthedocs.io/en/latest/api.html#discord.Server.roles
http://discordpy.readthedocs.io/en/latest/api.html#utility-functions

On the rewrite branch:
https://discordpy.readthedocs.io/en/rewrite/ext/commands/api.html#discord.ext.commands.Context.author
https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Member.add_roles
https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Guild.roles
https://discordpy.readthedocs.io/en/rewrite/api.html#utility-functions

For further help using the library, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.
