### ISSUE TITLE
Add an add role method that calls the add role endpoint.

### ISSUE THREAD

**Issue by macdja38** [Rapptz/discord.py#1459]
Race conditions can occur when modifying a member's roles by passing it a list of roles.

For example if two bots attempt to modify a member's roles at the same time by supplying a list the 2nd request will succeed, the first will be overwritten.

This member for example is probably having this issue. 
https://github.com/discordapp/discord-api-docs/issues/635

I suggest adding an add_role method that calls https://discordapp.com/developers/docs/resources/guild#add-guild-member-role

**Comment by Gorialis** [comment]
This is what [`rewrite` already does](https://github.com/Rapptz/discord.py/blob/rewrite/discord/http.py#L688) when in [atomic mode](https://github.com/Rapptz/discord.py/blob/rewrite/discord/member.py#L502-L506) (the default). `async` does not have support for this and likely will not get it.

**Comment by Harmon758** [comment]
Relevant documentation: https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Member.add_roles
For posterity:
https://github.com/Rapptz/discord.py/blob/8d39ab8c8ca041a2d77aa58e12c76c5a3070503e/discord/http.py#L687-L690
https://github.com/Rapptz/discord.py/blob/8d39ab8c8ca041a2d77aa58e12c76c5a3070503e/discord/member.py#L502-L506

**Comment by macdja38** [comment]
Oh, yea I was looking at the default branch.
