### ISSUE TITLE
Adding an optional 'user' field for Emoji

### ISSUE THREAD

**Issue by Galarzaa90** [Rapptz/discord.py#1462]
The API's [emoji object](https://discordapp.com/developers/docs/resources/emoji#emoji-object) contains a user field with user data of the emoji creator.

This field is only available if the `MANAGE_EMOJIS` permission is present. Both in [List Guild Emoji](https://discordapp.com/developers/docs/resources/emoji#emoji-object) and [Get Guild Emoji](/guilds/{guild.id}/emojis/{emoji.id})

It would be nice to have this in the python API as well.

```json
{
    "managed": false,
    "name": "whip",
    "roles": [],
    "user": {
        "username": "Nezune",
        "discriminator": "2269",
        "id": "162070610556616705",
        "avatar": "104be0527d9f897b34814b197b4b3140"
    },
    "require_colons": true,
    "animated": false,
    "id": "255459240037056529"
}
```

**Comment by GenericError** [comment]
Hi mate, I think I was able to add it, although I don't have any code to test it with.
