### ISSUE TITLE
how to know if audio stream is done? or if its playing .

### ISSUE THREAD

**Issue by Dj-jom2x** [Rapptz/discord.py#1467]
Player.is_live this is always false

**Comment by Harmon758** [comment]
[`Player.is_live`](https://discordpy.readthedocs.io/en/latest/api.html#discord.VoiceClient.create_ytdl_player) is an indicator of whether the YouTube or other source is being livestreamed.
What you want are the [`StreamPlayer` operations](https://discordpy.readthedocs.io/en/latest/api.html#discord.VoiceClient.create_stream_player), specifically `player.is_done()` and `player.is_playing()`.

**Comment by Dj-jom2x** [comment]
thats what i need check if the current YouTube playing at bg is done or na.

but its always false..
its playing tho

i tried to print the value is live after start just to check if it goes to true.

should i wrap youtube dl instead and used streamplayer? btw thanks for fast response :)

**Comment by Dj-jom2x** [comment]
i get it now haha

**Comment by Harmon758** [comment]
Like I said, [`Player.is_live`](https://discordpy.readthedocs.io/en/latest/api.html#discord.VoiceClient.create_ytdl_player) indicates if the source is a livestream, not if the audio stream to Discord is playing.
As the [documentation for `create_ytdl_player()`](https://discordpy.readthedocs.io/en/latest/api.html#discord.VoiceClient.create_ytdl_player) states, the operations that can be done on the player that it returns are the same as those for [`create_stream_player()`](https://discordpy.readthedocs.io/en/latest/api.html#discord.VoiceClient.create_stream_player).

For future help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api).
