### ISSUE TITLE
Implement `messages_from`.

### ISSUE THREAD

**Issue by c-edw** [Rapptz/discord.py#1469]
It's possible to filter guild messages from specific users using the following endpoints.
```
/guilds/{}/messages/search?author_id={}&include_nsfw=true&count=25&offset={}
/channels/{}/messages/search?author_id={}&include_nsfw=true&count=25&offset={}
```

This returns JSON structured like so. Messages are ordered most recent descending.
```javascript
{
    "messages": [
        [
            {
                // Message context. 
            },
            {
                // Message context. 
            },
            {
                // A message sent by the user we are filtering. This is always message[2].
            },
            {
                // Message context. 
            },
            {
                // Message context.
            }
        ],
        ...
    ]
}
```

I will be happy to submit a PR for this if the functionality is approved.

**Comment by Harmon758** [comment]
These are undocumented endpoints that bots can't use.

**Comment by c-edw** [comment]
That is true, but it appears that discord.py supports API usage as a user.

**Comment by Rapptz** [comment]
This is the search endpoint. It's not a secret endpoint or anything but it won't be implemented until bots gain the ability to use it since their output will be different.

**Comment by c-edw** [comment]
It's a feature I really need to be able to use this library. I have implemented the API call myself, but I will have to instantiate `discord.Message` with the message ID myself, which is kind of dodgy. The only method to build a `discord.Message` object from a message ID is `get_message`, but this is bot-only.

**Comment by scragly** [comment]
Then don't use it or implement your own setup like you already apparently have.
Breaking Discord TOS by automating user accounts isn't recommended by anyone here, and the support that's present in the lib was from a time where the usage of userbots were not as clean-cut in regards to Discords stance.

**Comment by c-edw** [comment]
Partially implemented it myself, but as I said it's hacky. I was hoping to use the library more elegantly. I will close this since it is unsupported.

**Comment by Znunu** [comment]
Wait, do bots get a 401 or something when trying trying to access this url?
@scragly as if there's anything to support, user accounts and bots are basically identical in how they interact with the API
