### ISSUE TITLE
User.roles is undocumented

### ISSUE THREAD

**Issue by ArendDanielek** [Rapptz/discord.py#1473]
http://discordpy.readthedocs.io/en/latest/api.html#user should contain a variable entry for User.roles

![image](https://user-images.githubusercontent.com/5826345/43492189-b61f1456-94dc-11e8-8315-a1091e088e2a.png)

**Comment by Rapptz** [comment]
User doesn't have a `roles` attribute.

**Comment by ArendDanielek** [comment]
I definitely just used it. Here is a quick repro script:

```
import discord
import asyncio

client = discord.Client()

@client.event
async def on_ready():
    print('Logged in as')
    print(client.user.name)
    print(client.user.id)
    print('------')

@client.event
async def on_reaction_add(reaction, user):
    for role in user.roles:
        print(str(role) + ": " + str(role.id))


client.run('token')
```
output after I add a reaction to a msg in discord
```
$ python UserRolesRepro.py
Logged in as
ZeroObserver
473933308015673365
------
@everyone: 421033509654626315
Admin: 421036180231159838
Zero Engine Writer: 422866783704186881
Zero Engine Developer: 421370400501661696
```
If you want me to take a gif or something I can, but this is definitely a thing.

**Comment by Werseter** [comment]
Just because you call a Member instance user doesn't make it a User class.

**Comment by ArendDanielek** [comment]
Ahhh, this makes sense now. When I was looking at the docs for `on_reaction_add` it uses the name `user` for the 2nd parameter and lists `User` before `Member` in the possible types `user` could be. I don't think I ever looked back after I original read the entry and just assumed the type was `User`. 


![image](https://user-images.githubusercontent.com/5826345/43537464-38b9b302-9574-11e8-9a96-c2a60da8100b.png)
I should have done the further type checking to confirm my assumptions, and that is my bad.

Sorry if my 2nd response came across wrong, I was just trying to provide a repro for something I thought was a simple documentation issue, that I thought I had proof of. I definitely should have included why I thought there was a `roles` attribute in the original issue text, I probably would have gotten a more informative response.
