### ISSUE TITLE
Issue on stopping manually the ffmpeg or YouTubedl

### ISSUE THREAD

**Issue by Dj-jom2x** [Rapptz/discord.py#1477]
song plays .
if you stop it manually..
it will stop and its pretty fine.. but the input console is blocked??

but if song plays .
and let it finished
the input console is back to normal..

does that mean the pipe still alive at the background? still reading and waiting??

its not an issue tho you can start and play another song without worrying for anything.. but my concern here is why the input still blocked if stopped manually?

thanks :)

**Comment by Dj-jom2x** [comment]
i tried discord rewrite version if its gonna change but the problem still persists

```
self._voice.play(discord.FFmpegPCMAudio("http://cabhs35.sonixcast.com:20068/stream;test.mp3"), after=lambda e: print('done', e))
self._voice.is_playing()
#stop after 5 seconds
#for testing
await asyncio.sleep(5)
self._voice.stop()
```

if you stop the player manually .. the console input still blocked.. well you can still read the other inputs but im talking with typing on console. it blocked you to type

whats the blocked input for? 

if you let it finish the input on console is fine.

but why?

i feel like the popen subprocess of ffmpeg still at the background joy.

**Comment by Werseter** [comment]
If I remember correctly, the ffmpeg itself had a problem, of actually not blocking the input, but rendering the console unable to display characters correctly on Linux . Blindly typing in `reset` and pressing enter could confirm this.On Aug 2, 2018 4:56 AM, Dj-jom2x <notifications@github.com> wrote:i tried discord rewrite version if its gonna change but the problem still persists
self._voice.play(discord.FFmpegPCMAudio("http://cabhs35.sonixcast.com:20068/stream;test.mp3"), after=lambda e: print('done', e))
self._voice.is_playing()
#stop after 5 seconds
#for testing
await asyncio.sleep(5)
self._voice.stop()

if you stop the player manually .. the console input still blocked.. well you can still read the other inputs but im talking with typing on console. it blocked you to type
whats the blocked input for?
if you let it finish the input on console is fine.
but why?
i feel like the popen subprocess of ffmpeg still at the background joy.

**Comment by Dj-jom2x** [comment]
one more thing..

when you stop it manually. it only execute the first line of the after callback.

```..., after=lambda e: self.safe_callback(message))
```

i add this on my callback..
print ("done")
print("can you call me")

the 2nd print only works if you let the player stop his streaming.. example a direct video of YouTube streaming is ended.

i also try to set a variable true false just to see if maybe it because ffmpeg is blocking it

self._test = False


yeah test still true.
it really doesn't execute it all.

i also tried this

```
 after=lambda e: self._bot.loop.call_soon_threadsafe(self.safe_callback(message)))
```

i also tried this

after = self.safe_callback(message)

all same result
