### ISSUE TITLE
Event loop is closed

### ISSUE THREAD

**Issue by abrooks9002** [Rapptz/discord.py#1490]
I just started trying to create a discord bot, but can't get passed this error. Any help would be appreciated!

**Here's the error:**
runfile('C:/Users/jaust/untitled2.py', wdir='C:/Users/jaust')
Traceback (most recent call last):

  File "<ipython-input-36-a2f8de85e622>", line 1, in <module>
    runfile('C:/Users/jaust/untitled2.py', wdir='C:/Users/jaust')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/jaust/untitled2.py", line 24, in <module>
    client.run(TOKEN)

  File "C:\ProgramData\Anaconda3\lib\site-packages\discord\client.py", line 556, in run
    task = asyncio.ensure_future(self.start(*args, **kwargs), loop=loop)

  File "C:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 519, in ensure_future
    task = loop.create_task(coro_or_future)

  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 282, in create_task
    self._check_closed()

  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 357, in _check_closed
    raise RuntimeError('Event loop is closed')

RuntimeError: Event loop is closed

**Here is the code:** 
import discord

TOKEN = 'token'

client = discord.Client()

@client.event
async def on_message(message):
    # we do not want the bot to reply to itself
    if message.author == client.user:
        return

    if message.content.startswith('!hello'):
        msg = 'Hello {0.author.mention}'.format(message)
        await client.send_message(message.channel, msg)

@client.event
async def on_ready():
    print('Logged in as')
    print(client.user.name)
    print(client.user.id)
    print('------')

client.run(TOKEN)

**Comment by abrooks9002** [comment]
I'm not sure how to do the thing where it puts the code in that grey box thingy.

**Comment by Harmon758** [comment]
Are you running this script multiple times in the same REPL environment?
[`Client.run`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Client.run) closes the event loop after execution, so you won't be able to do that with any environment that keeps state.

Also, it seems like you're using the rewrite branch, so [`Client.send_message`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.send_message) [won't work](https://discordpy.readthedocs.io/en/rewrite/migrating.html#models-are-stateful).
You'll want to use [`TextChannel.send`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.TextChannel.send) instead.
See the updated examples on the rewrite branch.

For further help using the library, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.
Also, what you want are [code blocks](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).
