### ISSUE TITLE
connection problem

### ISSUE THREAD

**Issue by ttatanepvp123** [Rapptz/discord.py#1495]
hello I have a problem with my bot
when I connect with the function client.run ("e-mail", "password")
the bot connects is this deconnect to infinity
![screen](https://zupimages.net/up/18/32/6ryl.gif)
code :
```python
...
...
Prefix = "sig!"
client = Bot(command_prefix=Prefix)

...

@client.event
async def on_ready():
    await client.change_presence(game=discord.Game())
    await client.change_presence(game=discord.Game(name=Prefix+"help | SERVER : "+str(len(client.servers))), status="online")
    print("bot ready")

client.run("****", "***")
```
please help me

**Comment by Hornwitser** [comment]
Automating normal user accounts [is forbidden](https://support.discordapp.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-).  Create a bot account on the [discord developers dashboard](https://discordapp.com/developers/applications/) and use that instead.

**Comment by ttatanepvp123** [comment]
OK, thanks
