### ISSUE TITLE
Not using the token correctly?

### ISSUE THREAD

**Issue by kian7890** [Rapptz/discord.py#1501]
so, my should be working but it doesnt want to use the token? (the "print("point x")" is used for my personal debugging). the program shows that it gets to my point 3 but doesnt go any further. its getting stuck on the token part of the code and i dont know why? Im using python 3.6.6 with the newest version of discord.py

```
import discord
import asyncio
from discord.ext.commands import bot
from discord.ext import commands
import time
print("point 1")
client = commands.Bot(command_prefix = "!")
print("point 2")
Client = discord.Client()
print("point 3")
client.run("*correct token would be here but i removed it*")
print("point 4")

@client.event

async def on_ready():
	print("yoyo wassup")
print("point 5")
@client.event

async def on_message(message):
	if message.content == "xx":
		await client.send_message(message.channel, "xxxxxx")
print("point 6")
```

**Comment by Hornwitser** [comment]
`client.run()` starts the bot and does not return until the bot has disconnected/logged out.  It should therefore be done last, as warned about in the documentation.

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.

PS: use triple backticks (```)  for code blocks

**Comment by kian7890** [comment]
ahh ok. thanks. ill try that
