### ISSUE TITLE
[rewrite] Negative latencies with AutoShardedBot?

### ISSUE THREAD

**Issue by Diniboy1123** [Rapptz/discord.py#1502]
Hi,

We are using a simple AutoShardedBot currently, and especially if the ws latency is huge, sometimes it is negative:

![image](https://user-images.githubusercontent.com/29148882/43995484-9a992aac-9dae-11e8-9efb-f251073fc5fd.png)

And the bot is up and running for 2 days, so it isn't the first run's behaviour....

What can I do?

**Comment by Hornwitser** [comment]
This should be fixed by bd46708.  Could you update your discord.py install and test it?

**Comment by Diniboy1123** [comment]
Works well now, thanks!
