### ISSUE TITLE
Having trouble with sending messages

### ISSUE THREAD

**Issue by u296** [Rapptz/discord.py#1510]
I am quite new to discord.py and my bot was working quite well, I realised there was an update and I installed it. I then got tons of errors in python 3.7, in the source code, and websockets. I reverted back to 3.6 and importing the library worked just fine. But now I'm stuck, every time I try to send a message with my bot, it results in the following `AttributeError`:

`Ignoring exception in command add
Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\me\Desktop\programming\.py files\Projects\DiscordBot\DiscordBot.py", line 71, in add
    await ctx.send(Sum)
AttributeError: 'str' object has no attribute 'send'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\ext\commands\bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\ext\commands\core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\ext\commands\core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'str' object has no attribute 'send'`

Does anyone know why ctx gets passed in as a string? please help.

the code looks like this:
`import discord
import os
import ImageDownload
from discord.ext import commands

bot = commands.Bot(command_prefix='bot ', description='hello there')

@bot.event
async def on_ready():
    print('Logged in as: ' + bot.user.name)
    print('With user id: ' + str(bot.user.id))
    print('--------------------------------')
...
...
...
@bot.command()
async def add(ctx, *args: float):
    Sum = 0
    
    for num in args:
        Sum += num
        
    if Sum - int(Sum) == 0:
        Sum = int(Sum)
        
    await ctx.send(Sum)
...
...
...
bot.run(token)`

**Comment by Harmon758** [comment]
In the future, you need to share the relevant code for anyone to help you.
However, from what I can tell, you're using the async branch of discord.py, but trying to use syntax from the rewrite branch.
If the issue isn't that you have the wrong branch installed, then you need to show your code for the add command for any further help.

As for issues using the async branch with Python 3.7, see #1249 and #1401.

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.
