### ISSUE TITLE
Kwargs in client commands.

### ISSUE THREAD

**Issue by Zac-Stewart** [Rapptz/discord.py#1513]
Hi,

I was messing around with my bot today and was struggling with inputting kwargs from discord.
My question is: what would I have to type on discord to get python to print:
``` python
1
(2, 3, 4, 5)
{'a': 6, 'b': 7, 'c': 8}
```
or something similar

This is the basic structure of code I have
``` python
@client.command(name="f", pass_context = True)
async def f(ctx, a, *args, **kwargs):
    print(a)
    print(args)
    print(kwargs)
```

Thanks in advance.

edit:
Wrong brackets for dictionary. Not the error though.

**Comment by Gelbpunkt** [comment]
A python list is not a hash
```py
{'a': 6, 'b': 7, 'c': 8}
```
Type `{prefix}f 1 2 3 4 5`

Kwargs don't work except you write your own command parser

**Comment by Zac-Stewart** [comment]
That really sucks.

**Comment by Gelbpunkt** [comment]
A very basic idea is this
```py
command = "help --less True --flags user"
args = {}
command_name = command.split()[0] 
for c in command.split():
    if c.startswith("--"):
        args[c.lstrip("--")] = command.split()[command.split().index(c) + 1 ]

return command_name, args
```

**Comment by Zac-Stewart** [comment]
I will explore that.

**Comment by Harmon758** [comment]
To expound, the commands extension doesn't support variable-length keyword argument lists like that.
This is how it handles parameters: https://github.com/Rapptz/discord.py/blob/1863a1c6636f53592519320a173ec9573c090c0b/discord/ext/commands/core.py#L297-L321 with the `param.kind` value being [`inspect.Parameter.kind`](https://docs.python.org/3/library/inspect.html#inspect.Parameter.kind).

As you can see, `VAR_KEYWORD` (`**kwargs`) isn't handled.
`POSITIONAL_OR_KEYWORD` is just a specified positional parameter, like `a` in your example.
`VAR_POSITIONAL` (`*args`) and `KEYWORD_ONLY` (`*, kwarg`) actually consume the input until the end, returning it as a tuple of arguments, that were separated by whitespace, and a string, respectively.

In your example, the first argument of your command is passed as `a`.
The rest of the input is passed as a tuple of arguments as `args`.

**Comment by Zac-Stewart** [comment]
Thanks for all the suggestions, it is now working :)!

**Comment by PG-Development** [comment]
`def parseKeywords(kwargs: dict, info: str, ctx):
    args = []  # "days=1 hours=1" - input
    final = {}  # {"days": 1, "hours": 1} - desired output
    args = info.split(" ")  # [days=1, hours=1]
    splitArgs = []
    for item in args:
        splitArgs = item.split("=")
        final[splitArgs[0]] = splitArgs[1]
    for item in final.keys():
        if item in kwargs.keys():
            try:
                if kwargs[item] == "str":
                    final[item] = str(item)
                elif kwargs[item] == "int":
                    final[item] = int(item)
                elif kwargs[item] == "float":
                    final[item] = float(item)
            except TypeError:
                await ctx.send(f"Invalid type for {str(item)}, that parameter must be of type {kwargs[item]}")
                return False
        else:
            await ctx.send(f"Not a valid kwarg. Valid kwargs are: {kwargs.keys()}")
            return False
    return final`

Excuse messy code, but i think this could work as a very preliminary parser. You'd pass to it a string containing the arguments, and a dict containing possible kwargs and their types. It would return a dictionary I guess. I found this to be easier than using argparse but im a simpleton so
