### ISSUE TITLE
ModuleNotFoundError: No module named 'discord'

### ISSUE THREAD

**Issue by Arthurdw** [Rapptz/discord.py#1515]
Hello, I've installed Discord.py successfully but when I try to run the "Import discord" its says ModuleNotFoundError: No module named 'discord'
When I go to Project Interpreter it says Discord.py but I'm still unable to run the command.
![75e50eb3a79fd7dd4e5db80ecb81b512](https://user-images.githubusercontent.com/38541241/44201888-ac968e80-a14a-11e8-937b-1d5cefadb813.png)
IMG link: https://i.gyazo.com/75e50eb3a79fd7dd4e5db80ecb81b512.png

**Comment by SilicalNZ** [comment]
async will not work on 3.7.  See #1249 and #1401

**Comment by Harmon758** [comment]
Are you importing it on the same Python version that you installed it on? i.e. Python 3.7
Also, `Import discord` with a capital I will raise a syntax error.
And as @SilicalNZ noted, the async branch will not work as is with your current setup on Python 3.7.

For further help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by Arthurdw** [comment]
@SilicalNZ @Harmon758 
 Do you suggest that I re-install Python from 3.7 to 3.5?

**Comment by ItWasAllIntended** [comment]
@Arthurdw Why would you install 3.5? 3.6.6 is the latest version that works with dpy

**Comment by Arthurdw** [comment]
@ItWasAllIntended The suggested version is 3.4 and 3.5.

I installed python 3.5 and it works now.
(had to redo the discord.py 2)
![pythonversion](https://user-images.githubusercontent.com/38541241/44214265-09587000-a170-11e8-8893-9f708499315a.png)

**Comment by ItWasAllIntended** [comment]
@Arthurdw For a start [3.5.6](https://www.python.org/downloads/release/python-356/) so if you're going to get 3.5 use that. And second of all why do you think 3.4 and .3.5 are recommended. The Readme states 3.4.3+. There is no reason not to use 3.6.6 and you would be losing features and performance not using it.

**Comment by Arthurdw** [comment]
@ItWasAllIntended Thanks, I'm now running perfectly on 3.6.6!
I didn't use these code's tho for my bot.

**Comment by Arthurdw** [comment]
*update for anyone who sees this.
Async will work till version 3.6.x.
If you want to have 3.7.x you will have to go the the rewrite libary, the rewrite libary has some other positive things too but it sacrifices the python 2.7.x support.

**Comment by CapnS** [comment]
The version of the library on pip does not work with python 3.7, you'll either have to downgrade your python or use the rewrite branch of the library. 

To install the rewrite version of the library, use this command:
```
pip install -U git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]
```

In the future, please don't necro issues, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by slavish-coder** [comment]
Im using Atom and it shows this error 
![EEEEEEEEEEEEEEEEEEEEEEEEEEEEE](https://user-images.githubusercontent.com/87075843/124779928-00ea2280-df64-11eb-8c01-00ebee371134.PNG)

**Comment by mesub7** [comment]
Please don't necrobump old, closed issues. 

If you require support visit the [discord server](https://discord.gg/dpy) or go to the [discussion page](https://github.com/Rapptz/discord.py/discussions).
