### ISSUE TITLE
TypeError: 'dict' object is not callable

### ISSUE THREAD

**Issue by H3X3DTech** [Rapptz/discord.py#1516]
I am making my bot and for all my commands it says _TypeError: 'dict' object is not callable_

`@Bot.commands(pass_context=True)
async def user(ctx, user: discord.Member):
    embed = discord.Embed(title="{}'s user info!".format(user.name), description="Here's what I could find ecksdee", color=0x00ff00)
    embed.add_field(name="User Name", value=user.name, inline=True)
    embed.add_field(name="I.D.", value=user.id, inline=True)
    embed.add_field(name="Status", value=user.status, inline=True)
    embed.add_field(name="Joined", value=user.joined_at, inline=True)
    embed.add_field(name="Created At", value=user.created_at, inline=True)
    embed.set_thumbnail(url=user.avatar_url)
    await bot.say(embed=embed)`

**Comment by crrapi** [comment]
You want `@Bot.command()`, not `@Bot.commands()`.

**Comment by H3X3DTech** [comment]
ok thanks

**Comment by H3X3DTech** [comment]
Thank you this as worked!

**Comment by Harmon758** [comment]
For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.
