### ISSUE TITLE
Python 3.7 to 3.5

### ISSUE THREAD

**Issue by Arthurdw** [Rapptz/discord.py#1517]
Hello.
I started my project but I was needed to uninstall Python 3.7 and install 3.5.
After doing this I tried again and everything seemed to work a bit but when I tried to run it said this:
```
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00000dcc (most recent call first):
```

When I tried to change the interpreter this showed up:
![11d8cc6c1966e3ec8e26686450b42fc3](https://user-images.githubusercontent.com/38541241/44223004-a920f880-a186-11e8-9d7e-2d9401cf3f25.png)

When I wanted to look if it stated the Python 3.5 too it didn't state it.

**Comment by Harmon758** [comment]
This is not an issue with discord.py.
A simple Google search comes up with https://bugs.python.org/issue27054.

As I've already told you, for further help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.
