### ISSUE TITLE
Author.top_role not updating on role hierarchy changes

### ISSUE THREAD

**Issue by Tigerism** [Rapptz/discord.py#1518]
Hello. I've moved one role that I have to the top of the roles in my server, and when I print ``author.top_role``, it shows the old role.

Screenshot 1: https://cdn.discordapp.com/attachments/305571047535673345/479841129341255681/unknown.png

Screenshot 2:
https://cdn.discordapp.com/attachments/305571047535673345/479841165114605568/unknown.png

I added an ``on_guild_role_update`` event to track if the role positional update gets fired, and it does, so the members' roles aren't updated when ``on_guild_role_update`` fires.

**Comment by Rapptz** [comment]
This should have been fixed.
