### ISSUE TITLE
Is There A Way I Can Put This Command On A Timer?

### ISSUE THREAD

**Issue by DemonicKyle** [Rapptz/discord.py#1519]
I'm not especially skilled in python so bear with me here.I'm making a naruto based bot and i would like to know, is there a way I can make my command stop when a timer ends?
Here's My Code

```py
@bot.command(pass_context=True)
async def enroll(ctx):
    await bot.say(a)
    @bot.command(pass_context=True)
    async def village(ctx, *args):
        await asyncio.sleep(120)
            village = ' '.join(args)
            if (
    village != '1' and village != '2' and
    village != '3' and village != '4' and
    village != '5' and village != '6'
    ):
                await bot.say('Thats Not Even A Village! Ya Know!')
            
```

**Comment by x3l51** [comment]
Yes. You can use `return` or `break` for this, depending on where you want to use it.

Is the code snippet completely unrelated and random?

**Comment by Harmon758** [comment]
I'm not sure what's going on with your indentation or what exactly it is that you're asking.
If you want your command to stop execution at a certain point, you can just `return` from the function. Note that using `break` is exclusive to exiting loops, of which I don't see any in your snippet, and does not stop execution of anything in the command/function after the loop.
Alternatively, if you want to run a certain task every once in a while, you should look into background tasks. See the background_task.py example.

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.

**Comment by Arthurdw** [comment]
Yes add this at the start:
`@commands.cooldown(1, 30, commands.BucketType.user)`
Works for me.

**Comment by Harmon758** [comment]
@Arthurdw Please don't spoon-feed without any explanation or reference.

The relevant documentation for command cooldowns: https://github.com/Rapptz/discord.py/blob/1863a1c6636f53592519320a173ec9573c090c0b/discord/ext/commands/core.py#L907-L935 Also see https://github.com/Rapptz/discord.py/commit/cd0de57d13b15f709aaacf78ce611dd87e0784ce.
