### ISSUE TITLE
Status update

### ISSUE THREAD

**Issue by Arthurdw** [Rapptz/discord.py#1527]
Hey, is there an option to let the bot update the status after an x amount of seconds?
I'm asking this because my bot has a `bot.get_all_members` feature in the status and if it stands in `async def on_ready():` it doesn't update the member count.

**Comment by Inspectiver** [comment]
You can run it in a [background task](https://github.com/Rapptz/discord.py/blob/master/examples/background_task.py)

**Comment by Harmon758** [comment]
As you've been told repeatedly, GitHub issues are not the proper place for asking for help using the library. They are for issues with the library itself. For further help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.
