### ISSUE TITLE
Error when upgrading with pip

### ISSUE THREAD

**Issue by mephasor** [Rapptz/discord.py#153]
Hello, everything worked fine last week, but when I try to upgrade to the current version, I am getting errors. The same happens when I try to install the current version of the API on a different machine. The log file created can be found here: 

http://pastebin.com/S8Ek7hkN

**Comment by ZetaHunter** [comment]
Read library requirements in readme before creating an issue.

**Comment by mephasor** [comment]
The discord API thread helped. Packages that had to be installed: 

`python3.5-dev build-essential libssl-dev libffi-dev`
