### ISSUE TITLE
Specify that Member.history() (and User.history()) return DM message histories and not messages on servers

### ISSUE THREAD

**Issue by qxu21** [Rapptz/discord.py#1533]
I tried to retrieve one member's messages with `Member.history()` and no messages came up. I asked on the library Discord and Vex#3110 told me that these retrieve DM histories. Could this be specified in the docs? Right now it just says `Member.history()` returns `an AsyncIterator that enables receiving the destination’s message history.` which is the same thing listed under `Channel.history()`.

**Comment by crrapi** [comment]
`Members`/`Users` are destinations in addition to `Channels`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by LyricLy** [comment]
Member.history implies using a Member as a destination, which is only ever used for DMs.
