### ISSUE TITLE
No event for if and only if a member was kicked from a server.

### ISSUE THREAD

**Issue by AraHaan** [Rapptz/discord.py#154]
You guys might be thinking ``You can get this in the on_member_remove`` event and check if a member was banned and if so return nothing. But in the event if a ``member`` is ``kicked`` or if the ``member`` left at their will it would mix the 2 up and log them as ``kicked`` even if they left at their will. So as such if you want to log raw ``kicks`` you cant right now sadly or easily. I am requesting for a event ``on_member_kicked`` to be created. so that way it can help resolve this issue.

**Comment by Rapptz** [comment]
There is no internal event for if a member is kicked. As far as the Gateway Protocol is concerned a kick and leaving is GUILD_MEMBER_REMOVE.
