### ISSUE TITLE
on_raw_reaction_add confusion and arguments 

### ISSUE THREAD

**Issue by myusernamewastakenx2** [Rapptz/discord.py#1543]
i was recently on the async branch and decided to switch to rewrite almost purely because of "on_raw_reaction_add" because i was making a verification bot based of reactions but ive totally lost myself in the process ive read through the documentation but confused myself even more in the process, i cant find any video sources of rewrite either anyway heres my current code 
`import discord
from discord.utils import get

TOKEN = '<omitting token>'

client = discord.Client()

@client.event
async def on_ready():
    print('Bot Ready!')

@client.event
async def on_raw_reaction_add(message_id, user_id, channel_id, emoji):
    if channel_id == 482716421047189506:
        role = discord.utils.get(guild.roles, name="member")
        member = user_id
        await member.add_roles(role, reason='Verified')
client.run(TOKEN, bot=True, reconnect=True)`

**Comment by crrapi** [comment]
`on_raw_reaction_add` takes one argument, the "payload", which is a [RawReactionActionEvent](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.RawReactionActionEvent). This has attributes such as `emoji`, `user_id`, etc. Reading the [relevant documentation](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.on_raw_reaction_add), you would have figured this out.

**Comment by ItWasAllIntended** [comment]
Questions like this are also more suited to the [discord.py server](https://discord.gg/r3sSKJJ)

**Comment by withinmyself** [comment]
@myusernamewastakenx2 
If you look at the documentation regarding RawReactionActionEvent everything in there is accessible by doing payload.message_id or payload.channel_id.   Knowing this you should be able to navigate to whatever you need.
