### ISSUE TITLE
Access a message.content on a synchronous function #question

### ISSUE THREAD

**Issue by dikano** [Rapptz/discord.py#1544]
hi , im sorry for the post i tried to resolve this problem for some days with no luck 
i want to either call the async on_message function or some how access the 'Signal' variable ( its basically a list which  contains  some of the message content ) outside the async function.
this is how my code looks like 
i just need the Signal value whenever a new message is posted on a channel
```
import asyncio
from syncer import sync
import discord
import os
import time
from discord.ext import commands

class A:

    TOKEN = "XXXXXXXXX"
    client = commands.Bot(command_prefix = ".")


    @client.event
    async def on_message(message):
        autor = message.author
        content = message.content
        channel = message.channel.id
        while ( channel == 'XXXXXXXXXXXXXX' ):
            if #some filters 
                Signal =[message.content]

                return Signal #'till here the code functions and i get the list' 

 bot =A()
 tasks = asyncio.ensure_future(bot.on_message())
 loop =asyncio.get_event_loop()
 loop.run_until_complete(asyncio.gather(*tasks))

 bot.client.run(bot.TOKEN)
```
the error says : 

> loop.run_until_complete(asyncio.gather(*tasks)) AssertionError: yield from wasn't used with future

i tried to use an async to sync wrapper called [sync](https://github.com/miyakogi/syncer) : 

```
bot =A()
b = sync(bot.on_message(message))
assert  Signal ==b()
```
i get 

> b = sync(bot.on_message(message)) NameError: name 'message' is not defined Unclosed client session client_session:

when i define message :

```
message = {}
bot =A()
b = sync(bot.on_message(message))
assert  Signal ==b()
```
 i get 

> b = sync(bot.on_message(message))
> TypeError: on_message() takes 1 positional argument but 2 were given Unclosed client session > > 
> client_session:

any help is appreciated

**Comment by Hornwitser** [comment]
Calling the `on_message` handler yourself doesn't make sense.  If you want to access some data you got in `on_message`, store it in some variable.  For example

```python
from discord.ext import commands

# I've removed the A class as it makes no sense.

# To avoid confusion a commands.Bot instance should be called bot.
bot = commands.Bot(command_prefix = ".")

# Some global variable to pass data through.
my_list = []

@bot.event
async def on_message(message):
    # on_message is invoked by the bot instance when ever a message
    # is received by the library.  Doing a while loop in here doesn't 
    # make any sense.  It also isn't necessary to store a reference
    # to message.channel.id in order to compare with it.  This can be
    # done directly, in the condition.
    
    if message.channel.id = '111122223333':
        # Code here is invoked every time a message is received in the
        # channel with that id
        my_list.append(message.content)

# Now a bot command or anything really, can do stuff with my_list
@bot.command()
async def list_last_content():
    while my_list:
        content = my_list.pop(0)
        await bot.say(content)

bot.run(TOKEN)
```

It's still unclear what you want here.  You are not showing the relevant code, or saying anything about _why_ you need this.  If you want to do something with the message content in `on_message` why can't you do it in `on_message`?

---

For further questions like these, consider joining either the [official discord.py server]( https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) as the readme recommends.

**Comment by dikano** [comment]
first of all thanks for the reply 
im writing a code where i need the value of the variable defined 'Signals' every time a message is posted on that channel
the code is supposed to act based on the content of that list .
like for example if Signal[0] == something do things but its already long and contains many functions i cant write it under on_message function.
the goal is to access that list and store it outside the async function
ah and the rest of the code have nothing to do with discord the bot exists only to get that message
many thanks again im a noob here , any help is appreciated

**Comment by mental32** [comment]
Are you trying to write a command handler in on_message?

**Comment by dikano** [comment]
no commands are needed for the bot 
the discord bot is supposed to only read the message and pass it to the rest of the script 
the rest of the script Handels another websites api 
for that i need to store and access that Signal variable whenever a new message is posted

**Comment by Hornwitser** [comment]
You are not showing any relevant code to what you're trying to accomplish.  We cannot read your mind, what is the issue with the solution I posted?

**Comment by dikano** [comment]
@Hornwitser  the rest of the code is written synchronously 

    def Signal_Filter (Plattform):

        # i supposed to append the Signal into master_liste

            master_liste = [S1, S2,S2, S3]
            Plattform_list = [x for x in master_liste if x[0] == Plattform ]

            return Plattform_list


    started = False
    bm = BinanceSocketManager(client)
    

    for x in Signal_Filter('Binance'):
        def process_message(msg):
            print(msg['p'], msg['s'])
            if  float(msg['p']) >= float(x[2]):
                print('sell')
                bm.stop_socket(conn_key)

        conn_key = bm.start_trade_socket(x[1], process_message)
        if not started:
            started = True
            bm.start()

**Comment by dikano** [comment]
if i append Signal to my_liste like you did above will it work if i call my list under a sync function like the one i posted above ?

**Comment by Hornwitser** [comment]
Unless you invoke the code that does start_trade_socket afterwards it wouldn't do anything.  Have you considered invoking the code that does the bm.start_trade_socket call in `on_message` instead of doing this weird passing through globals?

**Comment by dikano** [comment]
i have considered it yes if i cant find a better solution
what if i dump the list in a text file and read from it later ?
and maybe make it reads the text every time the size changes

**Comment by mental32** [comment]
Do what hornwitzer proposed or whatever you want but close this issue since it’s not an actual library issue
