### ISSUE TITLE
Discord Embed Color get's str error

### ISSUE THREAD

**Issue by Spyder-exe** [Rapptz/discord.py#1553]
Hey, I'm trying to make the colors of my embeds random, so I made this:

`import random

col = lambda: random.randint(0,255)

colour = '0x' + '%02X%02X%02X' % (col(),col(),col())`

So that generates a random Hexadecimal colour with the added "0x" in front of it for discord embed

However when testing this out in an embed I get the following error
`Expected discord.Colour, int, or Embed.Empty but received str instead.`

However if I print the generated hex (for example: 0x36AFDF )
And I replace the embed parameter `color=colour` by `color="0x36AFDF"`

It will work.

How can I format my code so that I can randomely generate a hex colour but avoid the str error?

**Comment by fixator10** [comment]
Why not use random int?
`colour=random.randint(0, 16777215)`
(0 = `#000`, 16777215 = `#FFF`)

**Comment by Spyder-exe** [comment]
@Gorialis Oh alright, yeah I never quite understood what 0x whas meant for, I researched a bit and that was what I found http://forum.sa-mp.com/showthread.php?t=69755, which gives no further explanation
So I thought you know, make a random Hex colour, and just add "0x" in front because that was what is required

Anyway thanks for the help!
