### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'mention'

### ISSUE THREAD

**Issue by sean-james** [Rapptz/discord.py#1556]
All of a sudden `mention` stopped working in my code which worked before? Have there been any changes to discord.py?

**Comment by Harmon758** [comment]
You need to show the full traceback and relevant code for anyone to help you diagnose the issue.

This also likely isn't an issue with the library itself, and for further help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by ItWasAllIntended** [comment]
GitHub issues are for issues with the library. We'll be happy to help at the [D.py server](https://discord.gg/r3sSKJJ). Just for when you join, it helps to post the code you're having trouble and the error that goes along with it. Discord.py and Python version can also be helpful,

**Comment by sean-james** [comment]
No matter I've fixed it.
