### ISSUE TITLE
How to check if entered argument is a valid emoji

### ISSUE THREAD

**Issue by doodthedoodthedood** [Rapptz/discord.py#1557]
Is there any way to check if an argument is a keyword for an emoji?

**Comment by Werseter** [comment]
What do you mean by _a keyword_ for the emoji? If you refer to the :emoji: syntax, the character is converted to Unicode, sometimes a single character, sometimes a few (I.e numbers), spread among the Unicode table in quite a few spots.I remember somebody once mentioned in a similar issue that there is an external library trying to handle them tough, but that's out of d.py scope.On Sep 2, 2018 16:21, doodthedoodthedood <notifications@github.com> wrote:Is there any way to check if an argument is a keyword for an emoji?

**Comment by Vexs** [comment]
While I'm not entirely sure what you mean, if you want to check if some string is a custom emoji, the format for those is `<:name:id>` which can be simply regexed. If you want to check if it's a standard unicode emoji, I've taken the liberty of compiling a dict of emoji names to unicode values [here.](https://gist.github.com/Vexs/629488c4bb4126ad2a9909309ed6bd71)

As a note, github issues aren't really for questions like this. For future questions like this, you should join the [official discord.py server](https://discord.gg/r3sSKJJ) for help, as the README recommends.
