### ISSUE TITLE
How to control a non-bot account that has authorised my app with OAuth2?

### ISSUE THREAD

**Issue by retnikt** [Rapptz/discord.py#1560]
I have authorised my app with OAuth 2 and got a token `Ll4MS********************PYu1e`.
My client ID and secret are `4864**************` and `-Vzz************************Agod`
How do I use these in `client.login` to login and use the API to send messages, change my status, etc, without using the Discord app?

**Comment by Hornwitser** [comment]
You don't.

The only things you can do through the OAuth2 API is listed under scopes [in the Discord API documentation](https://discordapp.com/developers/docs/topics/oauth2) (note that the endpoints for the rpc scopes are not publicly available.) 
 There's no way to send messages on a user's behalf through the OAuth2 API.

**Comment by crrapi** [comment]
Keep in mind that [Selfbots are against the Discord Terms of Service](https://support.discordapp.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-).
