### ISSUE TITLE
how do i install the rewrite? readme is incorrect

### ISSUE THREAD

**Issue by Liteb0t** [Rapptz/discord.py#1561]
the readme for the rewrite shows how to install the old discord.py, but i would like to know what to type to get the rewrite version

**Comment by shivaco** [comment]
`pip install -U git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]`

**Comment by Liteb0t** [comment]
now it says

Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/Rapptz/discord.py C:\Users\coloc\AppData\Local\Temp\pip-install-ucy3zv45\discord.py
Cannot find command 'git' - do you have 'git' installed and in your PATH?

**Comment by mrc0mmand** [comment]
Well, that message is self-explanatory - you need to install and correctly setup `git`[0]. Anyway, this is not a discord.py related issue, so I'd advise to use the official [discord.py server](https://discord.gg/r3sSKJJ) if you encounter any further problems.

[0] https://help.github.com/articles/set-up-git/
