### ISSUE TITLE
Suggestion: Reraise Errors

### ISSUE THREAD

**Issue by BluePhoenixGame** [Rapptz/discord.py#1562]
I have some code that i would like to safely close when i do `ctrl + c` or when it crashes. Therefor i think there should be an option in the `client.run` to reraise errors. This might be helpful for other kind of things as well.

**Comment by Rapptz** [comment]
Use a [`finally`](https://docs.python.org/3/tutorial/errors.html#defining-clean-up-actions) block.

**Comment by BluePhoenixGame** [comment]
I didn't think of that, thanks!
