### ISSUE TITLE
Unclosed client session Error

### ISSUE THREAD

**Issue by MyNameSolar** [Rapptz/discord.py#1567]
Hi, I am trying to make a discord bot, when I attempt to run it, the following error comes up:

Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x036EF8B0>

This is my code:
```
import discord
from discord.ext import commands
from discord.ext.commands import Bot
import asyncio

Bot = commands.Bot(command_prefix=";")

@Bot.event
async def on_ready():
    print ("Solar bot is ready")
    print ("I am running on" + bot.user.name)
    print ("With the ID: " + bot.user.id)

    bot.run("REMOVED")
```

I really need help, no other sites have fixed it. And please be gentle lol, I am very new to scripting

**Comment by crrapi** [comment]
Your `bot.run()` is inside the `on_ready` function. You'll want to unindent it. Also, in your case, using `bot.run()` will raise a NameError because your `commands.Bot` instance is capitalized.

**Comment by MyNameSolar** [comment]
Thanks, the Unclosed client session error is fixed but now I am getting this:

 File "C:\Users\Conor\Desktop\SolarBot\bot.py", line 8, in <module>
    bot = commands.bot(command_prefix=";")
TypeError: 'module' object is not callable

Sorry, I'm new :)

**Comment by MyNameSolar** [comment]
Nevermind, I've fixed it, thank you though, you have saved me lot's of time :D
