### ISSUE TITLE
stream from create_ytdl_player crashes consistently

### ISSUE THREAD

**Issue by edasaki** [Rapptz/discord.py#157]
I've been unable to get a full playthrough of a youtube video using the ytdl player

It always stops during the stream with this error:

[tls @ 0000006179cc62a0] Error in the pull function.
[matroska,webm @ 0000006179cdb640] Read error
[tls @ 0000006179cc62a0] The specified session has been invalidated for some reason.
    Last message repeated 1 times

When I try avconv by setting use_avconv=True, the output shows this:
https://r4---sn-q4fl6n7d.googlevideo.com/videoplayback?xxxxx[bunch of random stuff]xxxxx: Protocol not found

and never plays anything.

Does anyone know what's wrong? The create_ffmpeg_player function works fine, it's just when I try to stream from Youtube that I get issues.

The code I'm using for it is very standard; just create the ytdl player with a Youtube URL and then start() the player.

Others have mentioned that it may just be because ffmpeg has issues with streams. If this is the case, is it possible to add some toggle for the ytdl stream function to download the entire audio file before beginning playback? I'd honestly prefer downloading a <10MB file that can be later deleted if it means that the stream won't die on everything I try to play.

**Comment by SunDwarf** [comment]
I've never had this, and I use the YTDL player a lot.

What ffmpeg version are you using?

**Comment by edasaki** [comment]
I just updated to the most recent build of ffmpeg and it seems a bit better (less frequent) but the error still occurs.

The error did change a bit:

> 
[tls @ 0000000000729740] Unable to read from socket
[matroska,webm @ 0000000001fb24a0] Read error
[tls @ 0000000000729740] Unable to read from socket
    Last message repeated 1 times
[tls @ 0000000000729740] Failed to send close message

**Comment by SunDwarf** [comment]
Sounds like a simple case of a shaky network.

**Comment by khazhyk** [comment]
Try updating youtube-dl - they often push updates due to google changing their systems

**Comment by edasaki** [comment]
Right, this may have been a case of bad network. Rehosted on VPS and seems to work fine (stilll happens very rarely but it doesn't kill the bot, only ends the current stream, so I'm not too worried about it). Closing issue, thanks for the help.
