### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Annihilator708** [Rapptz/discord.py#1579]
First of all thanks for this amazing api, I use it about more then a year now and I love it.
To be pretty direct, 👍 : When you send a discord.gg invite a embed appears with a button.
I would really appreciate to have access to that button. Would be neat to edit the text in it aswel. 
maybe something like

    await ctx.send(
        discord.Embed(
            description='Button the game').set_button(
            text='Start', 
            on_action=self.foo))

Thanks 👌

**Comment by Harmon758** [comment]
That's not something that Discord's API is capable of.

**Comment by crrapi** [comment]
Those "embeds" for invite links are a part of the client itself and editing them would be basically impossible without a modified client.

**Comment by Annihilator708** [comment]
Unfortunate, thanks for the quick reply 👌
