### ISSUE TITLE
Can't install discord.py

### ISSUE THREAD

**Issue by minitolgy** [Rapptz/discord.py#1580]
I already try update pip, but it didnt work.. and install unroll have same issue:
<pre><font color="#CC0000">Command &quot;python setup.py egg_info&quot; failed with error code 1 in /tmp/pip-install-bjPTlQ/aiohttp/</font>
</pre>

<pre>$ pip install discord.py
Collecting discord.py
  Using cached https://files.pythonhosted.org/packages/97/3c/2a97b47fd8839f8863241857bbd6a3998d1de1662b788c8d9322e5a40901/discord.py-0.16.12.tar.gz
Collecting aiohttp&lt;1.1.0,&gt;=1.0.0 (from discord.py)
  Using cached https://files.pythonhosted.org/packages/09/5a/7b81ea8729d41f44c6fe6a116e466c8fb884950a0061aa3768dbd6bee2f8/aiohttp-1.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File &quot;&lt;string&gt;&quot;, line 1, in &lt;module&gt;
      File &quot;/tmp/pip-install-bjPTlQ/aiohttp/setup.py&quot;, line 60, in &lt;module&gt;
        raise RuntimeError(&quot;aiohttp requires Python 3.4.2+&quot;)
    RuntimeError: aiohttp requires Python 3.4.2+
    
    ----------------------------------------
<font color="#CC0000">Command &quot;python setup.py egg_info&quot; failed with error code 1 in /tmp/pip-install-bjPTlQ/aiohttp/</font>
</pre>

**Comment by minitolgy** [comment]
<pre>python3.6 -m pip install
<font color="#C4A000">pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.</font>
<font color="#C4A000">You must give at least one requirement to install (see &quot;pip help install&quot;)</font>
</pre>

**Comment by minitolgy** [comment]
And i think i have SSL in PC.. but for some reasons pc ignore it

**Comment by EvieePy** [comment]
Please refer to this SO:
https://stackoverflow.com/a/49696062

If you compiled Python yourself you will need to install the required packages first and recompile.

**Comment by minitolgy** [comment]
i got stuck on this step...
<pre>./configure
bash: ./configure: No such file or directory
</pre>

**Comment by EvieePy** [comment]
How did you install Python 3.6?

To make it easier and quicker for me to help could you please join [the official support server](https://discord.gg/r3sSKJJ). Thanks
