### ISSUE TITLE
disconnect() returns AttributeError: 'NoneType' object has no attribute 'disconnect'

### ISSUE THREAD

**Issue by TheMrRandomDude** [Rapptz/discord.py#1581]
Hello. So before I post my code and the error, I'll say that I did the following:

- Reinstalled Pyhon and upgraded from 3.6.1 32 bit to 3.6.5 64 bit and set the Path variables correctly
- Uninstalled discord.py module and installed discord.py[voice] with pip, multiple times.
- Reinstalled asyncio multiple times.
- All modules are up to date
- Restarted my computer after every major change and it works for a few minutes, then the error starts appearing and stays.
- The only fix I noticed was using **logout()** instead of **disconnect()**.

I am on Windows 10 at the moment.

Here's my code:

```python
import discord
from discord.ext import commands
import sys
try:
	TOKEN = 'XXXXX'
	client = commands.Bot(command_prefix = '?')

	@client.event
	async def on_ready():
		print("Bot je online.")

	@client.command(pass_context=True)
	async def joinaj(ctx):
		channel = ctx.message.author.voice.voice_channel
		await client.join_voice_channel(channel)

	@client.command(pass_context=True)
	async def leavaj(ctx):
		server = ctx.message.server
		voice_client = client.voice_client_in(server)
		await voice_client.disconnect()
		
	client.run(TOKEN)
except KeyboardInterrupt:
	client.logout()
	print("Gasenje")
	sys.exit()
```

Here's the error I'm getting:
```python
Ignoring exception in command leavaj
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "discord bot.py", line 21, in leavaj
    await voice_client.disconnect()
AttributeError: 'NoneType' object has no attribute 'disconnect'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'disconnect'
```

**Comment by Xillenn** [comment]
> First of all, you're going to want to change your token.
> As the traceback shows, this error is occurring on `await voice_client.disconnect()`, not on the bot disconnecting.
> [`Client.voice_client_in`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.voice_client_in) returns `None` when the voice client for the server is not found, e.g. when the bot isn't connected to a voice channel in that server.
> 
> For further help using the library, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

Ha, already changed my token. Forgot to remove it haha. I already asked on the official discord.py server and they told me that my program seems fine, one guy even ran it on his own and it worked just fine.

**Comment by Harmon758** [comment]
The error will only occur when `?leavaj` is used in a server where the voice client is not found.
You can easily handle the error by ensuring `voice_client` isn't `None` before using it.

**Comment by TheMrRandomDude** [comment]
Thanks, that worked.
This is the code that solved my issue:
```python
	@client.command(pass_context=True)
	async def leavaj(ctx):
		server = ctx.message.server
		voice_client = client.voice_client_in(server)
		if voice_client is not None:
			await voice_client.disconnect()
		else:
			return
```
