### ISSUE TITLE
Check embed size before sending

### ISSUE THREAD

**Issue by Bluscream** [Rapptz/discord.py#1582]
Is there any way to save bandwith by checking the total size of a `Discord.Embed` before sending it?

**Comment by Gorialis** [comment]
Optimizing via `discord.Embed` payload is not a particularly shrewd method of trying to reduce bandwidth usage, no matter the setup.

There are a couple points to consider here if we were to optimize Embed:
- There are frequent (and sometimes pretty large) websocket events (presence, typing) that will easily shadow this optimization in a matter of a few seconds.
- You could just as easily receive such an embed through the websocket (using bandwidth) and you wouldn't be able to do much about it.
- HTTP, TCP and TLS padding could easily cancel out the optimization anyway.

If your concern is bandwidth, rewrite supports turning off [`fetch_offline_members`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Client) to reduces the amount of data required to sync guilds, which is often a much more pressing issue.

**Comment by Bluscream** [comment]
So let's do it the old way then ...
```py
try: await message.channel.send(embed=em)
except discord.HTTPException as ex:
    if ex.status != 400: return
    if ex.code != 50035: return
```
