### ISSUE TITLE
[Rewrite] change_presence() does not update presence

### ISSUE THREAD

**Issue by ryanbroman** [Rapptz/discord.py#1595]
`await bot.change_presence(activity = Activity(name="example", activity=ActivityType.watching))`

The above code doesn't actually update the bot's presence, it simply says it is online.

**Comment by EvieePy** [comment]
activity should be type

e.g:
`await bot.change_presence(activity=discord.Activity(name='Test', type='discord.ActivityType.watching))`

**Comment by ryanbroman** [comment]
Thank you. Sorry
