### ISSUE TITLE
Can we get the entire info dict in the create_ytdl_player function?

### ISSUE THREAD

**Issue by TheBlackParrot** [Rapptz/discord.py#160]
YouTube likes to give back both 44.1kHz (non-opus) and 48kHz (opus) audio from the ytdl player, and I need the sample rate value to correctly determine a pitch effect (via the `asetrate` ffmpeg filter).

I'm not sure how to fetch the value, and I'm at a dead end.

The only way I know of that could *potentially* fix the problem, is determining when Opus is the source codec (via the info dict around line 530 in `voice_client.py`), but nothing is ever set for it.
```python
        ydl = youtube_dl.YoutubeDL(opts)
        func = functools.partial(ydl.extract_info, url, download=False)
        info = yield from self.loop.run_in_executor(None, func)
        if "entries" in info:
            info = info['entries'][0]
```
I'm wanting access to all of `info` as of here, essentially

I'm new to Python so excuse me if I'm using any wrong terminology :(

**Comment by SunDwarf** [comment]
You're better off just copy/pasting that code into your method, and modifying it as needed. You can then create the ffmpeg player via `voice_client.create_ffmpeg_player(url)`.

**Comment by Rapptz** [comment]
Use ytdl yourself. The player function is meant as a thin wrapper.
