### ISSUE TITLE
is it possible to perform unit tests on the commands using pytest?

### ISSUE THREAD

**Issue by modernNeo** [Rapptz/discord.py#1604]

**Comment by imayhaveborkedit** [comment]
More or less a dupe of #197.  Basically there's two ways to do this.  Either capture and replay gateway events to simulate a connection to discord, or separate your logic from your command structure and test it on its own.

**Comment by SilentHacks** [comment]
For anyone in the future, I made [SimCord](https://github.com/SilentHacks/simcord) which lets you simulate a Discord connection and mock commands, button interactions etc.
