### ISSUE TITLE
websockets vulnerability 

### ISSUE THREAD

**Issue by RDIL** [Rapptz/discord.py#1607]
# Denial of Service (DoS)
* [x] Affecting websockets package, versions [,5.0) 

## Overview
websockets is a library for building WebSocket servers and clients in Python with a focus on correctness and simplicity.

Affected versions of this package are vulnerable to Denial of Service (DoS) attacks due to not enforcing max_size when decompressing compressed zip messages.

## Details
Denial of Service (DoS) describes a family of attacks, all aimed at making a system inaccessible to its intended and legitimate users.

Unlike other vulnerabilities, DoS attacks usually do not aim at breaching security. Rather, they are focused on making websites and services unavailable to genuine users resulting in downtime.

One popular Denial of Service vulnerability is DDoS (a Distributed Denial of Service), an attack that attempts to clog network pipes to the system by generating a large volume of traffic from many machines.

When it comes to open source libraries, DoS vulnerabilities allow attackers to trigger such a crash or crippling of the service by using a flaw either in the application code or from the use of open source libraries.

## High CPU/Memory Consumption- 
An attacker sending crafted requests that could cause the system to take a disproportionate amount of time to process. For example, commons-fileupload:commons-fileupload.

## Crash - 
An attacker sending crafted requests that could cause the system to crash. For Example, npm ws package

## Remediation
Upgrade websockets to version 5.0 or higher.

*Credit to https://snyk.io*
#### More details: https://app.snyk.io/vuln/SNYK-PYTHON-WEBSOCKETS-42181

**Comment by Harmon758** [comment]
The rewrite branch uses websockets >= 6.0, < 7.0.
Also, this is unlikely to be applicable, since websockets is only used to connect to Discord's API/Gateways.

**Comment by ItWasAllIntended** [comment]
The async branch of D.py is no longer updated so the websockets version will not be bumped. Though, this has already been 'fixed' in the maintained rewrite branch as this uses the most recent version of websockets. If this is an issue for you, you would have to switch to the rewrite branch of D.py.

**Comment by RDIL** [comment]
ok.  should i close the issue?

**Comment by scragly** [comment]
Yes, also consider actually gathering info and evidence that links the issue you're bringing up with the respective library you're making an issue for in order for it to be properly relevant.

**Comment by RDIL** [comment]
:p it wasnt me that found it, it was my vulnerability checking program
