### ISSUE TITLE
Question (Unimportant) 

### ISSUE THREAD

**Issue by Y4hL** [Rapptz/discord.py#1608]
```
@client.event
async def on_message_delete(message):
    author = str(message.author)
    content = str(message.content)
    channel = str(message.channel)
    await client.send_message(channel, author + content)
```
When i delete a message it is giving these errors, 

```
File "C:\Program Files\Python36\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:/Users/Rasmus/Python/botnoggi2.py", line 77, in on_message_delete
    await client.send_message(channel, author + content)
  File "C:\Program Files\Python36\lib\site-packages\discord\client.py", line 1145, in send_message
    channel_id, guild_id = yield from self._resolve_destination(destination)
  File "C:\Program Files\Python36\lib\site-packages\discord\client.py", line 289, in _resolve_destination
    raise InvalidArgument(fmt.format(destination))
discord.errors.InvalidArgument: Destination must be Channel, PrivateChannel, User, or Object. Received str
```
Help would be greatly appreciated!
Also i tried using your discord for help, but nobody answered

**Comment by shivaco** [comment]
You are casting str() on a `Channel` object and then basically using `send_message` on `channel.name`.

**Comment by Y4hL** [comment]
client.send_message requires the destination to be sent first, so isn't `channel` a destination?

**Comment by Harmon758** [comment]
As the error says, [`send_message`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.send_message) doesn't accept a `str` as a destination.
You are explicitly casting the channel to `str`.

GitHub issues are not the right place to ask for help; they should be for issues with the library itself.
For further help using the library, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by Y4hL** [comment]
How then can i make it send it to a channel of my choice without using a string

**Comment by Harmon758** [comment]
As [the documentation for `Client.send_message`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.send_message) states, the destination can be a [`Channel`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Channel) or [`PrivateChannel`](https://discordpy.readthedocs.io/en/latest/api.html#discord.PrivateChannel) object, e.g. the one you're casting to a `str`.
