### ISSUE TITLE
how do I do something when a user changes their username in discord.py?

### ISSUE THREAD

**Issue by HypersDevelopment** [Rapptz/discord.py#1609]
When I google search this, it just pops up with changing the nickname. I'm looking for something like

    @client.event
    async def on_username_change(old, new, user):

or something like that. help?

**Comment by Harmon758** [comment]
[`on_member_update`](https://discordpy.readthedocs.io/en/latest/api.html#discord.on_member_update) should pick up username changes as well.

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.

**Comment by HypersDevelopment** [comment]
what should I put in the async def?

    async def(<What Here>):

**Comment by HypersDevelopment** [comment]
wait I didn't mean to close it

**Comment by Harmon758** [comment]
The event is [`on_member_update`](https://discordpy.readthedocs.io/en/latest/api.html#discord.on_member_update).
