### ISSUE TITLE
 channel.history

### ISSUE THREAD

**Issue by chizzy123** [Rapptz/discord.py#1615]
anyone know why this is not working all of a sudden?

async for message in channel.history(limit=3):
AttributeError: 'NoneType' object has no attribute 'history'

**Comment by Harmon758** [comment]
You need to provide more context for the code for anyone to help you.
Specifically, where you define `channel`, as you're trying to use it when it's `None`.

For further help using the library, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by chizzy123** [comment]
this is the code
```

@bot.event
async def on_ready():
    print('Logged in as')
    print(bot.user.name)
    print(bot.user.id)
    print('------')

    channel = bot.get_channel(CHANNEL_ID)

    messages = await channel.history(limit=3).flatten()

    # reversing because discord sends only data first,
    messages.reverse()

    for i, message in enumerate(messages):
        message = message.content
        req = requests.post('https://www.mybot.com/bot.cfm',data=message.encode('ascii','ignore'))
        print(req)
 

```

**Comment by Harmon758** [comment]
[`Client.get_channel`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Client.get_channel) returns `None` if the channel is not found.
Also, requests is [blocking](https://discordpy.readthedocs.io/en/rewrite/faq.html#what-does-blocking-mean).
