### ISSUE TITLE
TypeError: Callback must be a coroutine

### ISSUE THREAD

**Issue by wrgsRay** [Rapptz/discord.py#1619]
I am trying to run my bot on a remote server(pythonanywhere) and it is giving me this error. The code works fine on my local computer(windows 10). Full traceback and code snippet is included. Any idea why this is happening?

```
 (most recent call last):
  File "/home/wrgsRay/aria/aria.py", line 151, in <module>
    main()
  File "/home/wrgsRay/aria/aria.py", line 17, in main
    bot = commands.Bot(command_prefix='!')
  File "/home/wrgsRay/.local/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 183, in __init__
    self.command(**self.help_attrs)(_default_help_command)
  File "/home/wrgsRay/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 961, in decorator
    result = command(*args, **kwargs)(func)
  File "/home/wrgsRay/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 1107, in decorator
    raise TypeError('Callback must be a coroutine.')
TypeError: Callback must be a coroutine.
```

```
import aiohttp
import discord
from discord.ext import commands
import asyncio
from keys import aria_code
import random
from bs4 import BeautifulSoup as bs
import re


def main():
    # Set prefix and remove default help command
    bot = commands.Bot(command_prefix='!')
    bot.remove_command('help')
    activity = discord.Game(name="!help for help")

    # Print something to console once logged in
    @bot.event
    async def on_ready():
        print('We have logged in as {0.user}'.format(bot))
        await bot.change_presence(status=discord.Status.idle, activity=activity)
```

**Comment by Harmon758** [comment]
I'm unable to reproduce this with your snippet.
What version of discord.py are you using?
This shouldn't happen unless you override `_default_help_command` with a function that's not a coroutine.

**Comment by wrgsRay** [comment]
> 
> 
> I'm unable to reproduce this with your snippet.
> What version of discord.py are you using?
> This shouldn't happen unless you override `_default_help_command` with a function that's not a coroutine.

I am using 1.0.0a from here. https://github.com/Rapptz/discord.py/archive/rewrite.zip
As I have mentioned, this error only happened on PythonAnywhere. It worked fine on my local PCs(windows and macos).
Did you try running the code on your pc or PythonAnywhere?

**Comment by Harmon758** [comment]
Specifically, are you using the most up to date version of the rewrite branch? i.e. 1.0.0a1580+g836ae73
All the error is saying is that `_default_help_command` is not a coroutine, which it always has been in the library. This should not be platform specific.
Are you overriding `_default_help_command`?
Can you show the rest of your code?

**Comment by Erasmusss** [comment]
If you're using asyncio you have to put `async def` in front of every function.
