### ISSUE TITLE
[Suggestion] Add "user.voice_channel" to get the current voice channel of the bot itself.

### ISSUE THREAD

**Issue by AraHaan** [Rapptz/discord.py#163]
So, I was thinking it would be great if there was a ``user.voice_channel`` attribute so that way we can get the current voice channel of the Bot without a lot of effort and code.

**Comment by SunDwarf** [comment]
`client.voice` doesn't work?

**Comment by Mondanzo** [comment]
Is it not server.me.voice_channel ?

**Comment by AraHaan** [comment]
yeah it does but only if you append ``message.channel`` I wanted this to be a shorter way.

**Comment by Rapptz** [comment]
No.
