### ISSUE TITLE
Looping background task

### ISSUE THREAD

**Issue by Jonesyj83** [Rapptz/discord.py#1630]
Been trying to run a background task in a loop without success.
Decided to run the example 
https://github.com/Rapptz/discord.py/blob/rewrite/examples/background_task.py
Changed sleep to 10 instead of 60. All I get is '1' posted and nothing else, it just stops.
How can I continue the loop?

cheers

**Comment by Vexs** [comment]
The code in the example works fine- so you've made some error. 
This can't be diagnosed without the code you're running- and this really isn't the right place to ask. Github issues are for issues with the lib, not so much coding help- we have a [support server](https://discord.gg/r3sSKJJ) for that.

**Comment by Jonesyj83** [comment]
`import discord

class MyClient(discord.Client):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # create the background task and run it in the background
        self.bg_task = self.loop.create_task(self.my_background_task())

    async def on_ready(self):
        print('Logged in as')
        print(self.user.name)
        print(self.user.id)
        print('------')

    async def my_background_task(self):
        await self.wait_until_ready()
        counter = 0
        channel = self.get_channel(channelid) # channel ID goes here
        while not self.is_closed():
            counter += 1
            await channel.send(counter)
            await asyncio.sleep(10) # task runs every 60 seconds


client = MyClient()
client.run('token')`

This is the code I have run, and it isn't working. Which is why I posted here. Thinking something is wrong with the module.

**Comment by h4ckninja** [comment]
That was fast. :) So, I did also try with `discord.Channel(name='playground')` which threw a NoneType error. Now it makes more sense. Is there a reliable way to get the channel ID programmatically by name? I can only find getting the name by the ID.

**Comment by crrapi** [comment]
You could always use `discord.utils.get` to find something with a specific name/id from an iterable of objects (ex. `channel = discord.utils.get(some_server.channels, name="playground")`, `channel` would be a channel already, and you could pass that to send_message instead.

**Comment by h4ckninja** [comment]
Thanks. I just found `channel = discord.utils.get(client.get_all_channels(), server__name = '<my server>', name = 'playground')` which works just fine. :)

**Comment by topras** [comment]
Hey. I am using the same code too. I have done copy-paste and it doesn't work. I get no errors but it's just that the message never gets sent. (yes I've replaced the channel ID)

**Comment by CapnS** [comment]
Please don't necro issues. If you need help using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.
