### ISSUE TITLE
[question] Is there a permission for view_channels?

### ISSUE THREAD

**Issue by th3infinity** [Rapptz/discord.py#1632]
Hey,
Discord permission has this option but there is none in the discord.py docs. So is it possible to change the view_channel permission for a channel?
Tried to use view_channel = True but its not working.

Thanks in advance

**Comment by Harmon758** [comment]
The View Channel permission for voice channels is equivalent to the Read Messages permission for text channels.

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.
