### ISSUE TITLE
custom handlers broken

### ISSUE THREAD

**Issue by s0hvaperuna** [Rapptz/discord.py#1635]
After this commit https://github.com/Rapptz/discord.py/commit/27216892547bb073777056379d549a6dc42872cb#diff-5bab608907a27a2180166115e6299cefL264 which removes the custom handler calling, which makes calling custom handlers impossible since [call_handlers](https://github.com/Rapptz/discord.py/blob/rewrite/discord/state.py#L131) in `ConnectionState` only ever is called for calling the ready handle. 
Either bring back the old way or implement another way of registering handles (I've tried adding them to the Client._handlers dict)

**Comment by Rapptz** [comment]
Handlers are a private API which were purposefully not exported nor supported.
