### ISSUE TITLE
SSL: Certificate_verify_failed

### ISSUE THREAD

**Issue by Cheezy096** [Rapptz/discord.py#1636]
Hi, I'm having a problem when trying to run a bot, whenever i attempt to do so i receive the error could not connect to host discordapp.com ssl:None [[SSL: *the title of this issue*] certificate verify failed, now i know this is a certificate error however i have tried looking for a way to fix this issue with windows, so far i only managed to find fixes for max which is not the correct os i'm using, this is really annoying me now and i hope that someone might be able to help me fix this, i know i have to install a certain certificate however i do not know where to install nor receive this certificate, i hope someone here will be able to help me sort this problem out "and yes i did look it up on google my noodles but no luck" thanks again

**Comment by EvieePy** [comment]
I myself have not found a fix for this on Windows as of yet, someone more informed than me might be able to help.

The one thing you could try is installing openssl for windows:
http://gnuwin32.sourceforge.net/packages/openssl.htm

The only other fix requires changing the clients connector (I am not sure what ramifications, if any, this has):
```python
import aiohttp

bot = commands.Bot(connector=aiohttp.TCPConnector(verify_ssl=False))
```

**Comment by Cheezy096** [comment]
Thank you, the discord client and my bot are now opening, seriously thank you.

**Comment by Discordots** [comment]
not wrking for me plz help

**Comment by CapnS** [comment]
Please don't necro issues. If you need help using this library, you should join either the official discord.py server or the Discord API server, as the README recommends.
