### ISSUE TITLE
Member.joined_at is occasionally None

### ISSUE THREAD

**Issue by Tobotimus** [Rapptz/discord.py#1638]
Hi, I'm really sorry I am no longer able to reproduce this, but I can confirm this odd behaviour occurred on a bot of mine. The bot had been running for a few weeks, and one command which created a sorted list of `guild.members` by `Member.joined_at` failed. This screenshot of a [p]debug command (a poor man's version of [p]eval) shows an incomplete list of all users in a guild who had `joined_at` as None, which totalled to 572 users (out of ~3200 in the guild):
![image](https://user-images.githubusercontent.com/7438501/46440270-2f7cb280-c7a6-11e8-8e59-a3767488bb6e.png)

Restarting the bot fixed the issue, but I figure the fact that it occurred in the first place means that it ought to be tracked. I'm sorry I did not try to gather more info before restarting the bot.

**Comment by mikeshardmind** [comment]
Just a warning for anyone currently using this method, it is no longer safe to do so. With the new server discovery thing (see https://github.com/DJScias/Discord-Datamining/commit/977bd10e4180e09dcb5ca49da5b82b2db96ca8b2#commitcomment-32146369), discord added a lurker mode.

You can have member objects without a `joined_at` attribute with this being the intended behavior now.

This means any bot on a server with server discovery enabled can end up calling `Client.request_offline_members` continuously if they have any code which is currently relying on this as a workaround for the prior issue.

The only safe method going forward is to handle joined_at with NoneType safe methods.

This does pose a problem for members who aren't lurking and have ended up with a lack of a joined at date though, and (at least in my opinion) makes updating the member cache from other events worth considering.
