### ISSUE TITLE
Login fails [rewrite]

### ISSUE THREAD

**Issue by Skarlett** [Rapptz/discord.py#1639]
`client.run("email", "password")` appears to fail with the trace back being...

```
Traceback (most recent call last):
  File "/home/god/projects/discord_rpc/self_bot.py", line 18, in <module>
    client.run("*", "*")
  File "/usr/lib/python3.7/site-packages/discord/client.py", line 571, in run
    return task.result()
  File "/usr/lib/python3.7/site-packages/discord/client.py", line 478, in start
    await self.login(*args, bot=bot)
TypeError: login() takes 2 positional arguments but 3 positional arguments (and 1 keyword-only argument) were given
```

**Comment by EvieePy** [comment]
`run()` takes a token as an argument. An email/password combination has been invalid for quite some time now.

You can find your token, here: https://discordapp.com/developers/applications/

Click on your Application, click on Bot to the left... (Add Bot if you haven't already done so) and then you should see a token which you can click to reveal and copy.

**Comment by crrapi** [comment]
Also worth noting that [Self-bots are against the Discord Terms of Service](https://support.discordapp.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-) and could result in termination if found.
