### ISSUE TITLE
await client.send_message(discord.Object(id='123456'), 'hello') does not work

### ISSUE THREAD

**Issue by wrgsRay** [Rapptz/discord.py#1640]
I want to send a message to a specific channel when the bot goes online by adding an example I found here: https://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-send-a-message-to-a-specific-channel
```
    @bot.event
    async def on_ready():
        print('We have logged in as {0.user}'.format(bot))
        await bot.change_presence(status=discord.Status.idle, activity=activity)
        await bot.send_message(discord.Object(id='123456'), 'hello')
```
The error I got was:
```
await bot.send_message(discord.Object(id='123456'), 'hello')
AttributeError: 'Bot' object has no attribute 'send_message'
```

I am using the latest version of discord py 1.0

**Comment by Harmon758** [comment]
This example is for the async branch.
For the rewrite branch, see https://discordpy.readthedocs.io/en/rewrite/faq.html#how-do-i-send-a-message-to-a-specific-channel.

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.

**Comment by wrgsRay** [comment]
Harmon758,

Thanks. Done and done.
