### ISSUE TITLE
Get User locale

### ISSUE THREAD

**Issue by Foxlider** [Rapptz/discord.py#1644]
Is there a way since rewrite to get the user's locale ? 
It might be useful to get it to know what language the bot should speak in presence of a user.
There is an issue opened in the discord docs though https://github.com/discordapp/discord-api-docs/issues/535#issuecomment-392973019

**Comment by Foxlider** [comment]
Well that's not cool

**Comment by Shuvi-Hub** [comment]
![image](https://user-images.githubusercontent.com/66522712/84936575-be487480-b0da-11ea-8a89-b1193876dc4a.png)
Pls why is this not used????

**Comment by Rapptz** [comment]
Answer remains the same as it was 2 years ago. Please don't bump issues.
