### ISSUE TITLE
AttributeError: module 'discord' has no attribute 'overwrite'

### ISSUE THREAD

**Issue by ghost** [Rapptz/discord.py#1646]
So i created a system to create a channel only a new user can see:

> `@client.event
> async def on_member_join(member):
>     m_perms = discord.PermissionOverwrite(read_messages=True)
>     member = discord.overwrite(target=member, overwrite=m_perms)
>     await client.create_channel(server, "Hi, " + member, everyone, member)`

That's the error code i get:

> `m_perms = discord.overwrite(read_messages=True)
> AttributeError: module 'discord' has no attribute 'overwrite'`

**Comment by Harmon758** [comment]
As the error says, there is no `discord.overwrite`.
You're probably looking for `discord.ChannelPermissions`.
See the documentation for [`Client.create_channel`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.create_channel).

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.

**Comment by domerepu** [comment]
So i updated my code:

> `@client.event
> async def on_member_join(member):
>     m_perms = discord.PermissionOverwrite(read_messages=True)
>     member = discord.ChannelPermissions(target=member, overwrite=m_perms)
>     await client.create_channel(server, "Hi, " + member, everyone, member)`

An thats now the error code:

> `AttributeError: module 'discord' has no attribute 'ChannelPermissions'`

**Comment by domerepu** [comment]
now im using `ChannelPermissions` but the console say `module 'discord' has no attribute 'ChannelPermissions'`

**Comment by shivaco** [comment]
What do you even expect `"Hi, " + member` to be when you are doing `member = discord.ChannelPermissions(target=member, overwrite=m_perms)`?
Also, what is `server` defined as and why don't you do `await client.create_channel(member.server, "hi-{}".member.name, overwrites=m_perms)` instead?
I also recommend you joining [official discord.py server](https://discordapp.com/invite/r3sSKJJ) to get help with your issue.

**Comment by Harmon758** [comment]
What version of discord.py are you using?
This should be every version >= 0.10.0.

**Comment by domerepu** [comment]
I'm using Python 3.6.6

**Comment by shivaco** [comment]
Python is not discord.py.
