### ISSUE TITLE
on_voice_state_update() missing 1 required positional argument

### ISSUE THREAD

**Issue by celi28** [Rapptz/discord.py#1650]
## System Configuration :
* Python 3.6.6 (default, Oct  7 2018, 09:43:55) 
* [GCC 8.2.1 20180831] on linux
* discord.py 0.16.12

## Code to reproduce :
```python
import discord
import asyncio
client = discord.Client()

 @client.event
 async def on_voice_state_update(member, before,after):
     print(member)
 client.run(token)
```

## Error raised :
```python
Ignoring exception in on_voice_state_update
Traceback (most recent call last):
  File "[python3.6_path]/site-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
TypeError: on_voice_state_update() missing 1 required positional argument: 'after'
```

Anyone have a how-to-fix ?
Thanks

**Comment by NCPlayz** [comment]
The only two arguments that the event `voice_state_update` provides you with are `before`, and `after`. https://discordpy.readthedocs.io/en/latest/api.html#discord.on_voice_state_update

**Comment by celi28** [comment]
Oh damm, I was looking for the 1.0.0a version documentation available here: https://discordpy.readthedocs.io/en/rewrite/api.html#event-reference

Thanks.
#closing
