### ISSUE TITLE
Command.signature reports Greedy and Optional params as required

### ISSUE THREAD

**Issue by bmintz** [Rapptz/discord.py#1653]
```py
@commands.command()
async def foo(context, a: typing.Optional[discord.Member], b: commands.Greedy[discord.TextChannel], c):
    pass
```

Expected `foo.signature`:
`foo [a] [b...] <c>`

Actual `foo.signature`:
`foo <a> <b> <c>`

**Comment by crrapi** [comment]
Can reproduce with the latest rewrite version.

**Comment by XuaTheGrate** [comment]
I have been working on a PR to fix this issue, though I'm unsure if this is complete or not. Here's a couple of tests I've run and would like feedback if possible. Also I will run more tests if asked to.
```python
@bot.command()
async def test(ctx, a, b: commands.Greedy[int]=5, c=None):
    await ctx.send(f"{a} | {b} | {c}")
    await ctx.send(test.signature)
```
![image](https://cdn.discordapp.com/attachments/513649581506953219/525076471186718744/unknown.png)
```python
@bot.command()
async def hello(ctx, a, b: typing.Optional[bool], c: commands.Greedy[int], d: bool=True, *e):
    await ctx.send(f"{a} | {b} | {c} | {d} | {e}")
    await ctx.send(hello.signature)
```
![image](https://cdn.discordapp.com/attachments/513649581506953219/525076914726240257/unknown.png)
The relevant code can be found on my own Github page [right here.](https://github.com/XuaTheGrate/discord.py/commit/b8c30b3c2eb7ff4732559087af5f1eef4291f657)

**Comment by bmintz** [comment]
That looks done to me, can anyone else think of other test cases?

**Comment by XuaTheGrate** [comment]
Another test case suggested by @MusicOnline, this shows Greedy without a default, but not supplied a single argument to convert.
```python
@bot.command()
async def test(ctx, a, b: commands.Greedy[int], c=None):
    await ctx.send(f"{a} | {b} | {c}")
    await ctx.send(test.signature)
```
However this will raise an error (#1791) if used as follows:
![image](https://cdn.discordapp.com/attachments/514593990704889858/525177806410219522/unknown.png)
