### ISSUE TITLE
await invalid syntax

### ISSUE THREAD

**Issue by owengaming001** [Rapptz/discord.py#1654]
I Tried Using The reply.py file and it gave me a syntax error, i managed to fix it
but now im getting another one on another line
it says: 
  File "reply.py", line 14
    await client.send_message(message.channel, msg)
               ^
SyntaxError: invalid syntax

**Comment by mrc0mmand** [comment]
Without the rest of the source code it's practically impossible to tell you how to fix this issue. Also, you haven't stated which python and discord.py version you use.

As this question is not related to the library development, you should use the [official discord.py](https://discord.gg/r3sSKJJ) server instead.

**Comment by owengaming001** [comment]
import discord

client = discord.Client()

@client.event
@asyncio.coroutine
def on_message(message):
    # we do not want the bot to reply to itself
    if message.author == client.user:
        return

    if message.content.startswith('!hello'):
        msg = 'Hello {0.author.mention}'.format(message)
        await client.send_message(message.channel, msg)

@client.event
@asyncio.coroutine
def on_ready():
    print('Logged in as')
    print(client.user.name)
    print(client.user.id)
    print('------')

client.run('T37Y-AwcMcCuvbMHO_DBQlZhjKiIsy4A')

**Comment by owengaming001** [comment]
I Will Re-Generate The Token Later

**Comment by LockdownDoom** [comment]
You must change ‘def on_message’ to ‘async def on_message’ to signify an
asynchronous function.

**Comment by crrapi** [comment]
You should use `yield from` syntax, rather than `await` syntax. This is demonstrated in the 3.4 usage section of the readme. If you are using python 3.5+ then you can drop the `@asyncio.coroutine()` and use `async def`/`await` syntax instead.

**Comment by owengaming001** [comment]
By the way LockdownDoom the file was by default as you suggested, but I had to change it, that was the first syntax error I fixed, and I'm sorry if this is a bit hard! This is my first thread

**Comment by owengaming001** [comment]
Then It Returns
    yield from client.send_message(message.channel, msg)
             ^
SyntaxError: invalid syntax

**Comment by owengaming001** [comment]
By the way i'm using Python-2.7

**Comment by crrapi** [comment]
Discord.py does not support Python 2.7. The minimum required version for the async branch is 3.4 (Not recommended, because of the different syntax required), so you might as well get the latest supported version (Python 3.6.6). You can find a download [here.](https://www.python.org/downloads/release/python-366/)

**Comment by RDIL** [comment]
^

**Comment by matomfg** [comment]
I am using 3.6 and still having the same issue

**Comment by CapnS** [comment]
@matomfg You are probably not running it in an asynchronous environment (async def). 

In the future please don't necrobumb issues. This is not an issue with discord.py. GitHub issues for this repository should be used to report issues with this library. They are not a medium for requesting help with Python. For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), and for help with Python in general, you should join the official [Python server](https://discord.gg/python).
