### ISSUE TITLE
AttributeError: '<class 'discord.client.Client'>' object has no attribute 'get_member'

### ISSUE THREAD

**Issue by ModernMoGamer** [Rapptz/discord.py#1657]
Hello,
I'm currently getting the error in the title when I run the following code (extracted from my full code)
```
role = discord.utils.get(s.roles, name="Administrator: Currently In-Game")
user = client.get_member(user_id=254381293297598465)
await client.remove_roles(user, role)
```

Not too sure what my issue is, I have client set to discord.Client()

**Comment by Harmon758** [comment]
As the error says, `Client.get_member` does not exist.
You're probably looking for [`Server.get_member`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Server.get_member).

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.

**Comment by ModernMoGamer** [comment]
Solved it, Turns out that I had to set a variable ("s" is what I used for the server) and run:
```
s = client.get_server('349692657221500938')
```
To then use the "s" instead of client
```
user = s.get_member('user_id')
```
Though I also found that you are required to use quotes in async.
