### ISSUE TITLE
help

### ISSUE THREAD

**Issue by poske** [Rapptz/discord.py#1661]
code: 
@bot.command(pass_context=True)
async def enlist(ctx, *, nickname):
    await bot.change_nickname(ctx.message.author, nickname)

error:
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'Bot' object has no attribute 'change_nickname'

it's same with "bot.add_roles" and even if i switch "bot" to "client" it still doesn't work

**Comment by shivaco** [comment]
It looks like you have rewrite branch installed. The documentation for rewrite can be found [here](https://discordpy.readthedocs.io/en/rewrite/api.html).

Also, this is not an issue with the library itself, so please move to [official discord.py server](https://discord.gg/r3sSKJJ) if you will need more help.

**Comment by poske** [comment]
alright
