### ISSUE TITLE
Unhandled event GUILD INTEGRATIONS UPDATE

### ISSUE THREAD

**Issue by obiwankennedy** [Rapptz/discord.py#1662]
I got this error log frequently. Is there a way to prevent that ?

**Comment by crrapi** [comment]
This just means that there is an event (in this case, an update of guild integrations) being dispatched by the gateway that the library does not parse/handle. This can be safely ignored.

**Comment by Vexs** [comment]
Hm, out of curiosity, how many is many? It should be very very rare- I've only seen a handful of people get these. 

Anyway, what do you mean by `log`- just terminal output?

**Comment by obiwankennedy** [comment]
in 19 mins, I got 29 messages.
I log every command made to my bot. It helps to see what can be improved. 
To log info, I use python logger class. logs are writen into file. how do i hide log from the library ?

**Comment by CraftSpider** [comment]
This was fixed by #1899 being rebased, rewrite branch now handles this event
