### ISSUE TITLE
FFMPEG Opening instantly?

### ISSUE THREAD

**Issue by dedlyT** [Rapptz/discord.py#1668]
Hi! I am trying to make my music command more efficient by making it check if it is playing something and if it is, to add it to the queue.
The only problem is that if something is already playing, it still plays the second song, causing it to crash.
Any ideas?
```python
@bot.command(pass_context=True)
async def play(ctx, url):
    server = ctx.message.server
    voiceClient = bot.voice_client_in(server)
    player = await voiceClient.create_ytdl_player(url, after=lambda: check_queue(server.id))
    if player.is_live == True:
        print(player.is_live)
        if server.id in queues:
            queues[server.id].append(player)
        else:
            queues[server.id] = [player]
        title = player.title
        await bot.say("Added " + title + "to the queue")
    else:
        print(player.is_live)
        players[server.id] = player
        player.start()
        title = player.title
        await bot.say("Now playing: " + title + "\n" + url)
```

**Comment by Harmon758** [comment]
`player.is_live` refers to whether the source is a livestream or not.
What you're probably looking for is `player.is_done()` or `player.is_playing()`.
See the documentation for [`VoiceClient.create_ytdl_player`](https://discordpy.readthedocs.io/en/latest/api.html#discord.VoiceClient.create_ytdl_player) and [`VoiceClient.create_stream_player`](https://discordpy.readthedocs.io/en/latest/api.html#discord.VoiceClient.create_stream_player).

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.

**Comment by dedlyT** [comment]
Thanks! I wasn't expecting anybody to answer so fast
