### ISSUE TITLE
Error when saving to json

### ISSUE THREAD

**Issue by Kremund** [Rapptz/discord.py#1669]
I'm setting up a quoting system in my bot, and this is the code for saving a quote from a mentioned member:
```python
@bot.command()
async def quote(ctx):

    async for melding in ctx.message.channel.history(limit=50):
        if melding.author == ctx.message.mentions[0]:
            
            sitat = melding.content
            sitatforfatter = ctx.message.mentions[0]

            ny = {sitat: sitatforfatter}

            with open("quotes.json") as f:
                data = json.load(f)

            data.update(ny)

            with open("quotes.json", 'w') as f:
                json.dump(data, f)   
                         
            await ctx.send("Quote saved.")
            break
```

This produces this error:
![skjermbilde](https://user-images.githubusercontent.com/31285047/46917758-c9c0cf80-cfca-11e8-87a4-f54e953436fd.PNG)

I've tried saving `sitatforfatter` as a string, no difference. I've seen posts about this on other forums, but none about discord.py, and I don't know enough about web stuff to take anything out of those and apply it to my code.

Thank you.

**Comment by Harmon758** [comment]
This is an error in how your quotes.json file is formatted. It's likely not valid json.
This doesn't really have anything to do with discord.py.
For further help specific to using this library, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by Kremund** [comment]
@Harmon758 I'm actually in both of those servers, but for some reason I didn't think of asking there 🤦‍♂️. As far as json is concerned, the file was empty, and kinda makes sense that it didn't work. I just added some sample json, and now it works! Thank you, Harmon :)
