### ISSUE TITLE
Add a way to sanitize webhook content

### ISSUE THREAD

**Issue by starcraft66** [Rapptz/discord.py#1673]
Background: I am writing a discord bot to bridge chat between Minecraft and Discord, I send messages as webhooks in order for them to impersonate the Minecraft user on the other end for each message. The problem is that people can send messages containing @everyone pings, etc.

Normally with a regular bot message, filtering this out is trivial but there is currently no such luxury with webhooks since we are essentially just sending a string to an HTTP endpoint and this does not create a `Message` object, obviously, so we cannot get its `clean_content` property.

I'm thinking there should be some sort of method that would allow me to sanitize any arbitrary string, even if it is not a `Message`'s content.

**Comment by Diniboy1123** [comment]
You don't need a message object, just do:

```py
await commands.clean_content().convert(ctx, "@everyone")
```

However if you only want to escape the mentions and want to avoid using that coro, put a zero width space after each `@` character. AFAIK the clean_content does something similar too.

```py
your_string.replace("@", "@\N{zero width space}")
```

Or if you only want to escape everyone pings, replace `@everyone` instead.

**Comment by Rapptz** [comment]
Yeah I feel like maybe branching out the sanitizing to a different function makes sense. I remember trying to do it earlier but forgot about it.

I'd need some way to allow passing in a list of roles, members, etc for proper sanitisation of role/member mentions.
