### ISSUE TITLE
is there a recently known issue with data transfer?

### ISSUE THREAD

**Issue by modernNeo** [Rapptz/discord.py#1674]
my bot is experiencing this error alot lately and I was wondering if it was an incident isolated to my bot or something else?

`2018-10-05 18:59:18 = WARNING - Error in data transfer`
`Traceback (most recent call last):`
`  File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 496, in transfer_data`
`    msg = yield from self.read_message()`
`  File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 526, in read_message`
`    frame = yield from self.read_data_frame(max_size=self.max_size)`
`  File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 591, in` `read_data_frame`
`    frame = yield from self.read_frame(max_size)`
`  File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 632, in read_frame`
`    extensions=self.extensions,`
`  File "/usr/local/lib/python3.5/site-packages/websockets/framing.py", line 100, in read`
`    data = yield from reader(2)`
`  File "/usr/local/lib/python3.5/asyncio/streams.py", line 668, in readexactly`
`    yield from self._wait_for_data('readexactly')`
`  File "/usr/local/lib/python3.5/asyncio/streams.py", line 458, in _wait_for_data`
`    yield from self._waiter`
`  File "/usr/local/lib/python3.5/asyncio/futures.py", line 381, in __iter__`
`    yield self  # This tells Task to wait for completion.`
`  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 310, in _wakeup`
`    future.result()`
`  File "/usr/local/lib/python3.5/asyncio/futures.py", line 294, in result`
`    raise self._exception`
`  File "/usr/local/lib/python3.5/asyncio/selector_events.py", line 723, in _read_ready`
`    data = self._sock.recv(self.max_size)`
`ConnectionResetError: [Errno 104] Connection reset by peer`

**Comment by Harmon758** [comment]
Check that you're not doing anything [blocking](https://discordpy.readthedocs.io/en/latest/faq.html#what-does-blocking-mean).
Otherwise, this is likely just caused by connection issues.

**Comment by Rapptz** [comment]
"Connection reset by peer" means that Discord has terminated your connection via a TCP RST packet. It is not an issue with the library.
