### ISSUE TITLE
Rewrite: Find Messages from User?

### ISSUE THREAD

**Issue by dxf** [Rapptz/discord.py#1676]
Can't seem to find anything in the docs.

**Comment by dxf** [comment]
For reference, I just want to be able to find a message, and read the contents of that message/the embed in that message.

**Comment by BluePhoenixGame** [comment]
You want to get a message from a user? Either you can use the `wait_for` function, it's like a local on_message that only works once or if it already was sent do `async for CHANNEL.history` iirc, look that up in the docs. But that will return all messages in the channel in a for loop.

**Comment by Harmon758** [comment]
If you have the [`Messageable`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.abc.Messageable) and message ID, you can use [`Messageable.get_message`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.abc.Messageable.get_message).

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.

**Comment by dxf** [comment]
cheers
