### ISSUE TITLE
How i do to know who invited my bot for determinate server?

### ISSUE THREAD

**Issue by matheusmdx** [Rapptz/discord.py#1678]

**Comment by Harmon758** [comment]
You should be able to do so with [OAuth2](https://discordapp.com/developers/docs/topics/oauth2#advanced-bot-authorization), but that's not within the scope of this library.

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.

**Comment by matheusmdx** [comment]
> 
> 
> You should be able to do so with [OAuth2](https://discordapp.com/developers/docs/topics/oauth2#advanced-bot-authorization), but that's not within the scope of this library.
> 
> For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.

Ok, thanks.
