### ISSUE TITLE
Is there a way to utilize robobrowser to automate logging into sites?

### ISSUE THREAD

**Issue by sageharpuiahx** [Rapptz/discord.py#1679]
Like say there's a prefix, and then the account name and then the password as variables

**Comment by sageharpuiahx** [comment]
I'm trying to get my Discord bot to run it

**Comment by Harmon758** [comment]
Even so, this isn't an issue with discord.py.
[RoboBrowser](https://github.com/jmcarp/robobrowser) has its own repository.

For further help specific to using this library, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by sageharpuiahx** [comment]
Ok thanks.
