### ISSUE TITLE
Help with merging photos and putting in embeds

### ISSUE THREAD

**Issue by Matty2064** [Rapptz/discord.py#1680]
I wonder if theres a way to localy merge 2 photos without a save, and then send it in an embed to discord?

for example:

items = ['stick','rock','lightbulb']

randomitem = random.choice(items)

if randomitem == 'stick':
     merge(background,stick)

or something like that xD

**Comment by Harmon758** [comment]
This should be possible with an imaging library like Pillow.

For attaching the image to an embed, see [`Embed.set_image`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Embed.set_image).

To attach an image without saving it, you can pass the binary data, using [`io.BytesIO`](https://docs.python.org/3/library/io.html#io.BytesIO), as the file-like object.
See [`Client.send_file`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.send_file) (or [`File`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.File) for the rewrite branch).

To [attach a local image file to the embed](https://discordapp.com/developers/docs/resources/channel#create-message-using-attachments-within-embeds), you can set the url to something like `attachment://filename.png` and then send both the file and embed in a single message.
On the rewrite branch, this can be done easily using [`File`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.File) and [`Messageable.send`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.abc.Messageable.send).
On the async branch, you'll have to use a workaround with `Client.http.send_file`:
https://github.com/Rapptz/discord.py/blob/1863a1c6636f53592519320a173ec9573c090c0b/discord/http.py#L299 with `buffer` being the image data and `embed` being the dictionary returned from [`Embed.to_dict`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Embed.to_dict).
To get the [`Message`](https://discordpy.readthedocs.io/en/latest/api.html#message) object from this, you'll have to pass the returned data unpacked to `Client.connection._create_message`:
https://github.com/Rapptz/discord.py/blob/1863a1c6636f53592519320a173ec9573c090c0b/discord/state.py#L698-L704 You'll also need to include the channel kwarg.

For further help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by Matty2064** [comment]
Ok so now i have the picture but im not understanding how to attach it to an embed for example this is my code:
`embed = discord.Embed(color=0x0000ff)
                    embed.add_field(name="{}'s Pet".format(user), value="**{}**".format(petname), inline=False)
                    embed.add_field(name="Type", value="__{}__".format(pettype), inline=False)
                    embed.add_field(name="Color",value="{}".format(petcolor), inline=False)
                    embed.set_thumbnail(url=peticon) # pet img url
                    await bot.send_message(ctx.message.channel, embed=embed)`
variable peticon is an image url but i wanna change it into a local image, its hard for me to explain xD

**Comment by Matty2064** [comment]
embed = discord.Embed(color=0x0000ff)
                    embed.add_field(name="{}'s Pet".format(user), value="**{}**".format(petname), inline=False)
                    embed.add_field(name="Type", value="__{}__".format(pettype), inline=False)
                    embed.add_field(name="Color",value="{}".format(petcolor), inline=False)
                    embed.set_thumbnail(url=peticon) # pet img url
                    await bot.send_message(ctx.message.channel, embed=embed)

sorry

**Comment by Harmon758** [comment]
Like I said, for the async branch, you'll have to use `Client.http.send_file`, passing all the appropriate arguments, including the image data as `buffer` and with `attachment://filename.png` as the embed image url.

See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code for code block formatting.

For further help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.
