### ISSUE TITLE
My Python won't accept this code??

### ISSUE THREAD

**Issue by ThiefYT** [Rapptz/discord.py#1684]
In python I get this error message:
> Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\harri\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\harri\Favorites\Desktop\bot\bot.py", line 41, in on_message
    await client.send_message(message.channel,variable)
UnboundLocalError: local variable 'variable' referenced before assignment

 My code:
@client.event
async def on_message(message):

if message.content.startswith ("$say"):
        variable = message.content[len("$say"):].strip()
        if variable == "@ everyone":
            await client.send_message(message.channel,"Please don't ping @ everyone")
        if variable == "@ here":
            await client.send_message(message.channel,"Please don't ping @ here")
        
    else:
        await client.send_message(message.channel,variable)

**Comment by MusicOnline** [comment]
This is not an issue with the library.
(variable isn't assigned if message doesn't start with $sayl

**Comment by RDIL** [comment]
Try this code before using the variable:
variable = None
So it doesn’t call an error
That should fix it

**Comment by ThiefYT** [comment]
>           Try this code before using the variable:
> variable = None
> So it doesn’t call an error
> That should fix it

ok I will check that out
