### ISSUE TITLE
[rewrite] Adding reactions, but message.reactions is returning "[]"

### ISSUE THREAD

**Issue by averagewolfie** [Rapptz/discord.py#1686]
So this is the code I have written:

`add_reactions_to = await main.send(user.mention, embed = e)`
`await add_reactions_to.add_reaction("↖")`
`await add_reactions_to.add_reaction("➡")`
`print(str(add_reactions_to.reactions))`

Adding the reactions to the message works just fine, I see them in the message. But it's like it isn't actually updating the message's reactions in context because the list of reactions is empty, both in the print method (always returning "[]") as well as an await to sense which reaction the _user_ selects (always returning False).

**Comment by MusicOnline** [comment]
You need to get the message again to get the latest reactions. Wouldn't want the list to change sizes while you're iterating over it. I also have no clue what "an await to sense which reaction the user selects (always returning False)" means.

**Comment by averagewolfie** [comment]
Okay, so I decided finally to get back into this, and I'm rewriting code and I'm getting a desired effect, so I feel as though this won't be an issue any longer.

**Comment by Rapptz** [comment]
Keep this open as this is going to be worked on eventually.

**Comment by averagewolfie** [comment]
Uhh, if you're absolutely sure.~ The issue which _**I**_ had originally, is no longer, but if you think this can be optimized, then I'll leave you to it.

**Comment by Hunterfollow123** [comment]
is there a solution for it ? this problem has been bothering me for a month now

**Comment by Rapptz** [comment]
The API doesn't return any discernible information in that endpoint to update the state so it requires hooking it up to the gateway component of the API which comes with its own set of issues.
