### ISSUE TITLE
Can't install discord.py

### ISSUE THREAD

**Issue by RexTheCapt** [Rapptz/discord.py#1687]
Every single time i try to install discord.py i keep getting the error message 

> Command ""D:\Program Files (x86)\Python37-32\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-ydtbinw2\\PyNaCl\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))"
install --record C:\Users\user\AppData\Local\Temp\pip-record-jlrw0bg6\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-install-ydtbinw2\PyNaCl\

Here is the log https://hastebin.com/tipigopowu.coffeescript

**Comment by Phxntxm** [comment]
Don't use python3.7, the async branch of the library does not support it....it's recommended to use 3.6.6

**Comment by Harmon758** [comment]
Also duplicate of #1444

**Comment by narimanized** [comment]
Looks like a compilation error.
You need something (mingw or visual studio's compilators) to build `pynacl`==1.0.1. Not an easy way.
PyNaCl has wheels for its latest versions, to install it without compilation step.
As a workaround, you can install `pynacl` (latest version, idk exactly, but it should has a compatibility with  1.0.1), and then `discord.py` without `voice` extra.
And, as pointed before, `discord.py` is not compatible with Python 3.7. Use Python < 3.7 if you'd like so. Or install `rewrite` branch (from git), without `voice` extra as well.
Btw, it's not a duplicate of all that is mentioned before. But it would have happened if the installation was successful.

**Comment by Harmon758** [comment]
>  Or install rewrite branch (from git), without voice extra as well, but you can try with, if 1.2.1 has wheels.

The rewrite branch now fully supports Python 3.7, including with voice, as [PyNaCl 1.2.1 has wheels for Python 3.7 on PyPI](https://pypi.org/project/PyNaCl/1.2.1/#files).

**Comment by RexTheCapt** [comment]
@Phxntxm Thank you for the help. Successful install and my bot runs with no problem.

**Comment by progadro** [comment]
can i use python 3.8 here ?

**Comment by SebbyLaw** [comment]
@progadro Please don't necrobump old issues. The async branch of discord.py is no longer used, so this issue is no longer relevant.

For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.
