### ISSUE TITLE
Don't know how to fix this... please help

### ISSUE THREAD

**Issue by abrooks9002** [Rapptz/discord.py#1697]
Hi, I'm trying to create a dice rolling function for DND and can't seem to get it to work. Here's the code:

`@client.command(brief="Rolls a D6.",
                name= 'd6')
async def d6():
    d6 = ["1","2","3","4","5","6"]
    dice = random.choice(d6)
    await client.say("You rolled a:", dice)`

and then I get this error:
`Traceback (most recent call last):
  File "C:\Users\jaust\PycharmProjects\Giggly's Bot\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:/Users/jaust/.PyCharmCE2018.2/config/scratches/scratch_5.py", line 33, in d6
    await client.say("You rolled a:", dice)
  File "C:\Users\jaust\PycharmProjects\Giggly's Bot\lib\site-packages\discord\ext\commands\bot.py", line 350, in say
    coro = self.send_message(destination, *args, **kwargs)
TypeError: send_message() takes from 2 to 3 positional arguments but 4 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jaust\PycharmProjects\Giggly's Bot\lib\site-packages\discord\ext\commands\bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "C:\Users\jaust\PycharmProjects\Giggly's Bot\lib\site-packages\discord\ext\commands\core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\jaust\PycharmProjects\Giggly's Bot\lib\site-packages\discord\ext\commands\core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: send_message() takes from 2 to 3 positional arguments but 4 were given
`

**Comment by Vexs** [comment]
`Client.say` isn't like print; it takes a single string only.
As a further detail, doing random numbers like this is.... sloppy. Consider `random.randint` instead. [We have a full example of this as a command](https://github.com/Rapptz/discord.py/blob/async/examples/basic_bot.py#L23-L33)

This is not an issue with discord.py.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python
For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by Harmon758** [comment]
`Bot.say` uses [`Client.send_message`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.send_message):
https://github.com/Rapptz/discord.py/blob/1863a1c6636f53592519320a173ec9573c090c0b/discord/ext/commands/bot.py#L321-L342 [`Client.send_message`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.send_message), and therefore `Bot.say`, only accepts one positional argument for content.
You're passing two: `"You rolled a:"` and `dice`. You can simply concatenate the strings and pass it as a single string.

Also, as @Vexs said, you should look into using [`random.randrange`](https://docs.python.org/3/library/random.html#random.randrange) or [`random.randint`](https://docs.python.org/3/library/random.html#random.randint), as well as [`codeblocks for GitHub`](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).
