### ISSUE TITLE
Out of memory when installing discord.py

### ISSUE THREAD

**Issue by Inspectiver** [Rapptz/discord.py#1700]
When I run `pip install -U git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py` I get this error: 
![unknown 1](https://user-images.githubusercontent.com/33937835/47754197-027ecb00-dc92-11e8-8f3f-8d7cbd506f5c.png)

**Comment by Harmon758** [comment]
A simple search for `fatal: Out of memory, malloc failed` shows that this is an issue with Git, with resources outlining potential solutions.
