### ISSUE TITLE
Load an extension from a package

### ISSUE THREAD

**Issue by Fukutu** [Rapptz/discord.py#1703]
I think it would be useful to choose the package to load the extension providing the argument to can be preconfigured and not be by the name of the extension  **"package.extension"** etc.

![1](https://user-images.githubusercontent.com/44680570/47871243-5997b380-ddea-11e8-8c89-6b2894523b4b.png)
![2](https://user-images.githubusercontent.com/44680570/47871245-5a304a00-ddea-11e8-8681-3f5b7aea9650.png)

**Comment by Gorialis** [comment]
This can be done by just doing `load_extension("package.extension")` normally.

**Comment by Fukutu** [comment]
I know, but it's a tip

**Comment by Fukutu** [comment]
> I think it would be useful to choose the package to load the extension providing the argument to can be preconfigured and not be by the name of the extension **"package.extension"** etc.
> 
> ![1](https://user-images.githubusercontent.com/44680570/47871243-5997b380-ddea-11e8-8c89-6b2894523b4b.png)
> ![2](https://user-images.githubusercontent.com/44680570/47871245-5a304a00-ddea-11e8-8681-3f5b7aea9650.png)

**Comment by bmintz** [comment]
What's the use case for this?

**Comment by Hornwitser** [comment]
Well, given that `importlib.import_module("client", "discord")` does not import `discord.client` and that the desired effect can easily be achieved in the call with something like `.load_extension(f"{package}.{name}")`, I'd say all this does is add pointless confusion.
