### ISSUE TITLE
Changing a string to a user

### ISSUE THREAD

**Issue by Momo8289** [Rapptz/discord.py#1705]
I'm trying to have the bot send a DM to a user that is given in a message. I use `split()` to break up the message, but when I try and do `await client.send_message(mescon[1]`(And more, obviously) with `mescon` being the message as a list, I get the exception `discord.errors.InvalidArgument: Destination must be Channel, PrivateChannel, User, or Object. Received str`. How can I fix this?

**Comment by RainbowLegend** [comment]
1. If you’re not using the commands ext yet, I recommend you switch to it as it:
- Typehinting for specific instances is easy
- Easier arg parsing
If you are using the commands ext, use the `discord.Channel` typehint.
An example of this is the command in [basicbot.py](
https://github.com/Rapptz/discord.py/blob/1863a1c6636f53592519320a173ec9573c090c0b/examples/basic_bot.py#L46:L49)

2. You can parse the channel ID within that string by using `str[1:-2]` and using `Server.get_channel` you will get an instance of `discord.Channel`

**Comment by Harmon758** [comment]
[`Client.send_message`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.send_message) accepts the destination as the first argument.

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.
