### ISSUE TITLE
Appending a subfolder to the main script causes ffmpeg to not be found.

### ISSUE THREAD

**Issue by AraHaan** [Rapptz/discord.py#171]
Ok so I appened a folder towards the end of my path variable and it seems that it is simply not working much ``sys.path`` that is.

![5124c0e7d678082ae391abfc92d6bcad](https://cloud.githubusercontent.com/assets/15173749/14515571/fa38c3aa-01c0-11e6-8483-0f8784a971f5.png)
Image of the proof. It would be nice of it was to work.

**Comment by khazhyk** [comment]
is there an 'ffmpeg.exe' in that folder you added?

**Comment by AraHaan** [comment]
yes, it is in there it is oddly not finding it there.

**Comment by khazhyk** [comment]
If you open your console and type `where ffmpeg` what is the path it shows?

**Comment by AraHaan** [comment]
oh I see 
![253450a839d33753613954d395a5735a](https://cloud.githubusercontent.com/assets/15173749/14515728/460c99c2-01c2-11e6-9ae1-091b7829586f.png)

**Comment by khazhyk** [comment]
Fix your system PATH so that ffmpeg.exe shows up.
