### ISSUE TITLE
Issue with change_presence

### ISSUE THREAD

**Issue by ALittleHalfHearted** [Rapptz/discord.py#1716]
```
@bot.event
async def on_ready():
	print('Logged in as')
	print(bot.user.name)
	print(bot.user.id)
	print('------')
	await bot.change_presence(game=discord.Game(name='my game'))
```
This doesn't work for some reason. Everywhere I've checked has something almost exactly like this, but it just gives me an error "TypeError: change_presence() got an unexpected keyword argument 'game'." What am I doing wrong?

**Comment by ItWasAllIntended** [comment]
GitHub issues are for issues with the library itself. Please join the [D.py](https://discord.gg/r3sSKJJ) support server for help.

**Comment by ALittleHalfHearted** [comment]
Alright, sorry.
