### ISSUE TITLE
PyNaCl warning issued, even though VoiceClient not being used

### ISSUE THREAD

**Issue by sqldiablo** [Rapptz/discord.py#1719]
I'm using discord.py via Home Assistant, and I'm receiving the warning that PyNaCl isn't installed, and voice will not be available, but all Home Assistant is using is the text features. Can a feature be added to allow disocrd.py to disable voice altogether or to just suppress the PyNaCl warning when voice features aren't being actively used? It seems silly to fire a warning every time discord.py is initialized, even though the voice features aren't being used.

**Comment by Phxntxm** [comment]
Installing `discord.py` should install the package without voice support. Installing `discord.py[voice]` will include the voice requirements. I'm fairly certain that it does not try to install pynacl with the first option.

**Comment by sqldiablo** [comment]
Correct, but what pip installs or doesn't isn't the issue I'm reporting. The issue is that discord.py still logs a warning that PyNaCl isn't installed, even when I've only installed the non-voice version and have made no attempt to use voice features. Just by importing/initializing discord.py, discord.py does a check for PyNaCl and logs a warning if it's not present.

**Comment by sqldiablo** [comment]
Basically it's logging noise that I'm trying to get rid of. It shouldn't warn you until you try to initialize\use voice features.

**Comment by sqldiablo** [comment]
Or if there's some way I could initialize it with a parameter telling it to disable or ignore voice features, that would work too.

**Comment by Rapptz** [comment]
You are free to do `discord.VoiceClient.warn_pynacl = False`.

**Comment by sqldiablo** [comment]
Thanks @Rapptz, that took care of it.
