### ISSUE TITLE
Example for Checks in the commands documentation makes no sense (rewrite)

### ISSUE THREAD

**Issue by Merlintor** [Rapptz/discord.py#1729]
![image](https://user-images.githubusercontent.com/33966852/48664060-47c83880-ea99-11e8-9ba0-9688f06f23fb.png)

- There is only one check, but the example should show off multiple checks
- `is_in_guild` should be `predicate`

https://discordpy.readthedocs.io/en/rewrite/ext/commands/commands.html#checks

**Comment by crrapi** [comment]
See #1720

**Comment by crrapi** [comment]
> There is only one check, but the example should show off multiple checks

I don't think this is really necessary, as simply stating it should suffice.

**Comment by MusicOnline** [comment]
The next line after the example is
> If any of those checks fail in the example above, then the command will not be run.

An inaccurate example would only bring confusion.
