### ISSUE TITLE
OAuth'ing a bot while it's running leads to no console output until restart

### ISSUE THREAD

**Issue by MasterKale** [Rapptz/discord.py#173]
Here's a simple bot that I started writing:

```python
import asyncio

import discord


class IconScraperBot(discord.Client):
    def __init__(self):
        super().__init__()
        self.token = 'token_here'

    def run(self):
        return super().run(self.token)

    async def on_ready(self):
        print('Logged in as')
        print(self.user.name)
        print(self.user.id)
        print('------')

    async def on_server_join(self, server):
        print('joining {0}'.format(server.name))

    async def on_server_remove(self, server):
        print('leaving {0}'.format(server.name))

    async def on_message(self, message, flag=None):
        print('Message received: {0}'.format(message.content))


bot = IconScraperBot()
bot.run()
```
The bot starts fine, I see the `print()` statements in `on_ready()`, and I can see the bot in the list of users in my server after I use an OAuth URL to approve it.

The issue is somewhere in the following sequence of events:

1. Start bot
2. Use OAuth URL to grant access to the bot to join my server

The bot joins the server, but there's absolutely no console output. Nothing when it joins the server, nothing when I send it a message, and nothing when I kick the bot.

**However**, if I _restart_ the bot after it's joined then I at least see console output from `on_message()` and `on_server_remove()`. For whatever reason, something bugs out in `on_server_join()` which probably freezes the whole bot. There's no visible crashing in the console, though - everything appears to be running fine.

I've confirmed this on both Python 3.4.2 and 3.5.1

**Comment by Rapptz** [comment]
Should be fixed here: https://github.com/Rapptz/discord.py/commit/8d7dd79673a35c4977c285324b36738e1e6c82f7

**Comment by MasterKale** [comment]
Confirmed fixed. Thanks for the quick update.
