### ISSUE TITLE
I just want to say thanks

### ISSUE THREAD

**Issue by bmintz** [Rapptz/discord.py#1732]
Thanks to Danny, to spoopy, to hele, to Horn, to devon, to Mikusaba, to Harmon, to Vex, to Leo, to Papyrus, to all past, present and future contributors and proficients, and to countless other people who make this library great.

Thank you to @Rapptz aka danny aka block-san, the man, the myth, the oncologist, the legend, for making the library from scratch. You seem like a fantastically skilled programmer and it really shows in the countless hours you've spent developing this library, which I have definitely learned a lot from, like array.array, multiple inheritance, et al. And thanks for putting up with me and calling me blocked-kun :stuck_out_tongue_winking_eye: 

I'm thankful for @khazhyk aka spoopy, for your large amount of contributions, ideas, and for making spoo.py, which is definitely in my list of favorite bots of all time.

Big thanks to @Gorialis aka devon, for making the amazing Jishaku library, for always having a very interesting project to talk about, for bringing sound, well reasoned arguments to the table (and putting up with my not so sound arguments (USB C > ⅛″ headphone jacks 😛)) and for teaching me some internals about how the asyncio event loop works. Miyuki is amazing by the way, and you bring commands in that most people literally cannot implement. I hope someday Miyuki will be free software because I'm sure your code is very well structured and clean (well maybe except ~!hotornot 😛)

@Ikusaba-san, I remember when I was asking about something in #help, and you were the only person there who answered my question respectfully. I also remember when you did the same for someone who couldn't figure out that dividing seconds by 60 gives you minutes, and while everyone else was making fun of them, you tried to help them. I think that's rad, and I hope that someday you will decide to be a proficient again (but it's your decision of course). So thanks.

@CuteFwan Koishi is amazing, and I still think your depth command outdoes Devon's lol. The histostatus command is super rad, and what made me realize that I should use a bot to always be idle. I still find it amazing that you did histostatus in a single SQL query (!!) and I hope to be as awesome at SQL as you are. (`JOIN`s with more than a few clauses scare me pretty quickly lol)

Shout out to @Hornwitser for making all your code style and performance contributions.

Thanks to @scragly for helping me a ton with gettext. I've met people who enjoy translating my bots for free, and that's freaking rad. It's also great that now I know how to use gettext.

Big ty to @BeatButton for being an amazing friend to me, for discussing copyleft with me with kindness and respect, for helping me explore my sexuality, and for writing the neato beattie bot, whose jisho command I use whenever danny insults someone in Japanese 😛

Thanks to @Domterion, for being a great friend to me, and for asking me questions about SQL. I've learnt a lot from teaching you and your bots are neato cool.

Many thanks to @jwshields aka noodle. I know we have parted ways, but I still think you're a very cool person. I've learnt a lot about systems administration from you, and though we disagree on privacy and whether clean room engineering a bot is OK, I hope that someday, we can agree to disagree. I'm sorry I hurt you, even if it may not seem like it, I truly am from the bottom of my heart.

Thanks to @Gelbpunkt aka Adrian, for making such rad cool machine learning bots and for teaching me a bit about manual sharding. And for translating my bot to german.

 thanks to @Diniboy1123 aka Mary Johanna (oops, dox) for teaching me about hacking, helping me diagnose bugs in my bots, for providing excellent ideas for my bots, and for translating my bot to Hungarian.

Thanks for @TheTrain2000's helping me clone @Highlight xd, and for going to my weird hacker meetup that was an hour's drive from your house lol

Thanks to @fuyukai, for being a rad communist weirdo (I mean that in the best way possible) and for helping me decide on Curio vs Trio for a new bot. Maybe you don't like me or something (pls send me a server invite if you want to!), but I like you, and you seem to be one of the few other people in this community who loves copyleft *and* hates asyncio 😉

@Pandentia aka Liara, you are a v cool person, and I'm glad you also use federated services like ActivityPub/OStatus and Matrix. You also came up with the idea behind @EmoteCollector and though I am not sorry about the cloning, I am sorry if I hurt you by cloning it. And thank you for licensing the old version of Element Zero under the MIT license, even if it's CC-BY-NC nowadays 😉

@hexxferret your bot is the only economy bot that I actually wanted to use, even though all of them boil down to mindless "!daily" at some point lol.

@CapnS, thanks for working on that git post-receive hook with me that restarts your bot when you push. I had a lot of fun working on it and I hope you're still using it (or maybe something better, like watchdog!) And thanks for translating my bot to Spanish.

I think that's everyone I wanna write about. I may have missed some people, so if you want me to thank you just let me know and I'm sure I'll find a way that you're awesome.

Over the past year or so, I've had a ton of fun writing Discord bots, and though I feel conflicted about contributing to communities of people who use a nonfree, privacy-invasive, commercial chat platform, I just enjoy doing it. I've met many wonderful people along the way, be they in the discord.py or DAPI servers, or elsewhere, be they users or developers, and I would not have met these people were it not for your hard work.

Without this library I literally would not be the person that I am today, a much more experienced programmer, self confident programmer with more refined views on software licenses, and who's now somewhat adept at using SQL and doing system administration. Using discord.py has improved my resumé a lot and I may be getting a job because of it (alone).

So I just wanted to say thank you. I truly hope you have a fantastic Thanksgiving, I hope you had a fantastic year and I hope you will have many amazing Thanksgivings to come, you amazing, wonderful, beautiful, smart people.

**Comment by bmintz** [comment]
I'm closing this issue since it's off-topic, but please feel free to comment anyway, especially if I didn't thank you and you think I left you out.

**Comment by ir-3** [comment]
<3
