### ISSUE TITLE
Request entity to large

### ISSUE THREAD

**Issue by LiJu09** [Rapptz/discord.py#1733]
When I trying to send file I will get this error. discord.ext.commands.errors.Command.InvokeError: Command raised an exception: HTTPException: REQUEST ENTITY TOO LARGE (status code: 413): Request entity too large

I am using raspberry 3B+ with newest Raspbian

Please help.

And sorry for my bad english.

**Comment by Modelmat** [comment]
Most likely your file is larger than 8MB. Please try with a file smaller than this limit.

**Comment by LiJu09** [comment]
Ok

**Comment by bxrd** [comment]
Is there a way to bypass this?

**Comment by Rapptz** [comment]
No. This is an API limit.
