### ISSUE TITLE
Bad Request Error in embeds though no character limit overstepping

### ISSUE THREAD

**Issue by synarvis** [Rapptz/discord.py#1735]
I'm currently writing a bot in python to assist as a guide on a roleplay server ; it has a help command to display the FAQ in an embed message - which works - but the next command which has an embed message going into detail of the choosen question results in the following error:

```
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\saturn01\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:/Users/saturn01/PycharmProjects/Bots/snowdinhelp.py", line 81, in on_message
    await client.send_message(message.channel, embed=em)
  File "C:\Users\saturn01\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "C:\Users\saturn01\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400)
```

I looked the issue up of course, and it says that it's due to overstepping discord's character limit of 2000, but that's not the case since the code of the command which ends in said error message looks like this:

```
@client.event
async def on_message(message):
    if message.content.lower().startswith('?general'):
        em = discord.Embed(description="⠀\n `Knowledge about the way this server is organised and about the story of the roleplay.` \n⠀", color=0xbb752f)
        em.set_author(name="-- General")
        em.add_field(name="Where do I find ... on here?", value=" ", inline=False)
        em.add_field(name="What is this roleplay about?", value=" ", inline=False)
        em.add_field(name="Why is this an already existing story?", value=" ", inline=False)
        em.set_footer(text="Page 1 of 1 | Use ?question<number> to select the answer you want to look at.")
        await client.send_message(message.channel, embed=em)
```

The same set works perfectly with the prior command, as I said - its text is even longer than this one. Where's the problem, what am I doing wrong?

**Comment by Vexs** [comment]
`value` fields can't be blank. And yes, spaces count as blank. You can use a zero-width-space like `\u200b` to escape this. 

As a note, GitHub issues for this repository should be used to report issues with this library.
For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.
