### ISSUE TITLE
If a Spotify song being listened to is longer than 128 characters, member.activity returns None instead

### ISSUE THREAD

**Issue by numbermaniac** [Rapptz/discord.py#1738]
Another user was initially having this issue in the discord server, which I then was able to reproduce.

https://open.spotify.com/track/5YnS9oWrGcwf1tgode1F7z?si=bp0Zkk3qSF68yxSZjOuVzA

This song's name is exactly 128 characters long, and if you have it playing while connected to Discord, `member.activity` will correctly return a `discord.activity.Spotify` instance with the song details.

https://open.spotify.com/track/47dPsSo7cEDNkvIOSB4O2k?si=id9VCJHiSiWpedthzYQcUA

This song title, however, is 129 characters long, and if the user is listening to this song while connected to Discord, `member.activity` will always return `None`.

[activity.py](https://github.com/Rapptz/discord.py/blob/rewrite/discord/activity.py#L41) indicates that this may be an intentional limit. Is this a Discord API limitation or an issue with discord.py? If it's an API limitation, perhaps it should be noted in the documentation as this could be an unexpected surprise.

**Comment by Rapptz** [comment]
Right. This is an API limitation, not one that has to do with the library. The library just presents the information as-is.

**Comment by numbermaniac** [comment]
Thanks for the answer! Since it's an API limitation, maybe a note should be added to the documentation somewhere warning of this behaviour?

**Comment by SilicalNZ** [comment]
Music said this well and I feel like it applies to this situation as well.
https://github.com/Rapptz/discord.py/pull/1656#issuecomment-428910927
