### ISSUE TITLE
How can I have a command that sends a DM to a user.

### ISSUE THREAD

**Issue by DiggerZC** [Rapptz/discord.py#1743]
Basicially I would type something like "!dm [user] [text]",
but I am not sure how to do this. Could anyone let me know how I could program this into my bot?

**Comment by Vexs** [comment]
Take a look at some of the [examples](https://github.com/Rapptz/discord.py/blob/async/examples), specifically [basic_bot.py](https://github.com/Rapptz/discord.py/blob/async/examples/basic_bot.py)

This is not an issue with discord.py.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.
For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by NeviraOwner** [comment]
I don't know how to define the target user and the content both at one command, but I can provide how to send it:
`await bot.send_message(targetid, content)`
