### ISSUE TITLE
Probelm adding command to category in help coomand

### ISSUE THREAD

**Issue by Charlie-Char** [Rapptz/discord.py#1750]
I rewrote my code from the async version to the discord.ext.commands and realsied it has an integrated help command. How to add them to a category?

I know its using cogs with the following structure
`class Name:

    @bot.command()
    async def command1():
        blahblahbla
    @bot.command()
    async def command2():
        blahblahbla 
bot.add_cog(Name())`

But it raises  `discord.errors.ClientException: Command is already registered.
`
Can someone help me with this?

EDIT: In my code it's done with async def, forgot to write it when copying

**Comment by Gelbpunkt** [comment]
Cogs use `@commands.command()` and `async def`.
Consider also checking if a command called `command1` or `command2` already exists.

**Comment by NCPlayz** [comment]
Within cogs, you use `@commands.command()` since adding commands to the bot is implicitly dealt with

**Comment by Charlie-Char** [comment]
> Cogs use `@commands.command()` and `async def`.
> Consider also checking if a command called `command1` or `command2` already exists.

Will try that, but there is not any other command named the same anywhere in the code

**Comment by Charlie-Char** [comment]
@commands.command() was it. Thank you both

> Within cogs, you use `@commands.command()` since adding commands to the bot is implicitly dealt with, and use async def for commands since they are asynchronous



> Cogs use `@commands.command()` and `async def`.
> Consider also checking if a command called `command1` or `command2` already exists.
