### ISSUE TITLE
RuntimeWarning: coroutine 'setup' was never awaited   lib.setup(self)

### ISSUE THREAD

**Issue by Shiatryx** [Rapptz/discord.py#1751]
As the name implies, I'm getting an error when starting up the bot. This is being raised from `Discord.ext.commands.Bot.load_extension`. I looked, and sure enough, someone didn't await line 700 of the `Bot` class.
```python
lib.setup(self)
```
Is it safe for me to modify the file and await it myself?

**Comment by Shiatryx** [comment]
Note:
    Python 3.6
    Discord.py rewrite

**Comment by Phxntxm** [comment]
The setup function is not meant to be a coroutine. It's not awaited *because* it's not meant to be a coroutine. Don't make yours a coroutine and everything will be fine.

**Comment by Shiatryx** [comment]
I'm an idiot. I'm so used to having everything be a coroutine that I forgot that the setup function wasn't supposed to be. Thank you.
