### ISSUE TITLE
AttributeError: module 'discord' has no attribute 'abc'

### ISSUE THREAD

**Issue by noneteya** [Rapptz/discord.py#1754]
> mac / pyenv / pycharm / python 3.6.0

## MyCode

```python
import discord

client = discord.Client()

@client.event
async def on_ready():
    print('Logged in as')
    print(client.user.name)
    print(client.user.id)
    print('------')

@client.event
async def on_message(message):
    if isinstance(message.channel, discord.abc.PrivateChannel):
        await client.send_message(message.channel, "private channel")

client.run("{Token}")

```

## Error

```python
Ignoring exception in on_message
Traceback (most recent call last):
  File "/Users/{User-Name}/PycharmProjects/{Project-Name}/venv/lib/python3.6/site-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "/Users/{User-Name}/PycharmProjects/{Project-Name}/{File-Name}.py", line 11, in on_message
    if isinstance(message.channel, discord.abc.PrivateChannel):
AttributeError: module 'discord' has no attribute 'abc'
```

:(

**Comment by noneteya** [comment]
Thank you for your kind reply :)
I'll try them.

**Comment by ItWasAllIntended** [comment]
Abc stands for Abstract Base class and  is a concept, not directly accessible. Please ![read the docs on](https://discordpy.readthedocs.io/en/rewrite/api.html#abstract-base-classes) the subject to learn more.

**Comment by noneteya** [comment]
@ItWasAllIntended Hmm...?
I just read the docment.

> Abstract base classes cannot be instantiated. They are mainly there for usage with isinstance and issubclass.

If Abc is mainly used with isinstance and issubclass, why my  code still doesn't work??

```python
@client.event
async def on_message(message):
    if isinstance(message.channel, discord.abc.PrivateChannel):
        await client.send_message(message.channel, "private channel")
```

**Comment by numbermaniac** [comment]
Have you made sure that the version of discord.py on your computer is the latest version?

**Comment by noneteya** [comment]
@numbermaniac Yes.


name / version / leatest version
<img width="748" alt="2018-12-03 21 26 31" src="https://user-images.githubusercontent.com/45062623/49373704-502f9d00-f742-11e8-88af-16e28a8b8973.png">
(Python 3.6.7 pyenv)

**Comment by numbermaniac** [comment]
0.16.12 is the async version of the library. `abc`s didn't exist (or at least weren't documented) in the async version.

You can use `channel.is_private` in the async library to check if a channel is a private message. https://discordpy.readthedocs.io/en/latest/api.html#discord.Channel.is_private

**Comment by noneteya** [comment]
@numbermaniac Oh!!!!!!!!!!! Yeah!!!!!!
That's exactly my problem!
Thanks million!

**Comment by ItWasAllIntended** [comment]
@nonetya Make sure to close the issue of it's all sorted

**Comment by noneteya** [comment]
@ItWasAllIntended Okay. Thank you.

**Comment by CryptoLover705** [comment]
Hello I am trying to set up a tipbot but I am getting this error 

```
Traceback (most recent call last):
  File "bot.py", line 3, in <module>
    from utils import output, parsing, checks, mysql_module, g
  File "/root/sct-tip-bot/utils/checks.py", line 1, in <module>
    from utils import parsing, mysql_module
  File "/root/sct-tip-bot/utils/mysql_module.py", line 11, in <module>
    class Mysql:
  File "/root/sct-tip-bot/utils/mysql_module.py", line 24, in Mysql
    class __Mysql:
  File "/root/sct-tip-bot/utils/mysql_module.py", line 98, in __Mysql
    def check_server(self, server: discord.Server):
AttributeError: module 'discord' has no attribute 'Server'
```

**Comment by ShineyDev** [comment]
1. it's `discord.Guild` now
2. please don't necrobump issues, create your own or better, join the discord.py guild; https://discord.gg/r3sSKJJ
