### ISSUE TITLE
More voice events like on_speak and on_speak_stop 

### ISSUE THREAD

**Issue by HarryjosephSADPS** [Rapptz/discord.py#1755]

**Comment by Phxntxm** [comment]
(Unless I am mistaken) Discord does not send these events, meaning the library cannot provided them.

https://discordapp.com/developers/docs/topics/gateway#commands-and-events-gateway-events

**Comment by HarryjosephSADPS** [comment]
I heard JS

**Comment by imayhaveborkedit** [comment]
The event you're referring to is `VOICE_SPEAKING_UPDATE` which is sent over the voice websocket.  The library does not implement these events yet since they are part of voice receive.

**Comment by HarryjosephSADPS** [comment]
> The event you're referring to is the `SPEAKING` event which is sent over the voice websocket. The library does not implement these events yet since they are part of voice receive.

So is that a "it's never going to happen" or just not yet?

**Comment by Harmon758** [comment]
See #444 and #1094

**Comment by HarryjosephSADPS** [comment]
So it got requested two years ago and isn’t yet planned from what I can see...

**Comment by ClementJ18** [comment]
It's almost as if it's a lot of work

**Comment by ItWasAllIntended** [comment]
@HarryjosephSADPS No amount of complaining is going to help. Use d.js if you're alright with subpar implementationions of things and check other opened PRs and issues before making your own please.

**Comment by HarryjosephSADPS** [comment]
Yeah I mean it’s as if it does say “write suggestions”

**Comment by imayhaveborkedit** [comment]
Subset of #444.
