### ISSUE TITLE
Where are the FFMPEG temp files?

### ISSUE THREAD

**Issue by CentrixCode** [Rapptz/discord.py#1759]
I was wondering where the FFMPEG temp files are stored because i wanted to do some experimantel things with that folder.

**Comment by Harmon758** [comment]
I'm not sure what temp files for FFmpeg you're referring to, but this is not an issue with discord.py.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with FFmpeg.
For further help specific to using this library, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.
