### ISSUE TITLE
No way to edit webhook channel

### ISSUE THREAD

**Issue by Vexs** [Rapptz/discord.py#1761]
There presently is no provided way to edit a webhook channel post creation as far as I can see- primarily because its the one thing you cannot edit when using tokens to edit webhooks. [Relevant documentation](https://discordapp.com/developers/docs/resources/webhook#modify-webhook-with-token)

As a workaround you can do
`client.http.request(Route('PATCH', '/webhooks/{webhook_id}', webhook_id=webhook.id), json={'channel_id':'123456789'})`

**Comment by ExDomino** [comment]
The workaround is not working because name 'Route' is not defined.

**Comment by apple502j** [comment]
@ExDomino `discord.http.Route`

**Comment by ExDomino** [comment]
Thanks.
