### ISSUE TITLE
Cant use same names of command and subcommand

### ISSUE THREAD

**Issue by itsrave** [Rapptz/discord.py#1765]
I have i command play, and command group playlist. When in code i have "play" command and "play" command in command group "playlist" ($playlist play), i cant use first one.
Code:
`@commands.command(pass_context=True)
	async def play(self, ctx, url):
	# some code

@commands.group(pass_context=True)
    async def playlist(self, ctx):
        if ctx.invoked_subcommand is None:
            await self.client.say('Avaiable subcommands: create, delete, add, remove, play')

@playlist.command(pass_context=True)
    async def play(self, ctx, plsname):
	# some code`
The error is: `Command "play" is not found <discord.ext.commands.context.Context object at 0x7faf4efee5c0>`

**Comment by LucasCLuk** [comment]
This can be fixed by using the ``name`` kwarg in the decorator eg:

```py
@playlist.command(name="play",pass_context=True)
async def playlist_play(self,ctx,plsname):
```
This is just another way of delcaring the command name instead of having it use the function name.

**Comment by itsrave** [comment]
Worked flawessly for me! Thanks :)
