### ISSUE TITLE
support UserProfile.mutual_friends

### ISSUE THREAD

**Issue by bmintz** [Rapptz/discord.py#1766]
Feature request: add a way for selfbots to see friends shared with a given user.

Use case: I'd like to write a small script to sort my friends list by mutual friends

**Comment by BluePhoenixGame** [comment]
Selfbots are against ToS

**Comment by Gelbpunkt** [comment]
Half of this library's features are only usuable on selfbots.
I don't see the point of not adding this, as it's a part of Discord's API, which this library is covering

**Comment by LyricLy** [comment]
@BluePhoenixGame The library doesn't aim to work against selfbots. It has support for many features that only selfbots can use, and commands.Bot even contains a convenience kwarg for people writing selfbots.
