### ISSUE TITLE
A fix for cx_freeze not correctly importing discord.ext.commands

### ISSUE THREAD

**Issue by MarcelBeining** [Rapptz/discord.py#1769]
Hi,
I use cx_freeze to create an Windows executable from my Python program, which uses the Bot class from discord.ext.commands.
However, when freezing and trying to run the executable I get an Import Error because "Bot" is not found.
I found out that the content of folder `discord/ext/commands` does not get copied because `discord/ext` does not contain an `__init__.py` file, hence is not recognized as a package. Adding such a file (with no content) solves the problem!

I'd appreciate if you simply add an `__init__.py` file to `discord/ext` to let python freezers find all of your sub packages successfully.

**Comment by Gorialis** [comment]
This is not an issue with the library. `discord.ext` was changed into a namespace package in bb8f5f4725104d55b1270dedab29e45fca8e3932 and the commands extension is correctly packaged by both `egg` and `wheel`, so there aren't any definition issues.

cx_freeze has [https://cx-freeze.readthedocs.io/en/stable/script.html#cmdoption-include-modules](two) [https://cx-freeze.readthedocs.io/en/stable/distutils.html#build-exe](ways) in which you can include namespace submodules. Any further issues with this should be brought up with them, not us.
