### ISSUE TITLE
AttributeError: module 'aiohttp' has no attribute 'get'

### ISSUE THREAD

**Issue by siddrath** [Rapptz/discord.py#1771]
async with aiohttp.get('http://random.cat/meow%27) as r:
if r.status == 200:
js = await r.json()
await client.send_message(channel, js['file'])

it shows that error can anyone say me what iam missing

**Comment by Vexs** [comment]
Not only have you necro'd an old issue with an earlier comment, this issue isn't even remotely related to discord.py. Consider the aiohttp documentation instead. 

GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.
For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.
