### ISSUE TITLE
purge_from check does not work

### ISSUE THREAD

**Issue by AyJayHam** [Rapptz/discord.py#1775]
the example to delete bots messages given in the API does not work at all.

def is_me(m):
    return m.author == client.user

deleted = await client.purge_from(channel, limit=100, check=is_me)
await client.send_message(channel, 'Deleted {} message(s)'.format(len(deleted)))

if u remove the check it delets all messages in the limit but as soon as a check is added it stops working

**Comment by Hornwitser** [comment]
Please clarify what you mean with "it stops working"

**Comment by AyJayHam** [comment]
It does not return any found messages and also does not delete any messages

**Comment by AyJayHam** [comment]
yes there are

**Comment by diceroll123** [comment]
Compare `m.author.id` to `client.user.id` instead.

m.author is a `Member`, while `client.user` is a `ClientUser`

**Comment by Harmon758** [comment]
Are you encountering any errors?
Can you paste the exact code you're using? Preferably using a [code block](https://help.github.com/articles/creating-and-highlighting-code-blocks/).
What version of discord.py are you using?
