### ISSUE TITLE
Add a user has nitro option

### ISSUE THREAD

**Issue by TerryTheFiganto** [Rapptz/discord.py#1777]
i think what is missing to check if the user has nitro subsribtion or have early supporter and the brilliance badges

**Comment by Gorialis** [comment]
The Discord API does not expose this information to regular bot accounts and so, it is not possible to get this information through the library when using a Discord bot account (as there is no method of obtaining it).

When using the `rewrite` branch, userbots can use [`Client.get_user_profile`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Client.get_user_profile) and from there use [`Profile.nitro`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Profile.nitro) to determine if a user has nitro or not. The other mentioned flags are also documented under the [`discord.Profile`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Profile) category.
