### ISSUE TITLE
how would i go about making a load and unload command?

### ISSUE THREAD

**Issue by EEKIM10** [Rapptz/discord.py#1780]
i dont understand how i get it to work. ive got cogs and the folder, but it wont register it

**Comment by EEKIM10** [comment]
oh ok

**Comment by EEKIM10** [comment]
im using the following code to load n stuff

```
[`@bot.command(hidden=True)`
async def load(*, module : str):
    """Loads a module."""
    try:
        bot.load_extension(module)
    except Exception as e:
        await bot.say('{}: {}'.format(type(e).__name__, e))
    else:
        await bot.say('\N{OK HAND SIGN}')

@bot.command(hidden=True)
async def unload(*, module : str):
    """Unloads a module."""
    try:
        self.bot.unload_extension(module)
    except Exception as e:
        await bot.say('\N{PISTOL}')
        await bot.say('{}: {}'.format(type(e).__name__, e))
    else:
        await bot.say('\N{OK HAND SIGN}')

@bot.command(name='reload', hidden=True)
async def _reload(*, module : str):
    """Reloads a module."""
    try:
        bot.unload_extension(module)
        bot.load_extension(module)
    except Exception as e:
        await bot.say('\N{PISTOL}')
        await bot.say('{}: {}'.format(type(e).__name__, e))
    else:
        await bot.say('\N{OK HAND SIGN}')

```

> 

> ](url)

**Comment by EEKIM10** [comment]
`@bot.command(hidden=True)
async def load(*, module : str):
    """Loads a module."""
    try:
        bot.load_extension(module)
    except Exception as e:
        await bot.say('{}: {}'.format(type(e).__name__, e))
    else:
        await bot.say('\N{OK HAND SIGN}')

@bot.command(hidden=True)
async def unload(*, module : str):
    """Unloads a module."""
    try:
        self.bot.unload_extension(module)
    except Exception as e:
        await bot.say('\N{PISTOL}')
        await bot.say('{}: {}'.format(type(e).__name__, e))
    else:
        await bot.say('\N{OK HAND SIGN}')

@bot.command(name='reload', hidden=True)
async def _reload(*, module : str):
    """Reloads a module."""
    try:
        bot.unload_extension(module)
        bot.load_extension(module)
    except Exception as e:
        await bot.say('\N{PISTOL}')
        await bot.say('{}: {}'.format(type(e).__name__, e))
    else:
        await bot.say('\N{OK HAND SIGN}')`
the code im using for load etc

**Comment by Harmon758** [comment]
Do you get that error when attempting to load the file with the `Test` class?
Is your setup function outside the `Test` class? It's unclear since you're not using [code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/).
You're also attempting to pass your `test` command/function to `add_cog` instead of your `Test` class.
For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends, where you'll also be able to find examples of cogs being used.

**Comment by laggycomputer** [comment]
That last part needs to be repeated constantly; GH Issues are for library problems, not problems using it. For support, join the aforementioned Discord servers.
