### ISSUE TITLE
NameError: name 'client' is not defined

### ISSUE THREAD

**Issue by PonixX** [Rapptz/discord.py#1784]
I am making a chat bot for discord

`    
Bot = commands.Bot(command_prefix=".")

@Bot.event

async def on_message(message):
    if message.author == client.user:
        if "." in message.content:
            UserInput=message.content
            out=chatbot.get_response(UserInput)
            await Bot.send_message(message.channel, out)
        return
    if message.author.bot: return

Bot.run(TOKEN)
Bot.logout()`

The error I get is:

Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\CYBER\Anaconda3\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "<ipython-input-4-7718350c5f21>", line 10, in on_message
    if message.author == client.user:
NameError: name 'client' is not defined

I've been going off of my own knowledge of python along with many different examples I've seen.
I'm not sure what I'm doing wrong and why I'm getting this error.  If someone could help I'd be very grateful

**Comment by Harmon758** [comment]
As the error says, you don't define `client` anywhere.
You're using an instance of `commands.Bot` which you define as `Bot`.
For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.
For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.

**Comment by PonixX** [comment]
> As the error says, you don't define `client` anywhere.
> You're using an instance of `commands.Bot` which you define as `Bot`.
> For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.
> For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.

Okay thanks I fixed it
