### ISSUE TITLE
discord.errors.HTTPException: UNAUTHORIZED (status code: 401): 401: Unauthorized

### ISSUE THREAD

**Issue by PonixX** [Rapptz/discord.py#1786]
I'm not sure what I'm doing wrong here...
This is supposed to be a simple chat bot for Discord.

```
    
Bot = commands.Bot(command_prefix="")


@Bot.event

async def on_message(message):
    if message.author == client.user:
        if "" in message.content:
            UserInput=message.content
            out=chatbot.get_response(UserInput)
            await Bot.send_message(message.channel, out)
        return
    if message.author.bot: return
    
Authorization: 'My Token Here'

Bot.login()
Bot.logout()
```
My correct token is in place of "My Token Here" in my code.
I'm getting an error every time it tries to reply back to me.
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\CYBER\Anaconda3\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "<ipython-input-22-5c7252024c46>", line 13, in on_message
    await Bot.send_message(message.channel, out)
  File "C:\Users\CYBER\Anaconda3\lib\site-packages\discord\client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "C:\Users\CYBER\Anaconda3\lib\site-packages\discord\http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: UNAUTHORIZED (status code: 401): 401: Unauthorized
```

**Comment by CapnS** [comment]
As was sent to you in the last issue you made, github issues are for _errors_ in discord.py, not help with Python. If you need help with using this library, feel free to join the [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by Harmon758** [comment]
I'm not sure why you're still using `client`, why you're logging in (without passing a token) and then immediately logging out, or what `chatbot` and `Authorization: 'My Token Here'` are.
You need to share the actual code that you're using.
Does your bot have permission to send messages in that channel?

This doesn't seem like an issue with discord.py.
GitHub issues for this repository should be used to report issues with the library itself.
For further help specific to using this library, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.
