### ISSUE TITLE
Messages missed during blocking events

### ISSUE THREAD

**Issue by l1n** [Rapptz/discord.py#1799]
Using the rewrite branch here: do `@client.event async def on_raw_message_delete(message)` type things get queued during blocking coroutines? If not, is it possible to add some kind of layer to allow holding those messages, even if they end up out of order?

**Comment by Harmon758** [comment]
The events that occurred will be received by the websocket and dispatched after whatever is blocking finishes executing. This should not be noticeable unless you're [blocking for too long](https://discordpy.readthedocs.io/en/rewrite/faq.html#what-does-blocking-mean).
If you block long enough, your bot will also disconnect. If you're able to reconnect and the bot resumes, you'll receive the missed events.

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.
