### ISSUE TITLE
Choppy audio when playing from URL with FFmpegPCMAudio

### ISSUE THREAD

**Issue by FadedCoder** [Rapptz/discord.py#1802]
This is how the function looks like:

```
source = discord.PCMVolumeTransformer(
    discord.FFmpegPCMAudio(stream_url_from_youtube),
    volume=guild_state.volume)
```

My bot runs on a 1 Gbps up server and my client runs on a 100 Mbps down internet connection. However, the audio still feels choppy, like some parts were hurried and some parts were slowed.

I can't understand, why this is happening? Is this the fault of Discord servers? FFmpeg?

**Comment by devakira** [comment]
This most likely isn't an issue with discord.py. It's probably something with connectivity issues, whether it's your connection or a third-party's.

Issues for this repo are for reporting bugs with the library, and this most likely isn't a bug. For further help, you can join the [discord.py](https://discord.gg/r3sSKJJ) server or the [Discord API server](https://discord.gg/discord-api) and ask your question there. If you believe that this is an issue with FFmpeg, you can learn how to report one [here](https://ffmpeg.org/bugreports.html).
