### ISSUE TITLE
Incorrect explanation for on_reaction_remove?

### ISSUE THREAD

**Issue by numbermaniac** [Rapptz/discord.py#1803]
https://discordpy.readthedocs.io/en/rewrite/api.html#discord.on_reaction_remove

The user parameter is explained as:
```user – A User or Member of the user who removed the reaction.```

However, from experiments done by users on the Discord server, it seems that, if a user's reaction is removed by another user (or bot), then the `user` parameter is the owner of the reaction, not the user that removed the reaction. That contradicts the explanation given in the documentation.

https://discordapp.com/channels/336642139381301249/381965564807086080/528081869070401546 (and some of the subsequent messages below it)

**Comment by gamescom15** [comment]
Even the[ official API Docs](https://discordapp.com/developers/docs/topics/gateway#message-reaction-remove) are unclear on this.
Note that it says "when a user removes a reaction"


![image](https://user-images.githubusercontent.com/10470023/50529978-984f9e80-0af9-11e9-8fb8-034f2ed195a1.png)

**Comment by numbermaniac** [comment]
(PR: #1804)
