### ISSUE TITLE
No good way to separate bulk deletes from single message deletes for logging purposes

### ISSUE THREAD

**Issue by Vexs** [Rapptz/discord.py#1807]
Presently I'm not aware of any clean way to separate bulk message deletes from single message deletes for logging purposes. For example, if someone has a basic deleted message logger that just dumps messages in `on_message_delete` a purge will ratelimit it quite quickly. 

Rewrite provides `on_raw_message_delete` and `raw_bulk_message_delete` which are dispatched separately, however, deleted message logging doesn't work well here, as the message is immediately purged from cache after the event is dispatched- which will lead attempts to fetch said message from cache in any `raw_bulk_message_delete` listener failing. 

An easy fix is just replacing the `message_delete` dispatch inside `ConnectionState.parse_message_delete` with `bulk_message_delete`, which would be dispatched with a list of message objects bulk deleted. 

Alternatively, as a non-breaking change, `RawBulkMessageDeleteEvent` could have an optional list of cached message objects deleted attached to it.

**Comment by Modelmat** [comment]
This same issue exists with knowing if a non raw method has been dispatched for any raw method (eg. was the message in cache).

Another way I was thinking this could be done, is giving the properties (naming may vary) message_was_in_cache or bulk_deleted. This would not break old code, and allow you to filter outer based on these attributes.
