### ISSUE TITLE
TypeError: get_member_named() missing 1 required positional argument: 'self'... But there is NO 'self'

### ISSUE THREAD

**Issue by BlueberryTech123** [Rapptz/discord.py#1812]
It's saying that `get_member_named()` requires a `self` attribute. But according to the docs, it's only `get_member_named(name)`...

**Comment by Helloman892** [comment]
`get_member_named` is an instance method - it needs to have a `Guild` instance as a receiver, rather than the class object.

**Comment by KingWilliam-I** [comment]
I'm having a similar problem with a different instance method. How do I instantiate Guild? what should I pass to the data and state params?

**Comment by Harmon758** [comment]
Please don't necro-bump old closed issues.
You should not be instantiating it yourself. See https://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-get-a-specific-model.
For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README also links.
