### ISSUE TITLE
Custom emojis not parsed properly in message.clean_content

### ISSUE THREAD

**Issue by CorentinJ** [Rapptz/discord.py#1836]
Emojis arent transformed to their name.

**Comment by Harmon758** [comment]
[`Message.clean_content`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Message.clean_content) does not handle Unicode emoji, as Discord parses the syntax for them on input and the message content itself contains the actual Unicode character.
As for custom emoji, see #92.
I'm also unable to reproduce mentions not being transformed properly.
Do you have a reproducible example? What version of discord.py are you using?

**Comment by CorentinJ** [comment]
Mentions were a mistake on my end, so this is just a duplicate of #92.
