### ISSUE TITLE
on_reaction_add on messages before the bot started

### ISSUE THREAD

**Issue by morbyosef** [Rapptz/discord.py#1843]
I am using on_reaction_add event in order to check reaction and I want to use it on a specific message.
Is there any way to use it on a message sent before the bot started so I can use it with a message Id? Thanks

**Comment by Harmon758** [comment]
You can filter [`on_socket_raw_receive`](https://discordpy.readthedocs.io/en/latest/api.html#discord.on_socket_raw_receive) for reactions to messages that are not in the cache.
On the rewrite branch, you can use [`on_raw_reaction_add`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.on_raw_reaction_add).

For further help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by morbyosef** [comment]
Thanks it solves the problem.
