### ISSUE TITLE
did discord-rewrite get removed from pip?

### ISSUE THREAD

**Issue by modernNeo** [Rapptz/discord.py#1848]
I got this error when trying to install

`Collecting discord-rewrite==1.0.0 (from -r requirements.txt (line 3))  `
`    Could not find a version that satisfies the requirement discord-rewrite==1.0.0 (from -r requirements.txt (line 3)) (from versions: )`  
  
and sure enough, when I googled it, [`discord-rewrite`'s page](https://pypi.org/project/discord-rewrite/) on pip now says package is not found. It is being pulled or just a temporary glitch?

**Comment by Vexs** [comment]
`discord-rewrite` was never an official distribution. It was an old version put up there by someone. To install the rewrite branch, use `pip install -U git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]` instead.

**Comment by modernNeo** [comment]
is there a reason why the developers **don't** release it via a package on pypi?

**Comment by lejakewolf** [comment]
Talking about why the rewrite branch isn't released yet? If yes, that's because the rewrite branch is still in development. No one really knows when it'll be released. But when it is indeed released, it'll be an update to the discord.py package anyway. It's just a waiting game for now.

**Comment by modernNeo** [comment]
I see. are there bugs that they need to work out or still more upcoming features that they want to implement before releasing it or is something else entirely holding it up?

**Comment by modernNeo** [comment]
or is there no reason and they just havent gotten around to it yet?

**Comment by gogurtenjoyer** [comment]
"because the rewrite branch is still in development" as was said above.

**Comment by modernNeo** [comment]
"still in dev" could mean either bugs to work out or more upcoming features or both. I was just curious if it was one or the other.

**Comment by lejakewolf** [comment]
I believe Danny has some features that he wants to add before releasing the rewrite branch. There could also be bugs. But I would think it's mainly because Danny wants to add some more features but hasn't gotten around to completing them yet.

**Comment by gogurtenjoyer** [comment]
Perhaps this link will help:
https://github.com/Rapptz/discord.py/projects/1 
There's at least one upcoming breaking change.

**Comment by modernNeo** [comment]
I see. well since my initial query has been answered, guess I can close this issue. thanks for the info

@gogurtenjoyer guess I should have seen that myself and damn, didnt know he was planning all that. look forward to it.
