### ISSUE TITLE
Rewrite : Breaking disconnection issue (which doesn't kill the process)

### ISSUE THREAD

**Issue by Nenrikido** [Rapptz/discord.py#1850]
So it's been several weeks since i have a lot of issues, my bots using d.py rewrite are disconnecting randomly between 10 minutes and 2 days after their launch. I've this log from an entire session (sorry, it's using the python module logging so i've not the timestamps) https://hastebin.com/gaqatuyebi.php.
I've tried putting a `reconnect=True` inside `bot.run`, it doesn't work. And as the process doesn't kill, systemd or screen can't reboot it.
Thanks for reading this and i'm hoping that there'll be some patches to, at least, kill the process in case of breaking exceptions

**Comment by Hornwitser** [comment]
Please provide the code for your bot, preferably a minimum complete example experiencing the issue, as it's simply not possible to debug your problem for the log alone.

**Comment by Nenrikido** [comment]
Here's the pastebin of the bot code : https://pastebin.com/GAVPP7Mh it'll expire in 1 day, so copy it if you want to analyze it for more (I don't want it to be online for too much).
And i can't give you an example of an experience of the issue, as, as i said, it's happening randomly. But, as an example, the bot is currently running (at least the system daemon) but disconnected

**Comment by Nenrikido** [comment]
@lejakewolf It's not even used, as u can see in the profile command, the if False disable it

**Comment by Gelbpunkt** [comment]
@Diniboy1123 had the exact same issue, a discord developer stated this:
![Image](https://raw.githubusercontent.com/Gelbpunkt/known-discord-issues/master/status-changing.png)

Removing frequent status changes fixed the problem for us.
I don't know how helpful this is for you, as I don't know how big your bot is and therefore whether you're affected or not. Just try it

**Comment by Nenrikido** [comment]
My bot was big before (by big i mean, 30+ servers) and i had this issue, now it's not big anymore, but i've still the issue, so idk, i'll try anyway

**Comment by Rapptz** [comment]
Due to lack of reproducible steps this issue will be closed now. If the issue still happens feel free to open a new issue that has more information to reproduce it.
