### ISSUE TITLE
Get the id of a user

### ISSUE THREAD

**Issue by C0deDuck** [Rapptz/discord.py#1853]
How do you get the id of a specific user that is not the author of the message?

**Comment by C0deDuck** [comment]
But I can only get the user object if I have the id

**Comment by Harmon758** [comment]
There are other ways to get `User` objects, depending on what you're trying to do.

This isn't an issue with the library itself though, so you should join the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for further help.
