### ISSUE TITLE
Integrate a REST API with aiohttp

### ISSUE THREAD

**Issue by Shellwhale** [Rapptz/discord.py#1856]
Hello. I am looking for a way to integrate a REST API inside my bot, using the rewrite branch. I thought I should using aiohttp to handle requests but I am unsure of which approach I should take. The objective is to make for example a GET request to the API that would return a list of guilds the bot is in. Or as another example, a POST request that would ask the bot to write a given message into a specific channel. It's not just about retrieving data (I'd simply write what I need in file) but rather have a full control over HTTP.   

Issue is, my aiohttp server isn't able to retrieve any data from the client instance. Besides, the aiohttp server does not run asynchronously. I expect the on_ready(self) to run, but it never does. What am I doing wrong ?

```python
import discord
import asyncio
from aiohttp import web

client = discord.Client()

async def on_ready():
    print(f'Logged on as {client.user}!')

async def get_guilds(request):
    guilds = []
    for guild in client.guilds:
        print(guild) # Print nothing 
        guilds.append(guild)
    return web.Response(text=str(guilds)) # Return an empty list

bot_task = client.loop.create_task(client.start(TOKEN))
app = web.Application()
app.router.add_get('/guilds', get_guilds)
web.run_app(app, port=80)
```
PS : I've looked for help over at the official discord.py server, discord api server and stackoverflow with no concrete success.

**Comment by crrapi** [comment]
Although this is not necessarily related to the library, you could [run a Flask app in a discord.py bot using this example](https://gist.github.com/crrapi/c8465f9ce8b579a8ca3e78845309b832). Aiohttp's web server is probably fighting with discord.py, trying to take control of the event loop.

**Comment by Harmon758** [comment]
This is because [`aiohttp.web.run_app`](https://docs.aiohttp.org/en/stable/web_reference.html#aiohttp.web.run_app) is blocking.
For information on how to run an aiohttp server asynchronously, see https://docs.aiohttp.org/en/stable/web_advanced.html#application-runners and other relevant aiohttp documentation.

This isn't an issue with discord.py itself, so for further help, I'd recommend you still ask in the official discord.py server or other forums that provide help with Python. If you're unable to find any help, feel free to mention or DM me; I'll always respond if I can help and it's still unresolved, even if I see it belatedly.

**Comment by Vexs** [comment]
The method used by @crrapi is.... not recommendable at all. If you want to host a webserver in the same process as the bot, use the method @Harmon758 provided. You may also look at quart as an asynchronous webserver lib, which will likely have similar methods.

However, I'd recommend separating your bot and webserver processes and talking between the two- either using a small API server hosted on the bot, a messaging queue like rabbitMQ, or you could even leverage a DB's pubsub or notify services, if they exist.

Also as Harmon noted, this isn't an issue with discord.py at all. Lib issues are for issues with the lib itself, no general help. You should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for further detail.

**Comment by Shellwhale** [comment]
@Vexs If I get you right, I should make two process. One for the bot, one for the REST API. 
Now what I need is a way for them both to communicate. 

You mentioned "using a small API server hosted on the bot" but that is kind of what I am trying to do in the first place thus I guess I should be using something different than aiohttp for the bot itself. But what would that be ? Could redis.io be a solution ? I'm running everything inside Docker containers by the way.

**Comment by Vexs** [comment]
I suppose I didn't say that very well- if you're intending to do some web control panel or the like, you'll want separate processes. If you want to set up an API to control the bot, same process for the api server is an obvious ease- but the other methods mentioned are also good options.

I'm not going to go into full detail on how to design your system in github issues, however. You're welcome to find me on our discord.

**Comment by jhorst** [comment]
@Shellwhale if you need to know bot info... write it to a json file via the bot and read it from the rest API. A Webhook can be named the same as your bot... the rest API can send a msg to the channel via that. This was my approach... I did try it the first time like you want, I don't recommend it.
