### ISSUE TITLE
There is no On_Member_Kick event listener

### ISSUE THREAD

**Issue by UGEYT** [Rapptz/discord.py#1858]
There is on member ban but not on member kick, which is leaving me with little to no ways of detecting kicks whilst running in background.

**Comment by Vexs** [comment]
There is no on_member_kick event because discord does not provide an event for it. See [the documentation](https://discordapp.com/developers/docs/topics/gateway#commands-and-events-gateway-events)

**Comment by UGEYT** [comment]
Is there any way to detect kicks? Maybe on audit log or something? Wait for audit log kick?

**Comment by Vexs** [comment]
There is no provided event for audit logs updating either.

You can poll the audit log on member leave, that's it. For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by UGEYT** [comment]
I’m on the discord, but I sometimes get hostile remarks for my lack of knowing every square inch of the documentation.
