### ISSUE TITLE
Flattening discord.Reaction.users returns the first 100 users over and over

### ISSUE THREAD

**Issue by TunnelBlanket** [Rapptz/discord.py#1859]
Performing the following:
```python
users = await message.reactions[0].users().flatten()
```
on a message with 1.2k+ reactions returns a list of the first 100 users 12 times. I'm not sure if this bug is limited to `.flatten()` usage but it makes no sense to me considering `.flatten()` has no documented limit and `.users()`'s limit is automatically set to `None`.

**Comment by Harmon758** [comment]
This should now be fixed with https://github.com/Rapptz/discord.py/commit/4b22dd216cae63273d75379d321a219e68dab9f9 (#1860).

**Comment by TunnelBlanket** [comment]
Awesome! Thanks!
