### ISSUE TITLE
bot.command and bot.event on_message

### ISSUE THREAD

**Issue by NotSoSuper** [Rapptz/discord.py#186]
`bot = commands.Bot(command_prefix='.', description=description)`

Whenever you have bot.command and `@bot.event async def on_message(message):` in the same code, it breaks all the commands (bot.command).

Not sure why but anywhere you put it, the event for on_message works perfectly but none of the commands work for some reason!

**Comment by imayhaveborkedit** [comment]
Since the commands stuff isn't really documented, you're probably not to blame for this, but see this docstring: https://github.com/Rapptz/discord.py/blob/async/discord/ext/commands/bot.py#L558

**Comment by NotSoSuper** [comment]
I see, what would I do to fix this? Have another @asyncio.coroutine or async

**Comment by Rapptz** [comment]
Make sure you call `await bot.process_commands(message)` somewhere in the function once.

**Comment by NotSoSuper** [comment]
thank you good sir, all fixed.

**Comment by Ciinny** [comment]
It doesn't work for me :/

**Comment by paradoor** [comment]
@Ciinny Be more specific. Are you getting errors? Does nothing happen when you try to call commands? What's your code?

**Comment by Rapptz** [comment]
Please don't necro old issues with irrelevant comments.
