### ISSUE TITLE
Announcer

### ISSUE THREAD

**Issue by IAmSeager** [Rapptz/discord.py#1867]
Hey there, i have a problem. I want to code a listener that will send discord message into channel when google website content changes. I've did the website part but i don't know how to send messages outside of event functions. 

EDIT: Sorry about the weird code insertion. This is my first GitHub issue tbh.

import hashlib
import urllib.request
import time
import discord
import asyncio
from bs4 import BeautifulSoup

class MyClient(discord.Client):
    async def on_ready(self):
        print('Logged in as')
        print(self.user.name)
        print(self.user.id)
        print('------')

#Set the url http:// or https:// format
website = "http://www.google.com/"

first = True
with urllib.request.urlopen(website) as url:
        html = BeautifulSoup(url)
        lastHash = hashlib.md5(html.encode("utf-8")).hexdigest()
while(True):
    with urllib.request.urlopen(website) as url:
        html = BeautifulSoup(url)
        Hash = hashlib.md5(html.encode("utf-8")).hexdigest()
        print(lastHash, Hash)    
        if(Hash != lastHash):
            client = MyClient()
            client.run('myId not going to tell u lol')
            
        lastHash = Hash    
        time.sleep(5)

**Comment by Harmon758** [comment]
First of all, you're going to want to change your token now if you haven't already.
Secondly, `urllib.request` is [blocking](https://discordpy.readthedocs.io/en/latest/faq.html#what-does-blocking-mean).
What channel is the message supposed to be sent in? If it's a predetermined channel that you have the ID for, see https://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-send-a-message-to-a-specific-channel.

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.
For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.

**Comment by IAmSeager** [comment]
Thanks. did some research on internet and made it to work.
