### ISSUE TITLE
Rewrite: please add a `invoked_parent` feature.

### ISSUE THREAD

**Issue by MonAaraj** [Rapptz/discord.py#1874]
I know it's not a must, I can do it regularly, with `{ctx.message.content[0:(len(ctx.message.content)-(len(ctx.invoked_with)+1))]}` inside the subcommand, but is that really how you wanna do it? is that good code? I just thought that `invoked_parent` would be good to add, thank you.

**Comment by gear4s** [comment]
[This](https://discordpy.readthedocs.io/en/rewrite/ext/commands/api.html#discord.ext.commands.Command.full_parent_name), [this](https://discordpy.readthedocs.io/en/rewrite/ext/commands/api.html#discord.ext.commands.Command.root_parent) or [this](https://discordpy.readthedocs.io/en/rewrite/ext/commands/api.html#discord.ext.commands.Command.qualified_name) seems like what you need

**Comment by Phxntxm** [comment]
`full_parent_name` retrieves the qualified name, aka it would not reveal what alias is used
`root_parent` retrieves the actual `Group` object, again it would not reveal the alias used
`qualified_name` same issue as `full_parent_name`

None of these server what he is asking for

**Comment by gear4s** [comment]
then maybe it should be named as "invoked_parent_alias" instead of "invoked_parent", or he should specify that he wants the parent *alias* not just the parent's *qualified name*

**Comment by Phxntxm** [comment]
He never specified that he wanted the qualified name, you just misinterpreted. If you'd look at the code that he used to "mock" what he is wanting, you'd see that he wanted the alias, as that is what it would return. I see nothing wrong with how he described it. If this was chosen to be added, then it can be called whatever then, the name of the variable is not really the important detail here.
