### ISSUE TITLE
[rewrite] Random bot crashes

### ISSUE THREAD

**Issue by Diniboy1123** [Rapptz/discord.py#1875]
Sometimes the bot goes offline, the websocket connection dies but the process still seems to be running and doesn't even attempt to reconnect. It's really rare once it throws an exception so I wasn't prepared for it completely, that's why I only have the exception's last part from the journalctl logs... If it happens again and if needed, I can provide a more detailed traceback.

```
it_for=<Task pending coro=<WebSocketCommonProtocol.transfer_data() running at /home/travitia/.local/lib/python3.6/site-packages/websockets/protocol.py:532> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f92ac10a6a8>()]> cb=[<TaskWakeupMethWrapper object at 0x7f92ace81558>()]>>
Exception ignored in: <generator object WebSocketCommonProtocol.close_connection at 0x7f92ad213518>
RuntimeError: generator ignored GeneratorExit
```

Any ideas?

**Comment by Harmon758** [comment]
There's not much to go on here, but this seems like an issue with websockets rather than discord.py.

**Comment by Diniboy1123** [comment]
That's what I thought. I'll try to get a proper exception then and ask it there. Thank you
