### ISSUE TITLE
[rewrite] ytd player stream 

### ISSUE THREAD

**Issue by Maladra** [Rapptz/discord.py#1878]
I use youtube_dl and work very well but since a few days, the music stop before end and I have this message.
`[tls @ 0500eb60] Error in the pull function.`
`[matroska,webm @ 0501c500] Read error`
`[tls @ 0500eb60] The specified session has been invalidated for some reason.`
`Last message repeated 1 times`

I see this issues #315, but nothing work for me.

**Comment by Harmon758** [comment]
Also duplicate of #157, #671, and #756.
