### ISSUE TITLE
Command.qualified_name

### ISSUE THREAD

**Issue by NeuroAssassin** [Rapptz/discord.py#1879]
I'm trying to make a commandchart command where it gets the latest commands used in a channel by getting the context of it, and was using `ctx.command.qualified_name`, but instead of giving me the whole command name, it instead only gave me the root command (for example, if you typed in `[p]groupy subgroupy subcommand argument`, you should get `groupy subgroupy subcommand`, but instead I was getting just `groupy`.).  I have some pictures below.

Picture of the command I was using:
![image](https://user-images.githubusercontent.com/42872277/52276242-b17d1380-291f-11e9-90f2-265960c8bd60.png)

Me getting the context of the message and the qualified_name of it:
![image](https://user-images.githubusercontent.com/42872277/52276297-d3769600-291f-11e9-941b-f8555a58b123.png)

**Comment by NeuroAssassin** [comment]
I just looked into the library a bit, and I think I know what the problem is.  When the command is initialized, it sets `parent` to `None`, and doesn't change that.  Then, when you call `qualified_name`, it runs `full_parent_name`.  Since `parent` is equal to `None`, it returns an empty list, and then `qualified_name` returns only the name of the command since the return value from `full_parent_name` is an empty list.

**Comment by NeuroAssassin** [comment]
I just looked into the library a bit, and I think I know what the problem is.  When the command object is initialized, it sets `parent` to `None`, and doesn't change that.  Then, when you call `qualified_name`, it runs `full_parent_name`.  Since `parent` is equal to `None`, it returns an empty list, and then `qualified_name` returns only the name of the command since the return value from `full_parent_name` is an empty list.

`self.parent` declaration: https://github.com/Rapptz/discord.py/blob/rewrite/discord/ext/commands/core.py#L181
`full_parent_name`: https://github.com/Rapptz/discord.py/blob/rewrite/discord/ext/commands/core.py#L408
Where `qualified_name` checks if return value is empty:
https://github.com/Rapptz/discord.py/blob/rewrite/discord/ext/commands/core.py#L452

**Comment by Phxntxm** [comment]
The issue here isn't with a command's qualified name, it's with `ctx.command`

![image](https://user-images.githubusercontent.com/3664828/52283635-74694f00-2928-11e9-9868-5d6ac2e62f13.png)

When a command is added to a group, it has the parent set to the group:
https://github.com/Rapptz/discord.py/blob/rewrite/discord/ext/commands/core.py#L868

So like mentioned, it's not an issue with the qualified name:
![image](https://user-images.githubusercontent.com/3664828/52283735-a8447480-2928-11e9-8498-df0efb13bc97.png)

**Comment by NeuroAssassin** [comment]
> The issue here isn't with a command's qualified name, it's with `ctx.command`
> 
> ![image](https://user-images.githubusercontent.com/3664828/52283635-74694f00-2928-11e9-9868-5d6ac2e62f13.png)
> 
> When a command is added to a group, it has the parent set to the group:
> https://github.com/Rapptz/discord.py/blob/rewrite/discord/ext/commands/core.py#L868
> 
> So like mentioned, it's not an issue with the qualified name:
> ![image](https://user-images.githubusercontent.com/3664828/52283735-a8447480-2928-11e9-8498-df0efb13bc97.png)
> 
> When the command is actually _invoked_ then the handling of subcommands happens:
> 
> https://github.com/Rapptz/discord.py/blob/rewrite/discord/ext/commands/core.py#L1009
> 
> Since you're doing a "get message then get context from message" with no invoke, this step never happens. However in normal cases where commands are just called, the invoke will fix up the subcommand step.

So then, the problem is that `context.command` is returning the first command that is in it, instead of the last one, if I understand your comment correctly @Phxntxm

**Comment by Phxntxm** [comment]
Yes, I edited my first comment to explain why this is...sorry forgot to put it in the original post.
