### ISSUE TITLE
Add property to HelpFormatter for i18n

### ISSUE THREAD

**Issue by cod-sushi** [Rapptz/discord.py#1886]
I'm developing japanese language discord bot.

`ext.commands.Bot` class has `command_not_found` and `command_has_no_subcommands` property.
Document says, They are useful for i18n. I use them usefully.

But, in `HelpFormatter` class's `get_ending_note` method, message `Type {0}{1} command for more info on a command. You can also type {0}{1} category for more info on a category.` is fixed text.
It's not useful for i18n.
I want `help_more_info` property to `HelpFormat` class, like `command_not_found` of `Bot`.

**Comment by Vexs** [comment]
If you want this, you can subclass the formatter and pass it on `commands.Bot` initialization.

For example:
```py
class myFormatter(commands.HelpFormatter):
    def get_ending_note(self):
        command_name = self.context.invoked_with
        return "whatever you want. Prefix: {0}, command: {command_name}".format(self.clean_prefix, command_name)

bot = commands.Bot(formatter=myFormatter(), **kwargs)```

**Comment by cod-sushi** [comment]
Thank you for your quick response and  kindness to give me example codes! 
You're right. However, with all due respect, something feels weird.

Although it is the same "help" command wording modifying,
there are different patterns:
· Subclassing(for help command not found)
· Setting properties(for help command below message)

Feel a little disproportionately...
Can I try make pull-request? (or it is contrary to the design?)

Sorry for my broken English :weary:

**Comment by cod-sushi** [comment]
Or, I want to add docs(FAQ or tutorial) about guide for bot translation.

**Comment by Vexs** [comment]
I'm not sure I follow- both require subclassing, and documentation PRs are always welcome.

**Comment by cod-sushi** [comment]
I'm sorry. about 
> · Setting properties(for help command below message)

What I mean is:
```python
from discord.ext import commands
TOKEN = XXXX...

bot = commands.Bot()
bot.add_command(some_command)
bot.command_not_found = "Command {} not found." # no need to subclass
bot.run(TOKEN)

@commands.command()
def some_command(ext):
    ...
```

**Comment by Vexs** [comment]
As far as I am aware, `bot.command_not_found` isn't part of discord.py, and if it did exist, that functionality would not be part of the helpformatter. Perhaps you are referring to the `CommandNotFound` error raised in command processing? (which is still not an attribute of commands.Bot)

As a note, it's not required to call `bot.add_command(some_command)` in your main file. You can simply use the `bot.command` decorator instead. For other files, you can use the automatic command-adding of cogs.

**Comment by cod-sushi** [comment]
@bot.command & cogs! thank you. I am going to use cogs lerning from RoboDanny's code.

**Comment by cod-sushi** [comment]
On second thought, I need to translate not only `"Type {0}{1} command for more info on a command. You can also type {0}{1} category for more info on a category."`, but also `"Commands:"`
