### ISSUE TITLE
[rewrite] Any plans to merge rewrite with master and use release mechanism

### ISSUE THREAD

**Issue by tmitrovich** [Rapptz/discord.py#1895]
Any plans to merge the rewrite branch with master and start using the release mechanism again? It would be **GREAT** if we could start using pip to install the library based on specific version numbers. Thoughts from others?

**Comment by SnowyLuma** [comment]
This is planned, but will most likely not happen before the [Rewrite Project](https://github.com/Rapptz/discord.py/projects/1) is finished and all issues/PRs with the [Rewrite Milestone](https://github.com/Rapptz/discord.py/milestone/5) are fixed/merged.

**Comment by CraftSpider** [comment]
I feel that at this point, the async branch being on master is doing more harm than good. It has several known issues, and doesn't support multiple new discord features. Despite the project not being 100% complete, rewrite is the more stable branch. It seems odd to have the 'official release' be the less stable branch.
