### ISSUE TITLE
[rewrite] Trailing whitespaces on bytestrings passed into _get_mime_type_for_image

### ISSUE THREAD

**Issue by MonoHearted** [Rapptz/discord.py#1901]
I recently ran into an issue regarding an "invalid" image when attempting set an avatar. It appears that the read image byte string ends with trailing whitespace (``b' '``). Appending an ``.rstrip(b' ')`` resolves the issue.

I am unsure how common this issue is; but replacing the existing ``.rstrip(b'\0')`` with ``.rstrip(b' \0')`` on line 252 of utils.py would resolve this.

**Comment by MusicOnline** [comment]
An example image which caused this issue for OP:
![image](https://user-images.githubusercontent.com/39178127/52871742-b777bd80-3185-11e9-9df9-416bffb0101a.png)
