### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by joshua-s** [Rapptz/discord.py#1903]
I would like to use this project, but it seems unmaintained (the last commit was over a year ago). Is it dead?

**Comment by XuaTheGrate** [comment]
The rewrite branch exists but async should still work fine for the most part.

**Comment by IamTails** [comment]
Check the rewrite branch

**Comment by Harmon758** [comment]
The async branch is no longer in development.
The rewrite branch was updated within the last 24 hours.

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.

**Comment by joshua-s** [comment]
Thank you!
