### ISSUE TITLE
Listing all roles in a guild

### ISSUE THREAD

**Issue by DuckyWucky69** [Rapptz/discord.py#1905]
I have tried to do many different things and nothing seemed to work, im not a proffesionalist at python, but in most cases i do understand what is happening. sadly this is not one o those times.
I am trying to list all roles that the server contains. I am attempting to do this by using the following code.
`        embed.add_field(name="Roles", value=server.roles, inline=False)`
however, I do know that this won't work just I have no idea what will work. I've looked everywhere for awnsers but nothing is suitable for my problems. I am using `discord.py async python version 3.6.5` and i have no idea how to get all roles inside an embed. Thanks in advance!

**Comment by CapnS** [comment]
This is not an issue with discord.py.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python or using the library.
For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by Harmon758** [comment]
[`Embed.add_field`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Embed.add_field) accepts a string for `value`, and [`Server.roles`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Server.roles) is a list.
