### ISSUE TITLE
Labelling issues

### ISSUE THREAD

**Issue by MusicOnline** [Rapptz/discord.py#1910]
Here's a meta-issue. Can issues be labelled more actively, with the birth of @dpy-manager-bot? Especially the `question` label, so that real issues can be seen at a glance.

**Comment by NCPlayz** [comment]
Had an RFC tag for ages so I might as well give my two cents... I feel like there should be a role (bar Proficient) that can help label issues, since at times, Proficients aren't always available. Asking to give more to the role is probably too risky.

**Comment by Rapptz** [comment]
Issues have now been automatically assigned via templates so there aren't any unlabeled issues outside of really old ones thankfully, so not much to do now.
