### ISSUE TITLE
[rewrite] make discord.Greedy raise MissingRequiredArgument

### ISSUE THREAD

**Issue by flapili** [Rapptz/discord.py#1914]
Hi, is it possible to does Greedy raise MissingRequiredArgument if is empty, so we would have
```Python
async def foobar(ctx, numbers: Greedy[int] = []):
```
for optional args and that for required args
```Python
async def foobar(ctx, numbers: Greedy[int]):
```
that will raise `MissingRequiredArgument` if `numbers` is empty.

Maybe add new converter to avoid break some codes ?
for now i'm using ugly trick
```Python
	async def emoji_remove(self, ctx, emojis: commands.Greedy[discord.Emoji]):
		if not emojis:
			signature = inspect.signature(self.emoji_remove.callback)
			params = signature.parameters
			raise commands.errors.MissingRequiredArgument(params["emojis"])
```

ps: sorry for poor english i'm French and I would have liked to propose a pull request but is but it's too hard for my level 😦

**Comment by Rapptz** [comment]
I don't think I'm going to change the behaviour of `Greedy` to account for this. For an overwhelming majority of cases, I believe an empty list is what people expect and want.

You don't have to raise `MissingRequiredArgument` nor use that hack in your code -- you can use any other exception derived from `CommandError` to get the same effect without going through the `inspect` effort. The error handler will capture it all the same.
