### ISSUE TITLE
[Rewrite] HTTP 400 misidentified as throttling

### ISSUE THREAD

**Issue by hlieberman** [Rapptz/discord.py#1917]
In the debug logs, discord.py seems to misidentify an HTTP 400 as a throttling error inside the emoji handling sequence.

For example:
```
Feb 22 22:03:14 li64-16 python3[2783]: DEBUG:discord.http:PUT https://discordapp.com/api/v7/channels/xxxxxx/messages/xxxxxx/reactions/%E2%9C%94%EF%B8%8F/@me with None has returned 400
Feb 22 22:03:14 li64-16 python3[2783]: DEBUG:discord.http:A rate limit bucket has been exhausted (bucket: PUT:xxxxxx:None:/channels/{channel_id}/messages/{message_id}/reactions/{emoji}/@me, retry: 0.25).
```

**Comment by hlieberman** [comment]
Actually, looking in more detail, this seems to be a broader problem.

In [http.py](https://github.com/Rapptz/discord.py/blob/rewrite/discord/http.py#L162) we're assuming that all circumstances where `X-Ratelimit-Remaining` is 0 and we're not being throttled overall that we've exhausted a particular bucket.  That's not necessarily the case -- when I repeat the above posted request, the JSON that I get back is clearly not a case of the bucket being full:

```javascript
{'code': 10014, 'message': 'Unknown Emoji'}
```

I'm not clear on the purpose of this block of code, or I'd attempt to PR it myself.  Reading the Discord API docs seems like it should be able to be merged into the block beginning L178, even though the if clause clearly separates the two.

**Comment by Rapptz** [comment]
This seems like a discord issue if this is the case and not one of mine. This assumption is generally safe to make, so I'm not going to fix it since that is the documented behaviour that we are expected to implement. In short, if Discord reports that we have no requests remaining when we do indeed have requests remaining then that seems like a bug on their end.

The purpose of that block is pre-emptive rate limiting -- a key part that libraries are expected to implement so bots do not get banned for spamming requests.

**Comment by hlieberman** [comment]
It might be worth adding a special exception to the emoji case, at least.
It's documented that the values aren't reliable when you're making emoji
calls.

-- 
Harlan Lieberman-Berg
~hlieberman

**Comment by Rapptz** [comment]
That exception is not for *reactions*, but rather for the *management* of custom emoji.

**Comment by khazhyk** [comment]
http:A rate limit bucket has been exhausted means the *next* request would be rate limited if we don't delay, it has nothing to do with the request status

**Comment by hlieberman** [comment]
Closing in favor of https://github.com/discordapp/discord-api-docs/issues/864.
