### ISSUE TITLE
You are being rate limited.

### ISSUE THREAD

**Issue by NotLazy** [Rapptz/discord.py#192]
Up until recently, my bot was operating fine. Specifically, the chat clearing function. Then, today, I try to clear a chat with "!!purge 100" and it only clears about 4-5 messages, then stops. Now at the time I thought "Oh weird." and didn't think to check the console. Then, just a few minutes ago, I was working on it to try to fix it, and went to close the console to refresh the code, and noticed this:

`discord.errors.HTTPException: TOO MANY REQUESTS (status code: 429): You are being rate limited.`

**Comment by EJH2** [comment]
I just tested on mine and can confirm that this is happening.

**Comment by NotLazy** [comment]
Found the issue. Went to test this on RH1-N0 and he said this:

> Due to a recent rate limit added to message deletion by the Discord Developers, I can no longer delete messages in a quick and efficient way as I am only allowed to remove 5 messages per second across all servers that I serve.
If you think this is a silly restriction like I do, I suggest telling them that on their server which I'll link for you!
<br>I've been fitted with a new command "!softban" which willban and unban a user, clearing all of their messages! The Devs suggest to use thisrather than purge. I'm sorry for any inconvenience that this may cause and hope you have a great day <3
<br>https://discord.gg/0ESuwoZe4M4iCEEw

Question is now, 1: Why did they do this, and 2: Can they do us a solid and remove it?

**Comment by SunDwarf** [comment]
`await asyncio.sleep(0.21)`

**Comment by NotLazy** [comment]
@SunDwarf That fixes the issue, but like RH1-N0 mentions it's not a "quick and efficient way". It'd be nice if they just reverted the change.

**Comment by SunDwarf** [comment]
Wait until `delete_many` is implemented.

**Comment by khazhyk** [comment]
The only current solution is to delete slower. Let the devs know that you want the ability to fast delete a lot of messages. :) As it stands, there is no chance this rate limit will be reverted.

**Comment by AraHaan** [comment]
or look at #204.

**Comment by jaydenkieran** [comment]
As of hammerandchisel/discord-api-docs/issues/40, a new **bulk delete** endpoint was added for bot accounts. https://github.com/Rapptz/discord.py/commit/1b601097d2a5e5c2a3ab1e7e257472212ee63aec and https://github.com/Rapptz/discord.py/commit/1f86a9b795326ce72a03f4bde6dbebb676ff60d8 both implement the endpoint.
