### ISSUE TITLE
[Rewrite] Cog names with spaces can't be accessed in the default help

### ISSUE THREAD

**Issue by ir-3** [Rapptz/discord.py#1921]
When a cog has a name with spaces, it cannot be accessed in the default help command. 

For example, _"help image manipulation"_ returns _"No command called "Image" found."_. I am not sure how to resolve this but it is a tad annoying.

**Comment by ir-3** [comment]
This was dumb, you can just use quotes 🤦‍♂️...

**Comment by MusicOnline** [comment]
IMO, you should be able to do `?help My Cog Name With Spaces` without adding quotes. (aka the lib should try to look for a cog by joining the arguments first)
It's not user friendly if I have to add quotes to get the cog.
Also, to be honest, I discovered cog-specific help pages only way later after using discord.py. (wasn't that obvious to me that I could do that)

~~Should be a quick PR :eyes:~~
