### ISSUE TITLE
Position of Check decorators causes check bypassing

### ISSUE THREAD

**Issue by ryanbroman** [Rapptz/discord.py#1923]
On version `1.0.0a1691+gf686924` (latest as of 24 Feb 2019), if the `is_owner()` check is *above* `command()`, non-owners are able to run the command just fine.

 
![image](https://user-images.githubusercontent.com/10637001/53306287-05548b80-3840-11e9-9e94-4665dc37b1ae.png)

**Comment by Harmon758** [comment]
This should have been fixed with https://github.com/Rapptz/discord.py/commit/9827d6eeaf191fb4cd8a144388804617922f50f4, and I'm unable to reproduce it anymore.
Are you sure you're on version 1.0.0a1691+gf686924?

**Comment by ryanbroman** [comment]
![image](https://user-images.githubusercontent.com/10637001/53319202-b716ab00-3886-11e9-9992-bb70ed2ac913.png)
From what I can tell, yes. But if this is CNR then it must be some odd issue on my end, I guess?

**Comment by Harmon758** [comment]
Can you provide a minimal reproducible example?

**Comment by ryanbroman** [comment]
I don't think I can. I created a blank project to try and reproduce the issue, however it works fine. Doesn't make a lot of sense, but alas...

**Comment by VisualTuber** [comment]
Something else might be causing this issue, check above the check to find out why it doesn't work
