### ISSUE TITLE
Can't get str, int or float from param even with typing.Union

### ISSUE THREAD

**Issue by d4sein** [Rapptz/discord.py#1925]
this works:
```
async def clear(ctx, amount: typing.Union[int]):
```

this doesn't:
```
async def clear(ctx, amount: typing.Union[int, float, str]):
```

I get this error: `AttributeError: '_Union' object has no attribute '__name__'`

I apologize if I'm being obnoxious with those issues, but I'm really confused with that.

**Comment by Harmon758** [comment]
As stated in #1924, the `typing.Union` converter exists on the rewrite branch, not the async branch, and for further help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api).
