### ISSUE TITLE
[commands] can't stack @commands.Cog.listener(name=...)

### ISSUE THREAD

**Issue by bmintz** [Rapptz/discord.py#1926]
```
🐍 class Stats(commands.Cog):
••      @commands.Cog.listener(name='on_guild_join')
••      @commands.Cog.listener(name='on_guild_remove')
••      async def on_guild_change(self, guild):
••              await self.send_stats()
•• 
🐍 cog = Stats()
🐍 cog.get_listeners()
[('on_guild_join', <bound method Stats.on_guild_change of <__main__.Stats object at 0x7fd09d50ffd0>>)]
```
I expected there to be two entries, one for `on_guild_join` and another for `on_guild_remove`. 

Currently I'm using the following code in my stats cog:
```py
for guild_change_event in 'on_guild_join', 'on_guild_remove':
    self.bot.add_listener(self.on_guild_change, guild_change_event)
```

But this has the downside of not being removed when the cog is unloaded.

**Comment by Rapptz** [comment]
Currently this is by design.

I'd have to change the implementation to a list instead of a single string to allow this to work. Not sure how common this is but it is possible/worth considering.

**Comment by Phxntxm** [comment]
Since you're curious how common this is I'd like to +1 this.... It's quite common for bots on those bot sites to send their stats on guild changes...I currently make the same method call on GUILD JOIN/LEAVE and READY....I'd love this change, would be a nice QOL thing imo

**Comment by bmintz** [comment]
An alternative design which might be simpler would be to only allow one decorator, and have it take in a `names: Sequence[str]` kwarg.

**Comment by OrangutanGaming** [comment]
I agree that it would be a quite nice QOL change, but it might give a wrong impression to some people like some people may try to have events with different numbers of arguments and expect it to work (like guild changes and ready)
