### ISSUE TITLE
discord.on_reaction_remove(reaction, user) has no way to determine who removed the reaction

### ISSUE THREAD

**Issue by Glenn1963** [Rapptz/discord.py#1932]
Since Issues 1803,1804,1806 and maybe others were resolved by updating the documentation, there appears to remain no way to determine who actually removed a reaction. 

It would be useful to have a third argument (remover?) to identify that user.

**Comment by Vexs** [comment]
Discord does not expose who removed a reaction in the `MESSAGE_REACTION_REMOVE` event, so discord.py cannot provide this information. It does provide the ID of the user whose reaction was removed, which discord exposes.
