### ISSUE TITLE
Emoji is unhashable

### ISSUE THREAD

**Issue by nguuuquaaa** [Rapptz/discord.py#1933]
Title. Even though Emoji is supposed to be inherited from `abc.Hashable`.
An eval `print(discord.Emoji.__hash__)` spits out `None` and `print(issubclass(discord.Emoji, discord.mixins.Hashable))` gives `True`.
This happens even before the cog update I think, and doesn't happen in commit b79a53c at least.

**Comment by Rapptz** [comment]
Thanks for the report.

If you're curious, this broke during #1815. When a type gets a `__eq__`, the language removes its `__hash__` so you have to define it (again).
