### ISSUE TITLE
What is the correct way to reconnect your Discord bot if your internet goes out.

### ISSUE THREAD

**Issue by EthanHicks1** [Rapptz/discord.py#1936]
I have done a lot of research and tried a lot of things but never gotten a solution that fully works. The code below I found online and added a print statement to: 

```
while True:
    try:
        client.loop.run_until_complete(client.start(TOKEN))
    except BaseException:
        print("client offline")
        time.sleep(5)
```

which does the following behavoir:

> Logged in as
PaladinsAssistant
537345817070141450
client offline
client offline
client offline
```
Task exception was never retrieved
future: <Task finished coro=<WebSocketCommonProtocol.run() done, defined at C:\Users\Ethan\Anaconda3\envs\Customs\lib\site-packages\websockets\protocol.py:428> exception=ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)>
Traceback (most recent call last):
  File "C:\Users\Ethan\Anaconda3\envs\Customs\lib\site-packages\websockets\protocol.py", line 434, in run
    msg = yield from self.read_message()
  File "C:\Users\Ethan\Anaconda3\envs\Customs\lib\site-packages\websockets\protocol.py", line 456, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "C:\Users\Ethan\Anaconda3\envs\Customs\lib\site-packages\websockets\protocol.py", line 511, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "C:\Users\Ethan\Anaconda3\envs\Customs\lib\site-packages\websockets\protocol.py", line 546, in read_frame
    self.reader.readexactly, is_masked, max_size=max_size)
  File "C:\Users\Ethan\Anaconda3\envs\Customs\lib\site-packages\websockets\framing.py", line 86, in read_frame
    data = yield from reader(2)
  File "C:\Users\Ethan\Anaconda3\envs\Customs\lib\asyncio\streams.py", line 674, in readexactly
    yield from self._wait_for_data('readexactly')
  File "C:\Users\Ethan\Anaconda3\envs\Customs\lib\asyncio\streams.py", line 464, in _wait_for_data
    yield from self._waiter
  File "C:\Users\Ethan\Anaconda3\envs\Customs\lib\asyncio\selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```
>Logged in as
PaladinsAssistant
537345817070141450
------

So it runs as expected until I unplug the internet and see that it prints that it is offline three times. Then I plug my internet back in and the client reconnects but throws the error seen above before it calls  
```on_ready():``` 
again.

I also tried some things with the function: 
```client.loop.run_until_complete(client.logout()) ``` which does close the client but then prevents it from ever restarting.

**Comment by Tarek1337** [comment]
Use rewrite. It handles all of this for you.

**Comment by EthanHicks1** [comment]
I have never heard of rewrite. What is that @Tarek1337? I already have a fully functional bot (700 ish lines) so I don't want to have to restructure my bot that much if possible.

**Comment by laggycomputer** [comment]
Ever noticed how stale the default branch is? Have you checked the others? Rewrite is another branch on this lib, and the only one currently developed.

GitHub issues are not for library help, they are for actual library *issues*. Please join the discord.py support server, as the README recommends.

**Comment by Vexs** [comment]
You've got it kinda close- you want to run `client.connect` in a loop, not client.start- client.start handles a bunch of stuff which.. won't react nicely to being done multiple times. You'd also want to implement a backoff so you're not spamming attempts.
I'm not sure exactly what is causing your code to react in the way it is- and excepting `BaseException` is obscuring a lot of that- and it's also generic bad practice.

If you want to implement this on the async branch (0.16.x), take a look at how the [rewrite branch implements it.](https://github.com/Rapptz/discord.py/blob/rewrite/discord/client.py#L399-L433)

Really though, you should just migrate to the rewrite branch, which has reconnection logic fully implemented, as well as a number of new features. It's also under active development, which the async branch is not. Rewrite is scheduled for full release within a month or so, and 700 lines won't be too hard to migrate now. See [the migration guide on the docs.](http://discordpy.readthedocs.io/en/rewrite/migrating.html) 

If you want more details, you should join the [discord.py server.](https://discord.gg/r3sSKJJ)

**Comment by EthanHicks1** [comment]
Thanks for the information/explanation and links @Vexs. I think I can go ahead and close this issue then and look into using the rewrite branch.

**Comment by FlashlightET** [comment]
> Use rewrite. It handles all of this for you.

im using rewrite and its still struggling to reconnect

**Comment by EthanHicks1** [comment]
@FlashlightET as long as your using the built-in `.run()` function in rewrite by default it should attempt to reconnect. If you haven't already, check out some examples on the GitHub: https://github.com/Rapptz/discord.py/tree/master/examples 

If your still having issues I would recommend joining the discord server which Vexs linked at the bottom of his message.
