### ISSUE TITLE
Checking if message.author.top_role is upper than user.top_role in the role list

### ISSUE THREAD

**Issue by KubasPlay** [Rapptz/discord.py#1941]
I want to create administrator commands but I don't know how to check if message author top role is upper than user top role or if they're on the same place. My code:

> elif message.content.upper().startswith((prefix)+'BAN'):
>         if message.author.server_permissions.ban_members:
>             for user in message.mentions:
>                 msg = ':warning: You are banned!'.format(message)
>                 await client.send_message(user, msg)
>                 await client.ban(user)
>                 msg = ':white_check_mark: Success! Banned '+(user.name)+'#'+(user.discriminator)+'!'.format(message)
>                 await client.send_message(message.channel, msg)

I want to check before ban if message author top role is upper than mentioned user top role or if they're on the same place on the list.

**Comment by CapnS** [comment]
For one I would recommend looking into the commands extension if you are making commands instead of using on_message. And two, you can compare roles using binary operators.

**Comment by TheRockettek** [comment]
you can use ctx.guild.me.top_role > role to see if it is higher on the role list :T

**Comment by Rapptz** [comment]
Roles can be compared with comparator operators (i.e. `<`, `>`, `>=`, `<=`, etc).
