### ISSUE TITLE
Having a issue on installing the rewrite....

### ISSUE THREAD

**Issue by awesomehd1** [Rapptz/discord.py#1945]
So when I was installing the rewrite using this:
`https://github.com/Rapptz/discord.py/archive/rewrite.zip`

and while I was installing there is a error about not incompatible with the discord.py rewrite:
`discord 0.16.12 has requirement discord.py==0.16.12, but you'll have discord-py
1.0.0a0 which is incompatible.`

**Comment by laggycomputer** [comment]
You should be installing rewrite with a clone of the git repo, not a zipped copy of the project files.

GitHub issues are not for library/installation help. For that, join either the Discord API server or the discord.py server, as the README recommends.

**Comment by awesomehd1** [comment]
oh
