### ISSUE TITLE
Support multi-base class cogs for organizational purposes.

### ISSUE THREAD

**Issue by Rapptz** [Rapptz/discord.py#1950]
I do not know how people write multi-inheritance cogs. I rarely see them in the wild but they are apparently useful for "organizational purposes". I assume most users have a different meaning of what this actually does. For the sake of argument I see one major proposal, which is to create a "super-cog" where the "children cogs" are not actually added to the bot:

```py
class ChildCog(commands.Cog):
    @commands.command()
    async def test(self, ctx):
        ...

class ChildCogTwo(commands.Cog):
    @commands.command()
    async def another_test(self, ctx):
        ...

class SuperCog(ChildCog, ChildCogTwo):
    @commands.command()
    async def super_cmd(self, ctx):
        ...
```

After this, `SuperCog` has `super_cmd`, `test`, and `another_test` as commands.

Unless there are other use-cases presented that I haven't caught, in which case let me know.

**Comment by trantinan2512** [comment]
Due to the new implementation of Cog (which is good!), all of my directory-based "cog" commands stopped working.

The directory was like this:
```cogs
|--- moderation
   |--- __init__.py
   |--- modcog1.py
   |--- modcog2.py
|--- cog1.py
|--- cog2.py
|--- ...
```
`modcog1.py` and `modcog2.py` "cogs" which are imported into the `__init__.py` to get loaded, didn't work. 
So I came up with the idea of subclassing the `commands.Cog` to override the `__new__` method it has, looking like this:
```py
class CogGroup(commands.Cog):

    def __new__(cls, *args, **kwargs):
        self = super().__new__(cls)

        # customized loop 
        for item in dir(self):
            # convert to attribute
            attr = getattr(self, item)
            # these codes are from the commands.CogMeta
            if isinstance(attr, _BaseCommand):
                cls.__cog_commands__.append(attr)
            elif inspect.iscoroutinefunction(attr):
                try:
                    is_listener = getattr(attr, '__cog_listener__')
                except AttributeError:
                    continue
                else:
                    for listener_name in attr.__cog_listener_names__:
                        cls.__cog_listeners__.append((listener_name, attr.__name__))

        # and these are from the __new__ method in commands.Cog
        cmd_attrs = cls.__cog_settings__

        # Either update the command with the cog provided defaults or copy it.
        self.__cog_commands__ = tuple(c._update_copy(cmd_attrs) for c in cls.__cog_commands__)

        lookup = {
            cmd.qualified_name: cmd
            for cmd in self.__cog_commands__
        }

        # Update the Command instances dynamically as well
        for command in self.__cog_commands__:
            setattr(self, command.callback.__name__, command)
            parent = command.parent
            if parent is not None:
                parent = lookup[parent.qualified_name]

                removed = parent.remove_command(command.name)
                parent.add_command(command)
        return self
```
The idea is to loop through all the available attributes using `dir()` and check if that attribute is a command or a listener, then add to the respective places. I bet you know this as those comments are from the `CogMeta` haha.

then the `__init__.py` file
```py
class ModerationCog(CogGroup, BanCog, MuteCog):
    pass


def setup(bot):
    bot.add_cog(ChallengeCommands(bot))
```
I've tested subclassing `CogGroup` at first and last, nothing affected.
`BanCog` and `MuteCog` can be a subclass of `commands.Cog` or not.

It looks kinda messed up, but I hope it gives you some ideas 🍡

**Comment by diceroll123** [comment]
I have multiple TextChannels that when moved into a category called "Events", to trigger functionality to set up the channels appropriately, such as creating roles and updating the channel description.

For the sake of the argument I'll just use one. The ID will be 1000 for simplicity's sake.

Without trying to metaclass for my hypothetical example (as this implementation will not work anyway), here's what I'm trying to do.

```python
class BaseEventCog(commands.Cog): # i'll need metaclassing or subclassing here, i know
    def __init__(self, bot, channel_id)
        self.bot = bot
        self.channel_id = channel_id

    def cog_check(self, ctx):
        return ctx.channel.id == self.channel_id

    @commands.Cog.listener()
    async def on_guild_channel_update(self, before, after):
        # it'll do some logic to make sure that the event was a channel moving in/out of the 'Events' Category
        # and it will tell the EventCog accordingly, and trigger a coro like "on_event_channel_added(channel)"

    async def on_event_channel_added(self, channel):
        raise NotImplementedError

    async def on_event_channel_removed(self, channel):
        raise NotImplementedError
```

As for the "real" cog + setup...

```python
class EventCogTeamChallenge(BaseEventCog): # i'll need more metaclassing or subclassing here, i know
    def __init__(self, bot):
        self.channel_id = 1000
        # i want BaseEventCog to use this channel ID

    async def on_event_channel_added(self, channel):
        # make roles, update the channel description

    async def on_event_channel_removed(self, channel):
        # remove roles etc

    @commands.command()
    #and so on...

def setup(bot):
    bot.add_cog(EventCogTeamChallenge(bot))
```

Notes:
- BaseEventCog will have no commands ever, and it purely for listeners/logic to be dispatched appropriately to parent cogs.
- Godspeed.

**Comment by mikeshardmind** [comment]
I also use composite cogs in a few places, so updating has been... problematic at best.

The below is something which works in some cases for people who want to stay up to date with the lib for now, but I can't say it is without issue.

<details><summary>code example</summary><p>

This is essentially dynamically creating a new class with a base class of commands.Cog, and the methods and attributes of the other classes. This isn't a great solution, but it is a working temporary one.

```py
# __init__.py
from . import BaseOne, BaseTwo

def setup(bot):
    attrs = dict()

    for base in (commands.Cog, BaseTwo, BaseOne):  # order here is important
        attrs.update(base.__dict__)

    def cog_init(self, bot, *args, **kwargs):
        # super needs some help to work with this
        super(self.__class__, self).__init__(*args, **kwargs)
        self.bot = bot

    attrs.update({"__init__": cog_init})

    CogName = type("CogName", (commands.Cog,), attrs)

    bot.add_cog(CogName(bot))
```
</p></details>

In my opinion, the best way to handle this longterm might be to modify the mechanisms in `Bot.add_cog` to call a function which would exist in the cog base class which assigns all of the attributes the base was created to handle. This would ensure the attribute creation happens at no time other than when the cog class is ready to be added to the bot.
