### ISSUE TITLE
How to exit an event

### ISSUE THREAD

**Issue by stevealexandre** [Rapptz/discord.py#1952]
Hello,

A simple question and sorry if it's seems simple to do ...
How can I exit a current event when meeting a condition ?

For example:
My bot should be use only in a channel of a server. So if a user PM the bot, he will answer to call it from a channel server.

I've tried this two method which doesn't working :
1-Put a else condition in the definition of "on_message"
> async def on_message(message):
>   if message.content.startswith('!config') and message.channel.is_private != True:
>     await client.send_message(message.channel, 'Configuration...')
>   else:
>     await client.send_message(message.channel, 'Error: You have to setup the bot on a discord server...')

2-Put a if condition in the definition of "on_message"
> @client.event
> async def on_message(message):
>   if message.channel.is_private:
>     await client.send_message(message.channel, 'Error: You have to setup the bot on a discord server...')
>   if message.content.startswith('!config'):
>     await client.send_message(message.channel, 'Configuration...')
>     await client.send_message(message.channel, message.channel.is_private)

In the both example, the bot loop when I'm PM with !config:
> Seffy Today at 17:06
> !config
> MatchMaking SystemBOT Today at 17:06
> Error: You have to setup the bot on a discord server...
> Error: You have to setup the bot on a discord server...
> Configuration...
> Error: You have to setup the bot on a discord server...
> True
> Error: You have to setup the bot on a discord server...
> Error: You have to setup the bot on a discord server...
> Error: You have to setup the bot on a discord server...
> Error: You have to setup the bot on a discord server...

Thank you for your help

**Comment by Phxntxm** [comment]
Events are just functions. Simply return

Also, github issues are more for issues in the library...for questions like this, you should join the discord server https://discord.gg/r3sSKJJ

**Comment by stevealexandre** [comment]
Yes I know it's a function but the bot loop because he's replying the message and understand this like a new message so reply again and again to himself.
I have tried to filter on author should not be the client himself but entering in a loop.

Will use the discord server in a future yep

**Comment by stevealexandre** [comment]
Switching to discord for help
