### ISSUE TITLE
Add support for path objects on cog loads

### ISSUE THREAD

**Issue by makusu2** [Rapptz/discord.py#1955]
Could we maybe add support for Path objects (pathlib) when loading/unloading cogs?
Currently you must specify the path of the cog module with dot notation.
Using a Pathobject raises `AttributeError: 'WindowsPath' object has no attribute 'startswith'` (Varies depending on OS)

`self.load_extension('project.reminders')` -> `self.load_extension(PROJECT_PATH / 'reminders.py')`

I'd love to work on this and submit a pull request, I just want to make sure there's no big issue with doing this before I start.

Edit: Rewrite

**Comment by Gorialis** [comment]
This sounds like this will probably bring up several problems. Not that I'm against it being possible if reasonably implementable, though.

There are a couple of things to note here:
- `load_extension` does **not** accept a path. It accepts a module name, something you can do `import <x>` to.
- `Path` objects can point anywhere on the system, including ones that may be in completely separate trees to where your interpreter or project is running.
- `Path` (and just paths in general) have varying behaviors depending on the platform that is being run on.
- Modules themselves have ambiguous locations: `foo.bar` could point to `./foo/bar.py`, `./foo/bar/__init__.py`, the equivalents in `$PYTHONHOME` or `$PYTHONPATH`, could be in `site-packages`, etc.

Consider, for example, on Windows, this directory structure:
```

**Comment by makusu2** [comment]
Importlib has a similar function, one that can import based on a Path. I'll look into it; thanks for the additional info!
https://docs.python.org/3/library/importlib.html

**Comment by makusu2** [comment]
It's possible to import a module with a path, I've tested it and the bot loads the cog just fine.
However, the issue is getting the name of the module. 

.
├── mybot.py
|   
└── mycog.py
If 'mycog.py' is in the same directory as 'mybot.py', importing with dot notation will name the module 'mycog' and importing with a path will name the module 'mycog'. That's what we want.

.
├── cogs
|   └── mycog.py
└── mybot.py
If 'mycog.py' is in a 'cogs' folder, importing with dot notation will name the module 'cogs.mycog' and importing with a path will name the module 'mycog'. That's a major issue when dealing with the bot's extensions, at least when the user is sometimes using a path and sometimes using dot notation.

.
├── bot
|   └── mybot.py
└── mycog.py
If 'mycog.py' is in a parent folder, importing with dot notation is not possible with the load_cog method (as far as I can tell). This is true even if the bot is in a package, since it requires that load_cog's call to importlib.importmodule takes a 'package' argument, which is not supported in load_cog. Loading with a path object will actually allow this (the module will be named 'mycog'). 

Solutions:
1. For path arguments, only allow cogs on the same level as the bot
    No, far too restrictive.
2. Allow cogs on the same level as the bot and in subdirectories. Change bot.extensions keys to only include the stem of the module ('cogs.mycog' -> 'mycog')
    Absolutely not. It would require the user to change their calls to bot.extensions.
3. Allow cogs on the same level as the bot and in subdirectories. Attempt to turn the path into a dot-sourced string.
    Maybe. I imagine there would be a few ways to screw things up, like the fourth point @Gorialis brought up. That specific example wouldn't be an issue, since that is only a problem with translating a dot-sourced string to a path and this is the other way around, but there will likely be a few similar issues.

Solution 3 would be the best. It would also allow importing parent-level cogs in the future with path objects. 


Additional thoughts: 
*If someone changed their path and managed to load 'cogs.mycog' and later load 'project.cogs.mycog' (same location), the current load_cog would allow both cogs to be loaded, as it checks against the name of the module ('cogs.mycog' vs 'project.cogs.mycog') rather than the location.

**Comment by Vexs** [comment]
One issue I have with this is I'm not really sure when this would be useful, short of obscure designs where you have cogs placed in odd locations. As far as I can tell, solution 3 looses all these dubiously useful benefits, and gains nothing aside from being able to define cogs differently.

**Comment by makusu2** [comment]
I'd wanted to change it because when reorganizing my bot into folders, because for all the other references to files, I could use a Path object. Once I figured out what the issue was, I changed it all, it just wan't clear to me at first why the import was failing.

So, another solution could just be testing for a Path argument and raising an ImportError, along with a 'you must dot-source' message.

**Comment by Rapptz** [comment]
The documentation is kind of clear in this (I hope) that it only accepts dot qualified notation.

A couple of things that I want to mention however:

1) The `importlib` facility that accept a `Path` object and is relevant to this is only `importlib.util.spec_from_file_location`. This function however accepts both a module name and its path. If you have the module name, then you should just use that anyway. There is no facility, as far as I'm concerned, for a sole `Path` to be converted into a magical dot-qualified name.
2) Due to the nature of modules, I don't imagine that to be a thing anyway. Something like `import foo` depends on more than just a file system location due to how the import machinery works. It could be in `site-packages`, it could be in your local directory as a `foo.py` file, it could be a folder with an `__init__.py` such as `foo/__init__.py`. The current behaviour just propagates from the import machinery without many gotchas. It can also handle cases where someone `pip install`'s an extension. I do not feel exactly comfortable with having to pick a potentially erroneous choice when faced with ambiguity and would rather the import error be propagated.

**Comment by makusu2** [comment]
@Rapptz To point 1, that was the issue I mentioned above; you're allowed to use `importlib.util.spec_from_file_location` with whatever name you want, it will just cause issues when comparing it to another module whenever you use bot.extensions. If you enforce that the cog be in the same directory or a subdirectory, it wouldn't be too difficult to get the dot-qualified name from the cog path and the script path. 
To point 2, all of those issues are if you're attempting to translate dot-qualified to a normal path. This would be the other way around, so none of those issues should be a problem.

You're right that the exception shouldn't be reraised, but couldn't we at least append a message to the AttributeError's message attribute?

The documentation is fine, ~~you're aware I basically idolize your code and documentation~~, but I feel like having some sort of message  indicating the issue would make it easier on a new user who's just getting to know the library.
Something like `__import__`'s message: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __import__() argument 1 must be str, not OSPath
```
All it has to do is describe the issue. If it said something like this, it'd be perfect:

```
Traceback (most recent call last):
  File "C:\redacted\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\redacted\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\redacted\project\__main__.py", line 43, in <module>
    DemoBot().run(token)
  File "C:\redacted\project\demobot.py", line 31, in __init__
    self.load_extension(Path())
  File "C:\redacted\lib\site-packages\discord\ext\commands\bot.py", line 612, in load_extension
    lib = importlib.import_module(name)
  File "C:\redacted\lib\importlib\__init__.py", line 118, in import_module
    if name.startswith('.'):
AttributeError: 'WindowsPath' object has no attribute 'startswith'
load_extension must be passed a dot-sourced string, not OSPath
```

Alternatively, if `isinstance(name, Path)` passes, we could just throw a warning so that it would show before the exception.

What do you think of that? Or maybe it'd just unnecessarily clutter the code?

**Comment by makusu2** [comment]
Also, and this might be a much better idea: I'd like to add Path support for attachment.save. 
Currently you get `AttributeError: 'WindowsPath' object has no attribute 'write'`

**Comment by Gorialis** [comment]
Issues should encapsulate one concept (question, problem, etc). If you want to suggest a different change, please do so in its own issue, as it makes it easier to catalogue, find and reference issues later.
