### ISSUE TITLE
get_guild(id) error

### ISSUE THREAD

**Issue by 258rkd** [Rapptz/discord.py#1956]
Currently using a tutorial to learn how to make a bot and I'm at a part where I'm trying to get a member count to print to the screen. 

![screen shot 2019-03-05 at 5 23 21 pm](https://user-images.githubusercontent.com/26587033/53849072-86600100-3f6b-11e9-84a8-4d33a8be034b.png)

However it's repeatedly giving out the error 

![screen shot 2019-03-05 at 5 23 37 pm](https://user-images.githubusercontent.com/26587033/53849104-9f68b200-3f6b-11e9-8793-28059c42f8db.png)

And i cant seem to find any help for this error anywhere. The code is directly off tutorial other than the id and the string im looking for. Any ideas on what im missing?

**Comment by palmtree5** [comment]
are you sure you're using the rewrite?

**Comment by 258rkd** [comment]
Im fairly confident I am, async works for other functions this and the current one does the first print. The only issue it's giving me is with the get_guild() function

**Comment by Phxntxm** [comment]
First off, you're not using rewrite....based on the traceback that you provided, that is async code. Second, for things like this you should really join the discord server, github issues are more for issues with the library. https://discord.gg/r3sSKJJ

Also as a note you probably shouldn't override builtins (id is a builtin method, you should call your variable something different)

**Comment by 258rkd** [comment]
Thanks, will do.

**Comment by laggycomputer** [comment]
Quite a few warnings.

First, It's not recommended to use tutorials, given the impending release of rewrite.
Second, it's a bad idea to hardcode guild objects like this.
Third, don't use on_message for commands, use the commands extension,
