### ISSUE TITLE
Why can't I edit messages?

### ISSUE THREAD

**Issue by 12944qwerty** [Rapptz/discord.py#1960]
I used the commands edit function (ctx.edit(content='NEWCONTENT')) but it says that CTX has no attribute of edit. How do I edit otherwise?

**Comment by laggycomputer** [comment]
`.edit` is not a function of `ctx`, see the docs for available ways to obtain a message object.
GH issues are for library issues, not help. For that, please join the discord.py support server, see the README.

**Comment by 12944qwerty** [comment]
Yes, I have seen that before, but I want to use the commands function. It's easier for everything. So I don't know how to edit a message using `@client.**commands**(). `. It's not working from what I got off of on the docs.

**Comment by scragly** [comment]
`ctx` has a message object available as an attribute, which is shown in the docs previously mentioned:
https://discordpy.readthedocs.io/en/rewrite/ext/commands/api.html#discord.ext.commands.Context.message

Again, library github issues isn't for code help, please close this ticket and seek assistance in a more appropriate place such as the discord.py support server, also previously mentioned.

**Comment by 12944qwerty** [comment]
Where is the discord.py support server?

**Comment by numbermaniac** [comment]
https://discord.gg/r3sSKJJ

**Comment by 12944qwerty** [comment]
that invite is not working

**Comment by laggycomputer** [comment]
That's an issue with your internet, not a concern of ours, but try restarting your router and your computer.

**Comment by numbermaniac** [comment]
That's the official invite link to the discord.py server. Based on the screenshot it looks like it's trying to open the Discord program on your computer but failing for some reason.

Have you tried opening the Discord program on your computer, hitting the plus button at the bottom of the server list and copying that invite URL in?
