### ISSUE TITLE
Unclosed client session error

### ISSUE THREAD

**Issue by fogleins** [Rapptz/discord.py#1961]
Hi everyone,

every time I'm running a bot and a torrent client at the same time, I get the error "Unclosed client session". I've read quite a lot posts with possible fixes for this issue, but none of them seem to work for me. At first I thought this might be an issue with Deluge, but I've tried Transmission too, and the bot's terminal returns the same error. The bot usually starts up normally, but after some time it prints this error and/or goes offline (longest uptime I could get was around 15 hours). I wonder if there's a solution for this issue. I'm running the bot on my Raspberry Pi with Python 3.6.8.
[This ](https://www.reddit.com/r/linuxquestions/comments/axd9my/getting_these_errors_when_trying_to_run_a_python/)is the full error message and here's a screenshot of it: 
![image](https://user-images.githubusercontent.com/44982432/53969106-7295d580-40f8-11e9-8ecb-a3689977a45a.png)

So is there a way to fix this issue or is it impossible to run the two processes simultaniously?

**Comment by lejakewolf** [comment]
Could be possibly anything that I really can't answer without knowing what code you have. GitHub issues are also generally for issues within the lib itself. You should join the discord.py server for further help. Questions will also be answered quicker there.
Link: https://discord.gg/r3sSKJJ

**Comment by fogleins** [comment]
I've already asked around on the discord.py server as well as on reddit, but I haven't succeded, that's why I've posted here too

**Comment by lejakewolf** [comment]
Well, posting here won't get you anywhere either. People mostly tend not to respond to issues like this even.

**Comment by Rapptz** [comment]
1) The unclosed client session is ultimately irrelevant. This is just something that happens due to lack of cleanup. The actual error is the `OSError`.
2) Connect call failed is pretty self explanatory. The attempted connection to that IP (which is Discord) failed. Internet issue more than likely.

There isn't much I can do here since this is outside of scope of the library.
