### ISSUE TITLE
Testing with py.test

### ISSUE THREAD

**Issue by klvbdmh** [Rapptz/discord.py#197]
I adapted the addition function from examples folder into a class so I could move command functionality into a separate module. It's in `cogs/addition.py`:

    from discord.ext import commands

    class Math:
        def __init__(self, bot):
            self.bot = bot

        @commands.command()
        async def add(self, left: int, right: int):
            """Adds two numbers together."""
            await self.bot.say(left + right)

    def setup(bot):
        bot.add_cog(Math(bot))

How would I go about testing the `add` function? I tried the following code:

    from cogs import addition
    from discord.ext import commands

    bot = commands.Bot(command_prefix='.', description='None')

    def test_coin_flip():
        cl = addition.Math(bot)
        assert cl.add(5, 4) == 9

but once I run it I get `TypeError`:

    ============================= test session starts =============================
    platform win32 -- Python 3.5.1, pytest-2.8.1, py-1.4.30, pluggy-0.3.1
    rootdir: D:\Dev\discord-cloudbot\tests, inifile: 
    collected 1 items

    D:\Dev\discord-cloudbot\tests\test_cogs.py F
    def test_coin_flip():
            cl = addition.Math(bot)
    >       assert cl.add(5, 4) == 9
    E       TypeError: 'Command' object is not callable

**Comment by SunDwarf** [comment]
I'd be impressed if you could unit test a bot that requires an external service as input.

**Comment by khazhyk** [comment]
To get the wrapped function from a Command object you use Command.callback

**Comment by klvbdmh** [comment]
> You'd be better off separating your logic and testing that unit separately, rather than testing commands directly.

Yeah, that's probably what I need. A momentary lapse of judgement from my part.

**Comment by JacobCover** [comment]
Not related to this, but someone on the discord just brought this to my attention, might work as a solution for now. I'm going to check it out.
https://github.com/DXsmiley/dismock

**Comment by ldeluigi** [comment]
> I'd be impressed if you could unit test a bot that requires an external service as input.

boy do I have [news ](https://pypi.org/project/dpytest/) for you
