### ISSUE TITLE
[Improvement] Message routing based on a template

### ISSUE THREAD

**Issue by t94j0** [Rapptz/discord.py#1970]
The `on_message` function can sometimes be too long, so it would be great if there was a decorator that could route messages based on some sort of template.

Here is an example implementation of a decorator that could accomplish message routing through decorators: https://github.com/t94j0/discord-router

**Comment by Rapptz** [comment]
There is already a command extension. https://discordpy.readthedocs.io/en/rewrite/ext/commands/commands.html

I do not know what the so called router would accomplish over that.
