### ISSUE TITLE
Make sending help messages inside of commands more convenient

### ISSUE THREAD

**Issue by OrangutanGaming** [Rapptz/discord.py#1983]
### The Problem

Sending help for a command using the built-in HelpCommand is really inconvenient. Before the changes you had to do something like `(await bot.formatter.format_help_for(ctx, ctx.command))[0]` and with the changes it seems like a good oportunity to make this more convenient, but instead it's worse:
```python
help_command = bot.help_command
help_command.context = ctx
await help_command.prepare_help_command(ctx, ctx.command)
await help_command.send_command_help(ctx.command)
```

### The Ideal Solution

Having a single method to call that can send the help messages or have a method that returns a list of the messages it is planning on sending so we can manually send the messages.

**Comment by Rapptz** [comment]
I don't understand why you wouldn't just do `await ctx.invoke('help', command=ctx.command.qualified_name)`.

**Comment by OrangutanGaming** [comment]
If you do do that, you aren't able to get the help as text/embed and I know it's called `HelpCommand` but being able to use it outside of just using the help command may be useful in some places. For example, if you have a command group and you only have subcommands, you might want to send the usage if just the base group command is used,  and might want to use a different location than normal. I understand it's a bit of a weird case but being able to give more control to the bot creator is usually helpful

**Comment by Rapptz** [comment]
There's now a helper for this.

`await ctx.show_help(ctx.command)` will do the trick. [Relevant documentation](https://discordpy.readthedocs.io/en/rewrite/ext/commands/api.html#discord.ext.commands.Context.show_help)
