### ISSUE TITLE
Installing on Pythonista

### ISSUE THREAD

**Issue by Jerry12798** [Rapptz/discord.py#1984]
I’m on iOS 12.0.1 and using Python 3.6 with Pythonista 3.3. So I managed to do ```pip install discord.py``` and successfully install it. However I can’t manage to get this one installed. I currently have 0.16 without voice support.. the script won’t with the voice support version

**Comment by CapnS** [comment]
From what I have learned using Pythonista, it is not possible to install voice support. It also couldn't support voice support even if it could download it as it does not include the needed tools to use voice.

**Comment by Jerry12798** [comment]
Ok I see.. so actually I think I need ```ctypes.macholib```. I thought it was due to not having the voice support. I can’t seem to pip install that however

**Comment by gogurtenjoyer** [comment]
I had this issue on Pythonista and I BELIEVE that this is what I did to fix it: https://github.com/omz/Pythonista-Issues/issues/311

**Comment by Jerry12798** [comment]
So how do I use that to fix it? I’m fairly new and don’t see a script to update or add it

**Comment by gogurtenjoyer** [comment]
I meant specifically this comment: https://github.com/omz/Pythonista-Issues/issues/311#issuecomment-398715503

**Comment by Jerry12798** [comment]
Ok fixed it now just getting the 1.0 discord.py

**Comment by Harmon758** [comment]
In the future, please make sure you're using the latest development version when reporting issues.
Also, for future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.

**Comment by torpedojason** [comment]
How can i get discord.py on pythonista

**Comment by gogurtenjoyer** [comment]
Read the above comments from myself.
