### ISSUE TITLE
Documentation Consistency / Clarification

### ISSUE THREAD

**Issue by NCPlayz** [Rapptz/discord.py#1988]
I mainly wanted to make this issue to help out with `ext.commands` documentation, and there's a few issues with the documentation I wanted clarification with. 
I have already been told that you should have a new line after the docstring due to lib style, as well as having raw strings if the docstring contains commas.
```py
r"""|coro|

This does something useless, but it doesn't have to be!
"""
```
But when I was scanning the docs, I realised there was a difference in the order of information.

[`Client.get_invite`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Client.get_invite) has an order of [Description, Parameters, Raises, Returns, Return Type], whereas [`Client.get_user_info`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Client.get_user_info) has an order of [Description, Parameters, Returns, Return Type, Raises].

I managed to compile a list assuming that the order is not `[Parameters, Raises, Yields/Returns + Return Type]`:
- `Client.application_info()` [Returns, Return Type, Raises]
- `Client.get_user_info()` [Parameters, Returns, Return Type, Raises]
- `Webhook.avatar_url_as()` [Parameters, Returns, Return Type, Raises]
- `Messageable.get_message()` [Parameters, Returns, Return Type, Raises]
- `ClientUser.avatar_url_as()` [Parameters, Returns, Return Type, Raises]
- `ClientUser.create_group()` [Parameters, Returns, Return Type, Raises]
- `User.avatar_url_as()` [Parameters, Returns, Return Type, Raises]
- `User.mutual_friends()` [Returns, Return Type, Raises]
- `Guild.icon_url_as()` [Parameters, Returns, Return Type, Raises]
- `Guild.banner_url_as()` [Parameters, Returns, Return Type, Raises]
- `Guild.splash_url_as()` [Parameters, Returns, Return Type, Raises]
- `Guild.create_custom_emoji()` [Parameters, Returns, Return Type, Raises]
- `Guild.create_role()` [Parameters, Returns, Return Type, Raises]
- `Guild.vanity_invite()` [Returns, Return Type, Raises]
- `Member.avatar_url_as()` [Parameters, Returns, Return Type, Raises]
- `Member.get_message()` [Parameters, Returns, Return Type, Raises]
- `Member.mutual_friends()` [Returns, Return Type, Raises]
- `TextChannel.get_message()` [Parameters, Returns, Return Type, Raises]
- `DMChannel.get_message()` [Parameters, Returns, Return Type, Raises]
- `GroupChannel.get_message()` [Parameters, Returns, Return Type, Raises]

1. What is the order that the information should be in?
2. When referring to builtins do we do [``:class:`int` ``](https://github.com/Rapptz/discord.py/blob/rewrite/discord/invite.py#L112) or just [`int`](https://github.com/Rapptz/discord.py/blob/rewrite/discord/iterators.py#L190)?
3. When referring to objects with IDs do we do [``:class:`Message` or id-like``](https://github.com/Rapptz/discord.py/blob/rewrite/discord/iterators.py#L194) or [``:class:`abc.Snowflake` ``](https://github.com/Rapptz/discord.py/blob/616616b8470267c8c417c5c3e198623f43932e28/discord/reaction.py#L109)?
4. When is it appropriate to add [`Note`](https://github.com/Rapptz/discord.py/blob/616616b8470267c8c417c5c3e198623f43932e28/discord/opus.py#L135) to the docstring?

I feel like there should be some form of documentation template, so that we can help document things that seem to be sparsely documented.

**Comment by Rapptz** [comment]
1. The `r` is not for commas, it is for backslashes inside the string.
2. The order should be `[Parameters, Raises, Yields/Returns, ReturnType]`
3. Built-ins should link back. There was an interim period before and after intersphinx was added so it's not consistent because of it.
3. Objects with IDs should always be Snowflake.
4. `Note` and `Warning` headers are legacy, use `.. note` and `.. warning` instead.
