### ISSUE TITLE
Emoji.save, to mimic Attachment.save

### ISSUE THREAD

**Issue by diceroll123** [Rapptz/discord.py#1997]
### The Problem

I believe Emoji.save should be a thing.

### The Ideal Solution

Emoji.save, a la Attachment.save. Like, exactly the same, just abstracted away from being HTTPClient.get_attachment. I wouldn't make a PR which changes/removes public methods, so I'm making this issue.

### The Current Solution

```python
fp = BytesIO()
async with session.get(emoji.url) as resp:
    fp.write(await resp.read())
# now do stuff with the emoji data
```

### Summary

I want to save emojis to a file, and/or bytesIO etc in a clean, lib-provided way.

Use cases include backing up emojis, fun emoji commands like deepfrying them or whatever... 

---

In the d.py server, it was also brought up by others to be able to do this for other things such as avatars, https://discordapp.com/channels/336642139381301249/336642776609456130/557351275247829012

**Comment by Vexs** [comment]
Fug u linkin' my half-thoughts.

But yeah, cdn-related stuff happens all over the lib and it's re-implemented at each usage in the lib- ie, emoji.url, guild.icon_url, member.avatar_url, etc. It seems sensible to me to implement some "cdn asset" base class/mixin because of this.

**Comment by shtabbbe** [comment]
Is this something we need, should I work on this?
