### ISSUE TITLE
Allow for cooldown predicates and rollbacks.

### ISSUE THREAD

**Issue by EvieePy** [Rapptz/discord.py#1999]
### The Problem

Currently, cooldowns lack flexibility in how they are processed. With no support for custom processing checks or state rollbacks.

### The Ideal Solution
**1.)** - Allow the cooldown to take in a predicate callable, which takes in a  sole parameter of `ctx`, which either returns a truth or false value. The predicate will be checked before the bucket is updated, allowing consumers to determine logically whether or not a cooldown bucket should be updated. 

Take for example a Whitelist example:
```py
async def my_cooldown_check(ctx):
    if ctx.author.id in [whitelistsed_users, ...]:
        return False
    return True

@commands.command(...)
@commands.cooldown(1, 60, commands.BucketType.user, predicate=my_cooldown_check)
async def my_command(...):
    ...
```
Here we return False if the author is in the whitelist, indicating that the cooldown should `not` be updated. True otherwise, indicating that the cooldown should be updated.

**2.)** - I haven't put too much thought into this one, but as it was brought up recently I'd thought I'd share a quick idea here. Currently there is no clean way of rolling back the cooldown by a single token in the case of a command failing during invocation, but after checks. 

My first thought was to add an optional kwarg, something along the lines of `update_on_failure=True/False`. I'm not sure what this means internally, I am yet to determine an appropriate solution to this, if one exists. My second thought was to expose a method on the cooldown which would allow the user to easily rollback a token. This would still need to be done in error handlers, but it would be much less ambiguous.

 
### The Current Solution

**1.)** - Currently the only way of achieving this sort of behaviour is to map the cooldown to a check.

**2.)** - Currently the only way of achieving this is by doing some messy workaround in error handlers.

### Summary

Allow flexibility in cooldowns by allowing optional predicates, and a way to clearly rollback the cooldown in case of a command failure.

Even though we briefly discussed on discord, I decided it was best to open this up and get feedback, ideas before actually making any sort of PR.

**Comment by Rapptz** [comment]
Implemented by #6691 

The question so asynchronicity is still up in the air but returning `None` for the cooldown is effectively a bypass.
