### ISSUE TITLE
Support gateway redirects

### ISSUE THREAD

**Issue by Rapptz** [Rapptz/discord.py#2]
Something to add to my todo list for a later date.

Stan says:

> Just so you guys know probably within a week there will be a major real-time system change to Discord.
the /gateway call will need the auth token because gateways will be assigned around a consistent hash ring
If you conncet to the wrong gateway it will send you a redirect opcode with the URL to the correct one
But the easiest way to be ready for this is to just send the auth token to /api/gateway and then you dont need to worry about it
But the redirect opcode can be also fired if the servers rebalance
but doubt that will be happening for a bit after the upgrade
its special cause gateways support resuming a session id
instead of identify you send a resume
with the previous session id
and it keeps going on the new node
This way we can seamless move people between gateways during DDoS or just scale up 😃
also works for timeouts (aka cloudflare issue)
opcode is 7
and the data is just
{"url": "new websocket url here"}
If you want to support resuming a session you need to keep the session_id in your websocket instance.. and also keep track of the 's'  variable aka seq on events (keep last one)
and when you try reconnect after a DC or a redirect
send opcode 6 with {'session_id': session_id, 'seq': seq}
instead of identify
every message will have a seq
's'
keep the last one

**Comment by Rapptz** [comment]
Afterwards you could get either `READY` or `RESUMED`.

Of which `RESUMED` has:

`{"t": "RESUMED", "d": {"heartbeat_interval": N}}`

**Comment by Rapptz** [comment]
If the websocket is closed with error code 1012 then you have been forced to reconnect with the same gateway.

>ReactToday at 3:15 PM
u just reconnect
to the same URL
DannyToday at 3:15 PM
or do you mean opcode 7 w/ new URL + close 1012
oh I see
ReactToday at 3:15 PM
no so what will happen
is your WS
will terminate
w/ 1012
then you will reconnect to the gateway again
DannyToday at 3:15 PM
close 1012 meaning restart completely
gotcha
ReactToday at 3:15 PM
the gateway will either
redirect u
resume u
or give u a new READY packet
meaning u could not be resumed
if u are redirected
try to RESUME on the new server
as your session may have been transferred to it

**Comment by AraHaan** [comment]
as far as I see the current gateway is ``wss://gateway-arthas.discord.gg/``

**Comment by Jamm111** [comment]
first issue ?
