### ISSUE TITLE
AttributeError: module 'discord.ext.commands' has no attribute 'Cog'

### ISSUE THREAD

**Issue by Arthurdw** [Rapptz/discord.py#2007]
### Summary

When trying to add a 'COG' I got an error.

### Reproduction Steps

This is a short representation of my code that is relevant.

>Run file:
>```python
>import discord
>from discord.ext import commands
>
>class bot(commands.Bot):
>    def __init__(self):
>        super().__init__(command_prefix ='!',
>                        description='desc',
>                        help_attrs=dict(hidden=True))
>        self.token = "XXXMYTOKENXXX"
>
>        for extension in EXTENSIONS:
>            try:
>                self.load_extension(extension)
>            except Exception as e:
>                print('An error occurred while trying to load the "{}" extension.\n{}: {}'.format(extension, type(e).__name__, e))
>        
>    async def on_ready(self):
>        print('Logged in as:')
>        print('Username: ' + self.user.name)
>
>    async def on_message(self, message):
>        if message.author.bot:
>            return
>        await self.process_commands(message)
>
>    def run(self):
>        super().run(self.token, reconnect=True)
>
>if __name__ == '__main__':
>    runbot = bot()
>    runbot.run()
>```

>Main (COG) file: 
>```python
>import discord
>from discord.ext import commands
>
>class main(commands.Cog):
>    def __init__(self, bot):
>        self.bot = bot
>
>    async def on_ready(self):
>         print("Loaded the 'Main' extention!")
>
>def setup(bot):
>    m = main(bot)
>    bot.add_cog(m)
>```

### Expected Results

The cog should load, and be fully functional.

### Actual Results

An error got produced.
Error:
>`An error occurred while trying to load the "Extensions.main" extension.
>AttributeError: module 'discord.ext.commands' has no attribute 'Cog'`

### Checklist

>- [x] I have searched the open issues for duplicates.
>- [x] I have shown the entire traceback, if possible.
>- [x] I have removed my token from display, if visible.

### System Information

- discord.py version: 1.0.0a1634+g7f4c57d
- Python version: Python 3.7.2
- Operating system: Windows 10 (version 1803)

**Comment by numbermaniac** [comment]
> 1.0.0a1634+g7f4c57d

Your discord.py is out of date, try re-running the rewrite installation command to update to the latest version.

**Comment by Rapptz** [comment]
You are out of date.

You have 1.0.0a1634+g7f4c57d but the latest version is 1.0.0a1773+c30a366.

**Comment by bora399** [comment]
Hey, do you find any solution? I have the same issue.

**Comment by lgaan** [comment]
You shouldn't necrobump old issues, instead join the official discord server (as the README suggests) to get further support.
