### ISSUE TITLE
WebhookUser model

### ISSUE THREAD

**Issue by apple502j** [Rapptz/discord.py#2009]
### The Problem
Messages sent with webhooks have author User instance. However, there are three problems:
1. the developers might get confused if message on guild does not have Member as author
2. most of the operations of User won't work
3. no guild attr

### The Ideal Solution
WebhookUser. this class has some attrs:

- id - Webhook ID
- guild - the guild of the webhook
- channel - the channel of the webhook
- name - the name of the webhook
- avatar, avatar_url, avatar_url_as, created_at: same as User

NOTE: this is not same as Webhook because token is unknown.

### The Current Solution
User model

### Summary
A new class to represent the author of a message sent with webhook

**Comment by Rapptz** [comment]
The API does not use a different model for webhooks but it does separate them with a distinct discriminator of 0000. If a user wants to filter webhooks then they should check the discriminator.
