### ISSUE TITLE
Checking if message has no mentions

### ISSUE THREAD

**Issue by klvbdmh** [Rapptz/discord.py#201]
I'm writing a simple greeting command that takes a member mention as an imput.

    from discord.ext import commands

    bot = commands.Bot(command_prefix='.', description=description)

    @bot.command()
    async def greet(user: discord.User):
        await bot.say('Hello {}!'.format(user.mention))

Upon writing `.greet @user` in the chat it correctly greets a mentioned user.

I want to extend the functionality so that when someone writes `.greet` without any mentions it will send a generic response.

    @bot.command(pass_context=True)
    async def greet(ctx, user: discord.User):
        if not ctx.message.mentions:
            await bot.say('Hello everyone!')
        await bot.say('Hello {}!'.format(user.mention))

But once `.greet` is written, nothing happens. Same thing when I replace `if not` with `if len(ctx.message.mentions) == 0` or `if not user`

If I remove `not`:

    @bot.command(pass_context=True)
    async def greet(ctx, user: discord.User):
        if ctx.message.mentions:
            await bot.say('Hello everyone!')
        await bot.say('Hello {}!'.format(user.mention))

and write `.hello @user`, both messages are sent as expected.

How can I check for lack of mentions in the passed command?

**Comment by khazhyk** [comment]
The command will not fire if required arguments are not passed. What's happening is probably that you're using just `.greet`, which is missing the required `user` parameter, and fails. You can make the user parameter optional by giving it a default value of `None`, then in your logic you can just do `if not user`

**Comment by klvbdmh** [comment]
Excellent, this fixed the issue. Thanks.
