### ISSUE TITLE
SIGINT handling on Windows

### ISSUE THREAD

**Issue by mdiller** [Rapptz/discord.py#2011]
### The Problem

Windows does not seem to support doing `loop.add_signal_handler(signal.SIGINT, self._do_cleanup)` to handle SIGINT commands. 

### The Current Solution (and the issue with it)

Currently, we're just relying on catching the KeyboardInterrupt exception that gets thrown. ([line ~500 in client.py](https://github.com/Rapptz/discord.py/blob/d48a424f6f464044a59275d5e885b493a4a1aef7/discord/client.py#L551-L554))

This 'works,' but most of the time it does not react instantly, and I've observed it taking anywhere from 3 seconds to 30 seconds for the exception to be caught and the bot to close. This seems to be due to an issue with asyncio where the SIGINT gets blocked until something updates. I found [this issue](https://github.com/python/asyncio/issues/191) that describes the problem and says it was fixed in a later release of asyncio but it is still happening on my system, and for someone else in that thread.

### A Workaround

I've found [a workaround](https://stackoverflow.com/questions/24774980/why-cant-i-catch-sigint-when-asyncio-event-loop-is-running/24775107#24775107) that works for now. Adding the following lines to the run function in client.py solves the issue and the SIGINT is caught instantly.
```py
        def wakeup():
            loop.call_later(0.1, wakeup)

        try:
            loop.call_later(0.1, wakeup)
            loop.run_forever()
        except KeyboardInterrupt:
```
Is this an acceptable workaround to put in the main code or is it too hacky of a solution? If it sounds fine, I'll create a pull request to add it. Could also make it only run if it is on a windows machine.

### System Info

- discord.py version: 1.0.0a1781+gd48a424
- Python version: 3.6.5
- Operating system: Windows 10

**Comment by Andrej730** [comment]
I'm encountering the same problem and my current solution is to add to client.py the following line:

```python
signal.signal(signal.SIGINT, lambda: bot.loop.stop())
```

**Comment by Rapptz** [comment]
I feel like this should be fixed upstream via Python by now (and if not, then it should be handled by asyncio upstream) so I'm closing this for now.

**Comment by sbourdeauducq** [comment]
You can fix it like this: https://github.com/m-labs/sipyco/commit/930ca5fc9c0ca79f31d538393c6238685ba53883
