### ISSUE TITLE
Easier way of getting overridden methods in Cogs.

### ISSUE THREAD

**Issue by XuaTheGrate** [Rapptz/discord.py#2013]
### The Problem

I'd like to be able to have a better way to find out of a function in a cog has been overridden or not.

### The Ideal Solution

Probably something is `Cog.is_method_overridden("cog_command_error")` which returns a `bool` if it has or not.

### The Current Solution

Currently I can achieve this via `Cog._get_overridden_method(<my_cog>.cog_command_error) is not None`

### Summary

My main use case for this would be for my error handler, I don't want it running if there is a cog handler that exists already.
```py
    @commands.Cog.listener()
    async def on_command_error(self, ctx, exc):
        if ctx.cog is not None and ctx.cog._get_overridden_method(ctx.cog.cog_command_error) is not None:
            return
        # handler stuff here
```

**Comment by Rapptz** [comment]
There is now `Cog.has_error_handler` in 1.7 which solves this particular issue. I doubt any other overridden methods are of value.
