### ISSUE TITLE
AttributeError: 'Client' object has no attribute 'say'

### ISSUE THREAD

**Issue by logi6000** [Rapptz/discord.py#2021]
### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- discord.py version:
- Python version:
- Operating system:

**Comment by logi6000** [comment]
the latest version of discord.py
Python 3.5 I think
Linux Mint 19

import discord
from discord.ext import commands

client = commands.Bot(command_prefix = '!')



@client.event
async def on_ready():
	activity = discord.Game(name="Half Life 3")
	await client.change_presence(status=discord.Status.online, activity=activity)
	await client.say("test")
	print(f"Bot is ready")
	print(f"Bot name {client.user}")
	print(f"Bot ID {ID}")
	print(f"Bot Token {TOKEN}")
	print(f"_____________________________________________________________")

@client.event
async def on_message(message):
	print(f"{message.channel}: {message.author}: {message.author.name}: {message.content}:") 
	if "!hi" == message.content.lower():
		await message.channel.send("Hello welcome to the server! Type !help for some commands.")
		return

	if "!test" == message.content.lower():
		await message.channel.send("You said test!")
		return

	if "!help" == message.content.lower():
		await message.channel.send("check out this webpage for some commands. hidden")
		return

	if "!tools" == message.content.lower():
		await message.channel.send("hiding this")
		return

	if "!project" == message.content.lower():
		await message.channel.send("hiding this")
		return

	if "!github" == message.content.lower():
		await message.channel.send("hiding this")
		return

	if "!ping" == message.content.lower():
		await message.channel.send("Pong!")
		return

	if "!buybot" in message.content.lower():
		await message.channel.send("contact hidden to buy a cheap custom discord bot!")
		return

client.run(TOKEN)


await client.say("test")
AttributeError: 'Bot' object has no attribute 'say'

**Comment by Gorialis** [comment]
This issue is unactionable until you complete the template properly. The categories exist for a reason, not just for you to tick all 3 boxes after posting, even though there is clear evidence to show you haven't done some, and reasonable assumption therefore that you have not done any of them.

For any further assistance on this issue we need:
- Your discord.py version. "Latest" does not tell us anything, we need the actual version number.
- The traceback for the error. It begins with `Traceback (most recent call last)` and is emitted alongside pretty much every exception. You ticked to say you had included this, but you have not.

**Comment by CapnS** [comment]
From the looks of it you have mixed rewrite and async code, which are two completely different versions of this library. You probably installed rewrite it which case you should use Channel.send("message") (where Channel is a discord.abc.Messageable object) instead of bot.say().

**Comment by numbermaniac** [comment]
You've placed your `client.say()` within your `on_ready()` event, which isn't going to work at all. How would your bot know _where_ to say "test"?
