### ISSUE TITLE
Exception raised when checking permissions of client user in a channel

### ISSUE THREAD

**Issue by aBMania** [Rapptz/discord.py#2025]
### Summary

`client_user.permissions_in(self, channel)` raise exception : ClientUser object has no attribute 'roles'

I may be using it wrong, but it seems strange

### Reproduction Steps

```
channel = ...
permissions = self.user.permissions_in(channel) # Self is class MyClient(discord.Client)
# Exception raised
```

### Actual Results

`User.permissions_in` calls: 
```
channel.permissions_for(self) # Pass a user as parameter
```

But the `self` type passed to `permissions_for` is instance of `ClientUser`.
`permissions_for` expect an instance of `Member` : 

```
    def permissions_for(self, member):
        """Handles permission resolution for the current :class:`Member`.

        This function takes into consideration the following cases:

        - Guild owner
        - Guild roles
        - Channel overrides
        - Member overrides

        Parameters
        ----------
        member: :class:`Member`
            The member to resolve permissions for.

        Returns
        -------
        :class:`Permissions`
            The resolved permissions for the member.
        """
```

And as the `roles` property is on `Member class`,  it cannot be found in `ClientUser`, hence the error.

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- discord.py version:  1.0.0a0 (rewrite)
- Python version: Python3.6
- Operating system: MacOS 10.13.6

Anyway, thanks for maintaining the lib :)
Cheers !

**Comment by aBMania** [comment]
Just found that it duplicated https://github.com/Rapptz/discord.py/issues/1670
To prevent this, a solution may be to move the `permissions_in` method from `User` into `Member`

**Comment by Phxntxm** [comment]
This error is being raised "correctly", you even answered your own issue in your original post.
```
But the self type passed to permissions_for is instance of ClientUser.
permissions_for expect an instance of Member

And as the roles property is on Member class, it cannot be found in ClientUser, hence the error.
```

This is correct, it expects a `Member` object, not a `ClientUser` object. The second comment you posted is not a "workaround", it is the intended use.

**Comment by aBMania** [comment]
Oh okay ! 
I found it confusing for `permissions_in` to be in `ClientUser` since calling it will raise an exception. 
If permissions are relative to `Guild`, it wouldn't it be better suited in `Member` ?

**Comment by Harmon758** [comment]
Note, this is unlikely to change because `ClientUser.permissions_in` and `User.permissions_in` currently work with DM (and probably Group) channels.
