### ISSUE TITLE
[commands] Iterating through the help command mapping returns NoneTypes

### ISSUE THREAD

**Issue by sirtezza451** [Rapptz/discord.py#2029]
### Summary

Each item in the help command mapping is a NoneType when iterating through it by doing the following:
```python
for key, value in mapping.items():
    ...
```

### Reproduction Steps

Iterate through the items that `Bot.get_bot_mapping()` returns, then use any attribute of `Cog`, e.g. `qualified_name`

```python
    async def send_bot_help(self, mapping):
        for cog, cmds in mapping.items():
            name = cog.qualified_name
            ...
```

### Expected Results

Each key in `Bot.get_bot_mapping().items()` is of type `Cog`, and `cog.qualified_name` returns the cog's name

### Actual Results

An `AttributeError` occurs with the message `'NoneType' object has no attribute 'qualified_name'`, meaning that each key in the dictionary is a `NoneType`

Full traceback:
```
Traceback (most recent call last):
  File "~/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 63, in wrapped
    ret = await coro(*args, **kwargs)
  File "~/.local/lib/python3.6/site-packages/discord/ext/commands/help.py", line 754, in command_callback
    return await self.send_bot_help(mapping)
  File "~/DiscordBot/core/utils.py", line 28, in send_bot_help
    name = cog.qualified_name
AttributeError: 'NoneType' object has no attribute 'qualified_name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "~/.local/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 860, in invoke
    await ctx.command.invoke(ctx)
  File "~/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 698, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "~/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 72, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'qualified_name'
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- discord.py version: rewrite alpha 1590
- Python version: 3.6.8
- Operating system: Debian 9.8

**Comment by Rapptz** [comment]
From the [documentation](https://discordpy.readthedocs.io/en/rewrite/ext/commands/api.html#discord.ext.commands.HelpCommand.send_bot_help):

> mapping (Mapping[Optional[Cog], List[Command]) – A mapping of cogs to commands that have been requested by the user for help. The key of the mapping is the Cog that the command belongs to, or **None if there isn’t one**, and the value is a list of commands that belongs to that cog.

Emphasis mine.
