### ISSUE TITLE
[commands] Commands don't work from within a Bot subclass

### ISSUE THREAD

**Issue by sirtezza451** [Rapptz/discord.py#2031]
### Summary

Running `self.add_command(self.callback)` from within a subclass of `commands.Bot` adds the command. However, a `MissingRequiredArgument` is raised when the command is run, saying that the `ctx` argument is missing.

When the command is in a different file, and that file is loaded as an extension, it is completely fine.

### Reproduction Steps

From within a subclass of `commands.Bot`, run `self.add_command(self.callback)` and then run that command from Discord.

```python
class BotSubclass(commands.Bot):
    def __init__(self):
        self.add_command(self.callback)
        ...

    @commands.command()
    async def callback(self, ctx):
        ...
```

### Expected Results

Running `[prefix]command` in Discord runs the command as normal.

### Actual Results

A `MissingRequiredArgument` is raised, saying that `ctx` is a required argument which is missing.

Traceback:
```
Ignoring exception in command callback:
Traceback (most recent call last):
  File "~/.local/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 887, in invoke
    await ctx.command.invoke(ctx)
  File "~/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 691, in invoke
    await self.prepare(ctx)
  File "~/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 655, in prepare
    await self._parse_arguments(ctx)
  File "~/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 570, in _parse_arguments
    transformed = await self.transform(ctx, param)
  File "~/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 426, in transform
    raise MissingRequiredArgument(param)
discord.ext.commands.errors.MissingRequiredArgument: ctx is a required argument that is missing.
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- discord.py version: rewrite alpha 1790
- Python version: 3.6.8
- Operating system: Debian 9.8

**Comment by MusicOnline** [comment]
According to Danny on Discord post cogs update, this was never intended to work. Commands can only and must take `self` in cogs, and nowhere else. You can either make the method a static method (bad), or better yet, use the `@bot.command` decorator instead.
