### ISSUE TITLE
NameError: name 'change_server' is not defined

### ISSUE THREAD

**Issue by McCrafterIV** [Rapptz/discord.py#2032]
### Summary

I want to change the server name of one Server, but that not work's. After a look in the client.py I see that in change_server the name is not defined

### Expected Results

`client.edit_server(server, name="Test")`
No Output and no changes 

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- discord.py version: newest
- Python version: 3.7.3
- Operating system: Windows 10

**Comment by MusicOnline** [comment]
It's a coroutine. `await` it.

**Comment by McCrafterIV** [comment]
opps...thanks @MusicOnline my fault

**Comment by Harmon758** [comment]
See https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.edit_server

For future issues, please specify your exact version of discord.py, as the current "newest" version is v1.0.0a1791+g4ec7213 on the rewrite branch, and you seem to be using the async branch.
For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README also links.
