### ISSUE TITLE
get input from user?

### ISSUE THREAD

**Issue by JBB0** [Rapptz/discord.py#2042]
I want to get input from a user, but I do not know how.

I am making a command called !setup, where the bot asks you to specify the name of your server, and you are supposed to type in the name of your server. Then that string the user entered is now assigned to the variable 'name'.

**Comment by Phxntxm** [comment]
https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.wait_for_message

This is what you want.
As a side-note, github issues are typically for issues with the library, not for questions about how to use it. For future questions like this, it's typically best to join the [discord server](https://discord.gg/r3sSKJJ) and ask in there.

**Comment by Harmon758** [comment]
Note, on the rewrite branch, passing `"message"` to [`Client.wait_for`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Client.wait_for) is the equivalent.
