### ISSUE TITLE
Update version numbers (to 1.0.1a or something)

### ISSUE THREAD

**Issue by VoxelPrismatic** [Rapptz/discord.py#2052]
### The Problem
You don't update version numbers
 Knowing what version of rewrite you have

### The Ideal Solution

 
**update the version numbers**

### The Current Solution

 Lol there is none

### Summary

 Please update version numbers, it's annoying when you don't...

**Comment by VoxelPrismatic** [comment]
Why is this invalid

**Comment by Rapptz** [comment]
https://github.com/Rapptz/discord.py/blob/61ee88b0fc48ba2bfc479bccec0e99a92c05fa1d/setup.py#L15-L30

**Comment by OrangutanGaming** [comment]
1. This will be updated on release
2. The git hash is added to the version number depending on how you install the library

**Comment by NCPlayz** [comment]
you use the commit to track what version of 1.0.0a you have
