### ISSUE TITLE
(0.16.12) no discord.Category (async)

### ISSUE THREAD

**Issue by TrentonGage11** [Rapptz/discord.py#2070]
### The Problem
I want to get get a category ID by its name in discord.py ver: 0.16.12 (i'm not updating)

### The Ideal Solution
maybe a snip of code or a way to get it without discord.Category

### The Current Solution
Don't have one

### Summary
Just general help

**Comment by Rapptz** [comment]
This version is now unsupported.

**Comment by TrentonGage11** [comment]
> This version is now unsupported.

Yes, I know this

**Comment by Rapptz** [comment]
Opening an issue here counts as support. Since it's unsupported and no longer receiving updates then don't open issues pertaining to it because no development time will be allotted to it. 

Thanks for understanding.
