### ISSUE TITLE
int(SpeakingState.voice) TypeError

### ISSUE THREAD

**Issue by XuehaoXiang** [Rapptz/discord.py#2078]
At discord/gateway.py line 664
'speaking': int(state), 
which state defaults to SpeakingState.voice
My python version is 3.6.6 and it can't convert SpeakingState.voice to int type.

the error message:

  File "C:\ProgramData\Anaconda3\lib\site-packages\discord\gateway.py", line 725, in load_secret_key
    await self.speak()
  File "C:\ProgramData\Anaconda3\lib\site-packages\discord\gateway.py", line 664, in speak
    'speaking': int(state),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'SpeakingState'

**Comment by Rapptz** [comment]
If only you didn't skip the contributing guidelines and the issue template you would have posted the version number and then found out you were out of date since v1.0.1 is the one on PyPI and the one you have is v1.0.0.

A real shame.
