### ISSUE TITLE
Exception handling for KeyboardInterrupt does nothing

### ISSUE THREAD

**Issue by raylu** [Rapptz/discord.py#208]
While looking into why the bot doesn't exit after one SIGINT, I noticed the exception handling in `Client.run` introduced by 6d26d73. It looks like the code was taken from http://stackoverflow.com/a/27910822/385891 . The main issue is that it calls `loop.run_forever` again for some reason.

It also calls `Future.exception` but ignores the return value. https://docs.python.org/3/library/asyncio-task.html#asyncio.Future.exception doesn't raise, but even if it did, you have an `except: pass` right after that would drop it.

Possibly related: https://github.com/Rapptz/discord.py/pull/8

**Comment by Rapptz** [comment]
I think I fixed this. Reopen if you don't think so.
