### ISSUE TITLE
TypeError: on_voice_state_update() missing 1 required positional argument: 'after'

### ISSUE THREAD

**Issue by hwahyang1** [Rapptz/discord.py#2099]
### Summary

I wrote and executed the code as follows, but the error occurred.

**@app.event
async def on_voice_state_update(member, before, after):
    print("success")**

### Reproduction Steps

I wrote the code above and entered the Voice channel.

### Expected Results

It prints "success"

### Actual Results

**Ignoring exception in on_voice_state_update
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
TypeError: on_voice_state_update() missing 1 required positional argument: 'after'**

### Checklist

- [ O ] I have searched the open issues for duplicates.
- [ O ] I have shown the entire traceback, if possible.
- [ O ] I have removed my token from display, if visible.

### System Information

- discord.py version : 0.16.12
- Python version : 3.6.5
- Operating system : Windows 10 pro X64 (English)

**Comment by Rapptz** [comment]
The v0.16.12 version of the library is unsupported now. The signature that you are using is for v1.0 or higher, that's why it's giving you an error. I suggest migrating and following the guide to help you: https://discordpy.readthedocs.io/en/latest/migrating.html
