### ISSUE TITLE
Incorrect Documentation

### ISSUE THREAD

**Issue by BluePhoenixGame** [Rapptz/discord.py#2100]
### Summary
While looking through the docs I noticed a few mistakes and typos. Here I have them listed.

### Reproduction Steps
Go to the documentation at https://discordpy.readthedocs.io/en/rewrite/api.html
### Expected Results
Correct grammar and etc.
### Actual Results
Incorrect grammar and other mishaps.
### Checklist

- [ ] I have searched the open issues for duplicates.
- [ ] I have shown the entire traceback, if possible.
- [ ] I have removed my token from display, if visible.

### System Information

- discord.py version:
- Python version:
- Operating system:

**Comment by BluePhoenixGame** [comment]
Oops, accedentslly opened it before I was done. Gonna close and edit it. Sorry.

**Comment by MinerChAI** [comment]
It's better to send a pull request.
Go to any page of docs, then follow this screenshots 
![First](https://user-images.githubusercontent.com/43097806/56374781-a3dfe600-620c-11e9-8fb8-4d897ed380fa.png)
![Second](https://user-images.githubusercontent.com/43097806/56374809-b22e0200-620c-11e9-84ee-c77a87ced04f.png)

**Comment by BluePhoenixGame** [comment]
I don't know the ".rst" "language" but I might as well learn along the way. Thanks.

**Comment by MinerChAI** [comment]
You don't need any knowledge - just find the phrase and correct
