### ISSUE TITLE
Auto help breaks when using check

### ISSUE THREAD

**Issue by bannsec** [Rapptz/discord.py#2105]
### Summary
The auto population of the `help` command fails to populate once a `check` wrapper is around the function.

### Reproduction Steps
```python
from discord.ext import commands
from ..decorators import permission_checker
import functools

@commands.check(functools.partial(permission_checker, allowed_roles='admin'))
async def ping(ctx):
    """Returns Pong! How exciting!"""
    await ctx.send('Pong')
```

### Expected Results
Expect the `ping` help to be shown when using `.help`

### Actual Results
No ping information in help anymore. Without the `commands.check` wrapper, help does successfully grab the info about ping.

### Checklist
- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information
- discord.py version: `discord.py==1.0.1`
- Python version: `Python 3.6.7`
- Operating system:  `Ubuntu 18.04`

**Comment by Rapptz** [comment]
https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.HelpCommand.verify_checks

**Comment by bannsec** [comment]
The check passes for me when called. Shouldn't that mean the command should
show up in help?

**Comment by Rapptz** [comment]
If you are the one running the command and the checks pass then yes that should be the case, and indeed that is what happens when I run code that does this locally.

**Comment by bannsec** [comment]
Ah. Permissions check was wrong.
