### ISSUE TITLE
send_message Issues

### ISSUE THREAD

**Issue by loub2018** [Rapptz/discord.py#2108]
Hello. I'm making a bot that DMs people when they join a discord server. I was told to use send_message but when I use it, it says "'Client' object has no attribute 'send_message'".

HELP!!
![proof](https://user-images.githubusercontent.com/35196589/56464240-cf98d280-63aa-11e9-8aa2-a194175a1178.PNG)

**Comment by loub2018** [comment]
Update: This is the code I have.

![my_code](https://user-images.githubusercontent.com/35196589/56464262-1b4b7c00-63ab-11e9-8c0e-d0241616c34b.PNG)

**Comment by XuaTheGrate** [comment]
0.16.x (async branch) is no longer supported. Please read the migrating guide [here](https://discordpy.readthedocs.io/en/latest/migrating.html) and update your code to the latest verison.

**Comment by Rapptz** [comment]
The 0.16.12 version of the library is unsupported. If you need help migrating, visit the migration guide: https://discordpy.readthedocs.io/en/latest/migrating.html

If you need more help consider joining the [official Discord server](https://discord.gg/r3sSKJJ).
