### ISSUE TITLE
client.send() issues

### ISSUE THREAD

**Issue by loub2018** [Rapptz/discord.py#2109]
sorry if this is documented, but i supposedly "updated" my code and now it says client has no attribute send. please help.

**Comment by loub2018** [comment]
idc about my bad grammar im just trying to get this done with.

**Comment by loub2018** [comment]
> help me
-like no one ever

**Comment by CapnS** [comment]
This is in fact documented, much like everything else in the library. If you were to read the [documentation](https://discordpy.readthedocs.io/en/latest) you would see that it's not Client.send(). It is in fact Channel.send() or Context.send(). 


This is not an issue with discord.py.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.
For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by Harmon758** [comment]
As the [migration guide](https://discordpy.readthedocs.io/en/latest/migrating.html) outlines, `Client.send_message` has been changed to [`Messageable.send`](https://discordpy.readthedocs.io/en/latest/api.html#discord.abc.Messageable.send).
This means you need use an object of a type that implements [`Messageable`](https://discordpy.readthedocs.io/en/latest/api.html#discord.abc.Messageable).
[`Client`](https://discordpy.readthedocs.io/en/latest/api.html#client) is not one of those classes.
See https://discordpy.readthedocs.io/en/latest/migrating.html#sending-messages.

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README also links.

**Comment by loub2018** [comment]
sorry, but i dont understand. can you give me a simple explanation?
