### ISSUE TITLE
Depency Update

### ISSUE THREAD

**Issue by AngerKingz** [Rapptz/discord.py#2110]
### The Problem

update to webscockets 7.0

**Comment by Vexs** [comment]
Thanks for filling out the issue form.

[It's not updated because websockets v7 has a bug preventing it's usage in this library. ](https://github.com/aaugustin/websockets/issues/551)

**Comment by Harmon758** [comment]
Also see https://github.com/Rapptz/discord.py/commit/5fe1ab279af779fd225278517261d09690af0106 and https://github.com/Rapptz/discord.py/issues/1996.
