### ISSUE TITLE
Client.wait_for() can't receive a response from a specific message

### ISSUE THREAD

**Issue by IVIuho** [Rapptz/discord.py#2111]
Before version 1.0:
```
response = await self.wait_for_reaction(
    emoji=[u"\U0001F44D", u"\U0001F44E"],
    timeout=float(20),
    user=message.author,
    message=some_message
)
```

Now version 1.0:
```
response = await self.wait_for(
    "reaction_add",
    check=lambda re, user: re.emoji in [u"\U0001F44D", u"\U0001F44E"] and user == message.author,
    timeout=float(20)
)
```

I can't recieve response from 'some_message'.
I want to recieve from that, but Client.wait_for() reacts the same in other messages.
How can I solve this problem?

**Comment by Rapptz** [comment]
Questions are better suited [for the official Discord server](https://discord.gg/r3sSKJJ).

Your `wait_for` check needs to also handle the message case like the old code. Reaction objects have a [`message`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Reaction.message) attribute that you can access and then you can just compare their IDs.

**Comment by IVIuho** [comment]
I apologize for my stupidity. Thanks to help
