### ISSUE TITLE
Spotify objects with different songs are equal in on_member_update

### ISSUE THREAD

**Issue by TheGrammarJew** [Rapptz/discord.py#2113]
### Summary

When a song progresses to a different one on Spotify, `on_member_update` is called, but `before == after`, and `before.activities == after.activities`.

Seems to be caused by [hashing the session id](https://github.com/Rapptz/discord.py/blob/a7f3300821a47c7fc5fb7531ca1a72c3864ca545/discord/activity.py#L500), which doesn't change between songs.

### Reproduction Steps
```
@bot.event
async def on_member_update(b,a)
    print(b==a)
    print(b.activities == a.activities)
```
#### Output:
`False`
`False`

#### Output:
`True`
`True`

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] ~I have shown the entire traceback, if possible.~ N/A
- [x] ~I have removed my token from display, if visible.~ N/A

### System Information

- discord.py version: 1.0.1
- Python version: 3.7.1
- Operating system: Platform-independent (Tested on Centos 7, Win7/10)

**Comment by NCPlayz** [comment]
Doing a quick check reveals that comparing `Member` only compares the member ID and nothing else, as written [here](https://github.com/Rapptz/discord.py/blob/master/discord/member.py#L173). 
Assuming `Member.activities` has only an instance of [Spotify](https://github.com/Rapptz/discord.py/blob/master/discord/activity.py#L425), comparing the two only compares the session ID, as written [here](https://github.com/Rapptz/discord.py/blob/master/discord/activity.py#L499). 

A simple way to represent this is:

```py
class MyClass:
    def __init__(self):
        self.id = 5
        self.something_else = 2
        
    def __eq__(self, other):
        return self.id == other.id
    
my_list = [MyClass()]

m = MyClass()
m.something_else = 6
my_other_list = [m]

print(my_list == my_other_list)  # True because both instances of MyClass have the same ID
```

A way to work around this would be to compare the track_id of the Spotify instances instead.

**Comment by Rapptz** [comment]
The behaviour of `Member.__eq__` is not going to change. 

However, the behaviour of `Spotify.__eq__` could be better I suppose.

**Comment by Rapptz** [comment]
Fixed in https://github.com/Rapptz/discord.py/commit/01588fa34b782e8eee83d6900bb3485d095ca13c
