### ISSUE TITLE
Member.move_to(None) fails silently instead of kicking/throwing errors.

### ISSUE THREAD

**Issue by gamescom15** [Rapptz/discord.py#2128]
### Summary

I'm trying to use the new feature of [`move_to`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Member.move_to), where you can pass `None` to kick a member from a voice channel. 
However, it seems to fail silently, and as far as i know, i'm not eating any errors.

### Reproduction Steps

Create a simple kick command (in my case in a cog)
```py
    @commands.command()
    async def vkick(self, ctx, target_member: discord.Member):
        """Kicks a Member from a voice channel"""
        await target_member.move_to(None)
```
Use it (in this case `-vkick @username`)

### Expected Results

It should kick the target member, or throw an error if it is missing permissions.

### Actual Results

It fails silently. 
Tested in the following cases where the bot is trying to kick:

- himself
- the server owner
- someone lower on the hierarchy
- someone higher on the hierarchy
- someone that has no roles
- someone that is not in a voice channel

Note: In this Test, the bot has Administrator Permissions.

### System Information

- Python version: 3.7.0-final
- discord.py version: discord.py v1.1.0-alpha
    - discord.py pkg_resources: v1.1.0a1919+g91e00d8 (newest commit as of now)
- aiohttp v3.5.4
- websockets v6.0
- Operating system: Windows 10, basic example also tested on Ubuntu 16.04 LTS

**Comment by Rapptz** [comment]
Discord has not released this API yet, the change in the library was done in preparation.

**Comment by Harmon758** [comment]
See https://github.com/discordapp/discord-api-docs/pull/933
