### ISSUE TITLE
'name#discriminator' property for User / Member

### ISSUE THREAD

**Issue by DevilXD** [Rapptz/discord.py#2129]
### The Problem

`name#discriminator` combination is often used in feedback messages to specify that something happened to a specific User / Member, without bothering them with mentions. Because it's used so often, I thought that it could be made into a helper property, just like `mention` exists right now.

### The Ideal Solution

Add a property to User / Member that returns their "discord tag" in `name#discriminator` form. The property name could be `tag` or `full_name`, or anything better fitting I guess.

```py
'{}'.format(user.tag)
'{0.tag}'.format(user)
f'{user.tag}' # Python 3.6+ only
```

### The Current Solution

These:

```py
'{}#{}'.format(user.name, user.discriminator)
'{0.name}#{0.discriminator}'.format(user)
f'{user.name}#{user.discriminator}' # Python 3.6+ only
```

**Comment by Rapptz** [comment]
Just cast it to `str`.

**Comment by DevilXD** [comment]
Omg, I'm dumb >.<
