### ISSUE TITLE
on_reaction_add doesn't always receive correct emoji (rewrite v1?)

### ISSUE THREAD

**Issue by robertlugg** [Rapptz/discord.py#2131]
on_reaction_add() accepts a reaction.  reaction.emoji sometimes returns the incorrect value.

Consider : p e n c i l 2 :  ✏️ 
ord(v[0]) is 9999
but length is 1 character.  I believe it should be two characters which would be
9999 and 65039

**Comment by Rapptz** [comment]
:pencil2: has is codepoint U+270F

0x270F corresponds to 9999 in decimal.

There is no issue here.

See: http://www.fileformat.info/info/unicode/char/270f

**Comment by robertlugg** [comment]
I'm comparing an emoji entered in a message to the reaction.emoji and they differ.  Note that some emojis are fine.

I apologize as I may be doing something wrong.  Would you take a look at this session where I interrogate an emoji in a message:
![pencil_emoji_in_message](https://user-images.githubusercontent.com/6054540/57008837-c6c4af80-6ba7-11e9-8e1c-780e2cbc9375.png)

And the value of reaction.emoji:
![pencil_emoji_in_reaction](https://user-images.githubusercontent.com/6054540/57008842-c9270980-6ba7-11e9-99b3-6ab6c89e7d92.png)

That second character (65039) is described as a VARIATION SELECTOR-16
https://www.fileformat.info/info/unicode/char/fe0f/index.htm
, if I understand correctly.

Can you suggest what is going on?  I can just ignore that second character but I don't think that is generally correct.

**Comment by Rapptz** [comment]
This just seems like someone's message having faulty copy-pasting. If the `reaction.emoji` value is `0x270F` then the culprit is not the reaction's emoji, but the user input that's being compared.

**Comment by khazhyk** [comment]
some mobile clients or emoji keyboards may add extra modifiers etc. that discord does not support, which may be where you're getting this strange input

**Comment by numbermaniac** [comment]
The list of emojis you can add as a reaction is limited by Discord's list though, so I don't think that's true.
