### ISSUE TITLE
Try Disallowing Shadowing at Compile Time in Cogs

### ISSUE THREAD

**Issue by Rapptz** [Rapptz/discord.py#2134]
I'm thinking of disallowing shadowing with a more descriptive error at compile time for the cog. One thing I worry about is "legitimate" use cases. I could not think of any. I'm tracking this issue to receive comments on whether this should a compile time error the library does to save some support time.

Example of what would be disallowed:

```py
class C(commands.Cog):
    @commands.command()
    async def foo(self, ctx):
        pass

    @commands.command()
    async def foo(self, ctx):
        pass
```

**Comment by gamescom15** [comment]
Considering that the `name` keyword argument for the `@commands.command()` decorator exists, i don't think that this

**Comment by ALobsterDog** [comment]
I would be curious if anyone could come up with a valid use-case for this. Definitely should raise at compile-time

**Comment by mikeshardmind** [comment]
As long as this only prevents shadowing commands (and not functions) this won't be a large issue. 

With the prevention of shadowing all functions in a class built into this, you could break uses of `typing.overload` needlessly.

**Comment by bmintz** [comment]
What happens if you subclass a cog and use `ctx.invoke(super().command, ...)` or `super().command.callback(ctx, ...)` to extend one of the commands?

**Comment by Rapptz** [comment]
Nothing?

**Comment by bmintz** [comment]
OK. And if this is a breaking change, why is it being considered?

**Comment by bmintz** [comment]
It's labeled as such. And this breaks the behavior of a cog which shadows a command name.

**Comment by LucasCLuk** [comment]
@bmintz an issue brought up every once and a while is having a function name foo spread between 2 different command groups. Having an error would make it more obvious to the developer.

**Comment by Rapptz** [comment]
It's more of a bug fix than a breaking change. Shadowed commands have never worked.
