### ISSUE TITLE
Issue with token verification

### ISSUE THREAD

**Issue by VoxelPrismatic** [Rapptz/discord.py#2135]
### Summary

Able to log in and do whatever I want, but upon trying to send a message a `411 Length Required` error is thrown

### Reproduction Steps

Just add `\n` to the end of your token
**EDIT** Apperently you need 2 newlines, so put `\n\n` at the end of your token

### Expected Results

I expect that the invalid token was caught earlier, preferably before logging in

### Actual Results

I could log in to my bot with an invalid key, and only sending a message threw an error
Traceback is [here](https://imgur.com/gallery/kAe87A9) (imgur cuz I don't have the copy-paste)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- discord.py version: `1.0.1a RW`
- Python version: `3.7.3`
- Operating system: `Kubuntu 18.10 Cosmic Cuttlefish`

**Comment by CapnS** [comment]
I have tested this with two bots, and I cannot reproduce this. It throws an error on login because the authentication is incorrect.

**Comment by VoxelPrismatic** [comment]
I'm not too sure, but given that you cannot reproduce this, it may be a Linux specific issue

**Comment by CapnS** [comment]
On linux, I get a similar, yet slightly different error when having a newline at the end of my token.

Traceback:
```
Traceback (most recent call last):
  File "testbot.py", line 10, in <module>
    bot.run(TOKEN_REDACTED)
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 544, in run
    self.loop.run_until_complete(runner())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 539, in runner
    await self.start(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 510, in start
    await self.login(*args, bot=bot)
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 376, in login
    await self.http.static_login(token, bot=bot)
  File "/usr/local/lib/python3.6/dist-packages/discord/http.py", line 258, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/usr/local/lib/python3.6/dist-packages/discord/http.py", line 222, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: Bad Request (status code: 400): <html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
```

**Comment by VoxelPrismatic** [comment]
Are you sure you did `bot.run('{token}\n')`?

**Comment by CapnS** [comment]
yes

**Comment by VoxelPrismatic** [comment]
Interesting

**Comment by VoxelPrismatic** [comment]
Maybe it's because I put the key into a different file called `secrets.txt`...
```python
with open('secrets.txt', 'r') as KEY: secret = KEY.readlines()
key = secret[0]
bot.run(key)```

**Comment by CapnS** [comment]
Can we please take this issue into the [discord.py server](https://discord.gg/r3sSKJJ)?

**Comment by VoxelPrismatic** [comment]
Sure

**Comment by VoxelPrismatic** [comment]
My discord tag is `!] VOXΞLIZΣD PRISMΛTIC#9244`

**Comment by VoxelPrismatic** [comment]
Apperently 2 new lines are needed, according to `Ava#4982` and `Phantom#0004`

**Comment by davfsa** [comment]
By digging into the code, I have found that this could be a error caused by discord ignoring new lines when authenticating and discord.py not removing the new lines. A fix could be removing all the new lines off the token before authenticating : https://github.com/Rapptz/discord.py/blob/master/discord/client.py#L376

The reason why this error comes up is because when the requests are sent the newlines are included messing up the request.

**Comment by VoxelPrismatic** [comment]
The funny part is, you fail to log in with a single new line, but log in fine with two.... But yeah, that is an issue.
Because I'm not proficient in python, the following code is NOT the best to use, but is certainly good enough
```py
await self.http.static_login(token.replace("\n", ""), bot=bot)
```

**Comment by MinerChAI** [comment]
Better use `
token.strip()
`

**Comment by OrangutanGaming** [comment]
1. You shouldn't ever have this problem, there is no good reason to ever have any, let alone 2, new lines. If you want to store your token in a file, either make sure you're doing it properly or use JSON
2. Just removing the newlines when logging in isn't a great solution as it doesn't tell the user that they have a problem with their code and instead tries to fix it for them.
