### ISSUE TITLE
AttributeError: 'Client' object has no attribute 'send_message'

### ISSUE THREAD

**Issue by S-B99** [Rapptz/discord.py#2138]
### Summary

The attribute "send_message" is missing

### Reproduction Steps

- run `python3.6 startup.py`
- requires a discord API token in a file called `token.txt`
- execute `!hello` in the server, it finds the call correctly and tries to execute but finds "send_message" does not have any attributes.

### Expected Results

The command executes successfully.

### Actual Results

It ignores the exception and does not execute.

> Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/usr/.local/lib/python3.6/site-packages/discord/client.py", line 255, in _run_event
    await coro(*args, **kwargs)
  File "startup.py", line 34, in on_message
    await client.send_message(message.channel, msg)
AttributeError: 'Client' object has no attribute 'send_message'

### Checklist

- [X] I have searched the open issues for duplicates.
    - Only other duplicate was closed due to non reply.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
    -  Inside separate file

### System Information

- discord.py version: `1.0.1`
- Python version: `3.6`
- Operating system: Ubuntu 18.10 non-LTS

**Comment by Gorialis** [comment]
`Client.send_message` is a method from the async (0.16.x) version of the library. Support for this version has ended, and you must migrate to v1.0:
https://discordpy.readthedocs.io/en/latest/migrating.html

**Comment by S-B99** [comment]
Thanks, got it.
