### ISSUE TITLE
Webhook retry mechanic bug

### ISSUE THREAD

**Issue by Werseter** [Rapptz/discord.py#2140]
### Summary

Currently, the mechanic allowing multiple attempts to send a webhook mechanic has a bug, that overwrites the request data with the response, rendering every attempt latter than the first one to send an incorrect request.

### Reproduction Steps

For example, sending executing multiple webhooks executions in short succession, triggering ratelimiting asynchronous sleep period.

### Expected Results

We are supposed to still send the same request we tried to send prior to retrying.

### Actual Results

Server response is fed back. This can cause multitude of errors, i.e 'Cannot send an empty message' due to last response from 'X-Ratelimit-Remaining' being empty prior to continuing.

### Checklist

- [x] I have searched the open issues for duplicates.
- [ ] I have shown the entire traceback, if possible.
- [ ] I have removed my token from display, if visible.

### System Information

- discord.py version: latest commit 792b318 (running from source)
- Python version: Python 3.6
- Operating system: Windows 8.1

**Comment by Rapptz** [comment]
I believe this is an issue with Discord rather one with the library.

Discord has done this from time to time before, whether with the library doing it or something like `curl` or `requests` alone.

**Comment by Werseter** [comment]
I didn't find time to make a PR from PC but the fix is a simple manner of renaming data to response inside the loop so the original data that we send through the webhook doesn't get overwritten when retrying.

**Comment by Rapptz** [comment]
Oh I see what you're referring to. It got conflated with the curl-related issue I've seen before, e.g. https://canary.discordapp.com/channels/336642139381301249/336642776609456130/576496506983677953
