### ISSUE TITLE
Invalid behaviour of role position updates

### ISSUE THREAD

**Issue by Fogapod** [Rapptz/discord.py#2142]
### Summary

I create 10-15 roles with my command and place them below author's top role.
The problem is the order is broken. 20-30% of roles remain at the bottom.

### Reproduction Steps

The following code reproduces issue in 90% of the time for me
```
insert_pos = ctx.author.top_role.position - 1

for i in range(10):
  created = await ctx.guild.create_role(name=str(i))
  await created.edit(position=insert_pos)
```

### Expected Results

Roles to be placed in the following order: `[..., top_role, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, ...]`

### Actual Results

Roles are placed in the following order: `[..., top_role, 0, 1, 3, 4, 5, 6, 8, 9, ..., 2, 7, @everyone]`
(order is random all the time)

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- discord.py version: 1.0.1
- Python version: 3.7.3
- Operating system: Manjaro Linux x86_64

**Comment by Vexs** [comment]
What's happening is you're running into a cache issue by the looks of it- role objects and the like are only added to cache when they get the update from the websocket that the role has been created. Just calling `create_role` doesn't add it to cache, there's a noticeable delay. 

Further, moving a role isn't a one-at-a-time operation- you actually set the new positions of all roles affected by the change. Discord.py uses the cache to make this operation easier for you, by figuring out what roles are affected and where they need to go. But as the cache isn't going to be up-to-date in this case, the behavior you're seeing happens.

Without getting into lib internals, you can add a sleep in your loop to hopefully wait for the cache to be updated. 
This isn't really a perfect answer, and a good fix requires you to mess with some internal methods- take a look at [the implementation for role-moving](https://github.com/Rapptz/discord.py/blob/master/discord/role.py#L179-L200) and you should be able to figure out how to do it. You'd create all your new roles first, and then after you'd call `http.move_role_position` with the positions you want. 

As there doesn't appear to be a method for this in the library, I'll open a feature-request issue.

**Comment by Fogapod** [comment]
I ran below code trying to add some delay between role edits, but it did not help at all.
```
import asyncio

created = []
for i in range(10):
  created.append(await ctx.guild.create_role(name=str(i)))

await asyncio.sleep(10)
for role in created:
  await role.edit(position=ctx.author.top_role.position-1)
  await asyncio.sleep(10)
```
The result of running this code is on the screenshot. Is it really a caching issue? 10 seconds should be enough for events to fire. Sometimes these roles are placed above author's top role, other roles go to random positions all the time.
![image](https://user-images.githubusercontent.com/22667809/57568496-f322cc00-73f0-11e9-95a6-7d588fa0766d.png)

**Comment by Fogapod** [comment]
Low level solution to initial problem:
```
created_ids = []
for name in to_create:
    created = await ctx.guild.create_role(name=name)

    created_ids.append(created.id)

positions = []
for role in ctx.guild.roles:
    if role.id in created_ids:
        continue

    if role == ctx.author.top_role:
        positions.extend(created_ids)

    positions.append(role.id)

payload = [{"id": r, "position": i} for i, r in enumerate(positions)]
await ctx.bot.http.move_role_position(ctx.guild.id, payload)
```

**Comment by Rapptz** [comment]
This is fixed and supported by https://github.com/Rapptz/discord.py/pull/2501
