### ISSUE TITLE
discord.Invite attributes missing

### ISSUE THREAD

**Issue by BluePhoenixGame** [Rapptz/discord.py#2146]
After a bit of testing it seems that some invite attributes return None when using `InviteConverter` and when using `Client.fetch_invite(str)`, more specifically: `Invite.created_at`, `Invite.max_age`, `Invite.max_uses`, `Invite.uses`
None of the attributes are documented to be `Optional[X]` _(X being whatever class it should be returning)_ so if it's meant to return None sometimes then that needs to be changed.

To reproduce replace "TOKEN" with your token, run the bot and send the command with discord.py's invite: `https://discord.gg/r3sSKJJ`
```python
import discord
from discord.ext import commands

bot = commands.Bot(command_prefix="!")

@bot.command()
async def test_invite(ctx, invite: discord.Invite):
    await ctx.send("{}, {}, {}, {}, {}, {}".format(invite.code, invite.guild.name, invite.created_at, invite.max_age, invite.max_uses, invite.uses))

bot.run("TOKEN")
```
Or with `Client.fetch_invite(str)`
```python
import discord
from discord.ext import commands

bot = commands.Bot(command_prefix="!")

@bot.command()
async def test_invite(ctx, invite_str: str):
    invite = await bot.fetch_invite(invite_str)
    await ctx.send("{}, {}, {}, {}, {}, {}".format(invite.code, invite.guild.name, invite.created_at, invite.max_age, invite.max_uses, invite.uses))

bot.run("TOKEN")
```

![discordpy_issue](https://user-images.githubusercontent.com/38372706/57568263-219aaa00-73e5-11e9-87c3-06cffcc6ed05.png)

discord.py: 1.1.0
Python: 3.7.3
Operating System: Ubuntu 19.04

**Comment by MusicOnline** [comment]
Here's a reminder that the issue template exists ;v
Unfortunately everything needs to be typed as `Optional` at some point because Discord's API is fun stuff.
:yikes:

**Comment by BluePhoenixGame** [comment]
Yeah, i know the template exists. Wait yeah, i forgot to add my discord.py version and all sorry

**Comment by Rapptz** [comment]
![](https://cdn.discordapp.com/attachments/182332539975892992/576824076862095382/unknown.png)

https://discordpy.readthedocs.io/en/latest/api.html#invite
