### ISSUE TITLE
Background tasks runs before the bot starts

### ISSUE THREAD

**Issue by MCK001** [Rapptz/discord.py#2156]
### Summary

The background task runs before the bot actually starts, and the bot never starts.

### Reproduction Steps

```py
async def my_background_task():
         await client.wait_until_ready()
         feed = parse("rss link")
         channel = client.get_channel(channelID)
         print("Started background task.")
         while not client.is_closed():
             lastMessage = open("lastMessage.txt", "r")
             latestEntry = feed.entries[0]['link']
             if latestEntry == lastMessage.read():
                 pass
             else:
                 lastMessage.close()
                 lastMessage = open("lastMessage.txt", "w")
                 lastMessage.write(latestEntry)
                 lastMessage.close()
                 await channel.send(latestEntry)
                 print("Sent.")
client.loop.create_task(my_background_task())
client.run("key") 
```

### Expected Results

The bot starts, finds the latest article from the RSS feed, and posts it, unless it's already been posted. It will loop and continue to do this.

### Actual Results

The background task starts but the bot doesn't.

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- discord.py version: 1.0.0a0
- Python version: 3.6.0
- Operating system: Windows 10

**Comment by MCK001** [comment]
sorry about the formatting of my code, github's being weird

**Comment by Hornwitser** [comment]
Please use [code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) when posting code.

**Comment by Vexs** [comment]
It's very difficult to read this but as best I can tell it's not that the loop starts before the bot does- it's that it blocks and prevents anything from happening. You don't yield to the event loop anywhere. See [the faq on blocking.](https://discordpy.readthedocs.io/en/latest/faq.html#what-does-blocking-mean)

Further, you'll want to see if there is some async-compatible rss feed reader.
