### ISSUE TITLE
AttributeError: 'Client' object has no attribute 'get_server'

### ISSUE THREAD

**Issue by OujiaBoard** [Rapptz/discord.py#2163]
await coro(*args, **kwargs)
  File "main.py", line 16, in on_ready
    await main()
  File "main.py", line 20, in main
    server = client.get_server(SERVER)
AttributeError: 'Client' object has no attribute 'get_server'

**Comment by Rapptz** [comment]
You seem to be using old code. The 0.16.12 version of the library is unsupported. If you need help migrating, visit the migration guide: https://discordpy.readthedocs.io/en/latest/migrating.html

If you need more help consider joining the [official Discord server](https://discord.gg/r3sSKJJ).
