### ISSUE TITLE
Old messages sent when using message.channel.send (beginner question)

### ISSUE THREAD

**Issue by patrickjane** [Rapptz/discord.py#2164]
### Summary

I have the most basic bot which shall respond to the messages 'lol'. 
However the bot sends out multiple messages while the code only contains one `message.channel.send` call.

### Reproduction Steps

```
import logging
import discord

class DiscordClient(discord.Client):

    username = ''

    def __init__(self, *, loop=None, **options):
        discord.Client.__init__(self, **options)

        self.log = logging.getLogger(__name__)

    async def on_ready(self):
        self.username = self.user.name
        self.log.info('Logged on as {}'.format(self.username))

    async def on_message(self, message):
        # don't respond to ourselves
        if message.author == self.user:
            return

        self.log.info('Received message [{}]'.format(message.content))

        if message.content == 'ping':
            await message.channel.send('pong')
            return

        if message.content == 'lol':
            await message.channel.send('What oO')
            return
```

Then in the chat send "lol"

### Expected Results
`What oO`

### Actual Results
Logs:
```
2019-05-17 15:15:38,349:bot:INFO: Connecting to discord using 1.1.1 ...
2019-05-17 15:15:38,349:discord.client:INFO: logging in using static token
2019-05-17 15:15:39,106:discord.gateway:INFO: Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2019-05-17 15:15:39,107:discord.gateway:INFO: Shard ID None has sent the IDENTIFY payload.
2019-05-17 15:15:39,259:discord.gateway:INFO: Shard ID None has connected to Gateway: gateway-prd-main-1scj, discord-sessions-prd-1-27 (Session ID: xxxxx).
2019-05-17 15:15:41,263:bot:INFO: Logged on as D00de
2019-05-17 15:15:43,878:bot:INFO: Received message [lol]
```

Chat:
```
D00de BOT heute um 15:15 Uhr
What oO
What oO
```

So, according to the logs (and my actions, e.g. only sending 'lol' once in discord) the bot received 1 message ('lol') and the `on_message` method was called once. Thus, the `message.channel.send` method was also called only once.
Yet the bot sends 2 replies.

When repeatedly sending "lol" in chat, the number of replies sent by the bot vary.

Also at some point I changed the response message from `selber lol oO` to `What oO`. Still sometimes the bot responds with "selber lol oO", even after the process was restarted and the bot reconnected to discord.

Example:

https://imgur.com/a/4egLa9B

So I am new to python programming, and I want to apologize in advance for making some obvious mistake I just fail to see right now.

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- discord.py version:
1.1.1
- Python version:
3.7
- Operating system:
macOS 10.14.4

**Comment by MinerChAI** [comment]
1) Consider joining [support server](https://discord.gg/r3sSKJJ) for help
2) If you need commands, use the commands extension.
**Docs:** <http://discordpy.readthedocs.io/en/latest/ext/commands/api.html>

**Why should I use the commands extension?**
 - Prevents spaghetti code
 - Better performance
 - Easy handling and processing of command arguments
 - Argument type converters
 - Easy sub commands
 - Command cooldowns
 - Built-in help function
 - Easy prefix management
 - Command checks, for controlling when they're to be invoked
 - Ability to add command modules via extensions/cogs
 - Still able to do everything you can do with `Client`

**Comment by patrickjane** [comment]
Hello, thanks for your reply. I do not want to use commands, currently.

**Comment by MinerChAI** [comment]
Can't reproduce. Maybe you're running two instances of the bot.

**Comment by Rapptz** [comment]
Chances are you're running two instances of the bot. 

Check task manager or `htop`, whatever flavour you're using.

**Comment by patrickjane** [comment]
Yes indeed it was two instances. I don't know how I achieved this, but only a restart helped. After that, the messages were printed correctly.

Sorry again for the wrong alert.
