### ISSUE TITLE
Running local works just fine, running in docker causes Dispatching event command_error

### ISSUE THREAD

**Issue by MostHated** [Rapptz/discord.py#2175]
### Summary
Hey there,
    I am having an issue but I somewhat believe it might just be lack of information on the subject. I am trying to run my bot in Docker (docker-compose). Everything works just find if I run it locally on a PC or one of my server (local pc is a Ubuntu derivative OS, server is Ubuntu, docker container is also Ubuntu based) but I can't get it to work properly in the container. 

In the container, the bot loads up fine, but when I try to issue a command to it, it comes back saying the following:

```
verifier    | 2019-05-20 21:12:35,939 [DEBUG] Dispatching event socket_response
verifier    | 2019-05-20 21:12:35,940 [DEBUG] Dispatching event typing
verifier    | 2019-05-20 21:12:36,507 [DEBUG] Dispatching event socket_raw_receive
verifier    | 2019-05-20 21:12:36,508 [DEBUG] For Shard ID None: WebSocket Event:  ---- This has a bunch of info on what I sent. It's super long so I omitted it.
verifier    | 2019-05-20 21:12:36,508 [DEBUG] Dispatching event socket_response
verifier    | 2019-05-20 21:12:36,508 [DEBUG] Dispatching event message
verifier    | 2019-05-20 21:12:36,509 [DEBUG] Dispatching event command
verifier    | 2019-05-20 21:12:36,509 [DEBUG] Dispatching event command_error
```

Unfortunately, that is all it ever comes back with, too. I asked around on the Discord channel, but no one there was able to come back with any insight. They looked at my code as well as my logging setup and everything was setup the way it should be. As I mentioned, it works fine as a standalone, but I can't figure out why it's not working in the container. I had it in this container: ```FROM python:3.7.3-stretch``` which is the same version of python3 I was running on the server and PC I tested it on which worked fine. 

Part of me thought it might be because I didn't have ports exposed explicitly. I tried to see what port this used to see if I could assign it, but it changed and I didn't see a way to set it. I noticed it kept being in the 2kish range so I tried exposing 2000-2100 but it didn't seem to make a difference. Plus, the bot was able to actually connect and it looks like I did receive this ``` [DEBUG] GET https://discordapp.com/api/v7/oauth2/applications/@me with None has returned 200``` so I am guessing it might not be an actual communication issue?

Here is my Dockerfile and my docker-compose, perhaps I am missing something necessary for general functionality of the bot? 

```Dockerfile
FROM python:3.7.3-stretch

WORKDIR /app

COPY ${PWD}/Verifier /app

RUN apt-get update \
        && apt-get install -y curl apt-transport-https gnupg2 net-tools \
        && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
        && curl https://packages.microsoft.com/config/debian/9/prod.list > /etc/apt/sources.list.d/mssql-release.list \
        && apt-get update \
        && ACCEPT_EULA=Y apt-get install -y unixodbc unixodbc-dev msodbcsql17 mssql-tools software-properties-common \
        && python3 -m pip install cython \
        && python3 -m pip install lxml \
        && python3 -m pip install PyMySQL \
        && python3 -m pip install pyodbc \
        && python3 -m pip install -r requirements.txt --no-cache-dir

CMD python3 __main__.py
```
Here was the command I was attempting to run. Starting at line 143, which takes input and then is supposed to ask me for my email address and move on from there, but I send the input and then get the command error.

https://github.com/instance-id/verifier/blob/8d4b716a9fa0f5884a45e395725e9524d5326652/instance/modules/validate/validate.py#L143

So really, I guess I am just trying to see if I am doing something incorrectly, or if something about discord.py just doesn't like running in docker?
If anyone has any insight, I would greatly appreciate it.

Thanks,
-MH

- Python v3.7.3-final
- discord.py v1.1.1-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Linux 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019

**Comment by Vexs** [comment]
This isn't a connection problem at all, and discord.py itself seems to be operating normally- as seen by your logged errors, the command itself is raising an issue. This means it's being invoked properly, but errors out.

Discord.py provides tracebacks to stderr by default unless you've overriden those methods- you should figure out how to get that output from your docker container. 

The usual culprit for "code runs fine on my machine but errors out on a remote machine" is that you're running different versions of discord.py. `1.1.1` is the current version of discord.py, and is incompatible with `0.16.x` versions, and has some incompatibility with `1.0.0a`.

**Comment by MostHated** [comment]
Just for comparison, I wanted to make sure everything was similar, here were the results.

```bash
docker exec -it verifier /bin/bash
root@hpcs:/app#  python -m discord -v
- Python v3.7.3-final
- discord.py v1.1.1-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Linux 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019
root@hpcs:/app# exit
exit
```

Then from the server:
```bash
~/code/verifier # workon verifier                                                                                                                                                                            
(verifier) ------------------------------------------------------------
~/code/verifier # python -m discord -v                                                                                                                                                                       
- Python v3.7.3-final
- discord.py v1.1.1-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Linux 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019
(verifier) ------------------------------------------------------------
~/code/verifier #  
```
Then from PyCharm
```bash
(venv) ------------------------------------------------------------
~/_dev/programming/python/Verifier/Verifier/instance/modules/validate(master*) » python -m discord -v                                                                                                                                                                                                                    mosthated@mosthated-pc
- Python v3.7.3-final
- discord.py v1.1.1-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Linux 5.0.0-15-generic #16pop0-Ubuntu SMP Wed May 15 14:41:25 UTC 2019
(venv) ------------------------------------------------------------
```
I will check in the container to see what I can find, but I was running with output directly to the console as I was running the container. Everything being displayed was exactly the same info that showed up when I ran it anywhere else, minus there was an error, when elsewhere there wasn't. 


Here is an example of the output at the start of the container that comes to the console.

```
verifier    | DEBUG
verifier    | Importing MySQL configuration
verifier    | 2019-05-20 22:14:03,922 [INFO] logging in using static token
verifier    | 2019-05-20 22:14:04,112 [DEBUG] GET https://discordapp.com/api/v7/users/@me with None has returned 200
verifier    | 2019-05-20 22:14:04,113 [DEBUG] GET https://discordapp.com/api/v7/users/@me has received {'username': 'instance.id', 'verified': True, 'locale': 'en-US', 'mfa_enabled': False, 'bot': True, 'id': 'XXXXXXXXXXXXXXXXXXXXXX', 'flags': 0, 'avatar': None, 'discriminator': '1736', 'email': None}
verifier    | 2019-05-20 22:14:04,124 [DEBUG] GET https://discordapp.com/api/v7/gateway with None has returned 200
verifier    | 2019-05-20 22:14:04,125 [DEBUG] GET https://discordapp.com/api/v7/gateway has received {'url': 'wss://gateway.discord.gg'}
verifier    | 2019-05-20 22:14:04,216 [INFO] Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
verifier    | 2019-05-20 22:14:04,218 [DEBUG] Dispatching event socket_raw_receive
verifier    | 2019-05-20 22:14:04,219 [DEBUG] For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 10, 'd': {'heartbeat_interval': 41250, '_trace': ['gateway-prd-main-cpgv']}}
verifier    | 2019-05-20 22:14:04,220 [DEBUG] Dispatching event socket_response
verifier    | 2019-05-20 22:14:04,221 [DEBUG] Dispatching event socket_raw_send
verifier    | 2019-05-20 22:14:04,223 [DEBUG] Dispatching event socket_raw_send
verifier    | 2019-05-20 22:14:04,225 [INFO] Shard ID None has sent the IDENTIFY payload.
verifier    | 2019-05-20 22:14:04,248 [DEBUG] Dispatching event socket_raw_receive
verifier    | 2019-05-20 22:14:04,250 [DEBUG] For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
verifier    | 2019-05-20 22:14:04,251 [DEBUG] Dispatching event socket_response
verifier    | 2019-05-20 22:14:04,311 [DEBUG] Dispatching event socket_raw_receive
verifier    | 2019-05-20 22:14:04,318 [DEBUG] For Shard ID None: WebSocket Event: {'t': 'GUILD_CREATE', 's': 2, 'op': 0, 'd': {'voice_states': [], 'verification_level': 0, 'vanity_url_code': None, 'unavailable': False, ----------- This was extremely long.
verifier    | 2019-05-20 22:14:04,319 [DEBUG] Dispatching event socket_response
verifier    | 2019-05-20 22:14:04,324 [DEBUG] Dispatching event guild_available
verifier    | 2019-05-20 22:14:06,319 [DEBUG] Dispatching event ready
verifier    | Logged in as
verifier    | my_account
verifier    | XXXXXXXXXXXXXXXXX
verifier    | ------
verifier    | https://discordapp.com/oauth2/authorize?client_id=XXXXXXXXXXXXXXXXX&scope=bot
verifier    | 2019-05-20 22:14:06,369 [DEBUG] GET https://discordapp.com/api/v7/oauth2/applications/@me with None has returned 200
verifier    | 2019-05-20 22:14:06,370 [DEBUG] GET https://discordapp.com/api/v7/oauth2/applications/@me has received {'description': ---- etc

```

**Comment by Vexs** [comment]
Then, yeah, looks like this is just an issue with your code. 
`verifier    | 2019-05-20 22:14:10,321 [DEBUG] Dispatching event command_error`
`command_error` is the event that errors in commands raise to. By default, it will print the traceback to stderr- ensure you're not eating your error if you've overriden this method.

I really can't comment further without code.

**Comment by MostHated** [comment]
I noticed that the code on the page didn't 100% reflect my active code I was working with. I updated it which removed the logging from within the cog itself, there is only the initial logger in __main__.py which is watching 'discord' as recommended by the folks in the Discord channel, which was how I had been testing it locally anyways. Just wanted to make sure anyone else saw the same thing I was actually working with, which is this from master.

https://github.com/instance-id/verifier/blob/master/instance/modules/validate/validate.py

**Comment by Gorialis** [comment]
I have a set of discord.py-oriented docker images under the [`gorialis/discord.py`](https://hub.docker.com/r/gorialis/discord.py/) tag, which I have a mandated automatic CI test suite on that ensures complete functionality of the image before it is uploaded. I use these images with docker-compose myself in production, and I haven't experienced issues like this.

I can't see any immediate reason why your docker setup would fail to work - especially considering it is basing on the official image and doesn't appear to do anything out of the ordinary to the distribution. For this reason, I don't think this issue lies in your docker configuration itself.

I would first write a command error handler, since in both logs it is triggering, likely with a useful exception and traceback that would indicate what is failing, and why.

Other than that, my best guess would be either that your docker daemon is not installed correctly or there is some kind of permissions issue (maybe the container isn't allowed to use certain ports, protocols or devices?)

**Comment by MostHated** [comment]
What you mentioned got me wondering, so to test I extracted the image and moved it over to one of my other servers which is used exclusively to run containers as I just wanted to rule out the setup/server itself as being part of the problem. I ended up with the same result, so at least I can check that off the list.
