### ISSUE TITLE
Make the get methods do int(id) 

### ISSUE THREAD

**Issue by claderoki** [Rapptz/discord.py#2177]
### The Problem
The problem is that when (for example) a method like Client.get_guild gets called, when the parameter guild_id passed is a string, it will always return None, without any errors or anything.

For example, in my case, I use Json to store data, in Json you cannot have an int as a key value.

### The Ideal Solution
A solution to this could be a simple check 

```py
if not isinstance(guild_id, int):
    if guild_id.isdigit():
        guild_id = int(guild_id)
    else:
        raise TypeError("This is not a number!")
```

**Comment by Rapptz** [comment]
This is intended. If you want to cast then you can cast it yourself. These methods accept a certain type and I don't like most forms of coercion. Sometimes string coercion is fine (e.g. in formatting or the like) but I don't particularly want to do int coercion which can raise a different error. 

Just do it yourself.

**Comment by claderoki** [comment]
I understand. Would it be possible to do a check whether the argument is actually an int, and raise an error if it is not?
