### ISSUE TITLE
Write docs on getting bots to get streaming status.

### ISSUE THREAD

**Issue by AraHaan** [Rapptz/discord.py#218]
I think there needs to be docs for this so people could do such thing. I also think that ``type=`` and ``url=`` needs to be in ``change_status`` as well to help simplify this too.

**Comment by TickerOfTime** [comment]
Just create a Game with type set to 1.

`await client.change_status(game=discord.Game(name="Fun Game", url="twitch.tv/streamer", type=1))`

[client.change_status](http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.change_status)
[Game](http://discordpy.readthedocs.io/en/latest/api.html#discord.Game)

**Comment by Stevyb0t** [comment]
Now discord is using `client.change_presence` instead of `client.change_status`
