### ISSUE TITLE
Guild boosted status variable

### ISSUE THREAD

**Issue by Ristellise** [Rapptz/discord.py#2184]
### The Problem

As of now, there isn't anyway to tell if a guild has a boosted status or not.

### The Ideal Solution

Implement 3 variables/properties in the `Guild` class which are:  
`boost_level`:  
Has a range from 0 to 3. where 0 means there isnt any boost applied to the Server/Guild, while 3 means the highest (level 3) boost is applied.  
`boost_duration`:
This can be in timedelta or in seconds (which ever is easier to do). defining how long the boost is going to last.  
`boost_count`:  
The number of boosts in total applied to the Server/Guild at one time.

### The Current Solution

No implementation at all.

### Summary

Implement 3 variables in `Guild` Class, `boost_level`, `boost_duration`, `boost_count`.

### Notes

Discord marks this as experimental. Some Servers/Guilds may not show this option at all to users. In that case, its preferable to set `boost_level` to 0.

Relevant blog about Server/Guild boosting: https://support.discordapp.com/hc/en-us/articles/360028038352-Server-Boosting-

**Comment by Vexs** [comment]
This is currently coming in the (premium-guilds branch)[https://github.com/Rapptz/discord.py/tree/premium-guilds]. It's missing a couple bits still, plus I'm not sure if discord has completely settled on what this includes.

**Comment by OrangutanGaming** [comment]
Most of the details are practically finalised but in case they *do* change, it's best to not add things like that to the library when they could change and become inaccurate
