### ISSUE TITLE
Allow bot to always call typing 

### ISSUE THREAD

**Issue by PokestarFan** [Rapptz/discord.py#2187]
### The Problem
I want to be able to have my bot call typing() when sending data through a channel, so I tried to create a subclass of  TextChannel and make discord.TextChannel equal to my TextChannel. However, I do not think that did anything.

### The Ideal Solution

Every time send gets called in a channel, [bot name] is typing... shows up

### The Current Solution
Override TextChannel's send and edit methods and call typing() and then the parent class's send/edit

Code:
```python
class TypingSendChannel(discord.TextChannel):
    async def edit(self, *, reason=None, **options):
        async with self.typing():
            return await super().edit(reason=reason, **options)

    async def send(self, content=None, *, tts=False, embed=None, file=None, files=None, delete_after=None, nonce=None):
        async with self.typing():
            return await super().send(content, tts=tts, embed=embed, file=file, files=files, delete_after=delete_after,
                                      nonce=nonce)

discord.TextChannel = TypingSendChannel # this could go very badly
```

**Comment by khazhyk** [comment]
typing notifications are only rendered until the next message is received (on the client). If you send typing then immediately send a message, both will arrive at the same time so the typing notification will never show up.

The point of the `typing` context manager was as ease of use for long-running operations e.g.

```py
async with ctx.typing():
  await long_operation
await ctx.send()
```
will send typing notifications in a loop in a background task until `long_operation` is done

**Comment by IngeniousCoder** [comment]
[bot name] is typing will disappear once something by the bot is sent. If you trigger typing and then immediately make the bot send, what is the point? The typing will most probably not even show up.

**Comment by Rapptz** [comment]
This feature request won't be implemented since there is already a context manager that does this and the benefits for it are too slim to add this niche use case into the library proper.
