### ISSUE TITLE
Why can't I get a Reactions from Channel.pins ?

### ISSUE THREAD

**Issue by 1ntegrale9** [Rapptz/discord.py#2189]
# tried

I tried the following code.

```python
# get channel.pins() to reactions directly
messages = await channel.pins()
for msg in messages:
    reaction_total = sum(reaction.count for reaction in msg.reactions)
    print(reaction_total) # always 0 !
```

```python
# relay the message ID to get channel.pins() to reactions 
messages = [await channel.fetch_message(m.id) for m in await channel.pins()]
for msg in messages:
    reaction_total = sum(reaction.count for reaction in msg.reactions)
    print(reaction_total) # number of reactions
```

# examined

I read the following code and API reference, but I did not understand the cause.
Both stated that they would get "Message Object".

### abc.Messageable.pins
https://github.com/Rapptz/discord.py/blob/fc5a2936dd9456f1489dc1125c12448a2af23e15/discord/abc.py#L891-L905

### http.pins_from
https://github.com/Rapptz/discord.py/blob/fc5a2936dd9456f1489dc1125c12448a2af23e15/discord/http.py#L433-L434

### get-pinned-messages (discord api)
https://discordapp.com/developers/docs/resources/channel#get-pinned-messages

### abc.Messageable.fetch_message
https://github.com/Rapptz/discord.py/blob/fc5a2936dd9456f1489dc1125c12448a2af23e15/discord/abc.py#L860-L889

### http.get_message
https://github.com/Rapptz/discord.py/blob/fc5a2936dd9456f1489dc1125c12448a2af23e15/discord/http.py#L407-L409

### get-channel-message (discord api)
https://discordapp.com/developers/docs/resources/channel#get-channel-message

**Comment by Rapptz** [comment]
The API's returned JSON does not have the `reactions` key filled up. This is an issue with Discord not with discord.py, unfortunately.

**Comment by 1ntegrale9** [comment]
Thank you for the quick response !
