### ISSUE TITLE
The command won't work.

### ISSUE THREAD

**Issue by 1003lul** [Rapptz/discord.py#2196]
### Summary

Me and my friend tries to code our bot but we keep getting this error message.
### Expected Results

We was hoping that the command will work but unexpectedly, it didn't.
### Actual Results

discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'Bot' object has no attribute 'message'

### Checklist

- [x] I have searched the open issues for duplicates.
- [ ] I have shown the entire traceback, if possible.
- [ ] I have removed my token from display, if visible.

### System Information

- discord.py version: 1.2.0a
- Python version: 3.7.3
- Operating system: Windows 10 OS

**Comment by AXVin** [comment]
1. You are required to complete all the steps in the check list
2. This question is best suited for the official support server. Please ask it there https://discord.gg/r3sSKJJ

**Comment by Harmon758** [comment]
As the error says, [Bot](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#bot) does not have a `message` attribute. It does not make sense for it to.
Without a full traceback and the relevant code, it's unclear what exactly you're attempting to do and it's difficult to help you.

However, GitHub issues for this repository should be used to report issues with the library, which this does not seem to be.
For further help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README also links.
