### ISSUE TITLE
User game somehow got set to empty game?

### ISSUE THREAD

**Issue by khazhyk** [Rapptz/discord.py#221]
Saw a user with their game set to a Game with name=None, url=None, type=None, which was causing errors due to `__str__` returning None. Not 100% sure the cause, I don't have relevant websocket info.

My hunch is if the game is set to {} or something like that.

Yup,

```
bot.change_status(game=discord.Game(name={}))
```

This can trigger this bug reliably.

wew lad

```
{'t': 'PRESENCE_UPDATE', 's': 967, 'op': 0, 'd': {'guild_id': '137792044671303680', 'status': 'online', 'game': {'name': None}, 'user': {'id': '109379894718234624'}, 'nick': None, 'roles': ['138735469084147713']}}
```

**Comment by GusCaplan** [comment]
I would say this is a feature :)

**Comment by khazhyk** [comment]
This is still pretty prevalent. Could change Game.__str__ to handle name being None (currently will get angry since it returns None), also could treat game existing, but name === null to set game to None when parsing the member update, as I believe this is how the client treats this weirdness

`meval sum(bool(m.game and m.game.name is None) for m in bot.get_all_members())
(ﾉ◕ヮ◕)ﾉ✧･ﾟ*✧spoo.py✧*･ﾟ✧ヽ(◕ヮ◕)ﾉBOT - Today at 10:23 PM
['13', '17', '18', '11', '114', '11', '21', '26', '17', '10']

**Comment by Pandentia** [comment]
I remember `discord.Game(name=None)` also being able to cause this reliably (to other clients seeing the change).

**Comment by khazhyk** [comment]
Discord has *quality* data:

```
sum(bool(m.game and m.game.name is None) for m in bot.get_all_members())
['20', '18', '16', '19', '11', '23', '7', '11', '20', '26']

sum(bool(m.game and m.game.name == {}) for m in bot.get_all_members())
['2216', '2335', '2244', '2280', '2270', '2281', '2212', '2253', '2311', '2292']

sum(bool(m.game and m.game.name) for m in bot.get_all_members())
['19090', '22133', '19941', '20925', '21258', '19876', '17267', '18247', '20906', '21428']
```

The top two show up as not playing any game on Desktop, and "playing null" on mobile.

**Comment by Rapptz** [comment]
I guess this can be closed now.

Thanks Discord.
