### ISSUE TITLE
Close old pull requests?

### ISSUE THREAD

**Issue by Bluenix2** [Rapptz/discord.py#2210]
Currently we have a few old pull requests that wants to merge into the async branch, these should be closed. We also have some quite old pull requests, shouldn't these have been merged or closed yet?
The pull requests that want to merge into the async branch are from what i could find: #757, #856, #882, #1081, #1871

**Comment by NCPlayz** [comment]
This sort of ties into this... Some Pull Requests were auto-closed when the `rewrite` branch was closed. There are some such as #1972 which was officially approved, but was not reopened. Would it mean that the author would have to create a new Pull Request, or someone else can propose it again?

**Comment by BluePhoenixGame** [comment]
Can't they just be reopened and changed to master? I feel like the author should do that.

**Comment by numbermaniac** [comment]
If the repository owner (in this case Rapptz) closes a PR, the author of the PR cannot re-open it.
