### ISSUE TITLE
Broaden scope of ExtensionFailed

### ISSUE THREAD

**Issue by Travus** [Rapptz/discord.py#2211]
### The Problem

Currently, when you load an extension with bot.load_extension, the ExtensionFailed exception is given if an error occurs inside the setup entrypoint. When something outside of the setup entrypoint encounters an error, like some code in the global scope, the error that is encountered is raised instead.

Additionally, if an ImportError is raised during the loading process of an extension, the ExtensionNotFound error is given by bot.load_extension, despite the fact the extension was in fact found and only ran into an error. I'm not sure if this can actually be fixed since I believe the absence of a module is also signaled by an ImportError so both would look the same to the library, but I can't be sure.

Edit: I did some more research into this after waking up, and as suspected is the current way the library detects ExtensionNotFound just going by importlib ImportErrors so it currently cannot tell the difference.

### The Ideal Solution

I would like for the ExtensionFailed exception to be called even if the extension encounters an error outside of the setup entrypoint during loading, and if at all possible even if the error encountered is an ImportError. This way you can just listen for the ExtensionFailed exception in order to report back to users that the extension they tried to load failed to execute properly. (And you don't wrongly tell them it doesn't exist because the extension has incorrect imports.)

### The Current Solution

Add a catchall after loading exceptions that reports back to the user when any undefined exception is raised by bot.load_extension. And check if the file is present manually instead of using ExceptionNotFound.

**Comment by bmintz** [comment]
Actually it is possible to detect if a module is importable without executing it, according to the [importlib docs](https://docs.python.org/3.7/library/importlib.html#checking-if-a-module-can-be-imported)

**Comment by bmintz** [comment]
I made a PR which does the opposite of this issue: #2244
