### ISSUE TITLE
Error message with on_message event

### ISSUE THREAD

**Issue by mjcarter95** [Rapptz/discord.py#2217]
### Summary

Receiving an exception message in the "on_message" event inside a cog.

### Reproduction Steps

I have the following cog

`import discord
from discord.ext import commands
from utils.Credits import Credits

class CreditsController(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        self.credits = Credits()
    
    @commands.Cog.listener()
    async def on_message(self, message):
        self.credits.update(message.author.id, 1)

def setup(bot):
    bot.add_cog(CreditsController(bot))`

where "Credits" is a class that handles the respective CRUD operations in the database. The exception occurs whenever a user sends a message.

### Expected Results
User credits would be updated with no exception.

### Actual Results
User credits are updated but an exception message also occurs.

`Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\matth\Desktop\discord_bot\venv\lib\site-packages\discord\client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\matth\Desktop\discord_bot\venv\lib\site-packages\discord\ext\commands\bot.py", line 901, in on_message
    await self.process_commands(message)
  File "C:\Users\matth\Desktop\discord_bot\venv\lib\site-packages\discord\ext\commands\bot.py", line 897, in process_commands
    ctx = await self.get_context(message)
  File "C:\Users\matth\Desktop\discord_bot\venv\lib\site-packages\discord\ext\commands\bot.py", line 813, in get_context
    prefix = await self.get_prefix(message)
  File "C:\Users\matth\Desktop\discord_bot\venv\lib\site-packages\discord\ext\commands\bot.py", line 758, in get_prefix
    ret = await discord.utils.maybe_coroutine(prefix, self, message)
  File "C:\Users\matth\Desktop\discord_bot\venv\lib\site-packages\discord\utils.py", line 311, in maybe_coroutine
    value = f(*args, **kwargs)`

### System Information
Python 3.7
Discord.py 1.2.2

**Comment by Vexs** [comment]
The issue doesn't seem to have anything to do with your cog, unless that traceback is sorely misleading. It appears to be an issue with your prefix?
Either way, can't really diagnose this with presented information- no code, and I'm pretty sure you copied half the traceback. 

Would be nice if you could fix the formatting in your issue for the future however.

**Comment by TheRockettek** [comment]
Seems half of the traceback is missing

**Comment by mjcarter95** [comment]
> The issue doesn't seem to have anything to do with your cog, unless that traceback is sorely misleading. It appears to be an issue with your prefix?
> Either way, can't really diagnose this with presented information- no code, and I'm pretty sure you copied half the traceback.
> 
> Would be nice if you could fix the formatting in your issue for the future however.

Not sure why the formatting was messed up; tried to correct it a few times but to no avail. Issue was with prefixes, thank you.
