### ISSUE TITLE
Client.private_channels isn't returning all private channels

### ISSUE THREAD

**Issue by computer2467** [Rapptz/discord.py#2227]
### Summary

Title says it all. I know that there are more private channels because member.history() returns on members other than what the printout says.

### Reproduction Steps

(i'm running this in the on_message event and it fires when a certain phrase is dm'd to the bot)
```python
print(self.private_channels)
```

### Expected Results
prints:
[(list of all groups and dms it's in)]

### Actual Results
prints:
[(only the dm that the command was sent in)]

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.7.2-final
- discord.py v1.2.2-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Windows 10 10.0.17763

**Comment by khazhyk** [comment]
This is a Discord limitation and there is no way around it, bots have their DM channels aggressively closed by Discord (which removes them from private_channels)

member.history() will re-open the DM channel, even if it's not present in private_channels

**Comment by computer2467** [comment]
>This is a Discord limitation and there is no way around it, bots have their DM channels aggressively closed by Discord (which removes them from private_channels) ...

@khazhyk Hmm, guess I’ll just use a file and add the ID of anybody who dms the bot to the file, and just read the file and get every conversation from there. thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
