### ISSUE TITLE
message.channel returns object

### ISSUE THREAD

**Issue by synbitz** [Rapptz/discord.py#223]
Might be stupid but ... I'm trying to get the channel name  and get 
<discord.channel.Channel object at 0x7f6c609196d8>

```
@client.event
def on_message(message):
    print(str(message.channel))
```

This way I can not distinguish between channels, any help? 
python3.5

**Comment by alfalfascout** [comment]
try message.channel.name

**Comment by Rapptz** [comment]
To distinguish between channels use its unique ID. `message.channel.id`. As per the documentation, `message.channel` can be an `Object` if unordered messages happen.

**Comment by synbitz** [comment]
thanks
