### ISSUE TITLE
Why there is no Docs for the rewrite version?

### ISSUE THREAD

**Issue by Lukas562Dev** [Rapptz/discord.py#2233]
Generally speaking support questions are better answered in our Discord server. The response rate is faster and many people are willing to help. If you **really** feel like the question belongs here then feel free to delete this text and continue on. **Please do not open issues about asking how to implement a feature in your bot, these will be instantly closed.**

Our support servers can be found here:

Official server: https://discord.gg/r3sSKJJ
Discord API: https://discord.gg/discord-api

**Comment by Rapptz** [comment]
The rewrite branch is no more. It's just regular ol' discord.py now. The documentation is located in https://discordpy.readthedocs.io/en/latest/
