### ISSUE TITLE
Support for encoding in higher than 128kbps audio

### ISSUE THREAD

**Issue by s0hv** [Rapptz/discord.py#2235]
### The Problem

It would seem that audio is encoded only up to 128kbps bitrate. Now that server boosting is a thing and bitrates have been boosted all the way up to 384kbps it would be nice if bots could benefit from that. 

### The Ideal Solution

Editing the `opus.py` file to allow for higher bitrate. I don't know if changing the function [set_bitrate](https://github.com/Rapptz/discord.py/blob/master/discord/opus.py#L242) to accept higher than 128 bitrate is enough since I'm not all that familiar with how this all works
### The Current Solution

Don't really know any

### Summary

Support higher quality encoding for opus

**Comment by zomatree** [comment]
#2232

**Comment by s0hv** [comment]
Checking pull requests didn't come to my mind so I'm just gonna close this since a fix exists elsewhere
