### ISSUE TITLE
"Listen to bots" flag

### ISSUE THREAD

**Issue by mdiller** [Rapptz/discord.py#2238]
### The Problem

I'm working on a testing system for my bot and it would be useful if my bot could treat other bots as an actual user, instead of skipping any command processing of messages sent by other bots

### The Ideal Solution

Seems like it would be pretty straightforward to do, by just adding another condition to this statement in bot.process_commands:
```
if message.author.bot:
	return
```
The only part I'm not sure about is where the flag should be passed in, and what it should be called.

### The Current Solution

Modifying the code in the discord.py library before running your bot.

### Summary

A flag that lets a bot listen to other bots

**Comment by Phxntxm** [comment]
All you have to do is subclass the bot, override `process_commands`, and don't include that if statement.

**Comment by dyc3** [comment]
Ok, but wouldn't it be super trivial and convenient to include an option for this?
