### ISSUE TITLE
Bug with managed roles

### ISSUE THREAD

**Issue by BluePhoenixGame** [Rapptz/discord.py#2242]
### Summary

Currently there's some weird issues with on_guild_update.
### Reproduction Steps
A:
1. So start out with this script
```python
from discord.ext import commands

import time

class MyBot(commands.Bot):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    async def on_guild_update(self, before, after):
        print("GUILD UPDATE", after.roles)

    async def on_member_join(self, member):
        print("MEMBER JOIN", member.guild.roles)

    async def on_message(self, message):
        print("MESSAGE", message.guild.roles)
bot = MyBot(command_prefix="?")
bot.run("GetYourOwnToKeN")
```
2. Run it
3. Then invite a bot and give it some permission so that a managed role will get created.

B:
1. Start out with script above.
2. Run it
3. Invite your friend.
### Expected Results

A:
I expected to see three prints because a new role got created and a new member, also a welcome message was sent.
```
MEMBER JOIN [<Role id=519195377547870209 name='@everyone'>, <Role id=592123206710591503 name='Nadeko'>, <Role id=592121559544758278 name='Discot'>]
GUILD UPDATE [<Role id=519195377547870209 name='@everyone'>, <Role id=592123206710591503 name='Nadeko'>, <Role id=592121559544758278 name='Discot'>]
MESSAGE [<Role id=519195377547870209 name='@everyone'>, <Role id=592123206710591503 name='Nadeko'>, <Role id=592121559544758278 name='Discot'>]
```

B:
I expected to see three prints because the invite got another use, and the new member. Plus the welcome message.
Same prints as above.
### Actual Results

```
MEMBER JOIN [<Role id=519195377547870209 name='@everyone'>, <Role id=592121559544758278 name='Discot'>]
MESSAGE [<Role id=519195377547870209 name='@everyone'>, <Role id=592123206710591503 name='Nadeko'>, <Role id=592121559544758278 name='Discot'>]
```
on_guild_update should've been called. And on_member_join should have the up to date guild object. I don't know if it is by design to suppress the change in invite uses, maybe it isn't even possible to call on_guild_update when that happens.

### System Information
```
- Python v3.7.3-final
- discord.py v1.2.2-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Linux 5.0.0-17-generic #18-Ubuntu SMP Tue Jun 4 15:34:08 UTC 2019
```

**Comment by Rapptz** [comment]
Your expectations are wrong.

I'm pretty sure what happens during this flow is:

- GUILD_MEMBER_ADD aka `on_member_join` (bot joins)
- GUILD_ROLE_CREATE aka `on_guild_role_create` (managed role is created)
- GUILD_MEMBER_UPDATE aka `on_member_update` (manage role is automatically assigned to bot)

I don't see why you think the guild object is updated.

**Comment by BluePhoenixGame** [comment]
Oh, i was looking at the wrong event. In the documentation on `on_guild_update` it says 
```
Called when a Guild updates, for example:
Changed name
Changed AFK channel
Changed AFK timeout
etc
``` 
and so i assumed this got called on every change in the guild like roles and channels etc. But yeah, it's more split up into several events.
