### ISSUE TITLE
Can't send a DM to someone with the bot.

### ISSUE THREAD

**Issue by RogueSoldier777** [Rapptz/discord.py#2248]
I am trying to send a DM to a user by saying `
@bot.command()
async def dm(ctx):
    await bot.send_message(message.author, message.content)`

That didn't work and the error I got was 'Instance of Bot has no 'send_message' member'

**Comment by RogueSoldier777** [comment]
#How to Direct Message someone?

**Comment by Phxntxm** [comment]
The code you are using is of a version (0.16.12) that is no longer supported. If you need help migrating, visit the migration guide: https://discordpy.readthedocs.io/en/latest/migrating.html

If you need more help consider joining the official [Discord server](https://discord.gg/r3sSKJJ).

**Comment by Harmon758** [comment]
For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
