### ISSUE TITLE
A Member.has_role method for speeded up checking if a member has a role

### ISSUE THREAD

**Issue by kb-1000** [Rapptz/discord.py#2250]
### The Problem

I want to check whether a member has a role. This is currently a little bit slow, as it involves accessing the `roles` property which could call `Guild.get_role` many times and using `list.__contains__` for the actual check. This would become faster.

### The Ideal Solution

A `Member.has_role` method that accepts integer snowflakes as well as `Role` instances would be nice. It would then use SnowflakeList.has.

### The Current Solution

I would have to get all roles of the member, which involves many dictionary accesses, and then many calls to `Role.__eq__`.

### Summary

Speedup for finding out if a member has a role

**Comment by numbermaniac** [comment]
#1762 
#2243

**Comment by xoxfaby** [comment]
Curious, have you actually ever run into a situation where `member in role.members` or `role in member.roles` was too slow for you?

**Comment by kb-1000** [comment]
Not yet, but if I get really much members to check at once I will.

**Comment by Rapptz** [comment]
This has been implemented in v2.0 using `Member.get_role`.
