### ISSUE TITLE
[Commands] Using a typing.Optional[] converter in a commands.Greedy[] one

### ISSUE THREAD

**Issue by jschmitz3141** [Rapptz/discord.py#2253]
### Summary

I tried making a command with an argument like
`cmd(ctx, arg: commands.Greedy[typing.Optional[int]])`
(actual command and types not shown, but they work on their own)
However, the bot gets stuck in an infinite loop in Command._transform_greedy_pos().

### Reproduction Steps

I had a typing.optional[] type in a command's commands.Greedy[] converter. Similar to
`cmd(ctx, arg: commands.Greedy[typing.Optional[int]])`

### Expected Results

For this example, if I had a command like
`>command str 1 2 str 3`
arg would be passed a value of
`[None, 1, 2, None, 3]`
since the strings would get converted to `None` under the typing.Optional converter

### Actual Results

The bot is stuck in an infinite loop between lines 460-476 of core.py, in Command._transform_greedy_pos() at the loop 'while not view.eof'

### Checklist

- [x] I have searched the open issues for duplicates.
- [ ] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

```
- Python v3.6.8-final
- discord.py v1.2.3-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Windows 10 10.0.17134
```

**Comment by Rapptz** [comment]
This should probably just error out since it doesn't make sense.
