### ISSUE TITLE
except still not catching errors in bot.run()

### ISSUE THREAD

**Issue by EEKIM10** [Rapptz/discord.py#2256]
### Summary

still will not catch errors on bare try/except.

### Reproduction Steps

```py
try:
    bot.run(fake_token)
except:
    print("M how bout no")
```
### Expected Results

console should print "M how bout no"

### Actual Results
```bash
Task exception was never retrieved
future: <Task finished coro=<Client.run.<locals>.runner() done, defined at C:\Users\---\AppData\Roaming\Python\Python37\site-packages\discord\client.py:577> exception=LoginFailure('Improper token has been passed.')>
Traceback (most recent call last):
  File "C:\Users\--=-mue\AppData\Roaming\Python\Python37\site-packages\discord\http.py", line 258, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\---\AppData\Roaming\Python\Python37\site-packages\discord\http.py", line 222, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 401 UNAUTHORIZED (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\---\AppData\Roaming\Python\Python37\site-packages\discord\client.py", line 579, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\---\AppData\Roaming\Python\Python37\site-packages\discord\client.py", line 542, in start
    await self.login(*args, bot=bot)
  File "C:\Users\---\AppData\Roaming\Python\Python37\site-packages\discord\client.py", line 400, in login
    await self.http.static_login(token, bot=bot)
  File "C:\Users\---\AppData\Roaming\Python\Python37\site-packages\discord\http.py", line 262, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
```

### Checklist

- [ x] I have searched the open issues for duplicates.
- [ x] I have shown the entire traceback, if possible.
- [ x] I have removed my token from display, if visible.

### System Information
d.py version: 1.2.3
py version: 3.7.3
os: linux

**Comment by Phxntxm** [comment]
```
┌─[dhess]─[~]
└──╼ python test.py 
caught
┌─[dhess]─[~]
└──╼ cat test.py 
from discord.ext import commands

bot = commands.Bot(command_prefix="!")

try:
    bot.run("test")
except:
    print("caught")
┌──[dhess]─[~]
└──╼ python -m discord --version
- Python v3.7.1-final
- discord.py v1.2.3-final
```

Make sure you actually are updated to 1.2.3, that is when it was fixed, and as you can see from my test above it worked perfectly fine.

**Comment by EEKIM10** [comment]
im 100% updated. ill run the update command again to make absolutely sure

**Comment by EricGPTI** [comment]
When I run a simple exemple or other code, include my own code, a same error is shown:

Code:
```
import discord
import asyncio

class MyClient(discord.Client):
    async def on_ready(self):
        print('Logged on as', self.user)

    async def on_message(self, message):
        # don't respond to ourselves
        if message.author == self.user:
            return

        if message.content == 'ping':
            await message.channel.send('pong')

client = MyClient()
client.run('MyCode')
```


   raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.

I get authorization token with developer mode of firefox. If I run with bot token the application run normaly.

**Comment by Phxntxm** [comment]
Your issue is not related to the OP's issue. First, questions regarding usage of the library and not issues in the library itself should typically be put in the [official discord server]( https://discord.gg/r3sSKJJ)

Second, selfbots are [banned, see the link](https://support.discordapp.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-) so you should not use your own account unless you want to risk getting banned.

Third, if you ignore this and want to use a use account, then you need to pass `bot=False` into the `.run` call...[see this link](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.login)
