### ISSUE TITLE
change_nickname requires 'nickname'

### ISSUE THREAD

**Issue by FukujiMihoko** [Rapptz/discord.py#227]
In the docs (and in the comments inside client.py), the nickname argument in change_nickname are listed as optional, but nickname doesn't have a default value to it so it can be optional. Should be as simple as changing the method's declaration @discord/client.py L1558 to the following, so it complies with the documentation.
`def change_nickname(self, member, nickname=None):`

**Comment by khazhyk** [comment]
I think Optional[type] is intended to mean type or None. It is used this way in multiple areas. In any case, the method signature seems intentional.

**Comment by FukujiMihoko** [comment]
Oh, okay. Just not something straightforward as it seems. Thanks for the fast answer!
