### ISSUE TITLE
Client.application_info().owner returns Team Info and not actual owner info thus, causing `Client.is_owner()` to work incorrectly

### ISSUE THREAD

**Issue by Dyleee** [Rapptz/discord.py#2271]
### Summary

Client.application_info().owner returns Team Info and not actual owner info thus, causing `Client.is_owner()` to work incorrectly for Bots or applications under Teams.

### Reproduction Steps
Reproduction Steps:

- Put a Bot under a Team
- Try to retrieve `application_info()`
- Use `Client.is_owner(user)` and it will return False despite using the owner.

### Expected Results
`Client.is_owner(user)` should return True if `user` is the bot owner.

### Actual Results
`Client.is_owner(user)` returns False because it's `owner` object is a Team Info and not a User

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
In #2239 and the subsequent fixes that I've done in the master branch support teams. Since you didn't follow the format properly I don't know what version you refer to, but as far as I'm concerned team support is working just fine on the master branch.
