### ISSUE TITLE
Integrate a scheduling option

### ISSUE THREAD

**Issue by mvettosi** [Rapptz/discord.py#2273]
I have developed few bots using discord.py so far and one feature that almost all of them had in common was for the bot to proactively do something periodically or on specific times of the week.

To implement that, my favourite solution is derived from this old template: https://github.com/agubelu/discord-bot-template.

I think it would be really useful if discord.py could provide a class to extend, for example `ScheduledEvent`, that would work exactly like when subclassing the `Cog` class (extending it, adding it to the bot), while being configured in its `__init__` method.

**Comment by Devoxin** [comment]
I believe the library already has something similar to what you're looking for called `tasks` provided under `discord.ext`. I'd provide a link if I wasnt on mobile but a quick search in the docs should lead you right to it

**Comment by MinerChAI** [comment]
https://discordpy.readthedocs.io/en/latest/ext/tasks/index.html# here you are

**Comment by mvettosi** [comment]
Holy cow, how could I miss that?
I'll give it a go, thanks =D
