### ISSUE TITLE
Option to populate message cache?

### ISSUE THREAD

**Issue by Heath123** [Rapptz/discord.py#2278]
### The Problem

I'm making something that allows users to access the recent message history of a channel, but I have to do an "await" call to "channel.history" every time, causing unnecessary latency. 

### The Ideal Solution

I would be able to use a function such as "channel.populate_cache(limit=50)" to populate the message cache with channel history and avoid API calls.

### The Current Solution

Either use API calls (slow) or rewrite the message cache code (hard).

### Summary

Please add a function such as "channel.populate_cache(limit=50)" to populate the message cache with channel history and avoid API calls.

**Comment by Vexs** [comment]
You can access the existing message cache as client.cached_messages, which by default is the last 5000 messages seen- which you can trivially filter. If this is insufficient, a more reliable option is building a dict of {channel:deque} and maintaining your own message cache in on_message.

With these two easy methods out of the way, I'm not really sure what your proposed method would do at all. To populate a message cache you need to either do a history call or wait for message events- and what cache does this proposed method populate?

**Comment by Heath123** [comment]
Yes but after a restart, the cache will be empty. It would do a history call.

**Comment by TheRockettek** [comment]
This sounds bad.

**Comment by Heath123** [comment]
Why?

**Comment by Heath123** [comment]
Why?

**Comment by Heath123** [comment]
How do you suggest I do it?

**Comment by TheRockettek** [comment]
This is github, you should instead join the discord at https://discord.gg/r3sSKJJ if you want to discuss it.

**Comment by Heath123** [comment]
No, I'm saying that there's no good way to do it as the message cache is read-only

**Comment by Rapptz** [comment]
Your own cache is probably better for this since the message cache is not designed to be filled by users (nor will it be at this time). It's not difficult to do your own cache, it is one line of code in 3.6+:

```py
cache = {m.id: m async for m in channel.history(limit=100)}
```
