### ISSUE TITLE
Is there a way to use commands in class?

### ISSUE THREAD

**Issue by philliphemleb** [Rapptz/discord.py#2279]
Hello,

I just started with the library but I dont know how to use commands in a class.
I just implemented commands from discord.ext, but I can´t inherit my class from commands like the example on the startpage does.

So how can I do that?

Thanks for helping!

**Comment by zomatree** [comment]
in a cog you would use `@commands.command()` in a bot subclass you cant

**Comment by philliphemleb** [comment]
Is there an example?
Do I need to make a main class which inherits from discord.Client?

**Comment by philliphemleb** [comment]
Nevermind, I figured out thanks!

Do you know how I can use client.logout in my cog?

`import discord
from discord.ext import commands


class MyBot(commands.Cog):
    def __init__(self, client):
        self.client = client

    @commands.command()
    async def ping(self, ctx):
        await ctx.send('Pong!')

    @commands.command()
    async def disconnect(self, ctx):
        await self.client.close


def setup(client):
    client.add_cog(MyBot(client))
`

**Comment by MinerChAI** [comment]
`await self.client.logout()`

**Comment by philliphemleb** [comment]
Thanks!

**Comment by Harmon758** [comment]
For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README also links.
