### ISSUE TITLE
Position kwarg in channel.edit() is overly strict

### ISSUE THREAD

**Issue by FoglyOgly** [Rapptz/discord.py#2280]
### Summary

The position argument in guild.create_text_channel() accepts arbitrary positive integers (this plays well with Discord as well) but channel.edit() raises InvalidArgument when the position argument is greater than the number of channels in the guild.

### Reproduction Steps

`foo = await guild.create_text_channel('foo', position=1000)`
`bar = await guild.create_text_channel('bar', position=1001)`
`await foo.edit(position=1002)`

### Expected Results

Channels foo and bar are created, with foo directly above bar.
Channel foo is moved below bar.

### Actual Results

Channels foo and bar are created, with foo directly above bar. (Later access of the channel objects have position attributes of 1000 and 1001.) However, the channel edit fails. The relevant traceback is below.

`File "/home/foglyogly1/MeowthProject/MeowthAlpha/Meowth/lib/python3.7/site-packages/discord/abc.py", line 203, in _move`
`raise InvalidArgument('Channel position cannot be greater than {}'.format(len(channels) - 1))`

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.7.1-final
- discord.py v1.2.1-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Linux 4.15.0-1036-gcp #38-Ubuntu SMP Mon Jun 24 13:49:05 UTC 2019

**Comment by apple502j** [comment]
*I am sure it has nothing to do with it, but your discord.py is a bit old.*

**Comment by Rapptz** [comment]
This is by design.
