### ISSUE TITLE
client.get_channel returns None

### ISSUE THREAD

**Issue by BWACpro** [Rapptz/discord.py#2282]
### Summary

client.get_channel, client.fetch_channel, client.get_guild ect always returns None

### Reproduction Steps

```async def restartallstreams():
    for submission in reddit.subreddit('all').stream.submissions():
        if os.path.exists('streams/' + str(submission.subreddit) + '.json'):
            with open('streams/' + str(submission.subreddit) + '.json') as sub_data:
                sub_info = json.load(sub_data)
                for channel_id in sub_info['channels']:
                    print(client.get_channel(channel_id))
                    channel = await client.get_guild(575607965416161301)
                    await channel.send('https://www.reddit.com/r/' + submission.subreddit + '/comments/' + submission)

client.login("nope")
asyncio.run(restartallstreams())
```
### Expected Results

It should return a channel.
### Actual Results
But it just gives None

###TraceBack
```Traceback (most recent call last):
  File "/home/bwac/Desktop/Reddit/versions/1.2.4/stream.py", line 33, in <module>
    asyncio.run(restartallstreams())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/bwac/Desktop/Reddit/versions/1.2.4/stream.py", line 29, in restartallstreams
    channel = await client.get_guild(575607965416161301)
TypeError: object NoneType can't be used in 'await' expression
```

### System Information

- Python v3.7.3-final
- discord.py v1.2.3-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Linux 5.0.0-20-generic #21-Ubuntu SMP Mon Jun 24 09:32:09 UTC 2019

**Comment by BWACpro** [comment]
If you ask me to join the discord for help: I am banned. I do not know why. I dont even really know why i was banned. The only reason i can think of is i ask to be. My name is bwac#2922

**Comment by Vexs** [comment]
`get_x` methods return none if they don't find a match in the cache. This will happen if the ID is wrong, the bot isn't logged in, the bot can't see that object (not a member, etc), or you're calling a fetch'd guild's get_x method.
The last of those isn't what's happening, and assuming it's the correct ID and it's a member of that guild, you're most likely trying to fetch from cache before the bot is logged in.
Further, fetch_x method raise, they don't return none.

Also, remember that bans are by IP as well as by member.

**Comment by BWACpro** [comment]
Thanks for replying so fast, so what do i do? 
`client.wait_until_ready()`
returns a weird error
`RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "/home/bwac/Desktop/Reddit/versions/1.2.4/stream.py", line 33, in <module>
    asyncio.run(restartallstreams())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/bwac/Desktop/Reddit/versions/1.2.4/stream.py", line 22, in restartallstreams
    await client.wait_until_ready()
  File "/home/bwac/.local/lib/python3.7/site-packages/discord/client.py", line 698, in wait_until_ready
    await self._ready.wait()
  File "/usr/lib/python3.7/asyncio/locks.py", line 293, in wait
    await fut
RuntimeError: Task <Task pending coro=<restartallstreams() running at /home/bwac/Desktop/Reddit/versions/1.2.4/stream.py:22> cb=[_run_until_complete_cb() at /usr/lib/python3.7/asyncio/base_events.py:158]> got Future <Future pending> attached to a different loop`

**Comment by BWACpro** [comment]
Also, this laptop is the only computer it shows being banned on

**Comment by Vexs** [comment]
Ensure you read my edit, but you're mismanaging your event loop(s). You're awaiting that in a different loop than the client is using. 

Remember that internal IPs and external IPs on a home network are two different things, your home computers are all behind the same external ipv4 IP.

**Comment by BWACpro** [comment]
Placing client.start in the beginning of restartallstreams  returns this mess
```
Traceback (most recent call last):
  File "/home/bwac/Desktop/Reddit/versions/1.2.4/stream.py", line 33, in <module>
    asyncio.run(restartallstreams())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/bwac/Desktop/Reddit/versions/1.2.4/stream.py", line 23, in restartallstreams
    await client.start("")
  File "/home/bwac/.local/lib/python3.7/site-packages/discord/client.py", line 542, in start
    await self.login(*args, bot=bot)
  File "/home/bwac/.local/lib/python3.7/site-packages/discord/client.py", line 400, in login
    await self.http.static_login(token, bot=bot)
  File "/home/bwac/.local/lib/python3.7/site-packages/discord/http.py", line 258, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/home/bwac/.local/lib/python3.7/site-packages/discord/http.py", line 158, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "/home/bwac/.local/lib/python3.7/site-packages/aiohttp/client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "/home/bwac/.local/lib/python3.7/site-packages/aiohttp/client.py", line 417, in _request
    with timer:
  File "/home/bwac/.local/lib/python3.7/site-packages/aiohttp/helpers.py", line 568, in __enter__
    raise RuntimeError('Timeout context manager should be used '
RuntimeError: Timeout context manager should be used inside a task
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f7e46166b00>
```

**Comment by BWACpro** [comment]
I have resolved this by putting the function in @client.on_ready

**Comment by Harmon758** [comment]
This error was again caused by using a different event loop, to run `client.start`, than the one `client` was using. [`asyncio.run`](https://docs.python.org/3/library/asyncio-task.html#asyncio.run) creates a new event loop, so if you defined `client` as a [`Client`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client) object prior to using it, the `Client` will be initialized with a different event loop than the one `asyncio.run` creates.

It's difficult to determine this form your incomplete reproduction steps, but if the order is accurate, then that's the cause of these issues. You can simply use [`Client.run`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.run) instead of your `asyncio.run` call, if you have no need to run `Client.start` inside a coroutine. Or you can just use the existing event loop to run it instead of `asyncio.run` or create and manage your own event loop, passing it to `Client` on initialization.

Also, note, [`Client.get_guild`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.get_guild) is not a coroutine. Hence, the actual direct cause of the traceback for your initial error.

Make sure you're not at the 100 servers limit rather than being banned. Otherwise, if you don't know why you're banned, you can attempt to appeal the ban.
You can also join the [Discord API server](https://discord.gg/discord-api) for help, as the README also links.
