### ISSUE TITLE
Documentation: document the type expected by Client.get_channel

### ISSUE THREAD

**Issue by Morwenn** [Rapptz/discord.py#2285]
### The Problem

It is unclear from the documentation which type is expected from `Client.get_channel`, and from what I gathered said type changed sometime in history so some pieces of code don't work for non_obvious reasons. Moreover, passing the wrong type to `get_channel` doesn't cause it to crash but to return `None` instead, making the issue silent.

I'm actually opening this issue because it took me much more time to find where the problem was than it should have.

### The Ideal Solution

The simplest and most conservative solution is to simply document the type expected by `Client.get_channel`.

Alternative solutions would be to accept either `int` or `str` as an id and convert accordingly, or to throw a `TypeError` when the type passed to function is not the one it expected, but both sound like breaking changes, so even a simple note in the documentation seems good enough.

**Comment by Phxntxm** [comment]
...?
![image](https://user-images.githubusercontent.com/3664828/61641250-6c963080-ac64-11e9-9585-289d245b1bfa.png)

It tells you exactly what type it is returning, what are you talking about. Have you tried *clicking* `abc.GuildChannel` to see what it is?

![image](https://user-images.githubusercontent.com/3664828/61641308-833c8780-ac64-11e9-94b8-f6b6d615db0f.png)

It's pretty clear

**Comment by AXVin** [comment]
`get_x`s and `utils.get` are meant to return `None` whenever wrong types/invalid properties are given to them.
This is intended behavior and makes life easier at various instances.

If you ever use these then you must handle the returned None value in code

**Comment by Morwenn** [comment]
I'm not surprised that it's a deliberate choice, hence why I mostly asked to complete the documentation :)

My issue was with discoverability: I started by playing with some code examples online which didn't handle the returned `None`, and realized that I would probably have spent 20 fewer minutes to find my issue if the expected type had been documented.

**Comment by Vexs** [comment]
This behavior is documented.
https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.get_channel

**Comment by Morwenn** [comment]
Thanks a lot! :)

**Comment by Rapptz** [comment]
The fact that two people thought it was documented just means that it was assumed to be implicit knowledge since every `id` attribute is already an `int`, you can extrapolate that the retrieval must also be an `int`.

However, being explicit in the documentation is better than being implicit so no harm done.

**Comment by Morwenn** [comment]
I guess that people who found it was an `int` indeed just remembered it and went on without having to give it a second though, it was purely an issue of discoverability.

**Comment by OrangutanGaming** [comment]
I think with #1497 this will become less likely with other methods as IDEs will flag it up when using the wrong type
