### ISSUE TITLE
Opus doesn't load with Pyinstaller

### ISSUE THREAD

**Issue by Gunner-Bones** [Rapptz/discord.py#2288]
My script runs fine normally (I'm on Windows 10), but when put through Pyinstaller it doesn't work, telling me Opus failed to load. I checked lots of forums about this issue and found I need to load the library using `discord.opus.load_opus()`, so I manually got the libopus-0.dll and that still didn't work. I've tried everything on the similar Opus failed to load issues and they haven't worked. The Discord.py and Discord API server staff straight up refused to help me. What is the fix to this?
Thanks

**Comment by CapnS** [comment]
A few google searches led me to [this answer](https://stackoverflow.com/a/38682416) which recommends using the --path argument when running pyinstaller. I also found [this answer](https://stackoverflow.com/a/46679099) which has a lot of other suggestions on how to fix this type of problem.

**Comment by shuanaongithub** [comment]
> My script runs fine normally (I'm on Windows 10), but when put through Pyinstaller it doesn't work, telling me Opus failed to load. I checked lots of forums about this issue and found I need to load the library using `discord.opus.load_opus()`, so I manually got the libopus-0.dll and that still didn't work. I've tried everything on the similar Opus failed to load issues and they haven't worked. The Discord.py and Discord API server staff straight up refused to help me. What is the fix to this?
> Thanks

Maybe try this if you are trying to load opus via windows:
```py
import os, struct, discord
bitness = struct.calcsize('P') * 8
target = 'x64' if bitness > 32 else 'x86'
filename = os.path.join(os.path.dirname(os.path.abspath(discord.__file__)), 'bin', f'libopus-0.{target}.dll')
discord.opus.load_opus(filename)
```
