### ISSUE TITLE
Reached Rate Limit

### ISSUE THREAD

**Issue by screamopancakes** [Rapptz/discord.py#2292]
Figured id submit an issue given that its supposed to be handled internally and never actually reach the cap.

Discord.py version: 1.2.2
OS : CentOS
Installed with pip

Error traceback
```
Ignoring exception in command tempcheck:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/ubuntu/discord/admin/tempcheck.py", line 180, in tempcheck
    data= await asyncio.gather(*[getAllGuildInfo(s) for s in self.client.guilds[0:20]])
  File "/home/ubuntu/discord/admin/tempcheck.py", line 105, in getAllGuildInfo
    data[s.id]['channels'] = await asyncio.gather(*[getChannelInfo(c) for c in s.channels])
  File "/home/ubuntu/discord/admin/tempcheck.py", line 139, in getChannelInfo
    channel['pins'] = getMessagesInfo(await c.pins())  # must be able to see channel
  File "/home/ubuntu/.local/lib/python3.7/site-packages/discord/abc.py", line 915, in pins
    data = await state.http.pins_from(channel.id)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/discord/http.py", line 225, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 429 TOO MANY REQUESTS (error code: 0): You are being rate limited.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 727, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 429 TOO MANY REQUESTS (error code: 0): You are being rate limited.

```

Explanation:
i Iterate trough every guild the bot is in within an asyncio.gather, running `getAllGuildInfo` command.

`getAllGuildInfo` Iterates(using asyncio.gather to do them all at once) through all channels and gets the pins/webhooks for the channel. Along with basic information(channel type, topic, NSFW, news, slowmode,etc)

`getAllGuildInfo` Iterates(using asyncio.gather) through all the roles to get basic info for them(name, id, permissions, hoist,position, managed, mentionable, default)

`getAllGuildInfo` Iterates(using asyncio.gather) through all members to get basic info for them(id, name, discriminator, roles, nick, avatar_url)

```data= await asyncio.gather(*[getAllGuildInfo(s) for s in self.client.guilds[0:20]])
async def getAllGuildInfo(s):
    data[s.id]['channels'] = await asyncio.gather(*[getChannelInfo(c) for c in s.channels])
    data[s.id]['roles'] = await asyncio.gather(*[getRolesInfo(r) for r in s.roles])
    data[s.id]['members'] = await asyncio.gather(*[getMemberInfo(m) for m in s.members])```
	
I hit the rate limit right about 5 guilds into the 20. My guess is its the global limit.

I expected it to automatically limit itself  should it get close to request limit, extending runtime to provide time for more api calls.

**Comment by Harmon758** [comment]
Can you provide the debug logs for when this occurs?
The line this error is originating from should only be encountered after 4 retries:
https://github.com/Rapptz/discord.py/blob/12343c142262c675ca4b0483ad9bb099c9fac835/discord/http.py#L224-L225

**Comment by DevilXD** [comment]
If the last, 5th retry ended up being limited globally (after the first four failed due to any / unknown reason), getting this is a normal, possible thing.

If you will keep burning through the rate limits by doing lots of calls and hit the global one, any request that will consistently re-hit said limit (due to "bad luck" and all of those other API calls still going) will eventually fail after the 5th retry with this exact error.

You have to implement your own retry system in `getChannelInfo`, `getRolesInfo` and `getMemberInfo` that will redo the API call in case you'd get this. Keep in mind that `discord.NotFound` and `discord.Forbidden` inherit from `discord.HTTPException` so you probably want to handle those two differently first so that it won't just keep retrying to fetch from a channel it doesn't have access to for example.

Also an important note - hitting the rate limits often (especially the global limit) is a great way to get your bot token banned for API abuse - just keep this in mind.

**Comment by Harmon758** [comment]
@DevilXD The request is retried 4 times for a total of 5 tries. There is no 5th retry.
Encountering this error is abnormal and shouldn't happen (even if it's possible in the code), as the library should handle rate limits, including the global one, which is why this is a bug.

**Comment by screamopancakes** [comment]
@Harmon758 where would i get the debug logs? Would I have to recreate the problem first? currently added a 10 sec delay between guilds which fixed it.

**Comment by Harmon758** [comment]
See https://discordpy.readthedocs.io/en/latest/logging.html.
Yes, the debug logs for when the error is actually encountered would be needed.
