### ISSUE TITLE
Weird check decorator behaviour

### ISSUE THREAD

**Issue by DevilXD** [Rapptz/discord.py#2295]
### Summary

Having a function defined before / outside of a cog, and having a method with the same name inside the cog, confuses the `@commands.check()` decorator in such a way that the cog / extension loads without errors, but none of the added commands work, and trying to check help for the added command results in a TypeError and CommandInvokeError.

The extension (modified just for this test): https://www.dropbox.com/s/735q24z7r4rr6d2/st.zip?dl=1
I expect the cause to be some kind of variable shadowing, that's why it's named `ShadowTest`.

### Reproduction Steps

1. Load the attached extension with a single cog in it - notice no loading errors
2. Try using the `st`, `st add`, `st remove` and `st check` commands from the cog - notice none of them work
3. Try doing `help st` - you will receive the attached traceback

### Expected Results

The extension / cog shouldn't be allowed to load without any errors, mainly the faulty check should signal that something is wrong.

### Actual Results

Cog loads just fine, but none of the added commands work, and trying to see help for the command causes this traceback:

```py
Ignoring exception in command help:
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Python37\lib\site-packages\discord\ext\commands\help.py", line 810, in command_callback
    return await self.send_group_help(cmd)
  File "C:\Python37\lib\site-packages\discord\ext\commands\help.py", line 992, in send_group_help
    filtered = await self.filter_commands(group.commands, sort=self.sort_commands)
  File "C:\Python37\lib\site-packages\discord\ext\commands\help.py", line 524, in filter_commands
    valid = await predicate(cmd)
  File "C:\Python37\lib\site-packages\discord\ext\commands\help.py", line 518, in predicate
    return await cmd.can_run(self.context)
  File "C:\Python37\lib\site-packages\discord\ext\commands\core.py", line 935, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "C:\Python37\lib\site-packages\discord\utils.py", line 318, in async_all
    for elem in gen:
  File "C:\Python37\lib\site-packages\discord\ext\commands\core.py", line 935, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
TypeError: verification_check() missing 1 required positional argument: 'member'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\discord\ext\commands\bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Python37\lib\site-packages\discord\ext\commands\core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Python37\lib\site-packages\discord\ext\commands\core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: verification_check() missing 1 required positional argument: 'member'
```

Note: If the function has a different name, everything works fine (as the comment inside the extension / cog states).

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.7.3-final
- discord.py v1.2.3-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Windows 7 6.1.7601

**Comment by TheRockettek** [comment]
I see nothing wrong with this. It is working properly as it will prioritise the function inside of the class first and will instead use that.

**Comment by DevilXD** [comment]
@TheRockettek The cog and it's method inside the class don't exist at the time the decorators are defined and processed, that's why one cannot use `self.verification_check` inside it as far as I know and understand. It's also why checks cannot be cog's methods (which really sucks btw).

Am I doing something wrong here? `verification_check` and `self.verification_check` are two different things: https://cdn.discordapp.com/attachments/160386989819035648/606850260106608666/unknown.png

Also, this issue was more about literally nothing working and the cog loading anyway with the broken commands instead of throwing an error of any kind.

**Comment by BeatButton** [comment]
@DevilXD That's incorrect. As you define methods on the class-level, they become defined in the namespace, and your decorators etc can refer to them. Otherwise, `@st.command` wouldn't work.

**Comment by BeatButton** [comment]
```python
x = 1

class A:
    print(x)
    x = 2
    print(x)```
This is a trivial example of this concept that will print `1` and then `2`

**Comment by Jestemkiosk** [comment]
`@commands.check(verification_check)` Will always refer to local scope before checking the global scope.

**Comment by DevilXD** [comment]
Hmm, alright, I guess I need to educate myself better on how to define decorators properly.

But like, the check should error out when trying to invoke the command, no? Since checks are ran before invocation, yet none of the commands seemed to even work, yet they were partially added in some shape or form because help can see them. It seems to me like the exception from the check is getting eaten up somewhere, canceling the command invocation.

I made this issue mostly for the confusing behavior of the check and how it fails silently, preventing the command from being ran at all. Note that the check is on a subcommand, yet the whole command group doesn't work.
