### ISSUE TITLE
Discord bot event on_message overwrite all the commands

### ISSUE THREAD

**Issue by kokosxD** [Rapptz/discord.py#2297]
i have a problem when i have the on_message event and at the same time command functions.

Even if i have the on_message event after the command function, the on_message is running instead of the command function even if i have type a command. i think that the on_message event takes the !something as a simple message and is running instead of the actual command. can someone help me? i also have 2 other problems, i want to add checks before some events but i dont know how and even if its possible and i want to run the on_message event after the program has check to see if its a existing command even if it starts with the `command_prefix` (which in my case is the `!`)

here is the code, if this is helpful:

```
bot.command()
async def test():
	#do stuff 1
@bot.event
async def on_message(message):
	#do stuff 2
```
i type:

`!test`
and the output is

`#do stuff 2`

**Comment by TheRockettek** [comment]
https://discordpy.readthedocs.io/en/latest/faq.html#why-does-on-message-make-my-commands-stop-working

**Comment by kokosxD** [comment]
now both `#do stuff 1` and `#do stuff 2` are happening.
here is my code after i add the `await bot.process_commands(message)` in the end of the `on_message` event:
```
@bot.command()
async def test():
	#do stuff 1
@bot.event
async def on_message(message):
	#do stuff 2
	await bot.process_commands(message)
```

**Comment by TheRockettek** [comment]
thats because its running the command?
