### ISSUE TITLE
random and fake invalid syntax error?

### ISSUE THREAD

**Issue by GreatZardasht** [Rapptz/discord.py#2298]
im using repl python runner and when i have a unban command it says 
  File "main.py", line 244
    async def Unban(ctx, userName: discord.User):
            ^
SyntaxError: invalid syntax

i dont get how it dosnt work please help me
@client.command(pass_context = True)
async def Unban(ctx, userName: discord.User):
    """Unban a user ( Oh Snap Here We Go Again)""" 
    try:
       await client.unban(userName)
       await ctx.send("Successful!")
    except:
        await ctx.send("You don't have permissions :thinking:")

**Comment by TheRockettek** [comment]
What python version are you using
