### ISSUE TITLE
Unknown Emoji while get reactions for custome emojis and add them

### ISSUE THREAD

**Issue by YuiyuD** [Rapptz/discord.py#2299]
### Summary

Unknown emoji while reacting custom emoji like nitro emoji, using self-bot

### Reproduction Steps

for reaction in sent_message.reactions:
     print(reaction)
     await sent_message.add_reaction(reaction.emoji)

### Expected Results

Add custom emoji

### Actual Results

 ['Traceback (most recent call last):', '  File "appuselfbot.py", line 1087, in reaction_pkm', '    await sent_message.add_reaction(train_emo)', '  File "/app/.heroku/python/lib/python3.6/site-packages/discord/message.py", line 690, in add_reaction', '    await self._state.http.add_reaction(self.id, self.channel.id, emoji)', '  File "/app/.heroku/python/lib/python3.6/site-packages/discord/http.py", line 214, in request', '    raise HTTPException(r, data)', 'discord.errors.HTTPException: BAD REQUEST (status code: 400): Unknown Emoji']

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

Python 3.6.7
1.1

**Comment by TheRockettek** [comment]
This is just because they did an emoji the bot doesnt have.

**Comment by YuiyuD** [comment]
yep, I tested with older version async 0.16.12 they are working, and add emoji is ok, in print object reaction, which is object, not string like "<:name:id>" in new version and didn't word

**Comment by Rapptz** [comment]
Without code there isn't much to say with your problem. Likewise we don't know if your bot is in the server with the custom emoji etc.
