### ISSUE TITLE
Role.is_everyone() is broken

### ISSUE THREAD

**Issue by Hornwitser** [Rapptz/discord.py#23]
Running the expression 
```python
'\n'.join(['**Server** {}\n{}'.format(s.name, '\n'.join(
    ['"{}"'.format(r.name) for r in s.roles if r.is_everyone()]
)) for s in self.servers])
```
to list up all `@everyone` roles in all servers yielded

    Server Technic

    Server Logger Test
    "@everyone"
    Server /r/Dota2
    "@everyone"
    "cant post links"
    Server Discord Developers

    Server Discord API
    "@everyone"

Which is obviously not correct.  Replacing `r.is_everyone()` with `r.id == s.id` correctly listed up all `@everyone` roles.  I suggest changing the logic behind `Role.is_everyone()` to check if the role id is equal to the server id to fix this.

**Comment by Rapptz** [comment]
Fixed in d2741ca38a94bde92b080fb6a9f65b6673f5a656
