### ISSUE TITLE
Python Version Problem

### ISSUE THREAD

**Issue by DingessXL** [Rapptz/discord.py#230]
I have Python 3.5.1 installed but when i pip using:
<code>pip install git+https://github.com/Rapptz/discord.py@async</code>
It won't install because it says I don't have 3.4.1+. Any tips?

**Comment by alfalfascout** [comment]
try pip3 install git+https://github.com/Rapptz/discord.py@async

**Comment by DingessXL** [comment]
^ Thanks. Worked like a charm, I tried pip-3.4 as well, but they changed their structure back in 0.8.
