### ISSUE TITLE
doesn't support any linux OS

### ISSUE THREAD

**Issue by CarnageKeith3301** [Rapptz/discord.py#2303]
i tested this (through VM) an all the MAIN Linux distributions, and they all came out with a message saying that the distribution is not supported. so i'd suggest you stop lying like a faggot and tell ppl that linux aint supported

**Comment by DepressedGiraffe** [comment]
Not reproducable

**Comment by zomatree** [comment]
What is this error message?

**Comment by dragdev** [comment]
I'm using unbuntu, so, you stop being a lying faggot and tell people Linux is supported

**Comment by nerdstep710** [comment]
Why wouldn't it work? I use it on Ubuntu and it works fine

**Comment by Rapptz** [comment]
Unlike your statement implies, of the 70,000 downloads this package gets a day [about 68,000](https://pypistats.org/packages/discord.py) of them are on a Linux machine. Most people who use this library host their bots on a Linux server. So there is no false advertisement there.

If you want to report an actual issue I recommend following the template and acting like an adult.
