### ISSUE TITLE
Edit timestamp is not updated on cached messages

### ISSUE THREAD

**Issue by Exploder98** [Rapptz/discord.py#2310]
### Summary

When a message is edited, the edit timestamp is not actually updated on cached messages. This means that the edit timestamp is inaccessible in any method that uses the cached messages, such as `on_message_edit` and `on_message_delete`. This does not affect `fetch_message`, since that method loads the message as new instead of taking it from the cache.

### Reproduction Steps

1. Run the following client code:
```python
import discord

client = discord.Client()

@client.event
async def on_ready():
    print('Ready!')

@client.event
async def on_message_edit(before, after):
    print(after.edited_at)
    msg = await after.channel.fetch_message(after.id)
    print(msg.edited_at)

@client.event
async def on_message_delete(msg):
    print(msg.edited_at)

client.run('token')
```
2. Wait until the client is ready.
3. Send a message to a channel where the bot user has permissions to read messages, then edit that message.
4. Check the console output.
5. Delete the sent message.
6. Check the console output again.

### Expected Results

The edit timestamp is printed twice when the message is edited and once when it's deleted.

### Actual Results

`None` is printed first, meaning that the timestamp was not updated on the cached message. Then the timestamp is printed correctly, since `fetch_message` creates a new `discord.Message` object. Then `None` is printed again, this time in `on_message_delete`.

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information
```
$ python -m discord -v
- Python v3.7.3-final
- discord.py v1.2.3-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Linux 5.0.0-23-generic #24-Ubuntu SMP Mon Jul 29 15:36:44 UTC 2019
```

**Comment by Rapptz** [comment]
Fixed in master already https://github.com/Rapptz/discord.py/commit/70e62e8fe40503694d66b8200a896d00c61c07f6
