### ISSUE TITLE
Cannot identify a custom check failure

### ISSUE THREAD

**Issue by Renondedju** [Rapptz/discord.py#2311]
### The Problem

I want to be able to track which of my custom checks failed at the bot level to automatically send error messages or trigger a specific behavior.

Example: 
```py
    @commands.group(pass_context=True, invoke_without_command=True, hidden=True)
    @commands.check(is_developper)
    @commands.check(another_check)
    async def test(self, ctx):
        """ Test command group """

        if ctx.invoked_subcommand is None:
            await ctx.send(await ctx.bot.get_translation(ctx, 'test'))
```
Here, there is no way distinguish if the failure is comming from ``is_developper`` or if it was comming from ``another_check``.

### The Ideal Solution

Pass the check function that failed into the CheckFailure instance to allow local or global error handler to be able to identify the check that failed.

Example:
```py
    async def on_command_error(self, ctx, error):
        """ Handles command errors """

        if isinstance(error, commands.CheckFailure):
            # This would allow the identification of the failing check
            print(error.check.__name__)
```

### The Current Solution

The current solution is to inject some data in the context instance passed to the check in case of failure, which can cause many other issues and a lack of readability.

### Summary

Pass the check function that failed into the CheckFailure instance to identify the failing check for future error handlers.

**Comment by Gorialis** [comment]
A check is allowed to raise commands.CheckFailure (or, indeed, [any CommandError](https://discordpy.readthedocs.io/en/latest/ext/commands/commands.html#checks)) as an alternative to returning False if it wishes to attach its own error information.
