### ISSUE TITLE
Invite.max_x docs wrong

### ISSUE THREAD

**Issue by dragdev** [Rapptz/discord.py#2328]
### Summary

the docs for discord.Invite [max_age](https://discordpy.readthedocs.io/en/latest/api.html#discord.Invite.max_age) and [max_uses](https://discordpy.readthedocs.io/en/latest/api.html#discord.Invite.max_uses) both return None if infinite.

### Reproduction Steps

I had a custom function that converted seconds into a tuple of d,h,m,s, and according to the above docs, both of those properties should return an int, no matter what.
[image](https://i.imgur.com/pFZJ1Nj.png)

### Expected Results

max_age + max_uses to return 0 instead of None

### Actual Results

returns None (see https://i.imgur.com/pFZJ1Nj.png)

### Checklist

- [x ] I have searched the open issues for duplicates.
- [x ] I have shown the entire traceback, if possible.
- [x ] I have removed my token from display, if visible.

### System Information

- Python v3.7.3-final
- discord.py v1.2.3-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Windows 10 10.0.18362

**Comment by dragdev** [comment]
I would assume fetch_invite would get those values too, right?

**Comment by OrangutanGaming** [comment]
As it is mentioned in the docs it might be best to have this part of #1497
