### ISSUE TITLE
Unclosed Client Session Error

### ISSUE THREAD

**Issue by LouieK22** [Rapptz/discord.py#233]
I get this error whenever I try to run my bot

Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000299941FF080>

**Comment by sysadam** [comment]
Happened to me too

**Comment by ccubed** [comment]
This happens when there is an error in your code. Since there's an error in your code and python immediately exits, aiohttp's client session is never closed cleanly. So you see this error.

**Comment by someunknownperson** [comment]
I have no reproduce on this as well. I think they need to inspect their code and fix it.

**Comment by LouieK22** [comment]
Why did this just become all of a sudden active. I know the problem. Plus, I moved to discord.js

**Comment by Rapptz** [comment]
Good luck buddy.
