### ISSUE TITLE
Bot crash when voice_client.disconnect

### ISSUE THREAD

**Issue by jbdo99** [Rapptz/discord.py#2330]
### Summary
I'm creating a music bot and when i try to execute stop command, the bot doesn't repond anymore and the voice heathbeat is blocked

### Reproduction Steps

I use the music bot example and this stop command : 
```@commands.command()
    async def stop(self, ctx):
        """Stops and disconnects the bot from voice"""
        try:
            await self.ws_send_message(ctx.message.guild, "[STATE][BOT][STOP]") #send to website
            self.ws_interface[str(hash(ctx.message.guild))]['task'].cancel() #cancel ws receive task
            self.guild_playlist[str(hash(ctx.message.guild))]['player'] = [] #clear playlist
        except AttributeError:
            pass
        await ctx.voice_client.disconnect() # Block here
        if self.debug: # Debug is False
            await self.bot.close()
        else:
            pass
```

### Expected Results

Bot disconnect from voice channel

### Actual Results

Bot stay in voice channel and doesn't respond to command
Log : Voice heartbeat blocked for more than 5 seconds

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.7.4-final
- discord.py v1.2.3-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Windows 10 10.0.17763

**Comment by hammy3502** [comment]
You may want to ask on the [discord.py Discord Server](https://discord.gg/r3sSKJJ). You should be able to get a faster response there.
