### ISSUE TITLE
discord.Guild.premium_subscription_count returns None instead of 0

### ISSUE THREAD

**Issue by ZRunner** [Rapptz/discord.py#2331]
### Summary

Small report, nothing really insteresting, but I had a case where `discord.Guild.premium_subscription_count` returned None. According to the doc, this parameter should always return an integer, which created a bug on my bot.
After some researchs, it was the case for 67 servers out of the 195 on which my bot is running.

Also according to this line:
https://github.com/Rapptz/discord.py/blob/ea3d119ca61e269f3d5bfdfe42178a82d2dba5e6/discord/guild.py#L388 I guess that the None value is provided at the creation of the Guild object, which maybe means (I am not sure, I didn't look further upstream) that Discord itself is returning None instead of 0. 
But I also have 115 servers where the same request return 0, so there's no certainly.

### Reproduction Steps

I am not sure how to reproduce it, but I guess if you have a bot with enough small servers you should find it with a simple `return [guild.id for guild in self.bot.guilds if guild.premium_subscription_count==None]`.

### Expected Results

Well either fix it in the lib so it returns 0 instead of None, or modify the documentation to explains that it can return None.

### Actual Results

I think I explained enough above.

But basically, on a server the bot was in, `guild.premium_subscription_count == None` instead of `guild.premium_subscription_count == 0`.

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible. (well there is no error, so...)
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.7.4-final
- discord.py v1.3.0-alpha
    - discord.py pkg_resources: v1.2.3
- aiohttp v3.5.4
- websockets v6.0
- system info: Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64

**Comment by TheRockettek** [comment]
can reproduce on 1.3.0a

**Comment by OrangutanGaming** [comment]
can reproduce `None` on 9% of my guilds, 1.2.3

**Comment by PendragonLore** [comment]
Can reproduce with two of four total guilds. The two are not boosted, though a third one isn't as well, but ``premium_subscription_count`` is returning 0 in that case.
