### ISSUE TITLE
Message sending/role attribution very slow

### ISSUE THREAD

**Issue by RedBlaze42** [Rapptz/discord.py#2336]
### Summary

I have found that my bot take a very long time to send messages to multiple users or assign roles to them

### Reproduction Steps

Execute:
for member in guild.roles:
    member.send("Test")

### Expected Results

Maybe 10sec for sending 50 character messages to 100 users like when using discord.js

### Actual Results

More than 3minutes

### Checklist

- [ x] I have searched the open issues for duplicates.

### System Information

- Python v3.7.3-final
- discord.py v1.2.3-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Linux 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u2 (2019-08-08)

(Thank you for your awesome API)

**Comment by Rapptz** [comment]
The original claim that d.js is doing this in 10 seconds for 100 people is wrong. You're being rate limited.

**Comment by dragdev** [comment]
Mass-DMing is also the fastest way to get your bot banned so try and about that ratelimit

**Comment by flapili** [comment]
> Maybe 10sec for sending 50 character messages to 100 users like when using discord.js

either you are wrong or then d.js doesn't handle ratelimit 🤷‍♂
I hope for d.js you are wrong
