### ISSUE TITLE
Streaming is not returned as a status

### ISSUE THREAD

**Issue by Flame442** [Rapptz/discord.py#2337]
### Summary

The statuses returned by `member.status`, `m.web_status`, `m.mobile_status`, and `m.desktop_status` do not appear to accurately reflect the member's status when they are streaming. This isn't exactly an "issue", however it is an inconsistency with how discord displays statuses.

Streaming appears to be in a weird place where it is  displayed both as an activity ("Streaming x", just like "Playing x", "Listening to x", etc) and as a status (It changes the status color of the user to purple with the label "Streaming"). Currently, discord.py returns `discord.Streaming` as part of `member.activities`, however it does not return anything about the member streaming as part of `member.status`, `m.web_status`, `m.mobile_status`, or `m.desktop_status`.

### Reproduction Steps

View the result of  `member.status`, `m.web_status`, `m.mobile_status`, or `m.desktop_status` on a member who is streaming.

### Expected Results

Something like `discord.Status.streaming` to be returned by  `member.status`, `m.web_status`, `m.mobile_status`, and `m.desktop_status` when the member is streaming.

### Actual Results

The status returned is always one of the statuses in [discord.Status](https://discordpy.readthedocs.io/en/latest/api.html#discord.Status), which does not include anything for streaming.

### Checklist

- [x] I have searched the open issues for duplicates.
In [this comment](https://github.com/Rapptz/discord.py/issues/2199#issuecomment-498350670), you state that streaming takes over normal statuses, but this does not have anything to do with how dpy reports statuses.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.7.1-final
- discord.py v1.2.3-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Windows 7 6.1.7601

**Comment by Rapptz** [comment]
It's not a different status, the client just changes the colour for you.
