### ISSUE TITLE
Cythonized pyd modules can't be added.

### ISSUE THREAD

**Issue by applebee1558** [Rapptz/discord.py#2339]
I made a cog in an extension for discord.py. When I load this extension as it's python source, it works perfectly fine. However, whenever I compile the module with cython, discord.py complains that ```Callback must be a coroutine.```. This exception occurs from core.py in the commands directory of the library. Can you please check why this happens?

**Comment by bmintz** [comment]
You might have more luck moving the performance-sensitive code to a separate module, cythonizing that, and importing it from a pure-python extension.

**Comment by Rapptz** [comment]
Cythonizing modules is unsupported, only CPython is.
