### ISSUE TITLE
Not being able to use send_message when the player have been playing a song for a certain amount of time

### ISSUE THREAD

**Issue by tacocatt** [Rapptz/discord.py#234]
Hey there,
Recently, I noticed that when the music player(using the example playlist.py) is playing, the bot is not able to send message when the music reach over 1:30 (I tested many time and it always bug there)
however, it is able to do what the command say. For example, !volume 50 will set the volume to 50, but will NOT send the confirmation message until the bot is killed manually. When the bot finish the song, he is able to send messages again.

Is there a way to fix this? it's annoying a little...

**Comment by khazhyk** [comment]
Are you sure this isn't an error with your code? How, exactly, are you playing music, etc.
