### ISSUE TITLE
Add more streaming urls to the list of valids at discord.Streaming

### ISSUE THREAD

**Issue by RenanMsV** [Rapptz/discord.py#2342]
### The Problem

The problem is that some devs want to promote their youtube channel instead of twitch, and we cant use this, since it only accepts twitch.tv urls.
Example of issue at #692 

### The Ideal Solution

Minimal: 
- Add Youtube to the list of valid urls

Prefered:
- Add Youtube and also other streaming websites such as (the list was taken from [Top 9 live platforms](https://filmora.wondershare.com/live-streaming/top-9-live-game-streaming-platform.html)):
  - [Mixer](https://mixer.com/), 
  - [StreamCraft](http://streamcraft.com)
  - [Smashcast](https://www.smashcast.tv/)
  - [Bigo Live](http://www.bigo.tv)
  - [Afreeca](http://www.afreecatv.com/)
  - and others

Also if discord allows, change the colour of the status icon to match the streaming website theme

### The Current Solution

The current system only accepts twitch.tv urls

### Summary

Add more streaming urls to the list of valids, to allow more customization.

**Comment by Connor800** [comment]
This is not something discord.py is responsible for. Discord itself only supports Twitch URLs as you can see [here](https://discordapp.com/developers/docs/topics/gateway#activity-object-activity-types).
