### ISSUE TITLE
Commands extension is overly strict about types

### ISSUE THREAD

**Issue by DiscordLiz** [Rapptz/discord.py#2357]
### Summary

Commands are unnecessarily restricted to things matching `inspect.iscoroutinefunction`

### Reproduction Steps

```py
# stripped example
from functools import partial
from discord.ext import commands
from .extra_data import prefilled

bot = commands.Bot(...)  # leaving out details here.

async def needs_filling(ctx: commands.Context, arg_to_fill, *, user_args):
    pass  # leaving details out here

for name, (prefilled_arg, doc) in prefilled.items():
    com = commands.command(name=name, help=doc)(partial(needs_filling, arg_to_fill=prefilled_arg))
    bot.add_command(com)
```

### Expected Results

Commands would be added, hopefully allowing making a few commands which may change frequently to require only modifying what would essentially be a configuration file.

### Actual Results

Raises a TypeError insisting this isn't a coroutine due to use of `inspect.iscoroutinefunction`

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### System Information

- Python v3.7.4-final
- discord.py v1.2.3-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Linux 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018

**Comment by mikeshardmind** [comment]
Seems to be an issue with `inspect.iscoroutinefunction`, fixed in python 3.8 [BPO](https://bugs.python.org/issue34890)

Don't know if this should be handled in lib since lib supports as low as python 3.5.3
