### ISSUE TITLE
PyCharm does not sees discord.py

### ISSUE THREAD

**Issue by NiceCraftz** [Rapptz/discord.py#2359]
### Summary

i recently downloaded pycharm on my second hard disk the D: (python is installed there too)
and when i open my file (.py) my discord bot it says that discord is not a module something like that

pycharm does not see discord.py

### Reproduction Steps
I installed and i thought that the program will see python and the other pips but it did not happen so i need help

idk what does that mean

### Expected Results
i wanted to finish my discord bot on pycharm, expected to see everything working fine

### Actual Results

pycharm does not sees python and discord.py

### Checklist

- [x ] I have searched the open issues for duplicates.
- [ ] I have shown the entire traceback, if possible.
- [ ] I have removed my token from display, if visible.

### System Information

- Python v3.7.4-final
- discord.py v1.2.3-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Windows 10 10.0.18362

**Comment by NiceCraftz** [comment]
by the way im not the best programmer ever, its a funny and easy bot to make based on replies

**Comment by TheRockettek** [comment]
PyCharm uses a venv (virtual environment) and will not share the modules you have with your main python. You can see how to add modules here: https://www.jetbrains.com/help/pycharm/installing-uninstalling-and-upgrading-packages.html

**Comment by AwesomeAg1234** [comment]
you should go to your pycharm settings, go to the thing that says project name, and select interpreter. On the top of the settings window, there will be a dropdown menu. In that, put in the path to your python modules. On Linux/macOS, this would look like /usr/local/bin/python3.7 or something.

**Comment by Harmon758** [comment]
This is not an issue with discord.py.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with PyCharm.
For further help specific to using this library, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README also links.

**Comment by rjworks** [comment]
did you fix it?

**Comment by rjworks** [comment]
> PyCharm uses a venv (virtual environment) and will not share the modules you have with your main python. You can see how to add modules here: https://www.jetbrains.com/help/pycharm/installing-uninstalling-and-upgrading-packages.html

I installed the discord.py package on PyCharm and still doesn't auto complete anything.
