### ISSUE TITLE
add_field raise if empty value passed

### ISSUE THREAD

**Issue by EEKIM10** [Rapptz/discord.py#2363]
### The Problem

add_field accepts empty value/name

### The Ideal Solution
make it so it like... doesn't.

### The Current Solution

there isnt really one that can be automated... just try sending an embed and remove the field that fails or hardcode some text into it.

**Comment by dragdev** [comment]
uhh github you ok man?

**Comment by skyblockz** [comment]
It's just meant to be a new line for the embed, making embed more organized if people wants

**Comment by dragdev** [comment]
So why does it raise a httpexception?

**Comment by applebee1558** [comment]
Thats not with the library, the httpexception is raised by discord since discord disallows doing that.

**Comment by EEKIM10** [comment]
I'm not sure why this was bumped tbh, i forgot it existed
