### ISSUE TITLE
VoiceChannel.connect() hangs up after completing handshake.

### ISSUE THREAD

**Issue by GTG3000** [Rapptz/discord.py#2377]
### Summary

When attempting VoiceChannel.connect(), it goes through voice handshake and then just hangs until I get `discord.gateway # Shard ID None has stopped responding to the gateway. Closing and restarting.`.

I traced it to voice_client.py:223 but I've no idea what goes on in there and how it's supposed to work.

### Reproduction Steps

Attempt connecting to any voice channel, I suppose?

### Expected Results

A voice client being returned.

### Actual Results

The voice connection hangs. The bot considers itself already in voice for further connection attempts, but does not detect it and does not get the voice client.

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.7.3-final
- discord.py v1.2.3-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Windows 10 10.0.17134

**Comment by ShineyDev** [comment]
this is fixed in master, see [here](https://github.com/Rapptz/discord.py#installing) & install the development version.

**Comment by GTG3000** [comment]
Tried that, apparently it broke libopus somehow on install. Gonna fiddle with it a bit, see if it's my error.

**Comment by grappigegovert** [comment]
Which commit fixes this issue?

**Comment by ShineyDev** [comment]
https://github.com/Rapptz/discord.py/commit/8fdcb4de3b6dfd63c00bdd73583a63274f278998

**Comment by grappigegovert** [comment]
I literally just found that one :), Thanks a lot!

**Comment by GTG3000** [comment]
Alright, so that was just our code that was making sure libopus was loaded breaking everything now that it's lazy-load.
Thanks for the help!
