### ISSUE TITLE
Is there a reason a reaction is a tuple while a message is a single object?

### ISSUE THREAD

**Issue by LeptoSpira** [Rapptz/discord.py#2381]
When you wait for a user's message reply, it is a single `Message` object. with your usual `.author`, `.content`, etc.

This is, however, inconsistent with the `Reaction` object you get when waiting for the user to react. It instead is a tuple, with the `Reaction` object and the `User` object. The `.message` is the message the reaction is on, and there's no `.author`. Instead its index 1 in the tuple.

Is there a reason for this?

I would expect the return to be a single Reaction object, with `.author` being the user, and `.content` instead of `.emoji` as the content of the reaction. `.message` does make sense, but it can be confusing with the message object.

I hope there is some real reason behind this, and im curious what it is.

**Comment by ShineyDev** [comment]
`wait_for` returns the object(s) which would have been passed to the `on_` event handler, as stated in [the documentation](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.Bot.wait_for)
> In case the event returns multiple arguments, a tuple containing those arguments is returned instead. Please check the documentation for a list of events and their parameters.

**Comment by Vexs** [comment]
A reaction object isn't tied to one user, and a reaction object can be gotten from many other contexts besides reaction-related events. Messages, by comparison, have one single author that is always provided with that message object. 
So, we can add an inconsistent attribute to the reaction object and gain nothing, or we can provide two objects. It's worth noting that reaction-related events are not the only events that provide multiple arguments. 

Further, making the reaction object arbitrarily match the message object is... pointless and a breaking change.
