### ISSUE TITLE
Category attributes don't update when channels move between categories

### ISSUE THREAD

**Issue by EclipsedSolari** [Rapptz/discord.py#2386]
### Summary

When a channel is manually dragged from one category to another, the channel's category and category_id fields remain set to their original values. This appears to be a caching bug.

### Reproduction Steps

Establish a TextChannel reference to a Discord channel which is contained within a category, then drag the channel into a different category and examine the channel's category and category_id attributes. They remain set to their original values.

Restarting the script and re-establishing the channel reference properly refreshes these attributes.

### Expected Results

I expected the channel reference to automatically update its attributes.

### Actual Results

The channel reference kept its original (cached?) category and category_id attributes after being moved.

### Checklist

- [X] I have searched the open issues for duplicates.
- [ ] I have shown the entire traceback, if possible.
- [ ] I have removed my token from display, if visible.

### System Information

- Python v3.7.5-final
- discord.py v1.2.4-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Windows 10 10.0.18362

**Comment by Rapptz** [comment]
Cannot reproduce. 

![image](https://user-images.githubusercontent.com/1695103/67176321-9233f280-f397-11e9-807b-20aaa89db7aa.png)

**Comment by EclipsedSolari** [comment]
I observed the issue when _manually_ dragging channels between categories using the Discord GUI, not when using channel.edit.

**Comment by EclipsedSolari** [comment]
Oddly enough, the little script I just wrote to demonstrate the issue doesn't actually demonstrate the issue. I'll investigate further on my end.
