### ISSUE TITLE
Bot does not ignore one messages when images are attached to message

### ISSUE THREAD

**Issue by HunterAP23** [Rapptz/discord.py#2396]
### Summary

Bot ignores checks for if it was the sender of a message when the message contains an image / attachment.

### Reproduction Steps

In on_message, have the top command check if the message sender is the bot, and if it is the return.
Right after that, have a different if statement: if the message contains the word "hello" then send back "hello $user" with an image of a welcome sign

`async def on_message(self, message):
        # print(message)
        print("{0.author} ({0.channel}): {0.content}".format(message))
        if message.author == client.user:
            return

        if "hello" in message.content.lower():
            hello_file = discord.File("welcome.png")
            await message.channel.send(content="Hello!", file=hello_file)`

### Expected Results

Bot would should only send the "Hello!" message with image attachment once.

### Actual Results

Bot sees it's own previous "hello" message and gets stuck in an infinite loop of posting the same message.

The only way to fix this is to change this if statement:
`if "hello" in message.content.lower():`
to make sure the message was not sent by a bot with:
`if "hello" in message.content.lower() and not message.author.bot::`

### Checklist

- [x] I have searched the open issues for duplicates.
- [ ] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

**Comment by Phxntxm** [comment]
Cannot reproduce this, checking `client.user == message.author` works for me, including when a file is sent exactly how you have sent it. Due to this, I'm pretty sure it's actually an issue with your code and you should join the [support server](https://discord.gg/r3sSKJJ) in order to have help debugging what the issue is.

**Comment by HunterAP23** [comment]
Went through the example code in this repo, turns out that the documentation says to use `# if message.author == client.user:` but the example in exmaples/reply..py uses `if message.author.id == self.user.id:`, which seems to solve the issue.

**Comment by Rapptz** [comment]
> Went through the example code in this repo, turns out that the documentation says to use # if message.author == client.user: but the example in exmaples/reply..py uses if message.author.id == self.user.id:, which seems to solve the issue.

These two are equivalent.
