### ISSUE TITLE
Custom Statuses

### ISSUE THREAD

**Issue by ThePiGuy24** [Rapptz/discord.py#2400]
### The Problem

What I want is a way to set custom statuses as the feature has been added for users recently

### The Ideal Solution

Ideal solution would be using something like `client.change_presence(activity=discord.CustomStatus(status))`

### The Current Solution

None

### Summary

Just add or suggest some way to set custom statuses without the "Playing ...", "Watching ... " or "Streaming ..."

**Comment by Rapptz** [comment]
The fields in the presence payload that actually give the custom status text are ignored for bots. 

Until the payload for it is finalized it's not going to be added. See here https://github.com/discordapp/discord-api-docs/issues/1160 for tracking it on the Discord side.

**Comment by Shrubhog** [comment]
:tada: https://github.com/discordapp/discord-api-docs/issues/1160 was closed in https://github.com/discordapp/discord-api-docs/pull/1162!

**Comment by LordBoos** [comment]
https://github.com/discordapp/discord-api-docs/issues/1160 was closed, can you check it and add the custom status to discord.py?

**Comment by Harmon758** [comment]
Support for it should be coming soon.
> Custom status support is literally in my stash
I just have to pop it and that's it

\- [Danny, yesterday](https://discordapp.com/channels/336642139381301249/336642776609456130/646613363429736469)

**Comment by MEXAHOTABOP** [comment]
https://discordapp.com/developers/docs/topics/gateway#activity-object-activity-types

> 4 | Custom | {emoji} {name} | ":smiley: I am cool"


this is it?

**Comment by Phxntxm** [comment]
That is indeed what custom statuses are, if you were trying to inform others what it is though...I assure you Danny knows what custom statuses are, as the comment above yours showed he even has it ready in his stash.

**Comment by MEXAHOTABOP** [comment]
sorry i dont know who is danny 

i just mention what this is appear in developer documentation but discordpy still not support this

**Comment by MinerChAI** [comment]
> sorry i dont know who is danny
> 
> i just mention what this is appear in developer documentation but discordpy still not support this

Danny (aka Rapptz) is the creator of this lib lol

**Comment by MEXAHOTABOP** [comment]
ok that makes sense

**Comment by Harmon758** [comment]
This is likely delayed because:
> custom status [. . .] is gonna change in early 2020 apparently

\- [Danny, last Wednesday](https://discordapp.com/channels/336642139381301249/336642776609456130/656774207199510559)

**Comment by Rapptz** [comment]
Note that although this issue is closed, as of right now bots still cannot send a custom status. The developers mentioned that they were discussing whether bots should have it or not but there has been no update on that front.

**Comment by LordBoos** [comment]
What do you mean exactly? That the bot itself cannot have custom status? 
Because I use this new feature to load Custom statuses of Discord users on the same server as the bot is on and that works fine.

**Comment by MinerChAI** [comment]
Only users can set custom statuses

**Comment by Rapptz** [comment]
Reading is different from setting. Reading custom statuses works fine, I was referring to setting.

**Comment by Calamity34** [comment]
How do i put an emoji in `discord.CustomActivity(name=name,emoji=???)`

**Comment by windowsboy111** [comment]
Found [this](https://discordapp.com/developers/docs/topics/gateway#activity-object-activity-types) just now on discord developer portal. I think bots can do that now. (I know I'm a bit late)

**Comment by Salif500** [comment]
I'm trying to set a custom status but its just not working and it doesn't even have an error. I tried https://discordpy.readthedocs.io/en/latest/api.htmlhighlight=client%20wait_for#discord.CustomActivity. But it just doesn't work. Does anyone know how to use a custom activity?

**Comment by Gobot1234** [comment]
Please don't necro old issues,

Bots currently cannot set custom statuses, this is a discord limitation.

**Comment by PanSmuggler** [comment]
i just wanted set custom status for my account client and not work lol

**Comment by SlyTheFloof** [comment]
`@commands.Cog.listener()
    async def on_connect(self):
        await self.bot.change_presence(
            activity=discord.CustomActivity(name='Handling My Business!', emoji='<a:Tail_Wag:711971800157913088>'),
            status=discord.Status.dnd)`
sad

**Comment by Al-as** [comment]
Using type 3 you can emulate a custom status, not entirely though.

`bot.change_presence(activity=discord.Activity(name='56 users', type=3))   # Displays 'Watching 3 users'`
