### ISSUE TITLE
'command' has no attribute 'load()' JSON error, related to discord.py

### ISSUE THREAD

**Issue by AwesomeAg1234** [Rapptz/discord.py#2403]
When I try to run my bot, I get the error 'command' has no attribute 'load()' and other JSON errors whenever a command related to JSON is run. This has to do with discord.py because on my other personal programs, JSON works perfectly fine.

As you know about my above error that is raised, this is also another one:
`AttributeError: '_io.TextIOWrapper' object has no attribute 'update'`
Here is one of the codes related to JSON, which the error gets raised into:
`def checkforprofile(userid):`
   ` with open("gp.json", mode="r") as gp:`
     `   #gp = json.load(g)`
     `   user = "userid_" + str(userid)`
`       if user not in gp:`
            `addprofile(userid);`
           ` print("Profile " + str(user) + "created");`
       `     rules = discord.Embed(title=".",description='.')`
         `   rules.add_field(name="**ADB** profile created!", value=":)")`
            `bot.get_user(userid).send(embed=rules)`
   `     else: print("Profile creation request cancelled")`

### Expected Results

I expect it to do run that without errors, as well as all the other JSON files.

### Actual Results

As you know, the JSON file keeps raising errors. Once again, this has to do something with discord.py because: 1. It works in normal programs, so it's not JSON, and 2. it wouldn't sat `command` has not attribute error. I know this is not something related to extra files named json.py, just an FYI. 

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information
I am using python 3.7.3 on Mac OS and the softwares I use for coding are IDLE AND repl.it (I tried relp.it to see if it fixed the problem- it didn't)

**Comment by CapnS** [comment]
This means you have a command named json, so it's overwriting the module and causing this error.

**Comment by Harmon758** [comment]
As explained, you're shadowing/overwriting the json library.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.

**Comment by AwesomeAg1234** [comment]
@CapnS @Harmon758 as I explained in my post, this didn't have something to do with any overwriting or extra files, because I moved my code onto something with no files besides the ones I was using, none of which were named JSON, and it still didn't work. Also, as I explained above, JSON was working fine in normal programs without discord.py

**Comment by Harmon758** [comment]
You're overwriting json as a command within your code.
This is not an issue with the library.
For further help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README also links.

**Comment by AwesomeAg1234** [comment]
@Harmon758 I still get the following:
`AttributeError: '_io.TextIOWrapper' object has no attribute 'update'`

**Comment by AwesomeAg1234** [comment]
Thanks for the previous advice though

**Comment by CapnS** [comment]
This is still not an issue with discord.py. GitHub issues for this repository should be used to report issues with this library. They are not a medium for requesting help with Python. For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), and for help with Python in general, you should join the official [Python server](https://discord.gg/python).

**Comment by Phxntxm** [comment]
**Then join the server man** please, read the replies that you have been given instead of skimming them. This is the wrong place for this type of issue, join the server and we can help you further there.
