### ISSUE TITLE
2 stream in 1 ffmpeg process ? Is it possible ?

### ISSUE THREAD

**Issue by utkuearas** [Rapptz/discord.py#2406]
I want to streaming same audios in ffmpeg but i want to make only 1 process in ffmpeg in 2 streaming server. Is it possible ?

**Comment by CapnS** [comment]
No, this is not possible to do. An FFmpeg audio player can only be used by once voice client. If you tried to use the same player for two different voice clients, it would cause an error.

For future reference, this is not an issue with discord.py. GitHub issues for this repository should be used to report issues with this library. They are not a medium for requesting help with using the library or Python. For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), and for help with Python in general, you should join the official [Python server](https://discord.gg/python).

**Comment by imayhaveborkedit** [comment]
Yes, this is possible, but you would have to make your own AudioSource for it.  Think of it like multicast.  I could consider this a feature request and play with the idea a bit.
