### ISSUE TITLE
Get Channel always none

### ISSUE THREAD

**Issue by HerrHase** [Rapptz/discord.py#2409]
I don't get it, all works, i can see events in "on_message", but when i try to get a specifiy channel, anywhere in the code, the channel is always "none". Public Channels and Private Channels they seems to not exists.  

```
client = discord.Client()
channel = client.get_channel(12345678)
```

**Comment by apple502j** [comment]
`get_x` and `utils.get` both return `None` if they can't find anything matching. 
Common causes include:
• Wrong key
    ◦ Remember, IDs are ints, not strings
    ◦ If you're trying to copy an emoji ID, right-clicking the emoji in a message will copy message ID
• Bot not logged in, and trying to grab objects from cache
    ◦ Subvairant, using two client objects. See:`?tag botclient`
• Bot cannot "see" the object. 
    ◦ It has to be on the server, share a server with the member, etc
    ◦ If you're sharded on separate processes, each process will only have objects for that shard. 
• Objects retuned by `fetch_x` will not have a populated cache.

Also there is a great place for you to ask questions, at https://discord.gg/dpy - let's join and you can question there. Not here, sorry.

**Comment by Harmon758** [comment]
There is a reason the issue template for bug reports asks for a full traceback and reproduction steps.
Without the actual code you're running or a reproducible example (MCVE/SSCCE) of what you're trying, it's impossible to determine what your exact issue is. Your provided example will always set `channel` to `None`, as `12345678` is not a valid ID.
As explained, you're likely providing an invalid ID or an ID for a channel the client/bot cannot see.

**Comment by HerrHase** [comment]
Damn! A little misunderstanding, my script is in a Class and i try this,

```python
#
#
#
#
class MrDoorbell(discord.Client):

    #
    #
    #
    async def on_ready(self):
        client = discord.Client()
        channel = client.get_channel(12345678)
```
Of course it don't work. Sorry! Now it works fine with self.get_channel() ;-)
