### ISSUE TITLE
Add client.on_voice_disconnect() when forcibly disconnected from voice

### ISSUE THREAD

**Issue by Jetsurf** [Rapptz/discord.py#2410]
### The Problem

With the new feature of forcing disconnects from voice by users with proper permissions, its tricky to know when a bot is forcibly disconnected.
![Screenshot_2019-11-03_13-40-12](https://user-images.githubusercontent.com/9168867/68090261-8d634a00-fe3f-11e9-80dd-180eddcb4505.png)
When a user does this, the voice client knows about the disconnect as doing any further voice commands throws an exception, but there is no "clean" way to get a bot into a properly disconnected state.

### The Ideal Solution

Add a client.on_voice_disconnect() event to properly cleanup voice to a disconnected state.
```
async def on_voice_disconnect(server):
	##do cleanup
```

### The Current Solution

The first solution I came up with is to catch the exception discord.errors.ClientException - "Not connected to voice" and do cleanup from there. If there is a better solution, I am unaware of it.
```
async def on_error(event, *args, **kwargs):
	exc = sys.exc_info()
	if exc[0] is discord.errors.ClientException and str(exc[1]) == "Not connected to voice.":
		##do cleanup
```
### Summary

A recently added feature allows users to force disconnects from voice:
Add an event such as client.on_voice_disconnect() to allow proper cleanup of voice vars/classes.

Apologies if there is a method to do this that I am unaware of. This seems to be the cleanest way to go about this.

**Comment by TheRockettek** [comment]
Cant bot find this out when their voice state changes?

**Comment by Jetsurf** [comment]
Haven't tried it, but not sure if
`discord.on_voice_state_update`
will do it. Will check in a bit
