### ISSUE TITLE
Add options to commands decorators for commands-line syntax

### ISSUE THREAD

**Issue by LodrikMtl** [Rapptz/discord.py#2412]
### The Problem

I find the current way to do command-line syntax in discord.py to be repetitive and a little bit messy.

### The Ideal Solution

It would be nice to have a similar way like click python library does.

![image](https://user-images.githubusercontent.com/26026137/68130163-e1763900-fee8-11e9-9857-25fbb2c78dba.png)

Eg:
@commands.option("-v", "--verbose", ...)
@commands.option("-t", "--title", ...)
def func(self, ctx, verbose, title):

### The Current Solution

Write a Custom Parser inside the method to enable "command-line syntax"

**Comment by lganWebb** [comment]
There is currently a user made ext called `discord-flags`. You can find the project [here](https://github.com/XuaTheGrate/Flag-Parsing)

**Comment by LodrikMtl** [comment]
OH. Great News! Thx
