### ISSUE TITLE
OggStream doesn't check for end of stream

### ISSUE THREAD

**Issue by rkevin-arch** [Rapptz/discord.py#2413]
### Summary

OggStream doesn't seem to check if the stream is finished or not. If the stream is finished, [the read](https://github.com/Rapptz/discord.py/blob/4c3e53edf4ff90e3fcf195c429601a553d661cd8/discord/oggparse.py#L77) reads 0 bytes, which doesn't match an 'OggS' header, which causes it to raise an exception even when the audio was played successfully.

### Reproduction Steps

```python
#!/usr/bin/python3.5
import discord
from BOT_TOKEN import TOKEN

def print_exception(e):
    if e is not None:
        print("Exception!")
        print(e)

class TestBot(discord.Client):
    async def on_ready(self):
        vc=await self.get_channel(640586707384795150).connect()
        vc.play(discord.FFmpegOpusAudio("test.mp3"), after=print_exception)

TestBot().run(TOKEN)
```

### Expected Results

When the audio finishes playing successfully, there are no exceptions.

### Actual Results

```
Exception!
invalid header magic
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.5.3-final
- discord.py v1.3.0-alpha
    - discord.py pkg_resources: v1.3.0a2121+g4c3e53e
- aiohttp v3.5.4
- websockets v6.0
- system info: Linux 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019

**Comment by Harmon758** [comment]
Fixed by https://github.com/Rapptz/discord.py/commit/51b314331976dcc0d56db72bdf68c14e80000cc9 (#2414).
