### ISSUE TITLE
Crash on shard reconnect kills all shard connections permanently

### ISSUE THREAD

**Issue by TorKallon** [Rapptz/discord.py#2416]
### Summary

Randomly we see an exception where a single shard tries to reconnect, an uncaught exception occurs, and then we lose all connectivity to Discord. Our user-level heartbeat tasks keep running, but there is no discord activity and it doesn't look like it is trying to reconnect. 

### Reproduction Steps

<!-Dbot crash

lemagne-dbot	dbot.log-1	concurrent.futures._base.TimeoutError
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	raise futures.TimeoutError()
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	File "/usr/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	self.ws = await asyncio.wait_for(coro, timeout=180.0, loop=self.loop)
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	File "/home/charlemagne/charlemagne-prod/charlemagne1/lib/python3.6/site-packages/discord/shard.py", line 84, in poll
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	f.result()
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	File "/home/charlemagne/charlemagne-prod/charlemagne1/lib/python3.6/site-packages/discord/shard.py", line 274, in _connect
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	await self._connect()
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	File "/home/charlemagne/charlemagne-prod/charlemagne1/lib/python3.6/site-packages/discord/client.py", line 457, in connect
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	Traceback (most recent call last):
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	During handling of the above exception, another exception occurred:
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	discord.gateway.ResumeWebSocket: 1
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	raise ResumeWebSocket(self.shard_id) from exc
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	File "/home/charlemagne/charlemagne-prod/charlemagne1/lib/python3.6/site-packages/discord/gateway.py", line 473, in poll_event
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	await self.ws.poll_event()
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	File "/home/charlemagne/charlemagne-prod/charlemagne1/lib/python3.6/site-packages/discord/shard.py", line 78, in poll
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	Traceback (most recent call last):
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	The above exception was the direct cause of the following exception:
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	self.close_code, self.close_reason) from self.transfer_data_exc
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	File "/home/charlemagne/charlemagne-prod/charlemagne1/lib/python3.6/site-packages/websockets/protocol.py", line 501, in ensure_open
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	yield from self.ensure_open()
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	File "/home/charlemagne/charlemagne-prod/charlemagne1/lib/python3.6/site-packages/websockets/protocol.py", line 350, in recv
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	msg = await self.recv()
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	File "/home/charlemagne/charlemagne-prod/charlemagne1/lib/python3.6/site-packages/discord/gateway.py", line 468, in poll_event
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	Traceback (most recent call last):
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	The above exception was the direct cause of the following exception:
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	raise IncompleteReadError(incomplete, n)
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	File "/usr/lib/python3.6/asyncio/streams.py", line 666, in readexactly
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	data = yield from reader(2)
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	File "/home/charlemagne/charlemagne-prod/charlemagne1/lib/python3.6/site-packages/websockets/framing.py", line 100, in read
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	extensions=self.extensions,
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	File "/home/charlemagne/charlemagne-prod/charlemagne1/lib/python3.6/site-packages/websockets/protocol.py", line 710, in read_frame
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	frame = yield from self.read_frame(max_size)
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	File "/home/charlemagne/charlemagne-prod/charlemagne1/lib/python3.6/site-packages/websockets/protocol.py", line 645, in read_data_frame
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	frame = yield from self.read_data_frame(max_size=self.max_size)
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	File "/home/charlemagne/charlemagne-prod/charlemagne1/lib/python3.6/site-packages/websockets/protocol.py", line 580, in read_message
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	msg = yield from self.read_message()
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	File "/home/charlemagne/charlemagne-prod/charlemagne1/lib/python3.6/site-packages/websockets/protocol.py", line 528, in transfer_data
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	Traceback (most recent call last):
Nov 08 09:22:10.856	sekrion	charlemagne-dbot	dbot.log-1	2019-11-08 09:22:10,164:ERROR: Attempting a reconnect in 1.47s

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### System Information

- Python v3.6.3-final
- discord.py v1.2.3-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Linux 4.13.0-46-generic #51-Ubuntu SMP Tue Jun 12 12:36:29 UTC 2018

**Comment by Butts** [comment]
Same thing here, I just get a bunch of IDENTIFY's and zero discord activity. Very strange.

**Comment by Rapptz** [comment]
The sharding stuff was rewritten in v1.4 and subsequent versions so I think this issue is too stale now.
