### ISSUE TITLE
HEEELP

### ISSUE THREAD

**Issue by LymmyHD** [Rapptz/discord.py#2418]
channel = client.get_channel('643838295184506891')
          ^
IndentationError: expected an indented block

**Comment by LymmyHD** [comment]
The ^ are under the l

**Comment by Harmon758** [comment]
As the error says, there is expected indentation that is missing.
This is not an issue with discord.py.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.
For further help specific to using this library, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README also links.

**Comment by TheRockettek** [comment]
_Also ontop of bad indentation, channel ids are meant to be numbers._
