### ISSUE TITLE
URLs in escape_markdown() not properly matched

### ISSUE THREAD

**Issue by Jefffrey** [Rapptz/discord.py#2420]
### Summary

When using escape_markdown() from discord.utils, URLs are not properly recognized when the ignore_links argument is set to True. Issue lies with the regex string used for matching URLs:

`(?P<url>(?:https?|steam)://(?:-\.)?(?:[^\s/?\.#-]+\.?)+(?:/[^\s]*)?)`

Particularly, in the `(?:[^\s/?\.#-]+\.?)` group, why is the - dash character included? This regex string wouldn't work with some URLs that I will be encountering. Also, what purpose does the initial `(?:-\.)?` group right after the `(?:https?|steam)://` serve?

### Reproduction Steps

```python
import discord

test_string = """__Nijigasaki High School Idol Club 1st Live__
Official site: http://www.lovelive-anime.jp/nijigasaki/sp_1stlive.php
December 14 (Sat), 15 (Sun)"""

print(discord.utils.escape_markdown(test_string))
```

### Expected Results

```
\_\_Nijigasaki High School Idol Club 1st Live\_\_
Official site: http://www.lovelive-anime.jp/nijigasaki/sp_1stlive.php
December 14 (Sat), 15 (Sun)
```

### Actual Results

```
\_\_Nijigasaki High School Idol Club 1st Live\_\_
Official site: http://www.lovelive-anime.jp/nijigasaki/sp\_1stlive.php
December 14 (Sat), 15 (Sun)
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.7.1-final
- discord.py v1.2.3-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Windows 10 10.0.17763

**Comment by Rapptz** [comment]
These regex are meant to be compatible with the Discord client's regex.

From a cursory glance at the minified Discord source the following regex should catch the same URLs that the client handles (along with those forcibly made into links using `<...>`):

```regex
(?P<url><[^: >]+:\/[^ >]+>|(?:https?|steam):\/\/[^\s<]+[^<.,:;"'\]\s])
```

I'll commit a fix for this soon.
