### ISSUE TITLE
target_user and target_user_type in invite objects

### ISSUE THREAD

**Issue by StarrFox** [Rapptz/discord.py#2432]
### The Problem
target_user and target_user_type are given by the api but are not in invite objects
https://discordapp.com/developers/docs/resources/invite#invite-object-invite-structure

### The Ideal Solution

Adding target_user and target_user_type to invite objects

### The Current Solution

Using raw http calls

### Summary
target_user and target_user_type were added for stream invites but have not been added to discord.py

**Comment by avayert** [comment]
Is this not the [Invite.inviter](https://discordpy.readthedocs.io/en/latest/api.html#discord.Invite.inviter) attribute?

**Comment by StarrFox** [comment]
No, target_user is the user the invite is targeted at; it can be made by other people other than the target_user.
Atm the only thing using this are stream invites which can be made by anyone watching the stream.
Example:
```
{
    "code": "URy9TF",
    "guild": {
        "id": "536702243119038464",
        "name": "SF e&c",
        "splash": null,
        "banner": null,
        "description": null,
        "icon": null,
        "features": [],
        "verification_level": 0,
        "vanity_url_code": null
    },
    "channel": {
        "id": "618596987209646102",
        "name": "Streams",
        "type": 2
    },
    "inviter": {
        "id": "145897775274524672",
        "username": "Jay",
        "avatar": "8bb5ef9e91bf154bb8bee183f48d9d5e",
        "discriminator": "4707"
    },
    "target_user": {
        "id": "285148358815776768",
        "username": "StarrFox",
        "avatar": "f23b50a67ed78dcbef77d56b14e9f56f",
        "discriminator": "6312"
    },
    "target_user_type": 1,
    "approximate_member_count": 55,
    "approximate_presence_count": 28
}
```
