### ISSUE TITLE
My anaconda prompt is not updating discord.py.

### ISSUE THREAD

**Issue by ShpongledKane** [Rapptz/discord.py#2437]
### Summary

I can't update discord.py to version 1.2.5

### Reproduction Steps

I opened anaconda cmd prompt, activated my env and typed: 
"pip install discord.py"

### Expected Results

I expected it to update my discord.py to the 1.2.5 version.
### Actual Results

The answer was:
"Reqierement already satisfied". It just keeps the old 1.2.3 version of discord.py and won't update it.

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

 
- Python v3.6.9-final
- discord.py v1.2.3-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Windows 7 6.1.7691

**Comment by avayert** [comment]
You need the `--upgrade` (or `-U` for short) flag to upgrade an existing installation.

**Comment by Harmon758** [comment]
See https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-u.
This is not an issue with discord.py.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with pip.
For further help specific to using this library, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README also links.
