### ISSUE TITLE
Update Streaming activity to support API changes

### ISSUE THREAD

**Issue by SuperSajuuk** [Rapptz/discord.py#2442]
### The Problem
Currently, the library only supports retrieving a Streaming activity when it is from Twitch. As a result, all the properties are hard coded on the basis that Twitch is the only stream source, but that has since changed due to API updates.

### The Ideal Solution
Support all new properties from the API and allow for detection from YouTube.

### The Current Solution
See Ideal Solution

### Summary
Library only supports Twitch, so the activity.name doesn't include stream title any more, it just says Twitch because the .name property in the API is now the source site for a stream. .state and .details now include the data of Game Name and Stream Name as reported by those sites.

**Comment by Harmon758** [comment]
Resolved by #2445 (https://github.com/Rapptz/discord.py/commit/17901becf065d2621824a29cb6548dc2c3a0ba5f)
