### ISSUE TITLE
Passing Objects to Special Converters

### ISSUE THREAD

**Issue by ReinaSakuraba** [Rapptz/discord.py#2449]
### Summary

Passing in an Object to Optional or Union causes them to raise a TypeError saying they expect a type. These aren't a problem with the library itself but being unable to do this within the lib does impact usability as some Converters can be passed in as Objects by themselves e.g. commands.clean_content. Ideally there should be some way of doing this without needing to make custom Union and Optional Converters.

### Reproduction Steps

```py
@commands.command()
async def test(ctx, param: Union[int, commands.clean_content(use_nicknames=False)]):
    pass
```

### Expected Results

Being able to pass in a Converter Object to a special converter.

### Actual Results

`TypeError: Union[arg, ...]: each arg must be a type. Got <discord.ext.commands.converter.clean_content object at 0x7f5898382898>.`

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

```
- Python v3.8.0-final
- discord.py v1.3.0-alpha
    - discord.py pkg_resources: v1.3.0a2136+ga238c61
- aiohttp v3.5.4
- websockets v6.0
- system info: Linux 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23)

Exit code: 0
```

**Comment by XuaTheGrate** [comment]
The point of `clean_content` here is just to showcase a `Converter` object being passed into `Greedy`. It's irrelevant otherwise.

**Comment by Rapptz** [comment]
While it's possible to fake this for `clean_converter`, a better way to do this is to either use `Annotated` or `commands.param`. See #2590 for more info.
