### ISSUE TITLE
Docs imply availability of get_member even with guild_subscriptions disabled

### ISSUE THREAD

**Issue by JellyWX** [Rapptz/discord.py#2450]
### Summary

The docs imply that `Guild.get_member()` should still be available when `guild_subscriptions` are disabled so long as `fetch_offline_members` is enabled.

### Reproduction Steps

Disable guild subscriptions and try to fetch a member from a guild -> always returning `None`

Likely this behaviour is to be expected, however the documentation suggests it isn't (the warning box has `get_member()` as unavailable only when `fetch_offline_members` is also `False`)

### System Information

- Python v3.6.8-final
- discord.py v1.3.0-alpha
    - discord.py pkg_resources: v1.3.0a2146+g4ef0fb0
- aiohttp v3.6.2
- websockets v6.0
- system info: Linux 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019

**Comment by Rapptz** [comment]
https://discordpy.readthedocs.io/en/latest/api.html#discord.Client

The docs have a very long warning that details all of it. I don't really feel like detailing all of it in all the various sections so this isn't really a bug. If someone wants to open a PR to document them elsewhere then they can feel free to but this behaviour is already documented.

**Comment by JellyWX** [comment]
I know, this issue is suggesting that the warning is mistyped somewhat. Even with `fetch_offline_members` set as `True`, certain functionality (that the docs imply SHOULD work) don't work.

Basically, a line needs removing from the docs or there's a bug

**Comment by Rapptz** [comment]
The very bottom of the warning, the last paragraph is pretty explicit:

> In short, this makes it so the only member you can reliably query is the message author. Useful for bots that do not require any state.
