### ISSUE TITLE
Help with on_message, send_message and message Discord Bot

### ISSUE THREAD

**Issue by carlos1103** [Rapptz/discord.py#2452]
Hello I'm trying to do a simple discord bot which the only feature at the moment is to react to a X words but not only the word itself, if the word is in a sentence the bot should react to but right now it only reacts with the word.

To give more details now only reacts if it says 99, but I want to react if I say Hello 99, Hello 99 hello, Bla bla bla 99. I read somewhere it is related with a str? Also how it could be possible to put on the code to react to different words, by creating different events? And how to make a delay of 1 second? Thanks

# bot.py
import os
import random

import discord
from dotenv import load_dotenv

load_dotenv()
token = os.getenv('DISCORD_TOKEN')

client = discord.Client()

@client.event
async def on_message(message):
    if message.author == client.user:
        return
    
    brooklyn_99_quotes = ['Im the human form of the 100th emoji.', 'Bingpot!', ('Cool. cool cool, ' 'no doubt.'),]

    if message.content == '99':
        response = random.choice(brooklyn_99_quotes)
        await message.channel.send(response)
        
    

client.run(MY SERVER TOKEN - NOT REAL)

**Comment by TheRockettek** [comment]
"99" in message.content

But to be honest this is not a discord.py issue. I would recommend either going to the [discord.py](https://discord.gg/dpy) (if its an actual problem with the library) or the [python support server](https://discord.gg/python) in the future

**Comment by carlos1103** [comment]
Ah Im sorry! Im quite new to this so I didnt know where to ask, thank you for the help and sorry again!

**Comment by Harmon758** [comment]
See:
https://docs.python.org/3/reference/expressions.html#membership-test-details
https://discordpy.readthedocs.io/en/latest/ext/commands/index.html
https://docs.python.org/3/library/asyncio-task.html#sleeping

As explained, this is not an issue with discord.py.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.
For further help specific to using this library, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README also links.
