### ISSUE TITLE
Running setup.py install for websockets ... error

### ISSUE THREAD

**Issue by Glyph-ZA** [Rapptz/discord.py#2454]
### Summary

When i try and install discord.py it does installs fine until it treis to install the wbsockets.

### Reproduction Steps

py -3 -m pip install -U discord.py[voice]

### Expected Results

For it to install

### Actual Results

Running setup.py install for websockets ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Dylan\AppData\Local\Programs\Python\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Dylan\\AppData\\Local\\Temp\\pip-install-r31s1wd0\\websockets\\setup.py'"'"'; __file__='"'"'C:\\Users\\Dylan\\AppData\\Local\\Temp\\pip-install-r31s1wd0\\websockets\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Dylan\AppData\Local\Temp\pip-record-5r4h62sv\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\Dylan\AppData\Local\Temp\pip-install-r31s1wd0\websockets\
    Complete output (56 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\websockets
    copying websockets\client.py -> build\lib.win-amd64-3.8\websockets
    copying websockets\compatibility.py -> build\lib.win-amd64-3.8\websockets
    copying websockets\exceptions.py -> build\lib.win-amd64-3.8\websockets
    copying websockets\framing.py -> build\lib.win-amd64-3.8\websockets
    copying websockets\handshake.py -> build\lib.win-amd64-3.8\websockets
    copying websockets\headers.py -> build\lib.win-amd64-3.8\websockets
    copying websockets\http.py -> build\lib.win-amd64-3.8\websockets
    copying websockets\protocol.py -> build\lib.win-amd64-3.8\websockets
    copying websockets\server.py -> build\lib.win-amd64-3.8\websockets
    copying websockets\test_client_server.py -> build\lib.win-amd64-3.8\websockets
    copying websockets\test_exceptions.py -> build\lib.win-amd64-3.8\websockets
    copying websockets\test_framing.py -> build\lib.win-amd64-3.8\websockets
    copying websockets\test_handshake.py -> build\lib.win-amd64-3.8\websockets
    copying websockets\test_headers.py -> build\lib.win-amd64-3.8\websockets
    copying websockets\test_http.py -> build\lib.win-amd64-3.8\websockets
    copying websockets\test_protocol.py -> build\lib.win-amd64-3.8\websockets
    copying websockets\test_speedups.py -> build\lib.win-amd64-3.8\websockets
    copying websockets\test_uri.py -> build\lib.win-amd64-3.8\websockets
    copying websockets\test_utils.py -> build\lib.win-amd64-3.8\websockets
    copying websockets\uri.py -> build\lib.win-amd64-3.8\websockets
    copying websockets\utils.py -> build\lib.win-amd64-3.8\websockets
    copying websockets\version.py -> build\lib.win-amd64-3.8\websockets
    copying websockets\__init__.py -> build\lib.win-amd64-3.8\websockets
    creating build\lib.win-amd64-3.8\websockets\extensions
    copying websockets/extensions\base.py -> build\lib.win-amd64-3.8\websockets/extensions
    copying websockets/extensions\permessage_deflate.py -> build\lib.win-amd64-3.8\websockets/extensions
    copying websockets/extensions\test_base.py -> build\lib.win-amd64-3.8\websockets/extensions
    copying websockets/extensions\test_permessage_deflate.py -> build\lib.win-amd64-3.8\websockets/extensions
    copying websockets/extensions\__init__.py -> build\lib.win-amd64-3.8\websockets/extensions
    creating build\lib.win-amd64-3.8\websockets\py35
    copying websockets/py35\client.py -> build\lib.win-amd64-3.8\websockets/py35
    copying websockets/py35\server.py -> build\lib.win-amd64-3.8\websockets/py35
    copying websockets/py35\_test_client_server.py -> build\lib.win-amd64-3.8\websockets/py35
    copying websockets/py35\__init__.py -> build\lib.win-amd64-3.8\websockets/py35
    creating build\lib.win-amd64-3.8\websockets\py36
    copying websockets/py36\protocol.py -> build\lib.win-amd64-3.8\websockets/py36
    copying websockets/py36\_test_client_server.py -> build\lib.win-amd64-3.8\websockets/py36
    copying websockets/py36\__init__.py -> build\lib.win-amd64-3.8\websockets/py36
    running egg_info
    writing websockets.egg-info\PKG-INFO
    writing dependency_links to websockets.egg-info\dependency_links.txt
    writing top-level names to websockets.egg-info\top_level.txt
    reading manifest file 'websockets.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'websockets.egg-info\SOURCES.txt'
    copying websockets\speedups.c -> build\lib.win-amd64-3.8\websockets
    copying websockets\test_localhost.pem -> build\lib.win-amd64-3.8\websockets
    running build_ext
    building 'websockets.speedups' extension
    error: [WinError 3] The system cannot find the path specified: 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\PlatformSDK\\lib'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Dylan\AppData\Local\Programs\Python\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Dylan\\AppData\\Local\\Temp\\pip-install-r31s1wd0\\websockets\\setup.py'"'"'; __file__='"'"'C:\\Users\\Dylan\\AppData\\Local\\Temp\\pip-install-r31s1wd0\\websockets\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Dylan\AppData\Local\Temp\pip-record-5r4h62sv\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

### Checklist

- [x ] I have searched the open issues for duplicates.
- [x ] I have shown the entire traceback, if possible.
- [x ] I have removed my token from display, if visible.

### System Information

Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC v.1916 32 bit (Intel)] on win32

**Comment by Harmon758** [comment]
This is because [websockets 6.0 doesn't have wheels for Python 3.8](https://pypi.org/project/websockets/6.0/#files).
This means that you're building websockets during installation, and it has a speedups C extension with required build tools that you don't  have installed.
You can resolve this by installing a C++ compiler and/or the Windows SDK, e.g. with https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019.
Alternatively, you can downgrade to Python <= 3.7 or upgrade to websockets >= 8.0.1 (or >= 8.0.2).

See also #2453.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.

**Comment by Glyph-ZA** [comment]
> This is because [websockets 6.0 doesn't have wheels for Python 3.8](https://pypi.org/project/websockets/6.0/#files).
> This means that you're building websockets during installation, and it has a speedups C extension with required build tools that you don't have installed.
> You can resolve this by installing a C++ compiler and/or the Windows SDK, e.g. with https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019.
> Alternatively, you can downgrade to Python <= 3.7 or upgrade to websockets >= 8.0.1 (or >= 8.0.2).
> 
> See also #2453.
> 
> For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.

Thank you so much Harmon you saved me days of headaches!!Me installing the Winows SDK Worked!

**Comment by Muntarina** [comment]
![image](https://user-images.githubusercontent.com/49723413/83192242-108b1b00-a157-11ea-8a0b-0edc0c543c85.png)
hoe to resolve the error

**Comment by Phxntxm** [comment]
> ![image](https://user-images.githubusercontent.com/49723413/83192242-108b1b00-a157-11ea-8a0b-0edc0c543c85.png)
> hoe to resolve the error

Did you perhaps get lost? This is discord.py, what you're installing is not discord.py... you should go ask in their github issues, not here. 

Also you generally shouldn't necro github issues, this has been closed, you should make your own issue in the relevant repo
