### ISSUE TITLE
Command runs, but nothing happens

### ISSUE THREAD

**Issue by Sledge850T** [Rapptz/discord.py#2455]
'
@bot.command(pass_context=True)
async def setnick(ctx, user: discord.ext.commands.UserConverter, nickname):
    assert isinstance(nickname, object)
    bot.change_nickname(user, nickname)
    await ctx.send(f"Users nickname has been changed.")

'

The bot will reply but the users name won't change. Thanks in advance!

**Comment by TheRockettek** [comment]
0.16.x (async branch) is no longer supported. Please read the migrating guide [here](https://discordpy.readthedocs.io/en/latest/migrating.html) and update your code to the latest verison.

**Comment by laggycomputer** [comment]
Please also read up on how to use codeblocks, and kindly ask next time on the support server.
(Also, we have issue templates for a reason.)

**Comment by Harmon758** [comment]
You're mixing syntax for different versions of discord.py, including from v0.16.x of the library, which as explained, is no longer supported. See https://discordpy.readthedocs.io/en/latest/migrating.html.

For further help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README also links.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
