### ISSUE TITLE
With channel.purge, on_message_delete triggers instead of on_bulk_message_delete most of the time. 

### ISSUE THREAD

**Issue by AlexisBG06** [Rapptz/discord.py#2456]
So i have been trying to purge a channel thanks to channel.purge, with argument bulk always set to true and limit set to >1.
Most of the times, on_raw_message_delete triggers as many times as the amount of deleted messages set in the limit arg, instead of triggering the purge into one on_raw_bulk_message_delete.
I managed to to make on_raw_bulk_message_delete trigger with limit being set to a very little number like 2 or 3, but when I tried with a bigger limit like 14, it triggered several times the on_message_delete.
I assume it's an issue related to Discord API but wanna be sure.
Thanks in advance for answers^^

**Comment by apple502j** [comment]
`purge()` does not always bulk-delete: sometimes it deletes using the normal delete. (specifically: more than 100 or older than 14 days)

**Comment by Rapptz** [comment]
If a bulk delete is not possible (i.e. there's a single message left or it's more than 14 days old) then it uses a single delete instead.
