### ISSUE TITLE
Registering the same command twice doesn't show the command

### ISSUE THREAD

**Issue by Jekabs123** [Rapptz/discord.py#2457]
### Summary

When registering the same command twice inside different cogs it will show that A command is registered twice, but not saying which one it is

### Reproduction Steps

Register the same command twice inside 2 different cogs.

### Expected Results

> raise discord.ClientException('Command CommandName is already registered.')
or
> "Command CommandName is already registered."

### Actual Results

> raise discord.ClientException('Command {0.name} is already registered.'.format(command))

### System Information

Latest discord.py version,
Tested this on repl.it.

**Comment by Phxntxm** [comment]
Maybe I'm not understanding what you're actually saying here, but what you pasted in `actual results` literally proves what you're saying is wrong? It says *right there* which command is already registered, `{0.name}` will be the command that you're trying to register a second time
