### ISSUE TITLE
Role.members always empty

### ISSUE THREAD

**Issue by Skarlett** [Rapptz/discord.py#2462]
### Summary
getting members of roles is always empty

### Reproduction Steps
```py
@bot.listen
async def on_message(ctx):
  if ctx.guild:
    print(all(len(x.members) == 0 for x in ctx.guild.roles))
```
### Expected Results
I expected to be able to pull each User from their associated role.

### Actual Results
No traceback, just always empty.

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.7.4-final
- discord.py v1.2.5-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Linux 4.19.84-1-MANJARO #1 SMP PREEMPT Wed Nov 13 00:07:37 UTC 2019

**Comment by Rapptz** [comment]
I can't reproduce this.

**Comment by cyraid** [comment]
This happens to me too.
