### ISSUE TITLE
Command returns nothing anywhere when adding an argument.

### ISSUE THREAD

**Issue by baxcat** [Rapptz/discord.py#2468]
There's no error in console, and obviously no output in the text channel. I'm not sure what I'm doing wrong. When including no arguments (ie when i type only `-settings` and not `-settings game`), the embed does send. Here's the code:

```py
@commands.group()
@commands.is_owner()
async def settings(self, ctx, *args):
    if len(args) == 0:
        avatarlink = ctx.bot.user.avatar_url_as(static_format="png")
        botname = ctx.bot.user.name
        embed=discord.Embed(title=' ', description='**game** - set \'playing\' status', color=0xa3ceef)
        embed.set_author(name='{} settings - owner'.format(botname), icon_url='{}'.format(avatarlink))
        await ctx.send(embed=embed)

@settings.command()
async def game(self, ctx):
    await ctx.send('this is a test message')
```
Thanks for any help.

**Comment by SebbyLaw** [comment]
> if len(args) == 0:

Issues for the library should not be for debugging your bot code. In the future seek help in the [Official Support Server](https://discord.gg/r3sSKJJ).

**Comment by Harmon758** [comment]
This is as intended, as the settings command is invoked both times.
The behavior you're likely trying to get is that of the `Group` with [`invoke_without_command`](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.Group.invoke_without_command) set to `True`.

As noted, for further help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README also links.
