### ISSUE TITLE
Got socket closed randomly by cloudflare and unable to auto-reconnect

### ISSUE THREAD

**Issue by 0mza987** [Rapptz/discord.py#247]
My bot got socket closed by cloudflare randomly. I use AWS EC2 to host my bot and can confirm vps didn't reboot. 

I thought client.run() is supposed to auto-reconnect when its websocket got closed but it did not make it in my case. Is there a way to solve this problem?

Thanks very much in advance.

**Comment by Rapptz** [comment]
Need stack trace.

If it was a 1001 closure just update the lib because it now handles those.

**Comment by 0mza987** [comment]
I updated the lib and the problem seems to be solved, thank you for the reply ;)
