### ISSUE TITLE
Sending message with embed triggers on_message_edit

### ISSUE THREAD

**Issue by slysherz** [Rapptz/discord.py#2476]
### Summary

When the bot sends a message with an embed, it triggers `on_message_edit`. 
If the message with the embed is sent by a user instead, it works correctly and `on_message_edit` doesn't trigger.

### Reproduction Steps

1 - Run the bot
```
import discord

token = "???"
client = discord.Client()

@client.event
async def on_message(message):
    if message.author == client.user:
        return

    embed = discord.Embed()

    await message.channel.send(embed=embed)

@client.event
async def on_message_edit(before, after):
    print("message update!")

@client.event
async def on_ready():
    print("ready")

client.run(token)
```

2 - Send any message to the bot

### Expected Results

`on_message_edit` should not trigger and `message update!` should *not* be printed.

### Actual Results

```
ready
message update!
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

Windows:
- Python v3.8.0-final
- discord.py v1.2.5-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Windows 10 10.0.18362

Linux
- Python v3.7.5-final
- discord.py v1.2.5-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Linux 5.3.0-2-amd64 #1 SMP Debian 5.3.9-3 (2019-11-19)

**Comment by zomatree** [comment]
this is a intentional thing by discord

**Comment by slysherz** [comment]
Oh, okay. Do you know the reason for it, or do you have a link with more information?

**Comment by zomatree** [comment]
it happens because that's how discord does embeds

**Comment by Rapptz** [comment]
Discord fires what's called an "embed-only edit" to update the embeds in the message of the links you posted in the chat. It's best to check the delta for things you care about, e.g. `if before.content != after.content` or something along those lines.

**Comment by slysherz** [comment]
Okay, I see. Thanks for your help guys : )
