### ISSUE TITLE
Guild specific cog execution

### ISSUE THREAD

**Issue by Tylerlhess** [Rapptz/discord.py#2479]
### The Problem

I want to allow guilds to turn on and off commands and/or cogs without developer intervention. 

### The Ideal Solution

The ideal solution is to allow "subscription to" or "rights to use" cog functionality based on role, guild, or ID. This would also allow for cog based variables to be passed (EG role name, game id)

### The Current Solution

Complicated If then statements that have to be evaluated to make sure that command can go through rather than checking at the door if that command is relevant.

### Summary

a sub class of commands similar to cooldown that denotes the function can be subscribed to by guilds. 

a sub class of commands that allows roles to be assigned to commands by guilds.

**Comment by Vexs** [comment]
This functionality is available through [cog checks.](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.Cog.cog_check) For per command, you can use [command checks.](https://discordpy.readthedocs.io/en/latest/ext/commands/commands.html#checks)

**Comment by Tylerlhess** [comment]
thanks couldn't find it
