### ISSUE TITLE
discord has no Attribute 'PermissionOverwrite'

### ISSUE THREAD

**Issue by Rain288** [Rapptz/discord.py#248]
Greetings! I am messing around with making the bot create private channels, but for some reason it doesn't let me do this `everyone = discord.PermissionOverwrite(connect=False)`, and gives me the error in the title. Not sure what to do.
Thanks in advance! Not sure if I'm doing anything wrong, I tried to do `from discord import PermissionOverwrite as PermissionOverwrite` but that didn't work either.

**Comment by Rapptz** [comment]
Update your library.

`pip3 install --upgrade git+https://github.com/Rapptz/discord.py@async`
