### ISSUE TITLE
State.py issue with get_reaction_emoji

### ISSUE THREAD

**Issue by cleartonic** [Rapptz/discord.py#2488]
Location: https://github.com/Rapptz/discord.py/blob/master/discord/state.py
Code line: 947

The code below fails sometimes on the final try/except, where `data.get('animated',False)` started throwing an error. In my local code I put a try/except around that and added `Return None`, which fixed my code. 

```
def get_reaction_emoji(self, data):
        emoji_id = utils._get_as_snowflake(data, 'id')

        if not emoji_id:
            return data['name']

        try:
            return self._emojis[emoji_id]
        except KeyError:
            return PartialEmoji(animated=data.get('animated', False), id=emoji_id, name=data['name'])

**Comment by Vexs** [comment]
This would be way more actionable with a traceback/reproduction method.

**Comment by Rapptz** [comment]
I don't see how this raises an error and since no traceback was provided this issue is unactionable.
