### ISSUE TITLE
After isn't actually called at stream exhaustion

### ISSUE THREAD

**Issue by ccubed** [Rapptz/discord.py#249]
So, this has been bugging me for awhile really. The documentation states this about the after given for StreamPlayer and its associated classes:

> after – The finalizer that is called after the stream is exhausted. All exceptions it throws are silently discarded. It is called without parameters.

This is fine, I don't have any problem with that, except that it's wrong. Since StreamPlayer and all the forward facing iterations that we interact with are actually subclasses of ProcessPlayer, After isn't actually called when the stream is exhausted. Your intention was for it to happen that way because your code in StreamPlayer and its ilk only call it on end, HOWEVER, look at your definition for ProcessPlayer brocephus. [PPlayer Init](https://github.com/Rapptz/discord.py/blob/e736554777344757dc968f7cda019b319fc5c3bf/discord/voice_client.py#L137)

`super().__init__(process.stdout, client.encoder, client._connected, client.play_audio, after, **kwargs)`

You call init on the after that we pass in to the Player which means that Afters are in fact ran immediately, not on stream exhaustion. Sometimes this doesn't matter, but in the case of say, code like this, it's a bit of a difference:
`if server.id in self.queues and len(self.queues[server.id]):`

There may be 0 items in the queue at the start of the stream, but several items at the end. However, the code isn't ran at the end when the stream is exhausted, so even if items are added over time, it won't continue from there. It only evaluates it at the time init is called, which is to be expected. However, other interesting things happen, of course, because then if it gets called when there is another song in the queue then it skips a song, because there is another song in the queue, so it just moves over it since the after is already being called with the init. This doesn't matter so much with things that return generators, since they don't do anything until the generators are awaited or ran to completion.

So yeah, should probably fix this maybe. Or change the docs, either way really. Works for me. Can't be picky.

**Comment by Rapptz** [comment]
For the next person that comes across this issue I will leave the following words:

Doing something like this is *calling* the function and then sorting its result under `after`:

```py
player = voice.create_stream_player(..., after=self.some_function(args))
```

What the Player functions are expecting are *function objects*, i.e. `self.some_function` **without** being called. This is valid:

```py
player = voice.create_stream_player(..., after=lambda: self.some_function(args))
```

Or even clever use of `functools.partial`.

However invoking the function is not the correct way to do this.
