### ISSUE TITLE
Music doesn't play for user that just joined vc

### ISSUE THREAD

**Issue by s0hv** [Rapptz/discord.py#2492]
### Summary

When a user joins vc where a bot is already playing something they won't hear anything from the bot until you call `AudioPlayer._speak`. 
Now one fix would be calling `AudioPlayer._speak(True)` every time a user joins but I don't know if this is the best solution and if it's even a bug with this lib to begin with. Something could've changed on discords side as well that caused this behavior.

### Reproduction Steps

Make a bot join vc and start playing something. Disconnect yourself from voice and stay disconnected for a few seconds. Join back and you won't hear anything even though the bot is playing. Calling `AudioPlayer._speak(True)` will make you hear what the bot is playing again.

### Expected Results

You'd hear the sound after rejoining

### Actual Results

You hear nothing.

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.7.4-final
- discord.py v1.2.5-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Windows 10 10.0.18362

**Comment by IngeniousCoder** [comment]
I cannot reproduce the above.

Do you have code that automatically stops the playing of music when user leaves the voice chat to save memory?

**Comment by s0hv** [comment]
No I don't. If you took multiple people into account it would go like this. One person is listening to the bot just fine and another user joins in. The user who had been in voice will hear the bot but the one who joined can't. Did you use the desktop app for testing?

**Comment by IngeniousCoder** [comment]
tested on discord canary.

also, if it was platform specific, then it wouldn't be a discord.py problem.

**Comment by s0hv** [comment]
Okay I managed to find the solution. While comparing the implementation for `AudioPlayer._do_run` to my subclass's copy of it I had missed a single line that called `self._speak(True)` the first time I compared them. Now everything kinda makes sense after a second check there. At the time I made my own implementation `self._speak(True)` was never called in it so that's why I didn't have it there in the first place. 
Don't know if the change that caused this originally was discord.py side or discord side but it's now resolved by calling `_speak(True)` just before the voice playing loop starts going.

**Comment by IngeniousCoder** [comment]
How are you playing music now?

———

Regards,


Tay Chee Hean, Elton (Mr)
XtremeCoder
https://www.ingeniousapps.net
IngeniousApplications - The Home of Advanced Applications

**Comment by IngeniousCoder** [comment]
How are you playing music now?

**Comment by s0hv** [comment]
[Here's the source code](https://github.com/s0hv/Not-a-bot/blob/master/bot/player.py#L536) for my own `_do_run` function. It's pretty similar to the parent implementation with a few additions to enable a few features I need.
