### ISSUE TITLE
I can't make random image outputs using random.choice()

### ISSUE THREAD

**Issue by X1nto** [Rapptz/discord.py#2493]
### Summary

I'm trying to make a bot send random images that I have on my computer every time i want to run `!random` command

### Reproduction Steps

Here's a code i use to make a bot paste random image
```
#!/usr/bin/python3.6

import os
import discord
from dotenv import load_dotenv
import random

load_dotenv()
TOKEN = os.getenv('TOKEN')

client = discord.Client()

@client.event
async def on_ready():
    print('Connected!')        

@client.event
async def on_message(message):
    if message.author == client.user:
        return

    if message.content.startswith('!hello'):
       await message.channel.send('Hi')
    
    if message.content.startswith('!image'):
       await message.channel.send('Here ya go', file=discord.File('owl.jpg'))
    
    if message.content.startswith('!random'):
       await message.channel.send('take this', file=discord.File(random.choice('1.jpg', '2.jpg', '3.jpg', '4.jpg', '5.jpg', '6.jpg', '7.jpg', '8.jpg', '9.jpg', '10.jpg', '11.jpg', '12.jpg')))

client.run(TOKEN)
```
and here's a code for random image only
```
if message.content.startswith('!random'):
   await message.channel.send('take this', file=discord.File(random.choice('1.jpg', '2.jpg', '3.jpg', '4.jpg', '5.jpg', '6.jpg', '7.jpg', '8.jpg', '9.jpg', '10.jpg', '11.jpg', '12.jpg')))
```
### Expected Results

Ideally bot should be working and it should give me a random image from 1.jpg to 12.jpg

### Actual Results

instead i get this output in terminal instead of function working:
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/xinto/.local/lib/python3.6/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 37, in on_message
    await message.channel.send('take this', file=discord.File(random.choice('1.jpg', '2.jpg', '3.jpg', '4.jpg', '5.jpg', '6.jpg', '7.jpg', '8.jpg', '9.jpg', '10.jpg', '11.jpg', '12.jpg')))
TypeError: choice() takes 2 positional arguments but 13 were given
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.6.9-final
- discord.py v1.2.5-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Linux 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019

**Comment by Phxntxm** [comment]
`random.choice` takes a list of the choices you want it to choose from, not an argument list. Put them into a list or something.

This is not an issue with discord.py.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.
For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by X1nto** [comment]
Ok thanks, I'll put them into a list

**Comment by X1nto** [comment]
Wow that worked, it was so easy that I'm feeling too dumb now XD
