### ISSUE TITLE
Code for Pause and Resume here

### ISSUE THREAD

**Issue by MujyKun** [Rapptz/discord.py#2495]
@commands.command()
    async def pause(self, ctx):
        """Pauses currently playing song [Format: %pause]"""
        SongPlaying = ctx.voice_client.is_playing()
        Paused = ctx.voice_client.is_paused()
        if Paused != True:
            ctx.voice_client.pause()
            await ctx.send("> **The video player is now paused**")
        else:
            if SongPlaying == True:
                await ctx.send("> **The video player is already paused.**")
            else:
                await ctx.send("> **There is no song currently playing.**")

    @commands.command()
    async def resume(self, ctx):
        """Resumes a paused song [Format: %resume]"""
        Paused = ctx.voice_client.is_paused()
        if Paused == True:
            ctx.voice_client.resume()
            await ctx.send('> **Now resuming:**')
        else:
            await ctx.send('> **The video player is not paused**')

**Comment by Harmon758** [comment]
This is not an issue with discord.py.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for displaying your code.
If you have a question or need help using the library, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README also links.
