### ISSUE TITLE
external_emoji should have an alias use_external_emoji for UI consistency

### ISSUE THREAD

**Issue by dragdev** [Rapptz/discord.py#2496]
### The Problem

`external_emoji` in my opinion is a bit off, when the permission (in the UI) is called `use external emoji` and can get confusing and sometimes hard to remember.

### The Ideal Solution

Adding an alias to `external_emoji` called `use_external_emoji`. I think renaming the current would break a lot of bots so an alias would solve the issue.

### The Current Solution

just trying to remember its `external_emoji` and rtfd'ing it to make sure

### Summary

`external_emoji` is not consistent with the UI and an alias under `use_external_emoji` should be created.

**Comment by zomatree** [comment]
aliases in permissions have been declined because that they would require redoing how the permissions class works

**Comment by dragdev** [comment]
👌 thanks

**Comment by Rapptz** [comment]
Seems like a valid feature request to me

**Comment by dragdev** [comment]
It would still need re-writing though, wouldn't it?
