### ISSUE TITLE
Add a feature to find out who removed a reaction, the bot or the user themselves

### ISSUE THREAD

**Issue by xpopy** [Rapptz/discord.py#2503]
### The Problem

When using the `on_reaction_remove` event, you can't find out if it was the bot that removed the reaction using `reaction.remove(user)`, or if it was the user that removed it themselves.

### The Ideal Solution

Add another parameters for `on_reaction_remove` but probably with a better variable name:
`on_reaction_remove(reaction, user, user_that_removed_reaction)`

And for `RawReactionActionEvent` the `member` attribute could be the user that removed the reaction when the event_type is REACTION_REMOVE

**Comment by Harmon758** [comment]
As explained, [Discord's API does not provide that information with the event](https://discordapp.com/developers/docs/topics/gateway#message-reaction-remove), so there's no way for discord.py to provide that information.

Feel free to suggest it on [Discord's Feedback site for the API](https://support.discordapp.com/hc/en-us/community/topics/360000789911-API).

It's not an [audit log action](https://discordpy.readthedocs.io/en/latest/api.html#discord.AuditLogAction)/[event](https://discordapp.com/developers/docs/resources/audit-log#audit-log-entry-object-audit-log-events) either @zomatree.
