### ISSUE TITLE
Delete Webhook (as user)

### ISSUE THREAD

**Issue by Galarzaa90** [Rapptz/discord.py#2509]
### The Problem
Being able to delete a webhook as a user, instead of using the webhook's token.

When you delete a webhook using the webhook's token, the operation is anonymous, whereas deleting it as a user generates an Audit Log entry.

https://discordapp.com/developers/docs/resources/webhook#delete-webhook

### The Ideal Solution
I'm not sure what would be the ideal solution, maybe passing a client argument to `Webhook.delete`, but I don't know how that would play with adapters.

Maybe a `Client.delete_webhook(webhook_id)` method.

### The Current Solution
The current solution is to use make a manual http request, as :
```py
await ctx.bot.http.request(Route('DELETE', '/webhooks/{webhook_id}', webhook_id=webhook_id))
```

### Summary

This is similar to #1761, which requests implementing webhook editing as a user.

**Comment by ilyBenny** [comment]
How about creating a webhook?

**Comment by ilyBenny** [comment]
also ModuleNotFoundError: No module named 'Route'
