### ISSUE TITLE
Image File Upload not Rendering in Discord

### ISSUE THREAD

**Issue by MABradley** [Rapptz/discord.py#251]
I'm able to use send_file to upload a local image, however, the file that appears in the chat has no file type, and because of this Discord won't display the image like I want. I've sent the file to send_file in a couple different formats, but continue to see the same problem.

P.S. I've really enjoyed working with discord.py yesterday and today :)

**Comment by khazhyk** [comment]
use the "filename" keyword argument and give it an image like name

**Comment by MABradley** [comment]
I've gotten a good image through now, with an image like filename, but only if I read the file from disk. I'm attempting to send a file like object from memory after retrieving it from the web, and this is giving me the same problem. Here is an example (client is the reference to the discord client, this logic is in an on_message event, and message is a reference to the parameter, spacing around the link is for readability in this comment)

>import io
>import requests
>
>await client.send_file(message.channel, io.BytesIO(requests.get(" http://images.math.cnrs.fr/IMG/png/section8-image.png ",stream=True).raw.read()), filename="img.png", content="example content")

**Comment by khazhyk** [comment]
Are you sure your request is working properly? Check that the content of raw.read() is what you expect, and check that the status code for the request is 200

**Comment by MABradley** [comment]
Thank you for being so responsive, I'll take another look at this tonight and let you know what I find.

Thanks for marking this as a question Rapptz, it doesn't appear to be a bug.

**Comment by MABradley** [comment]
I'm not sure what I was running into yesterday, but I stepped through everything again. This works for me:
```
response = requests.get("http://keenthemes.com/preview/metronic/theme/assets/global/plugins/jcrop/demos/demo_files/image1.jpg", stream=True)
    with open ('img.png', 'wb') as f:
        f.write(response.raw.read())
    with open('img.png', 'rb') as f:
        await client.send_file(message.channel, f, filename='img.png', content='content')
```
 This also works for me:
```
response = requests.get("http://keenthemes.com/preview/metronic/theme/assets/global/plugins/jcrop/demos/demo_files/image1.jpg", stream=True)
   await client.send_file(message.channel, io.BytesIO(response.raw.read()), filename='img.png', content='content')
```
This uploads the file, and if you open it you see the image, but discord doesn't display it for you:
```
response = requests.get("http://keenthemes.com/preview/metronic/theme/assets/global/plugins/jcrop/demos/demo_files/image1.jpg", stream=True)
  await client.send_file(message.channel, io.BytesIO(response.raw.read()), content='content')
```
@khazhyk is right about the filename

**Comment by jd-murphy** [comment]
I just want to say big thank you to @khazhyk !!!

 the information about the file extension helped me out and solved my problem perfectly! I hadn't even thought to check that it wasn't set.... and of course it was causing the problem.
