### ISSUE TITLE
ModuleNotFoundError: No module named 'discord'

### ISSUE THREAD

**Issue by Quarol** [Rapptz/discord.py#2515]
Hi I've just installed appropriate module and I'm told information abovementioned.
Can anybody help me with that?

**Comment by Harmon758** [comment]
Make sure you're using the same Python version and environment that you installed it on.

GitHub issues for this repository should be used to report issues with the library.
They are not a medium for requesting help with installation.
For further help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README also links.
