### ISSUE TITLE
How to use PM's as an event?

### ISSUE THREAD

**Issue by Phxntxm** [Rapptz/discord.py#252]
(I see no other way to just ask a question)
I would have assumed on_message would work for this, however just this isn't working:
@client.event
async def on_message(message):
	if message.channel.is_private:
		if message.content.startswith('!testpm'):
			await client.send_message(message.channel,"I received a PM from you!")

**Comment by Rapptz** [comment]
Needs more info. "It's not working" is not very clear.

**Comment by NotSoSuper** [comment]
change
 await client.send_message(message.channel,"I received a PM from you!")
to
await client.send_message(message.author,"I received a PM from you!")

**Comment by Rapptz** [comment]
`message.channel` in a private channel context would be a `PrivateChannel` which would send it via PM. So your suggestion is just doing the same thing.

**Comment by NotSoSuper** [comment]
oh well, make sure you have client defined and your tabs/spaces right lol?

**Comment by Phxntxm** [comment]
My tabs and spacing is all correct, I'm using the same exact on_message method for multiple servers already successfully, tried both of those messaging systems and neither worked. Nothing happens, no errors at all, it's as if on_message is not called at all if it's a PM

**Comment by NotSoSuper** [comment]
oh, are you calling on_message multiple times in the same class/cog or file?
I've had an issue before where only one on_message event would register and the other wouldn't, try making a new class/cog and calling it there.

**Comment by Phxntxm** [comment]
No, it's in the same method as my other calls that are working.

**Comment by Phxntxm** [comment]
Okay..it randomly started working with not a single change to the code....I restarted the bot 4 times with these attempts, have no idea what happened, ignore this >.>
