### ISSUE TITLE
Importing ABC from collections directly was removed in Python 3.9

### ISSUE THREAD

**Issue by tirkarthi** [Rapptz/discord.py#2536]
### Summary

Importing ABC from collections directly was removed in Python 3.9. Use collections.abc instead.

### Reproduction Steps

The following line will produce an error in Python 3.9 . Since the project requires Python 3.5+. It can be fixed by using collections.abc like other places where ABC is used.

```
discord/ext/commands/bot.py:                if isinstance(ret, collections.Iterable):
```

I will raise a PR for this.

**Comment by Rapptz** [comment]
Closed via #2537
