### ISSUE TITLE
Add mutual guild method to user class

### ISSUE THREAD

**Issue by MouseAndKeyboard** [Rapptz/discord.py#2539]
### There is no simple way to quickly get the servers you share with a Member

Bot which helps users identify people who they share lots in common with on a server.

### The Ideal Solution

Adding a method to the Member class:
https://discordpy.readthedocs.io/en/latest/api.html#discord.Member
This would be the best and most obvious place to put it.

### Summary

Add a method to a User object to return a list of guilds you share in common

**Comment by SebbyLaw** [comment]
Would be O(n) since the way to do this gets slower the more guilds the bot is connected to.

**Comment by Vexs** [comment]
There's a couple things-
It's relatively easy to implement at a user level, `[g for g in client.guilds if g.get_member(id)]`, and it doesn't quite work when you introduce sharding beyond a single process. That could be considered an out of scope problem, but it's there.
