### ISSUE TITLE
Error sending embed with webhook

### ISSUE THREAD

**Issue by juliusjonker** [Rapptz/discord.py#2545]
`                
embed = discord.Embed(
    title='Restocked!',
    description='The Jordan 11 Bred just restocked on JD Sports',
    colour=discord.Colour.purple())

embed.set_footer(text='Fenix AIO')
embed.set_author(name='Fenix Restocks', icon_url='https://cdn.discordapp.com/attachments/637021387915264017/671068949504458767/T3KLOGO.png')
embed.add_field(name='Link',value='https://www.jdsports.nl/product/zwart-jordan-air-11-bred-heren/333875_jdsportsnl/')

webhook = DiscordWebhook(url='I keep my webhook private (but here is a valid webhook!!)', content=embed, username="test")
response = webhook.execute()
'

This piece a bove of the part in my script where I want it to send the embed to my webhook. But when I run this and my script comes to this part, it gives the following error:

    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Embed is not JSON serializable

Has anyone got an idea what's going on?

**Comment by Vexs** [comment]
You look to be passing an embed to the content argument, not the embed argument. Or maybe you're not, as content isn't an argument of the webhook constructor, it's an argument of send/execute

For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by Harmon758** [comment]
As explained, the other library you're using doesn't support discord.py objects.
This is not an issue with discord.py.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
