### ISSUE TITLE
Make message.reaction_add() return a reaction it creates as channel.send() does

### ISSUE THREAD

**Issue by ViChyavIn** [Rapptz/discord.py#2546]
### The Problem

It becomes easier to add a reaction and then easily remove it after.

### The Ideal Solution

I'd like the method to just return a reaction it adds as `channel.send()` method returns a message it sends.

### The Current Solution

There is a solution but it's a little bit tricky.

**Comment by Moooog** [comment]
maybe include the solution??

**Comment by Phxntxm** [comment]
https://discordpy.readthedocs.io/en/latest/api.html#discord.Message.remove_reaction

You know you can remove a reaction based on an emoji right? You don't need the reaction object. Just use whatever emoji you've sent

**Comment by Rapptz** [comment]
Return types are based off of the API responses and not something I directly control. This endpoint doesn't return anything.
