### ISSUE TITLE
bot.run() not logging in, but not return any errors

### ISSUE THREAD

**Issue by holzkne2** [Rapptz/discord.py#2547]
Bot has been working fine for weeks, now it is suddenly not running anymore. I am calling the run method, but it never returns an error, my bot never appears online, and no ready event is triggered. I have updated discord.py and create a new token for my bot. If I give the method a wrong token, it will return an error stating I gave an invalid token. 

code:
```
import discord
from discord.ext import commands

... # reading config file

client = commands.Bot(command_prefix='!')

... # commands and events

client.run(token, bot=True)
```

I am running this on a headless Raspberry Pi 3 b+.

**Comment by skyblockz** [comment]
What is your discord.py and python version?
You gotta provide some basic details

**Comment by holzkne2** [comment]
Python: 3.6.5
Discord.py: 1.9.1

**Comment by Vexs** [comment]
There is no v1.9.1 of discord.py, but that doesn't matter- there isn't enough information here to provide any sort of debugging. The lines presented, by themselves will function fine. In all likelihood, your issue lies in the unshown. 

For further debugging, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by holzkne2** [comment]
Okay, I made a file without out the middle stuff and still not working.
 literally just
```
import discord
from discord.ext import commands

client = commands.Bot(command_prefix='!')
client.run('TOKEN', bot=True)
```

**Comment by numbermaniac** [comment]
`bot=True` is not needed since that's the default. (Not that it will fix your issue)

Is it possible you have more than one bot account and you're entering the token for the wrong bot, thus causing your expected bot to not come online?

**Comment by skyblockz** [comment]
Do you have any antivirus that has poorly done firewall system that could block your python instance

**Comment by holzkne2** [comment]
Hmmm, was able to get the bot running on a different network. Guess a firewall on the Pi or Modem is causing this then. Thank you.
