### ISSUE TITLE
Role.members returns empty list

### ISSUE THREAD

**Issue by ThomasTaylorJr** [Rapptz/discord.py#2549]
**Summary**

**Context:**
Hello! The bot I'm using has complete admin access to the discord server that I'm working with; however, when using `Role.members`, the list returned is always empty.

**Reproduction Steps**
I just have a very basic script that connects to the discord server.

```
import discord
import asyncio

token = "000"
guild_id = "000"

invite_leaderboard_roles = {
    "partner": 000
}

client = discord.Client()

@client.event
async def on_ready():
    print(f'{client.user.name} has connected!')

async def update_invite_leaderboard():
    await client.wait_until_ready()
 
    while not client.is_closed():
        guild = await client.fetch_guild(guild_id)

        # Gather members
        partner_role = guild.get_role(invite_leaderboard_roles["partner"])

        print(partner_role.created_at)
        print(partner_role.members)

client.loop.create_task(update_invite_leaderboard())
client.run(token)
```

**Expected Results**
Receive a list of members provides from `Role.members`

**Actual Results**

```
Bot has connected!
2019-10-19 22:24:58.939000
[]
```

I can 100% confirm that this role has members. Any ideas? I believe there was another issue here that referenced the same problem: https://github.com/Rapptz/discord.py/issues/2462

**Comment by Harmon758** [comment]
The [`Guild`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Guild) object returned by [`Client.fetch_guild`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.fetch_guild) does not include [`Guild.members`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Guild.members).
This also applies to the [`Role`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Role) object that you're subsequently getting from the `Guild` using [`Guild.get_role`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Guild.get_role).

This is not an issue with the library, and for further help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README also links.

**Comment by 2br-2b** [comment]
Just putting a tip here for future searchers like me: using `guild = client.get_guild(guild_id)` works and returns a non-empty `partner_role.members`
