### ISSUE TITLE
'get_message' causes 401 'AuthenticationRequired' error

### ISSUE THREAD

**Issue by AlexxEG** [Rapptz/discord.py#255]
My code looks like this, excluding the irrelevant parts:
```python
class MemberStatus: # This is a cog
...
    async def on_member_update(self, before, after):
        ...
        self.delete_last_message(before)
        ...


    async def delete_last_message(self, before):
        ...
        # channel and last_msg_id is retrieved from sqlite database (channel is an actual Channel object)
        message = await self.bot.get_message(channel, last_msg_id)
        ...
```

This causes an error:
```
Ignoring exception in member_update
Traceback (most recent call last):
  File "/opt/vault101bot/py3.5env/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 247, in _run_extra
    yield from coro(*args, **kwargs)
  File "/opt/vault101bot/vault101bot/cogs/member_status.py", line 25, in on_member_update
    await self.delete_last_message(before)
  File "/opt/vault101bot/vault101bot/cogs/member_status.py", line 39, in delete_last_message
    message = await self.bot.get_message(channel, last_msg_id)
  File "/opt/vault101bot/py3.5env/lib/python3.5/site-packages/discord/client.py", line 1121, in get_message
    data = yield from self.http.get_message(channel.id, id)
  File "/opt/vault101bot/py3.5env/lib/python3.5/site-packages/discord/http.py",line 137, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: Unauthorized (status code: 401): <?xml version='1.0' encoding='UTF-8'?><Error><Code>AuthenticationRequired</Code><Message>Authentication required.</Message></Error>
```

Any help would be appreciated, thanks!

**Comment by Rapptz** [comment]
Consider logging in properly.

**Comment by AlexxEG** [comment]
I'm starting the bot like this:
```python
bot.run(config.get('bot_token'))
```

I already have a lot of other commands working, so I think it's logged in properly. Also I gave the bot all oauth permissions as well as role permissions.

**Comment by AlexxEG** [comment]
I feel like an idiot. The reason I couldn't get the message is because the 'last_msg_id' variable was a array or something.

I got it working by just getting the first item of the array. SQLite3's 'fetchone' method returns a row, so had to get the first column which contained the value I wanted.

The error threw me off I guess. Didn't even think to look at it this way.

**Comment by khazhyk** [comment]
Note, for future cases, the error message that was given was an XML response - this almost always indicates a malformed request url. Discord's api has a few places that overlap with other components, such as their cloud storage, which can cause these confusing responses.
