### ISSUE TITLE
Opus Libary not found

### ISSUE THREAD

**Issue by KeisariJulma** [Rapptz/discord.py#2551]
### Summary

Opus library not found

I just installed discrod.py on my server pc and I get error:
`Traceback (most recent call last):
  File ".\main.py", line 18, in <module>
    discord.opus.load_opus('opus')
  File "C:\Python3.8\lib\site-packages\discord\opus.py", line 156, in load_opus
    _lib = libopus_loader(name)
  File "C:\Python3.8\lib\site-packages\discord\opus.py", line 83, in libopus_loader
    lib = ctypes.cdll.LoadLibrary(name)
  File "C:\Python3.8\lib\ctypes\__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python3.8\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)`

Code work's on my laptop that I used create the code.

### Checklist

- [X] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have tried guides I found online about the problem.

### System Information
- Python v3.8.1-final
- discord.py v1.3.1-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Windows 10 10.0.17134

**Comment by avayert** [comment]
As the [documentation](https://discordpy.readthedocs.io/en/latest/api.html#discord.opus.load_opus) says, calling `load_opus` yourself on Windows should not be necessary, as the appropriate binaries are [distributed](https://github.com/Rapptz/discord.py/tree/master/discord/bin) alongside and [loaded automatically](https://github.com/Rapptz/discord.py/blob/master/discord/opus.py#L108-L112) within the library.

> Note
>
>On Windows, this function should not need to be called as the binaries are automatically loaded.

**Comment by Harmon758** [comment]
For future help like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README also links.
