### ISSUE TITLE
New issue with embed.set_footer

### ISSUE THREAD

**Issue by PimNelissen** [Rapptz/discord.py#2552]
This has never been an issue before for me until recently. It's kind of hard to explain so I added screenshots to show what I mean.

When creating an embed, I used the following line to create the footer for my poll command for example:

`embed.set_footer(text=f"Poll created by {str(ctx.message.author[:-5])}")`

However, now the command won't work and there is no error printed automatically by discord.py either. This used to work perfectly fine.

When I change the command to not include any variables through the f-string method, it will work again:

`embed.set_footer(text=f"Poll created by Test")`

https://i.imgur.com/oskhkb3.png

Does anyone know when/why this happened, and if it's an issue on my end, discord.py's end or is it an issue with Discord's API? Thanks for any help

**Comment by zomatree** [comment]
this should error as `ctx.message.author[:-5]` isnt allowed as you cannot index a Member/User object, you are most likely not printing the error inside an error handler you have, furthermore you can do [Member.name](https://discordpy.readthedocs.io/en/latest/api.html#discord.Member.name) to get there name so you dont have to index it to remove the discriminator

**Comment by PimNelissen** [comment]
> 
> 
> this should error as `ctx.message.author[:-5]` isnt allowed as you cannot index a Member/User object, you are most likely not printing the error inside an error handler you have, furthermore you can do [Member.name](https://discordpy.readthedocs.io/en/latest/api.html#discord.Member.name) to get there name so you dont have to index it to remove the discriminator

Whoops, yeah I see the issue now, see this worked in another command but not this one... I see I made a typo now.

`embed.set_footer(text=f"Poll created by {str(ctx.message.author[:-5]**)**}")`

The closing parentheses should be here instead:
`embed.set_footer(text=f"Poll created by {str(ctx.message.author**)**[:-5]}")`

I'll close the thread. Thanks for pointing it out!

**Comment by Harmon758** [comment]
For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README also links.
