### ISSUE TITLE
member object does not contain all members of the guild

### ISSUE THREAD

**Issue by chwba** [Rapptz/discord.py#2555]
### Summary

member object does not contain all members of the guild

### Reproduction Steps
```python
class DiscordClient(Client):
    async def on_ready(self):
        await self.close()
client = DiscordClient(keywork_arg=5)
client.run(token)
for guild in client.guilds:
  if guild.id == 12345:  # 12345 is an example guild id, in this example the guild shall contain 40 users
    for member in guild.members:
      print(member.id)
      print(member)
```

### Expected Results
Console print of all members ids and names

### Actual Results
Console print of only the bots name and id

### Checklist
- [x ] I have searched the open issues for duplicates.
- [ ] I have shown the entire traceback, if possible. (not applicable)
- [x ] I have removed my token from display, if visible.

### System Information
dpy version 1.2.5
python version 3.7.6
linux debian buster

**Comment by Harmon758** [comment]
I'm unable to reproduce this with the latest master branch.
Does this issue occur even if you attempt to print the members while the bot is running?
Have you tried updating to v1.3?

**Comment by Taarek** [comment]
There was an issue on Discord's end with member chunking last night, have you tried restarting your bot when this happened?

**Comment by chwba** [comment]
Yeah I have it does not work, even tried with a user token also did not work.

**Comment by dr3adx** [comment]
> Yeah I have it does not work, even tried with a user token also did not work.

hey, I have same issue, what's your discord so we can talk about this?

**Comment by lobstr** [comment]
Have you guys found anything further on this?  I am having the same issue where member object only contains a few (or only one) members of each guild.  Using discord.py version 1.3.1.

**Comment by bsalha1** [comment]
This is not a bug. The members field in the guild object returns the **cached** users. All the other users must be explicitly downloaded via guild.fetch_members().

**Comment by chwba** [comment]
@bsalha1 can you provide a working snippet?
