### ISSUE TITLE
channel.history stops getting messages when it encounters a member who no longer has access to the guild

### ISSUE THREAD

**Issue by iamawesome99** [Rapptz/discord.py#2556]
### Summary

channel.history stops getting messages when it encounters a member who no longer has access to the guild.
i don't know whether discord allows for getting messages from these members, but at the very least it should skip these messages.

### Reproduction Steps

create a new guild with a bot and two users, let's call them A and B.
have person A send a message (test1), then person B (test2), and one more from person A (test3).
kick person B from the server
next, try and get all the messages from that channel using ch.history
```python
async for msg in ch.history(limit=None):
    print(msg.author.name, msg.content)
```
### Expected Results

either all three messages would be printed or both of A's messages are printed
```
A test1
B test2
A test3
```
or
```
A test1
A test3
```

### Actual Results

only the the last message sent by A is printed
```
A test3
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

H:\>py -m discord -v
- Python v3.6.3-final
- discord.py v1.3.1-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Windows 10 10.0.17134

**Comment by Harmon758** [comment]
I'm unable to reproduce this.
Does the bot have permission to read message history?
How are you running your example code?

**Comment by EvieePy** [comment]
Cannot reproduce this on 1.3.1.

**Comment by iamawesome99** [comment]
i was a not smart and this was caused by some wild try catch and is not a bug

sorry
