### ISSUE TITLE
Recieving 400 in edit_profile

### ISSUE THREAD

**Issue by MABradley** [Rapptz/discord.py#256]
this is how I'm calling it:

`await client.edit_profile(password="password", avatar=file.read(), username="username"))`

consistently receive 400. Is there something wrong with this syntax?

**Comment by Rapptz** [comment]
If this is a bot account then you don't specify the password.

**Comment by MABradley** [comment]
This is not a bot account, so the password is correct I think. I'm starting to wonder if I simply reached some kind of edit limit, I got a successful call in and then another failure.

**Comment by Rapptz** [comment]
The rate limit for `edit_profile` returns a 400 instead of 429. I don't special case it. The rate limit is 2 changes per hour for your username.

**Comment by MABradley** [comment]
Thank you
