### ISSUE TITLE
Unexpected beheviour from discord.ext.commands.Bot.unload_extension

### ISSUE THREAD

**Issue by Gleb-ko** [Rapptz/discord.py#2563]
### Summary
`bot.unload_extension` removes cogs in sub-extensions as well as in the extension being unloaded; however, keeps the sub-extensions themselves loaded.

### Reproduction Steps
1. Have an extension and a sub-extension such as:
- `Extension`
- `Extension.sub_extension`

2. Have the extension `Extension.sub_extension` add a cog to the bot in the `setup()`

3. Run a bot and load both extensions.

4. Unload `Extension` - this will cause the cog added by `Extension.sub_extension` to be removed; however, keeping the extension `Extension.sub_extension` loaded.

Example code:

**bot.py**
```python
from discord.ext.commands import Bot

bot = Bot(command_prefix="!")

bot.load_extension("Extension")
bot.load_extension("Extension.sub_extension")
print("Extensions:",bot.extensions)
print("Cogs:",bot.cogs)

bot.unload_extension("Extension")
print("Extensions:",bot.extensions)
print("Cogs:",bot.cogs)
```
**Extension/__init__.py**
```python
def setup(bot):
    pass
```
**Extension/sub_extension.py**
```python
from discord.ext.commands import Cog

class A_Cog(Cog):
    pass

def setup(bot):
    bot.add_cog(A_Cog())
```

### Expected Results

(keep sub-extension cogs)
```
Extensions: {'Extension': <module 'Extension' from 'Extension/__init__.py'>, 'Extension.sub_extension': <module 'Extension.sub_extension' from 'Extension/sub_extension.py'>}
Cogs: {'A_Cog': <Extension.sub_extension.A_Cog object at 0x7fa273382940>}
Extensions: {'Extension.sub_extension': <module 'Extension.sub_extension' from 'Extension/sub_extension.py'>}
Cogs: {'A_Cog': <Extension.sub_extension.A_Cog object at 0x7fa273382940>}
```
OR
(unload the sub-extensions too)
```
Extensions: {'Extension': <module 'Extension' from 'Extension/__init__.py'>, 'Extension.sub_extension': <module 'Extension.sub_extension' from 'Extension/sub_extension.py'>}
Cogs: {'A_Cog': <Extension.sub_extension.A_Cog object at 0x7fa273382940>}
Extensions: {}
Cogs: {}
```

### Actual Results

```
Extensions: {'Extension': <module 'Extension' from 'Extension/__init__.py'>, 'Extension.sub_extension': <module 'Extension.sub_extension' from 'Extension/sub_extension.py'>}
Cogs: {'A_Cog': <Extension.sub_extension.A_Cog object at 0x7fa273382940>}
Extensions: {'Extension.sub_extension': <module 'Extension.sub_extension' from 'Extension/sub_extension.py'>}
Cogs: {}
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.7.3-final
- discord.py v1.3.1-final
- aiohttp v3.6.2
- websockets v6.0
- system info: Linux 5.0.0-38-generic #41-Ubuntu SMP Tue Dec 3 00:27:35 UTC 2019

**Comment by Rapptz** [comment]
This is by design. The idea is that you have a big extension module with various non-extension submodules for functionality. There are things that rely on this already so changing this probably isn't possible, not to mention I fail to see the use case.

**Comment by Gleb-ko** [comment]
Ah ok, I see. Also what do you mean about unloading being inconsistent because it's fine for me as I understand.
