### ISSUE TITLE
Missing set_owner function

### ISSUE THREAD

**Issue by TheSHEEEP** [Rapptz/discord.py#2565]
### The Problem

There doesn't seem to be a function to change the owner of a guild.  
If the guild was created by a bot, the bot should be able to change the owner.

### The Ideal Solution

In discord.js, you have a function for this: https://discord.js.org/#/docs/main/stable/class/Guild?scrollTo=setOwner

discord.py should have that as well.

### The Current Solution

If there is a solution, I don't know it.

**Comment by NCPlayz** [comment]
You can set the owner at `Guild.edit`. https://discordpy.readthedocs.io/en/latest/api.html#discord.Guild.edit
