### ISSUE TITLE
Trying to make a command to log all messages into a text file.

### ISSUE THREAD

**Issue by UpaDiarmo** [Rapptz/discord.py#2571]
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\diarm\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
TypeError: on_message() missing 1 required positional argument: 'message'

**Comment by dragdev** [comment]
Learn python. Please.

**Comment by Phxntxm** [comment]
Most likely, you have an extra parameter in your function declaration (perhaps a self, when not in a class). However with that said, this is not an issue with discord.py.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.
For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by Harmon758** [comment]
[`on_message`](https://discordpy.readthedocs.io/en/latest/api.html#discord.on_message) is only passed a single `message` parameter.

As explained, this isn't an issue with the library and you should join one of the servers for further help.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
