### ISSUE TITLE
`klass` kwarg has been renamed to `create_protocol` and the old one is deprecated

### ISSUE THREAD

**Issue by jack1142** [Rapptz/discord.py#2574]
### Reproduction Steps

Code:
```py
import warnings

import discord

warnings.filterwarnings("default", category=DeprecationWarning)

bot = discord.Client()


if __name__ == "__main__":
    TOKEN = ...
    bot.run(TOKEN)
```

### Expected Results

No deprecation warnings.

### Actual Results

I got a deprecation warning:
```
C:\Python38\lib\site-packages\websockets\client.py:407: DeprecationWarning: rename klass to create_protocol
  warnings.warn("rename klass to create_protocol", DeprecationWarning)
```
I didn't see any issue made for this so thought I will at least share it here.

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

```
- Python v3.8.1-final
- discord.py v1.3.2-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Windows 10 10.0.18362
```

**Comment by Harmon758** [comment]
This should no longer be an issue, as #2654 dropped websockets in favor of aiohttp and was released in v1.4.0.
