### ISSUE TITLE
Upload sources to pypi

### ISSUE THREAD

**Issue by noonien** [Rapptz/discord.py#2575]
### Summary

Version 1.2.4 was the last version to have sources uploaded to pypi.org. Not having sources uploaded breaks [pypi2nix](https://github.com/nix-community/pypi2nix)
### Reproduction Steps

1. https://pypi.org/project/discord.py/1.2.4/#files
2. https://pypi.org/project/discord.py/1.3.2/#files

### Expected Results

Have discord.py-<version>.tar.gz on pypi.org.
 
### Actual Results

Missing discord.py-<version>.tar.gz on pypi.org.

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
Sounds like an issue to file with pypi2nix, not here. I switched over to uploading only wheels a while ago because it's what setuptools does by default now.

**Comment by noonien** [comment]
The issue on pypi2nix was closed https://github.com/nix-community/pypi2nix/issues/422

I've not done python in ages, but isn't it normal to also upload source releases to pypi?

**Comment by mikeshardmind** [comment]
Pure python wheels (which discord.py is) are completely unpackable back to the original source code. pypi2nix may not be aware of this detail. Currently, the only reason to upload a source distribution to PyPI anymore is if you include non-python code. Even if you were to provide wheels in this case (and doing so for every possible os and platform isn't fun, or even well supported) the `--no-binary` option exists for a reason.

**Comment by noonien** [comment]
Hmm, perhaps I am missing something, but my understanding is that you don't get sources from wheels, but wheels from sources. Sources are a good way to basically have the inputs that the wheel was created from. In my case, it seems that pypi2nix does not use wheels, but instead the source, to build its own wheels, probably for valid reasons.

**Comment by mikeshardmind** [comment]
What you are missing is that wheels are just an agreed-upon delivery mechanism, and python still needs the actual python source code. You can't bundle it up non-reversibly, or you'd break expectations like tracebacks which show source code line numbers and more. `wheel unpack` will give you the files in a wheel, which should include packaging metadata, python source code, and any bundled binary files (such as in the case of manylinux wheels)

**Comment by Phxntxm** [comment]
You can even literally just do `unzip wheel.whl` and it will unzip, the source will be included in this (not advising this over `wheel unpack`, just pointing out that it's simple to retrieve the source from a wheel file).

**Comment by noonien** [comment]
Sure, if you wanted to get the source, you would get it from the distributed source (if it exists), and not from the wheel, no? Wheels might not contain the exact source, it might have added/removed files if I'm not mistaken.

**Comment by mikeshardmind** [comment]
> Wheels might not contain the exact source, it might have added/removed files if I'm not mistaken.

You are mistaken. As already stated, pure python wheels will contain the same files and data as a source distribution would. (you can even check this yourself by using a few commands to make a wheel and a source dist and compare unpacking the wheel to unpacking the source dist)

This *does* change when distributing extension code (in which case, source distributions are recommended to be available, see [this community-made reference](https://pythonwheels.com/) and [PEP-427](https://www.python.org/dev/peps/pep-0427/) if you'd like to learn more about this.)

In any case, pypi2nix also supports giving them a fully qualified remote git reference (by specifying git as a vcs with a url and ref), so them not supporting wheels does not prevent you from pointing it at https://github.com/Rapptz/discord.py with a ref matching the version you want to use.

**Comment by noonien** [comment]
Yes, you are correct that pure python wheels will contain the same files, but this is an artifact of how pure python wheels are built. It is wrong to assume that you can extract the source code that was used to build the wheel, from the wheel, and so, pypi2nix does not make this wrong assumption.

I know one CAN perhaps, currently, extract the source from the discord.py wheel, OR, grab the source from git, but pypi does allow source distributions, most packages take advantage of this, and so did discord.py until a while go. Are there any downsides to also uploading the source code on each release that perhaps I'm misssing?

**Comment by jD91mZM2** [comment]
> In any case, pypi2nix also supports giving them a fully qualified remote git reference (by specifying git as a vcs with a url and ref), so them not supporting wheels does not prevent you from pointing it at https://github.com/Rapptz/discord.py with a ref matching the version you want to use.

Thanks for writing this! I'm not at all familiar with how python packaging works, so I wasn't aware requirements.txt supported that. This pointer solved all my problems.

**Comment by Rapptz** [comment]
Following v1.3.3 on PyPI, sources are now uploaded. Sorry for the wait.
