### ISSUE TITLE
Message.delete() fails to acquire lock after you cancel an already completed task

### ISSUE THREAD

**Issue by LittleEndu** [Rapptz/discord.py#2580]
### Summary

I was copy pasting some of my old code and noticed I never programmed an exception for an edge case. I had an task waiting for message but never considered that the user might send a new command instead. After triggering the command twice and cancelling both I indeed get an error, but as it turns out it's this weird one from inside the library

### Reproduction Steps

Run this: https://gist.github.com/LittleEndu/b519ba6b4da0a762bb734284411e83c8
Send ``..test``, then ``..test``, then ``cancel`` in discord

### Expected Results

Both messages should delete successfully and continue running the rest of the code

### Actual Results

Second message.delete() fails to acquire a lock and raises and error, stopping other code from running that would after

### Checklist

- [ ] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible. (Check the gist)
- [x] I have removed my token from display, if visible.

### System Information

Windows 10 running python 3.6 and latest discord.py

**Comment by diceroll123** [comment]
You should probably either use an *actual* lock, or use `@commands.max_concurrency(1, BucketType.default, wait=True)` so that your test command can only be ran once at a time.

A `timeout` kwarg passed to your wait_for would probably be the simplest.

**Comment by LittleEndu** [comment]
That wouldn't fix the runtime error from happening for use case where you would want two or more commands to wait for some message before cleaning themselves up. The test code is something weird but completely reasonable and it should work in all versions of python (it already does in 3.7 and 3.8)

**Comment by SebbyLaw** [comment]
I am unable to reproduce this with the provided code on the latest version of discord.py (5de9287).
