### ISSUE TITLE
Documentation: BanEntry is not documented

### ISSUE THREAD

**Issue by BIRD-UP73** [Rapptz/discord.py#2585]
In readthedocs [`Guild.fetch_ban()`](https://discordpy.readthedocs.io/en/latest/api.html?highlight=fetch_ban#discord.Guild.fetch_ban) and [`Guild.bans()`](https://discordpy.readthedocs.io/en/latest/api.html?highlight=bans#discord.Guild.bans) both mention a `BanEntry`. However, there is no further information in the documentation about this class since it does not link anywhere.

**Comment by IAmTomahawkx** [comment]
`
This coroutine returns a list of BanEntry objects, which is a namedtuple with a user field to denote the User that got banned along with a reason field specifying why the user was banned that could be set to None.
`
- from the docs

**Comment by BIRD-UP73** [comment]
> `This coroutine returns a list of BanEntry objects, which is a namedtuple with a user field to denote the User that got banned along with a reason field specifying why the user was banned that could be set to None.`
> 
> * from the docs

This only appears in `Guild.bans()` and not in `Guild.ban()`

**Comment by Vexs** [comment]
The (not too uncommon) misunderstanding here is that a banentry, being a namedtuple is part of this library- it's [actually part of collections.](https://docs.python.org/3/library/collections.html#collections.namedtuple)

It seems wise to me to link to that documentation from within the dpy documentation.

**Comment by BIRD-UP73** [comment]
> `This coroutine returns a list of BanEntry objects, which is a namedtuple with a user field to denote the User that got banned along with a reason field specifying why the user was banned that could be set to None.`
> 
> * from the docs

Why put this twice in the two functions though? Wouldn't it be easier to maintain to just make one explanation for `BanEntry`?

**Comment by priyan161009** [comment]
nibba
