### ISSUE TITLE
How can i make my bot search in my forum

### ISSUE THREAD

**Issue by Scorpions95** [Rapptz/discord.py#2586]
Well this is not issue,but it's smth like question or idk.. just discuss
so,want to my bot search in my forum when someone type in discord (with this prefix for example \m/-)Skillet and bot need to search in topic and sub forums and etc
[my forums](https://translate.google.bg/translate?hl=bg&sl=bg&tl=en&u=https%3A%2F%2Frocknmetalbulgaria.eu%2Findex.php)

**Comment by Harmon758** [comment]
This is not an issue with discord.py.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python or your forum/website.
For further help specific to using this library, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README also links.
