### ISSUE TITLE
commands.Bot: `bot.tasks` or similar

### ISSUE THREAD

**Issue by dragdev** [Rapptz/discord.py#2587]
### The Problem

A property doesn't exist for bot that returns registered tasks loops

### The Ideal Solution

return a list of functions that are registered ext.tasks loops

### The Current Solution

Remember the functions. There is probably a better way i am unaware of.

**Comment by Rapptz** [comment]
The task objects don't have any reference to any bot object, this should be clear when you realize there's no bot passed in when you use the decorator.
