### ISSUE TITLE
Python 3.5.3 can't install discord.py rewrite version

### ISSUE THREAD

**Issue by moole100** [Rapptz/discord.py#2588]
https://user-images.githubusercontent.com/56115521/76161268-20f1b200-6175-11ea-88c6-25ef4090961d.png

...

**Comment by moole100** [comment]
I'am Python 3.5.3

**Comment by zomatree** [comment]
you need to use a higher python version

**Comment by skyblockz** [comment]
Python 3.5.3 had been dropped for a decent amount of time, you can always check the readme to see the oldest supported version (still recommend using latest anyways)

**Comment by AEnterprise** [comment]
interesting, since both the readme as well as pypi both list 3.5.3 as minimum required version

**Comment by Rapptz** [comment]
Chances are you're not actually running 3.5.3. Run `py -3 --version`

**Comment by moole100** [comment]
i'am update python...
it's true right...?
