### ISSUE TITLE
Creating a 100% Command Line-based Discord, questions before I try it.

### ISSUE THREAD

**Issue by SUPERMECHM500** [Rapptz/discord.py#2589]
1. A message can be sent using a function similar to this after logging in with user token:
`send_message(server, category, channel, *message)`
Is this also against Disord's ToS if the user is interacting with the command line?

2. Each message will log the user in, send the message to the corresponding destination, and log them out to prevent blocking calls in the code. Is this efficient at all? Is that even possible to do in one function?

I am using discord.py 1.3.2 in python3.8.x

**Comment by MinerChAI** [comment]
1. It is, though you're using async branch which is not supported anymore. Check [migrating page](https://discordpy.readthedocs.io/en/latest/migrating.html).
2. It is not efficient as isn't creating per-request sessions
3. Github issues page is for issues with lib, it isn't a medium for support. Please go to [support guild](https://discord.gg/r3sSKJJ) for that.

**Comment by diceroll123** [comment]
Never used it, but this exists: https://github.com/Bios-Marcel/cordless
