### ISSUE TITLE
Better typing for converters

### ISSUE THREAD

**Issue by 0az** [Rapptz/discord.py#2590]
### The Problem

Converters don't work well with the `typing` ecosystem. Specifically, they break type checks (without casts, etc) unless you write a custom class or monkeypatch in a `convert` function.

### The Ideal Solution

A way to register converters for types that we don't want to monkeypatch. `datetime.datetime` is one example.

### The Current Solution

Write a custom class or converter, both of which are unergonomic.

---

I'm willing to contribute code for this later.

Such a PR would add API for registering a converter. This will probably be implemented as a mapping between a `Type` and a `Callable[[Context, str], Type]` or some variant thereof.

Converter itself may get refactored into something using `__init_subclass__` to register itself, or Command may get modified to do this intelligently. However, neither of these suggested change are strictly necessary.

Aside from the new API, the only necessary change is here, adding the registry lookup:
https://github.com/Rapptz/discord.py/blob/5c7df3d943c899356a47960d23060c5f0e8db0f8/discord/ext/commands/core.py#L423

**Comment by Rapptz** [comment]
You have a few choices in v2, either using `typing.Annotated` or using `commands.param`. For clarity, here's both:

```py
from typing import Annotated
from discord.ext import commands
import datetime

@commands.command()
async def test(ctx: commands.Context, param: Annotated[datetime.datetime, MyConverter]):
    ...

@commands.command()
async def test2(ctx: commands.Context, param: datetime.datetime = commands.param(converter=MyConverter)):
    ...
```
