### ISSUE TITLE
requests 2.4.2 should be required

### ISSUE THREAD

**Issue by anowlcalledjosh** [Rapptz/discord.py#26]
Spent a couple of minutes banging head against wall today; the `json` parameter for `requests.post()` was only added in requests 2.4.2 (see http://docs.python-requests.org/en/latest/user/quickstart/#more-complicated-post-requests), and yet when I installed discord.py requests 2.4.2+ was not installed (it took `sudo pip3 install --upgrade requests`). Therefore, interesting crash:

```
Traceback (most recent call last):
  File "./dissonance.py", line 26, in <module>
    client.login(email, password)
  File "/usr/local/lib/python3.4/dist-packages/discord/client.py", line 654, in login
    r = requests.post(endpoints.LOGIN, json=payload)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
TypeError: request() got an unexpected keyword argument 'json'
```

To fix: depend on requests ≥ 2.4.2 (assuming that's possible with pip/pip3).

**Comment by Rapptz** [comment]
Already fixed.

https://github.com/Rapptz/discord.py/commit/7ff2cd008fce806fb575ce190c7bfb1f900c42cd
