### ISSUE TITLE
Cannot install discord.py

### ISSUE THREAD

**Issue by hansputera** [Rapptz/discord.py#2601]
![Screenshot_2020-03-16-05-00-32-19](https://user-images.githubusercontent.com/47862061/76711485-1621b900-6743-11ea-944f-a93908808e16.png)
Command: `python3 -m pip install discord.py`

**Comment by iomintz** [comment]
try running `pkg i build-essential` first

**Comment by davfsa** [comment]
Update pip (`pip install --upgrade pip`) and try again, it should work after that

**Comment by skyblockz** [comment]
> Update pip (`pip install --upgrade pip`) and try again, it should work after that

It works for me without doing the above steps, it should be his device issue
But we still recommend mobile programming

**Comment by iomintz** [comment]
@davfsa @skyblockz according to the error they are missing native complain tools. So your comments won't help.
