### ISSUE TITLE
ModuleNotFoundError: No module named 'discord'

### ISSUE THREAD

**Issue by sassarese** [Rapptz/discord.py#2602]
_Python 3.8.2
Windows8 64 bit
PyCharm Community Edition 2019.3.3_
I installed discord.py on the cmd with the command i found here
 `py -3 -m pip -U install discord.py`
and all was good, i even updated pip because the cmd told me to and i reinstalled discord with the same command to check if everything was right.
My problem is that on PyCharm if i code 
`import discord` 
i tells me module not found.
I deleted the only project i made, and it still doesn't work
I even used
 `py -3 -m pip freeze`
 to see all the pip installation and there's a file called: 
**discord.py==1.3.2**
, but still PyCharm tells me that there is no module called discord 
(I tried discord.py too)
If i write
`import discord`
in **python.exe**, it doesn't tells me that there's an error.
I cannot understand where' the problem

**Comment by TheRockettek** [comment]
PyCharm uses a venv (virtual environment) and will not share the modules you have with your main python installation. You can see how to add modules here: https://www.jetbrains.com/help/pycharm/installing-uninstalling-and-upgrading-packages.html

**Comment by MinerChAI** [comment]
This is not an issue with discord.py.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python or discord.py.
For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/r3sSKJJ).

**Comment by Midorina** [comment]
File -> Settings -> Project: "your_project_name" -> Project Interpreter 

In there, make sure you're using the correct interpreter. If you can't find your interpreter on the list, you can add it by clicking "Show all" -> plus sign on the right top corner.

**Comment by sassarese** [comment]
Ok so when i find discord.py I click on install package, but it says:
 _Error occurred when installing package 'discord.py'. Details..._
and if i click on Details it says me this(photo)

I already upgraded pip and I re-checked and on the cmd if i type
`python -m pip install --upgrade pip`
it says me:

_Requirement already up-to-date_

![15844735992988782176110324519132](https://user-images.githubusercontent.com/62296008/76894563-acaec100-688e-11ea-8092-8dc75c0110f5.jpg)

**Comment by MinerChAI** [comment]
Do what it says prolly

**Comment by sassarese** [comment]
nvm i solved
