### ISSUE TITLE
I do not know how to make this work

### ISSUE THREAD

**Issue by LucasBirkemose** [Rapptz/discord.py#2603]
I have tried to fix this problem with my discord bot for a while but I just can get it to work my code is:

@bot.command()
async def commandInfo(ctx, *, commandIN = None):
    if commandIN is None:
        return await ctx.send("You haven't specified a command!")

    if commandIN is fun:
        return await ctx.send("Testing Testing 1.2.3")"

**Comment by zomatree** [comment]
this isnt a issue with the library, please ask questions like this in the support server https://discord.gg/r3sSKJJ

**Comment by Moooog** [comment]
> this isnt a issue with the library, please ask questions like this in the support server https://discord.gg/r3sSKJJ

that also "fun"

**Comment by Harmon758** [comment]
You don't seem to define `fun`, and there's an improper trailing quotation mark at the end.
Other than that, without knowing what "this problem" is or why being able to get it to work is a problem and without a full traceback, there's not enough information to help you.

This is likely not an issue with discord.py though.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.
If you *are* reporting a bug, please properly fill out the issue template and provide a summary of the issue, reproduction steps, your expected and actual results, and your system information.
For further help specific to using this library, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README also links.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
