### ISSUE TITLE
VoiceClient.is_playing() doesn't respond the right answer

### ISSUE THREAD

**Issue by jbdo99** [Rapptz/discord.py#2605]
### Summary

The VoiceClient.is_playing() return False when the player is playing.

### Reproduction Steps

I took the basic_voice example, added a `self.guild_playlist` in init and changed this : 
```python
    @commands.command()
    async def play(self, ctx, *, url):
        if ctx.voice_client.is_playing():
            async with ctx.typing():
                if not str(hash(ctx.message.guild)) in self.guild_playlist:
                    self.guild_playlist[str(hash(ctx.message.guild))] = {'player': []}
                player = await YTDLSource.from_url(url, loop=self.bot.loop, stream=True)
                self.guild_playlist[str(hash(ctx.message.guild))]['player'].append(player)
        else:
            async with ctx.typing():
                player = await YTDLSource.from_url(url, loop=self.bot.loop, stream=True)
                ctx.voice_client.play(player, after=lambda e: self.next_handler(ctx))

```

### Expected Results

When music is playing, VoiceClient.is_playing should return True

### Actual Results

VoiceClient.is_playing return False

### Checklist

- [ x ] I have searched the open issues for duplicates.
- [ x ] I have shown the entire traceback, if possible.
- [ x ] I have removed my token from display, if visible.

### System Information

- Python v3.7.4-final
- discord.py v1.3.2-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Windows 10 10.0.18362

**Comment by quizwammer** [comment]
I seem to have the same issue, how did you fix it?

**Comment by NicGorod** [comment]
Hey, did you end up resolving this issue? Having the same one.
