### ISSUE TITLE
`BotBase.load_extension` overwrites modules from sys.modules.

### ISSUE THREAD

**Issue by Numerlor** [Rapptz/discord.py#2608]
### Summary
`BotBase._load_from_module_spec` does not check if a module is already loaded, overwriting modules if they were imported before.

### Reproduction Steps
file.py
```python
import os

from discord.ext import commands

import extension


bot = commands.Bot("?")

bot.load_extension("extension")

if __name__ == "__main__":
    bot.run(os.environ.get("BOTTOKEN"))
```
extension.py
```python
from discord.ext import commands

print("Loading extension")


class Test(commands.Cog):
    @commands.command()
    async def test(self, ctx) -> None:
        await ctx.send("Working command")


def setup(bot):
    bot.add_cog(Test())
```
### Expected Results
Loading extensions uses already imported modules when available.

### Actual Results
Loading an extension will ignore modules already present in `sys.modules`, overwrites and executes them again.

### Checklist
- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information
- Python v3.8.0-final
- discord.py v1.3.2-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Windows 7 6.1.7601

**Comment by Rapptz** [comment]
This is by design.
