### ISSUE TITLE
Add a way to clear image/thumbnail/author in `discord.Embed`

### ISSUE THREAD

**Issue by jack1142** [Rapptz/discord.py#2610]
### The Problem

It becomes easier to modify or reuse `discord.Embed` objects (with use of copy)

### The Ideal Solution

Make `name` kwarg of `set_author()` optional with default set to `EmptyEmbed`.
Make `url` kwarg of `set_image()` and `set_thumbnail()` optional with default set to `EmptyEmbed`.

### The Current Solution

The easiest but not supported one is accessing private attributes of `discord.Embed`.
Less easy one but supported would be using `to_dict()` and clearing image/thumbnail/author before using `from_dict()`

### Summary

I think there should be a way of clearing image/thumbnail/author of `discord.Embed` objects.

**Comment by jack1142** [comment]
Update: set_image() and set_thumbnail() now accept empty embed as a way to clear image/thumbnail (see #4053), only thing left for this issue is set_author()

**Comment by Harmon758** [comment]
This should be resolved with #4053 and #4068 in v1.4.0 and newer.
