### ISSUE TITLE
update function don't seems to work properly

### ISSUE THREAD

**Issue by desaleo** [Rapptz/discord.py#2613]
### Summary

hello. 
first of all sorry for my English i'm French. 
i encounter a problem when using the update function (discord.ext.commands.command.update) 
i want to modify the "help" attribute of a command with a decorator so i've done this:
```python
    @staticmethod
    def extra_help_for(mixin): #mixin is a command, a group or a Cog
        def inner(func):
            help = mixin.help
            mixin.update(help=help+"\n"+func())
            return func
        return inner
```
and i handle it like this:
```python
    async def send_command_help(self, command):
        await self.get_destination().send(embed=discord.Embed(title=command.qualified_name,
                                                              description=f"""{command.help if command.help else ""}\n\
                                                              **usage:**\n```{self.get_command_signature(command)}```""",
                                                              color=self.color)
                                                              .set_footer(text="arguments are: <required> [optional]"))
```

### Reproduction Steps

i've made a useless command to test:
```python
    @commands.command()
    async def test(self, ctx):
        """line 1 for test"""
        pass

    @Help.extra_help_for(test)
    def test_help():
        return "line 2 for test"
```

### Expected Results
me:
_help test
the bot:
line 1 for test
line 2 for test

### Actual Results

me:
_help test
the bot:
line 1 for test

### Little more

i have added some print in core.py line 219 and 228 in \_\_init__() to see what's append 
```python
        if self.name == "test": print("before", kwargs.get('help')) #here
        help_doc = kwargs.get('help')
        if help_doc is not None:
            help_doc = inspect.cleandoc(help_doc)
        else:
            help_doc = inspect.getdoc(func)
            if isinstance(help_doc, bytes):
                help_doc = help_doc.decode('utf-8')
        if self.name == "test": print("after", help_doc) #and here
        self.help = help_doc
```  
i expected four lines to be printed (two when the command is declared and two when my decorator call update who call \_\_init__) but eight appear:
```
before None
after line 1 for test
before line 1 for test
line 2 for test
after line 1 for test
line 2 for test
before None
after line 1 for test
```
how many time \_\_init__() is called and why? are commands re-declared when we call help? (my help class inherit from commands.HelpCommand)
and sorry if i dont use "update" the right way

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.8.1-final
- discord.py v1.3.2-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Windows 10 10.0.18362

**Comment by Rapptz** [comment]
`Command.update` is not meant to be used like this. If you want to update that attribute then update it the normal way. `Command.update` is basically an internal way of updating a copy of a command to fix certain issues with instances being shared across different classes.
