### ISSUE TITLE
Bot Starts but i cant use the command.

### ISSUE THREAD

**Issue by SwordSWD** [Rapptz/discord.py#2614]
I keep getting this error when i type !help and i dont know what to do 
INFO - Service server_help: Authorization Denied
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 56, in on_message
    await client.send_message(message.channel, result_message)
AttributeError: 'Client' object has no attribute 'send_message'

Can someone help me? Thanks.

**Comment by Harmon758** [comment]
`Client` no longer has a `send_message` method.
You're attempting to use syntax from v0.16.x of the library, which is no longer supported.
See [the guide for migrating to v1](https://discordpy.readthedocs.io/en/latest/migrating.html), specifically, the [Models are Stateful section](https://discordpy.readthedocs.io/en/latest/migrating.html#models-are-stateful).

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README also links.
