### ISSUE TITLE
Detecting emoji reaction, then editing message

### ISSUE THREAD

**Issue by ItCameFr0mMars** [Rapptz/discord.py#2616]
I have a long block of text that is being sent in one piece by a command. I want to split it into 2 pages, and add arrow emojis at the bottom. When a user clicks the right arrow, it edits the message and shows the second page. My code right now is this: `@bot.command()
async def text(ctx):
  msg = await ctx.channel.send('
 the text
  ')
  await msg.add_reaction('👍')
  @client.event
  async def on_reaction_add(reaction, user):
    if reaction.emoji('👍'):
      await reaction.channel.send('Test')`
I am unable to figure out how to edit the message when the user reacts to the message.

**Comment by zomatree** [comment]
this isn't a discord.py issue please ask questions in the [support guild](discord.gg/dpy). github issues are for actual issues with the library.

**Comment by ItCameFr0mMars** [comment]
the link is invalid

**Comment by zomatree** [comment]
https://discord.gg/dpy

**Comment by Harmon758** [comment]
There are a number of ways to do this. You could handle the event directly like you're attempting to do, but you'd need a way to store and access the message ID. Another way would be to wait for the reaction inside the command itself. Alternatively, you could look into using the experimental [menus extension](https://github.com/Rapptz/discord-ext-menus).

As explained though, this is not an issue with discord.py, and GitHub issues for this repository should be used to report issues with the library. For further help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README also links, if you haven't already.

For code block usage, see https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks.
