### ISSUE TITLE
Discord.py Music Queue

### ISSUE THREAD

**Issue by iNaruse** [Rapptz/discord.py#2625]
import discord
import re
import asyncio
import random
import openpyxl
import datetime
import pytz
import youtube_dl
import os

youtube_dl.utils.bug_reports_message = lambda: ''

ytdl_format_options = {
    'format': 'bestaudio/best',
    'outtmpl': '%(extractor)s-%(id)s-%(title)s.%(ext)s',
    'restrictfilenames': True,
    'noplaylist': True,
    'nocheckcertificate': True,
    'ignoreerrors': False,
    'logtostderr': False,
    'quiet': True,
    'no_warnings': True,
    'default_search': 'auto',
    'source_address': '0.0.0.0' # bind to ipv4 since ipv6 addresses cause issues sometimes
}

ffmpeg_options = {
    'options': '-vn'
}

ytdl = youtube_dl.YoutubeDL(ytdl_format_options)

class YTDLSource(discord.PCMVolumeTransformer):
    def __init__(self, source, *, data, volume=0.2):
        super().__init__(source, volume)

        self.data = data

        self.title = data.get('title')
        self.url = data.get('url')

    @classmethod
    async def from_url(cls, url, *, loop=None, stream=False):
        loop = loop or asyncio.get_event_loop()
        data = await loop.run_in_executor(None, lambda: ytdl.extract_info(url, download=not stream))

        if 'entries' in data:
            data = data['entries'][0]

        filename = data['url'] if stream else ytdl.prepare_filename(data)
        return cls(discord.FFmpegPCMAudio(filename, **ffmpeg_options), data=data)    

client = discord.Client()
que = {}
playerlist = {}
playlist = list()

def queue(id):
	if que[id] != []:
		player = que[id].pop(0)
		playerlist[id] = player
		del playlist[0]
                player.start()

ERROR: [matroska,webm @ 000001ae3f348700] File ended prematurely at pos. 267761 (0x415f1)

I want to save the que as -mqueue in the input, and then play the song registered as que when the song that was run with -mplay ends.

**Comment by Rapptz** [comment]
The issue tracker is not a place for code help or people writing your bot for you. If you have a concrete question regarding the library itself then feel free to open a new issue while following the issue template guidelines.
