### ISSUE TITLE
channel.topic return empty string instead of None

### ISSUE THREAD

**Issue by FightMan01** [Rapptz/discord.py#2632]
### Summary

When the `on_guild_channel_update` event runs and I use `before/after.topic` it return an empty string when no topic is set.

### Reproduction Steps

Use `on_guild_channel_update` event.

### Expected Results

It should return None.

### Actual Results

It returns an empty string.
### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.8.0-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Linux 5.3.0-40-generic #32-Ubuntu SMP Fri Jan 31 20:24:34 UTC 2020

**Comment by Rapptz** [comment]
There's nothing forbidding this behaviour at the API level so this is not a bug.
