### ISSUE TITLE
Raw Reaction Remove event will not trigger

### ISSUE THREAD

**Issue by MrGarlic1** [Rapptz/discord.py#2635]
### Summary

The raw reaction remove event does not trigger, even when used in the same way as the raw reaction add event.

### Reproduction Steps

The bug can easily be found with a simple event: While the first block of code works, the second block (raw remove event) will not trigger. This happens every time.
```
async def on_raw_reaction_add(payload):
    print("Hello")
```
```
async def on_raw_reaction_remove(payload):
    print("Hello")
```

### Expected Results
I expect the above block of code to print "Hello" whenever a message on a server has a reaction removed.

### Actual Results

The event does not trigger, and "Hello" is not printed to the console.

### Checklist

- [x] I have searched the open issues for duplicates.
- [ ] I have shown the entire traceback, if possible. (N/A)
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.7.0-final
- discord.py v1.3.2-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Windows 10 10.0.18362

**Comment by NCPlayz** [comment]
No repro. The event should dispatch as well as `raw_reaction_remove`. Are you sure you aren't just forgetting the `@bot.event` decorator?

**Comment by MrGarlic1** [comment]
Wow, I have no idea how I missed this. Fixed, thanks!
