### ISSUE TITLE
Type Annotations for library?

### ISSUE THREAD

**Issue by silasary** [Rapptz/discord.py#2647]
`ext.commands` already uses PEP 484 type hints in order to perform conversions.  Would it be possible to add type hints to the rest of the library so that users may perform type-checking against objects provided by discord.py?

I'm happy to do actually write the PR to add these, but I'd like to know if it is something that would be accepted before I go to that effort.

**Comment by slice** [comment]
Type hinting efforts live in issue #1497 at the moment.

**Comment by silasary** [comment]
Oh, sweet. I must have missed that when searching for previous efforts :)
