### ISSUE TITLE
I can't add a permission for just one person

### ISSUE THREAD

**Issue by DiaPikachu** [Rapptz/discord.py#2649]
So I made a command that is making a voice channel in a special category.
I want it that right after it makes the voice channel, the person who bought the voice channel gets a permission that makes him able to manage the voice channel.
This is the code:
```
@bot.command()
async def buy(ctx, to_buy=None):
    if to_buy != None:
        if to_buy == "vc":
            botserver = bot.get_guild(691981089903869963)
            VoiceChannelek_category = botserver.get_channel(697445352487518329)
            await ctx.channel.send("**Tessék Voice channel. c:**")
            await VoiceChannelek_category.create_voice_channel(
                name=f"{ctx.message.author} hangcsatornája",
            )
            overwrite = discord.PermissionOverwrite(manage_channels = True)
            await f"{ctx.message.author} hangcsatornája".edit_permissions(f"{ctx.message.author}", overwrite = overwrite)
        elif to_buy == "nick":
            await ctx.channel.send("**Változtasd meg.**")
        else:
            await ctx.channel.send("**Ilyen dolog nincs a boltban.**")
    else:
        await ctx.channel.send("**Valamit azért vegyél.**")
```

It's hungarian, don't check it. The problem is that it says:
'str' object has no attribute 'edit_permissions'
I was trying for a hole day without breaks. Please somebody help me...

**Comment by Phxntxm** [comment]
`f"{ctx.message.author} hangcsatornája".edit_permissions`

You are calling `edit_permissions` on a string here, this is not valid as the error says, `edit_permissions` isn't even a method that exists in the library. There is an `overwrites` parameter that you can use when creating a voice channel as noted here: https://discordpy.readthedocs.io/en/latest/api.html#discord.CategoryChannel.create_voice_channel

Also note a couple things, when posting code in a github issue please use codeblocks:
\`\`\`
code here
\`\`\`

Additionally, this is not an issue with discord.py.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.
For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by DiaPikachu** [comment]
Thank you, I think the overwrites parameter will work. I'm already joined the discord.py discord server.

**Comment by DiaPikachu** [comment]
And now when I tried it, it says it expects a dict, I know, I'm pretty annoying but I'm not English and even new to discord.py. So please help me.

**Comment by Phxntxm** [comment]
As mentioned in my last post, for this kind of help you would be better suited asking in the discord.py server, not in a github issue like this. Please ask in one of the help channels there if you've already joined and people will gladly help
