### ISSUE TITLE
Cannot install the library

### ISSUE THREAD

**Issue by VisiON4ALL** [Rapptz/discord.py#2651]

**Comment by VisiON4ALL** [comment]
![Снимок](https://user-images.githubusercontent.com/63402099/78889966-699ad480-7a6d-11ea-9bca-d1a625245191.JPG)

**Comment by TheRockettek** [comment]
sudo it.

**Comment by VisiON4ALL** [comment]
> sudo/run it in admin.

thanks,problem solved

**Comment by hamza1311** [comment]
You should *never* run pip commands with root/admin privileges. It creates security vulnerabilities. As the error message tells you, pip is running in unprivileged mode and does not have the permissions to write to the global packages directory. You should install it as user by using `--user` flag so the package is installed for your user, not globally
