### ISSUE TITLE
[WIP] AutoShardedClient redesign

### ISSUE THREAD

**Issue by Rapptz** [Rapptz/discord.py#2654]
I'm currently in the process of redesigning `AutoShardedClient` (and `AutoShardedBot`) to be more resilient and graceful when it comes to connections and the like.

The previous design had some timing issues with IDENTIFYs that caused for sessions to be invalidated too much due to IDENTIFYing too soon or concurrently. There is currently on-going work in this space under the [`sharding-rework` branch](https://github.com/Rapptz/discord.py/tree/sharding-rework).

Since I'm taking the time to redesign this code I also want to accommodate and remove need for big bot authors to touch internal code and provide hooks that allow for them to do things without stepping in the library's toes too much. 

The list of things that I have planned right now are as follows:

- [x] Switch to `aiohttp` instead of `websockets`
  - `websockets` has been giving me a lot of issues lately, 7.0/8.0/8.1 have been less than stellar and 6.0 is a bit too old by now.
- [x] Treat IDENTIFY as a first class citizen in the reconnection logic and queue them up to disallow concurrent IDENTIFY
- [x] Add an async hook that can be overridden before an IDENTIFY is sent with a signature of `async before_identify_hook(self, shard_id, *, initial)`
  - Multiprocess clusters of `AutoShardedClient` tend to need finer grained control over when they actually IDENTIFY
- [x] Rewrite the reconnection logic so every Shard has its own internal reconnection logic
- [ ] Add an async hook that can be overridden before a specific shard reconnects with a signature of `async before_reconnect_hook(self, retry_after, shard_id)`
- [ ] Allow manual reconnecting, disconnecting, and connecting of individual shards by IDs.
- [x] Add more shard related events (`on_shard_connect`, `on_shard_disconnect`, `on_shard_resumed`).

These signatures are subject to change depending on what people ask. Please use this issue if you have any feature requests pertaining to the `AutoShardedClient` and pain points you'd like to see amended.

**Comment by Gelbpunkt** [comment]
How's performance compared to websockes when using aiohttp for the websockets?
Also, do you need any help testing stability?

**Comment by FightMan01** [comment]
I found this issue with the voice channels.
```
[12/Apr/2020 16:29:36] ERROR - Disconnected from voice... Reconnecting in 18.97s.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/voice_client.py", line 258, in poll_voice_ws
    await self.ws.poll_event()
  File "/usr/local/lib/python3.8/dist-packages/discord/gateway.py", line 790, in poll_event
    raise ConnectionClosed(self.ws, shard_id=None)
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with None
```

**Comment by Rapptz** [comment]
That logging statement makes it seem like it'll reconnect. Voice stuff is unchanged outside of the websocket library being used and that should be fine.

**Comment by FightMan01** [comment]
> That logging statement makes it seem like it'll reconnect. Voice stuff is unchanged outside of the websocket library being used and that should be fine.

Yeah, it reconnects, but leaves immediately.

**Comment by FightMan01** [comment]
I discovered this issue with the latest build of the shard-rework branch.
When i disconnect my bt from the voice channel, the console prints this:
```
[14/Apr/2020 18:22:27] ERROR - Disconnected from voice... Reconnecting in 1.75s.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/voice_client.py", line 258, in poll_voice_ws
    await self.ws.poll_event()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/gateway.py", line 790, in poll_event
    raise ConnectionClosed(self.ws, shard_id=None)
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with None
```
And the bot joins back and disconnects and joins back....
So it does some reconnect loop.

**Comment by chwba** [comment]
https://github.com/Rapptz/discord.py/issues/4005 also relevant here

**Comment by chwba** [comment]
I see you fixed the above in the master branch. After manually implementing that fix into the current sharding-rework branch, that fixed it there as well but now there are numerous new errors.

Im getting lots of:
```
aiohttp.client_exceptions.ServerDisconnectedError
2020-04-18 18:53:23,670:ERROR:discord.client: Attempting a reconnect in 1.77s
```

and
```
aiohttp.client_exceptions.ClientOSError: [Errno 32] Broken pipe
```
as well as
```
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000
```

which leads to a lot of disconnects and reconnects

**Comment by Rapptz** [comment]
If the reconnection is being handled (notice how it's being logged) then there's nothing for me to do about your broken pipes or the server being disconnected since these are just networking errors on your end.

**Comment by chwba** [comment]
Interesting on that one is, that the old websocket-aiohttp-branch works perfectly stable without the modifications, that had been made

**Comment by PredaaA** [comment]
I noticed that I am getting that error sometimes on that branch. I'm not sure how to reproduce it since it happens completely randomly.
```py
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/discord/state.py", line 763, in _chunk_and_dispatch
    await self.chunker(guild.id)
TypeError: chunker() missing 1 required keyword-only argument: 'shard_id'
```

**Comment by Taarek** [comment]
> 
> 
> I noticed that I am getting that error sometimes on that branch. I'm not sure how to reproduce it since it happens completely randomly.
> 
> ```python
> Traceback (most recent call last):
>   File "/venv/lib/python3.8/site-packages/discord/state.py", line 763, in _chunk_and_dispatch
>     await self.chunker(guild.id)
> TypeError: chunker() missing 1 required keyword-only argument: 'shard_id'
> ```

https://github.com/Rapptz/discord.py/pull/4166 There is an open PR for this. Hopefully that'll resolve your issue, you could test their fork if it's happening frequently,

**Comment by PredaaA** [comment]
> > I noticed that I am getting that error sometimes on that branch. I'm not sure how to reproduce it since it happens completely randomly.
> > ```python
> > Traceback (most recent call last):
> >   File "/venv/lib/python3.8/site-packages/discord/state.py", line 763, in _chunk_and_dispatch
> >     await self.chunker(guild.id)
> > TypeError: chunker() missing 1 required keyword-only argument: 'shard_id'
> > ```
> 
> #4166 There is an open PR for this. Hopefully that'll resolve your issue, you could test their fork if it's happening frequently.

Thank you for your reply, I'm gonna try with this PR.
