### ISSUE TITLE
how do I move a member to a different voice channel

### ISSUE THREAD

**Issue by LoganDark2** [Rapptz/discord.py#268]
^

**Comment by LoganDark2** [comment]
@Rapptz

**Comment by SunDwarf** [comment]
http://bfy.tw/6iBM

**Comment by Maverun** [comment]
Nah that bad link
http://goo.gl/fNyjcb
this one work better.

**Comment by LoganDark2** [comment]
lmfao that's where I went @Maverun @SunDwarf and there's no function to move a member
http://discordpy.readthedocs.io/en/latest/api.html#member

**Comment by SunDwarf** [comment]
Client.move_member

**Comment by Maverun** [comment]
http://i.imgur.com/PyZIUa6.gif simple :D

**Comment by LoganDark2** [comment]
Oh.

**Comment by LoganDark2** [comment]
Thanks
