### ISSUE TITLE
Add a command extension API

### ISSUE THREAD

**Issue by Rapptz** [Rapptz/discord.py#27]
Something to help people make basic or even complex bots in a nice self-contained manner.

Roadmap in no particular order:
- [x] Allow composable creation of subcommands and commands.
- [x] Commands should use regular functions to figure out how they should be called.
- [x] A global error handler to capture errors in a more general and consistent way.
  - [x] Provide a way to have local error handlers as well to a specific command if needed.
- [x] Configurable command prefix.
  - [x] Dynamic command prefixes could be set by making it a callable.
  - [x] Command prefix could be a list to denote multiple prefixes.
- [x] Allow registration of "extensions" that allow you to load things from a different file and handles the unloading automatically.
- [x] Allow commands and such to be disabled or enabled dynamically.
- [x] Allow class-based categories that let you have some form of state per command.
- [x] Automatic generation of a `help` command that could be customised.
  - [x] Let people provide their own `Formatter` to change the output of help.
- [x] Allow multiple listeners for an event.
  - [x] This should be able to be used in the class based variant as well.
- [x] Allow people to set the strings in the help command for i18n.
- [x] A more deterministic cog unload function.
- [ ] A catch-all on_cog_command_error that triggers whenever a cog's command encounters an error.
- [ ] Write documentation for all of this.

**Comment by AraHaan** [comment]
Might need to add a option to remove ``help`` if they have another command with a different name that provides all of such info that would be in ``help``.

**Comment by EJH2** [comment]
@AraHaan Don't know if you still need it, but https://github.com/Rapptz/discord.py/blob/async/discord/ext/commands/bot.py#L155 would do the trick

**Comment by AraHaan** [comment]
@EJH2 hmm you happen to know why I am getting this as well? https://github.com/Rapptz/discord.py/issues/202

**Comment by iScrE4m** [comment]
Will you want to write the docs on your own or can we help?

**Comment by AraHaan** [comment]
tbh the docs are in the commands code files themselves. I think Rapptz wants that last thing doen and then he will start on the docs then.

**Comment by LoganDark2** [comment]
how do you make custom categories in the `help` command?

**Comment by EJH2** [comment]
@LoganDark2 to create custom categories for the help menu you have to create a class named the desired category name and then add your desired commands. After that's said and done you have to add it as a cog. An example coming from another one of Danny's repositories: https://github.com/Rapptz/RoboDanny/blob/master/cogs/mod.py#L13 and https://github.com/Rapptz/RoboDanny/blob/master/cogs/mod.py#509 and after *that* you have to register it in your main file if it isn't already there as shown in https://github.com/Rapptz/RoboDanny/blob/master/bot.py#16 and https://github.com/Rapptz/RoboDanny/blob/master/bot.py#115. Also, please open an issue.

**Comment by ButterCheezii** [comment]
@EJH2 You should get into the habit of using the file of a specific commit (preferably the latest), instead of the `master` branch, because lines will be added or removed thus making your answer invalid in the future.

**Comment by jokoast** [comment]
Hi @everyone, is it possible to make a bot that can take external calls from api ? How to set up the bot with the possibility to create a channel (for example) when my frontend asks it to do it via Flask(?) ? I don't know if it's understandable. (Sorry for the wrong place, but it's not an issue so ...)

Discord <--> Discord.api + Flask <--> My Front

**Comment by JeepartN** [comment]
how do i add a description for the different commands that ive added.
