### ISSUE TITLE
cannot ban a member that left the server

### ISSUE THREAD

**Issue by jonnyli1125** [Rapptz/discord.py#271]
revert to ``client.ban(server, user)``?

what usually happens is a spammer joins, then leaves the server. through the regular client, you can ban by right clicking on their name on the messages they left, but there's no way to get the member object with the bot if they left the server.

**Comment by Rapptz** [comment]
```py
member = discord.Object(id='user-id')
member.server = discord.Object(id='server-id')
```

**Comment by solsahar** [comment]
Thanks
