### ISSUE TITLE
on_message_edit content bug

### ISSUE THREAD

**Issue by NotSoSuper** [Rapptz/discord.py#273]
For some reason every message with a URL/Link the on_message_edit event is called and this happens to before.content and after.content,

before.content: "https://www.youtube.com/watch?v=UROVfmY3NTA&app=desktop"
after.content: "https www youtube com watch v urovfmy3nta app desktop"

My code doesn't touch anything relating to links or formatting in that way so it's the core code it's self.

**Comment by Rapptz** [comment]
Ran a bot printing `before.content, after.content` for 5 minutes and could not repro this. Sounds like an issue on your end.

**Comment by NotSoSuper** [comment]
this is my code, I don't see anything that would cause this lol
`	async def on_message_edit(self, before, after):
		try:
			if before.channel.is_private:
				return
			if before.content == after.content:
				return
			if before.author == self.bot.user:
				return
			sql = "SELECT server,channel FROM `logs` WHERE server={0}"
			sql = sql.format(before.server.id)
			cursor.execute(sql)
			result = cursor.fetchall()
			if len(result) == 0:
				return
			channel = result[0]['channel']
			server = result[0]['server']
			if before.server.id != server:
				return
			if before.channel.id == channel:
				return
			if len(before.content) > 2000:
				before.content = before.content[:2000]+"\n:warning: Message Truncated (<= 2000)"
			if len(after.content) > 2000:
				after.content = after.content[:2000]+"\n:warning: Message Truncated (<= 2000)"
			before.content = before.content.replace('@everyone', '@\u200beveryone').replace('@here', '@\u200bhere')
			after.content = after.content.replace('@everyone', '@\u200beveryone').replace('@here', '@\u200bhere')
			if len(before.mentions) != 0:
				for s in before.mentions:
					before.content = before.content.replace(s.mention, s.name)
			if len(after.mentions) != 0:
				for s in after.mentions:
					after.content = after.content.replace(s.mention, s.name)
			msg = "User: {0} <{1}>\n".format(before.author.name, before.author.id).replace("'", "")
			msg += "Channel: {0}\n".format(before.channel.name).replace("'", "")
			msg2 = "`Before`: \"{0}\"\n".format(before.content)
			msg2 += "`After`: \"{0}\"".format(after.content)
			target = discord.Object(id=channel)
			await self.bot.send_message(target, "`[{0}]`:warning: **Message Edit Log**\n".format(time.strftime("%I:%M:%S %p"))+cool.format(msg)+msg2)
		except discord.errors.Forbidden:
			self.remove_server(after.server)`

**Comment by billy-yoyo** [comment]
update discord.py, I had 100% reproduction before updating, now I can't reproduce it at all.

**Comment by NotSoSuper** [comment]
Great to know it's not my coding somewhere lol, thanks billy.

**Comment by klvbdmh** [comment]
Hope this will help identify and reproduce the bug.

**Steps to reproduce**

1. Run the following code (Python 3.5):

> import discord
> 
> client = discord.Client()
> 
> @client.event
> async def on_message_edit(before, after):
>     result = '''
> Edited message with ID: {}
> Before: {}
> After: {}'''.format(after.id, before.content, after.content)
>     await client.send_message(after.channel, result)
> 
> client.run('token')

where `token` is your bot token.
2. Invite bot to your server with all Text Permissions (523264)
3. In Discord client send a message with this content: `https://github.com/Rapptz/discord.py`
4. Send the above message again.
5. Send another message with a different link, for example `http://discordpy.readthedocs.io/en/latest/`

**Expected behavior**

We should see three messages:

1. (from user):
> https://github.com/Rapptz/discord.py

2. (from user):
> https://github.com/Rapptz/discord.py

3. (from user):
> http://discordpy.readthedocs.io/en/latest/

**Observed behavior**

Instead, we see five messages:

1. (from user):
> https://github.com/Rapptz/discord.py

2. (from bot):
> Edited message with ID: XXXXXXXXXXXXXX
> Before: https://github.com/Rapptz/discord.py
> After: https://github.com/Rapptz/discord.py

3. (from user):
> https://github.com/Rapptz/discord.py

4. (from user): 
> http://discordpy.readthedocs.io/en/latest/

5. (from bot): 
> Edited message with ID: XXXXXXXXXXXXXY
> Before: http://discordpy.readthedocs.io/en/latest/
> After: http://discordpy.readthedocs.io/en/latest/

**Comment by khazhyk** [comment]
@klvbdmh your observed behavior is the expected behavior

**Comment by klvbdmh** [comment]
But is it a desired behavior? 

* it's not documented
* the messages with embeds don't have `edited` tag visible in clients
* edited timestamps are None on both `after.edited_timestamp` and `before.edited_timestamp`
* `edit_message` function allows only editing the content of the message
* it's simply not in the spirit of editing as understood by users

Let's say I have a bot command that stores and retrieves the last edited message on each channel. If somebody sends a message with an embed and then call this command, it will return the message with an embed. It's not a behavior expected by the user of this command.

Is there any scenario where embeds are edited much later than sending the original message? If not, then I don't think embeds should be treated like edited messages.

**Comment by khazhyk** [comment]
You should bring up your concerns with the discord developers. All the wrapper does is relay the messages discord sends.

**Comment by klvbdmh** [comment]
I still think it's something that should be documented in the wrapper's documentation.

**Comment by khazhyk** [comment]
thats fair. you can add it

**Comment by klvbdmh** [comment]
[A reply from Discord dev](https://www.reddit.com/r/discordapp/comments/4xl5u1/discord_api_treats_messages_with_embeds_as_edited/d6gesoy):

> As far as how embeds work, we send the MESSAGE_CREATE event, then after we resolve the metadata for the embeds, a subsequent MESSAGE_UPDATE. We do not set edited_timestamp as the message is updated by the system to attach additional metadata.
> 
> A MESSAGE_UPDATE does not mean that the message was edited in all circumstances. It could mean that the embeds just got or that the message was pinned.

Seems like an update is not the same as an edit.

**Comment by khazhyk** [comment]
The message is more than the content, embeds are part of the message object.

**Comment by Rapptz** [comment]
I've updated the documentation to detail this case a little better since admittedly it can be confusing for those new to the Discord API.

https://github.com/Rapptz/discord.py/commit/83c7ba612edb8c1e5812688025d8e8fd5ddb5df6
