### ISSUE TITLE
Edit a message that contains a user metion

### ISSUE THREAD

**Issue by shrx** [Rapptz/discord.py#274]
Editing a message's content that contains a user mention does not work properly - the mention is not preserved.
For example, if the message content is `"edit me @botname"` and I edit the message with
```
contentReplaced = message.content.replace("edit me", "edited!")
yield from self.edit_message(message, contentReplaced)
```
It will be displayed as `"edited! <@botID>"`. How to fix this?

**Comment by Rapptz** [comment]
I don't get what you're asking.

@botname is not a mention. <@botid> is. The content is not touched on my end to "remove" mentions or anything of the sort. It is just a call that forwards an HTTP request to discord's end. 

Consider providing more information.

**Comment by shrx** [comment]
ah, sorry, I tested in the browser client and it appears it was an issue with an unofficial discord client.
