### ISSUE TITLE
client.move_member(member, channel), not working

### ISSUE THREAD

**Issue by zzzbatmand** [Rapptz/discord.py#277]
When i try to use the "client.move_member(member, channel)" command, nothing happens. There comes no errors and it doesn't crash, it just sits there and does nothing. It's like the command isn't even seen, why is this happening?

I have included a picture of my code where i use it.
![d65220d34a6b66a91bb5f1ec41926f18](https://cloud.githubusercontent.com/assets/15029818/17156683/5760a6e4-538b-11e6-9010-75d8421d6cb1.png)

**Comment by TickerOfTime** [comment]
@zzzbatmand Please read the docs next time. This has gotten so common we bet on it. `client.move_member` is a coroutine, that's all I'll say.
(Also, is that codeanywhere?)

![image](http://i.imgur.com/xqZLfpy.png)

**Comment by zzzbatmand** [comment]
.... Woow, I am so stupid, sorry for the stupid post. Thanks for your help anyway.

**Comment by zzzbatmand** [comment]
By the way i fixed it by typing "await" before the command so it became "await client.move_member(member, channel)".
