### ISSUE TITLE
Is it possible to run 2 bots at once with 1 script?

### ISSUE THREAD

**Issue by LoganDark2** [Rapptz/discord.py#279]
Hello, there is a command of another closed-source bot that can't be triggered by another bot. I use the bot account to clear the messages every time I want a user account to send a command to the bot. How do I do this?

**Comment by khazhyk** [comment]
You can run a bot on it's own thread. You will need to prepare the event loop on that thread, however.

```py

def my_thread():
  asyncio.set_event_loop(asyncio.new_event_loop())
  Bot().run("token")

Thread(target=my_thread).start()
```

I do believe you can also run two bots on the same event loop, although I haven't done that myself. Look at the source for client.run - I believe you can just run the client.start as a task.

**Comment by Rapptz** [comment]
Yes.

**Comment by marcoshuck** [comment]
Could you please give more information about this?

**Comment by Phxntxm** [comment]
This issue is closed and has been for nearly a year. Do not revive old issues.

**Comment by marcoshuck** [comment]
Sorry, I'll create a new one.
