### ISSUE TITLE
logs_from gets logs from the last 100 messages multiple times when limit >100

### ISSUE THREAD

**Issue by Saikimo** [Rapptz/discord.py#280]
So I want to extract the next 200 messages after a certain timestamp. I use the following code:

```Python
if message.content.startswith('!print'):
        command, time = message.content.split()
        utctime = convert_to_utc(time)
        logs = yield from client.logs_from(message.channel, limit=200, after=utctime)
        tmp = yield from client.send_message(message.channel, 'Collecting messages...')
        msg_counter = 0
        for msg in logs:
            print(msg.content)
        yield from client.edit_message(tmp, 'messages successfully collected')
```

I made for testing purposes a chatlog that counts up from 0 to 199

like this 
![image](https://cloud.githubusercontent.com/assets/16943959/17276466/cf13291c-572a-11e6-8921-d4d29c792cf2.png)

But after using `!print 13:31` to collect the 200 messages after 1:31 pm I get the following output:

[output.txt](https://github.com/Rapptz/discord.py/files/392390/output.txt)

Which are only the next 100 messages after 1:31 pm just collected twice.

**Comment by khazhyk** [comment]
What version of discord.py are you on?

**Comment by Saikimo** [comment]
Oh sorry I forgot to mention that:

Python is version 3.4.3 and discord.py is at 0.11.0

I installed via pip.

I'll clone the repo and test it there

**Comment by khazhyk** [comment]
I don't think logs_from works with more than 100 messages on 3.4. That it's repeating messages seems wrong though

**Comment by Saikimo** [comment]
Switching to 3.5 solved the problem for me.
