### ISSUE TITLE
player.volume not working

### ISSUE THREAD

**Issue by botiapa** [Rapptz/discord.py#283]
I'm using the player to play youtube music. Everything is working except the volume function. Here is the code:
                _ = int(num)/100
                print(_)
                player.volume(0)

it prints 0.5 and then throws a typerror.
thanks for helping me and sorry for my bad english.

**Comment by rksouthee** [comment]
shouldn't the line `player.volume(0)` be `player.volume = _`?

**Comment by botiapa** [comment]
Oh thank you
