### ISSUE TITLE
Need help with the create_ytdl_player

### ISSUE THREAD

**Issue by botiapa** [Rapptz/discord.py#284]
Here is the code:
http://pastebin.com/YLQrHWeC

Here is the log:
http://pastebin.com/m84wBA6B

I have 2 problems. First, it cannot run the "handle_musicbot" after the song is done because i need to put it in a coroutine but when i do it, it prints an error. Second when i type "!skip" in the discord chat,it won't start the music.

thanks for helping i'm new to this api.

**Comment by SunDwarf** [comment]
Revoke that token in your first link.

**Comment by Rapptz** [comment]
http://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-pass-a-coroutine-to-the-player-s-after-function

**Comment by botiapa** [comment]
thank you
