### ISSUE TITLE
The after parameter is not being called when the sound file ends.

### ISSUE THREAD

**Issue by botiapa** [Rapptz/discord.py#293]
I'm using the "create_ytdl_player()" method. The song plays but when it ends it won't call the method in the after parameter.

Here is the after method:

def after():
    global musicqueue
    global namequeue
    print("alma 3")
    coro = handle_musicbot()
    asyncio.run_coroutine_threadsafe(coro, client.loop)
    if len(musicqueue) == 0:
        yield from client.send_message(client.get_channel("141083656247705600"), "LemonBOT: Queue completed.")

**Comment by JohnDeCorato** [comment]
https://github.com/Rapptz/discord.py/blob/master/discord/voice_client.py#L113

**Comment by JohnDeCorato** [comment]
http://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-pass-a-coroutine-to-the-player-s-after-function
