### ISSUE TITLE
Unclosed client session error

### ISSUE THREAD

**Issue by lluisrojass** [Rapptz/discord.py#296]
even when i strip everything down to this

`import discord`
`client = discord.Client()`
`client.login("******","*******")`

i'm still getting

`'Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10365a518>'`

also somethings up with the login method. i can feed it any 2 strings and it won't raise a LoginFailure. at the same time is_logged_in turns up false no matter what. also will note i am running python 3.5.

**Comment by imayhaveborkedit** [comment]
Whatever you got that code from is horribly outdated.  https://github.com/Rapptz/discord.py/tree/master/examples

**Comment by Rapptz** [comment]
`client.login` is a coroutine. You have to manage the event loop yourself if you wish to use it.

It's better to use `client.run` instead.
