### ISSUE TITLE
Can't make [whatever it's called] argument optional

### ISSUE THREAD

**Issue by LoganDark2** [Rapptz/discord.py#298]
I don't know how to describe it so i'll give an example

Here's what I want to do:

I want to make `reason` in `async def kick(ctx, member : discord.Member, *, reason: str)` optional.

If I try to use `async def kick(ctx, member : discord.Member, *, *reason: str)`, it causes an error.

Can I have a solution to this?

**Comment by LoganDark2** [comment]
@Rapptz

**Comment by PapyrusThePlant** [comment]
Define a default value for the parameter and the command ext will consider it optional.
See more on function arguments there : https://docs.python.org/3.5/tutorial/controlflow.html#more-on-defining-functions

**Comment by LoganDark2** [comment]
Thanks!

**Comment by LoganDark2** [comment]
@PapyrusThePlant actually, do i do it `reason = None : str` or `reason : str = None`?

**Comment by Rapptz** [comment]
Latter.

**Comment by LoganDark2** [comment]
thanks
