### ISSUE TITLE
Need help categorizing commands in the help menu

### ISSUE THREAD

**Issue by LoganDark2** [Rapptz/discord.py#299]
[These instructions](https://github.com/Rapptz/discord.py/issues/27#issuecomment-237999369) aren't very easy to follow (for me), so can I have a quick example of how to categorize commands in the help menu? I need a really small and simple example.

Thanks in advance.

**Comment by ccubed** [comment]
Commands are categorized based on which cog they are a part of. That's the quick and simple explanation.

**Comment by LoganDark2** [comment]
maybe an example? i have no idea how to do cogs or anything like that.

"can I have a quick example of how to categorize commands in the help menu?"

**Comment by Helehelehele** [comment]
https://gist.github.com/leovoel/46cd89ed6a8f41fd09c5

**Comment by LoganDark2** [comment]
"quick and simple"

like a bot with 1 category with a single command in it, like 'test' or something

**Comment by Helehelehele** [comment]
Did you read the example?

**Comment by LoganDark2** [comment]
i'm too dumb to strip down your example

**Comment by ccubed** [comment]
That is quick and simple. The categories in that example would be RNG and Members. How much simpler do you want it?

**Comment by LoganDark2** [comment]
1 category with a single command in it and an extremely simple function to load it?

**Comment by LoganDark2** [comment]
i'm feeling like simple is too much to ask

**Comment by Helehelehele** [comment]
I'm feeling like you are not even reading the example.

**Comment by LoganDark2** [comment]
ok fine ill spend time stripping it down

**Comment by LoganDark2** [comment]
thanks
