### ISSUE TITLE
Snowflake IDs should not be strings

### ISSUE THREAD

**Issue by Rapptz** [Rapptz/discord.py#301]
Currently IDs are implemented as `str` because that is what the API returns it as. This can lead to some confusion or storage woes depending.

In reality, IDs are snowflakes which are 64-bit unsigned integers. So they should ideally be at least `int`. This comes with certain benefits:
- Faster hashing (O(1) vs O(n))
- Faster comparisons (O(1) vs O(n))
- Less memory consumption (28-36 bytes vs 49 + 16-19 bytes)

The standard `json` module allows for 64-bit integers as values, but the `json` module does not allow `int` keys since the JSON spec only allows string keys. Due to this, there may be some woes from the user end if they're using JSON storage using IDs as keys. Said users should cast it to `str` instead.

A proposed question must be taken into consideration before going through with this change in the future:
- Should the ID type be `int` or a subclass of `int` (i.e. `Snowflake`) with certain member functions?

The memory consumption of an ID if the type was `int` would be 28-36 bytes but it would increase to 52-60 bytes if it was a subclass. Otherwise the subclass would behave the same as the `int`.

**Comment by jaydenkieran** [comment]
+1 to `int`

**Comment by Helehelehele** [comment]
`int`. Handling JSON, etc. should be user's job.

**Comment by GusCaplan** [comment]
i think this basically comes down to if you want to build the library on catering to people who expect something to be a certain way. `int` seems easiest for the most people, but `snowflake` seems like it would have more utility

**Comment by leovoel** [comment]
> more utility

it would be the same thing as having `int`s and free functions that manipulate them (snowflake -> datetime etc.).

the only thing is that the class name specifies what they're for, so you expect them to have a certain purpose. but you can express that intent in the documentation too.

either way both approaches are more efficient than strings, so any of the two (`int` or `int` subclass) options work for me.

**Comment by ccubed** [comment]
IDs should be INTs. If you want to make a class out of it and incorporate the time of creation and other such utility functions then that would be fine too I think. However, I don't think it's your responsibility to code concessions for the programmers choice of data storage.

**Comment by LoganDark4** [comment]
+1 for custom class.

**Comment by treefroog** [comment]
I vote for a subclass of `int`, most likely `snowflake` because while it doubles its size, it is still relatively small and it defines what it is clearer.

**Comment by Socialery** [comment]
can just use `__slots__` if the size is much issue

```python
class A(int):
    __slots__ = ()
sys.getsizeof(int('1'*64,2))    # 36
sys.getsizeof(A(int('1'*64,2)))    # 36 apparently
```

But then that'd also stop users throwing random data onto the object, which might be unexpected
