### ISSUE TITLE
Server vs Guild

### ISSUE THREAD

**Issue by Rapptz** [Rapptz/discord.py#302]
At the moment the API wrapper calls what the API internally calls "guilds" as "servers" due to the UI association with a "guild" being called a server. This is a left over from the library being written as a reverse engineer attempt from the beginning.

Should `Server` and all instances of `server` be renamed to `Guild` and `guild` respectively to be more consistent with the API terminology?

You cannot have both naming schemes and I'm only going to count votes from this issue.

**Comment by SunDwarf** [comment]
I vote `Guild` as it's consistent with API terminology

**Comment by GusCaplan** [comment]
i think that guilds makes sense because it's how the official refers to it.

**Comment by martmists** [comment]
I vote server because I don't think we should fix something that isn't broken

**Comment by GetRektByMe** [comment]
I'd go for `Guild` because it'd match how the API refers to it

**Comment by Helehelehele** [comment]
`Guild`, thanks.

**Comment by Phxntxm** [comment]
I vote for Guild, keep the library consistent with how Discord itself calls it.

**Comment by Twentysix26** [comment]
As much as I dislike the word, `guild` for consistency with the API

**Comment by Emoticon** [comment]
`Guild`.

**Comment by Maverun** [comment]
`Guild` 
it is gonna be biggest break change for covert server object to guild lol

**Comment by NotSoSuper** [comment]
`Server`, this will be the biggest search and replace I'd have to do if renamed...

**Comment by Helehelehele** [comment]
@NotSoSuper It's for a rewrite, you'll have to rewrite most of your code anyways.

**Comment by ccubed** [comment]
As much as I hate the Guild structure,  a wrapper should mirror what it abstracts. So Guild here too.

**Comment by logandark3** [comment]
`guild` _and_ `server`

**Comment by NotSoSuper** [comment]
@Helehelehele how so? Afaik he's only changing the server class name to guild.

**Comment by jaydenkieran** [comment]
@NotSoSuper The entire lib is going through a rewrite

**Comment by Helehelehele** [comment]
@NotSoSuper see https://github.com/Rapptz/discord.py/milestone/5

**Comment by NotSoSuper** [comment]
thanks, was unaware of that.

**Comment by PapyrusThePlant** [comment]
I'm team 'server'.

As evoked in discord, the permissions have different names too, "Manage Server" vs "Manage Guild", etc. As much as being consistent with the api is nice, being consistent with the UI and what people are used to see feels more right.

Only people that are used to discord's docs might get confused, others will look at this lib's docs and never even know they have a different name.

If you go the "api consistency" way, I can already feel the "how do I check if someone has the manage server permission???" coming.

**Comment by daveter9** [comment]
I'd go with Guild as well.

**Comment by Helehelehele** [comment]
@PapyrusThePlant you can't cure ignorance. People get into d.py channel without knowing any programming languages. They are the ones who need to adapt, not the lib.

**Comment by abalabahaha** [comment]
`Guild` would be nice

**Comment by Maxie01** [comment]
I'm going with Server. I agree with Papyrus.

**Comment by james9837** [comment]
My 2 cents even though I just started... 'Server' 
- it works as-is
- API is inconsistent with UI anyway and the guild<->server mapping is even noted in the developer docs @ https://discordapp.com/developers/docs/resources/guild as: Guilds in Discord represent a collection of users and channels into an isolated "server".
- Add in the comments for relevant items something along the lines of "Note: the discord api refers to servers as guilds"

In the end, it doesn't really matter all that much. IF the decision is made to go with 'guild' then I'd suggest the reverse of the item above... "Note: the discord UI refers to guilds as servers"

**Comment by treefroog** [comment]
I vote `Guild` for consistency :smile:

**Comment by Pandentia** [comment]
I'd have to vote `Guild` too, as it's what the documentation and actual CSS use. I dislike the use of the word internally as I feel they're still servers, but it makes more sense from the official API point of view.

**Comment by megumisonoda** [comment]
+1 for `Guild` from me

**Comment by ngbeslhang** [comment]
Following the majority.

**Comment by tkdberger** [comment]
Screw it. `Guild`.

[Also, I made a strawpoll in case anyone wants to use it.](http://www.strawpoll.me/11420396/)

**Comment by hydrabolt** [comment]
If it's not too late, discord.js switched from Server to Guild between version 8 and 9

**Comment by abalabahaha** [comment]
discord.py isn't discord.js

**Comment by fwrs** [comment]
is this abandoned

**Comment by hydrabolt** [comment]
Abal I know but I thought it might help Danny as most of our users didn't care too much that it changed, he may choose to leave it the same for the sake of backwards compatibility but I believe he might as well change it now

**Comment by abalabahaha** [comment]
Your first message currently just states that discord.js switched from Server to Guild, and doesn't offer any reasoning or suggestions to go with that. Adding your reasoning ("most of our users didn't care too much that it changed") to that could have made it a bit more useful and seem less like "discord.js did this so discord.py should do this too".

**Comment by fwrs** [comment]
abal stop

**Comment by hydrabolt** [comment]
Sorry hope my further comment cleared it up

**Comment by Rapptz** [comment]
I already changed it to guild in the rewrite I have locally.
