### ISSUE TITLE
blocked from posting issues

### ISSUE THREAD

**Issue by logandark3** [Rapptz/discord.py#303]
My main account was blocked from posting issues. I don't believe I did anything wrong, please tell me why. I'd prefer to be unblocked, as i have a multitude of questions.

**Comment by logandark3** [comment]
@mgardne8 wew lad don't be too hasty ( ͡° ͜ʖ ͡°)

**Comment by NotSoSuper** [comment]
Join discord api server and ask there, no need to open unneeded issues on the github if they aren't related to bugs in the library or something along those lines. TL;DR: This isn't your help center.

**Comment by Rapptz** [comment]
He's banned from the API server too.
