### ISSUE TITLE
I have 3 questions

### ISSUE THREAD

**Issue by logandark3** [Rapptz/discord.py#305]
My main account was blocked from posting issues, so I'm going to post this here:

I have 3 questions.

### First question

Is it possible to change the arg name that is displayed in the help menu?

For example, I will use `!!help purge` (or whatever prefix/command), and I want to get this result:
```
!!purge <amount of messages>

Purges specified amount of messages, from 1 to 100. You must count the purge command as a message.
```
Note instead of the variable name used in the function, it says `amount of messages`.

This will be useful for my purge command.

### Second question

Is it possible to allow 2 different types? And if so, is it possible to display them in the help menu as 1 argument?

It's a confusing summarization, but let me walk you through what I'm trying to do:

For a `purge` command, I want to allow either a `discord.Member` or an `int` to be passed. I also want it to display as this, also taking inspiration from the first question:
```
!!purge <amount of messages | member> [amount]
```

This will be useful, obviously, for the purge command.

[removed third question because it was solved in the server]

**Comment by martmists** [comment]
> My main account was blocked from posting issues

inb4 ban for ban evasion

**Comment by Phxntxm** [comment]
It's funny that...when answered, you refuse to accept the answer, insult me, then ask again.

**Comment by logandark3** [comment]
I don't try to insult you. I'm sorry if it seemed that way, but sometimes I don't want to make the answer work

**Comment by logandark3** [comment]
no more need for this question, and nobody is responding. closing. thanks @abalabahaha for hating on me.
