### ISSUE TITLE
Joining a voice channel

### ISSUE THREAD

**Issue by TimHi** [Rapptz/discord.py#306]
Hi, i'm currently running into the issue that my Bot isnt joining the voice channel. I have simple code example to test it: 

```
import discord
from opus_loader import load_opus_lib
load_opus_lib()
client = discord.Client()



def joinVoiceChannel():

    channel = client.get_channel('RIGHT_CLICK_ID_FROM_VOICE_CHANNEL')
    voice = client.join_voice_channel(channel)
    print('Bot should joined the Channel')


@client.event
async def on_ready():
    print('Logged in as')
    print(client.user.name)
    print(client.user.id)
    print('------')
    joinVoiceChannel()

client.run('TOKEN')
```

It runs through the function and prints the message but doesnt join. 
Greetings

**Comment by Rapptz** [comment]
http://discordpy.readthedocs.io/en/latest/faq.html#what-is-a-coroutine

**Comment by TimHi** [comment]
I changed the line to:
`    voice = yield from client.join_voice_channel(channel)`
But now the function isnt executed at all. 
Or do i need to make it a async function and use await? I saw in the [documentation](http://rapptz.github.io/discord.py/async/api.html?discord.LoginFailure#discord.VoiceClient.create_ffmpeg_player)
That you used yield from.

**Comment by Rapptz** [comment]
`async def` and then `await` yes.

**Comment by TimHi** [comment]
Working as intended now, cheers!

**Comment by Antipire** [comment]
How could I install opus_lib?

**Comment by avrwhy** [comment]
Whats the code that works? @TimHi

**Comment by TimHi** [comment]
```
#Call Bot to your voice channel
    @commands.command(pass_context=True)
    async def summon(self, ctx):
        channel = discord.utils.get(ctx.message.server.channels, type=ChannelType.voice)
        self.voice = await self.bot.join_voice_channel(channel)
```
@avrwhy I switched to Discord4J and wrote my Bot in Java so this might not be up to date but this is the working join function from my old code, hope it helps you.

**Comment by popeyaho** [comment]
how to do that with new api updated?

**Comment by MinerChAI** [comment]
Better go to [support guild](https://discord.gg/r3sSKJJ)
