### ISSUE TITLE
How to ack a message

### ISSUE THREAD

**Issue by logandark3** [Rapptz/discord.py#307]
How do I acknowledge a message (mark as read)?

Also, is there a way to ack a server?

**Comment by Maverun** [comment]
May I ask that can you be more clarify on this? This is quite a vague at the moment...

**Comment by logandark3** [comment]
By scrolling to the bottom of unread messages on a channel, you are "acknowledging" (marking as read) all those messages. By sending a message, this also happens.

**Comment by logandark3** [comment]
Bot accounts cannot acknowledge messages.

**Comment by Marqin** [comment]
You want to mark all messages as read without getting them?

like using this?
![zrzut ekranu 2016-08-20 o 00 44 11](https://cloud.githubusercontent.com/assets/959429/17826270/3eedef3a-666f-11e6-821b-101dcbf3871a.png)

**Comment by Maverun** [comment]
Are you talking about bot?

**Comment by logandark3** [comment]
@Marqin Yes exactly like that but automated. I am in too many servers to mark them all as read manually.

**Comment by logandark3** [comment]
@Maverun Selfbot.

**Comment by Marqin** [comment]
Ok, now we know what you mean. (btw. you can use "mute server"/"mute channel" for this in Discord interface)

**Comment by logandark3** [comment]
Ik

**Comment by Maverun** [comment]
As far as I recall, I don't think it is possible to auto mark message/server as read.
I can't find this in doc atm.

**Comment by logandark3** [comment]
yeah, same.

**Comment by Maverun** [comment]
If it not in doc, then it is not possible.

**Comment by logandark3** [comment]
I'll look into a method of acking messages. I know Discordia has such a feature, maybe I could make a pull request?

**Comment by logandark3** [comment]
Thanks anyway.

**Comment by Bluscream** [comment]
https://github.com/Bluscream/Discord-Selfbot/blob/config-manager/cogs/utils/api.py#L53
