### ISSUE TITLE
`Message` class is not an `awaitable` class.

### ISSUE THREAD

**Issue by urda** [Rapptz/discord.py#310]
The `Message` class does not implement `__await__`, and causes linting errors since it's not an [awaitable](https://docs.python.org/3/glossary.html#term-awaitable).

I believe implementing [__await__](https://docs.python.org/3/reference/datamodel.html#object.__await__) corrects this.

![wt_await](https://cloud.githubusercontent.com/assets/1648492/17840776/f8dab2c0-67c3-11e6-8434-f30a5081c2b1.png)

**Comment by SunDwarf** [comment]
ignore the inspection

pycharm is stupid

**Comment by jaydenkieran** [comment]
pycharm is the reason we can't have nice things

**Comment by urda** [comment]
Less of a PyCharm thing and more of a [PEP 492](https://www.python.org/dev/peps/pep-0492/#await-expression) but whatever.

**Comment by SunDwarf** [comment]
No it isn't

PyCharm parses the `Returns` comment in the docstring, without seeing that it's a coroutine.

It doesn't apply the coroutine detection properly. Hence why it thinks the function returns that bare object.

**Comment by ccubed** [comment]
https://github.com/Rapptz/discord.py/blob/master/discord/client.py#L780

send_message is indeed a coroutine. Yes.
