### ISSUE TITLE
Bot works fine when running from single .py file, but when I split it across multiple files I get a HTTP 401 error when trying to send messages.

### ISSUE THREAD

**Issue by jrkanu** [Rapptz/discord.py#311]
As the title says, whenever I try to organize my code across multiple files, my bot can no longer send messages. The bot will successfully log in and show online, but when it tries to send a message it raises an HTTP 401:Forbidden error. I don't know if the issue is with Discord (the service) or discord.py (the library) but I figured I would ask here just in case. 

I'm thinking that perhaps the issue is with how I am importing my modules or invoking the client.run() command, but when I looked at R. Danny's source code I couldn't spot the relevant difference (if there is one).

My two files are woomy.py and commands.py, here are abbreviated snippits from both.

woomy.py:
```
import discord
import asyncio
import logging
import commands

logging.basicConfig(level=logging.DEBUG)

bot = discord.Client()

@bot.event 
async def on_ready():
    
    print("----------------------------")
    print("Success! Logged in as {}.".format(bot.user.name))
    print("----------------------------")
    
@bot.event
async def on_message(message):
    
    if message.content.startswith(';'):
        await commands.route_command(message)

def main():
    
    bot.run('<my token>')
    
if __name__ == "__main__":
    main()
```

commands.py:
```
import discord
import asyncio
import woomy

async def route_command(message):
    # Routes commands to the proper function.
    
    if message.content.startswith(";test"):
        await test(message)
        
async def test(message):
    print('test command ran')
    await woomy.bot.send_message(message.channel, "Hi, {}! Did I pass the test?".format(message.author.mention))
```
And this is the error log after a failed message attempt when I run the ;test command:
```
DEBUG:discord.client:Dispatching event message
test command ran
DEBUG:discord.http:POST https://discordapp.com/api/v6/channels/000/messages with {"content":"Hi, <@000>>! Did I pass the test?","nonce":-000} has returned 401
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/near/.local/lib/python3.5/site-packages/discord/client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "woomy.py", line 76, in on_message
    await commands.route_command(message)
  File "/home/near/Documents/Python Projects/Woomy/commands.py", line 11, in route_command
    await test(message)
  File "/home/near/Documents/Python Projects/Woomy/commands.py", line 18, in test
    await woomy.bot.send_message(message.channel, "Hi, {}! Did I pass the test?".format(message.author.mention))
  File "/home/near/.local/lib/python3.5/site-packages/discord/client.py", line 825, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts)
  File "/home/near/.local/lib/python3.5/site-packages/discord/http.py", line 137, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: UNAUTHORIZED (status code: 401): 401: Unauthorized
```
(replaced ID numbers with zeros but everything else should be the same)

Any help in this matter would be greatly appreciated, as I would rather not have to keep all the code for the bot in one big unwieldy file! Thank you.

**Comment by SunDwarf** [comment]
I don't see anything immediately wrong but this is almost definitely because of circular imports.

The better way to do this is to pass your `client` to `route_commands` and to your command so that you have the correct bot instance all the time.

**Comment by jrkanu** [comment]
Thank you for the quick reply! Removing the ```import woomy``` statement from commands.py and instead passing the client as an argument did indeed fix the problem! Much appreciated, SunDwarf!
