### ISSUE TITLE
Predicates are being added to the help command

### ISSUE THREAD

**Issue by logandark3** [Rapptz/discord.py#313]
Whenever I use the decorator `@commands.check(Checks.is_owner)` on a command, the `help` command mysteriously starts using that check. However, other commands still work fine. Am I doing something wrong here?

```py
# checks for owner, permissions, etc
class Checks:
    def is_owner(ctx):
        Utils.log('CHECK', 'is_owner check running for command {0}'.format(ctx.invoked_with))
        if ctx.message.author.id in Config.bconfig('ownerids'):
            return True
        else:
            Utils.aawait(Utils.smsg(Enum.Message.Error, ctx, 'You aren\'t an owner.'.format(perm)))
        return False
    # snip rest
```
```py
class Owner():
    def __init__(self):
        pass

    @commands.command(pass_context = True)
    @commands.check(Checks.is_owner)
    async def test(self, ctx):
        await bot.say('This is working!')
```

**Comment by khazhyk** [comment]
you can pass dict(show_check_failure=True) for the help_attrs param for the bot.
https://github.com/Rapptz/discord.py/blob/master/discord/ext/commands/bot.py#L189-L194

**Comment by logandark3** [comment]
I don't want this check to be applied to the help command. How do I fix this?

**Comment by khazhyk** [comment]
you can pass dict(show_check_failure=True) for the help_attrs param for the bot.
https://github.com/Rapptz/discord.py/blob/master/discord/ext/commands/bot.py#L189-L194

**Comment by logandark3** [comment]
What good will showing check failures do? How will it help? I don't want checks to be added to the help command ***at all***!

**Comment by khazhyk** [comment]
Look bud, if you can't handle having the answer literally handed to you, I'm not really sure what else to do.

This might help you understand better:
https://github.com/Rapptz/discord.py/blob/master/discord/ext/commands/formatter.py#L126-L128

**Comment by logandark3** [comment]
***That is not the answer. I am not looking for how to show check failures. As I specifically said multiple times, I AM LOOKING TO REMOVE CHECKS FROM THE HELP COMMAND.***
