### ISSUE TITLE
create_ytdl_player stream crashes

### ISSUE THREAD

**Issue by s0hvaperuna** [Rapptz/discord.py#315]
This is the error message I'm getting

`[tls @ 0500eb60] Error in the pull function.`
`[matroska,webm @ 0501c500] Read error`
`[tls @ 0500eb60] The specified session has been invalidated for some reason.`
`    Last message repeated 1 times`

It doesn't happen all the time though. Usually the first video plays just fine without problems. The video after that might play well but usually after that this error comes and snowballs to every video in the playlist that's left basically emptying the queue. 

The videos that get this error in the snowball effect usually play for a fraction of a second before it moves to the next video on the queue. 

I have looked at issue #157 but that hasn't been of any help since I have the latest versions of everything as of today. (I am using ffmpeg btw because avconv had the same issue as in #157)

**Comment by SunDwarf** [comment]
Redownload the URLs.

This is because the old URLs are no longer valid.

**Comment by s0hvaperuna** [comment]
How can you redownload the urls? I don't think I get it

**Comment by s0hvaperuna** [comment]
OK now its mostly fixed. I just added this line to `audio_player_task` in the `VoiceState` class

`self.current.player = await self.voice.create_ytdl_player(self.current.player.url, ytdl_options=self.opts, after=self.toggle_next)`

This seems to get the new download_url and works way more consistently. The error still comes sometimes but it doesn't cause the whole playlist to end now. Just one video will be skipped where the URL has expired. I have not tested this with long videos yet so I'm not sure how this fix is gonna affect those. I'll try to update the post when I have tested at those

**Comment by s0hvaperuna** [comment]
Just tested it with an hour long video and it played almost all of it. Maybe ten or so seconds ware dropped out because the URL expired. Gonna close this now since I cannot change the fact that youtubes direct video links expire want it or not.

**Comment by Vadyy** [comment]
Hey, @s0hvaperuna , I have the same issue with the latest ffmpeg and yt-dl, you seem to have almost fixed it, but I don't quite understand how, Can you please elaborate on how you did it?
I'm getting these errors:
![image](https://cloud.githubusercontent.com/assets/20133506/22756112/c66d7252-ee4e-11e6-8609-c6a02df622fc.png)

**Comment by s0hvaperuna** [comment]
@Vadyy I solved it completely by downloading the file first and then playing it. Also I think your problem is a bit different from mine since you are getting errors when trying to read from the socket. 

Can you tell the steps to reproduce this. I'll look into more detail on it tomorrow.

**Comment by s0hvaperuna** [comment]
@Vadyy So I reproduced the issue and this time I got the same error messages as you did, so I guess the problem is related. So now I'm gonna recommend that you download the files before playing, so you don't have to worry about that problem again. If you need help on how to do that, send me a message on discord s0hvaperuna#4758

**Comment by corpnewt** [comment]
@s0hvaperuna I've been having the same problem as @Vadyy for the past few days now (on a bot that's been running for 6 months or so).  I sent you a friend request on Discord - if you wouldn't mind walking me through the fix either here or there, I'd really appreciate it.  Thank you!

**Comment by s0hvaperuna** [comment]
I found an alternative solution for this problem that doesn't involve downloading the file. Add this to the `before_args` `" -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5"`

**Comment by corpnewt** [comment]
Hm... I had seen that before as well, but I get "Option reconnect not found." in the console when trying to use it.  Does it not work when pulling from the stdOut of youtube-dl?  With the rewrite branch of discord.py, I'm just using a subprocess wrapper around youtube-dl to pipe the audio stream.  Maybe I could subclass AudioSource - but that'd take some digging.

**Comment by s0hvaperuna** [comment]
@corpnewt try using the latest ffmpeg version

**Comment by corpnewt** [comment]
Yeah - same issue.  I'm on Windows, and I grabbed the static binaries from 5/2/2017 (which are the newest as of today) - but I get the same error.  I'll look more into it and see what I can figure out.

**Comment by matthew-morrison** [comment]
@s0hvaperuna I am having a similar problem, can you explain what the `before_args` is? I tried adding these options to the opts for the create_ytdl_player() and it hasn't solved my issue.

**Comment by Primus92** [comment]
@matthew-morrison you do it like this: 
`beforeArgs = "-reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5"
create_ytdl_player(url=self.url, ytdl_options=self.ytdl_format_options, before_options=beforeArgs)`
then it works.

**Comment by matthew-morrison** [comment]
Thanks a bunch @Primus92 !

**Comment by SSUHan** [comment]
If you use Ubuntu 16.04, ffmpeg is normally installed version 2.8~. 

However, This ffmpeg version didn't include "reconnect_streamed" and "reconnect_delay_max"..

So you need to upgrade your ffmpeg version to 3.. I'm using followed way and works well !

sudo add-apt-repository ppa:jonathonf/ffmpeg-3 -y
sudo apt update
sudo apt install ffmpeg -y

references : 
http://blog.programster.org/ubuntu-16-04-install-ffmpeg-from-ppa
https://github.com/qeled/discordie/issues/62

**Comment by IllidanS4** [comment]
I am facing the same issue; a link is downloaded, but ffmpeg stops downloading it after some time. This started happening recently, and I have done no changes to the system.

**Comment by iColdZ** [comment]
Thanks !
I used ffmpegopts = {
    'before_options': '-nostdin -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5',
    'options': '-vn'
} and it worked.

**Comment by iColdZ** [comment]
> @ matthew-morrison você faz assim: 
> `beforeArgs = "-reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5" create_ytdl_player(url=self.url, ytdl_options=self.ytdl_format_options, before_options=beforeArgs)`
> então funciona.


I do not understand, where do I use these options? In ffmpegopts?
send friend in discord :cry: iColdZ#1159

**Comment by Harmon758** [comment]
@iColdZ I'm not sure what you're asking.
In what you quoted, they outlined how to use those specific options in `beforeArgs` by passing them as the `before_options` kwarg parameter to [`create_ytdl_player`](https://discordpy.readthedocs.io/en/latest/api.html#discord.VoiceClient.create_ytdl_player).

**Comment by mellodoot** [comment]
Using the `beforeArgs` worked great for me, however while I'm not recieving ffmpeg errors anymore, the `tls` errors remain. My bot essentially stops after that - it's still running, but any attempts to interact with it do nothing.

This is what I'm getting instead:
```[tls @ 0000024af62cc480] Error in the pull function.
[https @ 0000024af62cc900] Will reconnect at 2834416 in 0 second(s), error=I/O error.
[tls @ 0000024af8282c80] Error in the pull function.
[https @ 0000024af62cc900] Will reconnect at 3309552 in 0 second(s), error=I/O error.```
