### ISSUE TITLE
I need my Data to be wiped

### ISSUE THREAD

**Issue by Zaqre** [Rapptz/discord.py#317]
I somehow broke the bot, now all I get is "Error in command 'filter' - HTTPException: BAD REQUEST (status code: 400)"

I tried it on a new server and it worked perfectly. But I kicked it from my server, added it back and it still had all the same settings and all. I was trying to contact you, but you have no way but here. My issue is I need my server's data wiped from your database so I can start over.

**Comment by ccubed** [comment]
Discord.py is a framework. If doesn't store any data anywhere unless you write code to store data somewhere.

**Comment by ngbeslhang** [comment]
What ccubed says/

**Comment by Rapptz** [comment]
Since this is a weird issue. Here's a youtube video explaining how I feel: https://www.youtube.com/watch?v=Co5CpwNx4V4
