### ISSUE TITLE
How do I authorize a bot using Oauth?

### ISSUE THREAD

**Issue by LoganDark4** [Rapptz/discord.py#318]
--off topic--
Unfortunately I have been blocked twice now.
I'm sorry if anything I did came off as rude. I'll try to be as nice as I can from now on.
--on topic--
I want to add an oauth command to my bot that allows it to authorize bots onto the server automatically. Do I need to use aiohttp, or does discord.py have an inbuilt feature?

I would prefer instructions as I have no idea how to use the official discord docs.

Thanks in advance.

**Comment by ngbeslhang** [comment]
You'll need to manually code all of it.

**Comment by LoganDark4** [comment]
Well then, how would I do that? Do I need to use aiohttp?

**Comment by ngbeslhang** [comment]
smh

**Comment by LoganDark4** [comment]
How am I hating on you?

**Comment by Rapptz** [comment]
It is impossible to do this. Bots cannot accept applications.

**Comment by LoganDark4** [comment]
Thanks for the information.

**Comment by Marqin** [comment]
@Rapptz it ca be done by selfbot AFAIK

**Comment by LoganDark4** [comment]
Now I understand why you limit the issue to collaborators.
