### ISSUE TITLE
HTTPException thrown on sending message is never retrieved

### ISSUE THREAD

**Issue by Jibodeah** [Rapptz/discord.py#326]
```
2016-09-09 23:20:28 asyncio ERROR Task exception was never retrieved
future: <Task finished coro=<Client.send_message() done, defined at /usr/lib/python3.5/site-packages/discord/client.py:774> exception=HTTPException('BAD REQUEST (status code: 400)',)>                                                                                                                                                   
Traceback (most recent call last):
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/site-packages/discord/client.py", line 825, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts)
  File "/usr/lib/python3.5/site-packages/discord/http.py", line 137, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400)
```

The exception never makes it to `on_error`, one feels that it should. Especially since in my particular case it was caused by attempting to send a message exceeding Discord's character limit (2000).

(discord.py version: 0.11.0)

**Comment by SunDwarf** [comment]
Can you show the code that causes this error?

it appears that asyncio is eating the middle frames, or something.

**Comment by Jibodeah** [comment]
`client.loop.create_task(client.send_message(dest, 'a'*2001))`

(where `dest` is some valid destination)

I'm using `client.loop.create_task` as I was calling this outside of a asynchronous environment but the same thing happens when calling within one.

**Comment by SunDwarf** [comment]
`on_error` will only catch errors that happen within your event frame, not a task frame elsewhere in the loop.

This is not a bug.

**Comment by Jibodeah** [comment]
Sorry.
