### ISSUE TITLE
Add an unload method to be called before a "cog" is unloaded

### ISSUE THREAD

**Issue by bsquidwrd** [Rapptz/discord.py#327]
It should be like the [lib.setup(self)](https://github.com/Rapptz/discord.py/blob/1e9251cfefe5e4ce70094b90c000334ca431e954/discord/ext/commands/bot.py#L719) but would allow cogs to have a more graceful unload (i.e. make sure databases are saved or files are written) and could maybe be added on line [discord.ext.commands.bot: 728](https://github.com/Rapptz/discord.py/blob/1e9251cfefe5e4ce70094b90c000334ca431e954/discord/ext/commands/bot.py#L728) before everything begins unloading.

**Comment by Rapptz** [comment]
Already exists.

```py
class Thing:
  def __unload(self):
    # called when the cog is being unloaded
    pass
```
