### ISSUE TITLE
Add Server Widget JSON API Support

### ISSUE THREAD

**Issue by ZetaHunter** [Rapptz/discord.py#33]
Discord provides "Widget"'s API which allows anyone with server ID to collect general info on server (channels, members, etc). Also has invite url.

API endpoint is `https://discordapp.com/api/servers/{server.id}/widget.json`
Example: https://discordapp.com/api/servers/94367845990805504/widget.json

For Widgets to work anyone with `Manage Server` permission must enable it under `Server Settings > Widget` tab.

**Comment by MemorableUsername** [comment]
Awwwwwwwwww yeah wanted this really badly

**Comment by Rapptz** [comment]
I evaluated this just now and decided it's not as useful as it could be. It only has voice channels and no text channels so that diminishes the usefulness a lot. Maybe in the next version I'll add it.

**Comment by ZetaHunter** [comment]
Requires too much effort both from server admin side and bot developer side to use.
Closing until further notice.
