### ISSUE TITLE
Avconv/ffmpeg was not found

### ISSUE THREAD

**Issue by a09hopper** [Rapptz/discord.py#330]
I have installed FFMPEG into my path and restarted python but it just says: `ClientException: ffmpeg/avconv was not found in your PATH environment variable` So either Windows version of ffmpeg does not come with avconv but can someone please help me.

**Comment by SunDwarf** [comment]
Log out and log back in again.

**Comment by a09hopper** [comment]
Doesn't work :/

**Comment by khazhyk** [comment]
Can you run ffmpeg from your command line?

**Comment by Helehelehele** [comment]
I think this person got help from API channel.
