### ISSUE TITLE
Extra parameter in prune_members

### ISSUE THREAD

**Issue by acffordyce973** [Rapptz/discord.py#332]
I'm not entirely sure if I'm missing something or if the * in the function is supposed to be there: https://github.com/Rapptz/discord.py/blob/master/discord/client.py#L2011

It's also present in estimate_pruned_members but I haven't see it anywhere else.

**Comment by Rapptz** [comment]
This is Python 3 syntax for a keyword only argument.

Basically to specify the `days` argument you have to be explicit. e.g. `f(days=10)`.
