### ISSUE TITLE
voice_client.connect() can get stuck in an infinite loop

### ISSUE THREAD

**Issue by imayhaveborkedit** [Rapptz/discord.py#337]
In a specific, unknown circumstance, voice_client.connect can get stuck in an infinite loop polling the ws for its secret key.  I'm not sure if this is because discord decided not to send it for whatever reason, or some other oversight.

**Comment by Quantification** [comment]
Observed the same problem.
Possible source (hypothesis stage): packages required for voice communications (python-dev, lobffi-dev) not installed.

**Comment by Quantification** [comment]
Ooops, the problem is back, suddenly. Stacktrace: 

>  result = future.result(12)
>  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 405, in result
>     return self.__get_result()
>   File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
>     raise self._exception
>   File "/home/admin/RCProject_dev/RCVenv/lib/python3.6/site-packages/discord/client.py", line 3184, in join_voice_channel
>     session_id_data = yield from asyncio.wait_for(session_id_future, timeout=10.0, loop=self.loop)
>   File "/usr/local/lib/python3.6/asyncio/tasks.py", line 356, in wait_for
>     raise futures.TimeoutError()
> concurrent.futures._base.TimeoutError

Well... the code that causes the error is
```python
    voice_channel = self.get_channel(channel_id)
    future = asyncio.run_coroutine_threadsafe(self.join_voice_channel(voice_channel), self.loop)
    try:
        result = future.result(12)
    except Exception as e:
        print(traceback.format_exc())
```
(The loop runs in separate thread, so threadsafe scheduling is used.)

The bug behaves strangely: since my previous post everything was OK until now. Now the bug appears in each call, it is impossible to join voice channel.

**Comment by Rapptz** [comment]
That issue is unrelated. It is **documented** that asyncio.TimeoutError is raised by `join_voice_channel`. There is no bug related to that.

Disregarding that, this is **completely** unrelated to the current issue. Please open a new one.

**Comment by Quantification** [comment]
Thank you for the answer.

Agree, this is unrelated. Is it worth opening an issue? After all, it is mostly a record of my mistakes, their symptoms and how to correct them.  I  just hoped this could be potentially useful for someone else. 

Or maybe there is a better place to post this kind of info to.

**Comment by Quantification** [comment]
Thank you for the answer.

Agree, this issue is unrelated. Is the subject worth opening a new issue? After all, this is a record of my mistakes, their symptoms and how to fix them. I just hoped it could be useful for someone else.

Or maybe there is another place to post this kind of info to?

**Comment by Rapptz** [comment]
The voice connection logic has become a lot better in the rewrite version of the library (see [here](http://discordpy.readthedocs.io/en/rewrite/migrating.html#voice-changes)). 

Feel free to re-open if this still happens.
