### ISSUE TITLE
When an user only has the @everyone role, their role array is empty

### ISSUE THREAD

**Issue by leovoel** [Rapptz/discord.py#34]
on the on_message event handler i was getting the author of the message, and printing their role array, but it would give me an empty array every time, so i couldn't even check if a role was the everyone role.

here's some sample code:
```python
import discord
import json
import os

client = discord.Client()

if os.path.isfile("auth.json"):
        print("auth details loaded from auth.json")
        with open("auth.json") as data_file:
            authdetails = json.load(data_file)
            client.login(authdetails["email"], authdetails["pass"])

@client.event
def on_message(message):
    print(message.content)
    print(message.author.roles)

@client.event
def on_ready():
    print("logged in")

client.run()
```
and here's what i get if i run that, and send a message, with my account role set to everyone:
![sample image](http://i.imgur.com/ACuX1i8.png)

is this intended behavior? am i being stupid and missing something?

**Comment by Rapptz** [comment]
All members implicitly have the @everyone role. So the READY message doesn't give it to the members. You can get it via the `Server.get_default_role()` function. To get a `discord.Server` instance you can do `message.channel.server`.

**Comment by leovoel** [comment]
oh alright, it was a misunderstanding on my part then! 
i was writing some simple text-based games and the server owner didn't want members with ONLY the everyone role playing them, only people with other custom roles that he defined.

thanks for the quick response!
