### ISSUE TITLE
How to Direct Message someone?

### ISSUE THREAD

**Issue by KingDGrizzle** [Rapptz/discord.py#342]
Hello.

I'm sorry if this is documented, but I cannot understand how send_message works. I am trying to make a command that allows people to "request music" and I get DMed with the links they requested. (Its for a "Radio").

Any help would be appreciated, and I'm sorry if I shouldn't ask in here..

**Comment by SunDwarf** [comment]
`await client.send_message(some_user, "content")`

Where `some_user` is the user/member object (probably `message.author`)

**Comment by KingDGrizzle** [comment]
Can some_user be an ID?

**Comment by SunDwarf** [comment]
no

**Comment by lgn-drk** [comment]
Inside a command:
`await bot.whisper('message')`
Outside a command:
`await bot.send_message(msg.author, 'message')`

**Comment by KingDGrizzle** [comment]
I'm going to try that.

But cause I was vague (in my opinion). I am currently editing SexualRhinoceros Music Bot to add that request command I was talking about.

My goal is to make the command when ran, send me a DM, and leave a message in the chat saying that the link has been dmed. I am trying to make it work, but I am a Discord.Py Semi-Noob..

**Comment by KingDGrizzle** [comment]
Ok, got it working. All I need is the bot to send a specific person a DM, not the message authors

**Comment by Helehelehele** [comment]
http://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-get-a-specific-user-role-channel-server

**Comment by KingDGrizzle** [comment]
I get a "Class Message does not define __await__, so the 'await' operator cannot be used."

**Comment by Helehelehele** [comment]
Is that a PyCharm warning, if so ignore it.

**Comment by KingDGrizzle** [comment]
Doesn't work.. " await self.send_message(Server.get_member_named("KingDGrizzle#0815"), 'test')" gets skipped.. Tried using get_member with an ID, same result

**Comment by Helehelehele** [comment]
Read the error. And I'd suggest learning Python first.

**Comment by KingDGrizzle** [comment]
I'm not getting an error. The command just doesn't run and it gives me the usage info..

**Comment by KingDGrizzle** [comment]
Oh... Got it working. I'm such a dumbo. I set a "owner" variable to get me, and now it works. Sorry for the inconvinience!

**Comment by lgn-drk** [comment]
Haha, glad you got it working. However, small issues like these (not library-specific) are not to be asked here. They are to be asked in the discord API server.

**Comment by MrSpockGithub** [comment]
@KingDGrizzle Did you do `owner="KingDGrizzle#0815"` or your id?
