### ISSUE TITLE
client.send_file sometimes uploads a zero-byte file

### ISSUE THREAD

**Issue by silasary** [Rapptz/discord.py#343]
We've been having issues where sometimes an image upload sends a 0 byte file instead of the specified image.

The files we are uploading do exist on disk, and often requesting the bot to repeat the upload give a valid file the second time.

No errors are raised - It just doesn't appear properly when the upload "completes".

**Comment by Rapptz** [comment]
This is probably a discord bug. It happens with the official client too, sometimes uploads fail and you upload a zero byte option. 

The other idea is that it might be a bug with the way I do `open` with the filename, albeit I doubt that. You can try doing the `open` statement yourself e.g.

```py
with open(some_filename, 'rb') as f:
  await client.send_file(dest, f, content='foo')
```

**Comment by Aareon** [comment]
```py
with open(str(file)+extension, 'rb') as f:
            await client.send_file(message.channel, f)```
Confirmed works
