### ISSUE TITLE
Request to add functionality to create custom user notes

### ISSUE THREAD

**Issue by Plenglin** [Rapptz/discord.py#347]
Discord supports adding a custom note to each user like this:
![discord_2016-10-01_16-06-31](https://cloud.githubusercontent.com/assets/7308591/19017516/66af9052-87f1-11e6-940a-80acf26eee9c.png)
Is it possible to add this feature to the bot API?

**Comment by khazhyk** [comment]
Discord has specifically requested this not be automated. If you need to store per-user characteristics, you'd be better off with a local data store. (json/db/etc.)

**Comment by Rapptz** [comment]
While I'm okay with adding client-only features, this was one of the few that they asked me specifically not to implement and I plan on following up on that process. The problem is that this can be automated to abuse discord as a key-value store.
