### ISSUE TITLE
looping until client.send_message never ends

### ISSUE THREAD

**Issue by OlofHaglund** [Rapptz/discord.py#352]
My following code sends a message to discord but after the message is sent the loop never ends

```
def send_message(message):
    print(str.encode("Message to discord: " + message))
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    loop.run_until_complete(client.send_message(SERVER,message))
    print("loop is completed")
    loop.close()
```

**Comment by SunDwarf** [comment]
Why are you making a new event loop?

**Comment by OlofHaglund** [comment]
Because the script crash when I try to use the client.loop

**Comment by SunDwarf** [comment]
That's because you're trying to run on the event loop that is already running. There is a design problem at the root here.

What are you doing with your send_message function? Why is it blocking and not async?

**Comment by OlofHaglund** [comment]
My send_message function takes a string from IRC and sends it to discord. The reason why I block it with run_until_complete is because without the blocking nothing is printed in the discord.

**Comment by ButterCheezii** [comment]
You can't do this. There's already a blocking function (`Client.login`) controlling the event loop. You have to use coroutines and `await`:

    async def send_message(message):
        print(str.encode("Message to discord: " + message))
        await client.send_message(SERVER, message)

You must use `await send_message(message)` instead of `send_message(message)` or it will create a `Generator` and get garbage collected.
