### ISSUE TITLE
client.change_presence() TypeError

### ISSUE THREAD

**Issue by Fantarius** [Rapptz/discord.py#354]
As soon as I pass client.change_presence() the game as an argument it raises a type error `'change_presence() takes 1 positional argument but 2 were given'`

game = discord.Game(name="name")
client = discord.Client()

@client.event
async def on_ready():
    await client.change_presence(game)

Am I just too dumb to use this method or is this a real issue?

**Comment by SunDwarf** [comment]
`game=<some game object>`

**Comment by adongy** [comment]
`change_presence` takes keyword arguments only.

**Comment by EnderDas** [comment]
`game=discord.Game(name="name of game")`

**Comment by Fantarius** [comment]
Well atleast this finally made me understand keyword arguments.. sorry guys :(
