### ISSUE TITLE
Channel Creation not working

### ISSUE THREAD

**Issue by SamHDev** [Rapptz/discord.py#357]
the code:
await client.create_channel(lserver, 'Voice', type=discord.ChannelType.voice)
does not work.
Error:

> `Ignoring exception in on_message
> Traceback (most recent call last):
>   File "C:\Users\samhu_000\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 273, in _run_event
>     yield from getattr(self, event)(*args, **kwargs)
>   File "D:\Computer\Users\Sam\Desktop\DiscordBot\DiscordBot-LiveStreem\newbot.py", line 221, in on_message
>     await client.create_channel(lserver, 'Voice', type=discord.ChannelType.voice)
>   File "C:\Users\samhu_000\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 1823, in create_channel
>     data = yield from self.http.create_channel(server.id, name, str(type), permission_overwrites=perms)
> AttributeError: 'str' object has no attribute 'id'`

**Comment by SunDwarf** [comment]
`lserver` in this case is a string, not a Server object.
