### ISSUE TITLE
My bot has an issue with returning None for member.voice_channel

### ISSUE THREAD

**Issue by Alkovalic** [Rapptz/discord.py#360]
My bot takes `message.author.voice_channel` upon a summon command, and joins that particular channel.
(using the `message` obtained via `on_message`)

`voice = await self.join_voice_channel(message.author.voice_channel)`

However, `message.author.voice_channel` returns `None` unless the user switches voice channels before summoning it.

The exception is myself:  if I use the summon command, then the bot joins the channel without issue, without me changing voice channels beforehand.

How do I get `message.author.voice_channel` to return the voice channel the user is in without having them switch voice channels beforehand?

**Comment by Rapptz** [comment]
Is this a userbot or a real bot?

**Comment by Rapptz** [comment]
Known bug for user bots due to the guild sync change internally. Hard to fix in the current code base.

**Comment by Alkovalic** [comment]
Okay, I'll finally make the switch to a real bot.

Thank you for your help!
