### ISSUE TITLE
Game doesn't show if already playing when connecting to discord

### ISSUE THREAD

**Issue by dklollol** [Rapptz/discord.py#362]
If you already have a game running when connecting, then it says your not playing anything.

**Comment by khazhyk** [comment]
Can you explain in more detail what you mean?

**Comment by dklollol** [comment]
When a member is already playing a game and triggers on_member_update(before, after) (by connecting to discord disconnected -> connected), both before and after games are set to none. But on discord it says hes playing for example rocket leauge.

**Comment by khazhyk** [comment]
So you mean a user is already online on one computer, then becomes online on another computer and their game gets unset?

**Comment by khazhyk** [comment]
I can't reproduce this behavior, how exactly does this situation arise?

**Comment by dklollol** [comment]
Its one user one machine one discord account. To reproduce it close discord start any game that discord can register and when the game is running you start discord. This way your connecting to discord with a game already running.

**Comment by khazhyk** [comment]
Are you trying to get your *own* game?

**Comment by dklollol** [comment]
I have a bot which logs and tracks when my server members start and stop playing a specific game (Discord id: xxxx81666752200704, start date: 2016-10-15 17:22:47, end date: 2016-10-15 18:14:37)

It works but there is one exception and that is if people have the game running already when connecting to discord. In that case it says hes playing nothing when connecting.

**Comment by khazhyk** [comment]
I can reproduce this, this is a discord bug, not with this library.

**Comment by Rapptz** [comment]
This is a discord bug. When you connect it shows that you're playing a game but in reality you're not. It manifests itself as the game disappearing on other people's screens.
