### ISSUE TITLE
[Solved] Used webhook rather than discord app

### ISSUE THREAD

**Issue by yesiateyoursheep** [Rapptz/discord.py#366]
I was trying to use a webhook rather than creating a discord app. The resulting issue was the error message; `discord.errors.LoginFailure: Improper token has been passed.`.

For anyone else, here's the docs; https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token

**Comment by SunDwarf** [comment]
...are you trying to log in with a webhook?

**Comment by yesiateyoursheep** [comment]
Yes, how else would you do it? (I am very new to this.)

**Comment by Pandentia** [comment]
You send a `POST` request to the webhook's URL with some JSON data, for example `{"content": "Hello, world!"}`. This will then appear in your channel as a specialized webhook account. Webhooks are not bot accounts. They can't receive messages, all they can do is send messages with fancy embeds. It's basically a one-way system, you don't get any other feedback than "your JSON has been accepted".
