### ISSUE TITLE
QUESTION: Get author of "commands.Bot().command()" call/usage.

### ISSUE THREAD

**Issue by luciengaitskell** [Rapptz/discord.py#367]
I have started to implement "discord.ext.commands". I would like to get the author of the command message being sent. How would I do that?

**Comment by Phxntxm** [comment]
@bot.command(pass_context=True)
async def command(ctx):
    author = ctx.message.author

**Comment by leovoel** [comment]
http://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-get-the-original-message

**Comment by luciengaitskell** [comment]
Thank you @Phxntxm and @leovoel.
