### ISSUE TITLE
Find if command has been run in 'on_message' (by 'process_commands')

### ISSUE THREAD

**Issue by luciengaitskell** [Rapptz/discord.py#368]
I saw in the FAQ about how if 'on_message' is used, 'process_commands' needs to be added to allow the commands to execute. Is there a way to tell if a command has been run by this function (without checking for the occurrence in the message myself)?

**Comment by Phxntxm** [comment]
It sounds like you're referring to this event `on_command_completion`?
https://github.com/Rapptz/discord.py/blob/967d43c35b4d4c288d47a9eb9d374bef34292f1d/discord/ext/commands/bot.py#L826

**Comment by luciengaitskell** [comment]
If 'process_commands' is run at the top of 'on_message', is there a way to get the list of commands run (to modify what is done in the 'on_message' function)?

**Comment by Rapptz** [comment]
No. There's a separate event for that, `on_command`.

**Comment by luciengaitskell** [comment]
Where would the documentation be?

**Comment by Rapptz** [comment]
http://discordpy.readthedocs.io/en/latest/faq.html#is-there-any-documentation-for-this

**Comment by luciengaitskell** [comment]
Is there an example usage of `on_command`?

**Comment by Helehelehele** [comment]
```py
@bot.event
async def on_command(command, ctx):
    ...
```
