### ISSUE TITLE
Websockets - ResumeWebSocket freezing the bot

### ISSUE THREAD

**Issue by lgkern** [Rapptz/discord.py#374]
Sometimes the bot, even running on a dedicated server, has been getting disconnected and then quickly reconnected. But, sometimes the following scenario happens

```
INFO:discord.gateway:Websocket closed with 1006 (), attempting a reconnect.
INFO:discord.client:Got ResumeWebSocket
```

which leads to the bot freezing up and not answering to any further events.

**Comment by Rapptz** [comment]
This needs more information.

**Comment by khazhyk** [comment]
This might be related to my heartbeat issue

**Comment by lgkern** [comment]
The issue haven't been happening since I moved the bot back to my personal computer (running W10) instead of the dedicated sever (running Windows Server 2012) it was running. So the OS might be related to the cause of it.
