### ISSUE TITLE
QUESTION: Where Are Event functions Called in Library

### ISSUE THREAD

**Issue by luciengaitskell** [Rapptz/discord.py#376]
I am trying to understand how this library works and I have a question: Where are the decorated `client.event` functions called? (For example `on_message` and `on_ready`)

**Comment by imayhaveborkedit** [comment]
https://github.com/Rapptz/discord.py/blob/master/discord/client.py#L282-L291

**Comment by luciengaitskell** [comment]
Thanks. To follow up: How are the functions in `state.ConnectionState`, for example: `parse_message_create` run (to then call `dispatch`)?

**Comment by luciengaitskell** [comment]
Nevermind... I found that the `parse_` functions are run in the `gateway.py` file.
