### ISSUE TITLE
Multithreading with discord.py

### ISSUE THREAD

**Issue by galac-tech** [Rapptz/discord.py#377]
Ok so, I am making a bot that gets input from a user and then dose x, y, z to that data. While it is doing x, y, z I am trying to show its progress by editing a message like so:
`0%, 28%, 57%...`

I have used Multithreading before, but when I try, I get :
```
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py:862: RuntimeWarning: coroutine 'update' was never awaited
  self._target(*self._args, **self._kwargs)
```

I looked at the `background_task.py` example and tried `client.loop.create_task()` but all it does is wait till it is all over and it goes from 0% to 100%

Any ideas?

Thanks!

**Comment by duke605** [comment]
I'm quite new to python and i may be completely wrong... BUT. did you put `await` before calling the `update()` function? If yes, does the function you're calling `update()` from have an `async` keyworrd before `def`?

**Comment by galac-tech** [comment]
@duke605  Yes, this is what it looks like :
```
async def update(scan, message):
    print (scan.total_ips)
    print (scan.ips_scan_compleat)
    while  scan.ips_scan_compleat == False:
        if scan.total_ips != 0:
            print(str(round(scan.ips_scaned/scan.total_ips*100))+"% : Completed")
            client.edit_message(message, str(round(scan.ips_scaned/scan.total_ips*100))+"% : Completed")
            time.sleep(1)
    await client.edit_message(message, "100% : Completed")
```
And I tried calling it like :
`await client.loop.create_task(update(scan, message))  `
and :
```
t = Thread(target=update, args=(scan, message))
t.start()
```

_Note: These are in-game ips (not real ones)._

**Comment by Rapptz** [comment]
First of all, I am not sure why you think running this stuff in a separate thread would work.

There's an entire section dedicated to why [asyncio is not thread-safe](https://docs.python.org/3/library/asyncio-dev.html#concurrency-and-multithreading). This sounds more like an issue with you being confused and not knowing how to solve your actual problem (a classical [X/Y problem](http://meta.stackexchange.com/q/66377/194858)).

Consider clarifying your problem a bit more.

**Comment by galac-tech** [comment]
@Rapptz, I have a discord bot where the user inputs a link to something like a paste bin page etc. and my bot adds all the ips on the page to a list. Then the bot goes through the list and check which ips are active. What I am trying to do is show the progress of the ip checker function while it is working. On previous projects I have done this with multithreading to update the console but I am new to using async and not sure how to go about it.

I hope that is enough background 😁

Thanks!

**Comment by ccubed** [comment]
Well, to begin with, you don't await create task. Otherwise, the error is pretty clear. Also, all the warnings about thread safety. Create task, for instance, is definitely not thread safe.

**Comment by galac-tech** [comment]
@ccubed, Thanks for the advice! 
I can now get it to print to the console but it still will not update the discoed message.   
<img width="121" alt="screen shot 2016-11-01 at 9 58 43 am" src="https://cloud.githubusercontent.com/assets/18410249/19898574/d6a93ff8-a019-11e6-9b65-cc8fad0d8760.png">

**Comment by ccubed** [comment]
Possibly because you aren't awaiting the edit message. Just a guess.

**Comment by galac-tech** [comment]
@ccubed, Then I get this error:
`coroutine 'update' was never awaited`

**Comment by Eternity71529** [comment]
You didn't "await" it. Coroutines need to be "await"ed.
You didn't await it. You have to await coroutines.  
I suggest looking at this first: http://discordpy.readthedocs.io/en/latest/faq.html#where-can-i-use-await

**Comment by galac-tech** [comment]
@Eternity71529, That might be my problem right there then, I'm using requests not aiohttp.

I'll look in to that later.
Thanks

**Comment by DiamondDemon669** [comment]
i dont know how to fix this

**Comment by Eternity71529** [comment]
fix what?

**Comment by Phxntxm** [comment]
He posted his own issue later that was already answered, on a separate note, please do not necro old issues.... this issue is over three years old, and frankly unrelated to the problem originally posted.
