### ISSUE TITLE
PyNaCl failing 

### ISSUE THREAD

**Issue by FloatCobra** [Rapptz/discord.py#378]
I ran "sudo pip install PyNaCl" and I got the error `Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5tt840r6/PyNaCl/`

**Comment by alfalfascout** [comment]
That happens a lot. Have you tried installing libsodium?

**Comment by FloatCobra** [comment]
I don't believe I have

**Comment by jaydenkieran** [comment]
![pynacl](http://i.imgur.com/5bQeXJX.png)

**Comment by FloatCobra** [comment]
I fixed it, apparently I never installed python3.5-dev rip
