### ISSUE TITLE
How do I get a token from an email and password combination?

### ISSUE THREAD

**Issue by ButterCheezii** [Rapptz/discord.py#379]
Currently, I can only use an account on my own machine due to IP restrictions. However, tokens can be used from anywhere. I'm using a _user account_. **How do I get a token from an email and password combination?**

**Comment by Phxntxm** [comment]
1. Open Discord
2. Press Ctrl+Shift+i
3. Click "Console" tab
4. Type localStorage.token

**Comment by ButterCheezii** [comment]
I wish to do this programmatically using a script. I do not have the time nor the will to sign into each account and find its token.

**Comment by jaydenkieran** [comment]
[No](https://github.com/hammerandchisel/discord-api-docs/issues/69#issuecomment-223886862).

**Comment by ButterCheezii** [comment]
If the bot can't get a token, how does it stay logged into a user account then? There has to be some way.

**Comment by ButterCheezii** [comment]
`Client.http.token`. Issue solved.

**Comment by RedstoneHair** [comment]
> `Client.http.token`. Issue solved.

how?
