### ISSUE TITLE
Add PermissionOverwrite.is_empty()

### ISSUE THREAD

**Issue by Rapptz** [Rapptz/discord.py#382]
This should help in cases where you want to query if the overwrites returned from `overwrites_for` are actually empty or not.

**Comment by wenyichen** [comment]
Hi, its my first time doing a pull request, would the change here just be 

`
def is_empty( self ):
   return bool( self._values )
`

**Comment by Rapptz** [comment]
Nah. If you do `x.read_messages = None` then the `self._values` wouldn't be empty but semantically it is.

**Comment by wenyichen** [comment]
Would this work?

```
def is_empty( self ):
   return not bool( self._values ) or not any( x is not None for x in self._values.values() )
```
