### ISSUE TITLE
Bot doesn't execute function or exits with code 0

### ISSUE THREAD

**Issue by liderb** [Rapptz/discord.py#383]
To summarize, when a bot admin uses !update command, it starts the update chain.

1. Gets a member list and server roles
2. Sees if any of the members already have any region role, removes them from the list if they do (to avoid making unnecessary queries)
3. Checks if there's someone with their nick/name in the regions, then returns a dict. With a key/value of nick/name : list_of_regions
4. If a dict is returned (the members list could be empty), it starts setting roles 
5. Finds the nick/name in the dictionary and adds role to the member with the respective nick/name.

However, it stops working just after entering step 4. Sometimes it exits the bot with exit code 0, others the bot keeps running, but without reaching doing anything in step 4.

The functions for step 4 and 5:
```python
async def roles(user, future_roles, server_roles):
    """
    :param user - A Member that is going to be assigned a role
    :param future_roles - A list of Names that match existing Roles.names
    :param server_roles - Self explanatory
    """
    print("you have reached roles function")
    for role in server_roles:
        if role.name in future_roles:
            await  client.add_roles(user, role)
            print("Role {} added to {}".format(role.name, user.display_name))


async def set_roles(user_region_dict, list_users, server_roles):
    """
    :param user_region_dict - A dictionary with Keys being Member's nicks or names, values the regions where they play
    :param list_users: - Self explanatory
    :param server_roles - Self explanatory

    How it works:
                Checks each member.nick/member.name in the dictionary and assigns the respective member
                that is in list_users due to the index variable.

                It calls the function roles with future_roles param being the region(s) where they play
    """
    print("You've reached set roles")
    for index, member in enumerate(list_users):
        print("You reached set roles step 2")
        if member.display_name in user_region_dict:
            print("Setting roles to {}".format(member.display_name))
            await roles(list_users[index], user_region_dict[member.display_name], server_roles)
```

Creating the issue because I'm not sure if it's my code that is wrong or if it's conflicting with the discord.py library.
I'm somewhat familiar with python but I probably make a lot of mistakes so feel free to call out on anything that I could improve ^^
[Picture to exemplify a test run](http://i.imgur.com/obv5NAr.png?1)
Note: The "Setting roles in a bit" is before entering step 4

**Comment by SunDwarf** [comment]
First off, I don't see anything that would make this an issue with the library.

Secondly, it's better to ask questions like this in the [Discord channel](https://discord.gg/5rjFc8j) rather than on this issue tracker for queries with your code.

**Comment by liderb** [comment]
Alright then, thanks for the info + link and sorry ^^
