### ISSUE TITLE
How to display an custom emoji within a bot message

### ISSUE THREAD

**Issue by Nerdietony** [Rapptz/discord.py#390]
When i just message is (":isabelle:, you work") and the emoji is isabelle, but the the custom emoji won't show, only the :isabelle: text

**Comment by Rapptz** [comment]
It's `<:emoji_name:emoji_id>` for custom emojis.

You can also find the `discord.Emoji` instance through `Server.emojis` and then cast it to `str`.

**Comment by qndel** [comment]
It doesn't work ...

**Comment by OrangeChaten** [comment]
discordpy.rtfd.io/en/latest/api.html

**Comment by armaan115** [comment]
If you are lazy and want to get the formatted version of `<:emoji_name:emoji_id>` automatically for your emoji, go in Discord and open type in `\:YourEmoji:` (Be sure to replace "YourEmoji with the name of your emoji!) 

Discord will automatically return a formatted version of  `<:emoji_name:emoji_id>` for your emoji. How cool is that!?

**Comment by SpectacularVernacular** [comment]
Very cool thanks. I accidentally got too many characters when I shift+clicked to get the emoji ID so this helped a lot.

**Comment by Lemon-Hacking** [comment]
Use utils.get then cast it to str :
```
emoji = discord.utils.get(bot.emojis, name='isabelle')
await ctx.send(str(emoji))
```
Or id if you have it, as there can be conflicting names.

**Comment by Aman-Sanoj** [comment]
Is there a way I can use custom emojis in the MessageEmbed title field?

**Comment by Aman-Sanoj** [comment]
<:emoji:emoji_id> doesnt work

**Comment by mesub7** [comment]
Please don't necrobump old, closed issues.

You cannot use custom emotes in the title field of an embed, due to Discord limitations.

If you require further support, please visit the [discord server](https://discord.gg/dpy) or go to the [discussions page.](https://github.com/Rapptz/discord.py/discussions)

**Comment by roudges2** [comment]
> <:emoji:emoji_id> doesnt work

The emoji must be on the server for it to work.

**Comment by TrentaFX2** [comment]
so epic
