### ISSUE TITLE
Multiple embeds in one message

### ISSUE THREAD

**Issue by Galarzaa90** [Rapptz/discord.py#396]
I recently started playing around with webhooks, creating messages with rich formatting using simple post requests. I was excited cause I could create better command replies using embeds.

Today I just noticed embeds are supported on discord.py too, however, only one embed is allowed per message. I'm wondering if Discord API is limiting this or if it is a limitation by discord.py.

Why not use multiple messages with a single embed? Cause then if reactions are enabled on that channel, they will get in the middle of messages.

I understand that this might be because they were recently implemented so adding support for multiple embeds might be on the plans, I just wanted to point that there are reasons to use them.

**Comment by Rapptz** [comment]
You can only have a single embed. If the API allows for many then sure, but as it stands right now it doesn't.

**Comment by Galarzaa90** [comment]
Too bad, guess we can only wait until it's supported by the API like they do with webhooks.
