### ISSUE TITLE
"on_reaction_add" not triggering on messages send before login

### ISSUE THREAD

**Issue by Akuba-** [Rapptz/discord.py#399]
That title can be confusing.

I noticed that `on_reaction_add` does not trigger on messages that have been send before the bot logged in.

Like: 
* User 1 sends a message.
* Bot started and logged in
* User 2 sends a message.
* User 2 reacts to User 1s message (<-- this does not trigger)
* User 1 reacts to User 2s message (<-- this does trigger)

**Comment by jaydenkieran** [comment]
> Similar to on_message_edit, if the message is not found in the Client.messages cache, then this event will not be called.

http://discordpy.readthedocs.io/en/latest/api.html#discord.on_reaction_add

**Comment by Akuba-** [comment]
Huh, how could I miss that part. Well, thats what I figured already.

~Close

**Comment by YouTwitFace** [comment]
Would it be possible to trigger the event and pass an empty message?
