### ISSUE TITLE
Reconnecting Loop because of VoiceRegion Change

### ISSUE THREAD

**Issue by aschenkuttel** [Rapptz/discord.py#3996]
### Summary
I still have problems with the bot permanently reconnecting after a while. The reason seems to be some discord internal voiceserver change for my guild since you can reproduce that behaviour by changing the voice region while the bot is in voice. It then disconnects and connects every minute till you force it to disconnect / restart. It's not my code, I reproduced it with a dummy bot aswell.

### Reproduction Steps
Connect your bot to any voice channel and change the server region

### Expected Results
A Reconnect once

### Actual Results
Infinite reconnects every minute with this failure:

> ERROR:discord.voice_client: Disconnected from voice... Reconnecting in 0.05s.
Traceback (most recent call last):
  File "C:\Users\Neel\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\gateway.py", line 746, in poll_event
    msg = await asyncio.wait_for(self.recv(), timeout=30.0)
  File "C:\Users\Neel\AppData\Local\Programs\Python\Python37\lib\asyncio\tasks.py", line 442, in wait_for
    return fut.result()
  File "C:\Users\Neel\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\protocol.py", line 350, in recv
    yield from self.ensure_open()
  File "C:\Users\Neel\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\protocol.py", line 512, in ensure_open
    self.close_code, self.close_reason) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 4000 (private use), no reason
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Users\Neel\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\voice_client.py", line 243, in poll_voice_ws
    await self.ws.poll_event()
  File "C:\Users\Neel\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\gateway.py", line 749, in poll_event
    raise ConnectionClosed(exc, shard_id=None) from exc
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 4000 (private use), no reason

Here's the complete log from reproducing it:
[discord.log](https://github.com/Rapptz/discord.py/files/4465911/discord.log)

### Checklist

- [X]  I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### System Information
- Python v3.7.4-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v6.0
- system info: Windows 10 10.0.18362

**Comment by aschenkuttel** [comment]
Edited the Issue, that should be fine now.
And also another discord.log running it for a while, the interval just increases but the disconnect-connect loop doesnt seem to end at all. Reinstalled and tried it multiple times, definitly a bug.

[discord.log](https://github.com/Rapptz/discord.py/files/4507886/discord.log)

**Comment by FightMan01** [comment]
Same issue here, but I'm getting 1001 going away too.
It just stuck. I usually delete the voice channel and create it again. This is a temporary fix, but not the best :/

**Comment by Rapptz** [comment]
Fixed by #4210 I believe
