### ISSUE TITLE
Add Audio API

### ISSUE THREAD

**Issue by ZetaHunter** [Rapptz/discord.py#4]
As title says, add support for Audio API like https://github.com/RogueException/Discord.Net has.

**Comment by jhgg** [comment]
I may take a crack at this in the upcoming week.

**Comment by tuckismad** [comment]
@jhgg did you get anywhere with it? I'd be willing to help out if I can

**Comment by ZetaHunter** [comment]
@tuckismad look at #35 
@Rapptz was earlier adapting it for Discord.py but due to personal reasons that is for time being delayed, if you are using 32bit Python 2.7 you will be golden, otherwise you are fucked.

**Comment by tuckismad** [comment]
@ZetaHunter Fuck, i'm using python 3 :(

**Comment by AraHaan** [comment]
Also I patched opuslib so take a look at this it only works if any bot code you make has the dll file named ``libopus`` in the fodler of it. Same if you compile it to exe.

**Comment by ZetaHunter** [comment]
Okay so Audio API partially has been added to Discord.py in the [async](/Rapptz/discord.py/tree/async) branch.

**Comment by Mondanzo** [comment]
Maybe would be a Soundcloud a good API to add?

**Comment by ZetaHunter** [comment]
Erm, this has already been added (both the audio api and the soundcloud api via youtube-dl).
Closing this.
