### ISSUE TITLE
Python stops after await .guild.create_role()

### ISSUE THREAD

**Issue by KieranJames1996** [Rapptz/discord.py#4000]
### Summary

When using await .guild.create_role(),  the python code does not continue to the next line. 

### Reproduction Steps

`print("Starts")`
`await message.guild.create_role(name="Lecturer")#Creates roles`
`print("Ends")`

The above code prints "Start", it then creates the role in the server as expected, but for some reason it never gets to print("Ends"). 

To clarify, the bot is still running after this command and still responds to other commands, but it never seems to get to print("Ends").

I've had this code working for about two months, but this issue has only arisen today with no changes to this segment as I can recall. 

### Checklist

- [X ] I have searched the open issues for duplicates.
- [ X] I have shown the entire traceback, if possible.
- [ X] I have removed my token from display, if visible.

### System Information

- Python v3.8.2-final
- discord.py v1.3.2-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Windows 10 10.0.18362

*Any help would be great, thank you!

**Comment by Rapptz** [comment]
Can't reproduce.

![image](https://user-images.githubusercontent.com/1695103/79082135-7fb8c700-7cf1-11ea-9758-5c1831aba29a.png)

**Comment by KieranJames1996** [comment]
Here's the code I'm using. 
[main2.txt](https://github.com/Rapptz/discord.py/files/4467357/main2.txt)

I would add it as code through markdown, but I'm terrible at doing it.

**Comment by Gobot1234** [comment]
I'll save people downloading it

```py
import discord
import asyncio

#Command Prefix
client = discord.Client(command_prefix='!')

#Log bot on
@client.event
async def on_ready():
	print('We have logged in as {0.user}'.format(client))

#On message received
@client.event
async def on_message(message):
	if message.author == client.user:
		return


	target_server_id = #serveridhere
			
	server = client.get_guild(target_server_id)

			#~~~~~~~~~~~~~~~~~Permission Setup~~~~~~~~~~~~~~~~~~~~
	print("Starts")
	await server.create_role(name="Lecturer")#Creates roles
	print("Ends")

client.run()#add key here
```

**Comment by Gobot1234** [comment]
Wait there is so much wrong with this

**Comment by KieranJames1996** [comment]
> Wait there is so much wrong with this, wait no there isn't you've just named thing weird.
> 
> Just a note though discord.Client doesn't take a `command_prefix` kwarg

Thanks, I'll keep that in mind. I'm super new and still trying to learn. 
This still didn't change the situation though.

**Comment by KieranJames1996** [comment]
> You should use the lib debug logging to double check that you have not hit a rate limit. If that's the case, the lib will sleep for you until the ratelimits expire. In you case, it can take days (!).

I have indeed been rate limited. Thank you for all your help!

**Comment by GeorgeUkranian** [comment]
> You should use the lib debug logging to double check that you have not hit a rate limit. If that's the case, the lib will sleep for you until the ratelimits expire. In you case, it can take days (!).

Can you please explain how to use the lib debug logging, because I dont know what it is, but I have the same problem with author of this disscussion.
