### ISSUE TITLE
how to unfriend a discord friend (selfbot)

### ISSUE THREAD

**Issue by Squuv** [Rapptz/discord.py#4004]
how to unfriend discord friend? 

i tried this but not working.
```
for user in bot.user.friends:
        print(user.name+"#"+user.discriminator)
        await user.remove()
```

**Comment by A-Trash-Coder** [comment]
Just don't use a self-bot. It's against ToS

**Comment by Vexs** [comment]
You're looking for [user.remove_friend](https://discordpy.readthedocs.io/en/latest/api.html#discord.User.remove_friend)

**Comment by treeofplant** [comment]
really sorry for this late reply but here

`for friends in bot.user.friends:
                try:
                    await friends.remove_friend()

                except:
                    print("Error")`

**Comment by treeofplant** [comment]
sorry for the late response, dont know if u can still concerned about this issue

for friends in bot.user.friends:
                try:
                    await friends.remove_friend()

                except:
                    print("Error")
