### ISSUE TITLE
CancelledErrors/RuntimeErrors within a Task upon restarting Bot

### ISSUE THREAD

**Issue by Leothechosen** [Rapptz/discord.py#4006]
### Summary
I have a task whose purpose is to update a targeted channel with the server's set timezone.

```
class Misc(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        self.theserverTime.start() # pylint: disable=no-member

    @tasks.loop(minutes=1.0)
    async def theserverTime(self):
        allGuildSettings = await database.getAllGuildSettings()
        fmt = "%H:%M %Z"
        for guild in allGuildSettings:
            try:
                if guild[1] is not None:
                    channel_for_servertime = self.bot.get_channel(id=guild[1])
                    serverTime = datetime.now(timezone(guild[2]))
                    serverTime = serverTime.strftime(fmt)
                    await channel_for_servertime.edit(name=serverTime)
            except:
                logger.exception("Server Time Error")
    
    @theserverTime.before_loop
    async def before_theserverTime(self):
        minutecheck = datetime.now(timezone("CET"))
        fmt2 = "%s"
        minutecheck = int(minutecheck.strftime(fmt2))
        minutecheck = 61 - (minutecheck % 60)
        await asyncio.sleep(minutecheck)
```

Sometimes, when restarting the bot via systemctl (usually after running for a few hours), a series of errors will occur, sometimes varying in amounts. The previous time, it returned 3166 lines of errors/tracebacks, and the log file indicated it was cleaning up after 36 tasks (see here: https://gist.github.com/Leothechosen/8793eac20b0050f6ed836781df58da29), versus the 6 that I usually get when restarting the bot 

### Reproduction Steps

1. Have a Task in a cog
2. Let it run for a couple of hours
3. Restart bot via systemctl 
4. Maybe you'll get errors.

### Expected Results

```
2020-04-15 12:09:31;discord.client;INFO;Cleaning up tasks.
2020-04-15 12:09:31;discord.client;INFO;Cleaning up after 6 tasks.
2020-04-15 12:09:41;discord.client;INFO;All tasks finished cancelling.
2020-04-15 12:09:41;discord.client;INFO;Closing the event loop.
```

### Actual Results
https://gist.github.com/Leothechosen/8793eac20b0050f6ed836781df58da29

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.7.3-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Linux 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020

**Comment by Rapptz** [comment]
This is because you're catching all exceptions (bad practice) which in turn catches the cancellation error and noisily logs it.

**Comment by Leothechosen** [comment]
Sure, but that's not the root problem. For some reason, it seems like the # of activate tasks is getting inflated over time. I restarted again just now, and it had 26 tasks to clean up after.
