### ISSUE TITLE
create_category() got an unexpected keyword argument 'position'

### ISSUE THREAD

**Issue by very-bad-dev** [Rapptz/discord.py#4007]
### Summary

`TypeError: create_category() got an unexpected keyword argument 'position'`

### Reproduction Steps

`await ctx.guild.create_category(name="uwu", position=2)`

### Expected Results

for `create_category` to take the "position" argument as stated in the docs

> await create_category(name, *, overwrites=None, reason=None, position=None)

### Actual Results

Ignoring exception in on_raw_reaction_add
Traceback (most recent call last):
  File "C:\Users\humbl\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\humbl\Desktop\bot.py", line 589, in on_raw_reaction_add
    if payload.emoji == client.get_emoji(527591885603209240): await post["confirm"](post["ctx"])
  File "C:\Users\humbl\Desktop\bot.py", line 1976, in confirm
    await ctx.guild.create_category(name=x.name, overwrites=x.overwrites, position=x.position)
TypeError: create_category() got an unexpected keyword argument 'position'

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.8.2-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Windows 10 10.0.18362

**Comment by ryanhampton** [comment]
You may have been looking at the docs for 1.4.0a which is unreleased. Take a look at the documentation here: https://discordpy.readthedocs.io/en/stable/api.html?highlight=create_category#discord.Guild.create_category

**Comment by ShineyDev** [comment]
This was fixed in a recent [unreleased patch](https://github.com/Rapptz/discord.py/commit/d2cc8aa459571eb981bda88f91c736524872bb26).
