### ISSUE TITLE
member.roles not show all roles

### ISSUE THREAD

**Issue by franciscomirasg** [Rapptz/discord.py#4014]
### Summary
I try to list all roles from an user in a test server, but the bot doesn't show all roles that the user has, only show two. 

### Reproduction Steps
    def is_auth(self,message):
        guild = client.get_guild(_guild id_)
        member = 0
        for m in guild.members:
            if m.id == message.author.id:
                member = m

        if m == 0:
            return False

        print('User exists') _is printed_
        print(member.id) _the id match with user id_
        user_roles = [y.name for y in m.roles]
        print(user_roles)
   

### Expected Results
List all roles from the user, the user I try have 5 roles

### Actual Results
Only shows @everyone and a roll which the user don't have
[debug.log](https://github.com/Rapptz/discord.py/files/4495826/debug.log) 

### Additional files 
[botTest1.zip](https://github.com/Rapptz/discord.py/files/4495829/botTest1.zip) withoud token or IDs

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### System Information
PS C:\Users\shadowgunther> py -3 -m discord -v
- Python v3.7.3-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Windows 10 10.0.19041

**Comment by Scaarus** [comment]
You are getting the id of `member`, but getting the roles of `m`. This is why you think you have the right member but the roles are wrong. `m` is going to be the last member in `guild.members` since it's set in your for loop. If you change your second to last line to `user_roles = [y.name for y in member.roles]` it should work correctly.

**Comment by franciscomirasg** [comment]
I have notice yet the failure, sorry for the stupid question.
