### ISSUE TITLE
`discord.File` cannot be sent multiple times

### ISSUE THREAD

**Issue by SebbyLaw** [Rapptz/discord.py#4022]
### Summary

sending a `discord.File` object through `Messageable.send()` changes the state of the file object.

### Reproduction Steps

```py
file = discord.File(io.BytesIO(my_bytes), filename='my_file')
await ctx.send(file=file)  # sends the file properly
await ctx.send(file=file)  # sends the file with zero bytes
await ctx.send(file=file)  # error
```

### Expected Results

Sending using the same file object multiple times works

### Actual Results

```
Traceback (most recent call last):
  File "/Users/seb/TestBot/venv/lib/python3.7/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/Users/seb/TestBot/cogs/Admin.py", line 126, in _eval
    return await ctx.send(**kwargs)
  File "/Users/seb/TestBot/venv/lib/python3.7/site-packages/discord/abc.py", line 851, in send
    embed=embed, nonce=nonce)
  File "/Users/seb/TestBot/venv/lib/python3.7/site-packages/discord/http.py", line 165, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "/Users/seb/TestBot/venv/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/Users/seb/TestBot/venv/lib/python3.7/site-packages/aiohttp/client.py", line 473, in _request
    ssl=ssl, proxy_headers=proxy_headers, traces=traces)
  File "/Users/seb/TestBot/venv/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 293, in __init__
    self.update_body_from_data(data)
  File "/Users/seb/TestBot/venv/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 478, in update_body_from_data
    body = body()
  File "/Users/seb/TestBot/venv/lib/python3.7/site-packages/aiohttp/formdata.py", line 148, in __call__
    return self._gen_form_data()
  File "/Users/seb/TestBot/venv/lib/python3.7/site-packages/aiohttp/formdata.py", line 142, in _gen_form_data
    self._writer.append_payload(part)
  File "/Users/seb/TestBot/venv/lib/python3.7/site-packages/aiohttp/multipart.py", line 767, in append_payload
    size = payload.size
  File "/Users/seb/TestBot/venv/lib/python3.7/site-packages/aiohttp/payload.py", line 310, in size
    position = self._value.tell()
ValueError: I/O operation on closed file.
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.7.6-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v6.0
- system info: Darwin 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64

**Comment by Rapptz** [comment]
File objects are single use. This is intended. I think if anything this needs documentation but I wont fix this.

**Comment by SmackleFunky** [comment]
You can do a file.seek(0) between each send to reset the pointer to start of file. This is to do with understanding file having in Python more than discord.py

**Comment by SebbyLaw** [comment]
> You can do a file.seek(0) between each send to reset the pointer to start of file. This is to do with understanding file having in Python more than discord.py

This is wrong. discord.File objects do not have a seek() method, and furthermore this method will not work as File objects are closed after two reads. Not sure why you felt the need to comment without even trying your own "solution".

For anyone reading this thread in the future, just reconstruct a new File object for each send.

**Comment by CHamburr** [comment]
@SebbyLaw A better way of doing this is `file.reset()`.

**Comment by nfearnley** [comment]
At the moment, when you create a Discord.File(fp) object, discord.py monkeypatches the fp.close() method to prevent aiohttp from being able close the fp after it attempts to send it. This allows discord.py to try resending the file after a failed attempt.

After discord.py finishes sending the file (or finishes failing to send the file), the fp.close() is _un-monkeypatched_, **BUT** discord.py does not close the file. This allows you to close the file yourself.

On subsequent reuses of the same Discord.File object, the fp.close() is now _no longer_ monkeypatched, and aiohttp is able to close the fp once a send is completed. This means that after the second ctx.send(file=file) call, aiohttp has closed the fp.

This also has the side-effect of breaking discord.py's retry logic during the second attempt.

So, you should _not_ try reusing the Discord.File object more than once. While it _will_ work on the second reuse, it's retry logic will be broken. And on third and further reuses, the fp object will be closed so the send will fail.

A reasonable alternative would be to just recreate the Discord.File object with the same fp object.
```
f = io.BytesIO(my_bytes)
await ctx.send(file=discord.File(f, filename='my_file'))  # sends the file properly
await ctx.send(file=discord.File(f, filename='my_file'))  # sends the file with zero bytes
await ctx.send(file=discord.File(f, filename='my_file'))  # error
```

**Comment by The-Bow-Hunter** [comment]
@Rapptz would it be possible to at least add a function like File.copy()?
