### ISSUE TITLE
Member.roles string does not work properly in embeds for some members

### ISSUE THREAD

**Issue by PimNelissen** [Rapptz/discord.py#4025]
Hi,

It seems like there's a weird problem with discord.py or discord's API when trying to mention people. Seems that while some people can be mentioned by doing <@USER_ID>, others must be mentioned using <@!USER_ID>. Simply using the mention attribute of a members seems to sometimes return a proper mention in embeds, while sometimes an incorrect one (see image below). Is there any solutions to this?

Edit: I am on discord.py 1.3.3
![image](https://user-images.githubusercontent.com/52689414/79963766-1885da00-848a-11ea-99b8-db032871c51d.png)

**Comment by SebbyLaw** [comment]
This is a client side issue, not with the api.

**Comment by Rapptz** [comment]
Embeds only render mentions of cached users.
