### ISSUE TITLE
purge is no-longer working

### ISSUE THREAD

**Issue by Moooog** [Rapptz/discord.py#4033]
### Summary

Went to purge some text and it didn't purge. Testing in another server and a test command and same results of no messages getting deleted. Asked in thbe discord sever in the #help section and it also wasnt working for them

### Reproduction Steps

```
    @commands.command()
    async def test(self, ctx, number: int):
        await ctx.channel.purge(limit=number)
        await ctx.send("done.")
```

 >test 10
Nothing deletes

### Expected Results

>test 10
10 messages deleted

### Actual Results

No messages deleted, no errors, etc. 

### Checklist

- [ x ] I have searched the open issues for duplicates.
- [ ] I have shown the entire traceback, if possible.
- [ ] I have removed my token from display, if visible.

### System Information

- Python v3.8.2-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v6.0
- system info: Windows 10 10.0.18362

**Comment by Moooog** [comment]
gif: https://gyazo.com/3944fa7cd966dfb73486b4b1de2c6af4

**Comment by Moooog** [comment]
messages deleted minutes after purge. I assume it's an API issue checking https://status.discordapp.com/ there has been a recent issue however its said to be resolved and was 9 hours from now.

**Comment by FightMan01** [comment]
I think this is an API issue, because my bot and other bots produces this as well.
