### ISSUE TITLE
send doesn't work

### ISSUE THREAD

**Issue by Gadzillion** [Rapptz/discord.py#4034]
### Summary

my ```ping``` command doesn't work

### Reproduction Steps

1. Run bot;
2. Write 'blink' to the chat;
3. Write 'ping' to the chat.

### Expected Results

Ping command will work.

### Actual Results

Ping command doesn't work.

### Code
```py
TOKEN = "..."

prefix = '?'
description = '''dessc'''

bot = commands.Bot(command_prefix=prefix, description=description)

@bot.command()
async def ping(ctx):
    await ctx.send('Pong')

@bot.event
async def on_ready():
    print('Bot is ready to go \nIf {0.user} say so'.format(bot))
    print('--------------------------')

@bot.event
async def on_message(message):
    if message.content.startswith("blink"):
        msg = await message.channel.send("Hi")
        await asyncio.sleep(1)
        await msg.edit(content="Ho")

bot.run(TOKEN)
```

### System Information

```txt
- Python v3.6.5-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Windows 10 10.0.18362
```

**Comment by Rapptz** [comment]
https://discordpy.readthedocs.io/en/latest/faq.html#why-does-on-message-make-my-commands-stop-working

**Comment by Gadzillion** [comment]
@Rapptz 
The "ping" function works, but if you use it after "blink" it doesn't.

**Comment by Rapptz** [comment]
@Gadzillion Please read the actual link. It shows how to solve your issue.

Essentially you have to add a `process_commands` call in your `on_message`.

**Comment by Gadzillion** [comment]
@Rapptz sry)

**Comment by helish88** [comment]
🤦
