### ISSUE TITLE
User Input Into String?

### ISSUE THREAD

**Issue by IfYouWouldStop** [Rapptz/discord.py#4048]
How would a make a users input into a string variable that I can use?

**Comment by MinerChAI** [comment]
GitHub issues are for reporting problems and making suggestions for discord.py. They're not a medium for help with Python or discord.py. Consider joining official [python guild](https://discord.gg/python) or [discord.py guild](https://discord.gg/r3sSKJJ) for that.

**Comment by MiguelCodes** [comment]
You can alternatively use 'message.content', since that is what I have been using for my SmartBot.

**Comment by Westo48** [comment]
`async def method(ctx, *, variable_name):`

This is an example, but using the `(ctx, *, variable_name)` will create a variable variable_name and set it to the user's input.

As @MinerChAI said this is not an issue for github.

**Comment by Rapptz** [comment]
https://discordpy.readthedocs.io/en/latest/ext/commands/commands.html
