### ISSUE TITLE
Error when setting emoji in the CustomActivity

### ISSUE THREAD

**Issue by FightMan01** [Rapptz/discord.py#4049]
### Summary

I'm trying to set a custom activity and getting an error.

### Reproduction Steps

```py
            cs = discord.CustomActivity(name="Custom status lol :P", emoji=discord.PartialEmoji(name='🤔'))
            await self.client.change_presence(activity=cs)
```

### Expected Results

The status will be set.

### Actual Results

First try with PartialEmoji (as seen in the docs):
```
Traceback (most recent call last):
  File "/Users/nemetharon/Desktop/FightMan01_bot/1.2.3/cogs/status.py", line 30, in on_status_ready
    cs = discord.CustomActivity(name="Custom status lol :P", emoji=discord.PartialEmoji(name='🤔'))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/activity.py", line 696, in __init__
    self.emoji = PartialEmoji.from_dict(emoji)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/partial_emoji.py", line 80, in from_dict
    return cls(animated=data.get('animated', False), id=data.get('id'), name=data.get('name'))
AttributeError: 'PartialEmoji' object has no attribute 'get'
```

Second try with a simple string:
```
Traceback (most recent call last):
  File "/Users/nemetharon/Desktop/FightMan01_bot/1.2.3/cogs/status.py", line 30, in on_status_ready
    cs = discord.CustomActivity(name="Custom status lol :P", emoji='🤔')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/activity.py", line 696, in __init__
    self.emoji = PartialEmoji.from_dict(emoji)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/partial_emoji.py", line 80, in from_dict
    return cls(animated=data.get('animated', False), id=data.get('id'), name=data.get('name'))
AttributeError: 'str' object has no attribute 'get'
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.8.2-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v6.0
- system info: Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64

**Comment by Vexs** [comment]
Bots can't have a custom statuses, but that said, this is either a documentation error or lib bug, as indeed, this doesn't work.

**Comment by webkaiyo** [comment]
Indeed, this is a bug caused by [this](https://github.com/Rapptz/discord.py/blob/e473f3c775b26a4bb54b18eb6240757306f4f5c1/discord/activity.py#L696) line. The documentation says that the `emoji` parameter receives an object of type `PartialEmoji` (as you did), but, in fact, it should receive a `dict` data to `PartialEmoji.from_dict` to create the object itself.

**Comment by Gugu7264** [comment]
Again, bots can't have a custom status, so you cannot run your code without having an error

**Comment by webkaiyo** [comment]
Even though bots cannot have emojis in `CustomActivity`, the error he gets does not match the documentation.

**Comment by FightMan01** [comment]
Thank you for the reply!
I just tried it.
But I think the docs should be inform me about it.
