### ISSUE TITLE
Allow extensions to do cleanup when being unloaded

### ISSUE THREAD

**Issue by ButterCheezii** [Rapptz/discord.py#405]
In an extension, when working with threads they will stay running when `unload_extension` is called.

I want you to allow the extension to have an `unload()` function that is called before unloading the extension, so we can have a chance to clean up any open file handlers, stop threads, etc.

**Comment by adongy** [comment]
that's called __unload.

**Comment by fwrs** [comment]
me too

**Comment by khazhyk** [comment]
There is already a __unload special method for cogs. (Note, not extensions)

**Comment by mikevb1** [comment]
Looking in the source, the function name should be `_ClassName__unload`, not `__unload`, correct?

**Comment by khazhyk** [comment]
No, the function name should be __unload, the python interpreter automatically translates double-underscore methods to that form.

**Comment by Maverun** [comment]
no, just 
```py
def __unload(self):
    pass
```

given example from Danny's bot
https://github.com/Rapptz/RoboDanny/blob/master/cogs/splatoon.py#L47

**Comment by ButterCheezii** [comment]
Does `unload_extension` call `__unload`?

**Comment by khazhyk** [comment]
unload_extension will call remove_cog on all cogs in the extension, which will call __unload

**Comment by ButterCheezii** [comment]
Yeah, unfortunately my bot uses extensions to add functionality (such as auto-reloading extensions when the file is updated) and since there is no chance to cleanup when the extension is reloaded, some tasks get messed up.

**Comment by khazhyk** [comment]
A workaround would be organizing your extensions into cog classes, and using bot.add_cog(), which will hook into the __unload thing.

**Comment by ButterCheezii** [comment]
I could, but I can't be arsed to re-do the entire bot. So I'll have to stick with my current solution, using a separate function to call the `unload` function if it exists before unloading it.

**Comment by khazhyk** [comment]
A very simple way would be to just have a dummy class.

```py
class MyCog:
  def setup(self):
    call_ur_setup()
  def __unload(self):
    call_ur_cleanup

def setup(bot):
  cog = MyCog()
  cog.setup()
  bot.add_cog(cog)
```

If there is interest in adding extension unloading, that might be possible to. Up2danny

**Comment by ButterCheezii** [comment]
My current solution works now, which is what matters to me. Of course it's up to danny to decide whether this should be a feature, or if it's too easy to work around. It's still a feasable nice-to-have, though.
