### ISSUE TITLE
Custom status not working

### ISSUE THREAD

**Issue by ldare373** [Rapptz/discord.py#4051]
Hi, I am having some issues with setting a custom status for my bot. I have tried the following in on_ready()

`await client.change_presence(activity=discord.Activity(type=discord.ActivityType.playing, name="status"))`
Sets the status to "Playing status"

`await client.change_presence(activity=discord.Activity(type=discord.ActivityType.listening, name="status"))`
Sets the status to "Listening to status"

But `await client.change_presence(activity=discord.Activity(type=discord.ActivityType.custom, name="status"))`
Does not set a status.

Am I  doing something wrong?

Thanks in advance, Ldare373

**Comment by webkaiyo** [comment]
Bots cannot have custom status.

**Comment by helish88** [comment]
`# Setting `Playing ` status
await bot.change_presence(activity=discord.Game(name="a game"))

# Setting `Streaming ` status
await bot.change_presence(activity=discord.Streaming(name="My Stream", url=my_twitch_url))

# Setting `Listening ` status
await bot.change_presence(activity=discord.Activity(type=discord.ActivityType.listening, name="a song"))

# Setting `Watching ` status
await bot.change_presence(activity=discord.Activity(type=discord.ActivityType.watching, name="a movie"))`

**Comment by ldare373** [comment]
Is there a reason they cannot have a custom status, or is is just not added yet?

**Comment by Vexs** [comment]
Discord disallows bots to have a custom status. Watching/playing/etc statuses are the only ones allowed.
