### ISSUE TITLE
Embed.from_dict does shallow copy for some attributes

### ISSUE THREAD

**Issue by return0927** [Rapptz/discord.py#4055]
### Summary
`Embed.from_dict` does shallow copy for the following attributes
```
thumbnail, video, provider, author, fields, image, footer
```

### Reproduction Steps
```py
>>> e.add_field(name="foo", value="bar", inline=False)
<discord.embeds.Embed object at 0x000001FF89E6D4C8>
>>> e_c = e.copy()
>>> e.add_field(name="bar", value="foo", inline=False)
<discord.embeds.Embed object at 0x000001FF89E6D4C8>
```

### Expected Results
```py
>>> id(e._fields)
2197039694216
>>> id(e_c._fields)
2197039694600  # Something different address
>>> e.fields
[EmbedProxy(inline=False, name='foo', value='bar'), EmbedProxy(inline=False, name='bar', value='foo')]
>>> e_c.fields
[EmbedProxy(inline=False, name='foo', value='bar')]
```

### Actual Results
```py
>>> id(e._fields)
2197039694216
>>> id(e_c._fields)
2197039694216
>>> e.fields
[EmbedProxy(inline=False, name='foo', value='bar'), EmbedProxy(inline=False, name='bar', value='foo')]
>>> e_c.fields
[EmbedProxy(inline=False, name='foo', value='bar'), EmbedProxy(inline=False, name='bar', value='foo')]
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information
- Python v3.7.6-final
- discord.py v1.2.5-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Windows 10 10.0.18362

**Comment by return0927** [comment]
As I found at [document](https://discordpy.readthedocs.io/en/latest/api.html#discord.Embed.copy), Embed.copy does shallow copy. But does it need to be a deep copy for the purpose to do copy?

**Comment by Rapptz** [comment]
Yeah this is by design. If you need a deepcopy you can use `copy.deepcopy` instead.
