### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by CHamburr** [Rapptz/discord.py#4056]
### Summary

There appears to be a severe memory leak in discord.py that can be observed whenever a shard is reconnected.

From the graph below, you can see that there are spikes in memory usage (that are typically within a period of 30 seconds). This is definitely not the behaviour of caching. Please ignore the drops at around 12:00 as I was testing out some restarts.

Also, you can see a snapshot (of another timeframe) that includes more graphs at [this link](http://discordtemplates.me:3000/dashboard/snapshot/nDc4JHOMNkcIVrZIh5m2ljO1VrIpgG7D).

![](https://media.discordapp.net/attachments/577008769297285130/706687329330528285/IMG_20200503_220042.png)

I have gone down to the logs and saw something similar to the following whenever a spike occurs. This could be potentially related to #2654. I can try out the new sharding design when it goes stable. Either way, the memory leak still exists.

![](https://media.discordapp.net/attachments/577008769297285130/706498795009212426/unknown.png)

### Reproduction Steps

You *should* be able to reproduce the issue by running any bot with AutoShardedClient. Some monitoring is needed to observes the spikes though. 

Note: While you don't need a significant amount of guilds to observe this, something above 2000 would be necessary.

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.8.0-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v6.0
- system info: Linux 4.15.0-99-generic #&#x2060;100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020

**Comment by Rapptz** [comment]
Chances are this is just the message cache maintaining strong references to prior Guild objects. I'm aware of this "issue". You can try disabling the message cache if you don't need it for now by passing `max_messages=None` in the constructor or just wait until the message in question cycles out and the GC takes care of it.

**Comment by CHamburr** [comment]
👌 Disabled message cache, will observe and report back later. Personally I don't see the GC helping, memory runs out after a few days and have to do restarts.

**Comment by CHamburr** [comment]
@Rapptz Looks like it's not related to message cache. I am still seeing similar spikes in memory usage after disabling the cache.

Also I am using this code to manually trigger the spike:
```py
import asyncio
from discord.gateway import ResumeWebSocket
await bot.shards[5].ws.identify()
raise ResumeWebSocket(5)
```

**Comment by Rapptz** [comment]
Well, this issue as-is is pretty inactionable then since I can't reproduce it.

Likewise, that approach to "manually reconnect" goes against how the actual reconnect flow works so I heavily advise you not to mess with the websocket that way.

If you want to properly debug a memory leak and get meaningful information out of it there's a message pinned in the official server to get you started -- but until that happens there's not much I can do in this case.

**Comment by CHamburr** [comment]
Had further discussions with Danny on Discord and we also tested out more things. Here is a summary of the conclusions made.

- This issue *does* exists, and you can observe the increase in memory whenever a single shard restarts (and re-identifies). You should be able to reproduce the issue with this code: https://mystb.in/jemepucuzu.py
- This most probably doesn't have to do with the library itself, it is due to the nature of python's memory allocator of not freeing small blocks often, or it is just not claiming back the memory for some reasons.
- For long-term, there is no easy fix for this issue. Danny is thinking of trying [jemalloc](https://github.com/jemalloc/jemalloc) as an alternative memory allocator.

**Comment by CHamburr** [comment]
Closing because this is fixed in sharding rework
