### ISSUE TITLE
Embed Footer Hyperlink Support

### ISSUE THREAD

**Issue by MurphyPone** [Rapptz/discord.py#4059]
### The Problem

Hyperlinks are currently not supported in the footer section of embedded messages.

### The Ideal Solution

Allow hyperlinks in the footer of embedded messages similar to to normal fields.

**Comment by zomatree** [comment]
This is a discord limitation not discord.py

**Comment by MurphyPone** [comment]
> This is a discord limitation not discord.py

Thanks for the swift response, sorry for my ignorance. 

Cheers!

**Comment by Noam188** [comment]
I was wondering the same! thanks for clarifying!

**Comment by Bituvo** [comment]
same
