### ISSUE TITLE
Command to install

### ISSUE THREAD

**Issue by ItsFenixMC** [Rapptz/discord.py#406]
Hello, when installing I encounter the issue when entering the command to install it.

it says python3 -m pip install -U discord.py

where as that does not work, infact;

py -m pip install -U discord.py works, please update the bio,

**Comment by DefaltSimon** [comment]
It depends on your python installation.
Some have python, some python3 or python3.5 and you have py.
It would be a burden to document every possible installation, so that's a part you have to figure out yourself, i suppose.

**Comment by jaydenkieran** [comment]
Yes, it can be `py`, `python`, `python3`, `python3.5` etc. No need to document every possible command.

**Comment by GetRektByMe** [comment]
Nice parrot of exactly what @DefaltSimon said Jayden <3

**Comment by jaydenkieran** [comment]
I'm more important
