### ISSUE TITLE
Change of Discord domain from discordapp.com to discord.com

### ISSUE THREAD

**Issue by Catbuttes** [Rapptz/discord.py#4063]
### The Problem

Discord is moving from discordapp.com to discord.com as per [this notification](https://discordapp.com/channels/613425648685547541/697138785317814292/706944540971630662)

### The Ideal Solution

Replace all references to discordapp.com to discord.com within discord.py

### The Current Solution

No other solution available at this time

### Summary

If the domain used to connect to the discord servers is not changed by November 7th 2020 then clients using the library will be unable to connect.

**Comment by avayert** [comment]
There is already a [pull request open for this](https://github.com/Rapptz/discord.py/pull/4062).

**Comment by Catbuttes** [comment]
Damn. I checked recent issues and commits but forgot tot check pull requests. I won't create another one then if it is already in hand!

**Comment by Harmon758** [comment]
This should be resolved with https://github.com/Rapptz/discord.py/commit/66c6be50d8ac5d401a658c757c5f1ccb454c798b, which was released in v1.4.0.
