### ISSUE TITLE
Give role to discord user on certain message.

### ISSUE THREAD

**Issue by HypaBoss** [Rapptz/discord.py#4065]
### The Problem

I cannot find out how to add a certain role from my discord server on the message -attack.

### The Ideal Solution

I would like to be able to people in the server a role if they send the message -attack.

### The Current Solution

I cannot find any.

### Summary

I would like to find out how I can add a role on the certain message. I have been researching this for a few hours and cannot find and answer on how I can put this into my code.

**Comment by zomatree** [comment]
questions like this should be asked in the support discord server (https://discord.gg/dpy) not on github issues

**Comment by UsersDoProgram** [comment]
You want to allow for automated role distribution based on messages correct?

**Comment by Westo48** [comment]
I use
`async def role(ctx, player_name):`
They call the command and type in their player name, it checks an api against the player name they entered, then it gives a string based on their role in the backend api. 'Member' for instance.
`member_role = discord.utils.get(member.guild.roles, name=new_role)`
This checks the created roles against the name you send it (again in this case 'Member'.
`await ctx.message.author.add_roles(member_role)`
then this will give the author of the message the role from member role.

This is how I have gone about it. Basically get the role from discord.utils.get from above and set it to the member using the add_roles.

As @Zomatree mentioned this is best not to be put on github issues. A different forum would be ideal for this sort of question.
