### ISSUE TITLE
Error during shard reconnect causes all discord.py calls to block

### ISSUE THREAD

**Issue by TorKallon** [Rapptz/discord.py#4067]
### Summary

Roughly once a day we see the following error occur during a shard invalidation and reconnect. After that occurs everything locks up because all discord.py call block forever. 

### Reproduction Steps

<img width="1283" alt="Screen Shot 2020-05-05 at 2 05 22 PM" src="https://user-images.githubusercontent.com/217879/81119101-f440e900-8ede-11ea-9240-d672d166c379.png">

### Expected Results

I expect it to not crash. 

### Actual Results

After that stack trace all discord.py calls block forever. 

### Checklist
- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### System Information

- Python v3.6.3-final
- discord.py v1.3.1-final
- aiohttp v3.6.2
- websockets v6.0

**Comment by Miolus** [comment]
I also have the issue with d.py 1.5.1, debian 10, python3.8.2, AutoShardedBot, with only not reconnecting and blocking without exception.
