### ISSUE TITLE
You cannot change default notifications setting

### ISSUE THREAD

**Issue by PanKlipcio** [Rapptz/discord.py#4074]
### Summary

You cannot change default notifications setting.

### Reproduction Steps

`await guild.edit(default_notifications=NotificationLevel.only_mentions)`

No error is shown but the debugger detects:
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/kacper/.local/share/virtualenvs/arwatbot-68U9yBdw/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "/home/kacper/PycharmProjects/arwatbot/maker.py", line 73, in on_message
    await msg.guild.edit(default_notifications=NotificationLevel.only_mentions)
  File "/home/kacper/.local/share/virtualenvs/arwatbot-68U9yBdw/lib/python3.8/site-packages/discord/guild.py", line 1053, in edit
    default_message_notifications = int(fields.pop('default_notifications'))
TypeError: int() argument must be a string, a bytes-like object or a number, not '_EnumValue_NotificationLevel'
```

### Expected Results
Notification level should change

### Actual Results
Nothing happens

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information
- Python v3.8.2-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Linux 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020

**Comment by avayert** [comment]
Fixed in #4047
