### ISSUE TITLE
Send Custom Animated Emoji Using Discord Bot

### ISSUE THREAD

**Issue by ShivangYT** [Rapptz/discord.py#4084]
I just made  a say command by which if i do {prefix}say "Some text" the bot will send the same message to same channel.

But i want custom server animated emojis in that message too but i don't have Nitro.

If i do >say <a:sad:708956905476980807> initially my message converted to >say :sad:

and my bot responds with :sad: how to fix that or is there any other way to do that.

Note: I don't only want emojis I want message content to in that command

Thanks

**Comment by slice** [comment]
This has nothing to do with the library itself. Discord processes user messages serverside to prevent non-Nitro users from being able to send emojis from other servers.

You can get around this by providing an alternative emoji syntax (that isn't processed by Discord) and transforming it as part of your bot code into an actual emoji code.
