### ISSUE TITLE
MacOS Python 3.8 SSL Error

### ISSUE THREAD

**Issue by Vigress** [Rapptz/discord.py#4092]
No sure if this has been addressed or not but when I run the bot with PyCharm or within any other terminal I get an SSL error.
Is there going to be a fix for this?
Once again, sorry if this has been addressed before.
Thanks!

**Comment by FightMan01** [comment]
Run the `Install Certificate.command` from the python 3.8 folder (located in the application folder)
<img width="571" alt="image" src="https://user-images.githubusercontent.com/29693718/81730842-73f62700-948e-11ea-8803-4ac28cb5e41b.png">

**Comment by Vigress** [comment]
Thanks!!
