### ISSUE TITLE
on_guild_channel_update edge case

### ISSUE THREAD

**Issue by diceroll123** [Rapptz/discord.py#4098]
### Summary

`on_guild_channel_update` does not work as expected if you move a channel from one category to another using code. Moving the channel by hand in the client works properly.

### Reproduction Steps

Move a channel from one category to another, using code, with an `on_guild_channel_update` listener checking the `before.category.id` and `after.category.id`. Compare them, they're the same.
`await ctx.channel.edit(category=other_category)`

### Expected Results

`on_guild_channel_update` to have the proper `before.category`

### Actual Results

`before.category.id` is the same as `after.category.id`

---

`GuildChannel._edit` updates the channel with the new category as you run it, and when `ConnectionState.parse_channel_update` is called, the channel already has the new category, so `before.category` is the new category. Given the other possible parameters that may affect it, I don't see a solution to this that isn't hacky.

**Comment by diceroll123** [comment]
The only *small* change that seems to work so far is removing `self._update(self.guild, data)` from `GuildChannel.edit` (and I suppose from `CategoryChannel.edit` for consistency) and just letting the gateway update the channels...

...but I have the strangest feeling that this change won't get pulled. _Side effects unknown._

**Comment by diceroll123** [comment]
Slight necrobump. Because I like bringing this issue up for educational purposes as well as just to meme. I will try to paint a better picture of what's wrong here, because people seem to not understand after reading, which is fair, it's a weird bug.

In as few words as possible to explain this bug thoroughly: You tell the channel to change categories -- and it does -- but due to the way discord.py is written, it's unable to internally dispatch that it has changed. Changing the channel category manually in the Discord client, it all works fine because discord.py is receiving all of that changed data through the gateway.

---

In my previous comment, I suggested removing the code that edits the Channel object in-place, so that it can update the data from the gateway.

In the picture below, I show why this isn't a good idea.
![unknown (1)](https://user-images.githubusercontent.com/1243957/99957041-e7c99400-2d3b-11eb-8267-a64b96fe05e1.png)

In this code, I essentially toggle a channel's category between two hard-coded category IDs, and I compare the current category ID to the one it *should* be.

Relying on the gateway to dispatch changes is not as fast as editing in-place and hoping for consistency later, because I immediately start doing things involving the data that I expect to have changed, the category ID. In the code I suggest that waiting 1 second is plenty, but that may just be for my bot which isn't very large, thus not receiving a ton of gateway packets. In short, this bandage fix isn't sufficient even for me, and it definitely won't scale well for large bots *if they were to try to do this very specific thing I am trying to do here*.

---

@Rapptz said in the d.py server: `there is no way to fix that issue w/o ruining in-place edits` and I've got to agree. 😭

**Comment by mikeshardmind** [comment]
I said some things about this in d.py's general chat, but I'd like to move them here for others curious, and to (hopefully) have a path forward for people experiencing this, even if it has to wait for a breaking version.


Let's start with the assumptions I made. If any of these are incorrect, it may indicate that what I outline here needs reconsideration, or at least checking that even after correcting the assumptions, the proposal works.


1. Keeping the in place edit is desirable to the library design.
2. It is desirable that events dispatched by the library are accurate.
3. It is desirable that the cache reflect the events received from discord.


These three assumptions appear to be incompatible at first glance. The inplace edit (1) violates (3)

I think the below works, but it has some sharp edges that I'm not sure are worth it.

1. User edits something
2. library determines if the object is cached and events are received for the object.
3a. If not, edit proceeds as current, and we are back out of library code.
3b. Using what has changed about the object, create a check which would indicate the new state contains the changes
4. edit proceeds without modifying the cached object.
5. If the edit does not error, wait for the cache to meet the condition determined in 3b, then return to user code.

This has some issues that could arise with eventual consistency and no guarantee of delivered events.


From this, I don't think it's worth fixing with this particular solution, at least not by default. It would seem preferable in the next breaking version to have separate edit and edit_in_place methods, with edit_in_place using logic described above and having a documented timeout on waiting for such a condition, raising a timeout error should that be hit for the consumer to determine how they wish to continue from there.

This would allow leaving the inplace edit for convenience where it matters, while correcting the event dispatch and the correctness of the cache with regard to received events.

**Comment by mikeshardmind** [comment]
Since an approach waiting on a corresponding event was rejected (see #6481) 

Would it be an acceptable behavioral change to remove the in-place edit for 2.x and have it return a new, non-cached object in any case where discord returns with a corresponding payload? This loses the in-place edit behavior (breaking change) but it works with HTTP only cases still and wouldn't have the issue of the cache having multiple sources of truth.
