### ISSUE TITLE
Channel.create_invite() fails

### ISSUE THREAD

**Issue by LoliHaxxer** [Rapptz/discord.py#4106]
Getting this for Channel.create_invite(), data or date['guild'] seems to be a string.
discord.py Version 1.3.3
1 person on the discord.py discord server could not reproduce this.

MNRE:
import discord

client = discord.Client()

@client.event
async def on_message(message_object):
	if message_object.guild:
		await message_object.channel.create_invite()

client.run(token)

Exception:
Traceback (most recent call last):
  File "discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "script.py", line 73, in on_message
    message_object.channel.create_invite()
  File "discord\abc.py", line 719, in create_invite
    return Invite.from_incomplete(data=data, state=self._state)
  File "discord\invite.py", line 282, in from_incomplete
    guild_id = int(data['guild']['id'])
TypeError: string indices must be integers

You can try and reproduce it, would like to have some feedback.

Can't come up with a reason how this is a local problem.

**Comment by Rapptz** [comment]
This only happens if you're running on a user account.

**Comment by LoliHaxxer** [comment]
Ah, I see. I guess updating the docs would help then. I didn't even suspect this to be a cause since other bot-only functions are annotated with 'This can only be used by bot accounts.' in the docs.
