### ISSUE TITLE
@commands.check problem

### ISSUE THREAD

**Issue by Nisutec** [Rapptz/discord.py#4107]
### Summary
I have a code like this:
https://pastebin.com/T47SzR6L

### Reproduction Steps

Use the "@commands.check" methode like you can see at my code

### Expected Results
Only the output and not the exeption.

### Actual Results
A Error on the Console like this:
https://pastebin.com/y9CFNvae

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information
- Python v3.7.4-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v6.0
- system info: Windows 10 10.0.18362

**Comment by XuaTheGrate** [comment]
According to your traceback, your exception is not coming from that command, but from this line:
```python
  File "C:\Users\Niclas\PycharmProjects\discord-bot\modules\ranking-mod.py", line 90, in on_message
    if guild_is_permited(message.guild.id):
```
Furthermore, this is not an issue with discord.py.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.
For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends

**Comment by Harmon758** [comment]
Those pastes are no longer available.
