### ISSUE TITLE
add_roles() doesnt work

### ISSUE THREAD

**Issue by DiamondDemon669** [Rapptz/discord.py#4110]
### Summary

i tried doing member.add_roles(role) but it just didnt work

### Reproduction Steps

i ran a command that would store role mention and give it to a user

### Expected Results

I expected the bot to give a mentioned role

### Actual Results

I have no idea what happened it just said it didnt work and it was something to do with the source code

**Comment by DiamondDemon669** [comment]
i accidentally clicked close issue i was supposed to click comment

**Comment by bijij** [comment]
Hi there, questions like these should be asked in the [discord.py support server](https://discord.gg/r3sSKJJ) rather than in GH issues.

**Comment by Rapptz** [comment]
The way this issue is currently framed is inactionable. There is not much provided to point to a library issue nor is there any information to help you out here such as code or traceback. If you have a question about the library please use [the official server](https://discord.gg/dpy) instead.
