### ISSUE TITLE
Cache is not populated when inside on_ready()

### ISSUE THREAD

**Issue by axc450** [Rapptz/discord.py#4112]
### Summary
When starting up a bot, I would like for a message to be sent to a channel. I attempted to do this in a `discord.Client` `on_ready()` event but every attempt to read the cache for the channel returns None. Fetching **does** work.

### Reproduction Steps
Startup
```
def connect(token):
    print("Connecting to Discord...")
    client = Automod()
    client.run(token)
```

Bot class (xxx is an **int** channel id)
```
async def on_ready(self):
        print(self.get_channel(xxx))
        print("Connected!")
```

- If I were too do `self.get_channel(xxx)` inside the `on_message` event - this works. It only seems to be when trying to access the cache inside `on_ready`.
- Using `await self.wait_until_ready()` inside the `on_ready` still doesnt work.
- I am migrating away from a DJS app - I do not see this issue with the JS version of `on_ready`.

### Expected Results
```
Connecting to Discord...
channel
Connected!
```

### Actual Results
```
Connecting to Discord...
None
Connected!
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information
- Python v3.7.3-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Linux 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019

**Comment by Gobot1234** [comment]
I imagine since you are coming from DJS you are used to channel ids being a string, this however is not the case with this library, you need to use an int instead. That should fix the issue 👍.

**Comment by Rapptz** [comment]
I can't really reproduce this. What do the logs show?

**Comment by axc450** [comment]
Using the code snippet here: https://discordpy.readthedocs.io/en/latest/logging.html
Produced:
[discord.log](https://github.com/Rapptz/discord.py/files/4673393/discord.log)

It doesnt look like there's any sensitive info in the debug log, but I cant be sure, so let me know if anything needs regenerating after sharing the above.

**Comment by Rapptz** [comment]
For whatever reason you're not getting the GUILD_CREATE from the one guild your bot is on. It seems Discord thinks it's unavailable for whatever reason. There's a timeout in there for 2 seconds (which is enough for every bot out there) for waiting for the guild to come up before firing the READY event. Looking at the 5 second lifetime of your bot it didn't fire in that time. I'm unsure what's making it take so long. The guild could genuinely just be unavailable.

**Comment by axc450** [comment]
Thanks for the explanation! The guild in question is quite large (many members, channels etc) which might factor into this issue? I don't know if the guild is actually unavailable - this has a 100% reproduction rate across the last week (including the test I just ran now); I have seen this issue every time I start the bot. Let me know if there's anything further you need me to test. Is there a way to manually raise the timeout?

**Comment by Rapptz** [comment]
I've allowed the timeout to be configurable in another branch. It'll be added in the next release. The name is of course not final and it's unstable but if you want to test it out you're free to do so in the sharding-rework branch.

**Comment by axc450** [comment]
Perfect, much appreciated.
