### ISSUE TITLE
await client.wait_for does not work inside cogs

### ISSUE THREAD

**Issue by sarangab** [Rapptz/discord.py#4113]
### Summary
  checkCouponCode = await client.wait_for('message', timeout=1800, check=check)

await client.wait_for commands do not work as expected when used inside the cogs. Example of one such command is above.

It works when the same command is used in a single py file without cogs.

### Expected Results

User gives an input that the bot can process
### Actual Results

No output - nothing happens

**Comment by Phxntxm** [comment]
With only this chunk of code it's pretty in-actionable, though I do have a guess based on what you've said. If you are in a cog and you **create** an instance of `discord.Client` or `commands.Bot` this is an entirely separate instance from the one you're actually connected to discord with. If this is what you're doing, then that's the issue, you need to grab the bot instance that you are actually connected with through some means, for example `ctx.bot`.

Regardless though, this is almost certainly not an issue with discord.py.
GitHub issues for this repository should be used to report issues with this library.
For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by sarangab** [comment]
Sorry about posting here, but your reply is extremely helpful.
client = commands.Bot(command_prefix='.') 
This is what I defined outside the class.

Inside the class, I am using:
def check(m):
                        return m.author != user.user
checkCouponCode = await client.wait_for('message', timeout=1800, check=check)

Could you help me with what is wrong here?
Should I use something like
checkCouponCode = await ctx.client.wait_for('message', timeout=1800, check=check)

**Comment by Phxntxm** [comment]
Like I said in the previous reply, the attribute is `ctx.bot` not `ctx.client`:
https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.Context.bot

Also like I said in the last reply, these types of questions are more suited for asking in the discord.py server... you should join that for questions like this.
