### ISSUE TITLE
connected_accounts not working with author.profile

### ISSUE THREAD

**Issue by ethanopp** [Rapptz/discord.py#4117]
### Summary

I am unable to pull 'connected_accounts' from a profile

### Reproduction Steps

```
    @commands.command()
    async def verify(self, ctx):
        print(ctx.author.profile)
```
returns

`<bound method flatten_user.<locals>.generate_function.<locals>.general of <Member id=376206974167285771 name='HebrewHammer' discriminator='2814' bot=False nick='Ethanopp' guild=<Guild id=712987987142770750 name='EthanOpp Drums' shard_id=None chunked=True member_count=4>>>`

however 

```
    @commands.command()
    async def verify(self, ctx):
        print(ctx.author.profile.connected_accounts)
```

returns

```
Ignoring exception in command verify:
Traceback (most recent call last):
  File "C:\Users\Ethan\PycharmProjects\discordbot-youtube\venv\lib\site-packages\discord\ext\commands\core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Ethan\PycharmProjects\discordbot-youtube\cogs\youtube.py", line 66, in verify
    print(ctx.author.profile.connected_accounts)
AttributeError: 'function' object has no attribute 'connected_accounts'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Ethan\PycharmProjects\discordbot-youtube\venv\lib\site-packages\discord\ext\commands\bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Ethan\PycharmProjects\discordbot-youtube\venv\lib\site-packages\discord\ext\commands\core.py", line 797, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Ethan\PycharmProjects\discordbot-youtube\venv\lib\site-packages\discord\ext\commands\core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'function' object has no attribute 'connected_accounts'

```

### Expected Results

List of connected accounts are returned

### Actual Results

Error above

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.7.1-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Windows 10 10.0.18362

**Comment by Gobot1234** [comment]
Firstly User.profile is only accessible to user bots which are against TOS.
Secondly that is a coroutine meaning you have to await it, which is why it is erroring.

**Comment by ethanopp** [comment]
Okay thanks for the info

**Comment by Synkstar** [comment]
Im wondering how you do it because there is a bot called altdentifier that can get your linked accounts. What I want to do is get the steamid of the attached account

**Comment by Gobot1234** [comment]
You can use OAuth2 to get connected profiles, I imagine that is how they do it.
