### ISSUE TITLE
Question about webhook equality and user attributes

### ISSUE THREAD

**Issue by Znunu** [Rapptz/discord.py#4124]
Few things I ran into, when using the library

- Why is \_\_eq\_\_ not implemented for webhooks?
- Why is the user attribute discriminator a str and not int?
- Why isn't there a boolean attribute that tells if the user is a webhook?

**Comment by zomatree** [comment]
> Why isn't there a boolean attribute that tells if the user is a webhook?

discriminators can have leading `0`'s
> Why isn't there a boolean attribute that tells if the user is a webhook?

webhooks count as bots so unless you have to check if the discriminator is `0000`

**Comment by hamza1311** [comment]
> webhooks count as bots so unless you have to check if the discriminator is `0000`

You can check if `message.webhook_id` is None which is probably better than checking for discriminator

**Comment by Znunu** [comment]
All right, that makes sense. The discriminator could still be int e.g. 0010 --> 10
About the equality, if there's no good reason it doesn't have it, then I think it should be added

**Comment by Rapptz** [comment]
Questions are better suited for the support server here: https://discord.gg/dpy

> Why is `__eq__` not implemented for webhooks?

Mainly oversight.

> Why is the user attribute discriminator a str and not int?

The API returns them as strings and there is no reason for them to not be strings, unlike IDs.

> Why isn't there a boolean attribute that tells if the user is a webhook?

It's not provided in the API and the current best way to do it is to check whether the discriminator is 0000 and the user is a bot.
