### ISSUE TITLE
discord.Guild.premium_subscription_count returns the number of boosts instead of number of boosters

### ISSUE THREAD

**Issue by siddhpant** [Rapptz/discord.py#4125]
### Summary

https://discordpy.readthedocs.io/en/latest/api.html#discord.Guild.premium_subscription_count

The doc states that this should return `How many users have currently “boosted” this guild`.

In one server, a guy has boosted twice, so this returns 2 instead of 1.

This is more of an error in the documentation.

### Reproduction Steps
`guild.premium_subscription_count` for a server where one member has boosted twice.

### Expected Results

Returned value should be 1.

### Actual Results

Returned value is 2.

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.8.2-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v8.1

**Comment by Rapptz** [comment]
Documentation was written when someone could only boost once. This has since changed. This is a documentation issue not an issue with the property.

**Comment by siddhpant** [comment]
I agree. That's what I said too.
