### ISSUE TITLE
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'send'

### ISSUE THREAD

**Issue by azulafns** [Rapptz/discord.py#4136]
Right so im trying to make a command where if i put %say in a channel and it would send it to the annoucments channel no one but the mods and bots can see then but im stuck as i keep getting the error None type has no attribute send

`@bot.command(pass_context=True)
@commands.has_role('Manager')
async def say(ctx, *args):
    message = ""
    message = ' '.join(args)
    channel = ctx.guild.get_channel("714229744798925012")
    await channel.send(channel, message)`
thats the code im using heres the error 
`discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'send'`

**Comment by Vexs** [comment]
IDs are ints, not strings. Judging from some other aspects of your code, you're likely reading outdated documentation, tutorials, or SO answers. 

Additionally, GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.
For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.
