### ISSUE TITLE
Create a method that returns all overwrites for a specific channel

### ISSUE THREAD

**Issue by bsquidwrd** [Rapptz/discord.py#414]
Instead of having to access `channel._permission_overwrites` there should be a method like `channel.get_overwrites()`

**Comment by Rapptz** [comment]
@Merlintor One came before the other. Or rather, back then `overwrites=` accepted a list of tuples similar to what (used to be) `channel.overwrites` returned. During the development of the new version the `overwrites` keyword argument was changed to be easier to use but the format of the `channel.overwrites` was not changed to match it. A case for consistency can be made before official release so I'll consider a breaking change before release.
