### ISSUE TITLE
Direct Conversation

### ISSUE THREAD

**Issue by KvaksMan** [Rapptz/discord.py#4141]
How to make the bot can correspond in private messages?

**Comment by bijij** [comment]
Hi there, questions like these should be asked in the [official server](https://discord.gg/r3sSKJJ) rather than in GH issues.

**Comment by KvaksMan** [comment]
> Hi there, questions like these should be asked in the [official server](https://discord.gg/r3sSKJJ) rather than in GH issues.

For my question nobody wants to answer. Ignore me.

**Comment by shahprog** [comment]
This is not a issue. Its a question. 
But you can handle DMs in `on_message` event.

**Comment by KvaksMan** [comment]
> This is not a issue. Its a question.
> But you can handle DMs in `on_message` event.
> 
> if message have no guild that means thats a DM.
> 
> Add a check if that msg is dm or not and send reply in dm simple

How to check that: have message guild or not?

**Comment by shahprog** [comment]
> > This is not a issue. Its a question.
> > But you can handle DMs in `on_message` event.
> > if message have no guild that means thats a DM.
> > Add a check if that msg is dm or not and send reply in dm simple
> 
> How to check that: have message guild or not?

```
if message.guild is None:
    # Codes
```

**Comment by KvaksMan** [comment]
> > > This is not a issue. Its a question.
> > > But you can handle DMs in `on_message` event.
> > > if message have no guild that means thats a DM.
> > > Add a check if that msg is dm or not and send reply in dm simple
> > 
> > 
> > How to check that: have message guild or not?
> 
> ```python
> if message.guild is None:
>     # Codes
> ```

And if this conditional is true - means message is private?

**Comment by shahprog** [comment]
> > > > This is not a issue. Its a question.
> > > > But you can handle DMs in `on_message` event.
> > > > if message have no guild that means thats a DM.
> > > > Add a check if that msg is dm or not and send reply in dm simple
> > > 
> > > 
> > > How to check that: have message guild or not?
> > 
> > 
> > ```python
> > if message.guild is None:
> >     # Codes
> > ```
> 
> And if this conditional is true - means message is private?

Yes.

**Comment by KvaksMan** [comment]
> > > > > This is not a issue. Its a question.
> > > > > But you can handle DMs in `on_message` event.
> > > > > if message have no guild that means thats a DM.
> > > > > Add a check if that msg is dm or not and send reply in dm simple
> > > > 
> > > > 
> > > > How to check that: have message guild or not?
> > > 
> > > 
> > > ```python
> > > if message.guild is None:
> > >     # Codes
> > > ```
> > 
> > 
> > And if this conditional is true - means message is private?
> 
> Yes. Its better to talk in discord. You can DM me `Shahriyar#9770`

Can I write you if I has questions about discord.py?
