### ISSUE TITLE
Add Type Annotations at least to the data classes

### ISSUE THREAD

**Issue by alkatar21** [Rapptz/discord.py#4150]
### The Problem

Currently in development environments such as PyCharm you don't have autocompletion in many places because the type is not known. This could easily be solved by type annotations and would speed up the writing of bots significantly. Since the type is usually already given in the documentation, this can be implemented quickly.

### The Ideal Solution

My idea would be to at least annotate members of the classes and return types of functions so that development environments can use them. 

### The Current Solution

Currently there is no solution for this in this library.

### Summary

By adding type annotations, the usability in development environments can be increased, because their comfort can be better used.
I could probably provide this as a pull request, since I already have partially annotated it myself to improve my own work.

**Comment by Rapptz** [comment]
https://github.com/Rapptz/discord.py/pull/1497
