### ISSUE TITLE
guild api call fetch emotes doesnt return managed emotes

### ISSUE THREAD

**Issue by TroyDota** [Rapptz/discord.py#4154]
### Summary

guild api call fetch emotes doesnt return managed emotes ie twitch sub emotes.
### Expected Results
guild api call fetch emotes should return all emotes

### Actual Results
guild api call fetch emotes doesnt return managed emotes

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

**Comment by NCPlayz** [comment]
This is an issue with the API, not the library, as all Guild.fetch_emojis does is receive the metadata from the API. It is best to make an issue on the official [respository](https://discord.com/discord/discord-api-docs).

**Comment by TroyDota** [comment]
perhaps this has something to do with #1083

**Comment by Rapptz** [comment]
This isn't a thing controlled by discord.py, this is an API issue.
