### ISSUE TITLE
How to discord bot Send private Message

### ISSUE THREAD

**Issue by CodesGamesYTB** [Rapptz/discord.py#4156]
Français:

Bonjour,
J'ai besoin de votre aide pour crée un bot discord en python.
Je veut que lorsque qu'une personne sur discord fait la commande "s!download", je veut que le bot lui envoie un messages privée en lui donnant un lien de téléchargement (exemple: "Voici le lient du téléchargement: [Lien]") et envoyer un message dans le salon dans lequel la personne a tapé la commande (exemple: "Le lien du téléchargement vous a été envoyer en message privée @LeNomDeLaPersonne")

Et je voudrais pouvoir désactivé/réactivé cette commande avec la commande "s!disable" / "s!enable" quand je fait une mise a jour du pack de texture.
Si la commande a été désactivé, je voudrai que sa envoie un message dans le salon dans lequel la personne a tapé la commande.(exemple: "Le lien du téléchargement a été désactivé temporairement @LeNomDeLaPersonne")

Merci d'avance pour votre aide ;)

English:

Hello,
I need your help to create a discord bot in python.
I want that when a person on discord orders "s! Download", I want the bot to send him a private message by giving him a download link (example: "Here is the link of the download: [Link]" ) and send a message to the room where the person typed the command (example: "The download link was sent to you in a private message @NameOfThePerson")

And I would like to be able to deactivate / reactivate this command with the command "s! Disable" / "s! Enable" when I update the texture pack.
If the order has been deactivated, I would like her to send a message to the room in which the person typed the command. (Example: "The download link has been temporarily deactivated @NameOfThePerson")

Thank you in advance for your help ;)

**Comment by Gobot1234** [comment]
We don't write code for you

**Comment by jack1142** [comment]
Issue tracker should not be used for questions on how to write something with the library, discord.py has a support server for that. There's even a nice button right when you try to create new issue:
![image](https://user-images.githubusercontent.com/6032823/83315881-12221500-a223-11ea-8b56-3081f9009614.png)

**Comment by CodesGamesYTB** [comment]
I know. But it's been several days that I try to find a solution but I have found nothing. I have already tried several code but nothing works because of the code which is not up to date

Sorry I don't speak English so I have to use a translation system

**Comment by Gobot1234** [comment]
Asking in the help channels in the discord server will normally yield the answer to any questions you may have

**Comment by CodesGamesYTB** [comment]
Sorry, I close the topic and recreate it in the right category

**Comment by CodesGamesYTB** [comment]
Which discord server?
