### ISSUE TITLE
Chunking woes with listeners never returning.

### ISSUE THREAD

**Issue by khazhyk** [Rapptz/discord.py#416]
Chunking listeners sometimes never return (~ state.py:184 , asyncio.wait(chunks) ).

This results in
 - old references being held to members and servers resulting in potential memory leak.
 - (perhaps) some servers never properly chunking.

I'm not sure why these listeners never return, but checking bot._listeners often is not empty even well after ready.

**Comment by Rapptz** [comment]
This should be fixed with the recent commits.
