### ISSUE TITLE
Command.brief is None and not first line of long help

### ISSUE THREAD

**Issue by makupi** [Rapptz/discord.py#4161]
### Summary

According to the docs `Command.brief` is supposed to be:

> The short help text for the command. **If this is not specified then the first line of the long help text is used instead.**

From my understanding this would mean that, if it's not specified I'm supposed to get the first line of the long help text instead. But when I used it I get `None`.

### Reproduction Steps

1. write a command with a docstring (long help) without specifying the brief.
2. use `Command.brief` and it should be the first line of the long help

### Expected Results

`Command.brief` should be the first line of the long help.

### Actual Results

`Command.brief` is `None`.

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.8.2-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Windows 10 10.0.19041

**Comment by jack1142** [comment]
I think it's documentation bug (as in, `brief` should only be documented as a parameter that can be passed to Command object, but not as supported attr), but even if I'm wrong, you can use `Command.short_doc` to get the output you expect.

**Comment by makupi** [comment]
Yes, that's what I thought. `Command.help` and `Command.short_doc` work fine. Should just be changed either in the docs or in code imo.
