### ISSUE TITLE
HTTP proxies don't function

### ISSUE THREAD

**Issue by LoliHaxxer** [Rapptz/discord.py#4163]
I am using free http proxies from https://www.proxyscrape.com/free-proxy-list and passing one to the proxy parameter in Client.__init\__.
But running results in Only http proxies are supported, and the proxies seem to function normally outside of using it in this wrapper.

Or is this again an issue that only comes up when using self-bots?

**Comment by feelingnothing** [comment]
discord itself supports only http (and not sure about https) proxies

**Comment by LoliHaxxer** [comment]
Yeah, the problem is it raises a ValueError: Only http proxies are supported, even though these are supposedly http proxies.

**Comment by bokja** [comment]
A Quick bumb anyone else figured this out ended up with the same error on my try

**Comment by kittenswolf** [comment]
@bokja Please share your solution so that others know how to fix it, as well.

**Comment by Rapptz** [comment]
This should be fixed with #2654 complete since it now uses the same proxy info for both the WS and the HTTP functions.
