### ISSUE TITLE
create_custom_emoji hangs forever

### ISSUE THREAD

**Issue by Znunu** [Rapptz/discord.py#4173]
### Summary

Calling create_custom_emoji while being emote rate-limited, will cause it to never return. Well.... I can only guess that it maybe keeps retrying, but the emote rate limit seems to be 30min!!!! 

### Reproduction Steps

Spam a server with emotes

### Expected Results

Throw an exception

### Actual Results

Nothing, bot is stuck

### Checklist

- [ x] I have searched the open issues for duplicates.
- [ x] I have shown the entire traceback, if possible.
- [ x] I have removed my token from display, if visible.

**Comment by zomatree** [comment]
The lib sleeps until the rate limit is over rather than erroring, see https://github.com/Rapptz/discord.py/issues/4155#issuecomment-636269552

**Comment by Znunu** [comment]
Awesome, guess every dev has to go through an obligatory one hour of debugging, because of this.

**Comment by Rapptz** [comment]
Consider not spamming. Rate limits are dynamic and some tend to be long.

**Comment by applebee1558** [comment]
Bypassing ratelimits is against discord’s api terms of service, I would advise you not to do so.

**Comment by applebee1558** [comment]
You can use command cooldowns to block users from spamming.

**Comment by muddyfish** [comment]
A way to return without creating the emoji if it would be rate limited would be useful

**Comment by applebee1558** [comment]
You are always welcome to make your own bot without a library btw. Nobody at Discord said you had to use library wrappers.

**Comment by muddyfish** [comment]
The point of feature requests is to extend the library. I already have a solution to this problem myself by patching out the retrying for my own purposes, but that's completely not the point

**Comment by Rapptz** [comment]
As mentioned in the issue I linked, if you want a timeout then add one yourself using wait_for.
