### ISSUE TITLE
Creating a discord bot on raspberry pi 4 

### ISSUE THREAD

**Issue by Nebulaaaaa** [Rapptz/discord.py#4176]
Hi I recently bought a raspberry pi 4, and I wanted to program a discord bot and run it on my server. However, I have been getting this error from the service I created using systemd

This is the status of the discordbot.service when I boot my raspberry pi. It seems to me that the error is caused by the service and I am not too sure why. I want my discord bot to run automatically whenever I boot up my raspberry pi.
`
● discordbot.service - My Discord Bot Service
   Loaded: loaded (/lib/systemd/system/discordbot.service; enabled; vendor preset: enabled)
   Active: failed (Result: start-limit-hit) since Thu 2020-06-04 11:20:39 +08; 1h 51min ago
  Process: 861 ExecStart=/usr/bin/python3 /home/pi/discordbot/discordbot.py (code=exited, status=0/SUCCESS)
 Main PID: 861 (code=exited, status=0/SUCCESS)

Jun 04 11:20:39 raspberrypi systemd[1]: discordbot.service: Service RestartSec=100ms expired, scheduling restart.
Jun 04 11:20:39 raspberrypi systemd[1]: discordbot.service: Scheduled restart job, restart counter is at 5.
Jun 04 11:20:39 raspberrypi systemd[1]: Stopped My Discord Bot Service.
Jun 04 11:20:39 raspberrypi systemd[1]: discordbot.service: Start request repeated too quickly.
Jun 04 11:20:39 raspberrypi systemd[1]: discordbot.service: Failed with result 'start-limit-hit'.
Jun 04 11:20:39 raspberrypi systemd[1]: Failed to start My Discord Bot Service.
`

This is my service I created using systemd, discordbot.service
`
[Unit]
Description=My Discord Bot Service
After=network-online.target

[Service]
Type=idle
Restart=always
User=pi
ExecStart=/usr/bin/python3 /home/pi/discordbot/discordbot.py

[Install]
WantedBy=multi-user.target
`

This is my python file, discordbot.py
`
import discord
import youtube_dl
from discord.ext import commands

TOKEN = 'my token'

description = '''Bot in Python'''
bot = commands.Bot(command_prefix='?', description=description)

players = {}

@bot.event
async def on_ready():
    print('Logged in as')
    print(bot.user.name)
    print(bot.user.id)
    print('------')

@bot.command()
async def clear(ctx, amount=2):
    """ Clears messages"""
    await ctx.channel.purge(limit=amount)

@bot.command(pass_context=True)
async def join(ctx):
    """ Bot to join voice channel """
    channel = ctx.message.author.voice.voice_channel
    await bot.join_voice_channel(channel)

@bot.command(pass_context=True)
async def leave(ctx):
    """ Bot to leave voice channel """
    server = ctx.message.server
    voice_bot = bot.voice_bot_in(server)
    await voice_bot.disconnect()

@bot.command(pass_context=True)
async def play(ctx, url):
    """ Play music """
    server = ctx.message.server
    voice_bot = client.voice_bot_in(server)
    player = await voice_bot.create_ytdl_player(url)
    players[server.id] = player
    player.start()

bot.run(TOKEN)
`

All help is appreciated :)
Thanks in advance!

**Comment by applebee1558** [comment]
Invalid Issue, it is probably better to ask this in the discord.py server or the python discord. The github is reserved for bugs and suggestions with the library itself, not on how to use.

Also, based on the code, it seems that you’re using the outdated async branch that isn’t supported anymore. Please consider switching to rewrite (1.x.x)
