### ISSUE TITLE
Members CustomActivity text is not updated when they share their screen or stream in discord channel

### ISSUE THREAD

**Issue by mojobojo** [Rapptz/discord.py#4184]
### Summary

From what I observed CustomActivity should be updated with whatever text you see in the status. When I change my own custom status in discord I can see that status in on_member_update and print it out to the console fine. I expect to see the same text when in on_voice_state_update and someone in the channel begins streaming a game or their desktop.

### Reproduction Steps

Use this snippet of code and share your desktop or stream a game in the channel.

```
@client.event
async def on_voice_state_update(member, member_last_state, member_current_state):
    for act in member.activities:
        if act.type is discord.ActivityType.playing:
            print(member.name + " is now playing " + act.name)
        if act.type is discord.ActivityType.streaming: 
            print(member.name + " is now streaming " + act.name)
        if act.type is discord.ActivityType.listening: 
            print(member.name + " is now listening to " + act.name)
        if act.type is discord.ActivityType.watching: 
            print(member.name + " is now watching " + act.name)
        if act.type is discord.ActivityType.custom: 
            print(member.name + " is doing custom status" + act.name)
```

### Expected Results

I would expect to see act.name to contain the status text "Is streaming <game>" or "Is sharing desktop"

### Actual Results

If you were to use this snippet of code and be in a channel it would trigger the custom status but act.name would be empty when you start streaming despite it saying "Is streaming <game>" or "Is sharing desktop" in your profiles status. 

### Checklist

- [ x] I have searched the open issues for duplicates.
- [x ] I have shown the entire traceback, if possible.
- [x ] I have removed my token from display, if visible.

### System Information

- Python v3.8.3-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Windows 10 10.0.18362

**Comment by TroyDota** [comment]
is this a discord.py problem or a discord api problem?
Have you tested with the raw api?

**Comment by Rapptz** [comment]
As far as I'm aware this is unrelated to CustomStatus and involves Streaming instead. However the text for this stuff could be client sided. I'd have to verify this stuff is sent via the gateway but there's no reason this text is dropped so I'm willing to bet it just isn't sent and is client sided.

**Comment by SebbyLaw** [comment]
This text is not part of CustomStatus. It is completely client-sided and dependent on receiving and tracking PRESENCE_UPDATE events.
