### ISSUE TITLE
guild.by_category() not returning empty categories

### ISSUE THREAD

**Issue by Erionline** [Rapptz/discord.py#4186]
### Summary

I was looking for listing all of the channels (including all types) with categories (sorted correctly like in UI) and found that comment from Danny on [issue #2392](https://github.com/Rapptz/discord.py/issues/2392#issuecomment-545738318). I noticed that the result returned by that method ignores empty categories (categories with no channels in it) for some reasons.

### Reproduction Steps

- Create a guild with two categories
- Create some test channels under one of the categories, leave the other empty 
- Use `ctx.guild.by_category()` and see results
```py
    @commands.command()
    async def test(self, ctx):
      await ctx.send(ctx.guild.by_category()) # Supposed to return both categories
      await ctx.send(len(ctx.guild.by_category())) # Supposed to return 2
```

### Expected Results

It should return all categories, so 2 in total.

### Actual Results

It ignores the empty category and only returns one.

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.6.9-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Linux 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2
020

**Comment by Rapptz** [comment]
This should be fixed by https://github.com/Rapptz/discord.py/commit/c01bf7cd564314903c89eb2add4e3271fbef5e69
