### ISSUE TITLE
max_members is always None even if the discord API returns a valid value

### ISSUE THREAD

**Issue by GNUGradyn** [Rapptz/discord.py#4188]
### Summary

discord.Guild.max_members is always None, even if the discord API returns a valid response. I tested this by manually making a GET request to guild/ID on the discord API, and I got 250000. Discord.py still reports this as None
![image](https://user-images.githubusercontent.com/20762604/84088764-83dc2a80-a9aa-11ea-9e89-17e714afc6da.png)

![image](https://user-images.githubusercontent.com/20762604/84088979-0e248e80-a9ab-11ea-8c83-d364ce557611.png)
Code for the Members field is `embed.add_field(name="Members", value=f"{message.guild.member_count}/{message.guild.max_members}", inline=True)`

### Reproduction Steps

1: Try to get the maximum number of users in a server via discord.Guild.max_members
2: Make a GET request to https://discordapp.com/api/guilds/(ID)

### Expected Results
The API and discord.py implementation will both return the same number

### Actual Results
discord.py returns None, API returns an actual number

### Checklist

- [ x] I have searched the open issues for duplicates.
- [ x] I have shown the entire traceback, if possible.
- [ x] I have removed my token from display, if visible.

### System Information

- Python v3.6.9-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Linux 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020

**Comment by Rapptz** [comment]
That attribute is only available through the REST endpoint (as you show). The equivalent in d.py is fetch_guild. The Guild objects are retrieved as part of the gateway API. If you want the information from the REST API then you should query it. 

This looks like a documentation request so I'll leave it open.
