### ISSUE TITLE
Add a user argument to the on_message_delete function

### ISSUE THREAD

**Issue by WorstGamr** [Rapptz/discord.py#4189]
We have no way to know who deleted a message with the `on_message_delete` function. This makes it difficult if not impossible to trace-back an admin gone mad or other moderation-related stuff.

Adding a user argument with the message would be nice. That way we could know who deleted a message.

I don' have a solution atm. I'm sure there is a way, but I don't know it.

**In short, a way to get the user who deleted the message.**

**Comment by Rapptz** [comment]
Discord doesn't provide this functionality.

**Comment by WorstGamr** [comment]
Ah damn. Thanks anyways for responding this fast lol
