### ISSUE TITLE
Usage question: Persistent out-of-band checking

### ISSUE THREAD

**Issue by Anorov** [Rapptz/discord.py#419]
If I wanted to asynchronously check a separate database (requests to an HTTP server) every N seconds, and immediately send a message if there's an update (regardless of what's happening in the Discord room), what would be the most idiomatic way of accomplishing this?

I see that most of the callback functions are for responding to input from the Discord rooms the bot is in; not for receiving input from something outside of Discord.

Thanks.

**Comment by khazhyk** [comment]
Look at the "background task" example in the examples directory. You can have a coroutine running a loop and sleeping in the background.

**Comment by Anorov** [comment]
Thanks, I somehow managed to look at every example except for that one.
