### ISSUE TITLE
Local Variable Client Referenced before assignment

### ISSUE THREAD

**Issue by IdioticProphet** [Rapptz/discord.py#4192]
### Summary
Same as title, it only threw a stack trace after I added a function below it, I believe there is nothing above it to cause that error, since it is a decorated function that should pass client.

Effective Code Sample(trimmed for relevancy)
```
TOKEN = "real-token-is-here"
client = discord.Client()

@client.event
async def on_message(message):
    if message.author == client.user:
        return

client.run(TOKEN)
```
stacktrace
```
  File "/usr/local/lib/python3.8/dist-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "lenin.py", line 60, in on_message
    if message.author == client.user:
UnboundLocalError: local variable 'client' referenced before assignment
```

### Expected Behavior
Not throwing a stack trace

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

Ubuntu 20.04 LTS
Tested with Python 3.8.0 Venv and Python 3.8.2 normal env and Windows on 3.8.1, same error

**Comment by Rapptz** [comment]
An UnboundLocalError is a Python runtime error when you refer to refer to a variable for writing but it's not found in the local scope. This is generally a basic Python error. It's recommended to brush up on Python knowledge before using this library. Note that the minimal code provided here does not have any error since there is no write anywhere.

**Comment by IdioticProphet** [comment]
Yes my apologies, I accidentally copied the same thing... Was about to close when I noticed, Vim bites in the butt

**Comment by IdioticProphet** [comment]
So the problem was that client was redefined later in the function
```
client = discord.Client()

@client.event
async def on_ready():
    logging.info(f"{client.user} Hello World!")


@client.event
async def on_message(message):
    if message.author == client.user:
        return

    if "!poggers" in message.content:
        channel = message.author.voice.channel
        if not channel:
            await message.channel.send("You are not in a voice channel!")
            return
        client = await channel.connect()
        source = FFmpegPCMAudio("poggers.mp3")
        player = client.play(source)
        await client.disconnect()
        return

client.run(TOKEN)
```

It was fixed by renaming the variable to vc instead of client...
