### ISSUE TITLE
AttributeError: module 'discord.ext.commands' has no attribute 'has'

### ISSUE THREAD

**Issue by TheCoolFarshad** [Rapptz/discord.py#4194]
Hi there, I have tried to use the checking feature but i get this error: AttributeError: module 'discord.ext.commands' has no attribute 'has'

Here is the code for it: 
@client.command()
@commands.has.permissions(manage_messages=Ture)
async def clear(ctx, amount=5):
    await ctx.channel.purge(limit=amount)
    
@client.command() 
@commands.has.permissions(kick_members=Ture)
async def kick(ctx, member: discord.Member,*, reason=None):
    await member,kick(reason=reason)

@client.command()
@commands.haspermissions(ban_members=Ture)
async def ban(ctx, member: discord.Member,*, reason=None):
    await member,ban(reason=reason)

@client.command()
@commands.has.permissions(ban_members=Ture)
async def unban(ctax, *, member):
    banned_users= await ctx.guild.bans()
    member_name, member_discrimintor =member.split("#")

    for ban_entry in banned_users:
        user =ban_entry.user
        
        if (user.name, user.discriminator) ==(member.name, member.discriminator):
            await ctx.guild.unban(user)
            await ctx.send(f"Unbanned {user.mention}")
            return

discord.py==1.3.3

**Comment by AlastairWoodbury** [comment]
You're looking for `@commands.has_permissions`, not `@commands.has.permissions`

**Comment by TheCoolFarshad** [comment]
well i changed it but i get a invaild sytax
![image](https://user-images.githubusercontent.com/52294084/84599001-c0a29880-ae66-11ea-947e-7cbe26d0d174.png)

**Comment by Gobot1234** [comment]
There shouldn't be a comma after has_permissions. You also appear to be misusing commas, in place of periods in multiple places.

For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by TheCoolFarshad** [comment]
k i did have comma removed but it gave an error which is on the title
