### ISSUE TITLE
 with open("prefixs.json", "w")     ^ IndentationError: unexpected indent

### ISSUE THREAD

**Issue by TheCoolFarshad** [Rapptz/discord.py#4198]
Hi there, 

When attempting to run my bot I get this:  with open("prefixs.json", "w")
    ^
IndentationError: unexpected indent

I have checked the code 3 times:

here is the code:
@client.event
async def on_guild_join(guild):
        with open("prefixes.json", "r") as f:
             prefixes = json.load(f)

        prefixes[str(guild.id)] = "n."

        
         with open("prefixs.json", "w")
          json.dump(prefixes, f, indent=4)

@client.event
async def on_guild_remove(guild):
    with open("prefixes.json", "r") as f:
        prefixes =json.load(f) 

    prefixes.pop(str(guild.id))

    with open("prefixes.json", "w") as f:
        json.dump(prefixes, f, indent=4)

@client.command()
aysnc def changeprefix(ctx, prefix)
 with open("prefixes.json", "r") as f:
        prefixes =json.load(f) 

    prefixes[str(ctx.guild.id)] = prefix

    with open("prefixes.json", "w") as f:
        json.dump(prefixes, f, indent=4)

Thanks

discord py ver: 1.3.3

**Comment by helish88** [comment]
please larn basic python [https://www.w3schools.com/python/gloss_python_indentation.asp#:~:text=Python%20Indentation,indicate%20a%20block%20of%20code.](url)

**Comment by TheCoolFarshad** [comment]
well whats wrong with it

**Comment by TroyDota** [comment]
This, is not a discord issue.

**Comment by TroyDota** [comment]
Please learn about python before attempting to code a discord bot, there are youtube guides.

**Comment by TheCoolFarshad** [comment]
First off, I know this is not a discord issue 

Second off, I know how to use python!

It’s just one issue and you guys are clearly NOT looking into the code

**Comment by AbstractUmbra** [comment]
Sorry, this is not a valid issue for discord.py. This issue tracker is for problems with the Discord.py library, not with errors in using it, or basic Python errors such as this one.

The error you are seeing is an IndentationError. A quick Google would have gotten you the solution for this.

**Comment by TheCoolFarshad** [comment]
All right thanks but searching on google didnt help so I decided to remove the code entirely and just left it there.

**Comment by TroyDota** [comment]
The best way to move forward and learn coding is how to google.
Ill take the time to show you.
"What is the IndentationError in python"

> As mentioned in the "expected an indented block" section, Python not only insists on indentation, it insists on consistent indentation. You are free to choose the number of spaces of indentation to use, but you then need to stick with it.

As the first link.
From that you can come to the conclusion that its a missing tab or space in your code.
