### ISSUE TITLE
Offset to change channel name

### ISSUE THREAD

**Issue by Army-py** [Rapptz/discord.py#4201]
### Summary

When I want to change the name of a channel it can take several minutes to do so.

### Reproduction Steps

```python
online = 0
        idle = 0
        dnd = 0
        online_count = self.client.get_channel(691011893464268900)

        for member in after.guild.members:
            if str(member.status) == 'online':
                online += 1
            elif str(member.status) == 'idle':
                idle += 1
            elif str(member.status) == 'dnd':
                dnd += 1
        await online_count.edit(reason=None, name=f"【📡】En ligne : {online + idle + dnd}")
```
The problem comes from the `await online_count.edit(reason=None, name=f"【📡】En ligne : {online + idle + dnd}")` , I had put a 'print' just before and after this line and I could see that it was this first line that had a problem. But several minutes after the second print that was after the `await` worked.

### Expected Results

I was expecting the name of the channel to change quickly, but since I switched to discord.py 1.4, I have the impression that it has slowed down the editing of the channel

### Actual Results

The channel wasn't renamed until several minutes later.

### Checklist

- [ ] I have searched the open issues for duplicates.
- [ ] I have shown the entire traceback, if possible.
- [ ] I have removed my token from display, if visible.

### System Information

```
- Python v3.8.1-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v6.0
- system info: Windows 10 10.0.18362
```

**Comment by Rapptz** [comment]
You're being rate limited. Channel names and topics are rate limited to twice per 10 minutes.
