### ISSUE TITLE
Empty members list on voice channel.

### ISSUE THREAD

**Issue by ibigpapa** [Rapptz/discord.py#4202]
### Summary

When attempting to get members of a voice channel i'm always getting 0 members.

### Reproduction Steps

```
async def full_voice_count(self) -> int:
        guild: Guild = await self.bot.fetch_guild(GUILD_ID)
        channels = await guild.fetch_channels()
        voice_channels = [
            channel for channel in channels if channel.type == ChannelType.voice
        ]
        return sum([len(channel.members) for channel in voice_channels])
```

### Expected Results

Expect current users in voice channel to be return with `channel.members`.

### Actual Results

empty list of members is returned.

### Checklist

- [X ] I have searched the open issues for duplicates.
- [ X] I have shown the entire traceback, if possible.
- [ X] I have removed my token from display, if visible.

### System Information

- Python v3.8.0-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Linux 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020

**Comment by Rapptz** [comment]
https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.fetch_guild

![image](https://user-images.githubusercontent.com/1695103/84750778-b9c07680-af89-11ea-830a-a35b882271c2.png)
