### ISSUE TITLE
Switching Websockets library to support proxy scenarios

### ISSUE THREAD

**Issue by akmet** [Rapptz/discord.py#4204]
### The Problem

My server has restricted access to the internet due to security reasons and therefore I have to use a proxy. Sadly the used [Websockets](https://websockets.readthedocs.io/en/stable/limitations.html?highlight=proxy) library does not support connections through proxies.

### The Ideal Solution

In the ideal solution the proxy parameter given to the client would be used by the websockets instance to connect to the gateway through the proxy.

### The Current Solution

There currently seems to exist no solution

### Summary
In my opinion the scenario of having a server with no direct connection to the internet is realistic. Also the presence of the proxy parameter shows that there is some interest on proxied connections. Limiting these connections to http and not also offer wss or even https seems surreal.

If changing the websockets library is on a low priority roadmap I would like to ask for more information to help accelerating the process.

**Comment by Gobot1234** [comment]
See https://github.com/Rapptz/discord.py/tree/sharding-rework, this uses aiohttp for the websocket connection, which supports proxies https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientSession.ws_connect.

**Comment by Vexs** [comment]
Additionally, another possibility would be to configure a proxy outside of the program, on the machine itself, then (depending on OS this can be hard or easy) set the program to use the proxied interface. On linux this could be done with netns

**Comment by akmet** [comment]
Thanks, this looks interesting.
Do you know if there is anything still to do or can I help on another way to fasten the merge into the master branch?

**Comment by Vexs** [comment]
There is still a fair bit of work to go, but that branch is being used in production by a number of people (some very large!)- should be safe to use.

**Comment by Harmon758** [comment]
That branch has since been merged into the master branch, and this issue should now be resolved, with #2654 released in v1.4.0.
