### ISSUE TITLE
how to blacklist members no cog 

### ISSUE THREAD

**Issue by seanalts7** [Rapptz/discord.py#4208]
### The Problem

just please
### Summary
i would like to blacklist members

**Comment by seanalts7** [comment]
* NO COG *

**Comment by Gobot1234** [comment]
This is not an issue with discord.py.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.

## For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by seanalts7** [comment]
oof
