### ISSUE TITLE
Infer types for attributes in Context

### ISSUE THREAD

**Issue by vintprox** [Rapptz/discord.py#4209]
### The Problem

Every occurrence of `ctx` is pulling me back to API reference of `Context` class, because I may be missing memory of what was there, and it's kind of inconvenient. Even after explicitly annotating `ctx: Context`, the problem appears to be with a lack of type annotations for each its member.

### The Ideal Solution

It would be invaluable commitment to have all attributes of `Context` typed properly, so any A-OK IDE can produce autocompletion for everything `ctx.*`.

### The Current Solution

Of course, we can infer attributes set for `ctx` by adding `: commands.Context` (or even better: `ctx: Context`). Doesn't solve the problem with inferring their types though, so it becomes only natural to keep browser tab with API reference open for your next move.

### Summary

Make `Context` great again, I suppose 😆 I believe it's no problem for us to add `: Context`, to start expecting type inference of anything `ctx.*`.

**Comment by ShineyDev** [comment]
see #1497

**Comment by vintprox** [comment]
> see #1497

Thanks, I think search went bonkers on me today :) By the way, it doesn't seem like more granular issue isn't worth some spotlight. `Context` is used a lot while making bot commands.
