### ISSUE TITLE
The system_content from MessageType.new_member outputs incorrectly

### ISSUE THREAD

**Issue by Geroyuni** [Rapptz/discord.py#4211]
### Summary
`message.system_content` returns something different from what is visible in the Discord client for messages of the type `MessageType.new_member`, 

![](https://files.catbox.moe/0wy14o.png)

### Reproduction Steps
See the `message.system_content` of a `MessageType.new_member` message.

### Expected Results
Shows same message as you see in your Discord client.

### Actual Results
Shows different message from what you see in your Discord client.

### Checklist
- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information
```
- Python v3.8.0-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v6.0
- system info: Linux 4.15.0-1063-aws #67-Ubuntu SMP Mon Mar 2 07:24:29 UTC 2020
```

**Comment by Rapptz** [comment]
Maintaining this is basically on an "as-is" basis. Sometimes the strings change and it can't be helped. Just like it only provides English versions of the string. You can consider it an approximation. I'm not sure constantly chasing after an undocumented client-only feature is worth doing long term so maybe this needs documentation.
