### ISSUE TITLE
adding a category object to a channel object

### ISSUE THREAD

**Issue by yotam201410** [Rapptz/discord.py#4213]
### The Problem

channel object does not have a category but just a category_id

### The Ideal Solution

insted of the categoty_id put a category object

### The Current Solution

getting the category using get_channel

### Summary

it would have been nice if you would have added insted of the id just an category object in a channel object

**Comment by zomatree** [comment]
https://discordpy.readthedocs.io/en/latest/api.html#discord.abc.GuildChannel.category

**Comment by yotam201410** [comment]
i am getting a channel through cxt so i can only get the category

**Comment by zomatree** [comment]
github issues are not for asking for help, ask question in the [help server](https://discord.gg/dpy).
