### ISSUE TITLE
You can no longer pass None to discord.Object

### ISSUE THREAD

**Issue by Taarek** [Rapptz/discord.py#4219]
### Summary

Since the https://github.com/Rapptz/discord.py/commit/e473f3c775b26a4bb54b18eb6240757306f4f5c1 commit, you can no longer pass ``None`` in discord.Object

### Reproduction Steps

```py
>>> import discord
>>> object = discord.Object(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\TarekPC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\object.py", line 66, in __init__
    id = int(id)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

### Expected Results

Return a discord.Object when passing None

### Actual Results

TypeError is raised

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.8.1-final
- discord.py v1.4.0-alpha
    - discord.py pkg_resources: v1.4.0a2338+g1ee1b7f
- aiohttp v3.6.2
- websockets v6.0
- system info: Windows 10 10.0.19041

**Comment by Rapptz** [comment]
Should be noted that the interface isn't `None` friendly and I'm unsure whether this is a good long term idea however it might break things in the wild if this is broken.

**Comment by jack1142** [comment]
I only remember using `Member.move_to(discord.Object(None))` which was a workaround I needed until the method started accepting `None` in d.py 1.1. Is there actually some use case for `discord.Object` to support `None`?

**Comment by Metropass** [comment]
I would assume we would put `None` for stability of the script itself, but I'm wondering if there's any practical use. 

Would we just create an empty Discord object?
