### ISSUE TITLE
User activity

### ISSUE THREAD

**Issue by ObscureBrandon** [Rapptz/discord.py#4221]
My bot utilizes activities to grab song lyrics based on the user's current activity and send them in dms. Which brings up the issue of users not having the **activity** property. 

The ability to utilize any users' activity which will surely open up a lot of possibilities 
### Solution

No solutions that i am aware of.

### Summary
The ability to grab users' activities

**Comment by Gobot1234** [comment]
Discord doesn't give this info for users.

**Comment by ObscureBrandon** [comment]
Thought so too. Thanks for clearing it up.

**Comment by Harmon758** [comment]
Note, [`Member.activities`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Member.activities) exists, so for a specific user, you can simply use their Member object in any of the guilds that your bot shares with them.
