### ISSUE TITLE
No default notification level attribute for the server object

### ISSUE THREAD

**Issue by OrangeChaten** [Rapptz/discord.py#425]
The api provides the default notification level for a server, a setting in server settings, but discord.py does not expose this anywhere, it may not be useful, but might as well add it for the odd person who uses it

**Comment by AL1L** [comment]
Can this be added anytime soon?

**Comment by Harmon758** [comment]
This has now been resolved by https://github.com/Rapptz/discord.py/commit/1ac432d9f053812a1caab8330d14d4a9ba526289 (#1722) on the rewrite branch.
