### ISSUE TITLE
Commands ext overwrites `instance` when adding a cog

### ISSUE THREAD

**Issue by Fuyukai** [Rapptz/discord.py#426]
Opening because I don't know if this is fixed in rewrite.

When having multiple bots running in the same process, the `instance` property of the cog object created is always set to the last bot that claims the cog, due to the Command instance staying between object creation, as they're members of the type.

Take this example code:

```py
class Example(object):
     def __init__(self, bot, a: int):
        self.bot = bot
        self.a = a

    @commands.command()
    async def d():
        await self.bot.say(self.a)

bot1 = Bot(command_prefix="!")
bot1.add_cog(Example(bot1, 1))

bot2 = Bot(command_prefix="?")
bot2.add_cog(Example(bot2, 2))
```

When `?d` is called, it will correctly respond with `2`. However, when `!d` is called, it will respond with `2` due to the second `add_cog` call overwriting `instance` on the Command object representing the `d` command.

This can also cause problems with multi-threaded bots where separate instances of loops running in threads return the wrong loop when `.say()` or similar is called, due to the loop being from another thread.

A workaround is to use `ctx.bot`, but this causes problems when you need to access other self attributes specific to that cog.

**Comment by Rapptz** [comment]
This should be fixed I guess in the rewrite. Feels weird though.

**Comment by Rapptz** [comment]
Reopening this as a note that it is not actually fixed 😒

**Comment by Hornwitser** [comment]
I've toyed with a Descriptor based method of fixing this.  It works much the same as how class functions turn into bound methods, but I don't really like it  See Hornwitser@1e10508339d42b8feee9a9ce4dcba25af34ec401 for a possible implementation.

**Comment by orlnub123** [comment]
An easier fix would be to create a new command instance using copy.copy or something similar and set the instance attribute on it. I could make a PR if you'd like to see an implementation of it.

**Comment by Rapptz** [comment]
Should be fixed in https://github.com/Rapptz/discord.py/commit/caf3d17d4aa3ce45435bb96ea6d99317bfef8618
