### ISSUE TITLE
Stop using asyncio

### ISSUE THREAD

**Issue by tbodt** [Rapptz/discord.py#427]
asyncio prevents me from using discord.py in the REPL. And you can get all the benefits of asyncio from gevent, without even thinking about how everything might block.

**Comment by leovoel** [comment]
this ain't changing, there was a long period of discussion about it and most people seemed okay with the decision. (see #50 for part of it)

in any case, there's another python lib for discord that does use gevent: https://github.com/b1naryth1ef/disco

**Comment by fwrs** [comment]
A work-in-progress library that uses curio: https://github.com/SunDwarf/curious

**Comment by tbodt** [comment]
interesting. maybe could have googled first...

**Comment by SunDwarf** [comment]
You can use asyncio in a REPL using https://github.com/aio-libs/aiomonitor.

**Comment by Rapptz** [comment]
I'm not going to fundamentally change the library just so you (or somebody else) can use it in a REPL. Not to mention asyncio REPLs already exist (see above).
