### ISSUE TITLE
Embed.from_data doesn't parse the footer

### ISSUE THREAD

**Issue by XDki113r** [Rapptz/discord.py#429]
It parses everything else. I checked the code and there's nothing that would do it either. I'm guessing the footer was forgotten.

Should Embed.from_data be documented so it appears on read the docs? It would help people who need to parse Message.embeds find how to do it.

**Comment by Rapptz** [comment]
The function is mainly for the rewrite since it's a breaking change. I added it in there without realising this though. It's purposefully undocumented at the moment.
