### ISSUE TITLE
Emojis not being added to messages

### ISSUE THREAD

**Issue by judge2020** [Rapptz/discord.py#430]
Currently, I am trying to be able to add reactions to messages from certain users/channels, however, there is a problem with actually adding a reaction. The reaction never shows up on the actual message and no exception is thrown.

![image](http://i.imgur.com/mO7fFkE.png)

my code is at https://github.com/judge2020/ReactBot/blob/master/ReactBot/ReactBot.py

note: I have tried with and without `:` colins

**Comment by leovoel** [comment]
missing `await` before each call to `add_reaction`.
also you can't use the :shorthand: stuff, read the faq: http://discordpy.readthedocs.io/en/latest/faq.html#how-can-i-add-a-reaction-to-a-message

**Comment by judge2020** [comment]
Thanks for the quick reply, while reading the docs I didn't go into the FAQ so that's my mistake. This fixed it,
