### ISSUE TITLE
'ready' event does not wait for guild_sync to finish

### ISSUE THREAD

**Issue by Sir-Fancy** [Rapptz/discord.py#431]
The following script is _supposed to_ print all of the games currently being played by members of a server. For some reason, for a server of over 25,000 members, it only prints 12 of them. I talked to a few people in the discord-api server and they are stumped as well. I am on the latest async dev branch, and I tried on stable too.
The script:
```#!/usr/local/bin/python3.5
import discord
import asyncio
import requests
from discord.ext import commands

bot = commands.Bot(command_prefix='[',self_bot=True)
token = "<token>"

@bot.event
async def on_ready():
    print("----------")
    print("Logged in as:")
    print("    "+str(bot.user.name))
    print("    "+str(bot.user.id))
    print("----------")
    lf = bot.get_server("<server_id>")
    with open("mems.txt", "w") as m:
        print(len(lf.members))
        for mem in lf.members:
            if mem.game != None:
                print(mem.game.name)
                #m.write("{}\n".format(mem.game.name))
    print("\n\nDone.")
    
if __name__ == "__main__":
    bot.run(token, bot=False)```

**Comment by khazhyk** [comment]
sum(bool(m.game) for m in server.members) gives me ~2500 members on the discord api server which has ~14k members, which sounds about right. Does this script work for that server? Are there any errors printed out, or is there any other unexpected behavior happening (e.g., does the final done statement print?)

**Comment by khazhyk** [comment]
I think this may be related to guild_sync and ready not waiting for it on user bots.

Try using an actual bot account and see if that works.

**Comment by Sir-Fancy** [comment]
That worked! I made a bot account and it seemed to give a more believable answer. Any reason why this only happened to me?

**Comment by Rapptz** [comment]
Waiting for GUILD_SYNC is a bit of a drag (the only thing that is affected is presences but ideally chunking should fix it?). So I'm not sure what's actually going on.

**Comment by khazhyk** [comment]
IIRC, and evidently, presences are not included with chunks

**Comment by Rapptz** [comment]
Quick glimpse:

```py
{
   {
      'roles':[],
      'user':{
         'avatar':None,
         'discriminator':'8297',
         'username':'Natdog98',
         'id':'188767382641180672'
      },
      'joined_at':'2016-06-04T21:35:25.892000+00:00',
      'deaf':False,
      'mute':False
   },
   's':31,
   't':'GUILD_MEMBERS_CHUNK'
}
```

**Comment by khazhyk** [comment]
Could the chunk listener logic be reused just for guild syncs as well?
