### ISSUE TITLE
selfbots unable to fetch certain users

### ISSUE THREAD

**Issue by Jan200101** [Rapptz/discord.py#432]

**Comment by SunDwarf** [comment]
#431

**Comment by khazhyk** [comment]
Could you be more descriptive?

**Comment by Jan200101** [comment]
seems to be the same issue as #431 but Im gonna explain.

On alot of servers users like owner or sometimes just members that have nothing in special just return a NoneType which will result in errors when trying to get the name of a expected member.

Here is a example

selfbot
![image](https://cloud.githubusercontent.com/assets/15076013/21588538/fce25ef8-d0e7-11e6-8785-038a80f13b22.png)

normal bot
![image](https://cloud.githubusercontent.com/assets/15076013/21588543/04ac0968-d0e8-11e6-8b05-1b5b089d4f1c.png)

**Comment by Rapptz** [comment]
This should have already been fixed in the async branch.

**Comment by Jan200101** [comment]
Im going to install the from the async branch then

**Comment by Jan200101** [comment]
yep fixed on the async branch
