### ISSUE TITLE
when_mentioned_or should be able to take a list and output an unpacked list

### ISSUE THREAD

**Issue by mylbp2ps3** [Rapptz/discord.py#439]
This line is pretty common:
`bot = Bot(command_prefix="!"`
You can also insert a list into the command_prefix.

But what's also very common is:
`bot = Bot(command_prefix=when_mentioned_or("!")`
but when you give it a list now, it'll bug out. It'll give a list similar to this:
`[["!joe", "!JOE"], @mention]`
Which can't be passed into command_prefix.

A simple fix for this is to add a star:
`bot = Bot(command_prefix=when_mentioned_or(*["!joe", "!JOE"])`
Though this is intuitive. when_mentioned_or should do this by default.

**Comment by Rapptz** [comment]
Please learn python. Just omit the brackets and the star. If you have an actual list then yes, use the expansion operator. I'm not fixing this.
