### ISSUE TITLE
[Question] original text/name from mentioned channel?

### ISSUE THREAD

**Issue by DarkOrbiTzX** [Rapptz/discord.py#441]
Is able to get it?
if yes, how to get it?
if no, well, waiting for next release~ :o

**Comment by Phxntxm** [comment]
channel.mentions
channel.name
These are the things you are looking for
http://discordpy.readthedocs.io/en/latest/api.html#channel

**Comment by DarkOrbiTzX** [comment]
ie: "well, please looks at #welcome "

**Comment by Phxntxm** [comment]
Yes

**Comment by DarkOrbiTzX** [comment]
Oke~
Thanks~
