### ISSUE TITLE
[Question] How to insert image from url/link?

### ISSUE THREAD

**Issue by DarkOrbiTzX** [Rapptz/discord.py#445]
Well, how?

I see on: http://discordpy.readthedocs.io/en/latest/api.html#discord.Embed.set_image
How to use it ?

Thanks

**Comment by Rapptz** [comment]
The same way you use any function..?

`e.set_image(url='some link here')`

**Comment by Phxntxm** [comment]
You literally linked it. I don't understand the question. Just provide the URL

**Comment by DarkOrbiTzX** [comment]
Ok, thanks.
