### ISSUE TITLE
Background task example doesn't work on Windows - Object has no attribute 'create_task'

### ISSUE THREAD

**Issue by BradBrock1** [Rapptz/discord.py#446]
![image](https://cloud.githubusercontent.com/assets/11216446/21721021/22bf553e-d41e-11e6-8d01-e33ff91c6f6c.png)

Using Python3.4, DiscordPy 0.16.0 on Windows 7 Sp1 causes the above error.

Exactly the same but using Linux Mint 17.3 doesn't cause an issue, and the program runs perfectly.

**Comment by Rapptz** [comment]
You need 3.4.2 or higher.
