### ISSUE TITLE
Add a .is_typing(member) method

### ISSUE THREAD

**Issue by aqua-rar** [Rapptz/discord.py#455]
The on_typing event isn't very helpful because it simply tells you that the user has started typing. There is no way to check if they finished typing other than receiving a message. It would be nice to know if they stopped typing without sending a message.

**Comment by SunDwarf** [comment]
This would add a stupid amount of overhead to tracking typing status for all members for very little benefit.

**Comment by aqua-rar** [comment]
Is there any other way to figure out if a user has finished typing other than receiving a message?

**Comment by SunDwarf** [comment]
No.

Track it yourself.

**Comment by Rapptz** [comment]
This is not worth it. It's too much overhead to track this.

You can track this yourself. Just keep a list of people typing in a dictionary mapping of `channel_id` to `set[user_id]`. Then remove them from the set after 10 seconds have passed or they sent a message.

Hopefully explaining this showcases how much overhead it would be to add this to the library for little benefit.
