### ISSUE TITLE
Not really an issue, but is there a configuration to limit the number of commands the bot can handle per minute?

### ISSUE THREAD

**Issue by theindependentwolf** [Rapptz/discord.py#457]

**Comment by SunDwarf** [comment]
This would be better asked in the [Discord API](https://discord.gg/discord-api) guild.

However, you can use cooldowns to limit individual commands, but there's no paticular built in way to limit the number of commands in total. You can override `process_commands ` and write your own code for it however.

**Comment by theindependentwolf** [comment]
Thanks SunDwarf, I shall ask there! I was about to write my own and I figured it wouldn't hurt to ask and stop myself from doing work that's already been done.
