### ISSUE TITLE
Docs do not say that discord.Client.create_server can only be used by GameBridge apps

### ISSUE THREAD

**Issue by poolala** [Rapptz/discord.py#458]

**Comment by NotSoSuper** [comment]
Why would a user account not be able to?

**Comment by poolala** [comment]
https://discordapp.com/developers/docs/resources/guild#create-guild
It appears that this is the endpoint create_server uses

**Comment by NotSoSuper** [comment]
You're right, just tried to create one from a user account and checked the endpoint, guess they changed it ;-;

**Comment by khazhyk** [comment]
From my user account /guilds/ is the endpoint that is used, which seems correct? Are you sure creating servers does not work from user accounts?

Creating servers previously did not work at all on bot accounts, that gamebridge accounts are allowed to is new but not more restrictive.

**Comment by poolala** [comment]
Yes - I tried it from a user account and a bot account, both of which returned HTTP 400.

**Comment by khazhyk** [comment]
The issue is the create_server logic is incorrect. It should be using value, not name here.

`discord.ServerRegion.us_west.name
us_west
