### ISSUE TITLE
Adding a asyncio-powered timeout for Client.connect

### ISSUE THREAD

**Issue by 39bit** [Rapptz/discord.py#459]
I suggest adding a (configurable?) timeout for the connect function under Client (for example, the timeout could be configured with an attribute).

I'm currently using a modification that goes something like this (a dirty hack, notice the 2.0 second timeout)
```
        while not self.is_closed:
            try:
                yield from asyncio.wait_for(self.ws.poll_event(), timeout=2.0, loop=self.loop)
            except concurrent.futures._base.TimeoutError as e:
                pass
            except (ReconnectWebSocket, ResumeWebSocket) as e:
                resume = type(e) is ResumeWebSocket
                log.info('Got ' + type(e).__name__)
                self.ws = yield from DiscordWebSocket.from_client(self, resume=resume)
            except ConnectionClosed as e:
                yield from self.close()
                if e.code != 1000:
                    raise
```

Adding a timeout here would allow an use case where an external source can add a coroutine call (such as send_message) into the Client loop by using asyncio.ensure_future to allow sending messages independently without a significant delay (around 30-40 seconds before the hack).

**Comment by SunDwarf** [comment]
What is the use case of this?

You can just use a background task instead.

```py
async def something(client):
    while True:
        await client.send_message(some_channel, "*beat*")
        await asyncio.sleep(2)

bot = Client(...)
bot.loop.create_task(something(bot))
bot.run('token')
```

**Comment by 39bit** [comment]
That seems correct. I remember trying something like that, but the task wouldn't actually run if done that way.

**Comment by ButterCheezii** [comment]
The reason it didn't work is because you didn't run it in Client.on_ready. It tried to send the message before the client logged in, throwing an exception and stopping the task.

**Comment by OrangeChaten** [comment]
You would want to use a background task, and `await client.wait_until_ready`, or run it in `on_ready`, either way, the message cannot be sent before the client is logged in and ready.
