### ISSUE TITLE
Issue in client.py when I run a compiled exe version of my bot.

### ISSUE THREAD

**Issue by AraHaan** [Rapptz/discord.py#46]
https://i.gyazo.com/cf85583cc07a981a88025839616e949c.png

This is what I see from it.

**Comment by Hornwitser** [comment]
We are not psychic, you have provided far too few details of your problem for anyone to be able to help you with your issue.  Please see http://www.catb.org/esr/faqs/smart-questions.html for some general guidelines on asking better questions and specifically the section [Be precise and informative about your problem](http://www.catb.org/esr/faqs/smart-questions.html#beprecise).
