### ISSUE TITLE
Fetching other servers as a selfbot

### ISSUE THREAD

**Issue by Jan200101** [Rapptz/discord.py#461]
Fetching other servers results in the selfbot freezing up.
I have tested it multiple times with a selfbot and normal bot and the normal bot seems to react like it should where the selfbot reacts as mentioned above

**Comment by SunDwarf** [comment]
What do you mean by `fetching other servers`?

**Comment by Jan200101** [comment]
getting info of a server you are currently not using, but are a member on

**Comment by SunDwarf** [comment]
Can you show the code you're using?

**Comment by Jan200101** [comment]
Okay I found the error.
It was a bit of a misuse of discordpy and while where it resulted in a endless loop of it getting another server
