### ISSUE TITLE
Loop / Timeout error - Task was destroyed but it is pending!

### ISSUE THREAD

**Issue by webbersky** [Rapptz/discord.py#463]
`#!/usr/bin/python
import discord
import asyncio
import time

PYTHONASYNCIODEBUG = 1

client = discord.Client()

def Test():
    TestSomething = "example"
    TimeToWait = 30 #Task killed on 30s, but works on 20s
    print("Waiting for function to complete - "+str(TimeToWait)+"s...")
    time.sleep(TimeToWait)
    return TestSomething

@client.event
async def on_ready():

    print('Logged in as')
    print(client.user.name)
    print(client.user.id)
    print('------')
    
    for x in range(0, 100000):
        TestString = Test()
        print(TestString)
        TimeToWait = 1
        print ("Looping in "+str(TimeToWait)+"s...")
        await asyncio.sleep(TimeToWait)
        print (time.ctime())

Token = "tokenhere"
client.run(Token)`

This code will run on if the TimeToWait set in Test() is set to 20s, but crashes on 30s
Task was destroyed but it is pending!
task: <Task pending coro=<Client._run_event() done, defined at /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/client.py:304> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x10565a678>()]>>

Thanks

**Comment by bippum** [comment]
You should probably remove the token you posted and go regenerate it.

**Comment by Helehelehele** [comment]
`time.sleep` suspends the whole thread, which means it blocks. Use [`asyncio.sleep`](https://docs.python.org/3.5/library/asyncio-task.html#asyncio.sleep) instead.  Note that this is also a coroutine which means you will have to `await`. And you should know, considering you use it already.

**Comment by webbersky** [comment]
Forgot to remove it, thanks and how can I await to wait for a function to return a variable?
As the function I run takes about 50s and it keeps killing the task

**Comment by Helehelehele** [comment]
```python
async def test():
    test_something = "example"
    time_to_wait= 30 
    print("Waiting for function to complete - {}s...".format(time_to_wait))
    await asyncio.sleep(time_to_wait)
    return test_something 
```

Then under your `on_ready` you can do
```python
    ...
    test_something = await test()
```

I would also recommend learning more about async/asyncio if you want to use this library, before trying to dive in. This was just a "simple example" regarding your issue, but there's much more to it.
