### ISSUE TITLE
when trying to run the basic examples: AttributeError: module 'discord' has no attribute 'Client'

### ISSUE THREAD

**Issue by neatville** [Rapptz/discord.py#465]
Related question: where are our credentials stored, and how do we retrieve them.  
Python 3, 32 bit windows.

**Comment by SunDwarf** [comment]
Is your script named `discord`?

**Comment by Phxntxm** [comment]
Your "credentials" will either be the token you get when you make the bot account here: https://discordapp.com/developers/applications/me

Or if you want it connected to your account, get the token this way:
1. Open Discord
2. Press Ctrl+Shift+i
3. Click "Application" tab
4. Expand Storage > Local Storage > https://discordapp.com
5. Find "token" under "key"
6. Copy the text in quotes on the same row

**Comment by neatville** [comment]
Good point, I changed the name of the file and it's just an 'unauthorized' error now. 
```
In this function, for the example on the front page:  
@client.event
async def on_ready():
    print('Logged in as')
    print(client.user.name)
    print(client.user.id)
    print('------')
```
Could I somehow replace the client.user.name and id with the tokens that will be given to me.

**Comment by OrangeChaten** [comment]
You want to login to someone elses account? you cant do that

**Comment by Phxntxm** [comment]
https://github.com/Rapptz/discord.py/tree/async/examples
Check the examples, in order to "login" you need the token I described in my last response. You need to "start" the connection for the bot, by using `client.run('token')` and replacing that with your token.

**Comment by neatville** [comment]
No that's not what I'm saying at all. The tokens that the website gives me. thanks everyone.
