### ISSUE TITLE
Add an option to make commands case insensitive

### ISSUE THREAD

**Issue by jkerkhoff** [Rapptz/discord.py#466]
All my commands are lower case right now, but some people on the guilds it's on are used to commands starting with an upper case character, so it would be useful if I could make my bot ignore case (for the command names, not the arguments), preferably globally. I think this should be quite simple to implement, but doing it with an override in my own bot would mean duplicating ~50 lines of code.

**Comment by Rapptz** [comment]
I'm not implementing this (or ever plan to). Case insensitivity only makes sense in English, which is a common language admittedly but the library does not assume to be English only in its interfaces. 

Outside of that, I don't like the idea of case insensitive commands since it's just a way to give users a lazy way out.

**Comment by jkerkhoff** [comment]
> I'm not implementing this (or ever plan to). Case insensitivity only makes sense in English, which is a common language admittedly but the library does not assume to be English only in its interfaces.

Would this be a problem if it was an option, like the command prefix?

> Outside of that, I don't like the idea of case insensitive commands since it's just a way to give users a lazy way out.

Haha, ok. Makes sense.

**Comment by Soliel** [comment]
You could, instead of using the command handler in d.py, write your own to call from on_message and make it case insensitive there. So it's not impossible.

**Comment by jkerkhoff** [comment]
@Soliel Yes, that's exactly what I'm planning on doing. It's not a big issue, I just thought it would be worth seeing if it could be implemented here to avoid some code duplication and possible future compatibility issues. Thanks for the suggestion though!

Since @Rapptz has stated they have no intentions of implementing this, I suppose I should close this issue. If not, feel free to re-open.

**Comment by Rapptz** [comment]
I won't add this natively. However in the rewrite supporting this is simple from the user end:

```python
async def on_message(self, message):
  ctx = await self.get_context(message)
  ctx.comand = self.commands.get(ctx.invoked_with.lower())
  await self.invoke(ctx)
```

I just don't care enough to add since it's 1) wrong to do so, 2) performance penalty when 99% don't need it.

**Comment by jkerkhoff** [comment]
Ok, thanks!

**Comment by Willbycraft** [comment]
how do we implement this code?

**Comment by ReynardoE15** [comment]
how bad of a performance loss if you use case-insensitive feature or code
