### ISSUE TITLE
BeautifulSoup warning - Add parser 

### ISSUE THREAD

**Issue by thatguywiththatname** [Rapptz/discord.py#467]
Python3 warning:

UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 202 of the file bot.py. To get rid of this warning, change code that looks like this:
 BeautifulSoup([your markup])

to this:
BeautifulSoup([your markup], "html.parser")

markup_type=markup_type))

---

Line 202 refers to  `client.run(discord_token)`

**Comment by Avaren** [comment]
The warning is misleading, the issue is with your own code/code used by a library wrapping discord.py. Look for BeautifulSoup or bs4 in your code and change it there.

**Comment by thatguywiththatname** [comment]
Oh ok. Thanks for the reply anyways
