### ISSUE TITLE
discord.Client() close coroutine: Unclosed client session

### ISSUE THREAD

**Issue by mc0de** [Rapptz/discord.py#469]
this relates to closed issue https://github.com/Rapptz/discord.py/issues/142
double space line client.py:478

still getting Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0409B870>

**Comment by Rapptz** [comment]
Not an issue with the library.

You're probably not running the bot via client.run` or not calling `client.close` explicitly. The linked issue is irrelevant.

**Comment by mc0de** [comment]
my bad, actually there was 2 client.run calls, how could i exit from one loop on_ready() and get into another loop with separate on_ready()? how do i use discord.Client(loop=??)
