### ISSUE TITLE
Function to obtain a Voice Channel ID when you only know the Name of the Voice Channel.

### ISSUE THREAD

**Issue by AraHaan** [Rapptz/discord.py#47]
So like the title says I am not sure if there is a function that I could import a Voice Channel name and it outputs the ID for me.

This is for Joining a voice channel when someone uses a command and they specify a Voice Channel name for the bot to Join.

If a Voice Channel of a name specified does not exist it must show a error.

**Comment by Rapptz** [comment]
```
channel = discord.utils.find(lambda c: c.name == 'some name' and c.type == 'voice', some_list_of_channels)`
if channel is not None:
    print(channel.id)
```

**Comment by asdasdasd69** [comment]
This helps:
```
channel = discord.utils.get(message.server.channels, name='General', type=discord.ChannelType.voice)
await client.join_voice_channel(channel)
```
