### ISSUE TITLE
Should async iterable utilities be added to the AsyncIterable concept?

### ISSUE THREAD

**Issue by Rapptz** [Rapptz/discord.py#473]
So you can do something like `await channel.history().find(lambda m: len(m.mentions) > 5)` or whatever.

Maybe more things could be added for the <3.6 peeps.

Some suggestions I'm unsure about:

- `find` (see: `discord.utils.find`)
- `get` (see: `discord.utils.get`)
- `map` 
- `filter`

I'm willing to add this but I don't know if it's a desired feature as more things will return async iterables in the rewrite. You can voice your concerns and thoughts here I guess.

For the curious, these return AsyncIterables:

- `Messageable.history` (i.e. `logs_from`)
- `Reaction.users`

Maybe more in the future. Not sure. Probably not.

**Comment by Helehelehele** [comment]
Being able to use awaitables in suggested utilities (such as  `channel.history().map(store_to_db)` where `store_to_db(message)` is a coroutine) can be nice.

**Comment by Rapptz** [comment]
This was implemented.

`map`/`filter` return async iterators to allow composition. Use `flatten` on the result to make it a list/eager.
