### ISSUE TITLE
[rewrite (and probably stable)] asyncio lock fails in http.py

### ISSUE THREAD

**Issue by diceroll123** [Rapptz/discord.py#475]
In my bot.log:

```
Exception in callback <bound method Lock.release of <asyncio.locks.Lock object at 0x7f7bb7708940 [unlocked]>>
handle: <TimerHandle cancelled None>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 186, in uvloop.loop.TimerHandle._run (uvloop/loop.c:50596)
  File "/usr/lib/python3.5/asyncio/locks.py", line 201, in release
    raise RuntimeError('Lock is not acquired.')
RuntimeError: Lock is not acquired.
```

I edited the MaybeUnlock class in http.py to show the lock repr's so I could match an ID to the error above, and so I did.

```python
    def __exit__(self, type, value, traceback):
        print('MAYBEUNLOCK lock is', self.lock)
        try:
            if self._unlock:
                self.lock.release()
        except Exception as e:
            print(e)
```

lo and behold, my console said: `MAYBEUNLOCK lock is <asyncio.locks.Lock object at 0x7f7bb7708940 [locked]>`, and as you can see the IDs do match. This goes for other lock IDs also used and printed, as it required slight spam to trigger the error.

Cog function to reproduce: *i'm not 100% sure if the message edit is necessary to the error occurring but it happens in my code so here it stays.* Ignore how nonsensical the code itself is, I've replaced meaningful content with placeholders.

**YOU NEED TO SPAM IT A FEW TIMES.**

```python
  @commands.command(hidden=True)
  async def test(self, ctx):
    emojis = ['\U0001f47d', '\U0001f914','\U0001f604','\U0001f636','\U0001f922'] # some reactions
    msg = await ctx.send(embed=discord.Embed(description='test message', color=random.randint(0, 0xFFFFFF)))
    await asyncio.sleep(2)
    await msg.edit(embed=discord.Embed(description='test message complete!', color=random.randint(0, 0xFFFFFF)))
    for emoji in emojis:
      await msg.add_reaction(emoji)
      await asyncio.sleep(0.5)

    while True:
      check = lambda r, u: r.message.id == msg.id
      try:
        react = await ctx.bot.wait_for('reaction_add', check=check, timeout=10.0)
      except:
        react = None
        pass

      if react is None:
        break

      # in my code i do things based on reactions but this isn't necessary here

    await msg.clear_reactions()
```

---

So far I don't know what this error does in terms of breaking things, but seeing as it's a broken async lock, this could be why crashing has occurred for me in times of heavy usage of the command in question that causes this issue

**Comment by Rapptz** [comment]
https://github.com/Rapptz/discord.py/commit/f5b455c119d40d8c58b7781b22b8c225fc9d1786
https://github.com/Rapptz/discord.py/commit/3558a0db27324d801a983a53bf65dc3f48e23fa2
