### ISSUE TITLE
Voice client disconnecting from other server

### ISSUE THREAD

**Issue by JacobCloud** [Rapptz/discord.py#477]
Hello,

Recently I have noticed that when my bot is being disconnected from the voice channel on other server i'm in while the voice is connected on another server i'm listening to, the audio cut, and I have to reconnect to hear the audio again. I have noticed it only happens to me, as others are able to hear, so it might be due to me having a mutual server with both of those server. Is there a way to fix this issue?

**Comment by Rapptz** [comment]
This is a discord bug.

**Comment by JacobCloud** [comment]
well damn. I hope it will be a fix soon, because it get's a bit annoying, as my bot does a join sound when someone joins a voice channel :/

**Comment by ZweiSpeedruns** [comment]
Would it be feasable to have the is_connected function actually do a ping to double-check that it is connected instead of simply checking if _connected is set? That would at least make it easy to set up a temporary watchdog system while this is being worked on.

**Comment by ZweiSpeedruns** [comment]
oops, nevermind, was thinking of a different issue

**Comment by Articuno1234** [comment]
are you using a userbot or something?

because they can only be in one voice channel at a time

**Comment by Harmon758** [comment]
This should now be fixed.
See https://trello.com/c/fVzj57Pa/181-bot-disconnecting-from-an-audio-server-in-mutual-guild-stops-playback-in-current-voicechannel and https://trello.com/c/ed5QQ5BP/1585-you-stop-hearing-bot-accounts-if-you-see-them-leaving-voice-channels-in-a-different-server.
I can't reproduce this anymore, aside from the green circular outline indicator not showing anymore after leaving the other server, but that just seems to be a visual bug as the audio still continues.
