### ISSUE TITLE
Allow all retrieval of channel history?

### ISSUE THREAD

**Issue by Rapptz** [Rapptz/discord.py#480]
This could be done via `channel.history(limit=None)`.

I'm not sure if it's a good idea (I'm personally leaning towards 'yes'). One slight issue I have is if someone ended up flattening it (see #473) and receiving a huge list in return. This is probably not *too much* of an issue but I feel it's one I must think about nonetheless.

Opening this issue to see other people's thoughts on the matter.

**Comment by Funky7Monkey** [comment]
This can cause bots to reach rate limits, causing an incomplete message history to be returned.

**Comment by Rapptz** [comment]
The library handles rate limits already.
