### ISSUE TITLE
"Commands:" list appears but is empty when a user can't use any of a group's commands

### ISSUE THREAD

**Issue by mikevb1** [Rapptz/discord.py#483]
If I create a privileged subcommand, and call `help` on the group, the "Commands:" text (with no subcommands listed) will appear even if I don't have the permissions to use any subcommands.

**Comment by Rapptz** [comment]
Fixed in https://github.com/Rapptz/discord.py/commit/b6bff5172a99046c8d2a1aa017be0e4110c7fd24 in rewrite.
