### ISSUE TITLE
Member status change event

### ISSUE THREAD

**Issue by drequivalent** [Rapptz/discord.py#484]
Is there an event handler for a situation when a member changes status?
I've found on_member_join and on_member_remove, but that's not quite what I want.
I need events when a member goes online or offline.
Is there such a thing?

**Comment by leovoel** [comment]
http://discordpy.readthedocs.io/en/latest/api.html#discord.on_member_update
http://discordpy.readthedocs.io/en/latest/api.html#discord.Member.status
