### ISSUE TITLE
`bot.get_channel` doesn't return DMChannels

### ISSUE THREAD

**Issue by ivandardi** [Rapptz/discord.py#490]
## Issue
Due to the endpoint change, you can't get DMs directly now. That makes the `bot.get_channel` function not work as intended, because as of now it's still trying to get the DM channels via the endpoint.

## Possible solutions

1. Make it so that it only returns TextChannels, and add a new `bot.get_dm_channel` to get DM channels
2. Make it so that it only returns TextChannels, and don't add a new `bot.get_dm_channel` to get DM channels
3. Make it so that it returns both TextChannels and DMChannels again

## Current workaround

```py
async def _get_channel(self, channel_id: int):

    channel = self.bot.get_channel(channel_id)
    if channel:
        return channel

    # No channel found, then we need to get the user, since channel_id is the ID of a user
    user = await self.bot.get_user_info(channel_id)

    # If the bot already has a dm_channel open with the user, then there's no need to create a new one
    if user.dm_channel:
        return user

    # Creating a new DM channel
    return await self.bot.create_dm(user)
```

**Comment by Rapptz** [comment]
This is not a real issue.

`get_channel` returns a channel from a given *channel ID*. You are passing it a *user ID*. Your "workaround" is working with both types of ID. The documented function *does not do that*. 

Private channels have their own IDs, and this ID is **not** the user ID.
