### ISSUE TITLE
create role from bot

### ISSUE THREAD

**Issue by PythonPi** [Rapptz/discord.py#491]
The route for `create_role` in http.py is incorrect. It has an extra `/` at the end that causes a 404 response.

Figured an issue ticket was preferable to a pull request.

**Comment by Rapptz** [comment]
[No?](https://github.com/Rapptz/discord.py/blob/async/discord/http.py#L589-L591)

Update your lib.

**Comment by PythonPi** [comment]
Well i feel like an idiot.
