### ISSUE TITLE
DMChannel.purge cannot be used by bots

### ISSUE THREAD

**Issue by mikevb1** [Rapptz/discord.py#496]
Adding a kwarg to trigger single delete might be a good solution.

**Comment by Rapptz** [comment]
This isn't true? See https://github.com/Rapptz/discord.py/commit/0e8b260d45369e4b606d3df45d166854f0431950

**Comment by Rapptz** [comment]
Since they can't be used reliably, I removed them from Messageable and `delete_messages` and `purge` are only in `TextChannel`. See [here](https://github.com/Rapptz/discord.py/commit/cbbc75cd8ddcdc15c8ac0565ce69ba0f4200a368) for more info.
