### ISSUE TITLE
How to go about using this library in the context of another thread?

### ISSUE THREAD

**Issue by Panoplos** [Rapptz/discord.py#497]
I have attempted to use discord.py in a `Thread` context, but get errors about the event loop not existing.

Here is the sample code:
```python
import discord
from threading import Thread, Event

class DiscordStream(Thread):
  
  def __init__(self):
    Thread.__init__(self)
    self.client = discord.Client()
    self.event  = Event()

  def run(self):
    @self.client.event
    async def on_ready():
      print('Logged in as')
      print(self.client.user.name)
      print(self.client.user.id)
      print('------')

    @self.client.event
    async def on_message(message):
      if message.content.startswith('>'):
        author = message.author
        print("User [{}] with ID [{}] sent message [{}].".format(author.id, author.name + '#' + author.discriminator, message.content))
        await self.client.send_message(message.channel, "I hear ya'...")

    self.client.run('MY-TOKEN')
    while not self.event.wait(10):
      continue
    else:
      self.client.loop.run_until_complete(client.logout())

  def start(self):
    Thread.start(self)

  def stop(self):
    self.event.set()

ds = DiscordStream()

ds.start()

msg = """
Testing Discord
Press Return to Exit...
"""
input(msg)

ds.stop()
```

Which results in:

```python
Testing Discord
Press Return to Exit...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "test_discord.py", line 26, in run
    self.client.run('MY-TOKEN')
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 519, in run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 491, in start
    yield from self.connect()
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 448, in connect
    yield from self.ws.poll_event()
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 408, in poll_event
    yield from self.received_message(msg)
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 367, in received_message
    func(data)
  File "/usr/local/lib/python3.5/dist-packages/discord/state.py", line 209, in parse_ready
    self._ready_state = ReadyState(launch=asyncio.Event(), servers=[])
  File "/usr/lib/python3.5/asyncio/locks.py", line 219, in __init__
    self._loop = events.get_event_loop()
  File "/usr/lib/python3.5/asyncio/events.py", line 632, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "/usr/lib/python3.5/asyncio/events.py", line 578, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-1'.
```

One of the problems that is related to this indirectly is that I noticed `client.run(...)` is a blocking method. Given this and the issue above, how would one go about running the discord event loop with callbacks in a thread context like I am attempting above?

The reason this is necessary, BTW, is because I am having to port a currently working bot for other platforms to discord (it connects to all platforms simultaneously, each in their own thread context and uses an abstracted interface for this.) I have tried to keep the interface, but remove the `Thread` inheritance, which works for the events, but because this call to `client.run(...)` is blocking it is problematic.

Thanks for your support.

**Comment by GetRektByMe** [comment]
As far as I'm aware asyncio isn't threadsafe, so it's just not going to work as far as running each in their own thread.

What you could do is have them all running on the same event loop though, this should be possible if you schedule all the events manually, bypassing client.run. client.run `https://github.com/Rapptz/discord.py/blob/async/discord/client.py#L493` is just a wrapper around a few asynchronous methods which creates an event loop.

**Comment by khazhyk** [comment]
You need to initialize the event loop on your second thread.
`asyncio.set_event_loop(asyncio.new_event_loop())` when starting your thread. Be aware that you will have one event loop per thread, and running things on an event loop from a different thread requires you use `asyncio.run_coroutine_threadsafe(loop, coro)`

**Comment by Panoplos** [comment]
Thanks for the responses.

@GetRektByMe Currently, the other libraries are not utilising `asyncio`, so it really doesn't matter if this is the only event loop. That being said, how can I use discord.py without having to change the whole architecture to support asyncio? For instance, is there a away just to call `client.login('token')` and `client.connect(...)` in a non-blocking manner to kick off the event loop inside the thread dedicated to discord.py?

**Comment by Panoplos** [comment]
OK, nevermind. Using @khazhyk's suggestion worked.

**Comment by Panoplos** [comment]
Ok, I tried using @khazhyk's approach with the following:

```python
import discord
import asyncio
from threading import Thread, Event

class DiscordStream(Thread):
  
  def __init__(self):
    Thread.__init__(self)
    self.client = discord.Client()
    self.loop = asyncio.new_event_loop()
    
  def run(self):
    @self.client.event
    async def on_ready():
      print('Logged in as')
      print(self.client.user.name)
      print(self.client.user.id)
      print('------')

    @self.client.event
    async def on_message(message):
      if message.content.startswith('$>'):
        author = message.author
        print("User [{}] with ID [{}] sent message [{}].".format(author.id, author.name + '#' + author.discriminator, message.content))
        await self.client.send_message(message.channel, "Now you're talkin'...")

    asyncio.set_event_loop(self.loop)
    self.client.run('MY-TOKEN')
    
  def start(self):
    Thread.start(self)

  def stop(self):
    self.loop.run_until_complete(self.client.logout())
    self.loop.stop()
    
ds = DiscordStream()

ds.start()

msg = """
Testing Discord
Press Return to Exit...
"""
input(msg)

ds.stop()
```

However, the problem comes when I attempt to stop the loop from the parent thread, as it complains as follows:

```Traceback (most recent call last):
  File "test_discord.py", line 48, in <module>
    ds.stop()
  File "test_discord.py", line 35, in stop
    self.loop.run_until_complete(self.client.logout())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 426, in logout
    yield from self.close()
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 477, in close
    yield from self.ws.close()
  File "/usr/local/lib/python3.5/dist-packages/websockets/protocol.py", line 241, in close
    self.worker_task, self.timeout, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 385, in wait_for
    yield from waiter
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
RuntimeError: Task <Task pending coro=<Client.logout() running at /usr/local/lib/python3.5/dist-packages/discord/client.py:426> cb=[_run_until_complete_cb() at /usr/lib/python3.5/asyncio/base_events.py:164]> got Future <Future pending> attached to a different loop
```

Which is perfectly logical, but doesn't help as I need `client.run(...)` to be non-blocking, or even be able to call `client.start(...)` from my thread...which is not possible without propagating the `async def` up to the `Thread.run` method.

**Comment by Emzi0767** [comment]
You cannot stop the loop from another thread

**Comment by SunDwarf** [comment]
Yes you can.

```py
loop.call_soon_threadsafe(loop.stop)
```

From within your other thread.

**Comment by Panoplos** [comment]
Then how can I stop it in the `DiscordStream` thread, as it blocks on `client.run(...)`? Or, how can I use `DiscordStream.run(...)` to kick off discord client without blocking?

**Comment by Panoplos** [comment]
@SunDwarf I get the following error when attempting to call with that:

```python
Traceback (most recent call last):
  File "test_discord.py", line 47, in <module>
    ds.stop()
  File "test_discord.py", line 34, in stop
    self.loop.call_soon_threadsafe(self.client.logout())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 532, in call_soon_threadsafe
    handle = self._call_soon(callback, args)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 505, in _call_soon
    raise TypeError("coroutines cannot be used with call_soon()")
TypeError: coroutines cannot be used with call_soon()
```

**Comment by SunDwarf** [comment]
did you read the error

**Comment by Panoplos** [comment]
Yes, which means what you suggested doesn't work. ;^)

**Comment by SunDwarf** [comment]
`logout` is a coroutine, `stop` is not so you didn't do what I suggested

**Comment by Panoplos** [comment]
Did you read the original error? :^)

**Comment by SunDwarf** [comment]
have you tried being less condescending because nobody will want to help you acting like this

**Comment by Panoplos** [comment]
In other words, `loop.stop` is not the initial problem. It is calling `client.logout` that is problematic. Thank you for addressing the `loop.stop` issue before getting to it, though. :^)

**Comment by Emzi0767** [comment]
Googling the message will yield answers, it's super easy.

**Comment by SunDwarf** [comment]
http://lmgtfy.com/?q=how+to+be+less+of+an+asshole+when+asking+for+help+online

**Comment by Panoplos** [comment]
@Emzi0767 Certainly, if that was the actual problem. The pertinent question asked above is not really about calling `loop.stop`, but about getting at the heart of how to handle an asyncio based lib (discord.py) in a Thread. We are getting close, as created a loop and setting it in the thread has gotten me to the loop running, but `client.run(...)` blocks, so I cannot close the client through signals generated by the main thread...

**Comment by SunDwarf** [comment]
`client.run` is a wrapper around `loop.run_forever` which is stopped by calling `loop.stop`

**Comment by Panoplos** [comment]
Correct, and I cannot (or rather maybe simply do not know how to) call `loop.stop` in the thread that `loop.run_forever` has been called in. Normally, I would wait for an event after kicking off the loop scheduler, but execution, of course, stops at that call.

**Comment by Aareon** [comment]
I've fumbled over this same issue once before. I'm interested to see if an explanation/solution comes out of this thread. Could this method possibly be used for sharding?

**Comment by khazhyk** [comment]
As i said, if you are calling a coroutine from another thread, you must use run_coroutine_threadsafe.

Calling ds.stop() is calling it on the main thread, not your calling thread.
