### ISSUE TITLE
discord.Member.avatar_url returns an invalid url

### ISSUE THREAD

**Issue by AggressivelyMeows** [Rapptz/discord.py#499]
I tried getting the url from my avatar. However every time i try, it returns a 404.
Not sure what i did wrong, but all im doing is 
```py
 print(member.avatar_url)
```
http://i.imgur.com/4l8VLsv.png

EDIT (More info):
Trying to do a get request on the url results in a 404. Not sure if discord changed the url formatting or not as im not in the dev server

**Comment by Boqi4** [comment]
Shouldn't it be cdn.discordapp.net?

**Comment by Gorialis** [comment]
the latest version of discord.py uses CDN links, but judging from (limited) testing, the old URLs on images.discordapp.net still work.

**Comment by AggressivelyMeows** [comment]
But im using the latest version

**Comment by Boqi4** [comment]
Are you sure you are?

**Comment by Gorialis** [comment]
try updating to the development version (although it's doubtful this is the cause of this specific problem):
```
python3 -m pip install -U https://github.com/Rapptz/discord.py/archive/master.zip#egg=discord.py[voice]
```

**Comment by AggressivelyMeows** [comment]
VersionInfo(major=0, minor=16, micro=7, releaselevel='final', serial=0)

**Comment by SunDwarf** [comment]
This might be Discord's weird 404 bug rather than a library issue.

**Comment by AggressivelyMeows** [comment]
Yeah, this is a discord issue as some images work while others dont.
