### ISSUE TITLE
Can i use cython to speed up discordpy?

### ISSUE THREAD

**Issue by botiapa** [Rapptz/discord.py#500]
And if yes, how?

**Comment by SunDwarf** [comment]
In what way would you leverage the features of Cython to speed it up?

**Comment by botiapa** [comment]
i mean, can I complie the discordpy package?

**Comment by botiapa** [comment]
I didn't use cython before so i don't really know how it works

**Comment by SunDwarf** [comment]
no

please look up what cython is before opening issues like this thanks
