### ISSUE TITLE
KeepAliveHandler stopped.

### ISSUE THREAD

**Issue by khazhyk** [Rapptz/discord.py#501]
Bot hadn't received a message for 2 days, but hadn't reconnected. Noticed the KeepAliveHandler had been stopped.
`bot.ws._keep_alive`
<KeepAliveHandler(Thread-6, stopped daemon 140053601072896)>

Gateway stopped on Mar 3rd, and I do not see a corresponding "We have stopped responding to the gateway." log, which would seem to mean the KeepAliveHandler was stopped for some reason other than the heartbeat failing to respond.

I do see the warning logs in other cases, so it does seem to work as expected most of the time.

**Comment by khazhyk** [comment]
This was the last thing in the log when it stopped responding:

```
[2017-03-03 04:26:19,789][websockets.protocol][INFO] Failing the WebSocket connection: 1011
[2017-03-03 04:26:19,789][discord.gateway][INFO] Websocket closed with 1006 (), attempting a reconnect.
[2017-03-03 04:26:19,789][discord.client][INFO] Got ResumeWebSocket
```

Seems like there's a possible case where we never get HELLO but our connection is half-closed - in this case the _keep_alive thread hasn't started yet.

We should time out and force a reconnect if we do not receive op HELLO in a certain time period.

**Comment by Rapptz** [comment]
That doesn't make sense. We first poll for op HELLO before I even set an attribute named `_keep_alive`.

**Comment by khazhyk** [comment]
I'm not seeing a "Created websocket connected to" message, nor resume/identify log, so it somehow hung in DiscordWebSocket.from_client.

(I was misunderstanding how this worked, I thought the websocket instance was reused, what I was seeing was the old closed connection just hadn't been updated yet, since the return of from_client is what gets set to the new value).

Is it possible for websockets.connect to hang indefinitely? There's a default timeout parameter set to 10, but it looks like this might not prevent connect from hanging:

> The timeout parameter defines the maximum wait time in seconds for completing the closing handshake and, only on the client side, for terminating the TCP connection. close() will complete in at most this time on the server side and twice this time on the client side.
(http://websockets.readthedocs.io/en/stable/api.html#websockets.protocol.WebSocketCommonProtocol)

**Comment by khazhyk** [comment]
It might make sense to have a static timeout for all websocket ops before we start the keep alive thread.

**Comment by Rapptz** [comment]
The keep-alive is irrelevant.

Your issue can probably be solved by wrapping `websockets.connect` in `asyncio.wait_for`.

**Comment by khazhyk** [comment]
That's what I'm suggesting

**Comment by khazhyk** [comment]
This looks like it's fixed in rewrite.
