### ISSUE TITLE
VoiceClient doesn't seem to have latency and average_latency

### ISSUE THREAD

**Issue by Tsumiki-Chan** [Rapptz/discord.py#5057]
### Summary

Upon trying to get the latency and average_latency properties from a discord.VoiceClient object it reports `AttributeError: 'VoiceClient' object has no attribute 'average_latency'`.
Same seems to appear when trying to get those properties from the DiscordVoiceWebSocket directly.
(` AttributeError: 'DiscordVoiceWebSocket' object has no attribute 'average_latency'`)

### Reproduction Steps

1. Connect to a voice channel
2. Wait a bit
3. call `VoiceClient.latency` or `VoiceClient.average_latency`

```py
    @commands.command(name='test')
    @Checks.has_permission("test")
    @commands.cooldown(rate=1, per=10.0, type=commands.BucketType.channel)
    async def test(self, ctx):
        """ Latency test """
        destination = ctx.author.voice.channel
        voice = await destination.connect()
        await asyncio.sleep(5)
        print(discord.__version__, repr(voice))
        await ctx.send(f"{round(voice.average_latency*1000, 0)} ms")
        await voice.disconnect()
```

### Expected Results

`voice.latency` to return a float

### Actual Results
```
Traceback (most recent call last):
   File "/home/tomori/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
   File "/home/tomori/Rewrite/cogs/BotInfo.py", line 205, in test
    await ctx.send(f"{round(voice.average_latency*1000, 0)} ms")
 AttributeError: 'VoiceClient' object has no attribute 'average_latency'
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### System Information

```
- Python v3.8.3-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Linux 4.15.0-106-generic #107-Ubuntu SMP Thu Jun 4 11:27:52 UTC 2020
```

**Comment by nihaals** [comment]
`discord.VoiceClient.latency` and `discord.VoiceClient.average_latency` is not available in your version (1.3.3), but is available in the development version ("latest").

- [The docs for your version](https://discordpy.readthedocs.io/en/v1.3.3/api.html#discord.VoiceClient)
- [The docs for latest (git)](https://discordpy.readthedocs.io/en/latest/api.html#discord.VoiceClient.latency)

The [README](https://github.com/Rapptz/discord.py/blob/66c6be50d8ac5d401a658c757c5f1ccb454c798b/README.rst#installing) gives an example of how to install the development version (it is not necessarily stable):
```bash
$ git clone https://github.com/Rapptz/discord.py
$ cd discord.py
$ python3 -m pip install -U .[voice]
```

**Comment by Tsumiki-Chan** [comment]
Then may I suggest adding "New in version 1.4." in the docs? :)

**Comment by nihaals** [comment]
It looks like this is one of the few attributes that are missing it, you might want to rename the issue to reflect a docs request
