### ISSUE TITLE
Getting issues on mac!

### ISSUE THREAD

**Issue by haaddaa1** [Rapptz/discord.py#506]
Ignoring exception in message
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 252, in _run_extra
    yield from coro(*args, **kwargs)
  File "/Users/_/Desktop/G/Red-DiscordBot/cogs/selfembed.py", line 33, in on_message
    if self.eee["toggle"] and author.id == self.bot.owner.user.id:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/client.py", line 296, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class '__main__.Bot'>' object has no attribute 'owner' 

**HELP**

**Comment by Phxntxm** [comment]
If you want the owner, you need to use this:

http://discordpy.readthedocs.io/en/latest/api.html#discord.AppInfo.owner

**Comment by haaddaa1** [comment]
?

**Comment by haaddaa1** [comment]
don't get it?

**Comment by haaddaa1** [comment]
i set my self as owner

**Comment by Phxntxm** [comment]
You are calling something here:
```
self.bot.owner.user.id
```

The error is this:
```
AttributeError: '<class 'main.Bot'>' object has no attribute 'owner'
```

The bot class....has no owner. Now I can see this is RedBot so maybe you want to go to them for help, but typically the `Client` or `Bot` class has no attribute owner.

**Comment by haaddaa1** [comment]
Idk

**Comment by haaddaa1** [comment]
...

**Comment by Gorialis** [comment]
This is an issue related to https://github.com/Twentysix26/Red-DiscordBot . Please check if there is a new version of the bot you are not on, and if you still get problems, please post an issue there.

**Comment by haaddaa1** [comment]
that didn't help lol

**Comment by haaddaa1** [comment]
i updated my bot and everything

**Comment by Gorialis** [comment]
The error you are getting is not related to discord.py directly. Post your error in https://github.com/Twentysix26/Red-DiscordBot/issues , as this error is caused by the code in that bot, not discord.py

**Comment by Phxntxm** [comment]
Just an FYI, next time you forget to add something, you can edit comments. GitHub isn't a chat program, it's a software development platform. Basically what I'm trying to say is, don't double-comment unless a significant amount of time has passed.

Also note a few things:
1) This isn't a library issue
2) This isn't a "Mac" issue
3) This is an issue with your RedBot. Post an issue, as said above, here:
https://github.com/Twentysix26/Red-DiscordBot/issues

**Comment by spikespaz** [comment]
**Please close this issue because it is irrelevant to this library.** Please post issues in the correct repository, write with formal grammar, indent code blocks, dont' post short, spammy messages, etc. Thank you.

**Comment by haaddaa1** [comment]
can someone help
