### ISSUE TITLE
ctx.message.mention_everyone false when a user don't have permission to mention everyone, but the message still contains the @everyoen ping.

### ISSUE THREAD

**Issue by FightMan01** [Rapptz/discord.py#5060]
### Summary

I have an afk command where the users can set text. I'm trying to filter if the user set everyone ping. If the user has permission, the `ctx.message.mention_everyone` returns True, but when the user don't have permission it returns False. 

### Reproduction Steps
```py
    @commands.command()
    async def afk(self, ctx, *, reason = None):
        if ctx.message.mention_everyone:
           await ctx.send("Ping detected.")
        else:
           await ctx.send("nope")
```
### Expected Results

When the user write `!afk @everyone` it should return `Ping detected`. 

### Actual Results

If the user has the permission it returns `Ping detected`. But the user doesn't have a permission it returns `nope`.

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.8.2-final
- discord.py v1.4.0-alpha
    - discord.py pkg_resources: v1.4.0a0
- aiohttp v3.6.2
- system info: Linux 5.4.0-31-generic # 35-Ubuntu SMP Thu May 7 20:20:34 UTC 2020

**Comment by Rapptz** [comment]
Per the [notes in the documentation](https://discordpy.readthedocs.io/en/latest/api.html#discord.Message.mention_everyone) this is working as intended.

**Comment by FightMan01** [comment]
🤔 But it doesn't make too much sense.

**Comment by numbermaniac** [comment]
If you just wanted to check whether the ping attempt is present in the message you could just use `'@everyone' in ctx.message.content` or similar. `mention_everyone` is only True if the everyone/here ping was actually successful.
