### ISSUE TITLE
Automatically replace underscores with dashes in command names

### ISSUE THREAD

**Issue by Artemis21** [Rapptz/discord.py#5065]
### The Problem

Whenever I want a dash in a command name, I have to use an underscore in the function name, and provide the name parameter to the command wrapper. While this isn't very much work, I do not think it would be much work to change in the library, and for me, it is *always* what I want to do. Dashes always feel more user friendly, and they are an established convention in existing bots. This change should still, of course, be overwritten by the name parameter.

### The Ideal Solution

When an underscore (`_`) occurs in the function name for a command, replace it with a dash (`-`).

### The Current Solution

The library does not do anything automatically, you must use the `name` parameter.

### Summary

Automatically replace underscores with dashes when they appear in the name of functions that are commands.

I would be happy to implement this if the idea is accepted.

**Comment by apple502j** [comment]
This is a breaking change.

**Comment by Artemis21** [comment]
This is a breaking change in that it would change command names in bots that do not use the name parameter, yes.

**Comment by Phxntxm** [comment]
```
While this isn't very much work, I do not think it would be much work to change in the library, and for me, it is always what I want to do.
```

I do not mean to be rude but, you realize you are not everyone correct? If it is what *you* want to do it, that does not mean that that is what *everyone* wants to do. This is a breaking change for something so trivial to do yourself it makes absolutely no sense to be in the library. It's also completely not intuitive to guess that underscores would be transformed to dashes so I'd be against the idea in the *first* place. Some people may want it to be underscores, in fact I've used a couple commands with underscores.

**Comment by Rapptz** [comment]
Transformations of the command name is not something I want to do.

**Comment by jack1142** [comment]
It is also not hard to implement yourself by subclassing `Command` (and `Group`) class, if that's what *you* want.

**Comment by Artemis21** [comment]
Ok :+1:
