### ISSUE TITLE
webhook send does not return a message

### ISSUE THREAD

**Issue by DontStarve72** [Rapptz/discord.py#5078]
### Summary

The webhook send function returns none instead of a message type

### Reproduction Steps

```python
import discord
from discord import Webhook, RequestsWebhookAdapter

webhook = Webhook.partial( '123456', 'abcdefg', adapter=RequestsWebhookAdapter())
msg = webhook.send("Test Message")

print(msg.id)
```

### Expected Results

The ID of the message sent via webhook

### Actual Results

```
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    print(msg.id)
AttributeError: 'NoneType' object has no attribute 'id'
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### System Information

- Python v3.8.3-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Linux 5.7.4-arch1-1 #1 SMP PREEMPT Thu, 18 Jun 2020 16:01:07 +0000

**Comment by bijij** [comment]
Hi there, [if you read the documentation](https://discordpy.readthedocs.io/en/latest/api.html#discord.Webhook.send) you can see that by default `Webhook.send` will return None, only when the `wait` parameter is set to `True` then the function will return the `Message` object.
