### ISSUE TITLE
ERROR:asyncio:Task exception was never retrieved

### ISSUE THREAD

**Issue by botiapa** [Rapptz/discord.py#508]
I've built a music bot that downloads a youtube video, converts it to mp3 then plays it with voice.create_ffmpeg_player. It plays the music fine until randomly it stop and throws this error message:

```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<VoiceClient.poll_voice_ws() done, defined at E:\python35\lib\site-packages\discord\voice_client.py:269> exception=ConnectionClosed('WebSocket connection is closed: code = 1006, no reason.',)>
Traceback (most recent call last):
  File "E:\python35\lib\site-packages\discord\gateway.py", line 635, in poll_event
    msg = yield from asyncio.wait_for(self.recv(), timeout=30.0, loop=self.loop)
  File "E:\python35\lib\asyncio\tasks.py", line 392, in wait_for
    return fut.result()
  File "E:\python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "E:\python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "E:\python35\lib\site-packages\websockets\protocol.py", line 298, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006, no reason.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "E:\python35\lib\site-packages\discord\voice_client.py", line 276, in poll_voice_ws
    yield from self.ws.poll_event()
  File "E:\python35\lib\site-packages\discord\gateway.py", line 638, in poll_event
    raise ConnectionClosed(e) from e
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 1006, no reason.
```

I'm using PyTube (https://github.com/nficano/pytube). And if you're wondering why I created a custom yt downloader and player, I wanted more control over the quality. I hope you can understand me, 

Thanks

**Comment by OrangeChaten** [comment]
That error is just cloudflare mucking about, dont worry about it, just restart your bot or the library will auto reconnect.

**Comment by botiapa** [comment]
But it happens all the time. I cannot use the musicbot at all because of this.

**Comment by JessWalters** [comment]
This also happens to me all the time. Is there any sort of way to fix/avoid this? Or is this something we just have to deal with?

**Comment by Zwork101** [comment]
I also have the same problem when i connect to a non-bot account, and have it running for a long period of time. I don't know if this works with music, but try to catch the error, and it doesn't seem to do much harm

**Comment by botiapa** [comment]
I finally fixed it. I ran them in another thread and waited until they are finished.

**Comment by botiapa** [comment]
It throws the error because something takes too long to complete and it freezes the whole script. For example in my bot it can take a few seconds to download the video so I have to run it in another thread.
