### ISSUE TITLE
Document BanEntry in Sphinx index

### ISSUE THREAD

**Issue by ghost** [Rapptz/discord.py#5080]
Looks like `BanEntry` is a dead link on Guild#fetch_ban.

![image](https://user-images.githubusercontent.com/67113319/86040099-57607f00-ba3b-11ea-9be5-c8e93df524e6.png)

I might be missing it, but I do not think I can find this in the search either. Would it be possible to check this to make sure it is documented, if appropriate?

If I have missed anything, apologies. 

Cheers :)

**Comment by NCPlayz** [comment]
It's already detailed in the other ban method `Guild.bans`.

**Comment by SebbyLaw** [comment]
I talked with Danny about this one when writing #5067. BanEntry is quite literally a namedtuple that stores two attributes, and is documented in the two places it is used, `guild.fetch_ban()` and `guild.bans()`. If you're curious about the code for BanEntry:
```py
BanEntry = namedtuple('BanEntry', 'reason user')
```
in [guild.py](https://github.com/Rapptz/discord.py/blob/master/discord/guild.py#L52)

**Comment by Rapptz** [comment]
Duplicate of #2585
