### ISSUE TITLE
Shard restarting randomly

### ISSUE THREAD

**Issue by crazygmr101** [Rapptz/discord.py#5089]
### Summary
Shard closes randomly, the bot isn't under much load.
Possibly related: https://github.com/Rapptz/discord.py/issues/1144, though I did notice that issue was a long time ago, and was probably fixed.

### Reproduction Steps

Happens randomly, not sure how to reproduce.

### Expected Results

Shard not to close

### Actual Results
```
WARNING:discord.gateway: Shard ID None has stopped responding to the gateway. Closing and restarting.
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [ ] I have shown the entire traceback, if possible.
- [ ] I have removed my token from display, if visible.

### System Information

```
- Python v3.7.5-final
- discord.py v1.3.2-final
- aiohttp v3.6.2
- websockets v6.0
- system info: Linux 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020
```

**Comment by Rapptz** [comment]
This falls in line with the general advice given here #5073. Basically this is normal and just happens on a day to day basis with no actual issue.

**Comment by crazygmr101** [comment]
Alrighty. Just figured I'd bring it up, in case it was an issue. Thanks!

**Comment by crazygmr101** [comment]
I am curious. Would this be better logged as INFO instead of WARNING, if it's normal? The only reason I thought something was wrong was cuz it was logging as a warning.
