### ISSUE TITLE
Video Live Stream

### ISSUE THREAD

**Issue by FxcMike** [Rapptz/discord.py#5098]
Allow bots to livestream(go live like users can in voicechat) so people can hook it up YouTube into it and people can watch videos with the bot.

**Comment by Taarek** [comment]
Discord doesn't support this behavior at this time. :)
See https://github.com/Rapptz/discord.py/issues/4179#issuecomment-639938033

**Comment by Androz2091** [comment]
This is not supported by the Discord API (see https://github.com/discord/discord-api-docs/issues/1386).
