### ISSUE TITLE
Some members/users when tagging them i get an error user not found

### ISSUE THREAD

**Issue by Ahmed-Khaled-dev** [Rapptz/discord.py#5104]
### Summary

When I try any command that involves the user tag @Anything it doesn't work with specific users especially users who have weird letters or emojis in their name but sometimes with regular users.

### Reproduction Steps
It says discord user not found

### Expected Results

I accept the command to work let's say avatar command that sends the avatar of a specific user on all users/members

### Actual Results
It says discord user not found

### Checklist

- [x ] I have searched the open issues for duplicates.
- [x ] I have shown the entire traceback, if possible.
- [x ] I have removed my token from display, if visible.

### System Information

- Python v3.7.4-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Windows 10 10.0.18362

**Comment by oakenduck** [comment]
Are you making sure to set the type of the `member` argument in the function definition to `discord.Member`?

**Comment by Ahmed-Khaled-dev** [comment]
Yes I am 100% sure you can take a look at this piece of code
`@client.command()
async def av(ctx, member: discord.Member):
    await ctx.message.delete()
    show_avatar = discord.Embed(
        color=RandomColor()
    )
    show_avatar.set_image(url="{}" .format(member.avatar_url))
    await ctx.send(embed=show_avatar)`

I added error handling so now when I tag some members it takes it as a User input error
it actually happened so some people and after a while, it started working with them and weird stuff so I am not sure but I am sure there is something wrong, probably not with my code I think

**Comment by oakenduck** [comment]
I only use `client.command` in the main file, in the form of my load, unload, and reload commands, so I'm not well acquainted with that half of `discord.py` I do know that I've had issues with it before, as it's not quite the same as using the cogs half. Try this command inside a cog, and see what's different.

**Comment by Vexs** [comment]
This issue has *zero* relationship to how commands work inside and outside of cogs. @Ahmed-Khaled-dev, please provide the exact traceback for your error for perfect clarity. If it's what I'm thinking of this could be a cache issue.

**Comment by oakenduck** [comment]
> 
> 
> This issue has _zero_ relationship to how commands work inside and outside of cogs. @Ahmed-Khaled-dev, please provide the exact traceback for your error for perfect clarity. If it's what I'm thinking of this could be a cache issue.

Yes, I know. I'm not saying that it is. I'm simply saying I have had issues with commands similar to this, and have in fact had essentially this exact issue. It was never solved, and I moved to using only cogs for my needs.

**Comment by Rapptz** [comment]
Back in v1.3 the converters were changed to use the mentions array to find users as a fallback in case they weren't in cache since Discord made a change to populate members that way for "stateless bots". As far as I'm aware this hasn't broken before on Discord's end so I'm unsure what's going on here unless you've failed to mention them or are not using the built-in Member/User converter.

**Comment by Ahmed-Khaled-dev** [comment]
Okay I have got some more info so anyone can help me with this:
So an example of what has been happening and still happening
is that for example user A#aaaa uses a command that involves discord.Member and he mentions B#bbbb in the command
it doesn't work and throws an error but since I have error handling all the time it considers it as a User input error.
but when C#cccc mentions B#bbbb in the same command IT WORKS!
and after some time like 2 weeks when A#aaaa tries to mention B#bbbb IT WORKS!
and this cycle keeps happening most of the time.
so I don't get it at all.
If someone can help it would be hugely appreciated.

**Comment by Ahmed-Khaled-dev** [comment]
@Rapptz So no I didn't fail to mention them, but can I know what's the Member/User convertor?

**Comment by isaa-ctaylor** [comment]
Did you actually mention the user or jist put `@person`? Could you provide screenshots of this in action?
