### ISSUE TITLE
adapter=discord.RequestsWebhookAdapter()

### ISSUE THREAD

**Issue by Natan60fps** [Rapptz/discord.py#5105]
``Traceback (most recent call last):
  File "C:/Users/natan/Desktop/Aerial-master/main.py", line 48, in <module>
    adapter=discord.RequestsWebhookAdapter()``

  ``File "C:\Users\natan\Desktop\Aerial-master\venv\lib\site-packages\discord\webhook.py", line 509, in from_url
    raise InvalidArgument('Invalid webhook URL given.')
discord.errors.InvalidArgument: Invalid webhook URL given.``

**Comment by SebbyLaw** [comment]
As the error states, you passed in an invalid webhook url.

Additionally, this is not an issue with discord.py.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.
For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/api), as the README recommends.

**Comment by Natan60fps** [comment]
the problem is that my webhook is valid, I don't know what to do

**Comment by Rapptz** [comment]
In the current version of the library the URLs have to meet the format of `discordapp.com`. The client gives URLs in forms of `discord.com`. Both work but the library doesn't recognise the latter. Your best bet is to just change it from `discord.com` to `discordapp.com` so the library can work with it. In the next version of the library this will be fixed.

**Comment by flipbit03** [comment]
This is still not fixed.

**Comment by NCPlayz** [comment]
That should have been fixed at 66c6be5.
