### ISSUE TITLE
Discord.py not recognizing one command

### ISSUE THREAD

**Issue by master98ofu** [Rapptz/discord.py#511]
I have a command called tetts

`	
@bot.command(pass_context=True)
async def tetts(ctx, *, IP):
	"""hi"""
	r = requests.get('http://ipinfo.io/{}/json'.format(IP))
	a = json.loads(r)
	await bot.say('IP FOUND! :rotating_light:\n\n**IP**: {}\n**Hostname**: {}\n**Location**: {}\n**Organization or ISP**: {}'.format(a['ip'], a['hostname'], a['city'] + ',' + a['region'] + "," + a['country'], a['org']))`

I try running it, other commands run just fine, but this one will not run at all. It will give me an error saying:

`Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "tetts" is not found`

What am I doing wrong?

**Comment by Rapptz** [comment]
This needs more information.

**Comment by ButterCheezii** [comment]
Is that your actual code? No newlines or indentation?

**Comment by Butts** [comment]
^ Also why are you passing context if you're not going to use it?

Lastly: http://discordpy.readthedocs.io/en/latest/faq.html#what-does-blocking-mean
