### ISSUE TITLE
Return pin Message object from Message.pin function

### ISSUE THREAD

**Issue by cclloyd** [Rapptz/discord.py#5112]
### The Problem

I want to pin a message, then delete the message that says a message was pinned.

### The Ideal Solution

The discord.Message.pin function returns the message that shows "X pinned a message to this channel" so you can easily run something like `await pin_message.delete()`

### The Current Solution

Unknown

### Summary

Make `discord.Message.pin` return the pin message if successful.

**Comment by Rapptz** [comment]
This is a denied feature request on Discord's end unfortunately. https://github.com/discord/discord-api-docs/issues/1617
