### ISSUE TITLE
discord.Streaming platform parameter does not work as it should when argument is YouTube

### ISSUE THREAD

**Issue by Batman212369** [Rapptz/discord.py#5118]
### Summary

Hello there. Recently, I tried making the bot stream a YouTube live video (for testing purposes), supplying it with all necessary arguments, including the platform argument. It does say "Streaming (NAME)", but when you open it, it says "Live on Twitch" instead of "Live on YouTube". Really not much else to say except that it is broken.

### Reproduction Steps

`await bot.change_presence(status=discord.Status.online, activity=discord.Streaming(platform="YouTube", url="https://www.youtube.com/watch?v=5qap5aO4i9A", name="Test"))`
(Even though everything is valid and the bot's status are set to "Streaming", it says "Live on Twitch")
(Can be replicated by simply using any YouTube URL, any name, and having the platform as "YouTube")

### Expected Results

Bot should be saying "Live on YouTube".

### Actual Results

Bot says "Live on Twitch".

![image](https://user-images.githubusercontent.com/56501846/87224557-dc7a5b00-c38e-11ea-9398-2148febd4cc1.png)

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

```
- Python v3.7.8-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Windows 10 10.0.15063
```

**Comment by gbdlin** [comment]
According to the codebase, `platform` is not a valid argument for `Streaming` class. Mapping of `__init__` arguments to class attributes looks like this:

`name` -> `platform`
`url` -> `url`
`state` -> `game`
`details` -> `name`
`details` -> `details`
`assets` -> `assets`

In conclusion: use `name` instead of `platform` and `details` instead of `name`.

**Comment by Rapptz** [comment]
As far as I'm aware bots aren't able to send non-twitch URLs so I wouldn't expect this to work.

**Comment by Batman212369** [comment]
> According to the codebase, `platform` is not a valid argument for `Streaming` class. Mapping of `__init__` arguments to class attributes looks like this:
> 
> `name` -> `platform`
> `url` -> `url`
> `state` -> `game`
> `details` -> `name`
> `details` -> `details`
> `assets` -> `assets`
> 
> In conclusion: use `name` instead of `platform` and `details` instead of `name`.

@gbdlin, Name doesn't seem to work either. Swapping `platform` with `name` and `name` with `details` still makes it say "Live on Twitch".

> As far as I'm aware bots aren't able to send non-twitch URLs so I wouldn't expect this to work.

@Rapptz, I mean, it does make the "Watch" button appear, and when you click it, it forwards you to the video. If this is the case though, why should it be documented in the first place, and if needed to be documented, shouldn't it be stated that it's not functional at the moment/doesn't really change anything, in the documentation? It creates a bit of confusion. It just says "New in version 1.3" and nothing else.

![image](https://user-images.githubusercontent.com/56501846/87225064-d8e8d300-c392-11ea-83d4-b418189c5a6a.png)
(https://discordpy.readthedocs.io/en/latest/api.html?highlight=streaming#discord.Streaming.platform)

**Comment by hamza1311** [comment]
This looks like a client bug. On my `Canary 63252 (7138483)` build, I can reproduce this behaviour but on my phone with version `29.2 (1179)`, it says `Streaming Youtube`
![image](https://user-images.githubusercontent.com/47357913/87226266-0d1cbd80-c3ac-11ea-8484-8328576f306f.png)

**Comment by Batman212369** [comment]
Alright. After some testing, I kind of figured it out. It is 99% a client bug rather than a code one. Thanks to @hamza1311 for mentioning it.

From what I understood, `details` will overwrite `name`. Having that in mind, we can continue to how this happens.
On phone (at least mine), whenever it's streaming, it says "Live on" and the displaying name. In desktop, it says "Live on Twitch". Only way to make it say "YouTube" is if the displaying name is "YouTube" and nothing else.

So in conclusion, mobile will just say "Live on" and whatever is displayed, while desktop will only switch to "Live on YouTube" if and only if whatever is displayed is saying "YouTube", so a custom name isn't possible. Also, on mobile, the "Watch" button will not appear when using YouTube URLs (not sure about Twitch ones). For example, if you made the name "A sick video", mobile would say "Live on A Sick Video" and desktop would say "Live on Twitch". If you were to make the name "YouTube", then mobile would say "Live on YouTube", and so would the desktop. With that being said, this should close this question as it is not an API bug, but a Discord client one (I believe).
