### ISSUE TITLE
Ssl issue but on Ubuntu 18.04 instead of Windows 8.1

### ISSUE THREAD

**Issue by Giancrafter** [Rapptz/discord.py#5122]
Im sorry guys in my previous Answer to this issue i messed something up.
But as already said in the title i am not on windows and my root certs are not expired. So what can I do?

_Originally posted by @Giancrafter in https://github.com/Rapptz/discord.py/issues/5119#issuecomment-657181996_

**Comment by Rapptz** [comment]
Please stop opening new issues when you mean to respond to one.
