### ISSUE TITLE
Argument "resend" for <discord.Message>.edit

### ISSUE THREAD

**Issue by artem-6191** [Rapptz/discord.py#5123]
### Current problem

Too many try/except for will make code more unreadable/incomprehensible/etc and appear on performance

### The Ideal Solution

Adding "resend" for <discord.Message>.edit
Example:
```py
msg = await ctx.send('hello')
await msg.edit(content='world', resend=True) # Will edit message to "world"
await msg.delete() 
await msg.edit(content='hello world', resend=True) # WIll send "hello world"
```

### The Current Solution

```py
try:
   await msg.edit(...)
except discord.errors.NotFound:
   msg = await ctx.send(...)
```

### Summary

With this feature it will be easier to resend message if bot can't edit message (i.e. message has been deleted, etc)
<discord.Message>.edit(resend=True) will automaticly try to resend message if message editing failed

**Comment by Rapptz** [comment]
This feels outside of the scope of the library since it's a niche use case. If you want to do this then feel free to make a helper function and use that instead. Keyword arguments passed to edit are usually reserved for things the API actually implements.
