### ISSUE TITLE
Ability to add more media per embed

### ISSUE THREAD

**Issue by isabelok** [Rapptz/discord.py#5129]
### The Problem
Embeds in the library can only contain one image. Videos also cannot be added to embeds (as far as I can tell) but are still detectable with `Embed.video`

### The Ideal Solution
Embeds would allow multiple images (this is possible by adding multiple embeds with the same title and title URL and adding a separate image to each, according to [this site](https://discohook.org/)) and would allow videos to be added. 
Multiple embeds per message would also allow you to fix the image issue.

**Comment by Rapptz** [comment]
Discord limitation on all accounts.

There is a way to do multiple images per embed using an undocumented hack but it requires multiple embeds which is only possible with webhooks.

**Comment by isabelok** [comment]
> Discord limitation on all accounts.
What do you mean by this?
> There is a way to do multiple images per embed using an undocumented hack but it requires multiple embeds which is only possible with webhooks.
Ah, ok.

**Comment by hamza1311** [comment]
Bots can only send one embed per message. The website you linked handles multiple embeds per message which only webhooks can send.

You also cannot pass video field to embed as mentioned by the note [here](https://discord.com/developers/docs/resources/channel#create-message-params).

**Comment by isabelok** [comment]
> Bots can only send one embed per message. The website you linked handles multiple embeds per message which only webhooks can send.
> 
> You also cannot pass video field to embed as mentioned by the note [here](https://discord.com/developers/docs/resources/channel#create-message-params).

Oh ok, thank you!

**Comment by Dillonzer** [comment]
If you are interested in doing multiple images per embed I've come up with an image carousal with my bot. It requires waiting for the specific emoji and then editing the embed with the new image link.
[Card Carousal](https://imgur.com/JeckmWg)
