### ISSUE TITLE
Audio playback from Youtube: TLS session invalidated

### ISSUE THREAD

**Issue by L12C** [Rapptz/discord.py#5131]
### Summary
When attempting to stream audio from Youtube to a voice channel, the connection to Youtube is closed after approximately three minutes. This only happens when using Discord.py and Youtube, not when using other video hosting sites or using other software to access it (such as directly using ffmpeg) 

### Reproduction Steps
Run the following code snippet with stream_url being a YT stream url as obtained from `YoutubeDL(YTDL_OPTS).extract_info(video_url, download=False)["formats"][0]["url"]`(using [youtube-dl](https://github.com/ytdl-org/youtube-dl/)):

```
source = discord.PCMVolumeTransformer(
    discord.FFmpegPCMAudio(stream_url), volume=state.volume)

def after_playing(err):
    asyncio.run_coroutine_threadsafe(client.disconnect(), self.bot.loop)

client.play(source, after=after_playing)
```

### Expected Results

The audio of the given Youtube video is played in the voice channel

### Actual Results

Playback starts, but after around three minutes terminates, printing this to the console:

```
[tls @ 0x55afa0b30640] Error in the pull function.
[matroska,webm @ 0x55afa0b2c300] Read error
[tls @ 0x55afa0b30640] The specified session has been invalidated for some reason.
    Last message repeated 1 times
https://r1---sn-4g5ednee.googlevideo.com/videoplayback?[OMITTED]: Input/output error
[2020-07-16 23:00:56,034] INFO [discord.player.cleanup:153] Preparing to terminate ffmpeg process 8873.
[2020-07-16 23:00:56,036] INFO [discord.player.cleanup:165] ffmpeg process 8873 successfully terminated with return code of 0.
[2020-07-16 23:00:56,064] INFO [discord.voice_client.terminate_handshake:166] The voice handshake is being terminated for Channel ID XXXXXXXXXXXXXXXXXX (Guild ID XXXXXXXXXXXXXXXXXX)
[2020-07-16 23:00:56,065] INFO [discord.voice_client.terminate_handshake:168] The voice client has been removed for Channel ID XXXXXXXXXXXXXXXXXX (Guild ID XXXXXXXXXXXXXXXXXX)
[2020-07-16 23:00:56,065] INFO [discord.voice_client.poll_voice_ws:251] Disconnecting from voice normally, close code 1000.
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information
- Python v3.8.3-final
- discord.py v1.3.4-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Linux 5.7.8-arch1-1 #1 SMP PREEMPT Thu, 09 Jul 2020 16:34:01 +0000

**Comment by Vexs** [comment]
If you stream the content it will die like this, depending. I assume youtube has some keep-alive heartbeat they use, but I don't know what it is- easy fix is to just download-then-play.

**Comment by Rapptz** [comment]
This issue has little to do with discord.py and has more to do with YouTube itself. Short of downloading the video yourself there's not much for me to do here.
