### ISSUE TITLE
message cache can cause severe ram usage spikes when re-identifying

### ISSUE THREAD

**Issue by AEnterprise** [Rapptz/discord.py#5133]
### Summary

When discord invalidates some shard sessions while running, this causes shards to re-identify, this re-identifying of a few shards causes so much io-wait it kills the entire vps. I am running 3 instances with 2 shards each). This extreme io-wait does not happen at all when starting the instances

i am already using the sharding-rework branch, and while this solved many issues, this still happens every few weeks.

log: https://gist.github.com/AEnterprise/3f004ef47bd21ffc71098f5a4962e66b

as you can see around 03:29 sessions dropped and got resumed, however at 03:32 timeouts started to happen and sessions invalidated. at 03:33 blocked hearbeats logs started and don't stop, at this point all shards start to die because this is overloading the vps with abnormal io-wait

![image](https://user-images.githubusercontent.com/5206666/87765209-d5809c00-c817-11ea-840a-d4a58b6cc598.png)

when cold booting the 3 instances i do not get anywhere close to this amount of cripeling io-wait

![image](https://user-images.githubusercontent.com/5206666/87766187-0dd4aa00-c819-11ea-838d-86762f309fc6.png)

the instances started at 08:41:47, 08:42:25 and 08:43:50. There was some initial iowait due to vps still starting, but it never reached the cripeling 98% that it reached when re-identifying

### Expected Results

It to re-identify the shards without causing extreme io-wait issues

### Actual Results

extreme io-wait leading to cascading failures

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information
- Python v3.7.5-final
- discord.py v1.4.0-alpha
    - discord.py pkg_resources: v1.4.0a2393+g36f3dca
- aiohttp v3.6.2
- system info: Linux 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020

**Comment by notcatt** [comment]
your brain is huge

**Comment by AEnterprise** [comment]
after digging into this deeper it seems the iowait isn't caused by d.py directly, instead the message cache is causing the ram usage to spike more then 50%, completely filling up both ram and swap, thus causing extreme iowait with the disk not keeping up

**Comment by Naegin** [comment]
I had the same issue a few days ago when Cloudflare died. The RAM usage went from 1.4GB to 3GB~.

**Comment by helish88** [comment]
Same here, 2-3 days ago

**Comment by Rapptz** [comment]
Fixed by https://github.com/Rapptz/discord.py/commit/d3e75fa8e17d3211fe3143a4804cf5ac8ce735af
