### ISSUE TITLE
Add support to Russian booleans

### ISSUE THREAD

**Issue by averyanalex** [Rapptz/discord.py#5134]
Now, it works well with "no", "false" "disable".
But there is no Russian language support.
Please, add True:
Да, д, вкл, включить, включено
False:
Нет, н, выкл, выключить, выключено
Becouse I did not found it in conventer.py

**Comment by MinerChAI** [comment]
What about other languages? The code would become too big if you add support for all the languages and I don't see any reason for making Russian an exception

**Comment by AbstractUmbra** [comment]
You can make your own boolean converter for your language if required. There is a small example of how the current boolean converter is implement in the [docs](https://discordpy.readthedocs.io/en/latest/ext/commands/commands.html#bool) already.

**Comment by averyanalex** [comment]
Ok, ok, I understand, but I think native support for languages will help. For small code, you can do special converter file 😀
