### ISSUE TITLE
Add Python Typings

### ISSUE THREAD

**Issue by skairunner** [Rapptz/discord.py#5135]
### The Problem

Optional Python typings do not exist for discord.py

### The Ideal Solution

Implement said typings

### The Current Solution

Muddling along by reading the docs

### Summary

* Add in all the Python type annotations for ease of use with IDEs
* Problem: Typings were only introduced in Python 3.6, meaning that this will raise the minimum version requirement for discord.py and make newer versions backwards incompatible

**Comment by ShineyDev** [comment]
see #1497

**Comment by skairunner** [comment]
Ah. Exciting.
