### ISSUE TITLE
"We are being rate limited" string doesn't appear correct

### ISSUE THREAD

**Issue by skairunner** [Rapptz/discord.py#5136]
### Summary

If you configure logger to level WARN or lower and get rate limited, the message printed is approximately the following:

```
WARNING:discord.http:We are being rate limited. Retrying in 589.30 seconds. Handled u
nder the bucket "733982997472084028:None:/channels/{channel_id}"
```

It seems like {channel_id} should be being filled in.

### Reproduction Steps

Get rate limited. The following snippet should work, since channel editing has an incredibly low rate limit.

```python
import logging
logging.basicConfig(level=30)

# ...
# log in and pick a channel of choice
# ...

await channel.edit(topic="blah")
await channel.edit(topic="bleh")
```

### Expected Results

I am not entirely sure what the error message should look like, but probably not like this.

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

```
> poetry run python -m discord -v
- Python v3.8.2-final
- discord.py v1.3.4-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Linux 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020
```

Note: Am running on Ubuntu 20.04 installed via WSL2.

**Comment by Rapptz** [comment]
The channel ID is 733982997472084028. It's in the bucket string.

**Comment by skairunner** [comment]
I know that the channel id is in the error message, but shouldn't it be in /channels/{channel_id}?

**Comment by Rapptz** [comment]
Nope. The string given to you is an internal bucket name.

**Comment by skairunner** [comment]
Is it internal to discord.py? [This page](https://discord.com/developers/docs/topics/rate-limits) looks similar to the error message but it uses routing-style formatting rather than {}.

**Comment by Rapptz** [comment]
Yes, it's an internal representation. It's `Route.bucket` in the code.
