### ISSUE TITLE
Editing an embed containing an attached file makes the file show at the start of the embed

### ISSUE THREAD

**Issue by dob9601** [Rapptz/discord.py#5139]
Upon editing an embed which has been sent with a local image attached to it, the image will show in full size above the embed

**Comment by Vexs** [comment]
This isn't a discord.py issue, it's the nature of how local image embeds work. Discord special cases these so if you upload a file and set the embed to attachment://file.png, it hides the normal file upload and puts it in the embed. When you edit it, the image is still there, but the URL isn't, so it re-appears. 

As you can't edit files uploaded, if you want this behavior my suggestion would be to host a fileserver (or other api, depending) on your host and set the URL to point to those files.

**Comment by dob9601** [comment]
Thanks, had considered that workaround - thought I'd raise it here first on the off chance there was a better solution

**Comment by Rikjimue** [comment]
You can just replace or the attachment when you edit the message so then it will not disappear.

**Comment by andykasen13** [comment]
how so? can you give an example?

**Comment by Prabesh01** [comment]
idk exact discord.py implementaion but in raw webhook requests you can remove everything from embed this way:

```
webhook_json = {
    "content": "Embed will disaapear now",
    "embeds": [],
    "attachments": [] 
}
requests.patch(webhook_url, json=webhook_json)
```
