### ISSUE TITLE
JPEG file not identified properly when setting server banner

### ISSUE THREAD

**Issue by Jefffrey** [Rapptz/discord.py#5143]
### Summary

In the[ _get_mime_type_for_image function in utils.py](https://github.com/Rapptz/discord.py/blob/master/discord/utils.py#L302), it relies on JPEG files having JFIF or Exif in the header, else it won't recognize the file as JPEG. However there may be JPEG files without JFIF or Exif in the header, such as [this one](https://i.imgur.com/v7oSOEQ.jpg). Setting it manually via discord client as banner works fine.

### Reproduction Steps

```py
	async def set_server_banner(self, guild, filepath):
		async with aiofiles.open(filepath, "rb") as f:
			b = await f.read()
			await guild.edit(banner=bytearray(b))
```

Where filepath is pointing to a local copy of the above mentioned image.

### Expected Results

Be recognized as JPEG image, thus be able to set as server banner.

### Actual Results

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.7/site-packages/discord/ext/tasks/__init__.py", line 73, in _loop
    await self.coro(*args, **kwargs)
  File "/home/ubuntu/bot/cogs/cog.py", line 556, in check
    await self.set_server_banner(guild, config["banner_filepath"])
  File "/home/ubuntu/bot/cogs/cog.py", line 423, in set_server_banner
    await guild.edit(banner=bytearray(b))
  File "/home/ubuntu/.local/lib/python3.7/site-packages/discord/guild.py", line 1027, in edit
    banner = utils._bytes_to_base64_data(banner_bytes)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/discord/utils.py", line 299, in _bytes_to_base64_data
    mime = _get_mime_type_for_image(data)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/discord/utils.py", line 295, in _get_mime_type_for_image
    raise InvalidArgument('Unsupported image type given')
discord.errors.InvalidArgument: Unsupported image type given
```

### Checklist
- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information
- Python v3.7.7-final
- discord.py v1.3.4-final
- aiohttp v3.6.2
- websockets v6.0
- system info: Linux 4.4.0-1052-aws #61-Ubuntu SMP Mon Feb 12 23:05:58 UTC 2018

**Comment by Rapptz** [comment]
Thanks, should be fixed in latest.
