### ISSUE TITLE
After restarting a discord bot, it will no longer be active.

### ISSUE THREAD

**Issue by DerekLovesPandas** [Rapptz/discord.py#5145]
A few minutes ago I tried to run my discord bot because I had turned my computer off, and I run it locally. It gave me an error saying: "TypeError: __new__() got an unexpected keyword argument 'deny_new'" for some reason. I checked with some friends, and they reran their bots and it gave the same issue.

**Comment by numbermaniac** [comment]
Duplicate of #5109. Update your discord.py to fix the issue.

**Comment by DerekLovesPandas** [comment]
Alright, thank you!
