### ISSUE TITLE
Changelog missing 1.3.4 entry detailing allow_new hotfix

### ISSUE THREAD

**Issue by jrabbit** [Rapptz/discord.py#5147]
### Summary

No changelog at https://discordpy.readthedocs.io/en/v1.3.4/whats_new.html that explains that #5109 was fixed

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
This was added in the latest documentation (though not in the v1.3.4 documentation, and it can't be without retagging). Hopefully that's good enough.

**Comment by jrabbit** [comment]
Yeah close enough, I did check the unversioned changelog first so it would
have worked for my needs.
