### ISSUE TITLE
Making Categories

### ISSUE THREAD

**Issue by PicklesJars** [Rapptz/discord.py#515]
Okay I've been trying so hard to figure this but I can't find anything on it.
How do you make categories for the preset help command 
It's starting to make me angry that I can't find anything on it

**Comment by Phxntxm** [comment]
The "categories" are different classes, using cogs. An example of how to use these can be found here:

https://gist.github.com/leovoel/46cd89ed6a8f41fd09c5

**Comment by PicklesJars** [comment]
I... Have no idea what that memes

**Comment by PicklesJars** [comment]
oh my god I wrote "memes" instead of "means" I am literally autistic
