### ISSUE TITLE
Mention that a Help Command has to be added to a bot before adding it to the Cog

### ISSUE THREAD

**Issue by PythonCoderAS** [Rapptz/discord.py#5154]
### The Problem

In my extension setup code, I tried to add my help command to my Help cog and then add it to the bot. However, it expects a private variable to be present. Upon further inspection, it seems that this private variable is filled when the help command is added to the bot.

### The Ideal Solution

The ideal solution is to make a note in `HelpCommand.cog` that it needs to be added to the bot before adding a Cog.

**Comment by Vexs** [comment]
This would be far more actionable with the related code- I have no idea what you're doing that should result in this.

**Comment by Rapptz** [comment]
This issue is a bit too vague to be actionable and almost looks like a bug report disguised as a feature request. There is no traceback nor any mention of what's going on short of guessing. Please give more information if you want something to be done.

**Comment by PythonCoderAS** [comment]
I decided to revisit this issue. This code sample helps.

```py
from discord.ext.commands import Cog, HelpCommand

class CustomHelpCommand(HelpCommand):
    pass

class CustomCog(Cog):
    pass

chc = CustomHelpCommand()
cc = CustomCog()
```

```py
>>> chc.cog
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/User/.local/share/virtualenvs/PokestarBot-8lQ-e5KE/lib/python3.8/site-packages/discord/ext/commands/help.py", line 471, in cog
    return self._command_impl.cog
AttributeError: 'NoneType' object has no attribute 'cog'
```

```py
>>> chc.cog = cc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/User/.local/share/virtualenvs/PokestarBot-8lQ-e5KE/lib/python3.8/site-packages/discord/ext/commands/help.py", line 476, in cog
    self._command_impl._eject_cog()
AttributeError: 'NoneType' object has no attribute '_eject_cog'
```

**Comment by Rapptz** [comment]
Thanks. That helps.
