### ISSUE TITLE
discord.py not working properly

### ISSUE THREAD

**Issue by Mihir-Nagalkar** [Rapptz/discord.py#5157]
I recently installed discord.py library to make a discord bot, but it doesn't work. the bot doesn't get online 
<img width="419" alt="code" src="https://user-images.githubusercontent.com/67877208/88406954-0439dc00-cdef-11ea-9d56-e20c41d7fe05.png"> 
^^^here is a pic of my code

**Comment by Gobot1234** [comment]
This is not an issue with discord.py, you should also reset your token at https://discordapp.com/developers/applications.
GitHub issues for this repository should be used to report issues with this library.

## For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.
