### ISSUE TITLE
Abstract User(discord.abc.User) and Member status not returning the same

### ISSUE THREAD

**Issue by Nekoraru22** [Rapptz/discord.py#5161]
### Summary

When I get the status of a user who has sent a message, it appears correctly, instead when I use the `client.fetch_member` function, its status always appears Offline.

### Reproduction Steps

```py
# msg comes from the on_message event.
member = await msg.channel.guild.fetch_member(msg.author.id)
member2 = msg.author
print(member.status, member2.status)
```

### Expected Results

"online online"

### Actual Results

"offline online"
![image](https://user-images.githubusercontent.com/57575090/88485575-1777b380-cf77-11ea-8d7c-b8a38390084f.png)

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.8.1-final
- discord.py v1.3.2-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Windows 10 10.0.18362

**Comment by Rapptz** [comment]
The HTTP API has no idea about presences.
