### ISSUE TITLE
AttributeError when using guild.me.fetch_message()

### ISSUE THREAD

**Issue by TheEnigmaBlade** [Rapptz/discord.py#5168]
### Summary

When using `fetch_message()` on the `Member` version of a `ClientUser`—i.e. `guild.me.fetch_message()`—the following error occurs:

```
Traceback (most recent call last):
  File "D:\...\venv\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "D:\...\test_fetch_message.py", line 11, in on_guild_available
    message = await guild.me.fetch_message(message_id)
  File "D:\...\venv\lib\site-packages\discord\abc.py", line 934, in fetch_message
    channel = await self._get_channel()
  File "D:\...\venv\lib\site-packages\discord\member.py", line 248, in _get_channel
    ch = await self.create_dm()
  File "D:\...\venv\lib\site-packages\discord\member.py", line 109, in general
    return getattr(self._user, x)(*args, **kwargs)
AttributeError: 'ClientUser' object has no attribute 'create_dm'
```

### Reproduction Steps

The error occurs on any use of `guild.me.fetch_message()`, such as in the following self-contained example.

```python
discord_token = "..."
guild_id   = ... # Numeric guild ID in which the target message resides
message_id = ... # Numeric message ID for the desired message

import discord
client = discord.Client()

@client.event
async def on_guild_available(guild):
    if guild.id == guild_id:
        message = await guild.me.fetch_message(message_id)
        print(f"Got the message: {message.clean_content}")

client.run(discord_token)
```
### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

Python versions tested:
- 3.8.5
- 3.7.8

discord.py versions tested:
- v1.3.4-final
- v1.4.0a2409+gb77af19 (most recent commit)

System: Windows 10 10.0.19041

**Comment by SebbyLaw** [comment]
You can't create a DM with yourself.

**Comment by Rapptz** [comment]
This is intended.

`fetch_message` on `Member`/`User` instances fetch a message on the user's DM channel. However bots can't DM themselves so that operation isn't available.

**Comment by TheEnigmaBlade** [comment]
So fetching messages only works on a channel level and not on a guild level through `.me`. I believe I understand better now.

**Comment by Rapptz** [comment]
Yup, the API endpoint requires a channel_id of sorts so you need a channel to fetch a message.
