### ISSUE TITLE
In @client.event, event isn't recegnized

### ISSUE THREAD

**Issue by Zwork101** [Rapptz/discord.py#517]
So, making my second discord bot, just copy and pasted the basic stuff:
```py
import discord
import asyncio

@client.event
@asyncio.coroutine
def on_ready():
    print('Logged in as')
    print(client.user.name)
    print(client.user.id)
    print('------')
    yield from client.change_presence(game=discord.Game(name="Python 3.6 (IDLE)"))
```
And on start-up, `event` in `@client.event` isn't recognized. 
```py
Traceback (most recent call last):
  File "C:\Users\Zwork101\AppData\Local\Programs\Python\Python36-32\D&D_Discord.py", line 4, in <module>
    @client.event
NameError: name 'client' is not defined
```
I feel like I'm making a super stupid mistake. I'm on python 3.6, (though so is my other discord bot, and it works fine) Any idea f why I'm having this problem, I really feel like I've just done something idiotic, but I can't put my finger on it.

**Comment by Phxntxm** [comment]
You need to define your client instance first, as it says it's not defined. Before that event something like:

```
client = discord.Client()
```

Check the examples folder for examples on this

**Comment by Zwork101** [comment]
:face_palm: omg I knew I missed somthing, thx. I am an idiot. I had that code in my other bot, but forgot to implement it

**Comment by hubogoss** [comment]
it does not recognize it as defined

**Comment by Harmon758** [comment]
@hubogoss Please don't necro old issues that are questions.
If you need help using the library, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by ICE104** [comment]
what do I make sure to mention two rooms in @ client.event in the welcome part when a person enters the server tells him (welcome user go visit our #roles and our #guide).
do you have any advice on how to do it?

**Comment by SebbyLaw** [comment]
@ICE104 Please don't necrobump old issues.

GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.
For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.
