### ISSUE TITLE
Allow disabling converters

### ISSUE THREAD

**Issue by nihilistkitten** [Rapptz/discord.py#5172]
### The Problem

I have a fairly complicated (read: poorly-written) codebase that I'm trying to add static type hints (for mypy) to. This can cause circular import trees (because the app is poorly-structured, and logic is interspersed with the bot layer). [Mypy's solution](https://mypy.readthedocs.io/en/stable/common_issues.html#import-cycles) to this is to use string literals for forward references and import the name only if `typing.TYPE_CHECKING` is true. The issue is that d.py expects the types to be well-defined so it can check if they're converters. Specifically, the issue is here:

https://github.com/Rapptz/discord.py/blob/b77af199392209017e59eff366b46354fa210f64/discord/ext/commands/core.py#L297-L302

### The Ideal Solution

Add a `no_converters` flag to the command decorator which turns off converters for that command. I'm also happy to submit a PR which implements this, I just wanted to see if there were any objections beforehand.

### The Current Solution

Solving this now would require a fairly significant restructure of the app I'm working on: this is something that I'll do eventually, but I don't want to do it immediately, and I'd like to have static type checking to help with that process.

### Summary

There should be some mechanism to turn off converters for specific commands, so as to allow static type checking without circular imports.

**Comment by BeatButton** [comment]
Out of curiosity, how does ```from __future__ import annotations``` fail to solve this problem for you?

**Comment by Rapptz** [comment]
This is kind of a core feature so disabling it isn't going to happen.

Aside from that, the snippet you're linking to is when the type annotations are a string literal which is the Mypy solution to circular imports and the like. Unfortunately if you're still having trouble even considering that then the only thing I can suggest is restructuring your project and fixing it since people already use both mypy and converters without issue that I've seen.

**Comment by nihilistkitten** [comment]
@BeatButton: if I still want converters for some commands which are defined in the same module. `__future__` imports only allow module-level granularity, as I understand it.

@Rapptz: that's the mypy solution to forward-referenced imports, not to circular import trees. The section of the mypy docs I linked explicitly say string literals are not sufficient for circular imports and so `typing.TYPE_CHECKING` is necessary. I understand converters are an important feature, but I'm not sure why an optional flag to disable them adds much complexity -- it seems like they aren't a necessary feature to the functioning of the library of even the commands extension. Regardless, thanks for the fast response.

**Comment by nihilistkitten** [comment]
To clarify, the problem is that the imports need to be behind a `TYPE_CHECKING` flag to avoid import circularity, but (and I think this happens in the snippet I linked) d.py tries to convert them to eval them, which isn't possible at runtime when `TYPE_CHECKING` is off. A solution if you don't want another `command` decorator flag is probably some error handling somewhere near the snippet I linked (for instance, if the eval block raises a name error, then log something and skip running converters for that function).

**Comment by Rapptz** [comment]
> I understand converters are an important feature, but I'm not sure why an optional flag to disable them adds much complexity -- it seems like they aren't a necessary feature to the functioning of the library of even the commands extension

As with all options -- they add complexity where people generally don't expect. For example, increasing support volume for something being disabled when they didn't expect it to be whether one way or another (custom subclass, `command_attrs` being passed, etc.), adding a branch for a feature that 99.99% of people will want to use also slows down the performance even if just a little bit. When adding a new feature there's more to technical debt than just "how many lines of code will this add", and when there's a niche feature request like this the only thing I can really do is reject it -- consider the fact that in the almost 5 years the command extension has existed no one has asked for this except this issue.

**Comment by jack1142** [comment]
> To clarify, the problem is that the imports need to be behind a TYPE_CHECKING flag to avoid import circularity, but (and I think this happens in the snippet I linked) d.py tries to convert them to eval them, which isn't possible at runtime when TYPE_CHECKING is off.

You can just do:
```py
if TYPE_CHECKING:
    from something import THING_FOR_TYPE_HINTING
else:
    THING_FOR_TYPE_HINTING = str
```
And if you do it a lot, putting all such type defs in a separate module seems reasonable.

**Comment by nihilistkitten** [comment]
Oh, great idea, thank you.
