### ISSUE TITLE
Change documentation to be more upfront about what uses cache and make use of API calls in type hints

### ISSUE THREAD

**Issue by asleep-cult** [Rapptz/discord.py#5174]
### The Problem

Cache rarely being mentioned in the documentation creates ambiguity as to what's acceptable in getting discord objects, for example get_user uses cache which requires the user to have a mutual guild with the bot for it to be cached in the first place but nowhere in the documentation is this mentioned. The discord.User type hint also seemingly uses get_user and never fetch_user which means the user must be in in a mutual guild even though it is simply a user and not a member! This can get very confusing at times. 

### The Ideal Solution

The documentation for get could be changed to mention that it uses cache and that a mutual guild is required to use it and the discord.<user/member etc..> type hints could also be changed to make use of fetch (try looking through cache then trying to use fetch) rather than solely depending on cache .

### Summary

Change documentation to be more upfront about what uses cache and make use of API calls in discord.<user/member etc...> type hints when needed

**Comment by numbermaniac** [comment]
For what it's worth, methods were standardised a while ago so that all `get_` methods rely on the cache whereas all `fetch_` methods call the API. Additionally, if `await` appears before a method name in the documentation then that can sometimes indicate that the method relies on an API call.

**Comment by hamza1311** [comment]
Every method that makes an API call with an equivalent to get from cache mentions it as note. Everything that doesn't mention it uses the cache.
Example: 
![image](https://user-images.githubusercontent.com/47357913/89036292-dd7f2680-d355-11ea-973a-fdad1253bdf1.png)
from https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.fetch_guilds

> The discord.User type hint also seemingly uses get_user and never fetch_user which means the user must be in in a mutual guild even though it is simply a user and not a member! This can get very confusing at times.

This is explicitly mentioned in the [docs](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.UserConverter).
![image](https://user-images.githubusercontent.com/47357913/89036719-9cd3dd00-d356-11ea-8562-0221dfb2237a.png)

If you want to fetch the user, the solution to that has always been making your own converter

**Comment by Vexs** [comment]
While the information is there, it's scattered all over the place with no centralized explanation. Considering the importance of the cache, and the recent reasons why things might not be in there, it seems wise to me to add some narrative docs on it.
Remember, documentation isn't just the API doc.

**Comment by Rapptz** [comment]
As far as I'm aware the converters are pretty explicit about their lookup strategy. There are various explanations of the usage of cache in there as well so I'm unsure what more should be needed here. If you feel the documentation is insufficient in explaining whether something uses cache or not you're free to open a PR.
