### ISSUE TITLE
Get github username from discord integration

### ISSUE THREAD

**Issue by ArduinoidIOT** [Rapptz/discord.py#5182]
### The Problem

I'm trying to make a bot that gives a role to someone if they have contributed to a github repo

### The Ideal Solution
Add an integrations attribute to the user/member class

### Summary
Add an option to access all displayed integrations in discord.py

**Comment by Vexs** [comment]
Discord's API does not provide this information to bot accounts, so discord.py cannot provide it.

**Comment by ArduinoidIOT** [comment]
Oh. :disappointed:

**Comment by mouncg** [comment]
@ArduinoidIOT You can use discord oauth2 with the connections option and ge that data iirc.
