### ISSUE TITLE
Command doesn't show

### ISSUE THREAD

**Issue by shantung** [Rapptz/discord.py#519]
idk which one is incorrect, I'm new with coding plz halp

import discord
import asyncio
from discord.ext import commands

class Tester:
    """My custom cog that does stuff!"""

    def __init__(self, bot):
        self.bot = bot

        @commands.command(pass_context=True)
        async def tester(self, ctx):

            author_name = ctx.message.author
            description = ("Short little description with a link to")
            field_name = "Generic Name"
            field_contents = "Example contents for this field"
            footer_text = "Hi. I am a footer text. I look small when displayed."

            embed = discord.Embed(colour=0xFF0000, description=description)
            embed.title = "title test"
            embed.set_author(name=str(author.name), icon_url=author.avatar_url)
            embed.add_field(name=field_name, value=field_contents)
            embed.set_footer(text=footer_text)

            await self.bot.say(embed=embed)
        
def setup(bot):
    bot.add_cog(Tester(bot))

**Comment by NotSoSuper** [comment]
do you actually load the cog/extension in your main bot file?

**Comment by shantung** [comment]
I loaded it, but when I run the command, it shows nothing.

**Comment by nitros12** [comment]
dedent the command block by one level, it's being created inside __init__ and then thrown away, it needs to be in the class definition.

**Comment by shantung** [comment]
still, it could be loaded, but if I type the command, nothing happened

```
import discord
import asyncio
from discord.ext import commands

class Tester:
    """My custom cog that does stuff!"""

    def __init__(self, bot):
        self.bot = bot

    @commands.command(pass_context=True)
    async def tesu(self, ctx):

        author_name = ctx.message.author
        description = ("Short little description with a link to")
        field_name = "Generic Name"
        field_contents = "Example contents for this field"
        footer_text = "Hi. I am a footer text. I look small when displayed."

        embed = discord.Embed(colour=0xFF0000, description=description)
        embed.title = "title test"
        embed.set_author(name=str(author.name), icon_url=author.avatar_url)
        embed.add_field(name=field_name, value=field_contents)
        embed.set_footer(text=footer_text)

        await self.bot.say(embed=embed)
        
def setup(bot):
    bot.add_cog(Tester(bot))
```

**Comment by martmists** [comment]
Could you show a screenshot of what you're typing?

**Comment by nitros12** [comment]
Check your variable names, you declare `author_name` but then proceed to use `author`

**Comment by shantung** [comment]
OMG, I'm much obligated to you. You've saved my life thanks so much!
