### ISSUE TITLE
'ConnectionState' object has no attribute '_ready_state'

### ISSUE THREAD

**Issue by N3evin** [Rapptz/discord.py#5190]
### Summary

Getting this error recently
```
AttributeError: 'ConnectionState' object has no attribute '_ready_state'
  File "discord/state.py", line 358, in _delay_ready
    for guild, unavailable in self._ready_state.guilds:
```

### Reproduction Steps

Running the bot 24/7, does not know how it happened

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information
- Python v3.7.8-final
- discord.py v1.3.4-final
- aiohttp v3.6.2
- websockets v8.1

**Comment by Rapptz** [comment]
Not enough information to work with here. Also doubt this has anything to do with your CPU.

**Comment by N3evin** [comment]
> Not enough information to work with here. Also doubt this has anything to do with your CPU.

sorry, I was just listing it and was working with the correct format. That's weird, it just spikes up after getting error and the server just jam. I had integrated with Sentry.io, I will update again once I got the error.
