### ISSUE TITLE
socket.gaierror: [Errno 11001] getaddrinfo failed

### ISSUE THREAD

**Issue by ashitamo** [Rapptz/discord.py#5191]
### socket.gaierror: [Errno 11001] 
i got this error:

    Task exception was never retrieved
    future: <Task finished coro=<VoiceClient._create_socket() done, defined at D:\Python\lib\site- 
    packages\discord\voice_client.py:172> exception=gaierror(11001, 'getaddrinfo failed')>
    Traceback (most recent call last):
      File "D:\Python\lib\site-packages\discord\voice_client.py", line 192, in _create_socket
        self.endpoint_ip = socket.gethostbyname(self.endpoint)
    socket.gaierror: [Errno 11001] getaddrinfo failed

i find it in './discord/voice_client.py'

    self.endpoint = endpoint.replace(':80', '')
    self.endpoint_ip = socket.gethostbyname(self.endpoint)

change

    self.endpoint = endpoint.replace(':80', '').replace(':443','')
    self.endpoint_ip = socket.gethostbyname(self.endpoint)

it's working

**Comment by Rapptz** [comment]
#5188
