### ISSUE TITLE
RunTime error upon closing connection to Discord.

### ISSUE THREAD

**Issue by parafoxia** [Rapptz/discord.py#5209]
### Summary

On closing the connection to Discord, it sometimes throws a `RuntimeError: Event loop is closed`. From what I've seen, this happens about 90% of the time. I've tested it using CTRL+C to shut the bot down, but not with a shutdown command. (EDIT: A friend gets this same issue using the `logout()` method as explained in a below comment).

### Reproduction Steps

It's happened in a few different scenarios, but this is enough to set it off from what I've seen.
```
async def shutdown(self):
        print(" Closing connection to Discord...")
        await super().close()

async def close(self):
        print("Closing on keyboard interrupt...")
        await self.shutdown()
```

### Expected Results

The bot closes it's connection to Discord. This does sometimes happen perfectly fine.

### Actual Results

This error:
```
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000014D19B61280>
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000014D18E1FC10>
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Program Files\Python38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```
The program does always exit, but I feel like this error isn't supposed to happen, especially as it doesn't occur in versions 1.3.4 and below.

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.8.5-final
- discord.py v1.4.0-final
- aiohttp v3.6.2
- system info: Windows 10 10.0.19041

**Comment by parafoxia** [comment]
I mentioned I hadn't tested this with a shutdown command, but I've had a friend confirm they get the same error using the `logout()` method of the `Bot` object.

**Comment by mikeshardmind** [comment]
https://bugs.python.org/issue39232

It's a Windows + ProactorEventLoop issue, however, switching to the selector loop will have other problems as the loops don't have compatible overlapping interfaces on windows due to deficiencies in selectors support on Windows

**Comment by parafoxia** [comment]
Ah I see. Is there a reason it's a new bug in v1.4? I know `websockets` was replaced with `aiohttp.ws`, but not sure if that would cause an issue like this.

**Comment by Rapptz** [comment]
This is an issue on windows that I cannot reasonably fix. It's best to wait for it to be fixed upstream or ignore it for now.

**Comment by arcosin** [comment]
Anyone find a good hack for this? It is ignored anyways, but anyone know a way to avoid or suppress the output?

**Comment by asarra** [comment]
> 
> 
> Anyone find a good hack for this? It is ignored anyways, but anyone know a way to avoid or suppress the output?

same

**Comment by Kaytuu** [comment]
You can just change the event loop policy:

```py
import platform
if platform.system() == 'Windows':
	asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```
