### ISSUE TITLE
Security issue with discord.py

### ISSUE THREAD

**Issue by ELginas** [Rapptz/discord.py#5215]
### Summary

Using `guild.channels` you get ALL channels, including private ones. So you can get a lot of information in this way. Also, you don't need ANY permissions.

### Reproduction Steps

`guild.channels`

### Expected Results

It should return only channels visible to bot.

### Actual Results

It returns ALL channels, including ones which bot shouldn't have access to.

### Checklist

- [ ] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

Windows, Python 3.7, discord.py 1.3.4

**Comment by Taarek** [comment]
This is not a bug. Discord's API returns this information. And it's only very basic information such as:
 - Channel name
 - Channel type
 - Channel topic (if applicable).

You should talk to Discord if you don't like this. :)
