### ISSUE TITLE
Bot connection closed, bot still appears online

### ISSUE THREAD

**Issue by MaximeHouis** [Rapptz/discord.py#5216]
### Summary

In version `1.4.0`, I couldn't use `await bot.close()` to terminate a Discord connection. Version `1.4.1` fixed this problem (#5207) but the bot still appears online in the member list of a guild after the connection has been closed and the program has been terminated.

### Reproduction Steps

Here is a minimal code I could use to reproduce the bug:
```py
import logging
import asyncio

import discord
from discord.ext import commands

logging.basicConfig(level=logging.INFO)
bot = commands.Bot(command_prefix='>>')

@bot.event
async def on_ready():
    """Close the bot 3 seconds after it's ready, just for the sake of the example."""
    await asyncio.sleep(3)
    await bot.close()

bot.run(TOKEN)
```

### Expected Results

I would expected the bot to appear offline once the `bot.close()` coroutine has been called, as it did in versions `1.3.x`

### Actual Results

The bot stops, function `bot.run(TOKEN)` returns and program closes successfully, but the bot still appears "online" in a guild / in DMs.  
Here are the logs I got with my previous example:
```
INFO:discord.client:logging in using static token
INFO:discord.gateway:Shard ID None has sent the IDENTIFY payload.
INFO:discord.gateway:Shard ID None has connected to Gateway: [...] (Session ID: XXX).
INFO:discord.gateway:Websocket closed with 1000, cannot reconnect.
INFO:discord.client:Cleaning up tasks.
INFO:discord.client:Closing the event loop.
```
*I suppressed output from the 'Shard ID None has connected to Gateway' line as I don't know if that could contain sensible information. I would be glad to share it privately if needed, or make it public if it does not contain sensitive information.*

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

```
- Python v3.8.5-final
- discord.py v1.4.1-final
- aiohttp v3.6.2
- system info: Linux 5.7.11-arch1-1 #1 SMP PREEMPT Wed, 29 Jul 2020 21:38:21 +0000
```

**Comment by Rapptz** [comment]
This isn't really something I can control. It seems that it happens to some people, for example [I cannot reproduce this](https://cdn.discordapp.com/attachments/381965515721146390/741922984817721415/2020-08-09_03-36-41.mp4).

**Comment by hxr404** [comment]
Can reproduce
This happens all the time to my bot. idk why
Windows 10 x64 discord.py newest version from pip
