### ISSUE TITLE
Discord Bot is not working

### ISSUE THREAD

**Issue by Jotohd** [Rapptz/discord.py#5218]
### Checklist

- [ ] I have searched the open issues for duplicates.
- [ ] I have shown the entire traceback, if possible.
- [ ] I have removed my token from display, if visible.

**Comment by helish88** [comment]
LMAO

**Comment by fwrs** [comment]
Can't reproduce 😢

**Comment by vefeyu** [comment]
Can't reproduce, i did all steps correctly. :'c

**Comment by Nereg** [comment]
LMAO get outa here

**Comment by H43X** [comment]
Did you try making a python script?
