### ISSUE TITLE
Discord Bot is not working with PyCharm

### ISSUE THREAD

**Issue by Jotohd** [Rapptz/discord.py#5219]
Obwohl ich PIP installiert habe und 'py -m pip install discord' geschrieben habe sagt mir PyCharm:
Traceback (most recent call last):
  File "C:/Users/***/PyCharm/JotoBot/main.py", line 13, in <module>
    client.run("***")
  File "C:\Users\***\AppData\Roaming\Python\Python38\site-packages\discord\client.py", line 648, in run
    loop = self.loop
AttributeError: 'str' object has no attribute 'loop'

Process finished with exit code 1

**Comment by Jotohd** [comment]
Andere Benutzer haben mir gesagt das ich bei den Python interpreter angucken sollte: Dort fand ich sowohl discord als auch discord.py

**Comment by numbermaniac** [comment]
`py -m pip uninstall discord`
`py -m pip install -U discord.py`

**Comment by Jotohd** [comment]
Thanks for your tip @numbermaniac but it don't helps :(

**Comment by bijij** [comment]
From the exception I would gather you have defined `client` as either `discord.Client` or `commands.Bot` the class rather than an instance of either.

By creating an instance you'll solve the issue you're having.

**Comment by Jotohd** [comment]
hey @bijij thanks for your help. 
can you explain this to me in more detail, since i'm a beginner

**Comment by bijij** [comment]
If you need more help I'd suggest you join the [discord server](https://discord.gg/r3sSKJJ) and ask in one of the the help channels.

**Comment by Jotohd** [comment]
whats your discord-name? @bijij

**Comment by Harmon758** [comment]
As noted, this is likely an issue with your usage of [`discord.Client`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client) and not an issue with discord.py itself, and for further help using the library, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README also links.

For code block usage, see https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks.
