### ISSUE TITLE
When invite deletion is attempted without manage channels permission, a 404 not found is returned

### ISSUE THREAD

**Issue by dob9601** [Rapptz/discord.py#5226]
### Summary

When invite deletion is attempted without manage channels permission, a 404 not found is returned. However, the discord.py docs imply that a 403 should be returned. Unsure as to whether this is:
 - A: An issue with the discord.py docs
 - B: An issue with the Discord api
 - C: An issue with discord.py itself

### Reproduction Steps

Attempt to delete an invite when you do not have the manage channels permission.

### Expected Results

An http 403 error to be returned

### Actual Results

You will find that the error below is returned:
```py
Traceback (most recent call last):
  File "/home/######/.local/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "/home/######/repos/######/bot/core.py", line 117, in on_raw_reaction_add
    await lfg_request.close_request(self.bot)
  File "/home/######/repos/######/bot/models.py", line 86, in close_request
    await invite.delete()
  File "/home/######/.local/lib/python3.8/site-packages/discord/invite.py", line 365, in delete
    await self._state.http.delete_invite(self.code, reason=reason)
  File "/home/######/.local/lib/python3.8/site-packages/discord/http.py", line 223, in request
    raise NotFound(r, data)
discord.errors.NotFound: 404 Not Found (error code: 10006): Unknown Invite
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

```
- Python v3.8.3-final
- discord.py v1.3.4-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Linux 5.6.19-2-MANJARO #1 SMP PREEMPT Wed Jun 17 22:24:52 UTC 2020
```

**Comment by Rapptz** [comment]
The library just propagates the status code from the API.

**Comment by dob9601** [comment]
This still means that there's an issue with the discord.py docs since until discord change something on their end, the statement that a 403 is returned is incorrect (https://discordpy.readthedocs.io/en/latest/api.html#discord.Invite.delete)

**Comment by Rapptz** [comment]
Well the choices here are either:

1. Change the documentation to update the string (pull requests welcome)
2. File an API bug in the [issue tracker](https://github.com/discord/discord-api-docs/issues) to correct what you deem to be broken behaviour.

**Comment by dob9601** [comment]
Reporting back from the discord api issue tracker - supposedly its intended behaviour to prevent brute forcing, which doesn't make the most sense to me since a 403 should just always be returned if the permission is not had imo (https://github.com/discord/discord-api-docs/issues/1903 for the discussion)

Either way, I'll create a PR for the docs at some point soon
