### ISSUE TITLE
Command response shows up multiple times

### ISSUE THREAD

**Issue by josphhh0181** [Rapptz/discord.py#5229]
### Summary

When I enter a command (eg .ping), the bots response shows up multiple times. Sometimes it shows up once, sometimes either 3,5 or 7 times.

### Reproduction Steps

```
@client.command()
async def ping(ctx):
	await ctx.send('Pong')
```

### Expected Results

For the bot to reply with 'Pong' once.

### Actual Results

The bot responds multiple times in multiple messages.

### Checklist

- [x ] I have searched the open issues for duplicates.
- [ x] I have shown the entire traceback, if possible.
- [ x] I have removed my token from display, if visible.

### System Information

- Python v3.8.5-final
- discord.py v1.4.1-final
- aiohttp v3.6.2
- system info: Windows 10 10.0.19041

**Comment by Rapptz** [comment]
You're probably running multiple instances of your bot. Be sure to properly terminate your processes before starting a new one.
