### ISSUE TITLE
AttributeError when importing the "Main" File

### ISSUE THREAD

**Issue by Biskit1943** [Rapptz/discord.py#523]
Everytime I write 'import Main' in my Twitter File I get this Error:
AttributeError: module 'Twitter' has no attribute 'Streamer'
This Error isn't even real! And I get it only if I import my Main Module where the bot runs....

**Comment by Phxntxm** [comment]
This doesn't seem to have anything to do with discord.py? What is this "Main" module that you're trying to import? Show your actual code, if this is related to discord.py at all

**Comment by Biskit1943** [comment]
Here:
https://github.com/Biskit1943/bot/blob/master/Main.py

**Comment by Phxntxm** [comment]
What is this `Twitter` module? I see no overshadowing, so this has to be an issue with either this module, or how you are using it. I wasn't able to find any module that matches being imported as `Twitter` so is this a module of your own?

**Comment by Biskit1943** [comment]
Yes of my own but the Code is alright. They both working alone but when I import Main the Error occors. If you want to see the code anyway here it is:
https://github.com/Biskit1943/bot/blob/master/Twitter.py

I've deleted the Variables so pretend they are there ;)

**Comment by Ikusaba-san** [comment]
From the looks of things it looks like you're doing a circular import.

You have `Main` -- which imports `Twitter`, which imports `Main`. When you import Main it attempts to initialize a thread using `Twitter.Streamer` which wasn't even defined yet.

**Comment by Painezor** [comment]
Off-topic, but Tweepy is blocking. There's an asynchronous library called [peony-twitter](https://github.com/odrling/peony-twitter) though.

**Comment by Biskit1943** [comment]
@Ikusaba-san so how do I solve this?

**Comment by Phxntxm** [comment]
By not circular importing, it seems the only reason you need to access the main module is for `twitter_call`. Put this somewhere else so that you can access it without circular imports

**Comment by Ikusaba-san** [comment]
Rethink your design. Why is your TwitterStreamer class in Main?

**Comment by Biskit1943** [comment]
@Phxntxm I've tried that but I need the Main Module anyway because of my bot... Thanks for the Help I gonna try to redesign
