### ISSUE TITLE
BanEntry class not documanted

### ISSUE THREAD

**Issue by yotam201410** [Rapptz/discord.py#5231]
### The Problem

BanEntry class is not documented in the docs

### The Ideal Solution

adding it to the docs

### The Current Solution

using guild.bans()
then just picking a random user and looking from what the class is made

### Summary

BanEntry class is not documented in the docs
and it should be documented

**Comment by Zomatree** [comment]
duplicate of https://github.com/Rapptz/discord.py/issues/2585
