### ISSUE TITLE
Add a way to get message by id

### ISSUE THREAD

**Issue by ParkerMc** [Rapptz/discord.py#525]
This is more of an enhancement but I would like a way to save and load the message objects if this is some thing you can point me to on how to add that would be great to.

**Comment by fwrs** [comment]
This is already possible. Have you tried searching in the documentation and or asking in the library's discord channel?

**Comment by Eternity71529** [comment]
1: You can use the `Client`'s message cache to get your desired `Message` Object
    -`Client`.message: http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.messages
   and you can just use `discord.utils.get` to get the `Message` Object yourself by iterating through the cache
2: Use `Client`.logs_from and iterate through the list of `Message` Objects : http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.logs_from

**Comment by Gorialis** [comment]
Bot users can obtain messages through [Client.get_message](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.get_message). This takes a channel object, which you can also obtain through [Client.get_channel](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.get_channel). If you are looking for a way to get messages by ID without knowing the channel, you will need to store the messages yourself, as the channel requirement is imposed by the Discord API and not by this library.

**Comment by ParkerMc** [comment]
@fwrs Yes I did look in the docs.
@Eternity71529 `Client.logs_from` should work for me thanks 😄 I guess I missed that.

**Comment by ParkerMc** [comment]
@Gorialis Whoa idk how I missed that sorry for the dumb issue.
