### ISSUE TITLE
create_invite 

### ISSUE THREAD

**Issue by FrozenDude101** [Rapptz/discord.py#529]
When I use create_invite it returns something like this. (The 0x04F569C0 bit changes each run)
<generator object Client.create_invite at 0x04F569C0>

This is the code.

elif message.content.startswith("fb:invite"):

        invite = client.create_invite(destination = message.channel, xkcd = True, max_uses = 1)
        await client.send_message(message.channel, invite)

Is there anyway to make it actually return the Invite object, because mine doesn't.

**Comment by TildeBeta** [comment]
Await create_invite

**Comment by FrozenDude101** [comment]
Oh.
Thanks, I didn't think of that for some reason, I'm such an idiot!
