### ISSUE TITLE
Unset server.owner breaks permission check

### ISSUE THREAD

**Issue by Unknowny** [Rapptz/discord.py#532]
I am checking my permissions on a channel with `channel.permissions_for(server.me)` right after ready event. And it produces: 
```
File "env/lib/python3.6/site-packages/discord/channel.py", line 260, in permissions_for
    if member.id == self.server.owner.id:
AttributeError: 'NoneType' object has no attribute 'id'
```
Right now I have to do `client.request_offline_members()` (even for small ~30 members servers) and `asyncio.sleep(1)` after that to make sure all members are set. This is all on non bot account.

Related to https://github.com/Rapptz/discord.py/issues/431?

**Comment by Rapptz** [comment]
This is fixed in rewrite.
