### ISSUE TITLE
Add a member.user method (rewrite)

### ISSUE THREAD

**Issue by Exahilosys** [Rapptz/discord.py#533]
Shorthand for `Client.get_user(id)`, makes more sense for something like that to be accessible from classes with borderline identical functionality.

**Comment by diceroll123** [comment]
but..

https://github.com/Rapptz/discord.py/blob/async/discord/member.py#L78

**Comment by Rapptz** [comment]
I cannot see the use case considering both `User` and `Member` meet the `abc.User` interface which allows you to use both of them as-if it was a `User`. ergo, this would be indistinguishable in a duck typing scenario.

**Comment by Rapptz** [comment]
Considering `User` and `Member` are comparable again I think this use case has been met differently.
