### ISSUE TITLE
unable to change nickname

### ISSUE THREAD

**Issue by Adam-A** [Rapptz/discord.py#535]
Could someone give me a quick way they would call the "change nickname" function?

change_nickname(membersName, nickNameWanted) 
gives me an error that says "change_nickname" is not defined

Sorry, I'm a noob at this :/

**Comment by Rapptz** [comment]
This isn't a global function. It's a function of a `Client`. You need a `discord.Client` instance and you need to run this function in one of the events of the library. e.g.

```py
# have a client instance:
client = discord.Client()

# somewhere inside an async def:
await client.change_nickname(some_member_obj, new_nickname_string)
```

See the [documentation](http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.change_nickname).

**Comment by Phxntxm** [comment]
Couple issues here, `change_nickname` is a method of your client:
http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.change_nickname

Therefore whatever your `discord.Client` or `commands.Bot` instance is called...you need to call it on that. For example:

```
client = discord.Client()
...
client.change_nickname
```

Second, it is a coroutine, you need to await it: `await client.change_nickname`

Third, I'm going to assume by the name of the variable `membersName` that this is the name of the member you're trying to change. This is not correct, if you check the link I provided above that is a `Member` instance that you want to provide, not a `str`. 

However you want to find that `Member` instance is up to you, if you're trying to find the bot's, try searching the documentation for the server data class, you may find where a `Member` attribute is for the bot. If this is in `on_message` or whatever and you want that author, check the documentation for `Message`...again you may find exactly what you need there.
