### ISSUE TITLE
how to do????

### ISSUE THREAD

**Issue by ScttB** [Rapptz/discord.py#536]
So, say I want to `send_message` to a server.
HOW DO I SPECIFY THE SERVER AND CHANNEL WITHOUT GETTING AN ERROR?!?!

**Comment by Phxntxm** [comment]
http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.get_channel
http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.get_server

Or if you have a message reference and you want the server/channel the message was sent from
http://discordpy.readthedocs.io/en/latest/api.html#discord.Message.channel
http://discordpy.readthedocs.io/en/latest/api.html#discord.Message.server

It's all in the docs.

**Comment by ScttB** [comment]
How do I get an ID?

**Comment by Rapptz** [comment]
For future references, this isn't how you open an issue. Have some sense of professionalism. 

If you want to get help for basic things I suggest going to the help server in https://discord.gg/discord-api

**Comment by ScttB** [comment]
(there should be a easy to understand how-to thing for this library, because I do know moderately well how to use python...)
