### ISSUE TITLE
message.channel not sending file to channel

### ISSUE THREAD

**Issue by DJ-TrainR3k** [Rapptz/discord.py#537]
`@client.command()	#butytho`
`async def butytho(message):`
	`await client.send_file(message.channel, 'fibCEus.gifv')`

I'm trying to send the image in the same channel as the command was issued. I think the fix is obvious but I can't find it.

The error thrown is 
>raise MissingRequiredArgument('{0.name} is a required argument that is missing.'.format(param))
discord.ext.commands.errors.MissingRequiredArgument: message is a required argument that is missing.

**Comment by NotSoSuper** [comment]
as in the docs, file path/object first then the channel
https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.send_file
`await client.send_file('fibCEus.gifv', message.channel)`

**Comment by DJ-TrainR3k** [comment]
It still throws the same error

**Comment by NotSoSuper** [comment]
sorry, I misread (was typing this while ingame), the file must the in the same dir you launched your script
`await client.send_file(message.channel, open('fibCEus.gifv', 'rb'))`
try that

**Comment by Ikusaba-san** [comment]
Your command is expecting a message parameter, which you most likely never gave.

If you want to get the original message, you have to make the command pass the original context. See this link for reference: http://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-get-the-original-message

**Comment by ButterCheezii** [comment]
working code
```py
@client.command(pass_context = True)
async def butytho(ctxmessage):
   await client.send_file(ctx.message.channel, 'fibCEus.gifv')
```
