### ISSUE TITLE
client.get_user_info() not working properly

### ISSUE THREAD

**Issue by helicoptersarecool** [Rapptz/discord.py#538]
In the documentation it says that Client.get_user_info(user_id) should return a User object, but it returns a generator. I have tried using next() on the generator that gets returned but nothing works and everything turns up errors. Thank you

**Comment by TheTrain2000** [comment]
You aren't `await`-ing it.

**Comment by helicoptersarecool** [comment]
Oh, thanks... There goes the last 4 hours of my life
