### ISSUE TITLE
set_role

### ISSUE THREAD

**Issue by SawnFx** [Rapptz/discord.py#540]
Can we set a user's role?
e.g:
`
user.set_role('some_role')
`
ps : sorry for bad english :x

**Comment by Rapptz** [comment]
There's [`Client.replace_roles`](http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.replace_roles) to replace it and [`Client.add_roles`](http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.add_roles) to add roles.
