### ISSUE TITLE
Resume events getting stuck

### ISSUE THREAD

**Issue by jowrjowr** [Rapptz/discord.py#542]
So I had an issue for awhile where a relatively simple discord bot would get "stuck". By "stuck" I mean the TCP sockets would be stuck in CLOSE_WAIT. Like, for days it would be stuck in that state and never getting out of it. Moderately infuriating.

The eventual culprit was found to be this block in gateway.py:

```        try:
            yield from ws.ensure_open()
        except websockets.exceptions.ConnectionClosed:
            # ws got closed so let's just do a regular IDENTIFY connect.
            log.info('RESUME failure.')
            return (yield from cls.from_client(client))
        else:
            return ws
```

After some research I've seen it's hit people in the past, eg: https://bugs.eclipse.org/bugs/show_bug.cgi?id=367433 - the socket states are even the same.

Unfortunately I can't for the life of me figure why the websocket isn't honoring stated timeout values.

So I cut the gordian knot. After ```yield from ws.resume()``` I drop in ```return (yield from cls.from_client(client))``` to force a real reconnect rather than play games waiting for the websocket to do the needful.

It's been working great for about two weeks now.

**Comment by Rapptz** [comment]
Should be fixed with the merging of #503
