### ISSUE TITLE
How to use client.add_reaction ?

### ISSUE THREAD

**Issue by MatCorgi** [Rapptz/discord.py#543]
I have looked in the docs, and everywhere, but i cant get add_reaction to work. In my current status, the code is giving this error "discord.errors.HTTPException: BAD REQUEST (status code: 400) ". Please help me ;3;

**Comment by TheTrain2000** [comment]
You most likely aren't trying to add an emoji. What is your code?

**Comment by MatCorgi** [comment]
elif msw("!addreaction"):
        await client.add_reaction(message.id, "<:lenny:305363712599130112>")
Notes : msw = message.content.startswith

**Comment by MatCorgi** [comment]
i also tried just message instead of message.id

**Comment by Gorialis** [comment]
When passing a custom emoji as text, you use `name:id`.
```py
await client.add_reaction(message.id, "lenny:305363712599130112")
```
If this still doesn't work, your bot doesn't have access to the custom emoji.

**Comment by MatCorgi** [comment]
Still isnt working :/
I just tried :
`await client.add_reaction(message, "wink:305366787204317185")`
and
`await client.add_reaction(message.id, "wink:305366787204317185")`
Neither worked.

**Comment by Gorialis** [comment]
What error are you getting? Is it different from before?

**Comment by MatCorgi** [comment]
`discord.errors.HTTPException: BAD REQUEST (status code: 400): Unknown Emoji`

**Comment by Gorialis** [comment]
Your bot doesn't have access to whatever emoji you are trying to use. Note that custom emoji for servers will only work in their respective servers under most cases, and your bot may not be able to access the emoji you can. You will likely have to use a different emoji for whatever purpose you need reactions for.

**Comment by Eternity71529** [comment]
Use `discord.utils.get()` to get the `Emoji` object and pass it in instead of the string (for custom emojis)
For normal ones just pass the raw emoji. Eg: 👌

**Comment by MatCorgi** [comment]
When giving emojis like `:ok_hand:`, the bot still says its a Unknown Emoji

**Comment by icycodec** [comment]
@MatCorgi You must use the unicode symbol.

**Comment by Gorialis** [comment]
Please [read the FAQ entry on this](http://discordpy.readthedocs.io/en/latest/faq.html#how-can-i-add-a-reaction-to-a-message) because it answers many of your questions surrounding `add_reaction`.

**Comment by MatCorgi** [comment]
Well so i have to get some better editor since when i paste a unicode symbol on idle, it crashes.

**Comment by MatCorgi** [comment]
![image](https://cloud.githubusercontent.com/assets/26722564/25306006/c6d04102-275b-11e7-9875-7412912105c7.png)
finally
