### ISSUE TITLE
Retrieve images

### ISSUE THREAD

**Issue by The-Penultimate-Defenestrator** [Rapptz/discord.py#55]
From a quick code and documentation search, there's no functionality for handling images sent, or sending images. Would this be hard to implement? There doesn't even seem to be functionality for downloading raw image data as a string. At least this functionality would be helpful, because:

```python
import discord
from PIL import Image
from StringIO import StringIO

client = discord.Client()
client.login('user','password')

def on_message(message):
    buff = StringIO()
    buff.write(message.content)
    try:
        im = Image.open(buff)
        isImage=True
    except:
        text = message.content
        isImage=False
    if isImage:
        im.save("img.jpg")
    else:
        print text
```
Setting it up like this would be an easy way to download images. Uploading images might work similarly.

**Comment by Rapptz** [comment]
Sending files is supported via `send_file`.

Getting files is your own thing. You can look at `message.embeds` or `message.attachments` and extract the images with an HTTP request if you want.

**Comment by The-Penultimate-Defenestrator** [comment]
Thanks. I'll look into it

**Comment by Izorr** [comment]
hey how to extract the image, what http request to use

**Comment by FireFeathers06** [comment]
HTTP request is raising HTTP error

**Comment by arifali123** [comment]
How to get the url of image

**Comment by TheRockettek** [comment]
attachment.url or attachment.proxy_url
