### ISSUE TITLE
How does one add categories?

### ISSUE THREAD

**Issue by Kosti1** [Rapptz/discord.py#551]

**Comment by Pandentia** [comment]
Simple questions like this should really be asked in the python_discord-py channel of the [Discord API server](https://discord.gg/discord-api). To answer your question however, you should have a look at how [cogs](https://gist.github.com/leovoel/46cd89ed6a8f41fd09c5) work.

**Comment by Cyrogen** [comment]
The different categories are just different ".py" files with names

**Comment by Pandentia** [comment]
Actually, they're the names of the classes in those files.

**Comment by Cyrogen** [comment]
Okay... also check my latest issue... :(
