### ISSUE TITLE
Nitro and Boost Flags on discord

### ISSUE THREAD

**Issue by Jovantri10** [Rapptz/discord.py#5556]
now the flags on discord.py just "brilliance, bravery, balance, staff, partner, etc...", well pls add the flags for nitro user and boost, thank you

**Comment by Phxntxm** [comment]
The library supports the flags that the API exposes... which can be seen here: https://discord.com/developers/docs/resources/user#user-object-user-flags

Nitro is not an exposed flag

**Comment by Jovantri10** [comment]
well, when am try :
`ctx.author.premium_type` as docs, isnt working

**Comment by Jefffrey** [comment]
Docs don't say that anywhere, not for `ctx.author`. `premium_type` is a field of `ClientUser`. This is different from User/Member. https://discordpy.readthedocs.io/en/latest/api.html?highlight=premium_type#discord.ClientUser.premium_type

**Comment by Jovantri10** [comment]
Well how to use, give example pls :/
i need that to add on my userinfo commands :/

**Comment by Phxntxm** [comment]
As my response explained, you can't, this is not information that the discord API exposes... therefore this is not information this library exposes. The `ClientUser` object is the representation of your client's user, the one you are logged in with... AKA your bot.

The only possible way that you can get information on this at the moment is if they have boosted a server that your bot can see, you can then check the member object in that guild: `if member.premium_since:`

**Comment by Jovantri10** [comment]
Oh okay, tysm to help me💕 💯

**Comment by cheesycod** [comment]
It is also possible to just get their badge
