### ISSUE TITLE
Can't use client.send_message with return from client.get_channel

### ISSUE THREAD

**Issue by daevski** [Rapptz/discord.py#556]
I appear to be using [Client.get_channel](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.get_channel) successfully, but then when calling [Client.send_message](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.send_message) something does wrong and I can't figure out what exactly is the problem.

Additional note: I am using send_message from the [Quick Example](https://github.com/Rapptz/discord.py#quick-example) perfectly fine.

 `¯\_(ツ)_/¯`

![sendmessage_exception](https://cloud.githubusercontent.com/assets/1388502/25761008/3e08b34e-31a7-11e7-9d1c-0d56614bf71d.png)

**Comment by Rapptz** [comment]
You are pointing at the wrong problem.

You're mixing threading and asyncio based on your traceback. In order to run a coroutine in a separate thread you have to use `asyncio.run_coroutine_threadsafe`.

**Comment by daevski** [comment]
Okay, thank you. I will read up on that and give it a try. I'll post the result here as well.

**Comment by Rapptz** [comment]
Feel free to reopen this if the issue persists. For now I'm going to close it.
