### ISSUE TITLE
How to get a specific message without id

### ISSUE THREAD

**Issue by SawnFx** [Rapptz/discord.py#557]
Hellow,
All is in the title
like the client.get_message but without the message id (or a fonction to have the message id? :3)
e.g:
https://files.sawnfx.com/i/1920644242
(The bottom message)
Thanks for your help :D
Btw, sorry for bad english :/

**Comment by LaaZa** [comment]
Try discord.utils.get(client.messages, content='the message I want', author=member_obj)
https://discordpy.readthedocs.io/en/latest/api.html#utility-functions

**Comment by Phxntxm** [comment]
Based on the image you provided there's two different types of messages you may want:

1) The message sent from the author..in which case you want this:
http://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-get-the-original-message
2) The message the bot sends, in which case using `send_message` or `bot.say` returns the message sent, so you can do this:

```
msg = await bot.say("Whatever")
# Now you have the `Message` object that the bot sent, do what you want with it
```
