### ISSUE TITLE
Client.get_server(id) returning NoneType

### ISSUE THREAD

**Issue by Jyurei** [Rapptz/discord.py#559]
I've read the discord.py documentation and I understand that the get_server function returns a NoneType when it's not able to find a server with the specific ID. I'm getting this issue and I don't understand why.
I'm using a bot in only one server. I need to use this function because I need a list of all members in that server. The way I'm using it is like this:
`client = discord.Client()
server = client.get_server('263361699145449474')

file = open('memberlist.txt','r+') #this is a list with all userID's
usernames = file.readlines()
memberlist;
for i in range(len(usernames)):
	memberlist[i] = server.get_member(usernames[i])`

I get an error of "NoneType has no attribute 'get_member'.", referring to the last line. I would like to understand what's wrong. Thanks in advance :)

**Comment by Jyurei** [comment]
Also, I've done a test and asked for the bot to print the server ID itself using a for loop and the Client.servers function. The ID is the exact same.

**Comment by Rapptz** [comment]
Since you have not logged on to Discord (you merely created a client), the cache is not ready to be used. The event that signifies this is [`on_ready`](http://discordpy.rtfd.io/en/latest/api.html#discord.on_ready). Do your retrieval there.

**Comment by Jyurei** [comment]
Thank you for your help! I wouldn't have figured this out by myself.
