### ISSUE TITLE
Removing a role from a Member does not remove it internally, causing an immediately subsequent call to add_role to add the role back

### ISSUE THREAD

**Issue by smmalis37** [Rapptz/discord.py#56]
I have a function that my bot provides that is designed to replace a role on a user with a different one. If I call remove_roles to remove the old role, then immediately call add_roles to add the new one, the end result is that the user now has both roles applied. I would expect that the user would only have the new role after this. My current workaround is to edit member.roles myself to remove the old role from that before calling add_roles.

**Comment by Rapptz** [comment]
Fixed.
