### ISSUE TITLE
No module named websockets

### ISSUE THREAD

**Issue by NoahLiedFilmSchool** [Rapptz/discord.py#560]
When i try to use the bot on a raspberry pi it gives the following error:

```
Traceback (most recent call last):
  File "BOT.py", line 2, in <module>
    import discord
  File "/home/pi/Desktop/NoahsClanBot/discord/__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "/home/pi/Desktop/NoahsClanBot/discord/client.py", line 42, in <module>
    from .voice_client import VoiceClient
  File "/home/pi/Desktop/NoahsClanBot/discord/voice_client.py", line 43, in <module>
    import websockets
ImportError: No module named 'websockets'
```

**Comment by PapyrusThePlant** [comment]
1. Delete that discord folder
2. [Install discord.py properly](https://github.com/Rapptz/discord.py#installing)
3. ????
4. Profit

**Comment by papydeath95** [comment]
```
Please note that on Linux installing voice you must install the following packages via your favourite package manager (e.g. apt, yum, etc) before running the above command:

libffi-dev (or libffi-devel on some systems)
python-dev (e.g. python3.5-dev for Python 3.5)
```

**Comment by NoahLiedFilmSchool** [comment]
I dont have voice

**Comment by Rapptz** [comment]
You don't install the library by putting it in the same folder in your bot. You must use `pip` or `setup.py`.

**Comment by pvvuuren** [comment]
@PapyrusThePlant how do properly install discord.py to Github?

The link you provided seems to install it locally on my pc like this 
'C:\Users\User2\AppData\Local\Programs\Python\Python36-32\Lib\site-packages\discord'

That does not help me to get it on Github (I manually copied the folder onto Github), but I get the following error on Heroku : ModuleNotFoundError: No module named 'websockets'

**Comment by nitros12** [comment]
Dont copy the library folder, read this: https://devcenter.heroku.com/articles/python-pip
