### ISSUE TITLE
attachment://example_file.png fails on rewrite

### ISSUE THREAD

**Issue by mdiller** [Rapptz/discord.py#567]
There is a problem with using the `_` character when specifying an image attachment as an embed image. This is reproducible via the following example

This works:
```
e = discord.Embed().set_image(url='attachment://examplefile.png')
await ctx.send(embed=e, file=discord.File('test.png', 'examplefile.png'))
```
This does not work:
```
e = discord.Embed().set_image(url='attachment://example_file.png')
await ctx.send(embed=e, file=discord.File('test.png', 'example_file.png'))
```

**Comment by Rapptz** [comment]
According to Discord, they don't support filenames with underscores so this won't be fixed.
