### ISSUE TITLE
Can't access cog class fields when check is called from help formatter

### ISSUE THREAD

**Issue by quvide** [Rapptz/discord.py#571]
This results from the help command's context preventing the use of `ctx.cog`.

Here's a minimal example that demostrates the issue. When the help formatter is called, ctx.cog is None so an exception is thrown. It would be nice to have a way to access the "original" cog. I checked the rewrite branch too and there didn't seem to be a way to do this yet.

(Also possible feature request: cog-wide checks)

```
from discord.ext import commands

def is_authorized():
    def predicate(ctx):
        return ctx.message.author.id in ctx.cog.admin_user_ids:

    return commands.check(predicate)

class Admin:
    """
    Commands available for admins only
    """

    def __init__(self, bot, admin_user_ids):
        self.bot = bot
        self.admin_user_ids = admin_user_ids

    @commands.command()
    @is_authorized()
    async def hey(self):
        await self.bot.reply("Hey!")

```
```
Traceback (most recent call last):
  File "venv/lib/python3.6/site-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "venv/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 102, in _default_help_command
    pages = bot.formatter.format_help_for(ctx, bot)
  File "venv/lib/python3.6/site-packages/discord/ext/commands/formatter.py", line 291, in format_help_for
    return self.format()
  File "venv/lib/python3.6/site-packages/discord/ext/commands/formatter.py", line 336, in format
    data = sorted(self.filter_command_list(), key=category)
  File "venv/lib/python3.6/site-packages/discord/ext/commands/formatter.py", line 255, in predicate
    return cmd.can_run(self.context) and self.context.bot.can_run(self.context)
  File "venv/lib/python3.6/site-packages/discord/ext/commands/core.py", line 438, in can_run
    return all(predicate(context) for predicate in predicates)
  File "venv/lib/python3.6/site-packages/discord/ext/commands/core.py", line 438, in <genexpr>
    return all(predicate(context) for predicate in predicates)
  File "app/admin.py", line 12, in predicate
    if ctx.message.author.id in ctx.cog.admin_user_ids:
AttributeError: 'NoneType' object has no attribute 'admin_user_ids'
```

**Comment by Phxntxm** [comment]
I don't know if ctx.bot exists on async, but rewrite it does:

```
ctx.bot.get_cog(ctx.command.cog_name)
```
You can get your cog this way

**Comment by Phxntxm** [comment]
I can't think of a way to do what you want. What you should do though is change where your `admin_user_ids` is saved; this should be something in a config file or something where you can access it wherever you need (which is your direct issue, you cannot access what you need).

**Comment by quvide** [comment]
@Phxntxm `ctx.command.cog_name` is None too when invoked from the help formatter. It feels dumb to use global configuration when you are using classes...

**Comment by SunDwarf** [comment]
Rewrite has cog-specific checks.

**Comment by Phxntxm** [comment]
Configuration for your bot shouldn't be in a specific cog's class, that makes no sense. Configuration is something that should be global, it's just illogical to go about this the way you are. There are surely ways to do it, but the issue here imo is the way you have your configuration setup.

Just think about it, why in the world would you have "the user's who are admins" saved in a cog's class? It is not relevant to that cog specifically, what happens when you later want to have something have the same check in a different class? It's completely viable. Configuration should be moved elsewhere

**Comment by quvide** [comment]
@Phxntxm Thanks for the suggestion. I changed my approach to handling the bot's configuration. I'm not sure though if this kind of functionality could be required for some kind of other scenario. I'll close the issue elsewise.
