### ISSUE TITLE
VoiceChannel.members sometimes returns incorrect amount

### ISSUE THREAD

**Issue by Brian-van-Rheenen** [Rapptz/discord.py#5739]
# Summary

I have this command to retrieve an empty voicechannel, but sometimes it will retrieve a voicechannel that is already filled with people. I have a simple if statement to check the members in that voicechannel `if len(channel.members) == 0` and apparently it goes through that statement even though there are people in that voicechannel.
VoiceChannel.members sometimes returns 0, while members are in that channel

### Reproduction Steps

```python
@commands.command(aliases=['vc'])
    async def voicechannel(self, ctx):
        channels = (c for c in self.guild.channels if c.type==ChannelType.voice)
        for channel in channels:
            if "Boost" in channel.name:
                if len(channel.members) == 0:
                    link = await channel.create_invite(max_age = 300)
                    msg = f"One empty voice channel as requested: **{channel.name}**\n{link}"
                    await ctx.message.channel.send(msg)
                    return

        await ctx.message.channel.send("All voice channels are occupied at the moment.")
```

### Expected Results

The actual amount of members in that voicechannel

### Actual Results

Most of the time it retrieves the correct amount, but sometimes it gives me incorrect amounts.

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.8.2-final
- discord.py v1.4.1-final
- aiohttp v3.6.2
- system info: Windows 10 10.0.18362

**Comment by Rapptz** [comment]
If the member cache gets stale then this will happen. There are various reasons why this happens which is why 1.3 introduced [`VoiceChannel.voice_states`](https://discordpy.readthedocs.io/en/latest/api.html#discord.VoiceChannel.voice_states) which bypasses the member cache. Try verifying that the information is correct there.

**Comment by Brian-van-Rheenen** [comment]
I noticed a similar issue with the members cache getting stale. After some time [`get_member`](https://discordpy.readthedocs.io/en/latest/api.html?highlight=get_member#discord.Guild.get_member) returned a `'NoneType' object` when trying to retrieve the nickname. And again, a restart fixed the issue, just like the voicechannels.
`Command raised an exception: AttributeError: 'NoneType' object has no attribute 'nick'`

If it might be of use, the Discord server that my bot is in contains 4626 members.
Does anyone know how to counter this problem?

**Comment by Brian-van-Rheenen** [comment]
I have fixed the problem. I wasn't using the guild from the given context, instead I used the guild which I initialized on startup and never updated, so my guess is that I was using outdated guild information when retrieving things like channels and nicknames.
