### ISSUE TITLE
Add multiple reactions at once

### ISSUE THREAD

**Issue by astariul** [Rapptz/discord.py#5740]
### The Problem

I'm the author of [`discord_interactive_help`](https://github.com/astariul/discord_interactive_help), a tiny library which add interactivity between the user and your bot, through reactions.

Basically we display a message with several reactions, and by reacting, the user can make some choice.

So the point is : **I need to display a message with several reactions.** 

And the problem is : **Since reactions should be added one by one through the [`add_reaction()`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Message.add_reaction) method, it takes quite some time to display all the reactions under the message.**

### The Ideal Solution

Ideally, we can specify a list of reactions to display when calling the [`send()`](https://discordpy.readthedocs.io/en/latest/api.html#discord.DMChannel.send) function, so we have only one call to do.

_Now, I understand it does not really make sense to add reactions when sending a message._

**Another good solution would be to allow a list of reactions in the ['add_reaction()'](https://discordpy.readthedocs.io/en/latest/api.html#discord.Message.add_reaction) method.**

### The Current Solution

Current solution is to call the ['add_reaction()'](https://discordpy.readthedocs.io/en/latest/api.html#discord.Message.add_reaction) method once per reaction, which takes some time and does not feel smooth on the user side.

### Summary

**Make the ['add_reaction()'](https://discordpy.readthedocs.io/en/latest/api.html#discord.Message.add_reaction) method accept a list of reactions.**

**Comment by AbstractUmbra** [comment]
The reason that `add_reaction()` only supports a single reaction per call is because that is what the API supports.

You cannot add more than one reaction per time within the discord client, for instance.

This will also impact ratelimits and the handling of them, among other reasons.

**Comment by astariul** [comment]
Thanks for the fast answer !
