### ISSUE TITLE
Arch linux inssue

### ISSUE THREAD

**Issue by FartOnCats** [Rapptz/discord.py#575]
"Collecting install
Could not find a version that satisfies the requirement install (from versions: )
No matching distribution found for install"
I receive this error when trying to install on arch linux

**Comment by TheDevFreak** [comment]
What did you run to isntall it, that would help.

**Comment by Rapptz** [comment]
This is missing information.

1) You haven't detailed how you attempted to install.
2) You're not giving a full error traceback.
3) You haven't made it clear what interpreter you used.

etc.

Elaborate on your issue or it's impossible to aid you.
