### ISSUE TITLE
Add a method to access the "message_reference" object on messages

### ISSUE THREAD

**Issue by GamingGeek** [Rapptz/discord.py#5754]
### The Problem

Currently when a message is pinned, you have no way of knowing what message was pinned. Discord sends a [message_reference](https://discord.com/developers/docs/resources/channel#message-object-message-reference-structure) object on the "User pinned a message to this channel" messages and also for crossposted messages either denoting the message that was pinned or the original message that was crossposted.

### The Ideal Solution

Ideally, messages could have a "reference" attribute that would allow you to access the data provided in the message_reference object, either allowing access to the id itself or the object linked to that id if possible (e.g. if the bot is in the guild and has access to the channel or if the pinned/original message is cached)

### The Current Solution

There is no good solution to this at the moment.

### Summary

Add a way to access a message's reference object :)

**Comment by apple502j** [comment]
FYI, `on_message_edit` triggers on message pin/unpin according to docs

**Comment by GamingGeek** [comment]
> FYI, `on_message_edit` triggers on message pin/unpin according to docs

oh I forgot about that but it'd still be nice to have

**Comment by hamza1311** [comment]
[`Message.type`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Message.type) is [`pins_add`](https://discordpy.readthedocs.io/en/latest/api.html#discord.MessageType.pins_add) when a message saying that a message was pinned to a channel so you can check for it in `on_message`. Also, like @apple502j mentioned, `on_message_edit` also triggers on pins updates. Both of these events give you message object which has all the fields that the `message_reference` provides (`message_id`, `channel_id` and `guild_id`)

**Comment by Phxntxm** [comment]
> [`Message.type`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Message.type) is [`pins_add`](https://discordpy.readthedocs.io/en/latest/api.html#discord.MessageType.pins_add) when a message saying that a message was pinned to a channel so you can check for it in `on_message`. Also, like @apple502j mentioned, `on_message_edit` also triggers on pins updates. Both of these events give you message object which has all the fields that the `message_reference` provides (`message_id`, `channel_id` and `guild_id`)

This isn't what's being asked though. He is asking for the `message_reference` information to be provided on a `Message` object just like is [documented here](https://discord.com/developers/docs/resources/channel#message-object-message-structure). This is a perfectly valid ask to me
