### ISSUE TITLE
Add to Message.reply

### ISSUE THREAD

**Issue by iNaruse** [Rapptz/discord.py#5759]
### The Problem

We used to use | await message.channel.send (f"{message.author.ment}, message").
When you add REPLY, await message.reply("HELLO") -> @SADZ#0000 HELLO
(Translator)

### The Ideal Solution

I was writing Discord.js and came over to Discord.py.
It's more functional and more relaxing than DIscord.js.
But it was a bit disappointing because there was no replay function. If you add this function, it will make it easier to make examples like ping pong with one await message.reply.
(Translator)
### The Current Solution

await message.channel.send(f"{message.author.mention}, HELLO")
### Summary

Send a reply to the person who entered the command.
@INIRU#0001, HELLO | Like this.
(Translator)

**Comment by Rapptz** [comment]
Trivial helpers like these don't really gain you much, likewise this functionality conflicts with the actual discord reply feature coming soon.
