### ISSUE TITLE
How to do a command that uses exec() ?

### ISSUE THREAD

**Issue by MatCorgi** [Rapptz/discord.py#576]
How do you use exec() inside a command? The only example i found is one that uses command extension, but i'm using just pure discordpy.

**Comment by Rapptz** [comment]
There's nothing inherent about commands extension that makes `exec` work differently.

Adapt the example for your needs and don't blindly copy paste and it's the same concept.

e.g. [here](https://github.com/Rapptz/RoboDanny/blob/a1d008a74ffcc02a93a2fb3c41ccc2bc2435365a/cogs/repl.py#L31-L75)
