### ISSUE TITLE
RuntimeError when calling logout or close

### ISSUE THREAD

**Issue by psidex** [Rapptz/discord.py#5770]
### Summary

When calling `client.logout` or `client.close`, the bot stops, but a `RuntimeError` is raised

### Reproduction Steps

```python
import discord

class testClient(discord.Client):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    async def on_ready(self):
        print("Ready")

    async def on_message(self, msg):
        if msg.author.bot:
            pass

        elif msg.content.startswith("s"):
            await self.logout()


client = testClient()
client.run("token")
```

Run this with your token and then send the bot the message "s".

### Expected Results

The bot would log off from discord, the script would stop executing, and nothing else would be output.

### Actual Results

```
PS C:\Users\Simon\Desktop> python .\test.py
Ready
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001ECC2E89940>
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Program Files\Python38\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 711, in call_soon
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 504, in _check_closed
RuntimeError: Event loop is closed
```

After this the bot is logged off and the script stops.

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.8.0-final
- discord.py v1.4.1-final
- aiohttp v3.6.2
- system info: Windows 10 10.0.19041

**Comment by Taarek** [comment]
This is an issue with Python3.8 on Windows see https://github.com/Rapptz/discord.py/issues/5209.

**Comment by psidex** [comment]
Ah ok my bad, I'll close this since it's essentially a duplicate of that
