### ISSUE TITLE
CategoryChannel potentially has broken attributes

### ISSUE THREAD

**Issue by parafoxia** [Rapptz/discord.py#5774]
### Summary

This is more a question rather than a bug report, as I'm not sure if there are instances that make these attributes valid. If there are, it'd be cool to know!

I'm making a `channelinfo` command that can return information on categories, and added an invites field, before getting a HTTPException. Exceptions of this nature are in the documentation, but I'm thinking - are there actually any instances where this **wouldn't** return a HTTPException? As far as I know, it's not possible to create invites for category channels.

There are other attributes and methods I have similar questions about too:
- `is_nsfw()`, as I don't believe it's possible to set categories as NSFW
- `category`, as surely this would always return `None`
- `create_invite()` as eluded to above
- `invites()` - ditto
- `permissions_synced`, as there would be no category, and would always return False

I could see some being there to account for a potential edge case of calling them on an object that could be any type of channel depending on the context, but really not sure how the invites would work.

### Reproduction Steps

Just doing `await channel.invites()` was enough to throw the HTTPException.

### Expected Results

It returns an integer or some sort (or if it's there for edge casing, `None` perhaps).

### Actual Results

`discord.errors.NotFound: 404 Not Found (error code: 10003): Unknown Channel`

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.8.5-final
- discord.py v1.4.1-final
- aiohttp v3.6.2
- system info: Windows 10 10.0.19041

**Comment by Rapptz** [comment]
Generally speaking if an HTTP request fails then you get an HTTPException, yes. Some things aren't available in the Discord API and thus the request would fail -- invites in a category is one such concept. The library uses interfaces to allow for common operations to work within a group of objects, in this case `invites()` comes from `abc.GuildChannel` which works for other types of channels just not `CategoryChannel` but special casing this would break inheritance when the alternative is much more clearer than an AttributeError (i.e. an HTTPException).

**Comment by parafoxia** [comment]
Ah, I see, that does make sense yeah.

Some potential changes could look like:
- Returning `0` for the `CategoryChannel.invites()`
- Creating an invite for the first channel in a category for `CategoryChannel.create_invite()`

On the one hand, they do serve to avoid errors, but on the other, it could lead to behaviour that could be seen as confusing or misleading. I guess there isn't really a perfect solution lmao.

**Comment by Rapptz** [comment]
Returning 0 for CategoryChannel.invites is nonsensical and a breaking change. The implementation for all of this is staying as-is.

**Comment by parafoxia** [comment]
Fair enough. Thanks for clearing this up for me though!
