### ISSUE TITLE
discord.PartialEmoji key is not supported in the dictionary with keys discord.Emoji

### ISSUE THREAD

**Issue by NESTOWL** [Rapptz/discord.py#5777]
### The Problem
```
exempl = {
    self.bot.get_emoji(12345): [1, 2, 3],
    self.bot.get_emoji(12345): [1, 2, 3],
    self.bot.get_emoji(12345): [1, 2, 3],
}
<. . .>
@commands.Cog.listener()
async def on_raw_reaction_remove(self, payload):
    hueta = exempl[payload.emoji]
```
i made a dict where the keys discord.Emoji
And I cannot access these keys using the discord.PartialEmoji
```
Traceback (most recent call last):
  File "C:\_DOSCORD_BOT_NESTOWL_\code\cogs\test\events.py", line 396, in on_raw_reaction_add
    hueta = exempl[payload.emoji]
KeyError: <PartialEmoji animated=False name='name' id=728534408646230017>
```
### The Ideal Solution
```
exempl = {
    self.bot.get_emoji(12345): [1, 2, 3],
    self.bot.get_emoji(12345): [1, 2, 3],
    self.bot.get_emoji(12345): [1, 2, 3],
}
<. . .>
@commands.Cog.listener()
async def on_raw_reaction_remove(self, payload):
    hueta = exempl[payload.emoji]
```
### The Current Solution
```
exempl = {
    self.bot.get_emoji(12345): [1, 2, 3],
    self.bot.get_emoji(12345): [1, 2, 3],
    self.bot.get_emoji(12345): [1, 2, 3],
}
<. . .>
@commands.Cog.listener()
async def on_raw_reaction_remove(self, payload):
    for key, value in exempl.items():
        if key == payload.emoji:
            hueta = value
```

### Summary
[1413](https://github.com/Rapptz/discord.py/issues/1413) one can only compare discord.Emoji and discord.PartialEmoji

it would be great if you could use discord.ParticalEmoji as a key in a dictionary where the keys discord.Emoji

If I did something wrong, I apologize, this is the first time I do it, and I also don't know English well (

**Comment by parafoxia** [comment]
It might be better to use the emoji's name or ID as the key in this scenario. I can't really think of an easy way to do it using the objects, as Emoji and PartialEmoji are not the same thing, and their use cases are different.

**Comment by NESTOWL** [comment]
@parafoxia maybe you're right
I will do as I wrote above, compare in a loop
or I'll rewrite it for keys with id emoji, but then I will have to rewrite a lot of code ...

The option with objects would be really not bad, there would be clean readable code without crutches!

**Comment by Rapptz** [comment]
They're distinct objects with different hashes so can't be used as keys -- this is a good thing and is what someone should expect a hashing container to be like.

**Comment by NESTOWL** [comment]
@Rapptz thanks for the answer!

What about the discord.Partial Emoji class convector in discord.Emoji?

```
def convert_PartialEmoji(partialemoj):
    pass
	# here create a discord.Emoji object based on discord.Partial Emoji so that it is valid for comparison

exempl = {
    self.bot.get_emoji(123): [1, 2, 3],
    self.bot.get_emoji(123): [1, 2, 3]
}
<. . .>
@commands.Cog.listener()
async def on_raw_reaction_remove(self, payload):
    hueta = exempl[convert_PartialEmoji(payload.emoji)]
```

should i write my own conversion function
I sketched an example like this, how good would such a solution be?

**Comment by NESTOWL** [comment]
@Rapptz Yeah, thanks, I ran tests, it works, you can store the keys in the form discord.PartialEmoji and then there will be no problems!
![Discord_yB7IMyixaK](https://user-images.githubusercontent.com/45520187/91839064-1b25e680-ec57-11ea-90d6-61d1ed4c9671.png)
