### ISSUE TITLE
Banning using await guild.ban doesn't work

### ISSUE THREAD

**Issue by MySixSenses** [Rapptz/discord.py#5779]
### Summary

Using await ctx.guild.ban(user, reason = "placeholder") doesn't work
### Reproduction Steps

```
@client.command()
async def ban(ctx, member: discord.Member, *, reason = None):
    if ctx.author.guild_permissions.ban_members:
        if ctx.author != member:
            print("Banning")
            await ctx.guild.ban(member, reason = reason + "provided by" + ctx.author)
            await ctx.send(f'{member.mention} has been banned')
        else:
            await ctx.send("Why would you ban yourself? \n I can't let you do that")
    else: 
        await ctx.send("Looks like you don't have the proper permissions to ban people. Contact the server owner if you think this is an error")
@ban.error
async def ban_error(ctx, error):
    if isinstance(error, discord.ext.commands.errors.BadArgument):
        await ctx.send("You swing your great ban hammer, but alas, you forgot to aim it at someone")
```
When the user does %ban, the bot doesn't respond. The debug print prints without error.
### Expected Results
For the user to be banned?

### Actual Results

The command line prints "Banning" but doesn't send the banned message or ban the user. No traceback either.

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information
- Python v3.8.3-final
- discord.py v1.3.4-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Windows 10 10.0.19041

**Comment by Zomatree** [comment]
Your command error handler is stopping errors from being displayed, if you disable it you should get an error because you cannot add a Member and string together (`reason + "provided by" + ctx.author`)
