### ISSUE TITLE
Invoking a command inside a command without knowing the parameters in discord.py

### ISSUE THREAD

**Issue by SHREESHMAN** [Rapptz/discord.py#5784]
When I need to invoke a command in discord.py rewrite i need to pass the argument it takes equal to a value

like for invoking the command **!say** with argument '**hi**' (i.e, !say hi)

```py
@commands.command()
async def say(self, ctx, msg):
   await ctx.send(msg)
```
i need the **parameter** "msg"

```py
@commands.command()
async def inv(self, ctx):
   await ctx.invoke(self.bot.get_command('say'),msg='hi')
```

but im trying to make a general invoke-command
i know how to get the name of the command so i just need to know how do i get the **arguments** required by the command and how can i use it inside **invoke**

```py
@commands.command()
async def playtest(self, ctx):
   await ctx.invoke(self.bot.get_command('nameofcommand'),<parameter>='hi')
```

even using **variables** here will just not work
```py
x = 'msg'
@commands.command()
async def inv(self, ctx):
   await ctx.invoke(self.bot.get_command('say'),x = 'hi')
```

**Comment by Gobot1234** [comment]
This is not an issue with discord.py.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.
## For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.
