### ISSUE TITLE
Self.bot.emojis returns None inside a cog command

### ISSUE THREAD

**Issue by BennehR** [Rapptz/discord.py#5788]
### Summary

Unable to retrieve any emoji data from self.bot inside of a cog, self.bot.emojis returns a lists of None

### Reproduction Steps

The bare bones of the code to cause this:
```
class LaunchLibrary(commands.Cog, name="Launch Library"):
    def __init__(self, bot):
        self.bot = bot
    
    @commands.command()
    async def launches(self, ctx):
        response = await ctx.send("Getting launches...")

        EmojiList = self.bot.emojis
        print(EmojiList)

def setup(bot):
    bot.add_cog(LaunchLibrary(bot))
```

This simply returns []
I have also tried these:
```
            emoji1 = self.bot.get_emoji('one')
            emoji2 = discord.utils.get(self.bot.emojis, name='two')
```
With the same result, both returning None

I tried to use strings and it doesnt accept those, when i tried to use unicode i received unicode errors from python

### Expected Results

Emoji objects to be returned

### Actual Results

```
Ignoring exception in command launches:
Traceback (most recent call last):
  File "[File Path]/lib/python3.6/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "[File Path]/cogs/LaunchLibrary.py", line 288, in launches
    await response.add_reaction(emoji1)
  File "[File Path]/lib/python3.6/site-packages/discord/message.py", line 952, in add_reaction
    emoji = self._emoji_reaction(emoji)
  File "[File Path]/lib/python3.6/site-packages/discord/message.py", line 1039, in _emoji_reaction
    raise InvalidArgument('emoji argument must be str, Emoji, or Reaction not {.__class__.__name__}.'.format(emoji))
discord.errors.InvalidArgument: emoji argument must be str, Emoji, or Reaction not NoneType.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "[File Path]/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "[File Path]/lib/python3.6/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "[File Path]/lib/python3.6/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: InvalidArgument: emoji argument must be str, Emoji, or Reaction not NoneType.
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### System Information

Python 3.6.1
Discord.py 1.4.1
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=raspbian
ID_LIKE=debian

**Comment by Rapptz** [comment]
[`Client.get_emoji`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.get_emoji) asks for an integer ID, not a string name. I don't really know why the emoji cache is empty as that shouldn't happen but the traceback being printed pertains to the `emoji1` variable which is due to mismatched data types. Judging from the traceback as well this isn't the complete code either.

**Comment by BennehR** [comment]
ok so that would be by that line is failing, that was just me trying different things to try get a result other than None

Your right in that it isnt the full code however what i removed isnt relevant, theres a whole chunk performing a DB transaction before this which has no impact on it, and some parts after where i use the declared emoji variables which then returns the None because its trying to add it as a reaction

Ill try just calling all emojis in my bots script instead of the cog, i dont know if its any different or what i can do with the info if it works, but at least i can feed that back to you?

for get_emoji, where or how can i obtain emoji ID's? when i google it i just get 3rd party websites for emoji lists and not ID numbers like im looking for

**Comment by alkatar21** [comment]
Emojis are only custom Emoji from Servers. Not the UTF-8 Emoji from discord. So you can not fetch for `:one:` = :one:
And as already mentioned. It would be helpfull to geht the exact code that is leading to the error.
```
File "[File Path]/cogs/LaunchLibrary.py", line 288, in launches
    await response.add_reaction(emoji1)
```
is the error bot we do not know what `emoji1` is.
I think you used `emoji1 = self.bot.get_emoji('one')` which of course is None since it is probably a Discord emoji and not an emoji added to a server where the bot is.

**Comment by BennehR** [comment]
heres where im at, knowing `self.bot.get_emoji` is the wrong thing ive gone back to what it was originally with the latest traceback

heres the full unedited method from the cog LaunchLibrary
```
class LaunchLibrary(commands.Cog, name="Launch Library"):
    def __init__(self, bot):
        self.bot = bot

    @commands.command()
    async def launches(self, ctx):
        ResultList = []
        response = await ctx.send("Getting launches...")
        async with ctx.typing():
            with open('Settings.json') as json_data:
                d = json.load(json_data)
            db_loc = d["db_loc"]
            print("Get Launches - Connecting to DB")
            conn = LaunchLibrary.create_connection(db_loc)
            print("Get Launches - Connection succesful")
            conn.row_factory = sqlite3.Row
            cur = conn.cursor()
            sql = f"SELECT * FROM Launch_Schedule ORDER BY Launch_Status, Launch_NET ASC LIMIT 10;"
            cur.execute(sql)
            data = [dict(row) for row in cur.fetchall()]
            
            emoji1 = discord.utils.get(self.bot.emojis, name='one')
            emoji2 = discord.utils.get(self.bot.emojis, name='two')
            emoji3 = discord.utils.get(self.bot.emojis, name='three')
            emoji4 = discord.utils.get(self.bot.emojis, name='four')
            emoji5 = discord.utils.get(self.bot.emojis, name='five')
            emojinext = discord.utils.get(self.bot.emojis, name='track_next')
            emojigreencircle = discord.utils.get(self.bot.emojis, name='green_circle')
            emojiredcircle = discord.utils.get(self.bot.emojis, name='red_circle')

            EmojiList = [emoji1, emoji2, emoji3, emoji4, emoji5, emojinext]
            print(EmojiList)
            embed = discord.Embed(title=f"Upcoming Launches", description=f"Next upcoming 5 launches, react with the corresponding emoji to see more details on that launch.", color=0x00ff00)
            
            for x in range(5):
                StatusEmoji = emojigreencircle if data[x]["Launch_Status"] == "Go" else emojiredcircle
                embed.add_field(name=f"{EmojiList[x]}", value=f"{StatusEmoji}{data[x]['Service_Provider']} - {data[x]['Rocket_Name']}", inline=True)
            
            embed.add_field(name=f"{emojinext}", value="See launches 6-10", inline=True)

            await response.add_reaction(emoji1)
            await response.edit(content=None, embed=embed)

        await ctx.send("Finished")

def setup(bot):
    bot.add_cog(LaunchLibrary(bot))
```

And heres the traceback
```
cogs.LaunchLibrary loaded OK!
cogs.maint loaded OK!
Getting token from db
Connection succesful
[Token Omitted]
We have logged in as BennehBot#XXXX
Get Launches - Connecting to DB
Get Launches - Connection succesful
[None, None, None, None, None, None]
Ignoring exception in command launches:
Traceback (most recent call last):
  File "[File Path]/lib/python3.6/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "[File Path]/cogs/LaunchLibrary.py", line 288, in launches
    await response.add_reaction(emoji1)
  File "[File Path]/lib/python3.6/site-packages/discord/message.py", line 952, in add_reaction
    emoji = self._emoji_reaction(emoji)
  File "[File Path]/lib/python3.6/site-packages/discord/message.py", line 1039, in _emoji_reaction
    raise InvalidArgument('emoji argument must be str, Emoji, or Reaction not {.__class__.__name__}.'.format(emoji))
discord.errors.InvalidArgument: emoji argument must be str, Emoji, or Reaction not NoneType.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "[File Path]/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "[File Path]/lib/python3.6/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "[File Path]/lib/python3.6/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: InvalidArgument: emoji argument must be str, Emoji, or Reaction not NoneType.
```

All emoji's come back as None, i was getting my info from [**_here_**](https://stackoverflow.com/questions/54012669/bot-wait-for-reaction-with-multiple-reaction-using-custom-emoji) which i now see why this was not what i was looking for, overlooking the "custom" emojis part of the question

What should I be using instead to get standard discord emojis?

**Comment by Phxntxm** [comment]
The bot has no collection of unicode emojis. You are trying to get unicode emojis from `bot.emojis`, which only contains custom eomjis (same reason why `bot.get_emoji` doesn't work). If you want to react with a unicode emoji you need to use the the codepoint, the unicode character itself (doesn't work with :one: - :nine:), or the format `1\N{variation selector-16}\N{combining enclosing keycap}` for :one:. 

Regardless, this isn't an issue with the discord.py library and would be better to be asked in the actual [help server](https://discord.gg/dpy).

**Comment by BennehR** [comment]
I would agree with that, ill try there again with new knowledge, thanks all
