### ISSUE TITLE
discord.Member.mention should be using <@!id> always

### ISSUE THREAD

**Issue by superloach** [Rapptz/discord.py#5791]
currently, `discord.Member.mention` uses the `<@!id>` format only if the member has a nickname:
```py
    @property
    def mention(self):
        """:class:`str`: Returns a string that allows you to mention the member."""
        if self.nick:
            return '<@!%s>' % self.id
        return '<@%s>' % self.id
```
however, it appears that the desktop client currently uses the `<@!id>` format for all members. I think this library should match.
if the `<@id>` format is needed from a member, `discord.Client.get_user(member.id).mention` can be used.

note: I will be pr'ing this very soon

**Comment by Rapptz** [comment]
The fact the client does this is a low priority bug on their end.

**Comment by superloach** [comment]
maybe I'm just confused, but why does it make sense to use the user mention format on a member if they don't have a nickname set?

**Comment by Rapptz** [comment]
Both mention strings work and are documented to work. Historically speaking, and how it used to be, was that the `<@!{id}>` format was used whenever a nickname was used in order for the push notification service to do an optimization in the lookup retrieval for display, while `<@{id}>` was used for the other cases. That implementation is represented there. At some point while they were rewriting the client's chat bar they made it so all mentions were `<@!{id}>` instead. When this was reported it was mentioned that it was a bug but it was low priority and won't be fixed right away.

Regardless, the fact remains that either mention format works despite the historical reason for their existence.

**Comment by superloach** [comment]
I know they both work for sending mentions, but it's inconvenient to not be able to get both formats for checking message content. for instance, checking if a message mentions the bot will fail if one uses `message.guild.me.mention` and the bot doesn't have a nickname set.

**Comment by superloach** [comment]
note: I'm aware this is a very minor issue, and easy to generate the format manually - I just thought it would be a nice simplification

**Comment by Rapptz** [comment]
Generally speaking most people use `commands.Bot` or their subclasses and pass `commands.when_mentioned` or `commands.when_mentioned_or` which handles all this for them hence why it isn't an issue for most people. Likewise, you're supposed to check for both of these mention formats anyway since the client will send both of these depending on circumstances.

**Comment by superloach** [comment]
> you're supposed to check for both of these mention formats anyway

is kinda what I'm getting at here, but I see your point about `commands.Bot`.
I prefer to work lower-level with just a `discord.Client`, and I suppose that's a fault of mine. thanks for your input :)
