### ISSUE TITLE
Message.edit raises TypeError about too many positional arguments on rewrite

### ISSUE THREAD

**Issue by Ovyerus** [Rapptz/discord.py#580]
May be an issue with ext as I haven't tested with regular.

Can be reproduced by the following snippet
```py
msg = await ctx.send('Test')
return await msg.edit('aaa')
```
Above snippet results in the following error
```py
TypeError: edit() takes 1 positional argument but 2 were given
```

**Comment by Rapptz** [comment]
It's a keyword only argument. `msg.edit(content='aaa')`
