### ISSUE TITLE
Read most recent DM's (such as normal people)?

### ISSUE THREAD

**Issue by ii-Python** [Rapptz/discord.py#5805]
This is **not** classified as a feature request at all. I just can't use discord right now since I'm at school (my bad).

Is there any possible way to get recent DM's from a bot and if there isn't shouldn't there be?
Something sort of like `bot.get_recent(max = 5)` which would return a list of `discord.DMChannel` objects.

If that isn't included in the Discord API please let me know.

**Comment by Vexs** [comment]
No, discord closes DMs very quickly and doesn't provide any info about them on login. Store this yourself.

**Comment by Rapptz** [comment]
There's [`Client.private_channels`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.private_channels) which is a LRU cache of the last 128 DMs someone has with your bot. However this information is probably going away soon as Discord is removing this information in its v8 gateway API. Likewise, this list will always be empty for sharded bots outside of shard ID 0.
