### ISSUE TITLE
[discord.ext.tasks] Loop Coro doesn't start

### ISSUE THREAD

**Issue by Luc1412** [Rapptz/discord.py#5808]
### Summary
 
Am using the `discord.ext.tasks` extension in my project. When I use it in a cog it works fine. In other cases outside a cog, the task gets created, but the core (including before_loop) doesn't start. 

I also got the same issue some time ago, that the task doesn't start in a specific cog.

This is a test environment and gets frequently restarted without canceling the task.

### Reproduction Steps

```py
class Cache:

    def __init__(self):
        self.bot = bot
        self.cache_update_loop.start()
        print('init')

    @tasks.loop(seconds=5)
    async def cache_update_loop(self):
        print(1)

    @cache_update_loop.before_loop
    async def before_cache_update_loop(self):
        print('before')
```

```py
    async def connect_all(self):
        self.cache= Cache()
        await self.start(self.config.get('core.{mode}.token'))

if __name__ == '__main__':
    if sys.platform == 'win32' and sys.version_info >= (3, 8):
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
    elif sys.platform == 'linux':
        asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())

    bot = Bot()

    loop = asyncio.get_event_loop()
    try:
        loop.run_until_complete(bot.connect_all())
    except discord.LoginFailure:
        bot.logger.exception(traceback.format_exc())
    except Exception as exc:
        bot.logger.exception(f'[CORE] Fatal exception! Bot is not able to login. Attempting graceful logout!\n\n'
                             f'```py\n{traceback.format_exc()}```')
        loop.run_until_complete(bot.logout())
    finally:
        if hasattr(loop, 'shutdown_asyncgens'):
            loop.run_until_complete(loop.shutdown_asyncgens())
        loop.close()
```

Result:
```
init
```

### Expected Results

It prints 'before'.  Afterward '1' every 5 seconds.

### Actual Results

Only 'init' gets printed. `start()` returns a Task

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.8.2-final
- discord.py v1.4.1-final
- aiohttp v3.6.2
- system info: Windows 10 10.0.19041

**Comment by Rapptz** [comment]
I believe this issue is a consequence of how loop references work. In order for the task extension to know what event loop to post on, it calls `asyncio.get_event_loop()` to fetch it at decorator time. However, in your code you change the event loop reference to something else so the task is now working on a dead loop object.  A more minimal example with no issue shows how to fix it:

```py
from discord.ext import tasks
import asyncio

class Cache:
    def __init__(self):
        self.cache_update_loop.start()
        print('__init__')

    @tasks.loop(seconds=5.0)
    async def cache_update_loop(self):
        print(1)

    @cache_update_loop.before_loop
    async def before_cache_update_loop(self):
        print('before loop')

async def main():
    cache = Cache()
    await asyncio.sleep(30)

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

You'll note that there is no new loop object reference. If you change the code to call `asyncio.run(main())` the issue will manifest as well.

Fixing this would require changing how the event loop is fetched and to do it lazily but I'm unsure at what point that should be done.

**Comment by Kaytuu** [comment]
Although it's been fixed, you can also instantiate the `tasks.Loop` class directly to specify your own loop:

```py
class Cache:

    def __init__(self):
        self.cache_update = \
            tasks.Loop(
                self.cache_update_loop, **{
                    'seconds': 5,
                    'minutes': 0,
                    'hours': 0,
                    'count': None,
                    'reconnect': True,
                    'loop': self.loop
                })

        self.cache_update._before_loop = \
            lambda: self.before_cache_update_loop()

        self.cache_update.start()
        print('init')

    async def cache_update_loop(self):
        print(1)

    async def before_cache_update_loop(self):
        print('before')
```

**Comment by Rapptz** [comment]
@Kaytuu please refrain from necroing closed issues.
