### ISSUE TITLE
Is there anyway to keep status?

### ISSUE THREAD

**Issue by IceRaider** [Rapptz/discord.py#581]
Hello, is there a way to keep it so that your Discord status remains the same instead of switching from Busy to Away, or from Online to Away?

Thanks, and this very helpful!

**Comment by Rapptz** [comment]
This is a place to report issues with the library, discord.py. Not for support about how to use Discord (the client).

**Comment by IceRaider** [comment]
I was not asking how to use the Discord client, just wondering if there is a workaround to remove the function in this program that changes status.

**Comment by Rapptz** [comment]
There is no "automatic" status changing in this library. When you change the presence, you do so because *you* put in code to do that.
