### ISSUE TITLE
frequently used processing flow

### ISSUE THREAD

**Issue by jakenjarvis** [Rapptz/discord.py#5811]
### The Problem

私は「よく使用する処理の流れ」をdiscord.pyに入れて欲しいと思います。その一つとして、私は次のコードで提案します。
I would like you to put "frequently used processing flow" in discord.py. As one of them, I suggest in the following code.
まずは、以下のよくある問題のあるコードをご覧ください。
First, take a look at the common problematic code below.

```python
    bot_message = await context.send(message)

    # ここでadd_reactionを実行すると、Emojiの数が多い場合にwait_forで待ち受けする前に
    # ユーザの入力が終わってしまうケースがあります。
    # これではユーザの入力を取りこぼす為、ユーザビリティが非常に悪くなります。
    # If add_reaction is executed here, the user input may end before waiting with
    #  wait_for when the number of Emoji is large.
    # This will miss the user's input, which will greatly reduce usability.
    for emoji in used_emojis:
        await bot_message.add_reaction(emoji)

    def check_reaction(reaction: discord.Reaction, member: discord.Member):
        return all([
            member.id == context.author.id,
            reaction.emoji in used_emojis,
            reaction.message.id == bot_message.id
        ])

    emoji = None
    try:
        reaction, member = await self.bot.wait_for(
            'reaction_add', check=check_reaction, timeout=30
        )
        emoji = reaction.emoji
    except asyncio.TimeoutError:
        emoji = None
```

add_reactionの追加速度は非常に遅く、追加している間にユーザがリアクションすると、botの反応が無いため、ユーザはそれをbotのバグだと判断します。
The add_reaction is very slow to add, and if the user reacts while adding, the bot will not respond and the user will consider it a bug in the bot.

### The Ideal Solution

一度に複数のリアクションが追加できる`add_reactions`を私は探しました。しかしそれは存在しません。Issue5740を読む限りAPIのサポート無しではこれを実現できそうにありません。
I searched for `add_reactions` that could add multiple reactions at once. But it doesn't exist. As far as I read Issue 5740, this is unlikely to be possible without API support.
https://github.com/Rapptz/discord.py/issues/5740

### The Current Solution

そこで、私は以下の小さなクラスを作成しました。
So I created the following small class.

```python
class ChoiceReactionFlow():
    def __init__(self, bot: commands.Bot, context: commands.Context):
        self.bot: commands.Bot = bot
        self.context: commands.Context = context
        self.bot_message: discord.Message = None
        self.used_emojis: List[str] = None
        self.index: int = 0

    def set_target_message(self, bot_message: discord.Message, used_emojis: List[str]):
        self.bot_message = bot_message
        self.used_emojis = used_emojis
        return self

    def check_choice_reaction_by_author_only(self) -> Callable[[discord.Reaction, discord.Member], bool]:
        return lambda reaction, member: all([
            member.id == self.context.author.id,
            reaction.emoji in self.used_emojis,
            reaction.message.id == self.bot_message.id
        ])

    async def wait_for_choice_reaction(self, *, check: Callable[[discord.Reaction, discord.Member], bool]=None, timeout: int=None, cancel: bool=True) -> str:
        if not check:
            check = self.check_choice_reaction_by_author_only()

        # 遅延が発生しますが、wait_forで待機している間にadd_reactionで追加することで、
        # botがユーザの入力を見逃さなくなります。
        # There will be a delay, but by adding it with add_reaction while waiting with
        #  wait_for, the bot will not miss the user's input.
        self.index = 0
        self.reaction_appender.count = len(self.used_emojis)
        #print(f"reaction_appender: start")
        self.reaction_appender.start()

        choice_emoji = None
        try:
            #print(f"wait_for: start")
            reaction, member = await self.bot.wait_for(
                'reaction_add', check=check, timeout=timeout
            )
            #print(f"wait_for: end")
            choice_emoji = reaction.emoji
        except asyncio.TimeoutError:
            choice_emoji = None

        if cancel:
            #print(f"reaction_appender: cancel")
            self.reaction_appender.cancel()

        #print(f"choice_emoji: {choice_emoji}")
        return choice_emoji

    @tasks.loop()
    async def reaction_appender(self):
        #print(f"reaction_appender: {self.index}")
        emoji = self.used_emojis[self.index]
        await self.bot_message.add_reaction(emoji)
        self.index += 1
```

これは以下のように使用することが出来ます。
It can be used as follows.

```python
    bot_message = await context.send(message)

    flow = ChoiceReactionFlow(self.bot, ctx)
    flow.set_target_message(bot_message, used_emojis)

    emoji = await flow.wait_for_choice_reaction(timeout=30)
```

### Summary

この例に限らず、このような便利な処理の流れを、discord.ext.flowなどで準備されていると私は嬉しいです。
Not limited to this example, I would be happy if such a convenient processing flow is prepared in discord.ext.flow etc.
私はdiscord.pyを使い始めて日が浅く、中身を十分に理解していないので、プルリクエストはしませんでした。
I didn't make a pull request because I'm new to discord.py and don't fully understand what's inside.

上記ソースコードは、このプロジェクトに寄贈します。自由に改変して組み込んでください。
The above source code will be donated to this project. Feel free to modify and incorporate it.

**Comment by apple502j** [comment]
もしかして: https://github.com/Rapptz/discord-ext-menus のことでしょうか?

**Comment by jakenjarvis** [comment]
@apple502j
返信ありがとうございます。
Thank you for your reply.

うわぁ、こんなのあったんだ！？と思いながら、READMEの冒頭に記載されていた「MyMenu」と「Confirm」の挙動を確認してみました。
Wow, there was something like this!? I checked the behavior of "MyMenu" and "Confirm" described at the beginning of the README.
私はもっと細かい単位での「処理フロー」をイメージしており、これほどまでメニューに特化したものを想像していませんでした。
I imagined a "processing flow" in smaller units, and I had never imagined something so specialized in menus.
これがまだテスト中とのことなので、正式採用されるのを期待します。
It is said that this is still under test, so I hope it will be officially adopted.


ついでなので、以下はdiscord-ext-menusを使ってみた感想です。
By the way, the following is my impression of using discord-ext-menus.
あらかじめ表示内容が決まっている「静的なメニュー」ならこれで十分ですが、「動的なメニュー」の場合は、使い勝手が難しそうに見えました。
This is sufficient for a "static menu" whose display contents are predetermined, but for a "dynamic menu", it seemed difficult to use.
discord-ext-menusの機能を全て理解していませんので、解決方法があるのかもしれませんが・・・。
I don't understand all the functions of discord-ext-menus, so there may be a solution...

Rapptzさん、とにかく素晴らしいものを作ってくれてありがとう。
Thank you Rapptz for making something great.

**Comment by jakenjarvis** [comment]
ああ、次のサンプル「MySource」が、動的メニューの例でしたね。私はもう少し試してみるべきでした。
Ah, the next sample "MySource" was an example of a dynamic menu. I should have tried a little more.
