### ISSUE TITLE
Detect when guild cache is incomplete on start up.

### ISSUE THREAD

**Issue by ghost** [Rapptz/discord.py#5816]
Currently, the library is waiting 2 seconds from the last GUILD_CREATE to determine if it is ready or not.

It would appear from https://github.com/discord/discord-api-docs/pull/1888 that you will receive GUILD_DELETE events for any unavailable guilds on startup. If this is the case, then you should be able to determine which guilds are currently in an outage on startup.

Keeping the 2 second timeout will be necessary if you are to handle eventual consistency where the create/delete event may be dropped, however, you would now be able to theoretically alter this logic to fire a warning that events have been dropped, should this timeout be fired.

Additionally, this will require the GUILDS intent to be enabled when migrating to v8 eventually, otherwise this will always fire the warning.

This would allow users to determine the issue in the case that a guild create event got dropped unknowingly on startup. This will allow them to identify that the cache is only partially constructed.

Of course, this is still dependent on whether that behaviour is documented or closed by Discord, but this may be a useful piece of functionality to allow for in the future, perhaps.

**Comment by NotGarrettE** [comment]
So what are you trying to get to, Is this an issue?
