### ISSUE TITLE
create_text_channel has weird behavior with position argument.

### ISSUE THREAD

**Issue by JCRaymond** [Rapptz/discord.py#5818]
### Summary

When either using discord.Guild.create_text_channel or discord.CategoryChannel.create_text_channel, the position argument is usually ignored. Editing the channel after creation fixes this issue. This could be an issue with the discord api itself, and not discord.py.

### Reproduction Steps

```python
channels = await guild.fetch_channels()
category = discord.utils.get(channels, name='My Category')
await guild.create_text_channel('chan1', category=category, position=3) # neither this or below works reliably
await category.create_text_channel('chan2', position=2)
```

### Expected Results

Channel to get created in the correct position always.

### Actual Results

Occasionally, the channel is created in the correct position, but usually it isn't

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.8.2-final
- discord.py v1.4.1-final
- aiohttp v3.6.2
- system info: Linux 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 16:50:52 UTC 2020

**Comment by Rapptz** [comment]
This stuff is passed through directly to the API. If it's ignored or doesn't work as expected then chances are the issue lies in the API itself which would require taking it up with Discord instead.
