### ISSUE TITLE
Bot crash at starting

### ISSUE THREAD

**Issue by OptimusVenatus** [Rapptz/discord.py#5822]
### Summary

Bot crash at starting

### Reproduction Steps

take https://github.com/Rapptz/discord.py/blob/master/examples/reply.py (or any script with discord.py)
place your token in client.run('token')
start your bot
and i get this error https://pastebin.com/HhPjnD9E

### Expected Results

bot start correctly

### Actual Results

Python crash and i got this error https://pastebin.com/HhPjnD9E

### Checklist

- [X ] I have searched the open issues for duplicates.
- [X ] I have shown the entire traceback, if possible.
- [X ] I have removed my token from display, if visible.

### System Information
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 22:39:24)
Win 10
latest version of discord.py (i think) i have upgraded it (py -m pip install --upgrade discord)

**Comment by lganWebb** [comment]
Update discord.py and re-run.

**Comment by Zomatree** [comment]
duplicate of #5109.
also the package is called `discord.py` not `discord`, please install that from pip

**Comment by Phxntxm** [comment]
Duplicate of #5109

**Comment by OptimusVenatus** [comment]
I have correctly updated discord.py with @Zomatree  advice and i get same error

**Comment by OptimusVenatus** [comment]
I have updated pip and retry upgrade of discord.py and it work perfectly 
sorry for the inconvenience
