### ISSUE TITLE
process_commands doesn't work with the "when_mentioned" prefix

### ISSUE THREAD

**Issue by JohnnyUrosevic** [Rapptz/discord.py#5828]
### Summary
If you override on_message, you cannot use process_commands to activate you commands, when using the `when_mentioned` prefix
### Reproduction Steps

```
import discord
from discord.ext import commands

bot = commands.Bot(command_prefix=commands.when_mentioned)

@bot.command()
async def ping(ctx):
    """Adds two numbers together."""
    await ctx.send('pong')

@bot.event
async def on_message(message):
    await bot.process_commands(message)

API_TOKEN = os.environ.get('API_TOKEN')
bot.run(API_TOKEN)
```

### Expected Results
I mention the bot and type ping and they respond pong

### Actual Results
The bot silently does nothing

### Checklist

- [x ] I have searched the open issues for duplicates.
- [ x] I have shown the entire traceback, if possible.
- [x ] I have removed my token from display, if visible.

### System Information

```
- Python v3.8.5-final
- discord.py v1.4.1-final
- aiohttp v3.6.2
- system info: Linux 5.8.6-1-MANJARO #1 SMP PREEMPT Thu Sep 3 14:19:36 UTC 2020
```

**Comment by Phxntxm** [comment]
I copy/pasted your own code and it worked for me, no change except token obviously. Just as a hunch, are you sure you mentioned your **bot** and not the **role** a bot auto creates when invited with permissions?

**Comment by JohnnyUrosevic** [comment]
Yes I made sure to mention the bot, changing the prefix to '.' or something works as expected

**Comment by Rapptz** [comment]
I can't see any reason why this doesn't work considering both mention formats are in the list. I'm almost certain this might be a role shadowing the mention. Try to confirm it by fetching the message and printing the content.

**Comment by JohnnyUrosevic** [comment]
I'm sorry how do you want me to fetch the message to show you?

**Comment by Anubhav1603** [comment]
@JohnnyUrosevic 
 [fetch_message](https://discordpy.readthedocs.io/en/latest/api.html?highlight=fetch%20message#discord.abc.Messageable.fetch_message)
U can use this to fetch message and then print  it's content

**Comment by Rapptz** [comment]
> I'm sorry how do you want me to fetch the message to show you? Like add `print(message)` in the on_message function?

`print(message)` works okay but it'll be a bit spammy. Ultimately if the content is something like `<@&...>` then it's a role mention and not a member mention.

**Comment by JohnnyUrosevic** [comment]
After trying this again today the problem disappeared. It's weird because this was happening to me with multiple bots but maybe I was just messing stuff up each time and then misremembering. Sorry about that
