### ISSUE TITLE
"abc.Messageable.send" ignores "allowed_mentions" when "file" kwarg is specified

### ISSUE THREAD

**Issue by fixator10** [Rapptz/discord.py#5835]
## Summary

"abc.Messageable.send" ignores "allowed_mentions" when "file" kwarg is specified

## Reproduction Steps

```py
file = discord.File(BytesIO())
await ctx.send(ctx.author.mention, file=file, allowed_mentions=discord.AllowedMentions(users=False))
```

## Expected Results

User was not mentioned

## Actual Results

User was mentioned

## Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

## System Information

```
- Python v3.8.5-final
- discord.py v1.4.1-final
- aiohttp v3.6.2
- system info: Linux 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020
```

**Comment by NotMaxee** [comment]
Are you sure that you are using discord.py v1.2.5? The ``allowed_mentions`` keyword was [not added until version 1.4](https://discordpy.readthedocs.io/en/latest/api.html#discord.abc.Messageable), which should raise a ``TypeError`` as you are passing an unexpected keyword argument if you were actually using v1.2.5.

**Comment by fixator10** [comment]
> Are you sure that you are using discord.py v1.2.5? The allowed_mentions keyword was not added until version 1.4, which should raise a TypeError as you are passing an unexpected keyword argument if you were actually using v1.2.5.

Ooops, used wrong binary in venv, thats was 3.7 instead of 3.8, updated, thanks for notice
