### ISSUE TITLE
Is there a way to post a local image?

### ISSUE THREAD

**Issue by adhoc92** [Rapptz/discord.py#584]
Posting an image link is easy:

    @bot.group(pass_context=True)
    async def john(ctx):
    
        if ctx.invoked_subcommand is None:
            await bot.say('https://i.imgur.com/rZWO3QB.png'.format(ctx))

But changing the URL to something like C:/blah/blah/blah.png obviously doesn't work. Is it possible?

**Comment by sliceofcode** [comment]
Please read the documentation. http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.send_file

**Comment by mikevb1** [comment]
[`bot.upload`](https://github.com/Rapptz/discord.py/blob/async/discord/ext/commands/bot.py#L420) is the commands ext equivalent of `Client.send_file`.

**Comment by armaan115** [comment]
For posting a _local_ image in an _embed_, see this StackOverflow thread: 
https://stackoverflow.com/questions/61578927/use-a-local-file-as-the-set-image-file-discord-py/61579108#61579108

(It's compatible with the rewrite of discord.py)
