### ISSUE TITLE
Custom Context returning error

### ISSUE THREAD

**Issue by 12944qwerty** [Rapptz/discord.py#5845]
## Summary

I've made a custom context with only one extra command that inherits from `Context`. I've made my own `get_context` command which just passes `MyCtx` as the `cls` arg. However, I'm getting the following error.

This code used to work a couple days ago, but it's not working anymore.

```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 52, in on_message
    await self.process_commands(message)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 926, in process_commands
    ctx = await self.get_context(message)
  File "main.py", line 66, in get_context
    return await super().get_context(message=message, cls=MyCtx)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 837, in get_context
    ctx = cls(prefix=None, view=view, bot=self, message=message)
  File "/home/runner/Ratchet/cogs/utils/context.py", line 7, in __init__
    super().__init__(self, *args, **kwargs)
TypeError: __init__() takes 1 positional argument but 2 were given
```

## Reproduction Steps

MyCtx Code:
```py
from discord.ext import commands
import discord


class MyCtx(commands.Context):
	def __init__(self, *args, **kwargs):
		super().__init__(self, *args, **kwargs)

	async def em(self, *, title, description=None, bot=None, **kwargs):
		"""Quick embed sending."""
		kwargs.pop('title', None)
		kwargs.pop('description', None)
		kwargs.pop('color', None)
		kwargs.pop('bot', None)
		em = discord.Embed(title=title, description=description, color=discord.Color.blue())
		if bot is not None:
			em.set_author(name=self.bot.user.display_name, icon_url=self.bot.user.avatar_url)
		return super().send(embed=em, **kwargs)
```

## Expected Results

For my bot to work properly without getting an error from context.

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

## System Information

repl.it python 3.8.3
discord.py 1.4.1

**Comment by apple502j** [comment]
You don't pass `self` to `super().__init__`. Not a bug.

**Comment by 12944qwerty** [comment]
Really? I've inherited other classes and they all work fine when I do this....

**Comment by Soheab** [comment]
take a look at this example: https://github.com/Rapptz/discord.py/blob/master/examples/custom_context.py

**Comment by 12944qwerty** [comment]
Hmm, I had tried not putting self before but that didn't work and when I put self, it did. Thank you though!
