### ISSUE TITLE
on_member_update does not appear to be working at all

### ISSUE THREAD

**Issue by lukenamop** [Rapptz/discord.py#5848]
## Summary

on_member_update does not appear to be working after the latest set of patches.

## Reproduction Steps

```@client.event
async def on_member_update(before, after):
	if after.roles != before.roles:
		print('role update detected, checking for expiration roles')
```

## Expected Results

I expect `role update detected, checking for expiration roles` to be printed when I add or remove a role from a user.

## Actual Results

Nothing is printed when I add or remove a role from a user.

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

**Comment by lukenamop** [comment]
I'm unsure exactly which patch broke this client event but I reverted to a commit 5 days ago (https://github.com/Rapptz/discord.py/tree/8f105a441dff397a72c9f3e54f73850b31eafdb6) and my code is working as intended again.

**Comment by Vexs** [comment]
[You need to explicitly enable member intents if you want to use them](https://discordpy.readthedocs.io/en/latest/intents.html)

**Comment by lukenamop** [comment]
Thank you for the link, I'll take a deeper look but on glancing through this appears to solve my issue.
