### ISSUE TITLE
Get a python discord bot to join the current voice channel i am in

### ISSUE THREAD

**Issue by Sneakyninja0129** [Rapptz/discord.py#585]
Im brand new to creating discord bots but i cant figure out how to get the bot to join the channel I AM IN. I know how to get the bot to join a channel with its ID but cant figure out the other way. Plz help

**Comment by Rapptz** [comment]
You have to query the member voice state via `Member.voice` and then get the voice channel from that.

Something like `member.voice.voice_channel is not None`. Where `member` can be e.g. `message.author`.
