### ISSUE TITLE
when using intents members get cached 1 shard at a time

### ISSUE THREAD

**Issue by AEnterprise** [Rapptz/discord.py#5857]
## The Problem

When using the new intents on 1.5.0a and running multiple shards, waits until all guilds from the first shard are cached before requesting any guild members from other chunks

## The Ideal Solution

requesting member chunks for all shards at the same time, or using maybe moving rotating through shards when one is ratelimited to start working on the next one as it usually has to wait a full minute before continuing on that shard.

## The Current Solution

There currently is no way to achieve this speedup

## Summary

Make member caching faster for bots running multiple shards

**Comment by Rapptz** [comment]
This is hard to solve because I'm using a queue so it'll be in queue order. I don't have any plans to change this any time soon and the Discord changes that basically force 1 guild per chunk request make this a hard problem.

**Comment by AEnterprise** [comment]
i tried making this in parallel but it's a bit troublesome the way d.py handles all this so for now i've implemented my own workaround, in case anyone is interested in an example implementation for this: https://github.com/gearbot/GearBot/commit/ec74dc30a7e2ddc4faa5d2f50b0ac9df6f95b05e

**Comment by iomintz** [comment]
The tl;dr of that approach is to `await asyncio.wait(*(guild.chunk() for guild in bot.guilds))`. That's clever.

**Comment by AEnterprise** [comment]
pretty much, tough i had to add some additional handling and tracking yesterday to retry after a timeout or getting a new ready event (and cancel the old ones) to also still get them after the socket dies in the middle of that.

but yeah that's main thing that makes it go faster
