### ISSUE TITLE
aiohttp setup.py : UnicodeDecodeError : "utf-8" codec can't decode byte 0xe9

### ISSUE THREAD

**Issue by s0me-1** [Rapptz/discord.py#586]
Hello,

The discord.py setup cannot install aiohttp directly (error in the title), and it attemps to uninstall any aiohttp version higher than 1.1.0, resulting in a failed installation in any case

**Comment by Rapptz** [comment]
Missing a traceback.

However, this isn't a problem with this library. It's a problem with `pip`.

**Comment by s0me-1** [comment]
My bad sorry. Anyway if anyone is wondering how to get things working here's what I did :

Manually install websockets and aiohttp :
`py -3 -m pip install aiohttp websockets`

Then install discord.js with --no-dependencies : 
`py -3 -m install discord.js --no-dependencies`

Everything is running fine, I just wanted to report the bug ;)
