### ISSUE TITLE
guild.get_role(role_id) returning None

### ISSUE THREAD

**Issue by lukenamop** [Rapptz/discord.py#5863]
## Summary

When I use `guild.get_role(role_id)`, I'm getting None as a response. This feature has worked for almost a year with no issues and I have quadruple checked to make sure the guild ID and role ID I'm referencing have not changed and are still accurate. Most likely a latest update issue, I'm using the latest dev build and staying on top of changes, my intents are all set correctly as per the update a few days ago: `members=True, bans=False, integrations=False, webhooks=False, invites=False, voice_states=False, typing=False` and I have correctly enabled member intent in the dev dashboard. Everything else seems to be working for me except for `guild.get_role(role_id)`.

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
You don't have the guild intent enabled.

**Comment by lukenamop** [comment]
Aren't all intents other than `members` and `presence` enabled by default, unless I manually specify them though? And I'm not getting any errors, it's just giving me None instead of the role.

**Comment by Rapptz** [comment]
No, I changed the constructor to work like other flags. If you want the default where everything is enabled by default then you use the classmethod (Intents.default()) and then modify the attributes that way. The constructor now has everything set to False except what you pass in.

**Comment by lukenamop** [comment]
Okay. Thanks for clarifying. I'm manually setting them all now. I did kind of like having those two (the ones that require special dashboard settings) being automatically False and the rest automatically True, but I guess I can understand why it would be helpful to have them all just default to False. Everything's working now for me, in any case.
