### ISSUE TITLE
get_member returns none always

### ISSUE THREAD

**Issue by Aaron1997ps** [Rapptz/discord.py#5867]
## Summary

A recent update to Discord seems to have caused get_member when using a guild to not return the member.

There was a sudden change in all instanced where get_member was used causing my bots to behave ab-normally without any code changes.

## Reproduction Steps

get a guild using client.get_guild(guildID)
use guild.get_member(userID)

```
@bot.event
async def on_ready():
    print(bot.get_guild(287096977630691329).get_member(750920031738789968))
```
bot.get_guild(287096977630691329) returns the proper guild.
The member ID is from a member in the server. I have tried other IDs.

## Expected Results

Returned Member Object

## Actual Results

Returned None

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

## System Information

- Python v3.6.7-final
- discord.py v1.5.0-final
- aiohttp v3.6.2
- system info: Linux 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1+deb9u1 (2020-06-07)

**Comment by SebbyLaw** [comment]
This is not a bug with the library. Please see the recently added [intents documentation](https://discordpy.readthedocs.io/en/latest/intents.html) and [v1.5 changelog](https://discordpy.readthedocs.io/en/latest/whats_new.html#v1-5-0).

**Comment by Pysics** [comment]
Why is this issue still pinned?
