### ISSUE TITLE
Help moving bot to another voice channel

### ISSUE THREAD

**Issue by Sneakyninja0129** [Rapptz/discord.py#587]
@client.command(pass_context=True)
async def joinvoice(ctx):
    """Joins your voice channel"""
    
    author = ctx.message.author
    server = ctx.message.server
    voice_channel = author.voice_channel
    if voice_channel is not None: #is in a channel
        discord.VoiceClient.move_to(voice_channel) <------------- This line is the only not working part
    await client.join_voice_channel(voice_channel)

Heres the code i have i need it to either disconnect from the voice channel or for it to move the bot to voice_channel

**Comment by Gorialis** [comment]
You're accessing the attribute `move_to` of the VoiceClient class, not an instance of it. Judging by your code, this line is unnecessary anyway, as you don't have a voice client to move yet.
```py
if voice_channel is not None:
    voice_client = await client.join_voice_channel(voice_channel)
```

**Comment by Sneakyninja0129** [comment]
Thats not what i need. What the problem is, is i want it to be able to move channels and if it is in a channel ie: if voice_channel is not None: I want it to disconnect and join the new channel

**Comment by Gorialis** [comment]
You can use [server.voice_client](http://discordpy.readthedocs.io/en/latest/api.html#discord.Server.voice_client) to obtain the [voice client](http://discordpy.readthedocs.io/en/latest/api.html#discord.VoiceClient) for a given server, if there is one. Don't try and use methods from `discord.VoiceClient` directly because that is the class, not the instance.

**Comment by Sneakyninja0129** [comment]
Thats still not what i need. My bot can join any channel. But once it is in a channel i cant get it to disconnect from the voice chat

**Comment by Gorialis** [comment]
Voice clients have a [move_to](http://discordpy.readthedocs.io/en/latest/api.html#discord.VoiceClient.move_to) coroutine you can use to shift them to another channel. If you need to disconnect (you don't for this), you can use [disconnect](http://discordpy.readthedocs.io/en/latest/api.html#discord.VoiceClient.disconnect) instead.

**Comment by Sneakyninja0129** [comment]
Could you write an example? Im confused about legit everything ive been coding for like 10 hours and im super tired

**Comment by PapyrusThePlant** [comment]
Those issues are not to help you with your code, but to report bugs within the library.
You can join the [discord api server](https://discord.gg/discord-api) to chat about code and stuff if you wish but please stop using github as a help desk as it spams over a thousand people's email with your inability to search the documentation.

**Comment by AXAz0r** [comment]
To disconnect from the current voice channel on the server:
```py
await message.guild.voice_client.disconnect()
```
To move to a new channel:
```py
await message.guild.voice_client.move_to(voice_channel)
```

**Comment by Gorialis** [comment]
@AXAz0r The property is only `message.guild` in rewrite, which in general you should assume users are **not** using.

**Comment by AXAz0r** [comment]
@Gorialis True enough, but the method is the same in async where you'd only replace `.guild` with `.server`

**Comment by Sneakyninja0129** [comment]
Where are you getting "message".server.voice_client.disconnect()?

**Comment by lepeli** [comment]
http://python.swaroopch.com/ (for complete beginners to programming)
https://learnxinyminutes.com/docs/python3/ (for people who know programming already)
https://docs.python.org/3.5/tutorial/ (for the in-between group, i.e. knows some programming but not a lot)
see also: http://www.codeabbey.com/ (exercises for beginners)

DOCS : http://discordpy.rtfd.io/en/latest/api.html

**Comment by Phxntxm** [comment]
Can't believe no one has answered this question. Everything given so far for the rewrite, not async version (except links to the documentation). He is using `message.server`. He is not using the rewrite. Y'all are petty.

http://discordpy.readthedocs.io/en/latest/api.html#discord.VoiceClient.move_to
What you're looking for is this. You need an instance of the VoiceClient. Notice the text "This client is created solely through Client.join_voice_channel() and its only purpose is to transmit voice."

This means that **you** need to save a reference to the voice VoiceClient somewhere. You can use this example to base off of:
https://github.com/Rapptz/discord.py/blob/async/examples/playlist.py

The idea is the state of the voice connection is saved, when trying to join a channel, check if that voice connection exists ( https://github.com/Rapptz/discord.py/blob/async/examples/playlist.py#L115 ) if it does, use `move_to` if it doesn't, use `join_voice_channel`.

The same goes for disconnecting, you have that VoiceState saved and if you have a connected VoiceClient, disconnect.

**Comment by Sneakyninja0129** [comment]
Sorry for reopening the thread but ive been stuck ever since i posted this thread
`import discord
import asyncio
import youtube_dl
import random
from random import randint
from discord.ext.commands import Bot
from discord.ext import commands

description = "SneakyBot"
Client = discord.Client()
bot_prefix= "s."

client = commands.Bot(description=description, command_prefix=bot_prefix)

@client.event
async def on_ready():
    print("Bot Online!")
    print("Name: {}".format(client.user.name))
    print("ID: {}".format(client.user.id))
    await client.change_presence(game=discord.Game(name='Under Construction'))
    print()

class VoiceState:
    def __init__(self, bot):
        self.current = None
        self.voice = None
        self.bot = bot

@client.command(pass_context=True)
async def ping(ctx):
    await client.say("Pong!")
    
@client.command(pass_context=True)
async def hi(ctx):
    await client.say("Hi!")

@client.command(pass_context=True)
async def vape(ctx):
    await client.say("Knas vapes, and therefore is homosexual")

@client.command(pass_context=True)
async def invite(ctx):
    #Put channel invite here
    print("not working")

@client.command(pass_context=True)
async def coin(ctx):
    headsortails = random.randint(1,2)
    if (headsortails == 1):
        await client.say("Heads")
    elif (headsortails == 2):
        await client.say("Tails")
        
@client.command(pass_context=True)
async def clear(ctx, number):
    mgs = [] #Empty list to put all the messages in the log
    number = int(number) #Converting the amount of messages to delete to an integer
    async for x in client.logs_from(ctx.message.channel, limit = number):
        mgs.append(x)
    await client.delete_messages(mgs)


@client.command(pass_context=True)
async def rn(ctx, number1, number2):
    number1 = int(number1)
    number2 = int(number2)
    number = randint(number1, number2)
    await client.say(number)

@client.command(pass_context=True)
async def joinvoice(ctx):
    """Joins your voice channel"""
    author = ctx.message.author
    server = ctx.message.server
    voice_channel = author.voice_channel
    await client.join_voice_channel(voice_channel)

@client.command(pass_context=True)
async def disconnect(self, ctx):
    
client.run("")
`
All i need is a simple disconnect command and i can friggin figure it out
