### ISSUE TITLE
on_raw_reaction_remove event's payload does not have a member attribute

### ISSUE THREAD

**Issue by Sunney-X** [Rapptz/discord.py#5871]
## Summary

The `on_raw_reaction_add` works just fine, the `payload.member` returns the member as default.

`on_raw_reaction_remove` payload should have member attribute, but it returns `None`

## Reproduction Steps

Reproduction is simple, just use the event

## Expected Results

the `member` attribute should've returned the member

## Actual Results

It returned  `None`

## Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

## System Information

- Python v3.6.8-final
- discord.py v1.4.1-final
- aiohttp v3.6.2
- system info: Linux 4.18.0-193.14.2.el8_2.x86_64 #1 SMP Sun Jul 26 03:54:29 UTC 2020

**Comment by Zomatree** [comment]
this is expected and documented, discord doesn't send it inside the remove event.

**Comment by Sunney-X** [comment]
> this is expected and documented, discord doesn't send it inside the remove event.

I've seen that in the source. Any idea why?

**Comment by Zomatree** [comment]
discord doesn't send it inside the reaction remove payload.

**Comment by BaderSpace** [comment]
You can get the member object in on_raw_reaction_remove by converting the user_id to a member object like this:
```python
guild = discord.utils.find(lambda g : g.id == guild_id, client.guilds)
member = await guild.fetch_member(payload.user_id)
```
