### ISSUE TITLE
ctx.message.guild.me fails

### ISSUE THREAD

**Issue by yunolawliet** [Rapptz/discord.py#5876]
## Summary

ctx.message.guild.me fails if you use it more than once.

## Reproduction Steps

1. do a print (ctx.message.guild.me)
2. ask bot to join your voice channel
3. ask the bot to leave
4. check the print (ctx.message.guild.me) it will be 'None'

These are the scenarios I did to replicate the bug.

**Comment by AbstractUmbra** [comment]
This is because of the new Intents release. It appears you currently don't have the Members intent enabled and as such the member data will not be populated. Please see the [docs](https://discordpy.readthedocs.io/en/latest/intents.html) on Intents to get started.

**Comment by Rapptz** [comment]
This is missing information to be actionable.

1. What are the intents you're passing in?
2. What version are you using?

**Comment by yunolawliet** [comment]
As @AbstractUmbra noted, enabling intent will fix this. Closing this issue now.

**Comment by Harmon758** [comment]
This should be fixed with https://github.com/Rapptz/discord.py/commit/61e25cb0904af0fe0831942314bf424344d3e42d in v1.5.1.
See also #5949.
