### ISSUE TITLE
Can't login with user email/password or token?

### ISSUE THREAD

**Issue by instanceofplayer** [Rapptz/discord.py#588]
I'm trying to make a selfbot using discord.py and everything I try doesn't work.

I tried using my token to login and my email/password combination but they both throw errors.
```discord.errors.LoginFailure: Improper token has been passed.```
and
```TypeError: write() argument must be str, not None```
respectively.

**Comment by Phxntxm** [comment]
```
bot.run('YOURTOKENHERE', bot=False)
```
Providing `bot=False` is required when trying to use a selfbot. Please use token and not email/password

**Comment by instanceofplayer** [comment]
Documentation said that ```bot=``` isn't considered when ```self_bot=True``` is used but it seems to work! Thanks :)
