### ISSUE TITLE
CategoryChannel.overwrites does not retrieve overwrites for users/members

### ISSUE THREAD

**Issue by geasedinburgh** [Rapptz/discord.py#5882]
## Summary

I was trying to retrieve a list of members who have permission overwrites for a category (as opposed to roles). The category in question had some members as well as roles with permission overwrites. When I attempt to retrieve the overwrites, CategoryChannel.overwrites retrieved only the role overwrites instead of all of the overwrites for the channel.

## Reproduction Steps

```
@client.command(name='findmoderator')
async def findModerator(ctx):
    categ = ctx.channel.category
    permissions = categ.overwrites
    print(permissions)
```

## Expected Results

I expected to get a dictionary with all the overwrites for the category, for members as well as roles.

## Actual Results

What I got instead was a dictionary of overwrites for the roles only. It did not return any of the users who had overwrites set for them.

## Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

## System Information

- Python v3.8.6-final
- discord.py v1.5.0-final
- aiohttp v3.6.2
- system info: Windows 10 10.0.18362

**Comment by Zomatree** [comment]
You need the members intent to get the overwrites for members, you can read up on intents here https://discordpy.readthedocs.io/en/latest/intents.html#

**Comment by geasedinburgh** [comment]
Thanks for that. I've already got all the intents enabled, both in the bot and on the Discord Developer portal. I'm able to use other commands that rely on the members intent (like fetch_member() etc. But it still doesn't seem to let me get the overwrites for members using CategoryRole.overwrites. Sorry for missing that out in my earlier post.

**Comment by XuaTheGrate** [comment]
``Guild.fetch_member`` does not rely on intents, as it is not done through the gateway.
Can you provide the exact intents you are passing into your bot's initializer? In order to receive members, you need the ``guilds`` intent alongside the privileged ``members`` intent.

**Comment by geasedinburgh** [comment]
Thanks for letting me know re `Guild.fetch_member`, I think I may have misread the docs about whether or not it relied on intents.

The intents I have provided are `discord.Intents.all()`.

**Comment by Rapptz** [comment]
The member intent isn't the only thing required to make this work -- you also need the guild to be properly chunked. If you're not chunking at start up, either because `chunk_guilds_at_startup=False` or `fetch_offline_members=False` is set in your `Client.__init__` then you need to chunk the guild in order for methods that use the member cache to work. There are plans to improve this but it requires some breaking changes so chunking is the best compromise there is. It's as simple as doing this:

```py
if not guild.chunked:
    await guild.chunk(cache=True)
```
