### ISSUE TITLE
AuditLogDiff is not iterable

### ISSUE THREAD

**Issue by TheEnigmaBlade** [Rapptz/discord.py#589]
For whatever reason, `AuditLogDiff.__iter__()` is not producing an iterable object. Any attempt to iterate it produces this error:

> TypeError: iter() returned non-iterator of type 'dict_items'

The expected result of `iter()` should be of the type `dict_itemiterator`, which is strange. The type `dict_items` is the result of `items()`.

```python
test = AuditLogDiff()
setattr(test, "testkey", "testvalue")

# Fail
for key, value in test:
    pass

# Fail
test_iter = iter(test)
```

Interestingly, `AuditLogDiff.__iter__()` can be copy-pasted or called directly and the result is perfectly iterable.

```python
# Pass
for key, value in test.__dict__.items():
    pass

# Pass
for key, value in test.__iter__():
    pass
```

The result of `items()` is iterable *before* it's returned from `__iter__()`:

```python
class AuditLogDiffFixed:
    def __iter__(self):
        return iter(self.__dict__.items())

test_fix = AuditLogDiffFixed()
setattr(test_fix, "testkey", "testvalue")

# Pass
for key, value in test_fix:
    pass
```

**Comment by Rapptz** [comment]
Yup. Good catch. Fixed.
