### ISSUE TITLE
Add utility function to only escape @everyone and @here

### ISSUE THREAD

**Issue by ChristopherJHart** [Rapptz/discord.py#5892]
## The Problem
Some applications may have a use case wherein they always want to escape `@everyone` and `@here`, but do not want to escape any other mentions (e.g. `@Role-Mention` or `@User-Mention`).

## The Ideal Solution
Ideally, either a new utility function is added to [utils.py](https://github.com/Rapptz/discord.py/blob/ab1c606ff2838ea4b71f66a3acf2174d48926239/discord/utils.py), or the existing `escape_mentions()` function is modified to accept a keyword that specifies whether `@everyone` or `@here` is stripped.

If the latter solution is implemented, it might be best to accept three new keywords:

* `escape_everyone` - Defaults to `True`. Removes `@everyone` mentions from parameter `text`.
* `escape_here` - Defaults to `True`. Removes `@here` mentions from parameter `text`.
* `escape_role_or_user` - Defaults to `True`. Removes user and/or role mentions from parameter `text`.

This should retain backwards compatibility while giving future applications the flexibility to choose what mentions are escaped.

## The Current Solution
To satisfy this specific use case, applications must filter out `@everyone` and `@here` mentions manually instead of using the `escape_mentions()` function.

## Summary
The `escape_mentions()` utility function should be enhanced such that users can choose what specific mentions they want to be escaped.

**Comment by Rapptz** [comment]
Escaping has been mostly superceded by AllowedMentions.

**Comment by ChristopherJHart** [comment]
I was not aware `AllowedMentions` was a thing - thank you! I'll make sure to use this moving forward.

Two questions as a side note:

1. Do we plan on deprecating the `escape_mentions()` utility function in the near future, since AllowedMentions arguably does the same job better?
2. Would you be open to a documentation PR changing the `escape_mentions()` utility function to point users towards AllowedMentions?

Thank you again!

**Comment by Rapptz** [comment]
1. No, the function is still fine for what it aims to do. 
2. Yeah that'd be a good place to put it.

**Comment by ChristopherJHart** [comment]
Gotcha - I'll close this issue out, open up a new one to track the documentation change, and submit a PR shortly to put a note in the `escape_mentions()` utility function's doc.

Thank you!

**Comment by Rapptz** [comment]
No problem. 

Just the PR would be enough I wager, no need for a tracking issue.
