### ISSUE TITLE
on_member_join does not work when hosted (heroku)

### ISSUE THREAD

**Issue by Th3Y3ll0wGuy** [Rapptz/discord.py#5895]
Hello,

I started to use Heroku to host my bot. I pushed a simple function to test with on_ready, on_member_join and a ping cmd.
When I run it on my laptop all functions work well but when I run it on Heroku on_member_join does not work.
There is no error in the console log.

Can you help me to solve this problem ? So I can upload the rest of my code.

**Comment by wasi-master** [comment]
May be because of intents? Did you setup the members and guilds intent?

**Comment by Th3Y3ll0wGuy** [comment]
what is: "members and guilds intent" ?

**Comment by SebbyLaw** [comment]
Please do not delete/disregard the text from the bug report issue template — it shows valuable information that may help diagnose your issues.

Your issue most likely lies with not passing the correct [intents](https://discordpy.readthedocs.io/en/latest/intents.html).

This is not an issue with discord.py. GitHub issues for this repository should be used to report issues with this library.

For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by Th3Y3ll0wGuy** [comment]
Okay, didn't know about intents as it works on my laptop. Thanks @SebbyLaw
