### ISSUE TITLE
embed.set_author(..., icon_url) - have `request` options for requesting the icon_url 

### ISSUE THREAD

**Issue by TAbdiukov** [Rapptz/discord.py#5899]
## The Problem

Suppose you have something like,
```
embed.set_author(..., icon_url)
```

Notice - you can only specify the URL, but you cannot specify the cookies, request type (GET, POST etc), the SSL mode (e.g. `verify=False`), etc

## The Ideal Solution

In my opinion,
```
embed.set_author(..., icon_url, super().request_instance.(your_custom parameters) = (desired value))
```

OR 

```
embed.set_author(..., icon_url, URL_REQUEST_SPECIFICS = [cookies = ..., type = "POST", etc]
```

## The Current Solution

(No known way)

## Summary

I request that there are to be specifiable `request` options for requesting the icon_url

**Comment by Rapptz** [comment]
This URL is not requested at all from the client side (i.e. `discord.py`). Discord processes these URLs themselves and makes a request on their end instead (using their media proxy which eventually gets sent to the Discord client).

**Comment by TAbdiukov** [comment]
Thanks for clarifying!
