### ISSUE TITLE
Best way to listen for commands and then default to a normal message handler?

### ISSUE THREAD

**Issue by SnowySailor** [Rapptz/discord.py#590]
So say I have a bot that I want to write commands for. Say I have
```python
@bot.command()
async def add(left : int, right : int):
    """Adds two numbers together."""
    await bot.say(left + right)
```
But I _also_ want to do something where you have a message event like in the reply.py example. So if a command isn't called, we still handle a message normally.
```Python
@client.event
async def on_message(message):
    ...
    ...
```

What's the best way to do that? Do you need to have two instances of the bot running at the same time, or is there a way to do it with just one instance?

**Comment by sliceofcode** [comment]
`commands.Bot` is a subclass of `discord.Client`, so both are supported within one `commands.Bot` instance.

**Comment by SnowySailor** [comment]
Right, but whenever I create an on_message listener associated with a bot.event, the bot.command() never happens. As an example, the echo command doesn't work in this case: http://puu.sh/wd8FF.png

What am I doing wrong? I'm not a python expert.

**Comment by Phxntxm** [comment]
http://discordpy.readthedocs.io/en/latest/faq.html#why-does-on-message-make-my-commands-stop-working

**Comment by SnowySailor** [comment]
Thanks
