### ISSUE TITLE
4014 error when moving bot to another voice channel

### ISSUE THREAD

**Issue by TimK50** [Rapptz/discord.py#5904]
## Summary

I'm trying to move bot to another voice channel after it connects. But it disconnects after moving with Gateway Intent Error 4014

## Reproduction Steps

intents = discord.Intents.all()
bot = commands.Bot(command_prefix=def_prefix, intents=intents)
await ctx.author.voice.channel.connect()

then await ctx.guild.voice_client.move_to(another.voice.channel) or manual moving

then in log:
 
> 2020-10-06 17:40:19,780:DEBUG:discord.gateway: Keeping shard ID None voice websocket alive with timestamp 1601995219780.
> 2020-10-06 17:40:19,780:DEBUG:discord.gateway: Sending voice websocket frame: {'op': 3, 'd': 1601995219780}.
> 2020-10-06 17:40:19,789:DEBUG:discord.gateway: Voice websocket frame received: {'op': 6, 'd': 1601995219780}
> 2020-10-06 17:40:21,111:DEBUG:discord.gateway: Received WSMessage(type=<WSMsgType.CLOSE: 8>, data=4014, extra='Disconnected.')
> 2020-10-06 17:40:21,111:INFO:discord.voice_client: Disconnecting from voice normally, close code 4014.
> 2020-10-06 17:40:21,112:INFO:discord.voice_client: The voice handshake is being terminated for Channel ID 732706167028973769 (Guild ID 659036893870293022)

## Expected Results

Bot not disconnects after moving and continue working (before.channel = smth, after.channel = smth)

## Actual Results

Bot moves (before.channel = smth1, after.channel = smth2)
Bot disconnects (before.channel = smth2, after.channel = None)

## Intents

intents = discord.Intents.all()

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

> 4014 | Disallowed intent(s) 
> You sent a disallowed intent for a Gateway Intent. You may have tried to specify an intent that you have not enabled or are not whitelisted for.

## System Information

- Python v3.8.2-final
- discord.py v1.5.0-final
- aiohttp v3.6.2
- system info: Windows 10 10.0.19041

**Comment by fofofofofofofofo** [comment]
FYI you're looking at the wrong event code, 4014 for voice is `Disconnected - Either the channel was deleted or you were kicked. Should not reconnect.`.

**Comment by TimK50** [comment]
> 
> 
> FYI you're looking at the wrong event code, 4014 for voice is `Disconnected - Either the channel was deleted or you were kicked. Should not reconnect.`.

But in log it recieved by discord.gateway

**Comment by pac-234** [comment]
I have the exact same issue, here are my logs:

> 
> 2020-10-09 08:27:10,102:DEBUG:discord.client: Dispatching event socket_response
> 2020-10-09 08:27:10,103:DEBUG:discord.client: Dispatching event voice_state_update
> 2020-10-09 08:27:10,105:DEBUG:discord.gateway: Updating our voice state to {'op': 4, 'd': {'guild_id': 102874787014956544, 'channel_id': 103888806519795712, 'self_mute': False, 'self_deaf': False}}.
> 2020-10-09 08:27:10,106:DEBUG:discord.client: Dispatching event socket_raw_send
> 2020-10-09 08:27:10,251:DEBUG:discord.client: Dispatching event socket_raw_receive
> 2020-10-09 08:27:10,252:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': 'VOICE_STATE_UPDATE', 's': 11, 'op': 0, 'd': {'member': {'user': {'username': 'Metheros Bot', 'id': '293345489384898571', 'discriminator': '5834', 'bot': True, 'avatar': 'bc002bef23da9a121f3fb056a6a4af7c'}, 'roles': ['341596227269427210'], 'nick': 'Mebot', 'mute': False, 'joined_at': '2017-07-29T11:46:43.889000+00:00', 'hoisted_role': '341596227269427210', 'deaf': False}, 'user_id': '293345489384898571', 'suppress': False, 'session_id': 'ca8505b0d58d51a08b2d72bf64f1687d', 'self_video': False, 'self_mute': False, 'self_deaf': False, 'mute': False, 'guild_id': '102874787014956544', 'deaf': False, 'channel_id': '103888806519795712'}}
> 2020-10-09 08:27:10,253:DEBUG:discord.client: Dispatching event socket_response
> 2020-10-09 08:27:10,254:DEBUG:discord.client: Dispatching event voice_state_update
> 2020-10-09 08:27:10,255:DEBUG:discord.gateway: Received WSMessage(type=<WSMsgType.CLOSE: 8>, data=4014, extra='Disconnected.')
> 2020-10-09 08:27:10,256:INFO:discord.voice_client: Disconnecting from voice normally, close code 4014.

**Comment by EvieePy** [comment]
Cannot reproduce.

**Comment by fofofofofofofofo** [comment]
This appears to happen only in guilds that have a different voice server for each voice channel

**Comment by TimK50** [comment]
> 
> 
> This appears to happen only in guilds that have a different voice server for each voice channel

So how to deal with this problem?

**Comment by pac-234** [comment]
> 
> 
> This appears to happen only in guilds that have a different voice server for each voice channel

Interesting, how to check which Server a channel is on?

**Comment by MinnDevelopment** [comment]
Discord will send a new VOICE_SERVER_UPDATE when the channel has a different voice server. It will close the old connection with a 4014 and the client needs to open a new connection when the server update arrives. The order of these events is not defined, from what I could tell. Correct me if I'm wrong but it seems like this will be an issue since additional VOICE_SERVER_UPDATEs are ignored by default here: https://github.com/Rapptz/discord.py/blob/2e06239d3c9c62887e479a21a9fd5bd4e7c6e473/discord/voice_client.py#L265-L267

Maybe, it would make sense to compare the new voice server update data to the existing connection details and update them accordingly, instead of just ignoring it.

**Comment by xFranciB** [comment]
> To fix this the connection has to be re-established when a VOICE_SERVER_UPDATE with a different endpoint is received.

I see what you mean @MinnDevelopment, but how do you do that? The endpoint servers are different on my main server, but then I tried the same thing on another server and it didn't leave on its own because the endpoint server were the same...
How do I set the same endpoint server for all voice channels? I don't think that's even possible.

**Comment by MinnDevelopment** [comment]
> How do I set the same endpoint server for all voice channels? I don't think that's even possible.

You don't. The library has to handle it.

**Comment by xFranciB** [comment]
> You don't. The library has to handle it.

Soo... this is a bug and we just have to wait for a fix, right?

**Comment by pac-234** [comment]
Thats how i understand it, but maybe we can get confirmation from somebody responsible?

**Comment by TimK50** [comment]
VoiceClient doesn't catch event to change voice server when moving bot. It works only with connect by method.

**Comment by cheez3d** [comment]
> VoiceClient doesn't catch event to change voice server when moving bot. It works only with connect by method.

Using a `disconnect` followed by a `connect` to the new voice channel instead of using `move_to` directly is a good workaround for now. The issue is that when you manually drag and drop the bot between 2 voice channels that are on different endpoint servers, it is equivalent to what `move_to` would do and the bot still disconnects.

**Comment by pac-234** [comment]
thanks for the quick fix!
