### ISSUE TITLE
Bot returns incorrect number of users in a voice channel after joining if users are already in channel.

### ISSUE THREAD

**Issue by yannickgloster** [Rapptz/discord.py#5913]
## Summary

A bot returns incorrect number of users in a voice channel after joining if users are already in channel when the bot joins and the call the bot from the channel

## Reproduction Steps
CODE:
```python
from discord.ext import commands

bot = commands.Bot(command_prefix='$')

@bot.command()
async def test(ctx):
    print(len(ctx.author.voice.channel.members))

bot.run('your token here')
```

1) 2 Users join voice channel.
2) Start Bot
3) Have a user call `$test`

## Expected Results

Expect the console output to be `2`

## Actual Results

Console output `0`

## Intents

```
        self.intents.members = True
        self.intents.presences = False
```

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

```
- Python v3.8.3-final
- discord.py v1.5.0-final
- aiohttp v3.6.2
- system info: Linux 5.4.0-1025-azure #25~18.04.1-Ubuntu SMP Sat Sep 5 15:28:57 UTC 2020
```

**Comment by SebbyLaw** [comment]
I can't reproduce this. Make sure you have member intents enabled both in your code and in the developer portal.

Your discord.py version in your System Information is 1.4.1. Intents are not introduced until v1.5, so make sure your library is up to date.

**Comment by yannickgloster** [comment]
@SebbyLaw 
My bad, I am using pipenv and I blindly copied the command to get the version. Here is the correct version
```
- Python v3.8.3-final
- discord.py v1.5.0-final
- aiohttp v3.6.2
- system info: Linux 5.4.0-1025-azure #25~18.04.1-Ubuntu SMP Sat Sep 5 15:28:57 UTC 2020
```

**Comment by yannickgloster** [comment]
@SebbyLaw 
Intents are also set
![Image](https://i.imgur.com/1LXOX93.png)

**Comment by yannickgloster** [comment]
@SebbyLaw
Also added new code to test
```python
from discord.ext import commands

bot = commands.Bot(command_prefix='$')

@bot.command()
async def test(ctx):
    print(len(ctx.author.voice.channel.members))

bot.run('your token here')
```

**Comment by SebbyLaw** [comment]
Your test code does not declare intents.

**Comment by yannickgloster** [comment]
Looks like in my original bot code, I am setting the intents wrong. My bad
