### ISSUE TITLE
PEP 614

### ISSUE THREAD

**Issue by j0hnmeow** [Rapptz/discord.py#5916]
## The Problem

Checking if at least one of checks passes

## The Ideal Solution

PEP 614 (implemented in Python 3.9) relaxes decorator syntax, allowing writing things like 
```py
@check1 | check2
async def cmd(ctx):
    pass
```

## The Current Solution

```py
@check_any(check1, check2)
async def cmd(ctx):
    pass
```
## Summary

Implement `__or__` for all callables returned from [`check`](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.check)

**Comment by Rapptz** [comment]
This is not good. Also the PEP 614 just relaxes grammar and 3.9 is not the minimum version for the library.

**Comment by j0hnmeow** [comment]
> 3.9 is not the minimum version for the library.

But that won't break code on lower versions

**Comment by j0hnmeow** [comment]
And why is it not good?

**Comment by korochun** [comment]
Agreed. Implementing `__or__` won't hurt Python 3.8- users, but definitely would benefit 3.9+ users.

**Comment by BluePhoenixGame** [comment]
> Agreed. Implementing `__or__` won't hurt Python 3.8- users, but definitely would benefit 3.9+ users.

It needs to not hurt Python 3.5.3 users which is the lowest requirement for discord.py

**Comment by j0hnmeow** [comment]
> > Agreed. Implementing `__or__` won't hurt Python 3.8- users, but definitely would benefit 3.9+ users.
> 
> 
> 
> It needs to not hurt Python 3.5.3 users which is the lowest requirement for discord.py

I don't see how can it hurt them. Also Python 3.5 itself is not supported.

**Comment by Gobot1234** [comment]
I personally do not agree with this, the proposed syntax is no better than the current option.

**Comment by j0hnmeow** [comment]
A lot of people will find it more intuitive

**Comment by numbermaniac** [comment]
> > It needs to not hurt Python 3.5.3 users which is the lowest requirement for discord.py
> 
> I don't see how can it hurt them. Also Python 3.5 itself is not supported.

At https://github.com/Rapptz/discord.py#installing it says that 3.5.3 or higher is supported, so your statement isn't true at all.

**Comment by j0hnmeow** [comment]
> > > It needs to not hurt Python 3.5.3 users which is the lowest requirement for discord.py
> 
> > 
> 
> > I don't see how can it hurt them. Also Python 3.5 itself is not supported.
> 
> 
> 
> At https://github.com/Rapptz/discord.py#installing it says that 3.5.3 or higher is supported, so your statement isn't true at all.

Which of them? 
1. I tried using a library with a fix on Python 3.5, it did work
1. Python 3.5 reached end of life on 30/09/2020

**Comment by iomintz** [comment]
Danny has stated on multiple occasions that he doesn't care about official EOL dates and will continue to support older versions until it becomes infeasible to do so.

**Comment by j0hnmeow** [comment]
> Danny has stated on multiple occasions that he doesn't care about official EOL dates and will continue to support older versions until it becomes infeasible to do so.

3.5 still won't break

**Comment by SebbyLaw** [comment]
The fact that it doesn't break previous versions is irrelevant if the library maintainer doesn't want the syntax to be used.

The fact that this issue is closed should speak volumes. Feel free to fork the library and implement whatever syntax support you desire, after all, it is open source.
