### ISSUE TITLE
A Member property called is_online

### ISSUE THREAD

**Issue by LakshyaShastri** [Rapptz/discord.py#5917]
## The Problem

There is no quick way to check if a member is online or not 

## The Ideal Solution

Giving `Member` a property called `is_online`, this also increases readability since currently, you have to do the following to check if someone's online

## The Current Solution

Currently, you'd have to check if the member's status is online, idle, or dnd to determine if they're online. 

## Summary

This can be made much easier if `Member` could just have an `is_online` property which would simply return True or False depending on their status

**Comment by AbstractUmbra** [comment]
I see no benefit here, this is extremely trivial to implement:

```py
Member.status is not discord.Status.offline
>>> False # because they are online, idle or dnd
```

The same check can be switch to `is discord.Status.online` if you only care about online (green).

**Comment by Rapptz** [comment]
This is too niche.
