### ISSUE TITLE
Unexpected Behavior for ext.Bot.command

### ISSUE THREAD

**Issue by jeriewang** [Rapptz/discord.py#5919]
## Summary

It seems that the `bot.command` decorator (or perhaps the entire `Command` class in general) does an unexpected thing to function argument based on annotation, which is not documented anywhere. I'm not completely sure if this is a documentation issue or something else, and the fact that it extracted the first possibility of a `Union` and cast the `arg` to it is just bizarre and can cause some hard-to-track-down bugs (as it already did in my code).  

## Reproduction Steps

```py
from discord.ext import commands
from dataclasses import dataclass
from typing import Union


@dataclass
class Foo:
    bar: str = 'bar'
    baz: str = 'baz'


bot = commands.Bot('')


@bot.command()
async def func1(ctx: commands.Context, *, arg):
    print(type(arg)) # str


@bot.command()
async def func2(ctx: commands.Context, *, arg: str):
    print(type(arg)) # str


@bot.command()
async def func3(ctx: commands.Context, *, arg: Union[Foo, str]):
    print(type(arg)) # Foo


@bot.command()
async def func4(ctx: commands.Context, *, arg: Union[str, Foo]):
    print(type(arg)) # str


bot.run(TOKEN)
```

## Expected Results

The type of `arg` in `func3` is `str`.

## Actual Results

As annotated in the code snippet

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

```
- Python v3.8.0-final
- discord.py v1.4.0-final
- aiohttp v3.6.2
- system info: Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64
```

**Comment by Rapptz** [comment]
There's no conversion hint in the code to go from string to Foo so it fails and then falls back to `str`. Unsure where this was implicated to work in the documentation.

**Comment by Rapptz** [comment]
Sorry, on second read this seems to be an interaction with the generated constructor of the data class. Foo(str) is valid so it constructs it. This is the same mechanism that allows e.g. int or any callable to work.

**Comment by jeriewang** [comment]
I feel it shouldn't do the typecast at all because the documentation says (with no indication that it reads type annotation at all)

> When you want to handle parsing of the argument yourself... you can ask the library to give you the rest as a single argument

And I was very unexpected to find that the argument it received was not a string at all. In my particular use case, I also called this function from somewhere else because I was providing a shortcut, in which case I passed in something other than a string. I was hoping that I could use type checking to differentiate whether the function was called by `discord.py` or called by my code.

**Comment by Rapptz** [comment]
All arguments in the library undergo conversion. This is by design. If the documentation implicates that this isn't the case then it needs to be changed because this has been the case for 5 years.

**Comment by jeriewang** [comment]
I think the misleading part in the documentation was the "handle parsing of the argument yourself", which gave me the impression that I would always get an unprocessed string.

**Comment by Rapptz** [comment]
Given the context that paragraph appears on it's talking about handling of quotes and whitespace.
