### ISSUE TITLE
How do I get emoji unicodes

### ISSUE THREAD

**Issue by PicklesJars** [Rapptz/discord.py#592]
How do I get emoji unicodes so I can add reactions to messages.

**Comment by leovoel** [comment]
http://www.fileformat.info/info/emoji/list.htm

in the pages that the fields in the "Unicode" column link to, there's even literals you can copy to your scripts.

**Comment by PicklesJars** [comment]
Yeah, but I'm looking for the letter emoji's and there are none in that.

**Comment by leovoel** [comment]
http://www.fileformat.info/info/unicode/char/search.htm?q=regional+indicator&preview=entity

**Comment by PicklesJars** [comment]
Oh... Well... Thank you.
