### ISSUE TITLE
Random module

### ISSUE THREAD

**Issue by ItzZayanPlayz** [Rapptz/discord.py#5922]
When I am doing pip3 install random it is saying I need a another version of it can you tell the version or something for creating a discord bot?

**Comment by xFranciB** [comment]
> When I am doing pip3 install random it is saying I need a another version of it can you tell the version or something for creating a discord bot?

What do you mean by "pip3 install random"? There is no library named random.
If you want to know what version of discord.py you should be using, go for the latest (1.5.0)

If you are having troubles with pip3, you shouldn't be asking on this repository, but here are some things you could try to solve your issue:

• If it's a pip3 version issue, you can always update it with:
`python -m pip install --upgrade pip`

• If it's a Python version info, you can always update it on [Python's official website](https://www.python.org/)

• If you are having trouble with discord.py's version, you can always update it with:
`python -m pip install --upgrade discord.py[voice]`

If you want to get a full guide on how to create a discord bot, you should probably check out a tutorial on YouTube (make sure they're running your same version) and check out the [official documentation](https://discordpy.readthedocs.io/en/latest/).

**Comment by ItzZayanPlayz** [comment]
thx
