### ISSUE TITLE
guild.get_member() does not return member

### ISSUE THREAD

**Issue by shironats** [Rapptz/discord.py#5924]
As the title says, I have a line that goes like this
`bot.get_guild(ID).get_member(ID).display_name`
and it keeps returning None instead of Member.

`bot.get_user(ID)` works fine, but what happened?
 
I tried this a few days ago and everything ran fine.

I have checked the other functions and the only error that pops up is about the guild.get_member() function.
Any help is much appreciated, thank you.

**Comment by SebbyLaw** [comment]
If you are on discord.py version v1.5 or above you will need to enable [member intents](https://discordpy.readthedocs.io/en/latest/intents.html#member-cache).

For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by shironats** [comment]
thank you for the explanation
