### ISSUE TITLE
guild.members returns only author on Python3.7/3.8

### ISSUE THREAD

**Issue by pocc** [Rapptz/discord.py#5928]
## Summary

message.guild.members fails on python3.7, python3.8, but not python3.6. This is on a VPS running Ubuntu 20.04.1.

## Reproduction Steps

I am running this on my testing server.

### Simple script to print guild members

```python
import discord
from keys import TOKEN
client = discord.Client()

@client.event
async def on_ready():
    print(f'{client.user.name} has connected to Discord!')

@client.event
async def on_message(message):
    print(message.guild.members)

client.run(TOKEN)
```

### Shell

```bash
$ python3.6 my_discord_bot.py
bosspile has connected to Discord!
[14 elements, deleted for privacy]
$ python3.7 my_discord_bot.py
bosspile has connected to Discord!
[<Member id=<id> name='<name>' discriminator='5734' bot=True nick=None guild=<Guild id=<guild ID> name='testing' shard_id=None chunked=False member_count=14>>]
$ python3.8 my_discord_bot.py
bosspile has connected to Discord!
[<Member id=<id> name='<name>' discriminator='5734' bot=True nick=None guild=<Guild id=<guild ID> name='testing' shard_id=None chunked=False member_count=14>>]
```

member id, name, guild ID removed for privacy.

## Expected Results

See above

## Actual Results

See above

## Intents

Default

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible. (people do this???)
- [x] I have provided the intents that my bot is using.

## System Information

```bash
$ python3.6 -m discord -v
- Python v3.6.12-final
- discord.py v1.4.0-final
- aiohttp v3.6.2
- system info: Linux 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020
$ python3.7 -m discord -v
- Python v3.7.9-final
- discord.py v1.5.0-final
- aiohttp v3.6.3
- system info: Linux 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020
$ python3.8 -m discord -v
- Python v3.8.5-final
- discord.py v1.5.0-final
- aiohttp v3.6.3
- system info: Linux 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020
```

**Comment by SebbyLaw** [comment]
Your issue is caused by a lack of Intent subscription. As noted in the [version 1.5 changelog](https://discordpy.readthedocs.io/en/latest/whats_new.html#v1-5-0) "API Changes" section, you are required to pass the required [`Intents`](https://discordpy.readthedocs.io/en/latest/api.html?highlight=intents#discord.Intents) to your `discord.Client` constructor to receive this information from the gateway.

This is not an issue with discord.py. For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by pocc** [comment]
This is a breaking change from 1.4 to 1.5. Why wasn't the version incremented to 2.0.0?

Annoyed at breaking changes, but I'll close the issue.

**Comment by Rapptz** [comment]
This change of internal API behaviour was forced upon by Discord, not the library. The external facing API of the library did not change so no version bump denoting that was given.

**Comment by pocc** [comment]
Per the first google result for "what is a breaking api change" , https://community.blackbaud.com/blogs/69/3219#:~:text=We%20define%20a%20breaking%20change,consider%20it%20a%20breaking%20change.

> We define a breaking change as any change to an API that could potentially cause failures in the applications that consume that API.

**Comment by Rapptz** [comment]
The definition used for the library is in the [documentation](https://discordpy.readthedocs.io/en/latest/version_guarantees.html). Arguing about this won't change anything. This isn't the first internal API breaking change that Discord has done that I've done without a version bump but this one is definitely one of the most annoying ones not just from your angle but from mine as well.
