### ISSUE TITLE
PermissionOverwrite's __eq__ has a logic error

### ISSUE THREAD

**Issue by egnor** [Rapptz/discord.py#5929]
## Summary

The `PermissionOverwrite` class's `__eq__` method gives a false negative (says two things are not equal when they are) if one instance has had a permission set to None, where the other has never had it set.

## Reproduction Steps

```
% python
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import discord
>>> o1 = discord.PermissionOverwrite(read_messages=None)
>>> o2 = discord.PermissionOverwrite()
>>> o1 == o2
False
```

## Expected Results

`True`

## Actual Results

`False`

## Intents

N/A

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

```
- Python v3.8.2-final
- discord.py v1.5.0-final
- aiohttp v3.6.2
- system info: Linux 5.4.0-26-generic #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020
```

**Comment by Rapptz** [comment]
I suppose this is a difference in expectations. To me, the mapping is an explicit tribool plus an evicted state (i.e. the keys are not there). It's a bit of a hold-over, since I never did end up using the third state for much so I guess the latter two (None and evicted) should be merged into one.

**Comment by egnor** [comment]
My case for removing/collapsing the None & evicted states would be:
- the quadstate behavior isn't documented
- it's inconsistent with Permissions (where False is the same as not-populated)
- there's no way to delete a key, so you can't actually set that fourth state (except by reconstructing the object)
- it's not consistent with Discord itself -- you can't round-trip that fourth state through Discord's pair-of-ints representation

Given all of the above, I'd make the case it's better and less surprising to make assigning None remove the key (the way assigning False "removes the key" for Permissions -- though of course internally different things are happening).

**Comment by egnor** [comment]
🎉 thanks!!
