### ISSUE TITLE
Getting unique ID for every server

### ISSUE THREAD

**Issue by SnowySailor** [Rapptz/discord.py#593]
I'd like to be able to get the unique ID of every server that a message comes from so that I can separate them into individual files for a bot I am writing. So I have a feeling servers have integer ID's in the backend of Discord, but the Message class' `server` attribute is a string with the name of the server in it (according to this: http://discordpy.readthedocs.io/en/latest/api.html?highlight=message#message).

Is there any way I can get the unique ID of each server so that if a server's name changes it won't change the functionality of the bot?

This would be using the on_message event handler and also some commands.

**Comment by khazhyk** [comment]
message.server is not a string, it is of type "server"

You want `message.server.id`.

Keep in mind, for direct messages, `message.server == None`

**Comment by SnowySailor** [comment]
Thanks. I just did a print(msg.server) and got a string printed to my screen so I assumed it was just a string. I closed the issue because I realized that it was in fact a server object. Thanks.
