### ISSUE TITLE
member.roles is [None] when member are requested with guild.fetch_members

### ISSUE THREAD

**Issue by iElden** [Rapptz/discord.py#5931]
## Summary

**The member indent is turned on**
When i request member list through guild.fetch_members, i succesfully got my whole members but when i want to acces their roles, i got a unexcepted result :

## Reproduction Steps

    guild : discord.Guild = client.get_guild(GUILD_ID)
    members = await guild.fetch_members(limit=20000).flatten()
    for i in members:
        print(i.roles)

## Expected Results

    [<discord.Role>, ...]
    [<discord.Role>, ...]

## Actual Results

    [None]
    [None]

## Intents

    client = discord.Client(intents=discord.Intents(members=True))

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python v3.7.3-final
- discord.py v1.5.0-final
- aiohttp v3.6.3
- system info: Windows 10 10.0.18362

**Comment by AbstractUmbra** [comment]
You require more than just the Members intent for this action.
 Specifically you need the [guilds intent](https://discordpy.readthedocs.io/en/latest/api.html?highlight=intents#discord.Intents.guilds).

**Comment by iElden** [comment]
My bad, i missread the part ``Guild and all its attributes.``
Thank you @AbstractUmbra and sorry for the issue
