### ISSUE TITLE
Improvement on ID Check within object.py

### ISSUE THREAD

**Issue by Metropass** [Rapptz/discord.py#5932]
## The Problem

**Check if ID is an 18 digit integer**

## The Ideal Solution

Check if ID is 18 digits, otherwise, Raise a `ValueError` 

## The Current Solution

We just pass an ID, and check if it's of type `int`. If True, we assign ID to it's appropriate member, if False, raise `TypeError`. This was a fix for #4002.
## Summary

From what I understand about Discord, ID's are 18 digits and the current system we have assumes that the ID is correct. 
We can check if the ID is appropriate by checking if it contains the correct amount of digits. If not, we can raise a `ValueError`

**Comment by Metropass** [comment]
This is a 5m fix that I can draw up quickly, if need be.

**Comment by Vexs** [comment]
IDs have no set length so this is invalid by default.

**Comment by hamza1311** [comment]
> IDs have no set length so this is invalid by default. 

They're supposed to be 64bit integers so that can be checked
