### ISSUE TITLE
Add type hints

### ISSUE THREAD

**Issue by ThatXliner** [Rapptz/discord.py#5935]
## The Problem

I use a static type checker called [mypy](https://mypy.readthedocs.io/en/stable/). Unless you are trying to [support old python versions](https://python3statement.org/) (which you really shouldn't), [type hints](https://docs.python.org/3/library/typing.html) should most definitely be added. It'll actually make more sense for API users if they're using code linters. That way, they can see what type of arguments the parameters need.

## The Ideal Solution

Just add type hints as specified by [PEP 484](https://www.python.org/dev/peps/pep-0484/), [PEP 526](https://www.python.org/dev/peps/pep-0526/), [PEP 544](https://www.python.org/dev/peps/pep-0544/), [PEP 586](https://www.python.org/dev/peps/pep-0586/), [PEP 589](https://www.python.org/dev/peps/pep-0589/), and [PEP 591](https://www.python.org/dev/peps/pep-0591/) directly on your code.

## The Current Solution

Because it may be tedious to add type hints to existing code, you should use the `stubgen` utility bundled with `mypy` to generate type stubs and edit those accordingly.

## Summary

We just need to add [type hints](https://docs.python.org/3/library/typing.html) to the code.

**Comment by Gobot1234** [comment]
See https://github.com/BryanForbes/discord.py-stubs

**Comment by ThatXliner** [comment]
Oh nice! Thank you! Maybe if you update the README, we won't have future false positives like this anymore.

**Comment by richfromm** [comment]
Coming to this a while later, just noting in case someone else sees this, it appears that type hints are indeed present as of 2.0.0
