### ISSUE TITLE
How to terminate event 

### ISSUE THREAD

**Issue by latusaki** [Rapptz/discord.py#594]
I have some logic being called `on_ready`, but I don't know how to cleanly exit the script when finished. Calling `await client.logout()` does not seem to have any effect, and sys.exit() works but error is thrown "Task was destroyed but it is pending!"

**Comment by Rapptz** [comment]
`Client.logout` **is** the way to terminate the connection to Discord.

**Comment by latusaki** [comment]
Should that be exiting the event thread then ? or is sys.exit() the only way to do it ?

**Comment by latusaki** [comment]
Script has the following code, but does not exit.
```
@client.event
async def on_ready():
    print('------')
    print('Logged in as')
    print(client.user.name)
    print('------')
    await message_all_clients() 
    print('Calling logout') # this prints 
    await client.logout()

try:
    client.run(EMAIL, PASSWORD)
except aiohttp.errors.ClientOSError:
    log_error('An error occured while ..'
```

**Comment by Rapptz** [comment]
That will exit.

`Client.run` then cleans up all remaining tasks.
