### ISSUE TITLE
[Feature Request] Message.deleted

### ISSUE THREAD

**Issue by tiritto** [Rapptz/discord.py#5944]
## The Problem

While I've been working on a bot I came to the point where I wanted to postpone a function execution within my `on_message()` listener by a few seconds just to make sure that the message was not instantly deleted, for example by another bot that would recognize the message as his own command and clean it, or a normal member deleting his own message after a short moment. That's when I realized that there is no easy way to actually check if cached message has been deleted or not, so in order to achieve my goal I actually have to create separate event listener and create my own list of deleted messages that I could check against.

## The Ideal Solution

New “deleted” attribute for Message objects that would contain a simple boolean that informs whether the Message has been deleted or not.

## The Current Solution

To achieve this functionality right now, you would have to create a new event listener for `on_message_delete()` and within it create your own mechanism, for example by creating a set of message id's, to “remember” all recently removed messages.

## Summary

Before I switched to Discord.py I've been using Discord.js, and they implemented such functionality in their framework under simple `<Message>.deleted` attribute, so I figured it might make a good feature request.

**Comment by lganWebb** [comment]
A hacky way to do this without lib modification would be to use `discord.Client.wait_for("message_delete", timeout=5, check=lambda m: m.id == message.id)` and catch an `asyncio.TimeoutError`.

This means that you can wait for however long your timeout is, and if it isn’t deleted before the timeout is raised then you can continue doing whatever you need.

Probably not the best solution though.

**Comment by tiritto** [comment]
> A hacky way to do this without lib modification would be to use `discord.Client.wait_for("message_delete", timeout=5, check=lambda m: m.id == message.id)` and catch an `asyncio.TimeoutError`.

That's a great approach idea for such case actually, thank you! You just saved me from overcomplicating my code :)

That being said, I still believe that `Message.deleted` could make a nice addition to the framework, especially since it just mostly a matter of an extra boolean. The only situation in which it wouldn't make much sense would be if Discord.py just removes the Message from the cache altogether, in which case the whole suggestion probably wouldn't make much sense. I'm not exactly sure on how cached messages are handled in d.py however.

**Comment by AbstractUmbra** [comment]
The issue with your suggestion of `Message.deleted` is that Message objects are stateful.
Message.deleted would never be updated without re-fetching the message first, which is what you'd have to do anyway if you wanted to test if it were deleted.

**Comment by Rapptz** [comment]
I'm not a fan of providing this since it gives a false sense of security. Two different objects fetched will have two different values for this boolean depending on which one is being tracked internally by the library. Not to mention when an object cycles out of the message cache and then gets deleted. 

The discord server is the authoritative figure for determining whether something is actually deleted so it's best to stick with that.

Note that something existing in discord.js is not a decent justification for me to have it in this library.
