### ISSUE TITLE
Bot user is deleted from Member cache when disconnecting from voice

### ISSUE THREAD

**Issue by tctree333** [Rapptz/discord.py#5949]
## Summary
Calling `client.disconnect()` causes the bot user to be removed from the member cache and `ctx.guild.me` to return `None`.

## Reproduction Steps
I have a disconnect function:
```python
async def disconnect(ctx):
    client = await get_voice_client(ctx) # returns a VoiceClient
    client.stop()
    print("1", ctx.guild.me)
    await client.disconnect()
    print("2", ctx.guild.me)
    await ctx.send("Bye!")
    print("3", ctx.guild.me)
```
Which outputs:
```
1 botuser#discrim
2 botuser#discrim
3 None
```
Commenting out the `await client.disconnect()` line causes all 3 print statements to print the `botuser#discrim` as expected. 

There also seems to be a 0.1 - 0.2 second delay between calling `client.disconnect()` and when `ctx.guild.me` starts returning `None`, so the 2nd print outputs the expected result while the 3rd print does not. Replacing `await ctx.send("Bye!")` with `await asyncio.sleep(0.2)` also causes the 3rd print to become `None`, while sleeping for only 0.1 seconds doesn't.

## Expected Results
`ctx.guild.me` should return the Member version of the current user (the bot).

## Actual Results
`ctx.guild.me` is None after the `ctx.send()` and the `client.disconnect()`.

## Intents
```python
intent: discord.Intents = discord.Intents.none()
intent.guilds = True
intent.messages = True
intent.voice_states = True
```
I'm not using the Member intent, but the docs say that the bot's own member should always be cached.

## Checklist
- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information
```
- Python v3.7.9-final
- discord.py v1.5.0-final
- aiohttp v3.6.2
- system info: Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64
```

**Comment by Rapptz** [comment]
This was fixed already in master and will be in 1.5.1.
