### ISSUE TITLE
on_guild_join does not get a list of all server members

### ISSUE THREAD

**Issue by SteweX** [Rapptz/discord.py#5951]
Hi, after the update, I just can't get a list of all server members when the bot connects to it

```
import discord
intents = discord.Intents.default()
intents.members = True
intents.guilds = True
```

Here is the event itself
```
@bot.event
async def on_guild_join(guild):
    for member in guild.members:
        print('-------------------')
        print (member.id)
```
For some reason, it only displays the bot itself
And I don't know what to do, it's either a bug, or I'm crooked

**Comment by averwhy** [comment]
have you set your intents on the developer portal?

**Comment by SteweX** [comment]
![image](https://user-images.githubusercontent.com/71728819/96459421-c51ef980-122a-11eb-8131-5a46fa564b65.png)
Yes

**Comment by averwhy** [comment]
show your bot constructor

**Comment by SteweX** [comment]
bot constructor? I don't quite understand

**Comment by scrazzz** [comment]
This is your bot constructor 👇🏼
`bot = commands.Bot(command_prefix='!', intents=intents)`

This is not the place to ask for #help btw. Join the discord.py server - https://discord.gg/dpy

**Comment by SteweX** [comment]
![image](https://user-images.githubusercontent.com/71728819/96460542-fa781700-122b-11eb-8d2e-7ce9a6a449ec.png)

**Comment by averwhy** [comment]
join https://discord.gg/dpy and close this

**Comment by SteweX** [comment]
![image](https://user-images.githubusercontent.com/71728819/96460850-56db3680-122c-11eb-8bc5-183bbdf44f2d.png)
Ок :(

**Comment by monkeyboy2805** [comment]
you need to use intents.presences else it won't work

**Comment by SteweX** [comment]
Now it only displays one random participant

**Comment by SebbyLaw** [comment]
Duplicate of #5867.

This is not an issue with discord.py. GitHub issues for this repository should be used to report issues with this library.

For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.
