### ISSUE TITLE
Not connected to voice when moving bot to another voice channel

### ISSUE THREAD

**Issue by Travisivart** [Rapptz/discord.py#5953]
## Summary
I believe this may be somewhat related to #5904 
I was using discord.py 1.5.0 and experienced the issue in #5904 where upon moving the bot either with the move_to method or manually moving using right click -> move to the bot would connect to the channel and then immediately disconnect.

Once upgrading to 1.5.1 the above issue was resolved, however, there is still some oddness when moving the bot. Sometimes the bot will move correctly and other times it encounters an error:

## Reproduction Steps

Start a bot and have it play audio. Use a command to execute the move_to method or manually move the bot to another voice channel while it is playing audio.

Usually, whatever audio is currently playing will end and the play methods after=lambda function will execute, in my case it will move onto the next song in the queue.

This is tricky to reproduce because you have to keep moving the bot between channels until it occurs. Occasionally the bot will encounter the error described above. This would sometimes occur on the first move_to and on other times would take 10 or even 20 moves before the error would occur.

## Expected Results

There are two things which I would expect to occur.

Previously (in 1.4.0) when the bot would move between channels with the move_to command, the audio stream wouldn't end and the after=lambda would not execute moving onto the next audio stream. It would rather flawlessly just continue the current audio stream. Now the audio stream ends and the next one begins when switching voice channels. I have been able to somewhat mitigate this by executing a pause() before executing the move_to(new_voice_channel) then using a resume() afterwards, however I still encounter the above Not connected to voice error on occasion.

Secondly, I would expect the bot to move to a channel without the strange occasional error described above.

## Actual Results

On occasion, sometimes on the first move_to, other times, after 10 or 20 moves the bot will encounter an error:

```sh
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/discord/player.py", line 598, in run
    self._do_run()
  File "/usr/lib/python3.8/site-packages/discord/player.py", line 591, in _do_run
    play_audio(data, encode=not self.source.is_opus())
  File "/usr/lib/python3.8/site-packages/discord/voice_client.py", line 635, in send_audio_packet
    self.socket.sendto(packet, (self.endpoint_ip, self.voice_port))
TypeError: str, bytes or bytearray expected, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/discord/player.py", line 611, in _call_after
    self.after(error)
  File "/tga-bot/TGA-Bot/bot/features/music/music.py", line 96, in <lambda>
    after=lambda e: self._finished_song())
  File "/tga-bot/TGA-Bot/bot/features/music/music.py", line 102, in _finished_song
    self._play_next()
  File "/tga-bot/TGA-Bot/bot/features/music/music.py", line 92, in _play_next
    self.voice_client.play(discord.PCMVolumeTransformer(
  File "/usr/lib/python3.8/site-packages/discord/voice_client.py", line 552, in play
    raise ClientException('Not connected to voice.')
discord.errors.ClientException: Not connected to voice.
```

## Intents

Intents are not passed and thus defaults to every intent being enabled except privileged as described [here](https://discordpy.readthedocs.io/ja/latest/intents.html)

## Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have provided the intents that my bot is using.

## System Information

- Python v3.8.5-final
- discord.py v1.5.1-final
- aiohttp v3.6.2
- system info: Linux 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020

**Comment by Rapptz** [comment]
This is probably due to the connected flag that the player thread using not being cleared during the initial reconnect but at a later point when the websocket connection is being initialized.

**Comment by TimK50** [comment]
I've temporary fixed it with on_voice_state_update event (move back track to queue and then move back to the time)
