### ISSUE TITLE
Turning on presence intent makes on_ready take forever to fire and prevents member events from firing

### ISSUE THREAD

**Issue by atarashansky** [Rapptz/discord.py#5954]
I wanted to track the number of online members on my server, so I turned on the presence intent. However, doing that made `on_ready` take forever to fire and also prevented the member intent-related event listeners from working. This is on a server with around 70 members.

On a test server with 2 members, the bot had no issues.

Sorry I can't really give a reproducible example since it's kind of random when the member events stop working.

**Comment by Rapptz** [comment]
There's a template for a reason. I am unsure why you deleted it. This issue is inactionable as-is.
