### ISSUE TITLE
client.get_all_members returns only its own self

### ISSUE THREAD

**Issue by danielthetam** [Rapptz/discord.py#5959]
**CODE**
```
def add_all_users_to_db():
    for member in client.get_all_members():
        print(member.name, member.id)
```
**OUTPUT**
`KnightsRPG 742218608230269060
`
For some reason my bot is returning its own name and id, and it does it three times. Is this a bug?

**Comment by Rapptz** [comment]
Next time you open an issue please do not delete the template. It's there for a reason.

This is a duplicate of https://github.com/Rapptz/discord.py/issues/5867 and the [documentation here](https://discordpy.readthedocs.io/en/latest/intents.html#where-d-my-members-go)

**Comment by danielthetam** [comment]
I see, sorry man. Thanks for letting me know
