### ISSUE TITLE
typing event does not fire for TextChannels if members intents is not enabled

### ISSUE THREAD

**Issue by Willy-C** [Rapptz/discord.py#5965]
## Summary

If members intents is not enabled and the typing occurs in a guild, then the event does not fire because `Guild.get_member` is used, so `member` is None. (The event still fires if typing in DM even with members intent disabled)
https://github.com/Rapptz/discord.py/blob/763d46cd7ab14a4b0345a69fd862de8a4eb6da10/discord/state.py#L1032-L1033
https://github.com/Rapptz/discord.py/blob/763d46cd7ab14a4b0345a69fd862de8a4eb6da10/discord/state.py#L1037-L1039

## Reproduction Steps

1. Have `typing` intents enabled and `members` disabled
2. Have an on_typing or a wait_for('typing')
3. Start typing in a guild

## Expected Results

The event fires

## Actual Results

Nothing happens because `member` is None

## Intents

- Typing enabled
- Members disabled

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

d.py 1.5.1

**Comment by Rapptz** [comment]
There's no good way of doing this at this time. The contract of the event specifies that it has a member parameter, since that contract cannot be met then the event is not fired. If the payload came with a full member object then this problem could be rectified but as far as I'm aware it doesn't.

**Comment by neonoxd** [comment]
could this be mentioned somewhere in the documentation?
