### ISSUE TITLE
Cannot run discord bot, with SSL error.

### ISSUE THREAD

**Issue by CocoaCrispies** [Rapptz/discord.py#5967]
## Summary

Whenever I try to run my discord bot, I get an error from aiohttp, talking about how my SSL certificates are outdated. I tried this on a VPS and local, and same error everytime.

## Reproduction Steps

I simply run by bot's `server.py` file, and get the error. I haven't changed anything and get this error.

## Expected Results

My bot to run normally.

## Actual Results

My error:
` raise ClientConnectorCertificateError(
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '162.159.135.232'. (_ssl.c:1122)")]`

## Intents

N/A

## Checklist

- [ x] I have searched the open issues for duplicates.
- [x ] I have shown the entire traceback, if possible.
- [ x] I have removed my token from display, if visible.
- [ x] I have provided the intents that my bot is using.

## System Information

- Python v3.9.0-final
- discord.py v1.5.1-final
- aiohttp v3.7.0
- system info: Windows 10 10.0.1904`

**Comment by Zomatree** [comment]
downgrade aiohttp to 3.6.3, discord.py's requirements.txt states aiohttp's version should not be 3.7.0

**Comment by CocoaCrispies** [comment]
> downgrade aiohttp to 3.6.3, discord.py's requirements.txt states aiohttp's version should not be 3.7.0

How would I go about doing that?

**Comment by pikaninja** [comment]
you can downgrade with pip, something like pip install aiohttp==3.6.3

**Comment by CocoaCrispies** [comment]
This solved it, ty.

**Comment by Harmon758** [comment]
This was [a bug in aiohttp 3.7.0](https://github.com/aio-libs/aiohttp/issues/5110) that was fixed in aiohttp 3.7.1.
Since [it's now supported](https://github.com/Rapptz/discord.py/commit/7f3737fcc2fc32078b0904131adcaa75d5eda942), upgrading to aiohttp > 3.7.0 should also resolve this issue.

For task list usage, see https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/about-task-lists.
