### ISSUE TITLE
 aiohttp  old version raised via github dependabot

### ISSUE THREAD

**Issue by DavidWylie** [Rapptz/discord.py#5970]
Hi 
The github dependabot has raised the discord.py reliance on aio htto 3.6 as an issue.
Is it possible to build this with 3.7

Thanks

Dependabot  aiohttp release notes details below.
  

  aiohttp 3.7.1 release
    Bugfixes

        Fixed a type error caused by the conditional import of Protocol. [#5111](https://github.com/aio-libs/aiohttp/issues/5111) <https://github.com/aio-libs/aiohttp/issues/5111>_
        Server doesn't send Content-Length for 1xx or 204 [#4901](https://github.com/aio-libs/aiohttp/issues/4901) <https://github.com/aio-libs/aiohttp/issues/4901>_
        Fix run_app typing [#4957](https://github.com/aio-libs/aiohttp/issues/4957) <https://github.com/aio-libs/aiohttp/issues/4957>_
        Always require typing_extensions library. [#5107](https://github.com/aio-libs/aiohttp/issues/5107) <https://github.com/aio-libs/aiohttp/issues/5107>_
        Fix a variable-shadowing bug causing ThreadedResolver.resolve to return the resolved IP as the hostname in each record, which prevented validation of HTTPS connections. [#5110](https://github.com/aio-libs/aiohttp/issues/5110) <https://github.com/aio-libs/aiohttp/issues/5110>_
        Added annotations to all public attributes. [#5115](https://github.com/aio-libs/aiohttp/issues/5115) <https://github.com/aio-libs/aiohttp/issues/5115>_
        Fix flaky test_when_timeout_smaller_second [#5116](https://github.com/aio-libs/aiohttp/issues/5116) <https://github.com/aio-libs/aiohttp/issues/5116>_
        Ensure sending a zero byte file does not throw an exception [#5124](https://github.com/aio-libs/aiohttp/issues/5124) <https://github.com/aio-libs/aiohttp/issues/5124>_
        Fix a bug in web.run_app() about Python version checking on Windows [#5127](https://github.com/aio-libs/aiohttp/issues/5127) <https://github.com/aio-libs/aiohttp/issues/5127>_

**Comment by Taarek** [comment]
Yeah well. ATM it's not possible. Aiohttp 3.7 is Python 3.6+.

Discord.py currently aims to support 3.5.3 (not for too long though).

**Comment by DavidWylie** [comment]
Fair enough.  Happy to close this and happy to test the build when your ready to make the jump

**Comment by jack1142** [comment]
Couldn't d.py lax the requirement to allow both aiohttp 3.6.x and 3.7.x? Or are there some incompatible changes in 3.7 that would require additional maintenance?

**Comment by BluePhoenixGame** [comment]
> Couldn't d.py lax the requirement to allow both aiohttp 3.6.x and 3.7.x? Or are there some incompatible changes in 3.7 that would require additional maintenance?

The incompatible change is that aiohttp requires python 3.6 or more. While discord.py aims to keep its support for 3.5.3

**Comment by jack1142** [comment]
> > Couldn't d.py lax the requirement to allow both aiohttp 3.6.x and 3.7.x? Or are there some incompatible changes in 3.7 that would require additional maintenance?
> 
> The incompatible change is that aiohttp requires python 3.6 or more. While discord.py aims to keep its support for 3.5.3

Yes, that's why I asked about laxing requirement to allow both 3.6.x and 3.7.x. This way, 3.6.x would be installed on Python 3.5 installations and 3.7.x would be installed on Python 3.6+ installations.

**Comment by Rapptz** [comment]
This is doable so I'll keep the issue open until it's done.

**Comment by fabaff** [comment]
The pinning is also blocking the installation of the package on Fedora. Fedora Rawhide ships already `aiohttp-3.7.1`.

**Comment by mikeshardmind** [comment]
rawhide is a daily development build and not a good point of reference, especially when saying "rawhide *already* ships" something. Even so, you're not limited to what fedora packages for your python dependencies.

**Comment by fabaff** [comment]
> rawhide is a daily development build and not a good point of reference

Well, Rawhide will become the next Fedora release and if I want to ship the RPM package of `discord.py` with Fedora 34 support for later aiohttp releases is needed.

**Comment by domnich446** [comment]
NetBeam is a [web development company in UK](https://netbeam.co.uk/website-development/#), specializing in creating custom, high-performance websites tailored to your business needs. With a focus on responsive design, seamless user experiences, and cutting-edge technologies, NetBeam ensures your website not only looks great but also performs exceptionally. Whether you need e-commerce solutions, bespoke web applications, or a complete site redesign, NetBeam provides end-to-end services to help your business thrive online.

**Comment by Toadubuilders** [comment]
The Aiohttp library, a popular asynchronous HTTP client/server framework for Python, has occasionally faced issues related to outdated dependencies. When older versions of Aiohttp have vulnerabilities or compatibility issues, GitHub's Dependabot often flags these in repositories where they are used. Dependabot is an automated tool that monitors dependencies in your project and raises alerts or pull requests to update outdated or insecure packages. For more information, [pleas visit:](https://docs.google.com/spreadsheets/d/1K5nf86Pg-t0MybrQVcHHtXmO8UPkiF56l4JqHw5lqEc/edit?gid=0#gid=0)
