### ISSUE TITLE
guild get_channel voicechannel members does not update correct

### ISSUE THREAD

**Issue by IHASASUSHI** [Rapptz/discord.py#5971]
## Summary
Either the `guild.get_channel([channel id]).members` or the voice `channel.members` does not update what members it can see.

The members it cannot see specifically are those that connected to a voice channel before it has joined.
However, it will recognize the member if bot has seen user join it after once. i.e.
1. Bot joins voice channel
2. User joins voice channel
3. Bot disconnects from voice channel
4. Bot reconnects to voice channel
The bot will be able to still see that user even in they are in a different voice channel

## Reproduction Steps
boot up the bot
have someone join a voice channel
have the bot join after said person has successfully joined the voice channel
check `channel.members`

## Expected Results
the members list should have both the bot and the member

## Actual Results
the members list will only have the bot

## Intents

N/A

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python v3.8.5-final
- discord.py v1.5.1-final
- aiohttp v3.6.2
- system info: Windows 10 10.0.19041

**Comment by Gobot1234** [comment]
Duplicate of #5867

**Comment by IHASASUSHI** [comment]
ah I, see will close.
