### ISSUE TITLE
after parameter of fetch_members doe snot seem to work on datetime objects

### ISSUE THREAD

**Issue by tilnow** [Rapptz/discord.py#5973]
## Summary

discord.py docs say that:

> after (Optional[Union[abc.Snowflake, datetime.datetime]]) – Retrieve members after this date or object. If a date is provided it must be a timezone-naive datetime representing UTC time.

but the following (with prevread=0):
`mem=await g.fetch_members(after=datetime.datetime.fromtimestamp(prevread)).flatten()`
gives:
`    mem=await g.fetch_members(after=datetime.datetime.fromtimestamp(prevread)).flatten() # reads only ones added since prevread
  File "/home/yak/.local/lib/python3.6/site-packages/discord/iterators.py", line 75, in flatten
    item = await self.next()
  File "/home/yak/.local/lib/python3.6/site-packages/discord/iterators.py", line 605, in next
    await self.fill_members()
  File "/home/yak/.local/lib/python3.6/site-packages/discord/iterators.py", line 627, in fill_members
    data = await self.get_members(self.guild.id, self.retrieve, after)
  File "/home/yak/.local/lib/python3.6/site-packages/discord/http.py", line 245, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In after: long value should be greater than or equal to 0.`
>

## Reproduction Steps

the code is above

## Expected Results

to return all members of the guild. i also tried with other dates, like 1973, which gave same error.
2019 worked, _in a sense_, because it returned 304 members. problem is there are >500 members that joined the guild after 1.1.2020

a plain (no "after" parameter) fetch_members returns all the members
## Actual Results
We have logged in as Shepherd#2960 [..... shard_id=None chunked=True member_count=656>]
0 1970-01-01 00:00:00 ### these are prevread and prevread converted to datetime (`print(prevread,datetime.datetime.fromtimestamp(prevread))`)
Traceback (most recent call last):
  File "/home/yak/.local/lib/python3.6/site-packages/discord/client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "shepherd.py", line 49, in on_ready
    await update_database()
  File "shepherd.py", line 108, in update_database
    await read_and_add()
  File "shepherd.py", line 117, in read_and_add
    mem=await g.fetch_members(after=datetime.datetime.fromtimestamp(prevread)).flatten() # reads only ones added since prevread
  File "/home/yak/.local/lib/python3.6/site-packages/discord/iterators.py", line 75, in flatten
    item = await self.next()
  File "/home/yak/.local/lib/python3.6/site-packages/discord/iterators.py", line 605, in next
    await self.fill_members()
  File "/home/yak/.local/lib/python3.6/site-packages/discord/iterators.py", line 627, in fill_members
    data = await self.get_members(self.guild.id, self.retrieve, after)
  File "/home/yak/.local/lib/python3.6/site-packages/discord/http.py", line 245, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In after: long value should be greater than or equal to 0.

## Intents

`intents = discord.Intents.default()
intents.members = True
client = discord.Client(intents=intents)
`
## Checklist

- [x ] I have searched the open issues for duplicates.
- [x ] I have shown the entire traceback, if possible.
- [x ] I have removed my token from display, if visible.
- [ x] I have provided the intents that my bot is using.

## System Information

python3 -m discord -v
- Python v3.6.9-final
- discord.py v1.5.0-final
- aiohttp v3.6.2
- system info: Linux 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020

**Comment by Rapptz** [comment]
In order for the datetime parameter to work, it must first be converted into a snowflake which is based off of a Discord epoch of 2015. The datetime you provided with 0 is a localtime equivalent based off of the UNIX Epoch of 1970, which is in the past. This leads to the conversion from datetime to snowflake to be negative causing it to error out.

If you want to get the earliest member in the guild then you're better off using the guild's creation time (using [`Guild.created_at`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Guild.created_at)) instead of an artificial time in the past.

**Comment by tilnow** [comment]
got you. i suggest the documentation be updated then. it seems to say to use a utc time.

Maier Fenster
