### ISSUE TITLE
Audio from youtube_dl bot only playing in the right channel

### ISSUE THREAD

**Issue by SnowySailor** [Rapptz/discord.py#598]
I've got my bot's audio working, but the issue I've got is the bot is only playing the audio out of the right channel. Has anyone else had this issue or is it just me? Is there some setting that I can change to make it work in both L and R?

**Comment by khazhyk** [comment]
do you happen to use macosx 10.10.5 yosemite and does this affect all users

**Comment by SnowySailor** [comment]
I do happen to use that, yes. People who are on Windows say that they can hear audio through both channels. Is this a Discord bug for my specific version of OSX?

**Comment by khazhyk** [comment]
Yes, I have it too. Jake pls fix

**Comment by SnowySailor** [comment]
It sounds like an issue with how the audio is encoded before being sent by the bot. People on Windows can hear it just fine so I have a feeling OSX Discord is just having issues decoding it when it's received from the servers.

**Comment by khazhyk** [comment]
Does this only affect your bot? For me it affects all sounds discord makes,
try other bots and users

**Comment by SnowySailor** [comment]
Oh interesting. I never use Discord on my Mac but I was testing out the bot before pushing to my repo. I guess it's a Discord issue then.

**Comment by khazhyk** [comment]
This is, iirc an Electron bug - it should work fine in the web browser.

**Comment by Rapptz** [comment]
Since this isn't an issue with the library I'm going to close this.
