### ISSUE TITLE
on_typing event doesn't trigger on 1.5.1

### ISSUE THREAD

**Issue by neonoxd** [Rapptz/discord.py#5983]
## Summary

On discord.py==1.5.1 the **on_typing** event doesn't trigger

## Reproduction Steps

```py
from discord.ext import commands
bot = commands.Bot(command_prefix='!')

@bot.event
async def on_typing(channel, user, when):
	print("typing")

bot.run(TOKEN)
```

## Expected Results

print "typing" in the console. The above code snippet works perfectly on 1.4.1

## Actual Results

the event did not trigger. no message on console.

## Intents

defaults. also tried with the following changes. and confirmed that `intents.Typing == True`

```py
intents = discord.Intents.default()
bot = commands.Bot(command_prefix='!', intents=intents)
```

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

```
(venv) C:\dev\pythonProject>python -m discord -v
- Python v3.7.2-final
- discord.py v1.5.1-final
- aiohttp v3.6.3
- system info: Windows 10 10.0.18362
```

**Comment by Gobot1234** [comment]
Duplicate of #5965

**Comment by neonoxd** [comment]
oh i searched for on_typing in the titles... my bad
