### ISSUE TITLE
Can someone help me understand why is the function "wordf" not found by the bot?

### ISSUE THREAD

**Issue by DevonDekhran** [Rapptz/discord.py#5987]
import discord
from discord.ext import commands
from discord.ext.commands import Bot
import json
import difflib
from difflib import get_close_matches

Dictionary = json.load(open('data.json'))

def getTheWord(word):
    ###too many lines so I won't bloat the post###

bot = commands.Bot(command_prefix='!!')

@bot.command()
async def say(ctx, *, text):
    await ctx.send(text)

@bot.command()
async def wordf(ctx, word):
    await ctx.send(getTheWord(word))

bot.run('')

**Comment by Harmon758** [comment]
There's not really enough information here to help you.
For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README also links, or create a [discussion](https://github.com/Rapptz/discord.py/discussions) instead, as you should have been prompted to do when creating this issue.

For code block usage, see https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks.
