### ISSUE TITLE
The event on_message_edit always return a type User for message.author

### ISSUE THREAD

**Issue by AiroPi** [Rapptz/discord.py#5999]
## Summary

When the "on_message_edit" is called, the "after message" argument has its "author" argument that is ALWAYS of type User (and not of type Member like it should bot if it's in a server).
I have the "members" intents activated.

## Reproduction Steps

Just look the type of the attribute "author" in the message which is given in "on_message_edit" event.

## Expected Results

Before the 1.5 update, I'm 99% sure that, if the message edited was in a server, its author attribute was of type Member

## Actual Results

It's always of type "User"

## Intents

All intents except presence

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python v3.8.2-final
- discord.py v1.5.1-final
- aiohttp v3.6.2
- system info: Windows 10 10.0.18362

**Comment by Phxntxm** [comment]
No repro
```
<class 'discord.member.Member'> <class 'discord.member.Member'>
```

```
@bot.event
async def on_message_edit(before, after):
    print(type(before.author), type(after.author))
```

This will however happen if you do not have member intents, so double check and make sure you have actually enabled it

**Comment by AiroPi** [comment]
> No repro
> 
> ```
> <class 'discord.member.Member'> <class 'discord.member.Member'>
> ```
> 
> ```
> @bot.event
> async def on_message_edit(before, after):
>     print(type(before.author), type(after.author))
> ```
> 
> This will however happen if you do not have member intents, so double check and make sure you have actually enabled it

I think it's because I try to fetch connected member when the bot starts, but because I've not the presence intent, there is just the bot in memory.
So, the "on_edit_message" try to get_member, and find nothing, to in my situation, I get a User type

**Comment by EvilasioAnisio** [comment]
Hi, I was facing the same issue with a bot that I have running 24/7. Discord recently changed how they handle some data (member list included), so now you have to turn on **Privileged Gateway Intents** by going to your [project page](https://discord.com/developers/applications/) > Bot (left side menu), in this case, you will want to turn on **SERVER MEMBERS INTENT**. You can then restart your bot and everything should be fine.


A big thanks to discord for breaking our bots without bothering to send a notification about this change!

**Comment by AiroPi** [comment]
My bot is already verified, and Discord refused me the presence intents, and it was not a problem, I thought that I didn't require it. So at the moment, I just check is the message is edited in a guild, and then overwrite the ctx.author with a fetched member.
