### ISSUE TITLE
Client.send_message() sends the same message forever

### ISSUE THREAD

**Issue by annabunches** [Rapptz/discord.py#6]
Running echo.py from the examples directory. When I type a message into a channel, the bot repeats the message as expected, but doesn't stop repeating it! Adding debug statements suggests that on_message only gets called once, so it seems like send_message is repeatedly sending without ever returning, but I can't see anything in the code that would try to retransmit like this. (I checked both here at HEAD and the code actually installed on my machine)

Any idea what's going on?

I'm using discord.py 0.6.3 (from 'pip install discord.py')

**Comment by Rapptz** [comment]
Kind of expected. I suppose it's a 'bug' on the example.

`send_message` sends a message. The WebSocket receives the message event and then `on_message` is triggered on that message. `on_message` then sends the message again.. and rinse and repeat. Infinite loop.

It needs a check on the user ID. I'll fix the example.

**Comment by Rapptz** [comment]
Should be fixed in https://github.com/Rapptz/discord.py/commit/bcee23b707ea3c08519b1a2a13598fadf309fd56.

**Comment by annabunches** [comment]
Ahh, that makes sense! Thanks.
