### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by LiveSide** [Rapptz/discord.py#6003]
## Checklist

- [ ] I have searched the open issues for duplicates.
- [ ] I have shown the entire traceback, if possible.
- [ ] I have removed my token from display, if visible.
- [ ] I have provided the intents that my bot is using.

**Comment by TheRockettek** [comment]
Cannot reproduce on my machine.

**Comment by SNvMK** [comment]
What? i dont see any text, except checklist

**Comment by NESTOWL** [comment]
@TheRockettek you just reproduce the problem incorrectly 😳

**Comment by SebbyLaw** [comment]
@NESTOWL Please don't bump old issues with spam.
