### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by ascpial** [Rapptz/discord.py#6005]
I have found an error in the documentation page : for the `User` object, `avatar` and `avatar_url` are inverted

[avatar ](https://discordpy.readthedocs.io/en/latest/api.html#discord.User.avatar)
[avatar_url](https://discordpy.readthedocs.io/en/latest/api.html#discord.User.avatar_url)

Ps : I'm french and my english aren't good

**Comment by Vexs** [comment]
I'm not sure what you mean by inverted- `user.avatar` returns the hash, which matches what the docs say, and `user.avatar_url` returns an `Asset` object, which matches the docs. 

Weather or not it makes sense for `user.avatar_url` to return an asset is a matter of contention but that's a separate issue.

**Comment by ascpial** [comment]
Yes, I was wrong, sorry...
