### ISSUE TITLE
'HistoryIterator' object is not an iterator 

### ISSUE THREAD

**Issue by BLucky-gh** [Rapptz/discord.py#6008]
## Summary
When I try to iterate over the last several messages in a channel that I got with  `messages = channel.history(limit=10)` I get the error ``TypeError: 'HistoryIterator' object is not an iterator ``

here's the code:
```python
@client.event
async def on_ready():
    print("The bot is running as "+str(client.user))
    channel=client.get_channel(channel_id)
    messages = channel.history(limit=10)
    print(messages)
    for i in range(1,10):
        print(next(messages))
```
(this is not the code that is gonna be used for what I described in the intents section but it's the code that's returning the error while I was trying to make it work before starting to code the actual code itself)

## Reproduction Steps

Get a HistoryIterator object with `messages = channel.history(limit=10)` and try to iterate over it or even use `next(messages)`

## Expected Results

I expect the iterator to be an iterator

## Actual Results

The iterator decides to use it's freedom of self expression and identifies as something else, idk

## Intents

I'm trying to check if the last message was sent by a certain user and send a new message only if the previous message was indeed sent by that user

## Checklist
- [Yes] I have searched the open issues for duplicates.
- [Yes] I have shown the entire traceback, if possible.
- [Yes] I have removed my token from display, if visible.
- [Yes] I have provided the intents that my bot is using.

## System Information

- Python v3.8.1-final
- discord.py v1.5.1-final
- aiohttp v3.7.2
- system info: Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64

**Comment by Zomatree** [comment]
`HistoryIterator` is an async iterator not a normal iterator so `next` will not work.

**Comment by BLucky-gh** [comment]
oh, it's an async iterator. I figured the error message would mention it in at least some way so I assumed it wasn't an iterator in the first place.  Thanks for the quick reply
