### ISSUE TITLE
`on_reaction_remove()` not called, while `on_reaction_add()` is called on the same message.

### ISSUE THREAD

**Issue by mousetail** [Rapptz/discord.py#6010]
## Summary

If I have both a `on_reaction_add` and a `on_reaction_remove()`. See https://stackoverflow.com/questions/64685581/python-discord-py-on-reaction-removed-not-called

## Reproduction Steps

This is a minimal example I have writen to reproduce the problem:

```python
import discord
import json

client = discord.Client()


@client.event
async def on_reaction_add(reaction, user):
    print("on_reaction_add called")


@client.event
async def on_reaction_remove(reaction, user):
    print("on_reaction_remove called")


# same problem if I remove this part
@client.event
async def on_raw_reaction_remove(payload):
     print("on_raw_reaction_remove called")


with open("secret.json") as f:
    config = json.load(f)
token = config["token"]
client.run(token)
```

Now write a new message in the server (to force it being included in the cache) and remove it again.

## Expected Results

I would expect the following in the console:

```
on_reaction_add called
on_reaction_remove called
on_raw_reaction_remove called
```

## Actual Results

However, `on_reaction_remove` is never executed.

The actual output is:

```
on_reaction_add called
on_raw_reaction_remove called
```

Note that I get the same problem if I don't include the `on_raw_reaction_remove()` callback, in that case only `on_reaction_add` is printed.

## Intents

I am using default intents. This includes reactions, and the bot is able to add reactions, and receive `on_reaction_add()` properly. I have tried many possible intents combinations but none seem to make a difference.

## Checklist

- [x ] I have searched the open issues for duplicates.
- [x ] I have shown the entire traceback, if possible.
- [x ] I have removed my token from display, if visible.
- [x ] I have provided the intents that my bot is using.

## System Information

I am using version 1.5.1. I verified and got the same issue in version 1.5.0 and 1.4.2.

```
- Python v3.7.9-final
- discord.py v1.5.1-final
- aiohttp v3.6.3
- system info: Windows 10 10.0.17763
```

**Comment by Rapptz** [comment]
This is an issue with not having the members intent, unfortunately.

Since the member is not cached, there's incomplete information and the event can't be dispatched. As [documented](https://discordpy.readthedocs.io/en/latest/intents.html#member-cache), only reaction add events get a member object that the library can use even without caching. Unfortunately Discord does not provide the same with reaction remove events.

**Comment by mousetail** [comment]
@Rapptz Thank you for replying. Perhaps this should be more clearly stated in the documentation.

 Right now the only hint is `This requires Intents.reactions to be enabled.`, but that should be `Intents.reactions and Intents.members` to avoid confusion.

**Comment by Rapptz** [comment]
It's more of a consequence of not having members intent. Even if you have the members intent and it's not cached it won't fire. This should probably be mentioned though you're right.
