### ISSUE TITLE
Add check parameter to message.clear_reactions

### ISSUE THREAD

**Issue by piotrusieeeek** [Rapptz/discord.py#6012]
## Summary

Adding `check` parameter in `message.clear_reactions()` so it's possible to remove only specific reactions

**Comment by Soheab** [comment]
https://discordpy.readthedocs.io/en/latest/api.html#discord.Message.remove_reaction Exists

**Comment by AbstractUmbra** [comment]
As this is not in an acceptable format I doubt it will gain any traction.

Consider using the template in future, it is provided for a reason.
