### ISSUE TITLE
Increase logging level of ratelimit bucket exhaustion

### ISSUE THREAD

**Issue by siddhpant** [Rapptz/discord.py#6013]
## The Problem

The library logs when a ratelimit is reached using the logging library, but the logging level must be set to DEBUG.

## The Ideal Solution

The logging level for this message should be WARNING. Exhausting ratelimits should be avoided as far as one can. The bot's workflow can potentially hang at one place for quite a significant period of time. Thus, this should have a higher level compared to other noise of DEBUG.

## The Current Solution

The logging level for the message is DEBUG.

## Summary

Ratelimit exhaustion messages should be logged with WARNING level, not DEBUG.

**Comment by SebbyLaw** [comment]
Hitting ratelimits is extremely common. I'd rather not clog my WARNING level logs with extra junk.

**Comment by siddhpant** [comment]
Not really, if you hit the ratelimits too frequently, you should probably look into refactoring.

**Comment by Rapptz** [comment]
WARNING is the level for actual rate limit hits. DEBUG is for the pre-emptive rate limits, i.e. the library is waiting for the rate limit to be over before it hit it.

**Comment by siddhpant** [comment]
If the library throttles requests with preemptive rate limits, then hitting actual rate limits is a cause for concern and should be ERROR, as the library failed to throttle the requests and the bot risks ban by the API, breaking the bot.

Atleast instances of high ratelimits should be logged as WARN.

**Comment by Rapptz** [comment]
There is no error here.

Due to how Discord rate limits are implemented (there are sub rate limits, shared routes, multi-process requests) a 429 is something that just happens every so often and should just be a warning, not logged as an error. There is no error associated with it.

**Comment by siddhpant** [comment]
Understandable. 

On my part, I intended to refer to high pre-emptive ratelimits, of the order of hours or so, not of things like message send ratelimits which gets encountered often.
