### ISSUE TITLE
ctx.guild.members kids

### ISSUE THREAD

**Issue by Squuv** [Rapptz/discord.py#6017]
big problem

any solutions ?

**Comment by Zomatree** [comment]
Please keep to the issue template, we don't have enough info to help you from this.

**Comment by Squuv** [comment]
ok ty

**Comment by fwrs** [comment]
hey fucker, enable intents

**Comment by Squuv** [comment]
what is this faggot 


intents = discord.Intents.all()

client = commands.Bot(command_prefix = get_prefix, intents=intents)


```
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by Squuv** [comment]
nvm fixed with this [https://discordpy.readthedocs.io/en/latest/_images/discord_privileged_intents.png](https://discordpy.readthedocs.io/en/latest/_images/discord_privileged_intents.png)
