### ISSUE TITLE
before and after Member objects have same values

### ISSUE THREAD

**Issue by Tawmy** [Rapptz/discord.py#6020]
## Summary

Certain events trigger both on_user_update and on_member_update. I have tested this with avatar and username changes. 

While I can see the old and new username/avatar in the on_user_update event as expected, both the before and after object only have the new values in the on_member_update event. The URL for the avatar is the same, new one in both, and the username is also the new one in both. If this is intended and only the on_user_update event is supposed to have the correct information in both objects, on_member_update should probably not be triggering.

## Reproduction Steps

Implemented the events using:
```
@commands.Cog.listener()
    async def on_member_update(self, before: Member, after: Member):

@commands.Cog.listener()
    async def on_user_update(self, before: User, after: User):
```

Bot and user were part of the same guild. Changed username and avatar in separate instances and each time, the described issue happened.

## Expected Results

Both events trigger on username and avatar changes, so I expect the before and after objects in both events to actually reflect the state before and after the event.

## Actual Results

The before object in on_member_update has the information from after the event, equal to the information from the after object. The information is correct in both objects in the on_user_update event.

## Intents

`discord.Intents.all()`

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python v3.9.0-final
- discord.py v1.5.1-final
- aiohttp v3.7.2
- system info: Linux 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020

**Comment by Rapptz** [comment]
That's because members share the same global user cache instance in order to save on memory. This is the reason the `on_user_update` event exists, since it allows the library to call it during the first time it detects this change.
