### ISSUE TITLE
Issues with .group() two-layers in, trying to access (self, ctx, *args, **kwargs)

### ISSUE THREAD

**Issue by Amelia-exe** [Rapptz/discord.py#6022]
## Summary

All required imports have been added to file, no naming conflicts at all.
Channel being passed to the command both, exists and is visible by the bot. (Bot running in Administrator perms).
Text has been replaced with `"Text"` to lessen the lines of code shown in Steps below.

Current issue being that, with doing the below, and giving the required arguments (including channel), it's still asking me for a channel as an argument?

## Reproduction Steps

```py
from discord import TextChannel
from discord.ext.commands import Cog, Context, check, group, has_permissions

class Cog_Name(Cog):
    def __init__(self, bot):
        self.bot = bot

    @check(has_permissions(administrator=True))
    @group(name="a", invoke_without_command=True)
    async def parent(self, ctx: Context):
        return await ctx.send("Text")

    @parent.group(name="b", invoke_without_command=True)
    async def child(self, ctx: Context):
        return await ctx.send("Text")

    @child.command(name="set")
    async def c_command(self, ctx: Context, channel: TextChannel):
        return await ctx.send(channel)


def setup(bot):
    bot.add_cog(Cog_Name(bot))
```
Command to run: `!a b set #welcome`, at this point in the code.

## Expected Results

Returning the name of the channel that **does exist**; Else, throwing an error: `ChannelNotFound`.

## Actual Results

```py
Ignoring exception in command level_system channel set.
Traceback (most recent call last):
  File ".\Python38\lib\site-packages\discord\ext\commands\bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File ".\Python38\lib\site-packages\discord\ext\commands\core.py", line 1329, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File ".\Python38\lib\site-packages\discord\ext\commands\core.py", line 1329, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File ".\Python38\lib\site-packages\discord\ext\commands\core.py", line 851, in invoke
    await self.prepare(ctx)
  File ".\Python38\lib\site-packages\discord\ext\commands\core.py", line 786, in prepare
    await self._parse_arguments(ctx)
  File ".\Python38\lib\site-packages\discord\ext\commands\core.py", line 697, in _parse_arguments
    transformed = await self.transform(ctx, param)
  File ".\Python38\lib\site-packages\discord\ext\commands\core.py", line 542, in transform
    raise MissingRequiredArgument(param)
discord.ext.commands.errors.MissingRequiredArgument: channel is a required argument that is missing.
```
## Intents

Using this on a test bot currently, passing `Intents.all()`.
## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python v3.8.6-final
- discord.py v1.5.1-final
- aiohttp v3.6.3
- system info: Windows 10 10.0.19041

**Comment by Amelia-exe** [comment]
Having tested it a little bit further, I removed `ctx: Context` from `c_command()`.
Then, added a `print(self)` to see what was contained within it.

The Output:
`<discord.ext.commands.context.Context object at 0x0000016FFD6D72B0>`

Therefore, removed `self`, from the args list, and seems to now be working(?)
Seems like going two-layers into `.group()`, self it not able to be passed?

**Comment by Rapptz** [comment]
I cannot reproduce this:

![image](https://user-images.githubusercontent.com/1695103/98469626-bafb7580-21ae-11eb-96b7-2be8a0107797.png)

Chances are your real code is shadowing the function name causing issues with the registration.

**Comment by Amelia-exe** [comment]
I shall give it a change up and see if it fixes it / produces any further issues.

**Comment by Amelia-exe** [comment]
Yeah, seems to be the function name and name set were clashing !

Thanks for the quick reply / resolution.
[#2141](https://github.com/Rapptz/discord.py/issues/2141) - Has this / Can this be implemented as well...?

**Comment by Rapptz** [comment]
Implementing it is a bit more difficult than it seems on the surface.

Next time please do not post reproduction steps that don't align with the actual code causing issues.
