### ISSUE TITLE
Custom description for Cogs

### ISSUE THREAD

**Issue by Jackywathy** [Rapptz/discord.py#6024]
## The Problem

Cogs don't seem to allow their description to be overridden except for providing a docstring on the class. This becomes a problem if we want to put technical documentation on the docstring or otherwise change the description during program execution.

## The Ideal Solution

Allow the description to be set during instantiation (in the metaclass `CogMeta`), similar to how name and command_attrs is set (https://github.com/Rapptz/discord.py/blob/abe54f5bdc48b2a92fd2a0d158ac15655049174d/discord/ext/commands/cog.py#L94). 

In addition, allow description to be assignable (currently it is a read-only property) on the cog.

## The Current Solution

Set docstring (but we lose the option to configure the description later + are forced to limit what is in it)

## Summary

Allow cog description to be better customisable

**Comment by Harmon758** [comment]
This should be resolved by #6028 with https://github.com/Rapptz/discord.py/commit/4adbe03d7ca03fce3411bea7bcd9e3619513ad94.
