### ISSUE TITLE
Guild.VoiceChannel.members does not include all members 

### ISSUE THREAD

**Issue by yuwex** [Rapptz/discord.py#6029]
## Summary

`Guild.VoiceChannel.members` does not include members that are in voice channel before the bot is launched.

## Reproduction Steps

1. Join a voice channel
2. Print all members in all voice channels (Inside cog):
```python
      for guild in self.bot.guilds:
            for vc in guild.voice_channels:
                for member in vc.members:
                    print(member.name)
```
2. Run your bot

## Expected Results

This should list all members in voice channels.

## Actual Results

Does not list any members in voice channels UNLESS members re-join voice channels.

## Intents

`discord.Intents.default()`
`intents.members = True`

## Checklist

- [x] I have searched the open issues for duplicates.
- [ ] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python v3.8.1-final
- discord.py v1.5.1-final
- aiohttp v3.6.2
- system info: Darwin 18.7.0 Darwin Kernel Version 18.7.0: Mon Aug 31 20:53:32 PDT 2020; root:xnu-4903.278.44~1/RELEASE_X86_64

**Comment by uKaigo** [comment]
You're need the `guilds` intent. As described [here](https://discordpy.readthedocs.io/en/latest/api.html#discord.Intents.guilds), ``Guild`` and all its attributes will be None when this intent is missing.

**Comment by yuwex** [comment]
@uKaigo whoops, forgot to add I had `discord.Intents.default()`, my bad.

**Comment by uKaigo** [comment]
I can't repro this issue with `guilds` intent.

I used this code and I got the expected results:

```py
import discord

intents = discord.Intents(members=True, guilds=True)

client = discord.Client(intents=intents)

@client.event
async def on_ready():
    print('Start of iteraction.')
    print('-' * 20)

    for guild in client.guilds:
        for vc in guild.voice_channels:
            for member in vc.members:
                print(member.name)

    print('-' * 20)
    print('End of iteraction.')

    await client.logout()

client.run('TOKEN')
```

Are you sure you're with the correct intents?

**Comment by yuwex** [comment]
You were right. I wasn't passing my intents into `commands.Bot()`. Thanks for your help!
