### ISSUE TITLE
Member cache cleared upon connection reset but memory not freed

### ISSUE THREAD

**Issue by apex2504** [Rapptz/discord.py#6032]
When a connection is flaky or there's an issue on Discord's end and the client loses connection to Discord, the `members` cache for a guild is cleared and the only way to fully rebuild it is to re-chunk every guild. This wouldn't usually be a problem; however, the previous `members` cache isn't cleared from memory. Therefore, memory usage can skyrocket because the previous cache is still in memory but completely inaccessible.  

### MemberCacheFlags
`joined = True`

`voice = True`

### Intents
Everything except `presences` 

### chunk_members_at_startup
`True`

**Comment by Rapptz** [comment]
Cache is not removed upon disconnecting from Discord. It's cleared depending on the event received while reconnecting.

Memory not going down is probably just the interpreter holding on to the memory since it's expensive to constantly reallocate memory.
