### ISSUE TITLE
ClientOSError: [WinError 64] The specified network name is no longer available

### ISSUE THREAD

**Issue by xPolar** [Rapptz/discord.py#6037]
## Reproduction Steps

Ran a command called `!export` within a text channel inside of a guild, the command should then get all of the messages within the text channel and write them into a text file. Once said text file is done it should try to send the file to the person who invoked the command if `discord.Forbidden` is raised then send the file to the channel it was invoked in.

```py3
with open("export.txt", "w+", encoding="utf-8") as file:
    file.write(f"Guild: {ctx.guild.name}\nChannel: {ctx.channel.name}\n{ f'Topic: {ctx.channel.topic}' if ctx.channel.topic else '' }")
    async for message in ctx.channel.history(oldest_first = True):
        file.write(f"\n[{message.created_at.strftime('%d-%b-%y %I:%M %p')}] {message.author}: {message.content}")
    file.seek(0)
    try:
        await ctx.author.send(file = discord.File(file, "export.txt"))
    except discord.Forbidden:
        await ctx.channel.send(file = discord.File(file, "export.txt"))
try:
    remove("export.txt")
except:
    return
```

## Expected Results

It should have exported the messages, sent it either to DMs or the channel, and then deleted it.

## Actual Results

It exports like three or so messages and then stops exporting anything and raises the following traceback.

```
Ignoring exception in on_command_error
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "c:\Users\Haris\Desktop\Code\SimBuilder\MessageExporter\Main.py", line 137, in export       
    await ctx.author.send(file = discord.File(file, "export.txt"))
  File "C:\Python38\lib\site-packages\discord\abc.py", line 886, in send
    data = await state.http.send_files(channel.id, files=[file], allowed_mentions=allowed_mentions,
  File "C:\Python38\lib\site-packages\discord\http.py", line 185, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "C:\Python38\lib\site-packages\aiohttp\client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "C:\Python38\lib\site-packages\aiohttp\client.py", line 504, in _request
    await resp.start(conn)
  File "C:\Python38\lib\site-packages\aiohttp\client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "C:\Python38\lib\site-packages\aiohttp\streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [WinError 64] The specified network name is no longer available

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "c:\Users\Haris\Desktop\Code\SimBuilder\MessageExporter\Main.py", line 191, in on_command_error
    raise error
  File "C:\Python38\lib\site-packages\discord\ext\commands\bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Python38\lib\site-packages\discord\ext\commands\core.py", line 859, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Python38\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ClientOSError: [WinError 64] The specified network name is no longer available
```

## Intents

Default

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

**Comment by Vexs** [comment]
This error seems to raise when you try to do operations on a closed socket. Why that's happening isn't strictly related to the code you've got, and is probably some issue with either your PC or local network. 

Maybe an antivirus is flagging the connection?

**Comment by xPolar** [comment]
I'll try to disable the Windows anti-virus to test this.

**Comment by xPolar** [comment]
No luck sadly.

**Comment by xPolar** [comment]
Looks like there is nothing that can be done about this, going to close it now.

**Comment by RoguedBear** [comment]
Im having the same issue when uploading a large file/attachment in the message. It seems like the upload gets "stuck" for reasons unknown.

Due to this bug, when the bot is under load and has other attachments to upload, they don't upload no matter their size. When the function im running times out with the exception `asyncio.exceptions.TimeoutError`, then those other pending files are uploaded.


At first when the uploading error happens these are logged:
```
DEBUG:[19 Sat, 20:45:35]:[request()]:POST https://discord.com/api/v7/channels/853218266868613130/messages with <aiohttp.formdata.FormData object at 0x0000027878ED8CA0> has returned 502
WARNING:[19 Sat, 20:45:36]:[write()]:socket.send() raised exception.
WARNING:[19 Sat, 20:45:36]:[write()]:socket.send() raised exception.
WARNING:[19 Sat, 20:45:36]:[write()]:socket.send() raised exception.
WARNING:[19 Sat, 20:45:36]:[write()]:socket.send() raised exception.
```
After the the function times out, this is the error log printed:
```
Traceback (most recent call last):
  File "D:\Collateral\OCR\main.py", line 137, in one_image_ocr
    await channel.send(f"Squigly lines:```{getenv('LANGUAGE')}\n{code}\n```\nTook `{dur:.2f}s`",
  File "D:\Program Files\Python\lib\site-packages\discord\abc.py", line 1044, in send
    data = await state.http.send_files(channel.id, files=[file], allowed_mentions=allowed_mentions,
  File "D:\Program Files\Python\lib\site-packages\discord\http.py", line 192, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "D:\Program Files\Python\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "D:\Program Files\Python\lib\site-packages\aiohttp\client.py", line 544, in _request
    await resp.start(conn)
  File "D:\Program Files\Python\lib\site-packages\aiohttp\client_reqrep.py", line 905, in start
    self._continue = None
  File "D:\Program Files\Python\lib\site-packages\aiohttp\helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
```
----

the uploading works fine when the file sizes are within 1MB, but larger than that it gets stuck for 5 minutes till it times out and sends the other pending small images.

**Comment by xPolar** [comment]
Weird, doesn't sound like an issue with bot limits as normal users can upload files as big as 8MB if I remember correctly (50 MB with Discord Nitro Classic and 100 MB with Nitro Boost).

> The maximum request size when sending a message is 8MB.

[Discord Documentation](https://discord.com/developers/docs/resources/channel#create-message-limitations) saying that a request size can't be larger than 8 MB

As well as after looking at the discord.py source code there doesn't seem to be any limit's less than 8 MB.

**Comment by RoguedBear** [comment]
I was thinking it was due to my internet upload speed. When i ran the same code on heroku, though the big image didn't upload on chat (cuz something in my program errored out), but printing that error meant that the program was past the upload stage.

When i skipped the uploading part altogether (and instead just sent a link back to the original image) my bot (locally on my computer) also sent the same error which the heroku instance sent. Again, having that error reply message is a thing in my code but the gist being im past the "uploading" phase.

so my temporary resolution of this problem: dont upload because when if someone sends a pretty big file, the bot wont send a message to anyone for 5 minutes then.
