### ISSUE TITLE
AttributeError raised on voice channel connection timeout

### ISSUE THREAD

**Issue by jkchen2** [Rapptz/discord.py#6039]
## Summary

If the bot times out when connecting to a voice channel, an `AttributeError: 'VoiceClient' object has no attribute 'ws'` exception is thrown. This results in the bot getting stuck in a bad voice channel connection state, and a restart is needed to clear it.

## Reproduction Steps

A bit inconsistent to reproduce as it really only happens on network blips, but can be mostly reproduced if the timeout is set to a small enough value:

```python
voice_channel = await bot.fetch_channel(...)
await voice_channel.connect(timeout=0.1)
```

## Expected Results

If a `TimeoutError` occurs, no `AttributeError` is raised, and the bot cleanly disconnects itself from the voice channel from an incomplete connection state.

## Actual Results

If a `TimeoutError` occurs, the bot will attempt to call `disconnect`, which will then attempt to access a not yet instantiated `self.ws`.

This results in the bot getting stuck in a bad state where it shows up as connected to the voice channel for an end user, but it isn't actually (i.e. no matching `VoiceClient` in `bot.voice_clients`). Additionally, further attempts to connect to the voice channel will fail with a `TimeoutError`.

Partial traceback:

```
  File "/usr/local/lib/python3.6/dist-packages/discord/abc.py", line 1122, in connect
    await voice.connect(timeout=timeout, reconnect=reconnect)
  File "/usr/local/lib/python3.6/dist-packages/discord/voice_client.py", line 346, in connect
    await self.disconnect(force=True)
  File "/usr/local/lib/python3.6/dist-packages/discord/voice_client.py", line 460, in disconnect
    if self.ws:
AttributeError: 'VoiceClient' object has no attribute 'ws'
```

## Intents

No additional intents are passed to the bot, but I don't think intents are related to this issue anyway.

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

```
- Python v3.6.7-final
- discord.py v1.5.1-final
- aiohttp v3.6.3
- [I have omitted the system info line because frankly, it is too embarrassing to admit that I haven't updated my kernel in literally over 3 years]
```

**Comment by Armster15** [comment]
Yea I also started getting this error with my bot too.
