### ISSUE TITLE
putting <> around @everyone bypasses "message.mention_everyone"

### ISSUE THREAD

**Issue by Chrisdies** [Rapptz/discord.py#6040]
## Summary

"message.mention_everyone" results in false if the user puts <> around @everyone

## Reproduction Steps

1) create a bot that responds back the same message it's sent but if message.mention_everyone is true don't do anything. 
2) send the bot @everyone
3) send the bot <@everyone>

## Expected Results
both times the bot shouldn't respond as they both mention @everyone
## Actual Results
the bot will mention @everyone on the second case
## Intents
doesn't pertain to the issue
## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python v3.7.6-final
- discord.py v1.5.1-final
- aiohttp v3.6.3
- system info: Windows 10 10.0.18362

**Comment by Zomatree** [comment]
`mention_everyone` comes directly from discord, its not something the library does itself. This is an issue with discord not the library.

**Comment by Chrisdies** [comment]
> `mention_everyone` comes directly from discord, its not something the library does itself. This is an issue with discord not the library.

Guess discord sucks at making api features. I'll go ahead and close this as it doesn't pertain to discord py.

**Comment by Harmon758** [comment]
I'm unable to reproduce this now, so perhaps it's been fixed.
