### ISSUE TITLE
Aggressive event parsing

### ISSUE THREAD

**Issue by squili** [Rapptz/discord.py#6053]
## The Problem

some events, like `reaction_add`, only trigger if some data is in the cache. this is not intuitive and forces developers to use raw events, which are pretty ugly and annoying to work with.

## The Ideal Solution

`DiscordWebSocket.received_message` (coroutine) calls parsers. instead of just running them, detect if the parsers are coroutines and create tasks for them instead of just calling them. this allows events to do asynchronous actions, like making api calls.

`ConnectionState.parse_message_reaction_add` is a good example. this can be turned into a coroutine. add a `state._get_message_aggressive(message_id, channel_id=None)` coroutine that tries to get the message from cache, but falls back to fetching the message from the api instead of just returning `None`. if the event doesn't get a `channel_id` for some reason, it can just not provide it to the function call and the old behaviour will be returned. additionally, you can expose this functionality to the developer with a `channel.get_message_aggressive(message_id)` coroutine.

as this behaviour is different than what currently happens, it makes sense to be able to toggle it. add an option called `aggressive_event_parsing` and have `state` save the setting in `self._aggressive_event_parsing`. check if `self._aggressive_event_parsing` is enabled in the event before using the aggressive call.

## The Current Solution

listen to raw events and get the event data yourself

## Summary

parse more rich events by fetching the message/user data from the api if they're not cached.

**Comment by Rapptz** [comment]
This isn't gonna happen any time soon. The parsing isn't async because I don't want to deal with excessive back pressure due to needing to make this synchronous. For your specific use case you're better off using the raw event, that's what they're there for.

**Comment by squili** [comment]
What do you mean by excessive back pressure? I completely respect your decision to not implement this, but I was able to get this working on a [fork](https://github.com/squili/discord.py). `on_reaction_add` was called for all events, not just events where the message was in cache.

**Comment by BluePhoenixGame** [comment]
You may want to read this: https://lucumr.pocoo.org/2020/1/1/async-pressure/

**Comment by squili** [comment]
Ah, I see. So if events come in faster than the endpoint can give messages for, it'll end up with tons of events in queue which are waiting on that one endpoint call. Makes sense to me.
