### ISSUE TITLE
Support the new Reply feature

### ISSUE THREAD

**Issue by remyjette** [Rapptz/discord.py#6054]
## The Problem

Discord recently added support for inline replies to the client: https://support.discord.com/hc/en-us/articles/360057382374-Replies-FAQ

Right now, discord.py only provides partial support for this functionality.

## The Ideal Solution

I should be able to know when a given message is a reply to another. The existing `Message.reference` field gives me a `MessageReference`, to the source message, but the documentation needs to be updated to reveal that it will also be populated for replies. `MessageType` should have a `reply` member so I can tell it is a reply (looks like #5200 implements this part) - right now on a reply the `type` is `MessageType.default`.

I should also be able to create a new reply to an existing message. Perhaps the `Message` object could have a `reply` coroutine for this purpose.

## The Current Solution

Only partial functionality exists today. To determine if a message is a reply, I would need to check that the message is neither a cross-post nor a `MessageType.pins_add`. There is currently no solution for sending replies (other than perhaps interacting with `client.http` directly).

## Summary

Please add support for the new replies feature. Thank you!

**Comment by Rapptz** [comment]
Just want to note that the reply type being `19` is available only in v8. This library uses v6 of the gateway and v7 of the API so it defaults to type `0`. The type being `19` won't be supported since it's a breaking change and will be in v2.0.
