### ISSUE TITLE
How can I play an audio-file from specific position?

### ISSUE THREAD

**Issue by grigandal625** [Rapptz/discord.py#6057]
I need this to implement the time rewind slider, as in ordinary music programs

So far I have done this via dynamically trimming the audio file into a temporary file:

```
from ffmpeg import AudioSegment
import discord

# - there comes a moment when you need to play not from the beginning:

client.voice_clients [0] .stop ()

end = full_duration # - full duration of the audio file (in ms)
start = start_position # - the position from which I want to start playback (in ms)
song = AudioSegment.from_mp3 ('initial \ file \ path \ initial-file.mp3') # load the original file to trim
extract = song [start: end] # - cut off
extract.export ('./ source.mp3') # - save

client.voice_clients [0] .play (discord.FFmpegPCMAudio ('./ source.mp3')) # - play the trimmed file
```

However, this method is probably not the only one, and it is also very expensive - if the audio file is large, processing will be very long.

How else can you do it?

**Comment by imayhaveborkedit** [comment]
You don't need to use pydub for something like this.  Just pass a start timestamp as an ffmpeg option with `before_options="-ss timestamp"` where `timestamp` is in `HH:MM:SS.MS` format.
