### ISSUE TITLE
Editing/deleting webhook messages

### ISSUE THREAD

**Issue by sersorrel** [Rapptz/discord.py#6058]
## The Problem

AIUI, it's not currently possible to edit webhook messages via discord.py. Historically this has been due to Discord limitations, but recently support for this was added: https://github.com/discord/discord-api-docs/issues/1544#issuecomment-708707645

![](https://user-images.githubusercontent.com/11778454/96054661-fb2d3980-0e36-11eb-8391-e83972a73546.png)

## The Ideal Solution

I'd like to be able to edit messages sent via webhook; it would be nice to be able to delete them via the webhook API too, in the case where the bot user lacks permission to manage messages.

## The Current Solution

It's not possible to edit webhook messages via discord.py, and webhook messages can only be deleted if a bot user has the relevant permissions.

## Summary

discord.py should support the new webhook API endpoints for editing and deleting messages.

**Comment by ShineyDev** [comment]
We're aware. There isn't a good way to implement it in discord.py's current state.

See [this conversation](https://discord.com/channels/336642139381301249/603069307286454290/766077840575561728) in the [discord.py Discord server](https://discord.gg/dpy).
