### ISSUE TITLE
Very simple bot, learning discord.py, crashes with some errors

### ISSUE THREAD

**Issue by jeremieSimula** [Rapptz/discord.py#606]
Hi everyone,

I have this very simple bot: (I used the "quote" instead of "code" markups because the code does not seem to be colored at all and looks ugly)

> import discord
> import asyncio
> client = discord.Client()
> 
> @client.event
> @asyncio.coroutine 
> def on_message(message):  
>     # Per the discord.py docs this is to not have the bot respond to itself
>     if message.author == client.user:
>         return
>     #If the bot sees the command !hello we will respond with our msg string
>     if message.content.startswith('!hello'):
>         msg = 'Hello {0.author.mention}'.format(message)
>         yield from client.send_message(message.channel, msg)
> 
> @client.event
> @asyncio.coroutine 
> def on_ready():
>     print('Logged in as')
>     print(client.user.name)
>     print(client.user.id)
>     client.close();
>     print('------')
> 
> 
> client.run('xxxx')
> client.close()

When I run it I got this error:

> python test1.py 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/discord/http.py", line 258, in static_login
>     data = yield from self.request(Route('GET', '/users/@me'))
>   File "/usr/local/lib/python3.4/dist-packages/discord/http.py", line 200, in request
>     raise HTTPException(r, data)
> discord.errors.HTTPException: UNAUTHORIZED (status code: 401): 401: Unauthorized
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "test1.py", line 27, in <module>
>     client.run('xxxxxxx')
>   File "/usr/local/lib/python3.4/dist-packages/discord/client.py", line 519, in run
>     self.loop.run_until_complete(self.start(*args, **kwargs))
>   File "/usr/lib/python3.4/asyncio/base_events.py", line 316, in run_until_complete
>     return future.result()
>   File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
>     raise self._exception
>   File "/usr/lib/python3.4/asyncio/tasks.py", line 236, in _step
>     result = coro.send(value)
>   File "/usr/local/lib/python3.4/dist-packages/discord/client.py", line 490, in start
>     yield from self.login(*args, **kwargs)
>   File "/usr/local/lib/python3.4/dist-packages/discord/client.py", line 416, in login
>     yield from getattr(self, '_login_' + str(n))(*args, **kwargs)
>   File "/usr/local/lib/python3.4/dist-packages/discord/client.py", line 346, in _login_1
>     data = yield from self.http.static_login(token, bot=is_bot)
>   File "/usr/local/lib/python3.4/dist-packages/discord/http.py", line 262, in static_login
>     raise LoginFailure('Improper token has been passed.') from e
> discord.errors.LoginFailure: Improper token has been passed.
> Unclosed client session
> client_session: <aiohttp.client.ClientSession object at 0x7ff960e94f28>
> Exception ignored in

**What I have done and tried**:
My bot is "registered" on my discord personal channel and I can see it there.
I generated multiple times the secret token just in case: did not change anything
The python version I am using is: Python 3.4.3 (default, Nov 17 2016, 01:08:31)
The discord.py version I use is: 0.16.8

My questions
Is there anything wrong with the code itself?
Is there any step that I have missed in the creation of my bot?
Could there be a problem of UTF-8 encoding with my code so that the token is "mis-read" ?

Thank you in advance for your help.

**Comment by Rapptz** [comment]
This literally just means your token is incorrect. There's nothing more to it.

Check this [video](https://discord.is-serious.business/6fd481.mp4) on how to fetch your token.
