### ISSUE TITLE
Weird behaviour when moving roles.

### ISSUE THREAD

**Issue by rrmTV** [Rapptz/discord.py#6060]
## Summary

When creating multiple ordered roles in a for loop I'm creating a role, getting a bookmark role position, and then setting the new role position to bookmark role position -1. Somehow, roles manage to be moved incorrectly, move other roles, which were pre-existing and in general not work.

## Reproduction Steps

```
   for missing_role in missing_roles:
        role = discord.utils.get(member.guild.roles, name=f'{missing_role} {skills[missing_role.lower()]}')
        if role is not None:
            new_roles.append(role)
        else:
            role = await member.guild.create_role(name=f"{missing_role} {skills[missing_role.lower()]}", color=Colour(value=int(ROLE_COLORS[missing_role.lower()], 16)), reason='Updating skills')
            closest_position = discord.utils.get(member.guild.roles, name=f'{missing_role} Bookmark').position
            print(member.guild.roles)
            print(f'{role}         {role.position}       {closest_position-1}')
            await role.edit(position=closest_position-1)
```

## Expected Results

Was expecting it to go from this:
![image](https://user-images.githubusercontent.com/37328719/99560932-19a2c980-29cf-11eb-88c7-f3305a37a8e4.png)

To this:
![image](https://user-images.githubusercontent.com/37328719/99560826-faa43780-29ce-11eb-8ca1-3f5cc386fb8b.png)

## Actual Results

Results are +- different each time

Went from this:
![image](https://user-images.githubusercontent.com/37328719/99560939-1b6c8d00-29cf-11eb-8dd4-f13dbb8d8795.png)

To this:
![image](https://user-images.githubusercontent.com/37328719/99560687-d0eb1080-29ce-11eb-810b-2b5d51327440.png)

Things, like bookmarks shouldn't be moved at all.

Log from the prints:
[quick_log.txt](https://github.com/Rapptz/discord.py/files/5561528/quick_log.txt)

## Intents

```
intents = discord.Intents().default()
intents.members = True
```

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python v3.7.4-final
- discord.py v1.5.1-final
- aiohttp v3.6.3
- system info: Windows 10 10.0.18362

**Comment by ShineyDev** [comment]
This is likely due to Discord's role and channel position APIs being [eventually consistent](https://discord.com/developers/docs/reference#consistency).

**Comment by rrmTV** [comment]
Any way around this issue?

**Comment by ShineyDev** [comment]
> Any way around this issue?

This is a Discord limitation.

That said, updating the position of all roles - one by one - to incremental values should get them consistent on the server, then updating the incorrectly positioned roles may solve this, and has done so for me in the past. There is no guarantee that this will not break again.

**Comment by Vexs** [comment]
Create all your roles then use [edit_role_positions.](https://discordpy.readthedocs.io/en/latest/api.html#discord.Guild.edit_role_positions) This edits all the role positions at once and sidesteps the cache-out-of-date-discord-out-of-date issue

**Comment by rrmTV** [comment]
I'll try doing that.
Quick question. Why was the code I provide moving roles that it shouldn't?

**Comment by Vexs** [comment]
Discord doesn't provide a way to move a singular role at once- you actually edit the positions of every role. Discord.py uses it's internal cache to calculate the new role positions for everything, but when you do that in a loop, the positions get rapidly out of date and fuckery happens. Using edit_role_positions does this all at once, avoiding cache, and fuckery.

**Comment by rrmTV** [comment]
Updated some code, at least now the roles are in the correct order, but not correct positions.

**Comment by rrmTV** [comment]
Code used:
```
    for missing_role in missing_roles:
		role = await member.guild.create_role(name=f"{missing_role} {skills[missing_role.lower()]}", color=Colour(value=int(ROLE_COLORS[missing_role.lower()], 16)), reason='Updating skills')
		new_roles.append(role)

    for role in new_roles:
        closest_position = 0
        result = re.search('^(Alchemy|Combat|Enchanting|Farming|Fishing|Foraging|Mining|Taming) ([0-9]+)', role.name)
        closest_position = discord.utils.get(member.guild.roles, name=f'{result.group(1)} Bookmark').position
        new_roles2[role] = closest_position - 1

    print(new_roles2)
    await member.guild.edit_role_positions(new_roles2)
```

**Comment by rrmTV** [comment]
First run:
![image](https://user-images.githubusercontent.com/37328719/99570443-9edfab80-29da-11eb-8f00-31f268c1fef1.png)
Deleted the roles and tried again:
![image](https://user-images.githubusercontent.com/37328719/99570559-c898d280-29da-11eb-8201-5fc744c4851b.png)

The position shift each run.

**Comment by rrmTV** [comment]
Well, this sucks. Got rate-limited and have no choice but to retry experimenting in 12 days...
