### ISSUE TITLE
Hyperlinks

### ISSUE THREAD

**Issue by NightZan999** [Rapptz/discord.py#6064]
## The Problem

In discord.py is it possible to put hyperlinks, since some links are far too long which should be able to hyperlink. Often people find the links too weird and long

## The Ideal Solution
Can you please make it so that we can use hyperlinks in discord.py
I am quite an avid user of discord.py in listing users = len(client.users) and yeah. If there is already a feature please reply and tell me how can we put hyperlinks

Thanks and Regards,
NightZan999

**Comment by averwhy** [comment]
What? You can hyperlink in embeds. What are you asking?

**Comment by Daggy1234** [comment]
`"[Text To Click](https://www.youtube.com/)"`
- Needs to be a full url
- Only works in embeds, duh
- This won't work in the title, footer or field titles
If you want to hyperlink a title, you can use the url kwarg in an Embed

**Comment by NightZan999** [comment]
What? So in an embed you can hyperlink, thanks a lot for the help. Sorry I'm an idiot haha.
