### ISSUE TITLE
commands.Bot.guilds returns empty list, when the bot is in multiple servers

### ISSUE THREAD

**Issue by erick-dsnk** [Rapptz/discord.py#6066]
## Summary

I recently needed a list of all the guilds my bot is in to set up a database for an economy system I wanted to implement. Only to find out that for some reason, the `guilds` property is an empty list. I checked multiple times and I am 100% sure that my bot is in multiple servers.

## Reproduction Steps

This is issue hasn't happened before since I used this property in other things.
What I did was: I iterated through the guilds list to add to a MongoDB collection, and i noticed that the code inside the for loop was never triggered. Then when I tried printing `client.guilds` it returned `[]`. My code for setting up the bot and the database:
```python
import discord
from discord.ext import commands
from exts.database import economy_collection # the mongo db collection, its in another file

intents = discord.Intents.all()
client = commands.Bot(command_prefix = '-', intents=intents)
client.remove_command('help')

print(client.guilds) #  []

def setup_database():
    for guild in client.guilds:
        if not economy_collection.find_one({"_id": guild.id}):
            members = []

            for member in guild.members:
                members.append(
                    {"id": member.id, "money": 0}
                )

            economy_collection.insert_one(
                {
                    "_id": guild.id,
                    "name": guild.name,
                    "members": members
                }
            )
        
        else:
            pass

setup_database()

client.run("my token")
```

## Expected Results

I expected a list with all the guilds

## Actual Results

There's no error, but the client.guilds is empty

## Intents

```python
intents = discord.Intents.all()
client = commands.Bot(command_prefix = '-', intents=intents)
```

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

Python version: `3.9.0-final`
discord.py version: `1.5.1-final`
aiohttp version: `3.6.3`

Operating System: `Microsoft Windows 10 Home 10.0.18363 N/A Build 18363`

**Comment by SebbyLaw** [comment]
You need to connect to discord in order to populate any caches.

**Comment by erick-dsnk** [comment]
oh that was fast. What do you mean by populating caches?

**Comment by SebbyLaw** [comment]
> oh that was fast. What do you mean by populating caches?

You try to access the client's guild cache before calling `client.run()`. It is empty because it is not connected to discord, and therefore has not received any guild objects from discord yet.

This is not an issue with discord.py.

For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by erick-dsnk** [comment]
Yeah that makes sense. I kinda figured it had something to do with it but wasn't sure. I had already asked in both the Python Discord server in the discord.py channel about this issue as well as the official dpy server but I had no luck in getting some help. 

Thanks for explaining!
