### ISSUE TITLE
Add a method to remove mentions like @everyone or @here in a Message

### ISSUE THREAD

**Issue by Ari24-cb24** [Rapptz/discord.py#6069]
## The Problem

So the problem is that some bots may have implemented a say command or something else where the output depends on the user input. I know that you can use embeds to avoid this but always using embeds isn't good.

## The Ideal Solution

Add a method like ``Message.removeMentions(everyone=True, here=True, role_mention=True, user_mention=True, channel_mention=True)`` that work's with a regex and replaces the mention with something like an escaped version of that mention or the username/channelname.

## The Current Solution

Currently you can use embeds or build your own extra long method for that.

## Summary

I think this should be implemented because this makes life a lot easier and discordjs also supports something like that.

Thanks for reading and sorry for my english skills shrug

**Comment by pikaninja** [comment]
this is already a thing, there is an allowed_mentions kwarg [docs here](https://discordpy.readthedocs.io/en/latest/api.html?highlight=messageable%20send#discord.abc.Messageable.send)

**Comment by Ari24-cb24** [comment]
![image](https://user-images.githubusercontent.com/56089155/99717593-e41ede80-2aa9-11eb-8e76-6e4f5966556d.png)
Here's an example if a user can control the output.

**Comment by Rapptz** [comment]
This is called AllowedMentions and is already implemented as mentioned above.
