### ISSUE TITLE
message.reactions is not a PartialEmoji

### ISSUE THREAD

**Issue by Snawe** [Rapptz/discord.py#6070]
## Summary

In the doc is written that `on_raw_reaction_add()` and `Message.reactions` both return a partial emoji
https://discordpy.readthedocs.io/en/latest/api.html?highlight=file#discord.PartialEmoji

However, if I am not wrong it seems like message.reactions returns a reaction (https://discordpy.readthedocs.io/en/latest/api.html?highlight=file#discord.Reaction)  and `on_raw_reaction_add` => payload.emoji is a PartialEmoji

## Reproduction Steps

`payload.emoji` in `on_raw_reaction_add()` looks like:
```
animated:False
id:None
name:'⚔'
```

```for reaction in message.reactions:```
reaction:
```
count:1
custom_emoji:False
emoji:':crossed_swords:'
me:True
```

=> You can see, the ID is missing in the message.reactions.

Even stranger is that if you pass a custom emoji to the  message.reactions you get:
```
count:1
custom_emoji:True
  emoji:<Emoji id=XXX name='name' animated=False managed=False>
  ...
  id:XXX
  managed:False
  name:'name'
```

## Intents
All but presences

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have provided the intents that my bot is using.

## System Information
Discord py 1.5.1

I stumble over it because I need the emoji id (even if its None) in `for reaction in message.reactions:` :/

**Comment by Daggy1234** [comment]
Message.reactions does not return a `PartialEmoji` , but rather a list of `Reaction` objects. On those Objects you can acccess the `emoji` attribute to get a Union of either `Emoji` or `PartialEmoji` or `str`.

**Comment by Snawe** [comment]
Ah ok. Seems I missunderstood the help..

Anyway. Is there a way to get an `Emoji` or `PartialEmoji` instead of a `string` if you access the `emoji`  via `Message.reactions` (on a non custom emoji)?
My problem is: I want to uniformly access the `reaction.emoji` with `.name` and `.id` no matter if it is or is not a custom.. and currently this only works on custom emojis :/

**Comment by SebbyLaw** [comment]
Non-custom emojs are just unicode strings. In this case, what would the `name` be? What would the `id` be? It doesn't make sense to return `Emoji` here when it is quite literally a string. 

The builtin [`isinstance`](https://docs.python.org/3/library/functions.html#isinstance) is what you want here.

**Comment by Snawe** [comment]
Thats true. But if you have a look at `payload.emoji` in `on_raw_reaction_add()` you get the emoji unicode in `name` and None in the `id`.

**Comment by SebbyLaw** [comment]
It is written in the documentation for [`Reaction.emoji`](https://discordpy.readthedocs.io/en/latest/api.html?highlight=file#discord.Reaction) that it is a `Union[Emoji, PartialEmoji, str]`. This **is not a bug with discord.py.** If you would like to change this behavior, feel free to open a pull request, but this bug report is invalid.

**Comment by Snawe** [comment]
Yes, you are right. Thats why I have written 
> Ah ok. Seems I missunderstood the help..
