### ISSUE TITLE
Strange behavior when editing embed in message

### ISSUE THREAD

**Issue by NESTOWL** [Rapptz/discord.py#6073]
## Summary

The Discord API allows post editing 5 times within 5 seconds.
Which allows us to change the message every second without breaking ratelimit

So it is, if you edit the content of the message every second then everything works well! This has been the case before.

But recently, for 4-5 months now, when editing an embed message, hangs occur, as if editing is blocked for a few seconds! There was no such thing before!

In other words
if you edit the content of the post, everything works as expected!
if you edit embed messages, problems appear.

## Reproduction Steps

here are two loops that edit the message
in the first, content is edited
in the second embed is edited

```
message = await _channel.send('123')
embed = discord.Embed()

for x in range(30):							# This works well as it should!
    content = f'TEST {x}'
    await message.edit(content=content)
    await asyncio.sleep(1)

for x in range(30):							# there is definitely a problem with this!
    embed.description = f'TEST {x}'
    await message.edit(embed=embed)
    await asyncio.sleep(1)
```
![UQxWYI83eg](https://user-images.githubusercontent.com/45520187/99882023-8071ee00-2c2e-11eb-9314-38b198a6b680.gif)
![0WrkC9qROm](https://user-images.githubusercontent.com/45520187/99882083-f8d8af00-2c2e-11eb-8370-7f4028782785.gif)

in the first cycle, the message is stably edited every second!
And in the second, delays occur ...
There was no such thing before!

I experimented a lot to figure it out and this is definitely not ratelimit
Below I wrote a sample code that without discord.py edits embed message with and there is no delay! and without breaking ratelimit

## Expected Results
Both of these loops will run at the same speed, will edit the message once a second!

## Actual Results
When editing embed, there are significant delays that were not there before!

## The Current Solution
if you edit the message without discord.py then everything works fine!
```
import aiohttp, json, asyncio

url = 'https://discord.com/api/v6/channels/779174359625498634/messages/779719047351631874'

headers = {
    'User-Agent': 'NESTOWL Testing Discord API Python(3.8.6) aiohttp(3.6.3)',
    'X-Ratelimit-Precision': 'millisecond',
    'Authorization': 'Bot token',
    'Content-Type': 'application/json'}

session = aiohttp.ClientSession()

for x in range(30):

    hueta = {
        'content': f'TEST {x}',
        'embed': {'description': f'TEST {x}'}
    }
    data = json.dumps(hueta, separators=(',', ':'), ensure_ascii=True)

    async with session.request('PATCH', url, headers=headers, data=data) as r:
        print('request num: ', x)
        print('STATUS: ', r.status)
        print('x-ratelimit-limit: ', r.headers.get('x-ratelimit-limit'))
        print('x-ratelimit-remaining: ', r.headers.get('x-ratelimit-remaining'))
        print('x-ratelimit-reset-after: ', r.headers.get('x-ratelimit-reset-after'))
        print()

    await asyncio.sleep(1)
```
![f6pCxjE5b6](https://user-images.githubusercontent.com/45520187/99881798-f37a6500-2c2c-11eb-8798-2df8434f1d38.gif)

## Intents

discord.Intents().all()

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information
- Python v3.8.6-final
- discord.py v1.5.1-final
- aiohttp v3.6.3
- system info: Windows 10 10.0.19041

**Comment by Rapptz** [comment]
The library doesn't do anything special here. Though this would have been more apparent if you had used logging instead of these screenshots. There is no special casing of this endpoint so any wait time is probably due to pre-emptive rate limit handling so you don't get hit with a 429. Note that sending and editing is under the same rate limit bucket.

**Comment by NESTOWL** [comment]
@Rapptz Can you please in more detail, if not difficult?

Before, everything was fine.
Is the Ratelimit for a message with Embed different ...
Well, it's strange that blocking only if the message contains Embed

Okay, good, but if I write my own function that will separately send a PATCH request to change the message and through it I will make editing within the Ratelimit 5 edits within 5 seconds.
Will there be no problems? I wrote the example code above

And I also asked a friend a similar loop in JS and changed Embed in message  every second and everything worked well!

**Comment by SebbyLaw** [comment]
I can't reproduce this behavior. The rate limit for editing is the same regardless of payload. 

The library does pre-emptive rate limit handling so you don't get hit with a 429, this is most likely what is happening in your case, although we can't be sure since you did not enable logging.

**Comment by NESTOWL** [comment]
Thanks, it looks like the problem is solved
on the same token, another copy of the bot was launched which updated messages ...

everything works on the newly created bot.
The only strange thing is that when editing content everything was fine, but when editing Embed there was a delay
according to the idea the rate limit for editing is the same regardless of payload.

**Comment by User25514** [comment]
I'm currently having this issue where it can take up to 5 minutes to edit an embed.

**Comment by MahdeenSky** [comment]
still happens...

**Comment by TrayHard** [comment]
`hueta = {` 
)))
