### ISSUE TITLE
Setting position=0 in create_text_channel() and create_voice_channel() doesn't work

### ISSUE THREAD

**Issue by Zahariel** [Rapptz/discord.py#6078]
## Summary

I have a bot that creates channels in my discord server. Some channels are "special", and I would like them to be created so that they sort to the top of their category (and I don't care how they sort within that; there's usually only one special channel in a category anyway). Most channels are not "special", and I'm fine with them sorting in creation order, or really anything else; I don't care. I tried to do this by using `create_text_channel(name, position=positive_number)` for non-special channels and `position=0` for special channels. This did not work; the special channel sorted to the bottom when it was created. It seems like 0 specifically is being treated the same as None. I can work around this personally by setting `position=at_least_two` for non-special channels and `position=1` for special channels, since I control everything in my current situation, but it still means that a bot has no reliable way to create a channel at the top of a category unless it can know that everything else has a higher number. I haven't tried `channel.edit(position=0)` but it wouldn't surprise me if it has the same problem.

## Reproduction Steps
```
# this is from a Cog but it doesn't actually matter
category = self.bot.get_channel(CATEGORY_CHANNEL_ID)
await category.create_text_channel("test-one", position=1)
await category.create_text_channel("test-three", position=3)
await category.create_text_channel("test-zero", position=0)
await category.create_text_channel("test-two", position=2)
```

## Expected Results
I wanted setting `position=0` to show up at the top of the category, or at worst after all other channels created with `position=0` (either of these would be fine); therefore, the channels in the above test would appear as test-zero, test-one, test-two, test-three

## Actual Results
The channels in the above test appear in the client in the order test-one, test-two, test-three, test-zero.

## Intents
Default Intents, didn't do anything special. I don't have Members and Presences activated but they really shouldn't matter here.

## Checklist
- [x] I have searched the open issues for duplicates.
I originally thought #2392 was the problem I was encountering, but I don't think it is. That issue refers to the actual value of `position` not matching the observed position in the client. I don't care about that; I just want a way to create a channel reliably at the top of its category.

## System Information

- Python v3.8.5-final
- discord.py v1.5.1-final
- aiohttp v3.6.3
- system info: Linux 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020

(this looks weird because it's in a Docker Compose on Docker Desktop for Windows)

**Comment by NCPlayz** [comment]
The `position` parameter is never modified throughout its lifetime in `create_text/voice_channel` so there is a high chance this could be an upstream issue (/ implementation detail), so I have filed an issue at discord/discord-api-docs#2640.

**Comment by Rapptz** [comment]
This seems to have been fixed upstream.
