### ISSUE TITLE
userid to discord username resolution sporadically failing

### ISSUE THREAD

**Issue by kelly-cs** [Rapptz/discord.py#6079]
## Summary
In a simple bot implementation I've been working on, discord username resolution has suddenly began to fail after 4 months of usage with no code modifications. That is to say:
**username = client.get_user(discord_userid_integer).name** had originally worked without issue for 4 months.
Now, a strange issue happens in which client.get_user(id).name returns Nonetype for certain users, seemingly for no reason. 
https://github.com/kelly-cs/rumsey-bot/issues/7

## Reproduction Steps

These users have perfectly valid userids that are independently verifiable with <@id> in chat and online, and my storage of this information has not been corrupted. This issue continues to happen until a user is @'d in a discord channel, and when this code is ran again thereafter (that is, until the bot itself is restarted), the bot will "remember" the username going forward. This issue has just recently began.

## Expected Results

It is expected that doing client.get_user(user_id_as_an_integer).name will return an appropriate discord username (and has for 4 months)

## Actual Results

Instead of returning a discord username when provided a valid id, Nonetype is returned for certain users all of a sudden until they are @'d in chat while bot is online.

**Comment by SebbyLaw** [comment]
Please don't delete parts of the issue template, they are there for a reason. Specifically, your issue is missing the section with your subscribed intents.
