### ISSUE TITLE
Support chunking an AsyncIterator

### ISSUE THREAD

**Issue by RobertCraigie** [Rapptz/discord.py#6082]
## The Problem

In a situation where iterating one by one is inefficient but calling flatten() could blow up memory usage and result in a very long time for users to see results

## The Ideal Solution

Add an optional argument to flatten() which if passed would only flatten the first n items.
or
Add a chunk() method that does the same as above.

Example usage
```py
async for items in iterator.chunk(n=500):
  await do_chunked(items)
```

## The Current Solution

Manually chunking, e.g.
```py
curr = 0
chunk = []
chunk_at = 500
async for item in iterator:
  curr += 1
  chunk.append(item)
  if curr >= chunk_at:
    await do_chunked(chunk)
    curr = 0
    chunk = []

if chunk:
  await do_chunked(chunk)
```

## Summary

Add support for chunking an AsyncIterator.

I would be happy to make a PR for this feature if it is wanted, thanks.

**Comment by Rapptz** [comment]
I think this idea is fine. I'm not sure if I want to call it `chunk` since there's a library concept for this already under [`Guild.chunk`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Guild.chunk). On the other hand there's no other name for this concept so maybe the confusion wouldn't be there.

**Comment by nwunderly** [comment]
While there might be a small amount of confusion, this concept is generally called chunking, as you mentioned. I don't think `AsyncIterator.chunk(n)` would really be confused with `Guild.chunk` as long as the docs are clear enough. This seems like a useful idea. An optional argument to `flatten()` would, I think, be less useful than being able to read an AsyncIterator in chunks.
