### ISSUE TITLE
guild value did not exist.

### ISSUE THREAD

**Issue by gunyu1019** [Rapptz/discord.py#6083]
## Summary
Earlier this morning, a server confirmed that it was trying to use this discord bot. However, since the discord bot joined the server, there has been a continuous error (typically similar to #4008) and we have debugged it, but as shown in the picture below, we have found a server that does not have a value. It was reported that only IDs exist and other members, owners, and channels are all empty or have a quirky server that returns None.

## Reproduction Steps
I don't know how it happened. I think it is a serious bug even though it is a phenomenon that has happened by accident.

## Expected Results
I think the "owner" value should be recalled even if the list does not contain or is normal.
The "client.guilds" alone should have called up the server name if it were normal.

## Actual Results
In fact, I asked the server to "member_count" but the same thing happened as #4008. And I tried "owner" to find out the owner of the server, but None was returned and I tried to call up "channels" to bring up the channel list, but there was nothing in the list. And just in case, I asked for the id value, but strangely, only the id value existed.

I normally "client.guilds" to find the location of the server, and when I printed the value, the error was called.
```py
import discord

client = discord.Client()
@client.event
async def on_ready():
    print(client.guilds[14])
client.run(token)
```
```pytc
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\gunyu\AppData\Roaming\Python\Python38\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "d:\test.py", line 8, in on_ready
    print(client.guilds[14])
TypeError: __str__ returned non-string (type NoneType)
```
Requiring a name to obtain a normal server name returns None.
```py
import discord

client = discord.Client()
@client.event
async def on_ready():
    print(client.guilds[14].name) #None
client.run(token)
```

## Intents
In the case of an intent, both "PRESENCE INTENT" and "SERVER MEMBERS INTENT" have been activated recently by asking the discords.

## Checklist

- [x] I have searched the open issues for duplicates.
I thought it was a problem similar to #4008, but when I checked it, I found a dummy server that didn't exist.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information
* Python v3.8.6
* discord.py v1.5.1
* aiohttp v3.6.3
* system info: Linux4.19.118-v7l+ or Windows 10 Pro(Checked in two places)

**Comment by SebbyLaw** [comment]
I can't reproduce this. 

Make sure your intents are enabled both in your code and in the developer portal.

**Comment by gunyu1019** [comment]
It was all activated. In particular, since this discord bot has already been certified, it has been activated by asking questions.
![image](https://user-images.githubusercontent.com/16767890/100187740-14440280-2f2c-11eb-8e21-e5dfe59fb2e9.png)

The content code is included as follows.
```py
intents = discord.Intents.default()
intents.members=True
intents.guilds=True
intents.presences=True

client = discord.Client(intents=intents)
```
Only this guild seems to have a constant problem. If necessary, we can provide the id value of the guild that is causing the problem.

**Comment by iDutchy** [comment]
I also seem to be having this issue with 1 guild my bot is in. I have guilds, members and presences intent enabled and both privileged intents. Just this 1 guild has this issue. Using a get_guild on the ID returns both name and member_count as None. Maybe more, but that's all I see in the repr. Using fetch_guild it does return the name, however still no member_count...

**Comment by Rapptz** [comment]
This happens if a guild is unavailable.

Reasons include:

1. The guild is legitimately down.
2. The guild reached the presence cap and no more users can join.
3. You do not have the guild intent.
4. The client never received the guild's full info from the gateway.
5. Discord doesn't want to make that guild available for whatever reason. 

Either way, not much I can do here. The code being provided here feels incomplete and there isn't really much information to go off from other than vague statements that aren't actionable. Consider checking your intents or just making sure the guild is actually available. You can do this by checking the "unavailable" attribute.

**Comment by iDutchy** [comment]
> This happens if a guild is unavailable.
> 
> Reasons include:
> 
>     1. The guild is legitimately down.
> 
>     2. The guild reached the presence cap and no more users can join.
> 
>     3. You do not have the guild intent.
> 
>     4. The client never received the guild's full info from the gateway.
> 
>     5. Discord doesn't want to make that guild available for whatever reason.
> 
> 
> Either way, not much I can do here. The code being provided here feels incomplete and there isn't really much information to go off from other than vague statements that aren't actionable. Consider checking your intents or just making sure the guild is actually available. You can do this by checking the "unavailable" attribute.

With all intents enabled and using fetch_guild, Guild.unavailable returned False

**Comment by Rapptz** [comment]
The concept of an unavailable guild is only applicable via gateway.
