### ISSUE TITLE
Sound Scrambles when playing

### ISSUE THREAD

**Issue by js802025** [Rapptz/discord.py#6086]
## Summary
When using vc.play with FFmpegPCMAudio the sound condenses into a short bit, doesn't play at all or cuts off.

## Reproduction Steps
`if message.author.voice and message.author.voice.channel:
            vc = await message.author.voice.channel.connect()
            source = discord.FFmpegPCMAudio('sound_file.mp3')
            vc.play(source, after=lambda e: print('done', e))`

## Expected Results
the audio file to play correctly

## Actual Results
the audio plays flawed

## Intents

default

## Checklist

- [x ] I have searched the open issues for duplicates.
- [x ] I have shown the entire traceback, if possible.
- [ x] I have removed my token from display, if visible.
- [ x] I have provided the intents that my bot is using.

## System Information
- Python v3.8.5-final
- discord.py v1.5.1-final
- aiohttp v3.6.3
- system info: Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64

**Comment by numbermaniac** [comment]
Does it happen for any audio file you try, or just one specific file?

**Comment by js802025** [comment]
I’m pretty sure it’s because the file cant load in time and when I try to use 0pus it calls not in discord. I got it working with a bunch of delays but it’s not a great solution

**Comment by Kizuwe1lf** [comment]
Try not directly joining voice channel
Join the voice channel then do something like this

```python
guild = ctx.guild
voice_client: discord.VoiceClient = discord.utils.get(bot.voice_clients, guild=guild)
audio_source = discord.FFmpegPCMAudio(f"your_audio_source.mp3")
if not voice_client.is_playing():
    voice_client.play(audio_source, after=None)
```
