### ISSUE TITLE
Member not found errors

### ISSUE THREAD

**Issue by EinTim23** [Rapptz/discord.py#6088]
## Summary

If you run a command in discord dms where you need to mention someone you will get an error.

## Reproduction Steps

make a bot which accepts commands by dm and where you need to mention someone.
## Expected Results

This error should pop up and the command should fail:
![grafik](https://user-images.githubusercontent.com/57799248/100385501-12109f80-3023-11eb-8a87-d779ff9e9621.png)

## System Information

Version information:
- Python v3.7.7-final
- discord.py v1.6.0-alpha
    - discord.py pkg_resources: v1.6.0a2582+g12d0ae7
- aiohttp v3.6.3
- system info: Windows 10 10.0.19041

**Comment by fwrs** [comment]
Please tell us what intents are you using for your bot? This is the `discord.Intents` class you pass to the client

**Comment by uKaigo** [comment]
Members are attached to guilds, meaning they don't work in DMs. That's why you got a MemberNotFound error.

And please, don't erase anything in the issue template, they're there for a reason.
