### ISSUE TITLE
AutoBuild Command Summary string

### ISSUE THREAD

**Issue by CodingWideScreen** [Rapptz/discord.py#6097]
## The Problem

I find it time consuming have to manually write out all of my command documentation into command like !commands that would return requesting user a list of available commands to channel/dm.

## The Ideal Solution

Unsure if possible in Python to collect the """comments""" on the decorated bot.command or client.command functions but this would be nice as one could just write the documentation in the comments and have access to them in a dictionary we could access by the commands name

## The Current Solution

Write out a giant string that isn't scalable when adding new commands, must manually add in more documentation for those commands.

## Summary

Creation of command documentation based on decorated function comments

**Comment by Zomatree** [comment]
The library already does this, you can use [Command.help](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.Command.help) to access the docstring of the command.
