### ISSUE TITLE
Add Reaction.remove() on rewrite

### ISSUE THREAD

**Issue by Nekorooni** [Rapptz/discord.py#610]
Is this something to consider so you don't have to call `await message.remove_reaction(reaction.emoji, user)`?
Or would this not be convinient since there's no user linked to the Reaction?

Mainly for this:
```py
r, u = await self.bot.wait_for('reaction_add', check=lambda r, u: u.id == ctx.author.id)
await m.remove_reaction(r.emoji, u)
# or
await r.remove()
```
I can imagine this functionality not being worth the hassle of recoding though.

**Comment by Harmon758** [comment]
This was added with https://github.com/Rapptz/discord.py/commit/806295a1be2cfb0ebc8659aa9abb605bd59ff3b6 (#1891).

**Comment by BatteTarte** [comment]
this dont work

**Comment by Ender2K89** [comment]
you do realize this issue is from 2019.. right?
