### ISSUE TITLE
Occasional Command failes to return member object when using discord.utils.get() and or [bot/client].get_user()

### ISSUE THREAD

**Issue by shireishi** [Rapptz/discord.py#6104]
## Summary

Failure to return member object.

When using a proposal command for a verification process, the bot gathers the user information from the member id and parsing through the members of the server. Before moving to the discord.utils.get() I had used bot.get_user() but that had returned a NoneType Object as well. The command has worked in the past, but after a restart of the bot, for a new command to be added, the bot no longer does the command, instead returning a NoneType Object, and I get the error NoneType object has no attribute name.

## Reproduction Steps

user_object = discord.utils.get(ctx.guild.members, id=int(user_id))

## Expected Results

print(user_object.name, user_object.discriminator)
>>> The Doctor#4141

## Actual Results

discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'name'

## Intents

Intents = All

## Checklist

- [x] I have searched the open issues for duplicates.
- [ ] I have shown the entire traceback, if possible.
- [ ] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python v3.7.3-final
- discord.py v1.5.1-final
- aiohttp v3.6.2
- system info: Linux 5.4.72-v7+ #1356 SMP Thu Oct 22 13:56:54 BST 2020

**Comment by NotKino** [comment]
This is not a bug with the library. You may have the wrong ID, your bot cannot "see" the object, or something else. Generally you should discuss these types of issues in the respective channels of the [Official Discord.py Discord Server](https://discord.gg/dpy) before making an issue on Github.

**Comment by shireishi** [comment]
> This is not a bug with the library. You may have the wrong ID, your bot cannot "see" the object, or something else. Generally you should discuss these types of issues in the respective channels of the [Official Discord.py Discord Server](https://discord.gg/dpy) before making an issue on Github. 

I have used the same id in another command and it retrieved all requested information, however using the exact same process in another command, it fails to return the user information.

**Comment by Harmon758** [comment]
Have you enabled the server members intent in your bot's dashboard?

**Comment by Rapptz** [comment]
These functions are documented to return `None` if they're not cached. How you handle it is up to you but there are ways to mitigate the library not caching members, for example [the documentation on Intents has some troubleshooting hints](https://discordpy.readthedocs.io/en/latest/intents.html#where-d-my-members-go).
