### ISSUE TITLE
Can't Private Message, using the API

### ISSUE THREAD

**Issue by bobmcdouble3** [Rapptz/discord.py#611]
I have been making a simple command to private message myself, but it appears not to do anything. It doesn't throw any errors, and if I put it in a try, except statement, it will just go with no exceptions. I am using this code: 'bot.send_message(message.author, 'hi')'

Thanks, kmak

**Comment by Phxntxm** [comment]
Are you awaiting `bot.send_message`? It is a coroutine.

**Comment by bobmcdouble3** [comment]
Haha, I am so dumb, I forgot await

**Comment by Real-Wizard** [comment]
lol

**Comment by bobmcdouble3** [comment]
works fine now
thanks
