### ISSUE TITLE
magic async def that remains in the cog on any changes

### ISSUE THREAD

**Issue by cucumb3r-ru** [Rapptz/discord.py#6115]
## Summary

It's time to create a new async def (not command) for my cog ('Economy') to send server transaction information to a specific channel. Having created an async def in Economy, I tried it from another cog to check it works (everything was correct). After supplementing that async def again with new transaction types, I reload cog (unload + load), tested again from another cog, I noticed that my changes did not take effect. I updated the async def a couple of times, did a reload cog, but nothing changed (as if it worked like the very first time). After rebooting the machine, it was again the same. I tried commenting out this function, reload cog again, but it still worked like the very first time. I tried changing other functions in the cog (commands, simple def), after reloading the cog they worked with the changes, but not the same async def. (async def works even by calling inside the cog when it is commented out)
_note_ - I have the same thing with my classes, I update them, reload cog, but there are no changes in the work of the class, only after restarting the bot does it start working

## Reproduction Steps

1. Create a bot with cogs
2. Write a simple async def (not a command) to one of the cogs
3. reload cog
4. Rewrite async def work
5. reload cog

## Expected Results

I was expecting working changes to async def after reload cog

## Actual Results

async def remains working as it was the first time for any changes

## Intents

from none to guilds, members, bans, emojis, voice_states, guild_messsages, guild_reactions, presences = True

## Checklist

- [x] I have searched the open issues for duplicates.
- [ ] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

Python 3.8.5
discord.py 1.5.1
Linux bot-machine 5.4.0-56-generic 62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64 GNU/Linux _(uname -a)_

**Comment by cucumb3r-ru** [comment]
I feel like an idiot that my code view was somehow strangely updated, and everything was fine. sorry

**Comment by Harmon758** [comment]
For future reference, they're called coroutines. `async def` is simply the syntax you use to define them.

Also, in the future, you might want to try to create and provide a reproducible example (MCVE/SSCCE).
This would help to confirm that it's an issue with the library rather than on your end and potentially avoid something like this.
