### ISSUE TITLE
Sending a message with files seems to be blocking other messages

### ISSUE THREAD

**Issue by Mattlau04** [Rapptz/discord.py#6126]
## Summary

When a message with files is sent in a channel, other messages (from other commands) will have to wait until the message with files is sent before they are sent

## Reproduction Steps

Just send a message with a file, for exemple with the command bellow
```python
@commands.command()
async def testsending(self, ctx):
    await ctx.send('loading file')
    filesss = discord.File(open("filewow.txt"), filename="testfile.txt")
    await ctx.send('starting sending')
    await ctx.send("aaaa", file=filesss)
```

## Expected Results

The other messages that should be sent from other command called after should be sent without having to wait for the message with files to finish sending

## Actual Results

here is a screenshot of the command above blocking all messages until the file gets sent https://i.imgur.com/tdn3N1w.png

## Intents

i pass discord.Intents.all()

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python v3.9.0-final
- discord.py v1.5.1-final
- aiohttp v3.6.3
- system info: Windows 10 10.0.18362

**Comment by Rapptz** [comment]
This is an issue with the dependency, aiohttp and I do not control it. You're better off taking it in their issue tracker (without any discord.py code).

**Comment by Mattlau04** [comment]
Just in case it might be something else in my bot, i made a completly fresh one:

```python
import discord
from discord.ext import commands

bot = commands.Bot(command_prefix='ff!')

@bot.event
async def on_ready():
    print('logged in')

@bot.command()
async def testsending(ctx):
    await ctx.send('loading file')
    filesss = discord.File(open("filewow.txt"), filename="testfile.txt")
    await ctx.send('starting sending')
    await ctx.send("aaaa", file=filesss)

@bot.command()
async def a(ctx):
    print('a')
    await ctx.send('a')

bot.run([censored])
```
but the issue still persists: https://i.imgur.com/8zsRSEp.png

**Comment by Mattlau04** [comment]
ok :/
