### ISSUE TITLE
this happens when I try to install discord.py. I´m on w10 and python 3.9.0

### ISSUE THREAD

**Issue by antonchu2006** [Rapptz/discord.py#6127]
PS E:\programas\python\bot> py -3.9 -m pip install discord.py      
Collecting discord.py
  Using cached discord.py-1.5.1-py3-none-any.whl (701 kB)
Collecting aiohttp<3.7.0,>=3.6.0
  Using cached aiohttp-3.6.3.tar.gz (1.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Antón\AppData\Local\Programs\Python\Python39\python.exe' 'C:\Users\Antón\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\ANTN~1\AppData\Local\Temp\tmpzjado9kt'
         cwd: C:\Users\Antón\AppData\Local\Temp\pip-install-u3luwq6j\aiohttp_aec13e5d000d4dbeb527b2db968201e0
    Complete output (24 lines):
    Error in sitecustomize; set PYTHONVERBOSE for traceback:
    SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xf3 in position 0: unexpected end of data (sitecustomize.py, line 7)
    running dist_info
    creating C:\Users\Antón\AppData\Local\Temp\pip-modern-metadata-rhob3uus\aiohttp.egg-info
    writing C:\Users\Antón\AppData\Local\Temp\pip-modern-metadata-rhob3uus\aiohttp.egg-info\PKG-INFO
    writing dependency_links to C:\Users\Antón\AppData\Local\Temp\pip-modern-metadata-rhob3uus\aiohttp.egg-info\dependency_links.txt
    writing requirements to C:\Users\Antón\AppData\Local\Temp\pip-modern-metadata-rhob3uus\aiohttp.egg-info\requires.txt
    writing top-level names to C:\Users\Antón\AppData\Local\Temp\pip-modern-metadata-rhob3uus\aiohttp.egg-info\top_level.txt
    writing manifest file 'C:\Users\Antón\AppData\Local\Temp\pip-modern-metadata-rhob3uus\aiohttp.egg-info\SOURCES.txt'
    reading manifest file 'C:\Users\Antón\AppData\Local\Temp\pip-modern-metadata-rhob3uus\aiohttp.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'aiohttp' anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '*.lib' found anywhere in distribution
    warning: no previously-included files matching '*.dll' found anywhere in distribution
    warning: no previously-included files matching '*.a' found anywhere in distribution
    warning: no previously-included files matching '*.obj' found anywhere in distribution
    warning: no previously-included files found matching 'aiohttp\*.html'
    no previously-included directories found matching 'docs\_build'
    writing manifest file 'C:\Users\Antón\AppData\Local\Temp\pip-modern-metadata-rhob3uus\aiohttp.egg-info\SOURCES.txt'
    creating 'C:\Users\Antón\AppData\Local\Temp\pip-modern-metadata-rhob3uus\aiohttp.dist-info'
    error: invalid command 'bdist_wheel'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Antón\AppData\Local\Programs\Python\Python39\python.exe' 'C:\Users\Antón\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\ANTN~1\AppData\Local\Temp\tmpzjado9kt' Check the logs for full command output.

**Comment by Harmon758** [comment]
Make sure you have setuptools installed and that it's up to date, e.g. `py -3.9 -m pip install --upgrade setuptools`.
If it still errors, try installing the latest version of wheel, e.g. `py -3.9 -m pip install --upgrade wheel`.

For code block usage, see https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks.

**Comment by AGaiki** [comment]
> Make sure you have setuptools installed and that it's up to date, e.g. `py -3.9 -m pip install --upgrade setuptools`.
> If it still errors, try installing the latest version of wheel, e.g. `py -3.9 -m pip install --upgrade wheel`.
> 
> For code block usage, see https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks.
I attempted running both commands, and then running `py -3 -m pip install -U discord.py[voice]` and received an error (albeit a different one), which is attached. I have also tried running the Microsoft C++ Build Tools installer, as it suggested I do that, which made no difference. I am running Windows 10 with Python 3.9.
[discord.py error.txt](https://github.com/Rapptz/discord.py/files/5648230/discord.py.error.txt).

**Comment by Harmon758** [comment]
See #5898 and #5984.

In the future, you should just paste the error directly.

**Comment by Turcan-vs** [comment]
because of python 3.9, install 3.8.2 and try again. it would work.
