### ISSUE TITLE
how do I install it to my discord server?

### ISSUE THREAD

**Issue by TheLegend2003** [Rapptz/discord.py#613]
making a new discord server & I don't have a clue, can someone help?

**Comment by VarHolo** [comment]
What do you even mean?
The discord.py library is for making bots with python.
If you are talking about how you can install with pip, Rapptz made a very detailed tutorial on the project page...

**Comment by Rapptz** [comment]
You don't install the library to a Discord server.

You install it on a machine and then program a bot and run the program on said machine.
