### ISSUE TITLE
Bot presence "Online" after clean log-off via .close()

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [Rapptz/discord.py#6134]
## Summary

When the bot is logged off cleanly via `.close()`, its Presence nevertheless remains "Online" for about 110 seconds.

## Reproduction Steps

The below bot perfectly reproduces the issue:

```py
import os
import discord

client = discord.Client()

@client.event
async def on_message(message):
	if message.author == client.user: return

	if message.content == "die":
		await message.channel.send("I am now exiting.")
		await message.channel.send("Please observe, however, that my Presence will remain incorrectly Online for about 110 seconds.")
		await message.channel.send("(Bye.)")
		await client.close()

client.run(os.environ['token'])
```

## Expected Results

At least a non-sharded bot should go Offline when disconnecting cleanly via `.close()`.

## Actual Results

Even a non-sharded bot appears Online for approximately 110 seconds after disconnecting cleanly via `.close()`.

## Intents

I am not passing any Intents to the bot.

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] ~~I have shown the entire traceback, if possible.~~ There is no traceback
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python `v3.8.6-final`
- discord.py `v1.5.1-final`
- aiohttp `v3.6.3`
- system info: Linux `5.8.18-200.fc32.x86_64` #1 SMP Mon Nov 2 19:49:11 UTC 2020

**Comment by Rapptz** [comment]
If the bot eventually goes offline that's all that I can do. Cleanup closes the websocket and everything else involved so there's literally nothing I can do more than that.

**Comment by JamesTheAwesomeDude** [comment]
> If the bot eventually goes offline that's all that I can do. Cleanup closes the websocket and everything else involved so there's literally nothing I can do more than that.

Just killing the TCP socket is *not* a full cleanup.

If `.logout()` aka `.close()` is called, and didn't have any fatal issues in doing so, you should also issue a disconnect code to the gateway.

> ### [Disconnections](https://discord.com/developers/docs/topics/gateway#disconnections)
> …
> When you close the connection to the gateway with the close code 1000 or 1001, your session will be invalidated and your bot will appear offline. If you simply close the TCP connection, or use a different close code, the bot session will remain active and timeout after a few minutes.

**Comment by Rapptz** [comment]
Yes, and the websocket is already closed with a close code of 1000.

**Comment by JamesTheAwesomeDude** [comment]
> the websocket is already closed with a close code of 1000

The Discord API docs [see prev. comment] state that

* if that happens, the bot “will appear offline”
  (which does *not* happen);
* and, if it does *not*, the bot “will remain active and timeout after a few minutes”
  (which *is* what happens).

How can I verify that this code really is being *sent*? (I see that [the underlying `ws.close()` function](https://github.com/aio-libs/aiohttp/blob/3.6/aiohttp/client.py#L903) doesn't _seem to_ take the argument it's [being passed](https://github.com/Rapptz/discord.py/blob/v1.5.x/discord/client.py#L618), though I could be misinterpreting the code.)

If it is really being sent, I'll take that verification and pass it upstream to Discord.

**Comment by Rapptz** [comment]
If the argument can't be passed then you'd receive a `TypeError` upon `close` being called. Obviously, since this is not the case it means that you have the completely wrong function there.

The function you're looking for is [here](https://github.com/aio-libs/aiohttp/blob/3.6/aiohttp/client_ws.py#L162), note that it does have a code that can be passed around. 

Like I've mentioned more than once in this issue, I already do what I have to do.

**Comment by cheez3d** [comment]
I just wanted to mention that for example versions 1.3.4 or 1.3.3 of the library (these are the ones that I've tried) do not exhibit this behavior. When calling `close` or `logout` the bot goes offline immediately.
Starting from 1.4, the issue described here appears.
Maybe there is something that has changed between 1.3 and 1.4 that causes this?

**Comment by Rapptz** [comment]
No, this code has been relatively unchanged for a long time. The only change-set was made to `Client.run` to not call `close` if it was already called which isn't particularly related.

**Comment by JamesTheAwesomeDude** [comment]
@Rapptz I just tried it out in a venv, and I **can confirm** that it's a regression.

```sh
python3 -m venv demo6134
. demo6134/bin/activate
pip3 install https://github.com/Rapptz/discord.py/archive/v1.3.3.zip
python3 -m discord -v
read -r -s token ; export token
python3 -m demo.py
```

```py
# demo.py
import discord, os

client = discord.Client()

@client.event
async def on_message(message):
	if message.author == client.user: return
	await message.channel.send("<https://discord.com/developers/docs/topics/gateway#disconnections>\n> When you close the connection to the gateway with the close code 1000 or 1001, your session will be invalidated and your bot will appear offline.")
	await client.close()

client.run(os.environ['token'])
```

This bug **is not present** under the following runtime:

- Python v3.8.6-final
- discord.py `v1.3.3-final
- aiohttp v3.6.3
- websockets v8.1
- system info: Linux 5.9.11-100.fc32.x86_64 #1 SMP Tue Nov 24 19:16:53 UTC 2020

However, it is still present (I just took a video for the Discord Support ticket I'd opened) with the runtime described in the OP.

https://user-images.githubusercontent.com/2776014/102680044-2f441400-4172-11eb-83f2-28983544136b.mp4

**Comment by JamesTheAwesomeDude** [comment]
Here is footage of the bug not being present on the previous version

https://user-images.githubusercontent.com/2776014/102680127-d4f78300-4172-11eb-8de6-2060797db0a4.mp4

**Comment by JamesTheAwesomeDude** [comment]
(And, lest there be any doubt that the purity of a virtualenv was causing the bug not to be present or tainted system libraries ere causing the problem: I just tried the same venv process with the latest, `v1.5.1-final`, and the bug is still present.)

**Comment by Rapptz** [comment]
v1.3.x used a different websocket library, so, we're really just back to the same square. I'm locking this issue as resolved.
