### ISSUE TITLE
`on_member_update` triggers twice when changing to `offline` status

### ISSUE THREAD

**Issue by Kwieeciol** [Rapptz/discord.py#6141]
## Summary

`on_member_update` triggers twice when changing to `offline` status, the first time it triggers the statuses are the same, the second time, they're different.

## Reproduction Steps

```py
@bot.event
async def on_member_update(before, after):
    print(before.status, after.status, sep=' -> ')
```
And change the status to `offline`

## Expected Results

```
{first status} -> offline
```
## Actual Results

```
{first status} -> {first status}
{first status} -> offline
```

## Intents

I have all intents enabled

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python v3.9.0-final
- discord.py v1.5.1-final
- aiohttp v3.6.3
- system info: Windows 10 10.0.18362

**Comment by BluePhoenixGame** [comment]
The activity may also change, which could be why it's triggered twice. Once for status, once for activity.

**Comment by Kwieeciol** [comment]
I have activities disabled in my discord account

**Comment by Rapptz** [comment]
This event is basically pass through from the gateway events PRESENCE_UPDATE and GUILD_MEMBER_UPDATE. I'm unsure what in particular is triggering the first event but you'll have to investigate by checking the changed attribute. As it stands to reason now I don't believe there's anything odd on my part calling the event more than necessary.

**Comment by scrazzz** [comment]
When logged into two clients (mobile and pc) changing the presence on one client triggers `on_member_update` and prints the status multiple times. I'm not sure if that's the problem or not.
