### ISSUE TITLE
Python 3.7.9: No module named 'discord'

### ISSUE THREAD

**Issue by hoverdoge** [Rapptz/discord.py#6143]
## EDIT

I was running the wrong interpreter in VS Code.

## Summary

I just switched from a web-based IDE(repl.it) to VS Code on my Mac running Catalina. I have installed 3.7.9 and set it as global, and of course installed discord.py with pip. However, running `import discord` still causes the following error to appear: `ModuleNotFoundError: No module named 'discord'`. 
I also have the following packages: https://i.stack.imgur.com/dlnTq.png

## Reproduction Steps

```import discord``` in VS Code running Python 3.7.9

## Expected Results

I expected discord to reflect its status as being installed.

## Actual Results

`ModuleNotFoundError: No module named 'discord'`
`Traceback (most recent call last):
  File "/Users/myname/Desktop/CM-Public/main.py", line 6, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'`

## Intents

I am using all intents, though I doubt it's relevant to this.

## Checklist

- [x] I have searched the open issues for duplicates. (i have looked and found all issues and soverflow posts and none have solved my issue)
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python v3.7.9-final
- discord.py v1.5.1-final
- aiohttp v3.6.3
- system info: Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64

**Comment by numbermaniac** [comment]
In your Python script, what output do you get if you try the following?
```py
import sys
print(sys.version)
```

**Comment by hoverdoge** [comment]
`3.7.9 (default, Dec  9 2020, 16:48:19) 
[Clang 11.0.3 (clang-1103.0.32.62)]`

**Comment by gogurtenjoyer** [comment]
This isn't a bug with the library - what is most likely happening is that you've installed discord.py to a different python environment than you are using with VS Code. A simple way to check this would be to try running your bot script from the command line, using the python interpreter that corresponds to the environment that you've installed it to.

**Comment by hoverdoge** [comment]
Sorry, I edited the post earlier but forgot to close it. If anyone else is finding this, make sure you have discord.py installed to the interpreter you are using.
