### ISSUE TITLE
Event loop is closed

### ISSUE THREAD

**Issue by Miolus** [Rapptz/discord.py#6152]
## Summary

Shard crashes in certain cases when shard.connect()  is used.

## Reproduction Steps

on_disconnect(id):
sh = bot.get_shard(id)
sh.connect()

bot  = bot.run(****, reconnect'=False)

## Expected Results

Shard reconnects

## Actual Results

In certain cases bot crashes with Event loop is closed error.

## Intents

members

## Checklist

- [x ] I have searched the open issues for duplicates.
- [ x] I have shown the entire traceback, if possible.
- [ x] I have removed my token from display, if visible.
- [x ] I have provided the intents that my bot is using.

## System Information

discord.py 1.5.1

**Comment by Rapptz** [comment]
By removing reconnect logic from the `bot.run` code, whenever a disconnect is encountered the function terminates which cleans up the event loop and closes it. I recommend leaving the auto reconnect logic enabled if you want it, rather than poorly reimplementing it.

**Comment by Miolus** [comment]
@Rapptz i did this, but after a few days it did not reconnect some shards anymore.

**Comment by Miolus** [comment]
But ok thanks for help, i will make a different logic.
