### ISSUE TITLE
playing

### ISSUE THREAD

**Issue by pyth0nnnn** [Rapptz/discord.py#6154]
## The Problem

Make it easier to check whether a member is playing a game and what is the title of that game

## The Ideal Solution

Something like member.game.playing which returns a boolean if a member is playing a game or not and something like member.game.name that returns the name of the game they are playing

## The Current Solution

If the member has only one activity you can get the name of the game and check if its a game easier but if they have multiple activities you have to go through the activities and check the type of activity but some games have different types which makes it harder to do.

## Summary

I would like an easier way to check if a member is playing a game and then the name of that game, preferably something just added in the member class.

Thank you

**Comment by Rapptz** [comment]
You're looking for [`Member.activity`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Member.activity).

**Comment by pyth0nnnn** [comment]
Yes I checked that out but if someone has a custom status it doesn't have anything about the game they are playing but only that status

**Comment by Taarek** [comment]
Read the note of the thing Rapptz linked.
