### ISSUE TITLE
accessing NSFW tagged channels?

### ISSUE THREAD

**Issue by awesomebrick** [Rapptz/discord.py#616]
I'm trying to write a bot that tests the activity of a person on a server, in terms of messages sent. It's basically code built on top of one of the examples. However, whenever it hits an NSFW channel, it returns an error, even though the bot should for all intents and purposes be able to view messages in that channel. Is there a limitation with that new warning Discord has built into nsfw tagged channels? Or am I just missing something?

**Comment by khazhyk** [comment]
Is this a user bot.
Do you have permission to read the channel (server.me.permissions_in(channel).read)

**Comment by Rapptz** [comment]
I'm pretty sure the NSFW channel thing is purely a client-side thing, so I'm not sure what issue you would be having.

This needs more information.

**Comment by kratonisch** [comment]
Which python version do you use?
