### ISSUE TITLE
Timed invites do not trigger on_invite_delete

### ISSUE THREAD

**Issue by thedoctorjtd** [Rapptz/discord.py#6169]
## Summary

Limited use invites trigger on_invite_delete, however timed invites will not trigger on_invite_delete.

## Expected Results

I would expect any invite removals (manual, timed, or user limited) to trigger on_invite_delete.

## Intents

default and members

## Checklist

- [x ] I have searched the open issues for duplicates.
- [n/a ] I have shown the entire traceback, if possible.
- [n/a ] I have removed my token from display, if visible.
- [x ] I have provided the intents that my bot is using.

## System Information

- Python v3.8.2-final
- discord.py v1.5.1-final
- aiohttp v3.6.2
- system info: Windows 10 10.0.19041

**Comment by SebbyLaw** [comment]
This is a discord limitation. Nothing the library can do about it
