### ISSUE TITLE
How to send direct message using the user id

### ISSUE THREAD

**Issue by Ikeiwa** [Rapptz/discord.py#617]
In my project I store the id of users in a sqlite database and I want to send a direct message to them, but I can't find a way using only a user id.
If this is impossible, is there a better method to save users in a database ?

**Comment by YourLocalDemon** [comment]
This is a FAQ
http://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-get-a-specific-user-role-channel-server
If that doesn't work then make sure that your IDs are of correct type (int/str) for your version of d.py

**Comment by Ikeiwa** [comment]
thanks!
I manage to make it work by using server.get_member.

**Comment by LoloTest76** [comment]
uwu
