### ISSUE TITLE
When max concurrency is triggered, the command invocation still counts towards cooldown

### ISSUE THREAD

**Issue by jack1142** [Rapptz/discord.py#6172]
## Summary

When max concurrency is triggered, the command invocation still counts towards cooldown. While I'm not sure if it's not intentional, it's not documented and might be a bit confusing for someone who doesn't know how it works internally.

## Reproduction Steps

This should do as an example command:
```py
@commands.max_concurrency(1)
@commands.cooldown(1, 15)
@commands.command()
async def test(ctx):
    await asyncio.sleep(20)
```
So, to reproduce this, you need to:
1. Run `test` command.
2. Run `test` command after the cooldown wears off, but before the command from `1` stops running.
2.1. This should result in an error about the concurrency.
3. Try running `test` command either right after that or when the command from `1` stops running, but before cooldown wears off, it doesn't matter.
3.1. You should see that the command gets cooldowned even though it didn't run in `2`.

## Expected Results

When max concurrency is triggered, I expected the command invocation to not count towards cooldown.

## Actual Results

When max concurrency is triggered, the command invocation still counts towards cooldown.

## Intents

Shouldn't be needed in this, but I use `discord.Intents.all()` as my intents.

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

```
- Python v3.8.6-final
- discord.py v1.5.1-final
- aiohttp v3.6.2
- system info: Windows 10 10.0.19041
```

**Comment by Rapptz** [comment]
This seems like a fair bug. I guess I didn't anticipate the mixed usage since they are quite similar. 

If the decorator switched to queue mode (wait=True) then if this behaviour were changed the cooldown would never run. I guess that makes intuitive sense.
