### ISSUE TITLE
Performing actions before invoking a subcommand in a group?

### ISSUE THREAD

**Issue by SnowySailor** [Rapptz/discord.py#618]
So I've got a group of commands that I would like to have only people with the manage_server permissions execute. Is there a way that I can have

```python
if not ctx.message.author.manage_server:
    client.say("You don't have the correct permissions.")
    return
```

Block of code _before_ the subcommands are invoked? Or do I need to put this check inside each individual subcommand? I wasn't able to find anything in the docs or FAQ's about this.

**Comment by Kargoly** [comment]
Use a decorator function to check before the command is invoked

**Comment by SnowySailor** [comment]
So I should decorate the function definition for the command group is what you're saying?

**Comment by Kargoly** [comment]
Yeah, perform the check there instead of in the command itself.

**Comment by SnowySailor** [comment]
I'll give that a try. Currently in the middle of refactoring a ton of my code and I haven't had the chance to test it yet so I need to get that working first. Thanks.

**Comment by Rapptz** [comment]
Idiomatically, this is done via a concept called a check.

Something like this:

```py
def needs_manage_server():
  def predicate(ctx):
    if ctx.message.server is None:
      return False
    return ctx.message.author.server_permissions.manage_server
  return commands.check(predicate)
```

Afterwards you apply it to the command:

```py
@commands.command(pass_context=True)
@needs_manage_server()
async def foo(self, ctx, *, arg: str):
  await self.bot.say(arg)
```

To handle the error, you need to handle `commands.CheckFailure` in the local error handler.

```py
@foo.error
async def foo_error(self, error, ctx):
  if isinstance(error, commands.CheckFailure):
    await self.bot.say('Hey you need manage server to use this')
```

Good luck.
