### ISSUE TITLE
Using channel.history hangs the discord bot 

### ISSUE THREAD

**Issue by guysudai1** [Rapptz/discord.py#6181]
## Summary

When trying to use `channel.history`, the aiohttp library hangs on session request and will not retrieve the message history. Leaving the program frozen

## Reproduction Steps

```python
for channel in guild.text_channels:
  async for message in channel.history(limit=1):
     print(message)
```

## Expected Results

I expect to see the last 2 messages printed out in every channel

## Actual Results

Debugged the code and the code sent a request to:
`https://discord.com/api/v7/channels/<my_channel_id>/messages (GET)`
with kwargs:
```
{'params': {'limit': 2}, 
 'headers': {
    'User-Agent': 'DiscordBot (https://github.com/Rapptz/discord.py 1.5.1) Python/3.8 aiohttp/3.6.2', 
    'X-Ratelimit-Precision': 'millisecond', 
    'Authorization': 'Bot <my_auth_token>
  }
}
```

Nothing happens, and the bot hangs.

I traced it back:
```
- discord/abc.py:1055
 |
  - discord/iterators.py:326
   |
     - discord/http.py:470
       | 
        - discord/http.py:185 (hangs here)
```
## Intents

Uses all the intents 
(e.g. `discord.Intents.all()`)
## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

```
- Python v3.8.5-final
- discord.py v1.5.1-final
- aiohttp v3.6.2
- system info: Linux 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020
```

**Comment by Gobot1234** [comment]
Do you have logs for this, I would imagine you are rate limited?

**Comment by guysudai1** [comment]
I do not have the logs for this, but the amount of time I had to wait way beyond rate limiting. (>10 minutes, and it still hasn't finished)

**Comment by SebbyLaw** [comment]
Logs would still be helpful to diagnose this issue.

**Comment by guysudai1** [comment]
The issue no longer occurs so I cannot provide logs. Not sure what caused it :/
