### ISSUE TITLE
Is there a way to have a bot respond to an empty command?

### ISSUE THREAD

**Issue by tao-lu** [Rapptz/discord.py#619]
In the event that its prefix is satisfied, but is followed by either an empty command or an invalid one, I'd like to print something like a help message or just an acknowledgement of the invalid request.

**Comment by Rapptz** [comment]
Empty command I believe is not able to be caught. 

You can do something like this for that case:

```py
@bot.event
async def on_message(message):
  if message.content == '!': # just our prefix
    # handle it here
  await bot.process_commands(message)
```

For incorrect command you can use the `on_command_error` event and check for `commands.CommandNotFound`.

```py
@bot.event
async def on_command_error(error, ctx):
  if isinstance(error, commands.CommandNotFound):
    await bot.say('not a valid command friend')
```
