### ISSUE TITLE
Server boosters list is empty, even though I am boosting the server.

### ISSUE THREAD

**Issue by jvadair** [Rapptz/discord.py#6193]
## Summary

guild.premium_subscribers returns an empty list

## Reproduction Steps

@bot.event
async def on_message(message):
     print(message.guild.premium_subscribers)
## Expected Results

A list of member objects containing the users boosting the server (me)

## Actual Results

An empty list []

## Intents

Honestly not quite sure what these are because I'm not using any.

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python v3.9.0-final
- discord.py v1.5.1-final
- aiohttp v3.6.3
- system info: Linux 4.19.139-10018-gaf7e5d091ef8 #1 SMP PREEMPT Thu Nov 19 12:15:56 PST 2020

**Comment by Phxntxm** [comment]
If you don't have member intents on, this will be an empty list ~~iirc~~, so you not using any is probably the exact problem. You should read about the intents here:
https://discordpy.readthedocs.io/en/latest/intents.html
