### ISSUE TITLE
change in Member.pending does not cause on_member_update()

### ISSUE THREAD

**Issue by classabbyamp** [Rapptz/discord.py#6194]
## Summary

When I pass the rules screening, no `on_member_update()` event is fired for the change in `Member.pending`

## Reproduction Steps

Code:
```py
@bot.event
async def on_member_update(before: discord.Member, after: discord.Member):
    print("pending before:", before.pending)
    print("pending after:", after.pending)
```
1. Enable rules screening
2. User joins server
3. User accepts rules

## Expected Results

The event `on_member_update()` should fire ([source](https://discord.com/channels/336642139381301249/381965515721146390/791379451111800862))

## Actual Results

Nothing happens. There is no traceback.

## Intents

- guilds
- members
- messages
- dm_messages

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python v3.9.0-final
- discord.py v1.6.0-alpha
    - discord.py pkg_resources: v1.6.0a2705+geb11079
- aiohttp v3.7.3
- system info: Linux 5.9.12-arch1-1 #1 SMP PREEMPT Wed, 02 Dec 2020 16:14:56 +0000

**Comment by Rapptz** [comment]
I can't reproduce this. Make sure that the member is properly cached.

```py
@bot.event
async def on_member_join(member: discord.Member):
    print(f'{member} joined {member.guild}')

@bot.event
async def on_member_update(before: discord.Member, after: discord.Member):
    if before.pending != after.pending:
        print(f'before: {before.pending}, after: {after.pending}')
```

prints out

```
Danny#0007 joined Test Guild
before: True, after: False
```
