### ISSUE TITLE
[docs] The description of the `on_member_update` function is not clear

### ISSUE THREAD

**Issue by ishowta** [Rapptz/discord.py#6209]
## Summary

(Sorry if there is/are some mistakes, i'm not an English speaker)
In the description of the `on_member_update` function, it says _Called when a Member updates their profile._ But this is probably misleading, because `status` and `activity` property changes are done automatically by Discord, not by Member.

https://github.com/Rapptz/discord.py/blob/master/docs/api.rst#event-reference
```
.. function:: on_member_update(before, after)

    Called when a :class:`Member` updates their profile.

    This is called when one or more of the following things change:

    - status
    - activity
    - nickname
    - roles

    This requires :attr:`Intents.members` to be enabled.

    :param before: The updated member's old info.
    :type before: :class:`Member`
    :param after: The updated member's updated info.
    :type after: :class:`Member`
```

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [ ] I have provided the intents that my bot is using.

**Comment by SebbyLaw** [comment]
This is pedantic. The meaning is the same either way.

**Comment by scrazzz** [comment]
You can join the [discord.py server](https://discord.gg/dpy) to ask any doubts if you have as this isn't actually a bug.

**Comment by ishowta** [comment]
I'm sorry. I probably made a big mistake about English. I close the issue.

**Comment by Rapptz** [comment]
If this were to be changed to be less confusing I'd just remove all mentions of the "profile" and just say "Called when a member is updated".
