### ISSUE TITLE
[docs] Badly readable text in dark theme

### ISSUE THREAD

**Issue by sinus-x** [Rapptz/discord.py#6215]
## Summary

With the new design of the docs, there is a problem with highlighting. If you search for a term which is link, the result is non-pleasant combination of yellow and blue (see the screenshot).

![image](https://user-images.githubusercontent.com/14353790/103149936-d4607d00-476e-11eb-9707-74ed628a9c51.png)

I've tried to make the highlighted code white and it is much more readable:
![image](https://user-images.githubusercontent.com/14353790/103149911-9ebb9400-476e-11eb-83bf-99a06b07c3f2.png)

All I did was to add `color: #ffffff` to the CSS selector `span.highlighted`, but I'm not sure what else could have been affected by this.

**Comment by Rapptz** [comment]
I don't want to the link text white so I'll have to either pick a different colour for the highlight or change the link colour to be more friendly for it.

**Comment by Vyvy-vi** [comment]
How about we alter the css to alter the font-color, while the word is searched and highlighted.
Like:
![Screenshot 2020-12-26 at 10 01 48 PM](https://user-images.githubusercontent.com/62864373/103155445-1072fc80-47c6-11eb-96ff-fb2ccbd6a9ce.png)
