### ISSUE TITLE
client.fetch_guilds()  yields Guilds that don't have any `_roles` (including default role)

### ISSUE THREAD

**Issue by 07734willy** [Rapptz/discord.py#6216]
## Summary

Using client.fetch_guilds() returns Guild objects which do not have any roles, including the default role. I ran into an issue when it couldn't even find the default role (role.id == guild.id), instead returning `[]`, which was tripping up a `member.guild_permissions` expression.

>   File "/home/myname/Desktop/discord/prune_bot/src/prune.py", line 90, in prune_member
>     if member.guild_permissions.administrator:
>   File "/home/myname/Desktop/discord/venv/lib/python3.9/site-packages/discord/member.py", line 481, in guild_permissions
>     base.value |= r.permissions.value

The member's roles are `[None]`, the None coming from `result.append(g.default_role)` in Member.roles(...), line 370 in discord.py 1.5.1

## Reproduction Steps

Run the following, with a bot added to any server which has roles (technically all servers, since the default role counts).

```python
from discord import Client
import os

TOKEN = os.getenv('PRUNE_BOT_TOKEN')

class CustomClient(Client):
	async def on_ready(self):
		async for guild in self.fetch_guilds():
			print(guild.roles)

client = CustomClient()
client.run(TOKEN)
```

## Expected Results

I expect the `Guild` objects to have roles populated, with the actual server roles.

## Actual Results

The roles list is empty.

## Intents

None.

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python v3.9.0-final
- discord.py v1.5.1-final
- aiohttp v3.6.3
- system info: Linux 5.4.0-58-generic #64~18.04.1-Ubuntu SMP Wed Dec 9 17:11:11 UTC 2020

**Comment by XuaTheGrate** [comment]
https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.fetch_guilds
![img](https://cdn.discordapp.com/attachments/658050565275779110/792958792202584084/unknown.png)
