### ISSUE TITLE
Is there a way for a bot to send an embed?

### ISSUE THREAD

**Issue by tao-lu** [Rapptz/discord.py#622]
As far as I can tell, embeds are sent with client.send_message, but I'm unsure how to run the client event loop next to the bot event loop; I don't think that's how this problem is meant to be solved, anyway. Wondering if you knew of a better method.

**Comment by Vexs** [comment]
Bot inherits from client, anything you can do with client, you can do with commands.ext.bot. It's not a great idea to use both at the same time, unless you have a very specific reason.

**Comment by Rapptz** [comment]
They're subclasses.

Don't make both. Use one.
