### ISSUE TITLE
Webhook-sent messages are no longer directly publishable in 1.6.0a

### ISSUE THREAD

**Issue by bast0006** [Rapptz/discord.py#6220]
## Summary

Prior to changes involved in #6058 , webhooks would return the Message object sent by a webhook. While this didn't permit editing, it did permit deleting and it also permitted publishing a webhook-sent message. When they were translated over to the new WebhookMessage backend the publish() function was missed, and now throws an error. 

## Reproduction Steps

```py
wh = (await channel.webhooks())[0]
print(wh)
msg = await wh.send("test", wait=True)
await msg.publish()
```

## Expected Results

The message to be published, like before.

## Actual Results

A WebhookMessage does not set up its http state, and therefore the publish() command fails:

```
File "<string>", line 9, in func
     await msg.publish()
File "/usr/local/lib/python3.8/site-packages/discord/message.py", line 1061, in publish
    await self._state.http.publish_message(self.channel.id, self.id)
File "/usr/local/lib/python3.8/site-packages/discord/webhook.py", line 382, in __getattr__
    raise AttributeError('PartialWebhookState does not support http methods.')
AttributeError: PartialWebhookState does not support http methods.
```

## Intents

Members, Presences

## Checklist

- [ x ] I have searched the open issues for duplicates.
- [ x ] I have shown the entire traceback, if possible.
- [ x ] I have removed my token from display, if visible.
- [ x ] I have provided the intents that my bot is using.

## System Information

- Python v3.8.1-final
- discord.py v1.6.0-alpha
    - discord.py pkg_resources: v1.6.0a2618+g93f102c
- aiohttp v3.7.3
- system info: Linux 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020

**Comment by Rapptz** [comment]
I don't think this ever worked so this seems like a feature request to me, not a bug.

**Comment by bast0006** [comment]
We've had a feature using it for quite a bit (some months) and it broke recently. It's probably our fault for pinning such a bleeding edge version, but I figured since we'd relied on it and it now throws an exception it wasn't an intended behavioral change.

**Comment by Rapptz** [comment]
I was mostly surprised because `PartialWebhookState` has always existed and always made methods on Message fail if they came from a "partial" webhook object such as `Webhook.from_url` or `Webhook.partial`. However, looking at the traceback and the reproducible code it's using a full Webhook object and I guess getting coerced into a PartialWebhookState which does seem like a regression so I'll have to look into it.

**Comment by bast0006** [comment]
It comes to mind this may also affect pin() and unpin(), as they also use http and should be valid for a webhook message, although I haven't tested them. It's a weird issue, and probably falls under both labels honestly.

**Comment by Rapptz** [comment]
This should be fixed, if it isn't feel free to reopen the issue. I tested this using pin/unpin since the underlying mechanism is the same.
