### ISSUE TITLE
The member cache for guilds is not updated.

### ISSUE THREAD

**Issue by alkatar21** [Rapptz/discord.py#6222]
## Summary

`Guild.get_member()` does not find members that have been added to the guild since the last time the bot was started.
Possibly a problem since adding the intents?

## Reproduction Steps
1. Start bot.
2. Join the guild, the bot is in.
3. Use the command to geht the member:
```python
@command()
async def check_id(self, ctx: Context, id_: int):
    print(self.bot.guilds[0].get_member(id_))
```

## Expected Results
That the user is returned, because the intents that are necessary for this are all active to update the cache correctly.

## Actual Results
The result is `None` but should be the user. 

## Intents
```python
Intents(
    guilds=True,
    members=True,  # priv
    bans=False,
    emojis=True,
    integrations=False,
    webhooks=False,
    invites=True,
    voice_states=False,
    presences=False,
    messages=True,
    guild_reactions=True,
    typing=False, )
```
## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information
- Python v3.7.3-final
- discord.py v1.5.1-final
- aiohttp v3.6.2
- system info: Linux 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17)

**Comment by Rapptz** [comment]
This is something that is impossible to reproduce reliably with the code given.

Member cache depends on more than just intents, it depends on the following:

1. The member cache flags setting
2. The intents that you have enabled
3. Whether the guild is chunked or not

The 3rd point is important. By default the library attempts to chunk guilds if the member intent is enabled but sometimes the guild can get out of sync for some reason. This is why the library exposes the tools necessary to fill the member cache manually via Guild.query_members and Guild.chunk. Likewise, you can check whether a guild is chunked or not by using Guild.chunked.

This issue doesn't have enough information to debug anything so I'll close it. Hope the above helps.
