### ISSUE TITLE
Cooldown is broken

### ISSUE THREAD

**Issue by NightZan999** [Rapptz/discord.py#6223]
## Summary
So basically I want to display the amount of time a user has to wait so that they can use a command with the cooldown. 

## Reproduction Steps
See this just happened suddenly

## Expected Results
```
@new.error
    async def new_error(self, ctx, error):
        if isinstance(error, commands.CommandOnCooldown):
            em = discord.Embed(title = "<:fail:761292267360485378> New Error", color = ctx.author.color)
            em.add_field(name = "Reason:", value = "If your trying to spam the server then get off!")
            em.add_field(name = "Try again in:", value = "{:.2}s".format(error.retry_after))
            await ctx.send(embed = em)
```
Shouldn't this put a result like Try again in 5s or something like that. 
## Actual Results
![image](https://user-images.githubusercontent.com/57224016/103331580-a8a20780-4a8c-11eb-8db5-3c7b53651042.png)
This is what happened! Can you please tell me why and how I can resolve this? This started happening to all my other cooldowns

## Intents
I use all the intents (discord.Intents.all)

## Checklist

- [ x] I have searched the open issues for duplicates.
- [ x] I have shown the entire traceback, if possible.
- [ x] I have removed my token from display, if visible.
- [ x] I have provided the intents that my bot is using.

**Comment by Rapptz** [comment]
If you want fixed point representation for a floating point you need to use the `f` format specifier, e.g. `{:.2f}`.

This has nothing to do with the library.

**Comment by NightZan999** [comment]
Sorry im just dumb. So what exactly does this "3.2e mean?"

**Comment by Rapptz** [comment]
That's scientific notation.
