### ISSUE TITLE
function Suggestion

### ISSUE THREAD

**Issue by pruebando** [Rapptz/discord.py#6226]
## The Problem 

It will make easier see uptime(the time the bot was ready) of the bot without making dificult things and only with a function
## The Ideal Solution

bot.uptime(), shows the uptime in seconds

## The Current Solution

do dificult things with the time module and check how many time was the script running

## Summary

 make a bot.uptime function

**Comment by kaylynn234** [comment]
I believe issues about this have been opened before - for memory, they've been closed since this is a fairly trivial thing to implement yourself. I doubt that opinion has changed.

**Comment by Rapptz** [comment]
This is incredibly trivial to make yourself.
