### ISSUE TITLE
How can I send a PM to a user?

### ISSUE THREAD

**Issue by MrSpockGithub** [Rapptz/discord.py#623]
Well i have tried `        await client.send_message(client.get_user(id="225611118033371137"), embed=embed)` But it didn't work. What do i have to use?

**Comment by Rapptz** [comment]
In v0.16.x of the library, `Client.get_user` is not a thing.

So you have a few options when it comes to PMing a certain user:

First looping through `Client.get_all_members`:

```py
member = discord.utils.get(client.get_all_members(), id='1234')
```
Secondly, if you have DM'd them before, they'd be in `Client.private_channels` and you can use `utils.get` on that:

```py
user = discord.utils.get(client.private_channels, recipient__id='1234')
```

Lastly, you can make an HTTP request and just work on that:

```py
user = await client.get_user_info('1234')
```

After that you throw it in the `Client.send_message` call.

---

In the rewrite version of the library (i.e. v1.0), you can just do the following and it'll work:
```py
user = client.get_user(1234)
if user is not None:
  await user.send('hello')
```
