### ISSUE TITLE
on_raw_reaction_add wont work as commands.Cog.listener()

### ISSUE THREAD

**Issue by Miolus** [Rapptz/discord.py#6231]
## Summary

on_raw_reaction_add ends with error if it is in @commands.Cog.listener() and not bot.event

## Reproduction Steps

````
@commands.Cog.listener()
async def on_raw_reaction_add(event):
 print(event.emoji)
````

## Expected Results

Print emoji as in the same bot.event

## Actual Results

AttributeError: 'Events' object has no attribute 'emoji'

## Intents

reactions, default

## Checklist

- [x ] I have searched the open issues for duplicates.
- [ x] I have shown the entire traceback, if possible.
- [ x] I have removed my token from display, if visible.
- [ x] I have provided the intents that my bot is using.

## System Information

discord.py 1.5.1, python3.8.2

**Comment by lganWebb** [comment]
As with all python classes; unless your method is a staticmethod or a classmethod, its first argument will always be its class. You will need to update your arguments to `self, event`.

As this is not a bug, I recommend you join the Official sever (linked in the README) for python related help.
