### ISSUE TITLE
Request to change "yield from" to "await" in documentation

### ISSUE THREAD

**Issue by tBostic** [Rapptz/discord.py#625]
![image](https://user-images.githubusercontent.com/8574441/27837057-35c26814-60b0-11e7-9622-bc991711fda5.png)

As someone new to Python, it is confusing how await is used everywhere except for in the example of create_ffmpeg_player(). To me it seems the documentation is written primarily for python 3.5+ and as such the example should be:
voice = await client.join_voice_channel(channel)
player = voice.create_ffmpeg_player('cool.mp3')
player.start()

As I mentioned I am new to Python, so if there is a reason for this please let me know, but if not please consider the change.

**Comment by Rapptz** [comment]
Thanks. Was indeed an oversight.
