### ISSUE TITLE
Guild.Roles not fetching roles correctly when many changes are made at once, however does after a bot restart

### ISSUE THREAD

**Issue by RandomGgames** [Rapptz/discord.py#6262]
## Summary

When multiple roles are updated and changed at the same time and saved, when fetching the roles on a guild, the list shows multiple roles that have the same position tag as well as has them swap in the list than guild.roles returns. Restarting the bot however fixes this issue and it disappears, so I think it has to do with the bot not being able to process all the changes that have happened.

## Reproduction Steps

Create a bunch of roles, move them around, change their positions, and save all the changes at the end only, causing a lot of changes to be made and updated in one go. Use a loop to get all the positions/names of roles on the guild.

## Expected Results

Roles should not have the same position tag and should be in the reversed order of the visible list on the server's role management page.

## Actual Results

Some roles are in the correct order and others are not. Roles with the same position tag are swapped with respect to how they should be ordered and ones with unique position tags are in the correct order. 
See below from the .txt file from the command being run, once right after all the role updates and one after the bot is restarted. Nothing else changed.
```
1/3/2021 | 3:48:45:816494 pm - GETTING ROLES:
1/3/2021 | 3:48:45:816989 pm - Name: "Administrator", Position: "13", ID: "728059702969368636"

1/3/2021 | 3:48:45:818973 pm - Name: "TestBot", Position: "12", ID: "791121144711217153"

1/3/2021 | 3:48:45:819966 pm - Name: "temp 1", Position: "11", ID: "795389246902763591"

1/3/2021 | 3:48:45:820957 pm - Name: "---sarbot start", Position: "10", ID: "790842126841151520"

1/3/2021 | 3:48:45:822445 pm - Name: "test 1", Position: "9", ID: "790842195586449449"

1/3/2021 | 3:48:45:824429 pm - Name: "test", Position: "9", ID: "795393124587405354"

1/3/2021 | 3:48:45:825421 pm - Name: "test 2", Position: "7", ID: "790842222202454036"

1/3/2021 | 3:48:45:826909 pm - Name: "new role", Position: "7", ID: "795392939815469119"

1/3/2021 | 3:48:45:827901 pm - Name: "test 3", Position: "5", ID: "790842239307612184"

1/3/2021 | 3:48:45:828397 pm - Name: "temp 2", Position: "5", ID: "795389262659846144"

1/3/2021 | 3:48:45:829885 pm - Name: "tes", Position: "3", ID: "795393042777243668"

1/3/2021 | 3:48:45:830877 pm - Name: "---sarbot end", Position: "2", ID: "790842156768034866"

1/3/2021 | 3:48:45:831869 pm - Name: "temp 3", Position: "1", ID: "795389276836724787"

1/3/2021 | 3:48:45:832861 pm - Name: "@everyone", Position: "0", ID: "612360148857389122"

1/3/2021 | 3:48:45:833357 pm - Done.
1/3/2021 | 3:51:26:758444 pm - GETTING ROLES:
1/3/2021 | 3:51:26:758941 pm - Name: "Administrator", Position: "13", ID: "728059702969368636"

1/3/2021 | 3:51:26:759436 pm - Name: "TestBot", Position: "12", ID: "791121144711217153"

1/3/2021 | 3:51:26:759932 pm - Name: "temp 1", Position: "11", ID: "795389246902763591"

1/3/2021 | 3:51:26:760429 pm - Name: "---sarbot start", Position: "10", ID: "790842126841151520"

1/3/2021 | 3:51:26:760926 pm - Name: "test", Position: "9", ID: "795393124587405354"

1/3/2021 | 3:51:26:761421 pm - Name: "test 1", Position: "8", ID: "790842195586449449"

1/3/2021 | 3:51:26:761916 pm - Name: "new role", Position: "7", ID: "795392939815469119"

1/3/2021 | 3:51:26:761916 pm - Name: "test 2", Position: "6", ID: "790842222202454036"

1/3/2021 | 3:51:26:762414 pm - Name: "temp 2", Position: "5", ID: "795389262659846144"

1/3/2021 | 3:51:26:762910 pm - Name: "test 3", Position: "4", ID: "790842239307612184"

1/3/2021 | 3:51:26:763404 pm - Name: "tes", Position: "3", ID: "795393042777243668"

1/3/2021 | 3:51:26:763404 pm - Name: "---sarbot end", Position: "2", ID: "790842156768034866"

1/3/2021 | 3:51:26:763902 pm - Name: "temp 3", Position: "1", ID: "795389276836724787"

1/3/2021 | 3:51:26:764396 pm - Name: "@everyone", Position: "0", ID: "612360148857389122"

1/3/2021 | 3:51:26:764396 pm - Done.
```

## Intents

Gather a list of roles to allow users to say a number in chat to toggle which roles they want. Since the order for the embed is based on the hierarchy order, so when a bot restart changes the order, things break. This is the code that was fetching the roles while testing:

```python
#Command to get roles on the server
	if message.content.lower() == "!sarbot getroles":
		roles = message.guild.roles
		roles.reverse()
		log("GETTING ROLES:")
		for role in roles:
			log("Name: \"" + str(role.name) + "\", Position: \"" + str(role.position)  + "\", ID: \"" + str(role.id) + "\"\n")
		log("Done.")
```
This is just a snippet of code, not the entire bot's code. log just prints to the console and to a .txt file. Treat it as print().

## Checklist

- [x] I have searched the open issues for duplicates.
- [ ] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python v3.9.0-final
- discord.py v1.5.1-final, v1.6.0
- aiohttp v3.6.2
- system info: Windows 10 10.0.19041

**Comment by Rapptz** [comment]
Role positions are not unique. They are disambiguated by ID when sorting which is why the number is merely a hint. If you want to compare roles then `<` and `>` should be used instead.
