### ISSUE TITLE
Move docs search bar to sidebar (as per previous layouts)

### ISSUE THREAD

**Issue by EdwardChamberlain** [Rapptz/discord.py#6263]
## The Problem

Regarding the docs page: https://discordpy.readthedocs.io/en/latest/

Previous docs versions (<1.5.1) included a search bar on the sidebar. The latest version (1.6.0) uses a new (darker) theme with the search bar at the top of the page. This means you have to scroll to the top of the page every time you want to do a new search which is far less efficient than the previous sidebar search especially considering the length of some pages.

## The Ideal Solution

Move the search bar (or place another search bar) on the sidebar for quick access.

## Summary

Add search bar to the sidebar as in previous docs versions.

**Comment by Rapptz** [comment]
No plans to do this. The previous position caused issues since the RTD footer would block it making it inaccessible to those without adblock.
