### ISSUE TITLE
Missing guild features.

### ISSUE THREAD

**Issue by Geige2** [Rapptz/discord.py#6264]
## The Problem
"preferred_locale" and "templates" are missing from the guild object/the template object.

## The Ideal Solution
A property or method for guilds to access their preferred locale and created templates.

## The Current Solution
As far as I can tell there is none, and to implement this it requires manually using aiohttp.

## Summary
guild.templates / await guild.templates()
guild.preferred_locale

possibly:
await template.get_from(guild)

**Comment by Rapptz** [comment]
https://discordpy.readthedocs.io/en/latest/api.html#discord.Guild.preferred_locale
https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.fetch_template

**Comment by Geige2** [comment]
Sorry, I meant a way to set the preferred locale (completely messed up that explanation) and a way to get the template codes for a guild (maybe there's a way to do that, but I can't figure it out).
