### ISSUE TITLE
Guild feature

### ISSUE THREAD

**Issue by Geige2** [Rapptz/discord.py#6268]
The Problem

"set_preferred_locale" is missing from the guild object.
The Ideal Solution

A method for guilds set their preferred_locale (note this is different from voice_region)
The Current Solution

As far as I can tell there is none.
Summary

await guild.set_preferred_locale()

**Comment by Rapptz** [comment]
This was already implemented.

**Comment by Geige2** [comment]
Really, where? I've checked the docs a hundred times at least, and I can't find it.

**Comment by SebbyLaw** [comment]
It was just implemented in 3a75816 for [`Guild.edit`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Guild.edit)

Apologies for the reply in your previous issue.

**Comment by Geige2** [comment]
Ty!
