### ISSUE TITLE
Get user CustomActivity

### ISSUE THREAD

**Issue by Hattorius** [Rapptz/discord.py#6269]
## The Problem
Not being able to get the CustomActivity set by an user.

## The Ideal Solution
Getting the CustomActivity set by an use.

## The Current Solution
None.

## Summary
As the change logs for [v1.3.0](https://discordpy.readthedocs.io/en/latest/whats_new.html#v1-3-0) show: 
![v1.3.0 image](https://i.imgur.com/uZFI8mA.png)
Bots can not send custom statusses, but is it possible to get the custom status by an user?

Thanks,

**Comment by Rapptz** [comment]
This is available under [`Member.activity`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Member.activity) and [`Member.activities`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Member.activities).

You need [privileged intents to use it](https://discordpy.readthedocs.io/en/latest/intents.html#privileged-intents)
