### ISSUE TITLE
avatar_url is returning old avatar

### ISSUE THREAD

**Issue by MangaD** [Rapptz/discord.py#6273]
## Summary

I have a bot command for fetching a user's avatar, but it is returning an old avatar. I have to restart the bot for it to fetch the new avatar.

## Reproduction Steps

Here is the code corresponding to the command:

```py
@commands.command(description="Get the avatar image of a user. Usage: .avatar @user")
        async def avatar(self, ctx, *,  avamember : discord.Member=None):
                """Get the avatar image of a user. Usage: .avatar @user"""
                userAvatarUrl = avamember.avatar_url
                await ctx.send(userAvatarUrl)
```

## Expected Results

Return the latest avatar.

## Actual Results

Returned the old avatar.

## Intents

Not using this feature I think.

## Checklist

- [x] I have searched the open issues for duplicates.
- [ ] I have shown the entire traceback, if possible.
- [ ] I have removed my token from display, if visible.
- [ ] I have provided the intents that my bot is using.

## System Information

- Python v3.7.3-final
- discord.py v1.5.1-final
- aiohttp v3.6.2
- system info: Linux 5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020

**Comment by helish88** [comment]
You must enable Intents

**Comment by Rapptz** [comment]
In v1.5.1 you need the members intent for this due to global user cache. This is fixed in master/1.6 though.

**Comment by MangaD** [comment]
> In v1.5.1 you need the members intent for this due to global user cache. This is fixed in master/1.6 though.

Thank you very much for the information. I have the following code now:

```py
intents = discord.Intents(messages=True, members=True)
member_cache_flags = discord.MemberCacheFlags.none()
Client = discord.Client(intents=intents, member_cache_flags=member_cache_flags)
```
I tried with and without `MemberCacheFlags`. However, it appears that when I change my avatar, the bot still returns the old one. What am I doing wrong?

**Comment by Rapptz** [comment]
By disabling the member cache you no longer get user updates.

**Comment by MangaD** [comment]
> By disabling the member cache you no longer get user updates.

Thank you again. I am new to `Intents`. Even with the following code, the `avatar_url` does not update:
```py
intents = discord.Intents(messages=True, members=True, presences=True, voice_states=True)
member_cache_flags = discord.MemberCacheFlags.all()
Client = discord.Client(intents=intents, member_cache_flags=member_cache_flags)
```

**Comment by Rapptz** [comment]
That seems unlikely. 

You're missing the guilds intent though so you're not actually caching any members.

**Comment by MangaD** [comment]
> That seems unlikely.
> 
> You're missing the guilds intent though so you're not actually caching any members.

I have this code now, but the problem persists.
```py
intents = discord.Intents(messages=True, guilds=True, members=True, presences=True, voice_states=True)
member_cache_flags = discord.MemberCacheFlags.all()
Client = discord.Client(intents=intents, member_cache_flags=member_cache_flags)
```

**Comment by Rapptz** [comment]
At this point that's no longer possible.

Members who update their avatar will dispatch an event updating their internal user object and things will work just as they did prior to intents existing. I suppose if a member is somehow not cached this could be missed? Though that feels unlikely since there would be log lines saying so currently.

**Comment by MangaD** [comment]
> At this point that's no longer possible.
> 
> Members who update their avatar will dispatch an event updating their internal user object and things will work just as they did prior to intents existing. I suppose if a member is somehow not cached this could be missed? Though that feels unlikely since there would be log lines saying so currently.

Unfortunately it is what is happening. How can I see the log?

**Comment by Rapptz** [comment]
https://discordpy.readthedocs.io/en/latest/logging.html#logging-setup

**Comment by LivestC** [comment]
hi

**Comment by MangaD** [comment]
> https://discordpy.readthedocs.io/en/latest/logging.html#logging-setup

Thank you for your time and help, @Rapptz. I have enabled logging and now see the events being logged. However, when I change my avatar, no event is shown in the log.

This is my code:
```py
import logging
logger = logging.getLogger('discord')
logger.setLevel(logging.DEBUG)
handler = logging.FileHandler(filename='discord.log', encoding='utf-8', mode='w')
handler.setFormatter(logging.Formatter('%(asctime)s:%(levelname)s:%(name)s: %(message)s'))
logger.addHandler(handler)

intents = discord.Intents(messages=True, guilds=True, members=True, presences=True, voice_states=True)
member_cache_flags = discord.MemberCacheFlags.all()
Client = discord.Client(intents=intents, member_cache_flags=member_cache_flags)
```

I have also noticed that, if I do the following:
1. Start bot
2. Change avatar (no event is logged)
3. Run avatar command
Then, the new avatar is shown.

However, if I do:
1. Start bot
2. Run avatar command (current avatar is shown)
3. Change avatar (no event is logged)
4. Run avatar command
Then, the **old avatar** is shown.
