### ISSUE TITLE
Regression or other impact to wait_for reaction in 1.6.0

### ISSUE THREAD

**Issue by DefiDebauchery** [Rapptz/discord.py#6280]
## Summary

In version 1.6.0, the `wait_for` routine does not appear to return in the same manner as 1.5.1. 
While the check may or may not fire with the bot's `add_reaction` (just prior to the check), it never seems to handle subsequent user interaction.

## Reproduction Steps

```py
import asyncio
import discord
from discord.ext import commands

class TestCog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        self.prompt = ['✅', '❌']

    @commands.command()
    @commands.dm_only()
    async def test(self, ctx, *, test_input):
        embed = discord.Embed(title='Your input', description='Please confirm the value below.')
        embed.add_field(name='Input', value=test_input)

        prompt = await ctx.channel.send(embed=embed)
        for emoji in self.prompt:
            await prompt.add_reaction(emoji=emoji)

        def check(reaction, user):
            print('Checking user interaction for', user, emoji)
            return user == ctx.author and str(reaction.emoji) in self.prompt

        try:
            print('pre-reaction')
            reaction, user = await self.bot.wait_for('reaction_add', timeout=5.0, check=check)
            print('post-reaction')

            await ctx.channel.send('Post-reaction!')
        except asyncio.TimeoutError:
            await ctx.channel.send("We did not receive a response")

def setup(bot):
    bot.add_cog(TestCog(bot))
```

## Expected Results

As with 1.5.1, we would expect the following output:

```
❯ python3 main.py
pre-reaction
Checking user interaction for theBot#9876 ❌
Checking user interaction for MyUser#1234 ✅
post-reaction
```

<img width="273" alt="Screen Shot 2021-01-08 at 4 37 59 PM" src="https://user-images.githubusercontent.com/75273961/104066748-ec54e980-51cf-11eb-96cc-e309c2b1544b.png">

## Actual Results

When changed to 1.6.0, this is no longer handled in the same way

```
❯ pip3 install discord.py==1.6.0
❯ python3 main.py
pre-reaction
Checking user interaction for theBot#9876 ❌
```

And after 5 seconds, the bot states that it did not receive any input

<img width="257" alt="Screen Shot 2021-01-08 at 4 40 44 PM" src="https://user-images.githubusercontent.com/75273961/104066983-51104400-51d0-11eb-8b4c-1d2839daa672.png">

## Intents

No intents specifically defined, but do not believe changes would affect the outcome

## Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have provided the intents that my bot is using.

## System Information

- Python v3.8.7-final
- discord.py v1.6.0-final
- aiohttp v3.6.3
- system info: Darwin 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64

**Comment by Phxntxm** [comment]
```
Discord version 1.6.0
pre-reaction
Checking user interaction for Bonfire Dev#5358 ❌
Checking user interaction for Phantom#0004 ✅
```
No repro. Only changes I made is `print("Discord version", discord.__version__)` immediately after the command, and changing `print("Checking user interaction for", user, emoji)` to `print("Checking user interaction for", user, reaction.emoji)` because that's a bug in your code. You're printing the last emoji that's added to the message by the bot, and not the one that's being checked for in your current code.

**Comment by SebbyLaw** [comment]
I cannot reproduce this. No code changes.

> No intents specifically defined, but do not believe changes would affect the outcome

A lack of the `reactions` intent would cause this issue. You can find documentation on how to implement this [here](https://discordpy.readthedocs.io/en/latest/intents.html).

This issue is most likely caused by lack of intents, and is invalid.

**Comment by mikeshardmind** [comment]
A lack of member intents will cause this specifically in DMs. You can use the raw event and the author id as part of the check if you need this to function in DMs. 

There was an intentional decision not to have a stale user cache without the member updates made here https://github.com/Rapptz/discord.py/commit/7a3a571e0a641aaeb061e86d8a6e851c5cd4c381 to fix larger issues caused by a stale cache that would never get properly updated (see: #6034)

**Comment by DefiDebauchery** [comment]
I see. I did not expect to need a member intent in order for the bot to handle DMs that I (as a user) initiated.
Thank you for the explanation.
