### ISSUE TITLE
Reactions count bug

### ISSUE THREAD

**Issue by Infernus101** [Rapptz/discord.py#6281]
## Summary

Reactions count doesn't go up when I refetch the message after asyncio.sleep(). New reactions get registered in msg.reactions but count isn't working.
## Reproduction Steps

`msg = await ctx.send(embed=e)`
`await asyncio.sleep(10)`
`nmsg = await ctx.channel.fetch_message(msg.id)`
`reactions = nmsg.reactions`
`print(str(reactions))`

## Expected Results
Reactions count to go up when people react

## Actual Results
Reaction count stays stale

## Intents
intents.all()

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python v3.8.3-final
- discord.py v1.6.0-final
- aiohttp v3.6.3
- system info: Linux 5.4.0-51-generic #56-Ubuntu SMP Mon Oct 5 14:28:49 UTC 2020

**Comment by Squidtoon99** [comment]
Can reproduce I am not able to fetch more than 1 user using `await channel.fetch_message().reactions[0].users().flatten()` on a message with 100+ reactions.


When debugging, the data returned by the API [here](https://github.com/Rapptz/discord.py/blob/c09cf779a30eac9174a23827acf534e1cc18ce50/discord/message.py#L492) has `"count" : 1` while that reaction had much more than 1 user

running `await channel.fetch_message().reactions[0].users(limit=100000).flatten()` gives the full user list

**Comment by Rapptz** [comment]
This stuff is pass-through, I do not modify the API response much I just wrap it up nicely. Therefore his looks like an API bug.

Doing a raw API call without the library seems to return objects with a count set explicitly to 1, e.g.

```json
  "reactions": [
    {
      "emoji": {
        "id": "596577438461591562",
        "name": "upvote"
      },
      "count": 1,
      "me": false
    },
    {
      "emoji": {
        "id": "596577438952062977",
        "name": "downvote"
      },
      "count": 1,
      "me": false
    }
  ]
```

Not much I can do about this here.

**Comment by Rapptz** [comment]
I've reported this to Discord and they said it has been fixed and I can confirm it has.
