### ISSUE TITLE
Editing message returned from reply() ignores global AllowedMentions

### ISSUE THREAD

**Issue by Tawmy** [Rapptz/discord.py#6283]
## Summary

When editing a message returned from message.reply(), the globally set AllowedMentions are partially or fully ignored.

## Reproduction Steps

Send a reply using await ctx.message.reply(embed=embed)
Edit returned message using await message.edit(embed=embed)

## Expected Results

AllowedMentions is respected and user not mentioned.

## Actual Results

Globally set replied_user=False is ignored and user is mentioned.

https://user-images.githubusercontent.com/22292560/104108028-8ba5d980-52c1-11eb-8e07-a297d96238af.mov

## Intents

discord.Intents.all()

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python v3.9.1-final
- discord.py v1.6.0-final
- aiohttp v3.7.3
- system info: Linux 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020

**Comment by Rapptz** [comment]
Edits never mention. It's just a visual artifact. There were attempts to fix this earlier but I reverted it since it was complicating the edit code for no benefit.

**Comment by Tawmy** [comment]
Creating a new AllowedMentions instance on every message edit fixes this. Creating a helper method for this can be used to circumvent the issue, though it's anything but ideal.

**Comment by Rapptz** [comment]
This is ultimately an upstream issue (see https://github.com/discord/discord-api-docs/issues/1864 and https://github.com/discord/discord-api-docs/issues/2474). So the fix should be on Discord's part more than anything.
