### ISSUE TITLE
Add more endpoints ♥

### ISSUE THREAD

**Issue by Bluscream** [Rapptz/discord.py#629]

**Comment by NotSoSuper** [comment]
use rewrite

**Comment by Bluscream** [comment]
Is it already public?

**Comment by ardeaf** [comment]
Yes, it's the rewrite branch of this repo. You can install it by specifying the branch with pip.

_Sent from my Samsung SM-G935V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Bluscream** [comment]
Ohh dangit, thank you!
