### ISSUE TITLE
message.channel.send method does not exist in discord.py 1.6.0?

### ISSUE THREAD

**Issue by JellevanHaaften** [Rapptz/discord.py#6291]
Hi guys,

I've been wanting to learn some python and wanted to start with a bot. I've been following the own discordpy [documentation](https://discordpy.readthedocs.io/en/latest/quickstart.html) to create a bot that sends a message whenever the on_message event gets triggered. This seems like the simplest of tasks but every time i send a message in a channel i get: "AttributeError: 'Object' object has no attribute 'send'". 

It seems like the channel object does not have a send() method. In all of the documentation (official and non official) the client.event is used but for me it doesnt work. It works when i use the bot.event but i'd like to know if i'm doing something wrong :)

**Comment by scrazzz** [comment]
https://discordpy.readthedocs.io/en/latest/api.html?highlight=channel.send#discord.TextChannel.send

> the client.event is used but for me it doesnt work. It works when i use the bot.event

You need to use what you defined your bot constructor as. According to what you said, it seems like you defined it as `bot` not `client`. Also what's the code you currently have?

```
# here's an example.
# This sends a message in the channel if a member says "hello"

@bot.event
async def on_message(message):
    if message.author == bot.user:
        return
    
    if message.content.startswith("hello"):
        await message.channel.send("Hi there!")
```

You may refer this: https://discordpy.readthedocs.io/en/latest/quickstart.html

For future help, join the support server: https://discord.gg/dpy.

**Comment by JellevanHaaften** [comment]
In short this is my code whenever using the `client`. I load the token from an environment file, pass my intents and define the on_message event. Then i run the client. The event fires but the send method does not.

```
import os
import discord as dc
from discord.ext import commands
from dotenv import load_dotenv

dir = os.path.abspath(os.path.dirname(__file__))
load_dotenv(os.path.join(dir, 'var.env'))
TOKEN = os.getenv('DISCORD_TOKEN')

intents = dc.Intents(typing=True, messages=True)
client = dc.Client(intents=intents)

@client.event
async def on_message(message):
    if message.author != client.user:
        await message.channel.send('something')
```

**Comment by scrazzz** [comment]
Looks like you're missing `guilds` intents.

**Comment by JellevanHaaften** [comment]
Ah you are right. It works now! Did not see this documented anywhere but may have looked over it. 

Is there another intent or something missing to use the on_typing event? The event is in my code but does not get triggered whenever someone is typing in a channel.

```
@client.event
async def on_typing(channel, user, when):
    print(f'... {user.nick}!')
```

**Comment by scrazzz** [comment]
This issue seems to diverge to another question. Close this issue and ask in the discord.py help channel. You'll get a more better and a quicker response.
