### ISSUE TITLE
change_presence is a blocking

### ISSUE THREAD

**Issue by sevenc-nanashi** [Rapptz/discord.py#6294]
## Summary

When run change_presence, bot will stop a little

## Reproduction Steps

1. setup DEBUG logging
2. run change_presence

## Expected Results

changes presence without blocking.

## Actual Results

Bot stops a little.
https://user-images.githubusercontent.com/59691627/104245657-00d30380-54a8-11eb-94ec-6dff7fb700ff.mov

## Intents

discord.Intents.all()

## Checklist

- [x] I have searched the open issues for duplicates.
- [ ] I have shown the entire traceback, if possible.
- [ ] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

```powershell
PS > python -m discord -v

- Python v3.8.3-final
- discord.py v1.6.0-alpha
    - discord.py pkg_resources: v1.6.0a2603+gb00aaab
- aiohttp v3.7.3
- system info: Windows 10 10.0.17134
```

**Comment by SebbyLaw** [comment]
I can't reproduce this. Make sure your exec command itself isn't blocking.

**Comment by Rapptz** [comment]
WebSocket operations are asynchronous using aiohttp. It is unlikely to be blocking.
