### ISSUE TITLE
Channel Permission Overrides Out of Order

### ISSUE THREAD

**Issue by AXAz0r** [Rapptz/discord.py#630]
As reported and discussed in #python_discord-py on Discord API July 7th 2017 at 09:10 UTC.
Explicitly stating a permission is `True`, even when bellow one that overrides it as `False` will return `True` in the wrapper.

```py
[('@everyone', {
  'send_messages': True,
# Permissions with None redacted...
}), ('Dev BOT', {
  'send_messages': False,
# Permissions with None redacted...
})]
```

Permissions set to this will return `True` in the wrapper while being denied by Discord.
Reverting the permission of `@everyone` to `Default` instead of an explicit `True` returns the permission for the channel properly as `False`.

**Comment by Rapptz** [comment]
Fixed.
