### ISSUE TITLE
DM history can't get

### ISSUE THREAD

**Issue by CyberRex0** [Rapptz/discord.py#6302]
## Summary

I tried to get DM history between bot and me.
However, for some reason, the file sending operation is performed.

## Reproduction Steps

```py
h = await message.author.history(limit=1).flatten()
```

## Expected Results

It given errors with 413 Request entity  too large
(But I didn't send)

## Actual Results

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jishaku/cog_base.py", line 520, in jsk_python
    send(await ctx.send(file=result))
  File "/usr/local/lib/python3.8/dist-packages/discord/abc.py", line 915, in send
    data = await state.http.send_files(channel.id, files=[file], allowed_mentions=allowed_mentions,
  File "/usr/local/lib/python3.8/dist-packages/discord/http.py", line 247, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 413 Payload Too Large (error code: 40005): Request entity too large 
```

It looks like Jishaku is the cause, but it doesn't.

## Intents

Enabling All

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python v3.8.5-final
- discord.py v1.6.0-final
- aiohttp v3.6.3
- system info: Linux 5.4.0-60-generic #67-Ubuntu SMP Tue Jan 5 18:31:36 UTC 2021

**Comment by Rapptz** [comment]
This is jishaku behaviour and has nothing to do with the library. It's trying to send some data that's over 8MB long, whatever it is.

**Comment by CyberRex0** [comment]
it was caused by Jishaku. sorry
