### ISSUE TITLE
@invalid-user on mobile when using AllowedMentions.none()

### ISSUE THREAD

**Issue by Klemek** [Rapptz/discord.py#6310]
## Summary

Member mention is shown as `@invalid-user` on latest mobile app when `allowed_mentions` is set to `discord.AllowedMentions.none()`. 

(I need this features to show non-mentioning rankings, this has been reported to me by friends/users of my bot)

## Reproduction Steps

```python
import discord

client = discord.Client()


@client.event
async def on_message(message):
    if message.author == client.user:
        return

    await message.channel.send(
        f"Hello {message.author.mention} !",
        allowed_mentions=discord.AllowedMentions.none(),
    )

client.run("your token here")
```

## Expected Results

What we sees on desktop Discord :

![image](https://user-images.githubusercontent.com/12103162/104634858-76ee8a80-56a1-11eb-8569-ab9b83044691.png)

## Actual Results

This display on mobile :

![image](https://user-images.githubusercontent.com/12103162/104634988-a00f1b00-56a1-11eb-9541-4123528eee36.png)

## Intents

discord.Intents.all()

## Checklist

- [x] I have searched the open issues for duplicates.
- [ ] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

debug:
```
- Python v3.8.5-final
- discord.py v1.6.0-final
- aiohttp v3.6.3
- system info: Linux 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020
```

target server:
```
- Python v3.7.5-candidate
- discord.py v1.6.0-final
- aiohttp v3.6.3
- system info: Linux 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16)
```

**Comment by Taarek** [comment]
It's a Discord client bug, Sorry. :[

In the future you can report Discord bugs at https://discord.gg/discord-testers or https://support.discord.com/hc/en-us/requests/new?ticket_form_id=360006586013

**Comment by Klemek** [comment]
Thanks for your quick reply. As you recommanded, I opened a ticket containing the same info as this issue.

**Comment by Klemek** [comment]
I've been redirect to this already existing issue : https://bugs.discord.com/T1196
If you happen to have a bug reporter account and can verify this bug, please consider reporting it.o
