### ISSUE TITLE
"In certain cases, this can be None.” not clear on what cases!

### ISSUE THREAD

**Issue by EdwardChamberlain** [Rapptz/discord.py#6321]
## The Problem

The docs for member.joined_at states " In certain cases, this can be None.” but does not elaborate what cases.

## The Ideal Solution

Mention the situations that cause this to return `None` as is shown for functions like `get_guild` etc.

**Comment by Rapptz** [comment]
They are implementation specific depending on how the data is received in the Discord API which is subject to change. The cases don't actually matter since you should be checking for it anyway.
