### ISSUE TITLE
Intents documentation missing Guild.owner

### ISSUE THREAD

**Issue by TheBicPen** [Rapptz/discord.py#6326]
## Summary

The documentation on this page is missing the fact that Guild.Owner needs the Member Intent.
https://discordpy.readthedocs.io/en/latest/intents.html#intents-primer

According to this answer, Guild.Owner returning None is caused by the missing intent.
https://stackoverflow.com/questions/64685301/discord-py-why-is-my-serverinfo-command-showing-the-owner-as-none

Confirmed on discord.py v1.6.0-final.

**Comment by Rapptz** [comment]
This is implied in the member cache section where it details what member data you can get without the member intents. If I were to list every single thing missing that page would be never ending.
