### ISSUE TITLE
Message.edit() ignores default allowed_mentions with reply messages.

### ISSUE THREAD

**Issue by seojin200403** [Rapptz/discord.py#6331]
## Summary
I've set allowed_mention of my bot to **discord.AllowedMentions(everyone=False, roles=False, replied_user=False)**.
When I reply to a message and edit it, the edited message mentions everything. while original message didn't.

## Reproduction Steps
```
bot = commands.Bot(allowed_mentions=discord.AllowedMentions.none(),
                                   intents=discord.Intents.default())

...
message = await ctx.reply("@everyone Original message")
await message.edit(content="@everyone Edited message")  # The allowed_mention is ignored and it pings anyone.
```

## Expected Results
Both original and edited messages don't ping anyone.

## Actual Results
Edited message does ping. even when I explicitly set mention_author=False.
![image](https://user-images.githubusercontent.com/51256209/105033621-b18a6580-5a9b-11eb-949f-848c028176c2.png)
![image](https://user-images.githubusercontent.com/51256209/105033504-928bd380-5a9b-11eb-8f0c-1f1c89aa69ef.png)
![image](https://user-images.githubusercontent.com/51256209/105032326-fa411f00-5a99-11eb-8a25-537047e8c8b4.png)

It does not happen when I explictly pass the bot's allowed_mentions.
![image](https://user-images.githubusercontent.com/51256209/105032670-6d4a9580-5a9a-11eb-8e00-de914066dfee.png)

It does not happen if message is not a react message.
![image](https://user-images.githubusercontent.com/51256209/105033694-ca931680-5a9b-11eb-8ba8-58080dd9609c.png)

## Intents
discord.Intents.default()

## Checklist
- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information
Windows 10 x64
Python 3.8.6 64bit
discord.py 1.6.0

**Comment by Rapptz** [comment]
Discord issue. https://github.com/discord/discord-api-docs/issues/2474 and https://github.com/discord/discord-api-docs/issues/1864 are relevant. There was a workaround at the library level but it was removed due to being unmaintainable.
