### ISSUE TITLE
All Events Not working

### ISSUE THREAD

**Issue by ChillVibes-CA** [Rapptz/discord.py#6335]
I get absolutely no errors or tracebacks what-so-ever and my code has worked for over a week now but ever since I was playing around with making webhooks I'm pretty sure i may have accidentally did API abuse when I was trouble shooting. If this is the case and i cant do nothing about it tell me to start over. If it is the the other way around and this is not the cause, then something is seriously wrong, and it sure isn't on my side.

**Comment by SebbyLaw** [comment]
In its current state, this issue is inactionable. Please don't delete the issue template - it exists for a reason.
