### ISSUE TITLE
Better Docs Search

### ISSUE THREAD

**Issue by ZusorCode** [Rapptz/discord.py#6336]
## The Problem

While the current docs site is a huge improvement to the previous version, search still isn't great. There's no auto-suggestions, no keyboard shortcut, and it takes a while to load once the query is submitted. Results are ok but the way they're displayed could be better.

## The Ideal Solution

Improved search that implements these features. [Algolia](https://docsearch.algolia.com/) (free for open source) would be one option, it's used by a lot of js docs and works well there, it seems like there's [ways to use it for python as well](https://github.com/readthedocs/sphinx_rtd_theme/issues/761)
## Summary

Improve suggestions, keyboard shortcuts and results for docs search through a service like [Algolia](https://docsearch.algolia.com/) or others.

**Comment by Rapptz** [comment]
There are no plans to do this. Note that documentation is meant to be static without relying on external services to do any sort of indexing which limits us to mainly Sphinx provided search and a pure-js search engine. All the things suggested seem to be secondary goals to that. Unless a solution happens in the future that allows offline builds to continue working then it's not gonna happen.
