### ISSUE TITLE
Transmit function: Discord.py new generation.

### ISSUE THREAD

**Issue by LivestC** [Rapptz/discord.py#6338]
## The Problem

a function that can be transmitted, you choose if you want to transmit a video from a directory or otherwise transmit your desktop (depending on other modules) this function is especially necessary for accounts other than bot.

## The Ideal Solution

The idea of this function is: that a video of the directory can be transmitted in a voice channel, this function can also be related to other modules to transmit the screen of the device that is found.  This since users can broadcast live on a voice channel.

## The Current Solution

idk, it's just a new generation idea. to topple discord.js from the top.

## Summary

that non-bot users can transmit on a voice channel. If you can add for bot and/or user

**Comment by bluenix2** [comment]
Highly doubt this sorry, there are even talks of booting self-bot methods from the library in 2.0 entirely. Highly doubt anything would be merged regarding this.

**Comment by fwrs** [comment]
refer to: https://github.com/discord/discord-api-docs/issues/1386

**Comment by LivestC** [comment]
> refer to: https://github.com/discord/discord-api-docs/issues/1386

I don't mean that bots transmit.  But the users.

**Comment by LivestC** [comment]
maybe they have already noticed. I am trying to make a discord client, with discord.py.  My problem is that that function is missing.

**Comment by Rapptz** [comment]
There are no plans to support video at all

**Comment by LivestC** [comment]
> There are no plans to support video at all 

Even if you don't want to, is it possible to add that function to a library? I'm not trying to say add it, only if you could.

**Comment by Rapptz** [comment]
No. I don't think you realize how complicated audio streaming is.
