### ISSUE TITLE
Running looped lines alongside client

### ISSUE THREAD

**Issue by seanwlk** [Rapptz/discord.py#634]
Is there a way to run some lines when the client restarts? I'm currently running a feedparser that runs every time a message is received. But the real intent was to have that RSS feed notification as soon as it's available without depending on someone writing in one of the text channels.

**Comment by Vexs** [comment]
https://github.com/Rapptz/discord.py/blob/master/examples/background_task.py 

Here is an example of how to create a background task that runs every minute

**Comment by seanwlk** [comment]
Cool, thanks, this will solve another part of the script too.
