### ISSUE TITLE
Unable to receive messages from huge guilds

### ISSUE THREAD

**Issue by svaningelgem** [Rapptz/discord.py#6340]
## Summary

I am unable to receive messages from huge guilds.

## Reproduction Steps

Join the following 2 guilds:
https://discord.com/invite/guildwars2 [20k members]
https://discord.com/invite/betteramongus [500k members]

Run the following snippet with a user token & wait a few minutes for messages to get posted in both guilds:
```python
import discord

class DiscordClient(discord.Client):
    async def on_ready(self, *args, **kwargs):
        print(f"Connected as {self.user.display_name} to:")

        for guild in self.guilds:
            print(f"- {guild.name} (large? {guild.large})")

    async def on_message(self, message):
        print(f"Message from '{message.guild.name}'")

DiscordClient().run(TOKEN, bot=False)
```

## Expected Results

I expect to receive messages from all connected guilds.

## Actual Results

I only receive messages from the smaller one (guild wars), and none from the huge one.

## Intents

No intents used, so the default is in use.

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python v3.7.9-final
- discord.py v1.6.0-final
- aiohttp v3.7.3
- system info: Windows 10 10.0.18362

**Comment by oliver-ni** [comment]
Just tried, I can reproduce the issue on a userbot

**Comment by scrazzz** [comment]
Can reproduce.
```py
async def on_message(m):
  # both guild ids.
  ids = ['579772930607808537', '144894829199884288']
  for id in ids:
    if m.guild.id == int(id):
      print(m.guild.name, m.content)
```
![ABAB2050-3BC4-4268-BA64-077DF2E0FEA3](https://user-images.githubusercontent.com/70033559/105476286-80837e00-5cb1-11eb-8ac1-a186efdb5971.jpeg)

**Comment by svaningelgem** [comment]
Ok, I found a potential fix. However, I think it will have a lot of repercussions (meaning: need to check a lot of things if everything still keeps working).

Please find the diff here: https://github.com/Rapptz/discord.py/compare/master...svaningelgem:user_bot_does_not_receive_messages

The new_payload causes the server to respond with a "READY_SUPPLEMENTAL" event.
When I do not respond, it will still not send me messages.

But when I respond with opcode 14 (not documented as far as I saw), it will respond with a GUILD_CREATE and magically start to send me messages.

Maybe this will help you find the issue here?

**Comment by svaningelgem** [comment]
Ok, I boiled it even more down.
when I do:
```python
    async def on_ready(self, *args, **kwargs):
        for guild in self.guilds:
            payload = {
                "op": 14,
                "d": {
                    "guild_id": str(guild.id),
                    "typing": True,
                    "threads": False,
                    "activities": True,
                    "members": [],
                    "channels": {
                        str(guild.channels[0].id): [
                            [
                                0,
                                99
                            ]
                        ]
                    }
                }
            }

            asyncio.ensure_future(self.ws.send_as_json(payload), loop=self.loop)
```

I receive messages. When I do NOT do this, I don't.

**Comment by m10653** [comment]
I can also confirm I have get this same reaction when trying to read messages from
Genshin Impact Official ~ 700k members

**Comment by svaningelgem** [comment]
@Rapptz : Could you please explain why you closed this bug that has been confirmed by lots of other people?
Has it been resolved within the framework?

**Comment by Rapptz** [comment]
Selfbot issues will not be worked on.
