### ISSUE TITLE
Guild.default_role.mention won't mention

### ISSUE THREAD

**Issue by scrazzz** [Rapptz/discord.py#6344]
## Summary
Using `Guild.default_role.mention` won't mention `@everyone`, instead it sends `@@everyone`.

## Reproduction Steps
Make a command which mentions the default role.
```python
@bot.command()
async def aaa(ctx):
    await ctx.send(ctx.guild.default_role.mention)
```

## Expected Results
Bot actually pings `@everyone`.

## Actual Results
Bot doesn't ping everyone but only sends `@@everyone`.

## Intents
`discord.Intents.all()`

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information
- Python v3.8.7-final
- discord.py v1.6.0-final
- aiohttp v3.7.3
- system info: Linux 5.4.0-1019-gcp

**Comment by Rapptz** [comment]
By design. Everyone pings is the literal text `@everyone` not a role mention. There is no special casing for this.
