### ISSUE TITLE
You cannot get a list of members in on_ready() or on_connect(), however you can send messages to a channel.

### ISSUE THREAD

**Issue by LivestC** [Rapptz/discord.py#6348]
## Summary
try to edit a message in `on_ready()` and `on_connect()`, and try to use `await asyncio.sleep(30)` but it returns the same error. 

## Reproduction Steps
```
while True:
        await asyncio.sleep(3);
        bots = 0;
        countingserverles = 0;
        serverles = await client.fetch_guild(781918826312892437);
        for reactmember in range(0, len(serverles.member_count)):
            countingserverles += 1;
            if ((len(serverles.member_count) + 1) == countingserverles):
                break
            if (reactmember.bot == True):
                bots += 1;
```

## Expected Results
that the message begins to be edited every so often. (In on_`on_ready()` or `on_connect`)
## Actual Results
```Ignoring exception in on_connect
Traceback (most recent call last):
  File "//files/usr/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "nq/panel.py", line 14, in on_connect
    for reactmember in range(0, len(serverles.member_count)):
  File "/files/usr/lib/python3.9/site-packages/discord/guild.py", line 741, in member_count
    return self._member_count
AttributeError: _member_count```
## Intents
`client = discord.Client(intents=messages=True, guild=True, members=True);`

## Checklist
[yes, yes, yes, yes]

## System Information
Run `python panel.py`, modules used: `asyncio`, `discord`, `re`, `psutil`-->
<!-- python version: `3.9`, library version: idk, but install discord.py (today), system operative: Linux-Debian.

**Comment by Rapptz** [comment]
The documentation for [`Client.fetch_guild`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.fetch_guild) specifically mentions what is not available. One of these is member information. I don't know what the overall code is doing, but you probably wanted [`Client.get_guild`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.get_guild) instead.

**Comment by LivestC** [comment]
> The documentation for [`Client.fetch_guild`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.fetch_guild) specifically mentions what is not available. One of these is member information. I don't know what the overall code is doing, but you probably wanted [`Client.get_guild`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.get_guild) instead. 

Thanks!, but now i get another error from `serverles.member_count`, It seems to return nothing.
```
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/files/usr/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "nq/panel.py", line 12, in on_ready
    for reactmember in range(0, len(serverles.member_count)):
TypeError: object of type 'int' has no len()
```
I tried using: `str(serverles.member_count)`, But it does not work.
