### ISSUE TITLE
Accepting a friend request?

### ISSUE THREAD

**Issue by Johnystar** [Rapptz/discord.py#635]
Is it possible top accept a friend request or to send one? According to my knowledge you can't join a private group chat unless someone who added you to his friend list adds you. This means that if I would want to add my bot to a private group chat, I need to add him to my friend list first and he needs to accept my friend request. The problem is that I can't find a way to make the bot accept my friend request.

**Comment by Bluscream** [comment]
Either you do it with the requests module or use the rewrite branch

**Comment by Johnystar** [comment]
@Bluscream Ok, thank you. I'm still quite new to GitHub

**Comment by Bluscream** [comment]
You can install it with `python3 -m pip install -U https://github.com/Rapptz/discord.py/archive/rewrite.zip#egg=discord.py[voice]`

**Comment by Johnystar** [comment]
@Bluscream Ok, thx

**Comment by Rapptz** [comment]
You can't use those endpoints anymore since they're blacklisted by Discord and will unverify your account.

**Comment by sircal** [comment]
but its on the discord api? there has to be a function to do it?

**Comment by Harmon758** [comment]
Bots can't accept friend requests. The functionality just isn't there.
The endpoint itself is used by user accounts. However, self-bots on [user accounts](https://discordapp.com/developers/docs/topics/oauth2#bot-vs-user-accounts) [is forbidden now](https://support.discordapp.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-).
​
> do it with the requests module

I'd also liked to belatedly point out that requests is [blocking](https://discordpy.readthedocs.io/en/latest/faq.html#what-does-blocking-mean) and should not be used in conjunction with discord.py.

**Comment by LowJunnHoi** [comment]
oke

**Comment by Harmon758** [comment]
Please don't unnecessarily necro-bump old closed issues.
