### ISSUE TITLE
This Works pip install discord 

### ISSUE THREAD

**Issue by Hexxx-Cmd** [Rapptz/discord.py#6366]
All this was so helpfull, Thank you so much guys :D

_Originally posted by @TocxiDK in https://github.com/Rapptz/discord.py/issues/228#issuecomment-632394203_

**Comment by Soheab** [comment]
discord.py *

**Comment by Harmon758** [comment]
`discord` on PyPI is a mirror package. You should install `discord.py` instead.

GitHub issues for this repository should be used to report issues with the library itself, not for discussing or providing feedback on a closed and locked issue. For that, you should [create a discussion](https://github.com/Rapptz/discord.py/discussions/new) as you should have been prompted to do when creating this issue.
