### ISSUE TITLE
io.BufferedIOBase doesn't work with FFmpegPCMAudio despite what the documentation says

### ISSUE THREAD

**Issue by RioghanDer2te** [Rapptz/discord.py#6385]
# **Summary**

when supplying a `io.BufferedIOBase` object as `source` to `FFmpegPCMAudio`, it get complete instantly when played.

# **Reproduction Steps**

example `io.BufferedIOBase` object:
```py
buffer = io.BytesIO()
gTTS("test").write_to_fp(buffer)
buffer.seek(0)
```
execution with that object:
```FFmpegPCMAudio(buffer, options="-vn -loglevel fatal")```

with `pipe = True`, there's an `io.UnsupportedOperation: fileno` exception, because the file-like object is no actual file.

# **Expected Results**

I expected the audio to play, hearing "test"

# **Actual Results**

the audio got 'skipped'. It instantly compelted after starting without raising any exception

Exception for `source: io.BufferedIOBase` and `pipe = True`:
```py
Traceback (most recent call last):
  File "D:\PyCharm\Project\DiscordBot\venv\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:/PyCharm/Project/DiscordBot/main.py", line 91, in on_voice_state_update
    await cmd_music.ex([], None, client, "play", file=buffer, channel=after.channel)
  File "D:\PyCharm\Project\DiscordBot\commands\cmd_music.py", line 224, in ex
    vc.play(discord.PCMVolumeTransformer(discord.FFmpegPCMAudio(file, pipe=True, options=ffmpeg_options["options"], executable=ffmpeg_path.path), 0.5))
  File "D:\PyCharm\Project\DiscordBot\venv\lib\site-packages\discord\player.py", line 225, in __init__
    super().__init__(source, executable=executable, args=args, **subprocess_kwargs)
  File "D:\PyCharm\Project\DiscordBot\venv\lib\site-packages\discord\player.py", line 138, in __init__
    self._process = self._spawn_process(args, **kwargs)
  File "D:\PyCharm\Project\DiscordBot\venv\lib\site-packages\discord\player.py", line 144, in _spawn_process
    process = subprocess.Popen(args, creationflags=CREATE_NO_WINDOW, **subprocess_kwargs)
  File "D:\Python373\lib\subprocess.py", line 728, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "D:\Python373\lib\subprocess.py", line 1039, in _get_handles
    p2cread = msvcrt.get_osfhandle(stdin.fileno())
io.UnsupportedOperation: fileno
```

A temporary fix for this is the answer to #5192, where 
```py
process = subprocess.Popen(args, creationflags=CREATE_NO_WINDOW, **subprocess_kwargs)
```
is changed to 
```py
self._process = subprocess.Popen(args, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=stderr)
self._stdout = io.BytesIO(self._process.communicate(input=stdin)[0])
``` 
and the `io.BufferedIOBase` is `read()`
The problem with this fix is that it only works for `io.BufferedIOBase` types though.

# **Intents**

`discord.Intents.all()`

# **System Information**

discord.py version: 1.6.0
python version: 3.7
windows version: 10 build 1903

# **Checklist**

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Vitaman02** [comment]
I am having the same issues after trying the same thing. Any ideas?

**Comment by RioghanDer2te** [comment]
> 
> 
> I am having the same issues after trying the same thing. Any ideas?

You can use the workaround mentioned in the comment to the mentioned issue (#5192).
Though keep in mind that that workaround doesn't work with normal streams.
