### ISSUE TITLE
Internet crash

### ISSUE THREAD

**Issue by kratonisch** [Rapptz/discord.py#639]
Task was destroyed but it is pending!
task: <Task pending coro=<Client._run_event() running at /root/miniconda3/lib/python3.6/site-packages/discord/client.py:307> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f353c9ff5b8>()]>>

**Comment by Rapptz** [comment]
This is not a crash, it's a resource warning that means nothing.

Open another issue with more information if you have an actual issue with the library.
