### ISSUE TITLE
Reason not shown in audit log when deleting an emoji.

### ISSUE THREAD

**Issue by scrazzz** [Rapptz/discord.py#6400]
**Summary**

When deleting an emoji with a reason, the reason doesn't show up in the audit log.

**Reproduction Steps**

```py
@bot.command()
async def delete(ctx, emoji: int): # using id of the emoji here
    await bot.get_emoji(emoji).delete(reason="Testing")
```

**Expected Results**

The reason of deleting the emoji shown in the audit logs.

**Actual Results**

Emoji gets deleted but the reason of deleting the emoji doesn't show in audit log.

**Intents**

all

**System Information**

- Python v3.8.7-final
- discord.py v1.6.0-final
- aiohttp v3.7.3
- system info: Linux 5.4.0-1019-gcp

**Checklist**

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Zomatree** [comment]
this is an issue with the discord client not the library, the library sends the reason to the api. this can be proven by fetching the audit log via [guild.audit_logs](https://discordpy.readthedocs.io/en/latest/api.html#discord.Guild.audit_logs).

**Comment by scrazzz** [comment]
Okay.
