### ISSUE TITLE
I cant get list of members (guild.members, or role.members)

### ISSUE THREAD

**Issue by SmileaffO** [Rapptz/discord.py#6409]
**Summary**

Only bot info in member list

**Reproduction Steps**

import discord
from discord.ext import commands
client=commands.Bot( command_prefix='*' )
bot=commands.Bot(command_prefix=client)

@client.command()
async def test(ctx):
    for member in ctx.guild.members:
        print(member)

client.run('token')

**Expected Results**

SmileaffO_O Test#9789 (bot)
※Xa1era※#5280
Skelt0n#8202
SmileaffO_O#0668

**Actual Results**

SmileaffO_O Test#9789

**Intents**

i dont use that

**System Information**

- Python v3.9.1-final
- discord.py v1.6.0-final
- aiohttp v3.7.3
- system info: Windows 10 10.0.19041

**Checklist**

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

Code was wrote by MVSC(Miscrosoft Visual Studio Code)

**Comment by Rapptz** [comment]
> i dont use that

https://discordpy.readthedocs.io/en/latest/intents.html#where-d-my-members-go
