### ISSUE TITLE
Private Error handling doesn't work inside command groups

### ISSUE THREAD

**Issue by NightZan999** [Rapptz/discord.py#6412]
**Summary**

So, I made a command group and added a subcommand, I called this subcommand vote. Now it has a cooldown associated with it, but somehow the error handling doesn't trigger

**Reproduction Steps**

So, I made a command group and added a subcommand, I called this subcommand vote. Now it has a cooldown associated with it, but somehow the error handling doesn't trigger

```
@vote.error
async def vote_error(self, ctx, error):
    if isinstance(error, commands.CommandOnCooldown):
        await ctx.send("Slow it down, your on cooldown!")
```
Somehow I still get the error in my console

**Expected Results**

I expected that my bot would actually send, the string I put in. But somehow the error handling doesn't even get triggered. 

**Actual Results**

Instead I get an error message in the console, standard to the cooldown. 
Error:
```
Ignoring exception in command claimrewards vote:
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "/home/container/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1340, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/container/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 856, in invoke
    await self.prepare(ctx)
  File "/home/container/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 789, in prepare
    self._prepare_cooldowns(ctx)
  File "/home/container/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 773, in _prepare_cooldowns
    raise CommandOnCooldown(bucket, retry_after)
discord.ext.commands.errors.CommandOnCooldown: You are on cooldown. Try again in 3524.07s
```

**Intents**

discord.Intents.all()

**System Information**

1.5.1 

**Checklist**

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

So, uhh am I doing the error handler wrong. Or what am I doing wrong, I think this is a bug though!

**Comment by AbstractUmbra** [comment]
Given the slightly limited information here I need to make some assumptions.

I see you have a local error handler here for the `vote` command.
However I don't suppose you have something in your global error handler, to ignore commands that have this local error applied to them?

Something like:
```py
if hasattr(ctx.command, "on_error"):
    return
```

**Comment by NightZan999** [comment]
> Given the slightly limited information here I need to make some assumptions.
> 
> I see you have a local error handler here for the `vote` command.
> However I don't suppose you have something in your global error handler, to ignore commands that have this local error applied to them?
> 
> Something like:
> 
> ```python
> if hasattr(ctx.command, "on_error"):
>     return
> ```

No, I don't have a global error handler. I use the local error handling for all my commands, say a command is in a command group. How do I locally access the command, since when I do the vote.error thing, it never triggers the error handling. Perhaps I am doing this wrong or you cannot actually have error handling for subcommands? 

I don't know much about a global error handler, that is why I don't use them (I used to, but now I don't). And I am a bit confused, a global error handler is this right:
```py
@client.event
async def on_comand_error(ctx, error):
    pass
```
I don't have one of these.

**Comment by NightZan999** [comment]
@Rapptz what is no repro even mean? Is this fixable? Will this be fixed in V 2.0

**Comment by Rapptz** [comment]
It means the issue cannot be reproduced. Usually this means you're leaving something out of the bug report which would make it actionable or that there's another issue in here. I know for a fact error handlers work. Otherwise there would be a lot of bug reports over this (and there aren't any).

**Comment by NightZan999** [comment]
> It means the issue cannot be reproduced. Usually this means you're leaving something out of the bug report which would make it actionable or that there's another issue in here. I know for a fact error handlers work. Otherwise there would be a lot of bug reports over this (and there aren't any).

error handlers for command groups? how, explain it to me please? The normal command error handler (local) is simple, but no-one really uses groups that much. A solution to this?

**Comment by NightZan999** [comment]
and an obvious one would be to use a global error handler, most people use that. And that does not actually make that much sense to me, as the introduction of command groups, there should be a way to actually add local error handling in them.

**Comment by Rapptz** [comment]
In a group, you probably want the invocation order to be `invoke_without_command=True` if you want them to be separate commands. As it stands right now though, this issue is inactionable and seems more suitable as a support question asked in the official server since group error handlers do work just fine.

**Comment by NightZan999** [comment]
> In a group, you probably want the invocation order to be `invoke_without_command=True` if you want them to be separate commands. As it stands right now though, this issue is inactionable and seems more suitable as a support question asked in the official server since group error handlers do work just fine.

I put the invoke_without_ command  = True in the brackets. Does that mean anything?

**Comment by NightZan999** [comment]
>I see you have a local error handler here for the vote command.
However I don't suppose you have something in your global error handler, to ignore commands that have this local error applied to them?

@Rapptz, okay I figured this one out, that one comment made me think again. So I actually had this async def invoke_after in my cog which ignores commandoncooldown errors. So this was no bug with the library 

and you were right, no repro :D
