### ISSUE TITLE
ChannelType.RULES or Community Channels.

### ISSUE THREAD

**Issue by DolphinGamerYT** [Rapptz/discord.py#6418]
**Summary**

Add a way to know if a channel is community (also known as rules channel)

**What is the feature request for?**

The core library

**The Problem**

Basically, I'm coding a bot that deletes channels, and I found out that rules channel cannot get deleted (https://prnt.sc/z8fr5y). There's no known or documented way of knowing if a channel is a community channel.

**The Ideal Solution**

Get another type on `ChannelType` that's community or rules.

**The Current Solution**

Getting `guild.rules_channel`.

**Comment by SuperSajuuk** [comment]
This feature already exists: https://discordpy.readthedocs.io/en/latest/api.html#discord.Guild.rules_channel

if this is a channel, you can check if the id matches the one you’re trying to delete.

**Comment by Rapptz** [comment]
Rule channels aren't separate channel types. If you want to check if something is a rule channel you're better off checking if the ID matches for rule_channel_id or using rule_channel.
