### ISSUE TITLE
add_reaction event not working properly on DMChannels

### ISSUE THREAD

**Issue by ScriptHosT12** [Rapptz/discord.py#6427]
**Summary**

add_reaction event is not dispatched on direct messages

**Reproduction Steps**

run this code with the the necessary changes
```py
import asyncio

import discord

client = discord.Client()

@client.event
async def on_message(message):
    if isinstance(message.channel, discord.DMChannel) and message.content == "hey":
        target_message = await message.channel.send("Hey there buddy react this message please")
        await target_message.add_reaction("✅")

        def check(r, u):
            return u.id == message.author.id and target_message.id == r.message.id

        try:
            await client.wait_for("reaction_add", timeout=30, check=check)
        except asyncio.exceptions.TimeoutError:
            await message.channel.send("You didn't react...")
        else:
            await message.channel.send("Thanks!")

client.run("<token>")
```

**Expected Results**

The bot should respond after the reaction
(this behaviour happens on discord.py 1.5)

**Actual Results**

The bot does not respond to the reaction, and will blame it on you for not reacting after the timeout
(this behaviour happens on latest)

**Intents**

default intents

**System Information**

- Python v3.8.3-final
- discord.py v1.6.0-final
- aiohttp v3.6.3
- system info: Windows 10 10.0.18362

**Checklist**

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Zomatree** [comment]
You require the members intent to be able to use the `on_reaction_add` inside DMs, either [enable the members intent](https://discordpy.readthedocs.io/en/latest/intents.html) or use the `on_raw_reaction_add` event.
