### ISSUE TITLE
Add emojis in once

### ISSUE THREAD

**Issue by CyberRex0** [Rapptz/discord.py#6428]
**Summary**

It can add some emojis in once in one call

**What is the feature request for?**

The core library

**The Problem**

Currently, we have to call add_reaction multiple times to add multiple emoji.

**The Ideal Solution**

We would like to be able to add them in a single call.
I think we can use add_reaction internally and add it in a for loop.

**The Current Solution**

I would like to be able to pass in a list or tuple type.

```py
async def add_reactions(self, ctx, emojis):
  for emoji in emojis:
    await ctx.add_reaction(emoji)
```

And when we actually use it

```py
await message.add_reactions(['🤔', '😆'])
# or
await message.add_reactions(('🤔', '😆'))
```

**Comment by SebbyLaw** [comment]
Methods that do things in batch (eg: [`TextChannel.delete_messages`](https://discordpy.readthedocs.io/en/latest/api.html#discord.TextChannel.delete_messages) and [`Message.clear_reactions`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Message.clear_reactions)) correspond to a single api request that executes the batch operation.

This is a pretty trivial helper function you can implement yourself.

**Comment by CyberRex0** [comment]
Yes, it's a simple implementation, so I can do it myself ...
However, I believe that this will reduce the burden on developers in no small way.

**Comment by IAmTomahawkx** [comment]
a single for loop seems pretty small though. Again, quite trivial to implement yourself

**Comment by Rapptz** [comment]
In the library, batch functions and methods are only added if there is a corresponding batch endpoint in the API that can be used. Reactions have no such thing, therefore it's not available.

There can be a bit of an inconsistency, for example `member.add_roles` can operate either in batch endpoint mode or not depending on the `atomic` parameter being passed but ultimately even that one has an underlying batch endpoint should you want it.
