### ISSUE TITLE
Voice Client average latency issue

### ISSUE THREAD

**Issue by Shifty6** [Rapptz/discord.py#6430]
**Summary**

Voice Client average latency zero division error

**Reproduction Steps**

For the first 5~ seconds after joining a voice channel (until the first heartbeat ack), the `average_latency` property results in a `ZeroDivisionError`.

```py
async def join(ctx):
    voice_channel = ctx.author.voice.channel
    if voice_channel:
        await voice_channel.connect()
        print(ctx.guild.voice_client.average_latency)
```

**Expected Results**

Return `float('inf')` if there have been no heartbeat acks, just as it would if there was no heartbeat at all.

**Actual Results**

The bot attempts to calculate average -- `sum(recent_acks) / len(recent_acks)` -- resulting in `ZeroDivisionError`.

**Intents**

default intents

**System Information**

- Python v3.9.0-final
- discord.py v1.6.0-final
- aiohttp v3.6.3
- system info: Windows 10 10.0.19041

**Checklist**

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by RioghanDer2te** [comment]
I could reproduce it
