### ISSUE TITLE
Add argument on guild_only/dm_only decorator

### ISSUE THREAD

**Issue by Mika64** [Rapptz/discord.py#6438]
**Summary**

Add possibility to response on guild_only

**What is the feature request for?**

discord.ext.commands

**The Problem**

I need to ctx.channel.send when command is not authorized by guild_only/dm_only

**The Ideal Solution**

Add an argument on guild_only/dm_only decorator to response on error

**The Current Solution**

_No response_

**Comment by Vexs** [comment]
These decorators already raise an error to the `on_command_error` event. You can send a message from within this event. See [the documentation](https://discordpy.readthedocs.io/en/latest/ext/commands/commands.html#error-handling) for an example of how to do so.
