### ISSUE TITLE
How do I send a message when a command gets a "Bad Request"

### ISSUE THREAD

**Issue by PicklesJars** [Rapptz/discord.py#644]
How do I send a message when a command gets a "Bad Request"?

**Comment by MysterialPy** [comment]
Bad request usually means that you have more than 2000 characters and is not a lib issue it is from Discords end.

To ask these sorts of questions, you are better off joining https://discord.gg/0SBTUU1wZTUzBx2q
Read the channels topic for guidelines and then ask your question.

**Comment by PicklesJars** [comment]
Thanks.
