### ISSUE TITLE
add_reaction does nothing

### ISSUE THREAD

**Issue by Treehee** [Rapptz/discord.py#646]
I'm currently working on a bad word detector bot. It is supposed to add the 😡 emoji as a reaction to messages containing "bad" words. the client.add_reaction bit, however, does absolutely nothing; it doesn't even return a error!
code snippet;

`@client.event
async def on_message(message):
    if scan(message.content):
        client.add_reaction(message, "\N{POUTING FACE}")
        print("detected")
    else:
        print("safe")`

**Comment by TheTrain2000** [comment]
`add_reaction()` is a coroutine, therefor it must have `await` in front of it.

`await client.add_reaction(message, ...)`

**Comment by Treehee** [comment]
thank you :)

I should've figured xD

I always forget the await
