### ISSUE TITLE
Channel.permissions_synced returns False, despite being synced

### ISSUE THREAD

**Issue by AlexFlipnote** [Rapptz/discord.py#6464]
**Summary**

Sometimes not returning True when it's synced

**Reproduction Steps**

- Create a channel
- Sync it with a category
- Try executing `ctx.channel.permissions_synced`

**Expected Results**

```py
>>> ctx.channel.permissions_synced
True
```

**Actual Results**

![Channel](https://i.alexflipnote.dev/5fmxVuu.png) ![Command](https://i.alexflipnote.dev/2r5jS5w.png)

**Intents**

guilds, members, messages, bans, emojis, voice_states, presences, reactions

**System Information**

- Python v3.9.1-final
- discord.py v1.7.0-alpha
    - discord.py pkg_resources: v1.7.0a2774+gcc55a28
- aiohttp v3.6.3
- system info: Windows 10 10.0.19041

**Checklist**

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by AlexFlipnote** [comment]
Sidenote: I'm thinking it can be something to do with the new layout of channel permissions, as this command eval works fine in my different server that uses the old channel permission layout, while this one has the new layout and is made public (Community server)

**Comment by Rapptz** [comment]
I'm not sure what would cause this other than the official client either using a newer definition (it used to be overwrites being equal, which is what the library does) or somehow the overwrite cache being out of date.

**Comment by AlexFlipnote** [comment]
It keeps happening regardless if I reboot the bot (renewing the cache). Might possibly be what you mentioned abouta newer definition, not sure personally.

**Comment by Rapptz** [comment]
A dump of the category overwrites and the synced channel's overwrites would be useful to find out what the newer definition is.

**Comment by AlexFlipnote** [comment]
Here's from the channel
```json
{'stream': None, 'manage_emojis': None, 'manage_nicknames': None, 'view_audit_log': None, 'manage_roles': None, 'priority_speaker': None, 'deafen_members': None, 'ban_members': None, 'change_nickname': None, 'kick_members': None, 'manage_guild': None, 'add_reactions': None, 'use_voice_activation': None, 'embed_links': None, 'administrator': None, 'send_messages': None, 'manage_messages': None, 'read_message_history': None, 'mute_members': None, 'create_instant_invite': None, 'view_guild_insights': None, 'speak': None, 'send_tts_messages': None, 'manage_channels': None, 'connect': None, 'external_emojis': None, 'mention_everyone': None, 'attach_files': None, 'move_members': None, 'manage_webhooks': None, 'read_messages': None}
```
and here's from the category
```json
{'stream': None, 'manage_emojis': None, 'manage_nicknames': None, 'view_audit_log': None, 'manage_roles': None, 'priority_speaker': None, 'deafen_members': None, 'ban_members': None, 'change_nickname': None, 'kick_members': None, 'manage_guild': None, 'add_reactions': None, 'use_voice_activation': None, 'embed_links': None, 'administrator': None, 'send_messages': None, 'manage_messages': None, 'read_message_history': None, 'mute_members': None, 'create_instant_invite': None, 'view_guild_insights': None, 'speak': None, 'send_tts_messages': None, 'manage_channels': None, 'connect': None, 'external_emojis': None, 'mention_everyone': None, 'attach_files': None, 'move_members': None, 'manage_webhooks': None, 'read_messages': None}
```
Hopefully I'm dumping correct info, otherwise tell me how I can do it.

**Comment by Rapptz** [comment]
Sorry no, that's not what I'm looking for.

I need a dump of the two overwrite objects. It requires accessing some internals unfortunately but since we're debugging it's just `[x._asdict() for x in channel._overwrites]` for both the faulty channel and the category its in.

**Comment by AlexFlipnote** [comment]
Channel 
```py
[{'id': 86484642730885120, 'allow': 0, 'deny': 0, 'type': 'role'}, {'id': 453257814710943764, 'allow': 0, 'deny': 3136, 'type': 'role'}]
```
Category
```py
[{'id': 453257814710943764, 'allow': 0, 'deny': 3136, 'type': 'role'}]
```

As far as I can see from the dump you wanted, the [at]everyone role is missing from the category. I double checked today as well and the channel is still synced with the category in question.

**Comment by Rapptz** [comment]
Okay, I see what's happening here. The client doesn't consider empty permissions (allow and deny == 0). This should be relatively easy to fix.
