### ISSUE TITLE
adding a command check for preventing it being used on people who have a certain permission 

### ISSUE THREAD

**Issue by StandingPadAnimations** [Rapptz/discord.py#6475]
**Summary**

So there's a check that allows a command to only be used by people with a certain permission, but what about one for commands to not affect people with a permission(ex. ban command would work for most people, but not for people with the ban players permission)

**What is the feature request for?**

discord.ext.commands

**The Problem**

Making commands not affect users with certain permissions becomes easier. 

**The Ideal Solution**

A check that prevents commands from working on users with certain permissions like:
`@commands.do_not_affect(has_permissions = ban_players)`

**The Current Solution**

_No response_

**Comment by IAmTomahawkx** [comment]
Seems very niche

**Comment by Zomatree** [comment]
This cant be done via a check as it requires reading the command's parameters, consider using a custom converter or handling this inside the command.

**Comment by Rapptz** [comment]
This seems niche enough to be implemented locally.
