### ISSUE TITLE
Example in the readme does not work

### ISSUE THREAD

**Issue by egils-consulting** [Rapptz/discord.py#6480]
**Summary**

example seems broken

**Reproduction Steps**

copy pasted the example:
import discord

class MyClient(discord.Client):
    async def on_ready(self):
        print('Logged on as', self.user)

    async def on_message(self, message):
        # don't respond to ourselves
        if message.author == self.user:
            return

        if message.content == 'ping':
            await message.channel.send('pong')

client = MyClient()
client.run('token')

**Expected Results**

after inserting my token I expected the code to run

**Actual Results**

$ python discord.py 
Traceback (most recent call last):
  File "/home/user/src/discord-test/discord.py", line 1, in <module>
    import discord
  File "/home/user/src/discord-test/discord.py", line 3, in <module>
    class MyClient(discord.Client):
AttributeError: partially initialized module 'discord' has no attribute 'Client' (most likely due to a circular import)

**Intents**

none

**System Information**

$ python -m discord -v
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/nizo/src/discord-test/discord.py", line 1, in <module>
    import discord
  File "/home/nizo/src/discord-test/discord.py", line 3, in <module>
    class MyClient(discord.Client):
AttributeError: partially initialized module 'discord' has no attribute 'Client' (most likely due to a circular import)

**Checklist**

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by egils-consulting** [comment]
on arch, $ pacman -Q python-discord 
python-discord 1.6.0-1

the tree in 
/usr/lib/python3.9/site-packages/discord
looks ok.

**Comment by egils-consulting** [comment]
also tried the example here https://discordpy.readthedocs.io/en/latest/intro.html
with same result

**Comment by darthshittious** [comment]
Your main file is named discord.py
This conflicts with the library. Name it something else to avoid this.
