### ISSUE TITLE
Script hangs at 'client.run()'

### ISSUE THREAD

**Issue by gurke12** [Rapptz/discord.py#6491]
**Summary**

When I try to run my code, it doesn't continue at 'client.run()'. I know this bc I added multiple 'print("")' to show me what is happening.

**Reproduction Steps**

This began out of nowhere. I tried going back and simplefying the code to a few lines or setting up a new bot, but nothing helped. 

**Expected Results**

The Bot should start up like minutes before and perform the programmed actions

**Actual Results**

The Bot is displayed as online on discord, but doesn't answer and I can see in the console that it stop as 'client.run()'

**Intents**

No intents/Standart (?)

**System Information**

- Python v3.9.1-final
- discord.py v1.6.0-final
- aiohttp v3.7.4
- system info: Windows 10 10.0.19041

**Checklist**

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

_When I try to run my code, it doesn't continue at 'client.run()'. I know this bc I added multiple 'print("")' to show me what is happening.
This began out of nowhere. I tried going back and simplefying the code to a few lines or setting up a new bot, but nothing helped. 
The Bot is displayed as online on discord, but doesn't answer and I can see in the console that it stop as 'client.run()'_

**Console:** 

```
Starting...
discord imported
os imported
Logging in...

```
_After this nothing happens._

**Program:** 

```
print("Starting...")

import discord
print("discord imported")
import os
print("os imported")
import random

client = discord.Client()

print("Logging in...")

client.run(os.getenv("TOKEN"))

print("Startup complete.")

@client.event
async def on_ready():
  print("We have logged in as client {0.user}".format(client))
```

**Comment by Phxntxm** [comment]
![image](https://user-images.githubusercontent.com/3664828/109403597-afbd8880-790a-11eb-94ae-f5fa628dbbb6.png)
That's correct, this is how this functions... you need to do all the things you want attached to it BEFORE the `.run` call, as it notes in the docs it blocks

**Comment by gurke12** [comment]
So basically client.run has to be at the end?

**Comment by Phxntxm** [comment]
> So basically client.run has to be at the end?

Essentially

**Comment by gurke12** [comment]
Thank you veeeeeeery much for the fast help! I hope other people as dumb as me will see this before having a breakdown ;)
