### ISSUE TITLE
Webhook.delete() raises exception 'Session is closed'

### ISSUE THREAD

**Issue by Smerdokryl** [Rapptz/discord.py#6516]
### Summary

Webhook.delete() raises exception 'Session is closed'

### Reproduction Steps

```python
for webhook in await ctx.guild.webhooks(): 
	try:
		await webhook.delete();
	except Exception as e:
		print(e);
```

### Expected Results

All guild's webhooks get deleted

### Actual Results

No webhooks are deleted, console prints out:
Session is closed
Session is closed
Session is closed
...
for each webhook

### Intents

Presence and member

### System Information

- Python v3.7.3-final
- discord.py v1.6.0-final
- aiohttp v3.7.4
- system info: Linux 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

As described, I'm attempting to delete all webhooks in the guild, but instead I'm getting "Session is closed" exceptions

**Comment by Rapptz** [comment]
This needs more information. If you're calling this after the bot has logged off (i.e. after `run` is over) then this would happen. Otherwise I see no reason for this to happen.

**Comment by Smerdokryl** [comment]
@Rapptz The bot is not closed, I was calling this via a command.

However, now that I wanted to tell you whether the bot continues accepting other commands after this one, and I started it to check, this error has miraculously disappeared. Perhaps it was a temporary discord issue....

**Comment by Smerdokryl** [comment]
Okay, I restarted the bot and tried again - the error reappeared

**Comment by Rapptz** [comment]
The bot's internal session is only closed after a call to `logout`/`close`. 

If you have a minimal reproducible example that shows this you can post it here. Though I'd probably also need the full traceback (which was left out of the original report) to ensure that my suspicions are correct that this even involves the internal session in the first place.

**Comment by Smerdokryl** [comment]
Okay, I think I might have been mistaken: the 'Session is closed' exceptions appear n times where n is the number of webhooks only upon me closing the bot. Until then, it seems to just hang on the first webhook.delete(); iteration (while still accepting other commands)

**Comment by Rapptz** [comment]
Webhook requests are logged via logging. There is [documentation](https://discordpy.readthedocs.io/en/latest/logging.html#logging-setup) showing how to set it up. It'll show you what's happening with the request.

I'm unsure what more there is to it, I suspect you might be getting rate limited.

**Comment by Smerdokryl** [comment]
Yep, I just added logging and this is what I'm getting:
```
DEBUG:discord.webhook:Webhook ID ... with DELETE / has returned status code 429
WARNING:discord.webhook:Webhook ID ... is rate limited. Retrying in 2526.70 seconds
```

**Comment by Rapptz** [comment]
Yeah I see. The library is just waiting for the rate limit to be over. I didn't know webhook delete rate limits were this large though but that's why it's taking so long. I can't really do much about that one though so I'm going to close this issue.
