### ISSUE TITLE
Documentation for Bot.change_presence missing a warning/note

### ISSUE THREAD

**Issue by pythonmcpi** [Rapptz/discord.py#6517]
### Summary

When running two instances of a bot on the same account (same token), the older instance controls the status (online, idle, dnd, invisible).

### Reproduction Steps

Run two instances of a bot and have the younger instance try to change its status to dnd. The instance will think it changed its status, but the status displayed to users is still online. Changing the status on the older instance will change the actual status.

### Expected Results

I expected some form of warning or note on the documentation for Bot.change_presence.

### Actual Results

There was no note about an older instance of a bot controlling the bot status and led to a lot of head scratching.

### Intents

discord.Intents.all()

### System Information

- Python v3.9.1-final
- discord.py v1.6.0-final
- aiohttp v3.7.3
- system info: Windows 8.1 6.3.9600

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by scrazzz** [comment]
You normally wouldn't run two instances of the same bot. The bot instance which gets connected the last to the Discord API controls this presence (aka "status") afaik.

This is reproducible by self-botting and changing the presence on the client side. First, run the self-bot code and get connected to the Discord API (presence would be online if not specified). Then, login to that same account on the Discord client and change the presence to anything other than online, let's say we set it as Do Not Disturb. Now, even if you have logged out of the account on the client side, the presence stays to which one you set the last, that is, Do Not Disturb.

Again, you normally wouldn't run the same two instances of your bot as it's not practical to do so.
