### ISSUE TITLE
this lib doesn't work either

### ISSUE THREAD

**Issue by kidNinjaPenis** [Rapptz/discord.py#652]
I get this error when running the bot:

TypeError

**Comment by datmellow** [comment]
You need to elaborate more on what is going on.

What have you tried?
What code do you have?
full traceback.

This is not a good example if you actually want help

**Comment by kidNinjaPenis** [comment]
let me pull up mah code

**Comment by kidNinjaPenis** [comment]
aight so im running the example code and I get that error:
import discord
import asyncio

client = discord.Client()

@client.event
async def on_ready():
    print('Logged in as')
    print(client.user.name)
    print(client.user.id)
    print('------')

@client.event
async def on_message(message):
    if message.content.startswith('!test'):
        counter = 0
        tmp = await client.send_message(message.channel, 'Calculating messages...')
        async for log in client.logs_from(message.channel, limit=100):
            if log.author == message.author:
                counter += 1

        await client.edit_message(tmp, 'You have {} messages.'.format(counter))
    elif message.content.startswith('!sleep'):
        await asyncio.sleep(5)
        await client.send_message(message.channel, 'Done sleeping')

client.run('token')

**Comment by NCPlayz** [comment]
Step 0. Learn your programming language the correct way
Step 1. Read the docs; they're there to help you.
Step 2. Read the FAQ
Step 3. Try something on your own first, we're not spoon-feeding code
Step 4. Got  a traceback? Read it yourself first, and try to figure it out on your own. Use the FAQ and docs if needed.
Step 5. Can't figure out the traceback? Post it in the correct channel and show your code.
Step 6. Have patience while people try to help you. Not everyone is here 24/7 to help you.

**Comment by kidNinjaPenis** [comment]
OH maybe the error is there because I didn't indent anything

**Comment by kidNinjaPenis** [comment]
wait now it's erroring with "invalid syntax"

**Comment by NCPlayz** [comment]
also use @bot.command it's easier

**Comment by kidNinjaPenis** [comment]
what does that do?

**Comment by kidNinjaPenis** [comment]
my friend said it's a "label"

**Comment by kidNinjaPenis** [comment]
helloing?

**Comment by kidNinjaPenis** [comment]
hello*

**Comment by nitros12** [comment]
Please leave you're not funny.

**Comment by kidNinjaPenis** [comment]
that's RUDE

**Comment by kidNinjaPenis** [comment]
anyways, my issue is that I get a SynraxError

**Comment by NotSoSuper** [comment]
ur fault, go learn python

**Comment by kidNinjaPenis** [comment]
I know Python... My dad teaches Python at Harvard

**Comment by kidNinjaPenis** [comment]
Now please help my issue

**Comment by thenightex** [comment]
here you go https://www.learnpython.org/

**Comment by kidNinjaPenis** [comment]
The issue I've managed to isolate is this: SyntaxError. I'm going to paste my code

**Comment by kidNinjaPenis** [comment]
here's my custom code for my class system:
def create_objects(name, data, send=False, code=None):
    data = [r for r in data if r[0] and r[1]]
    keys = ['{}:{}'.format(*r) for r in data]
    
    existing_objects = dict(Object.objects.filter(name=name, key__in=keys).values_list('key', 'uid'))

    with transaction.commit_on_success():
        for (pid, w, uid), key in izip(data, keys):
            if key not in existing_objects:
                try:
                    if pid.startswith('_'):
                        result = Result.objects.get(pid=pid)
                    else:
                        result = Result.objects.filter(Q(barcode=pid) | Q(oid=pid)).latest('created')
                except Result.DoesNotExist:
                    logger.info("Can't find result [%s] for w [%s]", pid, w)
                    continue

                try:
                    t = Object.objects.get(name=name, w=w, result=result)
                except:
                    if result.container.is_co:
                        code = result.container.co.num
                    else:
                        code = name_code
                    t = Object.objects.create(name=name, w=w, key=key,result=result, uid=uid, name_code=code)

                    reannounce(t)

                    if result.expires_date or (result.registry.is_sending and result.status in [Result.C, Result.W]):
                        Client().Update(result)

                if not result.is_blocked and not result.in_container:
                    if send:
                        if result.status == Result.STATUS1:
                            Result.objects.filter(id=result.id).update(status=Result.STATUS2, on_way_back_date=datetime.now())
                        else:
                            started(result)

            elif uid != existing_objects[key] and uid:
                t = Object.objects.get(name=name, key=key)
                t.uid = uid
                t.name_code = name_code
                t.save()
                reannounce(t)

**Comment by NotSoSuper** [comment]
https://github.com/sobolevn/python-code-disasters/blob/master/python/create_objects.py
nice code bro
