### ISSUE TITLE
on_command/command_check Event

### ISSUE THREAD

**Issue by ICExFS** [Rapptz/discord.py#6524]
### Summary

on_command

### What is the feature request for?

discord.ext.commands

### The Problem

I think it was already asked but i'm not sure. It'd be cool if there is an "on_command" event which trigger everytime make a command.
My other proposition is to make a "command_check", which is a bool and return True or False
E.G
When someone send a message, the on_message triggers, then we need to add bot/client.process_command(message).
If the message is starting with the prefix, it'll try to make the command, right? But if the command isn't found, it'll make an error.

I think it'd be cool if there is like, "if message.content.is_command". If the message is a command, then it'll return True

### The Ideal Solution

.

**Comment by AbstractUmbra** [comment]
Already exists.
https://discordpy.readthedocs.io/en/latest/ext/commands/api.html?highlight=on_command#discord.on_command
