### ISSUE TITLE
wait_for doesn't actually add listener for the event, and causes it to block forever

### ISSUE THREAD

**Issue by dyc3** [Rapptz/discord.py#6527]
### Summary

client.wait_for doesn't actually add listener for the event, and causes it to block forever

### Reproduction Steps

2 files are required

`bot.py`:
```python
from turns import *
import logging
from discord.ext import commands
import test

logging.basicConfig(level=logging.DEBUG)

bot = commands.Bot(command_prefix='>')

@bot.command()
async def bug(ctx: commands.Context):
	await test.act(ctx)

@bot.command()
async def nobug(ctx: commands.Context):
	await prompt(ctx.author)
	await ctx.send("Success!")

async def prompt(user):
	if not user.dm_channel:
		await user.create_dm()
	msg = await user.dm_channel.send(content="react to me")
	def check(payload):
		logging.debug(f"checking payload {payload}")
		return payload.message_id == msg.id and payload.user_id == user.id
	await bot.wait_for("raw_reaction_add", check=check)

def get_token():
	with open("token", "r") as f:
		return "".join(f.readlines()).strip()

if __name__ == "__main__":
	bot.run(get_token())

```

`test.py`:
```python
from discord.ext import commands
import bot

async def act(ctx: commands.Context):
	await bot.prompt(ctx.author)
	await ctx.send("Success!")
```

Run with `python3 bot.py`.
- `>nobug` to demonstrate that `prompt` should work
- `>bug` to reproduce bug, and invoke insanity. Somehow the same code, when put in a different file, produces different results.

### Expected Results

Expected `wait_for` to stop blocking when the condition is met

### Actual Results

`wait_for` blocks forever

### Intents

unknown

### System Information

- Python v3.9.2-final
- discord.py v1.6.0-final
- aiohttp v3.7.4.post0
- system info: Linux 5.4.0-66-generic \#\74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by dyc3** [comment]
I've also tested this on python 3.10rc

**Comment by SebbyLaw** [comment]
This is not a bug with discord.py. In simple terms, when you import the `bot` module from another file, the same code is executed again, meaning this happens:
```py
bot = commands.Bot(command_prefix='>')  # now a different object than the main bot
```

For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by dyc3** [comment]
Ah I see. I dunno how I didn't catch that.
