### ISSUE TITLE
How do I send messages to a specific channel?

### ISSUE THREAD

**Issue by DafsCode** [Rapptz/discord.py#654]
I'm trying to make a bot that every thirty seconds it sends a piece of text to #bot-commands. How would I do this?

Code:
import discord
import time
client = discord.Client()
time.sleep(30)
channel.send(ChannelIDHere,'Hello')
client.run('mytokenboi')
Nothing gets sent.

Note: it is a selfbot.

Thanks!

**Comment by PapyrusThePlant** [comment]
[This example](https://github.com/Rapptz/discord.py/blob/async/examples/background_task.py) along with [this faq entry](http://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-send-a-message-to-a-specific-channel)

**Comment by Hackmastr** [comment]
Read this: http://discordpy.readthedocs.io/en/latest/faq.html?highlight=sleep#what-does-blocking-mean

Don't use `time.sleep`, instead use `asyncio.sleep`.

**Comment by DafsCode** [comment]
Now getting syntax errors
import discord
import asyncio
client = discord.Client()
await [redtext]asyncio[/redtext].sleep(30)
channel.send((discord.Object(id='12324234183172'), 'Hello')
client.run('token')

**Comment by Hackmastr** [comment]
Please you code tags/markup.

```
```py
code
```
```

What Python version are you running?

**Comment by Eternity71529** [comment]
read what @PapyrusThePlant said

**Comment by liampwll** [comment]
await **[redtext]**asyncio**[/redtext]**.sleep(30)

**Comment by DafsCode** [comment]
Someone close this, ty!

**Comment by DafsCode** [comment]
wait i can i never realised

**Comment by L3h4** [comment]
await client.send_message(discord.Object(id='1234567890'), 'hello')
