### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Visceros** [Rapptz/discord.py#6543]
### Summary

A case where Message.reactions gives incorrect return

### Reproduction Steps

if we have a message created with resending content of replied message (message.reference) like
msg = await ctx.send(replied_message.content)
the msg.reactions  returns an empty list

easily reproduced with short code:

@bot.command()
async def reactions_test(ctx):
    old_message = await ctx.channel.fetch_message(ctx.message.reference.message_id)
    msg = await ctx.send(old_message.content)
    await msg.add_reaction('👍')
    await msg.add_reaction('👎')
    await ctx.send(f'list of reactions provided by message.reactions method: {msg.reactions}')

### Expected Results

a list of Reaction type objects

### Actual Results

empty list

### Intents

all intents.

### System Information

- Python v3.7.1-final
- discord.py v1.6.0-final
- aiohttp v3.7.3
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

Was trying to make a command that makes a poll from replied message and encountered this bug.

**Comment by ImVaskel** [comment]
Can reproduce easily.

**Comment by Vexs** [comment]
This is a known limitation- message objects fetched with fetch_message won't be updated by the gateway. Further, even if they were, they would only update on a gateway update- which can be at some unknown point in the future, which might be after you check it's reactions.

If you want to reliably get the reactions added, either wait_for them or re-fetch the message.

**Comment by Visceros** [comment]
Thanks Vexs, going to try this approach.
