### ISSUE TITLE
discord.py does not use Retry-After header for ratelimiting?

### ISSUE THREAD

**Issue by Cobertos** [Rapptz/discord.py#6547]
### Summary

Discord.py does not take into account Retry-After header

### Reproduction Steps

1. Become Cloudflare rate-limited on an endpoint (in my case, excessive calling to `client.fetch_invite()`)
2. View the headers of the request, it includes a [`Retry-After`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) with seconds until rate limiting will end

![image](https://user-images.githubusercontent.com/6759176/111859772-a035cc00-8919-11eb-81ab-efb3aedb8626.png)

### Expected Results

At the least, discord.py should wait until [`Retry-After`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) header expires before querying again.

Ideally, it would apply the same logic to the per-endpoint ratelimitting bucket, as it does with [the `X-RateLimit-Remaining` Header](https://github.com/Rapptz/discord.py/blob/master/discord/http.py#L195-L198).

The ratelimitting I describe seems to only be on the one endpoint (invites)

### Actual Results

discord.py will raise an [HTTPException 429](https://github.com/Rapptz/discord.py/blob/master/discord/http.py#L207-L209), but not mark the endpoint as exhausted, nor wait the designated amount of time.

### Intents

None

### System Information

- Python v3.8.7-final
- discord.py v1.6.0-final
- aiohttp v3.7.4.post0
- system info: Linux 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

Prior-art:

* This was kinda-sorta handled in here https://github.com/Rapptz/discord.py/issues/2035#issuecomment-478335139
* Seems like there was something in here for it in like 2015, but I assume it was a much different time for Discord then... https://github.com/Rapptz/discord.py/blob/1e175f2ab3cb38c094b2eca8f9214d076b211c4b/discord/client.py#L773

![image](https://user-images.githubusercontent.com/6759176/111859772-a035cc00-8919-11eb-81ab-efb3aedb8626.png)

**Comment by Rapptz** [comment]
https://github.com/Rapptz/discord.py/blob/7836046621d6b670730217ad4de321ef3ecd5cff/discord/utils.py#L318-L326

Retry-After is not used because it lacks the precision needed (milliseconds). Cloudflare bans are not handled either.

**Comment by Cobertos** [comment]
I'm confused, the header itself is documented to be returned in seconds: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.37

Though MDN does mention that `Retry-After` support is inconsistent https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After#dealing_with_scheduled_downtime

**Comment by Rapptz** [comment]
Yes. Retry-After uses seconds, and the precision I need is milliseconds. A lot of routes use millisecond precision, mainly the ones involving reactions. Retry-After is not accurate enough for those rate limits.

**Comment by Cobertos** [comment]
Would it be too kludge-y to divide by 1000 and add a padding of an extra 1000ms, just using the more imprecise time? I can make a PR if desired.

Otherwise, if that doesn't work, this naive snippet would probably suffice for end-users:

```python
#...
except discord.HTTPException as e:
  if e.code == 429 and 'Retry-After' in e.response.headers:
    secondsToSleep = int(e.response.headers['Retry-After'])
    await asyncio.sleep(secondsToSleep)
```

**Comment by Rapptz** [comment]
There is no millisecond precision with Retry-After. It's rounded. So a ratelimit of 500ms is rounded up to 1 second.

I do not want to use Retry-After because it is imprecise. Rate limit headers return `X-Ratelimit-Reset-After` (which is what my snippet was showing). The only case where this isn't returned is when there is a cloudflare ban. Cloudflare bans are not handled (and can't be, because due to their nature they can last anywhere between 1 hour and multiple days). Waiting and sleeping for multiple hours is not desirable behaviour.
