### ISSUE TITLE
Bot suddenly stopped working

### ISSUE THREAD

**Issue by StandingPadAnimations** [Rapptz/discord.py#6552]
### Summary

I was running my bot like normal and it suddenly stopped working. No errors, bot was connected and online. I tried from my PC to see if it was a raspberry pi issue but it still persisted. I even regenerated my token but it still continued.

### Reproduction Steps

My code for the entire bot is(I removed the token and changed my Reddit password and client secret): https://pastebin.com/Sq42XLKT

### Expected Results

For the bot to be running like normal 

### Actual Results

Stopped working for no reason 

### Intents

members, messages, and presences 

### System Information

discord.py v1.6.0-final

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
This issue tracker is not for debugging issues with your bot. Issues need to have a minimal reproducible example or something more concrete to be actionable.

**Comment by ImVaskel** [comment]
Please join the discord at https://discord.gg/dpy for more help on your issue.

**Comment by Rishiraj0100** [comment]
> ### Summary
> I was running my bot like normal and it suddenly stopped working. No errors, bot was connected and online. I tried from my PC to see if it was a raspberry pi issue but it still persisted. I even regenerated my token but it still continued.
> 
> ### Reproduction Steps
> My code for the entire bot is(I removed the token and changed my Reddit password and client secret): https://pastebin.com/Sq42XLKT
> 
> ### Expected Results
> For the bot to be running like normal
> 
> ### Actual Results
> Stopped working for no reason
> 
> ### Intents
> members, messages, and presences
> 
> ### System Information
> discord.py v1.6.0-final
> 
> ### Checklist
> * [x]  I have searched the open issues for duplicates.
> * [x]  I have shown the entire traceback, if possible.
> * [x]  I have removed my token from display, if visible.

Your bot is ratelimited
