### ISSUE TITLE
guilds are 'NoneType' depending on get method

### ISSUE THREAD

**Issue by glass-ships** [Rapptz/discord.py#6566]
### Summary

discord.utils.get(client.guilds, name=GUILD) returns guild as NoneType with no attributes

### Reproduction Steps

```python
import os
import discord
from dotenv import load_dotenv

load_dotenv()
TOKEN = os.getenv('DISCORD_TOKEN')
GUILD = os.getenv('DISCORD_GUILD')

client = discord.Client()

@client.event
async def on_ready():

    guild = discord.utils.get(client.guilds, name=GUILD)

    print('{} has connected to {} (id: {})!'.format(client.user, guild.name, guild.id))

    members = '\n - '.join([member.name for member in guild.members])

    print('Guild Members:\n - {}'.format(members))

@client.event
async def on_message(message):
    if message.author == client.user:
        return

    if message.content == '.ping':
        await message.channel.send('pong!')

client.run(TOKEN)
```

### Expected Results

On connection to guild, print the string "\<bot name\> has connected to \<guild name\> (id: \<guild id\>)!"

### Actual Results

```python
> python bot.py
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/home/glass/dev/anaconda3/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 16, in on_ready
    print('{} has connected to {} (id: {})!'.format(client.user, guild.name, guild.id))
AttributeError: 'NoneType' object has no attribute 'name'
```

### Intents

none

### System Information

> python -m discord -v                                                                                                                                                             

- Python v3.8.5-final
- discord.py v1.6.0-final
- aiohttp v3.7.4.post0
- system info: Linux 5.8.0-45-generic #51~20.04.1-Ubuntu SMP Tue Feb 23 13:46:31 UTC 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

I noticed some other issues similar to this, but they were all closed saying the issue was fixed in v 1.5.0 

Following [this doc](https://realpython.com/how-to-make-a-discord-bot-python), the first method for getting a guild returned no errors:
```python
for guild in client.guilds:
        if guild.name == GUILD:
            break
```

however both methods using `discord.utils.get` and `discord.utils.find` return guild as NoneType. 

Is this something I've overlooked in the [API](https://discordpy.readthedocs.io/en/latest/api.html)?

**Comment by Rapptz** [comment]
`discord.utils.get` and `discord.utils.find` are both explicitly documented to return `None` if the result is not found. Make sure to double check your input. This isn't a bug since this is inactionable and documented.

**Comment by glass-ships** [comment]
Would you be willing to link me to the correct documentation? 

If the guild's ID is accepted as input then I have indeed verified my input multiple times. 

As mentioned, the loop method returns the expected result, so the value of `GUILD` is correct, and the bot is indeed connecting to the correct guild.

**Comment by Rapptz** [comment]
The [documentation is here](https://discordpy.readthedocs.io/en/latest/api.html#discord.utils.get). Note that you're searching via name not by ID. Name search are case sensitive.

**Comment by glass-ships** [comment]
Perfect, thanks so much! I appreciate the help
