### ISSUE TITLE
Watchdog pings to systemctl

### ISSUE THREAD

**Issue by Tylerlhess** [Rapptz/discord.py#657]
Looking through the code, I do not see any way to setup a watchdog service. I am using systemctl to daemonize the process and would like to have a way to send a regular ping. https://gist.github.com/Spindel/1d07533ef94a4589d348 has an example of a simple watchdog implementation.  Having some way to insert a call after every cycle to check if it's time to send another keep alive ping would prevent things like my bot hanging for a day. So while it was still running it wasn't doing anything or logged into my Discord server. I thought I remembered seeing this but couldn't find it afterwards.

**Comment by SunDwarf** [comment]
http://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-run-something-in-the-background

**Comment by Tylerlhess** [comment]
yes I did see the run something in the background and totally spaced I could write a keep alive loop to run in the background.

This still doesn't solve the issue if the bot is stuck in a loop and never returning to accept more commands. It could be idle but still stuck awaiting a response inside an on_message call.

**Comment by SunDwarf** [comment]
Don't write your code so that it blocks the event loop then.
