### ISSUE TITLE
How to remove "Playing" status?

### ISSUE THREAD

**Issue by dendory** [Rapptz/discord.py#658]
If I use this:

    yield from client.change_presence(game=discord.Game(name='Whatever'))

then later on I use this:

    yield from client.change_presence(game=None)

I would expect the bot to remove its "Playing" status completely, like when a user quits a game. But instead it doesn't change the game name at all. Any ideas why?

**Comment by Nekorooni** [comment]
How long do you wait between calls? I think it might be the rate limit, or it taking a while to show the change.

**Comment by dendory** [comment]
A few minutes

**Comment by Nekorooni** [comment]
I can't say for sure, since it's working on the rewrite branch, and I'm pretty sure it worked before too.
Which python are you using and what's the code you use to change it?

**Comment by dendory** [comment]
Python 3.4

I use it to set the title of songs:

        player = yield from voice.create_ytdl_player(my_video)
        player.start()
        yield from client.change_presence(game=discord.Game(name=player.title))

then when the stop command is called I'm trying to remove it:

        player.stop()
        yield from client.change_presence(game=None)

**Comment by Rapptz** [comment]
That should remove it (and it does for me).

Gonna need more info for this one.

**Comment by Repulser** [comment]
Its probably your client caching the status

**Comment by Crypti-x** [comment]
I think this issue can be closed
