### ISSUE TITLE
Removing "stacked" reactions doesn't always work or is delayed

### ISSUE THREAD

**Issue by jgayfer** [Rapptz/discord.py#659]
**Use Case:** The bot creates a message with certain prompts, and adds a check mark and an X emoji/reaction. When the user also reacts with a check mark or an X, the bot will execute whatever functionality the user has selected. But in order to keep things clean, once a user has reacted and the bot has taken action, the user's reaction should be removed

When the user adds a reaction that does NOT already exist on the message, the following chunk of code works just fine, and the reaction is removed immediately. However, when the user adds a reaction that already exists (ie, the user adds a checkmark after the bot adds one), the reaction is sometimes not deleted, or takes a few seconds to delete. The behaviour doesn't seem to be consistent in that sense.

```
@bot.event
async def on_reaction_add(reaction, user):
    if user.id != bot.user.id:
        await reaction.message.remove_reaction(reaction.message, reaction.emoji, user)
```

**Comment by Rapptz** [comment]
This is not a library issue.

The API has latency issues sometimes. There is also a shared bucket rate limit of 1 reaction request/0.25 seconds. 

I don't know what you expect me to do about it.

**Comment by jgayfer** [comment]
I understand the API limits the rate, but it seemed odd to me that other reactions are deleted immediately while stacked ones are not. However, thank you for the quick response, I'll try and come up with a work around.

**Comment by Rapptz** [comment]
The client could be slow at processing it, there could be a delay spike on your request, etc. There are a lot of things that could make it be slow. 

I rarely experience this and I paginate a lot.

**Comment by jgayfer** [comment]
For anyone else that might stumble across this, i managed to solve the problem by adding a `await asyncio.sleep(1)` before deleting the reaction. Not entirely sure what makes this work, but it solved my problem.
