### ISSUE TITLE
set_nickname not working:  TypeError: object Member can't be used in 'await' expression

### ISSUE THREAD

**Issue by BEPISMAN2** [Rapptz/discord.py#660]
So, I'm trying to implement a command in my bot that allows a user to change the bot's nickname with a command.  I've been using this function to go about this:  http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.change_nickname

However, whenever I use this command, I get the error ` TypeError: object Member can't be used in 'await' expression`.  This makes no sense, as _a Member object has to be passed to the function in the first place for it to work_.

Is this an oversight?  Or is it just incorrect usage?

Here is the complete code for the command.  It uses the commands extension.
```
	@commands.command(pass_context = True)
	async def setNick(self, ctx, *, nick : str):
		"""Nickname test"""
		botMember = await ctx.message.server.get_member(self.bot.user.id)
		await self.bot.change_nickname(botMember, nick)
```

**Comment by Rapptz** [comment]
`Server.get_member` is not a coroutine and thus cannot be awaited.
