### ISSUE TITLE
VoiceState

### ISSUE THREAD

**Issue by oriapp** [Rapptz/discord.py#6600]
### Summary

VoiceState has no data / support

### Reproduction Steps

Create a stage channel, and eval ctx.author.voice

### Expected Results

Return the channel ID, name, user limit, category id and etc

### Actual Results

None of them showing up

### Intents

default

### System Information

- Python v3.8.6-final
- discord.py v1.6.0-final
- aiohttp v3.6.0
- system info: Windows 10 10.0.19041

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by NCPlayz** [comment]
Stage voice channels have just been officially released. discord.py does not support them at the moment, however, which is why anything related to it will not work as intended.

**Comment by oriapp** [comment]
Not even going to send the channel id and or name?

**Comment by lgaan** [comment]
As has been said, they are not yet supported and so will not return data.
