### ISSUE TITLE
VoiceState does not print all the attributes (but they exist in the class)

### ISSUE THREAD

**Issue by ThisisDaan** [Rapptz/discord.py#6609]
### Summary

VoiceState __repr__ is missing attributes

### Reproduction Steps

when printing the class VoiceState to the console it shows the output of def __repr__(self): which does not contain deaf, self_video, afk

### Minimal Reproducible Code

```python
class DiscordClient(discord.Client):
    async def on_voice_state_update(self, member, before, after):
        print(after.deaf) # return True or False
        print(after) # returns a string of the class, but deaf is not in it.
```

### Expected Results

<VoiceState deaf=True self_video=False afk=False self_mute=True self_deaf=True self_stream=False channel=<VoiceChannel id=231388521112403968 name='AFK' position=31 bitrate=64000 user_limit=0 category_id=384067945812328459>>

### Actual Results

<VoiceState self_mute=True self_deaf=True self_stream=False channel=<VoiceChannel id=231388521112403968 name='AFK' position=31 bitrate=64000 user_limit=0 category_id=384067945812328459>>

### Intents

intents.voice_states = True

### System Information

- Python v3.7.0-final
- discord.py v1.6.0-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19041

### Checklist

I have searched the open issues for duplicates.
I have shown the entire traceback, if possible.
I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
Generally speaking, repr is just meant as a small peek into what the class attributes contain. It's not feasible to include everything (and most classes don't). So in the strictest sense, this isn't a bug. 

It could be added as a feature request, supposing it doesn't bloat it up but I won't consider it a bug if it doesn't.

**Comment by ThisisDaan** [comment]
> Generally speaking, repr is just meant as a small peek into what the class attributes contain. It's not feasible to include everything (and most classes don't). So in the strictest sense, this isn't a bug.
> 
> It could be added as a feature request, supposing it doesn't bloat it up but I won't consider it a bug if it doesn't.

Fair enough, something I didn't know.

As someone who didn't know this, I was confused why deaf and self_video wasn't getting printed and felt like someone forgot to update it.
