### ISSUE TITLE
Using bot.process_commands(message)

### ISSUE THREAD

**Issue by Crdguy** [Rapptz/discord.py#661]
So I've been using events and commands within my bot (namely Crdbot) and at the start, my commands didn't work. After adding bot.process_commands(message) to the ends of various bits of code, I got the commands to work- however, I have other (and larger) events that refuse to work, and they contain 'if' statements.

A sample of the code follows:

```
import discord
from discord.ext.commands import Bot
from discord.ext import commands

Client = discord.Client()
bot_prefix= ","
crdbot = commands.Bot(command_prefix=bot_prefix)


@crdbot.event
async def on_message(message):
    await crdbot.process_commands(message)
    if message.content.startswith('Ghetto'):
        await crdbot.send_message(message.channel, 'Like')
        await crdbot.send_message(message.channel, 'for')
        await crdbot.send_message(message.channel, 'a')
        import random
        r = random.randint(1,3)
        if r == 1:
            await crdbot.send_message(message.channel, 'free')
            await crdbot.send_message(message.channel, 'quantum')
            await crdbot.send_message(message.channel, 'processor')
            msg = await crdbot.send_message(message.channel, 'like?')
            res = await crdbot.wait_for_reaction(['\U0001F44D'])
            await crdbot.send_message(message.channel, '{0.user} liked! (Quantum processor)'.format(res))
        if r == 2:
           etc
        if r == 3:
           etc
        await crdbot.process_commands(message)
    await crdbot.process_commands(message)

@crdbot.event
async def on_message(message):
    if message.content.startswith('Crdguy'):
        await crdbot.send_message(message.channel, 'Lmao that scrub?')
    await crdbot.process_commands(message)

```

In this example any other '@crdbot.command's will work, but events containing if statements don't. It's probably something ridiculously obvious, but I'm relatively new to coding. There's nothing much about this around, so I'd appreciate if anyone could help with this. Thanks!

**Comment by datmellow** [comment]
your second on_message is overwriting your first one.

**Comment by Crdguy** [comment]
So I should combine the events?

**Comment by datmellow** [comment]
If you want multiple events, you will need to utilize "cogs"
as demonstrated here:
https://gist.github.com/leovoel/46cd89ed6a8f41fd09c5

**Comment by Crdguy** [comment]
Subroutines? Otherwise, I'm not quite sure what happened there, and I don't see events.

**Comment by datmellow** [comment]
you put the events you want to listen to, inside of cogs, that way you can have multiple "on_message"s.

to use events in cogs, all you do is:

`async def on_message(self, message):`

without the decorator.

Otherwise, the bot can only listen to 1 at a time, as in your code will only work for the 2nd `on_message` since that one is loaded last.

**Comment by Crdguy** [comment]
Ok, all my events now have been modified from ``async def on_message(message):`` to ``async def on_message(self, message):``, and I get errors saying positional argument "message" is missing.

**Comment by datmellow** [comment]
I should have specified, Cogs are classes. See the example I linked above to see the setup.

**Comment by Crdguy** [comment]
Apologies for my lack of knowledge, but I'm not entirely sure what a class is.

**Comment by zephyrkul** [comment]
I suggest Googling basic Python knowledge, then.

**Comment by Crdguy** [comment]
Yes, I have already done so.
