### ISSUE TITLE
Allow aliases to take sets

### ISSUE THREAD

**Issue by jay3332** [Rapptz/discord.py#6610]
### Summary

Allow command aliases to take sets rather than only lists or tuples.

### What is the feature request for?

discord.ext.commands

### The Problem

Currently, aliases can only take either tuples or lists.

### The Ideal Solution

Sets are faster than both tuples and lists, so unless order is heavily required when parsing aliases, support for sets should be allowed.

### The Current Solution

Using tuples or lists (which is not really a solution)

![image](https://user-images.githubusercontent.com/40323796/113429064-e7a26a80-93a5-11eb-8d3a-3aad9cf21e0c.png)

**Comment by Rapptz** [comment]
The underlying data type is a list. It's also just added to an internal dictionary so even that implementation detail doesn't matter.

I'm not sure what this is buying.
