### ISSUE TITLE
Adding check or error when trying to delete a community channel

### ISSUE THREAD

**Issue by DolphinGamerYT** [Rapptz/discord.py#6614]
### Summary

Users or bots cannot delete community channels, but there's no way of checking if the channel can be deleted

### What is the feature request for?

The core library

### The Problem

When a user or a bot tries to delete a community channel, a message pops up preventing you to delete the channel. The thing is, discord.py doesn't detect that, and when trying to delete a community channel, a HTTPException error pops up with the message: 
Command raised an exception: HTTPException: 400 Bad Request (error code: 50074): Cannot delete a channel required for community servers

### The Ideal Solution

Having a check to know if the channel can be deleted or not, or maybe (as mentioned here https://github.com/Rapptz/discord.py/issues/6418) get a type of channel (the issue is that discord doesn't define the channel as a community channel 😢)

### The Current Solution

There isn't any solution that I could think of.

**Comment by Rapptz** [comment]
You can check if a channel is equal to [`Guild.rules_channel`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Guild.rules_channel) or [`Guild.public_updates_channel`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Guild.public_updates_channel).
