### ISSUE TITLE
Embed Scheme is 'none'

### ISSUE THREAD

**Issue by jasonf7** [Rapptz/discord.py#6657]
### Summary

Sending embeds is broken for new discord version (1.6 -> 1.7.1)

### Reproduction Steps

My bot used to work before with version 1.6.
After upgrading to 1.7.1, all embeds fail to send with the same stack trace.

### Expected Results

The embed should be sent correctly.
Screenshot of the expected result
![image](https://user-images.githubusercontent.com/1820087/113766852-ed70b680-96eb-11eb-946c-c5577e13a3de.png)

### Actual Results

Fails with the following stacktrace
```
ERROR:asyncio:_ClientEventTask exception was never retrieved
future: <ClientEventTask state=finished event=on_command_error coro=<function on_command_error at 0x7fadc1af0c10> exception=HTTPException('400 Bad Request (error code: 50035): Invalid Form Body\nIn embed.url: Scheme "none" is not supported. Scheme must be one of (\'http\', \'https\').')>
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 337, in on_command_error
    await ctx.guild.get_channel(ADMIN_CHANNEL_ID).send(embed=embed)
  File "/app/.heroku/python/lib/python3.8/site-packages/discord/abc.py", line 1064, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "/app/.heroku/python/lib/python3.8/site-packages/discord/http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.url: Scheme "none" is not supported. Scheme must be one of ('http', 'https').
```

### Intents

members

### System Information

What works:
```
~ $ python -m discord -v
- Python v3.8.5-final
- discord.py v1.6.0-final
- aiohttp v3.7.4.post0
- system info: Linux 4.4.0-1086-aws #90-Ubuntu SMP Wed Feb 17 07:04:43 UTC 2021
```

What doesn't work:
```
~ $ python -m discord -v
- Python v3.8.5-final
- discord.py v1.7.1-final
- aiohttp v3.7.4.post0
- system info: Linux 4.4.0-1086-aws #90-Ubuntu SMP Wed Feb 17 07:04:43 UTC 2021
```

### Checklist

I have searched the open issues for duplicates.
I have shown the entire traceback, if possible.
I have removed my token from display, if visible.

**Comment by lgaan** [comment]
This is most probably not an issue with the library, rather your code.

However this is pretty much impossible to work out without reproduction steps and relevant code.

**Comment by jasonf7** [comment]
Ahh I think I see the problem, it might be with how I construct the embed.
```
embed = discord.Embed(title=title, description=description, url=url, color=0xd42d1f)
```
if I pass in `None` for url I'm guessing it breaks for 1.7.1 but not 1.6

Let me verify that now

**Comment by NCPlayz** [comment]
You're right. This was caused in 5a93e80.

**Comment by lgaan** [comment]
Ah, so it is an issue with the library.

My bad. However, it would be useful to have the reproduction steps in the future.

**Comment by jasonf7** [comment]
Thanks for the quick response! I just verified that is indeed the issue, so everything works now. Feel free to close the issue as you see fit.

Yes sorry I will add reproducible steps in the future!

One side effect is that now I see this "None" string printed if I don't pass in a URL on the latest version (1.7.1)
![image](https://user-images.githubusercontent.com/1820087/113769810-645b7e80-96ef-11eb-8290-2dada791ad48.png)

Is there a way I can get around this without reverting back to 1.6.0?

**Comment by Rapptz** [comment]
These methods were not documented to accept None and were documented to be implicitly casted to `str`. There was a bug originally that didn't do it at init time and I guess this caused an unfortunate bug to surface on your end.

I don't really consider it breaking since the documentation never mentioned it was okay to pass None.

**Comment by sergree** [comment]
Faced the same problem.

My old code:
```python3
def __construct_embed(title, description, url=None):
    embed = discord.Embed(
            title=title,
            color=config.embed_color,
            description=description,
            url=url
        )
    return embed
```

Solution:

```python3
def __construct_embed(title, description, url=discord.embeds.EmptyEmbed):
    embed = discord.Embed(
            title=title,
            color=config.embed_color,
            description=description,
            url=url
        )
    return embed
```

The code worked perfectly for a few years, don't tell me it's not a library problem. Thanks.
