### ISSUE TITLE
Support the bool(x) operation or define the __bool__ special method for discord.Embed

### ISSUE THREAD

**Issue by Flame442** [Rapptz/discord.py#6661]
### Summary

The current behavior of `bool(embed)` is unintuitive, the `__bool__` method should be explicitly defined for `discord.Embed`

### What is the feature request for?

The core library

### The Problem

The class `discord.Embed` does not have a `__bool__` special method, however it defines the `__len__` special method. This means that the result of `__len__` is used for determining the boolean value of a `discord.Embed` object. The `__len__` method is defined as a helpful tool to check the size of an embed, however by defining it the boolean operation on an embed outputs unexpected results.

### The Ideal Solution

I suggest that either the `__bool__` method should be explicitly defined, or the documentation for `discord.Embed` should include the `bool(x)` operation, explaining this behavior.

If the `__bool__` method is implemented, it could either always return `True` for a `discord.Embed` object, or explicitly use the value returned from `__len__` to keep current behavior intact. The former option would potentially be breaking for somebody, however this operation is not currently supported, so I do not know if it would be considered a breaking change under dpy version control.

### The Current Solution

The `bool(x)` operation is currently not a supported operation on a `discord.Embed` object.

**Comment by Vexs** [comment]
I'm curious what the usecase for this is

**Comment by Flame442** [comment]
The original issue isn't super important, but it was a piece of code roughly like this having unexpected behavior:
```py
def get_embed(...):
  """Returns either a discord.Embed, or False if one could not be created."""
  if cond:
    return False
  else:
    return discord.Embed(...)
    
# In a command
embed = get_embed(...)
if not embed:
  await ctx.send("Nope!")
await ctx.send(embed=embed)
```
This specific code can be fixed by checking `if embed is False` instead, however the point is that an embed with no text (only images) would cause the `not embed` to succeed, which in my opinion is unexpected behavior. Documenting this behavior or changing it would help with a situation like this.

**Comment by Snaptraks** [comment]
How about, in this specific case, return `None` if no embed can be created, and then check `if embed is None` instead? It's still unclear how a cast to bool would be useful/relevant

**Comment by Flame442** [comment]
As I said, the specific piece of code is not the concern here, the behavior is. I just think that this operation should be supported and documented, and maybe explicitly defined in the code. My title isn't super clear for that, I'll change it now to be more accurate.

**Comment by tylergibbs2** [comment]
A `__bool__` implementation on Embed would be ambiguous and unintuitive. What would you consider to be a `False` Embed? Different people might draw different conclusions, leading to unexpected behavior.

What you should be doing here is changing your if-statement. Rather than attempting to false-y compare an Embed, you should be checking `embed is False`, or `embed is None`.

**Comment by Rapptz** [comment]
I think if I have a bool method it should probably just check if any of the fields are active and not empty.
