### ISSUE TITLE
Update discord.Webhook.edit_message

### ISSUE THREAD

**Issue by Krangelj** [Rapptz/discord.py#6662]
### Summary

Allowing to edit files in webhook messages.

### What is the feature request for?

The core library

### The Problem

The library doesn't allow to edit files of existing webhook messages by itself, taking into account that there has been API changes towards the way that webhook edit request have changed.

### The Ideal Solution

It'd possibly be

```py
# webhook: discord.Webhook
# file: discord.File
# files: list[discord.File]

await webhook.edit_message(message_id, file=file)
await webhook.edit_message(message_id, files=files)
```

### The Current Solution

Currently can't be done within discord.py, the possible solution approach would be doing a manual http request to discord's API.

It has been brought to my attention that the discord API now allows webhooks to edit the contained files of a message if this is the outcome of a webhook (or a slash command webhook).

As result, It'd be good allowing this feature for webhook messages.

**Comment by Rapptz** [comment]
This is planned for v2.0.
