### ISSUE TITLE
Copy-pasted mention is not working

### ISSUE THREAD

**Issue by katomasa6969** [Rapptz/discord.py#6663]
### Summary

when_mentioned is not detected when mention to bot with copy-paste

### Reproduction Steps

- Run any command with mention
- Run same command again by copy-pasted former command

### Expected Results

First one (direct input)
@bot help
<help text>

Second one (copy-pasted)
@bot help
<help text>

### Actual Results

First one (direct input)
@bot help
<help text>

Second one (copy-pasted)
@bot help

### Intents

None

### System Information

- Python v3.9.3-final
- discord.py v1.7.0-final
- aiohttp v3.7.4.post0
- system info: Linux 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020

### Checklist

I have searched the open issues for duplicates.
I have shown the entire traceback, if possible.
I have removed my token from display, if visible.

I found a prefix of copy-pasted mention is "&"
> <@&{bot_id}> help
> <@!{bot_id}> help

And function when_mentioned is below.
Only "!" is there, so is it cause this bug?
```python
def when_mentioned(bot, msg):
    """A callable that implements a command prefix equivalent to being mentioned.

    These are meant to be passed into the :attr:`.Bot.command_prefix` attribute.
    """
    return [bot.user.mention + ' ', '<@!%s> ' % bot.user.id]
```

**Comment by Rapptz** [comment]
You're doing a role mention rather than a user mention.

**Comment by nnnarvaez** [comment]
5 years later this is still a problem. 

I type: `@nameofthebot something`
message.mentions gets populated.

I copy paste `@nameofthebot something`
message.mentions returns and empty list and 

```
log.info(f"user={message.raw_mentions} user name={client.user.name} user id={client.user.id} user mention={client.user.mention} mentions={message.mentions} content={message.content}")

[INFO] user=[] user name=nameofthebotuser id=3719609269890xxxxx user mention=<@3719609269890xxxxx> mentions=[] content=<@&15121984525141xxxxx> something
```

**Comment by Soheab** [comment]
> 5 years later this is still a problem. 
> 
> I type: `@nameofthebot something`
> message.mentions gets populated.
> 
> I copy paste `@nameofthebot something`
> message.mentions returns and empty list and 
> 
> ```
> log.info(f"user={message.raw_mentions} user name={client.user.name} user id={client.user.id} user mention={client.user.mention} mentions={message.mentions} content={message.content}")
> 
> [INFO] user=[] user name=nameofthebotuser id=3719609269890xxxxx user mention=<@3719609269890xxxxx> mentions=[] content=<@&15121984525141xxxxx> something
> ```

That's again a role mention, notice the content being `<`->@&<--`ID>`. This isn't something discord.py can control and you should take it up with Discord.
