### ISSUE TITLE
discord.Guild.change_voice_state() should return the new VoiceState

### ISSUE THREAD

**Issue by realSnosh** [Rapptz/discord.py#6681]
### Summary

discord.Guild.change_voice_state() should return the new VoiceState

### What is the feature request for?

The core library

### The Problem

"ctx.guild.me.voice" takes too long to update a variable after using the change_voice_state function. If change_voice_state would return the new VoiceState, I could put that directly into my variable (just like it works with channel.connect()) My English is bad so further questions regarding my problem would not be a problem.

### The Ideal Solution

If discord.Guild.change_voice_state() would return the new VoiceState of the Guild.

### The Current Solution

I am currently using ctx.guild.me.voice.

As i said, my English is bad so further questions regarding my problem would not be a problem.

**Comment by Rapptz** [comment]
This is a WebSocket operation so it's not really possible to do this since it doesn't actually return anything.
