### ISSUE TITLE
on_<object>_delete/remove() could be called with a new parameter

### ISSUE THREAD

**Issue by SUPERMECHM500** [Rapptz/discord.py#6685]
### Summary

Add a parameter for on_<object>_delete/remove() that contains the person who deleted the object

### What is the feature request for?

The core library

### The Problem

This feature will make it easier to access the user who deleted the object. 

### The Ideal Solution

Add `user` to on_<object>_delete/remove() parameters. It will make the user who deleted the object more accessible.
`user` _could_ be replaced with a special AuditLogEntry if it fits better with more information. `user` is User if it is in a DM channel.

### The Current Solution

Currently, users have to access the Audit log of the server when finding the perpetrator of a delete action.

**Comment by SUPERMECHM500** [comment]
`on_<object>_delete/remove()`*, markdown removed the word "object"

**Comment by Rapptz** [comment]
Discord does not provide this information.
