### ISSUE TITLE
ctx getting treated as an arg

### ISSUE THREAD

**Issue by yumm-b612** [Rapptz/discord.py#6697]
### Summary

ctx getting treated as an arg in a cog sub-command

### Reproduction Steps

**1.** make an async function in a cog
**2.** make 3 `@commands.group()`
**3.** make sub-commands using each group and in each sub-command pass in ctx
**4.** run the bot and run the sub-command

### Minimal Reproducible Code

```python
import discord
from discord.ext import commands
moji = commands.Bot(
    command_prefix='!',
    case_insensitive=True)
class yum(commands.Cog):
    def __init__(self, moji):
        self.moji = moji

    @commands.group(invoke_without_command=True, hidden=True)
    async def test1(self, ctx):
        await ctx.send('hewwo')
    @test1.command(name='error', hidden=True)
    async def _error(self, ctx):
        await ctx.send('hewwo1')

    @commands.group(invoke_without_command=True, hidden=True)
    async def test2(self, ctx):
        await ctx.send('hewwo')
    @test2.command(name='error', hidden=True)
    async def _error(self, ctx):
        await ctx.send('hewwo2')

    @commands.group(invoke_without_command=True, hidden=True)
    async def test3(self, ctx):
        await ctx.send('hewwo')
    @test3.command(name='error', hidden=True)
    async def _error(self, ctx):
        await ctx.send('hewwo3')
moji.add_cog(yum(moji))
moji.run(token)
```

### Expected Results

the bot will send **hewwo3**

### Actual Results

Ignoring exception in command test1 all:
Traceback (most recent call last):
  File "/home/kshly/.local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "/home/kshly/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 1340, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/kshly/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 856, in invoke
    await self.prepare(ctx)
  File "/home/kshly/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 790, in prepare
    await self._parse_arguments(ctx)
  File "/home/kshly/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 697, in _parse_arguments
    transformed = await self.transform(ctx, param)
  File "/home/kshly/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 542, in transform
    raise MissingRequiredArgument(param)
discord.ext.commands.errors.MissingRequiredArgument: ctx is a required argument that is missing.

### Intents

all

### System Information

- Python v3.9.2-final
- discord.py v1.6.0-final
- aiohttp v3.7.3
- system info: Linux 5.11.12-arch1-1 #1 SMP PREEMPT Wed, 07 Apr 2021 21:48:28 +0000

### Checklist

I have searched the open issues for duplicates.
I have shown the entire traceback, if possible.
I have removed my token from display, if visible.

### Additional Context

am yum :yum

**Comment by Rapptz** [comment]
You're shadowing (there are two functions with the same name). This overwrites one with another.

**Comment by yumm-b612** [comment]
> You're shadowing (there are two functions with the same name). This overwrites one with another.

ooh, thanks :yum:
