### ISSUE TITLE
Repeated calls of __eq__ are blocking the event loop

### ISSUE THREAD

**Issue by EEKIM10** [Rapptz/discord.py#6700]
### Summary

Whenever there is an event (called by state) that removes messages from the cache (namely bulk_message_delete), it blocks the loop from between 10 and 240 seconds.

### Reproduction Steps

For context, my bot is in ~900 servers, with the message cache at 300k, and getting approximately 2000 messages per minute.

1. Fire up an instance of AutoShardedBot with the message cap at 300k
2. enable logging
3. fill the message cache up
4. start purging
5. result

### Minimal Reproducible Code

```python
from discord.ext import commands


class Bot(commands.AutoShardedBot):
    ...  # all that I do here is write on_ready and load extensions in __init__


intents = discord.Intents(
    guilds=True,
    members=True,
    messages=True,
    reactions=True
)

bot = Bot(
    command_prefix="!",
    case_insensitive=True,
    allowed_mentions=discord.AllowedMentions(everyone=False, roles=True, users=True),
    status=discord.Status.dnd,
    intents=intents,
    max_messages=command_arguments.max_messages,
)

...

bot.run(...)
```

### Expected Results

The library doesn't block the loop with \_\_eq\_\_ calls, and the bot continues to function normally

### Actual Results

Logs: https://paste.pythondiscord.com/puqasapeji.py
Full logs: https://haste.clicksminuteper.net/kocufihube.py

The bot repeatedly goes offline during these blocks, and from what I can tell, there's nothing high level that I can do to reduce the impact of this

And before you ask, reducing the message cache size is not an option - we get so many messages per minute that lower cache sizes fill up far too fast and cause wait_fors to break.

### Intents

As shown in the code example, just guild, member, message and reactions

### System Information

```sh
pi@yummy ~/D/YourApps-v3> venv/bin/python3.9 -m discord -v                                                                                                                                          master
- Python v3.9.0-final
- discord.py v1.6.0-final
- aiohttp v3.7.4.post0
- system info: Linux 5.10.17-v8+ #1403 SMP PREEMPT Mon Feb 22 11:37:54 GMT 2021
```

### Checklist

I have searched the open issues for duplicates.
I have shown the entire traceback, if possible.
I have removed my token from display, if visible.

### Additional Context

From the tracebacks I've seen, it appears to be an issue within the state.py file.

**Comment by mikeshardmind** [comment]
This isn't an issue with the library.

You're causing the library to do a lot more work on each event touching the message cache by increasing the cache by a factor of 60 on what appears to be a pi.

You've stated you can't lower the cache size due to `wait_for`, but you don't need messages to be cached to wait for any events, use the raw events if this is a concern. You'd have to be waiting nearly about hour based on your cache size and rate stated before this comes into play anyhow, but this isn't a reason to oversize the cache like this.

**Comment by apple502j** [comment]
`__eq__` itself should not block.

Events that are included in the log are `message_update` and `message_delete_bulk`, both of which will perform iterations on the whole message cache:

- `message_update` calls `_get_message` which is implemented using `utils.find`. Same goes for `message_delete`, `message_reaction_add`, `message_reaction_remove_all`, `message_reaction_remove`, and `message_reaction_remove_emoji`.
- `message_delete_bulk` also loops over the whole message cache.
- `message_delete` and `message_delete_bulk` calls `deque._remove`  which (probably) also iterates, although not usually on the whole cache.

This can be fixed if message cache is a dict. (Dicts can't deque, so we need to implement it ourselves)

**Comment by EEKIM10** [comment]
> This isn't an issue with the library.
> 
> You're causing the library to do a lot more work on each event touching the message cache by increasing the cache by a factor of 60 on what appears to be a pi.
> 
> You've stated you can't lower the cache size due to `wait_for`, but you don't need messages to be cached to wait for any events, use the raw events if this is a concern. You'd have to be waiting nearly about hour based on your cache size and rate stated before this comes into play anyhow, but this isn't a reason to oversize the cache like this.

I'm aware that I can rewrite my WFs to use the raw events, however that is a lot of work and would require rewriting a lot of my checks and whatnot, which would make the bot harder to maintain. I'll do that if necessary, however I'd prefer to see if there's a way the message cache could be optimized to allow for a cache of this size without issues.

Also, I'm running it on my pi temporarily. It still does this on my dedicated server, just to a far lesser extent.

> `__eq__` itself should not block.
> 
> Events that are included in the log are `message_update` and `message_delete_bulk`, both of which will perform iterations on the whole message cache:
> 
>     * `message_update` calls `_get_message` which is implemented using `utils.find`. Same goes for `message_delete`, `message_reaction_add`, `message_reaction_remove_all`, `message_reaction_remove`, and `message_reaction_remove_emoji`.
> 
>     * `message_delete_bulk` also loops over the whole message cache.
> 
>     * `message_delete` and `message_delete_bulk` calls `deque._remove`  which (probably) also iterates, although not usually on the whole cache.
> 
> 
> This can be fixed if message cache is a dict. (Dicts can't deque, so we need to implement it ourselves)

I assume changing the message cache to a dictionary would be quite the challenge with the way the library is structured? I mean I could give it a shot with a local clone, but that feels like it would be too much work to implement library-wide and would benefit only a few users.


Is there a way to manually push messages out of the cache? I assume there's something in state you could play with, and maybe remove messages that are of a certain age, however I'm not sure how simple that'd be.

**Comment by apple502j** [comment]
Message cache is a deque; it's a list with a constant size (300k for you) - the problem is not about old messages (they're automatically removed, that's why you need big cache right?) the size matters. no matter how young the cached messages are, unless the cache is relatively small, it blocks.

It is possible to switch this to OrderedDict, but then we need to implement deque ourselves.
