### ISSUE TITLE
Youtube-dl - The specified session has been invalidated for some reason

### ISSUE THREAD

**Issue by ghost** [Rapptz/discord.py#671]
`[tls @ 0xac5820] Error in the pull function.`
`[matroska,webm @ 0xae10c0] Read error`
`[tls @ 0xac5820] The specified session has been invalidated for some reason.`
`    Last message repeated 1 times`

Someone can help me?

**Comment by MysterialPy** [comment]
I see you were already in the discord channel, please next time if you get kicked for being invisible, wait the 5 minutes and ask there. 

As for this error, it probably means that your URL has expired in ytdl (Youtube_dl). Downloading the song for playback will solve this, or only getting the URL when the song is to be played.

It's either that or your internet connection is poor.

**Comment by s0hvaperuna** [comment]
https://github.com/Rapptz/discord.py/issues/315
Already answered
