### ISSUE TITLE
Replying to embed fails to mention author when mention_author=True

### ISSUE THREAD

**Issue by cyrus01337** [Rapptz/discord.py#6710]
### Summary

When replying with an embed and setting `mention_author=True`, the author is not mentioned.

### Reproduction Steps

Reply with only the `embed=` and `mention_author=` kwargs appropriately filled.

### Minimal Reproducible Code

```python
embed = discord.Embed(title="title", description="description")
await ctx.reply(embed=embed, mention_author=True)
```

### Expected Results

For the reply to mention the author of the command.

### Actual Results

The reply did not mention the author of the command.

### Intents

`discord.Intents.all()`

### System Information

- Python v3.9.4-final
- discord.py v1.7.1-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19041

### Checklist

I have searched the open issues for duplicates.
I have shown the entire traceback, if possible.
I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
I did this request manually without the library and managed to reproduce the behaviour so I think this is an upstream bug on Discord's end.

**Comment by cyrus01337** [comment]
Noted, hopefully this will fix itself without any library changes.

**Comment by Rapptz** [comment]
I've been told by the developers this has been fixed and will be in the next API deploy.
