### ISSUE TITLE
Editing a message takes about 30 seconds, consistently, on multiple networks and machines.

### ISSUE THREAD

**Issue by GreenCobalt** [Rapptz/discord.py#6712]
### Summary

Editing a message takes about 30 seconds, consistently, on multiple networks and machines.

### Reproduction Steps

send message
on reaction, edit message

### Minimal Reproducible Code

```python
await reaction.message.edit(content="fdasfdwas")
```

### Expected Results

The message gets edited without a significant delay (> 5 seconds)

### Actual Results

Takes ~ 27 seconds to edit the message.

### Intents

members

### System Information

- Python v3.9.4-final
- discord.py v1.6.0-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19041

### Checklist

I have searched the open issues for duplicates.
I have shown the entire traceback, if possible.
I have removed my token from display, if visible.

### Additional Context

the entire function for the on reaction executes instantly. (under 500ms) I have 1g/1g internet, wired to my PC. other commands and stuff are very fast.

**Comment by SebbyLaw** [comment]
Can't reproduce this. Set up [logging](https://discordpy.readthedocs.io/en/latest/logging.html#logging-setup) and make sure you're not getting ratelimited.

**Comment by GreenCobalt** [comment]
Tried again today and it seems to be mostly better. Wasn't getting ratelimited (logging would say that right?) so IDK what happened.
