### ISSUE TITLE
Add User Connection Object

### ISSUE THREAD

**Issue by callFEELD** [Rapptz/discord.py#674]
Pleas add the user connection object to get informations about third party website's/applications like YouTube or Steam.
https://discordapp.com/developers/docs/resources/user#connection-object

Maybe there is a way to get these data in this libary but I didn't found it.

**Comment by datmellow** [comment]
This endpoint is blocked for bot accounts by Discord developers. This is not related to the lib, as no lib has the power to get this information due to Discord's policy.
