### ISSUE TITLE
Add note about store_true/false-type flags not being supported

### ISSUE THREAD

**Issue by Sonic4999** [Rapptz/discord.py#6761]
### Summary

Add a note about store_true/false-type flags not being supported with the new flag converter

### What is the feature request for?

The documentation

### The Problem

In recent commits, flags have been added to the library. I won't get too much into detail here, but, in a way, these replace an old extension ([ext.flags](https://github.com/XuaTheGrate/Flag-Parsing)) that has been deprecated.

Suggesting many people used this extension, and the extension author has said that they would delete the extension once an official implementation has been made, I hope it is not a jump to conclude that many people will think of this new flag system to effectively replace the old one, and would implement all of the features the old one had.

This is not exactly true, however. That old extension, as discussed by Danny himself, used a format more similar to POSIX flags. And with POSIX flags came the idea of store_true/false, where the simple appearance of a flag without any value would automatically set the flag to something.

However, there is no equivalent with the new flags system that has been introduced, and talks in the Discord server have revealed that there are no plans to add anything like it. Some users, when 2.0 releases and the final version of flags is revealed to the public, may complain about the change and ask about this very problem, among other things.

### The Ideal Solution

A simple note/warning telling any would-be bot developer that flags would not be able to perform anything like store_true/false, and to simply use a flag with a boolean value instead and make the user specify the value they wish.

### The Current Solution

N/A

### Additional Context

Yeah, I probably could have created a PR, but I'm honestly unsure if such a warning should include more than what I've suggested (like maybe go into detail about how flags isn't POSIX flag handling in general? You decide). And I'm just not the best at wording things in general (I probably could have shortened this issue a lot, for example).

**Comment by Rapptz** [comment]
I'm not sure where in the documentation the implication of it being a command line parser comes from. I guess maybe it's the PosixLike flag example which I might remove.

**Comment by Sonic4999** [comment]
I think that, the fact that it's replacing ext.flags, and just the general idea of flags (at least, from a developer point of view) kind of give that impression. Might mean a renaming is in order, but who knows.

**Comment by Rapptz** [comment]
ext.flags was never an official library nor mentioned in any capacity in the documentation. The command line arguments parsing library is called argparse, not really related to flags at all. Though it calls "arguments" flags in the documentation a few times.

I'm not sure what to rename it to. I definitely don't want people to get the impression that this has anything to do with CLIs. I'm guessing that this is mostly a losing battle though so just a note saying that it's not using POSIX style command line argument syntax is enough.
