### ISSUE TITLE
get_relationship is deprecated

### ISSUE THREAD

**Issue by godnolyn** [Rapptz/discord.py#6768]
### Summary

get_relationship bug?

### Reproduction Steps

anything involving get_relationship sends "/usr/local/lib/python3.9/dist-packages/discord/gateway.py:509: DeprecationWarning: get_relationship is deprecated.  func(data)"

### Expected Results

no error

### Actual Results

"/usr/local/lib/python3.9/dist-packages/discord/gateway.py:509: DeprecationWarning: get_relationship is deprecated.  func(data)"

### Intents

NA

### System Information

- Python v3.9.4-final
- discord.py v1.7.1-final
- aiohttp v3.7.4
- system info: Linux 4.15.0-132-generic #136-Ubuntu SMP Tue Jan 12 14:58:42 UTC 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by lgaan** [comment]
As stated in the warning this method is deprecated. 

As of version 1.7, all user related endpoints are deprecated and awaiting their subsequent removal in version 2.0.

This is not a library bug.

**Comment by Rapptz** [comment]
These functions are deprecated and slated for removal.
