### ISSUE TITLE
[Enhancement] [Documentation] Specify if an attribute is only available for selfbots.

### ISSUE THREAD

**Issue by spaceneb** [Rapptz/discord.py#6785]
### Summary

Instead of having no context for discord.ActivityType.custom specify that a selfbot can set this as it's status.

### What is the feature request for?

The documentation

### The Problem

discord.ActivityType.custom and other things like discord.Activity.assets are only available to selfbots.

### The Ideal Solution

Specify that something isn't available for regular bots.

**Comment by Zomatree** [comment]
Discord.py no longer supports anything to do with self-bots and are being removed in the next release, nothing new to do with self-bots will be added.

**Comment by pikaninja** [comment]
Additionally, some of the things you mentioned can be read, such as with `member.activity`, which can return the custom type
