### ISSUE TITLE
Errors with extended ASCII characters

### ISSUE THREAD

**Issue by ParzivalWolfram** [Rapptz/discord.py#679]
I'm trying to pass an extended ASCII character to a command and I get this. This happens with ALL commands.
`Exception in command 'ascii'
Traceback (most recent call last):
  File "lib\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\sethb\Red-DiscordBot\cogs\ascii.py", line 18, in _ascii
    if msg[0] == " ":
IndexError: string index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib\discord\ext\commands\bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "lib\discord\ext\commands\core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "lib\discord\ext\commands\core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: IndexError: string index out of range`

**Comment by Gorialis** [comment]
We're going to need some code for context on this one.

**Comment by khazhyk** [comment]
This means that "msg" is of length zero and thus msg[0] does not exist.

Here are some resources for familiarizing yourself with python.

https://automatetheboringstuff.com/ (for complete beginners to programming)
https://learnxinyminutes.com/docs/python3/ (for people who know programming already)
https://docs.python.org/3.5/tutorial/ (official tutorial)
http://python.swaroopch.com/ (useful book)
see also: http://www.codeabbey.com/ (exercises for beginners)

**Comment by ParzivalWolfram** [comment]
I don't see why this was closed. I am passing characters into this.
Lemme give you the example cog.
`# -*- coding: utf-8 -*-
from discord.ext import commands
from cogs.utils.chat_formatting import box

try:
    from pyfiglet import figlet_format
except:
    figlet_format = None


class Ascii(object):
    def __init__(self, bot):
        self.bot = bot

    @commands.command(name="ascii")
    async def _ascii(self, *, text):
        msg = str(figlet_format(text, font='cybermedium'))
        error = figlet_format('LOL, that\'s a bit too long.', font='cybermedium')
        if len(msg) > 2000:
            await self.bot.say(box(error))
        else:
            await self.bot.say(box(msg))


def setup(bot):
    if figlet_format is None:
        raise NameError("You need to run `pip3 install pyfiglet`")
    n = Ascii(bot)
    bot.add_cog(n)
`The problem seems to be with any characters that AREN'T normal text. Like "±" or "⌡".
