### ISSUE TITLE
Inserting a empty url argument in discord.Streaming doesn't report a exception

### ISSUE THREAD

**Issue by EnPeignoir** [Rapptz/discord.py#6796]
### Summary

Inserting a empty url argument in discord.Streaming doesn't report a exception

### Reproduction Steps

- Run the code
- Observe that the bot status hasn't changed
- Observe that no exception has being reported

### Minimal Reproducible Code

```python
@bot.command()
@bot.is_owner()
async def status(ctx, *, status):
    await bot.change_presence(activity=discord.Streaming(name=str(status), type='Twitch', url=''))
```

### Expected Results

discord.Streaming url argument is mandatory, this case should raise an exception.

### Actual Results

No exceptions were raised and the programme acted as if everything was normal.

### Intents

none

### System Information

Python v3.9.4-final
discord.py v1.7.1-final
aiohttp v3.7.4.post0
system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

it's my first time i'm reporting a bug, sorry if it's not a good bug to report.

**Comment by Rapptz** [comment]
There's no validation on purpose since these objects are created on a hot loop.
