### ISSUE TITLE
API v9

### ISSUE THREAD

**Issue by cheesycod** [Rapptz/discord.py#6817]
### Summary

Add API v9 support

### What is the feature request for?

The core library

### The Problem

See https://github.com/discord/discord-api-docs/pull/2855. We should support api v9

### The Ideal Solution

Support API v9 in 2.0.0

### The Current Solution

None

### Additional Context

None

**Comment by Rapptz** [comment]
API v9 has been in development in the `feature/threads` branch for the past few weeks.

**Comment by Rapptz** [comment]
Merged into master.
