### ISSUE TITLE
Ratelimit handling

### ISSUE THREAD

**Issue by Nimboss2411** [Rapptz/discord.py#6819]
### Summary

Two types of ratelimit handling

### What is the feature request for?

The core library

### The Problem

Sometimes when I get ratelimited, my bot just stops and waits out the ratelimit.
Which is fine of course, but sometimes I don't want that to happen.
Sometimes I want an exception to be thrown when I get ratelimited, so I can handle it and tell the user that "Hey, I'm getting ratelimited, try after sometime"

### The Ideal Solution

In the bot variable params, add something like a ratelimit-type selector:
Something like:
bot = commands.Bot(..., ratelimit_exceptions = True/False)
or
client = discord.Client(..., ratelimit_exceptions = True/False)

Of course if ratelimit exceptions are not enabled then the normal ratelimit handling comes into place, where it waits the ratelimit out.

### The Current Solution

Cooldowns would be the closest thing, but they tend to get annoying in normal use.

**Comment by Rapptz** [comment]
There isn't going to be an option to turn off the rate limit handling since that'll get your account banned.
