### ISSUE TITLE
Add the user who made the action (ban, unban, webhook update) in bots event

### ISSUE THREAD

**Issue by EnPeignoir** [Rapptz/discord.py#6830]
### Summary

Add the user who made the action (ban, unban, webhook update) in bots event

### What is the feature request for?

The core library

### The Problem

For example with the event @on_member_ban, we can get the user who get banned, but we can't get the user who banned him, which is very limitating

### The Ideal Solution

I don't know how to do it so i can't get into details, but it would be cool if for each of these events we can get @on_member_ban(guild, user, banning_user) which would help a lot for developping some features

**Comment by Rapptz** [comment]
Discord does not provide this information.

**Comment by EnPeignoir** [comment]
Sad ;(

**Comment by scrazzz** [comment]
Get it from audit logs
https://discordpy.readthedocs.io/en/latest/api.html#discord.AuditLogAction

**Comment by EnPeignoir** [comment]
Alright, i'll do that, thanks you i didn't know this feature ! :)
