### ISSUE TITLE
White color not showing in Embeds

### ISSUE THREAD

**Issue by chao813** [Rapptz/discord.py#6833]
### Summary

White hex code (0xFFFFFF) shows black on the embed 

### Reproduction Steps

When you set the embed color to white (0xFFFFFF), it shows up as black on the discord app on PC/Mac but white on mobile. 

### Minimal Reproducible Code

```python
embed = discord.Embed(color=0xFFFFFF)
```

### Expected Results

Show white embed instead of black. 

### Actual Results

Black color was in the embed. 

### Intents

none

### System Information

- Python v3.9.4-final
- discord.py v1.7.1-final

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
Discord reserves pure black and pure white embeds for their own use to allow it to be theme friendly. It is out of the control of the library. You should use the next closest colour instead if this is undesirable.

**Comment by JDJGInc** [comment]
This is add a discord issue, not api issue, you need to go one less than the value specified if you want it to show up my friend.

**Comment by chao813** [comment]
Got it, thank you! @Rapptz  @JDJGInc
