### ISSUE TITLE
couldn't force ipv4

### ISSUE THREAD

**Issue by gabrielhbcs** [Rapptz/discord.py#685]
I couldn't find a way to "--force-ipv4" when I'm creating an ytdl player, I tried lot's of things but when I looked for it on YoutubeDL.py I couldn't find a term to force it on dict, is it possible to --force-ipv4?

my youtube-dl is really slow when I start downloading something, when I looked up using "youtube-dl --force-ipv4 url" worked really well, but when I tried it on my code I just couldn't
This was my last attempt:
`player[i] = await chVoice[i].create_ytdl_player(url,ytdl_options={"force_ipv4":True})`

ps.: I already tried to put the force as default config and it worked by cmd, not on my code tho

**Comment by khazhyk** [comment]
have you tried {"force-ipv4": True} ?

**Comment by khazhyk** [comment]
Looking at the source for --force-ipv4, you want to set {"source_address": "0.0.0.0"}, which is super intuitive

**Comment by gabrielhbcs** [comment]
sorry for asking, it's not that intuitive for me, but it worked quite well, thanks!

**Comment by khazhyk** [comment]
(It's not actually intuitive)

**Comment by gabrielhbcs** [comment]
thank you!
