### ISSUE TITLE
Add GuildChannelConverter

### ISSUE THREAD

**Issue by sudosnok** [Rapptz/discord.py#6856]
### Summary

Add a generic GuildChannelConverter for typehinting commands

### What is the feature request for?

discord.ext.commands

### The Problem

Currently when a user wants to target some channel with a typehint, the simplest route is very unweildy, `..., arg: Union[discord.TextChannel, discord.VoiceChannel, discord.StageChannel, discord.CategoryChannel], ...`

### The Ideal Solution

If GuildChannel gets modified to a mixin, it would make a converter and its related typings much simpler, down to `..., arg: discord.(abc.)GuildChannel, ...` to target some channel in a guild (or via global lookup in the case of a DM context)

### The Current Solution

N/A

### Additional Context

N/A

**Comment by sudosnok** [comment]
Added by #6864

**Comment by JDJGInc** [comment]
Someone plans on adding this anyway.
