### ISSUE TITLE
editing verification_level does not work

### ISSUE THREAD

**Issue by xSuky** [Rapptz/discord.py#6865]
### Summary

editing verification_level does not work

### Reproduction Steps

So as the title says, I have tried editing the verification level like this:
            await ctx.guild.edit(verification_level=high)

Unfortunately everytime I get that NameError: name 'high' is not defined.
If I try to put anything else besides "high" I get:
InvalidArgument: verification_level field must be of type VerificationLevel.

### Minimal Reproducible Code

```python
@commands.command()
    @commands.guild_only()
    @permissions.has_permissions(manage_guild=True)
    async def vhigh(self, ctx):
            await ctx.send("**Verification level set to high**")
            await ctx.guild.edit(verification_level=high)
```

### Expected Results

It should change the verification level to high

### Actual Results

Nothing.

### Intents

guilds=True, members=True, messages=True, reactions=True, presences=True

### System Information

- Python v3.9.4-final
- discord.py v1.7.2-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
The `high` variable doesn't exist. So you get a `NameError`. To use an enum you need to qualify it, e.g. `discord.VerificationLevel.high`. This is not a bug with the library.

It is recommended to learn Python before using the library, since it can have difficult concepts for the novice programmer.

**Comment by lgaan** [comment]
This is not a library bug, you need to either define `high` or just give a VerificationType to the kwarg.

In your case it seems you’re looking for `discord.VerificafionType.high`.
