### ISSUE TITLE
`status` is not documented properly as an attribute of Client

### ISSUE THREAD

**Issue by pyxiis** [Rapptz/discord.py#6866]
### Summary

Client.status is missing in certain places.

### What is the feature request for?

The documentation

### The Problem

`status` does not appear as an attribute of Client under the tl;dr attributes list, even though it should. It appears under the expanded parameters list (**status** (Optional[`Status`]) – A status to start your presence with upon logging on to Discord.) but it doesn't have its dedicated section either.

### The Ideal Solution

This is how it should look: https://i.imgur.com/DD26Hk8.jpg, https://i.imgur.com/VCRLiwW.jpg

### The Current Solution

This is how the documentation currently looks: https://i.imgur.com/AM9a0W6.jpg

### Additional Context

This also appears to be an issue for discord.ext.commands.Bot's documentation.

**Comment by sudosnok** [comment]
The `status` parameter, and by extension the `activity` parameter, is passed around internally to the ConnectionState object to tell discord what activity and status the client should display, its never set to an attribute of Client, so it shouldn't be in the attrbute table.
