### ISSUE TITLE
Guild object, got from fetch_guild, does return an empty guild.members list!

### ISSUE THREAD

**Issue by leonfroschauer** [Rapptz/discord.py#6878]
### Summary

Tried, to fetch a guild by the await client.fetch_guild(ID) method, got guild objekt, but the objekt does return for guild.members an empty list!

### Reproduction Steps

Code:
```python
import discord

client = discord.Client(intents=discord.Intents.all())


@client.event
async def on_ready():
    print(discord.__version__)
    await client.wait_until_ready()
    guild = await client.fetch_guild(836214357791997953)  # Fetch Guild
    print(guild.name)  # Print Guilds name
    print(type(guild))  # Print Type
    print(len(guild.members))  # Print Len of members
    print(guild.members)  # Print Members

    channel = await client.fetch_channel(836214358136324168)
    print(channel.guild.name)  # Print guilds name
    print(channel.guild.id)
    print(type(channel.guild))  # Print Type
    print(len(channel.guild.members))  # Print Len of members

client.run("TOKEN")
```
Output:
```
1.7.1
Leon_'s server
<class 'discord.guild.Guild'>
0
[]
Leon_'s server
836214357791997953
<class 'discord.guild.Guild'>
2
```
Summary:

Version: is 1.7.1
when I fetch the Guild with fetch_guild I get an Guild objekt, but this objekt does not return guild.members, when I fetch a channel of the guild, and try to get the member list over the channel.guild it works, properly ...

### Minimal Reproducible Code

```python
Code shown above

import discord

client = discord.Client(intents=discord.Intents.all())


@client.event
async def on_ready():
    print(discord.__version__)
    await client.wait_until_ready()
    guild = await client.fetch_guild(836214357791997953)  # Fetch Guild
    print(guild.name)  # Print Guilds name
    print(type(guild))  # Print Type
    print(len(guild.members))  # Print Len of members
    print(guild.members)  # Print Members

    channel = await client.fetch_channel(836214358136324168)
    print(channel.guild.name)  # Print guilds name
    print(channel.guild.id)
    print(type(channel.guild))  # Print Type
    print(len(channel.guild.members))  # Print Len of members

client.run("TOKEN")
```

### Expected Results

```
1.7.1
Leon_'s server
<class 'discord.guild.Guild'>
2
[]  # List with Members
Leon_'s server
836214357791997953
<class 'discord.guild.Guild'>
2
```

Get list of all members and count of members

### Actual Results

Got an empty list

### Intents

discord.Intents.all(), off course enabled in the developer portal!

### System Information

- Python v3.9.4-final
- discord.py v1.7.1-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Zomatree** [comment]
This is expected (and documented) behaviour, see the note on [Client.fetch_guild](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.fetch_guild), consider using [Client.get_guild](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.get_guild) instead if you want access to the mmebers.

**Comment by leonfroschauer** [comment]
👍 Thank you for the information. I find this a bit confusing to be honest, but thanks for the answer! I will close the issue!
