### ISSUE TITLE
Intermittent message.add_reaction() - 403 Forbidden (error code: 50013)

### ISSUE THREAD

**Issue by lexicalunit** [Rapptz/discord.py#6886]
### Summary

Sometimes my bot gets 403 errors when trying to add reactions to messages.

### Reproduction Steps

It comes up in my logs sometimes. I haven't been able to figure out why.

### Minimal Reproducible Code

```python
import discord


def bot_can_react(message: discord.Message) -> bool:
    if message.channel.type == discord.ChannelType.private:
        return True
    
    perms = message.channel.guild.me.permissions_in(message.channel)
    
    return (
        perms.read_message_history and 
        perms.read_messages and
        perms.add_reactions and
        perms.manage_messages
    )


class Bot(discord.Client):
    async def on_message(self, message: discord.Message) -> None:
        if bot_can_react(message):
            message.add_reaction("✅")
```

### Expected Results

The bot should react to messages with a ✅ emoji.

### Actual Results

99% of the time this seems to work fine. Sometimes I get the 403 error 🤷🏻‍♀️ 

```
May 09 14:09:53 app/web.1 [2021-05-09 21:09:53][spellbot.operations][ERROR] - warning: discord (guild 841042902037823498): could not react to message: 403 Forbidden (error code: 50013): Missing Permissions
May 09 14:09:53 app/web.1 Traceback (most recent call last):
May 09 14:09:53 app/web.1   File "/usr/local/lib/python3.9/site-packages/spellbot/operations.py", line 133, in safe_react_emoji
May 09 14:09:53 app/web.1     await message.channel.send(s("reaction_permissions_required"))
May 09 14:09:53 app/web.1   File "/usr/local/lib/python3.9/site-packages/discord/abc.py", line 1065, in send
May 09 14:09:53 app/web.1     data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
May 09 14:09:53 app/web.1   File "/usr/local/lib/python3.9/site-packages/discord/http.py", line 248, in request
May 09 14:09:53 app/web.1     raise Forbidden(r, data)
May 09 14:09:53 app/web.1 discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
```

### Intents

32511

### System Information

- Python v3.8.8-final
- discord.py v1.7.1-final
- aiohttp v3.7.4.post0
- system info: Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

My main question is if I have the `bot_can_react()` function implemented correctly here. If it's a private channel I just assume that I have the permissions because AFAIK there's no way to tell? At least, I dug through the documentation and I couldn't find a way.

Otherwise I use `message.channel.guild.me.permissions_in()` to ensure that I have all the following permissions:

- read-message-history
- read-messages
- add-reactions
- manage-messages

That should be good, right? Are there other permissions that I need to check here? Is there a way to check permissions for Direct Messages that I'm missing?

I just don't know why I am seeing 403 errors here. It seems like it shouldn't be possible.

**Comment by Rapptz** [comment]
Your bot is probably blocked by the user. The permissions needed to react are just Add Reactions, Read Messages, and Read Message History.

**Comment by lexicalunit** [comment]
@Rapptz Is there some way to know if I am blocked by the user before attempting the `add_reaction()` call? I am trying to reduce spurious API failures so that my bot doesn't get automatically flagged as a DDoS attempt and blocked by Cloudflare. I can of course catch the exception and drop it on the floor, but too many of these kinds of errors within a given time period will get my bot blocked for a few hours. This has become a problem as the bot has grown in popularity and this issue happens more and more often.

**Comment by Rapptz** [comment]
> Is there some way to know if I am blocked by the user before attempting the add_reaction() call?

Nope.

**Comment by lexicalunit** [comment]
Ty for the quick response. Sad that the Discord API apparently sucks so much tho.

**Comment by Rapptz** [comment]
Yeah when this was introduced we library developers were against 400s/403s counting as spam for this reason but the Discord developers thought we were over-exaggerating the issue.

**Comment by lexicalunit** [comment]
Beautiful. I'll file a ticket with Discord again and let them know. Maybe if enough people make enough noise 🤷🏻‍♀️
