### ISSUE TITLE
Channel permissions sync bug

### ISSUE THREAD

**Issue by atesteyimateste** [Rapptz/discord.py#6895]
### Summary

Channel creation with overwrites acts weird and doesnt work for the first user in a for loop.

### Reproduction Steps

1. Take message.mentions as user list.

2. Make the bot create a category with view_channel denied for @everyone and granted for users in message mentions

3. Make a `for user in message.mentios:` loop and try to create a private text channel for every user using overwrites as read_messages denied for @everyone and granted for only **that** user.

4.Check each channel's permissions.

### Minimal Reproducible Code

```python
import discord

async def test(message):
    category_overwrites = {
        message.guild.default_role: discord.PermissionOverwrite(view_channel=False),
    }

    private_channels_category = await message.guild.create_category_channel("Private Channels Category", overwrites=category_overwrites)   

    for user in message.mentions:    
        await private_channels_category.set_permissions(user, view_channel=True)  

        private_channel_overwrites = {
            message.guild.default_role: discord.PermissionOverwrite(read_messages=False),
            user: discord.PermissionOverwrite(read_messages=True),
        }             

        await message.guild.create_text_channel("🏡"+user.name, category=private_channels_category, overwrites=private_channel_overwrites)
```

### Expected Results

Every created text channel should have indepented permissions and only one of the users and bot should be able to see private channels.

### Actual Results

The permissions for channel of first person mentioned gets synced with category permissions.

### Intents

(members=True, guilds=True, guild_reactions=True, guild_messages=True)

### System Information

- Python v3.9.5-final
- discord.py v1.7.0-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19042

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I tried adding another user to the beginning of message.mentions list to check. Both the user I added manually and first person mentioned (the item that previously was at position 0 but got moved to position 1 when I added an user)'s channels got synced and didnt work.

**Comment by mikeshardmind** [comment]
Underlying methods on this are all supposed to not depend on the current state (and don't on the library side).

I have not attempted to replicate the issue yet.

Assuming accuracy on everything said here, there's a bug *somewhere*.

It doesn't appear to be an issue with the library based on information available to me at this time. This presents as a potential data race on Discord's end, but without reproducing it myself, I'd be unwilling to make that as a claim, and others reading this should not jump to that as the only option.

**Comment by atesteyimateste** [comment]
> Underlying methods on this are all supposed to not depend on the current state (and don't on the library side).
> 
> I have not attempted to replicate the issue yet.
> 
> Assuming accuracy on everything said here, there's a bug *somewhere*.
> 
> It doesn't appear to be an issue with the library based on information available to me at this time. This presents as a potential data race on Discord's end, but without reproducing it myself, I'd be unwilling to make that as a claim, and others reading this should not jump to that as the only option.

I have no idea what is wrong but anytime I try to do something with channel permissions, channels I didn't even do anything about get synced, random permissions switch to default value, basically everything just go crazy.

As a temporary fix, I added a second for loop under the buggy code to deny read messages permission of every user on the first channel but it affects performance really bad:/

**Comment by ToxicKidz** [comment]
This isn't a bug, you just overwrote `private_channel_overwrites` is every iteration of the for loop.

**Comment by atesteyimateste** [comment]
It doesn't happen anymore.
