### ISSUE TITLE
Discord PyPi Support for Python 3.9.x

### ISSUE THREAD

**Issue by Zeyecx** [Rapptz/discord.py#6901]
### Summary

Pythonn 3.9.x

### What is the feature request for?

The core library

### The Problem

The current Discord or Discord.ext libary is unfortunately only usable up to Python 3.8. Due to the rapid increase in Python development, Python 3.9 has been published for some time. It would be nice if we can use the Discord wrapper classes there as well. 

### The Ideal Solution

Ideally, we should be able to install and use the packages in the same way as before.

``` pip install discord```

### The Current Solution

Currently there is no alternative solution for the PIP installation.

**Comment by Rapptz** [comment]
discord.py works fine in 3.9

**Comment by Zeyecx** [comment]
![image](https://user-images.githubusercontent.com/15014849/118060380-f3b11d00-b392-11eb-81e0-149b507f26ad.png)
ok i didn't know that. The new version was not listed in the docs.
