### ISSUE TITLE
The arguments given by context is empty list

### ISSUE THREAD

**Issue by SamuelCHICHA** [Rapptz/discord.py#6914]
### Summary

When creating my own decorator to check if the user is giving the right number of arguments. The arguments (Context.args) returns an empty list.

### Reproduction Steps

[prefix][command] [arguments]

### Minimal Reproducible Code

```python
def has_correct_number_arguments(minimum=None, maximum=None):
    def predicate(ctx):
        print(type(ctx))
        print(ctx.args)
        if minimum is None:
            if maximum is None:
                return False
            else:
                return len(ctx.args) == maximum
        else:
            if maximum is None:
                return minimum <= len(ctx.args)
            else:
                return minimum <= len(ctx.args) <= maximum
    return commands.check(predicate)


@bot.command(
    name='create',
    brief="Create one or many auto-channel for the guild.",
    signature=f"{prefix}create [auto-channel(s)]",
    require_var_postional=True
)
@commands.bot_has_guild_permissions(
    manage_channels=True,
    manage_roles=True,
    move_members=True,
    read_message_history=True,
    add_reactions=True
)
@commands.has_permissions(administrator=True)
@has_correct_number_arguments(minimum=1)
async def create_auto_channel(ctx, *args: lower):
```

### Expected Results

The args attribute of the passed Context object should give me a non empty list.

### Actual Results

I have an empty list;

### Intents

Default

### System Information

- Python v3.9.3-final
- discord.py v1.7.1-final
- aiohttp v3.7.4.post0
- system info: Linux 5.10.30-1-MANJARO #1 SMP Wed Apr 14 08:07:27 UTC 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Zomatree** [comment]
This is expected behavior, arguments are parsed after the checks are ran so they will always be empty inside the check.

**Comment by SamuelCHICHA** [comment]
> This is expected behavior, arguments are parsed after the checks are ran so they will always be empty inside the check.

Thank you, I didn't know that. I didn't find any so far but is there another way to do what I am trying to do ? Thanks again !

**Comment by Gobot1234** [comment]
You could make a custom converter similar to commands.clean_content (in that it supports initialisation with arguments) and consume the rest of the ctx.view and then parse from there.
