### ISSUE TITLE
on_reaction_add on older message

### ISSUE THREAD

**Issue by PizzaRules668** [Rapptz/discord.py#6918]
### Summary

on_reaction_add on older message

### Reproduction Steps

Trying to use on_reaction_add but it does not run on messages that were made before the bot started.

### Minimal Reproducible Code

```python
@bot.event
async def on_reaction_add(user):
    print(user)

also tried
@bot.event
async def on_raw_reaction_add(*args):
    print(args)
```

### Expected Results

Should print my discord username

should print

### Actual Results

Nothing

printed ()

### Intents

reactions

### System Information

1.7.2-final

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I tried issue https://github.com/Rapptz/discord.py/issues/2229

**Comment by lgaan** [comment]
This is expected behaviour. The `on_raw_reaction_X` events are fired for all messages (even outside the cache); `on_reaction_X` is called for messages only within the cache.
