### ISSUE TITLE
Can't set bot status to "streaming"

### ISSUE THREAD

**Issue by GTG3000** [Rapptz/discord.py#692]
Tried
`await self.client.change_presence(game=discord.Game(name="Game", type=1))`
and
`await self.client.change_presence(game=discord.Game(name="Game", url="Any", type=1))`
Without any effect other than setting the status. Any ideas?

**Comment by Rapptz** [comment]
The url has to be a twitch url.

**Comment by GTG3000** [comment]
Suggest you add that to the docs. The current definition is unclear.

**Comment by Mazen001** [comment]
How to change the Discord Activity to `Streaming` Status?

**Comment by dragdev** [comment]
please ask that in the [discord server](https://discord.gg/r3sSKJJ)
