### ISSUE TITLE
Make message functions take a message type object

### ISSUE THREAD

**Issue by Nimboss2411** [Rapptz/discord.py#6920]
### Summary

Message functions taking a message type object and replicating everything of the message - content, attachments, embeds etc

### What is the feature request for?

The core library

### The Problem

If you want to send the same message as another message you have to manually parse out content, attachments and embeds, which is quite tedious

### The Ideal Solution

To be able to send a message type object, where on sending it replicates the content, attachments, embeds etc

Examples:
await ctx.send(message = message_type_object)
await member.send(message = message_type_object)

### The Current Solution

Manually parsing out content, attachments and embeds, which is quite tedious

### Additional Context

N/A

**Comment by Rapptz** [comment]
This is the type of niche use case that is better solved on your own. There's 3 attributes you can send so it isn't too much effort to do on your own. These aren't hard to extract or paste over. You can re-post attachments in essentially one line: `files = [await attachment.to_file() for attachment in message.attachments]`. So I don't think I'll work on this.
