### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED, Ubuntu, tried eveything

### ISSUE THREAD

**Issue by newperson1746** [Rapptz/discord.py#6934]
### Summary

Even with up to date certs, SSL certificate verify still fails.

### Reproduction Steps

Make any discord bot and run it, discord.py will use aiohttp and try to connect to discord.com:443, and get the error 

### Minimal Reproducible Code

```python
(any bot)
```

### Expected Results

It works

### Actual Results

SSL errors
`raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')]
`

### Intents

N/A

### System Information

```
- Python v3.8.5-final
- discord.py v1.7.2-final
- aiohttp v3.7.4.post0
- system info: Linux 5.11.0 #1 SMP Sat Feb 20 00:57:37 EST 2021

```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Ubuntu 20.04, have tried:
- adding cacert.pem manually extracting all certs from latest mozilla into /usr/local/share/ca-certificates and running update-ca-certificates
- installing latest certifi as root to overwrite preinstalled certifi from late 2019
- compiling my own python3.9 and creating venv with latest certifi

NOT macOS, so the "Install Certificates.command" thing doesn't apply

**Comment by Zomatree** [comment]
have you tried the solution from #5968?

**Comment by newperson1746** [comment]
Wow, it works! I really didn't check thoroughly enough. This needs to be a pinned answer! I thought the SSL global vars didn't affect aiohttp (long discussion on an issue i read), so never even thought of that! Thank you very much :D

**Comment by gelodefaultbrain** [comment]
mine doesn't work

**Comment by jeanlucdupont** [comment]
It works. Thank you!

**Comment by mjmartis** [comment]
Commenting here because it is one of the top Google results for discord.py cert errors.

I solved this by resetting my system time to be accurate. It was erroneously set to a time in the past after an unexpected reboot.

**Comment by eminiorderflow** [comment]
Didnt solve the issue for me

```
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)
```

**Comment by noviksv** [comment]
If the reason a corporate firewall certificate problem on WSL, take a look this answer
https://stackoverflow.com/questions/72167566/wsl-docker-curl-60-ssl-certificate-problem-unable-to-get-local-issuer-certi

**Comment by aryamaan-exe** [comment]
putting this out there for mac users

```
brew install python
/Applications/Python*/Install\ Certificates.command
```

copy-paste the whole thing
