### ISSUE TITLE
on_guild_role_update sends double updates when position is changed

### ISSUE THREAD

**Issue by MagicaFreak** [Rapptz/discord.py#6938]
### Summary

on_guild_role_update send double update, one with position and rest update and another with only rest update

### Reproduction Steps

Change the permission of a role and his position

### Minimal Reproducible Code

```python
@commands.Cog.listener()
async def on_guild_role_update(self, before, after):
    print(after.name)
    print(before.position != after.position, before.permission.value != after.permission.value)
```

### Expected Results

role_name
True, True

### Actual Results

role_name
True, True
role_name
False, True

### Intents

all

### System Information

Discord.py v1.7.2
Windows 10
Python 3.9

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
These events are pass-through from Discord. When a channel's position is updated usually many update events are dispatched for the subsequent channels being moved in transit.

**Comment by NoirPi** [comment]
But in this case it fires for the exact same role twice.

So is it Discord which sends multiple events for the same role or what?
