### ISSUE TITLE
How to take all messages of one members ?

### ISSUE THREAD

**Issue by LavaPower** [Rapptz/discord.py#694]
I want to get the number of messages who a members write.
How i can make that ?

**Comment by jorkermc** [comment]
try
`			counter = 0
			tmp = await client.send_message(message.channel, 'Calculating messages...')
			async for log in client.logs_from(message.channel, limit=100):
				if log.author == message.author:
					counter += 1`

**Comment by NotSoSuper** [comment]
Wrong place to ask, join the discord server in the readme.

**Comment by mgardne8** [comment]
Joker is correct in using logs_from, look at the example in the documentation for more info:
http://discordpy.readthedocs.io/en/async/api.html?highlight=Logs#discord.Client.logs_from

**Comment by LavaPower** [comment]
Sorry, NotSoSuper. I answer to jorker and mgardne : but logs_from has a limit of 100 messages

**Comment by jorkermc** [comment]
you can change the limit

**Comment by jorkermc** [comment]
client.logs_from(message.channel, limit=10000)

**Comment by LavaPower** [comment]
But you can't use this command without limit ?

**Comment by jorkermc** [comment]
make limit absurdly high?

**Comment by jorkermc** [comment]
try limit=none

**Comment by jorkermc** [comment]
and join discord

**Comment by LavaPower** [comment]
I will try
