### ISSUE TITLE
Add fields without titles

### ISSUE THREAD

**Issue by PrashantBaid11** [Rapptz/discord.py#6942]
### Summary

Fields without titles in discord py embeds

### What is the feature request for?

The core library

### The Problem

The problem is that you have to give the title for every field you which does not look good. The feature is good but it is should not be mandatory. The embeds become messy when they have too many titles. 

### The Ideal Solution

Try making name parameter not mandatory. The embeds would look better and it did be a lot better for the discord-py bot devs. 

### The Current Solution

The current solution is changing the value of the name parameter to \u200b. Which creates a space between the fields. 
![image](https://user-images.githubusercontent.com/67903361/119249967-7f5c5200-bbba-11eb-8e19-e76a5866610d.png)

**Comment by Vexs** [comment]
This is a limitation set in place by discord. All fields require title and value to be filled.
If you want just a free text box, use the description of the embed.

**Comment by PrashantBaid11** [comment]
> This is a limitation set in place by discord. All fields require title and value to be filled.
> If you want just a free text box, use the description of the embed.

Well I can do that. Any wish any time later they can add this feature like other discord api wrappers have done.

**Comment by Vexs** [comment]
No, you can't do that- you're providing content in the form of a zero-width space, which, while invisible, is still filled content. 
Other wrappers include a zero-width space filler built-in to make this easier, but you're still left with the blank area between fields. If you don't want a blank area, then use the description of the embed, and not fields.
