### ISSUE TITLE
Ability to see time took in wait_for()

### ISSUE THREAD

**Issue by Nimboss2411** [Rapptz/discord.py#6943]
### Summary

The ability to see how long the user took to do `x` action in `client.wait_for()`

### What is the feature request for?

The core library

### The Problem

Example - I'm trying to make a typeracer command and would like to see how long the user took to answer, and I'm using wait_for() to detect the message. I can't find a good and asynchronous way to do that.

### The Ideal Solution

Maybe wait_for() can return the message AND the time it took for the user to enter the message in a tuple/list if specified in function parameters?

### The Current Solution

No good solutions, not that I'm aware of

**Comment by MrKomodoDragon** [comment]
Couldn’t you use `time.perf_counter`?

**Comment by lgaan** [comment]
Logic for this would just be 

```py
first = await send("start")
last = await wait_for(...)
taken = last.created_at - first.created_at
```

This feels like a pretty niche request anyway.

**Comment by Nimboss2411** [comment]
> Couldn’t you use `time.perf_counter`?

Time is blocking tho

**Comment by Nimboss2411** [comment]
> Logic for this would just be
> 
> ```python
> first = await send("start")
> last = await wait_for(...)
> taken = last.created_at - first.created_at
> ```
> 
> This feels like a pretty niche request anyway.

Thanks, was looking for something like this :)

**Comment by Cassandra622** [comment]
> > Couldn’t you use `time.perf_counter`?
> 
> Time is blocking tho

I mean `time.perf_counter` isn't blocking.
