### ISSUE TITLE
Better command argument type hinting 

### ISSUE THREAD

**Issue by FalseDev** [Rapptz/discord.py#6946]
### Summary

Better way to type hint command arguments 

### What is the feature request for?

discord.ext.commands

### The Problem

Currently there are some workarounds necessary in order to achieve both of
- Editor, linter support
- Library support 

This leads to some clunky code like
```py
class Duration(int):
  def convert(cls, ctx:commands.Context, arg:str) -> int:
    pass
    # Actual Implementation here

class MyCog(commands,Cog):
  @commands.command()
  async def mycmd(self, ctx:commands.Context, *, duration:Duration):
    pass
```

### The Ideal Solution

The ideal solution is something like this built into discord.py
**Note**: Heavily inspired from [`FastAPI`](https://fastapi.tiangolo.com) and `dataclasses`

```py
# Library code
class Argument:
  def __init__(self, converter:Callable[[commands.Context, str], Any], **kwargs):
    self.__converter = converter
    # other properties are set here

def argument(*args, **kwargs) -> Any: # preventing linter errors
  return Argument(*args, **kwargs)

# User code
def duration(ctx:commands.Context, arg:str) -> int:
  pass

class MyCog(commands,Cog):
  @commands.command()
  async def mycmd(
    self, 
    ctx:commands.Context,
    something:str,
    *,
    dur:int=argument(duration, default=10, )
  ):
    pass

```

Additionally a dependency injection system (if possible) that allows for something like this would make discord.py even more capable
```py

async def user_record(ctx: commands.Context, user: Member = argument(default=None)) -> tuple[Member, UserRecord]:
  user = user if user else ctx.author
  user_from_db = fetch_from_database(user.id)
  return user, user_from_db

@commands.command()
async def balance(
  ctx: commands.Context, 
  user: tuple[Member, UserRecord] = argument(dependency=user_record)
):
  await ctx.send("{0.mention} has {1.balance} in balance".format(user[0], user[1]))

```

ext.commands now notices that the dependency `user_record` takes some arguments itself and parses the remaining arguments from the message to pass it

### Additional Context

This could be a pretty large undertaking for discord.py version 2 and I don't 100% expect the dependency system to be added.

This entire concept is borrowed from [`FastAPI`](https://fastapi.tiangolo.com)

My discord ID is `FalseDev#0001`

**Comment by Rapptz** [comment]
FastAPI is not unique and this is already planned.
