### ISSUE TITLE
Add something like `get_cooldown_retry_after` for Tasks.loop

### ISSUE THREAD

**Issue by Prince2347X** [Rapptz/discord.py#6953]
### Summary

Just like `get_cooldown_retry_after`, For tasks.loop there should be something which will return the remaining time before the loop will start again.

### What is the feature request for?

discord.ext.tasks

### The Problem

This will help in tracking how much time is left before the loop will run again.

### The Ideal Solution

It should return amount of time remaining for a loop to start again.

**Comment by Rapptz** [comment]
You can compute it yourself using [`next_iteration`](https://discordpy.readthedocs.io/en/latest/ext/tasks/index.html#discord.ext.tasks.Loop.next_iteration).
