### ISSUE TITLE
Add attribute 'spectators'

### ISSUE THREAD

**Issue by hofaflo** [Rapptz/discord.py#6954]
### Summary

Provide a way of listing users who a watching a stream via the 'Go Live' feature

### What is the feature request for?

The core library

### The Problem

Tracking how many (and which) users are watching a certain 'Go Live'-stream is not possible right now.

### The Ideal Solution

VoiceState already has a boolean attribute 'self_stream'. It could be extended by an attribute 'spectators', a list containing Member-objects.

**Comment by thetimtoy** [comment]
The gateway doesn't provide this info.
