### ISSUE TITLE
ENABLED_DISCOVERABLE_BEFORE

### ISSUE THREAD

**Issue by helish88** [Rapptz/discord.py#6955]
### Summary

Add "ENABLED_DISCOVERABLE_BEFORE" in Guild.features

### Reproduction Steps

I translate all guild features
I copied all guild from [docs](https://discordpy.readthedocs.io/en/latest/api.html#discord.Guild.features) but `ENABLED_DISCOVERABLE_BEFORE` is not there
for example
```py
dict = {"VERIFIED" : "translated_verified"}
```

and I get key error `Command raised an exception: KeyError: 'ENABLED_DISCOVERABLE_BEFORE`

### Expected Results

to translate ENABLED_DISCOVERABLE_BEFORE

### Actual Results

keyerror

### Intents

all

### System Information

```bash
- Python v3.7.5-final
- discord.py v1.7.1-final
- aiohttp v3.7.4.post0
- system info: Linux 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

_No response_

**Comment by Rapptz** [comment]
This feature is legacy. It's slated for removal. In general you should expect the feature list to be dynamic and contain items that aren't documented or for them to be removed at will due to how Discord operates.
