### ISSUE TITLE
Support Buttons

### ISSUE THREAD

**Issue by Creepy-Creeper3625** [Rapptz/discord.py#6957]
### Summary

Support discords new interaction release

### What is the feature request for?

The core library

### The Problem

Discord has recently released a new feature called"buttons". Support for this feature will allow developers using discord.py a easy way for reaction roles and other methods involving reactions to get user input.

### The Ideal Solution

Implementation of buttons.

### Additional Context

Official announcement
https://support.discord.com/hc/en-us/articles/1500012250861-Bots-Buttons

**Comment by Zomatree** [comment]
They are already planned and half implemented in the [interactions branch](https://github.com/Rapptz/discord.py/tree/interactions), they will be available in version 2.0.

**Comment by MrKomodoDragon** [comment]
Button Development is being worked on the `feature/interactions` branch.

**Comment by Creepy-Creeper3625** [comment]
@Zomatree @MrKomodoDragon Thanks for letting me know.

**Comment by NixonXC** [comment]
> Button Development is being worked on the `feature/interactions` branch.

But how can i ascess it

**Comment by Chrovo** [comment]
You can use version 2.0 by running `pip install -U git+https://github.com/Rapptz/discord.py`. Note that it isn't recommended to use version 2.0 as it is in development and there are a lot of breaking changes.
