### ISSUE TITLE
how to import

### ISSUE THREAD

**Issue by jaffathedev** [Rapptz/discord.py#6958]
### Summary

uwu hey wapptz ._.

### Reproduction Steps

ok swo i dwo thwis ```py
fwom discord import Intwents
fwom discord.ext import commands
````
bwut how dwo i write `impowt discword` ??!?!?!

hewp waptzz daddy 🥵 

### Minimal Reproducible Code

```python
fwom discord import Intwents
fwom discord.ext import commands

bwot = commands.Bot(command_pwefix="sexy_wapptz", intents=Intwents.all())

@bwot.evwent
aswync dwef on_weady():
    pwint("hewwo wowld")

@bwot.command()
aswync dwef hewwo(ctx):
    return await ctx.swend(f"hewwo {ctx.aufow.mentwion}")

bwot.run(twoken)
```


### Expected Results

the bwot to wok :(

### Actual Results

it gwiv ewwor

### Intents

alot of them

### System Information

i hawv hentwai os 

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

i wove you wapttz

**Comment by Mrmagicpie** [comment]
shuana, honey, youre gonna get banned from the repo or something

**Comment by jaffathedev** [comment]
> shuana, honey, youre gonna get banned from the repo or something

i thwink wapptz lwikes mwe tho :shy:

**Comment by Fxcilities** [comment]
what the.

**Comment by Mrmagicpie** [comment]
sorry about her, Rapptz 😔

**Comment by jaffathedev** [comment]
> sorry about her, Rapptz 😔

wapptz im sowwy, needed to hawppen uwu

**Comment by lgaan** [comment]
It’s best to keep the GitHub issues to actual issues, feature requests or bugs. Not memes like this.

**Comment by jaffathedev** [comment]
> It’s best to keep the GitHub issues to actual issues, feature requests or bugs. Not memes like this.

i hawv trouwble tho 🥺

**Comment by lgaan** [comment]
Consider joining the [Discord server as the README suggests then.](https://discord.gg/dpy)

**Comment by jaffathedev** [comment]
> Consider joining the [Discord server as the README suggests then.](https://discord.gg/dpy)

im bwanned.

**Comment by mesub7** [comment]
There's also the [GitHub discussions page](https://github.com/Rapptz/discord.py/discussions).

**Comment by jaffathedev** [comment]
> There's also the [GitHub discussions page](https://github.com/Rapptz/discord.py/discussions).

owo i nwever knew about thwis 🙏

**Comment by MattW-source** [comment]
What the heck

**Comment by jaffathedev** [comment]
> What the heck

what? i jwust nweed hewp?

**Comment by MattW-source** [comment]
After carefully analysing your code, character by character. I have identified that a potential root cause of your issue is that you are using Uwu Language. Python does not understand uwu language. Try using English.

**Comment by muunie** [comment]
Please i beg you. stop

**Comment by jaffathedev** [comment]
> After carefully analysing your code, character by character. I have identified that a potential root cause of your issue is that you are using Uwu Language. Python does not understand uwu language. Try using English.

thwank ywou 🙏
