### ISSUE TITLE
Remove the profile section of docs

### ISSUE THREAD

**Issue by Nimboss2411** [Rapptz/discord.py#6965]
### Summary

Removing the discord.Profile section of the documentation

### What is the feature request for?

The documentation

### The Problem

The docs clearly say the whole section has been deprecated since 1.7, so why keep the discord.Profile section?

### The Ideal Solution

Removing the section

### The Current Solution

N/A

### Additional Context

N/A

**Comment by Rapptz** [comment]
These are already removed in v2.0 along with the documentation for it.
