### ISSUE TITLE
Add new color attribute to member

### ISSUE THREAD

**Issue by ironman9356** [Rapptz/discord.py#6969]
### Summary

The latest discord update bot colors to members in the profile 

### What is the feature request for?

The core library

### The Problem

The latest discord update added a new thing to member profiles where the dominant color in the users profile picture is put Example :
![image](https://user-images.githubusercontent.com/75370527/119852894-5676ec80-bf2d-11eb-8009-4c4091886030.png)
Red in my account 

### The Ideal Solution

This feature could return the color which can be used for embed colors 
An example embed can be coded like this 
```py
embed=discord.Embed(title="Title" , description="Description" , color=ctx.author.color)
````

**Comment by MrKomodoDragon** [comment]
Bots can’t see profiles, so this probably wouldn’t work.

**Comment by ironman9356** [comment]
> But isn't that a banner? What happens if I choose to have an image of a dog for example? What colour will it pick?

well its a discord thing i didnt make it i just found it can be good for embed colors but it will be the most dominant color

**Comment by ppotatoo** [comment]
Depends if Discord allows bots to view this info.

**Comment by ironman9356** [comment]
> Bots can’t see profiles, so this probably wouldn’t work.

Yes discord can send the color maybe in the next update i am not sure how it works

**Comment by MrKomodoDragon** [comment]
Also, the dominant color is client side

**Comment by Dorukyum** [comment]
`discord.Member.colour` already exists, and it returns the colour of the member's top role. If this ever gets implemented, it should have a different attribute name.

**Comment by Rapptz** [comment]
The algorithm for getting that colour is not public or exposed so I doubt I'll be able to fetch it. It's client-side only.

**Comment by Ender2K89** [comment]
> And get member "About me" and member banner

pretty sure bots can't get the about me of a user.
