### ISSUE TITLE
Support for Discord API Buttons

### ISSUE THREAD

**Issue by Evo-F** [Rapptz/discord.py#6973]
### Summary

Allow the Discord.py library to support the new Buttons feature introduced.

### What is the feature request for?

The core library

### The Problem

As of 26 May 2021, the Discord API has support for rich-text Buttons to be displayed inline on messages, ostensibly as a substitute for reactions being used in a functionally identical way. 

If the library had support for the Buttons, bot and app developers would be able to utilize them more effectively. 

### The Ideal Solution

Because Buttons are part of the Interactions system, it may be a while before they are rolled into the core library. Additionally, this issue is likely connected to issue #6149 regarding Slash commands, as those are also part of the Interactions system.

**Comment by ImVaskel** [comment]
Master branch currently supports buttons.

**Comment by Rapptz** [comment]
Buttons have already been implemented and will be part of the v2.0 release.
