### ISSUE TITLE
'View' object has no attribute '_timeout_handler'

### ISSUE THREAD

**Issue by itzFlubby** [Rapptz/discord.py#6979]
### Summary

View object is missing attributes in __slots__

### Reproduction Steps

1. Create View-object
2. Encounter bug

### Minimal Reproducible Code

```python
@client.event
async def on_message(message):
    view = discord.ui.View(timeout = None)
```

### Expected Results

Construction of discord.ui.View object

### Actual Results

```
Traceback (most recent call last):
  File "bot.py", line 148, in on_message
    await getattr(module.module, command)(client, message, botData)
  File "\modules\dev.py", line 96, in devtest
    view = discord.ui.View(timeout = None)
  File "C:\Users\itzFlubby\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ui\view.py", line 126, in __init__
    self._timeout_handler: Optional[asyncio.TimerHandle] = None
AttributeError: 'View' object has no attribute '_timeout_handler'
```

### Intents

32511

### System Information

- Python v3.9.5-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a0
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Bugfix is to add the missing attributes to `__slots__` in `/ui/view.py`

```
    __slots__ = (
        'timeout',
        'children',
        'id',
        '_cancel_callback',
        '_timeout_handler',
        '_stopped',
    )
```

**Comment by Rapptz** [comment]
This is fixed. This class should not have `__slots__`.
