### ISSUE TITLE
Add support for message components

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [Rapptz/discord.py#6989]
### Summary

Message components is a new discord feature that allows adding clickable buttons to messages 

### What is the feature request for?

The core library

### The Problem

Currently Message components are not implemented in discord.py. Adding this feature would allow to make better bots with modern discord features made specifically for bots.

### The Ideal Solution

I think ideal solution would be an optional keyword argument to `discord.abc.Messageable.send()`

### Additional Context

Official discord article about this feature: https://support.discord.com/hc/en-us/articles/1500012250861-Bots-Buttons
Discord API docs page about this feature: https://discord.com/developers/docs/interactions/message-components

**Comment by lgaan** [comment]
This is already implemented in master, and will be out in version 2.0.

Please make sure what you're requesting isn't already implemented in a project / in master.
