### ISSUE TITLE
Editing a message using `interaction.response.edit_message()` does not edit message on button click

### ISSUE THREAD

**Issue by muunie** [Rapptz/discord.py#6990]
### Summary

When using `interaction.response.edit_message()`, it does not seem to edit the view message, and also does not raise an error

### Reproduction Steps

In a button's `callback` method, override it in a subclass and use `interaction.response.edit_message()` somewhere. 

### Minimal Reproducible Code

```python
class AttackButton(ui.Button):
    def __init__(self, fight_cls: AttackBase, *args, **kwargs):
        self.fight_cls = fight_cls
        super().__init__(*args, **kwargs)

    async def callback(self, interaction: Interaction):
        await self.view.update_visuals(interaction, self.fight_cls)
        try:
            self.view.deal_damage(self.fight_cls.damage)
        except PlayerDead as exc:
            print("PLAYER DIED")
            player_id = exc.player_id
            for child in self.view.children:
                try:
                    child.disabled = True
                except AttributeError:
                    pass
            await interaction.response.edit_message("test")
            await interaction.response.send_message(f"<@!{player_id}> has been killed!")
            return self.view.stop()

        self.view.rotate_fighters()


in this example, both `.edit_message()` and `.send_message()` don't work.
```

### Expected Results

For the message to be edited.

### Actual Results

Nothing happens.

### Intents

Members Intent

### System Information

```sh
- Python v3.8.7-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3163+gf321efd4
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19041
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Zomatree** [comment]
`edit_message` takes keyword arguments, you want the `content` keyword argument. Please make sure you check the docs before making an issue.

**Comment by muunie** [comment]
Oh right. My bad. Thank you.
