### ISSUE TITLE
Buttons cannot be disabled outside the decorator

### ISSUE THREAD

**Issue by ironman9356** [Rapptz/discord.py#6991]
### Summary

When you try to disable a button on click by changing its value to True it doesnt get disabled

### Reproduction Steps

I made a command which involves buttons 
Code was given by Danny in [discord](https://ptb.discord.com/channels/336642139381301249/336642776609456130/847679358587109446)
I added a line of code to change the button to disabled  after clicked to make it something like  this 
![image](https://user-images.githubusercontent.com/75370527/120082423-9fbb6d80-c0e0-11eb-981e-77b4169d9701.png)
But on click it didnt change to disable 

### Minimal Reproducible Code

```python
#My current code 
class Confirm(discord.ui.View):
    def __init__(self):
        super().__init__(timeout = 60.0)
        self.value = None

    @discord.ui.button(style = discord.ButtonStyle.green, emoji = "<:BotEngineInc:847881726768054272>",disabled=False)
    async def yes(self, button: discord.ui.Button, interaction: discord.Interaction):
        self.value = "Bot Engine INC:tm: \nCorrect choice All the bots in once place :eyes:"
        # self.stop()
        # await self.ctx.send(self.value)
        self.yes.disabled=True

    @discord.ui.button(style = discord.ButtonStyle.green, emoji = "<:dpgbot:826780608780042241>")
    async def no(self, button: discord.ui.Button, interaction: discord.Interaction):
        self.value = "DPG BOT \nBad choice"
        # self.stop()
        self.no.disabled = True

    @commands.command(hidden=True)
    async def choose(self, ctx):
        confirm = Confirm()
        await ctx.send('What is better?', view = confirm)
        await confirm.wait()
        await ctx.send(f'{ctx.author} chose {confirm.value}')
```

### Expected Results

Button should be disabled

### Actual Results

Button doesnt get disabled

### Intents

all

### System Information

- Python v3.9.5-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3176+g69566241
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19042

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Phxntxm** [comment]
This code disables the button... but then never edits the view back into the message. This only disables the *object* in your python code, to actually communicate to discord that the button is now disabled you need to send the view again. What makes the most sense is editing interaction.message with the view after disabling the button. For example if I put a `self.stop()` after your disabling of a button, and add the view in that `await ctx.send(f'{ctx.author} chose {confirm.value}')` line it works as intended
