### ISSUE TITLE
Can't raise commands.MissingPermissions

### ISSUE THREAD

**Issue by WieeRd** [Rapptz/discord.py#6996]
### Summary

Can't create MissingPermissions/BotMissingPermissions, __init__ seems broken

### Reproduction Steps

I just wanted to use check `has_permissions` :(

### Minimal Reproducible Code

```python
from discord import Permissions
from discord.ext.commands import MissingPermissions
e = MissingPermissions([Permissions(manage_guild=True)])
print(e)
```

### Expected Results

You are missing Manage Server permission(s) to run this command.

### Actual Results

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wieerd/.local/lib/python3.9/site-packages/discord/ext/commands/errors.py", line 593, in __init__
    missing = [perm.replace('_', ' ').replace('guild', 'server').title() for perm in missing_perms]
  File "/home/wieerd/.local/lib/python3.9/site-packages/discord/ext/commands/errors.py", line 593, in <listcomp>
    missing = [perm.replace('_', ' ').replace('guild', 'server').title() for perm in missing_perms]
AttributeError: 'Permissions' object has no attribute 'replace'
```

### Intents

discord.Intents.none()

### System Information

- Python v3.9.5-final
- discord.py v1.7.1-final
- aiohttp v3.7.4.post0
- system info: Linux 5.4.118-1-MANJARO #1 SMP PREEMPT Tue May 11 17:46:18 UTC 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

In [discord/ext/commands/core.py#L1735-L1740](https://github.com/Rapptz/discord.py/blob/1b1577267129fcf7afa7704832158b391700c1c1/discord/ext/commands/core.py#L1735-L1740),  
check `has_permissions` pass argument of type `List[Permissions]` to initialize `MissingPermissions`.  
But in [`MissingPermissions.__init__`](https://github.com/Rapptz/discord.py/blob/1b1577267129fcf7afa7704832158b391700c1c1/discord/ext/commands/core.py#L1735-L1740) seems to be expecting type `List[str]`  
Same thing goes for check `BotMissingPermissions`, making check `has_permissions` and `bot_has_permissions` unusable.

**Comment by Rapptz** [comment]
This exception isn't meant to be raised by users but by the library. To make your own exception you should use `BadArgument`.

**Comment by WieeRd** [comment]
Did you just respond to new issue within 30 second
