### ISSUE TITLE
You have to str() emojis again in on_raw_reaction_add

### ISSUE THREAD

**Issue by Miolus** [Rapptz/discord.py#6999]
### Summary

You have to str() emojis again in on_raw_reaction_add to compare them to other strings.

### Reproduction Steps

Compare the event.emoji with ==

### Minimal Reproducible Code

```python
@commands.Cog.listener()
async def on_raw_reaction_add(self, event):
    emoji ="🥳" #React with the emoji
    if event.emoji != emoji:
        print("Not working :(")
    if str(event.emoji) == emoji:
        print("working")
```

### Expected Results

It should only print "working"

### Actual Results

It prints "not working" and "working"

### Intents

members

### System Information

newest stable + python 3.9

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
This isn't a bug. There is no comparison with strings. If you want to do a string comparison then you have to be explicit.
