### ISSUE TITLE
All errors/exceptions are swallowed?

### ISSUE THREAD

**Issue by annabunches** [Rapptz/discord.py#7]
I don't seem to be getting any error messages when running code using this library. Is this an artifact of the WebSocketClient library? Is it a bug? Is there some way of enabling errors that I'm missing?

**Comment by Rapptz** [comment]
Please read the documentation.

http://rapptz.github.io/discord.py/api.html#event-reference

**Comment by Orangestar12** [comment]
To add some flair to the issue (closed or not) here's some ways you can check for errors:

```
import logging
import traceback

logging.basicConfig() #This was suggested once in the #python_discord-py channel. It tells you when errors are swallowed sent to on_error.

@client.event
def on_error(event, type, value, tb):
    #print the traceback we recieved. (logging will already spit the error type.)
    traceback.print_tb(tb)
    print(value)
```

You could also do `print(traceback.format_exc())` which gives the last traceback encountered.

**Comment by Rapptz** [comment]
Chances are I'll merge the changes @Hornwitser did to `on_error` on the future as well -- which provides a decent alternative. Or I might even remove `on_error` all together.

**Comment by annabunches** [comment]
Ahh cool! Somehow I totally missed that documentation. Thanks.
