### ISSUE TITLE
avatar_url_as(static_format='webp') not working

### ISSUE THREAD

**Issue by Bluscream** [Rapptz/discord.py#701]
```py
message.guild.get_member(175456582098878464).avatar_url_as(format='gif', static_format='png', size=1024)
```
results in 
```
TypeError: avatar_url_as() got an unexpected keyword argument 'static_format'
```

Even tho the [docs](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.ClientUser.avatar_url_as) clearly state
> static_format ('str') – Format to attempt to convert only non-animated avatars to. Defaults to ‘webp’

**Comment by mgardne8** [comment]
could you please confirm if this does or does not work within your bot?
```python
    @command()
    async def avatar(self, ctx, *, user: discord.User=None):
        if user is None:
            user = ctx.message.author
        await ctx.send(user.avatar_url_as(static_format='png'))
```

**Comment by Rapptz** [comment]
You're out of date.

**Comment by Bluscream** [comment]
@Rapptz how much? i'm on 1.0.0a

**Comment by Rapptz** [comment]
Considering the rewrite version is based on current git HEAD, you will have to update every few days.

**Comment by Bluscream** [comment]
I got it up to date with `pip install -U git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]` thanks
