### ISSUE TITLE
Full type hinting

### ISSUE THREAD

**Issue by crazygmr101** [Rapptz/discord.py#7011]
### Summary

Typehinting everything in the library as per PEP 484

### What is the feature request for?

The core library

### The Problem

Pycharm's inferred typehints don't seem to work as well as they should due to the fact the library doesn't use typehints are per [PEP 484](https://www.python.org/dev/peps/pep-0484/). It seems to be able to *somewhat* infer them from the ReST-style docs, but not fully. I've not seen this problem with typehints.

![image](https://user-images.githubusercontent.com/22755628/120691200-24591380-c474-11eb-8a1b-a0755a14f4cc.png)

The particular line from the code

```py
    def add_listener(self, func, name=None):
        """The non decorator alternative to :meth:`.listen`.

        Parameters
        -----------
        func: :ref:`coroutine <coroutine>`
            The function to call.
        name: Optional[:class:`str`]
            The name of the event to listen for. Defaults to ``func.__name__``.

```

### The Ideal Solution

If `name` was typehinted as `name: str = None`, pycharm would be able to infer it correctly. 

### The Current Solution

The current solution(s) to the problem would be ignoring the warnings, or disabling them entirely. While these are completely valid solutions, they seem suboptimal, especially when working with an undocumented version, i.e., 2.0.

**Comment by MrKomodoDragon** [comment]
@crazygmr101 Typings will be added in 2.0.

**Comment by avayert** [comment]
This is a [bug with PyCharm](https://youtrack.jetbrains.com/issue/PY-44387), not the library

**Comment by crazygmr101** [comment]
> @crazygmr101 Typings will be added in 2.0.

Good to know :)



> This is a [bug with PyCharm](https://youtrack.jetbrains.com/issue/PY-44387), not the library

I didn't say that it *was* a bug with the lib, hence this being a feature request, not a bug report. :p Though I didn't know it was a PyCharm specific thing.

**Comment by NCPlayz** [comment]
While you could wait until 2.0 for full/official typings of the library, @BryanForbes has kindly been maintaining stubs for 1.x versions of the library, which can be seen [here](https://github.com/BryanForbes/discord.py-stubs).

**Comment by crazygmr101** [comment]
> While you could wait until 2.0 for full/official typings of the library, @bryanforbes has kindly been maintaining stubs for 1.x versions of the library, which can be seen [here](https://github.com/BryanForbes/discord.py-stubs).

I'm actually running a fork of 2.0, trying to keep up with Interactions and the latest changes. I've written a small library to handle buttons and such, but I know this lib would more than likely to it better :P
