### ISSUE TITLE
on_interaction() event causes persistent HTTP 404 (10062) error - "Unknown Interaction"

### ISSUE THREAD

**Issue by Evo-F** [Rapptz/discord.py#7015]
### Summary

After creating a message with Buttons, I attempt to use those Buttons to trigger other behavior via on_interaction. This produces an HTTP 404 (and consequent NotFound exception) with JSON 10062 "Unknown interaction"

### Reproduction Steps

1. Created a message with Buttons attached (message created via custom test command).
2. Attempt to use the newly-created Buttons to trigger bot behavior via on_interaction() event. 
3. At first line attempting to respond to the interaction, bot throws NotFound exception with error code 404 (10062) and message "Unknown interaction."

NB: This error DOES NOT OCCUR if the bot is restarted after Button creation. 
EXAMPLE: Bot is started in "session 1", command is invoked to create buttons. 
If buttons are used while Bot is still running in "session 1", error occurs as described.
If Bot is stopped and rerun in "session 2", and the buttons created during "session 1" are used, error does not occur and Bot behaves as expected.

### Minimal Reproducible Code

```python
@bot.event
async def on_interaction(interaction):
    await interaction.response.defer()
```

### Expected Results

I expected no error and for the Bot to behave normally.

### Actual Results

If the buttons are used within the same runtime session they were created, the error will be produced. If the bot is restarted and the buttons used afterward, the error will not occur. This error does not impact interactions from slash commands - only buttons.

Full trace below:

```
Heard an interaction! // This is the invocation of the command which creates the buttons. 
I think it's a command!
Starting new session... 
Heard an interaction! // This is the interaction from the buttons themselves.
Ignoring exception in on_interaction
Traceback (most recent call last):
  File "<censored user path>\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 315, in _run_event
    await coro(*args, **kwargs)
  File "<censored user path>/Coding/Python/IggyPy/main.py", line 67, in on_interaction
    await interaction.response.defer()
  File "<censored user path>\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\interactions.py", line 224, in defer
    await adapter.create_interaction_response(
  File "<censored user path>\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\webhook\async_.py", line 184, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
```

### Intents

all

### System Information

```
- Python v3.8.5-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3206+gdbd9ed2c
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19041
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Evo-F** [comment]
I have done some manual debugging and I have an update on this. Under the hood, there are two requests being sent to the API to the /callback endpoint. The first request, which I am not performing, is a type 6 (deferred response) request to the /callback endpoint. That's all well and good, but later on when I try to edit the original interaction response, a type 7 (edit) request is being sent to the /callback endpoint, when really it needs to be going to /@original.

**Comment by Rapptz** [comment]
Interaction.response is only meant to be called once. The View does this automatically for you if you don't do it for ease of use. Using on_interaction to handle button presses isn't really recommended since there are already ways to add persistent views using Client.add_view and using the callback dispatch mechanism which is easier to reason about than mucking about with custom_ids.
