### ISSUE TITLE
Embed Field Colors

### ISSUE THREAD

**Issue by willster277** [Rapptz/discord.py#7024]
### Summary

The addition of an optional color argument to the `add_field` method on embeds.

### What is the feature request for?

The core library

### The Problem

The ability to use color as a visual aid in embeds is severely limited. We can use red, green, or yellow to show a bit of context (eg a failed command show a help embed with a red sidebar) but if different sections of an embed need to be queued, it becomes a fight between sending too many embeds and the command taking too long to complete.

### The Ideal Solution

Similar to how `discord.Embed()` has a `color` argument to set the sidebar color, I feel there would be benefit to one such argument for `.add_field()`.

It would be optional of course as to not break anyones existing code, and would default to white.
However if specified, the parsed color value would be applied as the color of the field name.

Theres really not much more functionality for it, just a flag that allows for changing colors of field names.
My reasoning for this being at least plausible is that colors can be applied to the side bar, to role mentions, and to the usernames of members with roles, so why not to embed text? 

(By no means am I suggesting that it would be trivial to implement, I understand how difficult things that seem "simple" can be)

### The Current Solution

Currently to add color as a visual cue i'm sending an embed with the colored sidebar, sleeping for 2 seconds, repeat.

This gets incredibly slow when dealing with larger sets of data, and because I like being allowed to use my bot, I have to respect the 5 messages/5 seconds rate.

The current solutions are;
To wait a very long time for everything to send.
To use text, which is impossible to skim through when looking for a particular entry.

Honestly, both of these are terrible ways of doing it. After discussing with some other discord.py users, the other methods are plain hacky such as creating countless custom emojis to let every letter be displayed in a range of colors.

### Additional Context

Me and my coworkers use discord and discord bots to help us through the work day.
One of the bots I've been working on recently is effectively a copy of a scheduler such as trello or monday.

The feature I've been working on this week is the To-Do list element. Boring details aside i currently output each task as an embed with a color relating to its priority, but to avoid sending an excess of requests I do an `asyncio.sleep` of two seconds between each embed send. This takes ages to get everything sent, so much so that I re-built the command to only send specified priorities (our system uses 1-9, with 9 being critical).

Why not put each list entry in a field? Because color is a fantastic visual aid. Especially for those of us who are visually impaired or otherwise have difficulty skimming through text, we've found that using a distinct color for the priority of a list entry helps us find things faster.

The issue is that to use the color cues we have to wait a painfully long time, typically one of use will ask the bot for a list then go make everyone a coffee while we wait.
Having the option to simply color code the fields rather than only the embed sidebar would let us have shorter bot messages by using the `inline` flag, more directly draw attention to the color coded content, and be more obvious with the color as we find the sidebar to be a little too thin on some of our displays.

As for why we dont use an existing scheduler such as the ones mentioned, its because we dislike having different things in different places, a scheduler webapp is just another thing to have open all day.

**Comment by Zomatree** [comment]
This is not possible. This is a discord limitation, discord does not let us customize the colour here.

**Comment by willster277** [comment]
I hadn't realised, my bad.

I've submitted a request in the API section on discord's feedback page.
Maybe some day we'll be able to pretty up our embeds just that little bit more

**Comment by CleveyP** [comment]
three years later... surprised theres still no support for colors.
