### ISSUE TITLE
Github pages is still active

### ISSUE THREAD

**Issue by duhby** [Rapptz/discord.py#7026]
### Summary

The Github pages environment is still active but returns a 404

### Reproduction Steps

1. Go to [this link](https://github.com/Rapptz/discord.py/deployments)
2. See that the environment is still active
2. Click on `view deployment`
3. See that the page returns a 404 error

### Expected Results

The expected result is that there is no active environment if the page is not intended for use.

### Actual Results

The Github Pages environment is still active and returns a 404 upon viewing deployment.

### Intents

n/a

### System Information

n/a

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by JDJGInc** [comment]
can confirm it does 404 on all the developments, maybe it's private? 
That would make sense why it would be 404.
Otherwise I have no idea why it would be 404,

**Comment by Rxann** [comment]
I can confirm this issue.

**Comment by Rxann** [comment]
Also, If you look under environments on the Repo it will say that the github pages is still active!

**Comment by Rapptz** [comment]
Deleted the environment but this page still remains and I'm not really sure how to remove it but I think that's enough attention to this issue.
