### ISSUE TITLE
Any way to add video/gif to embed?

### ISSUE THREAD

**Issue by Ubuntium** [Rapptz/discord.py#703]
See title

**Comment by Rapptz** [comment]
No to video (discord limitation).

GIF can be set with `embed.set_image(url='some-gif-url')`

**Comment by Ubuntium** [comment]
okay, thanks

**Comment by SavageCoder77** [comment]
This doesn't seem to work now. I'm getting an error saying embedded is not defined.

**Comment by itsaryaman** [comment]
You must have entered an invalid url. Could you show us the code ?

**Comment by SavageCoder77** [comment]
`    elif message.content.startswith('.highfive'):
        embed.set_image(url='http://cdn.smosh.com/wp-content/uploads/2016/01/high-five-mass-fives.gif')`

**Comment by SourSpoon** [comment]
Please don't comment on closed issues with unrelated issues. Questions are better suited to the discord.py discord server
https://discord.gg/r3sSKJJ

**Comment by SavageCoder77** [comment]
https://github.com/SavageCoder77/Enchanter77_Discord_Bot/blob/master/bot.py
My code
