### ISSUE TITLE
Speaker request in stage

### ISSUE THREAD

**Issue by codinginpython123** [Rapptz/discord.py#7035]
### Summary

Make a bot able to request to speak in a stage

### What is the feature request for?

The core library

### The Problem

When connecting to a stage there is no method for the to request to speak.

### The Ideal Solution

To add a method in to the discord.VoiceClient class that the bot request to speak specific for stages.

### The Current Solution

There is no current solution

**Comment by NCPlayz** [comment]
https://discordpy.readthedocs.io/en/stable/api.html#discord.Member.request_to_speak
