### ISSUE TITLE
Discord.py Button Support

### ISSUE THREAD

**Issue by Rxann** [Rapptz/discord.py#7037]
### Summary

Support for Discord Bot Buttons

### What is the feature request for?

discord.ext.commands

### The Problem

I would like buttons to be implemented for discord.py because it would help developers not use reaction roles and use buttons for ease of use. It would also save time for developers because we wouldn't have to code out when the reaction is click we can just code the on button event. This would save lots of time for developers and keep our bots using new features.

### The Ideal Solution

The ideal solution would be that buttons are implemented in discord.py and available to everyone.

### The Current Solution

The current solution is to use unofficial libraries.

### Additional Context

For reference I will link a Node.js library that adds button usage: [The Package](https://www.npmjs.com/package/discord-buttons )

**Comment by Daggy1234** [comment]
Buttons are on master. They will be available in the 2.0 release. no eta.

**Comment by Rxann** [comment]
Thank you
