### ISSUE TITLE
Groups do not work with `ignore_extra=True` when `invoke_without_command` is left as default/False

### ISSUE THREAD

**Issue by OliverNichols** [Rapptz/discord.py#7038]
### Summary

I am trying to do things within my main group command that are used throughout my subcommands in the group. I just want it so that when people typo subcommands (or pass extra arguments in general), it doesn't trigger the main group command.

### Reproduction Steps

Simple script that should recreate the issue:
```py
from discord.ext import commands

bot = commands.Bot(command_prefix='.')

@commands.group(ignore_extra=True)
async def group(self, ctx):
  pass # do something that may be used in sub-commands

@group.command()
async def subcommand(self, ctx):
  pass # do something with result from main group

if __name__ == '__main__':
  bot.run(TOK)
```

Trying to use `.group` works fine, but it is now impossible to use `.group subcommand`.

### Expected Results

**Expected to work:**
- `.group`
- `.group <subcommand>`

**Expected to not work:**
- `.group <anything else>`

### Actual Results

**Works:**
- `.group`

**Doesnt work:**
- `.group <subcommand>`
- `.group <anything else>`

Error raised: `commands.errors.TooManyArguments`

### Intents

Default intents + members, but none required to recreate issue

### System Information

- Python v3.8.5-final
- discord.py v1.7.2-final
- aiohttp v3.7.4.post0
- system info: Linux 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
I can't reproduce this. `ignore_extra=True` is the default. Note your example code has a few issues. For starters, it's not being registered to a bot and there's an extraneous `self` parameter.

**Comment by OliverNichols** [comment]
Apologies for the messy example and description, I have updated the question and example and double-checked it reproduces the issue now.

**Comment by Rapptz** [comment]
This is a quirk of how the command framework works. I can't fix it. If you want to handle subcommands that aren't found you can do `if ctx.invoked_subcommand is None` in the body. If you want to ignore extra parameters passed you can do so in the command object. If you want the group to be a standalone command then you can use `invoke_without_command=True`.
