### ISSUE TITLE
Add support for webhooks

### ISSUE THREAD

**Issue by Rapptz** [Rapptz/discord.py#704]
Might as well add some support for this since it's a common request and it's useful for some forms of logging.

Not sure if I want this specific subset of the library to work with Python 2 & Requests. Probably not possible with the import model.

Support the following:

- [ ] Creating webhooks for a channel.
- [ ] Edit a webhook
- [ ] Querying what webhooks are in a channel.
- [ ] Posting via Webhook
- [ ] Querying what webhooks are in the server.
- [ ] `Webhook` objects must be able to be created without being tied to a `ConnectionState`
- [ ] Must be able to be executed in both asynchronous and synchronous modes 
  - [ ] This means that the user can provide their own `requests.Session` or an `aiohttp.ClientSession`
  - [ ] The ones provided by the library (e.g. `guild.webhooks()` or `channel.webhooks()` will just tie to the bot's `aiohttp.ClientSession` to the point this distinction will seem minimal).

No cache.

**Comment by tilda** [comment]
One PR has popped up for it - #718
