### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Kalmai221** [Rapptz/discord.py#7045]
### Summary

It is not letting me install discord.py

### Reproduction Steps

I tried adding Discord.py from the docs but it keeps having a error

### Minimal Reproducible Code

```python
py -3 -m pip install -U discord.py
```

### Expected Results

I expected for discord.py to install

### Actual Results

![image](https://user-images.githubusercontent.com/67641154/121555673-1c1c4d80-ca0b-11eb-8290-1d6075338f5f.png)

### Intents

N/A

### System Information

![image](https://user-images.githubusercontent.com/67641154/121555999-64d40680-ca0b-11eb-80a1-dc22db64f239.png)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by lgaan** [comment]
This is not a library bug.

You're running the command from a repl instead of the terminal.

**Comment by helish88** [comment]
try
```python install -U discord.py```
or
```python3 install -U discord.py```

**Comment by Tom-the-Bomb** [comment]
you need to run the command in your terminal/cmd/console not a python repl

**Comment by helish88** [comment]
join discord py help [server](https://discord.gg/dpy) and I think you should close this "issue"
