### ISSUE TITLE
Multiple event not working

### ISSUE THREAD

**Issue by Fusity** [Rapptz/discord.py#7049]
### Summary

The bot does not want to do several events at the same time

### Reproduction Steps

I've just multiple `@bot.event`

```python
@bot.event
async def on_message(message):
         print('Message!')
@bot.event
async def on_message_delete(message):
         print('Message deleted!')
@bot.event
async def on_guild_channel_delete(channel):
         print('Channel deleted!')
```

### Expected Results

I would like the bot to work when I indicate commands, events do not work and vice versa, when I indicate events, commands do not work

### Actual Results

Nothing happens, no errors, commands do not work as well as events

### Intents

All

### System Information

- Python v3.7.3-final
- discord.py v1.7.2-final
- aiohttp v3.7.4.post0
- system info: Linux 5.4.78-2-pve #1 SMP PVE 5.4.78-2 (Thu, 03 Dec 2020 14:26:17 +0100)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
Codeblocks require triple backtricks, not one.

That aside, this code is too stripped. Multiple events as given do work. However, you're probably using both `discord.Client` and `commands.Bot`. You don't have to mix them. `commands.Bot` is a subclass of `discord.Client` so it has the same stuff. As for why this stops your commands from working, check the [FAQ](https://discordpy.readthedocs.io/en/latest/faq.html#why-does-on-message-make-my-commands-stop-working).

In the future, these questions are better suited for [our discord server](https://discord.gg/dpy).
