### ISSUE TITLE
Add the Mobile Icon to Statuses

### ISSUE THREAD

**Issue by Rxann** [Rapptz/discord.py#7052]
### Summary

Add support for discord.py to add the option to display the mobile presence as a status.

### What is the feature request for?

The core library

### The Problem

It would become possible to display your bots status as a mobile icon. This would give developers the option to display new statuses.

### The Ideal Solution

I would like for this feature to display that the bot is supposedly using Discord Mobile and show the presence.

### The Current Solution

There is no current solution.

### Additional Context

If you don't understand what I mean by mobile Icon here is an image:
![pic](https://user-images.githubusercontent.com/80224521/121750203-f0b46400-cad9-11eb-8387-8d35c6a7f69f.PNG)

**Comment by NCPlayz** [comment]
Duplicate of #4009

**Comment by Rxann** [comment]
Thank You!
