### ISSUE TITLE
Add Bot user count

### ISSUE THREAD

**Issue by Shlol762** [Rapptz/discord.py#7058]
### Summary

Adding a "bot_count" to discord.Guild

### What is the feature request for?

The core library

### The Problem

According to the discord.py API documentation, there is an attribute called **`member_count`** for the class **`Guild`**. This attribute is very useful in creating a **Guild Statistics** command. Coming to the issue, many people out there making such commands usually add a bot count to the list of details about the guild. This becomes a problem as there isn't any direct way or attribute which returns the number of bot users in the guild and looping through the `Guild.members` list deciding the bot count with the help of the `Member.bot` value gets tiresome and slow in some cases.

### The Ideal Solution

I don't exactly have a hard written solution to this, but I'm sure there should be an easy way to make a `bot_count` attribute for the `Guild` class. The same way there's a `member_count` attribute for `Guild`.

**Comment by Phxntxm** [comment]
`member_count` comes from the discord API, that's why it's there. There is no provided info for this, so it would just end up doing the looping and checking either way

**Comment by Rapptz** [comment]
`member_count` is provided by the API via `GUILD_CREATE`. This attribute would have to be computed every time, at which point it might be better to do yourself.

**Comment by Shlol762** [comment]
Ah okay, thanks!
