### ISSUE TITLE
Add API v9 features such as Threads

### ISSUE THREAD

**Issue by MrMan314** [Rapptz/discord.py#7060]
### Summary

Add API v9 features such as Threads

### What is the feature request for?

The core library

### The Problem

There are new features in API v9, such as Threads and buttons.  I would like to see these added to the library.  

### The Ideal Solution

Add support for API v9 threads/buttons.

**Comment by Rapptz** [comment]
Already implemented in master.

**Comment by NCPlayz** [comment]
See #6817
