### ISSUE TITLE
Discord.py on_webhook_receive

### ISSUE THREAD

**Issue by Rxann** [Rapptz/discord.py#7065]
### Summary

I would like discord.py to be able to trigger an event when a payload from a webhook is received.

### What is the feature request for?

The core library

### The Problem

It would become easier to handle the giving out of perks such as: giving rewards when voting for a bot. I would like an event to trigger when data comes in from another webhook. The object would basically serve as a receiver that can trigger things for your bot.

### The Ideal Solution

The ideal solution would for this to be implemented.

### The Current Solution

The current solution would to be to setup your own webserver to handle this.

### Additional Context

No additional context

**Comment by Vexs** [comment]
Receiving webhooks requires a webserver to be run- it falls entirely out of the scope of this library, which is a client, not a server.

**Comment by Rxann** [comment]
Thank you for the feedback!
