### ISSUE TITLE
More Tasks Examples

### ISSUE THREAD

**Issue by Rxann** [Rapptz/discord.py#7068]
### Summary

I would like more examples to be added using Tasks.

### What is the feature request for?

The documentation

### The Problem

I would like for more examples to be created using discord.ext.tasks. Using tasks would become much easier if we have more examples to look at and get ideas/figure out how to use them using real life examples.

### The Ideal Solution

The ideal solution would be that more examples are created for discord.ext.tasks.

### The Current Solution

The current solution is to use Youtube videos and look at the current examples.

### Additional Context

Some Ideas for task examples: count how many times a command is used,make a mute command using tasks, and finally tracking bot uptime!

**Comment by Rapptz** [comment]
The [documentation](https://discordpy.readthedocs.io/en/stable/ext/tasks/index.html) is literally 60% examples.
