### ISSUE TITLE
Message and message replies

### ISSUE THREAD

**Issue by IncredibleDesign** [Rapptz/discord.py#7070]
### Summary

No distinction between normal message and reply to message.

### What is the feature request for?

The core library

### The Problem

Unfortunately, one cannot distinguish between a normal message and a reply to a message. It would be very nice if this were added.

### The Ideal Solution

For example, you should be able to do this:
```python
if message.reply:
     print(message.reply.content)
     print(message.reply.message)
```

**Comment by FastcordDE** [comment]
I think it would be very nice too :)

**Comment by Zomatree** [comment]
This already exist, its under [Message.reference](https://discordpy.readthedocs.io/en/latest/api.html#discord.Message.reference).

**Comment by lgaan** [comment]
> This already exist, its under [Message.reference](https://discordpy.readthedocs.io/en/latest/api.html#discord.Message.reference).

Adding onto this, just simply fetch the message from [MessageReference.message_id](https://discordpy.readthedocs.io/en/latest/api.html#discord.MessageReference.message_id).

**Comment by pikaninja** [comment]
> > This already exist, its under [Message.reference](https://discordpy.readthedocs.io/en/latest/api.html#discord.Message.reference).
> 
> Adding onto this, just simply fetch the message from [MessageReference.message_id](https://discordpy.readthedocs.io/en/latest/api.html#discord.MessageReference.message_id).

Adding more onto this, [MessageReference.resolved](https://discordpy.readthedocs.io/en/latest/api.html#discord.MessageReference.resolved) can also be used to get the message replied to.

**Comment by Rxann** [comment]
To use this you can store sending the message in a variable, and then do (varname).reply

**Note**
This is my personal way of doing it, there is a very high possibility of it not working for some people or just being straight up harder
