### ISSUE TITLE
Guild.chunk() is freezing

### ISSUE THREAD

**Issue by Aman-14** [Rapptz/discord.py#7075]
### Summary

`guild.chunk()` is not returning anything in some servers and program got stuck at the statement.

### Reproduction Steps

I used `jishaku` to reproduce the issue 
https://cdn.discordapp.com/attachments/841786304198082660/854988484082401290/unknown.png
 

### Expected Results

It should return all the members of the guild.

### Actual Results

It returns nothing.

### Intents

I have the required members intent

### System Information

- Python v3.8.3-final
- discord.py v1.7.2-final
- aiohttp v3.7.4.post0
- system info: Linux 4.14.231-173.361.amzn2.x86_64 #1 SMP Mon Apr 26 20:57:08 UTC 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Jerry-py** [comment]
Have you enabled Intents
![image](https://user-images.githubusercontent.com/64660183/122591200-9dd63180-d030-11eb-98ac-fd21aba08d96.png)

**Comment by Aman-14** [comment]
Yes I have, I wrote above too.

**Comment by diceroll123** [comment]
It's possible that `Guild.chunk()` can hang forever in some cases (such as the websocket response not coming in ever), it is suggested to do a timeout using `asyncio.wait_for`.

**Comment by Aman-14** [comment]
Oh, ok that's what I am doing now. Thanks!
