### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by halitalf** [Rapptz/discord.py#709]
When iterating message logs, it apparently tries to access the id attribute of None.

somewhere in here
```
        logs = client.logs_from(channel, limit=config["messages"], before=None, after=time)
        async for message in logs:
                if message.author == client.user:
                        infolog('Found a message by AdminCaller')
                        counter += 1
```

**Comment by Rapptz** [comment]
`channel` is `None`.

**Comment by halitalf** [comment]
@Rapptz explanation on how you arrived at this conclusion please?

**Comment by Rapptz** [comment]
The library accesses `channel.id` internally to figure out what request to send. Since `channel` is `None`, it's saying it has no attribute `id`.

**Comment by halitalf** [comment]
AH HA! I figured out why the channel is `None`! For some reason the `on_ready` event is not being fired.
