### ISSUE TITLE
Buttons and Forms in stable version

### ISSUE THREAD

**Issue by JoelNadar-TheSorceror** [Rapptz/discord.py#7090]
### Summary

A feature that allows you to create Buttons

### What is the feature request for?

discord.ui (In Dev)

### The Problem

Users have to type commands to fire sub commands.

### The Ideal Solution

Add a button in the message that will take in a function callback on click. It exists in development versions, but can you bring this to stable version??

**Comment by Evo-F** [comment]
Development versions will eventually be stable versions. It's coming.

**Comment by Rapptz** [comment]
Software development takes time. Things aren't stable until they're actually stable.
