### ISSUE TITLE
url attribute for more Discord objects

### ISSUE THREAD

**Issue by retke** [Rapptz/discord.py#7094]
### Summary

Adding a `url` attribute to objects such as users, channels or guilds.

### What is the feature request for?

The core library

### The Problem

Discord has "jump URLs", something commonly known for messages since you can right click on any message and copy its link. The library followed that by adding `discord.Message.jump_url`.

However, there are other objects that support those kind of URLs : 
- Users (will open the profile): https://discord.com/users/<USER_ID>
- Guilds (opens top channel): https://discord.com/channels/<GUILD_ID>
- Text channels: https://discord.com/channels/<GUILD_ID>/<CHANNEL_ID>  *(also works for categories but it shouldn't)*

With the buttons, it would be very useful to have an easy access to those links, simply imagine a link button redirecting to a specific channel, something I see more and more.

### The Ideal Solution

Add a `url` or `jump_url` attribute to the objects mentionned above, mostly doing the same thing as `discord.Message.jump_url`

### The Current Solution

Current solution is to format the URL ourself.

### Additional Context

I'm willing to PR this, quite an easy task, just wanna know if it's okay and what should be the name of the attribute.

**Comment by Rapptz** [comment]
These are routes in the browser app, they're not the same as the message jump link which has a special handler for it. If you click these in browser or in-app they'd just open a new tab.

**Comment by retke** [comment]
> If you click these in browser or in-app they'd just open a new tab.

That's the case for users, yes, not guilds and channels: 

![cFamMa5qNr](https://user-images.githubusercontent.com/23153234/122974353-7e256d00-d392-11eb-826b-996628a658b6.gif)
