### ISSUE TITLE
fetch_message() in announcement channel sometimes does not work

### ISSUE THREAD

**Issue by Snawe** [Rapptz/discord.py#7106]
### Summary

If you use the fetch_message() function in on_raw_reaction_add() on a message that is in an annoucement channel, the function sometimes does not return.

### Reproduction Steps

Placed the `fetch_message()` call in the `on_raw_reaction_add()`  event in an annoucement channel and add reactions. Sometimes you need to restart the bot. Sometimes you have to publish the message. Sometimes its works right away.

### Minimal Reproducible Code

```python
async def on_raw_reaction_add(self, payload: discord.RawReactionActionEvent):
    channel = self.get_channel(payload.channel_id)
    message = await channel.fetch_message(payload.message_id)
```

### Expected Results

`fetch_message()` returns a message

### Actual Results

`fetch_message()` does not return at all (sometimes)

### Intents

guilds = members = emojis = messages = reactions = true

### System Information

- Python v3.9.5-final
- discord.py v1.7.2-final
- aiohttp v3.7.3
- system info: Linux 5.4.0-54-generic 60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
This stuff is pass-through to the API. There should be no reason for this not to work other than an intermittent issue with the API.
