### ISSUE TITLE
Command.signature

### ISSUE THREAD

**Issue by NIRDERIi** [Rapptz/discord.py#7107]
### Summary

command.Signature partialy works.

### Reproduction Steps

I got a command object via `discord.ext.commands.Bot.get_command`, and then used the .signature attribute on it

### Minimal Reproducible Code

```python
cmd = bot.get_command("add-money")
print(cmd.signature)
```

### Expected Results

For it to print the command name, and then the arguments needed/optional

### Actual Results

Sometimes it printed just the arguments, and sometimes the command name and the arguments.
![bug_report_signature](https://user-images.githubusercontent.com/78727420/123423449-3daf3480-d5c8-11eb-84c7-c4712b6c3156.jpg)

### Intents

discord.Intents.all()

### System Information

- Python v3.9.1-final
- discord.py v1.7.0-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

No roast, please.

**Comment by Rapptz** [comment]
`Command.signature` doesn't return the name in any circumstance. If you pass `usage='...'` as a parameter to the command signature then it'll use that.
