### ISSUE TITLE
Sticker pack_id is no longer a required field, can cause KeyError: 'pack_id'

### ISSUE THREAD

**Issue by HexCodeFFF** [Rapptz/discord.py#7109]
### Summary

pack_id is no longer a required field in the discord API, discord.py assumes it is and this raises a KeyError

### Reproduction Steps

I'm unable to reproduce this error myself since I can't upload guild stickers (what I assume to be the cause of the error) but it seems that if discord.py tries to construct a sticker object without a pack ID the error is raised.

See sticker structure [here](https://discord.com/developers/docs/resources/channel#message-object-message-sticker-structure), `guild_id` has a `?` after it which seems to denote optional field.

This is the traceback, ignore all of the "temp_file reserved xyz" lines. I'd get a cleaner one but like I said, i can't reproduce it.

![image](https://user-images.githubusercontent.com/35177464/123486206-36405900-d5d1-11eb-809c-0d3f48341a08.png)

### Expected Results

No error, Sticker object is cleanly constructed.

### Actual Results

KeyError raised and entire bot crashes.

### Intents

Intents.default (not even using intents kwarg for bot)

### System Information

- Python v3.8.5-final
- discord.py v1.6.0-final
- aiohttp v3.7.3
- system info: Linux 5.4.0-77-generic # 86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Zomatree** [comment]
This is fixed in 1.7.3, update your discord.py.

**Comment by HexCodeFFF** [comment]
my bad, closed in 9376fcd69d91f518bed89d99124c91af3df16f15

**Comment by 0x2b00b1e5** [comment]
Version 1.7.3 did not fix this! 

```
Traceback (most recent call last):
  File "bot.py", line 634, in <module>
    bot.run(config.token)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 723, in run
    return future.result()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 702, in runner
    await self.start(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 666, in start
    await self.connect(reconnect=reconnect)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 566, in connect
    await self.ws.poll_event()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/gateway.py", line 559, in poll_event
    await self.received_message(msg.data)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/gateway.py", line 509, in received_message
    func(data)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/state.py", line 490, in parse_message_create
    message = Message(channel=channel, data=data, state=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/message.py", line 562, in __init__
    self.stickers = [Sticker(data=data, state=state) for data in data.get('stickers', [])]
  File "/home/pi/.local/lib/python3.7/site-packages/discord/message.py", line 562, in <listcomp>
    self.stickers = [Sticker(data=data, state=state) for data in data.get('stickers', [])]
  File "/home/pi/.local/lib/python3.7/site-packages/discord/sticker.py", line 77, in __init__
    self.pack_id = int(data['pack_id'])
KeyError: 'pack_id'
```

**Comment by HexCodeFFF** [comment]
i'll reopen this for you, but just in case, run `/home/pi/.local/lib/python3.7 -m discord -v` and make sure its 1.7.3

**Comment by Rapptz** [comment]
Don't reopen this issue.

This is line 77 in the library

https://github.com/Rapptz/discord.py/blob/v1.x/discord/sticker.py#L77

Note that this is different. Make sure you update your library before bumping an issue incorrectly.

**Comment by HexCodeFFF** [comment]
ah sorry about that

**Comment by 0x2b00b1e5** [comment]
It's funny though that when using `pip3 freeze` it'll show that 1.7.3 used (`discord.py==1.7.3`)

**Comment by HexCodeFFF** [comment]
my guess is that your system's `pip3` is linked to a different python installation than the one that is actually running. try to do `fullpythonpath -m pip` instead, so for you it'd be `/home/pi/.local/lib/python3.7 -m pip`.

**Comment by 0x2b00b1e5** [comment]
doing `python3 -m pip install discord.py --upgrade` did the trick.
