### ISSUE TITLE
Button label field is typing.Optional, and defaults to None, but is a Discord required field.

### ISSUE THREAD

**Issue by mirandazellnik** [Rapptz/discord.py#7113]
### Summary

The definition of `discord.ui.Button` shows the `label` field is an `Optional[str]`, which defaults to `None`. In fact, this field is required to successfully send a button.

### Reproduction Steps

- Create an instance of discord.ui.Button without setting the label
- Assign it to a view, and try to send that view.

### Minimal Reproducible Code

```python
@bot.command()
async def send_button(ctx: commands.Context):
    view = discord.ui.View()
    button = discord.ui.Button(style=discord.ButtonStyle.primary)
    view.add_item(button)
    await ctx.send('Message', view=view)
```

### Expected Results

A message with a button would be sent.

[The docs show](https://discordpy.readthedocs.io/en/master/api.html?highlight=view#id11) that the `label` field is marked as `Optional[str]`. This is in contrast to other fields which need to be specified at some point, such as the `description` field of an embed. The description field defaults to a special "Empty" value, and, importantly, has a type of `str` (no Optional) to note that it is required.

### Actual Results

You'll get this error:
```
File "/.../discord/ext/commands/core.py", line 125, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 120, in send_button
    await ctx.send('Message', view=view)
  File "/.../discord/abc.py", line 1316, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "/.../discord/http.py", line 333, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In components.0.components.0.label: This field is required
```

### Intents

Default intents

### System Information

Linux
discord.py v2.0.0a3267+gd30fea5b

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Zomatree** [comment]
`Optional` means you can pass either the type inside it or `None`. `label` is optional because you can send a button with an emoji without needing to pass a label
