### ISSUE TITLE
Custom Audit Log entries

### ISSUE THREAD

**Issue by Rxann** [Rapptz/discord.py#7117]
### Summary

Add the ability to make and add custom things to the audit log

### What is the feature request for?

The core library

### The Problem

It would become possible to log more actions to the audit log and have another way to log more complex actions.

### The Ideal Solution

The ideal solution would for this to implemented!

### The Current Solution

The current solution is to make a logging system to log actions to a logging channel.

### Additional Context

No Additional Context

**Comment by Rapptz** [comment]
Discord would have to do this. The library has no control over this.
