### ISSUE TITLE
discord.PermissionOverwite cannot set kwargs or any other attrubute

### ISSUE THREAD

**Issue by shadeyg56** [Rapptz/discord.py#7118]
### Summary

I am attempting to use discord.PermissionOverwrite to overwrite permissions for a channel. Upon setting the read_messages or send_messages kwargs or attributes it returns an error `AttributeError: `PermissionOverwrite' object attribute 'read_messages' is read-only` 

### Reproduction Steps

1. create a basic command
2. assign discord.PermissionOverwrite() to a var
3. attemp to set read_messages to True
4. run command and see traceback

### Minimal Reproducible Code

```python
@commands.command()
async def test(self, ctx):
    overwrite = discord.PermissionOverwrite()
    overwrite.read_messages = True # this line causes error
    overwrite.set_messages = True # this line also raises error. I have not tried with any other perms
    # discord.PermissionOverwrite(read_messages=True) raises same error
```

### Expected Results

No error should be returned and should be able to set kwargs in constructor or attributes

### Actual Results

`AttributeError: 'PermissionOverwrite' object attribute 'read_messages' is read-only` is raised

### Intents

default and reactions

### System Information

- Python v3.9.5-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
I cannot reproduce this.
