### ISSUE TITLE
User Input

### ISSUE THREAD

**Issue by Rxann** [Rapptz/discord.py#7119]
### Summary

Add the ability to get user input

### What is the feature request for?

The core library

### The Problem

It helps programmers be able to get user input easily and trigger events.

### The Ideal Solution

The ideal solution would for this to implemented 

### The Current Solution

Use bot.wait_for to wait for input

**Comment by Zomatree** [comment]
Can you expand on what you want? does `bot.wait_for` not suit what you need?

**Comment by Rxann** [comment]
Yes, I would like a simpler way for user input to be implemented.

**Comment by Phxntxm** [comment]
`wait_for` is there to wait for a specific event, and provides you a callable to filter that event however you want. This is extremely simple to do, with a one line check that compares the channel and the author to the correct one.

If you want to then reuse that over different places, then create a function that does that specific thing. This is very trivial to do yourself, I don't see what point including this in the library would have

**Comment by gogurtenjoyer** [comment]
This is already simple, and there's a simple example in the documentation [here](https://discordpy.readthedocs.io/en/latest/api.html?highlight=wait_for#discord.Client.wait_for). 

If you wanted to, you could write reusable code based upon this example.

**Comment by Rapptz** [comment]
There is no helper for this since it'd be hard to make an interface that suits everyone's need. This type of stuff is why wait_for was generalized instead of only allowing the events I thought were interesting back in v1.x beta.

**Comment by Rxann** [comment]
Tysm for all the people that helped me!
