### ISSUE TITLE
`None` being present as a command_prefix raises an unhelpful error

### ISSUE THREAD

**Issue by Gorialis** [Rapptz/discord.py#712]
I'll make a PR for this later if it's not already addressed by the time I get around to it, but I'm putting this here as a reminder.

At the moment, if `None` is present when Bot attempts to parse commands, it produces this exception:
```py
  File "/usr/local/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 902, in process_commands
    ctx = yield from self.get_context(message)
  File "/usr/local/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 847, in get_context
    invoked_prefix = discord.utils.find(view.skip_string, prefix)
  File "/usr/local/lib/python3.6/site-packages/discord/utils.py", line 167, in find
    if predicate(element):
  File "/usr/local/lib/python3.6/site-packages/discord/ext/commands/view.py", line 62, in skip_string
    strlen = len(string)
TypeError: object of type 'NoneType' has no len()
```
This is undeniably an unhelpful exception. and proposed fixes are as follows:
1. When `None` is presented, simply ignore it. (this means that if `command_prefix` is `None` or any sequence of just `None`s (e.g. `[None]`) commands will not function at all.)
2. Raise whenever `None` is present (this is effectively the same as what is already happening, but can be used to have a more helpful error message)
3. Raise on `None` only if there are no alternatives present (e.g. `None` would raise but `[None, '?']` would not)
4. Ignore `None` as in 1 but use `warnings` to warn the user a la `utils.deprecated` (alternatively, you could use `logging` at WARN level)

Will update this issue if, and when, PR or fix is made.

**Comment by Bluscream** [comment]
The third one looks best to me

**Comment by henry232323** [comment]
I think it should just break? Does it need to have a check if I pass a socket object? Or a number? I think if your misusing it it should just fail when passing invalid things. 

If this really needs a fix the third option just ignores invalids silently which isn't good, it should just crash.

**Comment by Gorialis** [comment]
Some people use databases or things like `dict.get` which are capable of returning `None`, meaning it's very potentially easy to make a callable prefix that returns `None` without users realizing it. This is the main reason this fix is proposed, at least if we choose to still raise on this, it should be a more useful error as in the second suggestion.

**Comment by Rapptz** [comment]
Fixed.
