### ISSUE TITLE
Audio bitrate limiting

### ISSUE THREAD

**Issue by FlyingThunder** [Rapptz/discord.py#7130]
### Summary

Being able to limit the bitrate of outgoing audio streams

### What is the feature request for?

The core library

### The Problem

Hosting bots on connections with low bandwidth can make the played audio lag, this could be solved by giving the option to throttle the outgoing audio from the bot to a lower bandwidth to sacrifice audio quality for stability

### The Ideal Solution

Being able to simply give `voice_channel.play` an option for bitrate (in kilobytes, i guess) - perhaps like the PCMVolumeTransformer is implemented.

```
vc.source = discord.PCMVolumeTransformer(vc.source)
vc.source.volume = float(volume)
```
->

```
vc.source = discord.BitrateTransformer(vc.source)
vc.source.bitrate = 32
```

### The Current Solution

None

**Comment by SYCKGit** [comment]
you can set the bitrate in kilobytes in [discord.FFmpegOpusAudio](https://discordpy.readthedocs.io/en/latest/api.html#discord.FFmpegOpusAudio)

**Comment by FlyingThunder** [comment]
Oh thanks! A dev of this repo said this wasnt possible and told me to create an issue, must have missunderstood him. Nice!
