### ISSUE TITLE
Add PDF docs for discord.ext.commands

### ISSUE THREAD

**Issue by leha-code** [Rapptz/discord.py#7134]
### Summary

Please add the PDF builds for the discord.ext.commands documentation

### What is the feature request for?

The documentation

### The Problem

I need PDFs for the documentation for discord.ext.comands

### The Ideal Solution

Build the documentation PDF with the builder you used with PDF documentation in the original documentation

**Comment by Rapptz** [comment]
discord.py makes use of custom extensions to add roles and directives. These extensions only work in HTML because making them work with LaTeX is too much effort on my part. As a result, PDF builds are disabled because they would not work with my extensions.

**Comment by Vexs** [comment]
Additionally if you need offline documentation you can build the sphinx docs on your machine.
