### ISSUE TITLE
Add support for Connection Objects

### ISSUE THREAD

**Issue by rudes** [Rapptz/discord.py#714]
I see in the Discord API spec there's an object for accessing linked account information. https://discordapp.com/developers/docs/resources/user#connection-object This would be really useful for integrations between steam and game trackers. I couldn't find anything for it in the docs. if i missed something i'm sorry.

**Comment by Vexs** [comment]
The primary reason I don't think this has been implemented is because it's not usable by bot accounts- only user accounts.

**Comment by rudes** [comment]
Wot? Sorry I missed where it specified users only. What a bummer I wish I could access public integrations.

**Comment by Rapptz** [comment]
Duplicate of #521 I guess.
