### ISSUE TITLE
Missing Message.stickers

### ISSUE THREAD

**Issue by attendeany** [Rapptz/discord.py#7140]
### Summary

discord.Message.stickers is always empty

### Reproduction Steps

Fetch any message with sticker and view discord.Message object in debugger.

![Test message](https://user-images.githubusercontent.com/39012750/123977649-db8b7080-d9c7-11eb-8aa1-6a62f55cb091.png)

### Expected Results

len(message.stickers) > 0

### Actual Results

len(message.stickers) == 0

### Intents

Intents.All() except integrations, typing, webhooks, presences

### System Information

- Python v3.6.8-final
- discord.py v1.7.2-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

This error is caused by incorrect parsing of the raw [message objects structure](https://discord.com/developers/docs/resources/channel#message-object):

discord.py [refers to the 'stickers' key](https://github.com/Rapptz/discord.py/blob/v1.7.2/discord/message.py#L563), but message stickers are currently located by the `sticker_items` key:
![raw data from discordpy](https://user-images.githubusercontent.com/39012750/123973573-8d28a280-d9c4-11eb-9387-1f550c343964.png)

Note that the **sticker object for the message has been changed** to [Message Sticker Item](https://discord.com/developers/docs/resources/channel#message-object-message-sticker-item-structure) which contains fewer fields than the [discord.Sticker constructor](https://github.com/Rapptz/discord.py/blob/9d2576e464bff87336c8b8134928c77e8d5ac55d/discord/sticker.py#L72) has.

P.S.: As far as I can see in the source code, this **problem is still relevant [at the time of the last commit](https://github.com/Rapptz/discord.py/blob/12e3eba011632f26aa9da8e69a39f1c2cb43f412/discord/message.py#L669) ('2.0.0a' version).**

**Comment by DebugOk** [comment]
Any ETA on a fix for this? I kinda needed the sticker object for my project :/

**Comment by Rapptz** [comment]
Discord no longer sends this data. It sends a minimal sticker item object instead in a separate key. So fixing this will not give you sticker objects.

**Comment by DebugOk** [comment]
I don't specifically care about the sticker object itself, I just need to know that a sticker is there

**Comment by Poloin34** [comment]
Same. We need to know how to access this object Rapptz was talking about 
> a minimal sticker item object

**Comment by JelNiSlaw** [comment]
> We need to know how to access this object Rapptz was talking about

You have to wait for #7126 to get finished and merged

**Comment by JelNiSlaw** [comment]
#7126 was merged, and this issue can be now closed
