### ISSUE TITLE
Threads

### ISSUE THREAD

**Issue by veni-vidi-code** [Rapptz/discord.py#7148]
### Summary

New API Version will need us supporting threads to avoid breaking changes

### What is the feature request for?

The core library

### The Problem

> Older API versions will not receive any Gateway Events for threads, so it is important to update soon!

Upcoming changes in the Discord API will lead to some messages not beeing received by the gateway events if they are send in threads. This might be breaking for a lot of bots such as exp bots, loggers, anti-spam etc. I know that it wont be coming that soon but it should be on the list to keep in mind to add sooner or later

### The Ideal Solution

Support Threads of API v9, register message events from threads as message events, support general thread feautures

### Additional Context

Most code should be capable of being ported from Textchannels

**Comment by NCPlayz** [comment]
See #7060

**Comment by veni-vidi-code** [comment]
Thanks
