### ISSUE TITLE
Not executing several discord.User actions

### ISSUE THREAD

**Issue by Bluscream** [Rapptz/discord.py#715]
`user.block()` `user.send_friend_request()` does nothing for me :/

```py
    @commands.command(pass_context=True)
    async def block(self, ctx, *, user: discord.User=None):
        if not user and isinstance(ctx.channel, discord.DMChannel):
            user = ctx.channel.recipient
        await ctx.message.edit(content=self.bot.bot_prefix+'Blocking %s'%user.mention)
        await user.block()
```
```py
    @commands.command(pass_context=True)
    async def friend(self, ctx, *, user: discord.User=None):
        if not user and isinstance(ctx.channel, discord.DMChannel):
            user = ctx.channel.recipient
        await ctx.message.edit(content=self.bot.bot_prefix+'Sending friend request to %s'%user.mention)
        await user.send_friend_request()
```

Am i using them wrong or is it really bugged out?

Using requests.post to the block API does block the user for me.

**Comment by Rapptz** [comment]
These endpoints are blacklisted.

They haven't been removed from the library because I'm not sure what to do with them.

**Comment by Bluscream** [comment]
Why are they blacklisted tho? :o Also that means that i have to use requests for these?

**Comment by Rapptz** [comment]
They're blacklisted because Discord said so. Using them will unverify your account. Repeated usage will possibly end up in your account being deleted or terminated.

**Comment by Bluscream** [comment]
.ack() works tho. This is hella confusing 😕

**Comment by Rapptz** [comment]
Relationship and Invite endpoints are blacklisted for user accounts. Ack is not.

Like I said, Discord decides what endpoints are blacklisted.

**Comment by Bluscream** [comment]
![image](https://user-images.githubusercontent.com/3318223/29248655-9256f5ae-801d-11e7-8756-75024d5ed264.png)

i wish there was more info on that

**Comment by Pandentia** [comment]
They are blacklisted because they can be used for spam, something Discord is very much against. Any endpoint that *could* be used for spam (most notably, relationship spam and joining raiding guilds via invites created by bots) is probably blacklisted.

**Comment by Bluscream** [comment]
Thanks for the heads-up. That actually makes a lot of sense, even tho i wanted to use it for the opposite (blocking dm invite spammers) but yeah i get why send_friend_request() is blacklisted then.
