### ISSUE TITLE
Document InteractionResponse's methods after initial response or change it to raise

### ISSUE THREAD

**Issue by jack1142** [Rapptz/discord.py#7153]
### Summary

InteractionResponse's methods doesn't do anything after initial response which should probably be documented or changed

### What is the feature request for?

The core library, The documentation

### The Problem

No indication (either through exception or in the documentation) of why the methods on InteractionResponse aren't doing anything after the initial response.

### The Ideal Solution

I want to say that the ideal solution would be changing the methods on `InteractionResponse` to raise when the developer is trying to use it for the second time but I'm guessing this must have been done for practical purposes (I'm unable to pinpoint them myself as I haven't played with it much but I trust that there was a reason for it). With that in mind, I would say that the ideal solution would be to have this behavior be documented.

### The Current Solution

Looking into source code to know that the method is returning immediately.
Might also be possible to *guess* this by reading Discord API documentation in order to know how the responses work.

**Comment by jack1142** [comment]
If this were documented, it might also be helpful to put a tip mentioning `Interaction.response` as a possible alternative.

**Comment by Rapptz** [comment]
> I'm guessing this must have been done for practical purposes

This was originally done because raising during the automatic defer would have been undesirable but I could have worked around it. However, having seen the issue it has caused makes me think I should be raising instead so I'll change it.

**Comment by jack1142** [comment]
What do you think about adding a pointer in the documentation of `InteractionResponse` and/or its methods mentioning `Interaction.followup` as suggested in the comment above?

**Comment by Rapptz** [comment]
I've already written it locally, it just hasn't been pushed.
