### ISSUE TITLE
Getting unexpected error when trying to send a webhook

### ISSUE THREAD

**Issue by Kile** [Rapptz/discord.py#7162]
### Summary

Getting an error relating to an internal function getting an unexpected keyword on `Webhook.send()`

### Reproduction Steps

Using <prefix>ask py on the code below

### Minimal Reproducible Code

```python
import aiohttp
from discord import Webhook, RequestsWebhookAdapter

session = aiohttp.ClientSession()
webhook = Webhook.from_url("valid_webhook_url", adapter=discord.RequestsWebhookAdapter(session))
await webhook.send("Hi :3", username="Just a webhook", avatar_url="https://i.imgur.com/FuDvCJg.png")
await session.close()
```

### Expected Results

A webhook is send with the specified content, username and avatar

### Actual Results

The following error occurs:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jishaku/features/python.py", line 95, in jsk_python
    async for send, result in AsyncSender(executor):
  File "/usr/local/lib/python3.8/dist-packages/jishaku/functools.py", line 109, in _internal
    value = await base.asend(self.send_value)
  File "/usr/local/lib/python3.8/dist-packages/jishaku/repl/compilation.py", line 140, in traverse
    async for send, result in AsyncSender(func(*self.args)):
  File "/usr/local/lib/python3.8/dist-packages/jishaku/functools.py", line 109, in _internal
    value = await base.asend(self.send_value)
  File "<repl>", line 7, in _repl_coroutine
    await webhook.send("Hi :3", username="Just a webhook", avatar_url="https://i.imgur.com/FuDvCJg.png")
  File "/usr/local/lib/python3.8/dist-packages/discord/webhook.py", line 989, in send
    return self._adapter.execute_webhook(wait=wait, file=file, files=files, payload=payload)
  File "/usr/local/lib/python3.8/dist-packages/discord/webhook.py", line 164, in execute_webhook
    maybe_coro = self.request('POST', url, multipart=multipart, payload=data, files=files_to_pass)
  File "/usr/local/lib/python3.8/dist-packages/discord/webhook.py", line 318, in request
    r = self.session.request(verb, url, headers=headers, data=data, files=multipart)
TypeError: _request() got an unexpected keyword argument 'files'
```

### Intents

discord.Intents.all()

### System Information

- Python v3.8.5-final
- discord.py v1.7.3-final
- aiohttp v3.6.2
- system info: Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

If this is not a bug and I just did something wrong I would love a bit clearer documentation on that

**Comment by Rapptz** [comment]
You're using the `RequestsWebhookAdapter` meant for the `requests` library with `aiohttp`. Use `AsyncWebhookAdapter` instead.
