### ISSUE TITLE
AttributeError when connecting to a voice channel after calling fetch_channel

### ISSUE THREAD

**Issue by Andelras** [Rapptz/discord.py#7163]
### Summary

AttributeError: 'Object' object has no attribute 'change_voice_state'

### Reproduction Steps

- fetch voice channel with `client.fetch_channel()`
- attempt to connect to the voice channel

It seems to occur because of this [line](https://github.com/Rapptz/discord.py/blob/c748e4bce58a74cfb6c8778693a3f034cbdf9a67/discord/client.py#L1412). `self.get_guild(guild_id)` is returning `None`, which results in the guild being set as a generic `Object` with the guild id.

### Expected Results

To fetch the channel and then connect to it

### Actual Results

  File "...\venv\lib\site-packages\discord\abc.py", line 1285, in connect
    await voice.connect(timeout=timeout, reconnect=reconnect)
  File "...\venv\lib\site-packages\discord\voice_client.py", line 342, in connect
    await self.voice_connect()
  File "...\venv\lib\site-packages\discord\voice_client.py", line 301, in voice_connect
    await self.channel.guild.change_voice_state(channel=self.channel)
AttributeError: 'Object' object has no attribute 'change_voice_state'

### Intents

None

### System Information

- Python v3.9.5-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
You probably want to use `Guild.fetch_channel` instead.
