### ISSUE TITLE
User-managed message cache

### ISSUE THREAD

**Issue by attendeany** [Rapptz/discord.py#7181]
### Summary

User ability to add messages to be placed in the non-expire cache (Regardless of `discord.Client.cached_messages` list)

### What is the feature request for?

The core library

### The Problem

From time to time, it is necessary to track the events of certain messages, even if the given message is **no longer in the internal message cache** (e.g. to the low value of Client.max_messages and high member activity or discord.Client restart)

This may be necessary in the following cases:
- interacting with the bot through reactions or [message references](https://discordpy.readthedocs.io/en/stable/api.html#discord.MessageReference.cached_message)
- event tracking for important messages (e.g. rules changes)

Implementation of this feature would make it easier to interact with target messages, having an up-to-date full set of data.

### The Ideal Solution

Something like:
`Client.add_to_user_cache(message: discord.Message)`
or
`Client.add_to_internal_cache(message: discord.Message) (if it is guaranteed that the message will not be deleted from cache while the bot is running)`
as well as functions for selective or complete cleaning of the persistent cache

_If there is any doubt about the integrity of the Message object you can force search this Message in internal cache or fetch fully up-to-date message object from discord API._

Then you can use full set of non-raw [discord.py events](https://discordpy.readthedocs.io/en/stable/api.html#event-reference) for this message and **don't worry that the message will suddenly disappear from the cache.**

### The Current Solution

1. We need to store information about current message state in user-implemented storage
2. To be sure to connect to raw discord.py events
3. Write the correct logic behind the state update we are tracking (while tracking the state of the message has long been implemented in the discord.py message cache logic)
4. Use analogs of discord.py non-raw events, which works with the structure of our user-implemented storage

A lot of time will be spent on the implementation of more flexible analogue of the discord.py message cache. Instead of just making some cache messages constantly alive.

### Additional Context

As you understand it, the idea is for the user to define a list of messages that the discord.py will process as if they were always in the `Client.cached_messages`. 

There are various options for implementing this behavior. My goal is to convey the very concept :)

**Comment by Rapptz** [comment]
There are no plans to allow for this. If you want your own cache behaviour it's trivial to maintain yourself and use the raw events to work with it.

> interacting with the bot through reactions or message references

Reactions are being superceded by buttons -- even if it wasn't the raw reaction events give you more than enough info without dealing with the actual message model. The message references already have a resolved message object that don't depend on the message cache.

> event tracking for important messages (e.g. rules changes)

This sounds like something that should be done homebrew rather than within the library.
