### ISSUE TITLE
ImportError when discord imported within file

### ISSUE THREAD

**Issue by theloni-monk** [Rapptz/discord.py#7183]
### Summary

ImportError: cannot import name 'EXACT_TOKEN_TYPES' from 'token'

### Reproduction Steps

Importing discord in the shell functions properly. But running ```import discord``` in a module results in an importerror

### Minimal Reproducible Code

```python
import discord # within file
```

### Expected Results

Discord imported normally

### Actual Results

```
Traceback (most recent call last):
  File ".\fanservice_meter\discord\discordbot.py", line 1, in <module>
    import discord
  File "C:\Users\TheoA\anaconda3\lib\site-packages\discord\__init__.py", line 23, in <module>
    import logging
  File "C:\Users\TheoA\anaconda3\lib\logging\__init__.py", line 26, in <module>
    import sys, os, time, io, re, traceback, warnings, weakref, collections.abc
  File "C:\Users\TheoA\anaconda3\lib\traceback.py", line 5, in <module>
    import linecache
  File "C:\Users\TheoA\anaconda3\lib\linecache.py", line 11, in <module>
    import tokenize
  File "C:\Users\TheoA\anaconda3\lib\tokenize.py", line 35, in <module>
    from token import EXACT_TOKEN_TYPES
ImportError: cannot import name 'EXACT_TOKEN_TYPES' from 'token' (C:\Users\TheoA\OneDrive\Documents\GitHub\FanService-Meter\fanservice_meter\discord\token.py)
```

### Intents

N/A

### System Information

- Python v3.8.8-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Using an anaconda3 environment with python 3.8.8 launched from powershell

**Comment by theloni-monk** [comment]
Solved: You cannot have a file named 'token.py' in the same module or discord.py will confuse it for its own internal library module.

**Comment by Rapptz** [comment]
`token.py` isn't a discord.py thing -- it's part of the Python standard library. You can't shadow the names of the standard library.
