### ISSUE TITLE
client.get_all_emojis() not returning anything

### ISSUE THREAD

**Issue by Ubiw** [Rapptz/discord.py#719]
I am iterating over client.get_all_emojis(). I converted it to list and printed it at one point. It returned [].
I iterated over the converted list and also over the generator. Both did nothing. appreciate some help!
I tried:
`for emoji in client.get_all_emojis():`
and
`for emoji in list(client.get_all_emojis()):`
I also tried server.emojis to try.

**Comment by Rapptz** [comment]
In order for this to do anything the cache needs to be ready, ergo you can only reliably query the state after the [`on_ready`](http://discordpy.rtfd.io/en/latest/api.html#discord.on_ready) event is called.

**Comment by Ubiw** [comment]
Oh, so I can't use it in the event?

**Comment by Rapptz** [comment]
You can. 

If you want to receive help you're going to need to post a short reproducible example.

**Comment by Ubiw** [comment]
`message = await client.send_message(client.get_channel('---'), "test message!")
	time.sleep(0.5)
	for emoji in client.get_all_emojis():
		time.sleep(0.1)
		await client.edit_message(message, str(emoji))`

**Comment by Rapptz** [comment]
First, [this is blocking](http://discordpy.readthedocs.io/en/latest/faq.html#what-does-blocking-mean). Second, this doesn't tell me much about where the code is being called. 

If you don't receive anything from the `get_all_emojis` generator and you've successfully logged in and the cache is ready (i.e. `on_ready` is called) then chances are your bot sees no custom emoji.

**Comment by Ubiw** [comment]
Thank you. I have waited until it's totally ready, then executed it.
