### ISSUE TITLE
Add message link redirect

### ISSUE THREAD

**Issue by Ricardolcm888** [Rapptz/discord.py#7191]
### Summary

With the above feature, the bot can get a discord.Message Type back with just the message link provided/

### What is the feature request for?

discord.ext.commands

### The Problem

Currently, you can only get a message's message link, but not reversing the function and get the message Type.

For example:
```
# To get a message link
message_link = message.jump_url  # we have that attribute

# The function I am suggesting

message = await bot.fetch_message(message_link)
print(type(message))
>> discord.Message

print(type(message_link))
>> str object
```

So that we can reverse the entire function and get a message type return back.

### The Ideal Solution

Use the re library and use some regex to seperate the slashs of the links which represents the guild ID, channel ID and message ID respectively/

**Comment by jay3332** [comment]
`MessageConverter` does this for you already

**Comment by ramansrivastava** [comment]
hey i am intermediate in python ,is there anything i can help with?

**Comment by OwenHunter** [comment]
@ramansrivastava This issue isn't actually an issue, it is a feature that the person didn't know about.
In future, rather than messaging asking if there is anything you can help with, have a look and see for yourself if there is any issue that you know you can fix.
