### ISSUE TITLE
Add from components in view

### ISSUE THREAD

**Issue by AurelienFT** [Rapptz/discord.py#7193]
### Summary

It could be cool to transform a list of component to a view.

### What is the feature request for?

The core library

### The Problem

There is a possibility to get the components of a view of a message with : `message.components` but we can't recreate the view easily from this list.

### The Ideal Solution

I think we could implent a `from_components` method to convert the component list to a view. Maybe the components in the list will need more informations.

### The Current Solution

Save the view in the code to always have it.

**Comment by Rapptz** [comment]
You're looking for `View.from_message`.

**Comment by AurelienFT** [comment]
@Rapptz The problem is that when I recreate a view from this I don't have the callback associated anymore.
