### ISSUE TITLE
Is there a way to get all of discord's emojis?

### ISSUE THREAD

**Issue by Ubiw** [Rapptz/discord.py#720]
Not just the custom emojis that the server has; all of the emojis in discord. [like these](http://prntscr.com/g8ipn4)
Thank you.

**Comment by Rapptz** [comment]
No. These are unicode codepoints.

**Comment by khazhyk** [comment]
You can find the discord emoji mapping/list by unminifying the client js source, fwiw, as not all codepoints have images. I do believe discord uses twitters twimoji v2, so looking there is likely easier.

**Comment by JellyWX** [comment]
Since emojis are unicode, would it not be possible to copy-paste them into strings, as long as you delclare the file type in the python file?

**Comment by Gorialis** [comment]
Unicode is always changing, so it can be difficult to keep a 'list' of all available emoji. Your list may become inconsistent with Discord's if they decide to implement their own emoji or don't support certain emoji yet.

There's also an issue of what counts as an emoji and what doesn't (for example, Discord counts © as an emoji but does not count ℗.)

The emojione repository has a JSON file that contains shortcodes and other information on emoji they implement. Their shortcodes seem to mostly coincide with Discord's, so it may serve as a good resource:
https://github.com/emojione/emojione/blob/master/emoji.json (make sure to read their [readme](https://github.com/emojione/emojione/blob/master/README.md) for information on licensing, etc)
