### ISSUE TITLE
ctx.command.usage always None

### ISSUE THREAD

**Issue by therealr5** [Rapptz/discord.py#7207]
### Summary

ctx.command.usage always is None in on_command_error and in commands

### Reproduction Steps

- Catch errors in one single on_command_error() funcion in a Cog

- Create a command the requires an argument

- Try to execute that command without giving the argument

- print out the ctx.command.usage 

### Minimal Reproducible Code

```python
@commands.command()
async def foo(self, bar):
    """
    Command description
    """
    print(bar)

@commands.Coc.Listener()
async def on_command_error(self, ctx, error):
    if isinstance(error, commands.errors.MissingRequiredArgument):
        print(ctx.command.usage)
```

### Expected Results

Output something like: `command-name <arg-1> <arg-2>`

### Actual Results

The output was `None`

### Intents

default

### System Information

- Python v3.9.5-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Linux 5.11.0-22-generic #23-Ubuntu SMP Thu Jun 17 00:34:23 UTC 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Gobot1234** [comment]
The property you are looking for here is [`Command.signature`](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.Command.signature) not `Command.usage`.

**Comment by therealr5** [comment]
Works, thank you very much
