### ISSUE TITLE
has-permissions check not working with move_members & mute_members

### ISSUE THREAD

**Issue by nose-gnome** [Rapptz/discord.py#7208]
### Summary

Permissions check fails on move_members & mute_members

### Reproduction Steps

I tried to use @has_permissions() check to check whether the user had the move members & mute members permissions.

### Minimal Reproducible Code

```python
from discord.ext.commands import command, has_permissions, Cog
 
 # This is not the actual code I used, this is just an example I made that should produce the same results
 class Example(Cog):
     def __init__(self, client):
         self.client = client
 
     @command()
     @has_permissions(move_members=True, mute_members=True)
     async def example_command(self, ctx):
         await ctx.send("You have both Move members and mute members permissions ")
```

### Expected Results

The bot to send a message saying "You have both move members and mute members permissions."

### Actual Results

The bot sends:
"You are missing Move Members and Mute Members permission(s) to run this command."

### Intents

discord.Bot(command_prefix=",", case_insensitive=True)

### System Information

1.7.3

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

The bot is unable to detect whether the user has the move members or mute members permissions.

**Comment by Rapptz** [comment]
Text channels do not have voice channel permissions.

**Comment by oliver-ni** [comment]
You're probably looking for [`has_guild_permissions`](https://discordpy.readthedocs.io/en/master/ext/commands/api.html#discord.ext.commands.has_guild_permissions).

**Comment by nose-gnome** [comment]
> You're probably looking for [`has_guild_permissions`](https://discordpy.readthedocs.io/en/master/ext/commands/api.html#discord.ext.commands.has_guild_permissions).

That seems to work.  Thanks.
