### ISSUE TITLE
AttributeError: module 'discord' has no attribute 'Embed'

### ISSUE THREAD

**Issue by Ubiw** [Rapptz/discord.py#721]
AttributeError: module 'discord' has no attribute 'Embed'
when I ran this code:
`embed = discord.Embed(title="hi", description="how are ya",colour=0x0066ff)`

**Comment by datmellow** [comment]
This issue is due to using an old version of discord.py, you will have to update in order to use ``Embed``

**Comment by Rapptz** [comment]
The library is out of date.
