### ISSUE TITLE
Cog, CogMeta, BotBase etc. are missing __repr__()

### ISSUE THREAD

**Issue by sinus-x** [Rapptz/discord.py#7216]
### Summary

Some common objects don't have human-readable __repr__()

### What is the feature request for?

discord.ext.commands

### The Problem

In development and/or while debugging the `print()` is frequently the easiest way to display information about the object. Some objects have their `__repr__()` specified (users, activities, channels, ...), but others (CogMeta, BotBase) don't.

Is there any reason for them not to have the dunder method? If not, what specifies what should and what shouldn't be included (attributes vs. properties)?

### The Ideal Solution

All common objects have a `__repr__()` defined, if possible.

### The Current Solution

Only some objects have human-readable representations, other return only the Python's default of their class and location in memory.

### Additional Context

I can create PR if there's an interest in having this included.

**Comment by Vexs** [comment]
What would be in these reprs?

**Comment by sinus-x** [comment]
Well, that's a part of what I'm asking about. For the Cog it could be something like
```py
def __repr__(self):
    return (
        f"<{self.__class__.__name__} qualified_name={self.qualified_name} "
        f"description={self.description} command_attrs={self.command_attrs!r}>
    )
```
which would produce
```
<Cog qualified_name="foo" description="foo description" command_attrs={}>
```
instead of
```
<discord.ext.commands.cog.Cog object at 0x7f1025441040>
```

**Comment by Rapptz** [comment]
Since these are meant to be the user's classes I don't change their default repr.

Bot repr doesn't really have any significance so I didn't add it.

**Comment by sinus-x** [comment]
I understand. I iterate over lists of users/cogs/... quite a lot; I keep falling into doing `print(cog)` and then seeing just a few pointers into the memory.
