### ISSUE TITLE
Is there a way to convert member to user?

### ISSUE THREAD

**Issue by Ubiw** [Rapptz/discord.py#722]
I am trying to get the ID of a member. Thank you.

**Comment by ccubed** [comment]
A member is a user. It has an ID.

http://discordpy.readthedocs.io/en/latest/api.html#member

**Comment by Ubiw** [comment]
Thank you!

**Comment by Rapptz** [comment]
If you have multiple easy to ask questions please use the API server, https://discord.gg/discord-api
