### ISSUE TITLE
Can't use message.author. avatar_url

### ISSUE THREAD

**Issue by TheLostProgrammer** [Rapptz/discord.py#7242]
### Summary

Error when adding message.author.avatar_url to an embed.

### Reproduction Steps

When using my bot with an embed, I use the users avatar.
I get this error:
```bash
Traceback (most recent call last):
  File "main.py", line 90, in on_message
    await commands[cmd](client, message, args)
  File "<string>", line 51, in function
AttributeError: 'Member' object has no attribute 'avatar_url'
```

### Minimal Reproducible Code

```python
embed = discord.Embed(title="User Information", colour=colour)
embed.set_author(name=message.author, icon_url=message.author.avatar_url)
embed.set_thumbnail(url=name.avatar_url)
await message.channel.send(embed=embed)
```

### Expected Results

I expected it to send the users avatar at the top of my embed.

### Actual Results

Instead, I got an error saying that the 'Member' object has no attribute 'avatar_url'

### Intents

I have all the intents set.

### System Information

- Python v3.8.0-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3391+gf14e5843
- aiohttp v3.7.4.post0
- system info: Linux 4.15.0-140-generic #144-Ubuntu SMP Fri Mar 19 14:12:35 UTC 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by mrvillage** [comment]
Before you install the development version and post a bug, please be sure to check the breaking changes list, member.avatar_url no longer exists, instead it can be accessed through member.avatar.url.

**Comment by TheLostProgrammer** [comment]
Ohh ok makes sense. I will read the breaking changes list next time. Thank you.
