### ISSUE TITLE
Add black to discord.Color or discord.Colour

### ISSUE THREAD

**Issue by Rxann** [Rapptz/discord.py#7248]
### Summary

Add the color black to the color class

### What is the feature request for?

The core library

### The Problem

I think that it would make it easier if there was a property for discord.Colour for embed creation.

### The Ideal Solution

Add black to discord.Colour

### The Current Solution

use discord.Color.from_rgb(0,0,0) to display the color black. You can also store that in a variable and call it for embed colors.

### Additional Context

This is a small change, but it would be cool to see!

**Comment by Rapptz** [comment]
`discord.Colour(0)` already does this. Alternatively, `discord.Colour.default()`.
