### ISSUE TITLE
Comparing VerificationLevel gives unexpected results

### ISSUE THREAD

**Issue by Twentysix26** [Rapptz/discord.py#7250]
### Summary

Comparing VerificationLevel does not work as expected

### Reproduction Steps

1. Tried to compare VerificationLevel 4 with 1
2. Received a different result than expected

### Minimal Reproducible Code

```python
>>> from discord import VerificationLevel
>>> VerificationLevel(4) > VerificationLevel(1) # "extreme" and "low"
False # !
```

### Expected Results

For the comparison to return `True`

### Actual Results

The comparison returned `False`

### Intents

-

### System Information

- Python v3.8.7-final
- discord.py v1.7.3-final
- aiohttp v3.7.3
- system info: Linux 5.10.49-1-MANJARO

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I was about to open a PR to use IntEnum instead but I see it was removed for compatibility with 3.5

**Comment by lgaan** [comment]
> I was about to open a PR to use IntEnum instead but I see it was removed for compatibility with 3.5

Just to confirm on this, all PRs currently are for the 2.0 version of the library; which drops compat for 3.5. This means you'd be able to PR this just fine.

**Comment by SebbyLaw** [comment]
This is a bug since this behavior is [documented](https://discordpy.readthedocs.io/en/v1.7.3/api.html#discord.VerificationLevel) to work.
