### ISSUE TITLE
discord.Embed's truthiness is False when there is only an image

### ISSUE THREAD

**Issue by PythonCoderAS** [Rapptz/discord.py#7252]
### Summary

The discord.Embed reports as being False when there is data.

### Reproduction Steps

I tried to check if an embed was True before sending it.

### Minimal Reproducible Code

```python
embed = discord.Embed()
embed.set_image(url="http://some.url.com")
print(bool(embed))
```

### Expected Results

The Embed should print `True`.

### Actual Results

The embed printed `False`.

### Intents

discord.Intents.all()

### System Information

- Python v3.8.11-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Darwin 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Truthiness is inferred from a `__bool__` attribute or checking if `__len__` is greater than 0. Since `Embed.__len__()` reports 0 when an image is present, the Embed will obviously report False.

**Comment by Phxntxm** [comment]
This was already fixed in master
