### ISSUE TITLE
`AttributeError`: module `discord` has no attribute `ui`

### ISSUE THREAD

**Issue by Rishiraj0100** [Rapptz/discord.py#7253]
### Summary

I saw in Examples/views/tictactoe

### Reproduction Steps

I just copied code from [`examples/views/tic_tac_toe.py`](https://github.com/Rapptz/discord.py/blob/master/examples/views/tic_tac_toe.py) and it didn't worked `AttributeError: module discord has no attribute ui`

Error:
```sh
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    class TicTacToeButton(discord.ui.Button['TicTacToe']):
AttributeError: module 'discord' has no attribute 'ui'
```

### Minimal Reproducible Code

```python
class TicTacToeButton(discord.ui.Button['TicTacToe']):
```

### Expected Results

I expected that it would run

### Actual Results

It didn't got run  and it raised module discord hasn't attribute `ui`

### Intents

discord.Intents.all()

### System Information

```sh
$ python3 -m discord -v

- Python v3.8.10-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Linux 5.8.0-1035-gcp #37~20.04.1-Ubuntu SMP Thu Jun 
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by ImVaskel** [comment]
You need to update to the master branch to use views.

**Comment by Rishiraj0100** [comment]
> You need to update to the master branch to use components.

How?

**Comment by ImVaskel** [comment]
> > You need to update to the master branch to use components.
> 
> 
> 
> How?

`pip3 install git+https://github.com/rapptz/discord.py`

**Comment by Rishiraj0100** [comment]
> > > You need to update to the master branch to use components.
> > 
> > 
> > How?
> 
> `pip3 install git+https://github.com/rapptz/discord.py`

Tysm worked
