### ISSUE TITLE
Fancier Default Help Command

### ISSUE THREAD

**Issue by Rxann** [Rapptz/discord.py#7257]
### Summary

Add the standard help command to change to an embed and the color can be chosen within the Bot or AutoShardedBot kwargs

### What is the feature request for?

The core library

### The Problem

I am trying to get a new way to change the look of the default help command. I love the way it is organized and works, but I would love it looked aesthetically, better. This would help improve our bots aesthetics. 

### The Ideal Solution

I would like for the defult help command to an embed and the color can be changed by setting an kwarg in Bot,AutoShardedBot, or Client.

### The Current Solution

Remove the command using client.remove_command("Help") and make a new command for it with an embed to send.

### Additional Context

No Additional Context

**Comment by gogurtenjoyer** [comment]
'The Current Solution' is incorrect; you'd actually subclass HelpCommand and implement using an embed as you see fit. see some examples here: https://gist.github.com/InterStella0/b78488fb28cadf279dfd3164b9f0cf96

**Comment by mesub7** [comment]
What's stopping you from making your own help command? 

The library has been designed in a way to allow you to subclass help commands and build your own (whether that is from the [default one](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.DefaultHelpCommand), a [minimal one](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.MinimalHelpCommand) or starting [from a blank slate](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.HelpCommand)). 

There's always going to be some issues with how people want their embed to look (from issues such as the sidebar colour to finer issues such as what you want in the footer). For this reason, the default help command is fine how it is; you can always change it if you don't like how it looks.

**Comment by Rxann** [comment]
I found an easier way to do this. ty for the help everyone
