### ISSUE TITLE
Boost Event

### ISSUE THREAD

**Issue by Rxann** [Rapptz/discord.py#7259]
### Summary

Add a boost event to discord.py

### What is the feature request for?

discord.ext.commands

### The Problem

I am trying to solve the problem of not having a boost event, which makes it kinda impossible to do things when a person boosts a guild. It would become like 10x easier to integrate boosts to our bots.

### The Ideal Solution

Add an event for when a user boosts a guild. The user that boosted. I would like to be able to retrieve the amount of months the user has boosted for, and if they have boosted before.

### The Current Solution

None

### Additional Context

None. ty for viewing

**Comment by XuaTheGrate** [comment]
Events are dispatched by Discord. Discord does not dispatch a boost event. The closest you can get to mimicking this behaviour is to watch the system channel for boost messages.

**Comment by Rxann** [comment]
ty
