### ISSUE TITLE
@bot.command()-s are ignored when there's an on_message()

### ISSUE THREAD

**Issue by konradybcio** [Rapptz/discord.py#7264]
### Summary

@bot.command()-s seem not to be picked up at all when on_message() is defined

### Reproduction Steps

- Add a few commands through @bot.command()
- Add an on_message
- spend 2h on "why are my commands not getting interpreted?!!?"

### Minimal Reproducible Code

```python
import discord
from discord.ext import commands

bot = commands.Bot(command_prefix='$')

@bot.event()
async def on_message(message):
    print('blah')

@bot.command()
async def test(ctx):
    await ctx.send('foo')

bot.run('super_secret_token')
```

### Expected Results

Both on_message() and test() work on their own

### Actual Results

on_message() works every time, test() never does

### Intents

neither default nor default+members work

### System Information

- Python v3.9.6-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Linux 5.12.15-arch1-1 #1 SMP PREEMPT Wed, 07 Jul 2021 23:35:29 +0000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by moanie** [comment]
Go ahead and read this: https://discordpy.readthedocs.io/en/latest/faq.html#why-does-on-message-make-my-commands-stop-working

**Comment by konradybcio** [comment]
Well thanks, that was quick.
