### ISSUE TITLE
NSFW channels

### ISSUE THREAD

**Issue by Nytelife26** [Rapptz/discord.py#727]
Looked at the API docs and I don't see a way to tell if a channel is NSFW or not. Since the newer updates you no longer have to have "nsfw" in your channel name so just checking the name is out of the question. Could you consider adding a feature to check if a channel is NSFW please?

**Comment by Pandentia** [comment]
Async (the branch you're probably using right now) isn't getting any new features anymore. Rewrite on the other hand, has a [method for this](http://discordpy.readthedocs.io/en/rewrite/api.html#discord.TextChannel.is_nsfw).

**Comment by KakolIsSomewhatGay** [comment]
@Nytelife26 Well, if you aren't keen of pretty much rewriting half or more of your bot to get onto rewrite you could use [my build of dPy](https://github.com/KakolIsSomewhatGay/discord.py) that has `is_nsfw` backported from rewrite. Do note that you most likely are going to need to switch to rewrite in future though.

**Comment by Pandentia** [comment]
"likely" is sugarcoating it. Rewrite will be v1.0 of the library.
