### ISSUE TITLE
Halting after joining voice channels

### ISSUE THREAD

**Issue by bnkk** [Rapptz/discord.py#7273]
### Summary

Upon joining voice channel, the bot will halt the function

### Reproduction Steps

Have a bot join a voice channel. After it connects, the function will halt

### Minimal Reproducible Code

```python
@tasks.loop(seconds=100)
async def boom():
    guild = client.get_guild(guildid)
    userid = myuserid
    dev = guild.get_member(myuserid)
    voice_channel = dev.voice.channel
    voice = discord.utils.get(client.voice_clients, guild=guild)
    
    await voice_channel.connect()
    print('after')
    voice.play(discord.FFmpegPCMAudio('weight.mp3'))
```

### Expected Results

- Bot joins voice channel
- Prints line of text
- Plays sound file

### Actual Results

Function will halt after line `await voice_channel.connect()`, the last two lines will not run.

### Intents

messages=True, guilds=True, reactions=True, members=True, presences=True

### System Information

- Python v3.9.0-final
- discord.py v1.7.3-final
- aiohttp v3.6.3
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
You need permission in the voice channel (i.e. `Connect`). Note that this doesn't hang indefinitely, there's a timeout parameter that controls how long to wait before timing out and finishing the flow.

**Comment by bnkk** [comment]
The bot joins the voice channel but refuses to do anything after that. Sorry for the confusion
