### ISSUE TITLE
[discordpy v2] In discord.Select, options that are defined as "default" are not present in Select.values If the user does not change the selected options

### ISSUE THREAD

**Issue by AiroPi** [Rapptz/discord.py#7284]
### Summary

When you create a UI.Select, with default values, and try to retrieve the selected values with Select.values, the list is empty.

### Reproduction Steps

When creating a Select list with a validation button : 
```py
class CustomView(ui.View):
    def __init__(self, bot: MyBot) -> None:
        super().__init__()
        self.bot = bot

    @ui.select(options=[discord.SelectOption(label='Français', value='fr', emoji='🇫🇷', default=True),
                        discord.SelectOption(label='English', value='en', emoji='🇺🇸', default=True)],
               max_values=2)
    async def callback(self, *_) -> None: ...

    @ui.button(label="Validate", row=1)
    async def validate(self, button, inter: discord.Interaction) -> None:
        print(self.children[0].values)  # Show [], but should show ['fr', 'en'] because they are selected by default
```

### Expected Results

`self.children[0].values` should show the default selected values.

### Actual Results

`self.children[0].values` show an empty list.

### Intents

all

### System Information

- Python v3.9.6-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3391+gf14e5843
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by AkshuAgarwal** [comment]
Something similar for me too.
The selected values is an empty list during initialization and if I'm not wrong it don't get updated if we don't edit the Select and just try to get those values.
So maybe, we can just manually append default values into the list.

![image](https://user-images.githubusercontent.com/83153460/127195179-3b683974-08fe-4c61-b638-58aac0ec6b50.png)

I also made a PR (#7286) which fixed the issue for me.

**Comment by adshivsat** [comment]
In Discord, Select Eject Parameter's and Switch o Off load drivers in order to initiate the R187 Protocol
