### ISSUE TITLE
discord.ext.commands.Flag disregards explicit annotation argument

### ISSUE THREAD

**Issue by PythonCoderAS** [Rapptz/discord.py#7292]
### Summary

The discord.ext.commands.Flag constructor takes a type annotation but completely disregards it when doing flag processing.

### Reproduction Steps

I made a custom converter and a datatype that is returned by it. I then constructed a flag and gave the converter as the `annotation` parameter, **but also gave the field its own type argument of the datatype**. When the flags are processed, it uses the type hint I gave and disregards the one specified in the Flag constructor.

### Minimal Reproducible Code

```python
class MyDataType:
    def __init__(self, pos_1, pos2): ...

class GenericDataTypeConverter(Converter):
    def __init__(self, type_to_convert): ...
 
   async def convert(self, ctx, arg): ...

class MyFlags(Flag):
    my_type: MyDataType = Flag(name="type", annotation=GenericDataTypeConverter(MyDataType))
    some_arg: str

@command
async def my_command(ctx, *, flags: MyFlags): ...
```

### Expected Results

It should use `GenericDataTypeConverter.convert`.

### Actual Results

It tries to do `MyDataType.__init__`, which will fail since it requires positional arguments.

### Intents

discord.Intents.all()

### System Information

- Python v3.8.11-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3407+gfc51736b
- aiohttp v3.7.4.post0
- system info: Darwin 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
I believe this was fixed in https://github.com/Rapptz/discord.py/pull/7861
