### ISSUE TITLE
get_channel returning null even when the channel exists and the bot is part of that channel

### ISSUE THREAD

**Issue by raavann** [Rapptz/discord.py#7293]
### Summary

The get_channel() method is occasionally returning None object for certain channel-id

### Reproduction Steps

I just created the bot and people added it, somehow it crashed when debugged it i found this error

### Minimal Reproducible Code

```python
for serv in client.guilds:
    print(serv.id)
    try:
        c_id = server_data.get_chnl_by_serv(serv.id)
    except:
        print('no such server in database serv = ', serv)
        print()

    channel= client.get_channel(int(c_id))
    if channel == None:
        print('channel is none for serv = ', serv)
        for c in serv.text_channels:
            if (c.permissions_for(serv.me).send_messages==True):
                server_data.update_serv(serv.id,c.id)
                print('updating the server channel = ',c )
                break
    else:
        print('channel is not none and channel = ' , channel)
        print()
```

### Expected Results

bot is running
795358694140280862
channel is not none and channel =  💻-contest-updates

858770457347751966
channel is not none and channel =  🤖-bot

859292086989881364
channel is not none and channel =  announcement

861949315584884748
channel is not none and channel =  gen

### Actual Results

bot is running
795358694140280862
channel is none for serv =

858770457347751966
channel is not none and channel =  🤖-bot

859292086989881364
channel is not none and channel =  announcement

861949315584884748
channel is not none and channel =  gen

### Intents

all intents are enabled

### System Information

- Python v3.9.4-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Note in the expected output, when i ran the loop once it gave the same result : i.e. it gave the correct result,
However when i ran the loop again it gave the incorrect output that i pasted above.

I.e: it is sometimes giving correct output sometimes not, i ran the loop several times,
i.e sometimes it can not get_channel of that particular channel

ALSO NOTE:
this issue is only with that particular channel that i mentioned in the output, every other channel behave normally

**Comment by Phxntxm** [comment]
The most likely case is you're doing something to cause this, such as for example this is in a task of some kind... and you haven't made sure you waited till the bot is ready. There are many reasons why `get_` can return None, and a situation where it just temporarily doesn't work sounds most probable to be this reason

**Comment by veni-vidi-code** [comment]
Try to use fetch channel in case of the channel not beeing available via get and tell us if this works maybe?

**Comment by FrostiiWeeb** [comment]
> ### Summary
> The get_channel() method is occasionally returning None object for certain channel-id
> 
> ### Reproduction Steps
> I just created the bot and people added it, somehow it crashed when debugged it i found this error
> 
> ### Minimal Reproducible Code
> ```python
> for serv in client.guilds:
>     print(serv.id)
>     try:
>         c_id = server_data.get_chnl_by_serv(serv.id)
>     except:
>         print('no such server in database serv = ', serv)
>         print()
> 
>     channel= client.get_channel(int(c_id))
>     if channel == None:
>         print('channel is none for serv = ', serv)
>         for c in serv.text_channels:
>             if (c.permissions_for(serv.me).send_messages==True):
>                 server_data.update_serv(serv.id,c.id)
>                 print('updating the server channel = ',c )
>                 break
>     else:
>         print('channel is not none and channel = ' , channel)
>         print()
> ```
> 
> ### Expected Results
> bot is running
> 795358694140280862
> channel is not none and channel = 💻-contest-updates
> 
> 858770457347751966
> channel is not none and channel = 🤖-bot
> 
> 859292086989881364
> channel is not none and channel = announcement
> 
> 861949315584884748
> channel is not none and channel = gen
> 
> ### Actual Results
> bot is running
> 795358694140280862
> channel is none for serv =
> 
> 858770457347751966
> channel is not none and channel = 🤖-bot
> 
> 859292086989881364
> channel is not none and channel = announcement
> 
> 861949315584884748
> channel is not none and channel = gen
> 
> ### Intents
> all intents are enabled
> 
> ### System Information
> * Python v3.9.4-final
> * discord.py v1.7.3-final
> * aiohttp v3.7.4.post0
> * system info: Windows 10 10.0.19041
> 
> ### Checklist
> * [x]  I have searched the open issues for duplicates.
> * [x]  I have shown the entire traceback, if possible.
> * [x]  I have removed my token from display, if visible.
> 
> ### Additional Context
> Note in the expected output, when i ran the loop once it gave the same result : i.e. it gave the correct result,
> However when i ran the loop again it gave the incorrect output that i pasted above.
> 
> I.e: it is sometimes giving correct output sometimes not, i ran the loop several times,
> i.e sometimes it can not get_channel of that particular channel
> 
> ALSO NOTE:
> this issue is only with that particular channel that i mentioned in the output, every other channel behave normally

This is probably because it is not in your cache, or maybe, like Phxntxm said, you haven't waited until the bot is ready. You shouldn't probaly use `fetch_channel`, but if you need to, you can use it.

**Comment by raavann** [comment]
I added
`await client.wait_until_ready()`
to the above code but it didn't solve the problem..
however i made the loop await 3 seconds every time the loop ran.. like
`for -----
     await asyncio.sleep(3)
-----`

and that solved the issue.
