### ISSUE TITLE
Extract listener mechanism from Client.dispatch

### ISSUE THREAD

**Issue by pxeger** [Rapptz/discord.py#7295]
### Summary

Separate the two separate functionalities to handle listeners from `wait_for`, and for scheduling handlers set with `@event`/overriding `on_XXX` methods, from the  `dispatch` method of `Client`

### What is the feature request for?

The core library

### The Problem

My library has functionality which replaces discord.py's event handler mechanism (the `@event` decorator / overriding the `on_XXX` methods), for which I need to override parts of [`Client.dispatch`](https://github.com/Rapptz/discord.py/blob/15eb3d2e5d9c4960ea68f7e776636388bbac6266/discord/client.py#L345). However, I want to keep the handling of "listeners" created with the `wait_for` method without reimplementing it from scratch.

### The Ideal Solution

Split [lines 349-376](https://github.com/Rapptz/discord.py/blob/15eb3d2e5d9c4960ea68f7e776636388bbac6266/discord/client.py#L349-L376) into a new method called `dispatch_waiting_listeners` or something.

### The Current Solution
Either:
- Copy-and-paste the section in to a new method
- Monkey-patch the method to keep the same bits

Both of these are unreliably because they inevitably rely on private API that is likely to change between discord.py versions.

### Additional Context

This would mean maintaining another piece of API, but I hope that's not too much of a problem.

I can do a PR.

**Comment by Phxntxm** [comment]
And why doesn't `super().dispatch()` solve this want?

**Comment by pxeger** [comment]
Because I can't then override the other bits of `dispatch`, i.e. lines 346-347 and 378-383

**Comment by Rapptz** [comment]
I have no plans to do this.

**Comment by pxeger** [comment]
Why? It's a 10 second change that I can do right now

**Comment by Rapptz** [comment]
`dispatch` itself is a private undocumented API that is going to change soon.

**Comment by pxeger** [comment]
Oh that makes sense. I assumed `dispatch` was public API because it didn't have a leading `_`.
