### ISSUE TITLE
mention highlights are broken

### ISSUE THREAD

**Issue by bui** [Rapptz/discord.py#73]
when discord.py sends a mention string (`<@id>`) it should highlight the user. I've noticed that recently it doesn't do that any longer, and mobile users see `@invalid-user` instead of the mention, screenshot: https://i.imgur.com/qCFwKJE.png

I've checked with discord support and other bot devs who use other libraries, and ultimately it sounds like a problem with discord.py

can you reproduce this at all? the following command doesn't highlight me, and appears broken on mobile:

    return discord.send_message(message.channel, '<@%s> pong' % message.author.id)

**Comment by khazhyk** [comment]
Use async, it's fixed by https://github.com/Rapptz/discord.py/commit/ec23434162a4798fa6b79a0c17eb2e9e75904ee7

**Comment by Rapptz** [comment]
Discord changed the way mentions were processed a while back. It used to be possible to send `<@id>` + an entry in `mentions` array but it changed to be `@name` + entry in mentions to finally `<@id>` only. As a result v0.9.1 and lower have the broken way of mentioning.

It'll be trivial to backport it one day I suppose.

**Comment by bui** [comment]
:+1:
