### ISSUE TITLE
Support for threads?

### ISSUE THREAD

**Issue by Jobsays** [Rapptz/discord.py#7303]
### Summary

Enable bots dependent on discord.py to interact with threads

### What is the feature request for?

The core library

### The Problem

I have an existing bot that listens to channel messages and responds to slash commands like many other bots out there.  Discord just released v0.0.263 (0.0.263) that features threads but I've discovered that my bot ignores messages it should respond to if they are in a thread.  Still works in the main channel tho.

### The Ideal Solution

Discord.py is updated so that it automagically interacts with threads like discord.js v13 and existing bots don't need to change code but just use the updated library (https://www.reddit.com/r/discordapp/comments/ou3jts/bots_interacting_with_threads/)

### The Current Solution

None that I know of.

**Comment by helish88** [comment]
install discord.py 2.0

**Comment by MhmCats** [comment]
Threads have been implemented in master.

**Comment by orgbookclub** [comment]
Has the documentation for threads been updated yet? Can't seem to find anything relevant after searching for "threads" in the API docs. Also, is there an expected date for the next stable release which will include support for threads?

**Comment by ironman9356** [comment]
> Has the documentation for threads been updated yet? Can't seem to find anything relevant after searching for "threads" in the API docs. Also, is there an expected date for the next stable release which will include support for threads?
It has been updated 
You can find it [here](https://discord.com/developers/docs/topics/threads)

**Comment by orgbookclub** [comment]
> > Has the documentation for threads been updated yet? Can't seem to find anything relevant after searching for "threads" in the API docs. Also, is there an expected date for the next stable release which will include support for threads?
> 
> It has been updated
> You can find it [here](https://discord.com/developers/docs/topics/threads)

Sorry, I should have been more clear. I meant, documentation specific to discord.py. For instance, if I want to access/create a thread via the `ctx` object, stuff like that.

**Comment by ironman9356** [comment]
> > > Has the documentation for threads been updated yet? Can't seem to find anything relevant after searching for "threads" in the API docs. Also, is there an expected date for the next stable release which will include support for threads?
> > 
> > 
> > It has been updated
> > You can find it [here](https://discord.com/developers/docs/topics/threads)
> 
> Sorry, I should have been more clear. I meant, documentation specific to discord.py. For instance, if I want to access/create a thread via the `ctx` object, stuff like that.


Oh its  [here](https://discordpy.readthedocs.io/en/master/search.html?q=threads)
