### ISSUE TITLE
discord.Interaction attributes not completely in docs 

### ISSUE THREAD

**Issue by Puncher1** [Rapptz/discord.py#7306]
### Summary

Adding attribute `data` of `class discord.Interaction` to the docs

### What is the feature request for?

The documentation

### The Problem

I think getting the data of an interaction is one of the most important things using interactions like buttons or select menus. 
But if you read the docs it seems that it's not possible to get the data. Why?

If you subclassing `ui.Button` and want to return the data of the interaction, you have to use `discord.Interaction.data`. But I couldn't find it in the docs, I randomely found it out. 

**Example:**
```py
class SelectMenu(ui.Select):
    """Adds a SelectMenu to a specific message and returns it's value."""

    def __init__(self):
        super().__init__()

    async def callback(self, interaction: discord.Interaction):
        self.view.value = interaction.data["values"][0] # <-----
        self.view.stop()
```

### The Ideal Solution

Adding the attribute `data` to the **Attributes** of `class discord.Interaction` would make it easier to find out how to get the data.

### The Current Solution

`class discord.Interaction`'s documentation is uncompleted.

**Comment by apple502j** [comment]
`self.values` should exist?

**Comment by Puncher1** [comment]
Oh yeah sorry. Didn't notice that.

**Comment by Harmon758** [comment]
Duplicate of #7185
