### ISSUE TITLE
add bot.member function

### ISSUE THREAD

**Issue by SepehrNazari** [Rapptz/discord.py#731]
It seems as though the only way to get the member class of the bot is to do:

    bots = [member for member in list(client.get_all_members()) if member.id == context.bot.user.id]
    this_server_bot = [member for member in bots if member.server == context.message.server][0]
    return this_server_bot

I think there should be an easier way to get this from the context.bot object.

**Comment by PapyrusThePlant** [comment]
`ctx.server.me` exists for that purpose.
http://discordpy.readthedocs.io/en/latest/api.html#discord.Server.me

**Comment by Rapptz** [comment]
[Server.me](http://discordpy.rtfd.io/en/latest/api.html#discord.Server.me)
