### ISSUE TITLE
Sync webhooks not working when run in threadpoolexecutor

### ISSUE THREAD

**Issue by JEF1056** [Rapptz/discord.py#7310]
### Summary

Sync webhooks don't send with attributeerror

### Reproduction Steps

Create a file with reproduction code below. Note: needs to be using the version in master

### Minimal Reproducible Code

```python
import os
from discord import SyncWebhook

whch= SyncWebhook.from_url(os.environ['LOG_URL'])
whch.send("something")
```

### Expected Results

the text "something" is sent to the webhook as defined in the enviorment variable LOG_URL

### Actual Results

the error below:
```
File "/src/discord/discord/webhook/sync.py", line 876, in send
     adapter: WebhookAdapter = _context.adapter
AttributeError: '_thread._local' object has no attribute 'adapter'
```

### Intents

discord.Intents(messages=True, guilds=True, typing = False, presences = False, members=True, reactions=True)

### System Information

- Python v3.8.8-final
- discord.py v2.0.0-alpha
- discord.py pkg_resources: v2.0.0a3428+gecf239d2
- aiohttp v3.7.4.post0
- system info: Linux 4.4.0-1094-aws #99-Ubuntu SMP Thu Jul 15 22:47:31 UTC 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
Are you doing this on a separate thread?

**Comment by JEF1056** [comment]
I beleive it is on the same thread, but I am using the autoshardedclient if that makes a difference

**Comment by Rapptz** [comment]
I can't reproduce this issue so I'm not sure what's happening here.

```py
>>> from discord import SyncWebhook
>>> url = '<censored>'
>>> wh = SyncWebhook.from_url(url)
>>> wh.send('hello')
```

This works just fine.

**Comment by JEF1056** [comment]
I looked a bot more into the code and turns out i am using a threadpoolexecutor, so it is running in a seperate thread. Here's some new example code you can try:
```
import asyncio
import discord
from discord import SyncWebhook
from concurrent.futures import ThreadPoolExecutor

url = 'URL'
loop = asyncio.get_event_loop()
wh = SyncWebhook.from_url(url)

def worker(message)
    wh.send(message.content)
    return message.content

@client.event
async def on_message(message):
    resp=await loop.run_in_executor(ThreadPoolExecutor(), update, message)
    await message.channel.send(resp)

client.run('TOKEN')
```

**Comment by Rapptz** [comment]
This is fixed, though you should probably be using the asynchronous webhook interface instead.
