### ISSUE TITLE
!help "command" output is very lackluster

### ISSUE THREAD

**Issue by enkeyz** [Rapptz/discord.py#7320]
### Summary

Better output for quering help on command

### What is the feature request for?

discord.ext.commands

### The Problem

`!help 'command'` output is very lackluster when discord user quering help about a command.

### The Ideal Solution

Instead of printing `![joke|h9j]` shoud print for example `!joke aliases[h9j]: Use this command for getting a random joke`

**Comment by Rapptz** [comment]
You can make your own help command by subclassing `HelpCommand` and making your own. Alternatively, you can try `commands.MinimalHelpCommand`
