### ISSUE TITLE
suggestion from some random person

### ISSUE THREAD

**Issue by Trojan2997** [Rapptz/discord.py#7326]
### Summary

tip: add a function that allows the bot to create and delete channels.

### What is the feature request for?

discord.ext.commands

### The Problem

what's up dude. well i have a server on discord and i wanted to implement an rpg matches function. I already have everything planned out, all that remains is to find a method to separate the members by channels. Sorry if my English isn't very good, if it's bad, it's google's fault.

### The Ideal Solution

I was thinking of a command format something like this:

@client.command
async def (command_name)(ctx):
     create_channnel(channel_type),(category),(max_members)

and also a command to delete channels (in my case, I would use it like this)

@client.command
async def (command_name)(ctx):
     delete_channel(channel_name/id)

**Comment by AnotherTwinkle** [comment]
Check out [this method](https://discordpy.readthedocs.io/en/latest/api.html#discord.Guild.create_text_channel)
and [this](https://discordpy.readthedocs.io/en/latest/api.html#discord.TextChannel.delete) for deletion.
