### ISSUE TITLE
Stubs for type checkers (ex: mypy)

### ISSUE THREAD

**Issue by ultrabear** [Rapptz/discord.py#7342]
### Summary

Adding Stubs for mypy/pytype to type check code

### What is the feature request for?

The documentation/Core library

### The Problem

When running mypy over X codebase that imports discord.py, mypy returns an error saying it could not load any stubs from discord.py, which makes it skip type checking for discord.py

### The Ideal Solution

When using mypy/pytype it can find a stub file and use it to type check over X codebase that imports discord.py, making development easier

**Comment by ImVaskel** [comment]
2.0 will have typing, but for now you can use https://github.com/bryanforbes/discord.py-stubs#readme for stubs on 1.7.

**Comment by Rapptz** [comment]
Type hints are inline, not with stubs. This is a work in progress. Closing as a duplicate of #5935

**Comment by richfromm** [comment]
Coming to this a while later, just noting in case someone else sees this, it appears that type hints are indeed present as of 2.0.0
