### ISSUE TITLE
Threads support

### ISSUE THREAD

**Issue by AtherActive** [Rapptz/discord.py#7346]
### Summary

Allow a bot to make a thread

### What is the feature request for?

The core library

### The Problem

Since threads have now rolled out to Discord, it would be nice if a bot was able to create them on-demand.

### The Ideal Solution

A simple function call 

`await [channel-object].create_thread(name,private,archive_time)`

### The Current Solution

There currently is no solution according to the documentation.

**Comment by Rapptz** [comment]
https://discordpy.readthedocs.io/en/master/api.html#discord.TextChannel.start_thread
