### ISSUE TITLE
Unable to Edit Stage Channel Topic

### ISSUE THREAD

**Issue by robsw** [Rapptz/discord.py#7354]
### Summary

Unable to Edit Stage Channel Topic with channel.edit(topic="test) but am able to edit stage channel name.

### Reproduction Steps

____________________________________
No Errors returned when command ran but did not update the topic. When swapping topic for name it works fine! have been following docs and says its supported. https://discordpy.readthedocs.io/en/latest/api.html#discord.StageChannel.edit

### Minimal Reproducible Code

```python
@bot.command(name="topic", guild_ids=guild_ids)
    channelid = bot.get_channel(866720961315209236)
    r = requests.get('https://uk2.radio01.xonos.gg/api/nowplaying/1')
    data = r.json()
    if not data:
        return await ctx.send(" to get stats. Please try again later.")
    # [{song_name}]
    stats = "{artist_name} - {song_name}".format(
        artist_name=(
            data["now_playing"]["song"]["artist"]
        ),                
        song_name=(
            data["now_playing"]["song"]["title"]
        ),
    )
    await channelid.edit(topic=stats)
```

### Expected Results

Stage Channel topic to be updated

### Actual Results

Channel topic did not update

### Intents

discord.Intents.all()

### System Information

- Python v3.8.6-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3407+gfc51736b
- aiohttp v3.7.4
- system info: Windows 10 10.0.17763

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Have contacted a few others and they cant seem to get it working either.

**Comment by robsw** [comment]
Oh and forgot to mention we tried it with 
`    await channelid.edit(topic="test")`
but this did not work either

**Comment by NCPlayz** [comment]
Seems like I forgot to remove the typing for that parameter when I was PR'ing it, but the documentation of it did get removed. `topic` is no longer an accepted parameter by Discord for editing a Stage Channel and has been phased out by Discord to use Stage Instances. 

As such, you will need to access the running [`.instance`](https://discordpy.readthedocs.io/en/master/api.html#discord.StageChannel.instance ) and [edit it](https://discordpy.readthedocs.io/en/master/api.html#discord.StageInstance.edit) or create a new stage instance and provide the topic via [`.create_instance`](https://discordpy.readthedocs.io/en/master/api.html#discord.StageChannel.create_instance). 

This still does remain to be a typing error in the library however.

**Comment by robsw** [comment]
> Seems like I forgot to remove the typing for that parameter when I was PR'ing it, but the documentation of it did get removed. `topic` is no longer an accepted parameter by Discord for editing a Stage Channel and has been phased out by Discord to use Stage Instances.
> 
> As such, you will need to access the running [`.instance`](https://discordpy.readthedocs.io/en/master/api.html#discord.StageChannel.instance) and [edit it](https://discordpy.readthedocs.io/en/master/api.html#discord.StageInstance.edit) or create a new stage instance and provide the topic via [`.create_instance`](https://discordpy.readthedocs.io/en/master/api.html#discord.StageChannel.create_instance).
> 
> This still does remain to be a typing error in the library however.

Thanks, do you happen to have a working example of this im still experiencing issues when using create_instance and not getting and errors in terminal the bot is just freezing on command.
