### ISSUE TITLE
is it possible to make a bot play system sound?

### ISSUE THREAD

**Issue by chgaming** [Rapptz/discord.py#736]
can you make a bot play system sound or play sound from a input on your pc? if so how would i do this?

**Comment by s0hvaperuna** [comment]
https://trac.ffmpeg.org/wiki/DirectShow You might be able to use this to pipe stereo mix through ffmpeg. Haven't testted it myself tho

**Comment by stolencatkarma** [comment]
echo ^G

https://en.wikipedia.org/wiki/Bell_character

Most OSs support it.
