### ISSUE TITLE
Custom Help Message

### ISSUE THREAD

**Issue by cmncaled** [Rapptz/discord.py#737]
How do I set a custom help message instead of the default one?

**Comment by Nekorooni** [comment]
You can make your own HelpFormatter and override the orginal when creating a bot, as shown [here](http://discordpy.readthedocs.io/en/rewrite/ext/commands/api.html?highlight=help#discord.Bot.formatter).
(These are docs from rewrite but this also [applies for the async branch](https://github.com/Rapptz/discord.py/blob/e2de93e2a65960c9c83e8a2fe53d18c4f9600196/discord/ext/commands/bot.py#L177-L182))

The second option as suggested is to make your own help command by disabling the existing help command using `remove_command('help')`.

**Comment by cmncaled** [comment]
@Nekorooni could you please indicate where in the code I would place `remove_command(help)` and `pm_help=true`? (Sorry, this is my first time coding a bot from the ground up and I'm sort of unfamiliar with stuff this complex)

**Comment by Nekorooni** [comment]
You set the formatter and pm_help when creating the bot, like:
```py
bot = commands.Bot(command_prefix=['`', '!', '.'], formatter=customhelp, pm_help=True)
```
where `customhelp` is an instance of HelpFormatter.

Or if you want your own help command, this would be one way:
```py
bot = commands.Bot(command_prefix=['`', '!', '.'], pm_help=True)
bot.remove_command('help')


@bot.command()
async def help():
    await bot.say("Here's your help.")


bot.run('token')
