### ISSUE TITLE
[v2] Add button id or reference in on_interaction

### ISSUE THREAD

**Issue by Miolus** [Rapptz/discord.py#7372]
### Summary

Add a button id or reference to on_interaction's interaction object.

### What is the feature request for?

The core library

### The Problem

There is no button referenced in on_interaction

### The Ideal Solution

Add custom_id to interaction

### The Current Solution

Create a custom button class for every id.

**Comment by Rapptz** [comment]
I'm not sure I understand what this is asking. There is no component attached to an interaction.

**Comment by JDJGInc** [comment]
![image](https://user-images.githubusercontent.com/22802640/129257633-20bf13c5-1afe-48a6-89c5-a70da343eb07.png)

**Comment by Miolus** [comment]
The custom id is attached in the interaction's json (["data"]["custom_id"]). So more specific, I wanted to ask if you can add this custom_id to the interaction object. Thanks.

**Comment by Rapptz** [comment]
Use interaction.data['custom_id'].
