### ISSUE TITLE
AllowedMentions default classmethod

### ISSUE THREAD

**Issue by JDJGInc** [Rapptz/discord.py#7387]
### Summary

Basically I want it so you can run AllowedMentions.default() that way it doesn't ping everyone or roles.

### What is the feature request for?

The core library

### The Problem

you basically need to either have allowed_mentions.all() then make everyone and roles set to False or 
do .none() then set the stuff you want on to on.

### The Ideal Solution

allowed_mentions = discord.AllowedMentions.default()
this way you just pass this into the bot allowed_mentions kwarg and it doesn't cause any issues.

### The Current Solution

allowed_mentions = discord.AllowedMentions(everyone=False, roles=False)
I am trying to make it that way you don't need to do this and you can just use a method to call this.

### Additional Context

I have a commit ready and I know I can be annoying but I just want a built in method to turn off everyone/ roles methods, if this is considered not warranted, I'll gladly do my current situation.
I hope you understand why I want this.

**Comment by Rapptz** [comment]
This default is fairly opinionated so I'm not going to do it.

**Comment by JDJGInc** [comment]
> This default is fairly opinionated so I'm not going to do it.

That's understandable, I was willing for a different name, but if you don't want this at all this is understable as well.
