### ISSUE TITLE
Issues with [p]help command

### ISSUE THREAD

**Issue by cmncaled** [Rapptz/discord.py#739]
So, I have a few problems I need resolved, and instead of submitting two issues, I'll keep them confined into one, as they are somewhat similar.

**First Issue**:

I am trying to get the bot to DM you when you do the help command. As of now, I have this code:

```
@bot.command()
async def help(ctx):
    """Direct messages you this message."""

    author = ctx.message.author

    embed=discord.Embed(title=" ", description="Cataclysmo's Commands:", color=0x0f8a6e)
    embed.set_author(name="Cataclysmo Help")
    embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/296789960013643796/350760427397054470/ono.jpg')
    embed.add_field(name="__", value="(See commands below)", inline=False)
    await bot.send_message(author, embed=embed)
```

The error message that I get in the console is: 

```discord.ext.commands.errors.MissingRequiredArgument: ctx is a required argument that is missing.```

How do I get this feature functioning?

**Second Issue**:

I keep getting the error for when my message has too many characters, even though it barely seems like they have any. If you look at the above code, the embed there is apparently right on the verge of having too many characters. How can I conserve space more in these embedded messages?

Thanks for bearing with me, I'm somewhat new to python and if you don't want to bother wasting time explaining this stuff to me, I understand.

**Comment by bsquidwrd** [comment]
**Issue 1**

Assuming you're using the `async` branch, you need to say `@bot.command(pass_context=True)` as seen here http://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-get-the-original-message

**Comment by Nekorooni** [comment]
You're better off asking questions on the [Discord API server](https://discord.gg/0SBTUU1wZTUzBx2q), it has a channel specifically for discord.py.

You're getting this error because you dont have `pass_context=True` in your command, so it is expecting something after the help command.
