### ISSUE TITLE
on_interaction_error

### ISSUE THREAD

**Issue by SYCKGit** [Rapptz/discord.py#7396]
### Summary

A global error handler for interactions

### What is the feature request for?

The core library

### The Problem

If one would want to do the same thing whenever any interaction fails, for example, sending `Oops! Something went wrong...`, they'd have to create an on_error in *every* subclass of `ui.View`.

### The Ideal Solution

A global interaction error listener, one like `on_command_error` could be made.

### The Current Solution

Having an `on_error` in every `ui.View` subclass.

**Comment by Rapptz** [comment]
This design doesn't make sense for interactions as I've mentioned in the other PR (https://github.com/Rapptz/discord.py/pull/7374#issuecomment-898267927).
