### ISSUE TITLE
Pipy package tells Python version 3.5 works, readme tells Python version 3.8 is required

### ISSUE THREAD

**Issue by RenatoLopes771** [Rapptz/discord.py#7397]
### Summary

Pipy package tells Python version 3.5 works, readme tells Python version 3.8 is required

### What is the feature request for?

The documentation

### The Problem

When inspecting the Pipy package (also shows the same banner on the readme) it shows python versions 3.5 through 3.8, while readme tells only python 3.8 works.

### The Ideal Solution

Only show Python version 3.8 in the banner

**Comment by Phxntxm** [comment]
The master version is 2.0 - 3.8+ is required for it
The current released version is 1.7.3 - 3.5.3+ is required for it

When 2.0 is released there won't be a difference between these

**Comment by RenatoLopes771** [comment]
> 
> 
> The master version is 2.0 - 3.8+ is required for it
> The current released version is 1.7.3 - 3.5.3+ is required for it
> 
> When 2.0 is released there won't be a difference between these

Ah very well. Was kinda confusing when reading it, I'll close this then.
