### ISSUE TITLE
Add current Discord API versions to documentation

### ISSUE THREAD

**Issue by DahliaSR** [Rapptz/discord.py#7401]
### Summary

The Discord API version supported/used by discord.py are not documented.

### What is the feature request for?

The documentation

### The Problem

The usual place to look up the Discord API versions used by discord.py are the documentation, the project description on PyPi or the Readme in the github repo, or at least the changelog, but its documented nowhere

I had had to check the source code of the 1.7.3 release, to find out which versions of the Gateway API and HTTP API discord.py currently uses.

### The Ideal Solution

Add the used Discord API versions to:

- PyPi Project Description
- Readme in GitHub Repo
- Documentation
- Changelog

The versions should be documented individually for each API.
e.g.:
```Release 1.7.3
Gateway API: v6
HTTP API: v8
Voice API: v...
```

### The Current Solution

Currently it needs to be looked up in the source code of the discord.py version used.

### Additional Context

A clear statement, that the API version are hardcoded for a good reason, in the Documentation and project description would also be awesome.

**Comment by Rapptz** [comment]
In case you're new to Discord's API, from 2016 to 2020 the API was essentially 2 versions, v6 and v7. From 2015-2016 we went through 5 versions. From 2020 onwards they released 2 new versions v8 and v9 (the latter of which is for threads). From what I can tell no one's really asked or cared about this before until v9 because they needed threads. This is the first issue in the entire history of the project where someone's asked for this. Note that threads aren't in v1.7 and won't be because it requires a breaking change. I'm not really sure what documenting this number would do since it's historically been mostly behind the scenes.

**Comment by DahliaSR** [comment]
> In case you're new to Discord's API, from 2016 to 2020 the API was essentially 2 versions, v6 and v7 (though de facto we only used v7). From 2015-2016 we went through 5 versions. From 2020 onwards they released 2 new versions v8 and v9 (the latter of which is for threads). From what I can tell no one's really asked or cared about this before until v9 because they needed threads. This is the first issue in the entire history of the project where someone's asked for this. Note that threads aren't in v1.7 and won't be because it requires a breaking change. I'm not really sure what documenting this number would do since it's historically been mostly behind the scenes.

Thanks for your responese - that was quick :)
I know most of the things you pointed out.
I'm not surprised, this is the first time an issue like this came up - I searched them before I created this one.
But I still think its a sane thing to have this piece of very basic info available where it can easily be found.
For now this question only came up becaause  this project is a bit behind of what discord currently offers, for a good reason - its not stable before its stable.
What if this is going to happen more often in the future, when Discord rolls out new features that people immediately want to use? They'll see this:

> 100% coverage of the supported Discord API.

and expect discord.py to have it.
But it does not have it, and then they join the discord server and bother people in the help channels, for no reason.

Its not super important, of course, but putting it on the list is a good idea, IMHO. The parts to change will touched sooner or later anyways, and the its probably added/fixed quickly.

**Comment by Rapptz** [comment]
I've removed the note you mention since it's caused nothing but grief and annoyance.
