### ISSUE TITLE
Custom activity not working

### ISSUE THREAD

**Issue by luki34567780** [Rapptz/discord.py#7404]
### Summary

client.change_presence does not work when supplied a custom status

### Reproduction Steps

Just run the code supplied below

### Minimal Reproducible Code

```python
import discord
intents = discord.Intents.default()
client = discord.Client(intents=intents)
@client.event
async def on_ready():
    activity_content = "test"
    activity = discord.Activity(type=discord.ActivityType.custom,name=activity_content)
    await client.change_presence(activity=activity)
    print("finished")
client.run("API Token here")
```

### Expected Results

The bot should go online and have a custom status with content test

### Actual Results

No Exception is raised and status is not set

### Intents

default intents

### System Information

 Discord.py version 1.7.3, python 3.9.6 64bit on Windows 10

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by XuaTheGrate** [comment]
Bots cannot have custom presences. See #2400

**Comment by luki34567780** [comment]
ok, thanks

**Comment by luki34567780** [comment]
Maybe it would be good to raise an Exception if this is used on a bot account
