### ISSUE TITLE
@everyone is not always guaranteed to be first in the role list

### ISSUE THREAD

**Issue by awaken1ng** [Rapptz/discord.py#741]
While bot testing on a test server, I noticed the `guild.me.colour` not returning the actual display colour of the bot on the said server
```python
response.colour = message.guild.me.colour
await message.channel.send(embed=response)
```
![](https://camo.githubusercontent.com/cc8823326f2291fd060fc86f2d254fa5de752aa2/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3230373933393033373930393039303330342f3335323130373731393231313038393932332f756e6b6e6f776e2e706e67)

Upon investigation, the reason for that was that the `@everyone` role is not on first position in the list on that server, 4 other servers properly had the role on first position however
```python
class Member(discord.abc.Messageable, _BaseUser):
  def colour(self):
    default_colour = Colour.default()

    print(self.roles)
    # [<Role id=206815085019004928 name='Yueri'>, <Role id=214026475203067904 name='@everyone'>]
    # [<Role id=206815085019004928 name='Yueri'>, <Role id=214026475203067904 name='@everyone'>, <Role id=214581426199330819 name='Adm'>]
    roles = self.roles[1:] # remove @everyone
    print(roles)
    # [<Role id=214026475203067904 name='@everyone'>]
    # [<Role id=214026475203067904 name='@everyone'>, <Role id=214581426199330819 name='Adm'>]
```

**Comment by Rapptz** [comment]
I see the issue here.

`Member.roles` gets sorted by ID and your bot's role ID is older than the guild's ID. This used to be impossible but due to the old app ID == bot user ID == role ID change it becomes possible to have role IDs that are older than the everyone role.

**Comment by Rapptz** [comment]
Thanks for the report.

This should have hopefully been fixed. `Member.roles` is now sorted by hierarchy instead of by ID.

**Comment by awaken1ng** [comment]
Yup, working as intended now, thank you for the quick fix

**Comment by ICEDSCRD** [comment]
drg
