### ISSUE TITLE
Support context menus

### ISSUE THREAD

**Issue by Robin5605** [Rapptz/discord.py#7425]
### Summary

Be able to create context menus & listen for them properly

### What is the feature request for?

The core library

### The Problem

Having a way for users to create and listen for the new context menus natively.

### The Ideal Solution

The context menus are somewhat similiar to buttons, and should be created in the same way, if possible.

- Like buttons, context menus are very easily created, even more so than buttons. You can create a simple one with a 2 line POST request. The decorator interface like we have for `discord.ui.button` could work pretty well for this. The decorator would decorate the callback, and said callback is called when the specific interaction is recieved.
- Buttons also allow for subclassing, which could also be done here. Subclass a `ContextMenu` class or something of that sort. The subclass will also have an overrideable callback class, just like the button class.

### The Current Solution

I've managed to get it to work by doing the following:

- Manually registering the command either using `aiohttp`, or some other way.
- Using `on_interaction` to listen for incoming interactions, and getting interaction data using `interaction.data` as the given attributes for interactions won't always work since the layout of the returned json from Discord is slightly different.

### Additional Context

I believe this shouldn't be _too_ hard to implement, consider it is very similar to buttons, and those were added relatively quickly to the library.

**Comment by CaptainDestructo** [comment]
Following this! This would be a super useful feature to have in my bot.

**Comment by Robin5605** [comment]
> Following this! This would be a super useful feature to have in my bot.

Indeed, it seems many other bots already have this and you can test it out for yourself using the method I mention in the issue. It's not the most intuitive as the on_interaction for this specific interaction doesn't provide all the info you might think. You'll have to get things like the message manually.

**Comment by Nyghl** [comment]
Well well, it's already in the D.py 2.0 atm 😅

**Comment by Rapptz** [comment]
Implemented.

**Comment by itttgg** [comment]
This is very good idea for feature in discord.py

**Comment by Pysics** [comment]
It has already been implemented @itttgg
