### ISSUE TITLE
Connecting to voice channels times out when using .connect() (version 2.0.0)

### ISSUE THREAD

**Issue by JEF1056** [Rapptz/discord.py#7429]
### Summary

Connecting to voice channels times out when using .connect() after 60 seconds.

### Reproduction Steps

Install the voice version of discord.py 2.0.0 from source, then get and connect to a voice channel.

### Minimal Reproducible Code

```python
import discord

intents = discord.Intents(messages=True, guilds=True, typing = False, presences = False, members=True, reactions=True)
client = discord.AutoShardedClient(intents=intents, chunk_guilds_at_startup=False)

@client.event
async def on_message(message):
    await message.author.voice.channel.connect()
    print(message.guild.voice_client)
    print(message.guild.voice_client.is_connected())

client.run('TOKEN')
```

### Expected Results

The bot should connect to a voice channel, then proceed to print the voice client in the guild and "True" to being connected

### Actual Results

Bot times out, raising an asyncio.TimeoutError():
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/jfan/src/discord.py/discord/client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "test_bot.py", line 8, in on_message
    await message.author.voice.channel.connect()
  File "/home/jfan/src/discord.py/discord/abc.py", line 1686, in connect
    await voice.connect(timeout=timeout, reconnect=reconnect)
  File "/home/jfan/src/discord.py/discord/voice_client.py", line 379, in connect
    await utils.sane_wait_for(futures, timeout=timeout)
  File "/home/jfan/src/discord.py/discord/utils.py", line 528, in sane_wait_for
    raise asyncio.TimeoutError()
asyncio.exceptions.TimeoutError
```

### Intents

discord.Intents(messages=True, guilds=True, typing = False, presences = False, members=True, reactions=True)

### System Information

- Python v3.8.10-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3495+gb6590d7f
- aiohttp v3.7.4.post0
- system info: Linux 5.4.0-81-generic 91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
Timeouts aren't a bug, it means the flow didn't finish. The most likely explanation is not having "Connect" permissions.

**Comment by JEF1056** [comment]
No, I've verified that the permissions are ok; in the voice channel I'm referring to the connect permission and view voice channel permission is available to everyone and the role the bot has specifically allows those permissions.

I should also note that the bot manages to join the channel on discord, but will timeout (and disconnect) afterward.
That is why I filed this as a bug

**Comment by JEF1056** [comment]
If anyone comes across this issue again, the voice_states intent is needed to connect to a voice channel. This could be made more clear in the documentation
