### ISSUE TITLE
TypeError: 'Button' object is not callable

### ISSUE THREAD

**Issue by Spaxly** [Rapptz/discord.py#7431]
### Summary

Getting an error when trying to use Discordpy 2.0

### Reproduction Steps

Trying to make a test button command but I come across this error.

### Minimal Reproducible Code

```python
class View(discord.ui.View):
    @discord.ui.Button(label="Close!", style=discord.ButtonStyle.primary, disabled=False)
    async def buttonClick(self, ctx, button: discord.ui.Button, interaction: discord.Interaction):
        await ctx.send('', view=View())
```

### Expected Results

To work

### Actual Results

Error

### Intents

All of them

### System Information

- Python v3.9.5-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3490+gd4c68373
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19043

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Phxntxm** [comment]
Lowercase b on button. Case is important, you're using the class as a decorator which it isn't designed to be.
