### ISSUE TITLE
[v2]: DM typing and Thread typing events are not dispatched.

### ISSUE THREAD

**Issue by onerandomusername** [Rapptz/discord.py#7432]
### Summary

DM typing events are not dispatched.

### Reproduction Steps

Start typing in a dm or a thread with an on_typing listener. The on_typing listener will never be dispatched.

### Minimal Reproducible Code

```python
import discord
import logging

logging.getLogger("discord").setLevel(logging.DEBUG)


class MyClient(discord.Client):
    async def on_ready(self):
        print(f"Logged in as {self.user} (ID: {self.user.id})")
        print("------")

    async def on_typing(self, channel, user, _):
        # we do not want the bot to reply to itself
        if user.id == self.user.id:
            return

        # these never gets called in a DM channel or Thread.
        print(f"{user} is typing in {channel}")
        await channel.trigger_typing()

    async def on_socket_raw_receive(self, msg):
        print(msg)


client = MyClient(intents=discord.Intents(typing=True), enable_debug_events=True)
client.run("token")
```

### Expected Results

The on_typing event should be dispatched to the client for dm typing events.

### Actual Results

The on_typing event is not dispatched to the client for dm typing events.

### Intents

typing=True ; the issue occurs even with all intents

### System Information

- Python v3.8.10-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3495+gb6590d7f
- aiohttp v3.7.4.post0
- system info: Linux 5.10.43.3-microsoft-standard-WSL2 #1 SMP Wed Jun 16 23:47:55 UTC 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

https://canary.discord.com/channels/815369174096412692/815369174096412695/878394332640591922

**Comment by onerandomusername** [comment]
Partially fixed in fbc4a51c355c029af61363038d0a8a9ac0bd8ace, dm typing is still not sent.

**Comment by Rapptz** [comment]
DM typings cannot be sent at the moment since the data is incomplete. The event only gives `user_id` so there's no good way to resolve it to a full `User` object. This might be impossible to fix without an event refactor for raw events.

**Comment by onerandomusername** [comment]
Hmmmm, what about a middle solution, of a raw_typing event? This wouldn't need to be resolved to a full user object, and other raw_ events already exist, so it wouldn't be unusual. All that it would provide are the user id and the channel id.

**Comment by sprmn24** [comment]
Good find. This kind of event dispatch issue is easy to miss
