### ISSUE TITLE
Problem with utils.get

### ISSUE THREAD

**Issue by cmncaled** [Rapptz/discord.py#744]
Okay, so I'm attempting to make a command that adds a role and then removes it after a specified amount of time. This is my code: 

```
@bot.command()
@commands.has_role("Staff")
async def mute(user : discord.Member, time):
    """Mutes a user."""

    muted = discord.utils.get(server.roles, id="352252350322311179")

    await bot.add_roles(user, muted)
    await bot.say("User has been muted.")
    await asyncio.sleep(time)
    await bot.remove_roles(user, muted)

@mute.error
async def setgame_error(error, ctx):
    if isinstance(error, discord.ext.commands.errors.CheckFailure):
        await bot.say("You do not have permission to use this command.")
```

Something isn't working here, and no tracebacks or errors appear in the console. I don't want to be spoon fed, I just want to know what I'm doing wrong here.

**Comment by Rapptz** [comment]
Without a traceback or an error it's pretty much just guessing to see what "doesn't work".

Immediately obvious the only thing that sticks out is that `time` is not annotated and thus will be a `str` rather than an `int` or ` float`.

**Comment by cmncaled** [comment]
@Rapptz how do I fix that?

**Comment by Rapptz** [comment]
By annotating it so the library knows what type to convert it to. e.g.

`async def mute(user: discord.Member, time: float)`

**Comment by cmncaled** [comment]
@Rapptz do I have to define a unit of time or some shit?

**Comment by cmncaled** [comment]
ah, fuck it. i clearly just need to do a shit ton of tutorials and get to know python more
