### ISSUE TITLE
How to make ffmpeg.exe run in background?

### ISSUE THREAD

**Issue by DumboGuy** [Rapptz/discord.py#745]
I'm running a music bot, but every time someone plays a song my computer automatically focuses on the ffmpeg.exe window. Is there a way to make it open in the background/not autofocus?
Sorry if this is an obvious question.

**Comment by lethargilistic** [comment]
[This seems to be what you're looking for.](https://superuser.com/questions/555289/is-there-a-way-to-disable-or-hide-output-thrown-by-ffmpeg)

It's not a problem with discord.py. Try channing ffmpeg's loglevel to quiet.
