### ISSUE TITLE
Printing out loop Error out of the configuration files?

### ISSUE THREAD

**Issue by Z3yf1re** [Rapptz/discord.py#7456]
### Summary

Im writing my first letters and this happened

### Reproduction Steps

writing the first lines of code

### Minimal Reproducible Code

```python
import discord

class MyClient(discord.Client):
    #Einloggen
    async def on_ready(self):
        print("Ich habe mich eingeloggt")

    #Wenn Nachricht gepostet wird
    async def on_message(self, message):
        print("Nachricht von " + message.author + " enthält " + str(message.content))

client = MyClient
client.run("...")
```

### Expected Results

Running normally the Code

### Actual Results

Traceback (most recent call last):
  File "C:\Users\jonas\Desktop\Discord Bot\main.py", line 13, in <module>
    client.run("...")
  File "C:\Users\jonas\Desktop\Discord Bot\venv\lib\site-packages\discord\client.py", line 692, in run
    loop = self.loop
AttributeError: 'str' object has no attribute 'loop'

### Intents

Tutorial Bot

### System Information

none

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I think I installed Python.py and my cmd says this, but i cant ask for the installed version

C:\Users\jonas>python -m pip install discord.py
Requirement already satisfied: discord.py in c:\users\jonas\appdata\local\programs\python\python39\lib\site-packages (1.7.3)
Requirement already satisfied: aiohttp<3.8.0,>=3.6.0 in c:\users\jonas\appdata\local\programs\python\python39\lib\site-packages (from discord.py) (3.7.4.post0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\jonas\appdata\local\programs\python\python39\lib\site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py) (5.1.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\jonas\appdata\local\programs\python\python39\lib\site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py) (21.2.0)
Requirement already satisfied: chardet<5.0,>=2.0 in c:\users\jonas\appdata\local\programs\python\python39\lib\site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py) (4.0.0)
Requirement already satisfied: async-timeout<4.0,>=3.0 in c:\users\jonas\appdata\local\programs\python\python39\lib\site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py) (3.0.1)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\jonas\appdata\local\programs\python\python39\lib\site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py) (1.6.3)
Requirement already satisfied: typing-extensions>=3.6.5 in c:\users\jonas\appdata\local\programs\python\python39\lib\site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py) (3.10.0.0)
Requirement already satisfied: idna>=2.0 in c:\users\jonas\appdata\local\programs\python\python39\lib\site-packages (from yarl<2.0,>=1.0->aiohttp<3.8.0,>=3.6.0->discord.py) (3.2)

**Comment by MinnDevelopment** [comment]
You forgot the `()` on your initialization. It should be `client = MyClient()` instead.

**Comment by Z3yf1re** [comment]
> You forgot the `()` on your initialization. It should be `client = MyClient()` instead.

Thank you!
That was my big mistake.

Sorry for this simple question, im at my first letters of code ^^
