### ISSUE TITLE
client.change_presence() does not change playing status

### ISSUE THREAD

**Issue by ZetaRift** [Rapptz/discord.py#746]
Despite being called correctly, `change_prescence()` does not appear to change playing status on the account it's connected to, I've also tried this on a standard account alongside a bot account, but that didn't work. No exceptions are being thrown either.
```
await client.change_presence(game=discord.Game(name=args)) # In this context, args is a user input variable
# Or this
await client.change_presence(game=None) 
```

**Comment by ReinaSakuraba** [comment]
Make sure to update to the latest version as this has already been fixed.

**Comment by ZetaRift** [comment]
Appears I was holding multiple versions of the wrapper, removed them all and then installed the latest version, that fixed the issue.
