### ISSUE TITLE
Wildcard Aliases

### ISSUE THREAD

**Issue by rudes** [Rapptz/discord.py#7461]
### Summary

Allow aliases to have * wildcards

### What is the feature request for?

discord.ext.commands

### The Problem

I could be using the flag wrong but it would be nice if i could add an alias like "*keyword*" and then my command could be called if anything using the prefix and the keyword gets called. Something like:
"*!I need help with keyword*" for example.

### The Ideal Solution

`@commands.command(aliases=['*keyword*'])` 
or another option might be a new flag
`@commands.command(wildcard=True)` 
to accept any command containing the function name or the name parameter if set

### The Current Solution

using the `on_message` event to catch the wildcard without the commands package

**Comment by NCPlayz** [comment]
You could dynamically create commands with the keyword as a name assuming you store responses.

**Comment by Rapptz** [comment]
Sorry, I have no plans for this one. The system doesn't work like this and it'd require a massive amount of rewriting to support a rather niche use case. This is probably better suited in `on_message`.
