### ISSUE TITLE
[v2] guild.icon.url raises error with default icon

### ISSUE THREAD

**Issue by Miolus** [Rapptz/discord.py#7468]
### Summary

Getting the url of a guild's icon which is default raises an error, it didn't raise an error before v2.

### Reproduction Steps

Get icon url from a guild with a default icon.

### Minimal Reproducible Code

```python
#guild = get some guild with default icon.
guild.icon.url
```

### Expected Results

Return the url

### Actual Results

Command raised an exception: AttributeError: 'NoneType' object has no attribute 'url'

### Intents

members

### System Information

d.py 2.0, Python 3.9

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by ironman9356** [comment]
This happens to me too but i just use `try:` and `except:`  to solve this

**Comment by Rapptz** [comment]
Not a bug. In v1.x `Guild.icon_url` returned an empty `Asset` which resolved to no URL. In v2.x the more sensible thing is to return `None` for `Guild.icon` and then the `url` would resolve to something valuable. If you want to avoid this then check if the guild has an icon in the first place using `if guild.icon`.
