### ISSUE TITLE
`TextInput` should have `__str__` function

### ISSUE THREAD

**Issue by HippoBaguette** [Rapptz/discord.py#7504]
### Summary

Give `TextInput` a `__str__` function which just gives the `value` property

### What is the feature request for?

The core library

### The Problem

```py
class TestModal(discord.ui.Modal, title = "Test"):
    question = discord.ui.TextInput(label = "Yes or No?")

    async def on_submit(self, interaction):
        await interaction.response.send_message(f"{self.question}", ephemeral = True)
```
Instead of saying "Yes" it sends
```
<TextInput label='Yes or No?' placeholder=None required=True>
```

### The Ideal Solution

The `__str__` function returning the `value` property

### The Current Solution

```py
await interaction.response.send_message(f"{self.question.value}", ephemeral = True)
```

**Comment by Rapptz** [comment]
Note that `TextInput.value` is `Optional[str]` and not `str` so it'd need a default for the `None` case (realistically, an empty string). I don't think any other `ui` actually have special methods like these which could also be considered an oversight.
