### ISSUE TITLE
Fix a simple error in the modal example 

### ISSUE THREAD

**Issue by dannynotsmart** [Rapptz/discord.py#7509]
### Summary

Instead of having it send `self.name`, have it send `self.name.value`

### Reproduction Steps

I ran the example code, and it sent the repr of the TextInput object, rather than the actual value, which I think is what this example is trying to do.

### Minimal Reproducible Code

```python
class Questionnaire(ui.Modal, title='Questionnaire Response'):
    name = ui.TextInput(label='Name')
    answer = ui.TextInput(label='Answer', style=discord.TextStyle.paragraph)

    async def on_submit(self, interaction: discord.Interaction):
        await interaction.response.send_message(f'Thanks for your response, {self.name}!', ephemeral=True)
```

### Expected Results

It would’ve sent,
`Thanks for your response, {…}!`
where … is the value you got from the name TextInput object 

### Actual Results

It sent `<TextInput label='Name'>`

### Intents

None

### System Information

I cannot get the version currently, but it is with the newest 2.0, with all the modals. 
The reason as to why I cannot get the version is because I am on mobile

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context
I hate to be nit picky. But I feel it’s important to point this out because there are people who solely rely on examples to learn, and this might confuse them if they can’t read docs or source code.

**Comment by bijij** [comment]
`self.name` would implicitly work here because TextInput impliments `__str__` it might be good to be explicit though.

**Comment by dannynotsmart** [comment]
Ah, my mistake. I wrote that bug when there was no `__str__` impl.
