### ISSUE TITLE
help with ban command

### ISSUE THREAD

**Issue by RudeBois** [Rapptz/discord.py#752]
Code:
https://pastebin.com/fu8i3znX

The hierarchy error message doesn't send, nor does the ban even work. The bot has adequate permissions.

**Comment by RudeBois** [comment]
by the way, i didnt include tracebacks or errors because none were given

**Comment by Rapptz** [comment]
These questions are better suited for the [official Discord API server](https://discord.gg/discord-api).

However, you have a few issues:

1. You're missing `pass_context=True` to the `@bot.command()` decorator.
2. You spelled `discord` as `discird`.
3. Your hierarchy check is done *after* you ban, you probably meant to do it before.

**Comment by RudeBois** [comment]
@Rapptz none of these changes fixed the problem

**Comment by Rapptz** [comment]
Well this is for issues with the library not with help debugging your code. So if you want to receive help go to the Discord API server and try to debug the issue yourself.
