### ISSUE TITLE
Improve App Command Sync

### ISSUE THREAD

**Issue by Luc1412** [Rapptz/discord.py#7534]
### Summary

Implement a more user-friendly and efficient app command sync.

### What is the feature request for?

The core library

### The Problem

Danny's Update states "The library does not offer automatic syncing. The user is responsible for this."

Especially for newcomers to the programming world, it can be very difficult to implement a good method for synchronizing commands. Even from the point of view of an advanced Py programmer, such a method can be very useful.

The current implementation can cause some problems. For example, calling it on every startup in a staging or multi-cluster bot scenario would cause serious rate limiting problems. In Prod, it can cause each restart to mean 1 hour of downtime as all commands are re-registered.

The only alternative way to use this in Prod is to register commands manually. This can be very annoying.
For development, there is no real alternative but to implement this feature request itself.

For editing commands while the bot is running, the sync loop is completely useless.

### The Ideal Solution

 Improved synchronization first fetches all commands. 
Then it scans the internal command cache and prepares a payload of commands that need to be updated.
Finally, the sync decides whether to perform a bulk update or add/remove commands manually.
  
  This method should provide the following options:
  - Force all commands to be synced (similar to current implementation).
  - Disable deletion of commands
  - Synchronize only global or guild commands

### The Current Solution

The current solution force sync all commands.

**Comment by drobotk** [comment]
I can't see how your Ideal Solution would solve rate limit problems. You'll actually end up making more API requests that way.

**Comment by Luc1412** [comment]
> I can't see how your Ideal Solution would solve rate limit problems. You'll actually end up making more API requests that way.

Currently you would call `.sync()` on any bot startup which bulk updates all commands.At least in Straging.

The improved sync would only add, remove or edit the commands you changed. If you just make changes to the callback it wouldn't update the commands at all.

**Comment by drobotk** [comment]
> The improved sync would only add, remove or edit the commands you changed.

But to know which commands have changed, you need to fetch them first, and that's an API request.

Current approach is just:
 - bulk sync all commands


Your approach would be:
 - fetch commands
 - maybe sync if something has changed

Your solution would make as many or more API requests as the current method, but never less.
(correct me if I'm not understanding something correctly)

**Comment by nerdguyahmad** [comment]
> Currently you would call `.sync()` on any bot startup which bulk updates all commands. At least in staging.

@Luc1412 You don't have to call `sync()` on every bot startup.

```py
client = discord.Client()
client.sync_tree = True # Set it to False when you don't want to sync.
tree = app_commands.CommandTree(client)

@client.event
async def on_ready():
  if client.sync_tree:
    print("Syncing commands tree.")
    await tree.sync()
    client.sync_tree = False
  
  print("Ready")

@tree.command()
async def foo(interaction):
  ...
```

Synchronisation as you describe it, will actually result in library making even more API calls behind user's back. Quoting Danny:

> A library should never make HTTP requests behind your back, especially ones that have rate limits that are between an hour to a day long.

**Comment by Luc1412** [comment]
> But to know which commands have changed, you need to fetch the existing ones first, and that's an API request.
> 
> Current approach is just:
> 
> * bulk sync all commands
> 
> Your approach would be:
> 
> * fetch commands
> * maybe sync if something has changed
> 
> Your solution would make as many or more API requests as the current method, but never less. (correct me if I'm not understanding something correctly)

@drobotk That's right. But bulk updating has way lower rate limits than just fetching commands.
It's not about the amount of requests, it's more about the ratelimits for those single requests and 1h delay for all commands instead of single commands.


> > Currently you would call `.sync()` on any bot startup which bulk updates all commands. At least in staging.
> 
> @Luc1412 You don't have to call `sync()` on every bot startup.

@nerdguyahmad Sure, but in staging it's more convenient to call it on every startup. And in prod a inexpensive get request doesn't matter that much.

> ```python
> client = discord.Client()
> client.sync_tree = True # Set it to False when you don't want to sync.
> tree = app_commands.CommandTree(client)
> 
> @client.event
> async def on_ready():
>   if client.sync_tree:
>     print("Syncing commands tree.")
>     await tree.sync()
>     client.sync_tree = False
>   
>   print("Ready")
> 
> @tree.command()
> async def foo(interaction):
>   ...
> ```
> 
> Synchronisation as you describe it, will actually result in library making even more API calls behind user's back. Quoting Danny:
> 
> > A library should never make HTTP requests behind your back, especially ones that have rate limits that are between an hour to a day long.

The user decides when to call `sync()`. Currently it will do one expensive PUT request. 
My suggestion would do a inexpensive GET request. Maybe followed by a expensive PUT or less expensive POST/DELETE/PATCH requests.

**Comment by Luc1412** [comment]
Here some cases where the current sync will fail:

## Case 1: Updating the bot 
A bot with 30 app commands pushes a update where one new command will be added and one will be updated
-> Discord.py will bulk update all commands instead of just doing a POST and PATCH

## Case 2: Updating the bot on runtime
A bot with 30 commands likes to update 1 commands option choices on runtime (as described here: https://github.com/Rapptz/discord.py/issues/7539#issuecomment-1059967245)
-> Discord.py will bulk update all commands instead of just doing just one PATCH

## Case 3: Working on bot in staging
A bot with 30 app commands is in development. The most convenient way is calling `.sync()` on connect if the bot is in staging mode.
->Discord.py would bulk update all commands instead of just doing single POST/PATCH/DELETE requests or just the initial get.

**Comment by GoogleGenius** [comment]
I think instead of bulk setting all commands with the current implementation, it should dynamically check whether the commands in code match with those registered to the API and only send a request if the command is added, edited, or removed to update it.

This was the implementation of the discord-py-slash-command library I believe.

**Comment by Rapptz** [comment]
According to Discord and a few other library developers I talked to, using the bulk upsert like I'm doing now is the preferred method of syncing commands over. All 3 cases you mentioned are already handled by the bulk upsert endpoint just fine and I'm not really sure the extra machinery and requests are worth it. If commands haven't changed then they don't count towards the daily creation limit so using it should be safe.

If you think there's anything that should be serviced by adding more complicated machinery to do the diff locally rather than letting Discord do it themselves, feel free to let me know but for now it seems like the current approach taken is fine by Discord.
