### ISSUE TITLE
Add custom Interaction (Context) Support

### ISSUE THREAD

**Issue by Luc1412** [Rapptz/discord.py#7549]
### Summary

Add custom Interaction (Context) Support

### What is the feature request for?

The core library

### The Problem

Currently there is no equivalent for the text command custom context. This can be very useful to provide functions that can retrieve data from the database or providing other shortcuts.

#### `ApplicationContext`/`InteractionContext`
Provides an `ApplicationContext` in the callback that embeds the interaction. Similar structure to the context of the text commands. The custom context can be implemented like the custom context of the text commands.

#### Custom interaction
This is an alternative consideration and would also benefit views. For example, a `get_interaction` could solve this. Not sure if Discord models should be modified so a separated context class might be better.

**Comment by Rapptz** [comment]
There are no plans for a "Context" class for app_commands (or views). The feature requires a specific hook which would be hard to place (in the tree? in the client?) not to mention it'd have to be stored somewhere and called and would have to work with type checkers. While technically possible, I'm not sure it's worth the effort involved considering the alternatives.

If you want custom functionality, it might be better off in your client subclass since you can access it via `interaction.client`.

**Comment by Luc1412** [comment]
> There are no plans for a "Context" class for app_commands (or views). The feature requires a specific hook which would be hard to place (in the tree? in the client?) not to mention it'd have to be stored somewhere and called and would have to work with type checkers. While technically possible, I'm not sure it's worth the effort involved considering the alternatives.

@Rapptz At least from a customization standpoint it might be not worth to do that effort. At least for now with the set deathline. As a huge breaking change is possible wouldn't be possible to implement it before v3.
From a usability perspective it might make sense as responding became a bit more complex since the release of Slash Commands. Instead of `ctx.send` you have to use `interaction.response.send_message` (not to forget that Jetbrains IDE won't provide intellisense for `interaction.response`)

I think a `ctx.defer()`,  `ctx.respond()` `ctx.send_modal()` would come in handy to make migration as simple as possible.

**Comment by Rapptz** [comment]
There are plans for some interop for hybrid commands or regular commands but that doesn't necessarily mean that Interaction will be customisable. Another problem with Interaction is that the constructor relies on private types.

**Comment by ArthurKun021** [comment]
> > There are no plans for a "Context" class for app_commands (or views). The feature requires a specific hook which would be hard to place (in the tree? in the client?) not to mention it'd have to be stored somewhere and called and would have to work with type checkers. While technically possible, I'm not sure it's worth the effort involved considering the alternatives.
> 
> @Rapptz At least from a customization standpoint it might be not worth to do that effort. At least for now with the set deathline. But otherwise as a huge breaking change is possible wouldn't be possible to implement it before v3. From a usability perspective it might make sense as responding became a bit more complex since the release of Slash Commands. Instead of `ctx.send` you have to use `interaction.response.send_message` (not to forget that Jetbrains IDE won't provide intellisense for `interaction.response`)
> 
> I think a `ctx.defer()`, `ctx.respond()` `ctx.send_modal()` would come in handy to make migration as simple as possible.

Have you solved this? `(not to forget that Jetbrains IDE won't provide intellisense for interaction.response)`. Pycharm can't detect the functions below Interaction.response

**Comment by Rapptz** [comment]
This isn't my problem to solve.

Pycharm does not understand descriptors or most complicated typing features. Note that this issue does not happen with other more reliant type checkers such as Pyright or mypy.
