### ISSUE TITLE
Announce newly joined users 

### ISSUE THREAD

**Issue by seanwlk** [Rapptz/discord.py#755]
Is there any easy way to check for newly joined users and do a certain routine?

**Comment by SourSpoon** [comment]
http://discordpy.readthedocs.io/en/latest/api.html#discord.on_member_join

Will give details about the member who joined.

**Comment by seanwlk** [comment]
ok that works, but what if the same bot is in multiple servers? It will grab joined people in all servers, can i sort an action for specific servers?
My bot is currently being used in 3 different servers but i want to add this join feature to only one of the servers.

**Comment by SourSpoon** [comment]
Member is not the same as user.

Member contains information about the server the user belongs to.

**Comment by seanwlk** [comment]
but for example if i make my bot send me an email every time a user joins, if i do this:

`@client.event`
`    async def on_member_join(member):`
`        string=str(member)+" joined"`
`        mail_log_f(subject,string)`
i will send me an email every time an user joins whatever of he 3 servers, but i want notifications only for 1

**Comment by SourSpoon** [comment]
http://discordpy.readthedocs.io/en/latest/api.html#discord.Member.server
http://discordpy.readthedocs.io/en/latest/api.html#discord.Server

You can just do an if.

**Comment by seanwlk** [comment]
thanks mate 👍  😄

**Comment by SourSpoon** [comment]
In future questions like this are better suited for the [official Discord API server](https://discord.gg/discord-api).

**Comment by xernphoton** [comment]
or the discordpy server

**Comment by iomintz** [comment]
@xernphoton the discord.py server was not suggested because it _literally did not exist yet_. Don't necrobump old issues.
