### ISSUE TITLE
Fire on member remove event even if the member is not cached

### ISSUE THREAD

**Issue by AmeyWale** [Rapptz/discord.py#7554]
### Summary

discord.py should fire on member remove event if the member member is cached or not cached

### What is the feature request for?

The core library

### The Problem

In order to use some member events like on_member_remove, etc, discord.py implements member cache to fire these events, when the bot sees more users, caching members takes a lot of ram. I think that on_member_remove event should be fired even if the member is not cached . 

### The Ideal Solution

To fire on member remove event if the member is cached or is not cached

### The Current Solution

I use on_socket_raw_receive event to get the raw member remove event, this takes a lot of cpu, I do not really know why it takes a lot of cpu when you have `enable_debug_events=True` in the bot constructor

**Comment by nerdguyahmad** [comment]
Library has to resolve the member from cache on these events because the data sent by Discord is incomplete (partial) and a new member instance cannot be created from that data.

**Comment by Rapptz** [comment]
This is planned during the eventual event refactor.
