### ISSUE TITLE
getch and get_message

### ISSUE THREAD

**Issue by CaedenPH** [Rapptz/discord.py#7556]
### Summary

creating a getch method and a get_message

### What is the feature request for?

The core library

### The Problem

It is sometimes annoying having to build your own getch methods when trying to write extra code. same goes for get_message, making an api call to a channel may be a pain.

### The Ideal Solution

just implementing methods into bot_base. other forks have done this and it works quite efficiently.

### The Current Solution

```py
def getch_xyz(...) -> Optional[xyz]:
     # first get
     # if that fails, fetch
```
and `get_message` just scrapes internal cache

**Comment by ImVaskel** [comment]
This has been talked about and denied before, see #7524.

**Comment by CaedenPH** [comment]
> This has been talked about and denied before, see #7524.

Thought it probably had been, but thought it was worth a shot.
