### ISSUE TITLE
`interaction.response.edit_message` Does Not Work in the `discord.ui.Modal` Class

### ISSUE THREAD

**Issue by Pysics** [Rapptz/discord.py#7577]
### Summary

`interaction.response.edit_message` does not work in the callback function for the `discord.ui.Modal` class.

### Reproduction Steps

1. Clone the latest version of `discord.py` from GitHub.
2. Use the code below.

### Minimal Reproducible Code

```python
class MyModal(Modal, title='Modal'):
    input_1 = TextInput(label="Short Input", placeholder="Placeholder Test")
    input_2 = TextInput(label="Longer Input", style=discord.TextStyle.long)
        
    async def on_submit(self, interaction: discord.Interaction):
        embed = discord.Embed(title="Your Modal Results", color=discord.Color.random())
        embed.add_field(name="First Input", value=self.input_1, inline=False)
        embed.add_field(name="Second Input", value=self.input_2, inline=False)
        await interaction.response.edit_message(embeds=[embed])
 
button = Button(label="Open Modal")
async def callback(interaction):
    modal = MyModal()
    await interaction.response.send_modal(modal)
button.callback = callback

view = View()
view.add_item(button)

await ctx.send("Hello", view=view)
```

### Expected Results

The original message should be edited with an embed.

### Actual Results

[This](https://media.discordapp.net/attachments/881309521610412082/944601730220445706/unknown.png) is the error that comes in the modal window and the message is not edited. There is no error.

### Intents

None

### System Information

Python 3.10
`discord.py` `master` Branch (on GitHub)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by LostLuma** [comment]
As the docs for `InteractionResponse.edit_message` state, this method can only be used to edit the message from an interaction created by using a message component such as a Button or Select menu:

 `Responds to this interaction by editing the original message of a component interaction.`

Responding to a an interaction originating from a message component with a Modal and then submitting it creates a new interaction which does not originate from a message component, but rather the Modal. If you run into further issues please ask in the #beta-testing channel on the [official support server](https://discord.gg/r3sSKJJ) for someone else to reproduce the bug or help you resolve it before opening an issue here.

**Comment by Pysics** [comment]
Then, is there a way to edit the message?

**Comment by LeoCx1000** [comment]
`interaction.message.edit`

**Comment by Pysics** [comment]
> `await interaction.message.edit(...)`

Thanks! This worked.

**Comment by KursK-sys** [comment]
> `await interaction.message.edit(...)`

I try this but : 

`discord.app_commands.errors.CommandInvokeError: Command 'aide' raised an exception: AttributeError: 'NoneType' object has no attribute 'edit'`

**Comment by V1NI1313** [comment]
Try:
`message = await interaction.original_response()`
`await message.edit(...)`

**Comment by V1NI1313** [comment]
> > `await interaction.message.edit(...)`
> 
> I try this but :
> 
> `discord.app_commands.errors.CommandInvokeError: Command 'aide' raised an exception: AttributeError: 'NoneType' object has no attribute 'edit'`

Try:
`message = await interaction.original_response()`
`await message.edit(...)`
or:
`await interaction.edit_original_response(...)`

**Comment by MTMrAlone** [comment]
> 

404 Not Found (error code: 10015): Unknown Webhook

**Comment by MTMrAlone** [comment]
> > > `await interaction.message.edit(...)`
> > 
> > 
> > I try this but :
> > `discord.app_commands.errors.CommandInvokeError: Command 'aide' raised an exception: AttributeError: 'NoneType' object has no attribute 'edit'`
> 
> Try: `message = await interaction.original_response()` `await message.edit(...)` or: `await interaction.edit_original_response(...)`

404 Not Found (error code: 10015): Unknown Webhook
