### ISSUE TITLE
How to get

### ISSUE THREAD

**Issue by rivermont** [Rapptz/discord.py#758]
Looks like it prematurely submitted itself?

Anyway, I am trying to get a list of all channels that the `client` has read/post access to, in all channels the `client` has access to. My current code is as follows:

```for server in client.servers:
   for channel in server.channels:
       if channel.type == 'text':
           print(channel.permissions_for(client)
```

I was then going to figure out the format of the return of `permissions_for` and test if the bot has access. However this never seems to run. I get no output nor error. Any ideas?

**Comment by khazhyk** [comment]
Specific questions on how to use the library are better suited to the [official Discord API server](https://discord.gg/discord-api). You may also find the [documentation](http://discordpy.rtfd.io/en/latest/) useful.
