### ISSUE TITLE
Add app commands in cogs

### ISSUE THREAD

**Issue by NarmyOnDiscord** [Rapptz/discord.py#7583]
### Summary

Add a way to get the tree defined with your client into the cog to use the decorator inside

### What is the feature request for?

The core library

### The Problem

You can't use the @tree.command() decorator in a cog

### The Ideal Solution

Make it possible to use the decorator in some way

### The Current Solution

Currently, you'd have either to define a new tree in every cog and then add every command in the `__init__` via `tree.add_command()` or define the tree in the main.py as `bot.tree = ...` and use `bot.tree.add_command()` in the `__init__` of your cog

**Comment by GoogleGenius** [comment]
@Rapptz Is 446bfa78b03cff8a837f510c4a7d8255c2d76b7d the full implementation for App Command Cogs?

**Comment by Rapptz** [comment]
Yes, this allows you to define app commands inside a cog and the cog would be aware of it on add/remove.

There's still more interop work to be done but that should be enough for this particular issue.
