### ISSUE TITLE
Channels not being removed from the cache

### ISSUE THREAD

**Issue by Pandentia** [Rapptz/discord.py#759]
On rare occasions, channels that have been deleted can stick around in the cache and be returned when using `client.get_channel`. I'm not quite sure what causes this, maybe there should be a `get_channel` equivalent for a direct API query?

**Comment by Gorialis** [comment]
Channels are removed from the cache when they are no longer referenced. It's possible you have messages in your cache that still reference the deleted channel and therefore it won't be removed until these messages are pushed out of the cache.

**Comment by Pandentia** [comment]
I should've mentioned, the channel in question is a VoiceChannel, so I doubt references are the issue.

**Comment by Rapptz** [comment]
I don't imagine this being possible unless Discord forgets to dispatch CHANNEL_DELETE. In which case, how do you expect me to delete the channel?

**Comment by Pandentia** [comment]
I'm not quite sure how this is possible myself, however it's happened on multiple occasions now and doesn't seem to be my own code, and have had users complain about the bot wrongly detecting the existence of a channel.

**Comment by Pandentia** [comment]
I haven't been able to verify it by listening to the raw socket events, so my best guess is that the channel was deleted during a short disconnect and the bot therefore wasn't able to receive the event and handle it accordingly, so I'll close this issue unless I find further evidence.
