### ISSUE TITLE
Context menus not being registered properly 

### ISSUE THREAD

**Issue by Robin5605** [Rapptz/discord.py#7594]
### Summary

Context menus don't show up on Discord after sync, neither do they seem to register locally.

### Reproduction Steps

Register a few basic context menus like so, as outlined in the gist:
```
@tree.context_menu(guild=TEST_GUILD)
async def bonk(interaction: discord.Interaction, member: discord.Member):
    await interaction.response.send_message('Bonk', ephemeral=True)

@tree.context_menu(guild=TEST_GUILD)
async def translate(interaction: discord.Interaction, message: discord.Message):
    await interaction.response.send_message('Translated', ephemeral=True)
```

Then attempt to print the registered commands like so:
```
@client.event
async def on_ready():
    print(f'Connected as {client.user}')
    app_commands = await tree.sync(guild=TEST_GUILD)
    for app_command in app_commands:
        print(app_command)
```

This prints nothing, which leads me to believe it was an empty list.

### Minimal Reproducible Code

```python
@tree.context_menu(guild=TEST_GUILD)
async def bonk(interaction: discord.Interaction, member: discord.Member):
    await interaction.response.send_message('Bonk', ephemeral=True)

@tree.context_menu(guild=TEST_GUILD)
async def translate(interaction: discord.Interaction, message: discord.Message):
    await interaction.response.send_message('Translated', ephemeral=True)
```

### Expected Results

Register the context menu in discord, and print out all the commands locally as well.

### Actual Results

The context menu was not registered in discord (does not show up when right clicking user OR message), and nothing is printed either.

### Intents

discord.Intents.default() (I do not believe this is important to the issue)

### System Information

- Python v3.10.2-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3789+g19aa5633
- aiohttp v3.7.4.post0
- system info: Linux 5.16.12-arch1-1 #1 SMP PREEMPT Wed, 02 Mar 2022 12:22:51 +0000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I actually can't really be sure if this is me messing something up, or something wrong with the internals of discord.py itself, as the documentation for the time being on this is very scarce.

I did some additional testing on my own, and have narrowed it to [this](https://github.com/Rapptz/discord.py/blob/master/discord%2Fapp_commands%2Ftree.py#L471) part of the code:

```
...
except KeyError:
    return [cmd for ((_, g, _), cmd) in self._context_menus.items() if g is None]
...
```

Changing that to this seems to fix the issue:
```
...
except KeyError:
    return [cmd for ((_, g, _), cmd) in self._context_menus.items()]
...
```
(Removing `if g is None`)

Doing this registers the slash command in Discord, 
```
app_commands = await tree.sync(guild=TEST_GUILD)
for app_command in 
    print(app_command)
```
Correctly prints out both test commands, and using them in Discord works flawlessly.

Now, I do want to add, I'm not all that good with the internals of the library, so I can't exactly tell what the variable `g` is in this case, and I also can't be sure that it breaks anything crucial. It's simply a solution that worked for me. I hope that, given this is a bug within discord.py, it could point someone in the right direction to fixing it. If it's something I did wrong, please feel free to close this.

**Comment by Rapptz** [comment]
Hello, thanks for the bug report.

I can't seem to be able to reproduce it though. Checking the internal data structures and calling the function it works as I expect. 
I'm also not sure why your commit shows 3789 when there have only been 3782 commits to master.

**Comment by Robin5605** [comment]
Looks like it was just on my end, was able to fix without messing with the internals. Thanks for the help!
