### ISSUE TITLE
TypeError: An asyncio.Future, a coroutine or an awaitable is required

### ISSUE THREAD

**Issue by tuna2134** [Rapptz/discord.py#7595]
### Summary

TypeError: An asyncio.Future, a coroutine or an awaitable is required

### Reproduction Steps

run a bot and using a on_ready event

### Minimal Reproducible Code

```python
from discord.ext import commands

bot = commands.Bot(command_prefix="hb?")

@bot.event
async def on_ready():
    print("ready")
```

### Expected Results

dispatch a on_ready event

### Actual Results

![73C14027-D971-4C40-B972-4ACD68DEFC1E](https://user-images.githubusercontent.com/45692264/157163747-ab744f18-2f28-4570-8172-d0a2783ece10.jpeg)

### Intents

discord.Intents.all()

### System Information

- Python v3.10.2-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3780+gacbd8ca
- aiohttp v3.7.4.post0
- system info: Linux 4.18.0-348.12.2.el8_5.x86_64 #1 SMP Wed Jan 19 17:53:40 UTC 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by JDJGInc** [comment]
try updating and see if fixes the issue.

**Comment by Rapptz** [comment]
Already fixed.

**Comment by tuna2134** [comment]
Oh
thanks
