### ISSUE TITLE
Allow app command options to be named in a non-pythonic way

### ISSUE THREAD

**Issue by Luc1412** [Rapptz/discord.py#7599]
### Summary

Allow app command options to be named in a non-pythonic way

### What is the feature request for?

The core library

### The Problem

Currently command option names will be taken from the callback parameter. This can cause bad practice or even completely limits the names. Some examples:
- example-option
- 1test
- type (shadows built-in type function)

### The Ideal Solution

This can be implemented on two ways simultaneously:

### Decorator:
```py
@app_commands.option_name(
    test1="1test"
)
async def test(interaction: discord.Interaction, test1: int)
``` 

### #7539:
```py
tree.add_command(app_commands.Command(options=[...]))
```

**Comment by adshivsat** [comment]
Core impact
