### ISSUE TITLE
If a guild and global command have the same name, the guild command will always be invoked.

### ISSUE THREAD

**Issue by Matthew1177** [Rapptz/discord.py#7602]
### Summary

If a guild and global command have the same name, the guild command will always be invoked regardless of which is called.

### Reproduction Steps

- Create a guild command and global command with the same name
- Run both and observe

### Minimal Reproducible Code

```python
import discord
from discord import app_commands

bot = discord.Client()
tree = app_commands.CommandTree(bot)


@tree.command(name="test", description="global")
async def test_global(inter: discord.Interaction):
    await inter.response.send_message("global command")


@tree.command(name="test", guild=discord.Object(GUILD_ID), description="guild")
async def test_guild(inter: discord.Interaction):
    await inter.response.send_message("guild command")


@bot.event
async def on_ready():
    await tree.sync(guild=discord.Object(GUILD_ID))
    await tree.sync()


bot.run(TOKEN)
```

### Expected Results

When running the global `/test`, the global `/test` is invoked.

### Actual Results

When running the global `/test`, the guild `/test` is invoked.

### Intents

discord.Intents.default()

### System Information

- Python v3.10.1-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3786+g3d74da8
- aiohttp v3.7.4.post0

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

This causes a CommandSignatureMismatch if the guild command has a different signature than the global command.

**Comment by Rapptz** [comment]
Differentiating this requires storing the IDs I think, which currently I don't do. It'd be nice if Discord provided a differentiator for these but this seems unlikely.

**Comment by Rapptz** [comment]
I talked to Discord and they're going to add a way to differentiate these. Hopefully in a few API deploys it'll be possible to do this without storing the ID.
