### ISSUE TITLE
Add message cache policy/filtering

### ISSUE THREAD

**Issue by Rooni** [Rapptz/discord.py#7620]
### Summary

Allow for filtering on which messages are stored in the internal message cache

### What is the feature request for?

The core library

### The Problem

The message cache has a fixed size. When you rely on this cache you might not care about about specific types of messages that will dequeue the messages you do care about.

For example you might not care about system/join messages, which can fill up the cache really fast.

### The Ideal Solution

Maybe something that's passed into the client similar to `MemberCacheFlags` but for messages, or a callable that takes a message to evaluate if it should be cached or not. 
Honestly wouldn't know the nicest solution for this.

I'll leave it up for discussion and if this is something that's nice to have, I could create a PR with the suggested solution if no one else feels like it.

### The Current Solution

Don't think there is a proper solution for this that doesn't involve touching the message cache yourself.

### Additional Context

One obvious use case for this is being able to track deleted/edited messages more reliably, which is obviously something discord doesn't want you to do with the new message intents, so maybe this isn't worth the effort unless there's another obvious use case.

**Comment by Rapptz** [comment]
I'm dubious of anything that would complicate the MESSAGE_CREATE code path any more than it currently does, especially with a user provided callable. 

> One obvious use case for this is being able to track deleted/edited messages more reliably

Is this something that is unfeasible today with the provided raw events?

**Comment by Rooni** [comment]
> Is this something that is unfeasible today with the provided raw events?

I mean in the sense of knowing the content of what was deleted or before editing. 
With this option available you could keep messages cached significantly longer on high traffic servers without raising the cap to consider junk, though I was also hesitant if this was worth at the core. 
The second solution has insignificant overhead, but it doesn't feel like a proper solution. I don't really know.

**Comment by Rapptz** [comment]
I don't think I want to go ahead with this, sorry. It has the potential to forbid optimisation strategies in the future for me for very little benefit.
