### ISSUE TITLE
Slash autocomplete in a cog bug

### ISSUE THREAD

**Issue by Soheab** [Rapptz/discord.py#7624]
### Summary

The library still passes self if the autocomplete callable is outside the class

### Reproduction Steps

The library tries to pass in `self` as the first parameter but it does not check if the callable is in a class or not, this makes it raise the following TypeError:
```py
Traceback (most recent call last):
  File '...\lib\site-packages\discord\app_commands\tree.py", line 666, in wrapper
    await self.call(interaction)
  File "...\lib\site-packages\discord\app_commands\tree.py", line 782, in call
    await command._invoke_autocomplete(interaction, focused, namespace)
  File "...\lib\site-packages\discord\app_commands\commands.py", line 438, in _invoke_autocomplete
    choices = await param.autocomplete(self.binding, interaction, value, namespace)
TypeError: my_autocomplete() takes 3 positional arguments but 4 were given
```

### Minimal Reproducible Code

```python
from typing import List

from discord import Interaction, Intents
from discord.ext.commands import Bot, Cog
from discord.app_commands import autocomplete, command, Choice, Namespace


async def my_autocomplete(interaction: Interaction, current: str, namespace: Namespace) -> List[Choice]:
  my_list: List[str] = ["alpha", "beta", "candidate", "final"]
  return [Choice(name=value, value=value) for value in my_list if value.startwith(current)]


class MyCog(Cog):
  
  @command(name="testing_issue7624", guild=123):
  @autocomplete(example=my_autocomplete)
  async def testing_command(self, interaction: Interaction, example: str):
    await interaction.response.send_message(f"{example=}")


bot = commands.Bot("...?!", intents=Intents.none())

@bot.event
async def on_ready():
  await bot.tree.sync()

bot.add_cog(MyCog())
bot.run(...)
```

### Expected Results

It calling my_autocomplete correctly.

### Actual Results

Raised a TypeError

### Intents

Not relevant but: `guilds, emojis, presences, messages, reactions, voice_states, message_content`

### System Information

- Python v3.9.6-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3817+gd22a7fb7
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000 (11 tho)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
This bug most likely manifests regardless of it being a Cog and also manifests with regular `app_commands.Group`.

**Comment by Polsulpicien** [comment]
I got the same error, you just need to add the `self` argument and delete `, namespace: Namespace`. Works fine afterwards.
