### ISSUE TITLE
Improve error when mismatched Choice are given

### ISSUE THREAD

**Issue by Luc1412** [Rapptz/discord.py#7625]
### Summary

Provide richer feedback if `.sync()` fails.

### What is the feature request for?

The core library

### The Problem

If the command registration fails, you receive something like this:
```py
iscord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In 0.options.3.options.1.choices.0.value: Choice values must be of type "string"
In 0.options.3.options.1.choices.1.value: Choice values must be of type "string"
In 0.options.3.options.1.choices.2.value: Choice values must be of type "string"
In 0.options.3.options.1.choices.3.value: Choice values must be of type "string"
```

If you sent the payload manually as json, it's clear what's wrong. But in d.py it's hard to find the command `0.options.3.options.1` as you would need to re-create the payload yourself, with
```py
commands = tree._get_all_commands(guild=guild)
payload = [command.to_dict() for command in commands]
```
print the json and search for the command.

### The Ideal Solution

Parse the error and provide richer feedback. Instead of Indexes the command names might be helpful.

**Comment by Rapptz** [comment]
I don't think this is part of `sync`. I'm also not exactly sure how you got the library to the state where you sent invalid choices. The library should be forbidding that from happening from the get go, therefore this issue feels like an X/Y problem.

**Comment by Luc1412** [comment]
> I don't think this is part of `sync`. 

Mb maybe inside the function it might be located better. 

> I'm also not exactly sure how you got the library to the state where you sent invalid choices. The library should be forbidding that from happening from the get go, therefore this issue feels like an X/Y problem.

I set the typehint to Choice[str] but provided by mistake a Choice(name="test", value=1). So improving type checking to prevent this issue might be the better way to go.
