### ISSUE TITLE
[Enhancement] Converters raise meaningful exceptions when they fail

### ISSUE THREAD

**Issue by Tobotimus** [Rapptz/discord.py#764]
Right now, when an argument conversion fails, `commands.BadArgument` is raised with a message as its first argument, something like "Object {arg} not found".

If I want a bot to tell the user they passed in a bad argument, my only option (more or less) is to send them that message. Unfortunately, this would mean I'd also send them messages like "Unexpected quote mark in non-quoted string" when argument parsing fails, since the parser raises the same exception.

I suggest that the parsing errors and conversion errors be separate classes (derived from `commands.BadArgument`), so that bots have the option to give more concise responses to users who pass an argument in which isn't converted (or parsed) correctly, whilst not making any breaking changes.

**Comment by ButterCheezii** [comment]
I don't mean to be rude, but it would be fairly easy to make these changes yourself and submit a pull request.

**Comment by Tobotimus** [comment]
@ButterCheezii I agree, and I'm happy to do so, I just usually test the waters and see if the devs agree with the idea before PRing. But if you say so, I'll submit a PR when I get the chance
