### ISSUE TITLE
Context menu not syncing unless there are slash commands

### ISSUE THREAD

**Issue by nmsturcke** [Rapptz/discord.py#7650]
### Summary

Context menu not syncing unless there are slash commands

### Reproduction Steps

> 1. Make a bot
> 2. Create a cog and in it add a context menu (in my case I bound it to a specific guild)
> 3. Sync commands (in my case for the specific guild)

> **Observe** -  if you did not add any slash commands, the context menu won't appear

> 5. Add a slash command (in my case to the specific guild) and sync again

> **Observe** - Both the slash command and the context menus appear

### Expected Results

The context menu appears without having to add a slash command.

### Actual Results

The context menu is not available unless you add a slash command.

### Intents

discord.Intents.none()

### System Information

- Python v3.8.9-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3817+gd22a7fb7
- aiohttp v3.8.1
- system info: Darwin 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
I'm not sure what this is about.

Context menus have to be free functions, they're not supported in group contexts (e.g. `app_commands.Group` or `commands.Cog`) so it should have errored out on creation, regardless of syncing.

**Comment by nmsturcke** [comment]
# bot.py 
```py
import os
import discord
from discord.ext import commands

class Bot(commands.Bot):
    def __init__(self):
        super().__init__(command_prefix=".")

bot = Bot()

bot.load_extension("cogs.contextmenu")


async def startup():
    await bot.wait_until_ready()
    await bot.tree.sync(guild=discord.Object(699658988299616304)
    print('Sucessfully synced applications commands')
    print(f'Connected as {bot.user}')


bot.loop.create_task(startup())

bot.run('token')

```

# cogs/contextmenu.py

```py
import discord
from discord.ext import commands
from discord import app_commands

@app_commands.context_menu(
    name="Contextmenu"
)
@app_commands.guilds(699658988299616304)
async def ctxmenu(interaction: discord.Interaction, message: discord.Message):
    await interaction.response.send_message("Hey!")

class ContextMenu(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        try:
            self.bot.tree.add_command(ctxmenu, guild=discord.Object(699658988299616304))
            print("added")
        except:
            self.bot.tree.remove_command("Contextmenu", guild=discord.Object(699658988299616304), type=discord.AppCommandType.message)
            self.bot.tree.add_command(ctxmenu, guild=discord.Object(699658988299616304))

            pass
    
    # @app_commands.command(name="slash", description="A random slash command")
    # @app_commands.guilds(699658988299616304)
    # async def slash(self, interaction: discord.Interaction):
    #     await interaction.response.send_message("hey")

def setup(bot):
    bot.add_cog(ContextMenu(bot))
```

If the slash command is commented, the contextmenu doesn't appear. However, if you uncomment the slash command and restart the bot, both appear.

**Comment by Rapptz** [comment]
I can't reproduce this.

![image](https://user-images.githubusercontent.com/1695103/158014211-7f5453da-9cbb-428e-8abf-2b19600050dc.png)

**Comment by atomflunder** [comment]
I have the exact same issue and I can reproduce this on my end with the code snippet above. When I have no slash commands registered at all, the context commands do not sync. When I have one or more slash commands registered in any file, it works properly.
