### ISSUE TITLE
message.content blank on VSC but not on replit

### ISSUE THREAD

**Issue by TacocaTYT** [Rapptz/discord.py#7653]
### Summary

trying to use message.content on VSC reveals message.content is not received

### Reproduction Steps

after setting up my VSC environment for bot developing, i copy pasted my existing bot from a repl.it project into VSC. upon running, no commands were detected and no message.content strings were returned when a message was detected, but other content such as message.author and message.channel are received. I noticed this when running the code below, and decided to check if it still wokred on repl.it, which for some reason it did. this means that code works in one environment and not the other.

![image](https://user-images.githubusercontent.com/37640938/158005509-e752ccff-009f-49d5-a282-30e3caa55f3c.png)

The image shows the result of running the below code with repl.it, and then with VSC

message.content not being received also means commands do not work

### Minimal Reproducible Code

```python
import discord
from discord.ext import commands

token = "TOKEN"

client = commands.Bot(command_prefix="b|", case_insensitive = True)

@client.listen()
async def on_message(message):
  if message.author != client.user:
    await message.channel.send(f"{message.content} sent by {message.author}")

client.run(token)
```

### Expected Results

both environments should print {message.content} sent by {message.author}

### Actual Results

repl.it allows {message.content} sent by {message.author}

VSC only allows sent by {message.author}

### Intents

intents = bot

### System Information

- Python v3.10.2-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3836+g206c3402
- aiohttp v3.8.1
- system info: Windows 10 10.0.19042

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### Additional Context

there is a chance this is an error from how i have set up my environment, but other users have assisted in setting things up and in fixing this error with no progress whatsoever

**Comment by ImVaskel** [comment]
you need the ``message_content`` privileged intent to see message content on master, due to api v10 requiring it.

**Comment by TacocaTYT** [comment]
in testing this to find the issue, I ran it in several intent configurations, including having message_content intent = True in my code and enabling it in the developer portal. I forgot to paste the most recent code I ran but it was not an issue of intent privileges within code or developer portal.
