### ISSUE TITLE
support for creating activities

### ISSUE THREAD

**Issue by sifte** [Rapptz/discord.py#7655]
### Summary

Support for creating activities inside of voice channels.

### What is the feature request for?

The core library

### The Problem

Creating activities 

### The Ideal Solution

None

**Comment by Luc1412** [comment]
That's already possible. When creating an invite you can provide a target_type=TargetType.embedded_application and application_id.

**Comment by Pysics** [comment]
@Luc1412 Is it possible for you to provide some code?

**Comment by sifte** [comment]
> @Luc1412 Is it possible for you to provide some **reproducible** code?
```py
invite = await ctx.author.voice.channel.create_invite(
        target_application_id=902271654783242291,
        target_type=discord.InviteTarget.embedded_application
        )
return invite 
``` 
Creates a sketch game activity

**Comment by Pysics** [comment]
@sifte I guess you can close this issue now.
