### ISSUE TITLE
`guild` and `guilds` make no effect

### ISSUE THREAD

**Issue by m1raynee** [Rapptz/discord.py#7657]
### Summary

`guild` and `guilds` in `add_cog` function make no effect on commands in cog

### Reproduction Steps

I was trying to understand how this kwargs works and found it.

### Minimal Reproducible Code

```python
# cog.py
class Cog(commands.Cog):
    @app_commands.command()
    async def ping(self, inter):
        ...

def setup(bot):
    bot.add_cog(Cog(), guild=discord.Object(GUILD_ID))

# main.py
bot.load_extension('cog')
```

### Expected Results

```python
bot.tree.get_commands(guild=discord.Object(GUILD_ID))  #  [<discord.app_commands.commands.Command ...>]
bot.tree.get_commands()  # None
```

### Actual Results

```python
bot.tree.get_commands(guild=discord.Object(GUILD_ID))  # None
bot.tree.get_commands()  #  [<discord.app_commands.commands.Command ...>]
```

### Intents

default

### System Information

- Python v3.10.1-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3843+gd921a039
- aiohttp v3.8.1
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I made a research and came to the conclusion that the root of the issue is here ([ext/commands/bot.py#L608](https://github.com/Rapptz/discord.py/blob/master/discord/ext/commands/bot.py#L608)) and/or here ([ext/commands/cog.py#L503](https://github.com/Rapptz/discord.py/blob/master/discord/ext/commands/cog.py#L503))

**Comment by AbstractUmbra** [comment]
I understand the confusion here, however this is an implementation details.
The correct way to add a specific "free" application command to a guild is to use the `@app_commands.guilds()` decorator, like so:

```py
# cog.py
class Cog(commands.Cog):
    @app_commands.command()
    @app_commands.guild(your_guild_id)
    async def ping(self, inter):
        ...

def setup(bot):
    bot.add_cog(Cog())

# main.py
bot.load_extension('cog')
```

The `guild` and `guilds` parameters of `Bot.add_cog` only apply when the Cog itself is when the class subclasses both `commands.Cog` and `app_commands.Group`.

**Comment by m1raynee** [comment]
So there is no way I can attach all "free" commands in a cog to the same guild?

**Comment by AbstractUmbra** [comment]
You can instead subclass both `Cog` and `Group`:

```py
class MyCog(commands.Cog, app_commands.Group, name="Parent"):
  def __init__(self, bot: ...) -> None:
    self.bot = bot
    
  @app_commands.command()
  async def my_command(self, interaction: discord.Interaction) -> None:
    ...
```

**Comment by m1raynee** [comment]
Yes, but then they will no longer be "free", so there is no such thing. You can reopen the issue if there is.

**Comment by Rapptz** [comment]
Right now, the `guild` and `guilds` keyword arguments only do anything if the cog is also a group. I figured the remaining uses of `guild` and `guilds` would be done via the decorators. I guess the fact this issue exists means that the behaviour is surprising, so I suppose I should make it so it applies regardless of whether the cog is a group or not.
