### ISSUE TITLE
Calling client.close() doesn't set client.is_closed to true

### ISSUE THREAD

**Issue by ChasL** [Rapptz/discord.py#766]
Pretty self explanatory. Any loop such as "while not client.is_closed" will just continue running when it shouldn't since client.is_closed is still false even after calling client.close().

**Comment by Rapptz** [comment]
Cannot reproduce this.

Note that in the rewrite you need parentheses since it was changed to a member function.

**Comment by ChasL** [comment]
I'm currently using version 0.16.11. By adding a parenthesis I'm assuming you mean client.is_closed()? That just gives me a TypeError: 'bool' object is not callable

**Comment by ChasL** [comment]
Actually ignore me. I misdiagnosed the problem being client.is_closed not being set. That is not my problem and it is correctly getting set. Sorry for the trouble
