### ISSUE TITLE
Empty Message Content for channel.history()

### ISSUE THREAD

**Issue by Jopeeee** [Rapptz/discord.py#7661]
### Summary

No content for messages when looked up through channel.history()

### Reproduction Steps

When checking for the last message in a channel using "channel.history()" the messages that are returned do not have any content unless I mention the bot in said messages. I suspected a problem with Intents but in "on_message" all messages returned with content.
The bot has all the necessary permissions.

### Minimal Reproducible Code

```python
async def on_ready(self):
        channel = client.get_channel(look_at_this_channel)
        messages = [message async for message in channel.history(limit=5)]
        for msg in messages:
            print(f"Content: {msg.content}")
```

### Expected Results

I expected that the content of the last 5 messages would be the output.

### Actual Results

Output:
`
Content:
Content:
Content:
Content:
Content:
`

### Intents

Intents.all()

### System Information

- Python v3.9.5-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3849+g6def5c91
- aiohttp v3.7.4.post0
- system info: Linux 5.11.0-16-generic -Ubuntu SMP

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by AbstractUmbra** [comment]
When using current builds of version 2.0, you must manually opt into the message content intent:
```
intents = discord.Intents.default()
intents.message_content = True

bot = commands.Bot(..., intents=intents)
```

Or similar is required.

**Comment by Jopeeee** [comment]
From my understanding Intents can not be the issue as i.e. in the on_message event I do get the message.content.

Also I tried your solution but that doesn't seem to help.

**Comment by AbstractUmbra** [comment]
I see. 
There are messages that have no content, such as one that only contain an embed, or an attachment. Is there a change you are actually reading over these messages?

**Comment by Jopeeee** [comment]
No, it's just normal messages.
It's the same messages that did return their content in on_message.

**Comment by AbstractUmbra** [comment]
I'm currently running my bot on the commit at 6def5c9131ac686edc3a2294cc6735cbbc30c909 and the following codeblock works as expected:
```py
messages = [m async for m in channel.history(limit=5)]
for m in messages:
  print(m.content)
```

Could you try updating the dev version you are running on?

**Comment by Jopeeee** [comment]
That should be the version I'm already running on.

**Comment by Rapptz** [comment]
I still cannot reproduce this, and I suspect this is an issue of not specifying intents since that's the only discernible reason this should happen.

**Comment by dolfies** [comment]
Toggle the intent on and off in the dev portal.

**Comment by codeofdusk** [comment]
Thanks, disabling then re-enabling the event in the portal has restored functionality!
