### ISSUE TITLE
Function to check that discord.FFmpegPCMAudio() is really delivering audio and running

### ISSUE THREAD

**Issue by Kim123LP** [Rapptz/discord.py#7672]
### Summary

I need a function to verify that discord.FFmpegPCMAudio() is actually delivering audio and running.

### What is the feature request for?

The core library

### The Problem

Since I transfer a web radio 24/7 with discord.FFmpegPCMAudio() to a voice channel on Discord, it sometimes happens that the bot simply stops getting audio from the web radio after 20 hours. This means that the bot still has a green speech bubble in the voice channel, but is not transmitting any sound.

### The Ideal Solution

It would be good to have a function if FFmpeg still gets audio so that you can restart the player in a loop if necessary. It would be the best if this would be directly implemented in the library. I know that this could also be due to the web radio, but you could still try to reconnect every 10 seconds.

**Comment by itttgg** [comment]
This is good idea)

**Comment by Rapptz** [comment]
I don't think realistically there are any plans on adding this one. The AudioSource concept is pretty basic -- it just reads from a subprocess so it has no good way discern whether it's playing or not if it's actually getting data from the source.

**Comment by Kim123LP** [comment]
Is there like an option that I can set for ffmpeg, so it would automatically reconnect or something. And how?
