### ISSUE TITLE
Better method of overwriting `client.setup_hook()` without subclassing

### ISSUE THREAD

**Issue by HigherOrderLogic** [Rapptz/discord.py#7677]
### Summary

Better method of overwriting `client.setup_hook()` without subclassing

### What is the feature request for?

The core library

### The Problem

Right now, there are 2 ways to overwrite `client.setup_hook()`, first is subclass `Bot`/`client`, the second one is using the `client.event` decorator. The first method is quite long and the second one isn't recommended by Danny.

### The Ideal Solution

Add a decorator to register the `setup_hook()`

### The Current Solution

Using the `client.event` decorator

**Comment by SebbyLaw** [comment]
Subclassing is the recommended way to define your bot's behavior.
