### ISSUE TITLE
Problem with typing.Literal

### ISSUE THREAD

**Issue by srlightt** [Rapptz/discord.py#7690]
### Summary

I ran into maybe a problem with the library, using the special converter typing.Literal, currently I can't pass just one parameter

### Reproduction Steps

I used it with my parameter to be a literal string "guild-avatar", in app command

```py
    @app_commands.command()
    async def avatar(self, interaction: discord.Interaction, user: discord.Member = None, argument: typing.Literal['guild-avatar'] = None):
```

### Expected Results

I hope typing.Literal only accepts one argument too, currently generating this error:

```py
  File "C:\Users\light\Documents\pycharm\newdiscordpy\venv\lib\site-packages\discord\app_commands\transformers.py", line 271, in _make_literal_transformer
    raise TypeError(f'typing.Literal requires at least two values.')
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.Info.avatar' raised an error: TypeError: typing.Literal requires at least two values.
```

### Actual Results

Apparently this is accepting 2 parameters upwards, the error is coming if we put only one argument

It currently does not generate an error if we use it this way:
```py
    @app_commands.command()
    async def avatar(self, interaction: discord.Interaction, user: discord.Member = None, argument: typing.Literal['guild-avatar', 'avatar'] = None):
```

### Intents

None

### System Information

- Python v3.9.6-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3881+g6dd8845
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by ImVaskel** [comment]
as stated in the error, typing.Literal takes 2+ arguments. why not make this parameter a boolean instead?

**Comment by srlightt** [comment]
> as stated in the error, typing.Literal takes 2+ arguments. why not make this parameter a boolean instead? at the point of accepting only one parameter, a boolean seems like the better idea?

If I use ['guild-avatar', x] and another parameter of another type, it generates this
```py
Choice values must be of type "string"
```

**Comment by Rapptz** [comment]
I originally had this limit because I thought the API would error out if you gave it one choice, since logically it's a bit strange. However, I just double checked and it seems it doesn't actually care so I removed the restriction.
