### ISSUE TITLE
on_private_message() bot.event

### ISSUE THREAD

**Issue by itttgg** [Rapptz/discord.py#7694]
### Summary

on_private_message() bot.event in discord.py v2

### What is the feature request for?

The core library

### The Problem

This event is checking that sended the private message to the bot (ignores private groups) or no. 

### The Ideal Solution

@bot.event
async def on_private_message(message):
         await message.channel.send(“hi”)

**Comment by IAmTomahawkx** [comment]
I'm failing to see the benefit of this as opposed to checking if message.guild is none in on_message

**Comment by drobotk** [comment]
This can be accomplished with a single `if` statement. 
```py
@bot.event
async def on_message(message: discord.Message):
    if isinstance(message.channel, discord.DMChannel):
        # is a dm, do stuff here... 
```

**Comment by itttgg** [comment]
> This can be accomplished with a single `if` statement. 
> 
> ```py
> 
> @bot.event
> 
> async def on_message(message: discord.Message):
> 
>     if isinstance(message.channel, discord.DMChannel):
> 
>         # is a dm, do stuff here... 
> 
> ```

It's not readable

**Comment by Vexs** [comment]
To mine eyes this seems plenty readable. That said, discord.py has broadly avoided events that aren't related to things the discord gateway doesn't distinctly dispatch- which would include things like this.

If your desire is just having the function name be that explicitly you can use `bot.listen`'s (or `add_listener`) `name` kwarg which allows you to use whatever function name your desire and listen to whatever event. Such as, for example
```
@bot.listener(name=on_message)
async def on_dm(...):
```

Also note that you can just check if `message.guild` is None- but I think that might have other effects these days?

**Comment by itttgg** [comment]
> To mine eyes this seems plenty readable. That said, discord.py has broadly avoided events that aren't related to things the discord gateway doesn't distinctly dispatch- which would include things like this. (I think there's been a similar request/PR in the past which has been similarly denied but I might be wrong)
> 
> If your desire is just having the function name be that explicitly you can use `bot.listen`'s (or `add_listener`) `name` kwarg which allows you to use whatever function name your desire and listen to whatever event. Such as, for example
> 
> ```
> @bot.listener(name=on_message)
> async def on_dm(...):
> ```
> 
> Also note that you can just check if `message.guild` is None- but I think that might have other effects these days?

yes this code is more readable. i think that this listener is more easy that old

**Comment by itttgg** [comment]
> > 'message.guild is None' - its not readable
> 
> 
> 
> I think the majority ...
Ok. I understood my error. I think that it is necessary to separate individual functions into events so that beginners do not have to go to the Internet and look for these constructions.

**Comment by Rapptz** [comment]
I have no plans to provide this.
