### ISSUE TITLE
Support for foreign language command name

### ISSUE THREAD

**Issue by quesera2** [Rapptz/discord.py#7698]
### Summary

Allow languages without the concept of capitalization

### What is the feature request for?

The core library

### The Problem

https://github.com/Rapptz/discord.py/blob/2d28d7b765016e0cf01b12048926ea2d6b52d24a/discord/app_commands/commands.py#L141-L147

An exception is raised if the app command name is not lower-cased according to the specification. However, some languages(e.g. Japanese) always treat it as an invalid name.

### The Ideal Solution

Determine if the characters made lower case with `lower()` are the same as the original name.

```python
if name.lower() != name: 
    raise ValueError('names must be all lower case') 
```

**Comment by Rapptz** [comment]
Oh `islower()` only checks the `Ll` category but Japanese is `Lo` so it fails the check. That is unfortunate.
