### ISSUE TITLE
AttributeError: type object 'Client' has no attribute 'servers'

### ISSUE THREAD

**Issue by reuscam** [Rapptz/discord.py#770]
VersionInfo(major=0, minor=16, micro=11, releaselevel='final', serial=0)

import discord
client = discord.Client
async def on_ready():
    print(client.servers)
    print('------')

this causes an "AttributeError: type object 'Client' has no attribute 'servers'" exception.

http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.servers seems to indicate this should exist.

**Comment by Helehelehele** [comment]
You are not creating an object.

`client = discord.Client()`

**Comment by senju-dev** [comment]
Same problem:

import discord
 
client = discord.Client()
 
@client.event
async def on_ready():
    print(discord.version_info)
    print(client.servers)

client.run('token', bot=False)

AttributeError: 'Client' object has no attribute 'servers'

**Comment by Harmon758** [comment]
If you're using the rewrite branch, [server is now guild](https://discordpy.readthedocs.io/en/rewrite/migrating.html#server-is-now-guild), so you'd need to use [`client.guilds`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Client.guilds).

For further help using the library, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.
