### ISSUE TITLE
Thank you for bringing project back :-)

### ISSUE THREAD

**Issue by Naman23-coder** [Rapptz/discord.py#7702]
### Summary

Thank you for bringing project back :-)

### What is the feature request for?

The core library

### The Problem

Thank you for bringing project back :-)

### The Ideal Solution

Thank you for bringing project back :-)

### The Current Solution

❤️ ❤️ :heart

### Additional Context

Thank you for bringing project back :-)

**Comment by rtk-rnjn** [comment]
...! You could thank Danny in the server
