### ISSUE TITLE
Slash command argument converters

### ISSUE THREAD

**Issue by philskillz-coder** [Rapptz/discord.py#7707]
### Summary

Better custom converters for slash commands

### What is the feature request for?

The core library

### The Problem

Converting string values into other classes / values

### The Ideal Solution

```py
class CustomConverter:
    def __init__(self, value: str):
        self.value = value

    @classmethod
    async def convert(cls, interaction: discord.Interaction, value: str):
        return cls(f"{interaction.user} said {value!r}")

@app_commands.command(name="mycmd")
@app_commands.converters(
    member=CustomConverter.convert
    # or # 
    member=CustomConverter
)   
async def my_command(interaction: discord.Interaction, member: CustomConverter):
    await interaction.response.send_message(member.value)
```
or this solution
```py
@app_commands.command(name="mycmd")
async def my_command(interaction: discord.Interaction, value: str):
    await interaction.response.send_message(value)
    
@my_command.converter(argument="value")
async def my_command_convert_value(interaction: discord.Interaction, value: str) -> str:
    return f"{interaction.user} said {value}"
```

Something like this would be perfect.
Notice that you have to specify the custom converters through a decorator and not through the typehint, this is so you can typehint a class and set a method (wich returns the typehinted class) as the converter.

### Additional Context

This feature also exists for normal (through chat message) commands :)

**Comment by JelNiSlaw** [comment]
This actually exists! It's called Transformers. You can find the source code in [app_commands/transformers.py](https://github.com/Rapptz/discord.py/blob/master/discord/app_commands/transformers.py)

**Comment by philskillz-coder** [comment]
@JelNiSlaw yes i know that Transformers exist. But they are in such a "weird" way. 
Thats also why this feature request has 'better' in the title.

**Comment by ChesterWOV-DPY** [comment]
It's just the same as the ext.commands converter. I don't find it confusing ngl

**Comment by Rapptz** [comment]
The `Transformer` interface does more than just convert. Realistically it could have been called `Option` and made more sense from an API naming perspective but `transform` came first before in the design before the remaining things.

Anyway I'm closing this since it's technically already implemented.
