### ISSUE TITLE
AttributeError: 'str' object has no attribute 'loop'

### ISSUE THREAD

**Issue by h0r1zon** [Rapptz/discord.py#771]
I'm attempting to run my bot when every time i try to start it I get the error:
```
Traceback (most recent call last):
  File "C:\Users\h0r1zonZ\Desktop\A\B\C\regular\DEFENDER.py", line 53, in <module>
    Bot.run(token)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\discord\client.py", line 543, in run
    loop = self.loop
AttributeError: 'str' object has no attribute 'loop'
```

**Comment by Rapptz** [comment]
You're not using the instance of the class. You're using the type itself.

It's:

```py
client = discord.Client()
client.run(...)
```

Not:

```py
discord.Client.run(...)
```

Please learn some more Python before attempting to make a bot.

**Comment by h0r1zon** [comment]
I didn't use discord.Client.run(..) or discord.Client at all for that matter

**Comment by Rapptz** [comment]
The point is the same regardless of if you used `commands.Bot`, `AutoShardedClient`, `AutoShardedBot`, etc.

**Comment by h0r1zon** [comment]
so Bot.run is incorrect?

**Comment by Rapptz** [comment]
Yes. You need an instance.

**Comment by Jaculabilis** [comment]
This was my top Google result for "discord.py has no attribute loop", which I searched because I ran into:
```AttributeError: '<class 'client.RobohorseClient'>' object has no attribute 'loop'```
In case some other wayward soul is googling for this error, I had forgotten to call `super().__init__()` in my Client subclass.

**Comment by JayTheD3veloper** [comment]
> You're not using the instance of the class. You're using the type itself.
> 
> It's:
> 
> ```python
> client = discord.Client()
> client.run(...)
> ```
> 
> Not:
> 
> ```python
> discord.Client.run(...)
> ```
> 
> Please learn some more Python before attempting to make a bot.

thank you Rapptz im dont seeing im making this (p.s yep im know python this was just an mistake)
