### ISSUE TITLE
Suggestion: Extensions that depend on other extensions.

### ISSUE THREAD

**Issue by ButterCheezii** [Rapptz/discord.py#774]

**Comment by TildeBeta** [comment]
Could you describe what you mean in more depth?

**Comment by ButterCheezii** [comment]
Let's say an "Extension 1" depends on "Extension 2". If "Extension 2" is not already loaded, the bot will attempt to load it before it loads "Extension 1". If the bot can't load "Extension 2", "Extension 1" will fail to load (because a required extension is missing or nonworking)

Additionally, if "Extension 2" is unloaded, "Extension 1" will be unloaded as well.

**Comment by SunDwarf** [comment]
This already exists; it's called the `import` statement.

**Comment by ButterCheezii** [comment]
`import`s are hard to hot-swap, though.

**Comment by SunDwarf** [comment]
What do you mean hot-swap?

This is literally a non-issue. Import Extension 2 in Extension 1. Unless you want E2 to be loaded with E1 without using it in E1, which has 0 point.

**Comment by ButterCheezii** [comment]
¯\\_(ツ)\_/¯. I tried.
