### ISSUE TITLE
[ext.tasks] Task not cancelled after task.cancel()

### ISSUE THREAD

**Issue by kittenswolf** [Rapptz/discord.py#7752]
### Summary

Starting a task immediately after cancelling (or stopping) it results in a RuntimeError complaining that the task is not completed. Adding any sleep (even a sleep of 0 seconds), fixes it.

### Reproduction Steps

I copied the [background_task.py example](https://github.com/Rapptz/discord.py/blob/master/examples/background_task.py) and slightly modified it to cancel and start the task when a message was sent (see below for code).

The code basically does the following:
- Bot starts task
- Task sends message
- on_message is fired
  - task is cancelled
  - task is started  <--- `RuntimeError: Task is already launched and is not completed.`

However, introducing any sleep after the task was cancelled - even a sleep of 0 (`await asyncio.sleep(0)`) - fixes this issue and no RuntimeError is thrown:

- Bot starts task
- Task sends message
- on_message is fired
  - task is cancelled
  - `await asyncio.sleep(0)`
  - task is started (no error)

(Note that the example with added sleep will spam messages. I'm aware this is not the most elegant example)

### Minimal Reproducible Code

```python
import asyncio

from discord.ext import tasks
import discord


class MyClient(discord.Client):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.counter = 0

    async def setup_hook(self) -> None:
        self.my_background_task.start()

    @tasks.loop(seconds=60)
    async def my_background_task(self):
        channel = self.get_channel(123456)
        self.counter += 1
        await channel.send(self.counter)

    @my_background_task.before_loop
    async def before_my_task(self):
        await self.wait_until_ready() # wait until the bot logs in


    async def on_message(self, message):
        print("Cancelling task")
        self.my_background_task.cancel()

        # Issue is fixed if you uncomment the line below
        # await asyncio.sleep(0)

        print("Starting task")
        self.my_background_task.start()

client = MyClient()
client.run('')
```

### Expected Results

I expected the task to be started normally without exception.

I also didn't expect a sleep with a duration of 0 seconds to fix it.

### Actual Results

An exception is thrown:

```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/kittenswolf/.local/lib/python3.8/site-packages/discord/client.py", line 373, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 34, in on_message
    self.my_background_task.start()
  File "/home/kittenswolf/.local/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 401, in start
    raise RuntimeError('Task is already launched and is not completed.')
RuntimeError: Task is already launched and is not completed.
```

### Intents

discord.Intents.default()

### System Information

```
- Python v3.8.10-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3952+geca47275
- aiohttp v3.7.4
- system info: Linux 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

According to the [asyncio docs](https://docs.python.org/3/library/asyncio-task.html#asyncio.sleep):

`
Setting the delay to 0 provides an optimized path to allow other tasks to run. This can be used by long-running functions to avoid blocking the event loop for the full duration of the function call.
`

but I'm not sure how to interpret this.

**Comment by Rapptz** [comment]
This is more or less how `asyncio` works. Cancelling a task calls `task.cancel()` which is a *request* to [cancel it during the next iteration of the event loop](https://docs.python.org/3/library/asyncio-task.html#asyncio.Task.cancel)

> This arranges for a [CancelledError](https://docs.python.org/3.8/library/asyncio-exceptions.html#asyncio.CancelledError) exception to be thrown into the wrapped coroutine **on the next cycle of the event loop.**

Emphasis mine. Since `cancel()` and `start()` are done during the same cycle of the event loop, the cancellation hasn't propagated yet. The `asyncio.sleep` call yields to the loop so the cancellation can propagate.

**Comment by kittenswolf** [comment]
Should this be added to the documentation since it's not obvious?
