### ISSUE TITLE
channel.fetch_message(msgID) not returning the message content

### ISSUE THREAD

**Issue by papillon107** [Rapptz/discord.py#7753]
### Summary

im tryign to fetch a message from a channel but when i try to print its ID it prints just "\n"

### Reproduction Steps

i fetched the message and tried to print the message.content because i need it to use in another function but it's empty it prints nothing

### Minimal Reproducible Code

```python
@bot.event
async def on_message(message):
    if message.channel.id == 950848738727976980:
        await message.add_reaction('✅')
    await bot.process_commands(message)

@bot.event
async def on_raw_reaction_add(payload):
    if payload.user_id != bot.user.id:
        if payload.channel_id == 950848738727976980:
            if payload.emoji.name == '✅':
                msgID = payload.message_id
                print(str(msgID))
                channel = bot.get_channel(950848738727976980)
                msgC = await channel.fetch_message(msgID)
                print(str(msgC.content))
```

### Expected Results

to print the message content

### Actual Results

it prints \n

### Intents

intents = discord.Intents.default() intents.message_content = True

### System Information

- Python v3.10.2-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3923+g98a31cf2
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000
- 
![image](https://user-images.githubusercontent.com/78275594/159739314-a90ce999-bb3e-4d04-86a5-7ab42176b0fd.png)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by helish88** [comment]
bcz message id must be int not string
```py
 print(str(msgID))

**Comment by AbstractUmbra** [comment]
The normal checklist for issues such as this are the following:
- if using `discord.py` 2.0 or higher, you need to subscribe to the [Message Content intent](https://discordpy.readthedocs.io/en/master/api.html?highlight=intents#discord.Intents.message_content).
```py
intents = discord.Intents.default()
intents.message_content = True
bot = commands.Bot(..., intents=intents)
```
- Check that your bot has permissions to read messages in the channel specified. If it does not have permissions to read message history, it can still receive message events but cannot read message content.

**Comment by AbstractUmbra** [comment]
As of the latest commit I cannot replicate either issue. All I can suggest is to try updating your library to the latest version.

**Comment by Rapptz** [comment]
If you have this issue and it still persists even when you have the message content intent enabled both in the developer portal and in your bot's code, then the issue is most likely on Discord's end. The way to fix this is to untoggle and then retoggle the message content intent in your bot's page in the developer portal.

See https://github.com/discord/discord-api-docs/issues/4552 and https://github.com/discord/discord-api-docs/issues/4655
