### ISSUE TITLE
Error while using create_text_channel with overwrites settings

### ISSUE THREAD

**Issue by leirn** [Rapptz/discord.py#7770]
### Summary

Using create_text_channel tiggers an exception when overwrites is set

### Reproduction Steps

To raise the issue, I run server.create_text_channel with an overwrites parameter.

The exception is not directly raised. It is raised by create_voice_channel right after it.

Removing overwrites parameter in create_text_channel allows create_voice_channel to be executed with no raised exception.

### Minimal Reproducible Code

```python
import discord
from config import BOT_TOKEN
from utils.config import DISCORD_ID, BOT_ID
from discord.utils import get
from discord.ext import commands

intents = discord.Intents.all()
intents.members = True
client = commands.Bot(command_prefix = "!", intents=intents)

@client.event
async def on_ready():
    print('We have logged in as {0.user}'.format(client))

@client.command()
async def test(ctx):
    role = get(server.roles, name="@everyone")
    bot = server.get_member(BOT_ID)
    overwrites = {
        role: discord.PermissionOverwrite(view_channel=False, send_messages=False, read_message_history=False),
        bot: discord.PermissionOverwrite(view_channel=True, send_messages=True, read_message_history=True,manage_channels=True),
    }
    server = client.get_guild(DISCORD_ID)
    text_channel = await server.create_text_channel(f"test", overwrites=overwrites)
    await server.create_voice_channel(text_channel.name)
    
    
client.run(BOT_TOKEN)
```

### Expected Results

I expect a text and a voice channel called test to be created.

### Actual Results

The following error happens:

Ignoring exception in command test:
Traceback (most recent call last):
  File "C:\Users\laure\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ext\commands\core.py", line 187, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\laure\OneDrive\Bureau\root-me\gitea\discord_bot\MainBot\test.py", line 17, in test
    role = get(server.roles, name="@everyone")
UnboundLocalError: local variable 'server' referenced before assignment

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\laure\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ext\commands\bot.py", line 1234, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\laure\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ext\commands\core.py", line 923, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\laure\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ext\commands\core.py", line 196, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: UnboundLocalError: local variable 'server' referenced before assignment

### Intents

discord.Intents.all()

### System Information

- Python v3.10.4-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3968+g8993b7f
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

The exception is raised only when  overwrites is set within
text_channel = await server.create_text_channel(f"test", overwrites=overwrites)
There is no exception when I use
text_channel = await server.create_text_channel(f"test")

This code, including the overwrites settings, is working on the bot with discord.py on version 1.7

**Comment by GoddeerisEdouard** [comment]
Did you read the error?

**Comment by ChesterWOV-DPY** [comment]
Your summary doesn't match the error or code. The error is basic too.

**Comment by Pysics** [comment]
@leirn You haven’t defined the variable `server`. Try adding this as your first line (in the command):
```python
server = ctx.guild
```

**Comment by leirn** [comment]
Sorry, that was a mistake in the code copy-paste. I have absolutely the same error while adding 
server = client.get_guild(RM_DISCORD_ID)
or
server  = ctx.guild

I updated both the code and the log

@Rapptz : can you please reopen the bug according to this update ?

@ChesterWOV-DPY : I don't get your point. The summary is done according to what I am able to understand, and what my tests have shown me. I would be happy to answer more precise question if required.

@GoddeerisEdouard : yes, and since it happens not in my code but in a two level deep function inside discord.py library in an object I apparently did not create or manipulate myself, I don't know what to do about it.

**Comment by ChesterWOV-DPY** [comment]
Your new error is still a code error. utils.get return None if not found.

**Comment by ChesterWOV-DPY** [comment]
[guild.py#L1151-L1182](https://github.com/Rapptz/discord.py/blob/master/discord/guild.py#L1151-L1182)
It iterates the `overwrites` dict, and it says one of the `target`s (the keys of the dict) is `None` which means the variable `role` is None.

**Comment by tailoric** [comment]
consider using
https://discordpy.readthedocs.io/en/master/api.html?highlight=guild%20me#discord.Guild.me
for the member object of your bot and
https://discordpy.readthedocs.io/en/master/api.html?highlight=default_role#discord.Guild.default_role
for getting the everyone role

**Comment by leirn** [comment]
> consider using https://discordpy.readthedocs.io/en/latest/api.html?highlight=guild%20me#discord.Guild.me for the member object of your bot and https://discordpy.readthedocs.io/en/latest/api.html?highlight=default_role#discord.Guild.default_role for getting the everyone role

Thanks, it solve the whole thing.
The initial code I have was working for month with python 3.8 and discord.py current stable release, it's why I get to github to raise an issue initially.

Many thanks to all
