### ISSUE TITLE
Create View without running loop

### ISSUE THREAD

**Issue by rexwu1104** [Rapptz/discord.py#7772]
### Summary

bot recreate a View without running loop

### Reproduction Steps

I create a View, In first time, here haven't any error, but in second time, it give me an error.
<img width="681" alt="image" src="https://user-images.githubusercontent.com/44058270/160269886-a2f4d34c-17dd-4488-8b86-3496ad488b7a.png">

### Minimal Reproducible Code

```python
if source is None and container.client is not None:
    container.play_status = MPlayStatus.UnStarted
    await_run(container.client.disconnect(force=True), loop=self.bot.loop)
    await_run(container.sent_message.delete(), loop=self.bot.loop)
    container.clear()
    container.view.stop()
    container.view = MusicView.ControlBoard(self)
    return

# here is in the after function
# await_run == asyncio.run_coroutine_threadsafe
```

### Expected Results

create a View without error

### Actual Results

create a View with error

### Intents

All

### System Information

- Python v3.10.2-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3972+g0bcb0d0e
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

**Comment by rexwu1104** [comment]
here write my system is windows 10, but it is windows 11

**Comment by Rapptz** [comment]
This is by design.
