### ISSUE TITLE
Creating embeds without certain values.

### ISSUE THREAD

**Issue by Abaios** [Rapptz/discord.py#7777]
### Summary

Embeds without titles, descriptions, etc.

### What is the feature request for?

The core library

### The Problem

When I attempt to create an embed without a title or description it always brings up an error. I've tried a couple of ways and even looked it up.

### The Ideal Solution

Making it so that you could have something like "embed = discord.Embed(title=pass, description=pass)" I think that this would be super useful and make embeds more dynamic.

**Comment by kittenswolf** [comment]
What error do you get? You can just leave out the kwarg of the value you don't want to set.

For example
```py
embed = discord.Embed() # create a completely empty embed

embed2 = discord.Embed(description="test") # embed with just a description
```

**Comment by Abaios** [comment]
Wait, so can I just write an embed like this and just ignore title?

embed = discord.Embed(description="test")

**Comment by kittenswolf** [comment]
Exactly
