### ISSUE TITLE
Slash cooldowns

### ISSUE THREAD

**Issue by AHiddenDonut** [Rapptz/discord.py#7790]
### Summary

Custom cool-downs implemented into slash commands.

### What is the feature request for?

The core library

### The Problem

Currently, to add cool-downs into slash commands, as suggested by @AbstractUmbra , it is a ton of work. Beginners and Intermediates aren't able to solve the problem by adding customised cool-down mapping by themselves.

### The Ideal Solution

Waiting for discord to implement cool-downs into slash is a good idea, but cannot help us currently. This may take a lot of time and potential for other work.

### The Current Solution

Adding custom cooldown mapping for the Interaction. I have no idea how this would work, but [here's](https://discord.com/channels/336642139381301249/381965515721146390/957920511516622858) what @AbstractUmbra suggested me to do which I was unable to do, or rather I was lacking the skills required.

**Comment by H1ppyXd** [comment]
Absolutely agree, Im looking forward to slash cooldowns
