### ISSUE TITLE
Clear PartitalEmoji Reaction

### ISSUE THREAD

**Issue by ElBe-Plaq** [Rapptz/discord.py#7793]
### Summary

Please add a featre to clear reactions with the type PartitalEMoji.

### What is the feature request for?

The core library

### The Problem

I try to clear a reaction in `on_raw_reaction_add`. For this I am using `payload`, but I can't convert an PartitalEmoji to an Emoji.

### The Ideal Solution

A converter for PartitalEmojis.

**Comment by Rapptz** [comment]
You can upgrade a `PartialEmoji` to an `Emoji` by doing `client.get_emoji(partial.id)`.

**Comment by ElBe-Plaq** [comment]
Thank you!
