### ISSUE TITLE
Error for getting list of online players

### ISSUE THREAD

**Issue by thatrandomperson5** [Rapptz/discord.py#7803]
### Summary

I run it and it gives an error

### Reproduction Steps

def notify(msg, role: discord.Role):
  guild = client.get_guild(*************)
  for member in guild.members:
    if role in member.roles:
      pass
notify('hi','lol')

Run it. It gives error
![59200D02-1B5C-45FD-BA6E-C08419FE0193](https://user-images.githubusercontent.com/94306853/160652090-e7f34dc0-31bf-42f4-a52b-a383eb054cd5.jpeg)

### Minimal Reproducible Code

```python
def notify(msg, role: discord.Role):
  guild = client.get_guild(************)
  for member in guild.members:
    if role in member.roles:
      pass
notify('hi','lol')
```

### Expected Results

It to pass every time it finds someone with the role “lol”

### Actual Results

It gave the error
![0138FA08-8A7B-43BE-903B-7C1AFD06F2AD](https://user-images.githubusercontent.com/94306853/160652428-ec9207bc-e08f-486a-bb9d-95c88b923078.jpeg)

### Intents

?? I’m new, idk what this means

### System Information

![0DDBEBDF-3C7E-47DF-82FD-A75471A5570C](https://user-images.githubusercontent.com/94306853/160652743-734b12e4-cf42-4465-8837-487920322286.jpeg)

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by pintermor9** [comment]
u need to have members intent enabled

**Comment by pintermor9** [comment]
where u create bot do `bot = discord.Bot(intents=discord.Intents.all())` this should work

**Comment by pintermor9** [comment]
but did u do https://github.com/Rapptz/discord.py/issues/7803#issuecomment-1082060508

**Comment by thatrandomperson5** [comment]
> where u create bot do `bot = discord.Bot(intents=discord.Intents.all())` this should work

What do u mean create bot? I’m new

**Comment by thatrandomperson5** [comment]
> but did u do [#7803 (comment)](https://github.com/Rapptz/discord.py/issues/7803#issuecomment-1082060508)

Yes I did, tho it took me awhile to find out there was a “save changes button”

**Comment by pintermor9** [comment]
in the main.py (or idk how you call it) where you create the bot instance (where you set the `bot` variable) you need to include the intents=discord.Intents.all() as i showed

**Comment by thatrandomperson5** [comment]
> in the main.py (or idk how you call it) where you create the bot instance (where you set the `bot` variable) you need to include the intents=discord.Intents.all() as i showed

![11652BBA-A742-4F22-82AC-FC0D4745789D](https://user-images.githubusercontent.com/94306853/160655863-8db8e8ba-4abd-4e44-b3e7-bb451f7a2378.jpeg)
U mean that?

**Comment by pintermor9** [comment]
yeah
do `client = discord.Client(intents=discord.Intents.all())`

**Comment by thatrandomperson5** [comment]
> yeah
> do `client = discord.Client(intents=discord.Intents.all())`

I’ll try it, people call it so many things I didn’t know that’s what you where talking about

**Comment by pintermor9** [comment]
did it work?

**Comment by thatrandomperson5** [comment]
> did it work?

Not really
![C54005EF-2336-4D1A-B37F-657EF9158174](https://user-images.githubusercontent.com/94306853/160657000-dbfb7c95-7421-49d8-9982-fec02e369750.jpeg)

**Comment by pintermor9** [comment]
oooooooohhhh
something's off with the guild

**Comment by thatrandomperson5** [comment]
> it needs to be an integer like 123456789

I k, I blurred out the guild ID on purpose.

**Comment by pintermor9** [comment]
idk than

**Comment by thatrandomperson5** [comment]
95***1264979062*** I still blurred out some

**Comment by pintermor9** [comment]
try to ask it in the discord (https://discord.gg/dpy)

**Comment by pintermor9** [comment]
in this channel https://discord.com/channels/336642139381301249/381965515721146390 they reply faster than here

**Comment by pintermor9** [comment]
Bro can u please double check u entered a correct guild id

**Comment by pintermor9** [comment]
> > in this channel https://discord.com/channels/336642139381301249/381965515721146390 they reply faster than here
> 
> It not work, says channel does not exist

Join the guild first https://discord.gg/dpy

**Comment by thatrandomperson5** [comment]
> 

Same does not work

**Comment by thatrandomperson5** [comment]
> 

Got it to work, but no one on the discord responds

**Comment by thatrandomperson5** [comment]
Solved by the discord!
Thx everyone,
