### ISSUE TITLE
Sending messages on join?

### ISSUE THREAD

**Issue by Acituanbus** [Rapptz/discord.py#781]
Any idea how I can make my bot send messages once it joins a server, if that server has a default channel?

The code for sending the message is clear, I just can't find anything about how to trigger it once it joins
Sending a message to the default channel should work like this, right?

```Python
await bot.send_message(server, "This is a message")
```

**Comment by Planet4546b** [comment]
I use a for loop to cycle through serves for an annoucement and also use "server" as a destination, so that part should be fine. I can't help you with the join message sadly :/

**Comment by bsquidwrd** [comment]
Assuming by your example `send_message` code, you're using the async version of the library right?

If so, look at the documentation http://discordpy.readthedocs.io/en/latest/api.html#discord.on_server_join
