### ISSUE TITLE
Add slash command interaction object in bot response message.

### ISSUE THREAD

**Issue by AleksQuantum** [Rapptz/discord.py#7819]
### Summary

The need to get the interaction object from the bot response.

### What is the feature request for?

The core library

### The Problem

There is no real way to get a person who has issued a command on the bot from any other bot. 
1. The bots that log command usage will benefit from it.
2. I need to thank a specific user for a certain slash command action, but I can't get their id or ping them.

### The Ideal Solution

Message object gets an interaction object developers can refer to and get the user from it, who issued a slash command.

### The Current Solution

The current solution is to look through raw message data in on_socket_raw_receive call and find the interaction there.

### Additional Context

Any other solution of getting the user who issued a slash command would be nice.

**Comment by Rapptz** [comment]
Messages have a [partial interaction object](https://discord.com/developers/docs/interactions/receiving-and-responding#message-interaction-object-message-interaction-structure) that isn't exposed right now. There was a PR (#7680) but it didn't actually go anywhere. This should be rather simple to expose.

**Comment by AleksQuantum** [comment]
> Messages have a [partial interaction object](https://discord.com/developers/docs/interactions/receiving-and-responding#message-interaction-object-message-interaction-structure) that isn't exposed right now. There was a PR (#7680) but it didn't actually go anywhere. This should be rather simple to expose.

I found out that I can do what I need through on_socket_raw_receive, but it would be much easier and better to do through message.interaction.user.id.
