### ISSUE TITLE
May I ask how to use "poll_voice_ws" to receive voice?

### ISSUE THREAD

**Issue by taylor224** [Rapptz/discord.py#782]
Hello,
May I ask how to use "poll_voice_ws" to receive voice from Discord?
In document, The description about "poll_voice_ws" function is too short to understand.
I want to process voice websocket packet to know who's talking now.
I tried with few code with asyncio sample code, It's failed.
It is okay that show short example code about "poll_voice_ws".
Thank you.

**Comment by Bottersnike** [comment]
The only way as of now to receive voice WebSocket packets is to monkey-patch in a handler for the decoded packets (IIRC). If you want to receive the voice data, you can't. There's a PR open though to add the functionality (#740) so if you _really_ need it you could probably clone that repo but be wary about the lack of updates.

**Comment by taylor224** [comment]
I'd better use #740 forked version. I think I can make what I want with forked version.
Thank you!
