### ISSUE TITLE
interaction.message does not work

### ISSUE THREAD

**Issue by chredeur0** [Rapptz/discord.py#7820]
### Summary

interaction.message does not work and returns None

### Reproduction Steps

1. Clone the latest version of discord.py from GitHub.
2. Use the code below.

### Minimal Reproducible Code

```python
@app_commands.command(name="test")
  async def test(self, interaction: discord.Interaction):
    print(interaction.message)
```

### Expected Results

Return valid interaction.message

### Actual Results

None

### Intents

discord.Intents.all()

### System Information

Python 3.10
discord.py master Branch (on GitHub)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by LeoCx1000** [comment]
Slash commands aren't bound to a message. When the bot received a command interaction, no message existe yet.
Buttons/selects's interactions are bound to a message.

The message of a command is the one you'd get after you .send_message and retrieve it with `await interaction.original_message()`
