### ISSUE TITLE
Get an error when use context_menu in cogs

### ISSUE THREAD

**Issue by ZebcoWeb** [Rapptz/discord.py#7823]
### Summary

error for context menu

### Minimal Reproducible Code

```python
@app_commands.context_menu(name='my menu')
    async def qanda_choose_answer(self, interaction: discord.Interaction, message: discord.Message):
        if message.channel.type == discord.ChannelType.public_thread and message.channel.parent_id == Channel.QA_CHANNEL_ID:
  ...
```

### Expected Results

I expected the menu to work properly and get to its parameters.

### Actual Results

**i get this error:**
`Extension 'cogs.qanda' raised an error: TypeError: context menu callbacks require 2 parameters, the first one being the annotation and the other one explicitly annotated with either discord.Message, discord.User, discord.Member, or a typing.Union of discord.Member and discord.User`

### Intents

all of them

### System Information

- Python v3.9.8-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4020+g3d914e0
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I looked for a solution on the library's Discord server but not found answer.

**Comment by AbstractUmbra** [comment]
It is not supported to define these within a class, they must be free standing functions.

**Comment by Rapptz** [comment]
Context menus do not support group contexts (e.g. `Cog` or `Group`). This is for a few reasons.

1. Within Discord itself, they cannot be bound to a group. There is no such thing as a "sub context menu" right now, and if it exists in the future it probably will not be in the same category as a `Group` would be.
2. If added, the `Group` and the `Cog` would need to handle and maintain a mapping of context menus to eventually add back and remove from the tree. This complication and extra space doesn't seem worth it to me, especially considering you can only have 5 context menu command sanyway.
3. The context menu would have to store bindings (the `self` parameter) which is an incredibly complicated thing to do that has been a common source of bugs within the library.

This is kind of ironic but this is one of those things that is actually significantly easier to do yourself rather than the library generalising it to fit to everyone's needs. For example, in a cog you can do the following:

```py
class MyCog(commands.Cog):
    def __init__(self, bot: commands.Bot) -> None:
        self.bot = bot
        self.ctx_menu = app_commands.ContextMenu(
            name='Cool Command Name',
            callback=self.my_cool_context_menu,
            # guild_ids=[...],
        )
        self.bot.tree.add_command(self.ctx_menu)

    async def cog_unload(self) -> None:
        self.bot.tree.remove_command(self.ctx_menu.name, type=self.ctx_menu.type)

    async def my_cool_context_menu(self, interaction: discord.Interaction, message: discord.Message) -> None:
        await interaction.response.send_message('hello...')
```

This lets you manually add the context menu to the bot tree when a cog is created. The Python runtime handles the self binding for you as well, rather than the library.

**Comment by ZebcoWeb** [comment]
Thanks for the explanation

**Comment by vaz1306011** [comment]
> Context menus do not support group contexts (e.g. `Cog` or `Group`). This is for a few reasons.
> 
> 1. Within Discord itself, they cannot be bound to a group. There is no such thing as a "sub context menu" right now, and if it exists in the future it probably will not be in the same category as a `Group` would be.
> 2. If added, the `Group` and the `Cog` would need to handle and maintain a mapping of context menus to eventually add back and remove from the tree. This complication and extra space doesn't seem worth it to me, especially considering you can only have 5 context menu commands anyway.
> 3. The context menu would have to store bindings (the `self` parameter) which is an incredibly complicated thing to do that has been a common source of bugs within the library.
> 
> This is kind of ironic but this is one of those things that is actually significantly easier to do yourself rather than the library generalising it to fit to everyone's needs. For example, in a cog you can do the following:
> 
> ```python
> class MyCog(commands.Cog):
>     def __init__(self, bot: commands.Bot) -> None:
>         self.bot = bot
>         self.ctx_menu = app_commands.ContextMenu(
>             name='Cool Command Name',
>             callback=self.my_cool_context_menu,
>         )
>         self.bot.tree.add_command(self.ctx_menu)
> 
>     async def cog_unload(self) -> None:
>         self.bot.tree.remove_command(self.ctx_menu.name, type=self.ctx_menu.type)
> 
>     # You can add checks too
>     @app_commands.checks.has_permissions(ban_members=True)
>     # @app_commads.guilds(12345)
>     async def my_cool_context_menu(self, interaction: discord.Interaction, message: discord.Message) -> None:
>         await interaction.response.send_message('hello...')
> ```
> 
> This lets you manually add the context menu to the bot tree when a cog is created. The Python runtime handles the self binding for you as well, rather than the library.

But how do I handle the error?
The general command is like this
```python
class MyCog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.command()
    async def echo(self, ctx, arg):
        await ctx.send(arg)

    @echo.error
    async def echo_error(self, ctx, error):
        await ctx.send("There was an error")
        if isinstance(error, command.MissingRequiredArgument):
            await ctx.send("MIssing Required Argument")
        else:
            raise error
``` 
in this case
```python
class MyCog(commands.Cog):
    def __init__(self, bot: commands.Bot) -> None:
        self.bot = bot
        self.ctx_menu = app_commands.ContextMenu(
            name='Cool Command Name',
            callback=self.my_cool_context_menu,
        )
        self.bot.tree.add_command(self.ctx_menu)

    @app_commands.checks.has_permissions(ban_members=True)
    async def my_cool_context_menu(self, interaction: discord.Interaction, message: discord.Message) -> None:
        await interaction.response.send_message('hello...')
        
    @my_cool_context_menu.error
    async def my_cool_context_menu_error(self, interaction: discord.Interaction, error: Exception) -> None:
        await interaction.response.send_message('error...')
```
This will report the error AttributeError: 'function' object has no attribute 'error'

**Comment by Rapptz** [comment]
You would do `self.ctx_menu.error(self.my_cool_context_menu_error)` inside `__init__` instead.

**Comment by vaz1306011** [comment]
> You would do `self.ctx_menu.error(self.my_cool_context_menu_error)` inside `__init__` instead.

oh,thanks

**Comment by glass-ships** [comment]
Sorry - I know this issue is closed and the discussion is somewhat old, but I couldn't find much info in doing research. 

How would one define multiple context menu interactions in one single cog?  
Or would the current implementation require separate cogs for each ContextMenu?

**Comment by AbstractUmbra** [comment]
You can definitely do more than one per Cog class.

A small example:

```py
class MyCog(commands.Cog):
  def __init__(self, bot: commands.Bot, /) -> None:
    self.bot: commands.Bot = bot
    self.ctx_one = app_commands.ContextMenu(name="Context Menu 1", callback=self.ctx_one_callback)
    self.bot.tree.add_command(self.ctx_one)
    self.ctx_two = app_commands.ContextMenu(name="Context Menu 2", callback=self.ctx_two_callback)
    self.bot.tree.add_command(self.ctx_two)

  def cog_unload(self) -> None:
    # remove both on cog unload to not clog up the tree incorrectly
    self.bot.tree.remove_command(self.ctx_one.name, type=self.ctx_one.type)
    self.bot.tree.remove_command(self.ctx_two.name, type=self.ctx_two.type)
```

Just define the callbacks as normal.

**Comment by glass-ships** [comment]
Awesome, thanks Umbra!
