### ISSUE TITLE
App command does not sync

### ISSUE THREAD

**Issue by chredeur0** [Rapptz/discord.py#7829]
### Summary

App command does not sync

### Reproduction Steps

1. Clone the latest version of discord.py from GitHub.
2. Use the code below.

### Minimal Reproducible Code

```python
import discord
from discord.ext import commands
from discord import app_commands

class Utility_Slash(commands.Cog):

    def __init__(self, client: commands.Bot):
        self.bot = bot
    
    @app_commands.command(name="test")
    @app_commands.guilds(discord.Object(id=...))
    async def test(self, interaction: discord.Interaction):
        await interaction.response.send_message("test")

async def setup(bot):
    await bot.add_cog(Utility_Slash(bot))
```

### Expected Results

Command shown in Discord

### Actual Results

No command are listed in discord

### Intents

discord.Intents.all()

### System Information

Python 3.10
discord.py master Branch (on GitHub)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
Did you call `tree.sync(guild=...)` at any point in the program?

**Comment by chredeur0** [comment]
> Did you call `tree.sync(guild=...)` at any point in the program?
I just tested and it works but if I want a command to be only for one guild how do I do?

**Comment by Rapptz** [comment]
Syncing to the guild only puts it in that guild.
