### ISSUE TITLE
'ValueError: I/O operation on closed file' when calling discord.PCMVolumeTransformer.cleanup().

### ISSUE THREAD

**Issue by matthewflegg** [Rapptz/discord.py#7840]
### Summary

'ValueError: I/O operation on closed file' when calling discord.PCMVolumeTransformer.cleanup() to skip a currently playing song..

### Reproduction Steps

1. Ran `main.py`. The repo is **[here](https://github.com/matthewflegg/bb-bot)**. Use the self hosting guide to run it for yourself.
2. Used `?play <song name>`.
3. Used `?play <another song name>`, letting the first song play.
4. Used `?skip`.

### Minimal Reproducible Code

```python
async def player_loop(self):
        """
        The main player loop.
        """
        await self.bot.wait_until_ready()

        while not self.bot.is_closed():
            self.next.clear()

            try:
                # Wait for the next song. If we timeout, cancel player and dc
                async with timeout(300):  # Wait 5 mins
                    source = await self.queue.get()
            except asyncio.TimeoutError:
                return self.destroy(self._guild)

            if not isinstance(source, YTDLSource):
                # Source was probably not downloaded
                # So we should regather
                try:
                    source = await YTDLSource.regather_stream(
                        source, loop=self.bot.loop
                    )
                except Exception as e:
                    await self._channel.send(
                        f":x: Sorry, I couldn't process your song.\n" + f"\n[{e}]\n"
                    )
                    continue

            source.volume = self.volume
            self.current = source

            self._guild.voice_client.play(
                source,
                after=lambda _: self.bot.loop.call_soon_threadsafe(self.next.set),
            )

            embed = discord.Embed(
                title=f"🎵 **Now Playing:** *{source.title}*",
                description=f"Requested by: **{source.requester}**",
            )

            self.np = await self._channel.send(embed=embed)

            await self.next.wait()

            # Make sure the FFmpeg process is cleaned up.
            source.cleanup()
            self.current = None

            try:
                # We are no longer playing this song...
                await self.np.delete()
            except discord.HTTPException:
                pass
```

### Expected Results

I expected the second song in the music queue to play.

### Actual Results

The following exception was raised.
![skip-command-error](https://user-images.githubusercontent.com/88111643/161437840-eb3009b5-460a-4379-91f8-2b1ed3a4bab1.png)

### Intents

discord.Intents.all()

### System Information

![Screenshot from 2022-04-03 17-26-50](https://user-images.githubusercontent.com/88111643/161437892-412f2baf-7bb2-4163-99ac-68a3b1295b2d.png)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I should note that this command has not been changed except for the removal of a color from the output embed messages. The command worked well and passed all of the unit tests using discord.py v1.7.3.

**Comment by Rapptz** [comment]
The cleanup function is almost always called by the library not by users. The proper way to trigger a cleanup is by stopping the player through the voice client.

**Comment by matthewflegg** [comment]
> The cleanup function is almost always called by the library not by users. The proper way to trigger a cleanup is by stopping the player through the voice client.

Okay, thanks. In that case, I would recommend preceding the cleanup method with _ or __, to indicate that it's private.

**Comment by Rapptz** [comment]
It's not private. It's an abstract **callback**.
