### ISSUE TITLE
Timeout Feature

### ISSUE THREAD

**Issue by Abaios** [Rapptz/discord.py#7852]
### Summary

Timeout feature for discord.py

### What is the feature request for?

The core library

### The Problem

The new timeout feature in Discord isn't supported by discord.py as of me writing this. I would prefer the feature to be added because it will eliminate the need to use a mute command that gives the user a role. 

### The Ideal Solution

Addition to Timeout to discord.py library.

**Comment by JDJGInc** [comment]
Update your dpy version to latest master, it's there

**Comment by Hirakudev** [comment]
This is supported in the `master` branch which you can find in both the [source](https://github.com/Rapptz/discord.py/blob/master/discord/member.py#L919) and in the [documentation](https://discordpy.readthedocs.io/en/master/api.html?highlight=timeout#discord.Member.timeout).

You can update to the master branch by doing as described [here](https://github.com/Rapptz/discord.py#installing) but make sure to follow the migration guides [here](https://discordpy.readthedocs.io/en/master/migrating.html?) as well!
