### ISSUE TITLE
Guild.get_category(self, id) implementation

### ISSUE THREAD

**Issue by Fallcrim** [Rapptz/discord.py#7857]
### Summary

I'd like to see a method to get categories by their ids instantly from a guild

### What is the feature request for?

The core library

### The Problem

Creating channels in general would be much easier 

### The Ideal Solution

It should be able to fetch a category directly from a guild object
Example:
`Guild.get_category(self, id)`

### The Current Solution

At the moment you have to fetch a category by using `discord.utils.get(guild.channels, id=?, name=?, ...)`

**Comment by Vexs** [comment]
Categories are channels too- and can be fetched with `get_channel`.
