### ISSUE TITLE
Random is broken

### ISSUE THREAD

**Issue by ThePizzaGod2** [Rapptz/discord.py#7868]
### Summary

whenever we use random it dose not work properly

### Reproduction Steps

so, i am making a bot and found a error
about the random 
i use random in a command and found that
its that when u give only 2 variables it dose not send it randomly but it send it a normal pattern unlike other api's . i never felt that using other api so u might wanna look into it 

### Minimal Reproducible Code

```python
@bot.command()
async def tod(ctx):
    jsdad = ['Dare',
           'Truth']
    await ctx.send(f'{random.choice(jsdad)}')
```

### Expected Results

truth
dare
truth
truth
dare
truth

or something like that

### Actual Results

Truth
Truth
Dare
Dare
Dare
Truth
Truth
Truth
Truth
Truth
Dare
Truth

it send the same patern for me again and again 

### Intents

.

### System Information

.

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context
if u want more info 
my discord id
TheGodOfPizza's#3454

_No response_

**Comment by VarMonke** [comment]
I don't see how this is related to discord.py.

**Comment by ImVaskel** [comment]
This is not related to discord.py. Beyond that, this is a possible output for true rng.

**Comment by Rapptz** [comment]
This has nothing to do with discord.py.
