### ISSUE TITLE
message.mentions handles "identical" messages the differently

### ISSUE THREAD

**Issue by triviajon** [Rapptz/discord.py#7891]
### Summary

 message.mentions does not identify mentions of a user if they are not filled in by discord user autocompete

### Reproduction Steps

In Discord, mention someone by typing "@user" and hitting enter (or clicking on their name from the discord menu). Send the message. This is normal behavior. Then, mention someone by typing "@username" (not their nickname) without using their 4 digit identifier. Do not hit "enter", first hit space and THEN send it. This will still mention the user on discord, but discord.py will not identify the mention in Message.mentions (even though Message.content shows these as the the same).

### Minimal Reproducible Code

```python
@bot.event
async def on_message(ctx):
    print(f"Message:", ctx.content)
    print(f"Mentions:", ctx.mentions)
    return None
```

### Expected Results

Mentions should be identical both times

### Actual Results

The mentions list in the second example is empty.

### Intents

default (?)

### System Information

- Python v3.10.4-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
This property is read straight from the API. If you want to report a bug with the API you should report it in https://github.com/discord/discord-api-docs though they'll probably want some more information. You can check what payloads you receive from Discord using DEBUG logging. If the MESSAGE_CREATE for some reason is missing the `mentions` field then that'll be a bug that needs to be reported.
