### ISSUE TITLE
on_typing event returning None  when it should return Channel type

### ISSUE THREAD

**Issue by ThomasRety** [Rapptz/discord.py#790]
Hello!

I have this exception when i try to say something when someone is typing, but my await client.say() raise me this exception. If i comment the "await client.say() " line, there is no exception.
This is my code, and following there is the exception that python3 throw me.                                                                        
@client.event                                                            
async def on_typing(channel, user, when):                                
    print("This is a working event")                                       
    await client.say("{} started typing".format(user.name))              
 
Ignoring exception in on_typing
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "bot.py", line 43, in on_typing
    await client.say("{} started typing".format(user.name))
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/bot.py", line 309, in _augmented_msg
    msg = yield from coro
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 1145, in send_message
    channel_id, guild_id = yield from self._resolve_destination(destination)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 289, in _resolve_destination
    raise InvalidArgument(fmt.format(destination))
discord.errors.InvalidArgument: Destination must be Channel, PrivateChannel, User, or Object. Received NoneType

Thanks for the support, 
Thomas

**Comment by Rapptz** [comment]
You can't use `Bot.say` outside of events. See [the FAQ](http://discordpy.readthedocs.io/en/latest/faq.html#can-i-use-bot-say-in-other-places-aside-from-commands)
