### ISSUE TITLE
More colors in `discord.Color`

### ISSUE THREAD

**Issue by prakarsh17** [Rapptz/discord.py#7905]
### Summary

Add new , enhanced and better colors in discord.Color like aqua , cyan etc

### What is the feature request for?

The core library

### The Problem

Add new , enhanced and better colors in discord.Color like aqua , cyan etc 
Also some colors like `discord.Color.red` is different from the standard red color  This enhancement would ease developer's problem while using colors especially `discord.Embed` .

### The Ideal Solution

Add more color codes in discord.Color class

### The Current Solution

Currently developers usually make their own `class` or `dictionary` etc for having more colors which arent available.

**Comment by Rapptz** [comment]
The library will only provide colours that are significant within Discord's branding or UI. Any extraneous colours should be done by users.
