### ISSUE TITLE
`discord.Message.guild` is always `None` 

### ISSUE THREAD

**Issue by timelessnesses** [Rapptz/discord.py#7914]
### Summary

`discord.Message.guild` is always `None` everytime in `on_message` event

### Reproduction Steps

1. make simple `on_message` event
2. try access any value inside `message.guild` like `message.guild.id`
3. run and try say anything inside a guild
4. errors
```py
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\moopi\AppData\Local\pypoetry\Cache\virtualenvs\botjam_mod-WKqEDRqB-py3.9\lib\site-packages\discord\client.py", line 375, in _run_event
    await coro(*args, **kwargs)
  File "F:\Desktop\botjam mod\src\automod.py", line 138, in on_message
    await self.profanity_checker(message)
  File "F:\Desktop\botjam mod\src\automod.py", line 90, in profanity_checker
    if db[str(message.guild.id)]["prevent_swearing"] == False:
AttributeError: 'NoneType' object has no attribute 'id'
```
### Minimal Reproducible Code

```python
import discord
from discord.ext import commands
class g(commands.Cog):
    def __init__(self,bot):
        self.bot = bot
    @commands.Cog.listener()
    async def on_message(self, message: discord.Message) -> None:
        message.guild.id

async def setup(bot: commands.Bot):
    await bot.add_cog(g())
```

### Expected Results

`discord.Message.guild.id` isn't `None`

### Actual Results

`discord.Message.guild.id` is `None`

### Intents

`discord.Intents.all()`

### System Information

```
- Python v3.9.7-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4154+g832d2c05
- aiohttp v3.8.1
- system info: Windows 10 10.0.19044
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by timelessnesses** [comment]
but message was sent in guild

**Comment by timelessnesses** [comment]
i enabled all intents for it
![image](https://user-images.githubusercontent.com/59832159/164508084-53ebf1fa-99eb-482c-a29b-9ce6271642e0.png)

**Comment by AbstractUmbra** [comment]
How is your Client/Bot configured, a la the `intents=` kwarg in the constructor?

**Comment by timelessnesses** [comment]
```py
bot = commands.Bot(
    "n!", intents=discord.Intents.all(), owner_id=int(os.getenv("OWNER_ID"))
)```

**Comment by timelessnesses** [comment]
`all()` should enable all intents right?

**Comment by rtk-rnjn** [comment]
Error must be coming from some other reasons, like "a naughty kid is spamming the text walls in your bot DM". Consider adding check like:
```py
if message.guild is None:
    return
```

**Comment by Rapptz** [comment]
> `all()` should enable all intents right?

Yes.

If you want to further debug this issue turn on logging and print out what message.channel is.

**Comment by timelessnesses** [comment]
i figured it out
