### ISSUE TITLE
Include guild scheduled events API support.

### ISSUE THREAD

**Issue by 0xabrar** [Rapptz/discord.py#7916]
### Summary

Get parity with the official API by including scheduled events support.

### What is the feature request for?

The core library

### The Problem

Currently missing wrapper code support for working with the Guild Scheduled Event API: https://discord.com/developers/docs/resources/guild-scheduled-event#list-scheduled-events-for-guild

### The Ideal Solution

Ideally should have functions for each of the endpoints for working with scheduled events. At the least, should have GET endpoints to read the list of scheduled events, and to fetch event by ID.

### The Current Solution

There is no current integration.

**Comment by dolfies** [comment]
This has been implemented in the master branch: [docs](https://discordpy.readthedocs.io/en/latest/api.html#discord.ScheduledEvent).

**Comment by Rapptz** [comment]
This is already implemented.

**Comment by 0xabrar** [comment]
Totally missed this through docs search, thanks for the link.
