### ISSUE TITLE
Message.content is empty when it triggers from a server channel

### ISSUE THREAD

**Issue by eschirni** [Rapptz/discord.py#7931]
### Summary

Message.content turns out empty when my bot gets a message from a server text channel.

### Reproduction Steps

- Upgraded from the stable version to the current 2.0 git version here, before it worked perfectly fine, it's the same code.
- Get a message and access it via the on_message function.
- This message has to be sent via a discord server text channel, it works perfectly fine in DMs.
- Check the string of Message.content and notice that it's an empty string.

### Minimal Reproducible Code

```python
@bot.event
async def on_message(msg):
    if (msg.content[0] == '?'):
        await do_smth(msg);
```

### Expected Results

I expected it to call do_smth when I type something that starts with '?'.

### Actual Results

It will give you an IndexError: string index out of range, because Message.content is an empty string.

### Intents

discord.Intents.default()

### System Information

- Python v3.8.7-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4169+g6d95ed19
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I also tried making my bot admin to assure has the access rights, but it's the same result.

**Comment by lightningyx** [comment]
Have you enabled the message_content Intent?

**Comment by eschirni** [comment]
Yep, that's a really good point, I forgot that, I'm sorry.
