### ISSUE TITLE
@commands.guild_only() is not working properly, please debug it soon...

### ISSUE THREAD

**Issue by Zaeem20** [Rapptz/discord.py#7940]
### Summary

@commands.guild_only() is not raising CheckFailure, when @commands.has_permission is there with

### Reproduction Steps

 This is a basic kick command, which need to raise error if command was executed in DMs channel, but here is a twist,
instead of raising CheckFailure, MissingPermission error got raised,

```py
    @commands.command()
    @commands.guild_only()
    @commands.has_permissions(kick_members=True)
    async def kick(self, ctx, member : discord.Member, *,reason=None):
        await member.kick(reason=reason)
        await ctx.send(f"**{member.name} was successfully Kicked for {reason}**")
```

i had setup an error handler for that see results

### Expected Results

![image](https://user-images.githubusercontent.com/60778335/165593020-3f6582f6-901a-42cb-8051-844305e7be25.png)

I fixed that code by changing order of checks, then i got this result:
```py
    @commands.command()
    @commands.has_permissions(kick_members=True)
    @commands.guild_only()
    async def kick(self, ctx, member : discord.Member, *,reason=None):
        await member.kick(reason=reason)
        await ctx.send(f"**{member.name} was successfully Kicked for {reason}**")
```

### Actual Results

![image](https://user-images.githubusercontent.com/60778335/165592918-2402e054-2470-4817-938d-146d2ff4471f.png)

### Intents

discord.Intent.all()

### System Information

- Python v3.9.9-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4062+gf0788597
- aiohttp v3.8.1
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

it can be fixed by changing the order of check, please debug the code, and find why is it so...

**Comment by Rapptz** [comment]
This is a decorator order thing. The bottom one is executed before the top one. Reorder them if this is important to you.
