### ISSUE TITLE
Support for @discord.app_commands.check() decorator use along with @discord.app_commands.autocomplete()

### ISSUE THREAD

**Issue by CL0Pinette** [Rapptz/discord.py#7969]
### Summary

Being able to do some checks before running the autocomplete on an app_command, just like we can do with app_commands

### What is the feature request for?

The core library

### The Problem

This feature would allow us to make some checks before letting a user use the autocomplete feature of an app_command

### The Ideal Solution

It would be great if the `@discord.app_commands.check()` decorator and his siblings (`@discord.app_commands.checks.has_role()`, ...) could work along with `@discord.app_commands.autocomplete()`. e.g.: it would be possible to restrict the use of autocomplete to only some users

**Comment by Rapptz** [comment]
I'm not really sure checks conceptually make sense for this. Checks raise errors that can be handled. Auto-complete interactions have to be responded to with a list of choices. I'm not really sure what you're expecting the user experience to be like for users that don't meet the check. 

Is this, perhaps, a bug report that despite having checks on the parent the autocomplete doesn't respect it?

**Comment by CL0Pinette** [comment]
Yes, from this perspective, this is more of a bug-report then. Despite making checks on the interaction, the autocomplete is still executed.

**Comment by Rapptz** [comment]
The previous implementation caused unexpected issues when interacting with cooldowns, so I'll need to rethink how I want to approach this.
