### ISSUE TITLE
Use self and message at the same time

### ISSUE THREAD

**Issue by RetardedGenji** [Rapptz/discord.py#797]
So I'm trying to make this :
`
@client.event
async def on_message(self, message):
    do.something_here()`
But I get an error : 
`
   yield from getattr(self, event)(*args, **kwargs)
TypeError: on_message() missing 1 required positional argument: 'message'
`
What should I do? (also, sorry for my bad english im French) 👍

**Comment by MrYetiGuy** [comment]
Just a question is this in a cog?

**Comment by MrYetiGuy** [comment]
Also its recommended you join the text channel and ask there they can help you out a lot faster:
https://discordapp.com/invite/0SBTUU1wZTWPnGdJ

**Comment by RetardedGenji** [comment]
Unfortunately, i've no idea what is a cog and its in a : 
`
class Bot:
    def __init__(self):
        pass
    @client.event
    async def on_message(self, message):
        do.something_here()
      
`
