### ISSUE TITLE
commands.HelpCommand.filter_commands() not working properly

### ISSUE THREAD

**Issue by nashradical** [Rapptz/discord.py#7970]
### Summary

filter_commands() is not filtering out permission restricted/hidden commands

### Reproduction Steps

1. Create command (not slash command)
2. Add a permission check
3. Create `commands.HelpCommand` class
4. Filter commands with `filter_commands()`
5. Run help command

### Minimal Reproducible Code

```python
import discord
from discord.ext import commands

class embed_help_command(commands.HelpCommand):
    def __init__(self):
        super().__init__()

    async def send_bot_help(self, mapping):
        embed = discord.Embed(title='The Watcher Help', colour=discord.Color.from_rgb(47,49,54))
        description = self.context.bot.description
        if description:
            embed.description = description

        for cog, commands in mapping.items():
            name = 'Core' if cog is None else cog.qualified_name.capitalize()
            filtered = await self.filter_commands(commands, sort=True)
            if filtered:
                full_commands = []
                for c in commands:
                    full_commands.append(f'**{c.name}** - {c.short_doc}')
                value = '\n'.join(full_commands)
                if cog and cog.description:
                    value = '{0}\n{1}'.format(cog.description, value)

                embed.add_field(name=f'__{name}:__', value=value)

        await self.get_destination().send(embed=embed)

## New Snippet Below ## ##

bot = commands.Bot(
    command_prefix = '$',
    case_insensitive = True,
    intents = discord.Intents.all(),
    help_command = embed_help_command()
)

@bot.command()
async def foo(ctx):
    await ctx.send("foo")

@bot.command()
async def bar(ctx):
    await ctx.send("bar")

@commands.check_any(commands.is_owner(), commands.has_permissions(administrator=True))
@bot.command()
async def restricted_command(ctx):
    await ctx.send("this command should not be seen")
```

### Expected Results

HELP MENU

foo - print foo
bar - print bar

### Actual Results

HELP MENU

foo - print foo
bar - print bar
restricted_command - you shouldn't see this

### Intents

discord.Intents.all()

### System Information

Issue occurs on both machines
### Personal Computer
```
- Python v3.10.1-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19044
```

### Production (Dedicated Server running Ubuntu) 
```
- Python v3.8.10-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Linux 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I have asked for assistance troubleshooting this issue in the discord.py Discord server, the people helping me were equally confused.

I am not reporting an issue with permission checks themselves, these are working properly and raising the `CheckFailure` error. The issue is that these commands are showing in the HelpCommand, even if the user **does not have permission to use them**

**Comment by pikaninja** [comment]
You're not using filtered? you're looping through commands not filtered. Unless i'm missing something
