### ISSUE TITLE
Outdated link

### ISSUE THREAD

**Issue by mb6ockatf** [Rapptz/discord.py#7976]
### Summary

The picture in docs is broken

### Reproduction Steps

Checkout it there https://github.com/Rapptz/discord.py/blob/master/docs/intents.rst

### Expected Results

There should be a picture i guess 

### Actual Results

No picture

### Intents

it is not about the bot itself

### System Information

uff

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by jack1142** [comment]
Documentation is meant to be read from here: https://discordpy.readthedocs.io/en/stable/intents.html, not from GitHub

**Comment by mb6ockatf** [comment]
uff, ok
