### ISSUE TITLE
AttributeError: 'async_generator' object has no attribute 'flatten'

### ISSUE THREAD

**Issue by bmdavis7139** [Rapptz/discord.py#7977]
### Summary

AttributeError: 'async_generator' object has no attribute 'flatten'

### Reproduction Steps

Call coroutine flatten() on async_generator and it throws: AttributeError: 'async_generator' object has no attribute 'flatten'

[async_generator](https://discordpy.readthedocs.io/en/stable/api.html#async-iterator) documentation showing it has the flatten function

### Minimal Reproducible Code

```python
@client.event
async def on_reaction_add(reaction, user):
	if user.bot:
		return

	users = await reaction.users().flatten()
```

### Expected Results

Flattens the async iterator into a list with all the elements.

### Actual Results

Throws error: AttributeError: 'async_generator' object has no attribute 'flatten'

### Intents

intents.all

### System Information

- Python v3.10.4-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4166+g277d35c
- aiohttp v3.8.1
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

The flatten function was present in the earlier versions of discord.py.  You can easily get around it by doing an async for loop, but it was a very nice utility.

**Comment by ImVaskel** [comment]
AsyncIterators were refactored to use the python built in instead.
You want to use 
```py
[ i async for i in iterator ]
```

**Comment by Rapptz** [comment]
This is a documented breaking change. See here: https://discordpy.readthedocs.io/en/master/migrating.html#moving-away-from-custom-asynciterator
