### ISSUE TITLE
Appcommands autocomplete triggers cooldown warning. 

### ISSUE THREAD

**Issue by aldalen** [Rapptz/discord.py#7978]
### Summary

Appcommands autocomplete triggers cooldown warning. 

### Reproduction Steps

Create an app command with an autocomplete and cooldown.  

This seems to be caused by 5e98626d41e6e39f82b9fbdc7a0723311fe5751b , which was the fix for #7969.  Confirmed SHA before worked.  

### Expected Results

Cooldown does not increment / trigger for autocomplete calls. 

### Actual Results

Autocomplete calls increment cooldown buckets. 

### Intents

None

### System Information

- Python v3.9.12-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4211+g0551214b
- aiohttp v3.8.1
- system info: Darwin 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by staciax** [comment]
I found this bug too.

**Comment by Rapptz** [comment]
Hm. I think unfortunately there's no good way for both of these to co-exist as-is so I'll revert the commit for now.
