### ISSUE TITLE
aiocron tasks stopped to work in 2.0

### ISSUE THREAD

**Issue by Flameblaxter** [Rapptz/discord.py#7986]
### Summary

aiocron tasks stopped to work in 2.0, simply not start. In the version 1.7.3 working perfetly

### Reproduction Steps

Updated the 1.7.3 discord.py to 2.0 alpha..

### Minimal Reproducible Code

```python
import aiocron

import discord # Discord Library
from discord.ext import tasks, commands # Discord Commands

import asyncio

@client.event
async def on_ready():
	example_task.start()

@aiocron.crontab('*/1 * * * *')
	async def example_task():
		print(f"beep")
```

### Expected Results

Beep in every one :) (Just for example)

### Actual Results

Nothing, like the .start() even not start..

### Intents

discord.Intents().all()

### System Information

-

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
This is the issue tracker for the discord.py library, not aiocron. So this does not belong here.

Chances are the aiocron library implicitly fetches the loop and it's different from the running loop, causing a mismatch and an error. This is not a problem if you use something like the tasks extension since it lazily fetches the running loop when it's available.

**Comment by Flameblaxter** [comment]
In 1.7.3 it working perfectly, so something made by your package :) I'm sure it will have other issue.

**Comment by Rapptz** [comment]
Yes, discord.py now uses modern asyncio idioms that utilize `asyncio.run`. If you want more information feel free to read [this gist](https://gist.github.com/Rapptz/6706e1c8f23ac27c98cee4dd985c8120). As it is now, consider filing an issue to the maintainers of aiocron to work well with a running event loop.

**Comment by Flameblaxter** [comment]
> Yes, discord.py now uses modern asyncio idioms that utilize `asyncio.run`. If you want more information feel free to read [this gist](https://gist.github.com/Rapptz/6706e1c8f23ac27c98cee4dd985c8120). As it is now, consider filing an issue to the maintainers of aiocron to work well with a running event loop.

Oh make sense now, im trying to use the discord.ext tasks then.
thank you for reply
