### ISSUE TITLE
Two Command Groups can't have same sub-command name

### ISSUE THREAD

**Issue by Intenzi** [Rapptz/discord.py#7988]
### Summary

It leads to a weird traceback error where only the last command group's sub-command can be invoked.

### Reproduction Steps

Simple discord bot with two or more command groups, I haven't tried reproducing with more than 2 commands groups.
The effect however should be the same.

You have to place them inside a cog, doesn't work in the main file.
I'll send minimal code for inside the cog:-

### Minimal Reproducible Code

```python
from discord.ext import commands


class Tasks(commands.Cog):
    def __init__(self, client):
        self.client = client

    @commands.group(invoke_without_command=False, case_insensitive=True)
    async def cat(self, ctx):
        pass

    @cat.command()
    async def food(self, ctx):
        print("meow hi")

    @commands.group(invoke_without_command=False, case_insensitive=True)
    async def dog(self, ctx):
        pass

    @dog.command()
    async def food(self, ctx):
        print("woof hi")


async def setup(bot):
    await bot.add_cog(Tasks(bot))
    print("Tasks loaded")
```

### Expected Results

On invoking !cat food
 It should print :    meow hi

On invoking !dog food
 It should print :  woof hi

### Actual Results

On Invoking !cat food

Ignoring exception in command cat food:
Traceback (most recent call last):
  File "C:\Users\r\PycharmProjects\PokeHelper\venv\lib\site-packages\discord\ext\commands\bot.py", line 1325, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\r\PycharmProjects\PokeHelper\venv\lib\site-packages\discord\ext\commands\core.py", line 1557, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "C:\Users\r\PycharmProjects\PokeHelper\venv\lib\site-packages\discord\ext\commands\core.py", line 940, in invoke
    await self.prepare(ctx)
  File "C:\Users\r\PycharmProjects\PokeHelper\venv\lib\site-packages\discord\ext\commands\core.py", line 862, in prepare
    await self._parse_arguments(ctx)
  File "C:\Users\ritvi\PycharmProjects\PokeHelper\venv\lib\site-packages\discord\ext\commands\core.py", line 769, in _parse_arguments
    transformed = await self.transform(ctx, param)
  File "C:\Users\r\PycharmProjects\PokeHelper\venv\lib\site-packages\discord\ext\commands\core.py", line 622, in transform
    raise MissingRequiredArgument(param)
discord.ext.commands.errors.MissingRequiredArgument: ctx is a required argument that is missing.

On invoking !dog food
It prints:- woof hi

### Intents

discord.Intents.default(), message_content, guilds, members

### System Information

- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4169+g6d95ed1
- aiohttp v3.8.1
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

First time addressing an issue, hopefully it got formatted correctly.

**Comment by Rapptz** [comment]
Yes, this is called shadowing. You're overwriting the previous one which makes the metaclass unable to retrieve it and it messes things up. If you want to do this use the name keyword argument.
