### ISSUE TITLE
Reading Audio to File example

### ISSUE THREAD

**Issue by Crypti-x** [Rapptz/discord.py#799]
I have a `discord.VoiceClient`.
I take the worth of audio with `discord.VoiceClient.source.read()`
But how I put this into a File? I need a WAV or MP3 File? With Opus or PCM.

**Comment by hanss314** [comment]
Voice receive isn't implemented yet. `read()` reads from what the bot is playing.

**Comment by Crypti-x** [comment]
Thanks, I did not know it.
