### ISSUE TITLE
Support For Automod

### ISSUE THREAD

**Issue by Pysics** [Rapptz/discord.py#7991]
### Summary

Support For Automod

### What is the feature request for?

The core library

### The Problem

It is not supported.

### The Ideal Solution

There should be an in-built feature.

**Comment by ImVaskel** [comment]
Auto mod isn't really released at this time. Also it seems a lot of the endpoints are limited to users.

**Comment by Pysics** [comment]
> Auto mod isn't really released at this time. When it receives a more wide release, it will be added. Also it seems a lot of the endpoints are limited to users.

Take a look at discord/discord-api-docs#4860 and discord/discord-api-docs/pull/4873.

**Comment by LeoCx1000** [comment]
Those aren't merged yet, so the point still stands

**Comment by GoogleGenius** [comment]
https://github.com/discord/discord-api-docs/commit/d3d478c64f2ecf57bcd0f77d5cce6bedee52d4d8

**Comment by Pysics** [comment]
AutoMod has been implemented in [`5426d19`](https://github.com/Rapptz/discord.py/commit/5426d19dc7b6a27b618eb5753ff1c33ba5673766).
