### ISSUE TITLE
Can't install discord.py

### ISSUE THREAD

**Issue by Deksastara** [Rapptz/discord.py#800]
The command `python -m pip install -U discord.py` will not run.
I get this error
`C:\Python36\python.exe: No module named pip`
when I do it with adding a 3 at the end of python (python3) it says:
`python3 : The term 'python3' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ python3 -m pip install discord.py
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (python3:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`
I am using Windows 8 and Python 3.6.2
I tried running the command in Windows Powershell and Command Promt. Nothing will work.

**Comment by Naught0** [comment]
Hey man sounds like you're missing pip. I'd try reinstalling python if I were you.  
`python -m pip install -U discord.py`  is the proper command to install the async branch.

**Comment by Deksastara** [comment]
Okay, after reinstalling should I run the command in command prompt or power shell? Does it matter?

**Comment by Naught0** [comment]
It doesn't matter so long as during the installation you've allowed python to be added to your path. I believe it's possible to select whether you'd like to install pip during the installation. Ensure it's checked.

**Comment by Deksastara** [comment]
Okay, I installed pip and now discord.py is installing. Thank you for your help!

**Comment by blha303** [comment]
For future reference you can install pip in any python distribution by running this https://bootstrap.pypa.io/get-pip.py
