### ISSUE TITLE
Please Update Pypi 

### ISSUE THREAD

**Issue by TnzGit** [Rapptz/discord.py#8000]
### Summary

Please Update on Pypi 

### What is the feature request for?

The core library

### The Problem

The version on pypi requires an older aiohttp lib which creates conflicts with other libraries especially with the new pip dependency resolver.

### The Ideal Solution

Update the version on Pypi

**Comment by BlockyTheDev** [comment]
As far as I know PyPi gets an update? when v2 ist finished.

**Comment by scrazzz** [comment]
You can make pip not install dependencies by using `--no-deps` flag while installing a package.

**Comment by Rapptz** [comment]
It'll be updated when a release is done, as it has always been done.
