### ISSUE TITLE
Sending view with stateful webhook doesn't work

### ISSUE THREAD

**Issue by diceroll123** [Rapptz/discord.py#8005]
### Summary

Sending view with stateful webhook doesn't work

### Reproduction Steps

Sent a webhook message with a view attached, no view came out. (the rest works)

### Minimal Reproducible Code

```python
v = discord.ui.View()
v.add_item(discord.ui.Button(url='https://www.discord.com/', label='cord', style=discord.ButtonStyle.link))
webhook = await bot.fetch_webhook(832285589902327848) # use your own
await webhook.send('yeet (webhook)', view=v) # webhook.send does not show view, but files/embeds work!
await webhook.channel.send('yeet (channel)', view=v) # works as expected
```

### Expected Results

Expected a view! :)

### Actual Results

No view. :(

### Intents

irrelevant

### System Information

current, v2.0.0a4251+gc779e34f

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
Did your bot create this webhook?

**Comment by diceroll123** [comment]
No, I did. 🤔

**Comment by Rapptz** [comment]
You can only send components via webhook if your bot created the webhook itself. It looks like Discord silently drops it rather than erroring when that happens.
