### ISSUE TITLE
Adding RGB colours to roles

### ISSUE THREAD

**Issue by piggeywig2000** [Rapptz/discord.py#802]
I know this may not be an issue, but is it possible to edit a role with a custom RGB colour? I've tried creating an integer, creating a string with a hexadecimal colour code, and using the python colour module, none of which worked.

Is there a way to do it, or do I have to use the preset colours?

**Comment by Rapptz** [comment]
You just pass in the appropriate integer when constructing the `discord.Colour` instance.

e.g.

```py
discord.Colour(0xFFFFFF)
discord.Colour(int('ffffff', 16))
```

**Comment by TrentonGage11** [comment]
Rapptz=British?

**Comment by khazhyk** [comment]
Rapptz is Filipino

**Comment by Gorialis** [comment]
`Colour` is used because it is the international standard spelling. This class is aliased to `Color` for convenience. Please do not necrobump issues.
