### ISSUE TITLE
Easier View creation

### ISSUE THREAD

**Issue by pintermor9** [Rapptz/discord.py#8025]
### Summary

Add support for passing components as argument to View() 

### What is the feature request for?

The core library

### The Problem

if i'm dealing with for eg.an dynamically generated View (which isnt always the same, doesn't always have the same components) i have to code unnecessary code

### The Ideal Solution

```py
buttons=[...] 
view = discord.ui.View(buttons) 
```

### The Current Solution

```py
buttons=[...] 
view = discord.ui.View() 
for button in buttons:
    view.add_item(button)
```

### Additional Context

It would be easy for you to do. Just do this in the `discord.ui.View.__init__`
```py
    def __init__(self, *items, timeout: Optional[float] = 180.0):
        for item in items:
            self.add_item(item)
        ... 
```
Why didnt you do this in the first place

**Comment by AbstractUmbra** [comment]
`View` is designed to be expansible, meaning that if this is the behaviour you would like, then you can create a `View` subclass and create it yourself.

You have already provided the `__init__`, you could easily just create your own re-usable View subclass.

**Comment by pintermor9** [comment]
Okay thanks. I'll definitely do that
