### ISSUE TITLE
bot talk stream

### ISSUE THREAD

**Issue by FlxiBoy1313** [Rapptz/discord.py#8027]
### Summary

Allow the bot to stream in Talk

### What is the feature request for?

The core library

### The Problem

You can do more with it, e.g. let YouTube stream videos

### The Ideal Solution

Good question, just find nice if the bot could also stream what e.g. good for music botz

**Comment by LeoCx1000** [comment]
Bots can't stream video. This is a limitation of the discord api itself.

**Comment by FlxiBoy1313** [comment]
Would something like that be possible later?

**Comment by GoogleGenius** [comment]
Only if Discord ever lets bots access streaming video ¯\_(ツ)_/¯ as again, this is a limitation with the API.
