### ISSUE TITLE
on_error of a commands.GroupCog is ignored by app_command children

### ISSUE THREAD

**Issue by Bluesy1** [Rapptz/discord.py#8028]
### Summary

If you try to override the on_error of a GroupCog it is ignored

### Reproduction Steps

1. Make a commands.GroupCog
2. make an `on_error` function in the GroupCog
3. make a command, or check that causes an error or fails
4. Notice the `on_error` is ignored

### Minimal Reproducible Code

```python
bot = commands.Bot(command_prefix="!", intents=discord.Intents.all())


class MyCog(commands.GroupCog, name="group", description="Description"):
    async def interaction_check(self, interaction: discord.Interaction) -> bool:
        return False

    async def on_error(self, interaction: discord.Interaction, error: AppCommandError):
        await interaction.response.send_message("In cog!", ephemeral=True)

    @app_commands.command(name="command", description="Description")
    async def command(self, interaction: discord.Interaction):
        await interaction.response.send_message("In command!", ephemeral=True)


@bot.tree.error
async def on_error(interaction: discord.Interaction, error: AppCommandError):
    await interaction.response.send_message("On tree", ephemeral=True)

async def main():
    await bot.add_cog(MyCog(), guild=discord.Object(id=GUILD_ID))

    await bot.start(TOKEN)

asyncio.run(main())
```

### Expected Results

The response `In cog!` to be returned

### Actual Results

The response `On tree` is returned
![image](https://user-images.githubusercontent.com/68259537/167942257-fa0df0d3-3ace-48f1-a64f-f591fbf1646a.png)

### Intents

discord.Intents.All()

### System Information

```bash
- Python v3.10.4-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4247+g4dd5cc2b
- aiohttp v3.8.1
- system info: Linux 5.15.0-27-generic #28-Ubuntu SMP Thu Apr 14 04:55:28 UTC 2022
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
`GroupCog` does not have `on_error` support like this. I guess you could consider it an oversight, but `GroupCog` was written so it doesn't do multi-inheritance due to MRO issues. I'd have to add a new special method for it but I'm unsure what to call it, plus I'd need to consider how it interacts with hybrid commands.

Since this isn't an actual bug but a feature request I'm going to close this issue. You can open a new one for adding support for an app_command specific error handler if you'd like.

**Comment by Bluesy1** [comment]
Thanks for your response! Fair enough, that makes sense. I just figured it was an oversight because you can add an on error to the `GroupCog`'s Group by setting it in the `__init__` for the group cog like so, but i suppose that shifts the binding and inheritance issues to python rather than the lib:
```py
class(commands.GroupCog, ...):
    def __init__(self, bot: Bot):
        super().__init__()
        self.bot = bot
        self.app_command.error(self.on_error)

    async def on_error(self, interaction: discord.Interaction, error: AppCommandError):
        await interaction.response.send_message("In cog!", ephemeral=True)
```
I'll open a feature request later probably.
