### ISSUE TITLE
2.0 Paginator Example

### ISSUE THREAD

**Issue by Nekurone** [Rapptz/discord.py#8029]
### Summary

Adding an example paginator using 2.0 components to /examples

### What is the feature request for?

The documentation

### The Problem

The old, reaction based paginator isn't what most people using 2.0 are looking for when it comes to pagination, especially with the new views,

There is also a lot of demand for more View documentation among beta testers, so this would aid that.

### The Ideal Solution

Adding a small, documented paginator example to /examples

### The Current Solution

Currently the best way for users to build a paginator is to use TicTacToe as an example for Views, and then cross reference with the Utils paginator to build their own

### Additional Context

I have most of this set up already locally, will PR if this idea is liked.

**Comment by Rapptz** [comment]
There are a lot of examples on views already. Pagination is something that will need to be explored later to incorporate PageSource from discord-ext-menus into the library since pagination is a bit more complicated than assumed here.
