### ISSUE TITLE
Autocomplete throws an "Unknown interaction" error and sometimes "Interaction has already been acknowledged"

### ISSUE THREAD

**Issue by LostPaul** [Rapptz/discord.py#8039]
### Summary

When you use the autocomplete option for your commands it gives an "Unknown interaction" error you an 

### Reproduction Steps

Create a command that uses autocomplete

### Minimal Reproducible Code

```python
@app_commands.command()
    @app_commands.rename(emoji_id="emoji")
    async def emojiinfo(self, interaction: discord.Interaction, emoji_id: str):
        """Get information about an emoji"""
        emoji = await interaction.guild.fetch_emoji(emoji_id)
        # emoji_chache = ...
        # emoji_server_data = emoji_cache...
        # discord.utils.get(emoji, [])
        embed = discord.Embed(
            title="Emoji info",
            color=3092790,
        )
        embed.set_thumbnail(url=emoji.url)
        embed.add_field(name="Name", value=emoji.name)
        embed.add_field(name="ID", value=emoji.id)
        embed.add_field(name="Managed", value=emoji.managed)
        if emoji.roles.__len__() > 0:
            embed.add_field(name="Locked to", value=f', '.join(
                str(f"<@&{role.id}>") for role in emoji.roles), inline=False)
        embed.add_field(name="Created at",
                        value=f"<t:{int(emoji.created_at.timestamp())}:D>")
        embed.add_field(name="Uploaded by", value=emoji.user)
        embed.add_field(name="Download link",
                        value=f"[Click here]({emoji.url})")
        await interaction.response.send_message(content=f"`{emoji}`", embed=embed)

@emojiinfo.autocomplete("emoji_id")
    async def emoji_autocomplete(self, interaction: discord.Interaction, current: str) -> List[app_commands.Choice[str]]:
          return [
        app_commands.Choice(name='Option 1', value='Option 1')
    ]
```

### Expected Results

It shouldn't give an error

### Actual Results

![Discord_bdUVIQQjnp](https://user-images.githubusercontent.com/70213368/168490477-4d9dedcb-30e0-4946-bf32-2f3edb2f86ce.gif)

4|PyBot  | future: <Task finished name='CommandTree-invoker' coro=<CommandTree._from_interaction.<locals>.wrapper() done, defined at /usr/local/lib/python3.8/dist-packages/discord/app_commands/tree.py:931> exception=NotFound('404 Not Found (error code: 10062): Unknown interaction')>
4|PyBot  | Traceback (most recent call last):
4|PyBot  |   File "/usr/local/lib/python3.8/dist-packages/discord/app_commands/tree.py", line 933, in wrapper
4|PyBot  |     await self.call(interaction)
4|PyBot  |   File "/usr/local/lib/python3.8/dist-packages/discord/app_commands/tree.py", line 1090, in call
4|PyBot  |     await command._invoke_autocomplete(interaction, focused, namespace)
4|PyBot  |   File "/usr/local/lib/python3.8/dist-packages/discord/app_commands/commands.py", line 709, in _invoke_autocomplete
4|PyBot  |     await interaction.response.autocomplete(choices)
4|PyBot  |   File "/usr/local/lib/python3.8/dist-packages/discord/interactions.py", line 844, in autocomplete
4|PyBot  |     await adapter.create_interaction_response(
4|PyBot  |   File "/usr/local/lib/python3.8/dist-packages/discord/webhook/async_.py", line 214, in request
4|PyBot  |     raise NotFound(response, data)
4|PyBot  | discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
4|PyBot  | Task exception was never retrieved
4|PyBot  | future: <Task finished name='CommandTree-invoker' coro=<CommandTree._from_interaction.<locals>.wrapper() done, defined at /usr/local/lib/python3.8/dist-packages/discord/app_commands/tree.py:931> exception=NotFound('404 Not Found (error code: 10062): Unknown interaction')>
4|PyBot  | Traceback (most recent call last):
4|PyBot  |   File "/usr/local/lib/python3.8/dist-packages/discord/app_commands/tree.py", line 933, in wrapper
4|PyBot  |     await self.call(interaction)
4|PyBot  |   File "/usr/local/lib/python3.8/dist-packages/discord/app_commands/tree.py", line 1090, in call
4|PyBot  |     await command._invoke_autocomplete(interaction, focused, namespace)
4|PyBot  |   File "/usr/local/lib/python3.8/dist-packages/discord/app_commands/commands.py", line 709, in _invoke_autocomplete
4|PyBot  |     await interaction.response.autocomplete(choices)
4|PyBot  |   File "/usr/local/lib/python3.8/dist-packages/discord/interactions.py", line 844, in autocomplete
4|PyBot  |     await adapter.create_interaction_response(
4|PyBot  |   File "/usr/local/lib/python3.8/dist-packages/discord/webhook/async_.py", line 214, in request
4|PyBot  |     raise NotFound(response, data)
4|PyBot  | discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

### Intents

intents = discord.Intents.default() intents.guild_messages = True intents.typing = False

### System Information

- Python v3.10.4-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4232+g4733a499
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

My vps:

- Python v3.8.10-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4232+g4733a499
- aiohttp v3.8.1
- system info: Linux 5.4.0 #1 SMP Tue Jan 25 12:49:12 MSK 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by LeoCx1000** [comment]
By looking at that gif, it appears there's already some other client responding to the autocomplete request, hence it saying it had been already responded to, since you can only respond to an interaction once

**Comment by LostPaul** [comment]
> By looking at that gif, it appears there's already some other client responding to the autocomplete request, hence it saying it had been already acknowledged/unknown, since you can only respond to an interaction once

Oh yeah it looks like the bot runs twice on my vps and I stopped it through pm2 but it keeps running somehow even though pm2 says it got stopped thanks anyways
