### ISSUE TITLE
add interactions endpoint

### ISSUE THREAD

**Issue by thedtvn** [Rapptz/discord.py#8049]
### Summary

interactions endpoint to receive interactions via HTTP POSTs rather than over Gateway with a bot user.

### What is the feature request for?

The core library

### The Ideal Solution

You can optionally configure an interactions endpoint to receive interactions via HTTP POSTs rather than over Gateway with a bot user.
*_from discord_

**Comment by ImVaskel** [comment]
discord.py isn't a webserver, so this doesn't make much sense to support.

**Comment by duongtuan303030** [comment]
> discord.py isn't a webserver, so this doesn't make much sense to support.

discord.py can add by add webserver use aiohttp

**Comment by cheehong1030** [comment]
> discord.py can add by add webserver use aiohttp

This setting can reduce the role resources of the bot
But the premise is that you must open the server port

**Comment by rfvermut** [comment]
This can be used in AWS Lambda Function URL scenario. No need to embed any webserver code, you will get your payload directly to function.
