### ISSUE TITLE
command_prefix=None for no message command

### ISSUE THREAD

**Issue by sevenc-nanashi** [Rapptz/discord.py#8057]
### Summary

It would be good if we can specify None for disabling message command(old style one). 

### What is the feature request for?

discord.ext.commands

### The Problem

commands.Bot has many good things, such as listener, Extensions, Cogs. So I want to use these things, without message commands.

### The Ideal Solution

Disable message command with `command_prefix=None`.

### The Current Solution

`command_prefix=" "` solves this, but None is more beautiful and simple.

**Comment by AbstractUmbra** [comment]
This was solved in #7809 where we allow `command_prefix=[]`, versus `command_prefix=None`.
