### ISSUE TITLE
Have any solution for verify NSFW Channels?

### ISSUE THREAD

**Issue by katho162** [Rapptz/discord.py#806]
Discord has changed how nsfw channel works and now has no way to verify if it is a nsfw channel but have an issue in this github to solve that but for me didn't work. anyone maybe can help me on that?

**Comment by TheTrain2000** [comment]
The `async` branch of this library will not receive support for NSFW channels, along with any other new features such as audit logs and channel categories. If you'd like to access these new features, please see the `rewrite` branch. 

Support server: https://discord.gg/discord-api
- https://github.com/Rapptz/discord.py/tree/rewrite for the source code
- http://discordpy.readthedocs.io/en/rewrite/ for the documentation
- http://discordpy.readthedocs.io/en/rewrite/migrating.html for a migrating guide from async -> rewrite
- https://github.com/Rapptz/discord.py/tree/rewrite/examples for examples

**Comment by katho162** [comment]
and how i can know if i'm using the rewrite?

**Comment by TheTrain2000** [comment]
If you do `print(discord.__version__)` and it isn't `1.0.0a` then you aren't using rewrite.

**Comment by katho162** [comment]
well them tells i'm using the 0.16 but how i can update that, becouse i had instaled like the https://github.com/Rapptz/discord.py/tree/rewrite tells but nothing had changed

**Comment by TheTrain2000** [comment]
```py
$ python3 -m pip install -U git+https://github.com/Rapptz/discord.py@rewrite
# or with voice
$ python3 -m pip install -U git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]
```

**Comment by katho162** [comment]
ooh, that works now! thanks, apologize for my noob questions becouse i'm newbie in python... but very thanks
