### ISSUE TITLE
Empty __slots__ in Intents class (flags.py) causing pylint(assigning-non-slot) in VSC

### ISSUE THREAD

**Issue by Aguileitus** [Rapptz/discord.py#8060]
### Summary

Pylint is highlighting pylint(assigning-non-slot) error while using "intent.members = True" in Visual Studio Code. 

### Reproduction Steps

Use pylint linter in Visual Studio Code (Version: 1.67.2 (user setup))

You should probably add the following to settings.json:

```
    "python.linting.pylintEnabled": true,
    "python.linting.enabled": true,
```

Create a dummy bot and use `intents.members = True`

### Minimal Reproducible Code

```python
intents: discord.Intents = discord.Intents.default()
intents.members = True
```

### Expected Results

Pylint error should not be shown.

### Actual Results

Pylint is highlighting error:

`Assigning to attribute 'members' not defined in class slots pylint(assigning-non-slot)`

![image](https://user-images.githubusercontent.com/14335637/169738313-feef0a2e-e7f3-4faa-89f7-1bda73904542.png)

### Intents

members

### System Information

- Python v3.10.4-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19043

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Currently in Intents class (flags.py), __slots__ is empty:

`__slots__ = ()`

The error disappears if you change it to:

`__slots__ = ('members')`

So I think this class is missing to add the necessary attributes just like it's done in other classes (like Integration or StickerPack).

Thanks :)

**Comment by Rapptz** [comment]
This is a linter bug.
