### ISSUE TITLE
max_concurrency broken

### ISSUE THREAD

**Issue by rxnk** [Rapptz/discord.py#8071]
### Summary

commands.max_concurrency seems to not function as it should

### Reproduction Steps

@bot.command()
@commands.max_concurrency(1, commands.BucketType.user)
async def test(ctx):
  await asyncio.sleep(3)
  await ctx.send('xx')

### Minimal Reproducible Code

```python
https://cdn.discordapp.com/attachments/977063298971365418/979165092241358888/unknown.png
```

### Expected Results

it's supposed to say its currently running whilst the command is still running

### Actual Results

it continues to say its running even though it finished 

### Intents

discord.Intents.all()

### System Information

- Python v3.9.5-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4294+g77baa06a
- aiohttp v3.8.1
- system info: Linux 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by SebbyLaw** [comment]
I cannot reproduce this. I suspect there is something else happening elsewhere in your code causing this to happen.
