### ISSUE TITLE
edit_message never finishes

### ISSUE THREAD

**Issue by notAlaanor** [Rapptz/discord.py#808]
Hello,
I have an issue in which the `edit_message` method doesn't ever "finish", for example, I have a method which prints help, each second edits the message, then after the 15th second deletes the message, like so:
```python
async def print_help(target):
    _msg = await client.send_message(target.channel, "**HELP:**\n"
                                              "```,commands    -   get a list of all commands PM'd\n"
                                              "``` This message will be automatically removed in 15 seconds.")

    timer_counter = [1]
    del_timer = Timer(1, del_help_msg, [timer_counter, _msg], True) # time interval 1 second, callback, callback arguments, should loop
```
`Timer` is a simple asyncio task class I wrote. However, the issue sits here:
```python
async def del_help_msg(timer_counter, _msg):
    timer_counter[0] = timer_counter[0] + 1

    print(timer_counter[0])

    await client.edit_message(_msg, "This message will be automatically removed in "
                              + timer_counter[0] +
                              " seconds.")

    if timer_counter == 15:
        await client.delete_messages(_msgs)
```
`1` is printed once, then never printed again, however when I remove the `edit_message` method from `del_help_msg`, it prints the timer seconds perfectly fine. Is the issue with the Timer class, or is the `edit_message` indeed not finishing?

**Comment by Rapptz** [comment]
Probably your timer.

There's also a rate limit of 5 message actions (sending, editing) per 5 seconds so the library has to back off to meet that rate limit.

**Comment by Vexs** [comment]
Take a look at asyncio.sleep, it's a bit more relevant for this.

**Comment by notAlaanor** [comment]
Alright, I'll probably tone down the updates to every 2.5 or 5 seconds and modify my Timer class. Thanks for the help.
