### ISSUE TITLE
Discord not won't run anymore

### ISSUE THREAD

**Issue by Pabsb** [Rapptz/discord.py#8090]
### Summary

Discord bot now shows errors when trying to run

### Reproduction Steps

Just use a clean install and try to get a discord bot to run

### Minimal Reproducible Code

```python
import os
import random
import discord

token = os.getenv("DISCORD_TOKEN")
my_guild = os.getenv("DISCORD_GUILD")

intents = discord.Intents.default()
client = discord.Client(intents=intents)

@client.event
async def on_ready():
    for guild in client.guilds:
        if guild.name == my_guild:
            break

    print(
        f"{client.user} is connected to the following guild:\n"
        f"{guild.name}(id: {guild.id})"
    )

client.run(token)
```

### Expected Results

Botname is connected to the following guild:
Guildname GuildID

### Actual Results

Traceback (most recent call last):
  File "bot.py", line 22, in <module>
    client.run(token)
  File "/home/pablo/.venvs/discord/lib/python3.8/site-packages/discord/client.py", line 723, in run
    return future.result()
  File "/home/pablo/.venvs/discord/lib/python3.8/site-packages/discord/client.py", line 702, in runner
    await self.start(*args, **kwargs)
  File "/home/pablo/.venvs/discord/lib/python3.8/site-packages/discord/client.py", line 665, in start
    await self.login(*args, bot=bot)
  File "/home/pablo/.venvs/discord/lib/python3.8/site-packages/discord/client.py", line 511, in login
    await self.http.static_login(token.strip(), bot=bot)
AttributeError: 'NoneType' object has no attribute 'strip'

### Intents

Its in the code

### System Information

- Python v3.8.10-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Linux 5.4.0-113-generic #127-Ubuntu SMP Wed May 18 14:30:56 UTC 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by drobotk** [comment]
Your token is None. Check the environment variable
