### ISSUE TITLE
Add a default_permission option to Slash Commands

### ISSUE THREAD

**Issue by TIBI4** [Rapptz/discord.py#8094]
### Summary

Slash Commands should have a decorator similar to @app_commands.default_permissions(), but to allow bot devs to set a default permission for their commands.

### What is the feature request for?

discord.ext.commands

### The Problem

As far as I digged into the docs ([this](https://discordpy.readthedocs.io/en/latest/interactions/api.html#:~:text=%40discord.app_commands.default_permissions(**perms))), there is no way to set a default value for Slash Commands permissions.

### The Ideal Solution

Have a decorator for setting a default value for Slash Command permission for each command.

For example:

**No solution:**
```
@app_commands.command(name="Awesome command.", description="This is a description.")
@app_commands.describe(word="Awesome word.")
async def awesomeCommand(self,interaction:Interaction,word:str):
    await interaction.response.send_message(embed=discord.Embed(title=f"The word **{word}** I'm awesome!", color=BOT_COLOR))
```

**Ideal solution:**
```
#Ideal solution:
@app_commands.command(name="Awesome command.", description="This is a description.")
@app_commands.describe(word="Awesome word.")
@app_commands.default_permission(False) #"default_permission" without the ending "s".
async def awesomeCommand(self,interaction:Interaction,word:str):
    await interaction.response.send_message(embed=discord.Embed(title=f"The word **{word}** I'm awesome!", color=BOT_COLOR))
```

### The Current Solution

No solution (afaik).

### Additional Context

I found these closed issues, but both were closed:
https://github.com/Rapptz/discord.py/issues/7592
https://github.com/Rapptz/discord.py/issues/7943

**Comment by Rapptz** [comment]
This is the deprecated and slated to be removed permissions v1. The new permission system, dubbed permissions v2, has been implemented and uses a permission bitmask instead.
