### ISSUE TITLE
Client.fetch_invite() throws KeyError: 'channel'

### ISSUE THREAD

**Issue by owocado** [Rapptz/discord.py#8095]
### Summary

Client.fetch_invite() throws KeyError when used with invite codes which does not have a channel associated with it.

### Reproduction Steps

Use `Client.fetch_invite` for invite code `YXfZcFe93D`

### Expected Results

for `fetch_invite` function to work successfully and return discord.Invite object with relevant data.

### Actual Results

It throws/errors with a KeyError instead.

### Intents

all

### System Information

- Python v3.9.13-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4318+g823d650e
- aiohttp v3.8.1
- system info: Linux 5.15.0-1006-oracle Ubuntu SMP Fri May 20 08:21:02 UTC 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [ ] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I think the invite was created from the new role membership intro channel, and as you can see on the payload from API (https://discord.com/api/invite/YXfZcFe93D), `channel` key/payload is missing and instead there is new `channel_id` key set to `null` instead. In the dpy library, this errors at: https://github.com/Rapptz/discord.py/blob/823d650e9748a58442bde80c233e3fa790117b20/discord/invite.py#L444-L446

**Comment by Rapptz** [comment]
The structure is documented to have an always available key at `channel` here: https://discord.com/developers/docs/resources/invite#invite-object

The fact it doesn't is either a breaking change or a discord bug.

**Comment by Rapptz** [comment]
I reported the bug earlier and it must have been fixed then.
