### ISSUE TITLE
on_server_join not working

### ISSUE THREAD

**Issue by mission** [Rapptz/discord.py#810]
trying to use on_server_join event but it seems to never be triggered for me. I added the event to the basic bot in the examples and in my logging it never dispatches the event nor does it print the message "Connected to server!"

the bot shows in the server, and reacts to commands, but will not trigger that event

```python
@bot.event
async def on_server_join(server):
    print("Connected to server!")
```

**Comment by Rapptz** [comment]
Not sure what you think that event does -- but it's only triggered when someone adds your bot to a new server.

**Comment by mission** [comment]
oh, the function name is misleading then and the docs are wrong
```
discord.on_server_join(server)
Called when a Server is either created by the Client or when the Client joins a server.
```

of  course a more appropriate name isn't easy to come up with without it being long
like on_join_added_server or on_added_to_server(doesnt really get the joined part across)
hmm..

**Comment by Rapptz** [comment]
The documentation is pretty clear.

1. It's called when the client *creates* a server.
2. It's called when the client *joins* a server.

I don't really know where your confusion lies. You don't "join" a server by existing in it.

**Comment by mission** [comment]
`You don't "join" a server by existing in it." ok, no, but you have to get into the server somehow after logging in. when i launch the bot, it connects to the servers associated with the account. once  connected to said servers i was expecting an event like on_server_join to be called so if you wanted to initialize some stuff at that time you could.
what it actually does is gets called when the client is added to a server or the client creates a server

to me "joins" == "connects to"(meaning anytime my bot connects to a server)

anyway we can close the issue, sorry for wasting your time with my misunderstanding
