### ISSUE TITLE
`ignore_bots` option in `commands.Bot` 

### ISSUE THREAD

**Issue by Skylake-dev** [Rapptz/discord.py#8101]
### Summary

Currently only commands issued by other bots are ignored by defualt. It would be nice to extend this behaviour and be able to ignore all events triggered by other bots

### What is the feature request for?

discord.ext.commands

### The Problem

Currently all events (message edit, deletion, etc ) are triggered also for bots.
This means that if i want to ignore other bots i need to perform the check on the bot flag of the user that triggered the event. This needs to be repeated for every event that i want to manage with the bot. 

### The Ideal Solution

Having a flag that can be set in the bot to ignore other bots for every event that can be set on bot creation
`my_bot = command.Bot(command_prefix='?', ignore_bots=True)`
or after, like
`my_bot.ignore_bots=True`

### The Current Solution

To check manually in every event.

**Comment by rtk-rnjn** [comment]
There are some bots, which are having features which depends on other "bots", and most of them are having more than one `on_message_x` like listeners, such `kwarg` (`ignore_bots`) would instead restrict features.

**Comment by Rapptz** [comment]
This isn't how events function in the library and there would be no consistent way to do this either way since not all events deal with users. Realistically, the best way to do this is just to do it within every event like you've alluded to. Doing anything else would be incredibly hard to do generically and a performance penalty when it came to dispatching.

**Comment by Skylake-dev** [comment]
Thanks for the quick reply.
Yeah i figured that it would not have been so easy but maybe it was possibile. I will look into this a bit more by myself.
