### ISSUE TITLE
support text chat for voice channel

### ISSUE THREAD

**Issue by duongtuan303030** [Rapptz/discord.py#8102]
### Summary

support text chat for voice channel

### What is the feature request for?

The core library

### The Problem

![image](https://user-images.githubusercontent.com/80153297/171868478-d5a79613-a6a8-4f47-8673-5d3fec3e55b2.png)
![image](https://user-images.githubusercontent.com/80153297/171868484-963ec956-7b1c-480a-a0a8-ffc82fbd82fb.png)
![image](https://user-images.githubusercontent.com/80153297/171868805-d39f05de-0d14-4933-8599-5852145ea64d.png)

### The Ideal Solution

no

**Comment by Rapptz** [comment]
This was implemented 2 months ago in v2 as of https://github.com/Rapptz/discord.py/commit/2aca705b95ba5be24e34efa2b76b260a8e66ab8d

**Comment by duongtuan303030** [comment]
> This was implemented 2 months ago in v2 as of [2aca705](https://github.com/Rapptz/discord.py/commit/2aca705b95ba5be24e34efa2b76b260a8e66ab8d)

 thank for info
