### ISSUE TITLE
The client.get_guild dont returning new users in server

### ISSUE THREAD

**Issue by XuliGan4eg2006** [Rapptz/discord.py#8113]
### Summary

The function is broken

### Reproduction Steps

Iam using on_message(self, message) as event. If new user joins to server and writes message, the get_guild returns only old users. This bug fixes only after full reboot of script.

### Minimal Reproducible Code

```python
import discord

TOKEN_AUTH = "" 


class MyClient(discord.Client):
    async def on_ready(self):
        print('Logged on as', self.user)
    

    async def on_message(self, message):
        print(client.get_guild(ID-HERE).members)

intents = discord.Intents.default()
intents.members = True

client = MyClient(intents=intents)
client.run(TOKEN_AUTH, bot=False)
```

### Expected Results

New users in client.get_guild(ID-HERE).members

### Actual Results

Returning only old useres

### Intents

default

### System Information

- Python v3.10.4-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by LeoCx1000** [comment]
> ``bot=False``

We don't provide self-bot support.
