### ISSUE TITLE
[v2] Scheduled events not auto-starting, start() claims channel must be set

### ISSUE THREAD

**Issue by xSetrox** [Rapptz/discord.py#8114]
### Summary

Scheduled events are not auto-starting, start() claims channel must be set

### Reproduction Steps

I created a scheduled event and then tried to start it. 

### Minimal Reproducible Code

```python
self.scheduled_event = await guild.create_scheduled_event(name = event_name, description = "hello", start_time = discord.utils.utcnow() + datetime.timedelta(seconds=5), entity_type = discord.EntityType.voice, channel = random.choice(active_vcs))
await self.scheduled_event.start()
```

### Expected Results

I expected the event to start on its own since I specified a start time. Even if this was not the case I expected `start()` to start it.

### Actual Results

The event does not auto-start despite the time for the event seeming correct in my guild. `start()`, which may or may not be redundant depending on what start_time should be doing, also produces an error:
`TypeError: channel must be set when entity_type is voice or stage_instance`.
Full error is [here](https://media.discordapp.net/attachments/669155775700271126/983130143071539310/unknown.png?width=1563&height=598)

### Intents

All

### System Information

```
(env) lance@ubuntu-4gb-ash-1:~/lanceBot$ python -m discord -v
- Python v3.8.10-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4283+g37076a04
- aiohttp v3.8.1
- system info: Linux 5.4.0-110-generic #124-Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
> I expected the event to start on its own since I specified a start time.

This automation is done by Discord, not the library so it should do it assuming times are synced up.

> Even if this was not the case I expected start() to start it.

Yes, there is a bug in the library with the `start()`, `cancel()`, and `end()` calls, but this has no bearing on the event automatically starting at the appropriate time.
