### ISSUE TITLE
`python -m discord -v` displays incorrect system info

### ISSUE THREAD

**Issue by emisdumb** [Rapptz/discord.py#8120]
### Summary

Operating system version is shown as "Windows 10" instead of "Windows 11"

### Reproduction Steps

1. Have Windows 11
2. Run `python -m discord -v` on the command line

### Minimal Reproducible Code

```python
n/a
```

### Expected Results

The correct operating system to be displayed

### Actual Results

"Windows 10" is displayed instead of "Windows 11"

### Intents

n/a

### System Information

- Python v3.10.4-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4324+gdb5a22d7
- aiohttp v3.8.1
- system info: Windows 10 10.0.22621

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

The build number is correct, but it should say "Windows 11 11.0.22621"

**Comment by Rapptz** [comment]
This uses the standard library `platform.uname()` function so not much I can do about it reporting weird information.

**Comment by GoogleGenius** [comment]
This is not a problem with Python nor discord.py. Windows 11 is technically almost practically Windows 10 under the hood. The versioning scheme has stayed the same.
