### ISSUE TITLE
Possible error in client.py...

### ISSUE THREAD

**Issue by Nixerton** [Rapptz/discord.py#813]
Basically I'm trying to implement a mute/unmute function in my discord bot, yet, when I try to check wether a user has permissions to write in a certain text channel (using the function "permissions_for") or not, I get an AttributeError exception stating the following:

`Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\Nicco.NICS-PC\Desktop\Discord Bot\BOT V 0.2.py", line 451, in on_message
    await unmute_user(message.channel,user_to_unmute)
  File "C:\Users\Nicco.NICS-PC\Desktop\Discord Bot\BOT V 0.2.py", line 28, in unmute_user
    permission = channel.permissions_for(user)
  File "C:\Python36\lib\site-packages\discord\channel.py", line 260, in permissions_for
    if member.id == self.server.owner.id:
AttributeError: 'NoneType' object has no attribute 'id'`

Any tips to fix it?

**Comment by mission** [comment]
I believe the error is the result of the user object being passed here isnt a vaild object (it ==None)
`permission = channel.permissions_for(user)`

Would need to see the code for the function unmute_user to tell you why this is happening though

**Comment by Nixerton** [comment]
`async def unmute_user(channel,user):
            permission = channel.permissions_for(user)
            #Check if the user has the permission to write
            unmute_overwrite = discord.PermissionOverwrite()
            unmute_overwrite.send_messages= True 
            await client.edit_channel_permissions(channel,user ,unmute_overwrite)
            await client.send_message(channel, ":white_check_mark: User "+str(user)+" has been unmuted!")
`

Here is it. Thank you for your help.

**Comment by mission** [comment]
im sorry, could i get the code for the function that is calling unmute_user, how are you setting user_to_mute?

**Comment by Nixerton** [comment]
Basically the bot takes the ID of the mentioned user, and then uses the get_member function that returns a Member obj, that is what permission_for() needs if I'm not mistaken. The code is quite messy at the moment but if these informations aren't enough I'll write it more clearly for you. Thank you again.

**Comment by Rapptz** [comment]
There are two possible scenarios here:

1. The guild has no owner (`Server.owner` is `None`)
2. The user you passed is `None`.

The library's v0.16.x release could handle cause 1 better but I think this might be a case of #2.

**Comment by Nixerton** [comment]
I'm sure that this is not a case of 2, I've tried passing `None` and it raises a different exception. 
About case 1, I don't understand how `Server.owner` has to do with this. I dind't find anything about it in the documentation.

**Comment by Rapptz** [comment]
Your traceback is in the line:

```py
if member.id == self.server.owner.id:
```

Since the exception is:

```py
AttributeError: 'NoneType' object has no attribute 'id'
```

That means either `member` is `None` or... `self.server.owner` is `None`.

Hence the two cases up there.

**Comment by Nixerton** [comment]
Right, my bad. I checked and `member` is not None, I'll look further in my code. I'm rewriting it in a more understandable way so I can post it here and you guys can help me figure out where the issue is.
