### ISSUE TITLE
`wait_until_ready` does not always respect ready state

### ISSUE THREAD

**Issue by jgayfer** [Rapptz/discord.py#8139]
### Summary

`wait_until_ready` does not wait if used too early, despite the cache not being ready.

### Reproduction Steps

Using `wait_until_ready` too early will not actually wait, despite `Client.is_ready()` returning `False`.

The reproduction example shown here is very contrived, but a more real world scenario is a call to `load_extension` for a cog that contains a background task, where the task is started in the setup hook, and that task blocks with a `wait_until_ready` before kicking off.

With the current version, sometimes a task will start executing despite the client cache not being ready, if the task is started directly from the cog's `setup` function.

### Minimal Reproducible Code

```python
import asyncio
import logging
from discord.client import Client

from discord import Intents

logging.basicConfig(level=logging.INFO)

client = Client(intents=Intents())

async def main():
    print(f"Ready? - {client.is_ready()}") # False
    await client.wait_until_ready() # Does not wait
    await client.start("token")

asyncio.run(main())
```

### Expected Results

In this contrived example, the client should not start, as we'll wait indefinitely for the cache to be ready.

### Actual Results

The client starts as normal, despite the explicit call to wait for the cache to be ready before starting (which will never happen as we haven't logged in).

### Intents

Intents()

### System Information

- Python v3.9.10-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4341+g3cb90199
- aiohttp v3.8.1
- system info: Darwin 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

It's possible to workaround this by starting the task via `setup_hook`

**Comment by Gorialis** [comment]
Clients remain unaware of the event loop as long as possible to try and improve usability. As part of this, before the client is made "aware" of the event loop, the client is not fully initialized and things like `wait_until_ready` and `load_extension` (on Bot) will not work.

You have two (supported) choices:
- Do anything that relies on the event loop after `run` or `start`.
- Make the client explicitly aware of the event loop like so:
```py
async with client:
    await client.wait_until_ready()  # if you REALLY want to do this
```

**Comment by Rapptz** [comment]
This happens because the bot is not bound to a loop when constructed and then when there is a running loop the library is not aware of it due to initialisation steps being skipped. In order to properly initialise you need to do a few things before a call to `wait_until_ready`:

1. Use the `async with` context manager
2. Use `login()` before `wait_until_ready`

There is an argument to be made that this should raise instead of silently passing but I'm not sure, I'd have to get the opinions of others on what they think should happen in this scenario.

**Comment by jgayfer** [comment]
Thanks for the responses.

I would be in favour of raising, or at least logging a warning, when methods that shouldn't be called in a given context are called.

I have been running into a fair bit of unexpected behaviour with `wait_until_ready` in its current state. In some cogs it works as expected, but not in others; I believe this has to do with the order the cogs are loaded.

In the current state of the function, I am likely to not use `wait_until_ready` for fear of not being able to trust it will behave correctly. Of course I can take the steps outlined above to ensure it will work, but I'd rather not rely on functions that require additional setup in order for them to behave correctly.

Your thoughts @Rapptz? I am willing to take on any work around this.

**Comment by Rapptz** [comment]
Using the asynchronous context manager and running your code there should definitely fix all your issues. Honestly, I'm a bit unsure how you managed to get to this state anyway considering the only way to do it is to do all this before `login()` is called and `start()` calls login.

There's a reason why every example either does this inside `setup_hook` (when async initialisation is complete) or inside the async with block.

I'm fine with raising, I'm just concerned that this was hit in the first place.

**Comment by jgayfer** [comment]
The quick and dirty of how this occurred is having my `load_extension()` calls  before `start()`, where some of the extensions kick off tasks which include a `wait_until_ready`.

**Comment by Rapptz** [comment]
I suppose in that case doing this should work fine:

```py
async with bot:
    # load whatever
    await bot.start(...)
```

Should work for you.

**Comment by Rapptz** [comment]
This raises now.
