### ISSUE TITLE
Bug in `PartialEmoji.read()`

### ISSUE THREAD

**Issue by Zapd0s** [Rapptz/discord.py#8148]
### Summary

A `discord.PartialEmoji`, obtained using `PartialEmoji.from_str` raises DiscordException: Invalid state (no ConnectionState provided)

### Reproduction Steps

- Instantiate a `discord.PartialEmoji` using `discord.PartialEmoji.from_str()`, providing a custom emoji string as an argument.
- Use the `.read()` method on the object.

### Minimal Reproducible Code

```python
import discord

emoji = discord.PartialEmoji.from_str("<:CatCryThumbs:924139760807739422>")
await emoji.read()
```

### Expected Results

An object of type `bytes` is returned

### Actual Results

```
Traceback (most recent call last):
  File "/home/a/env/lib/python3.8/site-packages/jishaku/features/python.py", line 149, in jsk_python
    async for send, result in AsyncSender(executor):
  File "/home/a/env/lib/python3.8/site-packages/jishaku/functools.py", line 119, in _internal
    value = await base.asend(self.send_value)
  File "/home/a/env/lib/python3.8/site-packages/jishaku/repl/compilation.py", line 141, in traverse
    async for send, result in AsyncSender(func(*self.args)):
  File "/home/a/env/lib/python3.8/site-packages/jishaku/functools.py", line 119, in _internal
    value = await base.asend(self.send_value)
  File "<repl>", line 3, in _repl_coroutine
    await emoji.read()
  File "/home/a/env/lib/python3.8/site-packages/discord/partial_emoji.py", line 262, in read
    return await super().read()
  File "/home/a/env/lib/python3.8/site-packages/discord/asset.py", line 84, in read
    raise DiscordException('Invalid state (no ConnectionState provided)')
discord.errors.DiscordException: Invalid state (no ConnectionState provided)
```

### Intents

guilds, members, messages, message_content, reactions

### System Information

- Python v3.8.10-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4320+g06c1f44d
- aiohttp v3.8.1
- system info: Linux 5.13.0-1025-gcp #30~20.04.1-Ubuntu SMP Tue Apr 26 03:01:25 UTC 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
This is documented and by design.

There's no associated state with it so it doesn't know how to make an HTTP request. If you want to do this you have two options:

1. Retrieve it as a full Emoji object using `Client.get_emoji`
2. Access the URL using the `url` attribute and then reading the bytes yourself using aiohttp.
