### ISSUE TITLE
As a developer I would like logging to help troubleshoot.

### ISSUE THREAD

**Issue by Tylerlhess** [Rapptz/discord.py#815]
I would like to be able to add async logging for my bot. This is for a few reasons but I have a service that has many moving parts one of which is a Bot that automates things for people.  When the bot breaks I want to be able to look at the inputs and outputs that happened. I would also like to be able to get alerts when things happen like that but mainly I don't want to have to repro everything because something didn't work and they don't know what they did. Having a way to easily send the messages or other parts of the program to logs would be beneficial.

**Comment by Naught0** [comment]
This exists!
Async branch: http://discordpy.readthedocs.io/en/latest/logging.html   
Rewrite branch: https://discordpy.readthedocs.io/en/rewrite/logging.html

**Comment by Tylerlhess** [comment]
Thanks, I was looking to have a function but didn't realize I just needed to implement the logging and it's taken care of for the most part.
