### ISSUE TITLE
Guild input in App Commands

### ISSUE THREAD

**Issue by balt-is-you-and-shift** [Rapptz/discord.py#8153]
### Summary

Allow adding file/guild inputs to app commands

### What is the feature request for?

The core library

### The Problem

I can't add file or guild inputs to app commands.

### The Ideal Solution

Add `discord.Guild`, `discord.File`, etc. selection to app commands.

### The Current Solution

There isn't any.

### Additional Context

I saw this was possible with the Blurplefier bot in the Project Blurple discord. You can't access these commands at the moment, though, since the Blurple event is over for the year.

**Comment by balt-is-you-and-shift** [comment]
After posting, I saw this in Dyno, so member selection is possible as well.
![image](https://user-images.githubusercontent.com/59123926/173977890-1bc4fe37-ad38-4115-8ff2-6a4c8d32ca07.png)

**Comment by Hirakudev** [comment]
Simply type hinting your arguments with `discord.Member` or `discord.Attachment` will do this for you.

```py
@app_commands.command(name="...", description="...")
async def command_name(interaction: discord.Interaction, member: discord.Member, file: discord.Attachment);
    #do stuff here
```

**Comment by balt-is-you-and-shift** [comment]
Ah, I didn't catch that. Thanks!

**Comment by balt-is-you-and-shift** [comment]
discord.Guild isn't accounted for.

**Comment by Hirakudev** [comment]
That is something you will have to account for yourself using app command choices / autocomplete. Only core "mentionables" such as users, members and channels are supported.

https://discordpy.readthedocs.io/en/latest/interactions/api.html?highlight=autocomplete#discord.app_commands.Command.autocomplete

**Comment by Rapptz** [comment]
Discord does not have a guild option type.

**Comment by balt-is-you-and-shift** [comment]
huh, could have sworn it was. sorry
