### ISSUE TITLE
"help" command using checks when not needed.

### ISSUE THREAD

**Issue by Swyreee** [Rapptz/discord.py#8154]
### Summary

Help command using other command's check even if that check is not decorated with @bot.check

### Reproduction Steps

- Create a temporary cog using the code below
- Run the bot
- Use "help" command
- An error should appear

### Minimal Reproducible Code

```python
from discord.ext import commands


class TestCogCheck:
    @staticmethod
    def this_will_be_false(ctx: commands.Context) -> bool:
        a.invalid_prop = False
        return True


class TestCog(commands.Cog):
    def __init__(self, bot: commands.AutoShardedBot) -> None:
        self.bot = bot

    @commands.hybrid_command()
    @commands.check(TestCogCheck.this_will_be_false)
    async def hi(self, ctx: commands.Context):
        await ctx.send("Hi! with err")

    @commands.hybrid_command()
    async def hi_nm(self, ctx: commands.Context):
        await ctx.send("Hi! normal")
```

### Expected Results

The help command will appear when using "help".

### Actual Results

NameError: name 'a' is not defined

### Intents

discord.Intents.default(), members, message_content

### System Information

- Python v3.8.13-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4359+g1ba290d8
- aiohttp v3.8.1
- system info: Linux 5.15.0-37-generic #39-Ubuntu SMP Wed Jun 1 19:16:45 UTC 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by AbstractUmbra** [comment]
`@commands.check()` will add a check to the Command (or in this case, the HybridCommand) to be called before execution, during the command processing stage.

This means that when this command is ran, there is indeed a `NameError` within, and it will be raised accordingly.
I'm not entirely sure what the point you're trying to make here is...?

Nowhere in this code does this bad check make it's way into the HelpCommand checks. This seems entirely self-contained.

**Comment by Swyreee** [comment]
> This means that when this command is ran, there is indeed a NameError within, and it will be raised accordingly.

I know, I am aware of this. But what I mean here is if you run the `help` command, not the problematic `hi` one, it will throw a `NameError` instead of what I want to show: the docstring of the command method.

For example, I have a check class containing checks for voice commands: `user_must_in_voice`, `bot_must_in_voice`, etc. (all are non-global) and they involve some property accesses and checkings, most of them will be non-existent or `None`. Therefore, an `Exception`/`Error` will throw, like when you are outside of a voice channel, an `AttributeError` will be thrown.
```python
def check_me():
    def pred(ctx: commands.Context):
        # stuffs that might throw exception
        return True
        
    return commands.check(pred)
```

So what I mean is, I want to check other commands' help without involving the checks of some command.

**Comment by Rapptz** [comment]
The help command runs checks in order to know whether to hide the command or not. You can disable this by passing `verify_checks` to the [`HelpCommand`](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.HelpCommand).
