### ISSUE TITLE
Context menus require resyncing after restarting the bot

### ISSUE THREAD

**Issue by Jakoobb** [Rapptz/discord.py#8167]
### Summary

Everytime i restart my bot, I must resync my commands first, otherwise using context menus results in "CommandNotFound"

### Reproduction Steps

- Run the bot
- Sync commands
- Restart the bot
- Use any context menu

### Minimal Reproducible Code

```python
import discord
from discord.ext import commands

intents = discord.Intents.default()
intents.presences = intents.members = intents.message_content = True

bot = commands.Bot(
    intents=intents,
    command_prefix='.',
    help_command=None,
    case_insensitive=True
)

@bot.tree.context_menu(name='say')
async def say(interaction: discord.Interaction, member: discord.Member):
    await interaction.response.send_message('I said something!')

@bot.command(name='sync')
async def sync(ctx: commands.Context) -> None:
    for guild in bot.guilds:
        bot.tree.copy_global_to(guild=guild)
        await bot.tree.sync(guild=guild)

bot.run('token')
```

### Expected Results

The bot responds after the restart.

### Actual Results

Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.10.5/envs/chonker/lib/python3.10/site-packages/discord/app_commands/tree.py", line 989, in wrapper
    await self.call(interaction)
  File "/home/user/.pyenv/versions/3.10.5/envs/chonker/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1132, in call
    await self._call_context_menu(interaction, data, type)
  File "/home/user/.pyenv/versions/3.10.5/envs/chonker/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1065, in _call_context_menu
    raise CommandNotFound(name, [], AppCommandType(type))
discord.app_commands.errors.CommandNotFound: Application command 'say' not found

### Intents

all intents are enabled

### System Information

- Python v3.10.5-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4367+g64849ebc
- aiohttp v3.7.4.post0
- system info: Linux 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
Yes, this is (mostly) by design.

Your command definition is global only and you're syncing by copying the data to a guild and then syncing. When you restart the bot, the code no longer knows you copied it over so it's global only again. However, there is a `fallback_to_global` keyword only argument in the `CommandTree` that falls back to the global command in cases like this, and it defaults to `True` such as in this code here.

That being said, there is a bug with `fallback_to_global` where it was ignored for context menus.
