### ISSUE TITLE
Guild had no attribute 'region'

### ISSUE THREAD

**Issue by zairullahdev** [Rapptz/discord.py#8168]
### Summary

Literally any fix for this?

### Reproduction Steps

by calling `ctx.guild.region`

### Minimal Reproducible Code

```python
`player = self.bot.lavalink.player_manager.create(ctx.guild.id, endpoint=str(ctx.guild.region))`
```

### Expected Results

The old version could do this.

### Actual Results

`Guild has no attribute 'region'`

### Intents

discord.Intents().All()

### System Information

- Python v3.10.5-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4367+g64849ebc
- aiohttp v3.7.4.post0
- system info: Linux 4.19.127-gfe17e779f-dirty #1 SMP PREEMPT Mon Mar 7 10:54:37 CST 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by GnomedDev** [comment]
Region was moved to be voice channel specific by discord.

**Comment by Rapptz** [comment]
https://discordpy.readthedocs.io/en/latest/migrating.html#removals

**Comment by zairullahdev** [comment]
How to replace the code with it?

**Comment by Rapptz** [comment]
Regions are now per voice channel, so you'll have to do [`voice_channel.rtc_region`](https://discordpy.readthedocs.io/en/latest/api.html#discord.VoiceChannel.rtc_region) where `voice_channel` is the channel you're connecting to.
