### ISSUE TITLE
How do I target the user who sent the command?

### ISSUE THREAD

**Issue by MoWizard** [Rapptz/discord.py#817]
Hello,
I have had issues trying to find a command that will let me target the user who sent a command. The `bot.say` command works like a charm but using commands like `bot.send_file` or `bot.send_message` won't send unless you give a specific channel or user.
Is there a way to find the user who sent the command or am I just trying to do something that is impossible (hint: it is not impossible).

Thanks for your help!!

**Comment by hanss314** [comment]
Use `@commands.command(pass_context=True)` and use `ctx.message.author`

**Comment by MoWizard** [comment]
I tried that but I got an error saying `NameError: name 'ctx' not defined`

**Comment by hanss314** [comment]
You have to pass it in as a parameter `async def command(ctx, *args)`

**Comment by MoWizard** [comment]
Thank you so much, you are a legend
