### ISSUE TITLE
Interactions in view documentation drop down

### ISSUE THREAD

**Issue by ChrisLovering** [Rapptz/discord.py#8174]
### Summary

Include a link to the Interactions manual in the "View Documentation For" drop down in docs

### What is the feature request for?

The documentation

### The Problem

Navigate easier to the Interactions API documentation. By including it in this drop down, user's don't need to go back to the index every time they want to navigate there.

### The Ideal Solution

The Interactions manual is an option in the dropdown, when clicked navigates the user to that page.

### The Current Solution

user navigates back to the index and clicks on the link under the manuals title.

### Additional Context

This is the relevant part in the code https://github.com/Rapptz/discord.py/blob/master/docs/_templates/layout.html#L92

I just don't know how to go about adding something to this template.

**Comment by Rapptz** [comment]
That interactions page is just temporary and I'm planning on removing it when api.html gets split into multiple pages.
