### ISSUE TITLE
Sorry but I'm still noob at adding apps_command

### ISSUE THREAD

**Issue by zairullahdev** [Rapptz/discord.py#8180]
### Summary

Literally can someone help me?, This happen when I'm using app_commands

### Reproduction Steps

Trying register slash command

### Minimal Reproducible Code

```python
@app_commands.command(name='lvbypass', description='Bypass Linkvertise')
```

### Expected Results

It's will register the slash command 

### Actual Results

`TypeError: unsupported type annotation <class 'discord.interactions.Interaction'>`

### Intents

discord.Intents().All()

### System Information

- Python v3.10.5-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4374+g7ad00750
- aiohttp v3.8.1
- system info: Linux 4.19.127-gfe17e779f-dirty #1 SMP PREEMPT Mon Mar 7 10:54:37 CST 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
This is not the place to ask library questions, go to the [official server](https://discord.gg/dpy) for that.
