### ISSUE TITLE
Add support for changing AppInfo.description

### ISSUE THREAD

**Issue by nashradical** [Rapptz/discord.py#8184]
### Summary

Is possible, add support for changing the Application's description (viewed as the bots "bio") through the library.

### What is the feature request for?

The core library

### The Problem

Allows developers to provide more dynamic/verbose info through the apps bio. Can function as a good alternative to "change_presence()"

### The Ideal Solution

Allow developers to update the bots description/bio through the python library

### The Current Solution

No current solution besides manually changing it through the Discord Developer Portal.

### Additional Context

I am not sure if this is a possible feature to add.

**Comment by GoogleGenius** [comment]
This isn't possible I believe.

**Comment by RGBCube** [comment]
This is an API limitation, you can only change the bots bio via the developer portal.
