### ISSUE TITLE
Problem with default_channel

### ISSUE THREAD

**Issue by entchen66** [Rapptz/discord.py#819]
Hey, I wanted to use the member.server.default_channel.name command to get the default channel, to write in when anew member join, but instead I get the error:

AttributeError: 'NoneType' object has no attribute 'name'

so why the defaultChannel is none?

hope we could fix it together :)

**Comment by Helehelehele** [comment]
The concept of default channels is gone now. See [here](https://github.com/discordapp/discord-api-docs/blob/master/docs/Change_Log.md#breaking-change-default-channels).

**Comment by Vexs** [comment]
Default channel is no longer functional due to the removal of it from discord. The recommended alternative is having the user of the bot set a welcome channel with configuration commands. (Or hardcode a channel ID I guess)

**Comment by entchen66** [comment]
sadly :(
So some clue how to get the first visible channel on the server?

**Comment by Vexs** [comment]
https://docs.python.org/3/howto/sorting.html

http://discordpy.readthedocs.io/en/latest/api.html#discord.Channel.position

You also want to check for the ability to send/read messages. I really just recommend having the user set a channel. More flexible, and in some ways a little easier.

**Comment by entchen66** [comment]
yeah, but then I will need a file, where I save settings for each server or a daabse.. hmm
