### ISSUE TITLE
Alphabetize subsections of each individual Class

### ISSUE THREAD

**Issue by Luunae** [Rapptz/discord.py#8199]
### Summary

Make it nicer to scan through documentation via alphabetization.

### What is the feature request for?

The documentation

### The Problem

When viewing sections of the docs(notably, Classes), the initial lists of Attributes and Methods are alphabetized. The descriptions of each feature, however, are not. I'll use [discord.ext.commands.Context()](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#context) for context.

When you go down the initial attributes list, it reads `args`, `author`, `bot`, `channel`, ... in alphabetical order.

Similarly when you go down the initial Methods list, it reads `fetch_message`, `history`, `invoke`, `pins`, ... in alphabetical order.

But going down the descriptions you get `message`, `bot`, `args`, `kwargs`, `prefix`, `commmand`, ...

No sense of ordering whatsoever!

### The Ideal Solution

Order the descriptions of the parts of the Class. I have no strong feelings as to whether Attributes and Methods should be mixed with each other, or separate.

Mixed alphabetical sorting would look like `args`, `author`, `bot`, `channel`, `cog`, `command`, `command_failed`, `fetch_message`, `guild`, `history`, ... merging the lists of Attributes and Methods and then sorting them alphabetically.

Separate alphabetical solution would look like `args`, `author`, `bot`, ... , `subcommand_passed`, `valid`, `voice_client`, `fetch_message`, `history`, `invoke`, ... , `send_help`, `trigger_typing`, `typing`.

### Additional Context

This should apply to any logical self-contained grouping. I would also think [Checks](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#checks) should be alphabetically sorted, as an example, but I'm not sure if groups of groups, like everything under the group of [Commands(Decorators, Command, Group, GroupMixin)](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#commands) should be alphabetized. I would, however, want [Command](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#command)'s features alphabetized.

**Comment by Rapptz** [comment]
It's called by-source order and it's not really that uncommon. It allows for different categorisation than alphabetical (e.g. for `Client`, `Guild`, etc. they're listed by relevance). Alphabetical throws that information away.

**Comment by Luunae** [comment]
So I looked this up. And technically it does throw information away. It throws away the information of matching it to the source code. I shouldn't ever need this information or your docs have already failed their entire purpose, so this shouldn't be a problem.

**Comment by Rapptz** [comment]
I guess we'll just agree to disagree then.

**Comment by Heurican** [comment]
> I shouldn't ever need this information 

well as far as alphabetization goes it doesn't really matter because Ctrl+F exists, and when a feature was implemented is much more valuable information than finding it easier because it's already too easy to just use the browser find feature.
