### ISSUE TITLE
How to get the username of an author?

### ISSUE THREAD

**Issue by MoWizard** [Rapptz/discord.py#820]
Hi, again,
I am trying to get my bot to say my username when I call a command. I type in
`user = ctx.message.author`
`bot.say(’’’Hello’’’ + user)`
and an error comes up saying `TypeError: must be str, not User`
I don’t know how to change that into a string, can you please help

Thanks

**Comment by Devoxin** [comment]
"Hello " + str(user)

**Comment by MoWizard** [comment]
Thank you, but how do I get rid of the 4 digits?

**Comment by Devoxin** [comment]
"Hello " + user.name

**Comment by Rapptz** [comment]
Please read the documentation on [`Message`](http://discordpy.rtfd.io/en/latest/api.html#discord.Message), [`User`](http://discordpy.rtfd.io/en/latest/api.html#discord.User), and [`Member`](http://discordpy.rtfd.io/en/latest/api.html#discord.Member).

**Comment by MoWizard** [comment]
I got an error saying `TypeError: send_message() takes from 2 to 3 positional arguments but 4 were given`

**Comment by Devoxin** [comment]
You know this is for issues with the library right? If you need help join the Discord API server. (discord.gg/discord-api)
