### ISSUE TITLE
Audio not playing anymore

### ISSUE THREAD

**Issue by lauralex** [Rapptz/discord.py#8202]
### Summary

Music/Audio not playing

### Reproduction Steps

I'm using Heroku with buildpacks:
- https://github.com/xrisk/heroku-opus.git
- https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest

Also, I'm using the latest version of discord.py using the following line in the requirements file:
- git+https://github.com/Rapptz/discord.py.git#egg=discord.py[voice]

Everything seems to be working correctly, but when I try to play some audio, it doesn't work anymore since 2/3 weeks ago. I don't know the reason.

### Expected Results

The audio playing correctly

### Actual Results

![image](https://user-images.githubusercontent.com/5181524/177061288-e1b5d02c-fc86-4af2-9398-6f8270c5e7f8.png)

### Intents

default + message_content = true

### System Information

```
- Python v3.10.5-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4392+gfd9c244f
- aiohttp v3.8.1
- system info: Linux 4.4.0-1104-aws #109-Ubuntu SMP Tue May 10 11:27:41 UTC 2022
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by lauralex** [comment]
Basically, it doesn't read anything from ffmpeg for some reason

**Comment by lauralex** [comment]
No exception is thrown unfortunately

**Comment by Rapptz** [comment]
Heroku isn't a supported host for voice, you're better off getting a VPS to host your bot for you instead.
