### ISSUE TITLE
Discord lib installation/use error

### ISSUE THREAD

**Issue by GlodeckWoW** [Rapptz/discord.py#8203]
### Summary

Unable to run discord lib (possible aiohttp conflict)

### Reproduction Steps

1. Install fresh anaconda package (3.9, win10, x64);
2. pip install vkbottle;
3. pip install discord

### Minimal Reproducible Code

```python
import discord
discord_token = {TOKEN}
intents = discord.Intents.default()
client = discord.Client(intents=intents)

@client.event
async def on_message(message):
    if message.author != client.user:
        await message.reply(message.content)
        
client.run(discord_token)
```

### Expected Results

client.run(discord_token) - works as intended. Bot goes online and echoes messages

### Actual Results

client.run(discord_token) - code does not respond. Bot does not go online and does not react to messages

### Intents

discord.Intents.default()

### System Information

- Python v3.9.12-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19043

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Upon installation of discord.py, where is a problem with dependancies. Aiohttp 3.8.1 gets deleted and 3.7.4.post0 is installed. Maybe it is the root of the problem:

pip install discord
...
Collecting aiohttp<3.8.0,>=3.6.0
  Using cached aiohttp-3.7.4.post0-cp39-cp39-win_amd64.whl (634 kB)
...
Installing collected packages: async-timeout, aiohttp, discord.py, discord
  Attempting uninstall: async-timeout
    Found existing installation: async-timeout 4.0.1
    Uninstalling async-timeout-4.0.1:
      Successfully uninstalled async-timeout-4.0.1
  Attempting uninstall: aiohttp
    Found existing installation: aiohttp 3.8.1
    Uninstalling aiohttp-3.8.1:
      Successfully uninstalled aiohttp-3.8.1
**ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
vkbottle 4.3.5 requires aiohttp<4.0.0,>=3.8.1, but you have aiohttp 3.7.4.post0 which is incompatible.
Successfully installed aiohttp-3.7.4.post0 async-timeout-3.0.1 discord-1.7.3 discord.py-1.7.3**

**Comment by Rapptz** [comment]
This is not an issue with discord.py. `pip` is saying that one of your libraries (`vkbottle`) wants to install aiohttp 3.8.1 or higher but discord.py wants to install something lower than 3.8 so it doesn't know what version of aiohttp to install. You can install 3.8.1 or higher yourself before running pip install on the library and it'll probably work.

**Comment by GlodeckWoW** [comment]
The problem here is that the abovementioned code (Minimal Reproducible Code) does not work. Even with the aiohttp.__version__=3.7.4.post0. The bot still stays offline and does not respond. If the lib is not the case, what can be the root ?

**Comment by Rapptz** [comment]
Considering that code works for hundreds of thousands of people, I'm not sure what the problem is. The problem you describe in the additional context is what I'm explaining.
