### ISSUE TITLE
"RuntimeError: Session is closed" after using .close() in setup_hook()

### ISSUE THREAD

**Issue by Aguileitus** [Rapptz/discord.py#8210]
### Summary

After using bot.close() inside setup_hook you see this "RuntimeError: Session is closed" error in the logs

### Reproduction Steps

Use bot.close inside setup_hook in Windows

### Minimal Reproducible Code

```python
import platform

import asyncio
import discord

from discord.ext import commands

class TestBot(commands.AutoShardedBot):

    def __init__(self) -> None:
        intents: discord.Intents = discord.Intents.default()  # All but the 3 privileged ones

        # Priviledged intents
        # pylint: disable=assigning-non-slot
        # intents.presences = True
        intents.members = True
        intents.message_content = True

        super().__init__(command_prefix="!", intents=intents)

    async def setup_hook(self) -> None:
        await self.close()

if __name__ == "__main__":
    if platform.system().lower() == 'windows':
        # This is to prevent "RuntimeError: Event loop is closed" error on Client.close()
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

    bot = TestBot()
    bot.run("TOKEN", log_handler=None)
```

### Expected Results

Not seeing this error.

### Actual Results

```
Traceback (most recent call last):
  File "D:\Bot\testbot.py", line 41, in <module>
    bot.run(Auth.TOKEN, log_handler=None)
  File "D:\Bot\venv\lib\site-packages\discord\client.py", line 872, in run
    asyncio.run(runner())
  File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\Bot\venv\lib\site-packages\discord\client.py", line 847, in runner
    await self.start(token, reconnect=reconnect)
  File "D:\Bot\venv\lib\site-packages\discord\client.py", line 781, in start
    await self.connect(reconnect=reconnect)
  File "D:\Bot\venv\lib\site-packages\discord\shard.py", line 440, in connect
    await self.launch_shards()
  File "D:\Bot\venv\lib\site-packages\discord\shard.py", line 421, in launch_shards
    self.shard_count, gateway = await self.http.get_bot_gateway()
  File "D:\Bot\venv\lib\site-packages\discord\http.py", line 2118, in get_bot_gateway
    data = await self.request(Route('GET', '/gateway/bot'))
  File "D:\Bot\venv\lib\site-packages\discord\http.py", line 445, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "D:\Bot\venv\lib\site-packages\aiohttp\client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "D:\Bot\venv\lib\site-packages\aiohttp\client.py", line 399, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed
```

### Intents

intents.members = True         intents.message_content = True

### System Information

- Python v3.10.4-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4396+g9fe19dcc
- aiohttp v3.8.1
- system info: Windows 10 10.0.19043

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Mihitoko** [comment]
Why whould you do that ? whats the usecase ?
Also setup hook is called before gatway connection is established so you closing your bot before it got online in the first place.

**Comment by Aguileitus** [comment]
I am running some validations on `setup_hook` like if the database is up and running and I don't think moving them to `on_ready` is really a good idea. If any of the validations fail I just close the bot.
Also, I'm 90% that this error was not happening in the previous release.

**Comment by Mihitoko** [comment]
I would run the validations before you run .connect()
Since setup_hook is called before gateway connection is made you can simply check the thinks before you start the bot in the first place.

If you use .run() to start your bot.

Just oberride it make your checks and if the checks pass just call .run() with super from the parent class.
If not just return the method.

Maybe with a value like -1 so the caller knows that the checks failed.
This would be my approach.
There are many ways to do it.
