### ISSUE TITLE
Support optional type annotations for `app_commands.Range`, `app_commands.Transform`

### ISSUE THREAD

**Issue by emisdumb** [Rapptz/discord.py#8214]
### Summary

Avoids an error with optional type annotations. e.g. `Range[...] | None` and `Transform[...] | None`

### What is the feature request for?

The core library

### The Problem

```py
@app_commands.command(name='my_command')
async def my_command(self, interaction: discord.Interaction, text: Range[str, 1, 16] | None = None):
    ...
```
This returns the following error:
```py
TypeError: unsupported operand type(s) for |: '_TransformMetadata' and 'NoneType'
```

### The Ideal Solution

The above code should work without issue. `Optional[Range[...]]` and `Optional[Transform[...]]` should also work.

### The Current Solution

Currently, the only solution is to remove the `| None` and ignore the type annotation entirely. However, this is slightly incorrect as a type annotation since `None` is a possible value.

**Comment by Rapptz** [comment]
This error is because `Range` returns an instance at runtime and it doesn't support `|` so it fails. `Optional[...]` and `Union[...]` etc work just fine.

**Comment by emisdumb** [comment]
If there's a way around that, it would be nice to have as a feature.

**Comment by Rapptz** [comment]
This can be bandaged around but this would require reworking how the transformer system works a bit to properly fix it.
