### ISSUE TITLE
Hybrid command/group permissions

### ISSUE THREAD

**Issue by SuchtiZockerLP** [Rapptz/discord.py#8239]
### Summary

Message command permission for hybrid commands

### What is the feature request for?

The core library

### The Problem

I wanted to do some hybrid commands, but I can't find a way to check permission for both. I tried using app_command.default_permissions and commands.has_permissions as well as both combined but it doesn't seem to work. I also could not find any other decorators to check for permissions.

### The Ideal Solution

I guess the best solution would be a commands.hybrid_permissions decorator or maybe to give the commands.hybrid_command decorator an permissions attribute but it would be different to both other ways so probably not the best solution.

### The Current Solution

Currently I just could check the permissions manually in every function, when it is a message command.

**Comment by Rapptz** [comment]
You can use checks and `app_command.default_permissions` just fine with hybrid commands, so I'm unsure what issue you're having.

**Comment by SuchtiZockerLP** [comment]
It's not an issue. It would just be nice and would make more sense with there would be a decorator for hybrid permissions, since there is one for both individual types.
But ok I'll try to work around it by using a check.

**Comment by Rapptz** [comment]
I have no plans to do this at the moment because it'll cause divergent behaviour. You can of course make this decorator yourself.
