### ISSUE TITLE
purge_from Not deleting messages from today

### ISSUE THREAD

**Issue by arielbeje** [Rapptz/discord.py#824]
When trying to do `purge_from(somechannel, after=somemsgid)` on messages from today, I get the error `You can only bulk delete messages that are under 14 days old.`
Example IDs: 364434063102181382, 360422489752469515.

I can delete the messages using `purge_from(somechannel, limit=someint)` just fine though.

**Comment by arielbeje** [comment]
Not a problem on rewrite.

**Comment by khazhyk** [comment]
is the "after" parameter within 2 weeks from the present?

**Comment by arielbeje** [comment]
The "after" is a message ID of a message sent today.

**Comment by khazhyk** [comment]
If after is set to today, then all messages returned should be newer than the provided message, so shouldn't be returning any messages at all older than two weeks. logs_from is working fine in testing, so I'm not sure why it would fail here.

Also, just to make sure, in both rewrite and async, the after param is a Message, not a message id, you are passing a Message, correct?

**Comment by arielbeje** [comment]
I am passing a message id in both cases.

**Comment by Vexs** [comment]
You need to pass a message object, or a datetime object. Not an ID. 

You can probably use discord.Object() here.
