### ISSUE TITLE
I got discord.errors.HTTPException: 401 Unauthorized (error code: 50027): Invalid Webhook Token when i try to send multiple embeds

### ISSUE THREAD

**Issue by FloRRenn** [Rapptz/discord.py#8260]
### Summary

401 Unauthorized (error code: 50027): Invalid Webhook Token when sending multiple embeds

### Reproduction Steps

I create some embeds with local images, 
Fetching to channel from channel id for sending them

### Minimal Reproducible Code

```python
try:
    manga = Manga(manga_id, chapter)
except Exception as e:
    await interaction.response.send_message(embed = embed_error(e.args[0]))
    return

filename = str(interaction.user.id) + ".jpeg"
view = SaveButton()
view.add_item(ui.Button(label = "Xem trên web", style = ButtonStyle.url, url = self.url))

async with aiohttp.ClientSession() as session:
    await download_image(session, manga.thumbnail(), filename)
    await interaction.response.defer()
    
    file_ = File(f'./images/{filename}', filename = filename)
    await interaction.followup.send(file = file_, embed = manga_info(manga, filename), view = view)
    
    image_url = await manga.get_chapter_images()
    for i in range(1, 100):
        check = await download_image(session, image_url + f"{i}.jpeg", filename)
        if check:
            file_ = File(f'./images/{filename}', spoiler = True)
            await interaction.followup.send(content = f"**Page {i} - Chap {manga.chapter_num}**", file = file_, view = view)
            await asyncio.sleep(0.5)
            
        else:
            break
```

### Expected Results

![image](https://user-images.githubusercontent.com/76693952/180445918-9a0a22cb-5365-4b56-b529-a27446ea4921.png)

### Actual Results

![image](https://user-images.githubusercontent.com/76693952/180446194-b6f9be01-0bea-4f6c-9a84-2364eec08414.png)

### Intents

discord.Intents.default()

### System Information

- Python v3.8.9-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4422+gdc50736b
- aiohttp v3.8.1
- system info: Windows 10 10.0.22621

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Bluesy1** [comment]
![Screenshot_20220722_061241](https://user-images.githubusercontent.com/68259537/180446887-c7cff8ab-3eaa-4e87-b4d4-363606c846b1.png)
discord is having issues right now with followups
