### ISSUE TITLE
Cog guilds parameter also for commands.command and hybrids

### ISSUE THREAD

**Issue by SuchtiZockerLP** [Rapptz/discord.py#8262]
### Summary

I would like the possibility to make commands.command and hybrids guild specific like app_commands.command

### What is the feature request for?

discord.ext.commands

### The Problem

I would like to make some commands only accessible on some guilds. The problem is, it currently only works with app_commands. It doesn't even affect the app_command part of hybrid commands so I can't combine it with a check and it's also not possible to split the hybrids into app and normal. 

### The Ideal Solution

I guess it would be ideal to somehow add at least the app_command part of hybrids (rest can be done with checks) so they will be hidden from the specified guilds. Additionally it would be nice to only need a list of the ids and not Objects of the guild.

### Additional Context

I'm actually trying to make cogs/commands customisable for users, so the user can say I would like those to be available on my guild, but the other ones not. I guess it could also be used to improve the tree sync time by filtering the guilds for example smaller ones only have text command and bigger ones have slash commands too but I don't know if that would change a lot.

**Comment by Rapptz** [comment]
You can stack decorators. I have no plans of adding specific functionality like this considering it can already be solved the usual way:

```py
@commands.hybrid_command()
@app_commands.guilds(...)
@my_checks.is_in_guild(...)
```
