### ISSUE TITLE
Member-role cache not consistently updating on changes

### ISSUE THREAD

**Issue by thedoctorjtd** [Rapptz/discord.py#8269]
### Summary

When adding or removing a role from a user, the member cache is not always updated to reflect the changes or there can be many minute long delays before it is updated.

### Reproduction Steps

Have a basic role Test
Give User the Test role
Call Test.members, or User.roles
Test.members will be empty and User.roles will not contain Test

Calling guild.fetch_member OR guild.fetch_roles did not appropriately update the cache.

A full restart will appropriately update the cache.

Applying roles manually (not through the bot) is tracked and updated immediately in the bot's cache- only when the bot manages others' roles does the cache not get updated.

### Minimal Reproducible Code

```python
@bot.command(name='RoleTest')
@commands.guild_only()
async def roleTest(ctx: commands.Context):
	await ctx.message.delete(delay=1)
	await ctx.guild.fetch_roles()
	onDutyRole = discord.utils.find(lambda m: m.name == 'OnDuty', ctx.guild.roles)
	print('Starting test...\nAuthor roles:\n' + str(ctx.author.roles).replace(', ', '\n'))
	print('---\nRole members:\n' + str(onDutyRole.members).replace(', ', '\n'))
	await ctx.author.add_roles(onDutyRole)
	print('Roles applied, checking...\nAuthor roles:\n' + str(ctx.author.roles).replace(', ', '\n'))
	print('---\nRole members:\n' + str(onDutyRole.members).replace(', ', '\n') + '\nSleeping\n\n')
	await asyncio.sleep(30)
	await ctx.guild.fetch_member(ctx.author.id)
	await ctx.guild.fetch_roles()
	print('Inverting test...\nAuthor roles:\n' + str(ctx.author.roles).replace(', ', '\n'))
	print('---\nRole members:\n' + str(onDutyRole.members).replace(', ', '\n'))
	await ctx.author.remove_roles(onDutyRole)
	print('Roles removed, checking...\nAuthor roles:\n' + str(ctx.author.roles).replace(', ', '\n'))
	print('---\nRole members:\n' + str(onDutyRole.members).replace(', ', '\n'))
```

### Expected Results

Roles should have been applied and the changes visible when viewing/interacting with the member cache.

### Actual Results

Roles were successfully applied (and subsequently removed), however the member/role cache remained blissfully unaware of this change.

From test run using provided code:

```
Starting test...
Author roles:
[<Role id=xxx name='@everyone'>]
---
Role members:
[]
Roles applied, checking...
Author roles:
[<Role id=xxx name='@everyone'>]
---
Role members:
[]
Sleeping


Inverting test...
Author roles:
[<Role id=xxx name='@everyone'>]
---
Role members:
[]
Roles removed, checking...
Author roles:
[<Role id=xxx name='@everyone'>]
---
Role members:
[]
```

### Intents

intents = discord.Intents.default() 		intents.message_content = True

### System Information

- Python v3.8.2-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4424+g31189191
- aiohttp v3.8.1
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by XuaTheGrate** [comment]
``Guild.fetch_member`` intentionally does not modify the cache, it is a single API call that returns the fetched member. ``Guild.members`` is empty because you have not enabled the privileged ``members`` intent (which is off by default).

**Comment by Rapptz** [comment]
> Calling guild.fetch_member OR guild.fetch_roles did not appropriately update the cache.

These functions do not modify or use the cache in any way by design. Their entire purpose is to bypass the cache and fetch from HTTP.

**Comment by thedoctorjtd** [comment]
> `Guild.fetch_member` intentionally does not modify the cache, it is a single API call that returns the fetched member. `Guild.members` and `Role.members` are empty because you have not enabled the privileged `members` intent (which is off by default).

Thanks for this. I had the intent enabled on the web, not on bot. Which actually makes me think that there is a different possibly unintended interaction happening. 

With (Web Members Intent) allowed, however without setting the bot's intent (Bot Members False), changes made by **others** were reflected in the cache. But actions done by the bot itself, would not be reflected as shown above. 

Point being, that part of the cache behavior is inconsistent and hence was quite confusing. 

---------

> > Calling guild.fetch_member OR guild.fetch_roles did not appropriately update the cache.
> 
> These functions do not modify or use the cache in any way by design. Their entire purpose is to bypass the cache and fetch from HTTP.

How is the cache supposed to resolve a discrepancy such as above? My point was not to say that those two `fetch` functions did not work as intended (they pulled the appropriate information), but instead to point out that attempts to get newer data seemed to not work. 

It would seem to me that `fetch` methods, while bypassing the cache for the lookup would update for the future.

**Comment by Rapptz** [comment]
> Point being, that part of the cache behavior is inconsistent and hence was quite confusing.

This behaviour is documented in detail in the [intents primer](https://discordpy.readthedocs.io/en/stable/intents.html#member-cache).

> It would seem to me that fetch methods, while bypassing the cache for the lookup, would update the cache for future non-fetch lookups.

The fetch functions *do not* modify the cache at all. The information discrepancy between the gateway and REST models would make this a non-starter anyway.
