### ISSUE TITLE
update move_to command to be available for StageChannel

### ISSUE THREAD

**Issue by zanza321** [Rapptz/discord.py#8285]
### Summary

Currently move_to command only works for VoiceChannel type, however the Discord API supports StageChannel which is not updated yet for discord.py

### What is the feature request for?

The core library

### The Problem

Discord fairly recently introduced "Stage Channels" which are special modified types of Voice Channels.

Currently, there doesn't seem to be any way for bots to be able to move members into StageChannel type rooms.  The move_to(channel) discord.py function (permission) only works for VoiceChannel type, however doesn't seem to be updated to work on StageChannel type rooms. 

The MOVE_MEMBERS official Discord API does allow for moving into Stage Channels and Voice Channels as it was updated recently
https://discord.com/developers/docs/topics/permissions#permissions

### The Ideal Solution

Function should be extended to work for StageChannel the same as it works for VoiceChannel type.  https://discord.com/developers/docs/topics/permissions#permissions

The discord.py discord.Member move_to(channel) command only supports VoiceChannel type.  It should be able to support (Union[VoiceChannel, StageChannel])
https://discordpy.readthedocs.io/en/stable/api.html#discord.Member.move_to

### The Current Solution

none

### Additional Context

none

**Comment by CinnamonSwirly** [comment]
I was going to submit a pull to fix this, but upon testing I couldn't replicate your issue. The unedited move_to coroutine accepts stages via the fetch_channel coroutine just like they were normal voice channels. 

I can submit it anyway but it's purely cosmetic at this point

**Comment by CinnamonSwirly** [comment]
Sorry, I'm fairly new at all this. Looks like your proposed change is already a thing. move_to supports a VocalGuildChannel, which is just Union[VoiceChannel, StageChannel].

**Comment by zanza321** [comment]
> Sorry, I'm fairly new at all this. Looks like your proposed change is already a thing. move_to supports a VocalGuildChannel, which is just Union[VoiceChannel, StageChannel].

thank you, you were right!
