### ISSUE TITLE
Raise error when User doesn't accept DM

### ISSUE THREAD

**Issue by CL0Pinette** [Rapptz/discord.py#8289]
### Summary

Raise an error if the user we try to send a message to doesn't accepts direct messages

### What is the feature request for?

The core library

### The Problem

Currently, there is no way to know if a user will receive a message when we send one.
And moreover, sending a message to someone not accepting it, blocks the execution flow and stops the function

### The Ideal Solution

The `user.send` and `member.send` functions should raise an Error such as the `Forbidden` error. So that we know if the execution failed. We would only need to catch this error and then adapt our code.

### The Current Solution

Currently there is none since it seems sending this kind of DM completely blocks the execution flow

**Comment by helish88** [comment]
[docs](https://discordpy.readthedocs.io/en/latest/api.html#discord.Member.send)

![image](https://user-images.githubusercontent.com/52331802/182321559-7f1d9f96-3b63-481b-bbfd-d643466609ae.png)

**Comment by CL0Pinette** [comment]
Yup I read this, but nothing is raised.. It looks like it is raised only if we want to send a message in a channel in which we don't have the required permissions

**Comment by helish88** [comment]
show the code
maybe you have bad error handler
and pls join [discord server](https://discord.gg/dpy)

**Comment by lmaotrigine** [comment]
I cannot reproduce this. If a user has their DMs closed, attempting to send a message to them anyway raises `discord.Forbidden`, as documented.
Make sure you have logging enabled, and are not suppressing errors with any existing error handlers.

**Comment by CL0Pinette** [comment]
hmm, looks like updating fixed it, but I don't see any commit that could have changed this behaviour..

**Comment by CL0Pinette** [comment]
I found where it was changed : 9fe19dcc6923e4b6133bdedafb33658bf37c9ab7
I apologize for creating this issue
