### ISSUE TITLE
Unable to utilize typing.Literal

### ISSUE THREAD

**Issue by amlxv** [Rapptz/discord.py#8307]
### Summary

I tried to adapt it to my project. However, it throws some errors. The code from the documentation is also giving the same outcome.

### Reproduction Steps

1. Copy the code from the documentation — [#typing_literal](https://discordpy.readthedocs.io/en/latest/ext/commands/commands.html#typing-literal)
2. Run the discord bot
3. Send the `shop` command with arguments: `buy 2 keyboard`

### Minimal Reproducible Code

```python
import discord
from discord.ext import commands
from typing import Literal

intents = discord.Intents.default()
intents.messages = True

bot = commands.Bot(command_prefix="-", intents=intents)


@bot.command()
async def shop(ctx, buy_sell: Literal['buy', 'sell'], amount: Literal[1, 2], *, item: str):
    await ctx.send(f'{buy_sell.capitalize()}ing {amount} {item}(s)!')


bot.run(DISCORD_TOKEN)
```

### Expected Results

Buying 2 keyboard(s)!

### Actual Results

```
raise TypeError(f"Cannot instantiate {self!r}")
TypeError: Cannot instantiate typing.Literal

The above exception was the direct cause of the following exception:

raise BadArgument('Converting to "{}" failed for parameter "{}".'.format(name, param.name)) from exc
discord.ext.commands.errors.BadArgument: Converting to "Literal" failed for parameter "buy_sell".
```

### Intents

- messages

### System Information

- Python v3.10.5-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
Literal is only supported on v2 not in v1.7.3
