### ISSUE TITLE
Adding Line Breaks Mid Message

### ISSUE THREAD

**Issue by JRSock** [Rapptz/discord.py#831]
Is it possible to add line breaks mid message. I tried using /n as shown below but would not insert a line break.

`await client.send_message(message.channel, 'hello /n goodbye')`

prints out

`hello /n goodbye`

**Comment by jfun** [comment]
bruh `\n`

**Comment by JRSock** [comment]
RIP, Now I know why my line breaks never worked in any of my problems :)
