### ISSUE TITLE
Mention working on desktop, but not mobile

### ISSUE THREAD

**Issue by nmedovich** [Rapptz/discord.py#832]
Mentions in format <@ID> display correctly in an embed element on the desktop version of discord (creating a mention).  However, in the mobile app (specifically tested on Android), the mention attempt displays the text "<@12345671234567>", or whatever the user's ID is.

Is this an error in the code being used, or does mobile handle this differently?

**Comment by Vexs** [comment]
Thats just mobile; not an issue with this lib. Best option is to just display their name regularly, or don't use an embed.

**Comment by Rapptz** [comment]
Not a lib issue. This is a QoI issue on the mobile client.

**Comment by frozenpandaman** [comment]
@nmedovich @Vexs @Rapptz Was this ever solved, or is more information available? I'm aware this isn't an issue with discord.py, but this is the only place I can find this issue documented online – three years later! It's only *one* specific server I'm in, and tagging/mentioning users on mobile (Android) is messed up in this exact way. Any leads on this?

**Comment by Rapptz** [comment]
The Discord client officially states that resolving user mentions works by accident and shouldn't be relied on. Realistically it resolves whenever the user is cached on the client side which can happen in various situations. Discord tells us not to rely on it so it's best to think of it as provided on an as-is basis. Alternatively use `Username#Discrim` for the output if you have them cached yourself.

**Comment by frozenpandaman** [comment]
>The Discord client officially states that resolving user mentions works by accident and shouldn't be relied on. 

This is… incredibly bizarre? What? Like, @mentions are an accidental feature, you're saying?

>Discord tells us not to rely on it so it's best to think of it as provided on an as-is basis.

…But there's still a bug with the Android app, and some reason it's affecting that specific server for all users when sending messages from mobile.

I opened a support case in hopes of making some headway toward getting this fixed.

**Comment by Rapptz** [comment]
Note that the original issue is about embeds. If you're talking about text content then you've necro'd the wrong issue.

**Comment by frozenpandaman** [comment]
Oh, bizarre. Well, then, aside from that the issue is identical – but no mention of it I've been able to find online. 🙃 Thanks anyway!

**Comment by Xarlos89** [comment]
This issue is still a thing in December 2022. No resolution by Discord.

**Comment by cleverNamesAreHard** [comment]
@Rapptz 
Can we have an update on this, it's been 5 years since I opened this issue, but this is still not resolved.

**Comment by Rapptz** [comment]
There's nothing to update here. What was mentioned earlier is still the case.
