### ISSUE TITLE
User provided name_localizations in Choice model is never assigned

### ISSUE THREAD

**Issue by MebinAbraham** [Rapptz/discord.py#8337]
### Summary

The `name_localizations` argument in the __init__ method of Choice is never assigned.

### Reproduction Steps

Use `Choice` with `name_localizations`, but your `name_localizations` will never be used.

### Minimal Reproducible Code

```python
https://github.com/Rapptz/discord.py/blob/master/discord/app_commands/models.py#L434-L439
```

### Expected Results

Use the values passed in on `__init__` of the Choice model.

### Actual Results

`name_localizations` arg in the `__init__` dunder method is never used.

https://github.com/Rapptz/discord.py/blob/master/discord/app_commands/models.py#L439

Currently, `self.name_localizations` is always set to `MISSING`. Is there any reason for this?

```py
self.name_localizations: Dict[Locale, str] = MISSING
```

---

Although it is always `MISSING` by default, the current check inside `to_dict` is also failing. (Happy to raise separate issue for this)
```py
if self.name_localizations is not MISSING:
```
which leads to:
```
base['name_localizations'] = {str(k): v for k, v in self.name_localizations.items()}
AttributeError: '_MissingSentinel' object has no attribute 'items'
```

They point to different memory address:
```sh
>> id(self.name_localizations)
4407963200

>> id(MISSING)
4351621536
```

### Intents

N/A

### System Information

N/A

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
> Currently, self.name_localizations is always set to MISSING. Is there any reason for this?

Kind of an oversight. I want `name_localizations` to be used if provided by Discord but for users of the library I want them to use the Translator machinery.

> Although it is always MISSING by default, the current check inside to_dict is also failing.

I can't reproduce this?

```py
>>> from discord.app_commands import Choice
>>> c = Choice(name='foo', value=10)
>>> from discord.utils import MISSING
>>> id(MISSING), id(c.name_localizations)
(1822711164544, 1822711164544)
```

**Comment by MebinAbraham** [comment]
> Kind of an oversight. I want name_localizations to be used if provided by Discord but for users of the library I want them to use the Translator machinery.

Ah okay.

As for the memory address difference, I am not sure why this may be, in the python console, I do get the same result as you. But at runtime, they seem to be not matching for some reason. Happy for it to be closed, as it is probably something my set up. I will dig into it when I get a bit of time and will update according as it may be useful to others. Thanks
