### ISSUE TITLE
send_message sending duplicates with delete_message

### ISSUE THREAD

**Issue by colinfike** [Rapptz/discord.py#834]
Hey, not really sure what is going on here. Been messing around with this for an hour or two.

I just want the bot to detect a substring in a string, delete that message, then send a message. This works fine except for if you keep sending "test" it will send duplicate messages. First time in a row it sends a message once. Second time it sends it the message twice. So on and so forth.

If delete_message isn't there then I do not experience this issue so it's something between send_message and delete_message.

There must be something simple that is just slipping past me. Any ideas?

```
import discord
import asyncio
import sys
import logging

client = discord.Client()

@client.event
async def on_ready():
    print('Logged in as')
    print(client.user.name)
    print(client.user.id)
    print('------')

@client.event
async def on_message(message):
    print(message.content)
    channel = message.channel
    if message.author.id == '<REDACTED>':
        print('escape')
        return
    lowered_message = message.content.lower()
    if 'test' in lowered_message or 'tester' in lowered_message or 'tes' in lowered_message:
        print('found')
        await client.send_message(channel, 'nope')
        await client.delete_message(message)

client.run('<REDACTED>)
```

**Comment by khazhyk** [comment]
Nothing looks obviously wrong to me.

Debugging these kind of issues usually works better in chat, try heading to discord.gg/discord-api and going to #python_discord-py and explaining your issue

**Comment by colinfike** [comment]
PEBKAC. The messages were being "merged" with the existing messages by the bot after the triggering message was deleted. I wasn't able to see that happening at first due to all the noise in my channel from testing.
