### ISSUE TITLE
Member.activities and Member.status doesn't show properly

### ISSUE THREAD

**Issue by TIBI4** [Rapptz/discord.py#8352]
### Summary

Activities and status doesn't show properly when the Member comes from an argument or from a fetch.

### Reproduction Steps

Use the `/testing` command in any member.

### Minimal Reproducible Code

```python
import discord
from discord import app_commands

SELECTED_BOT_TOKEN = ""

#Needed intents
class aClient(discord.Client):
    def __init__(self) -> None:
        super().__init__(intents=discord.Intents.all())
        self.synced = False

    async def on_ready(self):
        await self.wait_until_ready()
        await tree.sync()
        activity = discord.Game(name="⚠️ TESTING PRESENCE ⚠️")
        await self.change_presence(status=discord.Status.online, activity=activity)
        
client = aClient()
tree = app_commands.CommandTree(client)

@tree.command(name="testing",description="TEST!")
async def test(interaction:discord.Interaction,member:discord.Member):

    fetchedMember = await interaction.guild.fetch_member(member.id)
    
    await interaction.response.send_message(content=f"""TESTING:

    fetchedMember Name: {member.display_name}
    fetchedMember Activities: {member.activities}
    fetchedMember Activity: {member.activity}
    fetchedMember Status: {member.status}

    member Name: {member.display_name}
    member Activities: {member.activities}
    member Activity: {member.activity}
    member Status: {member.status}

    guild.me Name: {interaction.guild.me.display_name}
    guild.me Activities: {interaction.guild.me.activities}
    guild.me Activity: {interaction.guild.me.activity}
    guild.me Status: {interaction.guild.me.status}""")
        

client.run(SELECTED_BOT_TOKEN)
```

### Expected Results

![image](https://user-images.githubusercontent.com/25259582/185459871-5fe2512f-983a-4187-9c86-8e406dcf07b7.png)

For the bot in the image above, and testing the `/testing` command with the bot itself (named NICKNAME_TEST) should send:

TESTING:

fetchedMember Name: NICKNAME_TEST
fetchedMember Activities: (<Game name='⚠️ TESTING PRESENCE ⚠️',)
fetchedMember Activity: ⚠️ TESTING PRESENCE ⚠️
fetchedMember Status: online

member Name: NICKNAME_TEST
member Activities: (<Game name='⚠️ TESTING PRESENCE ⚠️',)
member Activity: ⚠️ TESTING PRESENCE ⚠️
member Status: online

guild.me Name: NICKNAME_TEST
guild.me Activities: (<Game name='⚠️ TESTING PRESENCE ⚠️',)
guild.me Activity: ⚠️ TESTING PRESENCE ⚠️
guild.me Status: online

### Actual Results

I'm receiving this output:

![image](https://user-images.githubusercontent.com/25259582/185459738-dcecffb5-7929-4d85-9dba-99a2a43b74d8.png)

### Intents

Intents.all()

### System Information

`sudo python3.9 -m discord -v`

```
- Python v3.9.4-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4518+g1a11c9ee
- aiohttp v3.8.1
- system info: Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19)
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
Presence information is only available via the gateway, which requires the privileged presence intent. Fetching the member is an HTTP operation and never includes presence information.

**Comment by TIBI4** [comment]
> which requires the privileged presence intent - @Rapptz 

Well, now without doing `fetch_member` but `get_member`, it seems that the member is not cached.

BUT, I'm using all the privileged intents, as you can see in the code below, and in the image:
`super().__init__(intents=discord.Intents.all())`

![image](https://user-images.githubusercontent.com/25259582/185467487-6a2b6466-33cf-4fb7-8391-90f165675b37.png)


### New test code:
```
import discord
from discord import app_commands

SELECTED_BOT_TOKEN = "XXX"

#Needed intents
class aClient(discord.Client):
    def __init__(self) -> None:
        super().__init__(intents=discord.Intents.all())
        self.synced = False

    async def on_ready(self):
        await self.wait_until_ready()
        await tree.sync()
        activity = discord.Game(name="⚠️ TESTING PRESENCE ⚠️")
        await self.change_presence(status=discord.Status.online, activity=activity)
        
client = aClient()
tree = app_commands.CommandTree(client)

@tree.command(name="testing",description="TEST!")
async def test(interaction:discord.Interaction,member:discord.Member):

    gettedMember = interaction.guild.get_member(member.id)
    
    await interaction.response.send_message(content=f"""TESTING:

    gettedMember Name: {member.display_name}
    gettedMember Activities: {member.activities}
    gettedMember Activity: {member.activity}
    gettedMember Status: {member.status}

    member Name: {member.display_name}
    member Activities: {member.activities}
    member Activity: {member.activity}
    member Status: {member.status}

    guild.me Name: {interaction.guild.me.display_name}
    guild.me Activities: {interaction.guild.me.activities}
    guild.me Activity: {interaction.guild.me.activity}
    guild.me Status: {interaction.guild.me.status}""")
        

client.run(SELECTED_BOT_TOKEN)
```

### Errored to:
`AttributeError: 'NoneType' object has no attribute 'display_name'`

**Comment by LostLuma** [comment]
You're still accessing the attributes from the member object you received from the interaction, rather than the one you got from the cache.

**Comment by TIBI4** [comment]
It was that. Sorry!

> You're still accessing the attributes from the member object you received from the interaction, rather than the one you got from the cache.

**Comment by Rapptz** [comment]
Application commands do not receive presence information either. It is exclusively through the gateway as mentioned earlier. If you want this to change you'd have to petition it to Discord though they already have an opened (and ignored) issue on the topic unfortunately.
