### ISSUE TITLE
Bug: on_guild_remove Randomly Called on Start

### ISSUE THREAD

**Issue by nmsturcke** [Rapptz/discord.py#8353]
### Summary

The `on_guild_remove(guild)` event is called randomly on start.

### Reproduction Steps

1. Create a bot instance
2. Have an `on_guild_remove(guild)` function with some type of logging
3. Start the bot
4. Observe how the latest guilds are 

### Minimal Reproducible Code

```python
import discord
from discord.ext import commands

class DiscordBot(commands.Bot):
    def __init__(self):
        intents = discord.Intents.default()
        super().__init__(intents=intents, command_prefix="!")
    
    async def on_guild_remove(self, guild: discord.Guild):
        print(f"[GUILD REMOVE] Name: {guild.name} | ID: {guild.id} | Object type: {type(guild)}")

bot = DiscordBot()
bot.run("YOUR_TOKEN")
```

### Expected Results

The event is not called unless the bot is removed from a guild.

### Actual Results

The event is called with the most recent guild changes at start.

### Intents

default

### System Information

- Python v3.9.13-final
- discord.py v2.0.0-final
- aiohttp v3.8.1
- system info: Windows 10 10.0.19044 (Also happens in ubuntu)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

ItsWilliboy#1337 can reproduce this bug, as per: https://canary.discord.com/channels/336642139381301249/1009882344578097214/1009902388196421662

Image of logging (INFO):
![image](https://user-images.githubusercontent.com/30734036/185481060-4d4fbe70-5970-4529-9b21-187aa456fdf5.png)

**Comment by Rapptz** [comment]
I think this needs debug logging for more information

**Comment by nmsturcke** [comment]
I'll send it in a second

**Comment by nmsturcke** [comment]
Mystbin - https://mystb.in/EdwardsAngelesCasual

**Comment by Rapptz** [comment]
That looks like a Discord issue to me

**Comment by dolfies** [comment]
This happens when you're in a guild TnS has soft-deleted.

**Comment by nmsturcke** [comment]
Alright, thank you
