### ISSUE TITLE
Snowflake Protocol class Invalid Under mypy

### ISSUE THREAD

**Issue by ultrabear** [Rapptz/discord.py#8354]
### Summary

The Snowflake class raises errors in mypy due to having a defined empty __slots__, when mypy reads the interface it expects types passed to it to also have empty slots, but as most dont mypy raises errors on them

### Reproduction Steps

run the below code through the `mypy` typechecker (using discord.py==2.0)

### Minimal Reproducible Code

```python
import discord
from discord import User, Guild


async def ban_user_snowflake_error(guild: Guild, user: User) -> None:

    await guild.ban(user)
```

### Expected Results

mypy should raise no error here, as does pyright

### Actual Results

mypy raises the following error due to expecting the defined slots on User to be `tuple[]`
```bash
test.py:11: error: Argument 1 to "ban" of "Guild" has incompatible type "User"; expected "Snowflake"
test.py:11: note: Following member(s) of "User" have conflicts:
test.py:11: note:     __slots__: expected "Tuple[]", got "Tuple[str]"
Found 1 error in 1 file (checked 1 source file)
```

### Intents

discord.Intents.all()

### System Information

- Python v3.10.5-final
- discord.py v2.0.0-final
- aiohttp v3.7.4.post0
- system info: Linux 5.15.60-1-MANJARO #1 SMP PREEMPT Thu Aug 11 13:14:05 UTC 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

While I understand mypy is not supported by discord.py, the fix is as simple as removing `__slots__ = ()` from the definition of Snowflake, and allows mypy to be used with discord.py again. Class init performance should not be a problem as Protocol subclasses may not be constructed at runtime.

**Comment by Gobot1234** [comment]
Snowflake is used as a base class to concrete classes and as you said discord.py doesn't support mypy and it's recommended that you use pyright. I think if you want this fixed you should ask the mypy team.

**Comment by ultrabear** [comment]
According to this REPL run I just did the concrete classes do not actually subclass from Snowflake (at least User/Guild)
```py
>>> import discord
>>> discord.User.mro()
[<class 'discord.user.User'>, <class 'discord.user.BaseUser'>, <class 'discord.user._UserTag'>, <class 'discord.abc.Messageable'>, <class 'object'>]
>>> discord.User.mro()[1].mro()
[<class 'discord.user.BaseUser'>, <class 'discord.user._UserTag'>, <class 'object'>]
>>> discord.Guild.mro()
[<class 'discord.guild.Guild'>, <class 'discord.mixins.Hashable'>, <class 'discord.mixins.EqualityComparable'>, <class 'object'>]
>>> 
```

Additionally in a patched version that comments out the __slots__ line User still has no `__dict__` attribute
```py
>>> print(inspect.getsource(discord.abc.Snowflake))
@runtime_checkable
class Snowflake(Protocol):
    """An ABC that details the common operations on a Discord model.

    Almost all :ref:`Discord models <discord_api_models>` meet this
    abstract base class.

    If you want to create a snowflake on your own, consider using
    :class:`.Object`.

    Attributes
    -----------
    id: :class:`int`
        The model's unique ID.
    """

    #__slots__ = ()
    id: int

>>> a = discord.User(data={'username': "foo", "id": "95", "discriminator": "4543", "avatar": "None"}, state={}).__dict__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'User' object has no attribute '__dict__'. Did you mean: '__dir__'?
```

**Comment by ultrabear** [comment]
An additional check using githubs class references feature on Snowflake shows that no classes outside of abc.py subclass Snowflake, and the only class that does subclass Snowflake (abc.User) also has no subclasses

**Comment by bijij** [comment]
`Snowflake` is a [`Protocol`](https://docs.python.org/3/library/typing.html#typing.Protocol), and as such classes do not need to subclass it to be accepted as instances of it, they just need to match the signature. i.e. in the case of `Snowflake` have an attribute `id` of type `int`.

**Comment by Rapptz** [comment]
This is definitely a bug in mypy, but since the friction in fixing it is low enough I'll fix it.
