### ISSUE TITLE
RequestsWebhookAdapter

### ISSUE THREAD

**Issue by XLinestX** [Rapptz/discord.py#8356]
### Summary

i can import it install it nothing

### Reproduction Steps

Rice me an error

### Minimal Reproducible Code

```python
a
```

### Expected Results

a

### Actual Results

a

### Intents

a

### System Information

a

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by AbstractUmbra** [comment]
Thank you for the very helpful Issue.

`RequestsWebhookAdapter` was removed with the update to 2.0, now there is `discord.SyncWebhook`.

**Comment by XLinestX** [comment]
> discord.SyncWebhook

Were i can get more information about discord.SyncWebhook ?

**Comment by AbstractUmbra** [comment]
From the [docs](https://discordpy.readthedocs.io/en/stable/api.html?highlight=syncwebhook#discord.SyncWebhook).
