### ISSUE TITLE
server.get_member() returns NoneType all the time

### ISSUE THREAD

**Issue by IHim2341** [Rapptz/discord.py#836]
Each time I run server.get_member(), the return value is always NoneType.

import discord

from discord.ext import commands

description = 'Ok'
bot_prefix = '!'

@client.event
async def on_ready():
    print('Logged in')
    print('Name : {}'.format(client.user.name))
    print('ID : {}'.format(client.user.id))
    print(discord.__version__)

client = commands.Bot(description=description, command_prefix=bot_prefix)

server = client.get_server('331815810353987584')

@client.command(pass_context=True)
async def kick(ctx, member):
    await client.say("Kicking " + member)
    oldid = list(member)
    oldid.remove('<')
    oldid.remove('@')
    oldid.remove('>')
    newid = ''.join(oldid)
    print(newid)
    await client.kick(server.get_member(str(newid)))

This is the error message.

>Ignoring exception in command kick

>Traceback (most recent call last):
  File "C:\Users\Ibrahim Abdullah\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:/Users/Ibrahim Abdullah/PycharmProjects/bottes/Test 2.py", line 58, in kick
    await client.kick(server.get_member(str(newid)))
  File "C:\Users\Ibrahim Abdullah\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 1367, in kick
    yield from self.http.kick(member.id, member.server.id)
AttributeError: 'NoneType' object has no attribute 'id'

>The above exception was the direct cause of the following exception:

>Traceback (most recent call last):
  File "C:\Users\Ibrahim Abdullah\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\bot.py", line 822, in process_commands
    yield from command.invoke(ctx)
  File "C:\Users\Ibrahim Abdullah\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 367, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Ibrahim Abdullah\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 52, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'id'

**Comment by MysterialPy** [comment]
It returns a None type because it is not finding any member with the "ID" you are passing to it.

Consider alternative solutions to retrieving the member.
Using a converter in your command function is a good start, which will return a member object if the member you pass is found.

```
@client.command(pass_context=True)
async def my_command(ctx, member: discord.Member):
    ...
```

**Comment by MysterialPy** [comment]
Also I just read your code, and the None type is actually coming from:
 `server = discord.Server(id='331815810353987584')`

That's not how you retrieve a server. Consider this... The Context passed to your command contains the server? Might be worth actually having a read through the documentation and learning some Python before diving straight into making a bot.

**Comment by IHim2341** [comment]
Sorry about that. Fixed the part with the server.

**Comment by IHim2341** [comment]
Is it possible if you show me how to make the converter?

**Comment by MysterialPy** [comment]
You don't need to make the converter. It's already done for you.
The code I showed above will work out of the box.

**Comment by IHim2341** [comment]
Thank you.
