### ISSUE TITLE
Check if an interaction is due to a hybrid command invocation

### ISSUE THREAD

**Issue by lmaotrigine** [Rapptz/discord.py#8366]
### Summary

title

### What is the feature request for?

The core library

### The Problem

for events and error handlers, it would be nice to know if the interaction that led there was actually the slash component of a hybrid command. These commands would have already invoked the regular command events, and need not be handled in duplicate.

### The Ideal Solution

An attribute of `Interaction`, or an additional parameter while dispatching said events indicating if the command is a hybrid.

### The Current Solution

Checking a private attr
```py
if interaction._baton and isinstance(interaction._baton, commands.Context):
    return
```

**Comment by Rapptz** [comment]
I have no plans on doing this because I want strict separation between the two.

For your use case in particular you can utilise `Interaction.extras` inside a global `before_invoke` hook doing something like ```py
async def before_invoke(ctx):
    if ctx.interaction:
        ctx.interaction.extras['hybrid'] = True
``
