### ISSUE TITLE
Tasks-Loop error!

### ISSUE THREAD

**Issue by ImInTheICU** [Rapptz/discord.py#8377]
### Summary

Tasks-Loop throwing error when the loop runs a new cycle

### Reproduction Steps

Just make a task, and wait for it to reloop

### Expected Results

The task to loop, as expected!

### Actual Results

```
Exception in callback Future.set_result(True)
handle: <TimerHandle when=3205169.561301999 Future.set_result(True)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
asyncio.exceptions.InvalidStateError: invalid state
```

### Intents

discord.Intents.all()

### System Information

- Python v3.10.5-final
- discord.py v2.0.0-final
- aiohttp v3.8.1
- system info: Windows 10 10.0.19044

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
Opening an issue without a minimal code example that showcases the error makes it inactionable. Consider opening another issue when you properly fill out the form with code that can reliably reproduce the error.
