### ISSUE TITLE
Allow empty string passed as name to command decorator

### ISSUE THREAD

**Issue by bryanforbes** [Rapptz/discord.py#838]
I have a command that I'd like to use just the prefix (in my case, `$`) to invoke it, but I'd like that to be the main name of the command (I plan to alias it as `$lookup` and write my own help formatter):

```python
    @commands.command(name='', aliases=['lookup'])
    async def lookup(self, ctx: 'Context', *, reference: str) -> None:
```

However, at [line 997 of core.py](https://github.com/Rapptz/discord.py/blob/bae6f803276da854fe5af3786ceecb1235e2f840/discord/ext/commands/core.py#L997), the assignment always uses `func.__name__` when `name` evaluates to a falsy value. It would be helpful if this assignment was:

```python
fname = name if name is not None else func.__name__
```

**Comment by Rapptz** [comment]
I'm not particularly a fan of this one.

Are you expecting this to be called as `$ foo` or `$foo` (note the space), because it's definitely not gonna be the latter.

**Comment by bryanforbes** [comment]
I was expecting to call it as `$ foo` (with a space). It’s already possible to create a command with an empty string for a name, add it, and use it. It’s just the decorator that doesn’t allow it.

**Comment by khazhyk** [comment]
Similar but not exactly this, a concept of a "default" command handler could be interesting

**Comment by ButterCheezii** [comment]
@khazhyk a hacky way to do that is to use the on_command_error event to check for a CommandNotFound, and use ctx.invoke on a Command object that might not be registered in the client

(on async, of course)
(and disclaimer, this is probably wrong, I haven't used discord.py in a while)
