### ISSUE TITLE
embed bug

### ISSUE THREAD

**Issue by Tumpa-Prizrak** [Rapptz/discord.py#8381]
### Summary

Checking for the number of embeds does not work correctly with a single embed

### Reproduction Steps

When I was rewriting the embed creation system, I made a typo and wrote `embeds` instead of `embed` in the `message.edit` function and specified a single embed

### Minimal Reproducible Code

```python
@bot.command()
async def error():
    emb = discord.Embed(title="Error")
    await ctx.send(embeds=emb)
```

### Expected Results

Error about incorrect type or auto-convertion to list

### Actual Results

Error about the number of Embeds
`ValueError: embeds has a maximum of 10 elements.`

### Intents

all

### System Information

- Python v3.10.4-final                               
- discord.py v2.1.0-alpha                            
    - discord.py pkg_resources: v2.1.0a4552+g9237106e
- aiohttp v3.8.1                                     
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I know that's minor bug, but I'm happy that I found something like that at d.py XD

**Comment by ImVaskel** [comment]
the embeds kwarg takes a list, not a singular element. for a singular element use the `embed` kwarg.

**Comment by cobaltgit** [comment]
The error checks against `len(embeds)`, if you pass a singular embed object IIRC it calculates the length of all text and stuff

**Comment by cobaltgit** [comment]
Which is why you should pass a list to `embeds`

**Comment by ultrabear** [comment]
I would list this as not a bug, as a typechecker should catch this and it avoids extra runtime checks that eat into perf

**Comment by SebbyLaw** [comment]
> a typechecker should catch this

Type checkers do not know the size of lists.

**Comment by Bluesy1** [comment]
> > a typechecker should catch this
> 
> Type checkers do not know the size of lists.

This is not about the size of a list, its about a `discord.Embed` being passed where a list of `discord.Embed`s are expected to be, and the `__len__()` method of `discord.Embed` returning the number of characters in the embed, raising a confusing error. However, this should be caught by typecheckers.

**Comment by SebbyLaw** [comment]
> > > a typechecker should catch this
> > 
> > 
> > Type checkers do not know the size of lists.
> 
> This is not about the size of a list, its about a `discord.Embed` being passed where a list of `discord.Embed`s are expected to be, and the `__len__()` method of `discord.Embed` returning the number of characters in the embed, raising a confusing error. However, this should be caught by typecheckers.

In the future, please make sure your minimal reproducible example actually works. You are missing the `ctx` variable in your `error` coroutine. 

After fixing your minimal reproducible example code, this is already caught by any sane type checker. Please type your code properly.
![Code_lRYSyDKGl6](https://user-images.githubusercontent.com/44045823/186787006-1e45b914-8311-4366-a65b-f233e2e27cf4.png)

Here is the code for you to try yourself.
```py
import discord
from discord.ext import commands

bot = commands.Bot(command_prefix='!', intents=discord.Intents.all())


@bot.command()
async def error(ctx: commands.Context):
    emb = discord.Embed(title="Error")
    await ctx.send(embeds=emb)
```
