### ISSUE TITLE
discord.Intents message_content=True error

### ISSUE THREAD

**Issue by ionutanton** [Rapptz/discord.py#8394]
### Summary

discord.Intents message_content=True error

### Reproduction Steps

Hi i get an error on running from this line.
intents = discord.Intents(messages=True, message_content=True)
error is: AttributeError: 'Intents' object has no attribute 'message_content'

it looks like a discord.py error.
dicrod.py 1.7.3

### Expected Results

no error 

### Actual Results

error on creating intents

### Intents

messages=True, message_content=True

### System Information

- Python v3.7.11-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by LostLuma** [comment]
Support for this intent was only added in version 2.0, the version you're using is no longer supported.
