### ISSUE TITLE
Propagate the edited object from Member.timout

### ISSUE THREAD

**Issue by mbaruh** [Rapptz/discord.py#8396]
### Summary

Member.timout should return the new Member object

### What is the feature request for?

The core library

### The Problem

`Member.timeout` uses `Member.edit` under the hood. While `Member.edit` returns the new object, it's not returned by `Member.timeout`. That means that in order to continue using a member object with an updated timeout datetime, you need to fetch the Member object again.

### The Ideal Solution

Ideally this value should be returned https://github.com/Rapptz/discord.py/blob/e62473a1b40177424221bbce02e56db37792c039/discord/member.py#L975

**Comment by Rapptz** [comment]
This was deliberate when I wrote it since none of the helper functions do this (e.g. `move_to`, `add_roles`, `remove_roles`, etc.) and if you wanted to get the result you'd use `Member.edit` instead,
