### ISSUE TITLE
timeout silently fails

### ISSUE THREAD

**Issue by benthetechguy** [Rapptz/discord.py#8406]
### Summary

A Member.timeout fails without any errors/exceptions in the terminal

### Reproduction Steps

1. Make a simple command to time a user out
2. Run command
3. Everything up to the actual timeout works but it stops there, and there are no errors indicating what went wrong.

### Minimal Reproducible Code

```python
@commands.command()
async def mute(self, ctx, user, time, *, reason):
    guild = ctx.message.guild
    if not guild.get_member(user):
        await ctx.send("User is not in the server.")
        return
    member = guild.get_member(user)
    if time > 2419200:
        await ctx.send("A member cannot be muted for more than 28 days.")
        return

    if member.is_timed_out():
        await ctx.send(f"{member} is already muted.")
        return
    await ctx.send("Debug: reached here")
    await member.timeout(until=timedelta(seconds=time), reason=reason)
    await ctx.send("Debug: timeout successful")
```

### Expected Results

Debug: reached here
*member is timed out*
Debug: timeout successful

### Actual Results

Debug: reached here
*nothing further happens, no output in terminal*

### Intents

default + members and message_content

### System Information

- Python v3.10.6-final
- discord.py v2.0.0-final
- aiohttp v3.8.1
- system info: Linux 5.19.4-zen1-1-zen #​1 ZEN SMP PREEMPT_DYNAMIC Sat, 27 Aug 2022 19:08:36 +0000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

In case something else that's not included in my minimal example is messing it up (unlikely since it makes it all the way to the timeout line then stops), the full command I'm using is [here](https://github.com/TechSupportCentral/TSCBot-py/blob/timeout/cogs/moderation.py#L517-L595).

**Comment by NextChai** [comment]
Do you have logging enabled? In discord.py now all default error handlers will use the `logging` library to display errors to the console.

**Comment by benthetechguy** [comment]
I didn't have logging enabled. An important change like that should've been documented in [Migrating to v2.0](https://discordpy.readthedocs.io/en/stable/migrating.html).
Now with it enabled, I discovered the issue was that I was using `until` as a keyword argument instead of a positional one.

**Comment by Willy-C** [comment]
> I didn't have logging enabled. An important change like that should've been documented in [Migrating to v2.0](https://discordpy.readthedocs.io/en/stable/migrating.html). Now with it enabled, I discovered the issue was that I was using `until` as a keyword argument instead of a positional one.


It is documented in the migrating guide you linked 
![image](https://user-images.githubusercontent.com/19799671/187096448-5331e137-e898-4f38-b0ba-c98f061a5143.png)

**Comment by lmaotrigine** [comment]
> An important change like that should've been documented in [Migrating to v2.0](https://discordpy.readthedocs.io/en/stable/migrating.html).

https://discordpy.readthedocs.io/en/stable/migrating.html#logging-changes

**Comment by benthetechguy** [comment]
Apologies, it's been over a week since I read it.
