### ISSUE TITLE
add_reaction hangs if the emoji is invalid

### ISSUE THREAD

**Issue by valadaptive** [Rapptz/discord.py#8408]
### Summary

If you call add_reaction with an invalid emoji as an argument, it will wait forever instead of throwing an error.

### Reproduction Steps

1. Call `add_reaction` with an invalid emoji (a string that isn't a supported Unicode emoji, or a custom emoji from a guild that the bot isn't in)
2. `await` that call

### Minimal Reproducible Code

```python
msg: discord.Message
await msg.add_reaction("this isn't an emoji!")
```

### Expected Results

It throws a `discord.errors.HTTPException: 400 Bad Request (error code: 10014): Unknown Emoji`, like it did in 1.x

### Actual Results

It never finishes running and `await`s forever

### Intents

guilds, members, bans, emojis, guild_messages, dm_messages, guild_reactions, dm_reactions, message_content, guild_scheduled_events, auto_moderation, auto_moderation_configuration, auto_moderation_execution

### System Information

- Python v3.10.5-final
- discord.py v2.0.1-final
- aiohttp v3.7.4.post0
- system info: `Linux 5.18.10-100.fc35.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jul 7 17:41:37 UTC 2022`

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by LostLuma** [comment]
It still raises this same error, however the library now uses the logging module instead of printing errors so you will need to set up logging. See the relevant migrating step: https://discordpy.readthedocs.io/en/stable/migrating.html#logging-changes
