### ISSUE TITLE
Windows Code Works Fine, Mac Gives An Error

### ISSUE THREAD

**Issue by FroostySnoowman** [Rapptz/discord.py#8419]
### Summary

I get an interesting error about aiohttp on Mac that I couldn't get on Windows.

### Reproduction Steps

Booted up VS code with Python just installed with a few pip installations.

### Expected Results

I expected for it to work and not produce the issue it is producing due to the fact it works flawlessly on Windows.

### Actual Results

https://paste.pythondiscord.com/yexokehexi.py

### Intents

I'm using all of the intents.

### System Information

- Python v3.10.6-final
- discord.py v2.0.1-final
- aiohttp v3.8.1
- system info: Darwin 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by FroostySnoowman** [comment]
Fixed by a user on Discord. 

Getting [SSL: CERTIFICATE_VERIFY_FAILED] on Python 3 on OS X?
Navigate to your Applications/Python 3.X/ folder and double click the Install Certificates.command to fix this.
Happy coding!

**Comment by SebbyLaw** [comment]
Duplicate of #4159

Windows: https://github.com/Rapptz/discord.py/issues/4159#issuecomment-640107584
Mac: https://github.com/Rapptz/discord.py/issues/4159#issuecomment-700615568
