### ISSUE TITLE
Discord.py sometimes fails to connect to discord.com leading to an unhandled error and crash

### ISSUE THREAD

**Issue by redace0001** [Rapptz/discord.py#8426]
### Summary

Sometimes Discord.py will fail to connect to discord.com and crash without handling the error itself

### Reproduction Steps

1. Connect your bot normally
2. Launch background tasks with asyncio or something
3. Wait a good while (everything is fine)
4. One on the tasks try to call a discord function related to an discord API call

### Minimal Reproducible Code

```python
# Can happen on any function calll leading to an discord.com API request
# This is a last example it crashed in
async def task(channel, msgId):
    try:
        msg = await channel.fetch_message(msgId)
    except discord.DiscordException:
        pass
```

### Expected Results

Discord.py detects a network problem and try to connect again

### Actual Results

The normal "except" looking for a discord.py exception doesn't trigger because the error is not a discord.py error

```
Task exception was never retrieved
future: <Task finished name='Task-13' coro=<checkArkServers() done, defined at ./bot.py:178> exception=ClientConnectorError(ConnectionKey(host='discord.com', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11001, 'getaddrinfo failed'))>
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\py38\lib\site-packages\aiohttp\connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\ProgramData\Miniconda3\envs\py38\lib\site-packages\aiohttp\connector.py", line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\ProgramData\Miniconda3\envs\py38\lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
    return await self.run_in_executor(
  File "C:\ProgramData\Miniconda3\envs\py38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\ProgramData\Miniconda3\envs\py38\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./bot.py", line 206, in checkArkServers
    except discord.DiscordException:
  File "C:\ProgramData\Miniconda3\envs\py38\lib\site-packages\discord\abc.py", line 1599, in fetch_message
    data = await self._state.http.get_message(channel.id, id)
  File "C:\ProgramData\Miniconda3\envs\py38\lib\site-packages\discord\http.py", line 624, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "C:\ProgramData\Miniconda3\envs\py38\lib\site-packages\aiohttp\client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "C:\ProgramData\Miniconda3\envs\py38\lib\site-packages\aiohttp\client.py", line 535, in _request
    conn = await self._connector.connect(
  File "C:\ProgramData\Miniconda3\envs\py38\lib\site-packages\aiohttp\connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\ProgramData\Miniconda3\envs\py38\lib\site-packages\aiohttp\connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\ProgramData\Miniconda3\envs\py38\lib\site-packages\aiohttp\connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
```

### Intents

default + messageIntents

### System Information

- Python v3.10.4-final
- discord.py v2.0.1-final
- aiohttp v3.8.1
- system info: Windows 10 10.0.17763

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

The code is running on a dedicated server and executes mutiples tasks at the same time for the bot. It was still responsive to other tasks but it crashed this specific one.
Some other tasks were also related to discord API calls but they didn't crash for what I could see.
Other unrelated tasks were unbothered however this is annoying as it doesn't crash the bot completly and doesn't leave a trace immediatly in the console since it crashed inside the task. I need to stop the bot with CTRL-C to see the trace. And because the bot is still online and other tasks running, I can't detect the problem if I don't see the console logs.

**Comment by Rapptz** [comment]
There is no crash here, only an unhandled exception. Network issues are unavoidable, for this one in particular you should setup a secondary DNS like Cloudflare or Google.

Note that the library does retry requests up to 5 times, though not for name resolution errors since those can't be retried most of the time.

**Comment by redace0001** [comment]
I still think it would be a good idea to raise an exception like discor.NetworkError or something. Otherwise you would need to know each possible exception possible in Discord.py that isn't a DiscordException. This means you need to actually stumble upon each of them at least once and identify this is a normal behavior of the module.
It would be far simpler for everyone coding their bot to simply have the behavior : the module failed to do this, so now I know i need to retry or carry on, or do something else. It can be any identifiable error inside discord.py that cause the module to be unable to perform the requested command, even if it's a generic DiscordException.
What do you think ?

**Comment by Rapptz** [comment]
There are an insurmountable amount of networking errors, I can't really reasonably catch all of them in particular and give it to you in another form. There's `OSError`, `ConnectionError`, `BlockingIOError`, `TimeoutError`, and whatever else some dependency might end up raising such as `aiohttp` or something else. 

"Best" thing I can do is `except Exception as e:` and wrapping that and raising it. However that's not a good idea for me to do on a request. However there's nothing complicated about you doing the same thing.
