### ISSUE TITLE
Unable to purge channel periodically?

### ISSUE THREAD

**Issue by carlbrockwell** [Rapptz/discord.py#843]
Firstly,a big thanks to rapptz for creating this API in the first place, it's been really useful. 

I'm trying to create a function in the bot that will allow for the messages to be purged weekly within the general channel without me having to submit a command like '?purge' to do it. 

I've looked into all sorts such as threading .sleep etc, but I must still be doing something wrong. Any advice would be greatly appreciated. this is currently how I'm trying to approach it:

`@bot.event
async def on_ready():
    print('Logged in as')
    print(bot.user.name)
    print(bot.user.id)
    print('------')

    async def purge():
        channel = bot.get_channel(channelId)
        print("purging?")
        print(channel.name)
        await bot.purge_from(channel, limit=100)
        threading.Timer(10, purge).start() #10 secs for testing purposes
    purge()`

Exception gives:
`discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
INFO:discord.gateway:sent the identify payload to create the websocket
D:/Users/carlb/IdeaProjects/DiscordBot/NimrodBot.py:37: RuntimeWarning: coroutine 'on_ready.<locals>.purge' was never awaited
  purge()
`

many thanks in advance

**Comment by khazhyk** [comment]
The error message explains pretty clearly what the problem is

"RuntimeWarning: coroutine 'on_ready..purge' was never awaited"
