### ISSUE TITLE
Hybrid subcommands don't run parent checks

### ISSUE THREAD

**Issue by ZRunner** [Rapptz/discord.py#8437]
### Summary

Hybrid subcommands don't seem to run parent checks, while normal subcommands do

### Reproduction Steps

1. Create an hybrid group with a subcommand
2. Add a check to the group with the `@commands.check` decorator
3. Run both the parent and the subcommand while debugging the check usage

### Minimal Reproducible Code

```python
def checker(ctx: commands.Context):
    print(f"Checker got called!  {ctx.invoked_with = }")
    return True

class TestCog(commands.Cog):
    """Hey, I'm a test cog! Happy to meet you :wave:"""

    def __init__(self, bot: Zbot):
        self.bot = bot
        self.file = 'test'

    @commands.hybrid_group(name="test")
    @commands.check(checker)
    async def test_main(self, ctx):
        pass

    @test_main.command(name="sub")
    async def sub(self, ctx):
        await ctx.send('Passed!')
```

### Expected Results

I'd expect both parent and subcommands to run the check (in my example both `test` and `test sub` should print the debug message).

### Actual Results

Only the parent command executes the check, not the subcommand (in my example, only `test` prints the debug message, not `test sub`).

### Intents

all

### System Information

```
- Python v3.9.13-final
- discord.py v2.0.1-final
- aiohttp v3.7.4.post0
- system info: Linux 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I am actually not sure if this is a bug or an undocumented behavior. But I expect the behavior described above because it is the one currently used for the old commands (by prefix only). If the use of `@commands.check` differs depending on the type of command, I think documenting it might be a good solution.

For reference, this is the same code as above but with the old commands system. If you test it, you'll see that both `test` and `test sub` print the debug message.
```py
def checker(ctx: commands.Context):
    print(f"Checker got called!  {ctx.invoked_with = }")
    return True

class TestCog(commands.Cog):
    """Hey, I'm a test cog! Happy to meet you :wave:"""

    def __init__(self, bot: Zbot):
        self.bot = bot
        self.file = 'test'

    @commands.group(name="test")
    @commands.check(checker)
    async def test_main(self, ctx):
        pass

    @test_main.command(name="sub")
    async def sub(self, ctx):
        await ctx.send('Passed!')
```

**Comment by Rapptz** [comment]
This is by design and documented, hybrid groups are made using the `invoke_without_command` setting being True.
