### ISSUE TITLE
Why is this code not working ?

### ISSUE THREAD

**Issue by Ouindoze** [Rapptz/discord.py#844]
https://hastebin.com/aniqasopij.py
Here is the code ^

http://prntscr.com/guzk3f
Here is the error^

why is it doing that ;-;

**Comment by Rapptz** [comment]
You're using the v1.0 version of the library.

Either downgrade or [migrate](http://discordpy.readthedocs.io/en/rewrite/migrating.html).

**Comment by Ouindoze** [comment]
How do i downgrade?

**Comment by MysterialPy** [comment]
Install from pip without the @rewrite e.g.:

`python3 -m pip install -U discord.py[voice]`

**Comment by Ouindoze** [comment]
The python3 is not working

**Comment by InkxtheSquid** [comment]
it's either this
```
python3 -m pip install -U git+https://github.com/Rapptz/discord.py@async#egg=discord.py[voice]
```
this
```
python -m pip install -U git+https://github.com/Rapptz/discord.py@async#egg=discord.py[voice]
```
or this (specifies the version)
```
python3.6 -m pip install -U git+https://github.com/Rapptz/discord.py@async#egg=discord.py[voice]
```

**Comment by Ouindoze** [comment]
Oh my god thank you so much!!!

**Comment by InkxtheSquid** [comment]
np but I rather keep in mind to [migrate](http://discordpy.readthedocs.io/en/rewrite/migrating.html) sometime.
