### ISSUE TITLE
How could i do that ?

### ISSUE THREAD

**Issue by Ouindoze** [Rapptz/discord.py#845]
How could i from a text file saved as a bat, make it open the cmd and type in
python "(location")
by itself so i just have to close or run the bat file to open the bot?

**Comment by jorkermc** [comment]
That seems unrelevant to discordpy but you can directly write "pythonw (location)" to a batch file and start it to start the bot then you can add another batch file containing "taskkill /IM (filename).py"(not recommended use bot.logout in the code) to kill it.

**Comment by Ouindoze** [comment]
Eh, is it okay to do the first task you told me and if i wanna kill it, just press (x) or it's dangerous?

**Comment by Rapptz** [comment]
This is not a library issue.
