### ISSUE TITLE
Discord server not working?

### ISSUE THREAD

**Issue by Ouindoze** [Rapptz/discord.py#846]
So i tried to go to the unnoficial API server but it keeps telling me the invite is expired, anyone have a new one?

**Comment by Mippy** [comment]
You're probably banned.

**Comment by PrestigeDox** [comment]
Most likely banned. Speak to Danny to see if you are banned. Sometimes if you connect to the same public hotspot as someone who is banned their IP ban carries over to you.

**Comment by Ouindoze** [comment]
Who is danny ? what his/her discord ?

**Comment by Mippy** [comment]
Danny#0007

**Comment by Ouindoze** [comment]
Thanks

**Comment by PrestigeDox** [comment]
Danny is = Danny#0007

Also go ahead and send your Discord username. I will check the logs to see if you are banned. As I said I might not be able to find it also you may be banned via IP due to connecting to a public hotspot.

**Comment by Ouindoze** [comment]
Ouindoze#9650 
And if you can please unban me, i really need help from you guys

**Comment by PrestigeDox** [comment]
<img width="194" alt="screen shot 2017-10-09 at 16 57 58" src="https://user-images.githubusercontent.com/23582349/31347080-06de1cfa-ad13-11e7-826c-d27d41650450.png">

**Comment by Ouindoze** [comment]
To be honest i didn't even knew i "shitposted", i'm not very good with english so it might have been because of that

**Comment by PrestigeDox** [comment]
Might have been. Speaking down to someone, being rude, calling people a noob and being rude about someones code can get you banned.

**Comment by Ouindoze** [comment]
Might have been because i said "haha nerd" in a joke way

**Comment by PrestigeDox** [comment]
Yes, it might have been. As I said message Danny. You 99% Won't be un banned but I recommend you message him. apologise, say you won't do it again and if he doesn't reply then DON'T spam him. He doesn't like the #spamthuglife

**Comment by Ouindoze** [comment]
Ok well i gotta wait for him to accept my friend request, but i don't get how saying a joke that small gets you banned and all, i didnt knew they were so strict

**Comment by Mippy** [comment]
[Image](https://mippy.prntsc.me/13ff04.png)

Ur banned forever sorry

**Comment by Ouindoze** [comment]
For a small joke, just for saying "haha nerd jk" ???? Jeez that's great and i really needed help
