### ISSUE TITLE
Close threads with thread.close()

### ISSUE THREAD

**Issue by RazzerDE** [Rapptz/discord.py#8475]
### Summary

Add a option for bots to close threads

### What is the feature request for?

The core library

### The Problem

Currently, there is no way for bots to close threads. If the feature would be added, bots can moderate the threads or even check which tags are applied and if the user made a mistake, they can say something like "don't do that again, open a new thread."

### The Ideal Solution

Allow bots to close threads like `await thread.close()`

**Comment by Rapptz** [comment]
You're looking for `await thread.edit(archived=True)` or `await thread.edit(archived=True, locked=True)`.
