### ISSUE TITLE
Discord.py with repl crazy error

### ISSUE THREAD

**Issue by yavda1** [Rapptz/discord.py#8478]
### Summary

Hi! I am trying to create a simple bot on repl with discord.py but it gives me a crazy error.

### Reproduction Steps

All I did was try to run some simple code on repl but it gives me a crazy error. I have used discord.py version 1.73 and it worked fine but now if I try it gives me an error. So does 2 and 2.1

### Minimal Reproducible Code

```python
All I did was this:

import discord
TOKEN = "token"
#intents = discord.Intents.default()
#ntents.message_content = True
client = discord.Client()

@client.event
async def on_ready():
  print("{0.user} is online!".format(client))
client.run(TOKEN)
```

### Expected Results

I expected it to come online and work

### Actual Results

What actually happened is that it gave me a crazy error
This is it. 
Was to big https://paste.pythondiscord.com/ofuyurapih
### Intents

I am using a version that doesn't have intents because I have no idea what they mean, but when I try the newer version and the example given I do this intents = discord.Intents.default() intents.message_content = True client = MyClient(intents=intents)

### System Information

- Python v3.8.12-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Linux 5.15.0-1017-gcp #23~20.04.2-Ubuntu SMP Wed Aug 17 02:46:40 UTC 2022
Note: Thi is on repl

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by IAmTomahawkx** [comment]
the ip you're using has been (temp)banned by discord. This commonly happens when using shared ips such as with repl
