### ISSUE TITLE
Author icons not displaying

### ISSUE THREAD

**Issue by OpalSec** [Rapptz/discord.py#8479]
### Summary

Author icons don't display when using icon_url parameter

### Reproduction Steps

Attempting to auto-populate author icons with favicons from websites results in some appearing and others just being a greyed out box:

![image](https://user-images.githubusercontent.com/33176069/191214683-99064086-8955-43b9-a867-75ac1dc4eb13.png)

I can't see any significant difference in the images that are appearing and the ones that aren't - they all appear to be normal .ico files and they render fine when browsed to, but not as the author icon_url property.

### Minimal Reproducible Code

```python
from discord import Webhook, RequestsWebhookAdapter, Embed

testhook = Webhook.from_url('https://discord.com/api/webhooks/000/000', adapter=RequestsWebhookAdapter())

icon_list = [
    ['https://threatpost.com/wp-content/themes/threatpost-2018/assets/images/favicon/favicon.ico', 'Threatpost'],
    ['https://www.bleepingcomputer.com/favicon.ico', 'Bleeping Computer'],
    ['https://www.theregister.com/design_picker/4ee431b84ac2d23c13376f753522acd7ecbb9b47/graphics/favicons/favicon.ico', 'The Register'],
    ['https://beta.darkreading.com/favicon-32x32.ico', 'Dark Reading'],
    ['https://www.infosecurity-magazine.com/favicon.ico', 'Information Security Magazine'],
    ['https://www.itnews.com.au/favicon.ico', 'IT News - Security'],
    ['https://msrc-blog.microsoft.com/favicon.ico', 'Microsoft Security'],
    ['https://www.recordedfuture.com/favicon.ico', 'Recorded Future']
]

for i in icon_list:
        embed=Embed(title='title', description=f'**summary:** insert here\n', color=0x04bd23)
        embed.set_author(name=i[1], icon_url=i[0])
        testhook.send(embed=embed)
```

### Expected Results

The icons should have appeared as the author icon in the author field - see the Dark Reading & Microsoft Security examples for expected behaviour

### Actual Results

greyed out boxes appear instead of the icons

### Intents

N/A

### System Information

- Python v3.10.2-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
The library is not responsible for rendering embeds, that's on the Discord client.
