### ISSUE TITLE
VoiceClient "stops" playing but believes it is still playing when moved between channels

### ISSUE THREAD

**Issue by Gorialis** [Rapptz/discord.py#8483]
### Summary

A playing VoiceClient that gets moved (either by its own accord using move_to, or from a moderator) appears to stop producing audio but continues to believe it is playing

### Reproduction Steps

- Play something through VoiceClient
- Move the bot into a different channel
- Observe as no sound comes through, but all methods on VoiceClient (`is_playing` etc) believe that sound is still being played.

### Minimal Reproducible Code

```python
# This shouldn't be hard to reproduce in basically any VoiceClient environment, but this does it just as well as anything else.
# Some assumptions made (you need to be in a voice channel and have working ffmpeg support)
vc = await ctx.author.voice.channel.connect()
vc.play(discord.FFmpegPCMAudio("https://github.com/ninjamuffin99/Funkin/blob/a083938ac803a91fbb15f03e432dea620f8a3b4a/assets/songs/bopeebo/Inst.mp3?raw=true"))
# Then just move the bot, and yourself, to a different channel, and see that the music does not appear to continue to play.
print(vc.is_playing())  # True
```

### Expected Results

Honestly I'm not quite sure. In my case I wanted the audio to continue playing, but I think the audio stopping is probably valid for other use cases. I only count this as a bug because it leaves the VoiceClient in a confusing state where everything appears to be OK from the bot side. RFC on how you think this should be handled I guess.

### Actual Results

Audio stops being heard. Notably:
- Moving the bot to a new channel and back to the one it started playing in without touching anything causes the audio to recover and continue playing again, but it won't play in any other channel but the one it started in.
- Pausing and resuming the audio "fixes" it and allows audio to continue playing in the new channel, suggesting some sort of WS flow might be needed on a channel move if we're actively connected to remind Discord that we are trying to play something.

### Intents

All except presences and members

### System Information

- Python v3.10.5-final
- discord.py v2.1.0-alpha
    - discord.py metadata: v2.1.0a4600+gc35ff4cf
- aiohttp v3.8.1
- system info: Linux 5.15.0-40-generic #43-Ubuntu SMP Wed Jun 15 12:54:21 UTC 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Here's my current terrible workaround for this. I don't particularly encourage its use.

```py
@commands.Cog.listener()
@commands.Cog.listener()
async def on_voice_state_update(self, member: discord.Member, before: discord.VoiceState, after: discord.VoiceState):
    if member != self.bot.user:
        return

    vc = member.guild.voice_client
    # Ensure:
    # - this is a channel move as opposed to anything else
    # - this is our instance's voice client and we can action upon it
    if (
        before.channel and  # if this is None this could be a join
        after.channel and  # if this is None this could be a leave
        before.channel != after.channel and  # if these match then this could be e.g. server deafen
        isinstance(vc, discord.VoiceClient) and  # None & not external Protocol check
        vc.channel == after.channel  # our current voice client is in this channel
    ):
        # If the voice was intentionally paused don't resume it for no reason
        if vc.is_paused():
            return
        # If the voice isn't playing anything there is no sense in trying to resume
        if not vc.is_playing():
            return
        
        await asyncio.sleep(0.5)  # wait a moment for it to set in
        vc.pause()
        vc.resume()
```

**Comment by anoadragon453** [comment]
It's possible that this also affects stages more than voice channels, as with a stage your bot needs to first join the audience, then *move* into speaking on stage.
