### ISSUE TITLE
How to get playing status?

### ISSUE THREAD

**Issue by OtakuSRL** [Rapptz/discord.py#850]
How do you get the playing/game status of a member (via User ID, would make sense)? Doesn't seem to exist in the documentation.

**Comment by ccubed** [comment]
You want:
```py
member.game
```

See [member.Game](http://discordpy.readthedocs.io/en/latest/api.html#discord.Member.game) for async or [member.Game](http://discordpy.readthedocs.io/en/rewrite/api.html#discord.Member.game) for rewrite

**Comment by OtakuSRL** [comment]
Okay, thanks. Figured there'd be a get function like a lot of other things but that's easy enough. Found it in Member.py but couldn't seem to find it in the documentation to see if it was that straight-forward, nice to see it is like I thought. Works well with easy implementation into code.

Also, I'm running this through get_all_members() and it's only returning one user as playing a game when we have a server population of 1,500+ and about 340 online right now, with many playing both real games and renamed ones. Any thoughts on why this isn't working as I intend? get_all_members() in general seems to only get a chunk of the population.

**Comment by OtakuSRL** [comment]
```python
for member in client.get_all_members():
				if member.game == None:
					return
				else:
					print(member.name, member.id, member.game)
```

**Comment by SunDwarf** [comment]
Sounds like you're running this bit of code before the bot has downloaded all the member chunks. When is this ran?

**Comment by OtakuSRL** [comment]
It's mostly standalone thus far, which means yeah it would be pretty early on - which makes sense (somewhat) to what you are going towards. I did do it after a wait_until_ready(), though. Is there additional steps I could take, or checks I could make, to ensure the "member chunks" are fully downloaded before utilizing this function?

**Comment by Rapptz** [comment]
If you're inside `on_ready` the chunks should already be downloaded. Chances are if you're doing this in a background task the cache was cleared and then being rebuilt.

**Comment by DPI3** [comment]
> ```python
> for member in client.get_all_members():
> 	if member.game == None:
> 		return
> 	else:
> 		print(member.name, member.id, member.game)
> ```
> 
> Prints out one user playing a game, and it's the same user each time it is run

I tried it and I got this: 'Member' object has no attribute 'game'. I also tried member.activity and member.activity.game, and I didn't get any error message but it always printed None. Any solutions to this problem?
