### ISSUE TITLE
Create Server invite get error 404

### ISSUE THREAD

**Issue by BlackScarx** [Rapptz/discord.py#852]
When I try to create an invite for my discord server

invite = await client.create_invite(client.get_server("guild id"), max_age=30, max_uses=1, unique='true')

I get this error

discord.errors.NotFound: NOT FOUND (status code: 404): Unknown Channel

But in the error it say Channel and it's a Server

**Comment by Rapptz** [comment]
That's because you create invites for channels -- not servers.

You need to get a *channel* to get the invite for, not a server.

**Comment by BlackScarx** [comment]
In the doc http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.create_invite
"Creates an invite for the destination which could be either a Server or Channel"

**Comment by Rapptz** [comment]
That was (unfortunately) before the default channel change was done. It worked by coincidence of prior design. Once Discord removed that concept that idea stopped existing as well.

**Comment by BlackScarx** [comment]
I use https://github.com/teamreflex/oauth2-discord
And I try to make accept the invite to the user
$invite = $user->acceptInvite($url);
But I got that ["code"]=> int(0) ["guild"]=> NULL ["xkcdpass"]=> NULL ["channel"]=> NULL
Because it need a server invite link and no a channel invite link

**Comment by BlackScarx** [comment]
Okay no I find the problem
It can't accept a invite link created by the bot himslef I guess
I have try with a invite link created by myself and it work

**Comment by Rapptz** [comment]
Okay well.

This is probably not the place.
