### ISSUE TITLE
Keeps receiving Closed with 1006 ("Going away")

### ISSUE THREAD

**Issue by anon276** [Rapptz/discord.py#86]
Version: 0.9.1
Branch: main

Hello, from week before, my chat bot keeps receives errors after some time of work (random time):
In python IDLE I see this errors: http://pastebin.com/MhDgE3CK
And at same time logging gives: 'Closed with 1006 ("Going away")'

What can I do with it? May be I can somehow make bot restart after this error? please help

**Comment by Rapptz** [comment]
Duplicate of #84
