### ISSUE TITLE
Context doesn't get passed to sub groups [rewrite]

### ISSUE THREAD

**Issue by Yorimor** [Rapptz/discord.py#862]
If you add a group to an existing group, the sub group doesn't get context passed to it and treats ctx like a command argument

[My code here](https://hastebin.com/rutiwadoge.py)

ctx shows up in `?help dnd stats`
`!dnd stats <ctx>`
and trying to use any subcommands of `stats` throws an AttributeError
`'str' object has no attribute 'invoked_subcommand'`

**Comment by ShineyDev** [comment]
Try using `pass_context=True` in the `@commands.group()` section of your code.

**Comment by Yorimor** [comment]
In rewrite that is now default behaviour, and pass_context=True would get ignored.
I tried it anyways, and it doesn't fix it
