### ISSUE TITLE
on_message_delete won't get called if the message was removed by someone else

### ISSUE THREAD

**Issue by Kurolox** [Rapptz/discord.py#864]
Hello!

I've noticed that if the message is removed by anyone else other than the original author (ie: a moderator, an administration bot, an anti-spam filterer...) the event `discord.on_message_delete`won't get called.

Is this the desired behavior?

**Comment by Kurolox** [comment]
Nevermind, my fault. The messages that were being deleted were too old and weren't in the cache. Everything works as expected.

**Comment by khazhyk** [comment]
fyi, you can use raw_message_delete and raw_bulk_message_delete to track messages that are deleted even if they are not in the client cache, however if you do not have a copy of the message yourself it is of limited use as the delete event does not have any metadata about the message itself.
