### ISSUE TITLE
Waiting for event to be called

### ISSUE THREAD

**Issue by danshat** [Rapptz/discord.py#867]
Hello.
How do I wait for the event to be executed? `on_reaction_add()`, to be exactly.
I tried this:

```
        reaction, user = await asyncio.wait_for(on_reaction_add(),15)
        print("ADDED A REACTION TO MESSAGE, "+user.name+" "+reaction.emoji)
```
But it didn't work.

**Comment by Rapptz** [comment]
http://discordpy.rtfd.io/en/latest/api.html#discord.Client.wait_for_reaction for v0.16.x
http://discordpy.rtfd.io/en/rewrite/api.html#discord.Client.wait_for for v1.0
