### ISSUE TITLE
Have seperate files per command

### ISSUE THREAD

**Issue by freakyy85** [Rapptz/discord.py#868]
Is that possible? Having a file per command, so different people can work on different commands at the same time for example? If yes, how? oO

**Comment by LittleEndu** [comment]
https://en.wikipedia.org/wiki/Version_control

**Comment by freakyy85** [comment]
This describes the problem better maybe - I'm already using git:
https://hastebin.com/joxebagoko.py

**Comment by freakyy85** [comment]
i guess @bot.command() needs to be defined before bot.run(self.config['token']). but, if i have commands in another file, how could i achieve that?

**Comment by nitros12** [comment]
Read this gist: https://gist.github.com/leovoel/46cd89ed6a8f41fd09c5

**Comment by freakyy85** [comment]
ok thank you ill try.
