### ISSUE TITLE
Bug with command ?

### ISSUE THREAD

**Issue by KolightFR** [Rapptz/discord.py#871]
Hello i've a problem with my bot all the command by on_message are working but when i try to create a command like ping command here, nothing is working on discord ? Why ?
When i try to create a new file with the command Ping it's working. The bug is not the bot so
`
import discord
import asyncio
import time
from discord.ext.commands import Bot
from discord.ext import commands

Client = discord.Client()
bot_prefix= "="
client = commands.Bot(command_prefix=bot_prefix)
botadmin = "280820768416333825"
botid = "369518460356657153"

@client.event
async def on_ready():
	print("Bot Online!")
	print("Name: {}".format(client.user.name))
	print("ID: {}".format(client.user.id))
	await client.change_presence(game=discord.Game(name='LADM1'))

@client.command(pass_context=True)
async def ping(ctx):
	await client.say("Pong !")

@client.event
async def on_message(message):
	if message.channel.id == "372392926606655491":
		if message.content.startswith("=invite"):
			async for msg in client.logs_from(message.channel):
				if(msg.id != "372395391276023812"):
					await client.delete_message(msg)
			server = message.server
			invite = await client.create_invite(client.get_channel("371613656313757701"), max_uses=1,unique=False)
			await client.send_message(message.channel, invite)
		elif message.author.id != botid:
			await client.delete_message(message)
	if message.content.startswith("=clearauto"):
		if message.author.id == botadmin:
			async for msg in client.logs_from(message.channel):
				await client.delete_message(msg)

@client.event
async def on_member_join(member):
	nouveau = discord.utils.get(member.server.roles, name="NOUVEAU")
	await client.add_roles(member, nouveau)	
	desc = ' \n{0.mention} vient de rejoindre le discord de LADM1\n \nContactez le ou allez lui rendre visite dans Accueil des RECRUES'.format(member)
	em = discord.Embed(title='Nouvelle RECRUE !', description=desc, colour=0x57FE01)
	await client.send_message(client.get_channel("372857522324897793"), embed=em)
            

client.run("MzY5NTE4NDYwMzU2NjU3MTUz.DMpBdQ.SjEJ6xkX-6sYRUxra3EZH9GkGHE")`

**Comment by NCPlayz** [comment]
Before asking any further, I advise you to revoke your token, if not done beforehand.

**Comment by KolightFR** [comment]
Yes i do

**Comment by FrostLuma** [comment]
If you want to have an `on_message` listener and have commands working you need to call the `process_commands` method the `Bot` class has. See [this faq entry](https://discordpy.readthedocs.io/en/latest/faq.html#why-does-on-message-make-my-commands-stop-working) for how it works, and check out the other ones too as they're quite useful.

You also don't need to create an instance of `discord.Client` and `commands.Bot`, Bot inherits from client which means all functionality the client has (which you don't even use - but that's not relevant) is available to use there.

**Comment by NCPlayz** [comment]
First, remove the `from discord.ext.commands import Bot`, since it is redundant - you using *commands*.Bot for the `client` variable.

**Comment by KolightFR** [comment]
Okay but is it still the same structures, using multiple arguments?

**Comment by NCPlayz** [comment]
What do you mean when you say structure? Could you please elaborate?

**Comment by KolightFR** [comment]
How to have this for exemple with process comand :

`@bot.command(pass_context=True)
async def joined_at(ctx, member: discord.Member = None):
    if member is None:
        member = ctx.message.author

    await bot.say('{0} joined at {0.joined_at}'.format(member))`

[Source](http://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-get-the-original-message)

**Comment by NCPlayz** [comment]
Use the FAQ that FrostLuma has kindly linked, to refer to how to use it.

**Comment by KolightFR** [comment]
Ok tanks for all !
