### ISSUE TITLE
When creating a guild channel it is not possible to set a parent_id for a category.

### ISSUE THREAD

**Issue by bendgk** [Rapptz/discord.py#877]

**Comment by Rapptz** [comment]
Not true.

`category` parameter in:

- [`Guild.create_text_channel`](http://discordpy.readthedocs.io/en/rewrite/api.html#discord.Guild.create_text_channel)
-  [`Guild.create_voice_channel`](http://discordpy.readthedocs.io/en/rewrite/api.html#discord.Guild.create_voice_channel)
