### ISSUE TITLE
Embeds are not being processed into the message object

### ISSUE THREAD

**Issue by yupi2** [Rapptz/discord.py#88]
At start of the the function [received_message](https://github.com/Rapptz/discord.py/blob/async/discord/client.py#L304) the variable `msg` includes the `embeds` data but after `msg` is processed into a dict [here](https://github.com/Rapptz/discord.py/blob/async/discord/client.py#L309) `embeds` is empty. I assume Python is probably at fault here for not converting `embeds` (an array of JSON objects) to a list of dicts.

**Comment by Hornwitser** [comment]
This seams rather strange.  Are you sure you're observing the embeds data being present in the `msg` variable, and then disappearing when it's decoded from JSON?  For messages with embeds, Discord will first send the message without the embeds in it, and then after a short time, it will send a message update with the embed data.

**Comment by yupi2** [comment]
@Hornwitser I was mistaken. I had confused a subsequent MESSAGE_UPDATE with the MESSAGE_CREATE while printing `msg`. I'm closing this issue since it's since it's not really an issue, Discord just doesn't send the embeds initially.
