### ISSUE TITLE
youtube-dl plays audio at half speed

### ISSUE THREAD

**Issue by ItalianRedstone** [Rapptz/discord.py#880]
When I try to make my bot play some music, it uses youtube-dl to download the song, but it plays it at half speed. Tried converting it with FFmpeg, but it's not very accurate (2.4x speed)...

Additionally, after 30 seconds of stream, the bot crashes with no errors on console.

Seeing https://github.com/Rapptz/discord.py/issues/768 actually makes me laugh xD

**Comment by Rapptz** [comment]
This isn't a library issue.
