### ISSUE TITLE
Convert member string to member object?

### ISSUE THREAD

**Issue by JoshQuake** [Rapptz/discord.py#881]
I'm having issues getting roles from a list of members. When I try to get m.roles from each m in memberslist, it errors with AttributeError: 'str' object has no attribute 'roles'

How do I convert string back to member object? Right now I have.
```
        membersdata = list('%s' % (m) for m in server.members)
        for m in membersdata:
            if 'Officer' in m.roles:
                messg.append(m)
```

Also if there is a better way to get members with a specific role please let me know. This looks like it's way more complicated than it should be

**Comment by mental32** [comment]
server.members does yield a member object you are just converting it into a string for every member in the server instead do `membersdata = [m for m in server.members]`

**Comment by Rapptz** [comment]
You have to get the role you're looking for first then loop through the members and check who has it.

```py
officer_role = discord.utils.find(lambda r: r.name == 'Officer', server.roles)
role_members = [m for m in server.members if officer_role in m.roles]
```
