### ISSUE TITLE
Question: Get user status? (Online, Idle, Do Not Disturb)

### ISSUE THREAD

**Issue by JoshQuake** [Rapptz/discord.py#883]
Is there a way to get the user status? (the green/yellow/red/grey circle) I can see a way to change the bots status, but nothing about referencing a users status.

**Comment by tilda** [comment]
You can get a user status with `Member.status` (`Member` being your `discord.Member` object). It will return something like `<Status.online: 'online'>`. This is just really `discord.Status.online`.

**Comment by JoshQuake** [comment]
Thank you tilda

**Comment by tilda** [comment]
np
