### ISSUE TITLE
change_presence doesn't update, and is not throwing an error

### ISSUE THREAD

**Issue by bobmcdouble3** [Rapptz/discord.py#887]
I am working on creating a simple self-bot. I want to make it appear, that I'm twitch streaming. I used this snippet, I got from the docs
`await self.change_presence(game=discord.Game(name='test', url="https://twitch.tv/twitch", type=1))`
It doesn't throw any errors, and I have confirmed that it is being called, but my status doesn't update.

**Comment by Gorialis** [comment]
Clients do not receive status updates from other clients logged into the same account. Chance is the call is working, but Discord is not showing it because you're the same user as is updating the presence. Try using an alt account or asking someone whether your status appears correctly.

**Comment by bobmcdouble3** [comment]
thanks!
