### ISSUE TITLE
accept_invite not working, and not returning an error

### ISSUE THREAD

**Issue by bobmcdouble3** [Rapptz/discord.py#888]
I am developing a selfbot, and I'm implementing a feature, to join a discord, then count the number of users, in the guild. I used `await client.accept_invite('INVITEHERE')`. But, this does not join the guild, and does not throw any errors!

**Comment by Vexs** [comment]
Accept invite is a blocked endpoint, it can no longer be used by anything except the official client, and attempting to use it will de-authenticate your account. The call is removed in later versions of discord.py

**Comment by bobmcdouble3** [comment]
Thanks!
