### ISSUE TITLE
Mentions do not ping the person

### ISSUE THREAD

**Issue by elephantLocator** [Rapptz/discord.py#89]
elephantLocator/UltraBot/issues/4

When mentioning a person, as we have in our mention file, it won't have orange highlighting etc. & ping the person. Probably a bug?

![](https://gyazo.com/096522c11a08bf7bd7865916b37f880f.png)

**Comment by khazhyk** [comment]
Mentions do not work in legacy/pip, they do however work in `async` as of https://github.com/khazhyk/discord.py/commit/ec23434162a4798fa6b79a0c17eb2e9e75904ee7

**Comment by elephantLocator** [comment]
Thanks khazhyk, that fixed it!
