### ISSUE TITLE
[rewrite] rich presence

### ISSUE THREAD

**Issue by xinitrc-ls** [Rapptz/discord.py#890]
Are we gonna get an option to use rich presence on rewrite?
Example below:
![68747470733a2f2f6661766e612e732d756c2e65752f4e456b3242504d412e706e67](https://user-images.githubusercontent.com/14354528/32530760-022ecefe-c40e-11e7-9790-f91541244cb9.png)

**Comment by khazhyk** [comment]
discord bans people who use rich presence outside of gamebridge

**Comment by MattIPv4** [comment]
Seems the above statement is wrong... https://i.imgur.com/mrBpbHQ.png

**Comment by Emzi0767** [comment]
You are misinterpreting what Mason says. Bots cannot display a rich presence. Nor will they ever be. What he refers to is ability to set rich presence for other users (via RPC, which is still closed).

**Comment by MattIPv4** [comment]
Just spoke to Jake to clarify. Bots cannot display or set rich presence, so it has to be done through a user account which would be user/self botting. Rip.

**Comment by lavendertheghost** [comment]
I believe this person means to be able to use the Rich Presence SDK via Discord.py, which I would also want.

**Comment by SourSpoon** [comment]
Bots cannot display or set rich presence

**Comment by tilda** [comment]
This could be done, but selfbotting would be only way to actually do it
You **could** do it.
[discord-rpc](https://github.com/discordapp/discord-rpc) could have some bindings or just a straight python port

**Comment by PolyacovYury** [comment]
A very nice feature would be to add an image parameter for a music bot to add an album artwork for music track the bot is currently playing. Or do the opposite - add an ability to hide the image placeholder.
![02-12-2017](https://user-images.githubusercontent.com/7702239/33509846-46600e4c-d716-11e7-9892-ff2927d03317.png)
On the side note - I think that removing multiline game names was a major mistake. Now the only method I have to view the full track name is to invoke a `now_playing` command which is not as convenient as a simple nickname click.

**Comment by khazhyk** [comment]
Fwiw, this isnt the place for discord feature requests, this is just an
unofficial community wrapper for the api

**Comment by PolyacovYury** [comment]
Sorry, I thought this repo (or its owner) have some connection to The Dev Team, and also - that this API is somehow able to influence certain things (e.g. adding an image attribute to the Game object suddenly allows the bot to change the image in Discord itself :) ) Too bad I was wrong, sorry for any annoyance this causes.

P.S. I am in coding since 2013 and I still believe in magic abilities of API authors :)

**Comment by MattBSG** [comment]
No, this library just uses the APIs discord provides. Rich presence is made to interact with games so you can see what a player is doing. Bot accounts can’t use it nor have they been said to be able to in the future. Knowing developers is a little different than feeding them features. If you’d like that to be a feature, see https://feedback.discordapp.com

**Comment by Rapptz** [comment]
There's support for this now. Sort of anyway. Bots can't send rich presence and I haven't tested user accounts but the preliminary stuff is there.

**Comment by scrazzz** [comment]
I found this that can set Rich Presence on user accounts. Hope this helps.

https://github.com/kairusds/eidolonrp

**Comment by lganWebb** [comment]
Please dont necrobump 2 year old issues.
