### ISSUE TITLE
Question: Why do not use latest aiohttp?

### ISSUE THREAD

**Issue by item4** [Rapptz/discord.py#892]
latest aiohttp is 2.3.2 but discord.py depend on aiohttp>=1.0.0,<1.1.0

Why use old version of aiohttp? How can I use latest one?

**Comment by khazhyk** [comment]
fwiw, I've been using aiohttp 2.2.5 without issues

**Comment by MysterialPy** [comment]
I have also been using 2.2.5 without issue.

**Comment by SunDwarf** [comment]
aiohttp had a tendency to memory leak or have other issues for a while (such as the flip-flop on ClientSession being inside a coroutine), hence why the lib pinned it to a stable version that doesn't do it.

**Comment by Rapptz** [comment]
Pinning dependencies isn't exactly strange. 

It's the recommended practice even.

Along with what was said above, v1.0 -> v2.0 is a breaking change so it requires review before pushed through. That upgrade path had e.g. memory leaks and the like so it wasn't done. It's probably fine now but I'm not gonna unpin it.

**Comment by Sispheor** [comment]
aiohttp is now 3.3.2.

**Comment by ItWasAllIntended** [comment]
The latest version of aiohttp is used in the [rewrite](https://github.com/Rapptz/discord.py/tree/rewrite) branch. The async branch no longer receives updates and will not have the requirements unpinned as the issues with the latest will not be fixed. If the latest aiohttp is a requirement, the rewrite branch is fully useable and still maintained.

**Comment by Philosoph228** [comment]
@Rapptz v1.0 aiohttp used back in python2. As in python3 introduced new importing API therefore legacy libraries rise a warning:
> `C:\Program Files\Python36\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__`

Please make discord.py support latest aiohttp, let it use python3 features and help developers get rid of warnings for more clear output.

**Comment by Philosoph228** [comment]
@Rapptz v1.0 aiohttp used back in python2. As in python3 introduced new importing API therefore legacy libraries rise a warning:

C:\Program Files\Python36\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__

Please make discord.py support latest aiohttp, let it use python3 features and help developers get rid of warnings.

**Comment by Gorialis** [comment]
Please don't necrobump issues.
`aiohttp` does not support Python 2 and [never has](https://github.com/aio-libs/aiohttp/tree/v0.1). This warning comes from the fact that old versions of Cython do not include complete package data by default. You could fix this by either disabling the speedups or compiling aiohttp for yourself, but as the async branch won't be maintained for much longer, it is a better idea to just pivot to using rewrite instead.

Consider joining the [discord.py Discord server](https://discord.gg/r3sSKJJ) if you want to learn more about upgrading to rewrite.
