### ISSUE TITLE
How to access and modify the messages cache in rewrite?

### ISSUE THREAD

**Issue by tinlun123** [Rapptz/discord.py#895]
Previously you would use Client.messages to read and write anything you would need to, but the rewrite stopped exposing Client.messages. How will we modify the messages cache in the rewrite?

**Comment by SunDwarf** [comment]
Why do you want to mess with it?

**Comment by notdisliked** [comment]
We have messages that serve as permanent role givers where the user can click on a reaction to get a role.  We found that the only way to get those messages to trigger on_reaction_add is to make sure they're always in the client.messages cache.

If there's another way to do this, please let us know, this is the only way we have found.

**Comment by Emzi0767** [comment]
You could solve that issue by using raw events. This way you can get the ID of the message and a reaction without doing what you weren't supposed to do anyways.

**Comment by Rapptz** [comment]
Use the raw message events. e.g. [here](http://discordpy.readthedocs.io/en/rewrite/api.html#discord.on_raw_reaction_add)

**Comment by isaacaddis** [comment]
I'm struggling with this and that link is broken. Lost on what to do because I can't find an equivalent in the documentation

**Comment by gogurtenjoyer** [comment]
https://discordpy.readthedocs.io/en/stable/api.html#discord.on_raw_reaction_add
