### ISSUE TITLE
Autocomplete does not work properly when used with range parameters.

### ISSUE THREAD

**Issue by Ferks-FK** [Rapptz/discord.py#8960]
### Summary

When using autocomplete together with range parameters in a slash command, it doesn't work correctly.

### Reproduction Steps

 - Create a slash command.
 - Add `Range` parameters to the command.
 - Add an autocomplete parameter *after* the `Range` parameters.
 - Watch the discord UI not respond correctly.

### Minimal Reproducible Code

```python
@app_commands.command(name="stuff", description="i do stuff")
async def stuff(self, interaction, param: Range[str, 18, 64] param_autocomplete: str)
   await interaction.response.send_message("stuff")

@stuff.autocomplete("param_autocomplete")
async def stuff_autocomplete(self, interaction, current: str):
    stuffs = ['stuff1', 'stuff2', 'stuff3']

    return [
      Choice(
          name="stuff",
          value="stuff"
      )
      for stuff in stuffs
   ]
```

### Expected Results

Show the options normally.

### Actual Results

discord shows "Unable to load options".

### Intents

intents.default, message_content and members.

### System Information

- Python v3.10.6-final
- discord.py v2.0.1-final
- aiohttp v3.8.1
- system info: Windows 10 10.0.19043

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

It looks like this happens when you set a `Range` parameter and then an `autocomplete.` parameter
It is important to say that the problem happens when you don't fill in the `Range` parameters in discord.
But when you do, it works normally.

My Parameters: `self, interaction: discord.Interaction, descrição: Range[str, 18, 255], portfolio: Range[str, 18, 96], área: int`
Preview: https://i.imgur.com/xgsQajV.gif

**Comment by Rapptz** [comment]
This is a Discord bug. You can track it here: https://github.com/discord/discord-api-docs/issues/5413
