### ISSUE TITLE
FFmpegPCMAudio not support bytes

### ISSUE THREAD

**Issue by thedtvn** [Rapptz/discord.py#8970]
### Summary

FFmpegPCMAudio not support bytes

### Reproduction Steps

play bytes audio

### Minimal Reproducible Code

```python
elif type(audio) is chiasenhac.Song:
                pageurl = audio.url
                img_url = audio.thumbnail
                title = audio.titleraw
                URL = io.BufferedIOBase((await (await audio.list_audio()).best_quality()).bytes)
            url = FFmpegPCMAudio(URL, **FFMPEG_OPTIONS)
            ctx.voice_client.play(url, after=lambda e: asyncio.run_coroutine_threadsafe(
                self.skip_audio(ctx), self.bot.loop))
```

### Expected Results

work

### Actual Results

not work

### Intents

all

### System Information

- Python v3.9.2-final
- discord.py v2.1.0-alpha
    - discord.py metadata: v2.1.0a4610+ge3b5fbd9
- aiohttp v3.8.3
- system info: Linux 5.15.61-v8+ #1579 SMP PREEMPT Fri Aug 26 11:16:44 BST 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

![image](https://user-images.githubusercontent.com/80153297/193436095-8bfe86f3-c8c2-4f23-b6dd-5cd9625b27d9.png)
![image](https://user-images.githubusercontent.com/80153297/193436098-3ace791f-eb0f-4d88-be96-24ddf81da126.png)

**Comment by Rapptz** [comment]
You're missing the `pipe=True` keyword parameter.
