### ISSUE TITLE
discord forum channels as slash command argument

### ISSUE THREAD

**Issue by RazzerDE** [Rapptz/discord.py#8971]
### Summary

Allow discord forum channels as slash command argument

### What is the feature request for?

The core library

### The Problem

The current way to allow the slash command author to select specific channel types is per slash command argument. You can set `discord.TextChannel` and `discord.VoiceChannel` as example. It would be very nice to allow `discord.ForumChannel` too.

If that get's implemented, users can only pick forum channels if the bot wants it.

### The Ideal Solution

allow `channel: discord.ForumChannel` as a slash command argument.

**Comment by Soheab** [comment]
Support for that was added in https://github.com/Rapptz/discord.py/commit/a53b609e371b50d7fb35e5b9e36a1da18e47bcaa and will be in the next patch (2.1).

**Comment by RazzerDE** [comment]
> Support for that was added in [a53b609](https://github.com/Rapptz/discord.py/commit/a53b609e371b50d7fb35e5b9e36a1da18e47bcaa) and will be in the next patch (2.1).

Do you know how I can import the GitHub version into pycharm?

**Comment by Soheab** [comment]
> 

You can use the following command to install the development version:
```cmd
python -m pip install git+https://github.com/rapptz/discord.py@master
```
The `git+url@master` part can also be used in a `requirements.txt`

**Comment by RazzerDE** [comment]
Its not in the master github branch.

**Comment by lmaotrigine** [comment]
It very much is in master. Make sure you are up to date.

**Comment by RazzerDE** [comment]
i installed it and still have this error

**Comment by Soheab** [comment]
> i installed it and still have this error

Which error?

**Comment by RazzerDE** [comment]
> > i installed it and still have this error
> 
> Which error?

The one from my issue, forumchannel is not possible to use as argument

**Comment by Soheab** [comment]
> > > i installed it and still have this error
> > 
> > 
> > Which error?
> 
> The one from my issue, forumchannel is not possible to use as argument

I don't see any traceback in the issue above?

**Comment by Rapptz** [comment]
This has already been implemented.
