### ISSUE TITLE
Message parameter for has_role method

### ISSUE THREAD

**Issue by RedHeadphone** [Rapptz/discord.py#8974]
### Summary

message parameter in commands.has_role which will be sent if user calling command doesn't have that role

### What is the feature request for?

discord.ext.commands

### The Problem

commands.has_role currently just ignores the command called by a user that doesn't have that role. So it would be better to have a parameter to set message which will be sent in such cases.

### The Ideal Solution

message parameter added in commands.has_role method which will be sent if user calling command doesn't have that role. If kept empty it will ignore that command.

### Additional Context

I would like to add this feature.

**Comment by LostLuma** [comment]
Such a feature request is very unlikely to be added to the library.

However, as mentioned in the documentation for the [`@has_role` decorator](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.has_role) the check will raise either a `MissingRole` or `NoPrivateMessage` error that you can then handle in the [command error event](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.discord.ext.commands.on_command_error) alongside other errors to send your message.

**Comment by RedHeadphone** [comment]
Any reason why it's unlikely to be added to the library?
I get that there is turn around which can give the results which we want, but shouldn't it be easy to implement with a parameter.

**Comment by SebbyLaw** [comment]
The purpose of command checks is to return a value or raise an error to indicate if a command should run.

**Comment by Rapptz** [comment]
This is not how error handling should be done. As mentioned earlier, using an error handler is the appropriate way to do so.
