### ISSUE TITLE
discord.client: Ignoring exception in on_message error

### ISSUE THREAD

**Issue by Zezoman1** [Rapptz/discord.py#8977]
### Summary

I am trying to make a discord bot and i got this error

### Reproduction Steps

I followed a tutorial and i did everything right but i get this error

### Minimal Reproducible Code

```python
i think what's causing the bug is


    @client.event
    async def on_message(message):
        if message.author == client.user:
            return
```

### Expected Results

the bot sends a response when i say the word code

### Actual Results

nothing the bot didnt send anything

### Intents

Using it with my friends privately 

### System Information

- Python v3.10.4-final
- discord.py v2.0.1-final
- aiohttp v3.8.3
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

this is the code 
import discord
import responses

async def send_message(message, user_message, is_private):
    try:
        response = responses.handle_response(user_message)
        await message.author.send(response) if is_private else await message.channel.send(response)
    except Exception as e:
        print(e)

def run_discord_bot():
    TOKEN = 'hidden'
    client = discord.Client(intents=discord.Intents.default())

    @client.event
    async def on_ready():
        print(f'{client.user} is now running')

    @client.event
    async def on_message(message):
        if message.author == client.user:
            return

        username = str(message.author)
        user_message = str(message.content)
        channel = str(message.channel)

        print(f"{username} said: {user_message} ({channel}")

        if user_message[0] == '?':
            user_message = user_message[1:]
            await send_message(message, user_message, is_private=True)
        else:
            await send_message(message, user_message, is_private=False)

    client.run(TOKEN)

**Comment by Rapptz** [comment]
You haven't given a traceback, but given the code you're missing the [privileged message_content intent](https://discordpy.readthedocs.io/en/latest/intents.html#message-content). This makes all `message.content` return `''` and `''[0]` raises an error, as you do in your `user_message[0]` code.
