### ISSUE TITLE
Message.content missing

### ISSUE THREAD

**Issue by radio-satellites** [Rapptz/discord.py#8978]
### Summary

When message.content is called, it returns a blank string

### Reproduction Steps

I called message.content

### Minimal Reproducible Code

```python
import discord
import os

client = discord.Client()

@client.event
async def on_ready():
    print('We have logged in as {0.user}'.format(client))


@client.event
async def on_message(message):
    if message.author == client.user:
        return
    print("MESSAGE "+str(message.content))
    await message.channel.send("Hello!")

client.run("TOKEN")
```

### Expected Results

The output will be 

MESSAGE HELLO

### Actual Results

Instead, this happens:

We have logged in as Bot#6284
"MESSAGE "

### Intents

I am using the code above, no intents are used

### System Information

- Python v3.7.9-final
- discord.py v1.4.1-final
- aiohttp v3.6.3
- system info: Windows 10 10.0.19041

Also doesn't work on 

- Python v3.7.9-final
- discord.py v1.7.3-final
- aiohttp v3.6.3
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

How can I fix this to run? This doesn't even work on older libraries. There was an older thread on this but it was inconclusive.

**Comment by SebbyLaw** [comment]
> no intents are used
The `message_content` intent is required in order to access the contents of messages. See documentation here: https://discordpy.readthedocs.io/en/latest/intents.html#message-content

**Comment by zeuschops** [comment]
I've recreated this bug on discord.py 2.0.1 and am using `discord.Intents.all()` with all intents enabled on the dashboard through Discord's developer portal. No message content is being passed back to the bot to my knowledge.


Using repr(message) on on_message(message) returns this;
```
<Message id=1035975277974671430 channel=<TextChannel id=1035326100550725772 name='bot-testing' position=17 nsfw=False news=False category_id=1025630807584411658> type=<MessageType.default: 0> author=<Member id=454598334448009216 name='ZeusChops' discriminator='7967' bot=False nick=None guild=<Guild id=1025577083226824705 name='Phtven' shard_id=0 chunked=True member_count=16>> flags=<MessageFlags value=0>>
```

**Comment by scrazzz** [comment]
The `__repr__` does not contain the message in it.
https://github.com/Rapptz/discord.py/blob/e92a6266628d0cc99727c8eb88c2432a931138a0/discord/message.py#L1528

Try getting it via `message.content`.

**Comment by scrazzz** [comment]
The `__repr__` does not contain the message content in it.
https://github.com/Rapptz/discord.py/blob/e92a6266628d0cc99727c8eb88c2432a931138a0/discord/message.py#L1528

Try accessing it via `message.content`.

**Comment by zeuschops** [comment]
Even using message.content, and checking with len(message.content) there is no content in the message...
<img width="1115" alt="Screenshot 2022-10-30 at 2 44 08 PM" src="https://user-images.githubusercontent.com/56428356/198903020-94f8cac2-cc72-435f-90c2-baa251b94604.png">
<img width="1229" alt="Screenshot 2022-10-30 at 2 43 58 PM" src="https://user-images.githubusercontent.com/56428356/198903022-622f0c4e-6e98-416b-b00f-204916f20915.png">

**Comment by dolfies** [comment]
Try toggling the intent in the developer portal. Sometimes it gets stuck.

**Comment by zeuschops** [comment]
Tried that just now for message content intent, and I am having the same issue.

**Comment by zeuschops** [comment]
I suppose it may take a few hours to update from Discord or something. I was able to confirm it working suddenly now..? Bizarre...appreciate it @dolfies and @scrazzz <3

Code to test with in case someone else has a similar issue... You'll want to toggle Message Intent on the discord developer panel, save it. Toggle it back to on, save it. Then wait a few hours for Discord's developer panel to reflect bot permissions, it goes through a review process to the best of my understanding...it's kind of weird...
```
import discord
from discord import app_commands

intents = discord.Intents.all()

class MyClient(discord.Client):
    def __init__(self, *, intents:discord.Intents):
        super().__init__(intents=intents)
        self.tree = app_commands.CommandTree(self)
    
    async def setup_hook(self):
        await self.tree.sync()

client = MyClient(intents=intents)
tree = client.tree

@client.event
async def on_ready():
    print(f"Logged in as {client.user} with id {client.user.id}")

@client.event
async def on_message(message):
    print(f"{message.id} | {message.guild.name} | {message.channel.name} | {message.author.name} | {message.content} | {len(message.content)}")

client.run('token')
```
