### ISSUE TITLE
on member join

### ISSUE THREAD

**Issue by Sleedyak** [Rapptz/discord.py#898]
How to do the "on member join" message? I tried it like this: 
`@bot.event
 async def on_member_join(ctx):
     await ctx.send("Hello! Welcome to {server} {user}!")`

But it doesn't work....

**Comment by Sleedyak** [comment]
white spaces are there i just couldnt copy it with them.....

**Comment by SourSpoon** [comment]
on_member_join doesn't take context, and instead takes a member object.
http://discordpy.rtfd.io/en/rewrite/api.html#discord.on_member_join

In addition, now that default channel has gone you will need to pick a channel or find some other logic to send the welcoming message to. 

These kind of questions are best suited for the discord server.
https://discord.gg/discord-api
