### ISSUE TITLE
ffmpeg/avconv was not found even though avconv is in PATH

### ISSUE THREAD

**Issue by mitgobla** [Rapptz/discord.py#899]
I'm running on Ubuntu 14.04 on a VPS.
When I request a song, it comes up with the error:
`ClientException: ffmpeg/avconv was not found in your PATH environment variable`
Even though when I type `echo $PATH` it links to the directory with avconv installed, and when I type `avconv` into the terminal it comes up with its version, etc.
Is there a way to point the youtube downloader/discord.py to the directory of avconv?

**Comment by Rapptz** [comment]
Did you pass in `use_avconv=True`
