### ISSUE TITLE
aenum as command choice support?

### ISSUE THREAD

**Issue by timelessnesses** [Rapptz/discord.py#8990]
### Summary

aenum support for discord.py

### What is the feature request for?

discord.ext.commands

### The Problem

I want to have multiple value of enum like if user choose selection `h` from enum it will only give me the value `h` and there will be no additional attribute for me to use it.  
Kinda like this

```py
import enum
class a(enum.Enum):
    fancy = 0 # ,call_fancy
    fancier = 1 # ,call_fancier
    fanciest = 2# , call_fanciest
# i couldn't do this on enum
```
but this kind of stuff supported in aenum
```py
import aenum
class a(enum.Enum):
    _init_ = "value __call_me__"
    fancy = 0, call_fancy
    fancier = 1, call_fancier
    fanciest = 2, call_fanciest

a(2).__call_me__(420)
```
but discord.py can't do selection because of the enum that choosen is tuple so user can't choose value in text command and be able to only select them in slash command  
if there's aenum supports this will support multiple value enums and so on

### The Ideal Solution

aenum supports so we can choose more selections and give more flexibility over selection like i said above

### The Current Solution

I need to do dictionary binding to those enum values
```py
class a(enum.Enum):
    fancy = 0
    fancier = 1
    fanciest = 2

binding = {
    a.fancy: call_fancy,
    a.fancier: call_fancier,
    a.fanciest: call_fanciest
}
```

**Comment by Ender2K89** [comment]
Do you mean something like Soheab is working on? https://github.com/Rapptz/discord.py/compare/master...Soheab:ext-commands-choices

**Comment by timelessnesses** [comment]
hmm likely

**Comment by Rapptz** [comment]
You can use a classmethod converter to make this work for whatever you want the syntax to be. For example:

```py
class X(enum.Enum):
  a = 1
  b = 2

  @classmethod
  async def convert(cls, ctx, argument):
    if argument == 'a' or argument == '1':
      return cls.a
    if argument == 'b' or argument == '2':
      return cls.b
    raise commands.BadArgument('bad enum')
```

I consider this better than just hijacking all enum parsing. For slash commands I have the freedom to do this because choices is a built-in concept but for something like enums which are external and library user dependent on how the parsing should be done then I don't want to touch it. For example, if someone doesn't like the built-in parser.
