### ISSUE TITLE
SIGTERM never causes bot to be closed

### ISSUE THREAD

**Issue by codeofdusk** [Rapptz/discord.py#8998]
### Summary

As of Discord.py 2.0 (and the new `async with` bot setup style), whenever `SIGTERM` is sent, `bot.close` is never called. This means that any custom cleanup code is never run if the bot is controlled by a systemd service and that service is stopped or restarted.

### Reproduction Steps

1. Set up a systemd service that runs a discord.py bot.
2. Run `systemctl start <service name>`
3. Run `systemctl stop <service name>`

### Minimal Reproducible Code

```python
Example bot from repo
```

### Expected Results

`bot.close` is called

### Actual Results

`bot.close` is not called

### Intents

n/a

### System Information

n/a

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I've manually set up a signal handler (using `bot.loop.add_signal_handler`) to my bot to handle this case, but the library should consider handling this.

**Comment by Rapptz** [comment]
The library uses `asyncio.run` to defer cleanup to the standard library now, so signal handlers aren't added.
