### ISSUE TITLE
Piped Audio Input Ends Prematurely

### ISSUE THREAD

**Issue by RileSamurott** [Rapptz/discord.py#9001]
### Summary

Piped video/audio input from sources like `youtube-dl` does not terminate the pipe stream correctly, often cutting off the last bit of the stream.

### Reproduction Steps

- Stream audio from another process using `subprocess.Popen`; in my case I was using `youtube-dl`
- Wait for the audio to play until it nears the end of the stream

### Minimal Reproducible Code

```python
client = await ctx.author.voice.channel.connect()
url = "https://www.youtube.com/watch?v=KAwyWkksXuo"
ytdl = subprocess.Popen(["youtube-dl", "-f", "bestaudio/worst", "-i", url, "-o", "-"], stdout=subprocess.PIPE)
audsrc = discord.FFmpegPCMAudio(ytdl.stdout, pipe=True)
client.play(audsrc)
```

### Expected Results

Discord.py plays the stream until the very end, then closes FFMPEG and stops playback.

### Actual Results

The stream is cut off slightly before the track actually finishes. For the sample video (cbat), it terminates roughly 6 seconds before the stream actually finishes. In addition, FFMPEG terminates with code 255, indicating a forced termination of the program.

### Intents

members, message_content, messages

### System Information

- Python v3.10.7-final
- discord.py v2.0.1-final
- aiohttp v3.8.3
- system info: Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

My current solution for this involves a modification of the `FFmpegAudio` class in `player.py`.
```python
class FFmpegAudio(AudioSource):
    # ...
    def _pipe_writer(self, source: io.BufferedIOBase) -> None:
        while self._process:
            # arbitrarily large read size
            data = source.read(8192)
            if not data:
                # self._process.terminate() <--- Removed this line, replaced with following
                self._stdin.close()
                return
            try:
                if self._stdin is not None:
                    self._stdin.write(data)
            except Exception:
                _log.debug('Write error for %s, this is probably not a problem', self, exc_info=True)
                # at this point the source data is either exhausted or the process is fubar
                self._process.terminate()
                return
```

**Comment by shozonu** [comment]
I can confirm, I noticed the same behavior when using the `FFmpegPCMAudio` class (which uses the `._pipe_writer()` method from `FFmpegAudio`. Modifying the `_pipe_writer()` method as above fixes the issue.

To keep the `terminate()` in there, I think we just need to add a `wait()` before to ensure we let the ffmpeg process finish before terminating it.
```python3
self._stdin.close()
self._process.wait()
self._process.terminate()
```

**Comment by RileSamurott** [comment]
> To keep the `terminate()` in there, I think we just need to add a `wait()` before to ensure we let the ffmpeg process finish before terminating it.
We could keep the terminate in that way, but I get the feeling that it isn't really necessary. `self.process.wait()` waits for the `ffmpeg` process to terminate by itself, so the secondary call to `terminate()` is redundant.
Plus, after stdin is closed the pipe thread does nothing anyways, so we can just immediately return after closing the stdin.

**Comment by thedtvn** [comment]
same bug

**Comment by kairi003** [comment]
Same bug

- Python v3.10.6
- discord.py v2.2.2
- aiohttp v3.8.4
- system info: Ubuntu 22.04.2 LTS
