### ISSUE TITLE
Adding the new selects feature

### ISSUE THREAD

**Issue by lol219** [Rapptz/discord.py#9003]
### Summary

Implementing the new select menu

### What is the feature request for?

The core library

### The Problem

This is a feature request to implement the new select menu components support in discord.py.

### The Ideal Solution

Implementing it

**Comment by ImVaskel** [comment]
Discord.py v2.0.0 supports all of the components api. You can find the docs [here](https://discordpy.readthedocs.io/en/latest/interactions/api.html#discord.SelectMenu).

**Comment by helish88** [comment]
> Discord.py v2.0.0 supports all of the components api. You can find the docs [here](https://discordpy.readthedocs.io/en/latest/interactions/api.html#discord.SelectMenu).

read [this](https://discord.com/developers/docs/change-log#new-select-menu-components)

**Comment by lol219** [comment]
> Discord.py v2.0.0 supports all of the components api. You can find the docs [here](https://discordpy.readthedocs.io/en/latest/interactions/api.html#discord.SelectMenu).

No there is something new about them.

**Comment by ChasL** [comment]
To expand, from my understanding reading the updated discord API docs, there are new types of selection dropdowns: String (the existing one), Channel, User, Role, and Mentionable. All but String are auto populated by the API. Currently this breaks some things like adding a selection dropdown to a Modal as components now require a type ID field to be sent in the call.

https://discord.com/developers/docs/interactions/message-components#select-menus

**Comment by Infiniticity** [comment]
This has been implemented in [`5009c83`](https://github.com/Rapptz/discord.py/commit/5009c83bc9fe866a03a2dbfc2042775d114ab1fc).
