### ISSUE TITLE
Add decorator for implicit `FlagConverter` creation, generate flags from function signature

### ISSUE THREAD

**Issue by Mega-JC** [Rapptz/discord.py#9004]
### Summary

A decorator should be implemented that allows for the creation of `FlagConverter` classes implicitly 

### What is the feature request for?

discord.ext.commands

### The Problem

The `FlagConverter` feature set added to `v2.0` of the library is great and allows us to sidestep former limitations within `discord.ext.commands`, whilst improving the UX side of things on the Discord end.

In a codebase however, every distinct text command requires the manual creation of a `FlagConverter` subclass in order to use flags as arguments. This works, but can be cumbersome, as you

1. Conceal flags inside a class, meaning that flag definitions aren't always directly visible.
2. Have to manage the definition of positional and flag parameters separately.

### The Ideal Solution

The main idea is to turn this

```py
class BanFlags(commands.FlagConverter):
    members: List[discord.Member] = commands.flag(name='member')
    reason: str
    days: int = 1

@commands.command()
async def ban(ctx, *, flags: BanFlags):
    for member in flags.members:
        await member.ban(reason=flags.reason, delete_message_days=flags.days)
```
... into this

```py
@commands.command()
@commands.flagconverter_kwargs(prefix="", delimiter=":", cls=commands.FlagConverter) # all arguments would be optional, these are the default
async def ban(
    ctx,
    *, # you can also have '*args', but the annotation must be supported by Greedy[...], to allow for proper parsing of flags
    reason: str, # will be a required flag, just like in normal Python
    days: int = 1,
    members: List[discord.Member] = commands.flag(name='member')
):
    for member in members:
        await member.ban(reason=reason, delete_message_days=days)
```

Adding this feature would streamline the experience of working with flags in a codebase, and would unify the definition of flags with positional parameters, whilst reducing the amount of code required to create flags.

The core implementation for this wouldn't be too complex: You wrap the command callback in a wrapper function that doesn't reveal itself (it would basically look like:
```py
async def wrapper(*args, flags: KwargOnlyFlags):
    return func(*args, **flags.__dict__)
```
) and generate a fake `inspect.Signature(...)` for it, based on the original callback's signature (which would make the wrapper now look like e.g.
```py
async def ban(
    ctx, *, flags: KwargOnlyFlags
):
```
) and assign that as a `__signature__` attribute for the library to use (it won't be able to tell).

I've got this to work with ~150 LOC, which I would like to contribute, but all feedback on the idea is appreciated.

### The Current Solution

To do things the usual way. It will always work, but could be more streamlined for some simpler use cases.

**Comment by Rapptz** [comment]
The way FlagConverter works makes this feature request non-trivial to do. On top of that, the entire point of the flag converter is to make it cleaner to do flags without polluting the signature with too many parameters and arguments, thus making it cleaner to use. It also allows you to have methods in the class, which this alternative syntax would not let you do. Fundamentally, this feature request is worse to read than the current equivalent, sorry.
