### ISSUE TITLE
add list of ui custom_id that working and not time out

### ISSUE THREAD

**Issue by thedtvn** [Rapptz/discord.py#9005]
### Summary

get list custom_id

### What is the feature request for?

The core library

### The Problem

can not see where discord.py save custom_id

### The Ideal Solution

᲼᲼

### The Current Solution

᲼᲼

### Additional Context

᲼᲼

**Comment by Rapptz** [comment]
This issue makes no sense as is. Please elaborate.

**Comment by thedtvn** [comment]
> This issue makes no sense as is. Please elaborate.

@Rapptz  how can i get list of custom_id list that handle the `Bot UI Kit`

**Comment by Rapptz** [comment]
Everything has a `custom_id` property. Use that.

**Comment by thedtvn** [comment]
> Everything has a `custom_id` property. Use that.

how to get list of custom_id that not timeout :\ and where is save this ??
![image](https://user-images.githubusercontent.com/80153297/196029053-1297f4d7-938f-488a-8373-f57401fc039f.png)

**Comment by Rapptz** [comment]
You provide it, e.g. `discord.ui.Button(custom_id='...')`.

This issue tracker is not for library questions. You can go to [the discord server for that](https://discord.gg/dpy).
