### ISSUE TITLE
on_scheduled_event_user_add doesnt trigger

### ISSUE THREAD

**Issue by Sedpower** [Rapptz/discord.py#9006]
### Summary

When an user click on the button "intersted" of an scheduled event, on_scheduled_event_user_add event doesn't trigger   

### Reproduction Steps

Just write this code and create an event in guild where the bot is. Then click on "interested" button. finally go check the console, nothing is printed.
```py
import discord
from discord.ext import commands

load_dotenv()

intents = discord.Intents.all()

bot = commands.Bot(command_prefix = "§", description = 'Vieux bot de test', intents=intents)

@bot.event
async def on_scheduled_event_user_add(event, user):
    print("test")

bot.run(os.getenv("TOKEN"))```

### Minimal Reproducible Code

```python
import discord
from discord.ext import commands

bot = commands.Bot(command_prefix = "THEPREFIX", intents=discord.Intents.all())

@bot.event
async def on_scheduled_event_user_add(event, user):
    print("test")

bot.run("THETOKEN")
```

### Expected Results

It should print `test` in the console

### Actual Results

Nothing is printed

### Intents

all

### System Information

- Python v3.8.10-final
- py-cord v2.2.0-final
- aiohttp v3.7.4.post0
- system info: Linux 5.15.0-50-generic #56~20.04.1-Ubuntu SMP Tue Sep 27 15:51:29 UTC 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I asked for help on the discord and a helper tried to help but he didn't find any error in my code so I opened this issue as last resort

**Comment by Rapptz** [comment]
This isn't the issue tracker for pycord.
