### ISSUE TITLE
Add new delete ephemeral messages endpoints

### ISSUE THREAD

**Issue by Koda31** [Rapptz/discord.py#9014]
### Summary

Implement new delete ephemeral messages

### What is the feature request for?

The core library

### The Problem

This is a feature request to implement the new delete ephemeral messages endpoints discord just released. Want to be able to delete ephemeral messages after the user has submitted a response from buttons/drop-downs.

### The Ideal Solution

To be able to call something like delete() on the incoming interaction. 

### Additional Context

https://discord.com/developers/docs/change-log#delete-ephemeral-messages

**Comment by Rapptz** [comment]
These endpoints are already implemented, discord just changed it so it works for ephemeral messages too.
