### ISSUE TITLE
Can't compare equality of messages

### ISSUE THREAD

**Issue by bmintz** [Rapptz/discord.py#902]
`m1 == m2` is False unless `m1 is m2`.

## Test case

```python
@bot.command()
async def foo(context):
    message = await context.send('Bar baz!')

    def check(reaction, user):
        return reaction.message == message

    reaction, user = await bot.wait_for('reaction_add', check=check)

    await context.send('Got one!')
```
### Alternate test case

```python
m1 = discord.Message(state='foo', channel='bar', data={'id': 123})
m2 = discord.Message(state='foo', channel='bar', data={'id': 123})
assert m1 == m2
```

## Problem steps

1. Say !foo
2. Add a reaction to the "Bar baz!" message

### Expected behavior

"Got one!" is sent.

### Actual behavior

Nothing happens.

## Workaround

Compare the IDs of the messages instead.

**Comment by Rapptz** [comment]
This is by design.

Some people would want it to compare `content` along with `id`, others would just want the `id`. So it's unimplemented.

**Comment by bmintz** [comment]
Shouldn't it raise `NotImplementedError` then?

**Comment by Rapptz** [comment]
No. Equality should never raise.
