### ISSUE TITLE
AttributeError: __aexit__ when attempted to run the basic_voice.py example

### ISSUE THREAD

**Issue by svioletg** [Rapptz/discord.py#9023]
### Summary

AttributeError: __aexit__ when attempted to run the basic_voice.py example

### Reproduction Steps

1. Download the basic_voice.py file from the examples directory in this repository.
2. Run with python.

At first I was trying to use it as a reference to make my own bot from scratch, but I had gotten the error that I mentioned. To check something I ran the file itself without modifying anything besides the token, and I received the same error.

### Minimal Reproducible Code

```python
@bot.event
async def on_ready():
	print(f'Logged in as {bot.user} (ID: {bot.user.id})')
	print('------')

async def main():
	async with bot:
		await bot.add_cog(Music(bot))
		await bot.start(my token here)
```

### Expected Results

Expected the bot to start and for the client to connect.

### Actual Results

The following error occurs when trying to run the python file:

```
Traceback (most recent call last):
  File "basic_voice.py", line 151, in <module>
    asyncio.run(main())
  File "C:\Users\Seth\AppData\Local\Programs\Python\Python38\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\Seth\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 608, in run_until_complete
    return future.result()
  File "basic_voice.py", line 146, in main
    async with bot:
AttributeError: __aexit__
```

### Intents

discord.Intents.default(), message_content=True

### System Information

- Python v3.8.0-final
- py-cord v2.2.2-final
- aiohttp v3.8.3
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

**Comment by AbstractUmbra** [comment]
You are using `pycord` and not discord.py. Please use their issue tracker and not ours.

**Comment by svioletg** [comment]
How do I use discord.py instead, then? I don't remember installing or using pycord at any point, I've been following discord.py's docs & tutorials this whole time.

**Comment by BlockyTheDev** [comment]
Have you installed discord.py with pip because you wrote "py-cord v2.2.2-final" in the System Information category?

**Comment by svioletg** [comment]
It seems to work after I uninstalled discord.py & pycord and then installed it again. I guess I must've had a different installation from years back, or something, but this seems like its solved.
