### ISSUE TITLE
Migrate to RESTful slash commands based Architecture?

### ISSUE THREAD

**Issue by theSoberSobber** [Rapptz/discord.py#9024]
### Summary

User triggered Serverless Architecture instead of always listening

### What is the feature request for?

The core library

### The Problem

Discord is slowly cutting the access the message intents for all. Slash command based serverless is the only way forward now.

### The Ideal Solution

This is a huge breaking change and requires changes in the core interaction utils. It's a big but necessary migration fro the road ahead. I am not very good in python, but am always available for further discussion here on this issue. Good Luck.

**Comment by Rapptz** [comment]
There are currently no plans for this. Discussion of this is on the discord server but for now making an agnostic server side implementation is not within the scope of the project. This can be revisited later but it's not important enough (despite FUD) to allocate more resources into.
