### ISSUE TITLE
Using client.login rather than client.run

### ISSUE THREAD

**Issue by FMWK** [Rapptz/discord.py#904]
I'm looking to use the API to grab server information periodically. The dilemma that I am having is I think using `client.run` is causing the code to hang and obviously wait for something to happen.

I am planning on calling the function to grab the stats from another file. I know I need to open the connection, store the stats and then close it again. How to achieve this, i'm not sure.

Any help would be greatly appreciated.

**Comment by Andris0** [comment]
`client.run` is a blocking call that starts the event loop and so, needs to be the last thing you call.
After running it, you can interact with client by using offered client events or self defined background tasks. If all you want to do is to collect information about a server, there are several approaches.

Keeping client alive:
- If you want to interact with the client through Discord, you can send a collection call yourself using `on_message` event with appropriate checks.
- If you want the collection to happen every x amount of time on its own, you can define a background task that will be run at the start and have an infinite loop with a `sleep` between each iteration (there is an example in docs FAQ section).

Keep client alive only during info gathering:
- Run the client, use `on_ready` event to execute the collection, save it to a file, call `client.logout()` at the end.
- If you do not want to save the information to a file, but rather be passed to an external function that will be creating the client, use `on_ready` to execute the collection, save the info as a client instance attribute, call `client.logout()` while also overwriting `client.run` to end with returning the information attribute (check `client.run` in docs to see how you can have more control over the event loop).

**Comment by Gorialis** [comment]
`client.run` is blocking. This is intentional, and in single-thread capacity unavoidable because it is required to run the asyncio event loop discord.py runs on.

If you wish to run stuff while the bot is running, you can either push the event loop (or your task) onto another thread or you can create background tasks as mentioned in the [FAQ](http://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-run-something-in-the-background).

Additionally, `client.login` does not substitute `client.run`. `client.run` wraps around the coroutine `client.start`, which runs both `client.login` and `client.connect`. If you only run `login`, your bot will not function properly as it won't be able to hear any events.

**Comment by Vexs** [comment]
Or you could create an event loop and run the bot inside that, which is more or less the same as doing a background task but in a different maybe-more-convenient order. This lib isn't really designed to be embedded, excluding parts of webhook.

Additionally, what stats are you looking for? For a lot of things, the widget json might be sufficient. (Server members, etc)

**Comment by Gorialis** [comment]
I don't understand what the point of creating your own event loop would be unless it's in a different thread. Your sync code can run or the event loop can. They can't both run at once unless you create new threads or tasks within the event loop.

**Comment by FMWK** [comment]
I'm an idiot and forgot to mention that I want to call this from my reddit bot script. Call it, get the information and then close the Discord connection

**Comment by Gorialis** [comment]
Discord doesn't tend to like people disconnecting and reconnecting often, so if you're doing this I'd suggest spacing out how often you connect quite a bit (connecting only once every 10 minutes would clear you of any chance of getting booted off the websocket for it).

As for the actual script side, you can connect to Discord using `client.run` as before but make an `on_ready` definition (or a background task that uses `wait_for_ready`) that grabs your information and then uses `await client.logout()` to sign out.
Note that logging out **closes the event loop** so you'll need to create a new one if you want to reconnect (you can do this easily by just putting the following before you `.run()`:)
```py
asyncio.set_event_loop(asyncio.new_event_loop())
```

**Comment by FMWK** [comment]
@Gorialis Thank you. You wouldn't be able to _mend_ my code for me would you?

`
import discord
import asyncio
from discord.ext.commands import Bot
from discord.ext import commands
import platform

client = Bot(description="Sys#5888", command_prefix="*", pm_help = False)

@client.event
async def on_ready():
	async def getUsersCount():
		users = str(100)
		await client.close()
		return users

client.run('MY_TOKEN')
`

I was getting no errors and am very unfamiliar with this API. I was hoping the no errors means I'm on the right lines? 

I am calling from my other file with

 `
from Bot import getUsersCount
.....
usersNum = getUsersCount()
`
