### ISSUE TITLE
Allow `Client.run` to raise `KeyboardInterrupt` to calling application

### ISSUE THREAD

**Issue by nzlosh** [Rapptz/discord.py#9040]
### Summary

Add a parameter to `Client.run` to enable to option of raising `KeyboardInterrupt`

### What is the feature request for?

The core library

### The Problem

When using the `Client.run` method from an application, the `KeyboardInterrupt` exception is caught and silently discarded by the discord module.  This is convenient in many cases, however, the application I'm working with needs to perform clean-up if the user  interrupts it via the keyboard.

### The Ideal Solution

In an ideal situation, the `Client.run` method would accept an argument to make `KeyboardInterrupt` conditionally raised.  For example:

```python
    def run(
        self,
        token: str,
        *,
        reconnect: bool = True,
        log_handler: Optional[logging.Handler] = MISSING,
        log_formatter: logging.Formatter = MISSING,
        log_level: int = MISSING,
        root_logger: bool = False,
        raise_keyboard: bool = False,
    ) -> None:

</snip>

        try:
            asyncio.run(runner())
        except KeyboardInterrupt:
            # nothing to do here
            # `asyncio.run` handles the loop cleanup
            # and `self.start` closes all sockets and the HTTPClient instance.
            if raise_keyboard:
                raise KeyboardInterrupt
            return
```

### The Current Solution

The alternative would be to not use `Client.run` and write all the async code in the application to perform the equivalent of `Client.run`.  I'd like to avoid this for simplicity sake.

**Comment by Rapptz** [comment]
I suggest using `asyncio.run` instead if you want finer control. [There's an example in the repository](https://github.com/Rapptz/discord.py/blob/master/examples/advanced_startup.py) showing you how to do this.

**Comment by nzlosh** [comment]
Thank you for the prompt response and the link.  I'll use `asyncio.run` as suggested.
