### ISSUE TITLE
with_counts=true, get  approximate_member_count of "fetch_invite" bug

### ISSUE THREAD

**Issue by wang2956** [Rapptz/discord.py#9041]
### Summary

Cannot get the correct value of the invite member number

### Reproduction Steps

1. Get guild
2. Get invite id
3. fetch_invite(invite.id)
4. print(invite member number)
5. Get all guild member number

### Minimal Reproducible Code

```python
guild = self.get_guild(ID)
obj_invites = await guild.invites()
for invite in obj_invites:
    _invite = await self.fetch_invite(invite.id, with_counts=True)
    print(f'{invite.inviter} {_invite.approximate_member_count}')
```

### Expected Results

1. Get guild
2. Get invite id
3. fetch_invite(invite.id)
4. print(invite member number)
5. Get all invite member number

### Actual Results

Get all invite member number

### Intents

discord.Client

### System Information

- Python v3.10.5-final
- discord.py v2.0.1-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
As it stands right now, your issue doesn't really make sense to me since I'm not sure what you're expecting. What are you expecting and what happened?

**Comment by Rapptz** [comment]
I'm guess you made a duplicate issue (https://github.com/Rapptz/discord.py/issues/9042) so I'm closing this one.

Please don't open duplicate issues next time, thanks.
