### ISSUE TITLE
Invite get approximate_member_count or approximate_presence_count is None Bug

### ISSUE THREAD

**Issue by wang2956** [Rapptz/discord.py#9042]
### Summary

Can't get Invite attribute

### Reproduction Steps

1. Get Guild
2. Get invites
3. print approximate_member_count
4. print approximate_presence_count

### Minimal Reproducible Code

```python
guild = self.get_guild(ID)
obj_invites = await self.obj_guild.invites()
for invite in obj_invites:
  print(f'{invite.inviter} {invite.approximate_member_count}')
  print(f'{invite.inviter} {invite.approximate_presence_count}')
```

### Expected Results

approximate_member_count and approximate_presence_count is not None

### Actual Results

approximate_member_count and approximate_presence_count is None

### Intents

members, message_content

### System Information

- Python v3.10.5-final
- discord.py v2.0.1-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
The API does not return member count data using that endpoint, this is a Discord limitation. In order to get that information you need to fetch the invite and use `with_counts=True`.

**Comment by Rapptz** [comment]
No, it's the member count. It works fine for me:

![image](https://user-images.githubusercontent.com/1695103/199729332-28ed9fbb-6863-42b5-9aaa-b0774ab8a5b2.png)

This is similar to how regular invites work in the client.

**Comment by Rapptz** [comment]
You are frequently misusing terminology here which makes it a bit confusing to understand you.

A guild is a "server" in Discord. An invite does not ever return the number of guilds. A member is a user that is in the guild. The `approximate_member_count` gives an estimate of this number.

What you're asking for is the *uses* of an invite. This is under `invite.uses`.

**Comment by JDJGInc** [comment]
Either you can use fetch_guild and with_counts
Or do it with invite up to you

**Comment by Rapptz** [comment]
`Guild.approximate_presence_count` is returned when you fetch a guild with counts.
`Invite.approximate_presence_count` is returned when you fetch an invite with counts.

They're received differently, even though the number might be the same.

If you want to ask questions about the library, please go to [the official server instead](https://discord.gg/dpy).
