### ISSUE TITLE
Support for user connections attribute

### ISSUE THREAD

**Issue by medcelerate** [Rapptz/discord.py#9048]
### Summary

It would be useful to add thir-party connections support to the user model.

### What is the feature request for?

The core library

### The Problem

Currently, there appears to be no object that allows you to fetch a users third-party connections. 

https://discord.com/developers/docs/resources/user#connection-object

### The Ideal Solution

Adding an additional model to the user or a method that returns the connection model.

### The Current Solution

Making a separate http request to the discord api.

**Comment by Rapptz** [comment]
Those are only available through OAuth2, not through regular means. So this is out of scope for the library at this time.
