### ISSUE TITLE
Using couroutine in "after" function

### ISSUE THREAD

**Issue by WDN2010** [Rapptz/discord.py#905]
Hello! I have a trouble with my music bot. I'm trying to play next track using _after = check_queue_. But i can use _await_ only inside _async def_ functions, so i cant use await. Without _await_ i'm getting generator instead of thread (that seems quite logical). And when i'm trying to use _yield_ or _yield from_, function check_queue just doesnt calling. Can you help me to reslove this problem?

**Comment by Gorialis** [comment]
Look at [How do I pass a coroutine to the player’s “after” function?](http://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-pass-a-coroutine-to-the-player-s-after-function)

**Comment by WDN2010** [comment]
omg i watched this answer for 3 days and tryed to use for full function, but only now understood that i should use this for coroutine. Many thanks @Gorialis
