### ISSUE TITLE
User/role/channel/mentionable selects

### ISSUE THREAD

**Issue by GEOEGII555** [Rapptz/discord.py#9050]
### Summary

The user/role/channel/mentionable select menus are a new Discord feature which allows you to select users/roles/mentionables/channels respectively

### What is the feature request for?

The core library

### The Problem

I want to send a select menu so the user will select a channel, but in some servers there are too many channels to show in the string select menus, and channel select menus aren't implemented

### The Ideal Solution

Add these new types of select menus to Discord.py

**Comment by Soheab** [comment]
These "new selects" are implemented in v2.1 per this https://github.com/Rapptz/discord.py/commit/5009c83bc9fe866a03a2dbfc2042775d114ab1fc commit.
