### ISSUE TITLE
active developer not work

### ISSUE THREAD

**Issue by thedtvn** [Rapptz/discord.py#9060]
### Summary

well  new update

### Reproduction Steps

eval comand
```py
print(ctx.author.public_flags.active_developer)
```
![image](https://user-images.githubusercontent.com/80153297/201365364-73e39ac8-104c-4679-811d-196235d005b2.png)
![image](https://user-images.githubusercontent.com/80153297/201365373-084ebe8b-2e9e-474c-9532-459fc8ee22ef.png)

### Minimal Reproducible Code

```python
print(ctx.author.public_flags.active_developer)
```

### Expected Results

return True

### Actual Results

return False

### Intents

all

### System Information

```
- Python v3.11.0-candidate
- discord.py v2.1.0-alpha
    - discord.py metadata: v2.1.0a4635+g55f272f6
- aiohttp v3.8.3
- system info: Linux 5.19.0-1006-raspi #13-Ubuntu SMP PREEMPT Mon Oct 17 19:01:51 UTC 2022
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
Probably not a public flag then.

**Comment by thedtvn** [comment]
lol  you did not test :L

**Comment by Rapptz** [comment]
It's not a question of not testing it, it's a user flag so I just added it into the models. I care very little whether Discord exposes it or not since it's there for completion sake.

**Comment by Rapptz** [comment]
FWIW, I can't repro this:

![image](https://user-images.githubusercontent.com/1695103/201368266-f6012b8f-0527-4f69-be29-1be780915d91.png)
