### ISSUE TITLE
add Quarantined public_flags

### ISSUE THREAD

**Issue by thedtvn** [Rapptz/discord.py#9065]
### Summary

Quarantined flags

### What is the feature request for?

The core library

### The Problem

nan

### The Ideal Solution

checkout this
https://discord-api-types.dev/api/discord-api-types-v10/enum/UserFlags#Quarantined

### The Current Solution

add it :>

**Comment by dolfies** [comment]
This is almost definitely not a public flag.

**Comment by ImVaskel** [comment]
Discord has stated before that  they do not intend on this being a "public" flag, so the library did not add it. See [discord/discord-api-docs#5202](https://github.com/discord/discord-api-docs/pull/5202).

**Comment by thedtvn** [comment]
ok
