### ISSUE TITLE
[Feature Request] Add `__len__` to server.members Class

### ISSUE THREAD

**Issue by Modelmat** [Rapptz/discord.py#907]
It would nice and easy if we could just do `len(server.members()` could return the length of server members via the use of [this](https://docs.python.org/3/reference/datamodel.html?highlight=__len__#object.__len__).

**Comment by Rapptz** [comment]
I think you might be very confused.

`Server.members` already returns an appropriate type that has `__len__`.

**Comment by Modelmat** [comment]
Apparently I am. Oh well :P
