### ISSUE TITLE
Cannot install discord.py - Wheels

### ISSUE THREAD

**Issue by el3ctro4ndre** [Rapptz/discord.py#9072]
### Summary

Cannot install discord.py

### Reproduction Steps

python -m pip install discord

### Expected Results

Python 3.12 installs discord.py

### Actual Results

PS C:\Users\Andrea\Desktop\Nuova cartella (7)> python -m pip install yarl  
Collecting yarl
  Using cached yarl-1.8.1.tar.gz (172 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: multidict>=4.0 in c:\users\andrea\appdata\local\programs\python\python312\lib\site-packages (from yarl) (6.0.2)
Requirement already satisfied: idna>=2.0 in c:\users\andrea\appdata\local\programs\python\python312\lib\site-packages (from yarl) (3.4)
Building wheels for collected packages: yarl
  Building wheel for yarl (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for yarl (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      C:\Users\Andrea\AppData\Local\Temp\pip-build-env-1rbc9kn8\overlay\Lib\site-packages\setuptools\config\setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      **********************
      * Accelerated build *
      **********************
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\yarl
      copying yarl\_quoting.py -> build\lib.win-amd64-cpython-312\yarl
      copying yarl\_quoting_py.py -> build\lib.win-amd64-cpython-312\yarl
      copying yarl\_url.py -> build\lib.win-amd64-cpython-312\yarl
      copying yarl\__init__.py -> build\lib.win-amd64-cpython-312\yarl
      running egg_info
      writing yarl.egg-info\PKG-INFO
      writing dependency_links to yarl.egg-info\dependency_links.txt
      writing requirements to yarl.egg-info\requires.txt
      writing top-level names to yarl.egg-info\top_level.txt
      reading manifest file 'yarl.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.cache' found anywhere in distribution
      warning: no previously-included files found matching 'yarl\*.html'
      warning: no previously-included files found matching 'yarl\*.so'
      warning: no previously-included files found matching 'yarl\*.pyd'
      no previously-included directories found matching 'docs\_build'
      adding license file 'LICENSE'
      writing manifest file 'yarl.egg-info\SOURCES.txt'
      copying yarl\__init__.pyi -> build\lib.win-amd64-cpython-312\yarl
      copying yarl\_quoting_c.pyi -> build\lib.win-amd64-cpython-312\yarl
      copying yarl\_quoting_c.pyx -> build\lib.win-amd64-cpython-312\yarl
      copying yarl\py.typed -> build\lib.win-amd64-cpython-312\yarl
      running build_ext
      building 'yarl._quoting_c' extension
      creating build\temp.win-amd64-cpython-312
      creating build\temp.win-amd64-cpython-312\Release
      creating build\temp.win-amd64-cpython-312\Release\yarl
      "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Andrea\AppData\Local\Programs\Python\Python312\include -IC:\Users\Andrea\AppData\Local\Programs\Python\Python312\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcyarl/_quoting_c.c /Fobuild\temp.win-amd64-cpython-312\Release\yarl/_quoting_c.obj
      _quoting_c.c
      yarl/_quoting_c.c(3732): warning C4244: '=': conversione da 'Py_ssize_t' a 'int'. Possibile perdita di dati.
      yarl/_quoting_c.c(5166): warning C4996: 'Py_OptimizeFlag': deprecated in 3.12
      yarl/_quoting_c.c(5471): warning C4996: 'Py_OptimizeFlag': deprecated in 3.12
      yarl/_quoting_c.c(5505): warning C4996: 'Py_OptimizeFlag': deprecated in 3.12
      yarl/_quoting_c.c(8944): warning C4013: '_PyUnicode_Ready' non definita. Verr… considerata come esterna che restituisce un int.
      "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\Andrea\AppData\Local\Programs\Python\Python312\libs /LIBPATH:C:\Users\Andrea\AppData\Local\Programs\Python\Python312 /LIBPATH:C:\Users\Andrea\AppData\Local\Programs\Python\Python312\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" /EXPORT:PyInit__quoting_c build\temp.win-amd64-cpython-312\Release\yarl/_quoting_c.obj /OUT:build\lib.win-amd64-cpython-312\yarl\_quoting_c.cp312-win_amd64.pyd /IMPLIB:build\temp.win-amd64-cpython-312\Release\yarl\_quoting_c.cp312-win_amd64.lib
         Creazione della libreria build\temp.win-amd64-cpython-312\Release\yarl\_quoting_c.cp312-win_amd64.lib e dell'oggetto build\temp.win-amd64-cpython-312\Release\yarl\_quoting_c.cp312-win_amd64.exp
      _quoting_c.obj : error LNK2001: simbolo esterno _PyUnicode_Ready non risolto
      build\lib.win-amd64-cpython-312\yarl\_quoting_c.cp312-win_amd64.pyd : fatal error LNK1120: 1 esterni non risolti
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for yarl
Failed to build yarl
ERROR: Could not build wheels for yarl, which is required to install pyproject.toml-based projects

### Intents

discord.Intents.all()

### System Information

No module named discord

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by scrazzz** [comment]
https://discordpy.readthedocs.io/en/stable/intro.html#installing

**Comment by Rapptz** [comment]
Some of the dependencies don't have wheels for 3.11 yet. Not a discord.py issue.
