### ISSUE TITLE
Hybrid groupCommand.update(enabled=True) makes all subcommands to dissapear

### ISSUE THREAD

**Issue by Aguileitus** [Rapptz/discord.py#9095]
### Summary

If you update a hybrid groupCommand with enabled=False and then update it with enabled=True, it makes all the subcommands to disappear

### Reproduction Steps

Using the Minimal Reproducible Code:

1. Disable the group command: `!disable group`
2. Optionally use the command `!group` or help command `!help group` to check it was disabled
3. Optionally use one subcommand `!group sub1` to check it was correctly disabled also
4. Enable the group command: `!enable group`
5. Try to use the group command (it works) and then try to use a sub command (it invokes the command group) or check the help of the group `!help group` (the subcommands do not appear)
6. Additionally, trying to manually enable a sub command `!enable group sub1`, throws `AttributeError: 'NoneType' object has no attribute 'update'` error (this does not happen if you disable and enable a sub command individually). 

### Minimal Reproducible Code

```python
"""This is bot.py"""
import asyncio
import platform
import discord
from discord.ext import commands
from discord.message import Message

class TestBot(commands.AutoShardedBot):
    def __init__(self) -> None:
        intents: discord.Intents = discord.Intents.default()  # All but the 3 privileged ones
        # pylint: disable=assigning-non-slot
        intents.members = True
        intents.message_content = True
        super().__init__(command_prefix="!", intents=intents)

    async def setup_hook(self) -> None:
        await self.load_extension("testcog")

    async def on_ready(self) -> None:
        print("Ready.")

    async def on_message(self, message: Message, /) -> None:
        """Executed when the bot detects a message in any channel of any server."""
        if message.author.bot:
            return # Avoids bot triggering itself (or by other bots)
        # Without this, no @commands.command will be invoked.
        await self.process_commands(message)

if __name__ == "__main__":
    if platform.system().lower() == 'windows':
        # This is to prevent "RuntimeError: Event loop is closed" error on Client.close()
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
    bot = TestBot()
    bot.run("your_token")

"""This is testcog.py"""
from typing import Literal, Optional
import discord
from discord.ext import commands
from bot import TestBot

class TestCog(commands.Cog):
    def __init__(self, bot: TestBot, /) -> None:
        self.bot: TestBot = bot

    @commands.command()
    @commands.is_owner()
    async def disable(self, ctx: commands.Context, *, command_name: str) -> None:
        """Disables a command."""
        command = self.bot.get_command(command_name)
        command.update(enabled=False)

    @commands.command()
    @commands.is_owner()
    async def enable(self, ctx: commands.Context, *, command_name: str) -> None:
        """Enables a command."""
        command = self.bot.get_command(command_name)
        command.update(enabled=True)

    @commands.command()
    @commands.guild_only()
    @commands.is_owner()
    async def sync(self, ctx: commands.Context, guilds: commands.Greedy[discord.Object], spec: Optional[Literal["~", "*", "^"]] = None ) -> None:
        """Use Umbra's sync command here if needed."""

    @commands.hybrid_command()
    async def hi(self, ctx: commands.Context):
        await ctx.channel.send("Hi")

    @commands.hybrid_group(fallback="base")
    async def group(self, ctx: commands.Context):
        await ctx.channel.send("This is a group.")

    @group.command()
    async def sub1(self, ctx: commands.Context):
        await ctx.channel.send("This is sub command 1")

    @group.command()
    async def sub2(self, ctx: commands.Context):
        await ctx.channel.send("This is sub command 2")

async def setup(bot: TestBot) -> None:
    await bot.add_cog(TestCog(bot))
```

### Expected Results

The sub commands should be enabled along with the group command.

### Actual Results

The sub commands completely dissapear.

### Intents

        intents.members = True         intents.message_content = True

### System Information

- Python v3.10.4-final
- discord.py v2.1.0-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19045

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
Could you use `command.enabled = False` and `command.enabled = True` instead? Using `update` is mostly an internal detail and hybrid commands don't play nicely with it at all since their interface isn't meant for it.

**Comment by Aguileitus** [comment]
Ah, of course!
Yes, that is working perfectly fine, the only downside is that it only disables the group command, not the subcommands, but that is easy to handle.
Thanks!
