### ISSUE TITLE
Kick and ban command not working

### ISSUE THREAD

**Issue by Zeph108-dev** [Rapptz/discord.py#9096]
### Summary

When i tried to add a automod feature to my bot when i tested the kick and ban commands the bot only kicked a userr if the user has no roles

### Reproduction Steps

make an app command. make a user input option to put in a user. use the await member.kick()

### Minimal Reproducible Code

```python
@app_commands.command(name="kick", description="kick")
async def kick_user(self, interaction: Interaction, user: discord.Member):
    await member.kick()
    await interaction.response.send_message("kicked user")
```

### Expected Results

To kick the user

### Actual Results

only kicked a user without roles

### Intents

all

### System Information

- Python v3.8.10-final
- discord.py v2.1.0-final
- aiohttp v3.8.1
- system info: Linux 5.4.0-132-generic #148-Ubuntu SMP Mon Oct 17 16:02:06 UTC 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
Role hierarchy dictates that you can't kick those with higher roles than you. For more information on how roles work on Discord, see [this support link](https://support.discord.com/hc/en-us/articles/214836687-Role-Management-101).

**Comment by Zeph108-dev** [comment]
the user only had minimal privilege and the bot was an administrator

**Comment by Rapptz** [comment]
It doesn't matter if you have administrator if the role they have is above your bot. These methods just call the API directly and the API behaves on a role hierarchy basis.

**Comment by Zeph108-dev** [comment]
the role the user has is purely cosmetic and has no privilege so the bot should have kicked them
