### ISSUE TITLE
function callbacks within subclass of discord.ext.commands.Bot are given wrong parameters

### ISSUE THREAD

**Issue by blakejalexander** [Rapptz/discord.py#9099]
### Summary

function callbacks within subclass of discord.ext.commands.Bot are given wrong parameters

### Reproduction Steps

1. Subclass discord.ext.commands.Bot with your own flashy bot class
2. Create functions within the bot class that manipulate the bot's state
3. Register those functions using discord.ext.commands.Bot.add_command and provide an error handler function that sends exceptions to the command channel
4. Try to use the command

### Minimal Reproducible Code

```python
#! /usr/bin/env python3

import discord
import discord.ext.commands
import discord.ext.commands.errors
import discord.ext.tasks

import os

class MyAwesomeDiscordBot(discord.ext.commands.Bot):
    def __init__(self, p1 : int, p2 : int, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.value = p1 + p2
        self.add_command(self.vget)
        self.add_command(self.vmanip)

    async def on_ready(self):
        print("bot started!")

    @discord.ext.commands.command(name="vget")
    async def vget(ctx):
        await ctx.channel.send(f"{ctx.bot.value}")

    @discord.ext.commands.command(name="vmanip")
    async def vmanip(ctx, arg):
        ctx.bot.value = ctx.bot.value * arg
        await ctx.channel.send("value manipulated")

    @vmanip.error
    async def vmanip_error(ctx, error):
        await ctx.send(error)

if __name__ == "__main__":
    intents = discord.Intents.default()
    intents.message_content = True
    bot = MyAwesomeDiscordBot(7, 10, command_prefix='!', intents=intents)
    bot.run(os.env('DISCORD_TOKEN'))
```

### Expected Results

As in pre 2.0, the command executes without error and the bot command is called successfully with the correct arguments.

### Actual Results

Command raised an exception: TypeError: MyAwesomeDiscordBot.vmanip() missing 1 required keyword-only argument: 'args'

### Intents

see minimal reproducible code

### System Information

```privacy@fake-hostname:~$ python3 -m discord -v
- Python v3.10.8-final
- discord.py v2.1.0-final
- aiohttp v3.8.3
- system info: Linux 5.17.9-arch1-1 #1 SMP PREEMPT Wed, 18 May 2022 17:30:11 +0000
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

This example worked prior to the major version increment, and there is no details within the migration notes which leads me to believe this a regression. From what I can see, the responsible code is in discord.ext.commands.core, below:
```
def get_signature_parameters(
    function: Callable[..., Any],
    globalns: Dict[str, Any],
    /,
    *,
    skip_parameters: Optional[int] = None,
) -> Dict[str, Parameter]:
    signature = Signature.from_callable(function)
    params: Dict[str, Parameter] = {}
    cache: Dict[str, Any] = {}
    eval_annotation = discord.utils.evaluate_annotation
    required_params = discord.utils.is_inside_class(function) + 1 if skip_parameters is None else skip_parameters
    if len(signature.parameters) < required_params:
        raise TypeError(f'Command signature requires at least {required_params - 1} parameter(s)')

    iterator = iter(signature.parameters.items())
    for _ in range(0, required_params):
        next(iterator)

    for name, parameter in iterator:
        default = parameter.default
        if isinstance(default, Parameter):  # update from the default        
```

This code is called when setting a command's callback function in order to create a dictionary of its arguments from the function signature. If the callback is within a class, it sets `required_params` to be `2`, meaning it skips over the first two arguments, the first being a Context (good) and the second being my command argument (bad) and the `params` dict that is returned is empty.

If this is acknowledged as a bug I'm happy to create a fix and submit a pull request.

**Comment by Zephyrkul** [comment]
Not a d.py bug. You're missing `self`, because you're inside of a class. That's why d.py skips one extra parameter when the callback is an instance method.

**Comment by Rapptz** [comment]
Commands within the bot subclass have never been officially supported, even in v1.0. Abusing function objects like this without them being static methods is also a bit odd, and if you had used the staticmethod decorator it would have pointed out the unsupported nature of what you're trying to do.
