### ISSUE TITLE
WebSocket ratelimiting cause the client to exit

### ISSUE THREAD

**Issue by Hornwitser** [Rapptz/discord.py#91]
If the client sends too many messages in a short amount of time on the WebSocet connection (for example by sending status updates too often), it will be terminated with the data "rate limited".  The current rate limit on the WebSocet is 60/60 according to the discord devs.

The debug logs shows the following appearing:

    DEBUG:websockets.protocol:client << Frame(fin=True, opcode=8, data=b'\x0f\xa8rate limited')
    DEBUG:websockets.protocol:client >> Frame(fin=True, opcode=8, data=b'\x0f\xa8rate limited')

The `Client.connect()` method then exits with no errors logged or exceptions raised, making it hard to track down what happened.

**Comment by Rapptz** [comment]
This is stupid.

**Comment by Rapptz** [comment]
I don't think I'm going to fix this. If someone is sending too many game presence updates then that's their problem.

**Comment by khazhyk** [comment]
I do believe discord devs also said they will be updating soon so too many updates will be ignored, rather than causing disconnect.

**Comment by njibhu** [comment]
rate limit is not only caused by client status update, you can try the following code or use discord.py in any server usef by many thousands of people..
`    async for msg in client.logs_from(chan, limit=1000):
        t = loop.create_task(client.delete_message(msg))`
