### ISSUE TITLE
pass_context=true, with 'true' not being defined

### ISSUE THREAD

**Issue by mightbemaybeme** [Rapptz/discord.py#911]
i have a command that needs ctx to work, so i added "pass_context=true" into the bot.command, and it errors out with:
```
Traceback (most recent call last):
  File "FoikunBot.py", line 27, in <module>
    @bot.command(pass_context=true)
NameError: name 'true' is not defined
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7600f990>
```

the command used to work before, but it now returns an error, and i have updated discord.py, with it not helping.

if it helps at all, the code i used is:
```
@bot.command(pass_context=true)
async def prune(ctx, amount : int):
```

**Comment by Harmon758** [comment]
Capital T for [True](https://docs.python.org/3/library/constants.html#True)

**Comment by mightbemaybeme** [comment]
```
Traceback (most recent call last):
  File "FoikunBot.py", line 27, in <module>
    @bot.command(pass_context=True)
NameError: name 'true' is not defined
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x75f68990>
```

**Comment by tilda** [comment]
are you on rewrite?
if so, you don't need to pass context, as you already have the `ctx` as argument

**Comment by mightbemaybeme** [comment]
not on rewrite

**Comment by fourjr** [comment]
as Harmon758 said, capital `True`

**Comment by mightbemaybeme** [comment]
>tfw the code works a couple hours later without changes
>im blaming cache
