### ISSUE TITLE
VoiceChannel Slowmode

### ISSUE THREAD

**Issue by TheUntraceable** [Rapptz/discord.py#9110]
### Summary

VoiceChannels can have a slowmode. This is not reflected in Discord.py

### What is the feature request for?

The core library

### The Problem

I want to be able to check the slowmode of a VoiceChannel, the editing part is fine (using the `VoiceChannel.edit` function with a `slowmode_delay` kwarg works as I've tested, but not documented). I have found no documentation for reading this attribute.

### The Ideal Solution

I wish for there to be a `slowmode_delay` attribute for `VoiceChannel`

**Comment by Phantom230** [comment]
Hi there, Untraceable; the fix to this is called get better.

**Comment by rdrescher909** [comment]
This does work, it's simply undocumented.
