### ISSUE TITLE
Add `delete_after` to `InteractionResponse.edit_message`

### ISSUE THREAD

**Issue by wmtorode** [Rapptz/discord.py#9145]
### Summary

InteractionResponse.edit_message should support an optional delete_after parameter

### What is the feature request for?

The core library

### The Problem

The nextcord fork of discord.py supports this feature, which allows for the deletion of the original interaction once it has completed by doing the following in a callback from a UI component like a select:

```python

    async def callback(self, interaction: nextcord.Interaction):

        if self.state == EStates.Done:
            await interaction.response.edit_message(delete_after=1)
            self.view.stop()
            return

```

the lack of this feature in discord.py currently stops me for returning from the fork to the mainline discord.py

### The Ideal Solution

add support for delete_after to InteractionResponse.edit_message or provide some manner to delete the original interaction upon its completion

**Comment by Subjoel** [comment]
i totally agree

**Comment by Soheab** [comment]
`delete_after` won't be added since it's one of the most hated things by the devs.

You can easily do it yourself with something like the following:
```py
import asyncio

# callback
# respond to the interaction 
await interaction.response.send/edit_message(...)
# wait 5 seconds
await asyncio.sleep(5)
# delete the response
# and ignore all errors
try:
    await interaction.delete_original_response()
except: # bad practice but this is what the delete_after does in other implementations
    pass
```
The above can be made into some helper func by yourself and called whenever.

**Comment by Rapptz** [comment]
Implemented in https://github.com/Rapptz/discord.py/commit/50e66d4072670b449e8371b3a28db0cd7726a73a
