### ISSUE TITLE
NameError: name 'bot' is not defined

### ISSUE THREAD

**Issue by Yoko11111111** [Rapptz/discord.py#9146]
### Summary

NameError: name 'bot' is not defined

### Reproduction Steps

I wanted to connect to my database. But i cant do @bot.command. Name "bot" is not defined.

### Minimal Reproducible Code

```python
cursor = mydb.cursor(dictionary=True)

@bot.event
async def on_ready():
    print('Online')


@bot.command()
async def set(ctx):
    sql = "INSERT INTO users (ID, BALANCE) VALUES (%s, %s)"
    val = (ctx.author.id, "1")
    cursor.execute(sql, val)
    print('insert into db')

@bot.command()
async def bal(ctx):
     cursor.execute(f'SELECT BALANCE from users where ID = {ctx.author.id}')
     print('select balance')

     rows = cursor.fetchall()
     for row in rows:
         await ctx.send(row["BALANCE"])

bot.run(token)
```

### Expected Results

As i said i wanted to connect to my db with this Code:
(I deleted the host usw for the showcase)

mydb = mysql.connector.connect(
    host='',
    user='',
    password='',
    database=''
)

cursor = mydb.cursor(dictionary=True)

@bot.event
async def on_ready():
    print('Online')

@bot.command()
async def set(ctx):
    sql = "INSERT INTO users (ID, BALANCE) VALUES (%s, %s)"
    val = (ctx.author.id, "1")
    cursor.execute(sql, val)
    print('insert into db')

@bot.command()
async def bal(ctx):
    cursor.execute(f'SELECT BALANCE from users where ID = {ctx.author.id}')
    print('select balance')

    rows = cursor.fetchall()
    for row in rows:
        await ctx.send(row["BALANCE"])

bot.run(token)

### Actual Results

I already tried this: bot = discord.Client()
i am not sure if it is the right way to fix that. I searched a lot and just found something like this. But it isnt working for me

### Intents

intents = discord.Intents.all()

### System Information

- Python v3.10.7-final
- discord.py v2.1.0-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Yoko11111111** [comment]
Traceback (most recent call last):
  File "C:\Users\jamu\\Desktop\Mail\db.py", line 16, in <module>
    @bot.event
NameError: name 'bot' is not defined

**Comment by helish88** [comment]
![image](https://user-images.githubusercontent.com/52331802/208691040-15ff7990-d20f-4a7e-8971-1fa852ace4e3.png)

**Comment by Yoko11111111** [comment]
> ![image](https://user-images.githubusercontent.com/52331802/208691040-15ff7990-d20f-4a7e-8971-1fa852ace4e3.png)

![grafik](https://user-images.githubusercontent.com/108374464/208693675-dc45bb26-72d0-430e-bccb-5e17816be176.png)

**Comment by Yoko11111111** [comment]
intents = discord.Intents.all()
intents.members = True
prefix = "!"
bot = commands.bot(command_prefix=prefix, help_command=None, intents=intents)
bot.run("")

**Comment by ImVaskel** [comment]
Please take issues like this into the [discord](discord.gg/dpy). The error does explain exactly what's wrong, this is not an issue with the library.

**Comment by Rapptz** [comment]
`NameError` is an exception that comes from your own code, it means that you're referring to a `bot` variable that doesn't exist. 

This issue tracker is for issues with the library, not your code. In order to make a Discord bot, it is recommended to understand Python, the official documentation  has [a tutorial](https://docs.python.org/3/tutorial/index.html) which might be of use. Alternatively, many resources exist online to help learn Python.
