### ISSUE TITLE
An int that is more that 16 characters is not classed as an int with slash commands

### ISSUE THREAD

**Issue by KanchiMoe** [Rapptz/discord.py#9147]
### Summary

An int that is more than 16 characters is not classed as an int in slash commands

### Reproduction Steps

1. Use the minimal reproducible code to create and run a bot.
2. When ready, run the slash command `/givemeanint 1234567890123456789`.

### Minimal Reproducible Code

```python
import discord
from discord.ext import commands
from discord import app_commands

DISCORD_BOT_TOKEN = "" 
BOT_INTENTS = discord.Intents.all()
BOT_CLIENT = commands.Bot(command_prefix='$$', intents=BOT_INTENTS, help_command=None)

@BOT_CLIENT.event
async def on_ready():
    print(f"Logged in as \"{BOT_CLIENT.user}\" (ID: {BOT_CLIENT.user.id})")  

    SlashCommandSynched = await BOT_CLIENT.tree.sync()
    print(f"Synched {len(SlashCommandSynched)} slash command(s).")

    print(f"Bot ready.")

@BOT_CLIENT.tree.command(name="givemeanint")
async def givemeanint(interaction: discord.Interaction, arg: int):
    await interaction.response.send_message(f"{arg}")

def main():
    BOT_CLIENT.run(DISCORD_BOT_TOKEN)

if __name__ == '__main__':
    main()
```

### Expected Results

In Discord, I run the command `/givemeanint 1234567890123456789`.

The argument should pass `int` validation checks, as it is an integer.

### Actual Results

Discord's interface says this number is not a valid integer, even though it is.

![](https://i.imgur.com/6WxnTRd.png)

### Intents

discord.Intents.all()

### System Information

```console
py -m discord -v
- Python v3.9.5-final
- discord.py v2.1.0-final
- aiohttp v3.8.1
- system info: Windows 10 10.0.19044
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

The integer I was using is a recent Discord snowflake so I could look up various discord elements (like `get_channel`). After a very quick Google search, python 3 doesn't appear to have an integer limit:

*  https://note.nkmk.me/en/python-int-max-value/
* https://stackoverflow.com/questions/7604966/maximum-and-minimum-values-for-ints

So this number should pass for a valid integer, but it doesn't.

**Comment by cibere** [comment]
This is a discord bug. Discord IDS are bigger than discord considers ints, so you will have to typehint your argument to `str`, and manually convert it to an int. And if It can not be converted, send an error saying so. Unfortunately, there is no better way to go about this.

**Comment by KanchiMoe** [comment]
> This is not a discord.py bug.

Ah, thanks for the assistance anyway. Do you know where would be best to report it?

**Comment by cibere** [comment]
You could always create a bug report: https://support.discord.com/hc/en-us/requests/new?ticket_form_id=360006586013
Though I'm fairly sure they know about this.

**Comment by KanchiMoe** [comment]
Thanks.

Closing per the above.
