### ISSUE TITLE
Wheel

### ISSUE THREAD

**Issue by 4rmy** [Rapptz/discord.py#9158]
### Summary

Would like a wheel to be built for use

### What is the feature request for?

The core library

### The Problem

As you might have heard, py-script is becoming increasingly popular.
With that, packages can only be used under certain circumstances. 
In order to use discord.py with py-script, a wheel must be built and uploaded to PyPI.

### The Ideal Solution

use pythons "build" in order to compile the package.

**Comment by Rapptz** [comment]
![image](https://user-images.githubusercontent.com/1695103/209604356-fed3cf66-93a8-4972-8f07-ac4d9d07bacd.png)
