### ISSUE TITLE
AttributeError: module 'discord' has no attribute 'ext'

### ISSUE THREAD

**Issue by potatonugget** [Rapptz/discord.py#916]
`
Traceback (most recent call last):
  File "bot.py", line 9, in <module>
    import dankbot
  File "C:\Users\xdxdx\potat\dev\Discord Bots\discordbot\dankbot\__init__.py", line 1, in <module>
    from .db import DankBot
  File "C:\Users\xdxdx\potat\dev\Discord Bots\discordbot\dankbot\db.py", line 8, in <module>
    class DankBot(discord.ext.commands.Bot):
AttributeError: module 'discord' has no attribute 'ext'
`

I keep getting this, even though no files inside my bot's folder is named 'discord'.

**Comment by Rapptz** [comment]
If this is rewrite, then `discord.ext` is a namespace package. Which means you must do something similar to `from discord.ext import commands` and not just `import discord` and using `discord.ext.commands`.

**Comment by potatonugget** [comment]
I think the version I'm using is 0.16.12. Also, it worked before, but I recently ran it, and it gave me that error

**Comment by Rapptz** [comment]
This code would work as-is under the old version of the library so I doubt it unless you have a `discord` folder or file.

**Comment by potatonugget** [comment]
Strangely, using `from discord.ext import commands` actually worked instead of just using `import discord` and `class DankBot(discord.ext.commands.Bot):`
