### ISSUE TITLE
Inconsistent embed suppression across help

### ISSUE THREAD

**Issue by ItsZabbs** [Rapptz/discord.py#9163]
### Summary

An invalid command help message would have embeds suppressed but an invalid group command help message doesn't have embeds suppressed

### Reproduction Steps

Using the R. Danny bot as a test subject here:

1. Send `?help https://google.com`. Notice how the response has a link but the embed for the link **is not present**.
2. Send `?help reminder https://google.com`. Notice how the response has a link and the embed for the link **is present**.

### Expected Results

Consistent behavior and the second example should not have an embed for the link.

### Actual Results

Inconsistent behavior. i.e the first example has no embed but the second example does.
First example:
![image](https://user-images.githubusercontent.com/74313798/210506265-94bbc6fe-108e-474f-963a-22d3dbed2acc.png)

Second example:
![image](https://user-images.githubusercontent.com/74313798/210506294-6aa32086-2a5d-4fde-af3a-18327de9cc7d.png)

### Intents

N/A

### System Information

N/A
discord.py v2.1.0

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
This isn't a bug with the library. I don't think it's ever been documented or intended for embeds to be suppressed in the help command.

The client isn't embedding one of the URLs because it has quotes in it.
