### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by dkatkf** [Rapptz/discord.py#9164]
### Summary

Bot is not online

### Reproduction Steps

pip3 install discord
pip3 uninstall discord -y
pip3 install discord
sudo apt install ca-certificates
sudo update-ca-certificates --fresh
export SSL_CERT_DIR=/etc/ssl/certs

### Minimal Reproducible Code

```python
SyntaxError: invalid syntax
gimjin-yeong@~~~~MacBookPro ~ %
```

### Expected Results

bot in action

### Actual Results

not online

### Intents

A bot I made as a joke

### System Information

MacBookPro ~ % python -m discord -v
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No module named discord

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by GoogleGenius** [comment]
This is not an issue with the library. It also appears for some reason you’re using python 2.7. Please make sure you use the correct version (discord.py v2 is 3.8+) and you can specify it using python3 in your commands. The commands you have input earlier don’t seem to have any syntax errors so I’m not sure what’s up with that. Maybe someone else can have a look…

**Comment by Rapptz** [comment]
This issue does not seem to be one from the library but rather a syntax error. As there is no actionable information here, I'll close this issue.
