### ISSUE TITLE
discord.app_commands.errors.CommandSyncFailure: Failed to upload commands to Discord (HTTP status 400, error code 50035 In redirect_uris.0: Not a well formed URL.

### ISSUE THREAD

**Issue by thedtvn** [Rapptz/discord.py#9168]
### Summary

discord.app_commands.errors.CommandSyncFailure: Failed to upload commands to Discord (HTTP status 400, error code 50035 In redirect_uris.0: Not a well formed URL.

### Reproduction Steps

this is a bug on restart bot i think is a bug on my old but after an update is still bug 

### Minimal Reproducible Code

```python
await bot.tree.sync()
```

### Expected Results

just work

### Actual Results

err

### Intents

all

### System Information
```
- Python v3.11.1-final
- discord.py v2.2.0-alpha
    - discord.py metadata: v2.2.0a4667+gd609c78a
- aiohttp v3.8.3
- system info: Linux 5.4.0-1077-raspi #88-Ubuntu SMP PREEMPT Mon Nov 28 14:31:37 UTC 2022
```
### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

![image](https://user-images.githubusercontent.com/80153297/211517406-5bd0eac1-0d73-49a7-9888-59905eea400f.png)

**Comment by Zerbaib** [comment]
i think [this](https://github.com/dolfies/discord.py-self/issues/365) can help you

**Comment by GoogleGenius** [comment]
You should probably update to the stable/latest version v2.1.

**Comment by GoogleGenius** [comment]
Also you shouldn't sync in on_ready, rather, use the asynchronous setup_hook provided in the Client

**Comment by AiroPi** [comment]
I have the same problem.
Maybe it relate on this ?
https://discord.com/channels/613425648685547541/697138785317814292/1054837953752486018

**Comment by Rapptz** [comment]
This is a Discord issue, I can't do anything about it. I'll wait until it's fixed, which Discord said it already is in https://github.com/discord/discord-api-docs/issues/5838

**Comment by thedtvn** [comment]
![image](https://user-images.githubusercontent.com/80153297/211688305-8b6ce52d-ae6e-4056-91bf-3ff6ee52b52d.png)
It has been fix
