### ISSUE TITLE
AttributeError: module 'logging' has no attribute 'getLogger

### ISSUE THREAD

**Issue by TheDocter** [Rapptz/discord.py#917]
When I run my code I get the following error on trying to import discord. I've installed all the requirements that are in the readme file. Any suggestions on what is missing?

> Traceback (most recent call last):
>   File "/Users/myuser/PycharmProjects/myproject/folder/main.py", line 8, in <module>
>     import discord
>   File "/virtunenv/lib/python3.5/site-packages/discord/__init__.py", line 20, in <module>
>     from .client import Client, AppInfo, ChannelPermissions
>   File "/virtunenv/lib/python3.5/site-packages/discord/client.py", line 28, in <module>
>     from .user import User
>   File "/virtunenv/lib/python3.5/site-packages/discord/user.py", line 27, in <module>
>     from .utils import snowflake_time
>   File "/virtunenv/lib/python3.5/site-packages/discord/utils.py", line 31, in <module>
>     import asyncio
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/__init__.py", line 21, in <module>
>     from .base_events import *
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 17, in <module>
>     import concurrent.futures
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/concurrent/futures/__init__.py", line 8, in <module>
>     from concurrent.futures._base import (FIRST_COMPLETED,
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/concurrent/futures/_base.py", line 42, in <module>
>     LOGGER = logging.getLogger("concurrent.futures")
> AttributeError: module 'logging' has no attribute 'getLogger

**Comment by Rapptz** [comment]
You probably have a file named `logging.py`, or a folder. Don't.
