### ISSUE TITLE
Login as me and not as a bot

### ISSUE THREAD

**Issue by SakiiR** [Rapptz/discord.py#918]
Is it possible via this module to connect as a user and not as a bot ?

If yes, what kind of token i've to send ? the oauth token or the browser local storage token ?

Thanks, great package btw (for bots at least).

**Comment by marios8543** [comment]
http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.login
`await client.login('email', 'password')`
Bear in mind that botting user accounts will get your account terminated

**Comment by SakiiR** [comment]
The goal is to make a plugin for weechat, people will use this with their accounts.

What do you mean by terminated ?

**Comment by marios8543** [comment]
then i don't think you will have any problems. account termination may occur if you create bots that appear as normal users instead of bot users

**Comment by SakiiR** [comment]
```sh
 $ python /tmp/lol.py                                                                                                                                                                 
  File "/tmp/lol.py", line 21
    await client.login(EMAIL, PASSWORD)
               ^
SyntaxError: invalid syntax
```

```sh
$ python --version
Python 3.6.2
```

**Comment by SakiiR** [comment]
@marios8543 Okay I see now :)

**Comment by Ikusaba-san** [comment]
Just specify `bot=False` in `client.run`. Don't pass your email and password because that's not allowed (deprecated a while ago).

Do note that user-bots and self-bots are against ToS so use them at your own risk.

(for the record, `await` can only be used inside `async def`)

**Comment by SakiiR** [comment]
Great, ty !

Working with this snippet:

```python
#!/usr/bin/env python


import discord
import asyncio

TOKEN_AUTH = "YOUR TOKEN"

client = discord.Client()

@client.event
async def on_ready():
    print(client.servers)

client.run(TOKEN_AUTH, bot=False)


```

**Comment by SakiiR** [comment]
The project is finished ! :')

Weechat don't support python3 so I can't use asyncio for my plugin :(

**Comment by SakiiR** [comment]
it supports it only for tests, and may be unstable with other plugins

**Comment by codyle61** [comment]
> http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.login
> `await client.login('email', 'password')`
> Bear in mind that botting user accounts will get your account terminated

Will my account be terminated if I write a program to say things on my behalf whenever I run it?

**Comment by 0xlgs** [comment]
@codyle61: Yep, that's the definition of self botting, and it's against the ToS.

**Comment by Vexs** [comment]
It's against ToS but it isn't an instant-ban feature. Further, it's presently broken without some adjustments due to a change on the API side.

**Comment by JackTheRipper1806** [comment]
@Vexs Care to inform me about the changes I'd need to make? Currently setting up some selfbot shit. And I really don't care if I'm violating TOS.

**Comment by JDLanyon** [comment]
Would that definition of self boting mean macros and such are self boting? I used to use AHK for phrases I'd type often or to assist me when explaining something (also for dumb ascii messages and such)

**Comment by CTRL-ALT-EXIST** [comment]
Do you mean if you type 'idk' your self-bot will auto correct to 'I Dont Know' once the message is sent?

**Comment by Harmon758** [comment]
Please don't necro-bump old closed issues.
Self-bots on [user accounts](https://discordapp.com/developers/docs/topics/oauth2#bot-vs-user-accounts) [are indeed forbidden now](https://support.discordapp.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-).
For further information and clarification, you should [contact Discord Support](https://support.discord.com/hc/en-us/requests/new).

**Comment by MutantRabbit767** [comment]
is python the only way you can selfbot now?

**Comment by SebbyLaw** [comment]
@MutantRabbit767 Please don't necrobump old issues.

GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python, and certainly not for requesting help with userbots as they are [against TOS](https://support.discordapp.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-).

For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by HarshTheGod** [comment]
can do anything like messaging

**Comment by BreakDee** [comment]
how to like leave a server as the user?

**Comment by XuaTheGrate** [comment]
@BreakDee Please don't necrobump old issues.

GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python, and certainly not for requesting help with userbots as they are [against TOS](https://support.discordapp.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-).

For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.
