### ISSUE TITLE
I cannot run my bot.

### ISSUE THREAD

**Issue by DCAus-code** [Rapptz/discord.py#9181]
### Summary

The new update is causing this error. discord.ext.commands.errors.ExtensionNotFound: Extension 'cogs.cog_example' could not be loaded.

### Reproduction Steps

I tried to import cogs.cogs_example. discord.ext.commands.errors.ExtensionNotFound: Extension 'cogs.cog_example' could not be loaded.

### Minimal Reproducible Code

```python
extensions = ['cogs.cog_example', 'cogs.other_cog']
async def load_extensions():
    for extension in extensions:
        await bot.load_extension(extension)

if __name__ == '__main__':  # Ensures this is the file being ran
    loop = asyncio.get_event_loop()
    loop.run_until_complete(load_extensions())
    loop.run_until_complete(bot.start('TOKEN'))
```

### Expected Results

the bot to run

### Actual Results

discord.ext.commands.errors.ExtensionNotFound: Extension 'cogs.cog_example' could not be loaded.

### Intents

intents = discord.Intents.default() intents.messages = True bot = commands.Bot(command_prefix='/', intents=intents)

### System Information

- Python v3.9.2-final
- discord.py v2.2.0-alpha
    - discord.py metadata: v2.2.0a0
- aiohttp v3.7.4.post0
- system info: Linux 5.10.147-20158-g0a75306e5639 #1 SMP PREEMPT Sun Nov 27 20:52:05 PST 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
That exception is raised by the library when something in your code raises an error during loading. You're suppressing the chained exception so it's not possible to provide more help. For help with the library please go to [the official server instead](https://discord.gg/dpy).
