### ISSUE TITLE
How do I add arguments to commands

### ISSUE THREAD

**Issue by THEWHITEBOY503** [Rapptz/discord.py#919]
So right now I am attempting to add commands to kick and ban people from servers (in other words, moderation tools.) I have no idea how to add arguments to commands. Like -kick @ user. Right now my commands all start with    `elif message.content.startswith('command name')`

**Comment by Vexs** [comment]
Use the commands ext, it makes this way easy. [Here's](http://discordpy.readthedocs.io/en/rewrite/ext/commands/api.html) the docs for the rewrite version, on async it's only documented in docstrings in the source. [Here's an example](https://gist.github.com/leovoel/46cd89ed6a8f41fd09c5) for the async branch.

**Comment by THEWHITEBOY503** [comment]
This doesn't make too much sense to me. Do I need to import discord.ext and use the ``class discord.ext.commands.Bot(beta_argtest, formatter=None, description=None, pm_help=False, **options)¶``

**Comment by Vexs** [comment]
commands.bot is discord.client but with a command handler attached. So if I wanted to do your aforementioned kick command I would do 

`bot = commands.Bot(command_prefix='?')

@bot.command(pass_context=True)
@commands.has_permissions(kick_members=True) 
async def kick(ctx, member:discord.Member):
    await bot.kick(member)`

What this does is create an instance of the bot class, and creates a command called "kick" with a context object as it's first arg (contains the message that triggered the command along with some other stuff) and a converter that converts the argument (like in "?kick @someone", @someone is the arg) to a member object. It then kicks them. The `@commands.has_permissions(kick_members=True)` is a decorator called a check that will prevent anyone who doesn't have that permission from running the command.

If you start using the commands ext you *completely remove* discord.Client() and replace it with commands.Bot(), as commands.Bot does everything discord.Client does and more. 

So if you had 
`mybot = discord.Client()`
You would replace with 
`mybot = commands.Bot(prefix=something)`

**Comment by THEWHITEBOY503** [comment]
ok I swapped out my discord.Client() for commands.Bot(prefix='beta_). So I just add `@bot.command(pass_context=True)
@commands.has_permissions(kick_members=True)
async def kick(ctx, member:discord.Member):
await bot.kick(member)`?

**Comment by THEWHITEBOY503** [comment]
Traceback (most recent call last):
  File "beta.py", line 12, in <module>
    client = commands.Bot(command_prefix='beta_')
NameError: name 'commands' is not defined

**Comment by Vexs** [comment]
You need to import it. 

`from discord.ext import commands`

I highly highly highly recommend porting your commands to commands ext. You should also join the discord for d.py, probably get better support there for simple stuff like this.  https://discord.gg/r3sSKJJ

**Comment by THEWHITEBOY503** [comment]
I got everything "working"

It's not seeing the command when I run it **I think**

**Comment by Kyousei** [comment]
The `kick` command already exists. Read the last line. 🤔

**Comment by mikevb1** [comment]
You shouldn't be adding commands in `on_message`. Define them outside and remove `on_message` entirely or add `bot.process_commands(message)` to the end of it.
