### ISSUE TITLE
Instructions to use `py -3` command in Windows cause virtualenv to be ignored

### ISSUE THREAD

**Issue by marcospgp** [Rapptz/discord.py#9194]
### Summary

Instructions to use `py -3` command in Windows cause virtualenv to be ignored. `py` without `-3` does not ignore virtualenv.

### Reproduction Steps

Followed instructions in documentation.

### Expected Results

Use virtualenv

### Actual Results

Virtualenv ignored

### Intents

None

### System Information

discord.py v2.1.0-final

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

`py --list` outputs:

```
  *               Active venv
 -V:3.11          Python 3.11 (64-bit)
```

To my best understanding, Windows users should be instructed to run commands with `py` and not `py -3`.

As of now, [instructions regarding setting up a virtual environment](https://discordpy.readthedocs.io/en/stable/intro.html#virtual-environments) have no effect.

**Comment by marcospgp** [comment]
`py --list` outputs:

```
  *               Active venv
 -V:3.11          Python 3.11 (64-bit)
```

**Comment by AbstractUmbra** [comment]
I believe a step was missed here, sorry?

The documentation you linked shows that you must "activate" your venv once it has been create.
This is typically done like:-
`bot-env\Scripts\activate.bat` (or the PowerShell `.ps1` file if you use PS over cmd).

This activation changes your local PATH to include the venv's binary folder. Meaning shortcuts like `python` and `pip` will work.

After activation you issue a `python bot.py` as normal.

**Comment by marcospgp** [comment]
Yes, the venv is active (this is done by default when opening the terminal in vscode).

`python` and `pip` will reference the venv correctly. `py` by itself will, as well. But `py -3` will run in the global environment.

Someone following the [virtual environments](https://discordpy.readthedocs.io/en/stable/intro.html#virtual-environments) instructions will not be able to run the [minimal bot example](https://discordpy.readthedocs.io/en/stable/quickstart.html#a-minimal-bot) with the given command.

I don't see this as an error, it could just be clearer. The quickest fix would be to change `py -3` in instructions to just `py`.

**Comment by AbstractUmbra** [comment]
If I'm not mistaken.. nowhere in the Virtual Environment documentation does it say to use `py -3`. Are you inheriting this from the section above?

**Comment by marcospgp** [comment]
Neither does it say not to use it. While you are technically correct, shouldn't documentation strive to be helpful?

**Comment by Rapptz** [comment]
The minimal tutorial is just meant to be a small one to get you up to and running, which is why it uses the Linux commands which are more common for a server where your bot is likely located.

I have no intention of making a larger tutorial or expanding the scope of it. I already link to the tutorial in the official Python docs if someone wants more info.

Since the original issue points to something that doesn't exist (I don't instruct `py -3` in the venv docs), I'm going to close it.

**Comment by marcospgp** [comment]
Please consider this humble PR that adds this info to the docs. I truly believe it to be an important issue as it is a relatively silent issue that will cause many to mistakenly assume they are making correct use of virtualenvs in their local dev environment.

https://github.com/Rapptz/discord.py/pull/9196
