### ISSUE TITLE
Handle custom emojis in Message.clean_content

### ISSUE THREAD

**Issue by Rapptz** [Rapptz/discord.py#92]
The format seems to be.. `<:emoji_name:emoji_id>`. I suppose transforming these into `:emoji_name:` is a good call.

**Comment by Rapptz** [comment]
This isn't gonna happen.

**Comment by PikalaxALT** [comment]
Petition to reopen this?  Would be nice for the discord.py backend to handle this so that I don't have to.

**Comment by Acituanbus** [comment]
Yes please!
