### ISSUE TITLE
Self is a required arugment that is missing?

### ISSUE THREAD

**Issue by Jakobohrnell** [Rapptz/discord.py#920]
I did my best with the title, but not quite sure what to name the post really. 

I run this code:

```
from discord.ext import commands

bot = commands.Bot(command_prefix='!', description="Derp")

class Test:
    def __init__(self):
        self.test = "foobar"

    @bot.command()
    async def test(self):
        await bot.say(self.test)

    bot.run("token")
```

And when I trigger the test command by typing !test into Discord it spits out this error:

```
Ignoring exception in command test
Traceback (most recent call last):
  File "D:\Program\Python\lib\site-packages\discord\ext\commands\bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "D:\Program\Python\lib\site-packages\discord\ext\commands\core.py", line 367, in invoke
    yield from self.prepare(ctx)
  File "D:\Program\Python\lib\site-packages\discord\ext\commands\core.py", line 345, in prepare
    yield from self._parse_arguments(ctx)
  File "D:\Program\Python\lib\site-packages\discord\ext\commands\core.py", line 304, in _parse_arguments
    transformed = yield from self.transform(ctx, param)
  File "D:\Program\Python\lib\site-packages\discord\ext\commands\core.py", line 212, in transform
    raise MissingRequiredArgument('{0.name} is a required argument that is missing.'.format(param))
discord.ext.commands.errors.MissingRequiredArgument: self is a required argument that is missing.
```

I'm passing self into the test function, so I'm not quite sure what the issue is. I've tried googling and looking into the files, but being quite noobish I can't make sense of any of it.

Also, the link to the unoffcial Discord API channel is expired.

**Comment by NCPlayz** [comment]
I believe what you are trying to do is use cogs. Click [here](https://gist.github.com/leovoel/46cd89ed6a8f41fd09c5) to view leovel's example of how to use cogs. These can be added in the same file and can be seen in the [playlist example](https://github.com/Rapptz/discord.py/blob/async/examples/playlist.py).

**Comment by SourSpoon** [comment]
I don't think this one is a cog issue. @NCPlayz.

Unlike many other programming languages it's not the norm to put everything in a class in python.

removing your test class and making your code more simple to
```py
from discord.ext import commands

bot = commands.Bot(command_prefix='!')

@bot.command()
async def test():
    await bot.say('foobar')

bot.run(token)
``` will make it work

**Comment by Jakobohrnell** [comment]
@SourSpoon I am aware I can do this little example without a class. But I can't seem to figure out how to pass around objects between the diffrent commands without using a class. I can't do something like

`@bot.command()
foo = async def bar():
    return "Hello"`

cause then it throws a fit.

**Comment by SourSpoon** [comment]
What are you trying to accomplish? because that isn't valid python.

**Comment by Jakobohrnell** [comment]
```
@bot.command()
async def join():
    channel = bot.get_channel("foobar")
    voice = await bot.join_voice_channel(channel)

@bot.command()
async def play():
    player = voice.create_ffmpeg_player(filename="some song)
    player.start()
```
Is what I'm trying to do. But the voice variable is not available to the play function. The player variable isn't available either for that matter.

**Comment by fourjr** [comment]
Join https://discord.gg/r3sSKJJ for the help support server.

**Comment by NCPlayz** [comment]
in `play()`, you can do:

```py
state = bot.get_voice_state(ctx.message.server)
player = state.create_ffmpeg_player(name='!')
```
as shown on [the playlist example](https://github.com/Rapptz/discord.py/blob/async/examples/playlist.py#L133)
