### ISSUE TITLE
ScheduledEvent.creator always None because Gateway does not provide it

### ISSUE THREAD

**Issue by Kejax** [Rapptz/discord.py#9201]
### Summary

creator is always None, although it seems like the api does not provide it everytime

### Reproduction Steps

used `creator` attribute of `ScheduledEvent`

### Minimal Reproducible Code

```python
@client.event
async def on_scheduled_event_create(event):
    creator = event.creator
```

### Expected Results

User object representing the creator of the event

### Actual Results

event.creator is None

### Intents

discord.Intents.all()

### System Information

- Python v3.11.1-final
- discord.py v2.1.0-final
- aiohttp v3.8.3
- system info: Windows 10 10.0.22621

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

According to an issue on this at the discord-api-docs on github, the creator field isnt always present but creator_id is

**Comment by AbstractUmbra** [comment]
I believe it is a touch hasty to say it is *never* sent. The [API docs](https://discord.com/developers/docs/resources/guild-scheduled-event) say the `owner` key is an optional key of a User type.

However we apparently do get the `creator_id` key (which does have a note saying it will not exist for events that existed before 25/09/2021).

It may be feasible to try and fall back to a cache lookup via the `creator_id` key if the `creator` key is not present.

**Comment by Kejax** [comment]
Tbh, I accedentally wrote that its always None, I meant most times. 
My fault

**Comment by Rapptz** [comment]
I can't do much about `ScheduledEvent.creator` being `None` since that comes directly from Discord. However, I've added `creator_id` and also added a second layer of cache lookup in-case Discord does not provide it.
