### ISSUE TITLE
The `on_command_error` method doesn't provide the error's traceback when used on a hybrid command.

### ISSUE THREAD

**Issue by Kyrela** [Rapptz/discord.py#9205]
### Summary

The `on_command_error` method doesn't provide the error's traceback when used on a hybrid command.

### Reproduction Steps

1. Define an hybrid command that raise an error.
2. Define an `on_command_error` event that prints the traceback of the given error.
3. Run the bot
4. Use the defined hybrid command as a slash command.

### Minimal Reproducible Code

```python
import discord
from discord.ext import commands

bot = commands.Bot(command_prefix="!", intents=discord.Intents.all())

@bot.hybrid_command()
async def crash(ctx):
    raise Exception("crash")


@bot.event
async def on_command_error(ctx, error):
    print(error)
    print(error.__traceback__)
    print("-" * 20)


@bot.event
async def on_ready():
    await bot.tree.sync()

bot.run("TOKEN")
```

### Expected Results

When using the hybrid command as a slash command, the traceback should be present in `error.__traceback__`.

### Actual Results

`error.__traceback__` is set to `None`

### Intents

Intents.all()

### System Information

- Python v3.11.1-final
- discord.py v2.1.0-final
- aiohttp v3.8.3
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Here's the result of the code snippet after triggering the command as a message, then as a slash command :

```
Command raised an exception: Exception: crash
<traceback object at 0x000001DA0EC0EC00>
--------------------
Hybrid command raised an error: Command 'crash' raised an exception: Exception: crash
None
--------------------
```

However, please not that the `logging` module is capable of displaying the full traceback without any problem. Here's the related code snippet (just replace the `on_command_error` method of the previous snippet by this one)

```py
@bot.event
async def on_command_error(ctx, error):
    print(error)
    print(error.__traceback__)
    import logging
    _logger = logging.getLogger(__name__.split(".")[0])
    _logger.error("error", exc_info=error)
    print("-" * 20)
```

**Comment by Rapptz** [comment]
Thanks. Good catch.

The traceback information is now added as well. I wasn't sure if this was automatically set when you called `__cause__` since that's how `raise ... from` works but it seems like it didn't. Do note that this exception is *synthetic*. It's not actually raised, so it doesn't actually have a traceback (as seen here). It's merely fabricated.
