### ISSUE TITLE
App Command Parameter Types aren't checked by discord.py

### ISSUE THREAD

**Issue by RainerZufall187** [Rapptz/discord.py#9214]
### Summary

hmmm discord.py not checking type of app command parameter

### Reproduction Steps

Sync with ``async def add(interaction: discord.Interaction, first_value: str, second_value: str):`` then change it in your code to without syncing ``async def add(interaction: discord.Interaction, first_value: int, second_value: int):``

### Minimal Reproducible Code

```python
@client.tree.command()
@app_commands.describe(first_value='The first value you want to add something to',
                       second_value='The value you want to add to the first value', )
async def add(interaction: discord.Interaction, first_value: int, second_value: int):
    await interaction.response.send_message(f'{first_value} + {second_value} = {first_value + second_value}')
```

### Expected Results

I expect that discord.py checks the types of the parameters from Discord and not just straight uses them. The same applies for Range. I think that this is why typing exists in the first place.

### Actual Results

My Client just takes the parameters from discord.

### Intents

discord.Intents.all()

### System Information

- Python v3.10.9-final
- discord.py v2.2.0-alpha
    - discord.py metadata: v2.2.0a4679+g24495e55
- aiohttp v3.8.3
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

no ok

**Comment by Rapptz** [comment]
I'm not sure what you expect me to check here. The type annotations are there to create a DSL for the command types. If you're changing the definition without syncing then obviously it's not going to be used. I'm not going to incur overhear of type checking in this case since you're responsible for syncing.
