### ISSUE TITLE
Silent Error when using send_message() after using .defer()

### ISSUE THREAD

**Issue by Notenlish** [Rapptz/discord.py#9224]
### Summary

Not raising an exception when using interaction.response.send_message() after having used interaction.response.defer()

### Reproduction Steps

Create a bot with this command, and use the /test1 command

### Minimal Reproducible Code
```python
import discord
from discord import app_commands
from discord.ext import commands
import logging
import requests

handler = logging.FileHandler(filename="bot.log")
SECRET_BOT_KEY = "secret_key"

intents = discord.Intents.default()
intents.message_content = True
description = ""

class MyClient(discord.Client):
    async def on_ready(self):
        print(f'Logged on as {self.user}!')
        await tree.sync(guild=None)
client = MyClient(intents=intents)
tree = app_commands.CommandTree(client)
bot = commands.Bot(command_prefix='/', description=description, intents=intents)

@tree.command(name = "test1", description = "")
async def test1(interaction: discord.Interaction, message: str = None):
    print("Start")
    await interaction.response.defer()
    print("Sent defer ")
    await interaction.response.send_message("Done")
    print("Done")

client.run(token=SECRET_BOT_KEY, log_handler=handler, log_level=logging.DEBUG)
```
### Expected Results

On the terminal:
    Start 
    Sent defer
    Done

On discord:
    Bot to respond to me with: "Done"

### Actual Results

On the terminal:
    Start
    Sent defer

On discord:
    It's showing that the bot is thinking.

The code just kept on waiting and couldn't reach the end of the function. I didn't know that I was supposed to use interaction.followup.send(). I think the module should raise an exception or warn the user.

### Intents

intents = discord.Intents.default()
intents.message_content = True

### System Information
- Python v3.10.6-final
- discord.py v2.1.0-final
- aiohttp v3.8.3
- system info: Linux 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023

### Checklist

- [X] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
You're using two clients for some reason. Regardless, this does raise an error due to responding twice. It should call the CommandTree.on_error method.

**Comment by Notenlish** [comment]
Oh thanks! I was trying to get slash commands to work and I thought you had to create both the bot and the client.
