### ISSUE TITLE
Server Profile

### ISSUE THREAD

**Issue by e1pupper** [Rapptz/discord.py#9236]
### Summary

Some kind of way to change the profile picture for each server

### What is the feature request for?

The core library

### The Problem

It would be a nice feature to implement so that people in there own servers can set profile pictures of a bot using a command developed by the bot. This would allow bot's to be more monetizeable while also making xyz server look more professional.

### The Ideal Solution

There is already server profiles for normal discord users so I can only imagine that you can do the same thing for the bots if discord allows it. 

Currently I know you can change your own bot's pfp like this:
```py
# client being the bot
with open('image.png', 'rb') as image:
    await client.user.edit(avatar=image.read())
```

but it would be interesting if the user can forexample pass a image as a parameter in a command
```py
@commands.command(name='profile')
async def profile(self, ctx: Context, message: Message):
    guild = ctx.guild.id
    await self.client.user.edit(guild= guild, avatar=message.attachments[0].url)
```

### The Current Solution

There is no solution at the moment(that im aware of) and no way to go around it really.

**Comment by Rapptz** [comment]
Unfortunately, Discord doesn't support this feature for bots.
