### ISSUE TITLE
How can I adapt this to make it unban a user from the getbans list?

### ISSUE THREAD

**Issue by AMZ4H** [Rapptz/discord.py#924]
@bot.command(pass_context = True)
async def unban(ctx, *, member : discord.Member = None):
    if not ctx.message.author.server_permissions.administrator:
        return
 
    if not member:
        return await bot.say(ctx.message.author.mention + "Specify a user to unban!")
    try:
        await bot.unban(member)
    except Exception as e:
        if 'Privilege is too low' in str(e):
            return await bot.say(":x: You cant use this command!")
 
    embed = discord.Embed(description = "**%s** has been unbanned!"%member.name, color = 0xFF0000)
    return await bot.say(embed = embed)

@bot.command(pass_context = True)
async def getbans(ctx):
    x = await bot.get_bans(ctx.message.server)
    x = '\n'.join([y.name for y in x])
    embed = discord.Embed(title = "List of Banned Members", description = x, color = 0xFFFFF)
    return await bot.say(embed = embed)

**Comment by AMZ4H** [comment]
These are my two commands and I want the unban command to be able to unban somebody from the ban list help me please.. Im really new to discord.py

**Comment by s0hvaperuna** [comment]
```py
@bot.command(pass_context=True)
async def unban(ctx, *, member):
    server = ctx.message.server
    bans = await bot.get_bans(server)
    try:
        # First we'll try matching with the exact user id
        uid = int(name)
        matches = list(filter(lambda u: u.id == uid, bans))
        if not matches:
            return await bot.say('no users ids matched with %s' % uid)
        _member = matches[0]

    except ValueError:
        # If the provided string isn't an id we'll try to get an exact match on a user from the bans list
        # The member string needs to be exactly the same as the users name + discrim combo like this Testuser#7777
        matches = list(filter(lambda u: str(u) == member, bans))
        if not matches:
            return await bot.say('no users matched with %s' % member)
        _member = matches[0]
    try:
        await bot.unban(ctx.message.server, _member )
    except:
        # Do your stuff
```
and in get_bans change 
```py
x = '\n'.join([y.name for y in x])
```
to 
```py
x = '\n'.join([str(y) for y in x])
```
so you'll get the correct name to match in unban
I haven't tested this but it should help give some general direction

**Comment by palmtree5** [comment]
`uid = int(name)`

`NameError: name 'name' is not defined` 
@s0hvaperuna

**Comment by s0hvaperuna** [comment]
corrected it to `member` as it should have been from the start

**Comment by AMZ4H** [comment]
Nevermind I found it.. Thanks alot for your help guys! I really needed it! :)
