### ISSUE TITLE
`Bot.get_command` gets the wrong command for command with group named the same as a command without group but alias

### ISSUE THREAD

**Issue by Kile** [Rapptz/discord.py#9243]
### Summary

Using `Bot.get_command` with a string that includes an alias of another command

### Reproduction Steps

I have one command in a GroupCog named `img`, having an alias called `image`. I also have a GroupCog called `image`. One of the commands included in said cog is `emojaic`. If I was to use
```py
_bot.get_command("image emojaic")
```
with jishaku it would return "img" as it somehow takes the first part of that string and finds a command with an alias of "image".

### Minimal Reproducible Code

```python
# One cog with 
class Cog1(commands.CogGroup, group_name="image")
    @commands.hybrid_command
    async def emojaic(self, ctx):
        ...

# Then another one which is
class Cog2(commands.CogGroup, group_name="some_group")
     @commands.hybrid_command(aliases=["image"]):
     async def img(self, ctx):
         ...

# Then as described above try to find `image emojaic` using jishaku
```

### Expected Results

Given that the whole command name, `image emojaic` is given, maybe it should work from the back to the front, searching for emojaic first instead of `image` and then return the first result which is `image emojaic`

### Actual Results

It returns an instance of the `<group> img` command

### Intents

all

### System Information

- Python v3.9.6-final
- discord.py v2.0.1-final
- aiohttp v3.8.3
- system info: Darwin 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Not 100% sure if this is a bug or an inconvenience but I'd be happy if it was somehow fixed while I have to create a wacky workaround in the meantime

**Comment by Rapptz** [comment]
The way `CogGroup` works is that it only affects the representation in an app command context, so despite you having `/image emojaic` the hybrid command only makes a text command named `[p]emojaic` so as far as I can tell this behaviour is as designed.
