### ISSUE TITLE
How can I create case logs using this code? Im really new to discord.py sorry xD

### ISSUE THREAD

**Issue by AMZ4H** [Rapptz/discord.py#926]
import discord
import random
from discord.ext import commands
from discord.ext.commands import Bot
import asyncio

bot = commands.Bot(command_prefix='!!')

@bot.event
async def on_ready():
    print("Bot Online!")
    print("Name: {}".format(bot.user.name))
    print("ID: {}".format(bot.user.id))
    await bot.change_presence(game=discord.Game(name='type !!help'))
    
    

@bot.command(pass_context=True)       
async def purge(ctx, number):
    mgs = []
    number = int(number)
    async for x in bot.logs_from(ctx.message.channel, limit = number):
        mgs.append(x)
    await bot.delete_messages(mgs)

@bot.command(pass_context=True)
async def ping(ctx):
    await bot.say("pong")
    print ("user has pinged")

@bot.command(pass_context=True)
async def flip(ctx):
    hot=random.randint(0,1)
    if hot == 0:
        await bot.say("Heads")
        hot=random.randint(0,1)
    else:
        await bot.say("Tails")
        hot=random.randint(0,1)

    

@bot.command(pass_context = True)
async def kick(ctx, *, member : discord.Member = None):
    if not ctx.message.author.server_permissions.administrator:
        return
 
    if not member:
        return await bot.say(ctx.message.author.mention + "Specify a user to kick!")
    try:
        await bot.kick(member)
    except Exception as e:
        if 'Privilege is too low' in str(e):
            return await bot.say(":x: Privilege too low!")
 
    embed = discord.Embed(description = "**%s** has been kicked!"%member.name, color = 0xFF0000)
    return await bot.say(embed = embed)

@bot.command(pass_context = True)
async def ban(ctx, *, member : discord.Member = None):
    if not ctx.message.author.server_permissions.administrator:
        return
 
    if not member:
        return await bot.say(ctx.message.author.mention + "Specify a user to ban!")
    try:
        await bot.ban(member)
    except Exception as e:
        if 'Privilege is too low' in str(e):
            return await bot.say(":x: Privilege too low!")
 
    embed = discord.Embed(description = "**%s** has been Banned!"%member.name, color = 0xFF0000)
    return await bot.say(embed = embed)

@bot.command(pass_context=True)
async def info(ctx, user: discord.Member):
    await bot.say("The users name is: {}".format(user.name))
    await bot.say("The users ID is: {}".format(user.id))
    await bot.say("The users status is: {}".format(user.status))
    await bot.say("The users highest role is: {}".format(user.top_role))
    await bot.say("The user joined at: {}".format(user.joined_at))

@bot.command(pass_context = True)
async def getbans(ctx):
    x = await bot.get_bans(ctx.message.server)
    x = '\n'.join([str(y) for y in x])
    embed = discord.Embed(title = "List of Banned Members", description = x, color = 0xFFFFF)
    return await bot.say(embed = embed)

@bot.command(pass_context=True)
async def unban(ctx, *, member):
    server = ctx.message.server
    bans = await bot.get_bans(server)
    try:
        uid = int(member)
        matches = list(filter(lambda u: u.id == uid, bans))
        if not matches:
            return await bot.say('no users ids matched with %s' % uid)
        _member = matches[0]

    except ValueError:
        matches = list(filter(lambda u: str(u) == member, bans))
        if not matches:
            return await bot.say('no users matched with %s' % member)
        _member = matches[0]
    try:
        await bot.unban(ctx.message.server, _member )
    except:
        return

bot.run("MYTOKENGOESHERE")

**Comment by Rapptz** [comment]
This is not the place to ask for code. This is for issues with the library.
