### ISSUE TITLE
Inconsistent ChannelType values

### ISSUE THREAD

**Issue by YoniFei** [Rapptz/discord.py#927]
**Issue:** When checking _channel.type_ , some channels(text, voice channels) return an ENUM, while others return an int (category channels)
I don't think this inconsistency is by design.

**Exact context/reproduce:** Getting a list of channels via _Server.channels_ , then checking _channel.type_

**Current result:** Category channels _.type_ are returning 4(int). Text and Voice return proper ENUM

**Desired result:** All cases return an ENUM?

This issue is a mild inconvenience. Unfortunately I will only be able to look into/fix this in 2 weeks.

**Comment by YoniFei** [comment]
After 1 minute of looking at the code from my phone, just need to add category = 4 to ChannelType.

**Comment by diceroll123** [comment]
This is included in rewrite. *upgrade tbh*

**Comment by YoniFei** [comment]
My bad, sorry
