### ISSUE TITLE
Can't connect to a VC. `discord.gateway.DiscordVoiceWebSocket.initial_connection` call never returns.

### ISSUE THREAD

**Issue by timotheyca** [Rapptz/discord.py#9277]
### Summary

`initial_connection` method coroutine never returns resulting in failing to connect to a VC

### Reproduction Steps

Call and await `connect()` on an instance of `VoiceChannel`.
Details on getting an instance of `VoiceChannel` (all checks are skipped for clarity):
```py
member = message.author
voice_state = member.voice
voice_channel = voice_state.channel
voice_client = await voice_channel.connect()  # this breaks
```

### Expected Results

Call to `connect` returns or raises an error.

### Actual Results

Call to `connect` never returns. It appears to be stuck on `discord.gateway.DiscordVoiceWebSocket.initial_connection`, specifically `recv = await self.loop.sock_recv(state.socket, 70)` line.
Seems to happen to other bots too (so, not only "my machine" situation).
No traceback (no errors; the method just doesn't return).

### Intents

discord.Intents.all()

### System Information

```
- Python v3.10.6-final
- discord.py v2.2.0-final
- aiohttp v3.8.4
- system info: Linux 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022
```
Running in docker (`FROM python:3.10`).
Happens both with `discord.py==2.2.0` and `discord.py==2.1.0`

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Error started being encountered between 6:38 and 13:45 UTC, March 1st.
Tested with three separate bot accounts and two separate machines.
I traced all `discord.gateway.DiscordVoiceWebSocket.initial_connection` calls. Appears that it only enters the coroutine.
`await self.loop.sock_recv(state.socket, 70)` is assumed to be the issue because the only other await (`await self.select_protocol(state.ip, state.port, mode)`) never enters the coroutine.

**Comment by MinnDevelopment** [comment]
I think we've identified the issue in JDA. It seems like the UDP discovery changed the response layout. You have to send 74 bytes instead of 70, and it used to reply with `[0, 1, 0, 70, ip, port]` and now replies with `[0, 1, 0, 70, port, ip]`. See my changes here:

https://github.com/DV8FromTheWorld/JDA/compare/fix/udp-discovery

**Comment by timotheyca** [comment]
Connection sometimes starts to work again after a restart.

**Comment by timotheyca** [comment]
I made a stupid patch just to get it to work
```py
async def initial_connection(self, data: dict[str, Any]) -> None:
    state = self._connection
    state.ssrc = data["ssrc"]
    state.voice_port = data["port"]
    state.endpoint_ip = data["ip"]

    packet = bytearray(74)
    struct.pack_into(">H", packet, 0, 1)  # 1 = Send
    struct.pack_into(">H", packet, 2, 70)  # 70 = Length
    struct.pack_into(">I", packet, 4, state.ssrc)
    state.socket.sendto(packet, (state.endpoint_ip, state.voice_port))
    recv = await self.loop.sock_recv(state.socket, 70)

    # the ip is ascii starting at the 4th byte and ending at the first null
    ip_start = 8
    ip_end = recv.index(0, ip_start)
    state.ip = recv[ip_start:ip_end].decode("ascii")

    state.port = struct.unpack_from(">H", recv, 6)[0]

    # there *should* always be at least one supported mode (xsalsa20_poly1305)
    modes = [mode for mode in data["modes"] if mode in self._connection.supported_modes]

    mode = modes[0]
    await self.select_protocol(state.ip, state.port, mode)


__import__("discord.gateway").gateway.DiscordVoiceWebSocket.initial_connection = initial_connection
```

**Comment by Jourdelune** [comment]
I have also seen that voice listen (not supported by discord.py I know) does not work now, discord doesn't send the audio flux.
