### ISSUE TITLE
No module named 'typing_extensions' on install

### ISSUE THREAD

**Issue by cloudwithax** [Rapptz/discord.py#9297]
### Summary

When installing discord.py on python 3.11, it says No module named 'typing_extensions

### Reproduction Steps

1. Install discord.py using `pip install discord.py[voice]` on Python 3.11

### Minimal Reproducible Code

```python
> `pip install discord.py[voice]`
> ...
>

File "/home/container/. local/1ib/python3.11/site-packages/discord/
types/voice.py", line 26, in <module>
from typing_extensions import NotRequired
ModuleNotFoundError: No module named 'typing_extensions
```
```


### Expected Results

Discord.py should have handled the dependency install

### Actual Results

The dependency was missing and i had to manually install it.

### Intents

N/a

### System Information

- Python v3.11.2-final
- discord.py v2.2.2-final
- aiohttp v3.8.4
- system info: Linux 5.15.0-1029-oracle #35-Ubuntu SMP Tue Jan 24 15:21:05 UTC 2023

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

_No response_

**Comment by Rapptz** [comment]
The library does not use `typing_extensions` at runtime, therefore it should not be possible to hit this error. Your "minimal reproducible example" does not cause a repro for me, as the library installs just fine.

How are you getting this error?

**Comment by cloudwithax** [comment]
i have my own pterodactyl instance that im using as a glorified web viewer for my containers and im using my discord bot within that container. on run, it first installs all dependencies listed in a file called `requirements.txt`. in that file, theres a lavalink client, discord.py (the voice one) and a couple other things. when that install command runs, this is what happens:
![Screenshot_20230311-225901_Brave2](https://user-images.githubusercontent.com/71564480/224516885-18d0936b-db33-40eb-b48f-410eec4ed049.png)

**Comment by Rapptz** [comment]
This is a problem with the `pomice` dependency importing the private `discord.types` namespace which is meant to only be imported in a `TYPE_CHECKING` block and is *not* public interface. I suggest filing an issue there instead.

**Comment by CDWimmer** [comment]
I'm having this issue now but it's explicitly being called not by `pomice` but by `discord\types\embed.py`. Line 26 `from typing_extensions import NotRequired, Required`

**Comment by Rapptz** [comment]
Once again, that module is not meant to be imported by user code.

**Comment by CDWimmer** [comment]
I *thought* I wasn't importing such a thing to user code... 

Turns out I'd written `from discord.types.embed import EmbedType` somewhere for reasons known only to a particularly cruel god. Sorry for the disturbance.
