### ISSUE TITLE
playing message tweaks

### ISSUE THREAD

**Issue by OKEPlazmA** [Rapptz/discord.py#930]
How would i be able to have it automatically update to a playing message such as '-help | 26 Guilds' i have seen a few bots that have that and i know how to do it in JS just not Python

**Comment by SourSpoon** [comment]
create a background task, there is an [example](https://github.com/Rapptz/discord.py/blob/async/examples/background_task.py)

where you change your status using change_presence, as far as what data you want to include, that's up to you.

**Comment by EricGrant0709** [comment]
Please unsubscribe me from these threads.

Thank you

**Comment by ButterCheezii** [comment]
@EricGrant0709 Nobody here can do that. Please be smart and use the convenient button that controls whether you recieve messages for new issues.
![image](https://user-images.githubusercontent.com/22616762/33330802-b86999c2-d414-11e7-9387-339752ad8775.png)
