### ISSUE TITLE
Support for super reacts

### ISSUE THREAD

**Issue by HereComesTheMoon** [Rapptz/discord.py#9309]
### Summary

Support for super reactions.

### What is the feature request for?

The core library

### The Problem

Discord is apparently rolling out super reactions—11 days too early, according to some people. Super reacts are "animated" reactions with limited uses. Ordinary users can use two super reacts a week, nitro users have five per week.

Currently there seems to be no way to distinguish between ordinary and super reactions using discord.py, nor to use them. It'd be great if this functionality existed. So far (after a bit of personal testing) it appears that both super reacts and ordinary reacts are basically both seen as reacts. Super reacts also trigger the on_react_add listener, for example.

Also, a user cannot react and super react with the same emoji to a message at the same time.

### The Ideal Solution

Presumably it'd be desirable to either have a method on reacts, which tells you if this react is "super" or not, at the bare minimum. 

If bots are also capable of using super reacts (I don't see why not), then functionality for this is necessary, as well as some way of querying how many super reacts the bot currently has available. 

### The Current Solution

Afaik there is no current solution implemented, it's a new feature.

**Comment by Puncher1** [comment]
Apparently the API for this feature is quite unstable at the moment. The DDevs are working on a better solution, refer to: https://github.com/discord/discord-api-docs/pull/6056#issuecomment-1499767061

**Comment by jaxoncarelos** [comment]
Any update on this? DDevs are making more moves on it, and it is available in the payload under the name of Burst (if burst == true than its a super react). Just not available to us to use in our discordpy projects?

**Comment by amir32** [comment]
I've read through your feature request regarding support for super reactions on Discord, and I can see how this can be a valuable addition, especially for Discord bots and applications like the one I work on, the Pokémon Fusion Calculator.

Having the ability to distinguish between ordinary and super reactions would indeed be helpful for developers like us. It would open up exciting possibilities for enhancing user interactions.

As for your request for a method on reacts to determine if a react is "super" or not, that sounds like a logical and useful feature. It would allow us to adapt our bot's behavior accordingly.

If bots are allowed to use super reactions, which I believe they should be, then functionality for this is essential. Additionally, having a way to query the number of available super reacts for a bot would be valuable for monitoring and optimizing bot interactions.

I appreciate you raising this issue, and I hope Discord considers implementing these features soon.

By the way, if you're looking for a fun and interactive way to engage with your Discord community, you might want to check out our Pokémon Fusion Calculator at [FusionCalculator.com](https://fusioncalculator.com/). It's a fantastic tool for creating unique Pokémon fusions and adds a playful twist to your Discord conversations!

**Comment by Soheab** [comment]
Support for this was added in https://github.com/Rapptz/discord.py/commit/97ae6409b0a6bf46c43366d700610143f43a3343
