### ISSUE TITLE
No error returned, but process not completing when calling replace_roles.

### ISSUE THREAD

**Issue by nmedovich** [Rapptz/discord.py#932]
Hello, I'm in the process of building a mute feature for a bot.  I'm using the API available through pip on python3.6, for clarity.

I have the problem narrowed down to the area in which I replace the roles.  The user exists, and so does the 'Muted' role, however, upon calling `replace_roles(member, *roles)`, no error is thrown, but the roles are not replaced.  I have tried using `remove_roles` by iterating over the user's roles, but this did not work either.  I saw in another thread in the issues that one is supposed to use replace instead of remove in this  instance.

The flow of logic is as follows:
```
if message.content.startswith("..mute"):
    # For getting the user's ID, as the command is used with a mention of the user
    to_mute = message.content.split(" ")[1][2:-1]
    member = discord.utils.find(lambda member: member.id == to_mute, message.channel.server.members)
    if member is not None:
        role = discord.utils.find(lambda role: role.name == 'Muted', message.channel.server.roles)
        if role is not None:
            client.replace_roles(member, role)
            tmp = yield from client.send_message(message.channel, "User muted!")
```

At which point, if I iterate over `member.roles`, it still retains all the old roles, despite printing that the user was muted.  This will likely prove to be an issue later when I am writing in a self-assignable roles feature.  Is there an piece of syntax I am missing?

**Comment by BlackSynder** [comment]
replace_roles is a coroutine.

**Comment by nmedovich** [comment]
I am an idiot, I deeply apologize.  I'll test this in a moment.
