### ISSUE TITLE
Select dropdown with minimum of 0 cannot select 0 items on Discord browser and desktop app

### ISSUE THREAD

**Issue by Difio3333** [Rapptz/discord.py#9322]
### Summary

When using the Discord.py library to create a multiselect dropdown with a minimum selection of 0, users are unable to select 0 items when using the Discord desktop app or browser version.

### Reproduction Steps

1. Create a multiselect dropdown using the discord.ui.Select class with a minimum selection value of 0
2. Add the dropdown to a view and send it to a channel or user on Discord
3. Attempt to select 0 items in the dropdown while using the Discord desktop app or browser version

### Minimal Reproducible Code

```python
import discord

options = [
    discord.SelectOption(label='Option 1', value='1'),
    discord.SelectOption(label='Option 2', value='2'),
    discord.SelectOption(label='Option 3', value='3')
]

select = discord.ui.Select(
    placeholder='Select some options',
    min_values=0,
    max_values=len(options),
    options=options
)

view = discord.ui.View()
view.add_item(select)

# Code to send view to channel or user goes here
```

### Expected Results

Users should be able to select 0 items in the multiselect dropdown when using the Discord desktop app or browser version.

### Actual Results

When attempting to select 0 items in the multiselect dropdown while using the Discord desktop app or browser version, the dropdown does not allow any items to be selected, even though the minimum selection value is set to 0.

### Intents

No general permissions. All Text Permissions. No Voice Permissions

### System Information

- Python v3.9.5-final
- discord.py v2.0.0-final
- aiohttp v3.7.4.post0
- system info: Darwin 19.6.0 Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
This sounds like a Discord bug, the library has no control over this.
