### ISSUE TITLE
Add error messages when command checks fail from the predicate's docstring

### ISSUE THREAD

**Issue by ddjerqq** [Rapptz/discord.py#9327]
### Summary

Command checks will get their error messages from the check predicate function's docstring when they fail

### What is the feature request for?

discord.ext.commands

### The Problem

Currently there are a few ways to do this, but the most straight forward and implicit would be to allow the check functions' docstrings to be sent when a given command check fails.

### The Ideal Solution

Read the check's docstrings (if any) and send those to the interaction/context channel.
We could also allow the user to customize this feature more, by for example, letting them choose if the check errors will cascade or not, meaning if they will stop at the first check error, or continue propagating.

### The Current Solution

there are many, from making custom Exception subclasses, and raising them, to handling the error manually on respective events.

**Comment by ddjerqq** [comment]
```py
def is_admin(ctx: Ctx) -> bool:
    """You are not an administrator!"""
    ...
```

**Comment by izxxr** [comment]
This isn't a good design. Docstrings are simply not meant for these kind of uses. This will basically disallow the developers from using docstrings for what they are meant for i.e documenting functions. Apart from being a bad design, this will be an absurd breaking change too.

If you really want to implement something like this (which I won't recommend), you can do this yourself in your error handler.

**Comment by Rapptz** [comment]
This type of design isn't going to be supported, if you want custom error messages then raise an exception derived from `CommandError` with that string you prefer.
