### ISSUE TITLE
Random 404 errors

### ISSUE THREAD

**Issue by 2br-2b** [Rapptz/discord.py#9331]
### Summary

Sometimes, unresponded `interaction.response.send_message`s give a 404 error

### Reproduction Steps

This does not happen for a majority of the interactions, but has happened a few times over the past couple of days

1. Get an interaction via a slash command
2. Do processing of the slash command
3. Confirm that `not interaction.response.is_done()`
4. Attempt to run `interaction.response.send_message`
5. Receive:
```
Traceback (most recent call last):
  File "/home/foo/StoryBot/cogs/generic_discord.py", line 260, in reply_to_message
    return await interaction.response.send_message(embed=embed, view=view, ephemeral=ephemeral, file=file)
  File "/home/foo/.local/lib/python3.10/site-packages/discord/interactions.py", line 778, in send_message
    await adapter.create_interaction_response(
  File "/home/foo/.local/lib/python3.10/site-packages/discord/webhook/async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
```

6. See interaction failed message in Discord

### Minimal Reproducible Code

Here's the code for the command in the cog itself (the error happens on the last reported line):

https://github.com/2br-2b/StoryBot/blob/2b14dd9f9e68fcc25b25f1e22bb5df7f88c66c3c/cogs/dm_listener.py#L1131-L1153

Here's the relevant code for `self.discord_generic.reply_to_message` (`interaction` as used in these lines has already been properly set):

https://github.com/2br-2b/StoryBot/blob/2b14dd9f9e68fcc25b25f1e22bb5df7f88c66c3c/cogs/generic_discord.py#L250-L260

I can add clarification if any is needed, as I know my code isn't the best documented

### Expected Results

I expected the response to go thru as a reply to the interaction

### Actual Results

I received the aforementioned error, plus the command in Discord said that it wasn't responded to

### Intents

intents = discord.Intents.default(), intents.guilds = True

### System Information
```
- Python v3.10.6-final
- discord.py v2.2.2-final
- aiohttp v3.8.3
- system info: Linux 5.19.0-35-generic #36~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 17 15:17:25 UTC 2
```
### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Thank you so much for the work you put into Discord.py! It makes it so easy to make quick, fun Discord bots. I've been coding using discord.py for a few years now and it was one of the main reasons I kept enjoying coding in college over the past few years.

If you want me to run any additional troubleshooting, I'm more than happy to; however, this seems to happen to me randomly, so I don't know how long it'll take before it happens again. It happened twice over the past few days, and it's happened on different commands each time, so I don't believe that the specific command is the cause. In addition, if I re-run the command right afterwards, it will work fine the second time.

Also, the traceback may be a little incomplete as of right now (I messed up the error logging), but I will add a more complete traceback when I next get one

**Comment by staciax** [comment]
code 10062 is “ Unknown interaction” (https://discord.com/developers/docs/topics/opcodes-and-status-codes)

Are you sure that your app command is processed in less than 5 seconds?

**Comment by 2br-2b** [comment]
I believe the commands are completed in under 5 seconds, but if not, that could be causing the issue. If this is the case, then putting `await interaction.response.defer()` at the beginning should fix the issue, right?

While I can't confirm too many details (this instance happened to an unknown end user), the error showed up in a command which has `await interaction.response.defer(ephemeral=True)` at the very beginning. I don't know too much about this specific instance, but I was able to find the log. It was on a slightly different version of the bot (so the line numbers may be a bit off), but the defer for the interaction was in the code at the time.

<details>
<summary>Here's the error</summary>

```
Task exception was never retrieved
future: <Task finished name='CommandTree-invoker' coro=<CommandTree._from_interaction.<locals>.wrapper() done, defined at /home/foo/.local/lib/pytho
n3.10/site-packages/discord/app_commands/tree.py:1087> exception=CommandInvokeError("Command 'write' raised an exception: NotFound: 404 Not Found (err
or code: 10062): Unknown interaction")>
Traceback (most recent call last):
  File "/home/foo/.local/lib/python3.10/site-packages/discord/app_commands/commands.py", line 841, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "/home/foo/StoryBot/cogs/dm_listener.py", line 390, in add_to_story
    await self.discord_generic.reply_to_message(reply_to=reply_to, content="Got it!  Thanks!",ephemeral=True)
  File "/home/foo/StoryBot/cogs/generic_discord.py", line 260, in reply_to_message
    return await interaction.response.send_message(embed=embed, view=view, ephemeral=ephemeral, file=file)
  File "/home/foo/.local/lib/python3.10/site-packages/discord/interactions.py", line 778, in send_message
    await adapter.create_interaction_response(
  File "/home/foo/.local/lib/python3.10/site-packages/discord/webhook/async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/foo/.local/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1091, in wrapper
    await self._dispatch_error(interaction, e)
  File "/home/foo/.local/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1084, in _dispatch_error
    await self.on_error(interaction, error)
  File "/home/foo/StoryBot/main.py", line 98, in on_tree_error
    raise error
  File "/home/foo/.local/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1089, in wrapper
    await self._call(interaction)
  File "/home/foo/.local/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1252, in _call
    await self.on_error(interaction, e)
  File "/home/foo/StoryBot/main.py", line 98, in on_tree_error
    raise error
  File "/home/foo/.local/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/home/foo/.local/lib/python3.10/site-packages/discord/app_commands/commands.py", line 867, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "/home/foo/.local/lib/python3.10/site-packages/discord/app_commands/commands.py", line 860, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'write' raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction
```
</details>

The `/write` command's code (as of now) can be found here: https://github.com/2br-2b/StoryBot/blob/aabaab1b0c4f78a3c2a71e3e859018d2a25ccd1d/cogs/dm_listener.py#L357-L397

**Comment by staciax** [comment]
If you don't send it to  `discord_generic.reply_to_message`

you try to comment it  and then send the message without having to send it to that function

**Comment by 2br-2b** [comment]
I would have tried that, but my concern is that:
1) there are so many places the function is used in different ways (143 to be exact);
2) the function also splits messages which are too long and creates embeds is a specific way; and
3) the error happens so randomly at unknown places without warning;
that it would be difficult (though not infeasible) to replace all the instances of `reply_to_message` with the body of the method itself.

If there's no other troubleshooting steps to take that could help, I'm fine closing the issue for now; it could just be a fluke in my system, especially since I haven't seen anyone else reporting similar issues. If there are further troubleshooting steps I can put in place to catch more details of the error when it happens, however, I'm more than happy to help!

**Comment by MooshiMochi** [comment]
I get this error as well:

`
11|manga-bot  | [2023-04-06 22:28:06] [ERROR   ] bot: ⚠️ An unhandled error has occurred: Command 'ext_update_check' raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction - More details can be found in logs/error.log
11|manga-bot  | [2023-04-06 22:28:06] [ERROR   ] asyncio: Task exception was never retrieved
11|manga-bot  | future: <Task finished name='CommandTree-invoker' coro=<CommandTree._from_interaction.<locals>.wrapper() done, defined at /root/mooshi/ManhwaUpdatesBot/venv/lib/python3.11/site-packages/discord/app_commands/tree.py:1087> exception=NotFound('404 Not Found (error code: 10015): Unknown Webhook')>
11|manga-bot  | Traceback (most recent call last):
11|manga-bot  |   File "/root/mooshi/ManhwaUpdatesBot/venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 841, in _do_call
11|manga-bot  |     return await self._callback(self.binding, interaction, **params)  # type: ignore
11|manga-bot  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11|manga-bot  |   File "/root/mooshi/ManhwaUpdatesBot/src/ext/commands.py", line 192, in next_update_check
11|manga-bot  |     await interaction.response.send_message(embed=em, ephemeral=True)
11|manga-bot  |   File "/root/mooshi/ManhwaUpdatesBot/venv/lib/python3.11/site-packages/discord/interactions.py", line 778, in send_message
11|manga-bot  |     await adapter.create_interaction_response(
11|manga-bot  |   File "/root/mooshi/ManhwaUpdatesBot/venv/lib/python3.11/site-packages/discord/webhook/async_.py", line 219, in request
11|manga-bot  |     raise NotFound(response, data)
11|manga-bot  | discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
11|manga-bot  | The above exception was the direct cause of the following exception:
11|manga-bot  | Traceback (most recent call last):
11|manga-bot  |   File "/root/mooshi/ManhwaUpdatesBot/venv/lib/python3.11/site-packages/discord/app_commands/tree.py", line 1248, in _call
11|manga-bot  |     await command._invoke_with_namespace(interaction, namespace)
11|manga-bot  |   File "/root/mooshi/ManhwaUpdatesBot/venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 867, in _invoke_with_namespace
11|manga-bot  |     return await self._do_call(interaction, transformed_values)
11|manga-bot  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11|manga-bot  |   File "/root/mooshi/ManhwaUpdatesBot/venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 860, in _do_call
11|manga-bot  |     raise CommandInvokeError(self, e) from e
11|manga-bot  | discord.app_commands.errors.CommandInvokeError: Command 'next_update_check' raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction
11|manga-bot  | During handling of the above exception, another exception occurred:
11|manga-bot  | Traceback (most recent call last):
11|manga-bot  |   File "/root/mooshi/ManhwaUpdatesBot/src/core/command_tree.py", line 31, in _respond_with_check
11|manga-bot  |     await interaction.response.send_message(embed=embed, ephemeral=ephemeral)
11|manga-bot  |   File "/root/mooshi/ManhwaUpdatesBot/venv/lib/python3.11/site-packages/discord/interactions.py", line 778, in send_message
11|manga-bot  |     await adapter.create_interaction_response(
11|manga-bot  |   File "/root/mooshi/ManhwaUpdatesBot/venv/lib/python3.11/site-packages/discord/webhook/async_.py", line 219, in request
11|manga-bot  |     raise NotFound(response, data)
11|manga-bot  | discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
11|manga-bot  | During handling of the above exception, another exception occurred:
11|manga-bot  | Traceback (most recent call last):
11|manga-bot  |   File "/root/mooshi/ManhwaUpdatesBot/venv/lib/python3.11/site-packages/discord/app_commands/tree.py", line 1089, in wrapper
11|manga-bot  |     await self._call(interaction)
11|manga-bot  |   File "/root/mooshi/ManhwaUpdatesBot/venv/lib/python3.11/site-packages/discord/app_commands/tree.py", line 1252, in _call
11|manga-bot  |     await self.on_error(interaction, e)
11|manga-bot  |   File "/root/mooshi/ManhwaUpdatesBot/src/core/command_tree.py", line 192, in on_error
11|manga-bot  |     await self._respond_with_check(interaction, embed)
11|manga-bot  |   File "/root/mooshi/ManhwaUpdatesBot/src/core/command_tree.py", line 33, in _respond_with_check
11|manga-bot  |     await interaction.followup.send(embed=embed)
11|manga-bot  |   File "/root/mooshi/ManhwaUpdatesBot/venv/lib/python3.11/site-packages/discord/webhook/async_.py", line 1800, in send
11|manga-bot  |     data = await adapter.execute_webhook(
11|manga-bot  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11|manga-bot  |   File "/root/mooshi/ManhwaUpdatesBot/venv/lib/python3.11/site-packages/discord/webhook/async_.py", line 219, in request
11|manga-bot  |     raise NotFound(response, data)
11|manga-bot  | discord.errors.NotFound: 404 Not Found (error code: 10015): Unknown Webhook
`

This is the code that I ran:

`
    @app_commands.command(name="next_update_check", description="Get the time of the next update check.")
    async def next_update_check(self, interaction: discord.Interaction) -> None:
        # await interaction.response.defer(ephemeral=True, thinking=True)
        em = discord.Embed(
            title="Next Update Check",
            description=(
                f"The next update check is scheduled for "
                f"<t:{int(self.check_updates_task.next_iteration.timestamp())}:T>"
            ),
            color=discord.Color.blurple()
        )
        await interaction.response.send_message(embed=em, ephemeral=True)
`

![image](https://user-images.githubusercontent.com/83987369/230487944-74e84404-7e0a-4c65-9b17-45c79acc21bf.png)

**Comment by SebbyLaw** [comment]
This is an issue with the discord api, not the library. https://github.com/discord/discord-api-docs/issues/5558

**Comment by mikeshardmind** [comment]
This may not be related to the API issue SebbyLaw linked in this case, as it only applies to one command, not all intermittently, and there are several network database calls happening in the code prior to a response or deferring. It could just be a slight variance in conditions of the event loop while the best case is already eating up most of your time to respond. You could check this by deferring prior to those and using a followup after. If the issue still persists then, it would be time to look into a seemingly rare API issue.

**Comment by 2br-2b** [comment]
I think this is a separate issue than the linked one (though it could be an issue on Discord's end or on my machine's end). From my limited experience with these errors, my interactions seem to show "This application did not respond" as opposed to having a viewable response.

I did have this happen in a [command which started with a response deferral](https://github.com/Rapptz/discord.py/issues/9331#issuecomment-1494732156) and [one without a response deferral](https://github.com/Rapptz/discord.py/issues/9331#issue-1652256802), but if it'd be helpful, I can add a deferral to every command.

I think the next troubleshooting step will a timer. I think the easiest way will be to store `time.perf_counter()` at the beginning of every command and pass it to the reply commands. Then, when the reply command is run, if it catches the error, then it'll log the time the command started at, the current time, and the difference between the two. I don't know if I'll have time over this weekend to test this out, but when I do, I will update this issue.

Just a side note: everything seemed to work fine until sometime within the past couple of weeks (though I couldn't say when - I need to improve my logging system). I'm also willing to chock this up to a hardware or system-specific issue if no one else encounters it, though it seems that [I'm not the only one anymore](https://github.com/Rapptz/discord.py/issues/9331#issuecomment-1499588567).

**Comment by ruuffian** [comment]
I am having the same error, I interaction.response.defer() and then later attempt to call interaction.followup.send() and I am hit with a "404 Unkown Webhook" error.

Here is the error:
![image](https://user-images.githubusercontent.com/58525247/231598222-2cf0e6f5-8f7e-4668-a5bd-e97dedacbc4f.png)

Here is the code that causes this error:
```python
    async def send_message(self, message: discord.Interaction, user_message):
        if self.is_replying_all == "False":
            author = message.user.id
            await message.response.defer(ephemeral=self.isPrivate)
        else:
            author = message.channel.id
        try:
            response = (f'> **{user_message}** - <@{str(author)}' + '> \n\n')
            response = f"{response}{await responses.handle_response(user_message, self)}"

            ...

            if self.is_replying_all == "True":
                await message.channel.send(response)
            else:
                # LINE 54 BELOW
                await message.followup.send(response)
        except Exception as e:
            if self.is_replying_all == "True":
                await message.channel.send("> **ERROR: Something went wrong, please try again later!**")
            else:
                await message.followup.send("> **ERROR: Something went wrong, please try again later!**")
            logger.exception(f"Error while sending message: {e}")```

**Comment by 2br-2b** [comment]
After adding a lot of response deferrals, the issue seems to be gone.

I'll close the issue for now and re-open it if the issue comes back up.
