### ISSUE TITLE
`intents.message_content = True` doesn't exist

### ISSUE THREAD

**Issue by dschiller** [Rapptz/discord.py#9344]
### Summary

Demo from `readme.rst` doesn't work

### Reproduction Steps

- Open https://github.com/Rapptz/discord.py
- Follow readme.rst
- In Quick Example the line `intents.message_content = True` fails with:
`AttributeError: 'Intents' object has no attribute 'message_content'`

### Minimal Reproducible Code

```python
See https://github.com/Rapptz/discord.py/readme.rst Quick Example
```

### Expected Results

Should work

### Actual Results

Doesn't work

### Intents

?

### System Information

macOS

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by rdrescher909** [comment]
Could you please output your discord.py version (`print(discord.__version__)` after importing the module or `python -m discord -v` at your command line.

**Comment by dschiller** [comment]
```
pip freeze
discord.py==1.7.3
```

**Comment by rdrescher909** [comment]
The quickstart was written for discord.py v2.0+. As the api version that v1.7.3 uses will be shut down by Discord in the near future, it is no longer supported.

You should migrate your code to use the latest version, a migrating guide is available at https://discordpy.readthedocs.io/en/stable/migrating.html

**Comment by dschiller** [comment]
Sure. It seems `pip3 install discord.py` doesn't install the latest version.

**Comment by rdrescher909** [comment]
v2.0+ requires Python >= 3.8
