### ISSUE TITLE
readme.md needs to fix the unofficial discord link.

### ISSUE THREAD

**Issue by genaside** [Rapptz/discord.py#935]
I would like to join the discord, but like is expired

**Comment by Rapptz** [comment]
The invite is valid.

However you are probably banned.

**Comment by genaside** [comment]
that is impossible, i never been to the server. Plus a different account doesn't work either

**Comment by Rapptz** [comment]
You're right. Sorry.

I just remembered we deleted all channels by the incident of November 19th, 2017. I should probably update the invites.
