### ISSUE TITLE
Update auto_archive_duration parameter documentation

### ISSUE THREAD

**Issue by SnipUndercover** [Rapptz/discord.py#9351]
### Summary

Description of the `auto_archive_duration` parameter in `create_thread` is misleading.

### What is the feature request for?

The documentation

### The Problem

The current (v2.2.2) library documentation for the `auto_archive_duration` parameter in...
- `Thread.auto_archive_duration`
- `TextChannel.create_thread(...)`
- `PartialMessage.create_thread(...)`
- `ForumChannel.create_thread(...)` *(possibly)*
- `Thread.edit(...)`

...is outdated and/or misleading.

----

In all examples, the library documentation states:
> `auto_archive_duration` - The duration in minutes before a thread is automatically archived for inactivity. If not provided, the channel's default auto archive duration is used.  
> Must be one of 60, 1440, 4320, or 10080, if provided.

However, reading up on [Discord's thread metadata documentation](https://discord.com/developers/docs/resources/channel#thread-metadata-object-thread-metadata-structure) we can find that the current purpose of `auto_archive_duration` is different:
> | Field | Type | Description |
> | --- | --- | --- |
> | `auto_archive_duration` | integer | the thread will stop showing in the channel list after `auto_archive_duration` minutes of inactivity, can be set to: 60, 1440, 4320, 10080 |

All usages of `auto_archive_duration` describe it as such, with the exception of [creating a thread in forum channels](https://discord.com/developers/docs/resources/channel#start-thread-in-forum-channel-jsonform-params), where the documentation matches. This might be an oversight on Discord's part, however I wasn't able to test this.

This caused confusion when going off of discord.py's docs, expecting the thread to be automatically archived after a set period of time.

### The Ideal Solution

The parameter should state that `auto_archive_duration` does **not** archive the thread, but it merely hides it from the channel list.

**Comment by LeoCx1000** [comment]
That used to be the case. Then discord made them worse...

**Comment by SnipUndercover** [comment]
Found some more cases where the parameter is described and edited the issue accordingly.
