### ISSUE TITLE
Error for linux?

### ISSUE THREAD

**Issue by fearwastaken** [Rapptz/discord.py#9360]
### Summary

i am on linux and i am trying to import the library using ``` python3 -m pip install discord.py``` but everytime i do it in the terminal it says "No module named pip"

### Reproduction Steps

do 
python3 -m pip install discord.py

in the terminal

### Expected Results

import the library

### Actual Results

"No module as pip"

### Intents

client = commands.Bot(command_prefix='?', intents=discord.Intents.All())

### System Information

python command not found
when i put python3 it says discord module not found

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by EvieePy** [comment]
Which operating system?

For Ubuntu/Debian you can run:
```
sudo apt update
sudo apt install python3-pip
```
That should fix your issue

**Comment by fearwastaken** [comment]
thanks
