### ISSUE TITLE
Option to Return Data as JSON

### ISSUE THREAD

**Issue by wa1ker38552** [Rapptz/discord.py#9370]
### Summary

Instead of creating objects could there be an option to return the data as is recieved from Discord?

### What is the feature request for?

The core library

### The Problem

Some of the objects and attributes are different in the objects than defined in Discord's documentation. If there could be an option to return data in json, it would be helpful to developers that might want to access more of the data that Discord provides, exactly as Discord provides.

### The Ideal Solution

Something like this? 
```py
client = discord.Client(json=True)

@client.event
async def on_message(message):
  print(message['author']['username'], message['content'])
```

### The Current Solution

I tried using the [JSONS](https://jsons.readthedocs.io/en/latest/) library as well as vars() but none of them seemed to work because of how complex the objects are in Discord.py

**Comment by Rapptz** [comment]
Nope.

**Comment by wa1ker38552** [comment]
Could I ask why not? Would it be too complicated?
