### ISSUE TITLE
Copy and pasting @bot results in a different bot id

### ISSUE THREAD

**Issue by 0xSage** [Rapptz/discord.py#9376]
### Summary

Directly typing @bot versus copying pasting "@bot" results in a different message string all together

### Reproduction Steps

1. Physically type "@myBotName" in a channel
2. Print `message.content`
3. See bot name is displayed as `<@1099...7850>` => correct
4. Then copy the message from step 1
5. Paste into a new message in a channel (instead of typing out `@..`)
6. Print `message.content`
7. See bot name is now `<@&1099...4901>` => now it's a pointer to something?

Question: is this intentional? If so, how do I retrieve this `<@&..>` id for the bot in the code from ClientUser object? Would rather not hardcode this in my implementation. 

Thanks!

### Minimal Reproducible Code

```python
see reproduction steps
```

### Expected Results

see repro steps

### Actual Results

see repro steps

### Intents

message

### System Information

- Python v3.11.3-final
- discord.py v2.2.2-final
- aiohttp v3.8.4
- system info: Darwin 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:43 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8112

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
This is just the client resolving the mention differently (i.e. copying it as a role mention instead of a user mention). I'm unsure why this was filed as an issue in this repository as it involves nothing from discord.py.
