### ISSUE TITLE
DM people with discord.py bot

### ISSUE THREAD

**Issue by seant4** [Rapptz/discord.py#938]
I am trying to have my bot dm certain people, essentially, i want to make a game with the bot that people join, then dm's them all a question, it the same question except one person gets a different question, and they all answer it, and they must vote who is the fake. Any ideas?

**Comment by BlackSynder** [comment]
You can send DMs by putting a user as the destination in [send_message](http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.send_message)

**Comment by seant4** [comment]
Thanks!
