### ISSUE TITLE
`.untimeout` method

### ISSUE THREAD

**Issue by teilorr** [Rapptz/discord.py#9391]
### Summary

Add a `.untimeout` method to `Member` objects

### What is the feature request for?

discord.ext.commands

### The Problem

The timeout interface as it is right now, is a bit weird to be used, specially to "untimeout" a member. We can agree that `.timeout(None)` is weird to read and see, specially when the `until` arg is pos-only. There is no way to make it more explicit and better-looking, like `.timeout(until=None)`. 

### The Ideal Solution

With this suggestion, i propose the implementation of a `.untimeout(*, reason: Optional[str] = None)` method to clarify things and make it easier to understand what the code is doing. With this method, you don't need to think: "timeout is a layer over `.edit`, so passing `None` here will undo the timeout", just: "this removes the timeout of x member" instead. Much easier, huh? This method would make it clear to new users to the library understand how to untimeout someone, as i've seen multiple questions like: "how do i remove the timeout of a member?". Just a simple feature to improve the general UX

**Comment by Rapptz** [comment]
There's already two ways to spell this out so I don't feel like a 3rd way would be better. Plus the term "untimeout" isn't really proper. If you don't like `member.timeout(None)` you can do `member.edit(times_out_until=None)`
