### ISSUE TITLE
sslv3 alert bad record mac

### ISSUE THREAD

**Issue by neozhaoliang** [Rapptz/discord.py#9395]
### Summary

Slash command cannot send followups to user

### Reproduction Steps

My bot needs to return some files/reaction buttons to the user; in a `followup` send, it works most of the time, but sometimes it reports the error
`aiohttp.client_exceptions.ClientOSError: [Errno 1] [SSL: SSLV3_ALERT_BAD
_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2633)`
And the bot cannot return the file and reactions.
Is it a network problem, or it's due to an improper api call?
For example, should I use bot.loop.create_task to send this `followup`, or should I use `asyncio.run_coroutine_threadsafe` to send it?

### Minimal Reproducible Code

```python
I need to call the following funtion in another non-async thread:


async def add_buttons(self, task, outdir, url):
        """Send the generated results and add reaction buttons."""
        buttons = UserReactionButtons(task, self)
        await task.msg.edit(
            content=f"**{task.prompt}** - <@{task.ctx.user.id}>, preview your model at {url}",
            embed=None,
            attachments=[
                discord.File(os.path.join(outdir, "output.mp4")),
                discord.File(os.path.join(outdir, "model.zip")),
            ],
            view=buttons,
        )


I use `bot.loop.create_task(bot.add_button(...))` or `asyncio.run_coroutine_threadsafe(bot.add_button(...), bot.loop)`.

The problem happen in both cases? (maybe more often in the first case)
```

### Expected Results

It does work most of the time (80%-90%), however it fails occasionally.

### Actual Results

The bot stuck for a while and fails to send the followup

### Intents

discord.Intents.all()

### System Information

- Python v3.9.16-final
- discord.py v2.2.2-final
- aiohttp v3.8.4
- system info: Linux 5.15.0-69-generic #76~20.04.1-Ubuntu SMP Mon Mar 20 15:54:19 UTC 2023

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
I can't do anything about these SSL errors.
