### ISSUE TITLE
Exceptions thrown in interaction_check are silently ignored

### ISSUE THREAD

**Issue by bjstarosta** [Rapptz/discord.py#9399]
### Summary

Discord.py error handlers do not catch exceptions raised in an overridden `Cog.interaction_check` method as expected. Bug solution is attached below.

### Reproduction Steps

Override the `interaction_check` method in a `Cog` subclass, and put code inside of the method that throws an exception. This exception will not be caught by any handler such as `Cog.cog_app_command_error` or `CommandTree.on_error`.

### Expected Results

Discord.py error handlers can catch the exception and handle it.

### Actual Results

The called slash command fails silently, the exception is not passed to any defined error handlers.

### Intents

Not applicable

### System Information

- Python v3.11.3-final
- discord.py v2.2.3-final
- aiohttp v3.8.4
- system info: Linux 6.3.1-arch1-1 # 1 SMP PREEMPT_DYNAMIC Mon, 01 May 2023 17:42:39 +0000

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I fixed this bug by navigating to line [848](https://github.com/Rapptz/discord.py/blob/master/discord/app_commands/commands.py#L848) in `discord/app_commands/commands.py`, and replacing this code:
```
    async def _invoke_with_namespace(self, interaction: Interaction, namespace: Namespace) -> T:
        if not await self._check_can_run(interaction):
            raise CheckFailure(f'The check functions for command {self.name!r} failed.')
```

With this code:
```
    async def _invoke_with_namespace(self, interaction: Interaction, namespace: Namespace) -> T:
        try:
            check = await self._check_can_run(interaction)
        except Exception as e:                
            raise CommandInvokeError(self, e) from e

        if not check:
            raise CheckFailure(f'The check functions for command {self.name!r} failed.')
```

After this change the exceptions thrown in interaction_error are caught correctly. I can open a pull request fixing this if desired.

**Comment by Rapptz** [comment]
Exceptions raised in `interaction_check` need to derive from `AppCommandError`, just like how regular commands need to be derive from `commands.CommandError`. Checks do not *cause* invoke errors because invoke errors are errors specifically within the *body* of the command itself.

The `_check_can_run` will just propagate the exception as-is when it's encountered, for the sake of example we'll use `TypeError`. `_invoke_with_namespace` is called inside `CommandTree._call` which, again, only catches `AppCommandError` and uses it to call error handlers. Since the exception is not handled it's propagated to the task frame and ignored as you've seen.

Note that this isn't different to how `Bot.invoke` works.

**Comment by bjstarosta** [comment]
> The `_check_can_run` will just propagate the exception as-is when it's encountered, for the sake of example we'll use `TypeError`. `_invoke_with_namespace` is called inside `CommandTree._call` which, again, only catches `AppCommandError` and uses it to call error handlers. Since the exception is not handled it's propagated to the task frame and ignored as you've seen.

I have an error handler defined in both `cog_app_command_error` and in the command tree, to catch both `AppCommandError` derived and other exceptions that have been wrapped in `AppCommandError` and are received in the handler via the `original` property (so for example . The main issue is: if there is an error in the code in `interaction_check`, it not only does not get passed down to the handler but it gets ignored all the way down. So I can't define any additional error handlers to handle non `AppCommandError` exceptions that would catch this, the only thing that fixes it is wrapping the exception in one derived from `AppCommandError` - as seems to be the case with exceptions raised in the method where the actual command logic takes place.

The reason why I have raised this is precisely because this behaviour differs from the behaviour of exceptions raised in a command method, as that gets wrapped properly and sent on to the error handler, e.g. result after throwing TypeError in a command method:

```
discord.app_commands.errors.CommandInvokeError: Command 'test' raised an exception: TypeError:
```

I am not sure why some exceptions get to be wrapped, while others don't. Surely you'd want this behaviour to be consistent across the entire library?

**Comment by Rapptz** [comment]
> I am not sure why some exceptions get to be wrapped, while others don't.

The only exceptions that get wrapped are the ones inside the body, purely because that case of error propagation is (unfortunately) way more common than any other place in the library. Checks have always been documented as needing to raise a properly derived exception for it to propagate.

**Comment by bjstarosta** [comment]
In that case, what is the preferred method of debugging checks? I understand that they *shouldn't be designed* to throw non `AppCommandError` exceptions, but how should I handle it if they do, considering that these errors get silenced before they have a chance to get logged by a logger?

**Comment by bjstarosta** [comment]
Just in case someone else stumbles this issue while looking for answers:

As pointed out above by the maintainer, there is an inconsistency in how the discord.py library handles exceptions thrown in checks vs. those thrown in command methods. While command methods catch non library exceptions by default to make things easier for the programmer and reduce boilerplate, if one wants to use `interaction_check` (or any other custom checks) and be able to catch or log non-library exceptions emitted from checks (as code can and does fail), they must wrap all code inside the method in a try-except statement that re-raises any caught exceptions as `app_commands.CommandInvokeError` (or some other exception derived from `app_commands.AppCommandError`). This can also pass the original exception down to the error handler.

This inconsistency, despite being documented, is not at all straight forward to catch when starting out with checks when one is used to the other behaviour of exceptions being passed to error handlers without adding further boilerplate. However, it is possible to design `Cog` classes around it:

```
import logging
import discord
from discord import app_commands
from discord.ext import commands

logger = logging.getLogger(__name__)


class TestCog(commands.Cog):

    def interaction_check(self, interaction: discord.Interaction):
        try:
            # your check code goes here
            pass
        except Exception as e:
            raise app_commands.CommandInvokeError(
                interaction.command, e
            ) from e

    async def cog_app_command_error(
        self,
        interaction: discord.Interaction,
        exc: app_commands.AppCommandError
    ) -> None:
        # Exception handling goes here, or to an on_error event handler.
        # At the end of the exception handling, log the exception.
        logger.error(exc, exc_info=True)
```

If attempting to minimise boilerplate, one can instead subclass the `Cog` class into a common parent and define a separate check method that is called by `interaction_check`, like so:

```
import logging
import discord
from discord import app_commands
from discord.ext import commands

logger = logging.getLogger(__name__)


class ParentCog(commands.Cog):

    def interaction_check(self, interaction: discord.Interaction):
        try:
            self.interaction_check_except(interaction)
        except Exception as e:
            raise app_commands.CommandInvokeError(
                interaction.command, e
            ) from e

    async def cog_app_command_error(
        self,
        interaction: discord.Interaction,
        exc: app_commands.AppCommandError
    ) -> None:
        # Exception handling goes here. It can also be handled by an on_error event.
        # At the end of the exception handling, log the exception.
        logger.error(exc, exc_info=True)


class ChildCog(ParentCog):

    def interaction_check_except(self, interaction: discord.Interaction):
        # your check code goes here
        pass
```

**Comment by Rapptz** [comment]
Your solution wraps *every* exception into `CommandInvokeError`. This is incorrect behaviour, and quite frankly, you shouldn't be throwing these manually anyway but unfortunately I forgot to stub out the constructor for these in the documentation to mark them as private.

If you want to just wrap functions as-is just write a decorator and apply it to your checks:

```py
import functools
from discord import app_commands
from discord.utils import maybe_coroutine

class InvalidCheck(app_commands.AppCommandError):
    pass

def wrap_check(func):
    @functools.wraps(func)
    async def wrapper(*args, **kwargs):
        try:
            return await maybe_coroutine(func, *args, **kwargs)
        except app_commands.CommandError:
            raise
        except Exception as exc:
            raise InvalidCheck() from exc

    return wrapper
```

No type hinting provided though.

**Comment by bjstarosta** [comment]
> Your solution wraps _every_ exception into `CommandInvokeError`. This is incorrect behaviour, and quite frankly, you shouldn't be throwing these manually anyway but unfortunately I forgot to stub out the constructor for these in the documentation to mark them as private.

I was considering using `CheckFailure`, but after reading the documentation I wasn't sure about what kind of failure it is supposed to represent. Is it supposed to be a runtime error failure? An exception thrown if one of the checks does not pass? Both? If it is both, maybe the solution is for the library to provide a built-in exception class such as `CheckInvokeError`? This could then allow the library to handle passing the exception to handlers too.
