### ISSUE TITLE
webhook for all channels

### ISSUE THREAD

**Issue by qrdlgit** [Rapptz/discord.py#9413]
### Summary

specify channel in webhook post body

### What is the feature request for?

The core library

### The Problem

I created a chrome extension so admins can post to channels when browsing.   We have quite a few channels and creating a bot for every channel for each admin is going to really add up.

Is there a way to just have one bot per admin instead of one bot per channel per admin?

One hack might be to edit the webhook before sending the message, but that seems wrong and potentially flakey.

### The Ideal Solution

have another parameter in the body for the webhook stating the channel

### The Current Solution

one webhook per channel

**Comment by cibere** [comment]
A webhook can only send a message to a single channel. This is how discord designed them. Though you only need 1 webhook per channel, since you can edit the username/logo when sending the message.

**Comment by qrdlgit** [comment]
yep, why it's a feature request.

You can edit a webhook before sending the message

webhook.edit({
	name: 'Some-username',
	avatar: 'https://i.imgur.com/AfFp7pu.png',
	channel: '222197033908436994',
})
	.then(webhook => console.log(`Edited webhook ${webhook}`))
	.catch(console.error)

**Comment by Rapptz** [comment]
I think you're in the wrong repository. This is for discord.py, not a JavaScript library. Note that in the library you can edit the webhook channel by calling Webhook.edit.
