### ISSUE TITLE
New username sys

### ISSUE THREAD

**Issue by thedtvn** [Rapptz/discord.py#9414]
### Summary

to  update  the  user  obj

### What is the feature request for?

The core library

### The Problem

- discord  has add new global name
- new username will have  discriminator == 0

![image](https://github.com/Rapptz/discord.py/assets/80153297/0dd8b85a-8dbc-4cec-9edc-b628e86592f3)

### The Ideal Solution

- add global_name
- fix 
```py 
def __str__(self) -> str:
        return f'{self.name}#{self.discriminator}'
```
in https://github.com/Rapptz/discord.py/blob/master/discord/user.py#L99
to 
```
def __str__(self) -> str:
   if self.discriminator != 0:
        return f'{self.name}#{self.discriminator}'
   return self.name

### The Current Solution

_No response_

### Additional Context

_No response_

**Comment by MajorTanya** [comment]
There is already a migration underway in the pomelo branch

**Comment by Soheab** [comment]
See https://github.com/Rapptz/discord.py/compare/master...feature/pomelo

**Comment by thedtvn** [comment]
> See [master...feature/pomelo](https://github.com/Rapptz/discord.py/compare/master...feature/pomelo)

@Soheab thank
