### ISSUE TITLE
Role Tag bug, single role tag is not returned in an array

### ISSUE THREAD

**Issue by ashkon91** [Rapptz/discord.py#9415]
### Summary

When there is a single role tag it is not returned in an array

### Reproduction Steps

Try to iterate through a roletag when there is a single one.

### Minimal Reproducible Code

```python
for tag in role.tags:
print(tag)
```

### Expected Results

The expected result would be an array with a single tag

### Actual Results

A single RoleTag object

### Intents

all intents 

### System Information

2.2.3

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

tags
The role tags associated with this role.

Type
Optional[[RoleTags](https://discordpy.readthedocs.io/en/stable/api.html?highlight=subscription#discord.RoleTags)]

as noted on the wiki

**Comment by No767** [comment]
are you sure that the `tags` attrs is iterable (meaning that is it a list of `RoleTags`?) I checked the docs and it isn't iterable. Seems to be working as intended
