### ISSUE TITLE
all attributes of an attribute is not recognized with @utils.cached_slot_property decorator.

### ISSUE THREAD

**Issue by LetsChill** [Rapptz/discord.py#9431]
### Summary

In pycharm, any attribute in a class that returns another class, with the @utils.cached_slot_propert decorator, will not recognize its attributes.

### Reproduction Steps

Try to use any attribute from a class that returns another class with the decorator @utils.cached_slot_propert on top.
# Examples: 
```py
discord.Interaction.response
discord.StageInstance.channel
```
and more.

PyCharm won't recognize the class given, and will flag the reference as unresolved.

### Minimal Reproducible Code

```python
@app_commands.command(name="ping", description="A ping command!")
async def ping(self, inter: discord.Interaction):
    await inter.response.send_message(content="Pong!") # <-- Cannot find reference 'send_message' in '() -> InteractionResponse'
```

### Expected Results

The object should be recognized and references should be shown, and the reference will not be flagged as unresolved.

### Actual Results

the object was flagged as unresolved due to the decorator @utils.cached_slot_property

### Intents

default

### System Information

```py
- Python v3.11.0-final              
- discord.py v2.2.3-final           
- aiohttp v3.8.4                    
- system info: Windows 10 10.0.1904
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
This is an issue that pycharm has to fix because it does not support descriptors. If you want proper type checking for Python I recommend using Pyright as it gets this right.
