### ISSUE TITLE
Max number of daily applications command reached

### ISSUE THREAD

**Issue by NotHansCYDIa** [Rapptz/discord.py#9439]
### Summary

I was working on a bot and testing json for a simple data store when I encountered an error stating that the maximum number of daily application commands had been reached.

### Reproduction Steps

I was working on a bot and testing json to create a simple data store. While running the bot and making some changes, I decided to test the json with a slash command. However, after a few minutes, I encountered an error message stating: 'The maximum number of daily application command creations has been reached'.

### Minimal Reproducible Code

```python
class abot(discord.Client):
    def __init__(self):
        super().__init__(intents=discord.Intents.default())
        self.synced = False
        
    async def on_ready(self):
        await tree.sync(guild=guild)
        self.synced = True
        print("===== mybot123456 =====")
        print("    bot is ready!")
```

### Expected Results

I expected the bot to work smoothly with the slash command and the JSON code working correctly

### Actual Results

I ran the bot and it started with the info messages until there was an error message saying that I reached the max limit of the daily application command.

### Intents

discord.Intents.all()

### System Information

- Python v3.11.3-final
- discord.py v2.3.0-alpha
    - discord.py metadata: v2.3.0a4841+ga8882f7c
- aiohttp v3.8.4
- system info: Darwin 22.4.0 Darwin Kernel Version 22.4.0: Fri Feb 10 08:09:16 PST 2023; root:xnu-8796.100.721.505.3~4/RELEASE_ARM64_T8112

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

After searching for the issue on various forums, I discovered that I might be experiencing a rate limit and would need to wait until the next day but I'm a bit impatient.

**Comment by Rapptz** [comment]
This is a discord bug. https://github.com/discord/discord-api-docs/issues/6188

**Comment by NotHansCYDIa** [comment]
oh alright

**Comment by didis97** [comment]
works now

**Comment by EvieePy** [comment]
Can confirm. This issue has been fixed https://github.com/discord/discord-api-docs/issues/6188#issuecomment-1570347487
