### ISSUE TITLE
Delete Existing Help Command

### ISSUE THREAD

**Issue by eltontay11** [Rapptz/discord.py#944]
If I want to have my own help command, how do I delete the existing help command?

**Comment by eltrhn** [comment]
http://discordpy.readthedocs.io/en/rewrite/ext/commands/api.html#discord.Bot.formatter

```By default, it uses the HelpFormatter. Check it for more info on how to override it. If you want to change the help command completely (add aliases, etc) then a call to remove_command() with ‘help’ as the argument would do the trick.```

**Comment by eltontay11** [comment]
Where do we put the remove command? Do we put it in @bot.event ?

**Comment by Eternity71529** [comment]
no you do that when instantiating your Bot instance or when loading the cog (if your command is in a cog)

**Comment by eltontay11** [comment]
So put it at where?

**Comment by eltontay11** [comment]
A line in front of bot.run?

**Comment by Eternity71529** [comment]
`bot=commands.Bot(...)
bot.remove_command("help")
#insert rest of code here
bot.run("<token>")`
OR
`#taking this to be a cog
def setup(bot):
    bot.remove_command("help")
    bot.add_cog(MyHelpCommandClass(bot))`

**Comment by eltontay11** [comment]
Ok thanks!
