### ISSUE TITLE
bot.status is not updated by bot.change_presence()

### ISSUE THREAD

**Issue by Oxymore13** [Rapptz/discord.py#9440]
### Summary

using the bot.chance_presence method did not update bot.status accordingly

### Reproduction Steps

1. Display `bot.status`
2. Use `bot.change_presence` to set the bot's status to `discord.Status.idle`
3. Display `bot.status` again, and it still shows `online`

_Note : the issue has also been observed with `discord.Status.dnd` instead of `discord.Status.idle`_

### Minimal Reproducible Code

```python
@commands.command(name="test")
async def test(ctx):
        
    print(bot.status)

    await bot.change_presence(status=discord.Status.idle)

    print(bot.status)
    
    return
```

### Expected Results

I expected `bot.status` to be set to `discord.Status.idle`

### Actual Results

`bot.status` value is still `discord.Status.online` after using `bot.change_presence`

### Intents

discord.Intents.all()

### System Information

- Python v3.11.2-final
- discord.py v2.1.1-final
- aiohttp v3.8.4
- system info: Windows 10 10.0.19045

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

it is possible to set `bot.status` manually, so adding `bot.status = discord.Status.idle` below solves the issue, however it doesn't seem to be a normal behaviour and I think `bot.status` was meant to be updated when using bot.change_presence.

**Comment by Rapptz** [comment]
This is by design. `Client.status` is for the status set automatically during `READY`. `Client.change_presence` is to change the current session's presence at runtime. They are different, though similar. If you want to retrieve a session from a guild you can use `Guild.me` to retrieve your current member and then get the status from there.

**Comment by Oxymore13** [comment]
Didn't find how on the documentation but thanks anyway, I guess I'll have to find a turnaround once again.
