### ISSUE TITLE
"display_name" attribute of "discord.Member" class isn't working anymore

### ISSUE THREAD

**Issue by sicco14** [Rapptz/discord.py#9447]
### Summary

Since Discord introduced their new username system the "display_name" always shows the username instead of the server nickname

### Reproduction Steps

Nothing, since I didn't change my code. But discord introduced their username updates.

### Minimal Reproducible Code

```python
author_dn = interaction.user.display_name
auticon = interaction.user.display_avatar
embed = discord.Embed(title=f'{selected_league} Report-Ticket: {current_ticket}\n\u200b', color=discord.Color.magenta())
embed.set_author(name=author_dn, icon_url=auticon)
```

### Expected Results

Usually member.display_name always showed the users (server)nickname and if there was no nickname set it showed the global discord name

### Actual Results

Now it ALWAYS shows the global discord name aka. the new usernames (even if there is a server nickname set)

### Intents

PRESENCE, SERVER MEMBERS, MESSAGE CONTENT

### System Information

- Python v3.8.6-final
- discord.py v2.2.2-final
- aiohttp v3.8.3
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
Obviously this requires an update because it's using a new attribute. This stuff is supported in the `master` branch and there will be a new release sometime soon that will address this. But as it stands right now, this is already working as intended in the master branch.
