### ISSUE TITLE
guild.get_member_named does not return users whose username is a four-digit number

### ISSUE THREAD

**Issue by ldjb** [Rapptz/discord.py#9451]
### Summary

get_member_named interprets four-digit username as discriminator

### Reproduction Steps

My 'new' Discord username is 3270 (or 3270#0, if you include the hidden discriminator).

You'd expect that calling guild.get_member_named('3270') would return my account. However, `None` is returned instead.

### Minimal Reproducible Code

```python
guild.get_member_named('3270')
```

### Expected Results

It should return a `Member` object representing my account (assuming I am a member of `guild`).

### Actual Results

The method returns `None`.

### Intents

N/A

### System Information

- Python v3.10.11-final
- discord.py v2.3.0-final
- aiohttp v3.8.4
- system info: Windows 10 10.0.22621

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I suggest testing whether the character `#` is present in the input, `name`. For example:

```py
def get_member_named(self, name: str, /) -> Optional[Member]:
    members = self.members

    if '#' in name:
        username, _, discriminator = name.rpartition('#')
        if discriminator == '0' or (len(discriminator) == 4 and discriminator.isdigit()):
            return utils.find(lambda m: m.name == username and m.discriminator == discriminator, members)

    def pred(m: Member) -> bool:
        return m.nick == name or m.global_name == name or m.name == name

    return utils.find(pred, members)
```

**Comment by Rapptz** [comment]
Thanks. This is fixed now. The issue happens regardless of whether a username is full of digits. I'm a bit surprised no one ran into this after a month.
