### ISSUE TITLE
Member.display_name returns the username instead of the display name

### ISSUE THREAD

**Issue by Galaeran** [Rapptz/discord.py#9455]
### Summary

Member.display_name returns the username instead of the display name for members who have performed username migration

### Reproduction Steps

I have a bot set up to post the display names of specific users within the server. Prior to username migration, this worked just fine for all members by showing the member's display name or server-specific display name.

However, for users who have performed the username migration (to remove the discriminator), Member.display_name now displays the user's username even if that user has specified a global display name. Server-specific display name overrides still work correctly.

I have tried using the following attributes within the Member class: name, display_name, nick, global_name. However, none of these show the member's correct Display Name.

### Minimal Reproducible Code

```python
import discord
client = discord.Client(intents=discord.Intents.all())
@client.event
async def on_message(message):
    print(message.author.display_name)
client.run(<REDACTED>)
```

### Expected Results

Member.display_name returns the user's Display Name specified in their account settings unless the user has a server-specific display name override.

### Actual Results

Member.display_name returns the user's username even if they have a Display Name specified.

### Intents

discord.Intents.all()

### System Information

- Python v3.11.2-final
- discord.py v2.1.1-final
- aiohttp v3.8.4
- system info: Linux 6.2.0-20-generic #20-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  6 07:48:48 UTC 2023

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by MajorTanya** [comment]
This was implemented in the v2.3 release, 99% sure
