### ISSUE TITLE
Dynamically Create Commands.

### ISSUE THREAD

**Issue by Bangbangboefratatata** [Rapptz/discord.py#9463]
### Summary

Pass arguments to discord.app_commands.command instead of getting the _params from the callback.

### What is the feature request for?

discord.ext.commands

### The Problem

You cant dynamically create 

With the current code the _params for the discord.app_commands.command are extracted from the callback function.
The problem with this is that you can't create commands that you can create dynamically as you can see in the code below.

`

    async def create_command(self, command):
        await self.bot.tree.add_command(
            command=app_commands.Command(
            name="example",
            description="example",
            callback=self.not_custom_callback
            )
          )

    async def not_custom_callback(self, interaction:discord.Interaction, arg1:str, arg2:str):
        #do stuff with the command
        pass
`

### The Ideal Solution

I dont have an Ideal solution, i only would be very happy if this would be implemented. I want to be able to create commands like you see in the code below, where you can use **kwargs to unpack all the arguments.

'

    async def create_command(self, command):
        await self.bot.tree.add_command(
            command=app_commands.Command(
            name="example",
            description="example",
            callback=self.not_custom_callback,
            arguments={"arg1":discord.Member, "arg2":discord.TextChannel}
            )
          )

    async def custom_callback(self, interaction:discord.Interaction, **kwargs):
        #do stuff with the command
        pass
        
'

### The Current Solution

My current solution to this is (haven't tested it yet) to add the arguments parameter to the discord.app_commands.command.

My current solution:
(discord.app_commands.commands.py)

In the __init__ of Command:
add parameter: `arguments: Dict[str, CommandParameter] = None,`
add: `self.arguments: Dict[str, CommandParameter] = arguments`

If arguments argument is passed to the Command class use that, if not passed extract the parameters from the callback.
'

        if self.arguments:
            self._params: Dict[str, CommandParameter] = arguments
        else:
            self._params: Dict[str, CommandParameter] = _extract_parameters_from_callback(callback, callback.__globals__)

'

### Additional Context

Hello,

I'm an aspiring coder and passionate about creating a versatile Discord bot. While using discord.py, I encountered a limitation regarding slash commands. Currently, the parameters for slash commands are extracted from the callback function.

However, I believe it would be beneficial to have the option to manually pass arguments for slash commands. This would provide greater control and customization possibilities for developers.

I have made modifications to the code to enable manual argument passing, and I believe this feature would enhance the flexibility and power of discord.py.

Thank you for considering my suggestion. I hope it aligns with the vision of discord.py and can be implemented in the future.

Best regards,
Jasper, mrbeast5000#0

**Comment by No767** [comment]
Btw u can't dynamically create them iirc. It has to be programmed before they are synced

**Comment by Bangbangboefratatata** [comment]
> Btw u can't dynamically create them iirc. It has to be programmed before they are synced

U sure? Bc in the class "Command" it looked like the _params were just extracted from the callback.

So i dont really see a difference between passing them directly or getting them from the callback.

But idk im pretty new to programming.

**Comment by Rapptz** [comment]
I have no plans for this. If you want to do this you're free to generate a function at runtime or at least modify the signature using `__signature__` with the one you want while masquerading the actual signature. I'm not sure if code like this would ever break since it's not part of the guarantees but that's the best I'll allow for this use case. For example:

```py
import discord
import inspect
import copy

async def mycallback(interaction: discord.Interaction, **kwargs) -> None:
    ... # do something... somehow


parameters = [
    # Required parameter
    inspect.Parameter(
        name='interaction', # Parameter name
        annotation=discord.Interaction, # Parameter type
        kind=inspect.Parameter.POSITIONAL_OR_KEYWORD,
    ),
    # Your own follows here
    inspect.Parameter(
        name='a', # Parameter name
        annotation=int, # Parameter type
        kind=inspect.Parameter.POSITIONAL_OR_KEYWORD,
    )
]

callback = copy.copy(mycallback)
callback.__signature__ = inspect.Signature(parameters=parameters)

# create Command object here
```
