### ISSUE TITLE
more-accurate typing stubs for @app_commands.command()

### ISSUE THREAD

**Issue by andrewj-brown** [Rapptz/discord.py#9468]
### Summary

@app_commands.command() typing stubs should be identical to the actual requirements on a command callback.

### What is the feature request for?

The core library... I think? The @app_commands.command() decorator is imported from the core library, at least.

### The Problem

When trying to use `mypy` to statically typecheck a discord bot, the @app_commands.command() decorator expects a callback of type:
`Callable[[<nothing>, Interaction[Any], VarArg(<nothing>), KwArg(<nothing>)], Coroutine[Any, Any, <nothing>]] | Callable[[Interaction[Any], VarArg(<nothing>), KwArg(<nothing>)], Coroutine[Any, Any, <nothing>]]`

The actual type of a callback (taking one text argument) is, for example:
`Callable[[CogClass, Interaction[Any], str], Coroutine[Any, Any, Any]]`

Attempting to add `*args` and `**kwargs` to the callback function result in discord.py firstly raising errors that all the callback arguments need types, and if you type them as e.g. `str`, then discord.py raises errors that `VAR_POSITIONAL` args are unsupported.

### The Ideal Solution

It would be nice if the @app_commands.command() types were updated to be a bit more specific and not take any VarArgs or KwArgs.

### Additional Context

If this issue is already solved, consider this to be a request for "how do I do this thing" to be slightly better documented. 

I can investigate tackling this problem myself, but only if this fix is actually necessary/desired for the library.

**Comment by Rapptz** [comment]
It takes `ParamSpec` not whatever `VarArg`/`KwArg` is, I suppose this is an internal mypy representation of a `ParamSpec`. `ParamSpec` is used because it's the only decent way to support callable parameters. I'm not even sure there's an alternative. `TypeVarTuple` does not work with e.g. keyword only arguments which are supported just fine.

**Comment by andrewj-brown** [comment]
I'll investigate `pyright` then. Apologies for the mixup.

**Comment by Rapptz** [comment]
No problem. It should be noted that there's no way in typing parlance to forbid e.g. `*args` or `**kwargs` in general.
