### ISSUE TITLE
Avy Changing

### ISSUE THREAD

**Issue by zZ0MBi3** [Rapptz/discord.py#947]
not-so-much-an-issue-but-more-of-a-question

is there some way to make a bot change profile pics from a selected folder every hour

**Comment by Vexs** [comment]
Yes. Use [edit_profile](http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.edit_profile) on async, use [Clientuser.edit](http://discordpy.readthedocs.io/en/rewrite/api.html#discord.ClientUser) on rewrite. 

In the future, please redirect similar questions to the discord.py discord channel, as it is better suited to these kind of questions.  https://discord.gg/r3sSKJJ
