### ISSUE TITLE
discord.ui.RoleSelect() and discord.ui.ChannelSelect() not displaying all roles/channels

### ISSUE THREAD

**Issue by simoovara** [Rapptz/discord.py#9470]
### Summary

they aren't listing all the channels or roles

### Reproduction Steps

make a `discord.ui.ChannelSelect()` or `discord.ui.RoleSelect()` in a server with a lot of channels/roles, and it won't list them all

### Expected Results

expected to see all the channels listed, pretty sure this is an issue on discord's part, but if there is a way to list all of them let me know

### Actual Results

only a few channels (categories, vc's, text channels) got displayed, and left out a TON of channels.

### Intents

discord.Intents.all()

### System Information

1st system:
- Python v3.11.3-final
- discord.py v2.3.0-final
- aiohttp v3.8.4
- system info: Windows 10 10.0.19045

2nd system:
- Python v3.10.6-final
- discord.py v2.3.1-final
- aiohttp v3.8.4
- system info: Linux 5.15.0-75-generic #82-Ubuntu SMP Tue Jun 6 23:10:23 UTC 2023

doesn't work on both systems

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by simoovara** [comment]
mentioned #82 by accident when running `python3 -m discord -v` on my linux system

**Comment by Rapptz** [comment]
The library doesn't control this so I don't think this belongs here.

**Comment by cibere** [comment]
FYI this is because discord has a max amount of options that they display. Start typing the name of the channel/role and you should find it

**Comment by simoovara** [comment]
> FYI this is because discord has a max amount of options that they display. Start typing the name of the channel/role and you should find it

i feel so stupid now cuz that works, didn't know you could type in there
