### ISSUE TITLE
Add who made the action in "on_member_ban" and "on_member_unban" events params

### ISSUE THREAD

**Issue by dfop02** [Rapptz/discord.py#9474]
### Summary

Add who made the action of event

### What is the feature request for?

The core library

### The Problem

Currently I need fetch the audit_logs to find who made the action and reason (if exists) of it.

### The Ideal Solution

on on_member_ban we receive guild and member/user as params, my suggest is add a new param for who made the action, or the action log that also has all this info

### The Current Solution

today I need do something like that:

```python
async def report(message):
    channel = bot.get_channel(CHANNEL_LISTEN_ID)
    await channel.send(message)
    
@bot.event
async def on_member_ban(guild, member):
    if member.id == bot.user.id:
        ban_log = await guild.audit_logs().find(lambda log: log.action is discord.AuditLogAction.ban)
        await report(f'HELP! <@{ban_log.user.id}> SOMEONE IS BANNING ME!')
        await report('<:pepeshotgun:1083220573708107848>')
    else:
        await report('<:pepecop:1114663204971360316>')
```

Indeed it works when the user banned is not the bot itself, but on this case where bot is being banned, there is no time to get the info and bot leaves the server before action finish.

### Additional Context

This addiction can be a good complement, instead collect info from audit_logs we would have a easiest way to use it.

**Comment by itswilliboy** [comment]
The only information recieved from Discord is the guild ID and the user who was banned. See [the documentation](https://discord.com/developers/docs/topics/gateway-events#guild-ban-add-guild-ban-add-event-fields).

**Comment by dfop02** [comment]
Oh, I see, is not something that we could easily add because depends of Discord's API, my bad. Thank you for your fast answer.

**Comment by LeoCx1000** [comment]
Could be gotten through [`on_audit_log_entry_create`](https://discordpy.readthedocs.io/en/stable/api.html#discord.on_audit_log_entry_create) instead.
