### ISSUE TITLE
Use of deprecated module audioop

### ISSUE THREAD

**Issue by wookie184** [Rapptz/discord.py#9477]
### Summary

discord.py uses the audioop module which will be removed in Python 3.13

### Reproduction Steps

On Python 3.11: `python -Walways -c "import discord"`

Output:
```
...\Python311\Lib\site-packages\discord\player.py:28: DeprecationWarning: 'audioop' is deprecated and slated for removal in Python 3.13
  import audioop
```

### System Information

```
- Python v3.11.2-final
- discord.py v2.3.1-final
- aiohttp v3.8.3
```

### Additional Context

The only usage is here: https://github.com/Rapptz/discord.py/blob/0871b34fc86af49deb6db2436d3e77f5516fdcba/discord/player.py#L633

There doesn't seem to be any standard library alternative, or external library that I can obviously see. It's been a while since it was deprecated so I'm not sure how much chance there is someone will turn it into an external library.

One option could be to try and reimplement it in Python, which seems like it could be doable as it doesn't seem too complicated: https://github.com/python/cpython/blob/036da3bd43aa2593d17d2fb73d4794f9965c577d/Modules/audioop.c#L944, not really sure though.

**Comment by Rapptz** [comment]
Yeah I know. When they voted to deprecated I voiced my concerns but I was more or less ignored. I'm unsure what to do going forward, it can't be in Python because this is low latency.

**Comment by SuperSonicHub1** [comment]
Maintaining `audioop` ourselves is always an option; it is just one C file.

**Comment by AbstractUmbra** [comment]
I actually already began work on this. I just need to wait for a less-than-alpha 3.13 release to test the build and CI.

**Comment by AbstractUmbra** [comment]
> I actually already began work on this. I just need to wait for a less-than-alpha 3.13 release to test the build and CI.

I believe this is ready for testing before signing off.
The repository this is located on is [here](https://github.com/AbstractUmbra/audioop). If you wish to test this then you can install from the git address with `pip` or use the provided dev container setup.
Pending testing and signoff I will push it to PyPi.
