### ISSUE TITLE
`IndexError` - pop from an empty deque

### ISSUE THREAD

**Issue by Iinksafe** [Rapptz/discord.py#9487]
### Summary

The library tries to `.popleft()` from an empty deque when receiving the `READY` event.

### Reproduction Steps

1. Run the code.
2. Wait for the `on_connect` function to be dispatched.
3. 2/5 of the time errors with the error in the title.

### Minimal Reproducible Code

```python
Traceback (most recent call last):
  File "main.py", line 279, in <module>
    asyncio.run(start())
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/asyncio/base_events.py", line 1884, in _run_once
    handle = self._ready.popleft()
IndexError: pop from an empty deque
```

### Expected Results

![image](https://github.com/Rapptz/discord.py/assets/78565096/e9e9ccaf-9958-4657-9556-349ef1f6222a)

### Actual Results

![image](https://github.com/Rapptz/discord.py/assets/78565096/1720a926-b2c3-43b4-9a79-7df5a5f21815)

### Intents

message_content, guild_messages, dm_messages, presences, members, emojis, guilds

### System Information

- Python v3.10.8-final
- discord.py v2.3.1-final
- aiohttp v3.8.3
- system info: Linux 5.19.0-1027-gcp #.29~22.04.1-Ubuntu SMP Thu Jun 22 05:13:17 UTC 2023

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I upgraded today to Python 3.10. This wasn't happening in Python 3.8. Maybe we should check whether `_ready` can be `.popleft()`ed (i.e., check if it's NOT empty before trying to use `.popleft()`).

**Comment by Iinksafe** [comment]
Please note that this only happens 2/5 of the time, not always. So there seems to be a problem with receiving events from the gateway (in specific, the `READY` payload.)

**Comment by Rapptz** [comment]
There's nothing in this traceback that points to anything within the library and seems like an asyncio internal issue.

**Comment by Iinksafe** [comment]
Alright, thanks for the quick response. Closing.
