### ISSUE TITLE
Does Discord.py not support channel categories yet?

### ISSUE THREAD

**Issue by NimecShady** [Rapptz/discord.py#950]
I'm trying to use the create_channel() command and use the 'parent_id=#' argument but I get the error:

TypeError: create_channel() got an unexpected keyword argument 'parent_id'

I assume that discord.py does not have support for creating channels in specific categories? Is there a workaround I can use or is this a limitation of the API at this time. 

Thanks!

**Comment by scragly** [comment]
async (v0.16) doesn't. rewrite (v1.0.0a0) does.

**Comment by NimecShady** [comment]
Ah, I wasn't aware of rewrite.  I assume there would be compatibility issues with my current project if I just switched over eh?

**Comment by scragly** [comment]
Yes. 
Here's the migration info:
http://discordpy.readthedocs.io/en/rewrite/migrating.html

**Comment by NimecShady** [comment]
I appreciate the feedback.  I'm extremely scared about migrating as I have countless hours in my project and I'm scared I wouldn't be able to get the port working properly.

Guess I'll stick with not being able to create channels under categories.  Bummer, but I appreciate it.

**Comment by scragly** [comment]
It's really not too bad. Shouldn't take too long with flip it and there's a tool that can assist with getting you a general headstart, which automatically gives you updated code for rewrite. I personally don't know much about that though, you'd have to ask others.

While rewrite is very stable atm, it's still a in-development version so it's possible that breaking changes can still occur before full release, plus voice is not yet completely done if I remember correctly. So it's definitely a choice you're welcome to make one way or another, no stress either way.

If you do decide to migrate though and need help, you're welcome to join the discord.py support server. There's heaps of people that would be willing to answer questions and have the experience of going through the same thing. 

If you're not already in it, here's the code: r3sSKJJ

**Comment by NimecShady** [comment]
Thank you.
