### ISSUE TITLE
The contents of "guild.categories" becomes an empty list.

### ISSUE THREAD

**Issue by murahito130** [Rapptz/discord.py#9503]
### Summary

"categories" of "guild" obtained by "fetch_guild()" becomes an empty list.

### Reproduction Steps

"guild" was obtained by "fetch_guild()" in the "on_raw_message_delete()" event.
Checking "guild.categories", we found an empty list.

### Minimal Reproducible Code

```python
import discord
client = discord.Client(intents=discord.Intents.all())
@client.event
async def on_raw_message_delete(payload: discord.RawMessageDeleteEvent):
    if not payload.cached_message:
        guild = await client.fetch_guild(payload.guild_id)
        print(guild.categories)
client.run(TOKEN)
```

### Expected Results

A list of category channels in the guild will be displayed.

### Actual Results

An empty list is displayed.

### Intents

discord.Intents.all()

### System Information

- Python v3.11.4-final
- discord.py v2.3.1-final
- aiohttp v3.8.5
- system info: Windows 10 10.0.22621

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

The following code does not cause any problems.
```py
import discord
client = discord.Client(intents=discord.Intents.all())
@client.event
async def on_raw_message_delete(payload: discord.RawMessageDeleteEvent):
    if not payload.cached_message:
        guild = client.get_guild(payload.guild_id)
        print(guild.categories)
client.run(TOKEN)
```

**Comment by Eternity71529** [comment]
did you add some prints inside your conditional statement to see if it's going through?

**Comment by Eternity71529** [comment]
In my testing, I found that the message got removed from the message cache before `on_raw_message_delete` gets dispatched, so I believe there is a chance that your payload doesn't have a cached message, the docs do say that it may or may not exist:

https://discordpy.readthedocs.io/en/stable/api.html#discord.RawMessageDeleteEvent.cached_message

also here is my test code
```py
import discord
client = discord.Client(intents=discord.Intents.all())

@client.event
async def on_raw_message_delete(payload: discord.RawMessageDeleteEvent):

    print(discord.utils.get(client.cached_messages, id = payload.message_id)) #returns None in most of my tests

    if not payload.cached_message: #hence this won't go through
        guild = client.get_guild(payload.guild_id)
        print(guild)
        print(guild.categories)

@client.event 
async def on_message(message):
    print(message.content, message.id)

client.run(TOKEN)
```

**Comment by LostLuma** [comment]
Channels are not included in this API response, they can be obtained via `Guild.fetch_channels` instead.
Do note that fetching the guild and channels here is not useful for you, as if you're running with the `guilds` intent enabled the cached version (via `Client.get_guild`) will always be up-to-date, and not use up part of your rate limits like fetching them does. If your bot grows this can cause issues for you.

Also @Eternity71529 you might want to read the questions people ask more carefully, neither of your posts answer what OP is talking about.

**Comment by Eternity71529** [comment]
mbmb I somehow started thinking with the latter part of the code snippet instead of the first one, Apologies!
