### ISSUE TITLE
Rich Presence

### ISSUE THREAD

**Issue by webmsgr** [Rapptz/discord.py#951]
Is this currently supported?

**Comment by NCPlayz** [comment]
No

**Comment by NCPlayz** [comment]
There have been unconfirmed rumors that it will be a feature in the near-future

**Comment by DismissedGuy** [comment]
I'd personally rather have a nice wrapper than it being built in into d.py, but oh well

**Comment by tilda** [comment]
Wouldn't work, RP is on client side RPC

**Comment by MinnDevelopment** [comment]
Bots can receive RPC but not set it. It is not client-side.

**Comment by Rapptz** [comment]
Dupe of #890
