### ISSUE TITLE
Middlewares and Filters

### ISSUE THREAD

**Issue by gfnprodev** [Rapptz/discord.py#9512]
### Summary

Add Middlewares for discord.py

### What is the feature request for?

The core library

### The Problem

![image](https://github.com/Rapptz/discord.py/assets/104313670/40cb3e71-b463-41b2-a60b-c5043e9d70dc)

Main URL: https://docs.aiogram.dev/en/dev-3.x/dispatcher/middlewares.html

A striking example is the opening/closing of database sessions. Example: The user enters a command, a session is opened through the middleware, the session is thrown into the command handler, functions are performed from the database (if they are there) and then the session is closed.

### The Ideal Solution

https://docs.aiogram.dev/en/dev-3.x/dispatcher/middlewares.html

**Comment by No767** [comment]
FYI for opening and closing database connection pools, you don't even need this. (The `advanced_example.py` example clearly demonstrates this). I fail to understand why this would be a useful feature to implement.

**Comment by Rapptz** [comment]
Python has this feature natively, they're called (async) context managers. If you need something other than resource cleaning there's also the various [`before_invoke`](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.Command.before_invoke) and [`after_invoke`](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.Command.after_invoke) hooks. Though they're not available for app commands.

**Comment by gfnprodev** [comment]
I can`t find advanced_example, only advanced_startup. In your example, opening only 1 session(Pool), but middlewares handling all handlers. Like this:


User input slash command /start -> Creating database session -> Using session in handler -> closing session after handler

You can see how can i use it in my pet project - https://github.com/gfnprodev/WordleTG

src -> tgbot -> middlewares 

And you can see in handler how can i use this session https://github.com/gfnprodev/WordleTG/blob/master/src/tgbot/dialogs/user/handlers/wordle_game.py 

handler on_click_play_choosed_category. Actually in this Project i used aiogram_dialog. Aiogram dialog stores my Holder in middleware_data.

**Comment by gfnprodev** [comment]
Sry my bad closing
