### ISSUE TITLE
utils.escape_markdown escapes `-` in the middle of string (doesn't work in link text)

### ISSUE THREAD

**Issue by Jackenmen** [Rapptz/discord.py#9516]
### Summary

utils.escape_markdown() function adds `\` to `-` when it doesn't act as a bullet point which breaks rendering in link text (e.g. `[escaped text](url)`)

### Reproduction Steps

1. Install discord.py 2.3.1 (it didn't work like this in 2.2.x).
2. Run the code provided in minimal repro below.
3. See the issue.

### Minimal Reproducible Code

```python
escaped_text = discord.utils.escape_markdown("a string with - in it")
embed = discord.Embed(description=f"[{escaped_text}](https://google.com)")
await ctx.send(embed=embed)
```

### Expected Results

I expected the escaped text to render normally, e.g.:
![image](https://github.com/Rapptz/discord.py/assets/6032823/75bf425b-6f03-47e5-b393-1807946f847d)

The above is the behavior on discord.py 2.2.3, the exact string is:
```py
'a string with - in it'
```

### Actual Results

The text has an extra `\` that is rendered by the Discord client:
![image](https://github.com/Rapptz/discord.py/assets/6032823/ea73630a-1e39-4b9a-8973-1a4dc90957c9)

This corresponds to the following string:
```py
'a string with \\- in it'
```

### Intents

discord.Intents.all()

### System Information

- Python v3.8.17-final
- discord.py v2.3.1-final
- aiohttp v3.8.5
- system info: Linux 5.15.0-78-generic #85-Ubuntu SMP Fri Jul 7 15:25:09 UTC 2023

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by No767** [comment]
You just need to set the arg `as_needed` to True

**Comment by Jackenmen** [comment]
I know that this works around the problem but I'm not sure it's really the proper solution (hence the bug report) here due to it opening you up to syntax abuse, as you mentioned.

**Comment by Rapptz** [comment]
I've fixed this particular case but this issue will most likely happen regardless cause I think the new link parser doesn't like escaped characters anymore, e.g.
![image](https://github.com/Rapptz/discord.py/assets/1695103/615b3858-f2b1-475d-8579-126e0ece4696)
