### ISSUE TITLE
.connect() loop and no return 

### ISSUE THREAD

**Issue by issamansur** [Rapptz/discord.py#9546]
### Summary

[VocalGuildChannel].connect() doesn't work

### Reproduction Steps

I trid to execute my script. But it doesn't work, where I call .connect().

### Minimal Reproducible Code

```python
async def join(ctx):
    if not await is_chat(ctx):
        return
    user_voice: discord.VoiceClient = ctx.message.author.voice

    if not user_voice:
        await ctx.send(ANSWERS.NO_VOICE_USER)
        return

    client_voice: discord.VoiceClient = ctx.voice_client
    if client_voice and client_voice.is_connected():
        if client_voice.channel.id == user_voice.channel.id:
            await ctx.send(ANSWERS.JUST_THERE)
        else:
            await ctx.send(ANSWERS.JUST_BUSY)
        return
    print('start')
    client_voice = await user_voice.channel.connect(timeout=60.0, self_deaf=True)
    print('end')
    await ctx.channel.send(ANSWERS.ON_JOIN)
    return client_voice
```

### Expected Results

I expect that I can take 'client_voice' 

### Actual Results

At start - all good:
# logs
```
start
2023-08-29 14:07:00 INFO     discord.voice_client Connecting to voice...
2023-08-29 14:07:00 INFO     discord.voice_client Starting voice handshake... (connection attempt 1)
2023-08-29 14:07:00 INFO     discord.voice_client Voice handshake complete. Endpoint found us-west8199.discord.media
```
But script loop on 'timeout' time - 60 seconds and then -
# logs
```
023-08-29 14:08:01 WARNING  discord.gateway Shard ID None has stopped responding to the gateway. Closing and restarting.
2023-08-29 14:08:46 INFO     discord.voice_client The voice handshake is being terminated for Channel ID ############# (Guild ID #################)
```

### Intents

intents=discord.Intents.all()

### System Information

aiohttp==3.8.5
discord==2.3.2
discord.py==2.3.2
PyNaCl==1.5.0
requests==2.31.0

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by imayhaveborkedit** [comment]
The voice connection code for the library has been rewritten.  If you're still having this issue, do you mind seeing if it still happens on the latest commit?

**Comment by issamansur** [comment]
I found the trouble - it proxy that blocking endpoint. Thanks for rewrite voice, I saw code, it looks better for me :)
