### ISSUE TITLE
App commands in cogs annotated with `@staticmethod` error when loading

### ISSUE THREAD

**Issue by Sophon96** [Rapptz/discord.py#9551]
### Summary

When defining commands with the `@discord.app_commands.command()` decorator with methods in a cog decorated with `@staticmethod`, a `TypeError` is raised with message "command function must be coroutine function."

### Reproduction Steps

1. Create a cog
2. Define an app command with a function signature such as
```py
@discord.app_commands.command()
@staticmethod
async def my_command(interaction: discord.Interaction):
  # ...
```
3. Add code to load the cog
4. Get `TypeError: command must be coroutine function` when running (though no type errors are reported by Pylance).

Such an example is attached in images (and see below):
![image](https://github.com/Rapptz/discord.py/assets/71684640/9b6ce830-6b72-4547-b97a-2162d545317f)
![image](https://github.com/Rapptz/discord.py/assets/71684640/2fc569bc-0f81-4dae-b734-2ea1af83f020)

### Minimal Reproducible Code

```python
import discord
from discord.ext import commands


class MyCog(commands.Cog):
    @discord.app_commands.command()
    @staticmethod
    async def my_command(interaction: discord.Interaction):
        await interaction.response.send("You will never see this")


class MyBot(commands.Bot):
    async def setup_hook(self):
        await self.add_cog(MyCog())


bot = MyBot("!", intents=discord.Intents.default())
bot.run("TOKEN")
```

### Expected Results

A command is registered, as usual.

### Actual Results

```py
Traceback (most recent call last):
  File "/app/minrepo.py", line 5, in <module>
    class MyCog(commands.Cog):
  File "/app/minrepo.py", line 6, in MyCog
    @discord.app_commands.command()
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 1965, in decorator
    raise TypeError('command function must be a coroutine function')
TypeError: command function must be a coroutine function
```

### Intents

Just the defaults (irrelevant)

### System Information

```
- Python v3.11.5-final
- discord.py v2.3.2-final
- aiohttp v3.8.5
- system info: Linux 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12)
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
`staticmethod` aren't supported for any type of commands due to limited usability. If you want this then define it outside of a class.

**Comment by Sophon96** [comment]
Thanks for replying.
