### ISSUE TITLE
Flagconverter bool flags

### ISSUE THREAD

**Issue by TheKidThatCodes** [Rapptz/discord.py#9552]
### Summary

See https://github.com/dolfies/discord.py-self/issues/563

### What is the feature request for?

discord.ext.commands

### The Problem

See https://github.com/dolfies/discord.py-self/issues/563

### The Ideal Solution

Implement https://github.com/dolfies/discord.py-self/issues/563 in this because it is useful and user friendly

### The Current Solution

See https://github.com/dolfies/discord.py-self/issues/563

### Additional Context

See https://github.com/dolfies/discord.py-self/issues/563

**Comment by Rapptz** [comment]
This is as designed not supported. See here: https://canary.discord.com/channels/336642139381301249/603069307286454290/833852644422451250 in the d.py server for the reason. I'll copy paste it here for posterity.

> Flags aren't meant to be posix flags or command line flags. They're meant to be the type of flag syntax that a regular user without experience with a CLI can use so to that end the user experience is meant to be mostly consistent and simple. To you and to me not passing a value to something to toggle comes as second nature but to most people I imagine it's confusing. 
>
> I don't think I'll add this. The syntax with the default configuration looks incredibly odd (`delete:`) because it looks like it expects a value there. There's no real harm in typing `delete: yes` or whatever.
