### ISSUE TITLE
AttributeError: 'Role' object has no attribute 'roles'

### ISSUE THREAD

**Issue by OrangeFlare** [Rapptz/discord.py#956]
When running this command

```
    @asyncio.coroutine
    async def cmd_confirm(self, author, server):
        """
        Usage:
            {command_prefix}confirm
            
        Confirms that you are above the legal age to view pornographic content according to your state laws thus giving you access to the NSFW and LEWD channels
        """

        roles = discord.utils.get(server.roles, name="18+")
        await discord.Client.add_roles(author, roles)
```

I get this error

`[ERROR:bot] Exception in on_message
Traceback (most recent call last):
  File "D:\Git\MonikaBot\musicbot\bot.py", line 2550, in on_message
    response = await handler(**handler_kwargs)
  File "D:\Git\MonikaBot\musicbot\bot.py", line 1924, in cmd_confirm
    await discord.Client.add_roles(author, roles)
  File "C:\Users\[USERNAME]\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 2915, in add_roles
    new_roles = utils._unique(role.id for role in itertools.chain(member.roles, roles))
AttributeError: 'Role' object has no attribute 'roles'`

What the hell does 'Role' object has no attribute 'roles'

Sorry it seems like you get this AttributeError Question asked a lot but this one I can not find anywhere nor can I find what I'm doing wrong

**Comment by datmellow** [comment]
You are using:
```await discord.Client.add_roles(author, roles)```

which is wrong. Client is the name of the variable that you call ``.run`` on


Also questions like this should be asked in the server : https://discord.gg/r3sSKJJ

**Comment by OrangeFlare** [comment]
Sorry about asking within the wrong place
