### ISSUE TITLE
.from_dict() classmethod for discord.Message

### ISSUE THREAD

**Issue by PearooXD** [Rapptz/discord.py#9564]
### Summary

This would be the same as discord.Embed.from_dict(), but with a Discord Message Object.

### What is the feature request for?

The core library

### The Problem

When a bot wants to add customizability, the developer either has to make a bunch of if statements to check if a user wants this and that for the message, or they have to make a request to Discord's API itself, which partly eliminates the purpose of discord.py.
For example: This is how a code for customizability would usually look like now:
```py
embed = {
    "title": "This will be the second embed (Message.embeds[1]).",
    "description": "If a bot has a web dashboard, the dashboard will save the embed in a JSON format that is following the same structure as what is specified in the Dev Docs' 'Embed Object' section."
}
messageObject = {
    "content": "Hello, this is a message!",
    "embeds": [
        discord.Embed(title="This message is customizable.", description="The user can remove the message's content, or the embed(s), or the attachments, or all of them, leaving only one thing to be used.").set_footer("(they can remove footers and authors too, however, this embed can be replaced using from_dict())"), discord.Embed.from_dict(embed)],
    "attachments": None
        
await ctx.send(content=messageObject["content"], embeds=messageObject["embeds"]) # this can, of course, be made with more variables in mind, such as mention_author, tts, components, etc.
```

### The Ideal Solution

If there was a `ctx.send.from_dict()` classmethod, it would be easier if an online dashboard stores customized messages according to Discord's Message Object format:
```py
embed = {
    "title": "This will be the second embed (Message.embeds[1]).",
    "description": "If a bot has a web dashboard, the dashboard will save the embed in a JSON format that is following the same structure as what is specified in the Dev Docs' 'Embed Object' section."
}
messageObject = {
    "content": "Hello, this is a message!",
    "embeds": [
        discord.Embed(title="This message is customizable.", description="The user can remove the message's content, or the embed(s), or the attachments, or all of them, leaving only one thing to be used.").set_footer("(they can remove footers and authors too, however, this embed can be replaced using from_dict())"), discord.Embed.from_dict(embed)],
    "attachments": None
        
await ctx.send.from_dict(messageObject)
```

This saves time.

### The Current Solution

Of course, you could hardcode every single check to see if the web dashboard told you to reply to a message, or to include an attachment, or to include buttons, or anything else that might be to the user's liking. But saving time can be really useful in coding. This is why most people use `discord.Colour.red()` instead of just using a hex code; it's easier.

### Additional Context

If something's unclear or if my phrasing sounds weird, ask for clarification in the replies. I could say English is not my first language, but to be honest, I'm just extremely high.
Edit: formatting

**Comment by Rapptz** [comment]
Message is a deeply nested and complicated structure. It is not viable to provide these methods for it. For example your simple example failed to address the channel or guild or author of the message.

**Comment by Soheab** [comment]
I think you literally want to unpack the dict?
```py
my_dict = {"hello": "world", "foo": "bar"}

some_method(**my_dict)
# ^ will send it as `hello="world", foo="bar"`
```
