### ISSUE TITLE
What's `-fec true -packet_loss 15`

### ISSUE THREAD

**Issue by Alicey0719** [Rapptz/discord.py#9565]
### Summary

The `-packet_loss 15` option makes the sound noisy. Is this necessary?
https://github.com/Rapptz/discord.py/blob/e67d00502d91c15914c640e1aae40e15544cdfa1/discord/player.py#L443
### Reproduction Steps

```
discord.FFmpegOpusAudio(str(row_source[0]),bitrate=512, before_options='-re ',options=f'-c:a libopus -rtbufsize 512M -filter:a "volume={MUSIC_VOLUME}"')
```

### Expected Results

Should sound Clean, but it sounds noisy.

### Actual Results

Noisy sound flows

### Intents

intents.guilds = True intents.guild_messages = True intents.voice_states = True intents.members = True intents.message_content = True

### System Information

```
- Python v3.11.5-final
- discord.py v2.4.0-alpha
    - discord.py metadata: v2.4.0a4919+ge67d0050
- aiohttp v3.8.5
- system info: Linux 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
This is a bad interaction with the `-re` flag which reads at a native frame rate. The `packet_loss` parameter is just the [expected packet loss rate](https://superuser.com/a/1240735) for Opus. The 15% default value is just a conservative default. If what you're doing makes it so this doesn't apply to you, then you're free to change the ffmpeg settings yourself as you've done.
