### ISSUE TITLE
Update basic_voice.py in examples

### ISSUE THREAD

**Issue by Lefeus** [Rapptz/discord.py#9566]
### Summary

Update basic_voice.py in examples

### What is the feature request for?

The core library

### The Problem

basic_voice.py is deprected.

### The Ideal Solution

Instead of this do slash commands with basic voice.

### The Current Solution

Instead of this do slash commands with basic voice.

**Comment by No767** [comment]
No it's not deprecated and using regular prefixed commands still works. For consistency, prefixed commands would still be preferred in the example `basic_voice.py`.
