### ISSUE TITLE
add check for invalid number used for `app_commands.Choices.value`

### ISSUE THREAD

**Issue by modernNeo** [Rapptz/discord.py#9568]
### Summary

raise error if user tries to specify an unsupported integer for app_commands.Choices value

### What is the feature request for?

The core library

### The Problem

due to JavaScript limitations on discord's side of thing, the `value` specified for `app_commands.Choice` object cannot exceed the [JavaScript Max for an Integer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER).

If someone does try to use a number that exceed that limit, there is no error on discord.py side, and all that the discord UI interface shows is `Loading options failed` but no indication of what happened which can be pretty vague as to whether its a user error, coding error, discord.py error or something on discord's side of things

### The Ideal Solution

For discord.py itself to raise an error if someone tries to use an int for the `value` that exceeds the JavaScript maximum. 

While I acknowledge this is not discord.py's responsibility to handle this particular use case since its not a limitation imposed by this library, I also think it's not too hard to raise an exception for this use case and can be pretty helpful for users who are not aware that discord is not properly handling such numbers in their front-end despite using them quite extensively when it comes to any IDs for any discord Objects.

**Comment by Rapptz** [comment]
I don't really do these types of checks, especially since there's no way to do it without everyone paying the price for it for every Choice being created regardless of internal type. Unfortunately it's just one of the things you need to be aware of when working with Discord as a whole. The same caveat applies to regular `int` parameters in app commands as well.

**Comment by modernNeo** [comment]
that's fair enough and what I figured you'd say regarding automatic checking but upon further investigation I see that in cases like this, if the user does use an `int` value that is larger than what Javascript supports, the response from discord's API actually does give an indication of what went wrong in this block of code below. 
https://github.com/Rapptz/discord.py/blob/3530a0f2a8926d24eb19ad1b9ffe35ee74fe5a7e/discord/webhook/async_.py#L177-L221


![Screenshot from 2023-09-16 19-16-08](https://github.com/Rapptz/discord.py/assets/14242088/ae982b05-052f-4864-8507-ed4be4cc5f4e)


However, the discord.py module choose to not report that error [code 400] as you can see here


https://github.com/Rapptz/discord.py/blob/3530a0f2a8926d24eb19ad1b9ffe35ee74fe5a7e/discord/interactions.py#L1027-L1035

I am wondering why you went the route of suppressing the error instead of at least logging it to users know something may have gone amiss?

**Comment by Rapptz** [comment]
The 400 is not ignored. It's evident in that code block, the `else` block raises `HTTPException`.

**Comment by modernNeo** [comment]
yes but what I mean is that the calling function does not do anything with that exception, I dont see it logged anywhere, it just silently gives up on the error.

do you see any different behaviour [with logs or otherwise] on your end?

**Comment by Rapptz** [comment]
The call is suppressed [here](https://github.com/Rapptz/discord.py/commit/4e09c34bbbd034307dbad2713780de60934fe15a) because the error can't be handled and propagating it leads to strange behaviour. I could add a logging call to it if necessary but generally any exception raised within autocomplete just leads to bad state.

**Comment by Rapptz** [comment]
I've added the logging call in the newest commit https://github.com/Rapptz/discord.py/commit/9e2f2cb3af30c9d4c6d3ff4f7850832c05488d6f. Thanks.

**Comment by modernNeo** [comment]
>I could add a logging call

I think that would really be helpful. I can see why you don't want to handle the exception itself but logging it seems really beneficial.
