### ISSUE TITLE
discord.Colours won't allow strings

### ISSUE THREAD

**Issue by TehRayinator** [Rapptz/discord.py#957]
I'm writing a code that changes a role's colour in a rainbow sequence.
My code is as follows
`discord.Colour('#%02x%02x%02x' % (RGB[0],RGB[1],RGB[2]))`

I'm running through an HSV that has been converted to RGB and am converting it into Hexadecimal.
Upon running the code the following error comes up:

> discord.errors.HTTPException: BAD REQUEST (status code: 400)

**Comment by Nekorooni** [comment]
discord.Colour takes an int so convert the hex to int or something like `0xff00ff`.

Though I recommend not rapidly changing a role color in a background task for various reasons.

**Comment by khazhyk** [comment]
http://discordpy.readthedocs.io/en/latest/api.html#discord.Colour

The value argument is an integer, not a string. There isn't really a good reason to make it accept a string. Accepting an r,g,b tuple might make sense as a convinience thing, but converting rgb tuple to a single number is pretty straightforward `number = r<<16 + g<<8 + b`
