### ISSUE TITLE
It takes a minute for the client to disconnect from voice channel, if bot is forcefully disconnected from voice channel.

### ISSUE THREAD

**Issue by Haiz14** [Rapptz/discord.py#9575]
### Summary

The bot tried to reconnect to a voice channel for a minute before disconnecting from voice channel, if the bot is forcefully disconnected.

### Reproduction Steps

-  connect to a voice channel
-  disconnect bot manually by clicking on disconnect button in bot's profile
- try to reconnect under 60 secs, via `voice_channel.connect()` you'll get error `Error: Already connected to voice channel`.
- After 60-65 secs you can connect and there won't be any error.
The logger shows 
```text
2023-09-22 10:24:04 INFO     discord.voice_client Disconnected from voice by force... potentially reconnecting.
2023-09-22 10:24:04 INFO     discord.voice_client Starting voice handshake... (connection attempt 2)
2023-09-22 10:25:04 INFO     discord.voice_client The voice handshake is being terminated for Channel ID 1153582285950558240 (Guild ID 1059338776146612254)
2023-09-22 10:25:04 INFO     discord.voice_client Reconnect was unsuccessful, disconnecting from voice normally...
```
![disconnect button](https://github.com/Rapptz/discord.py/assets/68465021/a36caeb5-18ca-4e9e-b7ae-62feda0b23c5) (Bot is forcefully disconnected via this button)

### Minimal Reproducible Code

```python
import discord
from discord.ext.commands import Bot

VOICE_CHANNEL_ID = ""
TOKEN = ""

PREFIX = "!"
DEVELOPER_INFO_MESSAGE = "If this error repeats, please snap a pic of this message and send it to the developer. They'll be happy to help you get back on track!"

intents = discord.Intents.default()
intents.message_content = True
intents.voice_states = True

bot = Bot(command_prefix=list(PREFIX), intents=intents) 


@bot.event
async def on_ready():
    #await add_help_command_with_embed(bot)
    bot.player = await setup_player(bot)

    print('Music Bot Ready')


async def setup_player(bot):
    voice_channel = await bot.fetch_channel(VOICE_CHANNEL_ID)
    player = await voice_channel.connect()

    return player


@bot.command(aliases=['r'])
async def reset(ctx):
    """
 Give the radio a good ol' reset! Use this command if the radio isn't working for some reason.
    """

    try:

        ctx.bot.player = await setup_player(ctx.bot)
        await ctx.send("Bot reconnected")
    except Exception as e:
        await ctx.send("Error: " +  str(e))

bot.run(TOKEN)
```

### Expected Results

- Fill in voice channel id and bot token
- run the code
- manually disconnect the bot
- run `!r` command, and the bot should reconnect

### Actual Results

The bot doesn't reconnect for 60-65 secs, after that it reconnect normally.

### Intents

message_content, voice_states

### System Information

❯ python -m discord -v
- Python v3.11.5-final
- discord.py v2.3.2-final
- aiohttp v3.8.5
- system info: Linux 4.14.186+ #1 SMP PREEMPT Thu Nov 17 15:43:57 CST 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by imayhaveborkedit** [comment]
This will be fixed with #9525

**Comment by Haiz14** [comment]
But why is it trying to reconnect for 60secs? If it's disconnected forcefully the disconnect.

**Comment by imayhaveborkedit** [comment]
That's just how long the timeout is.  If it's a weird state issue this pr might fix it.

**Comment by Haiz14** [comment]
Yupp should be a weird state issue, Even if I try to disconnect after forcefully disconnecting the bot (via disconnect button), I still get `Error: Already connected to a voice channel`
```python
import discord
from discord.ext.commands import Bot

VOICE_CHANNEL_ID = ""
TOKEN = ""

PREFIX = "!"
DEVELOPER_INFO_MESSAGE = "If this error repeats, please snap a pic of this message and send it to the developer. They'll be happy to help you get back on track!"

intents = discord.Intents.default()
intents.message_content = True
intents.voice_states = True

bot = Bot(command_prefix=list(PREFIX), intents=intents) 


@bot.event
async def on_ready():
    #await add_help_command_with_embed(bot)
    bot.player = await setup_player(bot)

    print('Music Bot Ready')


async def setup_player(bot, disconnect = False):
    if disconnect: await bot.player.disconnect()
    voice_channel = await bot.fetch_channel(VOICE_CHANNEL_ID)
    player = await voice_channel.connect()

    return player


@bot.command(aliases=['r'])
async def reset(ctx):
    """
 Give the radio a good ol' reset! Use this command if the radio isn't working for some reason.
    """

    try:

        ctx.bot.player = await setup_player(ctx.bot, True)
        await ctx.send("Bot reconnected")
    except Exception as e:
        await ctx.send("Error: " +  str(e))

bot.run(TOKEN)

```

**Comment by imayhaveborkedit** [comment]
In that example you would want to use `disconnect(force=True)`, but yeah the bot thinking it's connected when it isn't is one of the bugs fixed in that pr.

**Comment by Haiz14** [comment]
Thks, you are really great developer. You can actually make sense of the code in this short period of time. If you gave it to me, i  would certainly be slower. Thks
