### ISSUE TITLE
Add support for `default_values` of select menus

### ISSUE THREAD

**Issue by Robin5605** [Rapptz/discord.py#9579]
### Summary

The Discord API recently introduced support for pre-selecting options for user, role, mentionable, and channel select menu components. It would be nice to have that support in discord.py

### What is the feature request for?

The core library

### The Problem

As far as I know this has not been implemented yet in the core library, so users are not able to specify what default options they want for the pre-filled select menu types.

### The Ideal Solution

A `default_values` keyword argument for `UserSelect`, `RoleSelect`, `MentionableSelect`, and `ChannelSelect` that accept a `list[discord.User]`, `list[discord.Role]`, `list[discord.User | discord.Role]`, and `list[discord.abc.GuildChannel | discord.abc.PrivateChannel]` respectively.

### The Current Solution

None in the library as far as I'm aware. Users would have to monkeypatch this functionality in.

### Additional Context

I would like to attempt to implement this.

**Comment by Soheab** [comment]
See #9577

**Comment by Robin5605** [comment]
Sorry, missed that issue. Closing this as duplicate then.
