### ISSUE TITLE
Request to add regex for Transformers or allow stopping user submit arguments that aren't in suggestions.

### ISSUE THREAD

**Issue by PlusPlusMan** [Rapptz/discord.py#9597]
### Summary

Argument validation for cases where it can have more than 25 values.

### What is the feature request for?

The core library

### The Problem

Transformers are a great way to restrict the user from submitting unwanted arguments. We can use Literal type hint to let user choose only values from suggestions. But what if the pool of available arguments is bigger than 25? In my bot I tried to accomplish it in command that takes time string in a format `%H:%M`. I already have a choices' generator for it, and it would be great if there was a way to let the user only select arguments from suggestions. I propose adding similar functionality as in Literal type hint, but with regex, or updating the Transformer class (if it's even possible).

### The Ideal Solution

Either allow for type hints that are regex, example:
```python
class TimeFormat(typing.Protocol):
    #This is regex type hint for values that are in time format: %H:%M
    @staticmethod
    def __subclasshook__(cls):
        if re.match(r'^([01]\d|2[0-3]):[0-5]\d$', cls):
            return True
        return False

@client.tree.command()
async def time(interaction: discord.Interaction, time: TimeFormat):
    await interaction.response.send_message(f"time: {str(time)}, type {type(time)}")
```

Or allow to validate incorrect values in Transformer, example:
```python
class TimeTransformer(app_commands.Transformer):
    async def transform(self, interaction: discord.Interaction, value: str) -> Time:
        return Time.from_string(value, "%H:%M")

    async def autocomplete(self, interaction: discord.Interaction, value: str) -> List[app_commands.Choice[str]]:
        choices = await time_choices(value)  # This is a list of app_commands.Choices that changes based on the current/value
        if not choices:
            raise Exception("No choices found")  # This would be custom exception like BadArgument, that highlihts the field in red and doesn't allow to submit
        return choices

@client.tree.command()
async def time(interaction: discord.Interaction, time: app_commands.Transform[Time, TimeTransformer]):
    await interaction.response.send_message(f"time: {str(time)}, type {type(time)}")
```

### Additional Context

Without this functionality, it might look misleading for the user. He cannot choose values different from suggested for every argument in the command, outside this only one, that also shows suggestions, but doesn't stop him from submitting incorrect values like 'a' for time.

**Comment by PlusPlusMan** [comment]
> This is very much in the realm of "do it yourself". That's what transformers are for, validation and customizing parameters.

As I understand, there is no way to restrict the user in the same way as in boolean or Literal for my case with time

**Comment by Rapptz** [comment]
Yes, because autocomplete parameters are just augmentations of pure str, int, or float parameters with the choices being there to *guide* the user. bool/Literal get converted into choices which clamps the possible input.
