### ISSUE TITLE
Choice default value does not work correctly

### ISSUE THREAD

**Issue by downloadpizza** [Rapptz/discord.py#9605]
### Summary

the Choice default value either refuses to convert or makes wrong assumptions about other code

### Reproduction Steps

Try to make a default value for a Choice[int]

### Minimal Reproducible Code

```python
import discord
from discord import app_commands, Interaction
from discord.app_commands import Choice

from discord.ext.commands import Bot

import keys

class Client(Bot):
    def __init__(self, intents):
        self.polls = []
        super().__init__(intents=intents, command_prefix=[], help_command=None)


intents = discord.Intents.default()
intents.typing = False
intents.presences = False
intents.message_content = True

client = Client(intents=intents)


@client.event
async def on_ready():
    print(f'-------------------------')
    print(f'Logged in as {client.user}')
    print(f'-------------------------')
    synced = await client.tree.sync(guild=discord.Object(id=keys.SERVER_ID))
    print(synced)
    print(f"Synced {len(synced)} command(s).")


@client.tree.command(name="boople", description="the same but on a tree", guild=discord.Object(id=keys.SERVER_ID))
@app_commands.choices(foobar=[
    Choice(name="foo", value=0),
    Choice(name="bar", value=1),
])
async def weekend_poll_cmd(interaction: Interaction, foobar: Choice[int] = Choice(name="", value=0)): # this fails since the transformer says
    # `TypeError: invalid default parameter type given (<class 'discord.app_commands.models.Choice'>), expected (<class 'int'>, <class 'NoneType'>)`
# async def weekend_poll_cmd(interaction: Interaction, foobar: Choice[int] = 0): # this fails since it calls 0.value
    await interaction.response.send_message(f"Response: {foobar.value}")


if __name__ == '__main__':
    client.run(keys.BOTTOKEN)
```

### Expected Results

Either allow me to make the default argument a `Choice` or correctly convert the int to a choice with value 0

### Actual Results

Fails in either of the ways shown in the code near `async def weekend_poll_cmd`

### Intents

intents = discord.Intents.default() intents.typing = False intents.presences = False intents.message_content = True

### System Information

- Python v3.10.11-final
- discord.py v2.3.2-final
- aiohttp v3.8.5
- system info: Windows 10 10.0.19045

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
This is by design. It's to prevent people from relying on object identity.
