### ISSUE TITLE
bug(Member): _flags attribute missing

### ISSUE THREAD

**Issue by drlove2002** [Rapptz/discord.py#9609]
### Summary

 AttributeError in discord/member.py - 'Member' object has no attribute '_flags'

### Reproduction Steps

- Run the bot with the simplest code.
- Observe the traceback.

### Expected Results

The bot should start without any errors

## Stack Traceback
![image](https://github.com/Rapptz/discord.py/assets/39167433/516f7d76-4431-465e-a2de-e94e92e18ea3)

**The bot encountered an AttributeError.**

### Intents

33323

### System Information

```
- Python v3.10.12-final
- discord.py v2.3.2-final
- aiohttp v3.8.5
- system info: Linux 6.2.0-34-generic #34~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 13:12:03 UTC 2
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

This happens sometimes, so it might be hard to reproduce the bug.

**Comment by No767** [comment]
`_flags` is meant to be a private attr (really anything prefixed with `_`) so it's not meant to be publicly accessed. If you need to access the flags of the member, please use `Member.flags` instead

**Comment by drlove2002** [comment]
> `_flags` is meant to be a private attr (really anything prefixed with `_`) so it's not meant to be publicly accessed. If you need to access the flags of the member, please use `Member.flags` instead

I'm not accessing the _flags attr. I'm simply running the bot and this error is happening. You can see in traceback, it's happening when it's doing `old_member = Member._copy(member)`. I'm just running the bot with `bot.run()`

```py
import sys
from os import environ

from mainbot.core.bot import BaseMainBot
from mainbot.utils import logging

bot = BaseMainBot()
logger = logging.get_logger(__name__)


def main():
    bot.run(
        environ["TOKEN"],
        log_handler=logging.ch,
        log_formatter=logging.ch.formatter,
        log_level=logging.ch.level,
    )


if __name__ == "__main__":
    try:
        if sys.platform not in ("win32", "cygwin", "cli"):
            import uvloop

            uvloop.install()
    except ImportError:
        logger.info("UVLoop can't be installed in windows")
    main()
```

**Comment by Rapptz** [comment]
This is pretty strange, the attributes are always copied and given as-is. Your line is also offset by 1, which is kind of weird. Would you mind providing some debug logs to see where the issue is? It feels impossible for this attribute to not be set because it's always set in every location where a Member is constructed, whether in `Member._copy` or `Member.__init__`.

**Comment by drlove2002** [comment]
![image](https://github.com/Rapptz/discord.py/assets/39167433/634a1084-65a0-4d6c-9818-0814d9ed3621)

For some reason `_flags` were deleted from `__init__` at line 359.

I reinstalled discord.py and now it's working fine.

This issue can be closed
