### ISSUE TITLE
Error when loop over guild.fetch_scheduled_events()

### ISSUE THREAD

**Issue by basox70** [Rapptz/discord.py#9615]
### Summary

Error in `async for event in guild.fetch_scheduled_events()`

### Reproduction Steps

- Create a task loop
- Have a for loop over bot guilds
- Have a for loop ovet guild event

### Minimal Reproducible Code

```python
@tasks.loop(minutes=1)
async def event_reminder():
    for guild in my_bot.guilds:
        async for event in guild.fetch_scheduled_events():
            my_bot.logger.debug(event.name)
```

### Expected Results

loop over events (like guild.fetch_members() looping over each member)

### Actual Results

```
Traceback (most recent call last):
  File "Path_to_project\.venv\lib\site-packages\discord\ext\tasks\__init__.py", line 239, in _loop
    await self.coro(*args, **kwargs)
  File "Path_to_project/bot.py", line 357, in event_reminder
    async for event in guild.fetch_scheduled_events():
TypeError: 'async for' requires an object with __aiter__ method, got coroutine
```

### Intents

discord.Intents.default()

### System Information

```
$ .venv\Scripts\python.exe -m discord -v
- Python v3.8.10-final
- discord.py v2.3.2-final
- aiohttp v3.8.4
- system info: Windows 10 10.0.19045
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
This method is a coroutine not an async iterator, you call it and a list is returned which you iterate over.
