### ISSUE TITLE
Rename channel and Change category multiple times, does not work!

### ISSUE THREAD

**Issue by muhy06** [Rapptz/discord.py#9626]
### Summary

Rename channel and Change category multiple times, does not work!

### Reproduction Steps

I am trying to change category of a channel and changing its name. It works 1st, 2nd and 3rd time, but when you try after that renaming will not work at all on that channel. It will change category but rename will not work. I am not even getting the error.

### Minimal Reproducible Code

```python
await channel.edit(category=category_name)
await channel.edit(name=name)
```

### Expected Results

Should be able to rename channel multiple times while changing category

### Actual Results

After renaming 3 times, channel name changing does not work when using changing category each time as well.

### Intents

discord.Intents.all()

### System Information

- Python v3.11.1-final
- discord.py v2.2.2-final
- aiohttp v3.8.3
- system info: Windows 10 10.0.19045

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by No767** [comment]
Best guess is that you are being rate limited

**Comment by Rapptz** [comment]
The rate limit for channel name changes is twice per 10 minutes. It's very strict because they don't want you to do this. The library by default sleeps until the rate limit is exhausted before attempting the request.

**Comment by LeoCx1000** [comment]
No. Rate limits are set and enforced by discord, not by the library. And yes, the rate limits for bots are different to the ones for users, as you noticed.
