### ISSUE TITLE
Add a interaction completion event.

### ISSUE THREAD

**Issue by EncryptMan** [Rapptz/discord.py#9627]
### Summary

Add a function like on_view_interaction_complete in discord.ui.View class.

### What is the feature request for?

The core library

### The Problem

There is no function or listener event which will be called after completion of View button interaction. There is only event for app command completion: https://discordpy.readthedocs.io/en/stable/api.html#discord.on_app_command_completion

### The Ideal Solution

Add a function or event like `on_view_interaction_completion()` or more general event like `on_interaction_completion()` 

### The Current Solution

I am using this event currently `on_interaction()`

### Additional Context

I want this event to record bot interactions in the database to review data later and improve the bot. Like what features of the bot are used more so I should focus more on them.

**Comment by Rapptz** [comment]
I don't particularly see much point to this event, the app_command_completion event had decent rationale to be added. It was part of the commands framework and it's useful for building some statistics such as how many times a command gets used. The same rationale does not apply to buttons or views.
