### ISSUE TITLE
Channel in message is None

### ISSUE THREAD

**Issue by ZeroEpoch1969** [Rapptz/discord.py#963]
When attempting to use a selfbot or a normal bot in a group DM (The bot is on the user's friend list as it's an old bot account) instead of the channel being there as a GroupChannel it returns as a NoneType and has no channel variable set at all in the Message object

**Comment by datmellow** [comment]
Selfbots are banned
see: https://support.discordapp.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-

and normal bots cannot be in a group DM.

**Comment by ZeroEpoch1969** [comment]
@datmellow I don't use selfbots. And they can if you had them as a friend.
https://seth.doesnt-have-a.life/3trbhbf.png

**Comment by freetnt5852** [comment]
How do u add them as friend? It never works

**Comment by NCPlayz** [comment]
I'm guessing it's an old bot before oauth existed

**Comment by Rapptz** [comment]
This is an edge case that I never bothered to implement.
