### ISSUE TITLE
Read profile badges

### ISSUE THREAD

**Issue by geofurb** [Rapptz/discord.py#9638]
### Summary

Add API endpoint to retrieve users' profile badges

### What is the feature request for?

The core library

### The Problem

It would be useful to have the ability from the API to read users' Discord profile badges. (i.e. to check a user's Nitro status, see their legacy username#0000, etc.) For example, this would allow bots to determine if users have Nitro privileges when trying to provide assistance to users who use the bot's help command.

More on profile badges:
https://support.discord.com/hc/en-us/articles/360035962891-Profile-Badges-101

### The Ideal Solution

Ideally, implement an endpoint which retrieves the profile badges and returns a dict with the badges and their data.

### The Current Solution

The best current workaround is to check if a user is currently boosting the server, but this is very limited.

**Comment by No767** [comment]
That's already implemented

**Comment by geofurb** [comment]
I couldn't find the endpoint in the documentation. Can you point me at it?

**Comment by Rapptz** [comment]
This isn't supported by the bot API.

**Comment by geofurb** [comment]
> That's already implemented
> 
> https://discordpy.readthedocs.io/en/stable/api.html?highlight=user#discord.User.public_flags

It looks like you can't check Nitro status in these flags. Is there another way to?

**Comment by Rapptz** [comment]
You can't check for nitro status in messages.

**Comment by geofurb** [comment]
Is there another way to check this?

**Comment by Rapptz** [comment]
Not unless you use [OAuth2](https://discord.com/developers/docs/topics/oauth2), which is currently outside the scope of the library.

**Comment by geofurb** [comment]
Can you point me at a resource for accomplishing this by doing that?

**Comment by Rapptz** [comment]
The Discord documentation goes over it, but explaining OAuth2 flow in this issue tracker is definitely out of topic and is something better left off googling. Do note that this system requires a backend of some sort in order for the user to login to their Discord account to your service so it might not be feasible for your use case.

**Comment by geofurb** [comment]
I can do OAuth2 flow, just wanted to know which API documentation and where I need for getting Nitro subscriber status. Sounds like I'm heading over to the official docs. Thanks!
