### ISSUE TITLE
Pronoun responses.

### ISSUE THREAD

**Issue by naisu-dev** [Rapptz/discord.py#9639]
### Summary

I want to be able to get pronouns from discord.Member

### What is the feature request for?

The core library

### The Problem

We have created a command to search for users on the bot.
This is because we want that command to support 'search by pronoun'.

### The Ideal Solution

discord.member.pronoun?

**Comment by naisu-dev** [comment]
Translated from Japanese, so there is a possibility of strange sentences

**Comment by Gobot1234** [comment]
This is an API limitation so it currently cannot be added
