### ISSUE TITLE
Emoji does not get set in Custom Activity

### ISSUE THREAD

**Issue by callmephilip** [Rapptz/discord.py#9642]
### Summary

Provided emoji does not get displayed alongside text in custom activity

### Reproduction Steps

```python
import discord
import asyncio

class MyClient(discord.Client):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    async def on_ready(self):
        print(f'Logged in as {self.user} (ID: {self.user.id})')
        print('------')
        await self.change_presence(
            activity=discord.CustomActivity(name="Custom activity", emoji="😀")
        )

async def main():
    client = MyClient(intents=discord.Intents.default())
    await client.start('token')

if __name__ == "__main__":
    asyncio.run(main())
```

### Expected Results

Provided emoji should be displayed alongside custom activity text

### Actual Results

Only text is visible

### Intents

discord.Intents.default()

### System Information

- Python v3.10.9-final
- discord.py v2.3.2-final
- aiohttp v3.8.6
- system info: Darwin 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by callmephilip** [comment]
Current workaround:

```python
await self.change_presence(
    activity=discord.CustomActivity(name="😀 Custom activity")
)

```

**Comment by Soheab** [comment]
Bots don't support the emoji field, yet.

**Comment by Rapptz** [comment]
Discord doesn't support bot users having emoji in custom statuses due to complications in permission resolution (i.e. to know whether you can use the emoji or not). You'll just have to hope that Discord loosens the restriction one day.
