### ISSUE TITLE
Bot crashes when trying to react to a message with two reactions

### ISSUE THREAD

**Issue by MaroCrafter** [Rapptz/discord.py#9643]
### Summary

The bot crashes when trying to react to a message with two reactions.

### Reproduction Steps

I made a command which sends a message, and then reacts to that message with two different emojis. You can do this with any emoji. Then I tried running that command.

### Minimal Reproducible Code

```python
@bot.command()
async def my_command(ctx):
    message: discord.Message = await ctx.send("This is the message")
    await confirm_message.add_reaction("\u2705")
    await confirm_message.add_reaction("\u274c")
```

### Expected Results

I expected the bot to send the message and react with both emojis.

### Actual Results

The bot sent the message and reacted with the first emoji, but instantly crashed before reacting with the second emoji. Again, it did not matter what the emoji was. I got this error:
```Traceback (most recent call last):
  File "/home/container/file.py", line 2227, in <module>
    bot.run(token)
  File "/home/container/.local/lib/python3.10/site-packages/discord/client.py", line 763, in run
    return future.result()
  File "/home/container/.local/lib/python3.10/site-packages/discord/client.py", line 742, in runner
    await self.start(*args, **kwargs)
  File "/home/container/.local/lib/python3.10/site-packages/discord/client.py", line 706, in start
    await self.connect(reconnect=reconnect)
  File "/home/container/.local/lib/python3.10/site-packages/discord/client.py", line 600, in connect
    await self.ws.poll_event()
  File "/home/container/.local/lib/python3.10/site-packages/discord/gateway.py", line 604, in poll_event
    await self.received_message(msg.data)
  File "/home/container/.local/lib/python3.10/site-packages/discord/gateway.py", line 554, in received_message
    func(data)
  File "/home/container/.local/lib/python3.10/site-packages/discord/state.py", line 733, in parse_message_reaction_add
    raw = RawReactionActionEvent(data, emoji, "REACTION_ADD")
  File "/home/container/.local/lib/python3.10/site-packages/discord/raw_models.py", line 259, in __init__
    self.type: ReactionType = try_enum(data.get("type", 0))
TypeError: try_enum() missing 1 required positional argument: 'val'
```
I ran this code on my server which was running the recent version of Discord.py.

### Intents

discord.Intents().all()

### System Information

- Python v3.10.7-final
- discord.py v2.3.0-final
- aiohttp v3.8.3
- system info: Windows 10 10.0.19045

I want to note that the command worked on this version of Discord.py and that this was on my computer. I got the error when I tried running the command on the most recent version of Discord.py.

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I tried using try except to catch the error, but that didn't help. It directly crashed and gave out the error from above anyways.

**Comment by AbstractUmbra** [comment]
Upon further looking into this issue there are several discrepancies between your traceback and your version info.

Your pathing in the traceback indicates `/home/container...` as the path, yet you're on Windows 10?
L#259 in v2.3.0 of discord.py is [here](https://github.com/Rapptz/discord.py/blob/c785e4ba755e9b25c36953bdb0ffc34b41fe24d7/discord/raw_models.py#L259) and doesn't match what you've provided.

There's also an open PR on [Pycord](https://github.com/Pycord-Development/pycord/pull/2255) to resolve this issue you're having, as I cannot find it within discord.py's codebase at all...

**Comment by Rapptz** [comment]
This isn't discord.py as mentioned above.
