### ISSUE TITLE
add a "hard timeout" for the `View` class

### ISSUE THREAD

**Issue by Snawe** [Rapptz/discord.py#9646]
### Summary

Add a new optional class parameter that kinda works like the `timeout` but does not reset itself on interaction usage.

### What is the feature request for?

The core library

### The Problem

I have a view that needs to stop / timeout x time after the view is created. The current `timeout` parameter would not fit there because it resets every time a user interacts with the view. This could ofc also be implemented on the user side, I just thought it might be a good addition to the library.

### The Ideal Solution

adding a new optional parameter to the class. If set a task is created that, similar to the `timeout` parameter, calls an `on_xxx` function when the "hard timeout" is reached.

**Comment by Soheab** [comment]
This was discussed in the following bikeshedding post in the [server](https://discord.gg/dpy): https://discord.com/channels/336642139381301249/1085904646964531293

**Comment by Snawe** [comment]
Oh, true! But still my request is a bit different. I would propose an additional `absolute_timeout` parameter that isn't a flag. So for example if you set a `timeout` to 60 seconds, and an `absolute_timeout` to 120 sec, the view would timeout on:
* no interaction since 60 seconds
* **or** after 120 seconds even if an interaction was just like 1 sec before the `absolute_timeout`.

**Comment by Rapptz** [comment]
The end result is the same. I'm not sure how common this request is, but the timeout is settable at runtime which makes this request more complicated than it'd appear at a glance. 

For simple use cases that don't need to care about it, you can just do the following:

```py
class FixedTimeoutView(discord.ui.View):
    def __init__(self, timeout: float) -> None:
        super().__init__(timeout=None)
        loop = asyncio.get_running_loop()
        
        def callback():
            self.stop()
            loop.create_task(self.on_timeout())

        loop.call_later(timeout, callback)
```

**Comment by Snawe** [comment]
Yes, that is kinda what I also have ATM. Just thought it might be good in the lib ;) But I am also fine with having it in my own code. :+1:
