### ISSUE TITLE
bug: import GuildChannel will cause circular import

### ISSUE THREAD

**Issue by cutecutecat** [Rapptz/discord.py#9653]
### Summary

Cannot import GuildChannel for type hint

### Reproduction Steps

```bash
Python 3.9.18 (main, Sep 11 2023, 13:41:44) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from discord.types.channel import GuildChannel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/miniconda3/lib/python3.9/site-packages/discord/types/channel.py", line 30, in <module>
    from .threads import ThreadMetadata, ThreadMember, ThreadArchiveDuration, ThreadType
  File "/home/xxx/miniconda3/lib/python3.9/site-packages/discord/types/threads.py", line 31, in <module>
    from .message import Message
  File "/home/xxx/miniconda3/lib/python3.9/site-packages/discord/types/message.py", line 35, in <module>
    from .channel import ChannelType
ImportError: cannot import name 'ChannelType' from partially initialized module 'discord.types.channel' (most likely due to a circular import) (/home/xxx/miniconda3/lib/python3.9/site-packages/discord/types/channel.py)
```

### Expected Results

Import success.

### Actual Results

ImportError

### Intents

Nil

### System Information

- Python v3.9.18-final
- discord.py v2.3.2-final
- aiohttp v3.9.0
- system info: Linux 5.15.133.1-microsoft-standard-WSL2

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
`discord.types` is not public interface nor is it meant to be importable at runtime. They're strictly for `if TYPE_CHECKING` blocks for use within the library.

**Comment by Soheab** [comment]
You may `GuildChannel` from `discord.abc`.
