### ISSUE TITLE
Multiple loops of task being executed at same time

### ISSUE THREAD

**Issue by Jbleezy** [Rapptz/discord.py#9656]
### Summary

If the code in the task takes longer to execute than the time between iterations, then it is possible for multiple loops of the task to be queued up at once.

### Reproduction Steps

Have the code within the loop take longer than the specified time between interations.

### Minimal Reproducible Code

```python
initial_loop = True
prev_loop_end_time = 0

@tasks.loop(seconds=1, count=10)
async def main():
    global initial_loop
    global prev_loop_end_time

    if prev_loop_end_time:
        print("time between loops:", time.time() - prev_loop_end_time)

    if initial_loop:
        initial_loop = False
        await asyncio.sleep(5)

    prev_loop_end_time = time.time()
```

### Expected Results

time between loops: 1.0
time between loops: 1.0
time between loops: 1.0
time between loops: 1.0
time between loops: 1.0
time between loops: 1.0
time between loops: 1.0
time between loops: 1.0
time between loops: 1.0

### Actual Results

time between loops: 0.0
time between loops: 0.0
time between loops: 0.0
time between loops: 0.0
time between loops: 0.0
time between loops: 1.0
time between loops: 1.0
time between loops: 1.0
time between loops: 1.0

### Intents

discord.Intents.all()

### System Information

- Python v3.11.0-final
- discord.py v2.3.2-final
- aiohttp v3.9.0
- system info: Windows 10 10.0.19045

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
This is as designed. You're overshooting the timer by sleeping 5 seconds, so in order to catch up the task callback is called multiple times for all the times it missed.
