### ISSUE TITLE
AttributeError: 'MyClient' object has no attribute '_BotBase__tree'

### ISSUE THREAD

**Issue by Nelnitorian** [Rapptz/discord.py#9669]
### Summary

Code worked flawlessly. Tried to dockerize it. The exception showed up in container. Tried to replicate in local machine and... well, something's wrong.

### Reproduction Steps

Uninstalled discord version (which worked fine) `pip unintall discord.py`

Install with `pip install discord.py==2.3.2`

Execute code `python main.py`

### Minimal Reproducible Code

```python
import discord
from discord.ext import commands


class MyClient(commands.Bot):
    def __init__(self, *, intents: discord.Intents):
        pass


client = MyClient(intents=discord.Intents.default())


@client.tree.command()
async def hello(interaction: discord.Interaction):
    await interaction.response.send_message("hi")


client.run(TOKEN)
```

### Expected Results

The code to work.

### Actual Results

PS D:\***\Proyectos\DCBot> python3.9 .\main.py
```
Traceback (most recent call last):
  File "D:\***\Proyectos\DCBot\main.py", line 63, in <module>
    @client.tree.command()
  File "C:\Users\***\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\ext\commands\bot.py", line 1167, in tree
    return self.__tree
AttributeError: 'MyClient' object has no attribute '_BotBase__tree'
```

### Intents

discord.Intents.default()

### System Information

- Python v3.9.13-final
- discord.py v2.3.2-final
- aiohttp v3.9.1
- system info: Windows 10 10.0.19045

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

It seems impossible to me that this is a repo issue. So here I lie, with no clue. Any ideas?

**Comment by No767** [comment]
This is not an issue with discord.py. Within the code given, you never instantiated the `commands.Bot` subclass within the constructor, thus the tree was never instantiated to begin with.
