### ISSUE TITLE
Cog event error handler

### ISSUE THREAD

**Issue by FreakMediaLP** [Rapptz/discord.py#9674]
### Summary

Adding a error handler to events in cogs

### What is the feature request for?

The core library

### The Problem

I've read through the entire documentation and have not been able to find a error handler for events in cogs @commands.Cog.listener().
For normal @Client.event there is a [error handler](https://discordpy.readthedocs.io/en/stable/api.html#discord.on_error), which is just not available for listeners, as described in the documentation.

This makes absolutely no sense, because meanwhile there is a [has_error_handler](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html?highlight=error_handler#discord.ext.commands.Cog.has_error_handler) function, which returns, if a cog has a error handler or not.

Also there are error handlers for app_commands and commands in cogs, but not for events/listeners

### The Ideal Solution

Add a "cog_listener_error" error handler

### The Current Solution

None

**Comment by Rapptz** [comment]
`on_error` is mainly for catching all unhandled errors within the library that an event throws. For other types of error handlers you have `cog_error` for `ext.commands` and `cog_app_command_error` for `app_commands`.

**Comment by FreakMediaLP** [comment]
Thanks for the quick response, but I am still not seeing it trough, i have my @commands.Cog.listeners() in a cog and I am searching for a method, that catches the errors, as the cog_app_command_error method soes for errors in app_commands

**Comment by FreakMediaLP** [comment]
> `on_error` is mainly for catching all unhandled errors within the library that an event throws. For other types of error handlers you have `cog_error` for `ext.commands` and `cog_app_command_error` for `app_commands`.
> 
> The "specialness" of `on_error` is as designed, and there is really no real reason to override this at a cog level but if necessary you can just monkeypatch it.

Thanks for the quick response, but I am still not seeing it trough, i have my @commands.Cog.listeners() (for examlpe on_ready and on_message) in a cog and I am searching for a method, that catches the errors, as the cog_app_command_error method soes for errors in app_commands
