### ISSUE TITLE
Rename Interaction.user to Interaction.author for consistency

### ISSUE THREAD

**Issue by Duvio** [Rapptz/discord.py#9681]
### Summary

Rename Interaction.user to Interaction.author for consistency

### What is the feature request for?

The core library

### The Problem

Currently the user/member who has commissioned an interaction is obtainable through Interaction.user. However its equivalent in Context is Context.author. In some edge cases you have to work around this using isinstance().

### The Ideal Solution

Rename all corresponding occurrences of user to author.

**Comment by Rapptz** [comment]
The API attribute for this is `user` and so it's called that. For messages it's `author` so it's called that there too. The "inconsistency" is there because an interaction does not have an "author", you can get them without authoring anything at all (e.g. a button press or what have you).
