### ISSUE TITLE
on_server_join(server) error

### ISSUE THREAD

**Issue by chrisderwahre** [Rapptz/discord.py#969]
Hey im getting this issue when my bot joins the server. This is my Code:
`@client.event
async def on_server_join(server):
    em = Embed(title='Invited', description='Text.', colour=discord.Color.gold())
    await client.send_message(server, embed=em)`

And this is the Error:
`discord.errors.NotFound: NOT FOUND (status code: 404): Unknown Channel`

Im using Python 3.5

**Comment by datmellow** [comment]
The documentation stating that you can use a server as a destination in ``send_message`` is out of date, as it implies the server has a default channel, which not every server will have. You will need to explicitly state which channel to send too.

**Comment by chrisderwahre** [comment]
@datmellow Sounds bad. I just changed it that the bot send the server owner a DM, or is there any way to send a message to a random channel?

**Comment by datmellow** [comment]
The implementation is for you to decide, see ``Server.channels``.

**Comment by tilda** [comment]
You could go through the first channel which the bot can write to.
```py
async def find_channel(guild):
    """
    Finds a suitable guild channel for posting the
    welcome message.
    """
    for c in guild.text_channels:
        if not c.permissions_for(guild.me).send_messages:
            continue
        return c
```

**Comment by chrisderwahre** [comment]
@tilda Ok thanks, but how can send a message when it found a channel to send a message?

**Comment by tilda** [comment]
It returns a discord.Channel, so you store it in a variable and use it.
```py
# Replace guild with whatever variable that you use for a server
channel = await find_channel(guild)
# Send a message to the channel that was found
await channel.send('blah')
```

**Comment by Modelmat** [comment]
You could also use `http://discordpy.readthedocs.io/en/rewrite/api.html#discord.Guild.system_channel` (the default channel for welcome messages. However, this might not always be set.

**Comment by tilda** [comment]
@Modelmat Yeah, that's mostly why we use my find_channel function here. It finds the "default channel" (first one it can speak in, aka highest).

**Comment by Modelmat** [comment]
Yes. I see. I would recommend trying these:

1. Default welcome channel (system channel)
2. Finding #general and checking for perms
3. Iterating over sendable channels

**Comment by NCPlayz** [comment]
The problem with #2 is that not all guilds will have a #general

**Comment by Modelmat** [comment]
That's why we try the general channel.
