### ISSUE TITLE
context menu member status issue

### ISSUE THREAD

**Issue by Enzyklopaedie** [Rapptz/discord.py#9697]
### Summary

member is offline but on discord he's online

### Reproduction Steps

I created a context menu and the code only should executed, when the member is online with an if-loop. To catch the error, when the user is everything else but online, I added else, but now the code from the else is always executed. Also when I do `print(meber.status)` I get 'offline', which isn't true.

### Minimal Reproducible Code

```python
import discord
from discord.ext import commands
from discord import app_commands

intents = discord.Intents.all()
intents.presences = True
bot = commands.Bot(command_prefix='!', intents=intents)

@bot.event
async def on_ready():
    print(f"I'm logged in as {bot.user}!")

@bot.tree.context_menu(name="mitspielen", nsfw=False)
async def mitspielen(interaction: discord.Interaction, member: discord.Member):
    print(member.status)
    if member.status == discord.Status.online:
        await interaction.response.send_message(f"{member.mention}, **{interaction.user}** would like to play video games with you")
    else:
        await interaction.response.send_message(f"Choose an online person to play video games with", ephemeral=True)

bot.run("token")
```

### Expected Results

the if-loop should be executed, if the user is online on discord

### Actual Results

the else is executed and the member is offline according to my console, but on discord the person is displayed as online 

### Intents

discord.Intents.all()

### System Information

- Python v3.12.1-final
- discord.py v2.3.2-final
- aiohttp v3.9.1
- system info: Windows 11 10.0.22631

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

**Comment by Soheab** [comment]
The API doesn't return presences data with interactions for some reason. You can get the member from cache instead.
```py
cached_member = interaction.guild.get_member(user_id)
print(cached_member, cached_member.status)
```

**Comment by Puncher1** [comment]
Presences are sent over gateway only and are available in the `GUILD_CREATE` and `PRESENCE_UPDATE` event if the `GUILD_PRESENCES` intent is enabled. 
That's also why you can't get the status over the `fetch_` methods but with the `get_` methods because the status gets updated in the internal cache when one of the mentioned events occurr:

![image](https://github.com/Rapptz/discord.py/assets/65789180/f6b2916d-f735-467f-bc58-603aa944b9c6)

The solution as @Soheab already mentioned would be following:
```py
@bot.tree.context_menu(name="mitspielen", nsfw=False)
async def mitspielen(interaction: discord.Interaction, member: discord.Member):
    member = interaction.guild.get_member(member.id)  # get member from internal cache
    print(member.status)
    
    # ...
```
Output (in my case):
```
dnd
```
