### ISSUE TITLE
"Could not build wheels for multidict, which is required to install pyproject.toml-based projects"

### ISSUE THREAD

**Issue by monkey283636** [Rapptz/discord.py#9698]
### Summary

i cant install discord.py

### Reproduction Steps

all I did was run this command on python 3.10.0: "py -3 -m pip install -U discord.py"

### Minimal Reproducible Code

```python
py -3 -m pip install -U discord.py
```

### Expected Results

I expected for it to downlaod

### Actual Results

It failed.

### Intents

none

### System Information

I cant do that if it isnt installed

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by monkey283636** [comment]
if you need the log:
`Collecting discord.py
  Using cached discord.py-2.3.2-py3-none-any.whl.metadata (4.9 kB)
Collecting aiohttp<4,>=3.7.4 (from discord.py)
  Using cached aiohttp-3.9.1-cp312-cp312-win_amd64.whl.metadata (7.6 kB)
Collecting attrs>=17.3.0 (from aiohttp<4,>=3.7.4->discord.py)
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4,>=3.7.4->discord.py)
  Using cached multidict-6.0.4.tar.gz (51 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting yarl<2.0,>=1.0 (from aiohttp<4,>=3.7.4->discord.py)
  Using cached yarl-1.9.4-cp312-cp312-win_amd64.whl.metadata (32 kB)
Collecting frozenlist>=1.1.1 (from aiohttp<4,>=3.7.4->discord.py)
  Using cached frozenlist-1.4.1-cp312-cp312-win_amd64.whl.metadata (12 kB)
Collecting aiosignal>=1.1.2 (from aiohttp<4,>=3.7.4->discord.py)
  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting idna>=2.0 (from yarl<2.0,>=1.0->aiohttp<4,>=3.7.4->discord.py)
  Using cached idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Using cached discord.py-2.3.2-py3-none-any.whl (1.1 MB)
Using cached aiohttp-3.9.1-cp312-cp312-win_amd64.whl (362 kB)
Using cached frozenlist-1.4.1-cp312-cp312-win_amd64.whl (50 kB)
Using cached yarl-1.9.4-cp312-cp312-win_amd64.whl (76 kB)
Using cached idna-3.6-py3-none-any.whl (61 kB)
Building wheels for collected packages: multidict
  Building wheel for multidict (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for multidict (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [74 lines of output]
      *********************
      * Accelerated build *
      *********************
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\multidict
      copying multidict\_abc.py -> build\lib.win-amd64-cpython-312\multidict
      copying multidict\_compat.py -> build\lib.win-amd64-cpython-312\multidict
      copying multidict\_multidict_base.py -> build\lib.win-amd64-cpython-312\multidict
      copying multidict\_multidict_py.py -> build\lib.win-amd64-cpython-312\multidict
      copying multidict\__init__.py -> build\lib.win-amd64-cpython-312\multidict
      running egg_info
      writing multidict.egg-info\PKG-INFO
      writing dependency_links to multidict.egg-info\dependency_links.txt
      writing top-level names to multidict.egg-info\top_level.txt
      reading manifest file 'multidict.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files found matching 'multidict\_multidict.html'
      warning: no previously-included files found matching 'multidict\*.so'
      warning: no previously-included files found matching 'multidict\*.pyd'
      warning: no previously-included files found matching 'multidict\*.pyd'
      no previously-included directories found matching 'docs\_build'
      adding license file 'LICENSE'
      writing manifest file 'multidict.egg-info\SOURCES.txt'
      C:\Users\adam\AppData\Local\Temp\pip-build-env-0ij1bv45\overlay\Lib\site-packages\setuptools\command\build_py.py:207: _Warning: Package 'multidict._multilib' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'multidict._multilib' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'multidict._multilib' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'multidict._multilib' to be distributed and are
              already explicitly excluding 'multidict._multilib' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html


              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      copying multidict\__init__.pyi -> build\lib.win-amd64-cpython-312\multidict
      copying multidict\py.typed -> build\lib.win-amd64-cpython-312\multidict
      running build_ext
      building 'multidict._multidict' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for multidict
Failed to build multidict
ERROR: Could not build wheels for multidict, which is required to install pyproject.toml-based projects`

**Comment by LeoCx1000** [comment]
Some wheels don't exist for 3.12, fortunately umbra built them in their index.

Try this: `py -3 -m pip install -U --force-reinstall discord.py --extra-index-url https://abstractumbra.github.io/pip/`

**Comment by Rapptz** [comment]
This is a dependency issue, I can't do anything about it. Check the above comment for alternative install instructions.

**Comment by monkey283636** [comment]
ty it worked

**Comment by CDWimmer** [comment]
For the sake of people wandering in here from google etc. If you're installing to a venv (at least on Windows) use the slightly different `python -m pip install -U --force-reinstall discord.py --extra-index-url https://abstractumbra.github.io/pip/`

I found the command above managed to install to my global install despite being in my venv.

**Comment by leirn** [comment]
https://github.com/aio-libs/multidict/issues/887

Multidict has now 3.12 support since version 6.0.5

**Comment by CDWimmer** [comment]
> [aio-libs/multidict#887](https://github.com/aio-libs/multidict/issues/887)
> 
> Multidict has now 3.12 support since version 6.0.5

Excellent, can probably close this as resolved now?
