### ISSUE TITLE
'textchannel.create_thread()' method returns an object called 'ThreadWithMessage' instead of 'Thread' object

### ISSUE THREAD

**Issue by sicco14** [Rapptz/discord.py#9705]
### Summary

The documentation says that create_thread() will return a Thread object. But this is not the case for me. When I try to call the threads id via 'thread.id' it says : 'ThreadWithMessage' object has no attribute 'id'

### Reproduction Steps

I fetched a channel via ID. In this channel I create a thread and post an embed into it. Next I tried to get the threads id, which is not possible. By my understanding of the documentation it should be possible since the method should return a 'Thread' object.

### Minimal Reproducible Code

```python
channel = await interaction.guild.fetch_channel(config_get("REPORT_CHANNEL_ID"))
new_thread = await channel.create_thread(name=thr_name, embed=myembed)
print(new_thread.id)
```

### Expected Results

I expected my code to return the thread id.

### Actual Results

My code threw the error message: 'ThreadWithMessage' object has no attribute 'id'

### Intents

PRESENCE, SERVER MEMBERS, MESSAGE CONTENT

### System Information

- Python v3.8.6-final
- discord.py v2.3.2-final
- aiohttp v3.8.3
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

To be honest I was surprised that I could feed an embed attribute into the "create_thread" method. The docs say I can only add a message object.

**Comment by Soheab** [comment]
`channel` is probably a [`ForumChannel`](https://discordpy.readthedocs.io/en/stable/api.html#forumchannel) there and [`ForumChannel.create_thread`](https://discordpy.readthedocs.io/en/stable/api.html#discord.ForumChannel.create_thread) instead returns a tuple of [`Thread`](https://discordpy.readthedocs.io/en/stable/api.html#discord.Thread) and [`Message`](https://discordpy.readthedocs.io/en/stable/api.html#discord.Message) as documented.

**Comment by sicco14** [comment]
You are correct! Thanks a lot! That was actually pretty nooby of me. Im sorry!

**Comment by sicco14** [comment]
closed
