### ISSUE TITLE
has_role() function only recognizes roles by name.

### ISSUE THREAD

**Issue by therealfriendo** [Rapptz/discord.py#971]
Currently, has_role() within commands > core.py only recognizes roles by their name as a string. This allows a user to create their own discord server and add a duplicate role which then allows the bot to have the same privileges on the original server thereby gaining a privilege escalation. In order to prevent this, has_role() should also accept role ID as an argument as the role IDs would be different between servers.

**Comment by Rapptz** [comment]
`has_role` is by design meant for simple use cases.

If you want more complicated ones then feel free to make a custom check.
