### ISSUE TITLE
Cannot find reference 'send_message' in '() -> InteractionResponse' warning in pycharm

### ISSUE THREAD

**Issue by wolfricoz** [Rapptz/discord.py#9713]
### Summary

When working with the slash commands, it keeps warning me about Cannot find reference 'send_message' in '() -> InteractionResponse'

### Reproduction Steps

when calling the following line of code:
`await interaction.response.send_message("Forum not found")`

it warns me in that the reference for sent_message is not found in InteractionResponse.

### Minimal Reproducible Code

```python
@app_commands.command(name="test")
    async def test(self, interaction: discord.Interaction):
        """Just testing here."""
        await interaction.response.send_message("Test!")
```

### Expected Results

While writing the code, I expect it to not throw warnings for functions that do exist within the library.

### Actual Results

When using the interaction.response.send_message it throws a warning in the problems section of pycharm but it does run fine other than that.
![image](https://github.com/Rapptz/discord.py/assets/24657605/e3b864d2-c3ae-4d4f-bbe4-d4ba020d9450)

### Intents

Message_contents, members

### System Information

Pycharm Community Edition 2023.3.2
Python 3.10
discord 2.3.2

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

This is my first time opening an issue, my apologies in advance if I have not given enough information or details. This bug doesn't break any functionality but does misinform the user when coding which can be rather annoying - especially as it also causes it to not show up in autocomplete which can be rather annoying for new coders.

Thank you for taking the time to read this!

**Comment by No767** [comment]
Please see https://github.com/Rapptz/discord.py/discussions/9504
