### ISSUE TITLE
Provide a standard way to cancel a `Converter` conversion

### ISSUE THREAD

**Issue by WieeRd** [Rapptz/discord.py#9719]
### Summary

We need a way to "cancel", not "fail" the conversion.

### What is the feature request for?

discord.ext.commands

### The Problem

Some bots provide a selection menu of targets when they cannot find an exact match for the command argument.
e.g. A search result of guild members' nicknames when nobody has the exact same name as the given argument string.

<img src=https://github.com/Rapptz/discord.py/assets/59733058/673361ea-7011-4b42-9e68-459bc52ed0d6 width=40%>

It makes sense to put this feature in the custom `Converter` to make it reusable in many commands.
And since it requires user interaction, the conversion may time out or be cancelled by the user.

But currently, a `Converter` can only succeed or fail.
There is no way to "cancel" the conversion, to cleanly "give up" the conversion and the invocation of the command.

### The Ideal Solution

Introduce a new `CommandError` subclass, `ConversionCancelled`.
Custom converters can raise this exception to indicate intentional cancellation of the conversion.
Similar to `CommandNotFound`, it is mostly expected to be suppressed by the `on_command_error()` handler.

**Comment by Rapptz** [comment]
This just looks like something that should be implemented within your bot, there's nothing really to do here from the library POV that you can't do yourself. For example, cancelling the converter would do nothing in the library.

**Comment by WieeRd** [comment]
Well, that's what I'm doing right now, having that custom exception in my code.
But I thought it was something that would make sense to exist in the library itself.
