### ISSUE TITLE
change_presence

### ISSUE THREAD

**Issue by fbagjug** [Rapptz/discord.py#972]
@bot.event
    async def on_ready():
        bot.change_presence(game=discord.Game(name="My game"))
        print("Setting playing game!")

Anyone know why this isnt working?

**Comment by khazhyk** [comment]
Are you on `async` branch? (0.16.x)? I have this same issue but haven't bothered to investigate why

**Comment by fbagjug** [comment]
Not too sure to be honest

**Comment by khazhyk** [comment]
you're missing an await

**Comment by fbagjug** [comment]
i had one but it didnt do nothing

**Comment by fbagjug** [comment]
Ill retry

**Comment by fbagjug** [comment]
Fixed :D
