### ISSUE TITLE
Autocomplete Not Working as Expected

### ISSUE THREAD

**Issue by bsrecker** [Rapptz/discord.py#9734]
### Summary

Calling a Function in a different class can lead to unexpected results

### Reproduction Steps

1. Call Function in another class within the autocomplete function
2. Called a separate function from within that class to handles some db operations 

### Minimal Reproducible Code

```python
`class SomeClass:

    async def get_all_owned_businesses(
            self, interaction: discord.Interaction, current: str
    ) -> List[app_commands.Choice[str]]:
        businesses = await self.bot.database.fetch(
            """SELECT business_name FROM businessaccounts 
               WHERE account_owner = $1 AND business_name ILIKE $2""",
            interaction.user.id,
            f"%{current}%"  # Using ILIKE for case-insensitive matching
        )

        business_names = [
            app_commands.Choice(name=business["business_name"], value=business["business_name"])
            for business in businesses
        ]

        return business_names
    async def all_autopayment_accounts(self, interaction: discord.Interaction, current: str) -> List[
        app_commands.Choice[str]]:
        businesses = await self.get_all_owned_businesses(interaction, current)

        savings_account = app_commands.Choice(name="Savings Account", value="Savings Account")
        wallet = app_commands.Choice(name="Wallet", value="Wallet")

        businesses.append(savings_account)
        businesses.append(wallet)

        return businesses


class SomeOtherClass:

    @app_commands.autocomplete(account=SomeClass.all_autopayment_accounts)`
```

### Expected Results

I expected this to correctly return the information from the database.

### Actual Results

The following error was raised: 
`[2024-02-19 13:33:47] [ERROR   ] discord.app_commands.tree: Ignoring exception in autocomplete for 'autopay setup'
Traceback (most recent call last):
  File "C:\Users\brand\PycharmProjects\SSRP Economy\.venv\Lib\site-packages\discord\app_commands\tree.py", line 1240, in _call
    await command._invoke_autocomplete(interaction, focused, namespace)
  File "C:\Users\brand\PycharmProjects\SSRP Economy\.venv\Lib\site-packages\discord\app_commands\commands.py", line 888, in _invoke_autocomplete
    choices = await param.autocomplete(binding, interaction, value)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brand\PycharmProjects\SSRP Economy\utils\parameter_autocomplete.py", line 83, in all_autopayment_accounts
    businesses = await self.get_all_owned_businesses(interaction, current)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AutoPay' object has no attribute 'get_all_owned_businesses'

### Intents

all

### System Information

- Python v3.12.0-final
- discord.py v2.4 (checked in dev)
- aiohttp v3.9.3
- system info: Windows 11 10.0.22621

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

First off, I realize that the correct way to approach the issue I faced is with inheritance to access a different class, however I still do think that this is a bug since the behavior is inconsistent. I have other autocomplete commands that access this same class without issue however one of my functions fails at the following step `businesses = await self.get_all_owned_businesses(interaction, current)`. 

My Speculation (could be completely wrong)
Due to the error it seems that an instance of `SomeClass` is not actually created and when `self.get_all_owned_businesses` is called its looking to the other class to find it. 

Can this be supported or at a minimum can this be documented so others do not run into it?

**Comment by Rapptz** [comment]
Your code doesn't make sense in the first place. Where are you expecting the library to magically create these instances? The library operates on the bindings that it can manage to find, it's not in the business of creating classes out of thin air.

**Comment by bsrecker** [comment]
I understand but it just seems like the documentation could be more clear since the people using it may not have an in-depth knowledge of how the library is constructed.
