### ISSUE TITLE
Logs and on_ready in cogs & bot.start and bot.run

### ISSUE THREAD

**Issue by MayorLeon19** [Rapptz/discord.py#9735]
### Summary

Logs and on_ready in cogs & bot.start and bot.run

### Reproduction Steps

![image](https://github.com/Rapptz/discord.py/assets/114074229/630dc8c5-16ce-4281-9cc2-36e4b73c69ab)

### Minimal Reproducible Code

```python
**bot.start:**

async def main():
    await bot.load_extension("cogs.verification")
    await bot.start(BOT_TOKEN)

if __name__ == "__main__":
    asyncio.run(main())

**bot.run:**
class PersistentViewBot(commands.Bot):
    def __init__(self) -> None:
        super().__init__(command_prefix='!', intents=discord.Intents.all())

    async def on_ready(self):
        print(f'{bot.user}')
        await bot.load_extension("cogs.verification")

await bot.run(BOT_TOKEN)


**another cog(for bot.start and bot.run):**
class Ticket_System(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.Cog.listener()
    async def on_ready(self):
       
        print(f'Bot Loaded | ticket_system.py ✅')
```

### Expected Results

When using bot.run, in some cases on_ready did not work, but error output worked; When using bot.start, the error output in coga does not work, but on_ready works

### Actual Results

I think that with bot.run it should work on ready in cogs

### Intents

discord.Intents.all()

### System Information

last

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by AbstractUmbra** [comment]
This was part of the agreed upon redesign of the logging system that if you use `commands.Bot.start()` over the `.run()` implementation then you wish to take control of the startup of the bot - which includes logging.

It's pretty trivial to add your own call to `discord.utils.setup_logging(...)` as you outlined above, so it can be done in user-code before calling `bot.start()`.

... alternatively, as we *do* recommend subclassing Client/Bot, you can add this in an *overridden* `.start()` method.
