### ISSUE TITLE
Aliases issue for when string in passed

### ISSUE THREAD

**Issue by Modelmat** [Rapptz/discord.py#974]
I made a mistake rather than parsing a list to `@commands.command(aliases=['name'])`, I sent `@commands.command(aliases='name').` This game me weird errors about commands like `n` already existing.

Looking at the [code](https://github.com/Rapptz/discord.py/blob/rewrite/discord/ext/commands/core.py#L745), you can see that it does not check to make sure that it is a list, so it instead iterates through the characters of `name`. 

See PR #975

**Comment by Vexs** [comment]
Bit of an idiot fix isn't it? It's a trivial thing to avoid.

**Comment by Modelmat** [comment]
Well, yes it is. It's still a good thing not to have errors like that making other errors. Even if it was made to raise another error (aliases are not a list), that would be better.

**Comment by Rapptz** [comment]
Fairly trivial. 

Fixed.
