### ISSUE TITLE
user_count always returns 0 on ScheduledEvent

### ISSUE THREAD

**Issue by dom64** [Rapptz/discord.py#9750]
### Summary

user_count will always return 0 under any scheduled event even if there is 1 or more people.

### Reproduction Steps

1. Make a new discord event
2. Click on the interested bell
3. The number goes up by one but discord.py thinks it is zero

### Minimal Reproducible Code

```python
async def on_scheduled_event_user_add(event, member):
    print(event.user_count)
```

### Expected Results

For it to return the amount of users who are interested in the event

### Actual Results

It always returns 0

### Intents

all + intents.members

### System Information

- Python v3.11.8-final
- discord.py v2.3.2-final
- aiohttp v3.8.4
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Doing a curl request of `curl -Ss -H "Authorization: Bot <TOKEN>" -H "Content-Type: application/json" -X GET https://discord.com/api/v10/guilds/<GUILD_ID>/scheduled-events?with_user_count=True` makes it return the proper user_count so this seems to be a discord.py issue rather then a discord api issue

**Comment by dom64** [comment]
a simple fix i found for now is doing
```py
async def on_scheduled_event_user_add(event, member):
        user_count = 0
        async for user in event.users():
            users += 1
        print(user_count)
```

**Comment by okisooo** [comment]
i'm getting the same issue, it's definitely a discord.py issue, however this seemed to work pretty well for me as a workaround and it works well even in bigger servers since it gives you the entire member count, and checking for each one would impact performance
```python
async def on_scheduled_event_user_add(event, member):
    user_count = len(await event.users().flatten())
    print(user_count)

**Comment by Rapptz** [comment]
The gateway probably just doesn't provide an accurate count. It's not unusual for attributes to only be available in the REST API or vice versa.
