### ISSUE TITLE
discord has not attribute Bot

### ISSUE THREAD

**Issue by FewerElk** [Rapptz/discord.py#9753]
### Summary

Bot class not found when running

### Reproduction Steps

install discord.py (version 2.3.2)
install discord py interactions (version 5.11.0)
run a simple bot
have an error

### Minimal Reproducible Code

```python
import discord
TOKEN = "A TOKEN HERE"
bot = discord.Bot(intents=discord.Intents.all()) #error here

#never runned
bot.run(TOKEN)
```

### Expected Results

a bot that run well

### Actual Results

```
Traceback (most recent call last):
  File "/home/container/main.py", line 3, in <module>
    bot = discord.Bot(intents=discord.Intents.all()) # error here
AttributeError: module 'discord' has no attribute 'Bot'
```

### Intents

discord.Intents.all()

### System Information

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\fewer\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\__main__.py", line 33, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by No767** [comment]
Indeed discord.py does not have `discord.Bot`, as this is from an third party library. Perhaps you were looking for `commands.Bot`.

In order to aid in app commands (which I noticed that you are trying to use), discord.py has full support for these commands natively. [This](https://about.abstractumbra.dev/dpy) should help.

**Comment by FewerElk** [comment]
I wasn't looking for commands.Bot.

I have the same code on 2 devices, one works and the other not, but they have the same versions.

**Comment by AbstractUmbra** [comment]
This is not correct.

I do know however that 3rd party forks of discord.py utilise `discord.Bot`. Perhaps you're using one of those?

**Comment by FewerElk** [comment]
oh sorry i have just listed the librairies i used and i saw that i wasn't using dpy interaction but py-coord 😓 my bad. Have a good day !
