### ISSUE TITLE
Add support for User-Installed Apps

### ISSUE THREAD

**Issue by 2br-2b** [Rapptz/discord.py#9757]
### Summary

Add support for User-Installed Apps

### What is the feature request for?

The core library

### The Problem

Per their [announcement earlier today](https://discord.com/channels/613425648685547541/697138785317814292/1219333034701226044), Discord is betaing user-installable apps:

![image](https://github.com/Rapptz/discord.py/assets/43968991/a2b239d6-a242-4830-9e23-71586dc81eb5)

This allows users to install an app to their profile and access its commands in any server or in a dm, even if the bot isn't installed in the server

### The Ideal Solution

Add the necessary fields and decorators for these fields. If I have time later, I can write up a draft

https://discord.com/channels/613425648685547541/697138785317814292/1219333034701226044

### Additional Context

This is still in beta, so it is subject to change

**Comment by AbstractUmbra** [comment]
Please see #9406.

**Comment by 2br-2b** [comment]
Now #9760. Should I leave this issue open to track the feature's progress or close it as redundant/wip/planned?

Also, thanks to the dpy contributors for the quick turnaround!

**Comment by rowanchanner** [comment]
hurry

**Comment by Rapptz** [comment]
This is already in v2.4.
