### ISSUE TITLE
Use more than one prefix

### ISSUE THREAD

**Issue by Niels1006** [Rapptz/discord.py#976]
```python
@bot.command(command_prefix="+rep")
async def abc(member : discord.Member):
    print("abcbc")
```
Can I do something like this? And I dont want to do it with on_message, unless I cant do it this way.

**Comment by Rapptz** [comment]
If you're asking for per-command prefixes the answer is "Not really supported".


If you're asking for multiple registered prefixes then you can just pass a list to `command_prefix`.

**Comment by Niels1006** [comment]
Can I check which prefix was used to execute the method?

**Comment by Rapptz** [comment]
You can get `prefix` from the context.

**Comment by Niels1006** [comment]
Thank you, I totally forgot it ^^
