### ISSUE TITLE
Using a discord.ui.TextInput in a View is apparently not supported

### ISSUE THREAD

**Issue by Brosssh** [Rapptz/discord.py#9763]
### Summary

According to the doc, discord.ui.TextInput is supported in a View, however a simple view with a text input goes in error

### Reproduction Steps

Created a simple view with a text input field

### Minimal Reproducible Code

```python
class Test(discord.ui.View):

    def __init__(self):
        super().__init__()

        self.component = discord.ui.TextInput(label="Test")
        self.add_item(self.component)

async def test(ctx :discord.ext.commands.Context):
    await ctx.reply(view=Test())
```

### Expected Results

A view with the text input field

### Actual Results

```
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In components.0.components.0: Value of field "type" must be one of (2, 3, 5, 6, 7, 8).
```

### Intents

default()

### System Information

- Python v3.11.0-final
- discord.py v2.3.2-final
- aiohttp v3.9.3
- system info: Windows 10 10.0.19045

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by LeoCx1000** [comment]
Message component views do not support those. The View subclass ``discord.ui.Modal`` is the only one which lets you use that, and it is used with``interaction.response.send_modal``

**Comment by Rapptz** [comment]
Only modals can use `TextInput` (and `Modal` is a special subclass of `View`).

**Comment by Brosssh** [comment]
So this is wrong? Am I reading it wrong?
![Cattura](https://github.com/Rapptz/discord.py/assets/44944126/e7ae6784-cd29-4966-b106-b660b17c3da7)

**Comment by Brosssh** [comment]
Ah right, `Item` is for both `View` and `Modal`.
