### ISSUE TITLE
file_type property  for Attachment class

### ISSUE THREAD

**Issue by Hunter87ff** [Rapptz/discord.py#9771]
### Summary

Please add a file_type property for the Attachment class

### What is the feature request for?

The core library

### The Problem

i was working on some code with attachment. and what i just noticed that i was calling `requests.get(attachment.url).headers` to get the file type, which is not that good for me! so i discovered an idea. if there is an attribute which will return file type for the perticular attachment then it could be helpful, so i came here and searched issues about it but didn't found any issues. so i created this

### The Ideal Solution

we can add a `@property` to the attachment class which'll fetch the url or if there is any api to get the file type and then return the type of the file! i know it's not that big issue but still hope i'll get an update about it

### The Current Solution

Currently im using external module `requests` to get the file type by calling `get` function and calling the property `headers['Content-Type']`

**Comment by Rapptz** [comment]
It's called [`Attachment.content_type`](https://discordpy.readthedocs.io/en/stable/api.html#discord.Attachment.content_type). It can be `None` though.
