### ISSUE TITLE
Appcommands autcomplete should have a limit.

### ISSUE THREAD

**Issue by PrupleDood** [Rapptz/discord.py#9777]
### Summary

Adding more than 25 choices to an autocomplete doesn't generate an error

### What is the feature request for?

The core library

### The Problem

appcommands autocomplete does not generate an error if there are more than 25 choices. This is a limit set by discord and is stated [here](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-structure). 

### The Ideal Solution

An error to be generated if the number of choices exceeds 25 and updates to the documentation to reflect changes.

**Comment by Soheab** [comment]
Discord does throw an error for this but autocomplete errors were ignored up until https://github.com/Rapptz/discord.py/commit/9e2f2cb3af30c9d4c6d3ff4f7850832c05488d6f

Always try the latest build before opening an issue.
