### ISSUE TITLE
Circular Import in Discord Bot Types

### ISSUE THREAD

**Issue by Slyracoon23** [Rapptz/discord.py#9778]
### Summary

A circular import issue has been identified in the Discord bot types files, specifically between the message.py and interactions.py modules. This circular dependency prevents the code from running correctly and raises an ImportError.

### Reproduction Steps

1. Import the Message type from message.py in the interactions.py module.
2. Import the MessageInteraction type from interactions.py in the message.py module.
3. Run the code.

### Minimal Reproducible Code

```python
import discord.types.message
```

### Expected Results

The code should run without any `ImportError` related to circular imports.

### Actual Results

ImportError: cannot import name 'Message' from partially initialized module 'discord.types.message' (most likely due to a circular import)

### Intents

n/a

### System Information

- Python v3.10.14-final
- discord.py v2.3.2-final
- aiohttp v3.9.3
- system info: Linux 6.5.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 12 10:22:43 UTC 2

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Slyracoon23** [comment]
### Proposed Solution

To resolve the circular import issue, we can use forward references in one of the modules. Forward references allow referring to a type that hasn't been defined yet. Here's how we can modify the code:

1. In `message.py`, replace the import statement with a forward reference:

```python
if TYPE_CHECKING:
    from .interactions import MessageInteraction
```

2. In `interactions.py`, replace the import statement with a forward reference:

```python
if TYPE_CHECKING:
    from .message import Message
```

3. Make sure to import `TYPE_CHECKING` from the `typing` module at the top of both files:

```python
from typing import TYPE_CHECKING
```

By using forward references with `TYPE_CHECKING`, the actual import is only performed during type checking, avoiding the circular import issue at runtime.

This solution should resolve the circular import issue and allow the code to run without any `ImportError`.

**Comment by Rapptz** [comment]
Please see here: https://github.com/Rapptz/discord.py/issues/9653#issuecomment-1822374218

**Comment by Slyracoon23** [comment]
@Rapptz thanks for promptly responding. Makes sense.
