### ISSUE TITLE
discord.ext.commands.checks predicates acting different if command is in group

### ISSUE THREAD

**Issue by simoovara** [Rapptz/discord.py#9780]
### Summary

title sums it up pretty well

### Reproduction Steps

basically i'm making an usage function (when the user runs a command group without a subcommand, it will run) that returns all the possible functions that the user can run, along with parameters (if needed)

i've implemented this and it works, but it also showed users the commands they can't run because of permissions.
so after digging in the documentation i found `discord.ext.commands.checks`, an attribute that gives the list of predicates for every check in the command.

i made a little test command first (which was NOT in a command group) and my logic worked perfectly, but when i used a command in a command group it threw an error: `TypeError: object bool can't be used in 'await' expression`

(also i'll take suggestments on an easier implementation of this, it just happened to be the first thing i stumbled upon in the docs)
code snippet (yes i know its bad) is obviously not the code i have written, but just an example to reproduce my error

### Minimal Reproducible Code

```python
@bot.group()
async def group(ctx):
    if ctx.invoked_subcommand is None:
        # don't worry about the content of the usage() command, it's not relevant here
        await ctx.send(await usage(ctx))
        return

@group.command()
@commands.has_permissions(manage_messages=True)
async def group_command(ctx):
    pass  # do stuff here


@bot.command()
@commands.has_permissions(manage_messages=True)
async def normal_command(ctx):
    pass  # do stuff here


@bot.command()
async def can_i_run_normal_command(ctx): 
    # returns: True if the user CAN run the command (the check returns True)
    # returns: False if the user CANNOT run the command (the check raises CheckFailure)
    try:
        await ctx.send(await normal_command.checks[0](ctx)) 
    except commands.CheckFailure:
        await ctx.send(False)



@bot.command()
async def can_i_run_group_command(ctx):
    # returns: False if the user CANNOT run the command (the check raises CheckFailure)
    # returns: "TypeError: object bool can't be used in 'await' expression" if the user CAN run the command 
    try:
        await ctx.send(await group_command.checks[0](ctx)) 
    except commands.CheckFailure:
        await ctx.send(False)
```

### Expected Results

I expected `can_i_run_group_command` to have the same results as `can_i_run_normal_command`
note: the error `TypeError: object bool can't be used in 'await' expression` implies that my code is somehow running `await True` or `await False`

### Actual Results

the functions have the same results when the user CANNOT run the command, but raises that weird error in `can_i_run_group_command` when the user CAN run the command

### Intents

discord.Intents.all()

### System Information

python -m discord -v      
- Python v3.11.5-final
- discord.py v2.4.0-alpha
    - discord.py metadata: v2.4.0a4999+g425edd2e
- aiohttp v3.8.5
- system info: Windows 10 10.0.22631

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
You're looking for [`can_run`](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.Command.can_run) not `checks`. The `checks` attribute just gives you the checks attached to the function, it's most likely not what you're looking for.
