### ISSUE TITLE
Bug / Question

### ISSUE THREAD

**Issue by Soulivan71** [Rapptz/discord.py#9784]
### Summary

Bug with edit topic  VOICE channel

### Minimal Reproducible Code

```python
@client.event
async def on_voice_state_update(member, before, after):
	if after.channel and after.channel.id == vc_id:
		channel = member.guild.system_channel

		if channel is not None:
			await channel.edit(name=channel.name, topic="X")
```

### Actual Results
When the user join the specific channel I get this error :
2024-04-12 20:43:41 ERROR    discord.client Ignoring exception in on_voice_state_update
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/autres/NS.py", line 142, in on_voice_state_update
    await channel.edit(name=channel.name, topic="X")
  File "/usr/local/lib/python3.9/dist-packages/discord/channel.py", line 381, in edit
    payload = await self._edit(options, reason=reason)
  File "/usr/local/lib/python3.9/dist-packages/discord/abc.py", line 502, in _edit
    return await self._state.http.edit_channel(self.id, reason=reason, **options)
  File "/usr/local/lib/python3.9/dist-packages/discord/http.py", line 738, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
The bot has permission 'Statu voice set" on his role + on channel so I don't understand why he won't.

### Intents

all

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Hello,
Can someone help me.

**Comment by Soulivan71** [comment]
He has it :x

**Comment by Soulivan71** [comment]
![image](https://github.com/Rapptz/discord.py/assets/36502190/3a149bbf-061c-4310-be70-7009aedf0d76)
And the voice status thing to

**Comment by Soulivan71** [comment]
he only has one role..

**Comment by Soulivan71** [comment]
Yeah same, I got bot role +  the user directly (and @everyone has nothing check/disable)

**Comment by Soulivan71** [comment]
So Im gonna wait if its a knowing issue or not :x

**Comment by Soulivan71** [comment]
@Rapptz sry to ping u but idk if I can get any answer from a contributor, not a ''rdm''

**Comment by SebbyLaw** [comment]
This issue tracker is for issues with the library. You can join [the discord server](https://discord.gg/dpy) for help setting up permissions for your bot.

**Comment by Soulivan71** [comment]
Permission are well done....🙄

**Comment by bijij** [comment]
As said previously, the traceback you've provided indicates discord has rejected your request due to your bot missing required permissions. This isn't an issue with the library itself.

If you need assistance please join the [discord server](https://discord.gg/dpy) and create a thread in the help forum.

**Comment by Soulivan71** [comment]
I can read thx. But even if bot has all permission. "Missing permission" so its a pb from my side ?????
Can't understand that sry.

**Comment by Soulivan71** [comment]
Anyway. Thx for ur help. Im gonna find the solution by myself. Cause even if I put u proof from permissions ur kidding me and  that's not cool.

**Comment by Rapptz** [comment]
The API reports you have no permissions, so it's pretty obvious that's what it is since the server is the source of truth. Check your permissions with overwrites and see for yourself.
