### ISSUE TITLE
webhook ?thread_id= support

### ISSUE THREAD

**Issue by GDjkhp** [Rapptz/discord.py#9791]
### Summary

discord.Webhook.from_url(f'{url}?thread_id={id}', client=bot)

### What is the feature request for?

The core library

### The Problem

https://github.com/Rapptz/discord.py/blob/master/discord/webhook/async_.py#L1279

### The Ideal Solution

https://discord.com/developers/docs/resources/webhook#execute-webhook

**Comment by AbstractUmbra** [comment]
The description could be a little clearer, but from my understand is that you want `from_url` to respect the `thread_id` query parameter?

The current code means that your will receive a full webhook, you merely need to pass `thread=...` to your method calls, like [`.send`](https://discordpy.readthedocs.io/en/stable/api.html?highlight=webhook%20send#discord.Webhook.send). Could you explain why this is unsuitable?

**Comment by Rapptz** [comment]
This already exists as the `threads` parameter in `send` as mentioned above.

**Comment by GDjkhp** [comment]
oh sorry i was including ?thread_id= in the url itself but it gets ignored
