### ISSUE TITLE
Support for Proxies

### ISSUE THREAD

**Issue by Crack498** [Rapptz/discord.py#98]
Hello there!
I was going to execute discord.py in [pythonanywhere](pythonanywhere.com) but it gave me an error.
This error lead to https://help.pythonanywhere.com/pages/403ForbiddenError
It says 

> This error suggests that either the library you're using doesn't support using a proxy, or that it needs to be configured to use a proxy. Have a look at the docs for the library to determine which it is and consider raising an issue with the project about proxy support. 

Any help on this issue? Thanks!

**Comment by Hornwitser** [comment]
Unfortunately this isn't straight forward to do currently.  As far as I can tell you would have to replace all the calls to `aiohttp.get`, `aiohttp.post`, etc in the Discord.py library with calls through a [ProxyConnectior](http://aiohttp.readthedocs.org/en/stable/client_reference.html#proxyconnector) set up for the proxy you want to connect through.
