### ISSUE TITLE
Intents

### ISSUE THREAD

**Issue by Baluuu111** [Rapptz/discord.py#9810]
### Summary

Intents

### Reproduction Steps

Make a discord bot

### Minimal Reproducible Code

```python
import discord
import os
import dotenv

from dotenv import load_dotenv
from discord import Intents

load_dotenv()

DISCORD_TOKEN = os.getenv("DISCORD_TOKEN")

intents = discord.Intents.default()
intents.message_content = True
client = discord.Client(intents=intents)

@client.event
async def on_ready():
    print(f'We have logged in as {client.user}')

@client.event
async def on_message(message):
    if message.author == client.user:
        return

    if message.content.startswith('$hello'):
        await message.channel.send('Hello!')

client.run(DISCORD_TOKEN)
```

### Expected Results

Run the bot

### Actual Results

\main.py", line 17, in <module>
    bot = discord.Client()
          ^^^^^^^^^^^^^^^^
TypeError: Client.__init__() missing 1 required keyword-only argument: 'intents'

### Intents

default

### System Information

- Python v3.12.3-final
- discord.py v2.3.2-final
- aiohttp v3.9.5
- system info: Windows 10 10.0.19045

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by itswilliboy** [comment]
Your error doesn't math the code you provided?
`bot = discord.Client()` contra `client = discord.Client(intents=intents)`

**Comment by Baluuu111** [comment]
> Your error doesn't math the code you provided? `bot = discord.Client()` contra `client = discord.Client(intents=intents)`

It still displays that error, I understand where you coming from but I am getting the error for the given code? So what could be the problem here ?

**Comment by itswilliboy** [comment]
Yeah, probably. There are no errors in the code you provided.

**Comment by Baluuu111** [comment]
Thanks for the help, I was so stupid. I removed a space from the folders name and haven't reopened the folder in vsc :// sorry to waste your time....
