### ISSUE TITLE
support for 3.12 type aliases

### ISSUE THREAD

**Issue by HEROgold** [Rapptz/discord.py#9813]
### Summary

Discord 2.3.2 doesn't support python 3.12 type alises

### What is the feature request for?

discord.ext.commands

### The Problem

When creating aliases like this
`MemberOrRole = Role | Member`
The transformer has no issues

When creating aliases with the type statement, the transformer raises the error `unsupported type annotation`.
`type MemberOrRole = Role | Member`

The only difference in this example is the statement.

### The Ideal Solution

Being able to just use  `type MemberOrRole = Role | Member`
or more complex situations like `type NumberOrStringSequence [T: (int, float, str)] = Sequence[T]`

### Additional Context

The type statement for type aliases allows for generic type annotation, without the need for the typing module, and this greatly improves the coding experience for those that use 3.12. Just like mentioned on the [PEP-695](https://docs.python.org/3/whatsnew/3.12.html#whatsnew312-pep695:~:text=the%20new%20syntax%20allows%20declaring%20typevartuple%20and%20paramspec%20parameters%2C%20as%20well%20as%20typevar%20parameters%20with%20bounds%20or%20constraints%3A) it allows for declaring types, with constraints. That leads to a more controlled and readable environment.

**Comment by No767** [comment]
I really doubt that this is needed. I'll let the rest decide on this

**Comment by Rapptz** [comment]
Should be doable. It's a [`typing.TypeAliasType`](https://docs.python.org/3/library/typing.html#typing.TypeAliasType) so not too bad to add to support to it.
