### ISSUE TITLE
`discord.ui.Modal` `on_error` missing `items` parameter from parent class implementation

### ISSUE THREAD

**Issue by Nadock** [Rapptz/discord.py#9816]
### Summary

The `discord.ui.Modal` class's `on_error` function does not have an `items` parameter but the same method on it's parent type `discord.ui.View` does.

### Reproduction Steps

N/A — view the code for the two methods.

- `discord.ui.Modal.on_error`: https://github.com/Rapptz/discord.py/blob/71358b8dcea1923558fb0e51f641d5881e825bf4/discord/ui/modal.py#L152
- `discord.ui.View.on_error`: https://github.com/Rapptz/discord.py/blob/71358b8dcea1923558fb0e51f641d5881e825bf4/discord/ui/view.py#L400

### Expected Results

The subclass `Modal` method should have the `items` parameter.

### Actual Results

The method does not have the parameter.

### Intents

N/A

### System Information

- Python v3.11.8-final
- discord.py v2.3.2-final
- aiohttp v3.9.3
- system info: Darwin 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

The inconsistency means you can't override the `on_error` method in a `discord.ui.Modal` subclass without a `mypy` warning or accepting an `*args` parameter.

`mypy` either reports the following error without an `item` parameter in the overiden method:
```console
error: Signature of "on_error" incompatible with supertype "View"
[override]
            async def on_error(
            ^
note:      Superclass:
note:          def on_error(self, Interaction[Client], Exception, Item[Any], /) -> Coroutine[Any, Any, None]
note:      Subclass:
note:          def on_error(self, interaction: Interaction[Client], error: Exception) -> Coroutine[Any, Any, None]
```

or `mypy` reports this error if the overidden method includes the `item` parameter:
```console
error: Signature of "on_error" incompatible with supertype "Modal"
[override]
            async def on_error(
            ^
note:      Superclass:
note:          def [ClientT <: Client] on_error(self, Interaction[ClientT], Exception, /) -> Coroutine[Any, Any, None]
note:      Subclass:
note:          def on_error(self, interaction: Interaction[Client], error: Exception, item: Item[Any]) -> Coroutine[Any, Any, None]
```

**Comment by Rapptz** [comment]
This is by design. The modal `on_error` callback can't take an `item` parameter because the dispatch mechanism doesn't know it at that point. The mypy warning is unfortunately not possible to fix without ignoring it.

**Comment by Nadock** [comment]
Thanks for the quick reply @Rapptz and the explanation as to why this is the way it is. 

I think there are still a couple of options to "fix" this, off the top of my head either;
- the `Modal` class could stop inheriting from `View` and have it's own `on_error` signature
- the `item` parameter could be updated to accept `None` and the `Modal.on_error` could be passed `None` for the `item` parameter

**Comment by Rapptz** [comment]
Both of these are breaking changes, nor are they ideal.
