### ISSUE TITLE
discord.channel.members returns empty list

### ISSUE THREAD

**Issue by Stimunix** [Rapptz/discord.py#9835]
### Summary

Unimplemented property in code.

### Reproduction Steps

arbitrary_channel.members returns [].

### Minimal Reproducible Code

```python
@bot.event
on_voice_state_update(member, before, after):
   print("User connected to ", member.channel)
   #active members in channel
   members = after.channel.members
   for member in members:
      print(member)
```

### Expected Results

A list of members in a channel.

### Actual Results

[]

### Intents

Private

### System Information

- Python v3.11.7-final
- discord.py v2.3.2-final
- aiohttp v3.9.5
- system info: Windows 10 10.0.22631

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I traced back through the channel.py file, and found that it looked to me as though the code was not implementing the property _members.  It was not allocated in the slots, if that does anything at all for it.

**Comment by AbstractUmbra** [comment]
> # Intents
> private

This right here is entirely unhelpful. Can you confirm your intents please? This is not identifiable information and is 99.9999% likely the reason you're having this issue, as I can attest that VoiceChannel.members is correctly populated with the `members` intents, and receives updates using the `voice_states` intents.

**Comment by Stimunix** [comment]
Ok, listen here, buster.  Some of us are new & are asking because we don't know.  Regardless of how unhelpful it is, try explaining why, or how to do something rather than just acting like some 1800s poppycock academic from X scientific institution with a pompador wig.  If the API were clearly explained better on your website, I wouldn't have asked in the first place.  Try not being a jackass to someone on the internet.  I did my best, how about you try to do yours.
