### ISSUE TITLE
Failed to upload commands to Discord (HTTP status 400, error code 50035)

### ISSUE THREAD

**Issue by ThomazBrasil** [Rapptz/discord.py#9838]
### Summary

I am trying to put a slash command in a bot, but it's not working and it's showing a sync error.

### Reproduction Steps

I tried adding another command and this error started happening

### Minimal Reproducible Code

```python
@bot.event
async def on_ready():
    print(f"Bot iniciou como {bot.user} ")
    await bot.tree.sync()

@bot.tree.command(name= "command", description="desc")
async def yeah(interaction : discord.Interaction, message : str):
    channel = interaction.channel
    await channel.send(message)

@bot.tree.command(name= "command2", description="desc 2")
async def detect(interaction : discord.Interaction, member : discord.Member, thing : str):
    print(f"Member is {thing}")

bot.run("token")
```

### Expected Results

i expected the command to show up in discord

### Actual Results

The command didn't work and didn't go to Discord.

discord.app_commands.errors.CommandSyncFailure: Failed to upload commands to Discord (HTTP status 400, error code 50035)
In command 'command2' defined in function 'detect'
  In parameter 'thing'
    name: Command name is invalid

### Intents

all

### System Information

- Python v3.11.9-final
- discord.py v2.3.2-final
- aiohttp v3.8.6
- system info: Windows 10 10.0.22631

i mean im not in windows 10 (im in windows 11) but cmd printed that so

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
This exception is an error that comes from Discord. I don't think there's enough information here for why the name is invalid, and part of me feels like you edited the command name. Discord is saying the name is invalid and cannot be used, that's all this means.

**Comment by ThomazBrasil** [comment]
Hey man! I already fixed it

**Comment by crazyorange49** [comment]
> Hey man! I already fixed it

How did you fix it, I'm having the same issue
