### ISSUE TITLE
Discord.py, after about 20~30 minutes have passed since sending a message, I'm unable to edit it

### ISSUE THREAD

**Issue by kwoneogus** [Rapptz/discord.py#9856]
### Summary

Message not edit after a certain period of time

### Reproduction Steps

After sending a message using interaction in discord.py, I'm attempting to use buttons to edit it. Editing is possible roughly up to 30 minutes after sending the message, but after that, I encounter the error 'discord.errors.HTTPException: 401 Unauthorized (error code: 50027): Invalid Webhook Token' and cannot edit the message. 

### Minimal Reproducible Code

```python
async def editmsg(msg,con):
    await msg.edit(content=con)

@app_commands.command(name='sendmsg', description='sendmsg')
async def sendmsg(self, interaction: Interaction):
    await interaction.response.send_message(content='message')
    msg = await interaction.original_response()

    # The following code assumes that it is executed when a button is clicked.
    await editmsg(msg,'editmessage')
```

### Expected Results

Message editing

### Actual Results

discord.errors.HTTPException: 401 Unauthorized (error code: 50027): Invalid Webhook Token

### Intents

Intents.all()

### System Information

- Python v3.10.9-final
- discord.py v2.3.2-final
- aiohttp v3.9.3
- system info: Windows 10 10.0.19045

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by AbstractUmbra** [comment]
This isn't really an issue, but if it were it'd be a discord issue.

Interaction tokens (and therefor interactions) expire after 3 seconds (or a further 15 minutes if deferred) after their creation.

Trying to use the interaction response after this period will result in the error you're seeing.

**Comment by Rapptz** [comment]
Interaction tokens only last 15 minutes, you can't do anything more with them after that.
