### ISSUE TITLE
Release 2.4.0 undocumented breaking change to meesage.interaction

### ISSUE THREAD

**Issue by doluk** [Rapptz/discord.py#9868]
### Summary

The code changes related to depreciation of message.interaction causing a missing setter for message.interaction

### Reproduction Steps

Various tools like https://pypi.org/project/enhanced-chat-exporter/ relying on discord.py under the hood and are now broken because of the missing setter. this was caused by the change of message.interaction from a normal attribute to a function with property decorator [ref](https://github.com/Rapptz/discord.py/blob/master/discord%2Fmessage.py#L2240)

### Minimal Reproducible Code

```python
message2.interaction = message1.interaction
```

### Expected Results

Correctly set message attribute

### Actual Results

Exception 

### Intents

NA

### System Information

Doesn't matter as long as discord.py >=2.4.0

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

The fix is pretty straight forward as visible in the py-cord repo https://github.com/Pycord-Development/pycord/blob/bf4011653f75869a090c1bf88809568423c7c12e/discord/message.py#L1071

**Comment by Rapptz** [comment]
Message attributes have never been documented to be read-write so this seems like a problem of mismatched expectations.
