### ISSUE TITLE
Help command checks not working as expected.

### ISSUE THREAD

**Issue by Wiper-R** [Rapptz/discord.py#9876]
### Summary

HelpCommand.add_check doesn't work as intended.

### Reproduction Steps

Calling add_check in `HelpCommand.__init__` does add/append check to `HelpCommand._command_impl.checks` but it get's overwritten by new command instance that is being created in `HelpCommand._add_to_bot`

```py
# Current Workaround I am using

class HelpCommand(commands.HelpCommand):
    def __init__(self) -> None:
        super().__init__()
        self.add_check(
            commands.bot_has_permissions(
                read_message_history=True, embed_links=True
            ).predicate
        )


class Bot(commands.Bot):
    def __init__(self):
        super().__init__(
            help_command=None,
            ...
        )
        help_command = HelpCommand()
        self.add_command(help_command._command_impl)

```

### Expected Results

The checks to stay even if we need to create a new instance in `_add_to_bot`. But according to my guess that's redundant.

### Actual Results

The checks are overwritten by empty list, because of  `command_attrs`  passed to `HelpCommand._command_impl`

### Intents

-

### System Information

-

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by LeoCx1000** [comment]
This is fixed in v2.4, please update discord.py. (#9843)
