### ISSUE TITLE
Commands not syncing / updating names

### ISSUE THREAD

**Issue by Foo54** [Rapptz/discord.py#9883]
### Summary

I've been working on a bot for about a month now, and recently decided to rename a couple commands. Upon doing so, the bot suddenly refused to sync my commands, whether new, renamed, or old.

### Reproduction Steps

changed the names of a few commands

### Minimal Reproducible Code

```python
@force_update_group.command(name="freeze-force", description="Freeze or unfreeze a force")

# changed into

@force_update_group.command(name="freeze", description="Freeze or unfreeze a force")
```

### Expected Results

The command name to update

### Actual Results

Command name did not update, and changing command parameters or making commands would not do anything

### Intents

discord.Intents.all()

### System Information

```
cd GMRP-Bot
python3 -m venv bot-env
source bot-env/bin/activate
pip install -U discord.py
pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
python -m pip install requests
clear
python3 main.py
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I've waited 3 days and still nothing has updated.
I sync commands in setup_hook and whenever I ping my bot

**Comment by No767** [comment]
@Foo54 discord.py does not automatically sync application commands. You will need to sync them manually if you modify your application commands.

**Comment by Foo54** [comment]
![image](https://github.com/Rapptz/discord.py/assets/157067370/a23b10e5-ba26-4b95-a98b-3453624bb3ed)
here's how I sync the commands, and I've been stopping my bot an re-running it each time.

**Comment by No767** [comment]
@Foo54 Have you ensured that you restarted your discord client?

**Comment by Foo54** [comment]
@No767 
I've waited for the bot to go offline before running the code again, also this

![image](https://github.com/Rapptz/discord.py/assets/157067370/9a9014da-c4c8-4cbd-a0c0-705d45173eac)

this is in the on message command
![image](https://github.com/Rapptz/discord.py/assets/157067370/27170311-3b21-439b-8025-5694cc79559b)

**Comment by AbstractUmbra** [comment]
Having a slash command to control syncing is unwise (how do you sync your sync command?).

The issue I expect you're having above is that you have a globally synced command. You're clearing ones for that specific guild alone which will not remove the global.

Please also note this issue tracker is meant for bugs in the library, not *using* the library. Please convert to a discussion or join the [discord server](https://discord.gg/r3sSKJJ) for assistance in using the library.

**Comment by Foo54** [comment]
@AbstractUmbra

did some testing based off that and found out that my guild commands just aren't syncing in the first place. Thanks for the info and helping me clear this up.

As for the use of the issue tracker,
