### ISSUE TITLE
aiohttp.get and friends are deprecated

### ISSUE THREAD

**Issue by Hornwitser** [Rapptz/discord.py#99]
Since version 0.21 of the aiohttp library (not yet released on pip) the bare `get()`, `post()`, etc functions of the `aiohttp` module have been deprecated (see 0.21 change log and https://github.com/KeepSafe/aiohttp/issues/729).  Fixing this necessitates creating a `ClientSession` and keeping it around, but once done #98 should be straight forward to implement, and performance will be slightly better when doing many requests (which is totally useless with all the rate limiting going on, but oh well).

**Comment by Rapptz** [comment]
Implemented in ff14fa0fe8c93ca921a4bdc04f8ba108b5147f19.
