### ISSUE TITLE
Add support of weekdays to the task extension

### ISSUE THREAD

**Issue by Tianmaru** [Rapptz/discord.py#9902]
### Summary

Add the support of weekdays

### What is the feature request for?

discord.ext.tasks

### The Problem

Sometimes, you have a task that should be run at a certain time, but only on certain weekdays.

### The Ideal Solution

Support CRON-like time specifications, or allow timedelta objects as arguments (that way, you can at least run jobs once per week).

### The Current Solution

Don't use task extension?

**Comment by Snaptraks** [comment]
I feel like having a statement at the top of your task such as

```py
if datetime.now().weekday() > 4:
    return
```

would solve your issue. See the documentation for more info
https://docs.python.org/3/library/datetime.html#datetime.datetime.weekday

**Comment by Rapptz** [comment]
The task extension supports *time* not *datetime*. I have no plans on supporting datetimes. If you want this you're better off doing it in the body as mentioned above.

**Comment by Tianmaru** [comment]
> I feel like having a statement at the top of your task such as
> 
> ```python
> if datetime.now().weekday() > 4:
>     return
> ```
> 
> would solve your issue. See the documentation for more info https://docs.python.org/3/library/datetime.html#datetime.datetime.weekday

Yeah, I came to the same conclusion today. Sorry, it was quite late yesterday :sweat_smile:
