### ISSUE TITLE
my bot is not receiving/importing context

### ISSUE THREAD

**Issue by EthanCampana** [Rapptz/discord.py#991]
Im importing the following:

import discord
import asyncio
import random
from discord.ext import commands

and this is my test code 

**@bot.command()
async def test(ctx, arg):
    await ctx.send(arg)**

when i try to run this command like so: !test hi
i get this error: arg is a required argument that is missing.

**Comment by MysterialPy** [comment]
You need to provided context to the command.
```
@bot.command(pass_context=True)
async def test(ctx, arg):
    await ctx.send(arg)```

**Comment by MysterialPy** [comment]
Actually that makes no sense, since `ctx.send` is `1.0.0.a`...

What version of Discord.py do you have?

**Comment by Vexs** [comment]
Use `pip show discord.py` or do `print(discord.__version__)` in a py shell to find that- betting you're running code for the rewrite version of the lib on the older (async branch) version of the lib.

**Comment by EthanCampana** [comment]
yeah it looks like it  i have version 0.16.12

**Comment by Vexs** [comment]
You installed using the install instructions on the rewrite docs yeah? Those are out-of-date-in-the-future because they're written with the idea that the rewrite branch is the currently released branch. Do `python3 -m pip install -U git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]` to install the rewrite branch instead.

**Comment by MysterialPy** [comment]
In which case ctx.send() is not valid and you would need to pass_context to your command.

Otherwise you can install the rewrite version.

**Comment by EthanCampana** [comment]
Do i have to uninstall the previous version of the discord.py? or will it just overwrite

**Comment by MysterialPy** [comment]
`-U` will uninstall the previous version for you automatically

**Comment by EthanCampana** [comment]
I am getting the same error when i try to run the bot and do the command

**Comment by EthanCampana** [comment]
I Tried changing my version of Python still no luck
