### ISSUE TITLE
discord.Client() doesn't return

### ISSUE THREAD

**Issue by pavlukivan** [Rapptz/discord.py#993]
The title is self-explanatory. I can't even run examples, everything stucks on `client = discord.Client()`.

**Comment by Vexs** [comment]
Can we get an error? Have you installed the lib?

**Comment by pavlukivan** [comment]
Of course, it just doesn't return. No error messages

**Comment by pavlukivan** [comment]
It ran fine before yesterday, but suddenly stopped working

**Comment by Rapptz** [comment]
This requires way more information to be actionable.

**Comment by pavlukivan** [comment]
I agree, I just want to find a way to collect the "information"

**Comment by AileenLumina** [comment]
Come on the discord.py Discord server so we can solve your issue there, as this issue is not an issue of discord.py.

**Comment by pavlukivan** [comment]
ok, apparently it was related to broken routing table, reboot fixed the issue
