### ISSUE TITLE
Ui Button does not show any Color other than Gray when URL is given

### ISSUE THREAD

**Issue by Muhammad-awaisMurtaza** [Rapptz/discord.py#9931]
### Summary

I want a UI Button with primary color having URL but code always return Gray button. I think this is due to the code we have Downloads/discord.py-master/discord/ui/button.py line 125

### Reproduction Steps

All you need to do is use the code i mentioned and run it.
I think its because we are hardcodedly changing the style when URL is given at **discord/ui/button.py** Line 124

We should allow user to choose a color with url.

  ```
      if url is not None:
            style = ButtonStyle.link
```

### Minimal Reproducible Code

```python
button = discord.ui.Button(
 label="Polymarket",
 url=f"{base_link}{graph_data[5]}",
 style = discord.ButtonStyle.primary)

view = discord.ui.View()
view.add_item(button)

await message.channel.send(view=view)
```

### Expected Results

Button should be of color blue.

### Actual Results

Button is of color Gray.

### Intents

default()

### System Information

- Python v3.12.4-final
- discord.py v2.4.0-final
- aiohttp v3.10.5
- system info: Darwin 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Soheab** [comment]
This is a discord limitation, [link is a style on its own](https://discord.com/developers/docs/interactions/message-components#button-object-button-styles>).
