### ISSUE TITLE
jail command & find a channel

### ISSUE THREAD

**Issue by rektile** [Rapptz/discord.py#994]
so i made a command that jails people for a 1 minute.
to unjail someone i delete the channel.
i want to write some code that checks if the jail channels still exists but it gives me errors
```python
@bot.command(pass_context=True)
@commands.has_role(name="God's")
async def jail(ctx): 
    victim = ctx.message.mentions[0]
    timeout = time.time() + 60 ############1 min##################### 
    jail_channel = await bot.create_channel(ctx.message.server, "jail", type=discord.ChannelType.voice)
    await bot.move_member(victim, jail_channel)
    print(ctx.message.author, "jailed", victim, "for 60 seconden") 
    while time.time() < timeout: 
        print(victim, "is still jailed for ", timeout - time.time(), "seconds")
        ''' some code placed here thats checks if the channel still exists if it exists continue else break the loop '''
        await bot.move_member(victim, jail_channel) 
        await asyncio.sleep(1)
    try: 
        await bot.delete_channel(jail_channel)
        print("channel is deleted") 
     except: 
        print("channel is already deleted")
```
if you could help me it would be nice :D
btw i know the code isnt clean , im still learning :p

**Comment by jwshields** [comment]
This doesn't seem to be a library issue, try asking in the discord.py chat https://discord.gg/r3sSKJJ

**Comment by rektile** [comment]
the code works but i didnt make something that unbans someone so i want o make something that checks if the jail channel stik excists

**Comment by rektile** [comment]
do you know a way how i let the bot loop trough all the channels in my server and look if jail channel still exist ?

**Comment by Altarrel** [comment]
Use utils.get http://discordpy.readthedocs.io/en/async/api.html#discord.utils.get.

Also if you need more help join the server jwshields linked you to.

**Comment by Rapptz** [comment]
These issues are not meant for questions regarding how to implement bot features.

**Comment by rektile** [comment]
Altarrel ty man :D
