### ISSUE TITLE
Reflect API for Entitlements

### ISSUE THREAD

**Issue by Snawe** [Rapptz/discord.py#9940]
### Summary

`Entitlements` are missing some fields

### What is the feature request for?

The core library

### The Problem

In https://github.com/Rapptz/discord.py/blob/master/discord/sku.py#L104 the Entitlement is missing the fields:
* promotion_id
* gitft_code_flags
* subscription_id

that are present in the entitlements doc: https://discord.com/developers/docs/resources/entitlement#entitlements

### The Ideal Solution

Support those fields

**Comment by Puncher1** [comment]
They're undocumented on Discord's side. This is done by purpose as you can see in this pull request: https://github.com/discord/discord-api-docs/pull/6477

> `subscription_id`, `promotion_id` and `gift_code_flags` to remain undocumented at this time

**Comment by Snawe** [comment]
ok, so to get the `subscription_id` I would need to manually query the list endpoint? I am asking because of the new breaking changes to entitlements where they no longer provide `ends_at` if the subscription isn't cancelled.

**Comment by Puncher1** [comment]
At the moment yes, I don't know what the current status on Discord's side is, but at the moment they're not documented on Discord's side, so it probably won't be implemented in the library any soon. Maybe it's worth to ask discord directly about your problem on the original PR discord/discord-api-docs#6477

**Comment by Snawe** [comment]
Ok, thanks for the answer! But now that I slept over it, I think I don't actually need the `subscription_id` anyway. entitlement id should be enough. So I will close this since it's not documented anyway.
