### ISSUE TITLE
Why can't you subclass discord.ext.commands.Bot instead of discord.Client?

### ISSUE THREAD

**Issue by Vlek** [Rapptz/discord.py#9956]
### Summary

In order to have a Discord bot that is able to have event handlers and commands, in a class-based way, would make sense to subclass the Bot class.

### Reproduction Steps

Run the below code.

### Minimal Reproducible Code

```python
from discord import Intents, Message
from discord.ext.commands import Bot
from typing import Callable
import logging

class DiscordBot(Bot):
    def __init__(self, intents=None, command_prefix="$") -> None:
        self.messageHandlers: list[Callable] = []

        if not intents:
            intents = Intents.default()
            intents.message_content = True

        super().__init__(command_prefix=command_prefix, intents=intents)

    def addMessageHandler(self, handler: Callable) -> bool:
        """Adds given message handler to handlers."""
        added: bool = False

        if handler not in self.messageHandlers:
            self.messageHandlers.append(handler)
            added = True

        return added

    def removeMessageHandler(self, handler: Callable) -> bool:
        """Attempts to remove given handler from handlers."""
        removed: bool = False

        if handler in self.messageHandlers:
            self.messageHandlers.remove(handler)
            removed = True

        return removed

    async def on_message(self, message):
        """Handler broker for messages."""

        # Ignore messages coming from the bot itself
        if message.author == self.user:
            return

        for handler in self.messageHandlers:
            # We cannot be sure that the user's code will not have exceptions.
            # Need to log this information well so that it is easier to research
            # while also trying to make sure the Discord bot does not go down.
            try:
                await handler(message)
            except Exception:
                # This _should_ take care of logging the traceback correctly.
                logging.exception("")

if __name__ == "__main__":
    bot = DiscordBot()
    logger = logging.getLogger("discord")

    @bot.command()
    async def ping(ctx):
        await ctx.send("pong")

    async def logAllMessages(message: Message):
        logger.info(f"{message.author.display_name}: {message.content}")
        await message.reply(message.content)

    bot.addMessageHandler(logAllMessages)

    bot.run(TOKEN)
```

### Expected Results

When trying to use the DiscordBot class in order to register commands and handlers, both the handlers and commands should work.

Sending '$ping' in this case should:
- log an info level message with the string
- send pong back as the response

### Actual Results

It is only logging an info level message with the given string.

### Intents

default

### System Information

- Python v3.10.12-final
- discord.py v2.4.0-final
- aiohttp v3.10.8
- system info: Linux 6.9.3-76060903-generic #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by IAmTomahawkx** [comment]
This is not an issue with the library, you simply have a bug in your code. See https://discordpy.readthedocs.io/en/stable/faq.html#why-does-on-message-make-my-commands-stop-working

**Comment by EvieePy** [comment]
This is not an issue with subclassing, this is because you override `on_message`.

Some events have default implementations that you need to consider; in this case you can read what @IAmTomahawkx has just linked, if you don't need to change the behaviour the default events or to avoid accidentally doing so in the future you can consider the use of event listeners: https://discordpy.readthedocs.io/en/stable/ext/commands/api.html?highlight=listen#discord.ext.commands.Bot.listen

**Comment by Vlek** [comment]
That did it! Thank you both for your quick replies. I greatly appreciate the help. I will close the ticket.
