### ISSUE TITLE
Help with FFmpeg and YTDL player!

### ISSUE THREAD

**Issue by viral32111** [Rapptz/discord.py#997]
I need some help here. Whenever i run the code to play a youtube video on my music bot everything works fine but i get the ffmpeg window open. I wish to make it run in the background or just "hide" its self. I've seen #745 and I entered the commands on [this](https://superuser.com/questions/555289/is-there-a-way-to-disable-or-hide-output-thrown-by-ffmpeg) into CMD (Not sure if thats how i was supposed to do it) but i had no luck. So i tried playing around with the arguments for `create_ytdl_player `but i don't quite understand how and where to put them. My code attempts are below, I don't know if i have been getting the argument names wrong or the parameter name to pass to ffmpeg wrong (btw `link` is a string variable to the url)

`player = await voiceClient.create_ytdl_player( link, before_options="loglevel quiet" )`
`player = await voiceClient.create_ytdl_player( link, options="loglevel quiet" )`
`player = await voiceClient.create_ytdl_player( link, before_options="-loglevel quiet" )`
`player = await voiceClient.create_ytdl_player( link, options="-loglevel quiet" )`
All of these failed to hide the window but they still played the video, although when i tried these ones below the ffmpeg window opened then closed (I'm going to assume it crashed but it reported no errors into the shell)
`player = await voiceClient.create_ytdl_player( link, options="-loglevel quiet", before_options="-loglevel quiet" )`
`player = await voiceClient.create_ytdl_player( link, options="loglevel quiet", before_options="loglevel quiet" )`

Please help :/

**Comment by SpEaGs** [comment]
From what I can tell, you simply have the syntax for the option wrong. Try this:
`create_ytdl_player( link, options="-loglevel 'quiet, -8'")`
ffmpeg's docs show that the command flags needed for lowering the log level to quiet look like this:
`-loglevel 'quiet, -8'`
Here's a link to the ffmpeg docs to see for yourself:
https://ffmpeg.org/ffmpeg.html#Generic-options

That said, I have a strong feeling that what's causing the window to open in the first place is that you may have installed the wrong ffmpeg package. You'll want the static version for whatever bit count your rig runs on.
Here's a link to ffmpeg's downloads if u decide to try this:
Windows & Mac: https://ffmpeg.zeranoe.com/builds/
Linux: https://www.ffmpeg.org/download.html#build-linux

**Comment by viral32111** [comment]
Thanks! I'll check if it works in a bit.

**Comment by viral32111** [comment]
I've been testing it for a bit now and it seems to be doing what it was doing before, I tried deleting my previous version of FFmpeg then downloading it again (from your link), I then updated the Environment Variables so it could be used and it just opens then closes and nothing is played, Although whenever I remove the options argument and just have the URL it plays normally. I also had a look at the documentation on the loglevel parameter and I didn't see anything wrong with what I had done.

**Comment by MarkKoz** [comment]
Try the ffmpeg options `-nostats` and/or `-nostdin`. I don't think they're position-sensitive.
