### ISSUE TITLE
return in finally can swallow exceptions

### ISSUE THREAD

**Issue by iritkatriel** [Rapptz/discord.py#9981]
### Summary

return in finally can swallow exceptions

### Reproduction Steps

In a couple of places in your code, there is a `return` statement in a `finally` block, which would swallow any in-flight exception.

https://github.com/Rapptz/discord.py/blob/c8ecbd8d100b0e285987e33ef27209fce8bc71d1/discord/player.py#L606
https://github.com/Rapptz/discord.py/blob/c8ecbd8d100b0e285987e33ef27209fce8bc71d1/discord/gateway.py#L165

This means that if a `BaseException` (such as `KeyboardInterrupt`) is raised from the `try` body, or any exception is raised from an `except`: clause, it will not propagate on as expected.

See also https://docs.python.org/3/tutorial/errors.html#defining-clean-up-actions.

### Expected Results

Avoid return in finally.

### Actual Results

NA

### Intents

NA

### System Information

NA

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by mikeshardmind** [comment]
KeyboardInterrupt won't be received in a thread, and this is during the closing of the gateway, so any other base exception here being suppressed is fine, including several internal asyncio and concurrent futures exceptions that are considered base exceptions should be swallowed. (ie. TimeoutError, CancelledError) as well as system exit, if someone found a way to throw that into the thread (I don't think SystemExit should be possible here under normal operation)

The codec one has a similar issue, where KeyboardInterrupt (Possibly SystemExit if a codec probe here specifically calls sys.exit or raises it) is the only base exception that could occur here which we would want to avoid catching. 

The python standard library using BaseException for exceptions that involve recoverable and/or situationally ignorable concurrency state errors makes this more awkward than it should be here.
