### ISSUE TITLE
Addition of Ubuntu 24.04 install instructions to README.md

### ISSUE THREAD

**Issue by VoxelTek** [Rapptz/discord.py#9982]
### Summary

Ubuntu 24.04 changes how Python packages are installed. Instructions for this should be added.

### What is the feature request for?

The documentation

### The Problem

Hi there,

Ubuntu 24.04 doesn't support using `pip` to install Python packages. If you try and do so, it complains:
```
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```
Because of this, the install command `python3 -m pip install -U discord.py` does not work. While it can be forced, it is not recommended, per the error message above.

### The Ideal Solution

This Python package, however, does appear to exist within the `apt` repository, as `python3-discord`. As such, it can be installed with `sudo apt install python3-discord`. 

I believe this should be added to the install instructions, as this not only applies to Ubuntu 24.04, but also derivatives such as Kubuntu, meaning many Linux distros experience this same issue.

**Comment by Rapptz** [comment]
You should probably install the package using a virtual environment. I don't maintain the `python3-discord` package nor know who does so recommending its installation as an official alternative to this project would be kind of unwise. You're free to use it if you must but the venv approach is better.
