### ISSUE TITLE
A tuple for all valid discord.Colour preset colors

### ISSUE THREAD

**Issue by cleabent** [Rapptz/discord.py#9989]
### Summary

Needs a tuple for all valid colors

### What is the feature request for?

The core library

### The Problem

I'm adding a feature to a command that just outputs RGB values of a role's color, where it will check if the color of the role is equal to any of discord's preset colors.
I feel like it will benefit in these situations if there's a tuple with all default colors (as instance of `discord.Colour`).
I can then do a simple for loop to match them, and code does not need to be changed when preset color changes or new color is added.

### The Ideal Solution

A factory classmethod to make a tuple composed of all valid discord preset colors as a `discord.Colour` instance.

### The Current Solution

Boilerplate function to output tuple containing all of the preset colors, or a constant containing all of the preset colors.

### Additional Context

discord.py version : 2.4.0 using `pip install -U discord.py`
this is my first time writing an issue, hopefully this helps.

**Comment by Rapptz** [comment]
I think this is niche and uncommon enough that it's easier and better for you to do yourself.
