### ISSUE TITLE
Access other parameters in autocomplete response

### ISSUE THREAD

**Issue by PythonCoderAS** [Rapptz/discord.py#9997]
### Summary

An autocomplete function should be able to read the values for other arguments

### What is the feature request for?

The core library

### The Problem

I am trying to make a function that provides autocomplete for a parameter based on the values of other parameters (ie a user parameter). As of right now, there is no direct way to receive the value of the `user` argument if my autocomplete is for a different argument (such as `email`).

### The Ideal Solution

Ideally, I'd be able to either define a `**kwargs` attribute, or directly name the parameters I am looking for (so my function would be `async def autocomplete_func(interaction, current, user: discord.Member | None): ...`).

### The Current Solution

I can manually parse `interaction.data` but this feels very low-level and inelegant, also requiring having to change the parsing depending on the level of the command (top level command vs subcommand vs sub-subcommand).

**Comment by Rapptz** [comment]
[`Interaction.namespace`](https://discordpy.readthedocs.io/en/stable/interactions/api.html#discord.Interaction.namespace)

**Comment by PythonCoderAS** [comment]
Thank you! I will say though that the description of the namespace attribute does not make it clear that it contains the resolved arguments, maybe that can be improved (such as copying part of the Namespace class description to the `interaction.namespace` attribute description).
