### ISSUE TITLE
Add position arg to guild.create_role

### ISSUE THREAD

**Issue by RazzerDE** [Rapptz/discord.py#9998]
### Summary

Adding the "position" arg of a role to the function "await guild.create_role"

### What is the feature request for?

The core library

### The Problem

I'm trying to create a backup system to my own discord server and that's how I found that you need to make multiple API requests to make that possible.

### The Ideal Solution

The ideal solution would be to just use `await guild.create_role(position=int)`

### The Current Solution

Currently, if you want to create a new role with a specific position, you need to make 2 API requests: firstly `await guild.create_role()` and after that `await role.edit(position=int)`.

**Comment by LeoCx1000** [comment]
The [Create Guild Role](https://discord.com/developers/docs/resources/guild#create-guild-role) endpoint does not take a position parameter. The only way to do this is using the [Modify Guild Role Positions](https://discord.com/developers/docs/resources/guild#modify-guild-role-positions) endpoint after it has been created. Even if this was added, it would still make two requests.
